### ISSUE TITLE
Relative path based shader file imports stopped working

### ISSUE THREAD

**Issue by superdump** [bevyengine/bevy#10004]
## Bevy version

`main` at `4eb9b9f`

## What you did

`#import "something.wgsl" as something`

## What went wrong

It doesn't give any errors. If an incorrect path is provided, then `ERROR bevy_asset::server: path not found` is logged, but with the correct path there's no error, the shader just doesn't run.

## Additional information

From what @DGriffin91 can tell it's Bevy Asset V2 #8624, works just before, doesn't work after, doesn't work on current main.

**Comment by JMS55** [comment]
Fixed by https://github.com/bevyengine/bevy/pull/10030?
