### ISSUE TITLE
DDS loading does not recognize cubemap imports

### ISSUE THREAD

**Issue by LaserWitch** [bevyengine/bevy#10049]
##  Bevy and version information:
Tested on both recent bevy master and on 0.11.3

`AdapterInfo { name: "NVIDIA GeForce RTX 4080", vendor: 4318, device: 9988, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "537.13", backend: Vulkan }`

## What you did

I tried to use DDS cubemap textures for skyboxes and envmap textures.

## What went wrong
```
2023-10-08T18:55:09.680963Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (7)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `skybox_bind_group`
    Texture binding 0 expects dimension = Cube, but given a view with dimension = D2

', ...\wgpu-0.16.3\src\backend\direct.rs:3019:5
```
## Additional information
I have observed this issue with files output by <https://github.com/dariomanesku/cmftStudio> and ones output by <https://developer.nvidia.com/nvidia-texture-tools-exporter>. Using the Nvidia tool I've resaved my DDS file from cmft as a KTX2, and bevy loads that without issue. I then resaved it as .dds using the Nvidia tool, with otherwise the same settings, including set to export as cubemap. The resulting DDS file still has the error.

I'm attaching a zip that includes that working KTX2 skybox and the Nvidia-produced DDS saved from it.

[skyboxes.zip](https://github.com/bevyengine/bevy/files/12841506/skyboxes.zip)

**Comment by Kanabenki** [comment]
It seems the dds texture loading code does not check if the file is a cubemap as the ktx2 one does, I'll work on a fix.
