### ISSUE TITLE
Nothing displaying for 2D and 3D examples. 

### ISSUE THREAD

**Issue by jacksonlevine** [bevyengine/bevy#10055]
## Bevy version
0.11

## cargo --version output:

cargo 1.73.0 (9c4383fb5 2023-08-26)

AdapterInfo { name: "Intel(R) UHD Graphics", vendor: 32902, device: 35414, device_type: IntegratedGpu, driver: "Intel Corporation", driver_info: "Intel driver", backend: Vulkan }
SystemInfo { os: "Windows 10 Home", kernel: "19045", cpu: "Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz", core_count: "4", memory: "15.7 GiB" }

## What I did

Compile the breakout example:
`cargo run --example breakout`

(Also displays nothing if I compile the 3D Scene example)

## What went wrong

Nothing displays, only the clear color if set.

**Comment by TheoDulka** [comment]
May be duplicate of #8037, have you tried updating your graphics driver?

**Comment by jacksonlevine** [comment]
> May be duplicate of #8037, have you tried updating your graphics driver, or switching your wgpu backend to DX12?

Thank you for pointing this out. Intel has a "disclaimer" on their website, recommending the latest ASUS drivers (from May 2022) over their own, but upon installing the latest Intel graphics drivers anyway against this disclaimers recommendation, now the examples render.
