### ISSUE TITLE
No change notification using `commands.insert_resource`

### ISSUE THREAD

**Issue by msvbg** [bevyengine/bevy#1005]
**Bevy version**

Latest master, fcbae57489f58bb9eb7522131e86b1cf86291037.

**Operating system & version**

macOS 10.14.6

**What you did**

```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_resource(55 as u32)
        .add_system(sys)
        .add_system(sys2)
        .run();
}

fn sys(
    res: ChangedRes<u32>
) {
    println!("Changed {:?}", res);
}

fn sys2(commands: &mut Commands) {
    commands.insert_resource(56 as u32);
}
```

**What you expected to happen**

I expect to get a change notification from `commands.insert_resource(56 as u32)`.

**What actually happened**

There is only a change notification from the initial `.add_resource(55 as u32)`.

**Comment by alec-mccormick** [comment]
`Changed` only tracks changes that occurred earlier within the same frame. Adding sys2 to a stage before sys works.

```rust
fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_resource(55 as u32)
        .add_system(sys)
        .add_system_to_stage(stage::PRE_UPDATE, sys2)
        .run();
}
```

Also note that "55" is not logged here because sys mutates the same resource.

**Comment by msvbg** [comment]
Good point! So, not a bug then.
