### ISSUE TITLE
Instructions for how to disable dynamic linking when compiling to WASM

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [bevyengine/bevy#10054]
`bevy/dynamic_linking` doesn't work when compiling to WASM:
```
$ cargo build --lib --target wasm32-unknown-unknown --features bevy/dynamic_linking
error: cannot produce dylib for `bevy_dylib v0.11.3` as the target `wasm32-unknown-unknown` does not support these crate types
$ cargo build --lib --target wasm32-unknown-unknown
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
```

The [Fast Compiles](https://bevyengine.org/learn/book/getting-started/setup/#enable-fast-compiles-optional) section of the book should show to to make `bevy/dynamic_linking` disabled automagically on WASM (or, alternatively, enabled only on x86)

**Comment by SIGSTACKFAULT** [comment]
Apparently target-specific features is, like, a whole thing https://github.com/rust-lang/cargo/issues/1197

**Comment by SIGSTACKFAULT** [comment]
just found out the book is in bevy/bevy-website; not sure if contributors have a button to move the issue or i should close and open a new one or what.

**Comment by daxpedda** [comment]
Crate features still work if the dependency is behind a `cfg` guard.
https://github.com/bevyengine/bevy/blob/3d79dc4cdc3d4e56668bc314c9ee0bacb4bf0452/Cargo.toml#L254
could be moved behind a:
```rust
[target.'cfg(not(target_family = "wasm"))'.dependencies]
```
This would make the `dynamic_linking` crate feature be no-op on Wasm.
