### ISSUE TITLE
Two RenderInstance types

### ISSUE THREAD

**Issue by superdump** [bevyengine/bevy#10061]
#10002 introduced a `RenderInstance` trait. There is already a `RenderInstance` type that is a graphics API handle. One or the other should be renamed.

**Comment by jancespivo** [comment]
IMHO the new `RenderInstance` trait as it is described and implemented does the "extract" step "to render world" and should be named accordingly (`ExtractComponent` is named in this way). Btw this new trait is more generic (and powerful). `Send + Sync + Sized` - it is almost everything.

I can even imagine naming like `Extract`, `Extractable` or `ExtractInstance`. I don't have strong opinion, I'm just trying to understand bevy code and help. So anything more understandable will be an excellent choice :)

I've added fast and dirty refactoring PR to get some starting point.

**Comment by superdump** [comment]
Here is my proposal:
```rust
struct T;

impl ExtractInstance for T {
    type Query = Read<C>;
    type Filter = ();
    fn extract(item: QueryStuff) -> Self {}
}

pub struct ExtractedInstances<T>;

pub struct ExtractInstancePlugin::<T>::new();
```

**Comment by jancespivo** [comment]
@superdump I like `ExtractInstance` - `ExtractedInstances` - so there is visible difference.

 `ExtractInstancePlugin` might be `ExtractInstancesPlugin` Personally I don't like plural words in code, but in this case the meaning could be clearer. WDYT?
 
 cc @pcwalton as the author of the original improvement :heart:

**Comment by superdump** [comment]
`ExtractInstancesPlugin` is also fine by me.
