### ISSUE TITLE
Storing system params in a struct is too difficult

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#10076]
I'm filing this as a bug report because the issue is too complicated to easily discuss on Discord, and because I'm hoping to get a concrete resolution. However, this is not so much a "bug" as an architectural limitation of Bevy's design.

Assume that I have a Bevy system which is large and complicated, and I want to break it up into several smaller functions. This is relatively easy to do, since the system params can be passed to the helper directly:

```rust
fn example_helper(
    commands: &mut Commands,
    element_query: &mut Query<&mut Component1>,
    text_query: &mut Query<&mut Component2>,
    server: &AssetServer,
    assets: &Assets<MyAsset>,
    asset_path: &AssetPath,
    // (more params not shown)
) -> Result {
```
This works fine so long as the number of parameters passed to the helper function is relatively small. However, if the number of parameters is large, the natural tendency would be to combine several parameters into a struct which is then passed to the helper. This refactoring technique is common in just about every programming language.

(Note that there are other reasons why you might want to put parameters in a struct. For example, you might want to define an abstract interface that hides the details of the individual queries and other system params.)

Unfortunately, as soon as you attempt to put system params in a struct, the Rust compiler demands that you specify explicit lifetimes for each of the members. For example, this won't work:

```rust
struct ParamVals {
    element_query: &mut Query<&mut MyComponent>,
}
```
Instead, explicit lifetimes need to be added:
```rust
struct ParamVals<'r, 'w', 's, 'q> {
    element_query: &'r mut Query<'w, 's, &'q mut MyComponent>,
}
```
However, this won't work either, because even though you can declare a struct like this, you can't construct it - the compiler complains that the lifetime of the component reference is too short (the error message is not particularly helpful, I had to ask on Discord to figure this out). This can be worked around by declaring it as static:

```rust
struct ParamVals<'r, 'w', 's> {
    query: &'r mut Query<'w, 's, &'static mut MyComponent>,
}
```
Unfortunately, in order to construct this, you also have to add `'static` in the system param for your top-level system function - which seems wrong to me.

```rust
fn my_system(
    commands: &mut Commands,
    element_query: &mut Query<&'static mut MyComponent>,
    text_query: &mut Query<&'static mut Text>,
    // etc...
) -> Result {
```
However, it gets worse. If you want to store multiple parameters in your struct, they *each* need separate lifetimes:
```rust
struct ParamVals<'r1, 'w1', 's1, 'r2, 'w2', 's2, 'r3, 'w3', 's3> {
    query1: &'r1 mut Query<'w1, 's1, &'static mut Component1>,
    query2: &'r2 mut Query<'w2, 's2, &'static mut Component2>,
    query3: &'r3 mut Query<'w3, 's3, &'static mut Component3>,
}
```
In other words, as you add more members to the struct, you get an explosion of lifetimes.

I have explored a number of alternative approaches, all of which have led to dead-ends. For example, I thought about simply passing in `World` or `SystemState` in the helper object instead of individual members - but I quickly ran into problems because of borrowing - you couldn't mutably iterate a query and access a second query at the same time.

I've spent the last two months searching for some design pattern or technique that would allow me to write a classic `Visitor` pattern that would let me traverse a tree of entities in a top-down fashion (it needs to be top down because some data is inherited from upper levels). The goal is to have the visitor rebuild the tree as it goes. So far all I have to show for it are several dozens failed experiments. This is just...too hard.

**Comment by rparrett** [comment]
Sorry if I have misinterpreted the issue, and this is something you've already tried / won't work for you. If so, I'm not the lifetime wizard you're seeking.

But have you tried making your param struct a `SystemParam`?

Here is some code that compiles/works.

```rust
use bevy::{ecs::system::SystemParam, prelude::*};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(Update, main_system)
        .add_systems(Update, piecewise_system)
        .run()
}

#[derive(Component, Debug)]
struct Component1;

#[derive(Component, Debug)]
struct Component2;

#[derive(SystemParam)]
struct Params<'w, 's> {
    one: Query<'w, 's, &'static mut Component1>,
    two: Query<'w, 's, &'static mut Component2>,
}

fn helper(params: &mut Params) {
    let thing1 = params.one.single_mut();
    let thing2 = params.two.single_mut();

    println!("{:?} {:?}", thing1, thing2);
}

fn main_system(mut params: Params) {
    helper(&mut params);
}

fn setup(mut commands: Commands) {
    commands.spawn(Component1);
    commands.spawn(Component2);
}
```

**Comment by viridia** [comment]
@rparrett That is very interesting, I did not know about SystemParam (it's not mentioned in the cheatbook - an ongoing problem I've had with Bevy is that some of the most important things I've learned are things that I learned only by chance.)

I will have to experiment and see.

**Comment by dmyyy** [comment]
Discoverability is definitely an issue - I would recommend looking through the examples folder alongside using the cheatbook.

**Comment by viridia** [comment]
The SystemParam suggestion works well. I'm going to close this for now.
