### ISSUE TITLE
Link for Time resource documentation is broken

### ISSUE THREAD

**Issue by kshitijaucharmal** [bevyengine/bevy#10095]
[Resources Page](https://bevyengine.org/learn/book/getting-started/resources/)

The Time link in this page above is broken.
It used to lead to [this](https://docs.rs/bevy_core/latest/bevy_core/struct.Time.html) website.

It can be found using the wayback machine on brave, but essentially is unreachable otherwise.
Maybe its removed from [docs.rs](https://docs.rs)?

Please look into this

**Comment by alice-i-cecile** [comment]
This was migrated to the bevy_time crate :) To fix it, you'll need to make a PR to this repo: https://github.com/bevyengine/bevy-website/pulls

**Comment by kshitijaucharmal** [comment]
Okay :)
