### ISSUE TITLE
Add a way to iterate a system over some query.

### ISSUE THREAD

**Issue by brandon-reinhart** [bevyengine/bevy#10113]
## What problem does this solve or what need does it fill?

I have found I quite frequently write systems that are oriented around iterating on a primary query:

```rust
fn expand(
    mut commands: Commands,
    mut events: EventReader<SelectedTiles>,
    mut zones: Query<&mut Zone>,
    modify_zone_state: Res<ModifyZoneState>,
) {
    for event in &mut events {
        // Try to extend existing zones that intersect with the selected tiles.
```

This frequently happens with events, but also with other types of query where mainly want to do work for each of a thing.

```rust
fn despawn_if_empty(mut commands: Commands, zones: Query<(Entity, &Zone)>) {
    for (entity, zone) in &zones {
        if zone.tiles.is_empty() {
            commands.entity(entity).despawn_recursive();
        }
    }
}
```

This leads to an additional layer of nesting to express the iteration.

It would be nice to express these compactly as:

```rust
// Iterates over all members of Query<(Entity, &Zone)>
fn despawn_if_empty(mut commands: Commands, (entity, zone): (Entity, &Zone)) {
  if zone.tiles.is_empty() {
    commands.entity(entity).despawn_recursive();
  }
}
```

## What solution would you like?

There seem to be several ways of handling this, but one might be something that lets us express the iteration in the system conditions:

```rust
  despawn_if_empty
    .run_if(on_event::<SelectedTiles>())
    .for_each::<(Entity, &Zone)>()
```

## What alternative(s) have you considered?

Maybe there is a way to do it in the argument list, but this seems like it might be less readable.

**Comment by nicopap** [comment]
So this existed in bevy in times immemorial, but was deemed confusing and removed.

See https://bevyengine.org/news/bevy-0-4/#deprecated-for-each-systems

**Comment by james7132** [comment]
There's potential for optimization in allowing the engine take the reigns and decide when to iterate on one thread versus parallelize over all cores, but in practice this has traditionally been very inflexible, requires more refactoring to get into and out of that kind of state, and introduces decision confusion as to which each developer should be using in what particular case. In the interest of not relitigating the older implementations, I'm closing this as not planned. If there's genuine ecosystem-wide interest in this kind of functionality, we can revisit it if need be.
