### ISSUE TITLE
`Asset<...>` and `Handle<...>` queries returns `{unknown}`

### ISSUE THREAD

**Issue by musjj** [bevyengine/bevy#10116]
## Bevy version

0.11.3

## What you did

```rust
fn system(
    query: Query<&Handle<LdtkLevel>>,
    asset: Res<Assets<LdtkLevel>>,
) {
    for handle in query.iter() {
        let level = asset.get(handle);
    }
}
```

## What went wrong

The type for `handle` and `level` is `{unknown}`. The code compiles and functions perfectly fine though. I suspect that this is a `rust-analyzer` bug, but I wanted to understand the issue better before reporting it upstream.

Actually, I figured out that this *only* happens with `LdtkLevel`:
https://github.com/Trouv/bevy_ecs_ldtk/blob/1ee3be3035005b3093a713c760d6236ac728d676/src/assets/ldtk_level.rs#L18-L35
Not really sure if this is a plugin, bevy or rust issue anymore.

**Comment by alice-i-cecile** [comment]
Yep, this is an upstream bug <3 Feel free to keep discussing here, but I'm going to close this out as "not Bevy's fault" for now.

**Comment by adsick** [comment]
May be related to https://github.com/rust-lang/rust-analyzer/issues/14167

**Comment by musjj** [comment]
I don't really know enough Rust to debug this unfortunately :sweat_smile:, some hints would be appreciated. But I did found another mysterious behavior:

```rust
fn system(level_query: Query<(&Handle<LdtkLevel>, &Transform)>) {
    for (handle, transform) in level_query.iter() {
        let x = transform + 1.;
    }
}
```

Both `handle` and `transform` is `{unknown}` here, but `transform + 1.` yields an error (expectedly): `` cannot add `{float}` to `&bevy::prelude::Transform` ``. It's as if it knows the type but decides to not report it.

@adsick

I don't think this is a dependency issue. At least I don't really see any errors related to it.
