### ISSUE TITLE
Custom 3D mesh generation example does not work

### ISSUE THREAD

**Issue by Makogan** [bevyengine/bevy#10137]
## Bevy version

0.11.3

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

Rust version: 1.71.0
OS: Ubuntu Linux 22.04
Hardware: 
   - CPU: AMD Ryzen 5 5600
  ```ignore
    AdapterInfo { name: "NVIDIA GeForce GTX 1070", vendor: 4318, device: 7041, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "525.125.06", backend: Vulkan }
```

## What you did

Create a new project with `cargo new` Add bevy as a dependency.
Copy the code in https://github.com/bevyengine/bevy/blob/latest/examples/3d/generate_custom_mesh.rs into `main.rs`
Do `cargo run`

## What went wrong

Screen appears grey, no mesh is visible. Inspecting the renderer with renderdoc seems to show no dedicated draw call is being issued for geometry.

## Additional information
![image](https://github.com/bevyengine/bevy/assets/17284362/dff0dd87-ad61-4427-a9b5-d59adb36b863)
![image](https://github.com/bevyengine/bevy/assets/17284362/ba2dcc80-d0ce-4900-9ea9-b7134d6b8ce9)

**Comment by afonsolage** [comment]
This examples requires `assets/textures/array_texture.png`, have you added it to your project folder? Also, there is any warning or error in the console output?

I tested it here, on my Windows 11 machine, and it worked fine, I did a clean `cargo new` project.

**Comment by Makogan** [comment]
Oh I see, the engine does throw a warning, rather than an error explaining the issue which is why I missed it. Thank you.
