### ISSUE TITLE
Demonstrate how to use the Time API to effectively pause and resume your game

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#10133]
## How can Bevy's documentation be improved?

https://github.com/bevyengine/bevy/pull/8964 introduced several new APIs to pause, resume and slow down time. In the many games, this will be an effective way to pause the game! No need for run conditions or states.

However, this could use its own example under `bevy_time`.

**Comment by SecretPocketCat** [comment]
Can I take this?
I'm thinking a sprite moving left to right with buttons and keybindings to pause/resume and speed up/down time should cover it and UI showing the fixed and virtual times. Does that sound good?

**Comment by alice-i-cecile** [comment]
Yes please, that sounds great!

**Comment by SecretPocketCat** [comment]
When first looking at this I missed this should go in `bevy_time`. Does the outlined example makes sense in that crate? Shouldn't that be swapped with the current time example (which just logs stuff) or replace it?

**Comment by alice-i-cecile** [comment]
Oh, I meant to say, this should go in the `time` folder of the main `bevy` examples! Examples that are specific to the `bevy_time` crate will be hard to discover and not really that useful.

**Comment by SecretPocketCat** [comment]
I've landed on this, but I still need to properly document the example. I skipped the buttons 'cause that would add too much noise.

![image](https://github.com/bevyengine/bevy/assets/17273703/a885f1e4-3bd4-46cb-b911-abc02ccdaad9)

**Comment by WayneKeenan** [comment]
Are there any recent examples, existing or planned, that demonstrate using virtual time with rapier physics?
thanks
