### ISSUE TITLE
Asset loading on the Web produces many 404 errors for `.meta` files

### ISSUE THREAD

**Issue by coreh** [bevyengine/bevy#10157]
## Bevy version

5733d2403

## What you did

Ran any example that loads assets under WASM / WebGL with:

```bash
cargo run -p build-wasm-example -- $EXAMPLE_NAME_HERE && python3 -m http.server --directory examples
/wasm
```

## What went wrong

Got barraged with 404 error messages in the web inspector with the page trying to load `.meta` files for every asset loaded.

## Additional information

<img width="1212" alt="image" src="https://github.com/bevyengine/bevy/assets/418473/a21b71ca-879a-4d4d-83db-b8486449c608">

- Looks like with #8624 we now look for `.meta` files for every asset that we load
- On native this is a non issue, however on the web we do a bunch of requests, which both spam the console with 404 errors and also potentially slow down loading of the files that actually exist

**Comment by hymm** [comment]
A solution might be for the web asset source to write out a manifest file of the available asset files. This could also be used to solve `load_folder` not working on the web.

**Comment by mockersf** [comment]
Adding the 0.12 milestone. I think this should be looked over before the release, it will raise a lot of questions on wasm

**Comment by hymm** [comment]
Should probably just suppress the error on wasm for now, until we come up with something better.

**Comment by alice-i-cecile** [comment]
No PR exists, and the release is imminent. Bumping to 0.13, but I'd nominate this for 0.12.1 as well.

**Comment by rparrett** [comment]
Adding this info for searchability.

This is also tripping up users who are using `trunk` or other dev web servers that act in an "spa" mode where the server doesn't actually serve 404s.

They will see error messages like
```
/home/redacted/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.0/src/server/mod.rs:274 Failed to deserialize meta for asset image.png: Failed to deserialize minimal asset meta: SpannedError { code: ExpectedNamedStructLike("AssetMetaMinimal"), position: Position { line: 1, col: 1 } }
```
Because the web server is just serving the contents of `index.html` when a file is missing.

**Comment by forbjok** [comment]
When uploaded to itch.io, the server the assets are hosted on return 403 instead of 404, and this actually causes the game to completely fail to run.

**Comment by alice-i-cecile** [comment]
If we can get a fix in for this, we should include it in 0.12.1

**Comment by rparrett** [comment]
Is there a procedure users can follow right now to generate default meta files to work around the issue on itch?

**Comment by P13L0v3r** [comment]
Since it wasn't said, 
```rs
.set(AssetPlugin {
    mode: AssetMode::Unprocessed,
    ..default()
})
```
does not fix the issue.

**Comment by cart** [comment]
Yeah this needs fixing for 0.12.1, especially given that the next Bevy Jam is coming up / WASM builds are a big part of that.

I think long term the path forward is "asset packing/compression with manifests". That way we can record if a meta file exists in the manifest and avoid making the request. And WASM deployments should _probably_ ultimately be using processing + packing anyway to cut down on bandwidth usage / loading times.

Short term, I think we should probably just add a knob that controls meta file lookup behavior. Ex:

```rust
enum AssetMetaMode {
    // Always look for meta files
    Always,
    // Only look up meta files for assets in the given list 
    AllowList(Vec<AssetPath<'static>),
    // Never look for meta files. The default loader meta values will be used
    Never,
}
```

Given that most people probably aren't using meta files at this point, this is probably the right "patch fix" approach. Users can just set this to `AssetMetaMode::Never`. Ideally we have a fix that requires _no_ manual intervention, but I haven't thought of one yet.

**Comment by valyagolev** [comment]
Since nobody posted very _specifically_ what to do here, answer is: 

>add .insert_resource(AssetMetaCheck::Never) 

to your app

**Comment by rparrett** [comment]
> Since nobody posted very _specifically_ what to do here, answer is:

There's some code in the [linked PR](https://github.com/bevyengine/bevy/pull/10623) that adds the workaround. Make sure you add this resource **before** `DefaultPlugins`.

**Comment by awwsmm** [comment]
Can confirm that this is still happening in `0.13.0` and that @valyagolev 's single-line change prevents 404s from spamming the browser console

**Comment by SK83RJOSH** [comment]
Just wanted to follow up and say that this should definitely be kept in/after 14.0.0 - my app almost entirely processes non-bevy game assets that will never have meta files. Including loading/mounting archives which gates all other types of file I/O from happening - which ironically means if that if this feature is enabled, the archives themselves can get gated by asset waiting for `.meta` io.

Definitely something I can workaround by just letting those requests bypass the gate, but if someone else were to do something similar, and the archives themselves contain `meta` files... well it begins to get rather complicated quickly. 🙂 

That said, if this is kept in 14.0.0, I think it would be worthwhile to investigate an approach that lets particular resources/loaders/processors opt-out of meta files, as plugins would likely not want to force users to disable meta files across the board/manually register all exceptions.

**Comment by mrchantey** [comment]
**Single Page Applications**

When serving assets from a typical SPA setup they will not load at all without `AssetMetaCheck::Never`. This is because `example.com/assets/foo.meta` redirects back to `index.html` which bevy will cheerfully attempt to read as a meta file.

btw heres the `^0.14` one-liner
```rust
app.world_mut().insert_resource(AssetMetaCheck::Never);
```

**Comment by benfrankel** [comment]
In bevy `0.14` the workaround is now:
```rust
app.add_plugins(DefaultPlugins.set(AssetPlugin {
    meta_check: AssetMetaCheck::Never,
}));
```

**Comment by SK83RJOSH** [comment]
Just wanted to follow up and say the move to making this a non-resource makes the story for plugins even more complicated than before. Now I have to offer guidance on disabling meta files before my plugin is loaded, rather than just opt-out *if* my plugin is loaded, which makes the user story more complex.

As mentioned before, it would be nice to make this something a given source opts into/out of, instead of having it be global setting.

**Comment by AgustinRamiroDiaz** [comment]
> In bevy `0.14` the workaround is now:
> 
> ```rust
> app.add_plugins(DefaultPlugins.set(AssetPlugin {
>     meta_check: AssetMetaCheck::Never,
> }));
> ```

I think defaults are also needed

```
        DefaultPlugins
            .set(AssetPlugin {
                meta_check: AssetMetaCheck::Never,
                ..default()
            })
```

**Comment by katopz** [comment]
This should be add to all example or `AssetMetaCheck::Never` by default. I lost a day and crying because of this! And everything should work by default by all mean. T-T

**Comment by logankaser** [comment]
This can cause failures to load assets:
```
ERROR editor::tile: Failed to load tile at (11295, 83170): Failed to deserialize meta for asset <url redacted>: Failed to deserialize minimal asset meta: SpannedError { code: Utf8Error(Utf8Error { valid_up_to: 12, error_len: Some(1) }), span: Span { start: Position { line: 1, col: 1 }, end: Position { line: 1, col: 13 } } }
```
