### ISSUE TITLE
Add built-in font(s)

### ISSUE THREAD

**Issue by visualcode-t** [bevyengine/bevy#1017]
**What problem does this solve or what need does it fill?**

It would be nice if we were able to have at least one built-in font. Even better if we had the option to fall-back to this default when a font is unable to be found.

**Describe the solution would you like?**

Add support for one or more common fonts. Optionally allow setting of a "fall-back" font to an item when the expected font is not found.

**Comment by rparrett** [comment]
This may be relevant.

http://www.oxfordshireweb.com/smallest-file-size-google-web-fonts/

**Comment by nicopap** [comment]
For https://github.com/nicopap/bevy-debug-text-overlay/ I made a special font derived from Adobe Pro (SIL) with only the ASCII range. You can get very small file sizes with this trick.

What would be _ideal_ thought for a font is something with a C00 or public domain license. Then our users wouldn't have to worry about licensing issues, even in the case where the font is just really meant to be used in dev and not distributed with the final binary.

**Comment by mockersf** [comment]
I would really prefer to support defaulting to a system font (#1325) than using a limited to ascii font

**Comment by nicopap** [comment]
@mockersf Though with this approach, you wouldn't be able to use the system fonts on web target. I think a (feature-flag disableable) built-in font for debugging purpose is still useful, even considering access to system fonts.

**Comment by mockersf** [comment]
I haven't looked into it at all, but shouldn't it be possible to load fronts from the browser on web target?
