### ISSUE TITLE
Bevy crash in release mode with lto=fat and codegen-units=1

### ISSUE THREAD

**Issue by ameknite** [bevyengine/bevy#10190]
I found a weird bug.

## Bevy version

Bevy "0.11.3"

## Relevant system information

```
cargo 1.73.0 (9c4383fb5 2023-08-26)
```

```
SystemInfo { os: "MacOS 14.0 ", kernel: "23.0.0", cpu: "Apple M1", core_count: "8", memory: "8.0 GiB" }
```

```
AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

I try to run this in release mode

```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run();
}
```

with this configuration

```toml
[profile.release]
lto = "fat"
codegen-units = 1
```

## What went wrong

The program compile but don't run. Only output this:

It 

```
INFO bevy_render::renderer: AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## Additional information

I think is apple-silicon related, because it works with MacOS-x86-64 and web. Or maybe is llvm, idk.

Doesn't work in 0.11 neither 0.12.
Doesn't work in rust stable neither nightly.

***Only happens with the specific configuration mentioned.
Works fine in every other configuration.***

Works fine with only release mode.
Works fine with only lto fat.
Works fine with only 1 codegen-unit.
Works fine with release mode and lto fat.
Works fine with release mode and 1 codgen-unit.
Works fine with release mode, lto fat and 1 codegen-unit without the bevy code.
Works fine with dev mode, lto fat and 1 codgen-unit.

## Workaround
[profile.release]
lto = "thin"
codegen-units = 1

**Comment by mockersf** [comment]
I have a segfault with the following trace:
```
(lldb) thread backtrace
* thread #1, name = 'main', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x4010111d543)
  * frame #0: 0x0000000101032870 lighting`wgpu_types::TextureFormat::required_features::h4bedd5d698ff9ebd + 20
    frame #1: 0x0000000100f8a600 lighting`_$LT$T$u20$as$u20$wgpu..context..DynContext$GT$::device_create_texture::ha57f194316042610 + 3384
    frame #2: 0x00000001008bbc98 lighting`_$LT$bevy_sprite..mesh2d..mesh..Mesh2dRenderPlugin$u20$as$u20$bevy_app..plugin..Plugin$GT$::finish::hb38af1f736d8c01a + 2080
    frame #3: 0x000000010003305c lighting`lighting::main::h3e7bb3520d806574 + 5500
    frame #4: 0x0000000100011e14 lighting`std::sys_common::backtrace::__rust_begin_short_backtrace::h5112e50ff8968f77 + 12
    frame #5: 0x000000010003840c lighting`main + 588
    frame #6: 0x00000001886f3f28 dyld`start + 2236
```

Could you try to reproduce with a wgpu example?

**Comment by ameknite** [comment]
Now it works ¯\_(ツ)_/¯
