### ISSUE TITLE
Using custom rodio Source for audio output

### ISSUE THREAD

**Issue by tarkah** [bevyengine/bevy#102]
It appears `AudioSource` will only work with encoded data that can be decoded by rodio's `Decoder`.  It'd be awesome if we could pass any type that implements rodio's `Source` trait to the audio output as well. 

For example, I've ported an [Atrac3+ decoder](https://github.com/tarkah/atrac3p-decoder) to Rust that I'd love to use with this framework. I've also created an [ffmpeg decoder](https://github.com/tarkah/ffmpeg-decoder-rs) that implements `Source`, which opens up support for a huge amount of codecs, if someone really needed it. Neither of these will ever get added to rodio, so having this flexibility would be awesome.

This project is looking really great, can't wait to try it out!

**Comment by cart** [comment]
That sounds like a good call. So far I've just implemented the bare minimum to play sound, so theres still plenty of work to do in this area.

Its great to hear feedback from someone with more `rodio` experience! In the short term I'm gonna crank out PBR rendering, but audio will definitely get some love in the near-ish future. I'm also very willing to collaborate if anyone else wants to take a stab!

**Comment by tarkah** [comment]
Awesome! I'm totally down to contribute. Let me think through a reasonable API for this and I'll open a PR for feedback.

**Comment by tarkah** [comment]
What is the purpose of the `extensions` method for `AssetLoader`? Since this will be fairly generic, is having an empty extensions list ok? Or should we require the user to implement some sort of trait to define their custom source so we can properly capture the extension list for it?
