### ISSUE TITLE
Cargo build fails on example on MacOS 14.0 because it could not compile ahash

### ISSUE THREAD

**Issue by eikopf** [bevyengine/bevy#10241]
- Bevy 0.11.3
- Rust 1.75.0 (nightly, aarch64)
- MacOS Sonoma (14.0)

This looks to be because of [ahash #170](https://github.com/tkaitchuck/aHash/issues/170), which has been fixed and is [waiting](https://github.com/tkaitchuck/aHash/pull/171) to be merged into the master branch.

**Comment by mockersf** [comment]
the fix has been merged, and version 0.8.5 has been published. does it work for you with it?

**Comment by eikopf** [comment]
sorry for the delay; the project now builds, but segfaults on cargo run.

**Comment by eikopf** [comment]
also worth noting that this happens when dynamic linking is disabled, and after rebuilding without it i got the following error message:

```
> cargo run
    Finished dev [optimized + debuginfo] target(s) in 0.28s
     Running `target/debug/bevy-sandbox`
2023-10-25T15:06:08.988886Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
thread 'main' panicked at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/core/src/iter/adapters/enumerate.rs:87:17:
attempt to add with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
libc++abi: terminating due to uncaught foreign exception
fish: Job 1, 'cargo run' terminated by signal SIGABRT (Abort)
```

this only happened on the first run after the build, and then i continued to get the same segfault behaviour as before.

**Comment by eikopf** [comment]
final note for now; this issue only appears on the most recent nightly toolchain, and so it looks like this is a duplicate of #10273. for anyone looking for a workaround, set

```toml
[profile.dev.package."*"]
opt-level = 2
```

in your Cargo.toml.
