### ISSUE TITLE
Finish renaming cubic splines

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#10258]
@alice-i-cecile Shouldn't this be done for all the cubic splines, not just one of them? This makes the spline naming inconsistent.

https://docs.rs/bevy/0.11.3/bevy/math/cubic_splines/index.html

_Originally posted by @aevyrie in https://github.com/bevyengine/bevy/issues/9554#issuecomment-1778603460_

**Comment by aevyrie** [comment]
Would it make sense to revert that change prior to 0.12? If anything, it's made the API more confusing. Previously, all the `Cubic` types were the generic spline types that end users would use to generate points, etc. Now there is a Bezier type that shares this name, unlike all the other cubic spline generators.

**Comment by alice-i-cecile** [comment]
Yep, I would like to see this API consistent, one way or another, for 0.12.
