### ISSUE TITLE
Set the `GlobalTransform` of the children when spawning a scene

### ISSUE THREAD

**Issue by Selene-Amanita** [bevyengine/bevy#10265]
## Summary

This is not technically a bug, more like a pitfall that could be avoided in my opinion by having Bevy explicitely set the `GlobalTransform` of the children when spawning a scene instead of delegating that to `propagate_transform`.

## Bevy version

0.11.1
(0.12.0 might have solved the problem already?)

## What we are doing

We have a system, let's call it `spawn_pieces`, that spawn a single scene of several pieces that we want to be handled as separate entities by rapier.

For that, we used `bevy_scene_hooks`, and we created a hook that, when the scene is spawned, despawns the parent entity and use `remove_parent_in_place` to deparent the pieces.

## What went wrong

We had a pretty rare system ordering bug (meaning: it happened only sometimes, rarely, and when it happened it happened all the time until we close the game, when it didn't happen it never did until we close the game): sometimes, the pieces would all spawn at the origin instead of spawning where the scene was spawned and relative to their position in the scene.

We managed to reproduce the bug reliably by adding the following piece of code:
```rust
app.add_systems(Update, apply_deferred.after(scene_spawner_system).before(run_hooks));
```

What we believe happened is when the bug happens, the scene is spawned in `spawn_pieces`, then (in the same tick or next tick depending on the order between `spawn_pieces` and `scene_spawner_system` and when the commands are applied), in the following order in Update:
- `scene_spawner_system` from `bevy_scene runs`, the scene children spawn, with a default (ZERO) `GlobalTransform` (that should be updated to a correct value later in `PostUpdate`)
- there is an `apply_deferred` (probably added in a totally unrelated place in our code)
- `run_hooks` from `bevy_scene_hooks` runs the hook added in `spawn_pieces`, which deparents those children using `remove_parent_in_place`

Problem: `remove_parent_in_place` uses the children's `GlobalTransform` which still have the default value at this point, so they end up with a `Transform` at the origin.

This happened only sometimes because those systems weren't explicitly ordered.

We solved the problem by forcing the ordering above, but adding `propagate_transform` between `apply_deferred` and `run_hooks`, like this:
```rust
app.add_systems(
    Update,
    (apply_deferred, propagate_transforms)
        .chain()
        .after(scene_spawner_system)
        .before(run_hooks),
);
```

## What could Bevy do about it
This was actually a relative hard bug to debug and in my opinion it could have been avoided by making a change in Bevy (I put two but I think only the first one is realistic).

1. I think it wouldn't cost too much to set explicitly the `GlobalTransform` of the children of the scene in `scene_spawner_system` and it would solve the issue.
2. change `remove_parent_in_place` to test if the `GlobalTransform` was just added and is equal to ZERO, and in that case calculate the new Transform using the root of the hierarchy tree's Transform and going down, something like this, maybe a way to mark a GlobalTransform as being not actually set (since there are pitfalls in similar situations actually)?

## What could bevy_scene_hook do about it
I don't think it's bevy_scene_hook's responsibility to prevent this pitfall, but it could technically:

1. move `run_hooks` in PostUpdate after the `TransformPropagate` set
2. order `run_hooks` before scene_spawner_system
3. do what we did

**Comment by nicopap** [comment]
This is going to be fixed in 0.12 with the new scene spawning schedule, it was discussed here https://github.com/bevyengine/bevy/pull/9260
