### ISSUE TITLE
Inconsistent implementations for calculating aspect ratios

### ISSUE THREAD

**Issue by mamekoro** [bevyengine/bevy#10288]
## Bevy version
- 0.11.3
- the main branch as of `b22db47`

## What went wrong
Aspect ratios should be calculated as `width / height`, not `height / width`.

In the code base of the version 0.11.3 and the main branch (`b22db47`), I found that `bevy_render/src/texture/image.rs` wrongly uses `height / width` while other files correctly use `width / height`.

### v0.11.3
https://github.com/bevyengine/bevy/blob/0d23d71c19c784ceb1acfbb134dda9ce0c2adc61/crates/bevy_render/src/texture/image.rs#L260-L263

### The main branch as of `b22db47`
https://github.com/bevyengine/bevy/blob/b22db47e1003db2d712baec46c0f0a1f88b0a837/crates/bevy_render/src/texture/image.rs#L542-L546

## Additional information
Other files use `width / height`.

https://github.com/bevyengine/bevy/blob/0d23d71c19c784ceb1acfbb134dda9ce0c2adc61/crates/bevy_ui/src/ui_node.rs#L388-L391

https://github.com/bevyengine/bevy/blob/0d23d71c19c784ceb1acfbb134dda9ce0c2adc61/crates/bevy_render/src/camera/projection.rs#L121-L127

https://github.com/bevyengine/bevy/blob/0d23d71c19c784ceb1acfbb134dda9ce0c2adc61/crates/bevy_pbr/src/light.rs#L714

https://github.com/bevyengine/bevy/blob/0d23d71c19c784ceb1acfbb134dda9ce0c2adc61/crates/bevy_core_pipeline/src/bloom/settings.rs#L214

## Idea
Calculations related to aspect ratio can be confusing. So, what about the idea of creating a newtype struct like `pub struct AspectRatio(f32)`?

**Comment by superdump** [comment]
I’m surprised to see height / width anywhere. Curious.

**Comment by Olle-Lukowski** [comment]
I would like to try my hands on this, but I have one question. I think creating the `pub struct AspectRatio(f32);` is a good idea, but where should it be created? because it's used in multiple places. If this is a weird question, sorry I'm new to contributing.

**Comment by mamekoro** [comment]
Maybe `bevy_math`? It is widely used and contains some APIs related to rectangles. I think it's appropriate because aspect ratios are also related to rectangles.

**Comment by Olle-Lukowski** [comment]
Alright, I will get started then.

**Comment by Olle-Lukowski** [comment]
How should this be done? Only use the `AspectRatio` struct as an intermediate for making sure the calculations are consistent, or actually replace all instances where a f32 is used as the aspect ratio to use the struct?

**Comment by mamekoro** [comment]
I think the former is better for now in terms of making changes smaller. However, I think the APIs will be safer if field types and function return types are also `AspectRatio`.

I'd like to wait for members' opinions.
