### ISSUE TITLE
gLTF does not render correctly

### ISSUE THREAD

**Issue by erwanvivien** [bevyengine/bevy#10282]
## Bevy version

0.11.3

## What you did

```rust
//! Loads and renders a glTF file as a scene.

use bevy::{
    pbr::{CascadeShadowConfigBuilder, DirectionalLightShadowMap},
    prelude::*,
};

fn main() {
    App::new()
        .insert_resource(AmbientLight {
            color: Color::WHITE,
            brightness: 1.0 / 5.0f32,
        })
        .insert_resource(DirectionalLightShadowMap { size: 4096 })
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera3dBundle {
        transform: Transform::from_xyz(2.7, 2.7, 2.7).looking_at(Vec3::new(0.0, 0.3, 0.0), Vec3::Y),
        ..default()
    });

    commands.spawn(DirectionalLightBundle {
        directional_light: DirectionalLight {
            shadows_enabled: true,
            ..default()
        },
        // This is a relatively small scene, so use tighter shadow
        // cascade bounds than the default for better quality.
        // We also adjusted the shadow map to be larger since we're
        // only using a single cascade.
        cascade_shadow_config: CascadeShadowConfigBuilder {
            num_cascades: 1,
            maximum_distance: 1.6,
            ..default()
        }
        .into(),
        ..default()
    });
    commands.spawn(SceneBundle {
        scene: asset_server.load("karts/suv.glb#Scene0"),
        ..default()
    });
}
```

Adapted from [load gLTF example](https://bevyengine.org/examples-webgpu/3D%20Rendering/load-gltf/)

## What went wrong

The GLB is ok most of the time and some times not:

## Additional information

Asset is `suv.glb` from https://kenney.nl/assets/car-kit
Zip [suv.glb.zip](https://github.com/bevyengine/bevy/files/13188269/suv.glb.zip)

<img width="1392" alt="Screenshot 2023-10-27 at 13 18 12" src="https://github.com/bevyengine/bevy/assets/44021072/9833cc5d-20ee-473e-bb8d-446afc5769be">
<img width="1392" alt="Screenshot 2023-10-27 at 13 18 38" src="https://github.com/bevyengine/bevy/assets/44021072/ec0f4594-12d6-4654-8807-3728342f4fe8">

Thanks to someone on the Discord helping me a bit on Blender, I could try to re-export the model with re-computed normals (Didn't change anything)
Then we tried to remove backface culling which "helped" but is still not good

**Comment by superdump** [comment]
I wonder if it’s something like the winding order of the spare tyre is flipped and there’s some gltf property to do that that we aren’t respecting…

**Comment by erwanvivien** [comment]
Note: I was sure that the model was good as it renders fine in Blender and I re-exported the "valid" model

However this model loads the exact same way in Unreal engine as in Bevy
So, now my guess is that the asset is bad, so I'll let you decide on the future of this issue

**Comment by nicopap** [comment]
Try setting the [`alpha_mode`](https://docs.rs/bevy/latest/bevy/pbr/struct.StandardMaterial.html#structfield.alpha_mode) of the material to `AlphaMode::Opaque`. Here is a discussion on how to do it: <https://github.com/bevyengine/bevy/discussions/8533>.

**Comment by erwanvivien** [comment]
Hey! Thanks for the reply @nicopap

I'm afraid that it didn't fix much

![image](https://github.com/bevyengine/bevy/assets/44021072/78f7ede2-1cc8-4ec6-9dd6-8ec8f0fc72c7)

<details>
  <summary>New code used</summary>
  
  ```rust
//! Loads and renders a glTF file as a scene.

use bevy::{
    pbr::{CascadeShadowConfigBuilder, DirectionalLightShadowMap},
    prelude::*,
};

fn main() {
    App::new()
        .insert_resource(AmbientLight {
            color: Color::WHITE,
            brightness: 1.0 / 5.0f32,
        })
        .insert_resource(DirectionalLightShadowMap { size: 4096 })
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(Update, change_scene_materials)
        .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera3dBundle {
        transform: Transform::from_xyz(2.7, 2.7, 2.7).looking_at(Vec3::new(0.0, 0.3, 0.0), Vec3::Y),
        ..default()
    });

    commands.spawn(DirectionalLightBundle {
        directional_light: DirectionalLight {
            shadows_enabled: true,
            ..default()
        },
        // This is a relatively small scene, so use tighter shadow
        // cascade bounds than the default for better quality.
        // We also adjusted the shadow map to be larger since we're
        // only using a single cascade.
        cascade_shadow_config: CascadeShadowConfigBuilder {
            num_cascades: 1,
            maximum_distance: 1.6,
            ..default()
        }
        .into(),
        ..default()
    });
    commands.spawn(SceneBundle {
        scene: asset_server.load("karts/suv.glb#Scene0"),
        ..default()
    });
}

fn change_scene_materials(
    mut query: Query<&mut Handle<StandardMaterial>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    for material in query.iter_mut() {
        let color_mat = materials.get_mut(&material).unwrap();
        color_mat.alpha_mode = AlphaMode::Opaque;
    }
}

  ```
</details>

**Comment by nicopap** [comment]
Yeah, something fishy. I would leave the issue open until we figure why it's not rendering properly.

**Comment by erwanvivien** [comment]
Alright, thanks :) Have a great day

**Comment by superdump** [comment]
My suggestion would be to set double-sided to true and disable culling in that wheel.

**Comment by erwanvivien** [comment]
I just replaced the model tbh, so there is no urgency

**Comment by mockersf** [comment]
seems fixed on main, at least with `scene_viewer`
<img width="1280" alt="Screenshot 2023-10-30 at 22 31 28" src="https://github.com/bevyengine/bevy/assets/8672791/eacecd35-33b0-4597-9a2d-f1fde758e219">

**Comment by erwanvivien** [comment]
Cool, should I close @mockersf, do you know which commit fixed it ?

**Comment by erwanvivien** [comment]
Hey @alice-i-cecile, thanks for closing the issue
I'm just curious, has this been fixed or is it a won't fix?

Thanks :)

**Comment by nicopap** [comment]
> seems fixed on main, at least with `scene_viewer`
To me, this sounds like "fixed"

**Comment by erwanvivien** [comment]
Ok, I'm literally blind, sorry and thank again :)
