### ISSUE TITLE
Trait-based color conversions to/from Vec4 are too implicit and should be removed

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#10319]
No problem! I felt like `Vec4::from(color).truncate()` is a bit boilerplate-y, so I opened this PR.

_Originally posted by @st0rmbtw in https://github.com/bevyengine/bevy/issues/10318#issuecomment-1784969213_
            
Instead of the existing approach (and the one proposed in the linked PR), I think we should have explicit impl methods such as `Color::rgba_from_vec4(vec: Vec4)`.

It is very easy to screw up your color spaces currently, and forcing conversion methods to declare the color space used will improve matters.

**Comment by afonsolage** [comment]
We would need also:
```
Color::rgb_from_vec3(vec: Vec3)
Color::rgba_from_vec4(vec: Vec4)
Color::rgb_linear_from_vec3(vec: Vec3)
Color::rgba_linear_from_vec4(vec: Vec4)
Color::hsl_from_vec3(vec: Vec3)
Color::hsla_from_vec4(vec: Vec4)
Color::lch_from_vec3(vec: Vec3)
Color::lcha_from_vec4(vec: Vec4)
```
in order to match the current `Color` API.

And maybe also `*_to_vecX()`?
