### ISSUE TITLE
Query fails to find existing entity

### ISSUE THREAD

**Issue by torsteingrindvik** [bevyengine/bevy#10329]
## Bevy version

Latest main: d67fbd5

## What you did

I have two systems added to `render_app`:

```rust
render_app.add_systems(
                Render,
                prepare_bind_groups.in_set(RenderSet::PrepareBindGroups),
            )
            .add_systems(Render, map_read.after(RenderSet::Render))
```

The summarized systems are as follows:

```rust
fn prepare_bind_groups(
    ...
    views: Query<
        (Entity, &RenderImage, &CameraIndex),
        (With<PackedFrameSender>, With<ActiveFrameSender>),
    >,
) {
    ...
    for (entity, render_image, camera_id) in &views {
        info!("Preparing bind group for entity={entity:?}");
        ...
   }
}
```

```rust
fn map_read(
    ...
    debug_query: Query<
        (
            Entity,
            Option<&CameraIndex>,
            Option<&RenderImageBindGroup>,
            Option<&PackedFrameSender>,
        ),
        With<ActiveFrameSender>,
    >,
) {
    if debug_query.is_empty() {
        info!("No entities marked active");
    }
```

## What went wrong

I run my Bevy app and the query is populated (see **Working logs** below).
I stop my app and and I run it again (no code changes!), and the query is forever empty (see **Not working logs**) even though `prepare_bind_groups` finds the correct entity.

The working situation and the non-working situation happens about 50% of the time, but if it works it keeps working (until the app quits), and if it does not work it never works (i.e. then the query is always empty in `map_read` but `prepare_bind_groups` is ok).

I don't see a way for the query to be empty when `prepare_bind_groups` clearly finds the entity.
I even made all extra components (except the `ActiveFrameSender` marker) optional in order to debug the query, but still empty.

### Working logs

```
INFO system{name="prepare_bind_groups"}:prepare{frame=50}:cam{segment=3 index=0}: Preparing bind group for entity=17v0
INFO system{name="map_read"}:send packed{frame=50}:cam{segment=3 index=0}: Sending 10368000 bytes
```

### Not working logs

```
INFO system{name="prepare_bind_groups"}:prepare{frame=93}:cam{segment=3 index=0}: Preparing bind group for entity=17v0
INFO system{name="map_read"}:send packed{frame=93}: No entities marked active
```

**Comment by hymm** [comment]
Are you using main branch? 0.11.3 doesn't have a `RenderSet::PrepareBindGroups`

**Comment by torsteingrindvik** [comment]
> Are you using main branch? 0.11.3 doesn't have a `RenderSet::PrepareBindGroups`

Yes, latest main (I put a commit hash at the top)

**Comment by superdump** [comment]
Hmm. The PrepareFlush should be run after PrepareBindGroups and before Render.

**Comment by torsteingrindvik** [comment]
The bug has been flaky for me locally but I got it again this morning.

After fiddling a lot with `Schedule` and the `hierarchy` and `dependency` DAGs and trying to figure out if I could print them to `.dot` files (seems you can since `petgraph` is used) and trying to map `NodeId`s back to system names I tried something else.

I changed the render world's `ScheduleBuildSettings` to not have `ambiguity_detection` set to ignore, which printed out ~70 ambiguities for me (seems like there are quite a bit by default https://github.com/bevyengine/bevy/issues/1868).

One of my ambiguities was between my `map_read` system and things in the `Cleanup` render set.

At first I didn't see how that could be but then it dawned on me:

```rust
// before
app.add_systems(Render, map_read.after(RenderSet::Render))

// after
app.add_systems(Render, map_read.after(RenderSet::Render).before(RenderSet::Cleanup))
```

I haven't seen the problem since, and the ambiguity detection for `map_read` is gone.
I _think_ this fixed it but I'll keep watching for this bug for a few days.

I'd love for someone to comment on whether my interpretation is correct:

**Does `system_foo.after(set)` allow scheduling `system_foo` at _any_ time within the frame as long as `set` is complete?**

**Comment by johnbchron** [comment]
As far as I know it allows scheduling it anytime in the schedule (so in the `Render` schedule) after the `.after(foo)` run criteria.

**Comment by torsteingrindvik** [comment]
> As far as I know it allows scheduling it anytime in the schedule (so in the `Render` schedule) after the `.after(foo)` run criteria.

So since both `RenderSet::Render` and `RenderSet::Cleanup` are in the `Render` schedule, an `.after(RenderSet::Render)` on its own does not necessarily mean before `RenderSet::Cleanup`.

**Comment by alice-i-cecile** [comment]
I think we can close this out as not directly actionable, although I really want this experience to improve in several ways.
