### ISSUE TITLE
Fog improperly blending with background color

### ISSUE THREAD

**Issue by Rigidity** [bevyengine/bevy#10323]
## Bevy version

0.11.3

## Relevant system information

```ignore
`AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "525.125.06", backend: Vulkan }`
```

## What you did

I enabled fog and set it to the same color as the background.

## What went wrong

The fog doesn't correctly blend together with certain color and tonemapping settings. Specifically, tonemapping + black works, but tonemapping + white doesn't. No tonemapping + white works, but colors like `rgb(0.1, 0.0, 1.0)` don't regardless. Doesn't make any sense. It appears as if the fog's being rounded or something like that, maybe? `rgb(0.1, 0.0, 1.0)` shows as purple even though the background should be mostly blue.

## Additional information

This is a full minimum reproducible example: https://github.com/Rigidity/bevy-fog-issues-mre

![image](https://github.com/bevyengine/bevy/assets/35380458/dc2c0e8e-8db0-4a89-8309-48c590f1c9f4)
![image](https://github.com/bevyengine/bevy/assets/35380458/1d9051b1-74f5-4c00-81f8-8f4d48a67621)

**Comment by aevyrie** [comment]
> No tonemapping + white works, but colors like rgb(0.1, 0.0, 1.0) don't regardless

Might be gamma is also being missed?

**Comment by alice-i-cecile** [comment]
Can you reproduce this on main after https://github.com/bevyengine/bevy/pull/10226? It looks like this might be already fixed.
