### ISSUE TITLE
Error trying to load Window in serialized scene

### ISSUE THREAD

**Issue by naomijub** [bevyengine/bevy#10357]
## Bevy version

Version 0.11.3

## What you did

Whenever I execute my load scene code, I encounter this error:
`2023-11-03T21:01:54.867389Z  WARN bevy_asset::asset_server: encountered an error while loading an asset: Expected float at scenes/scene1.scn.ron:42:15`

This is the saved scene:
```
      components: {
        "bevy_window::window::Window": (
          cursor: (
            icon: Default,
            visible: true,
            grab_mode: None,
            hit_test: true,
          ),
          present_mode: Fifo,
          mode: Windowed,
          position: Automatic,
          resolution: (
            physical_width: 1280,
            physical_height: 720,
            scale_factor_override: None,
            scale_factor: 1.0,
          ),
          title: "App",
          composite_alpha_mode: Auto,
          resize_constraints: (
            min_width: 180.0,
            min_height: 120.0,
            max_width: inf,
            max_height: inf,
          ),
          resizable: true,
          decorations: true,
          transparent: false,
          focused: true,
          window_level: Normal,
          canvas: None,
          fit_canvas_to_parent: false,
          prevent_default_event_handling: true,
          internal: (
            minimize_request: None,
            maximize_request: None,
            physical_cursor_position: Some((
              x: 155.0,
              y: 108.0,
            )),
          ),
          ime_enabled: false,
          ime_position: (
            x: 0.0,
            y: 0.0,
          ),
          window_theme: Some(Dark),
        ),
        "bevy_window::window::PrimaryWindow": (),
      },
    ),
```

Where line 42 is the x on:
``` 
physical_cursor_position: Some((
    x: 155.0, <<-
    y: 108.0,
)),
```
The code behind this is (`world: &mut World,`):
``` 
if let Some(asset_server) = world.get_resource::<AssetServer>() {
      let scene =
          asset_server.load(format!("scenes/{}", state.load_file));
      world.spawn(DynamicSceneBundle { scene, ..default() });
      state.scene_load_result = Some(Ok(state.load_file.clone()));
  } else {
      state.scene_load_result =
          Some(Err("Error: AssetServer Resource not found".to_string()));
  }
```

## What went wrong
- what were you expecting?
Anything else than an error saying a float is not a float.

## Additional information

Should I skip serialization of the internal information in this case? How could I configure that when saving a scene? If I remove it from the ron I get the following error:
`encountered an error while loading an asset: missing field `internal` at scenes/scene1.scn.ron:40:9`

Is there an option to default missing values?

**Comment by alice-i-cecile** [comment]
Hmm. Do you want to be saving / loading windows in your scenes? This is definitely not a useful error message at all though.

**Comment by naomijub** [comment]
> Hmm. Do you want to be saving / loading windows in your scenes? This is definitely not a useful error message at all though.

Exactly!
My workaround was to not load window, as I have a constant window value that I can spawn. And the camera I removed the one that had issues from the saved file. However, when I spawn the scene, it becomes an empty entity

**Comment by naomijub** [comment]
I managed to avoid this error by extracting components that were not part of the scene:
```
let mut query = world.query_filtered::<Entity, (
                        Without<EditorOnly>,
                        Without<EditorCamera>,
                        Without<PrimaryWindow>,
                    )>();
let entities = query.iter(world).collect();
``` 

However, how can I load Handles, like `Handle<Mesh>` and `Handle<StandardMaterial>`, for the object that owned them correctly?

@alice-i-cecile
