### ISSUE TITLE
There should be a way of preventing `.despawn_recursive()` from despawning specific child entities.

### ISSUE THREAD

**Issue by JoJoJet** [bevyengine/bevy#10353]
## What problem does this solve or what need does it fill?

`despawn_recursive` is a useful extension method for removing a hierarchy of entities. However, some entities move between different parents, and/or are meant to survive their parent. There should be a way of making specific entities get ignored by `despawn_recursive`.

## What solution would you like?

Some type of marker component that tells `despawn_recursive` to skip a descendant entity.

```rust
#[derive(Component)]
pub struct NoDespawnRecursive;
```

## What alternative(s) have you considered?

None.

**Comment by cuppachino** [comment]
I would like to suggest an alternative with two variations. Having a filtered version of `despawn_recursive` would be more flexible.

### `where T: ReadOnlyWorldQuery`

```rust
commands.entity(entity).despawn_recursive_filtered::<With<FungalSpores>>()
```

### `where T: Bundle`

```rust
commands.entity(entity).despawn_recursive_filtered::<MyNoDespawnRecursive>()
```
