### ISSUE TITLE
Can't use `anyhow` when writing custom `AssetLoader`s or `AssetSaver`s

### ISSUE THREAD

**Issue by Roryl-c** [bevyengine/bevy#10350]
## Bevy version

v0.12.0

## What you did

Tried to use `anyhow::Error` as the value for the associated type `Error` in my implementation of an `AssetLoader`, as recommended in #10003.

## What went wrong

```
error[E0277]: the trait bound `anyhow::Error: StdError` is not satisfied
   --> src\asset.rs:111:18
    |
111 |     type Error = anyhow::Error;
    |                  ^^^^^^^^^^^^^ the trait `StdError` is not implemented for `anyhow::Error`
    |
note: required by a bound in `bevy::asset::AssetLoader::Error`
   --> <snip>\bevy_asset\src\loader.rs:31:17
    |
31  |     type Error: std::error::Error + Send + Sync + 'static;
    |                 ^^^^^^^^^^^^^^^^^ required by this bound in `AssetLoader::Error`
```

## Additional information

#10003 suggests that `anyhow::Error` is intended to be a drop-in replacement here, to make migrations easier. I had to add `thiserror` as a project dependency just for this one file.

**Comment by deltanedas** [comment]
did you do something like this?

```
#[derive(Error)]
pub struct LoaderError {
    #[error("uh oh")]
    error: anyhow::Error
}
```

**Comment by Roryl-c** [comment]
@deltanedas Naw I just enumerated the error types since I figured if I'm being made to pull in `thiserror` I might as well use it as intended.

However it doesn't seem intended that I had to pull in `thiserror` just to interact with this system in an ergonomic way, and the intention appears to have been for `anyhow::Error` to be a drop-in replacement, hence it seems to be a bug.

**Comment by deltanedas** [comment]
i think its an issue on anyhows end since youd expect to be able to use it for something that wants std error trait

**Comment by rparrett** [comment]
@bushrat011899 any idea what's going on here? It's not clear to me whether this is a trait bound issue or if the migration guide suggesting `anyhow` should be updated.

**Comment by deltanedas** [comment]
i looked at anyhow and couldnt see *any* Error trait implemention, bounds or not.

**Comment by Testare** [comment]
There's a github issue describing why anyhow::Error doesn't implement std::error::Error: https://github.com/dtolnay/anyhow/issues/25

Looking at the doc, anyhow doesn't implment Error but it has AsRef, Deref, and From implementation (From<Error> to StdError) to allow conversion.

**Comment by bushrat011899** [comment]
> There's a github issue describing why anyhow::Error doesn't implement std::error::Error: https://github.com/dtolnay/anyhow/issues/25
> 
> Looking at the doc, anyhow doesn't implment Error but it has AsRef, Deref, and From implementation (From<Error> to StdError) to allow conversion.

That's a mistake on my part then! When I made that PR, I assumed `anyhow::Error` would implement `Error`. I think the simplest option here would be to update the migration guide to suggest using `Box<dyn Error + Send + Sync>`, or a new type around `anyhow::Error`.

**Comment by Roryl-c** [comment]
> I think the simplest option here would be to update the migration guide to suggest using `Box<dyn Error + Send + Sync>`, or a new type around `anyhow::Error`.
@bushrat011899 I did try the first one before I made the issue, but unfortunately the way the trait bounds are set up it seems to want `Error` to be `Sized` as well...
```
error[E0277]: the size for values of type `(dyn StdError + Send + Sync + 'static)` cannot be known at compilation time
   --> src\asset.rs:119:18
    |
119 |     type Error = Box<dyn std::error::Error + Send + Sync>;
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `(dyn StdError + Send + Sync + 'static)`
    = help: the trait `StdError` is implemented for `std::boxed::Box<T>`
    = note: required for `std::boxed::Box<(dyn StdError + Send + Sync + 'static)>` to implement `StdError`
note: required by a bound in `bevy::asset::AssetLoader::Error`
   --> <snip>\bevy_asset\src\loader.rs:31:17
    |
31  |     type Error: std::error::Error + Send + Sync + 'static;
    |                 ^^^^^^^^^^^^^^^^^ required by this bound in `AssetLoader::Error`

For more information about this error, try `rustc --explain E0277`.
```
I'm not sure how to get a newtype around `anyhow::Error` to work either without explicitly implementing `std::fmt::Display` and `std::error::Error` for the newtype, which is much more tedious than just pulling in `thiserror`.

**Comment by Testare** [comment]
I still think we should try to make the associated Error type able to support anyhow::Error in some way, or enable some sort of generic Error handling. As far as I'm aware there's not really any sort of error handling that is type specific for AssetReader, just using the Error trait. Meanwhile, I have at least 4 different AssetReaders in my code currently across different crates, and now I have to create different error types for different ones and make sure that they convert all the errors to the appropriate type.

It might not make it into one of the 0.12.x patches, but supporting anyhow in 0.13 would be ideal

**Comment by rlidwka** [comment]
> Meanwhile, I have at least 4 different AssetReaders in my code currently across different crates, and now I have to create different error types for different ones

If you don't care about strong error typing, you can use `Box<dyn Error + Send + Sync>` as mentioned above.

**Comment by Roryl-c** [comment]
@rlidwka As also mentioned above, that produces an error message currently - the compiler wants the boxed type to be `Sized`.

**Comment by rlidwka** [comment]
@Roryl-c, okay, sounds like a bug then.

Do you have a minimal example (of a code that worked with anyhow before) that we can try out?

**Comment by Roryl-c** [comment]
@rlidwka My code was originally based on the `examples/shader/compute_shader_game_of_life.rs` example but `examples/asset/custom_asset.rs` is likely more minimal. Both used `anyhow::Error` before #10003.

**Comment by rafalh** [comment]
I also stepped onto this problem. I wanted to use `Box<dyn std::error::Error + Send + Sync>` as mentioned above but it does not work because `T` must be `Sized` for `Box<T>` to implement `std::error::Error` which is a little non-intuitive. It looks like a Rust bug that cannot be solved because of backward compatibility reasons. See: https://github.com/rust-lang/rust/issues/104485
Did anybody found a workaround that does not require to defining `Error` type for every loader?
