### ISSUE TITLE
`set_runner` doesn't work like it did in 0.11 after updating to 0.12

### ISSUE THREAD

**Issue by alexschrod** [bevyengine/bevy#10385]
## Bevy version

0.12

## What you did

I have a [Bevy plugin crate](https://github.com/alexschrod/bevy_doryen/) for using Bevy (mainly the ECS, although I also make use of the Bevy `App` to orchestrate the whole thing) with another game engine.

In order to support this, I'm using a custom runner, which up until 0.12, would always run *before* anything else, and so I could do some very early initialization safely there.

https://github.com/bevyengine/bevy/blob/32a5c7db3535250c43738e3da5877497b1274960/crates/bevy_app/src/app.rs#L312-L318

👆 Thanks to these lines added between 0.11 and 0.12, I'm now getting panics, because systems get to run (thanks to the call to `app.update()`) before my custom runner gets to do its required initializations.

## What went wrong

This change was very unexpected to me. I thought the runner would be in charge of everything, including running systems *at all*, but now this privilege has been taken from me, and it breaks everything.

Is there a way to make it so I can turn this new code off in later Bevy releases? I don't care about iOS support and want to be in total control over calls to `app.update()`.

## Additional information

If you're interested, this is my custom runner:

https://github.com/alexschrod/bevy_doryen/blob/140d7eb7a84a1ef9b8f064918d83f39e1f4d9508/src/lib.rs#L348-L381

And the reason it's important that only *I* get to call `app.update()` is that this *needs* to happen before and after each such call:

https://github.com/alexschrod/bevy_doryen/blob/140d7eb7a84a1ef9b8f064918d83f39e1f4d9508/src/lib.rs#L258-L260

**Comment by devil-ira** [comment]
You can avoid calling `app.set_runner()` and `app.run()` entirely and just manually call your existing runner function.
You may want to call `app.finish()` and `app.cleanup()` once before that in case any of your plugins make use of those.

**Comment by alexschrod** [comment]
I don't know what you mean by "I can avoid" those. Users of my plugin are expected to do
```rs
App::new()
    .add_plugins(DoryenPlugin)
    // [and everything else they want to use]
    .run();
```
like they would any other Bevy project. That's how I want the user experience to be; it's just Bevy coupled with a different engine. And as I pointed out, this has been working just fine since 0.4 through 0.11 and this change realy *feels* to me like it has "undermined" what runners should have the privilege of being in control over in this stack.

**Comment by devil-ira** [comment]
Sorry about that. I see how it's used now.

It does feel like this change should have happened inside the runner, not outside of it.
I'll take a look at it.

**Comment by devil-ira** [comment]
I've opened #10389 to revert the changes made to `App::run()`. I'm a bit disappointed that it was unnecessarily changed like that.

Now I'm fairly confident #10389 will be merged, but I'm unsure if it will make it into a 0.12 patch release :(

**Comment by ickk** [comment]
This also breaks me
