### ISSUE TITLE
0.12 migration guide doesn't mention the rename of `file_watcher`

### ISSUE THREAD

**Issue by RyeToastyO** [bevyengine/bevy#10402]
## How can Bevy's documentation be improved?

https://bevyengine.org/learn/migration-guides/0.11-0.12/

Asset Hot Reloading
Feature `filesystem_watcher` has been renamed to `file_watcher`.  In addition, you no longer need to manually configure the `ChangeWatcher` in the `AssetPlugin` as it is now configured automatically when the feature is enabled.

**Comment by alice-i-cecile** [comment]
Could you reopen this on the `bevy-website` repo? :) Great issue, and I want to make sure it doesn't get lost.

**Comment by RyeToastyO** [comment]
> Could you reopen this on the `bevy-website` repo? :) Great issue, and I want to make sure it doesn't get lost.

Ahh, just saw this, looks like you already took care of it though.  Thanks! <3
