### ISSUE TITLE
Regression: gizmo lines with vertices behind camera display artifacts

### ISSUE THREAD

**Issue by aevyrie** [bevyengine/bevy#10403]
## Bevy version

Appears in 0.12

https://github.com/bevyengine/bevy/assets/2632925/c2aa215a-e7a9-4132-b3f7-0715847d7e9a

Seems to be related to https://github.com/bevyengine/bevy/pull/9470

**Comment by devil-ira** [comment]
It is the changes in #9470 that are causing issues in the big_space demo. On 0.11.1 it looks fine aside from the lines deforming a little.
Looks like an issue with precision, but these cubes are only 2000 units and close to the center of the world, right?

Well I can reproduce this with a cube of 100 000 units. Definitely an issue with precision, I'll try to improve that.

**Comment by aevyrie** [comment]
Yes, these cubes are small and close to the origin. I was not seeing this issue on 11.3 fwiw.
