### ISSUE TITLE
Implement FromIterator for EntityHashMap

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#10418]
> This does change public API. Should a system be implemented to help migrate code?

Breaking changes are generally fine.

> Perhaps an impl From<HashMap<K, V, S>> for EntityHashMap<K, V>

I think that we should probably just use the `FromIterator` trait. Useful idea though, might as well do that here.

_Originally posted by @alice-i-cecile in https://github.com/bevyengine/bevy/issues/10415#issuecomment-1795508772_

**Comment by nicopap** [comment]
`EntityHashMap` is a type alias for `HashMap`, so whatever `HashMap` implements, `EntityHashMap` does. What is needed here is change the API of methods accepting a `EntityHashMap`.
