### ISSUE TITLE
Spatial Audio Functional Regression - different spatial scaling factor for each object

### ISSUE THREAD

**Issue by johnny-smitherson** [bevyengine/bevy#10414]
## What problem does this solve or what need does it fill?

I want to scale spatial audio differently for each effect. This is so I can have some "far away" effects (low volume, low distance scaling) mixed together with some "close up" effects (high volume, high distance scaling).

For example, explosions - when they happen far away, https://freesound.org/people/rhapsodize/sounds/255111/

When they happen close up, https://freesound.org/people/juskiddink/sounds/108641/

Both effects need to live at the same time with different spatial scales, because the camera can quickly move closer/further away from the audio source.

I would also want this to work on multiple listeners at the same time: one main camera for 80% volume, and a few extra cameras for 20% volume each.

This was trivial under Bevy 0.11 (in the old update positions system), but now is impossible with bevy_audio 0.12:

> https://bevyengine.org/learn/migration-guides/0.11-0.12/#more-ergonomic-spatial-audio
> If you were manually scaling emitter/listener positions, you can use the spatial_scale field of AudioPlugin instead.

But the `AudioPlugin` is a global, so all objects must share the same spatial scale.

## What solution would you like?

Extra field `spatial scale` for each Spatial Audio Source

## What alternative(s) have you considered?

- in a system, manually change the `RelativeVolume` component based on distance and some formula
  - problem: doesn't work with multiple listeners, because the volume is set per-effect not per-listener
- swap out bevy_audio for one of the external plugins

**Comment by rparrett** [comment]
"Spatial Scale" in Bevy 0.11 was also "global" -- it affects the position of the ears as well.

I think another potential workaround would be adding a system that multiplies your emitter `GlobalTransform` translations after `TransformSystem::TransformPropagate` but before `AudioPlaySet`. If that works for you, I'm not sure if this needs to be treated as a regression.

Affecting a particular audio source's distance attenuation seems useful. I'd like to see examples of how other game engine audio APIs work for this use-case.

**Comment by rparrett** [comment]
Godot has the following on its emitters:
- Attentuation model
- Max distance
- "Unit Size" (scale)

And no configuration for the listener, only position. There can only be one active listener.

**Comment by johnny-smitherson** [comment]
> "Spatial Scale" in Bevy 0.11 was also "global" -- it affects the position of the ears as well. At least how it was implemented in the examples.

Yes, what I did was scale the sink around the listener:

```
fn update_spatial_audio_locations(
    emitter_query: Query<(&GlobalTransform, &SpatialAudioSink, &SpatialAudioEffect)>,
    listener_query: Query<&GlobalTransform, With<SpatialAudioListener>>,
) {
    let Ok(listener) = listener_query.get_single() else {
        return;
    };
    let listener = listener.compute_transform();

    for (emitter, sink, effect_info) in &emitter_query {
        let emitter = emitter.compute_transform().translation;
        let emitter =
            listener.translation + (emitter - listener.translation) * effect_info.scale_range;
        sink.set_emitter_position(emitter);
        sink.set_listener_position(listener, SPATIAL_AUDIO_EAR_GAP);
    }
}
```

> I think another potential workaround would be adding a system that multiplies your emitter GlobalTransform translations after TransformSystem::TransformPropagate but before AudioPlaySet

I'll take a look, thanks!


>  I'd like to see examples of how other game engine audio APIs work for this use-case. 

### Godot

- each "audio source" is controlled by ["audio stream player 3d"](https://docs.godotengine.org/en/3.2/tutorials/audio/audio_streams.html#audiostreamplayer3d) which has separate spatial controls, including linear damping, collisions, reverb
- support for multiple listeners (called Audio Busses), mixed together: https://docs.godotengine.org/en/3.2/tutorials/audio/audio_buses.html#doc-audio-buses

### Unity

- "audio source" has a bunch of 3D Sound Settings - https://docs.unity3d.com/Manual/class-AudioSource.html
  - look at the graphs in the picture: volume,  reverb, etc. as functions of distance
- multiple listeners NOT supported - [Each scene can only have one Audio Listener.](https://docs.unity3d.com/Manual/class-AudioListener.html)


### Unreal
- extremely complex including volume attenuation, spatial collisions, focus, priority, etc.
- customizable for each separate audio source

**Comment by rparrett** [comment]
> - different spatial audio settings for each emitter object
meaningful support for multiple simultaneous listeners with different spatial settings and positions (like Godot Audio Busses)
> - should open a different feature request for this one

Agreed, thanks for doing that roundup. On the first bullet point, I know that scale is obviously feasible but I'm guessing that other attenuation options might not be doable with `rodio`.

Just need to determine whether or not there's an acceptable workaround now.
