### ISSUE TITLE
WASM build is failing for projects using Bevy 0.12 (including the Bevy wasm example)

### ISSUE THREAD

**Issue by forbjok** [bevyengine/bevy#10417]
## Bevy version

0.12.0

## \[Optional\] Relevant system information

cargo 1.73.0 (9c4383fb5 2023-08-26)
Windows 10 Pro 22H2 build 19045.3570

## What you did

Try to build a Bevy 0.12.0 project for WASM.

## What went wrong

The build fails with this error.
![image](https://github.com/bevyengine/bevy/assets/4687674/73a1daa1-69f8-414d-92fe-a0160c1f0be5)

This happens both with my game project, and when trying to build the WASM example in the Bevy repository.

**Comment by rparrett** [comment]
This is #10412. Running `cargo update` should fix the issue.

**Comment by forbjok** [comment]
> This is #10412. Running `cargo update` should fix the issue.

Nope, just tested again after running `cargo update`, and it's still producing the same error.

**Comment by mockersf** [comment]
```
cargo update --package blocking --precise 1.4.1
```

for now should make it work

**Comment by forbjok** [comment]
> ```
> cargo update --package blocking --precise 1.4.1
> ```
> 
> for now should make it work

Yep, that seems to work as a workaround.

**Comment by mockersf** [comment]
https://github.com/smol-rs/blocking/issues/52

**Comment by Irvingouj** [comment]
Blocking should never be used in any asynchronous context, this will never be tolerated in browser (wasm32-unknown-unknown).

**Comment by nicopap** [comment]
It is currently impossible to merge any PR due to this issue. Marking the issue as critical.

**Comment by nicopap** [comment]
Resolved now?

**Comment by forbjok** [comment]
> Resolved now?

Yes, the issue seems to have gone away now.
