### ISSUE TITLE
Forbid internal system ambiguities when using `DefaultPlugins` in CI

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#10416]
## What problem does this solve or what need does it fill?

Bevy-internal system order ambiguities are bad because:

1. They're often the source of real bugs.
2. They badly pollute end-user diagnostics.

## What solution would you like?

Add an integration test which adds all default plugins, checks for ambiguities and then panics if there are any.

Ideally this is run with all features enabled.

## Additional context

Discussed in:
- https://github.com/bevyengine/bevy/pull/10411
- https://github.com/bevyengine/bevy/issues/9511

**Comment by alice-i-cecile** [comment]
Done in bevy_xpbd by @johanhelsing in https://github.com/Jondolf/bevy_xpbd/pull/230

**Comment by BD103** [comment]
Similar (or maybe a duplicate? I can't tell): #7386

**Comment by alice-i-cecile** [comment]
Yep, duplicate.
