### ISSUE TITLE
Missing Asset error doesn't say which asset is missing

### ISSUE THREAD

**Issue by anarelion** [bevyengine/bevy#10438]
## What problem does this solve or what need does it fill?

Error is difficult to address

`2023-11-08T00:09:15.785413Z ERROR bevy_asset::server: encountered an io error while loading asset: The system cannot find the file specified. (os error 2)`

## What solution would you like?

I would like to know which file is missing.

## What alternative(s) have you considered?

I can find out, but it will take me time. I think it is much better if the error message is complete.

**Comment by orph3usLyre** [comment]
Hi, I'd like to take this up as my first issue!

Just to make sure that I understand correctly: would this require changing the `ReadAssetBytesError::Io(#[from] std::io::Error)` variant to also hold the the missing file path (and updating the error caller appropriately)?

**Comment by killercup** [comment]
Yup! The easiest option is to remove the `#[from]` and add another field, then fix the compiler errors you encounter (probably using `map_err` and manual construction of the error variant).

**Comment by orph3usLyre** [comment]
Awesome, thanks!

**Comment by DasLixou** [comment]
i think this can be closed?

**Comment by nicopap** [comment]
My testing shows this is fixed indeed. Closed by #10450
