### ISSUE TITLE
`Timer::{percent,percent_left}` should be renamed

### ISSUE THREAD

**Issue by mamekoro** [bevyengine/bevy#10439]
## Bevy version
0.12.0

## What went wrong
`Timer::percent()` and `Timer::percent_left()` should use the word "fraction" or "frac" instead of "percent" for their names.

The reasons are as follows;

- When I hear the word "percent", I imagine a value in the range of 0 to 100, but these functions return a value from 0 to 1, which causes confusion.

- It is confusing when the same word is used for several different behaviors. e.g. `Timer::percent()` returns a value from 0 to 1, but `Val::Percent` holds a value from 0 to 100. Both of these APIs contain the word "percent" but have different meanings.

**Comment by alice-i-cecile** [comment]
Definitely agree. Please feel free to make a PR!

**Comment by mamekoro** [comment]
Which word should I use, "fraction" or "frac"?

**Comment by AlexAegis** [comment]
I vote for fraction, haven't really heard frac being used before, and percent wasnt shortened to perc either
