### ISSUE TITLE
Custom Post-Processing WebGL2 example from website does not work; WebGPU version hangs chrome

### ISSUE THREAD

**Issue by johnny-smitherson** [bevyengine/bevy#10460]
## Bevy version

website example (latest?) https://bevyengine.org/examples/Shaders/post-processing/

## \[Optional\] Relevant system information

tested and fails on:
- WebGL2 / Firefox 119 / Windows: cube has no effect
- WebGL2 / Chrome 119 / Windows: cube has no effect
- [WebGPU](https://bevyengine.org/examples-webgpu/Shaders/post-processing/) / Chrome 119 / Windows: browser hangs until restart (other WebGPU examples work)

## What you did

Visit website examples in configurations above

## What went wrong

- WebGL: cube has no effect
- WebGPU: browser hangs until restarted

## Additional information

<img width="1834" alt="ppCapture" src="https://github.com/bevyengine/bevy/assets/127537716/263e2a5e-f496-4ebb-a874-f81c932e5df0">

shown: firefox in background, chrome in foreground, native Windows only one that actually applies the effect (checkout v0.12.0).

console log on firefox:

```
ERROR crates/bevy_render/src/render_resource/pipeline_cache.rs:811 failed to process shader:
error: required import 'bevy_core_pipeline::fullscreen_vertex_shader::FullscreenVertexOutput' not found
   ┌─ shaders/post_processing.wgsl:21:1
   │
21 │ #import bevy_core_pipeline::fullscreen_vertex_shader::FullscreenVertexOutput
   │ ^
   │
   = missing import 'bevy_core_pipeline::fullscreen_vertex_shader::FullscreenVertexOutput'

```

**Comment by rparrett** [comment]
The examples are unfortunately not yet up-to-date. (https://github.com/bevyengine/bevy-website/issues/814)

The example seems to work for me locally, so once that is resolved, this should be fixed as well.

**Comment by rparrett** [comment]
This got fixed.
