### ISSUE TITLE
Animation player jumps to the first frame after animation ends, instead of staying at the last frame

### ISSUE THREAD

**Issue by idanarye** [bevyengine/bevy#10480]
## Bevy version

Bevy v0.12.0

## What you did

The problem happens when I start a non-repeating animation with the `AnimationPlayer`. I've created a repository that demonstrates the problem: https://github.com/idanarye/demonstrate-bevy-0.12-animation-bug

In the demos, hit the Spacebar to start the animation. If you run them in WASM you'll probably need to click on the canvas first before it starts accepting keyboard input.

## What went wrong

- _what were you expecting?_ [The behavior I get in Bevy v0.11](https://idanarye.github.io/demonstrate-bevy-0.12-animation-bug/bevy11/bevy_github_ci_template): at the end of the animation, the model should be the last frame.
- what actually happened? [The behavior I get in Bevy v0.12](https://idanarye.github.io/demonstrate-bevy-0.12-animation-bug/bevy12/bevy_github_ci_template): at the end of the animation, the model jumps back to the first frame.

## Additional information

Note that I'm using the same glb file I used when I found the problem. I've tried to replicate it with a simpler glb file, but with no success. So it is possible that something is wrong with my glb file (which is very likely - I had to import some lost animation from an old export to the blender file, which could have messed things up), but since it works just fine in Bevy v0.11 there may be an actual regression in Bevy v0.12.

**Comment by egsam98** [comment]
I've also reproduced this error today

**Comment by sluedecke** [comment]
Same here after migrating from 0.11.3 to 0.12

**Comment by 5tr1k3r** [comment]
Saw that as well. I was using morph targets/shape keys animation.

**Comment by nicopap** [comment]
working on it
