### ISSUE TITLE
Panic when loading a custom asset

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#10492]
bevy version: 0.12

### What I did

Ran `some code` (will create a MRE later) using `cuicui_chirp` 0.11.0. It is supposed to load the chirp file

### What I expected

The file loads

### What occurred

A panic:

```
thread 'main' panicked at /bevy_asset-0.12.0/src/assets.rs:149:13:
internal error: entered unreachable code: entries should always be valid after a flush
```

More information coming.

**Comment by 5tr1k3r** [comment]
Can confirm that I had the same issue (once). At the time I was kinda heavily tinkering with things so didn't pay much attention to it (which is also why it'd be hard to reproduce). It was an instant crash upon loading the app.

**Comment by nicopap** [comment]
Duplicate of #10444
