### ISSUE TITLE
post_processing example failng with validation error when ran outside of bevy main repo and target wasm32-unknown-unknown

### ISSUE THREAD

**Issue by rafawo** [bevyengine/bevy#10503]
## Bevy version

`0.12.0`

## Relevant system information

* `cargo 1.71.0 (cfd3bbd8f 2023-06-08)`
* `AdapterInfo { name: "ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)", vendor: 32902, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }`

### OS

```ignore
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       Microsoft Corporation
System Model:              Surface Laptop Studio
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~3302 Mhz
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5030651
                           [02]: KB5012170
                           [03]: KB5031354
                           [04]: KB5031592
```

## What you did

- Setup vanilla project, copying post_processing example:

```cmd
cargo new --bin test_bevy_post_processing
cd test_bevy_post_processing
cargo add bevy@0.12.0
mkdir .cargo
echo [target.wasm32-unknown-unknown] > .cargo\config.toml
echo runner = "wasm-server-runner" >> .cargo\config.toml
curl https://raw.githubusercontent.com/bevyengine/bevy/v0.12.0/examples/shader/post_processing.rs > src\main.rs
mkdir assets\shaders
curl https://raw.githubusercontent.com/bevyengine/bevy/v0.12.0/assets/shaders/post_processing.wgsl > assets\shaders\post_processing.wgsl
```

- Build and run project
```cmd
cargo update -p wasm-bindgen
cargo install -f wasm-bindgen-cli
cargo install -f wasm-server-runner
cargo run --release --target wasm32-unknown-unknown
```

- Open `http://127.0.0.1:1334/` on preferred web browser

## What went wrong

- **what were you expecting?**
  - post_processing example to work on the browser after copy-pasting it from official bevy repository on a vanilla project
- **what actually happened?**
  - Failed to run post processing shader on web browser using wasm build with the following validation error:

```ignore
panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `post_process_pipeline`
    Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
    Shader global ResourceBinding { group: 0, binding: 2 } is not available in the layout pipeline layout
    Buffer structure size 32, added to one element of an unbound array, if it's the last field, ended up greater than the given `min_binding_size`
```

## Additional information

This error is confusing, as cloning the official bevy repository and running the example from there works just fine with  `cargo run --release --example post_processing --target wasm32-unknown-unknown`

My suspicion is that this might have something to do with a missing feature that is not part of bevy's defaults, but I couldn't pinpoint what nor I'm sure this is the case. Would appreciate any help here as I would like to do post processing on wasm builds.

**Comment by rumbogs** [comment]
I'm also encountering a similar issue when trying to reproduce the `custom_material` shader example locally.

I'm on `AdapterInfo { name: "Apple M2 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }`

**Comment by paul-hansen** [comment]
Ran into this too. Figured it out though, this line needs to be changed since your app won't have a `webgl2` feature:
https://github.com/bevyengine/bevy/blob/v0.14.0/examples/shader/post_processing.rs#L305

Essentially you need to make sure that padding is included when you compile your app for webgl2.

Also that line should probably be updated in Bevy to be:
```rust
#[cfg(all(feature = "webgl2", target_arch = "wasm32", not(feature = "webgpu")))]
```
Currently it's always including that field even on non-wasm targets since webgl2 is enabled by default.

**Comment by rafawo** [comment]
Ah nice, that definitely did the trick. I've also removed the `#ifdef` condition at https://github.com/bevyengine/bevy/blob/v0.14.0/assets/shaders/post_processing.wgsl#L27-L30, so it matches the material definition in `main.rs` and simply include the padding always as my app will build to webgl2 by default anyway.
