### ISSUE TITLE
Shader hot reloading no longer works for locally imported shaders

### ISSUE THREAD

**Issue by DGriffin91** [bevyengine/bevy#10500]
## Bevy version 0.12

In 0.11 it was possible to hot reload locally imported shaders. This no longer works in 0.12.

```wgsl
#import "shaders/bar.wgsl"::bar
[...]
let a = bar(frag_coord);
```

If I try to edit `shaders/bar.wgsl` I get:

```wgsl
2023-11-10T21:55:48.695089Z  INFO bevy_asset::server: Reloading shaders\bar.wgsl because it has changed
2023-11-10T21:55:48.707801Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: required import '"shaders/bar.wgsl"' not found
   ┌─ shaders/foo.wgsl:83:13
   │
83 │     let a = bar(frag_coord);
   │             ^
   │
   = missing import '"shaders/bar.wgsl"'
```

**Comment by cart** [comment]
This is what the [Embedded Asset Source](https://github.com/bevyengine/bevy/pull/98850) / multiple asset sources was built for. The old DebugAssetServer approach was pretty clunky and I didn't want to carry that pattern forward. We haven't ported built in shaders over yet unfortunately. I think an important step is to move to implicit module names (as in, the module syntax directly desugars to the embedded asset paths).

**Comment by cart** [comment]
Have you enabled the `file_watcher` feature? I can hot reload changes to `custom_material.wgsl` _and_ `custom_material_import.wgsl` in the `shader_material` example.

**Comment by DGriffin91** [comment]
I have enabled the `file_watcher` feature. If I edit `custom_material_import.wgsl` I get:
```rs
2023-11-10T22:44:27.261541Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: required import '"shaders/custom_material_import.wgsl"' not found
   ┌─ shaders/custom_material.wgsl:17:94
   │
17 │     return material.color * textureSample(base_color_texture, base_color_sampler, mesh.uv) * COLOR_MULTIPLIER;
   │                                                                                              ^
   │
   = missing import '"shaders/custom_material_import.wgsl"'
```

**Comment by cart** [comment]
Very strange. This is what I ran:

```
git checkout v0.12.0
cargo update
cargo run --example shader_material --features file_watcher
```

I can change either file, add new imports, etc and it all works.

I'm on linux.
