### ISSUE TITLE
Asset loading errors are not reported when using `load_untyped` or `load_folder`

### ISSUE THREAD

**Issue by juh9870** [bevyengine/bevy#10515]
## Bevy version

0.12.0

## What you did

I was writing an asset loading system for my game.

## What went wrong
When using `asset_server.load_untyped` or `asset_server.load_folder`, in case of asset loading failure, error is completely discarded without logging or reporting in any way, unlike `asset_server.load::<MyAssetType>`, which reports an error via `tracing` crate

## Additional information
Places where errors ~~go to die~~ silently disappear without reporting:

https://github.com/bevyengine/bevy/blob/c50561035833943876672a6f15e3cda2752ce11a/crates/bevy_asset/src/server/mod.rs#L349
https://github.com/bevyengine/bevy/blob/c50561035833943876672a6f15e3cda2752ce11a/crates/bevy_asset/src/server/mod.rs#L626

**Comment by cart** [comment]
Good catch. Seems like a straightforward fix!
