### ISSUE TITLE
Panic on custom `UiMaterial` using a texture not loaded yet

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#10513]
## Bevy version

0.12

## What you did

Follow [the docs for `UiMaterial`](https://docs.rs/bevy/latest/bevy/prelude/trait.UiMaterial.html), using an image texture.

## What went wrong

Panic:

```
  13:     0x7ff6ecaef015 - bevy_ui::render::ui_material_pipeline::queue_ui_material_nodes<my_project::ui::UiGrayscaleFilterMaterial>
                               at C:\Users\<user>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ui-0.12.0\src\render\ui_material_pipeline.rs:730
```

## Additional information

- `extract_ui_material_nodes` doesn't look at texture loading
- `queue_ui_material_nodes` does an `unwrap()` on the `RenderUiMaterials<M>`
- I suspect the custom material is only inserted in `RenderUiMaterials<M>` by `prepare_ui_materials` once the image is actually loaded
- The `example/ui/ui_material.rs` doesn't use an image so we don't have coverage for that case I think

**Comment by djeedai** [comment]
Debugged, this is `AsBindGroup::as_bind_group()` failed on first frame, because `Self::unprepared_bind_group()` returns `AsBindGroupError::RetryNextUpdate`. I can't really find the relevant derive code but I suspect the derive waits for the image to be loaded.

**Comment by cart** [comment]
@MarkusTheOrt

**Comment by MarkusTheOrt** [comment]
I’ll take a look as soon as I can. I currently have computer problems that I hope to have fixed by tomorrow.

**Comment by djeedai** [comment]
Thanks @MarkusTheOrt !
