### ISSUE TITLE
Allow asset loaders to call other asset loaders - the "gzip" problem

### ISSUE THREAD

**Issue by simbleau** [bevyengine/bevy#10518]
The feature request is simple: Process one asset and pass it to the next asset loader.

This should be possible:
- Asset loader exists for extensions "gz", "tar.gz"
- Asset loader decompresses the asset
- Asset loader sends to the next asset loader

In example:
I have a "my_image.svg.gz", which I want to be ungzipped, before my svg asset loader takes it.

**Comment by LennysLounge** [comment]
I am also interested in this as right now its not really possible to load an asset package that combines multiple assets into a single file.

The `LoadContext::load_direct` almost does this except it loads the asset from an asset path. We would instead need a way to load an asset from an `AsyncRead` impl instead.

Perhaps an API for this could look like this in `LoadContext`:

```rs
pub async fn load_direct_from_reader<'b>(
    &mut self,
    reader: &'a mut Reader,
    meta_file_reader: Option<&'a mut Reader>,
    path: impl Into<AssetPath<'b>>,
) -> Result<ErasedLoadedAsset, LoadDirectError> {
}
```

**Comment by LoopyAshy** [comment]
I indeed had this exact issue, I'd help implement it if I wasn't so busy but I did want to drop my 2cents that it is a desirable feature.

**Comment by bushrat011899** [comment]
> The `LoadContext::load_direct` almost does this except it loads the asset from an asset path. We would instead need a way to load an asset from an `AsyncRead` impl instead.
> 
> Perhaps an API for this could look like this in `LoadContext`:
> 
> ```rust
> pub async fn load_direct_from_reader<'b>(
>     &mut self,
>     reader: &'a mut Reader,
>     meta_file_reader: Option<&'a mut Reader>,
>     path: impl Into<AssetPath<'b>>,
> ) -> Result<ErasedLoadedAsset, LoadDirectError> {
> }
> ```

I've made a first-attempt PR based on this concept as #10565, good suggestion!

**Comment by simbleau** [comment]
> > The `LoadContext::load_direct` almost does this except it loads the asset from an asset path. We would instead need a way to load an asset from an `AsyncRead` impl instead.
> > Perhaps an API for this could look like this in `LoadContext`:
> > ```rust
> > pub async fn load_direct_from_reader<'b>(
> >     &mut self,
> >     reader: &'a mut Reader,
> >     meta_file_reader: Option<&'a mut Reader>,
> >     path: impl Into<AssetPath<'b>>,
> > ) -> Result<ErasedLoadedAsset, LoadDirectError> {
> > }
> > ```
> 
> I've made a first-attempt PR based on this concept as #10565, good suggestion!

Wow, awesome stuff! I'll be keeping a close eye.
