### ISSUE TITLE
Loading a blender exported gltf file errors with `Unsupported min filter` unless edited.

### ISSUE THREAD

**Issue by expenses** [bevyengine/bevy#1052]
**Bevy version**

3.0

**Operating system & version**

Arch Linux x86_64 5.9.13

**What you did**

If you export a gltf file from blender, it sets the `minFilter` to [one of the mipmap sampling modes](https://github.com/KhronosGroup/glTF/blob/c5740717e9d708b2f7f5087429c6f9704555f43d/specification/2.0/schema/sampler.schema.json#L43-L62), which aren't supported in bevy at the moment.

Seeing as files exported from blender are common, I suggest that instead of erroring, we print a warning and use the equivalent non-mipmap sampling mode instead.

**Additional information**

Here's an example: https://gist.github.com/expenses/2e6e6bcdc4d9b38f4ce82a664fced678. At the moment, bevy won't load this, but if you change the `minFilter` to `9729` the it loads fine.

**Comment by jamadazi** [comment]
This issue should be closed. It was fixed with #1639 , which removed the error, to allow loading the GLTF files (but rendering them without mipmaps for the time being, until #1685 is merged).
