### ISSUE TITLE
Provide option to obtain EventId on EventWriter send()

### ISSUE THREAD

**Issue by dimvoly** [bevyengine/bevy#10532]
## What problem does this solve or what need does it fill?

In my use case I send events and track them with `EventId`. I have a monitoring/managing system that sends out an event, then the receiving system sends back an `EventCompleted` event which contains the original event and the original `EventId`. That way the monitoring/managing system knows which tasks were completed.

## What solution would you like?

Something like this method on the `Event<T>`:

```rust
impl<E: Event> Events<E> {

    pub fn send(&mut self, event: E)
    ...

    /// Same as `.send()` but also provides the corresponding id.
    pub fn send_with_id(&mut self, event: E) -> EventId<E>
    ...
}
```

Optionally some extra documentation on the `pub fn oldest_id(&self) -> usize` to explain that it pertains to `events_a`. I've originally tried calling that function immediately after sending the event and I got the wrong id.

## What alternative(s) have you considered?

Current work around is this:

```rust
// send the event using Events<T>
ui_commands_events.send(new_command.clone());

// find the possible event usize indexes
let event_id_usize_min = ui_commands_events.oldest_id();
let event_id_usize_max = ui_commands_events.oldest_id()
       + ui_commands_events.iter_current_update_events().len();

// iterate from highest to lowest indexes and return the first event that you encounter
let id_range = event_id_usize_min..=event_id_usize_max;
let (_, event_id) = id_range
                .into_iter()
                .rev()
                .find_map(|i| ui_commands_events.get_event(i))
                .expect("Expect event id to be present given that we've just issued it.");
```

## Additional context

I'm using bevy 0.10.1. The new callbacks feature in 0.12 is another workaround, but is a different paradigm to what I'm trying to accomplish.

**Comment by alice-i-cecile** [comment]
I think we can just add the EventId to the return type of `send`.

In 99% of cases this will just get ignored with a semi-colon.
