### ISSUE TITLE
Post processing effect is applied to all cameras

### ISSUE THREAD

**Issue by EmbersArc** [bevyengine/bevy#10541]
## Bevy version

18d001d27ce475388743d9825f2833ce51f5b20d

```
AdapterInfo { name: "NVIDIA GeForce GTX 1650 with Max-Q Design", vendor: 4318, device: 8081, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "545.29.02", backend: Vulkan }
```
## What you did

I tried to add a post-processing effect to my game, based on the `post_processing` example.

## What went wrong

This worked fine, except that it was applied to all cameras. This was confusing, as the example specifically states:

```
        // Add the setting to the camera.
        // This component is also used to determine on which camera to run the post processing effect.
```

To reproduce: 

Modify the `post_processing` example by replacing the camera spawning code with this

```rs
    // camera
    commands.spawn(Camera3dBundle {
        transform: Transform::from_translation(Vec3::new(0.0, 0.0, 5.0))
            .looking_at(Vec3::new(-1.0, 0.0, 0.0), Vec3::Y),
        camera_3d: Camera3d {
            clear_color: ClearColorConfig::None,
            ..default()
        },
        camera: Camera {
            order: 1,
            ..default()
        },
        ..default()
    });
    commands.spawn((
        Camera3dBundle {
            transform: Transform::from_translation(Vec3::new(0.0, 0.0, 5.0))
                .looking_at(Vec3::new(1.0, 0.0, 0.0), Vec3::Y),
            camera_3d: Camera3d {
                clear_color: ClearColorConfig::Default,
                ..default()
            },
            camera: Camera {
                order: 0,
                ..default()
            },
            ..default()
        },
        // Add the setting to the camera.
        // This component is also used to determine on which camera to run the post processing effect.
        PostProcessSettings {
            intensity: 0.02,
            ..default()
        },
    ));
```

This effectively creates two cameras, one rendering on top of the other without a clear color.

![image](https://github.com/bevyengine/bevy/assets/1352472/c89ee553-149a-4d6f-b76e-c78fc13eff33)

This looks fine at first glance, I fully expect the chromatic aberration to be on both cubes (at least I think that should be expected). However, the chromatic aberration on the left cube is twice as strong as on the right, leading me to believe that it is applied twice, even though only one camera has the component.

In my own experiments, I also noticed that all cameras are affected, even those that render to textures.

There is another comment in the example that I don't know how to interpret:

https://github.com/bevyengine/bevy/blob/18d001d27ce475388743d9825f2833ce51f5b20d/examples/shader/post_processing.rs#L131-L134

This sounds like what I want, but I don't know how to actually do this.

**Comment by IceSentry** [comment]
You are absolutely right. I forgot to make sure it only runs on a specific camera when writing the example.

You can add the `PostProcessSettings` component to the ViewQuery and it will correctly only run for that camera.

```rust
    type ViewQuery = (
        &'static ViewTarget,
        // This makes sure the node only runs on cameras with the PostProcessSettings component
        &'static PostProcessSettings,
    );

// ...
// make sure you also modify the run() function
(view_target, _post_process_settings): QueryItem<Self::ViewQuery>,
```
