### ISSUE TITLE
"Unable to find a GPU!" on Android (OpenGL ES 2.0)

### ISSUE THREAD

**Issue by p0ryae** [bevyengine/bevy#10581]
## Bevy version

`v0.12`

## What you did

Compiled, bundled, and signed the example android source-code provided by bevy.

## What went wrong

Running the app throws the following error:
```sh
V/ActivityThread(23064): rust.trs_24 white listed for hwui
E/libEGL  (23064): validate_display:254 error 3008 (EGL_BAD_DISPLAY)
E/Adreno200-EGL(23064): <qeglDrvAPI_eglCreateContext:2189>: EGL_BAD_ATTRIBUTE
I/RustStdoutStderr(23064): thread '<unnamed>' panicked at /home/porya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.0/src/renderer/mod.rs:137:10:
I/RustStdoutStderr(23064): Unable to find a GPU! Make sure you have installed required drivers!
I/RustStdoutStderr(23064): note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
E/RustPanic(23064): Unable to find a GPU! Make sure you have installed required drivers!
```

Error is related to `bevy_render`.
There is a gpu for the android device, however. It is Adreno 200.
Not sure exactly what it means by “installed required drivers”. The error is likely giving that suggestion to non-android platforms.

## Additional information

It doesn't crash the app at all. It stays at a blank screen and throws the error via logcat.

**Comment by p0ryae** [comment]
`bevy_render` depends on wgpu it seems, and the error gets thrown when it gets initialized.

wgpu supports OpenGL ES 3.0 and above. Ardeno 200 series gpus are OpenGL ES 2.0.

Transferred here: https://github.com/gfx-rs/wgpu/issues/4697

**Comment by james7132** [comment]
An Adreno 200 dates back to 2008, and as noted is a shader model that does not support even uniform buffers, which runs up against the most basic design requirements of wgpu and bevy_render. This is likely unactionable on Bevy's end as this falls well below the minimum hardware specs that can be supported.
