### ISSUE TITLE
Demonstrate how to dispatch assets of the same extension to different Rust types

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#10595]
> So @bushrat011899, extending on my proposed use case a bit.
> 
>     1. I have multiple types which should be stored as a .json file.
> 
>     2. I want to parse the json file to determine what Rust type to load this in as, and then add it to a central collection.
> 
> 
> Is that feasible with this PR?

@alice-i-cecile Yes that should be entirely possible:

1. First you'd create a plain JSON `AssetLoader` to give you the parsed contents to inspect.

```rust
// Handle<JsonAsset> implied by .json file extension if
// `JsonAssetLoader` is configured to be default handler of .json
let my_data_json_handle = asset_server.load("data/my_data.json");
```

2. Once loaded, you can then inspect the JSON data for whatever information you'd need to determine the type it *should* be:

```rust
let my_data_json = json_assets.get(&my_data_json_handle)?;

let serde_json::Value::String(magic_token) = my_data_json.get("magic_token")? else {
    return None;
};

// Can re-use the path value for DRY reasons
let path = my_data_json_handle.path().unwrap();

// All match arms need to have the same return type, using UntypedHandle to avoid an enum
let my_data_handle = match magic_token {
    "key_bindings" => asset_server.load::<KeyBindingsAsset>(&path).untyped(),
    "settings" => asset_server.load::<SettingsAsset>(&path).untyped(),
    "scoreboard" => asset_server.load::<ScoreboardAsset>(&path).untyped(),
    _ => my_data_json_handle.untyped(),
};

Some(my_data_handle)
```

I imagine you'd want an `enum` for the central collection, and that would probably be the type of `my_data_handle` in the above `match` statement instead of using `UntypedHandle`'s. Additionally, this behaviour is extended to the `LoadContext::load` method, so you could put all of this functionality into a custom `AssetLoader` if the `load_with_reader` method @nicopap suggested in #10565 was added (would need another PR to add).

_Originally posted by @bushrat011899 in https://github.com/bevyengine/bevy/issues/10153#issuecomment-1815361605_

**Comment by torsteingrindvik** [comment]
I tried asking a similar question here: https://github.com/bevyengine/bevy/issues/9714#issuecomment-1773733884

My TL;DR is I wish I could just

```rust
let handle: Handle<Foo> = asset_server.load("data/foo.json");
let handle: Handle<Bar> = asset_server.load("data/bar.json");
```

**Comment by bushrat011899** [comment]
> I tried asking a similar question here: https://github.com/bevyengine/bevy/issues/9714#issuecomment-1773733884
> 
> My TL;DR is I wish I could just
> 
> ```rust
> let handle_foo: Handle<Foo> = asset_server.load("data/foo.json");
> let handle_bar: Handle<Bar> = asset_server.load("data/bar.json");
> ```

@torsteingrindvik with #10153, you *will* be able to do this!

**Comment by torsteingrindvik** [comment]
I am doing extensionless mapped to lots of types now so I'm not actively using e.g. json-to-many myself but recent PRs and tests added by @bushrat011899  means this can be closed I think
