### ISSUE TITLE
AssetSourceId::Name(embedded) does not have an AssetWatcher configured. Consider enabling the `file_watcher` feature.

### ISSUE THREAD

**Issue by stepancheg** [bevyengine/bevy#10602]
## Bevy version

0.12.0

## What you did

My program prints at start:

```
2023-11-17T00:16:11.164907Z  WARN bevy_asset::io::source: AssetSourceId::Name(embedded) does not have an AssetWatcher configured. Consider enabling the `file_watcher` feature. Note that Web and Android do not currently support watching assets.
```

But I have `file_watcher` feature enabled.

If I enable `embedded_watcher` feature, this warning disappears.

So I guess it is error message which needs to be fixed.

I'm sorry, I don't have small repro (I have no idea what triggers it), issue appeared after upgrade to 0.12.0.

**Comment by 5tr1k3r** [comment]
Must be this https://github.com/bevyengine/bevy/issues/10401

**Comment by ItsDoot** [comment]
Duplicate of #10401 as mentioned above.
