### ISSUE TITLE
Bevy panics if started from a read-only directory without an assets folder

### ISSUE THREAD

**Issue by tripokey** [bevyengine/bevy#10613]
## Bevy version

0.12

## Relevant system information

Reproducible under both Windows and Linux.
 
## What you did

Providing a minimal example application here:

```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run()
}
```

1. Compile the above code in release mode
2. Copy the executable to some folder that does not contain an `assets` subfolder and make that folder read-only.
3. Start the application from that folder.

## What went wrong

The application panics when it attempt to create an assets folder in the read-only directory.

```text
thread 'main' panicked at /home/tripokey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.0/src/io/file/mod.rs:48:13:
Failed to create root directory "/home/tripokey/projects/bevy_asset_issue_poc/testing/assets" for file asset reader: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When using bevy as a backend for an application without any assets and installing this application to some system folder it would be desirable if it did not panic upon not being able to create the `assets` folder.

## Additional information

A possible workaround for this problem could be to create an empty assets folder in the read-only directory.

**Comment by alice-i-cecile** [comment]
The other workaround I would suggest is disabling default features for these applications, and being sure that `bevy_assets` is off.

That said, we should fail gracefully here instead.

**Comment by tripokey** [comment]
@alice-i-cecile Would embedded assets still work with `bevy_assets` disabled?

**Comment by alice-i-cecile** [comment]
Hmm, good question. Probably not!
