### ISSUE TITLE
Add a set of standard clippy lints

### ISSUE THREAD

**Issue by Kanabenki** [bevyengine/bevy#10612]
## What problem does this solve or what need does it fill?

There's currently no project-level clippy lints defined.

## What solution would you like?

Once #10011 is merged, we could expand the `Cargo.toml` lint table with a set of clippy lints we want to uphold through the codebase. Something we could use as inspiration is the [set of clippy used in Embark projects](https://github.com/EmbarkStudios/rust-ecosystem/blob/main/lints.rs). While some lints in it are probably too restrictive/opinionated, we could filter it and possibly check for additional lints that might fit the codebase in the [full lint list](https://rust-lang.github.io/rust-clippy/master/).

 We could then remove the few clippy warnings [currently checked in CI](https://github.com/bevyengine/bevy/blob/bc9e159b2659435c4ca39eebd9b97396486161c2/tools/ci/src/main.rs#L20), since they would be picked up from the lint table. This could be done over the course of several PRs since the resulting diff might be large.

## What alternative(s) have you considered?

-  Keep the current setup as-is.
- Just move the lints checked in CI to `Cargo.toml`.

**Comment by alice-i-cecile** [comment]
For an initial PR, I'd like to do only those CI warnings we currently use.

Then, add one lint at a time in their own PRs. That will ensure each can be evaluated on its own, and reduce time-to-merge.

**Comment by Kanabenki** [comment]
It could maybe be worth it to also add a `.git-blame-ignore-revs` to ignore clippy-related changes in the git blame (Github picks it up), since those might generated large diffs over time? Thought that would require merging the relevant PRs without squashing (or additional PRs just for that).

**Comment by alice-i-cecile** [comment]
I think that's probably more complexity in the workflow than it's worth. Because this is a FOSS project with a huge range of contributors, we try to keep our project config and workflows simple where we can :)

**Comment by james7132** [comment]
What are the remaining items that aren't addressed on this issue?

**Comment by alice-i-cecile** [comment]
Going to close as completed: new lints should have their own issues and PRs :)
