### ISSUE TITLE
Added<T> skips one system run

### ISSUE THREAD

**Issue by stepancheg** [bevyengine/bevy#10625]
## Bevy version

0.12.0

## What you did

Two systems, `test1` and `test2`. `test2` is scheduled after `test1`.

`test1`:
* on first iteration ("0") creates an entity with component `MyC`
* on second iteration ("1") does nothing
* on third iteration ("2") modifies component `MyC` of previously created entity

`test2` prints the number of entities "changes" and "added".

```rust
fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Update, (test1, test2.after(test1)))
        .run();
}

#[derive(Component, Debug)]
struct MyC;

fn test1(mut local: Local<u32>, mut q: Query<&mut MyC>, mut commands: Commands) {
    if *local == 0 {
        println!("{} spawning", *local);
        commands.spawn((MyC,));
    } else if *local % 2 == 0 {
        println!("{} changing", *local);
        for mut c in q.iter_mut() {
            *c = MyC;
        }
    } else {
        println!("{} not changing", *local);
    }
    *local += 1;
}

fn test2(
    changed: Query<&MyC, Changed<MyC>>,
    added: Query<&MyC, Added<MyC>>,
) {
    println!("changed: {}", changed.iter().count());
    println!("added: {}", added.iter().count());
}
```

## What went wrong

Program outpus:

```
0 spawning
changed: 0
added: 0
1 not changing
changed: 1
added: 1
2 changing
changed: 1
added: 0

```

Which means:
* for actual changes (step "2") `Changed` is emitted immediately correctly
* for spawned entities (step "0") both `Changed` and `Added` **skip one system run**, they are emitted on the next run (step "1")

## Expected

Step "0" should print the component was both changed and added.

Or current behaviour should be at least documented.

**Comment by s-lambert** [comment]
This happens because commands aren't applied immediately, they're queued up to be run later on. [The documentation on Commands](https://docs.rs/bevy/latest/bevy/prelude/struct.Commands.html) mentions that it's a queue and won't actually do anything until `apply_deferred` is run. So what's actually happening is:
``` 
1st iteration:
system1 runs
system2 runs
apply_deferred runs (this is where the entity is actually added)
2nd iteration:
...
system2 runs, now has Added entity from the 1st iteration
```

If you change the systems to `(system1, apply_deferred, system2).chain()` then it'll print what you expect:
``` 
0 spawning
changed: 1
added: 1
1 not changing
changed: 0
added: 0
```

**Comment by DasLixou** [comment]
There is already a Try to automatically make sync points for these scenarios: #9822
