### ISSUE TITLE
Improve documentation for the bevy crates

### ISSUE THREAD

**Issue by ItsSunnyMonster** [bevyengine/bevy#10639]
A lot of the bevy crates lack documentation or have documentation that does not cover everything. For example, the [bevy_ecs documentation](https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/README.md) does not say what the features like `multi-threaded` or `trace` precisely does. I understand that there are a lot of these crates, but I think the most downloaded crates should be prioritised.

**Comment by alice-i-cecile** [comment]
I agree, but this is hard to take action on its current form. For example, when would this be "completed"? How would a new contributor know where to start?

Going to close this out, but please feel free to make new issues for specific problems with missing or inadequate docs so we can track this. For example, documenting what all of the features do would be a great choice.
