### ISSUE TITLE
Re-export winit::platform::android::activity::* in bevy_winit

### ISSUE THREAD

**Issue by Litttlefish** [bevyengine/bevy#10630]
## What problem does this solve or what need does it fill?

I want to set a fullscreen flag in my android game, but since the bevy_winit didn't re-export it, I can't set it.

code like this
```
    #[cfg(target_os = "android")]
    {
        use bevy::winit::platform::android::activity::WindowManagerFlags;
        let android_app = bevy::winit::ANDROID_APP
            .get()
            .expect("Bevy must be set up with the #[bevy_main] macro on Android");
        android_app.set_window_flags(
            WindowManagerFlags::FULLSCREEN,
            WindowManagerFlags::FORCE_NOT_FULLSCREEN,
        );
    }
```
will simply give a compile error.

## What solution would you like?

Just add a pub use in bevy_winit crate I think.

## What alternative(s) have you considered?

no for now

## Additional context

At first I want to simply re-export winit::platform::android::activity::WindowManagerFlags, but I think maybe others need more than this.

**Comment by alice-i-cecile** [comment]
As a workaround, you should be able to depend directly on `winit` and use their type, as long as the version matches.

That said, we do tend to re-export these. This particular one should be gated on an `android` feature flag though :)

**Comment by Litttlefish** [comment]
Ok, my temporary workaround for now is adding android-activity 0.4.3 in cargo.toml then use it directly in code, usable for now

**Comment by hecksmosis** [comment]
I'll do this
