### ISSUE TITLE
Incorrect window size obtained from `WindowResolution` in version 0.12

### ISSUE THREAD

**Issue by wgxh-cli** [bevyengine/bevy#10642]
## Bevy version

latest(0.12)

## What you did

I'm a archlinux and tiling window manager user, also used to coding in neovim.

To reproduce, just write the following program and run it:

```rust
// main.rs

use bevy::prelude::*;
use bevy::window::PrimaryWindow;

fn init_system(
  window: Query<&mut Window, With<PrimaryWindow>>,
) {
  let window = window.single_mut();
  let size = Vec2::new(window.width(), window.height());
  println!("Size: {}", size);
  window.set_cursor_position(Some(size / 2.0));
}

fn main() {
  App::new()
    .add_plugins(DefaultPlugins)
    .add_systems(Startup, init_system)
    .run()
}
```

## What went wrong

Expected:
1. Correct input in terminal to report the window size.
Since the bevy window split in half the **1920 * 1080** screen, so the correct size must be that divided by 2.

2. The cursor should be at the center of the window.
As the `window.set_cursor_position(Some(size / 2)` showed.

That was what I expected but in newer version bevy, I get these:

1. In terminal I got the size of 1280 * 720
Notice that `1280 * 720` is the **default value** in [window.rs](https://github.com/bevyengine/bevy/blob/main/crates/bevy_window/src/window.rs#L603C34-L603C34)

2. Since that I got incorrect cursor position in my window.

That is very strange because the same program act normally in 0.11.3 bevy, that I find out.

## Additional information

Before running this program I executed `sudo pacman -Syu` in my archlinux system.
That is to say, I already have the latest system environment.

I chose `wezterm` as my default terminal, and `bash` as my main shell.

In my project, I have `dynamic_linking` feature enabled, and naturally, have `resolver = "2"` in `[workspace]` entry.

Can anyone give me a help hand? Thanks a lot!

**Comment by mockersf** [comment]
this is probably the same issue as #10407 
for the first run of your systems, the window size / scale is not updated with the actual window but has the default values

**Comment by wgxh-cli** [comment]
Thanks! I solved that, close this soon.
