### ISSUE TITLE
Left mouse button input delay on macOS 14.1

### ISSUE THREAD

**Issue by JeanMertz** [bevyengine/bevy#10658]
## Bevy version

https://github.com/bevyengine/bevy/commit/83a358bf3396368a1778bab5e34ec828aa261168

## What you did

Running the `mouse_grab` example in this repository shows a noticeable delay (a few 100ms or so) between when I click the LMB (using an external, Logitech bluetooth mouse) and when the cursor is hidden (as per the [example code](https://github.com/bevyengine/bevy/blob/83a358bf3396368a1778bab5e34ec828aa261168/examples/input/mouse_grab.rs#L22)).

When I change the example to use `MouseButton::Right` (or anything other than `Left`), the delay is gone.

I initially [reported this](https://github.com/aevyrie/bevy_mod_picking/issues/283) in the `bevy_mod_pickings` plugin, as that's where I initially encountered the delay, but while digging deeper, I realized this happened in stock Bevy systems as well, and then noticed there was actually an existing example that shows the same behavior.

**Comment by Adamkob12** [comment]
Do you have a macOS plugin called Magnet? 
If so, try quitting it and see if the problem goes away.

**Comment by JeanMertz** [comment]
@Adamkob12 holy hell. I do, and it is indeed the cause of this issue. I would have never connected the dots (and I shouldn't have to, this is clearly a bug on their end).

I'll let them know, and I apologize for causing any unnecessary work here.

**Comment by JeanMertz** [comment]
For future reference, here are related reports, also pointing to Magnet.app (and also BetterTouchTool.app):

https://github.com/bevyengine/bevy/issues/5778
https://github.com/bevyengine/bevy/issues/6075

**Comment by Adamkob12** [comment]
@JeanMertz glad to help. I was tearing my hair out for two days over same issue.
