### ISSUE TITLE
Touch input is off on Y axis on WASM export

### ISSUE THREAD

**Issue by jaminhaber** [bevyengine/bevy#10694]
## Bevy version

```toml
[dependencies]
bevy = "0.12.0"
bevy_embedded_assets = "0.9.1"
rand = "0.8.5"
wasm-bindgen = "0.2.88"
```

## Relevant system information

- the Rust version you're using (you can get this by running `cargo --version`)
  - `cargo 1.73.0 (9c4383fb5 2023-08-26)`
- the operating system or browser used, including its version
  - `MacOS Sonoma 14.1.1 (23B81)`
- Browser: Chrome

## What you did

I get the position of a touch like this:
```rust
 let just_pressed = touches.iter().find(|t| touches.just_pressed(t.id()));
 let touch_pos =  just_pressed.unwrap().position();
 println!("touch at ({},{})", touch_pos.x, touch_pos.y);
  ```

then build using this script
```bash
APP_NAME="sokoban"
cargo build --release --target wasm32-unknown-unknown
wasm-bindgen --out-dir 'out/webgl' --target web "target/wasm32-unknown-unknown/release/${APP_NAME}.wasm"
open "out/webgl"
```

## What went wrong

touching the top right of the screen (640x480) produces the coordinates (19,218)

You can experience this by trying to press the buttons on the [live version of the game on my website](https://www.benjaminhaber.com/games/sokoban) while using the mobile emulator for chrome.... You will have to tap about half way up the screen in order to press the buttons on the menus.

## Additional information

<img width="143" alt="image" src="https://github.com/bevyengine/bevy/assets/2616400/37d81c2b-39d1-42f1-9884-5d84c83b93e4">

The coordinates are off by about half the screen height, maybe it has to do with the grid originating from the middle of the screen rather than the top?

<img width="384" alt="Screenshot 2023-11-22 at 12 45 22 PM" src="https://github.com/bevyengine/bevy/assets/2616400/d49ae934-c829-4a64-8477-4935fbb5b1fe">

**Comment by daxpedda** [comment]
This was probably fixed way back in https://github.com/rust-windowing/winit/pull/2704.
Cc https://github.com/bevyengine/bevy/pull/8745.

**Comment by jaminhaber** [comment]
@daxpedda Is that fix included in the packages listed in the report? if not, how can i update to get that?

**Comment by daxpedda** [comment]
It's part of Winit 0.29.
If you are using Bevy you can try #10702.

**Comment by jaminhaber** [comment]
@daxpedda will this be merged into bevy main? I can wait until then

**Comment by daxpedda** [comment]
I was just commenting because I help maintain Winit. I'm not a contributor/maintainer/member of Bevy!

**Comment by Vrixyz** [comment]
> @daxpedda will this be merged into bevy main? I can wait until then

Hey, I hope so! I believe https://github.com/bevyengine/bevy/pull/10702 is nearing completion.

I've got 2 items on my todo, which should not impact API usage, I'm very interested in having more fresh-eyes reviews :)
