### ISSUE TITLE
Some examples freeze after launch on macos. 

### ISSUE THREAD

**Issue by warycat** [bevyengine/bevy#107]
```
cargo run --example ui
```

**Comment by tbillington** [comment]
`ui` works on my mac, when I resize the window I can see it re-rendering.

**Comment by warycat** [comment]
I switch to stable rust. The cpu is not running crazy in this time. The examples will be better if they respond to user interaction.

**Comment by StarArawn** [comment]
The `ui` example works well for me too. I do agree I was initially confused by the ui example as it doesn't show any interactivity. I think it's mainly meant to showcase the rendering aspects of `bevy_ui`.

**Comment by Moxinilian** [comment]
I'm closing this, as it seems to be expected behaviour.
