### ISSUE TITLE
UI outline offset calculated incorrectly

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#10727]
## Bevy version

0.12.0

## What you did

Setting `Outline.offset` has no effect - however setting `Outline.width` affects both offset and outline.

The 'outline_offset' appears to be using `outline.width` instead of `outline.offset`. You can see the code here:

https://github.com/bevyengine/bevy/blob/1065028154b1a2b3b28cf137bb391fbba41328ce/crates/bevy_ui/src/layout/mod.rs#L412

## What went wrong

Looks like a simple typo. It should be using '.offset' instead of '.width'.

**Comment by ickshonpe** [comment]
Argh so embarrassing to miss something stupid like this. I wrote a few implementations, a third party plugin, one for the border radius PR, and a few for experimental forks of 0.11 and 0.12 with lots of rendering changes, and just the one I upstreamed to bevy has this bug. IIRC I just added some outlines to the borders example with offset and width set to 5 pixels, which worked of course, and assumed it was good :sweat:
