### ISSUE TITLE
Pixelated text font is blurry

### ISSUE THREAD

**Issue by Adar-Dagan** [bevyengine/bevy#10720]
## Bevy version

0.12.0

## \[Optional\] Relevant system information

AdapterInfo { name: "NVIDIA GeForce MX150", vendor: 4318, device: 7440, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "535.129.03", backend: Vulkan }

## What you did

I am trying to display text in the [joystix font](https://www.1001freefonts.com/joystix.font).

## What went wrong

The font is rendered blurry.

## Additional information

To show this I wrote this short example that renders the text using the font under a png of how it should look:

```
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(ImagePlugin::default_nearest()))
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    let mut camera = Camera2dBundle::default();
    camera.projection.scale = 0.5;
    commands.spawn(camera);

    commands.spawn(Text2dBundle {
        text: Text::from_section(
            "Ready!",
            TextStyle {
                font: asset_server.load("joystix.ttf"),
                font_size: 11.0,
                color: Color::YELLOW,
            },
        ),
        ..default()
    });

    commands.spawn(SpriteBundle {
        texture: asset_server.load("ready.png"),
        transform: Transform::from_xyz(0.0, 10.0, 0.0),
        ..default()
    });
}
```

This generates the following screenshot:
![blurry_text](https://github.com/bevyengine/bevy/assets/101581112/50a5415d-3470-4a57-8f3d-9dcd319938dc)

The png I used for the image:
![ready](https://github.com/bevyengine/bevy/assets/101581112/f4f7921c-4cef-4028-900e-d27cadb4c50c)
And the ttf file of the font is from [here](https://www.1001freefonts.com/joystix.font).

**Comment by nicopap** [comment]
Have you tried using the git version of bevy? I think this is fixed in #10537

**Comment by Adar-Dagan** [comment]
I just tried running the same code with the git version and I get the same issue:
![Screenshot from 2023-11-24 11-08-28](https://github.com/bevyengine/bevy/assets/101581112/8e6ea373-7c79-45b3-a501-99d001af9ce2)

**Comment by ickshonpe** [comment]
I'll just quickly try and see if I can fix your example so it renders correctly.

**Comment by nicoburns** [comment]
> This is a separate problem with Text2d, the text can be transformed arbitrarily so you can't just snap it to a pixel aligned position like with UI text

Presumably we could pixel align Text2d, we'd just need to do so after all transforms have been applied (an approach which I think would also solve some of the residual rounding issues we've had with UI). And I suspect that at the moment, the rendering system doesn't even know it's text at that point.

**Comment by aoidenpa** [comment]
I'm making a pixel art game and zooming on a small area. I want to just draw everything to that area, including UI. Text2d is working but as others have pointed out, it becomes blurry. Working in the window level is a bit painful in my case.

**Comment by musjj** [comment]
I'm also having this issue with *some* pixel art fonts. Most fonts work just fine when you specify the size as indicated by the font maker, but some require using a different size and some just doesn't work at all (it stays blurry).

For example: https://github.com/itouhiro/PixelMplus/releases

The `PixelMplus10` variant is only sharp when you set `font_size: 11.0`, even though it's supposed to be 10px font. The `PixelMplus10` on the other hand stays blurry at all sizes I've tried.

I wonder what's causing this to happen?

**Comment by rparrett** [comment]
With Bevy `main` / `cosmic-text`. Better...

<img width="663" alt="image" src="https://github.com/user-attachments/assets/17bd0fe6-57b1-4db5-bdbf-5bfb178a8a3b">

This cosmic-text issue may be relevant: https://github.com/pop-os/cosmic-text/issues/279

**Comment by coreh** [comment]
With #15368:

<img width="424" alt="image" src="https://github.com/user-attachments/assets/63238a29-8cf2-4461-8141-7b7853357c60">

```rust
use bevy::prelude::*;
use bevy::{color::palettes::css::YELLOW, text::FontSmoothing};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(ImagePlugin::default_nearest()))
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    let mut camera = Camera2dBundle::default();
    camera.msaa = Msaa::Off;
    commands.spawn(camera);

    commands.spawn(Text2dBundle {
        text: Text::from_section(
            "Ready!",
            TextStyle {
                font: asset_server.load("joystix.ttf"),
                font_size: 11.0,
                color: YELLOW.into(),
            },
        )
        .with_font_smoothing(FontSmoothing::None),
        ..default()
    });

    commands.spawn(SpriteBundle {
        texture: asset_server.load("ready.png"),
        transform: Transform::from_xyz(0.0, 10.0, 0.0),
        ..default()
    });
}
```
