### ISSUE TITLE
Add `app.add_state(inital_state)` convenience method

### ISSUE THREAD

**Issue by honungsburk** [bevyengine/bevy#10731]
## What problem does this solve or what need does it fill?

I want to initialize a state to an arbitrary state, not just default.

Right now I am using ``app.add_state::<MyState>()``

## What solution would you like?

Add a convenience method `app.add_state(MyState::MyArbitraryState)` to `App`

## What alternative(s) have you considered?

I read through the motivation for the [new state system](https://bevyengine.org/news/bevy-0-10/#simpler-states) but it doesn't mention why only the default trait is used for initialization. This seems like a clear win to me so I would be surprised at any objections.

**Comment by honungsburk** [comment]
I tried out this idea in my own game and it works great:

```rust
use bevy::ecs::schedule::common_conditions::run_once as run_once_condition;
use bevy::ecs::schedule::run_enter_schedule;
use bevy::prelude::*;

pub trait AppExtension {
    fn init_state<S: States>(&mut self, initial_state: S) -> &mut Self;
}

impl AppExtension for App {
    // Remove when [add_state is added](https://github.com/bevyengine/bevy/issues/10731)
    fn init_state<S: States>(&mut self, initial_state: S) -> &mut Self {
        self.insert_resource::<State<S>>(State::new(initial_state))
            .init_resource::<NextState<S>>()
            .add_systems(
                StateTransition,
                (
                    run_enter_schedule::<S>.run_if(run_once_condition()),
                    apply_state_transition::<S>,
                )
                    .chain(),
            );

        // The OnEnter, OnExit, and OnTransition schedules are lazily initialized
        // (i.e. when the first system is added to them), and World::try_run_schedule is used to fail
        // gracefully if they aren't present.
        self
    }
}
```

**Comment by honungsburk** [comment]
If someone gives the greenlight I'll happily create PR 😄

**Comment by roboteng** [comment]
I've done something a little different in my projects before. I'm not sure if its any better, but its another option.

```rust
pub struct BasePlugin(GameState);
impl Plugin for BasePlugin {
    fn build(&self, app: &mut App) {
        app.add_state::<GameState>();

        app.world
            .get_resource_mut::<NextState<GameState>>()
            .unwrap()
            .set(self.0);
   }
}
```

I just copied this from my project, but I don't think it'd be hard to change this to a method on `App` just like `add_state`

Is this any better/worse?

**Comment by doonv** [comment]
How about we split the `add_state` method into two methods: `init_state<T: State>()` and `insert_state<T: State>(state: T)`. `init_state` would work like `add_state`, and `insert_state` will initialize the state to the state you pass in.

The names are inspired by the `init_resource` and `insert_resource` methods.
