### ISSUE TITLE
Re-export serde

### ISSUE THREAD

**Issue by torsteingrindvik** [bevyengine/bevy#10760]
## What problem does this solve or what need does it fill?

Similar in spirit to the re-export of RON: https://github.com/bevyengine/bevy/issues/10504

If using custom assets, it's very likely a user will want to be able to do things like deriving serialize/deserialize on their own assets.

## What solution would you like?

Re-export serde.

## What alternative(s) have you considered?

Having serde as a separate dependency.

The main reason I'm not just putting up a PR is that I'm curious if anyone can think of downsides to re-exporting?

**Comment by alice-i-cecile** [comment]
It'll make it a bit less clear where it's coming from.

And if we ever want to move away from serde, it'll be very confusing for interop to suddenly and implicitly break because now we're using `bevy_reflect::Serialize` rather than `serde::Serialize`.

**Comment by torsteingrindvik** [comment]
Since opening this I've started using reflection- I didn't know that by deriving reflect I don't need serde.

If anyone sees this some pointers are the reflection example: https://github.com/bevyengine/bevy/blob/main/examples/reflection/reflection.rs#L84

This can be tied into a RON asset loader for a powerful combo.
