### ISSUE TITLE
Deprecate Query::for_each_unchecked_manual

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#10772]
Should we deprecate this function too?

_Originally posted by @JoJoJet in https://github.com/bevyengine/bevy/pull/6773#discussion_r1405553819_

**Comment by alice-i-cecile** [comment]
Just follow the pattern in the linked PR :)

**Comment by hecksmosis** [comment]
I'll work on this

**Comment by hecksmosis** [comment]
This is no longer an issue as Query::for_each_unchecked_manual has been removed I believe

**Comment by torsteingrindvik** [comment]
Yes- removed in https://github.com/bevyengine/bevy/commit/2148518758aaae30a2f04a5758cda5bf7c9154ca
