### ISSUE TITLE
Rendering issues on iOS bevy

### ISSUE THREAD

**Issue by enfipy** [bevyengine/bevy#1077]
**Bevy version**

Right after this commit - https://github.com/bevyengine/bevy/commit/509b138e8fa3ea250393de40c33cc857c72134d3 -iOS rendering started to fail.

**Operating system & version**

Tested on iOS 14 and on the simulator on Mac 10.14.

**What you did**

Tried to spawn SpriteBundle/gltf scene ([2d example](https://github.com/creator-rs/creator/tree/master/examples/2d) with working audio but with image rendering issue).

**What you expected to happen**

Image and gltf scenes render successfully as it was before this commit https://github.com/bevyengine/bevy/commit/509b138e8fa3ea250393de40c33cc857c72134d3 (for example with this commit everything works fine: https://github.com/bevyengine/bevy/commit/61b181a699ed2b450bebc8c14d96c6af55fa41cf).

**Additional information**

I'm pretty sure that something wrong with rendering changes but it's weird that it renders perfectly on Android, Windows, and Mac. I couldn't find any ios specific code that could break render.

**Comment by james7132** [comment]
Can you reproduce this in a more recent version of Bevy?

**Comment by enfipy** [comment]
We were able to build bevy on iOS on `bevy v0.8`. I close this issue.
