### ISSUE TITLE
Clarify `Commands`' purpose

### ISSUE THREAD

**Issue by Nilirad** [bevyengine/bevy#10805]
Currently, API docs state that `Commands` are for "impactful changes". However, recent discussions on #10756 made it clear that "structural changes" is a more appropriate and specific term.

The file to modify is found in `crates/bevy_ecs/src/system/commands/mod.rs`.

**Comment by xNapha** [comment]
Hello there!
First time contributing to an open-sourced project, so i decided to take this easy issue.
Let me know if I should have added more details or not

**Comment by Nilirad** [comment]
For me it is ok as it is. Thank you 👍

**Comment by doonv** [comment]
This issue should be closed as https://github.com/bevyengine/bevy/pull/10837 was merged.
