### ISSUE TITLE
API to retain bundle components on entities

### ISSUE THREAD

**Issue by iiYese** [bevyengine/bevy#10865]
## What problem does this solve or what need does it fill?

Sometimes we want to remove all components except for a select few from an entity. One use case I've encountered this for is when trying to do events as entities. I want to remove/rest all the data from event entities while keeping the `Event` markers that annotates the entity is an event entity. This comes up for less experimental use cases too.

## What solution would you like?

A `fn retain<T: Bundle>(&mut self) -> &mut Self` API for `EntityWorldMut` & `EntityCommands`.

## What alternative(s) have you considered?

```rust
let components = world.entity(e).take::<B>().unwrap();
world.despawn(e);
world.get_or_spawn(e).insert(components);
```
This will only work if the entity has all of the components in `B`. The `retain` API should work regardless of if all components in `B` are present.

**Comment by alice-i-cecile** [comment]
Something critical to document: you can pass in `()` as the Bundle type, and all components will be removed.
