### ISSUE TITLE
EventReader<MouseMotion> behaves oddly with 0.12.1

### ISSUE THREAD

**Issue by miketwenty1** [bevyengine/bevy#10860]
## Bevy version
0.12.1

video example of event deltas acting up and somehow it seems a new event is influenced by a previous event.
https://github.com/bevyengine/bevy/assets/7761473/7413b9ea-c952-49fd-a6ce-cf6397c9e382

To give an idea on how I'm accessing the event. Only when the mouse is pressed.
```rust
if mouse.pressed(mouse.pressed(MouseButton::Left) {
  //...
  for event in mouse_motion_events.read() {
    //...
```
## What you did

taking the events delta.x and delta.y I'm able to move around seemlessly. But after a release and another click I get inconsistent results. And If I try to move around quickly I'll snap back to the previous position. 

This doesn't happen at all with 0.12.0.

A work around is pointing bevy and bevy_ecs to 0.12.0.

**Comment by devil-ira** [comment]
The issue is that you need to read or clear the event reader to mark events as read, so they won't show up in the reader the next time the system runs.
Not doing this didn't cause very noticeable issues before because events only stuck around for two frames but with 0.12.1 unread events can stick around for dozens of frames.

**Comment by miketwenty1** [comment]
fwiw changing the loop to be like this instead where im just simply reading every event fixed most of my issues.

```rust
for event in mouse_motion_events.read() {
  //...
  if mouse.pressed(mouse.pressed(MouseButton::Left) {
    //...
```

**Comment by devil-ira** [comment]
Working as intended. It might be improved upon in the future by clearing events automatically.

Your original code should work if you add an unconditional call to clear after the if statement.
