### ISSUE TITLE
use of undeclared type `Camera2dBundle` (and `CameraUiBundle`)

### ISSUE THREAD

**Issue by biot023** [bevyengine/bevy#1087]
Hi -- I'm trying to basically draw something to the window and am pasting over code from the 'breakout' example to try to achieve this.
However, when I try this:

```rust
commands
    .spawn(Camera2dBundle::default())
    .spawn(CameraUiBundle::default())
```

I get this error:

```bash
[Running 'cargo check']                                                   
    Checking cells v0.1.0 (/home/mycomputer/work/home/rust/bevy/cells)   
error[E0433]: failed to resolve: use of undeclared type `Camera2dBundle`  
  --> src/main.rs:92:16                                                   
   |                                                                      
92 |         .spawn(Camera2dBundle::default())                            
   |                ^^^^^^^^^^^^^^ use of undeclared type `Camera2dBundle`
                                                                          
error[E0433]: failed to resolve: use of undeclared type `CameraUiBundle`  
  --> src/main.rs:93:16                                                   
   |                                                                      
93 |         .spawn(CameraUiBundle::default());                           
   |                ^^^^^^^^^^^^^^ use of undeclared type `CameraUiBundle`
                                                                          
```

I'm trying to work out how to `use` those structs but I'm failing so far -- any advice would be greatly appreciated!
Cheers,
   Doug.

**Comment by mockersf** [comment]
you should `use bevy::prelude::*;`, this will import most of the things you'll need to use bevy 👍

**Comment by biot023** [comment]
Cheers -- I should've made it clear in my snippet but I have that at the top of the code.
I also tried `use bevy_render::prelude::*` and all sorts of variations on that theme, too -- all to no avail.
I suspect this might be some Cargo black magic in the `bevy` repo. I've tried pasting over relevant-looking bits to my own Cargo.toml but nothing has worked, so far.

**Comment by KirmesBude** [comment]
What version of bevy are you using? 
In 0.3 those are still called Camera2dComponents/UiCameraComponents instead of *Bundle. 
https://docs.rs/bevy/0.3.0/bevy/prelude/struct.UiCameraComponents.html
https://docs.rs/bevy/0.3.0/bevy/prelude/struct.Camera2dComponents.html

**Comment by biot023** [comment]
Ah-ha! That'll be it -- thank you!
So would you recommend using the latest git commit, generally?
I'm pulling out bits of the examples so maybe that would be best.
And thanks again, man, that's really a massive help.
   Doug.

**Comment by lorr756** [comment]
___  .Is•+@94"
S se s tdr p d hque de
Cv4@0T sa eYxz  de de enx

LT  ****fotki
kbo********3g
Orla
:
Swso9dsx was ssj

**Comment by lorr756** [comment]
Se vm DK

**Comment by memoryruins** [comment]
> So would you recommend using the latest git commit, generally?

Use whichever examples that align with the version or git commit specified in your `Cargo.toml`.
For `0.3`, there is a git tag with a similar name https://github.com/bevyengine/bevy/tree/v0.3.0/examples.

Additional instructions are in the examples readme,
https://github.com/bevyengine/bevy/tree/master/examples#%EF%B8%8F-note-for-users-of-releases-on-cratesio.

Note: `0.4` will likely release sometime later today :)

**Comment by biot023** [comment]
Think I'll be jumping to 0.4 then -- cheers again!
