### ISSUE TITLE
`.chain` should be not applicable to arbitrary `SystemConfigs`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#10880]
I think `.chain` should be not applicable to arbitrary `SystemConfigs`. For two reasons:

* either it is zero or single item and chain makes little sense
* or `SystemConfigs` represent a set of systems configured properly, which are not meant to be chained by some library code which returned `SystemConfigs`

Instead, I believe, implementation should be `IntoChain` trait which is only implemented for tuples:

```
impl IntoChain {
  fn chain(self) -> SystemConfigs;
}

impl<A, B> Chain for (A, B)
where A: IntoSystemConfigs, B: IntoSystemConfigs
{ ... }

impl<A, B, C> Chain for (A, B, C)
where A: IntoSystemConfigs, B: IntoSystemConfigs, C: IntoSystemConfigs
{ ... }

// ...
```

_Originally posted by @stepancheg in https://github.com/bevyengine/bevy/issues/10858#issuecomment-1837794082_

**Comment by JoJoJet** [comment]
I think this would mean you'd have to call `.chain()` before anything else. `(A, B).run_if(...).chain()` would break.

**Comment by alice-i-cecile** [comment]
Right: I don't see any way around that. That's a big enough ergonomic hit that this isn't worth doing IMO.

**Comment by stepancheg** [comment]
> `(A, B).run_if(...).chain()` would break

which is probably a good thing that it breaks. Because it is very not obvious what this thing does.

It is not unreasonable to assume that last `chain` is no-op (that is what I would expect).

**Comment by JoJoJet** [comment]
I think it would be fine to forbid `(A,B).run_if().chain()` *if* there was a good error message that told users the proper way of doing it. However we don't have custom error messages in Rust so I think this would just cause more confusion.

**Comment by stepancheg** [comment]
> if there was a good error message that told users the proper way of doing it

Implement `chain` on `SystemConfigs` (directly, without trait). Make it permanently deprecated, panic at runtime.
