### ISSUE TITLE
bevy_ui build error

### ISSUE THREAD

**Issue by martinellison** [bevyengine/bevy#10890]
## Bevy version

`bevy = { version = "0.11", features = ["dynamic_linking"] }`

## Relevant system information

`cargo 1.76.0-nightly (9b13310ca 2023-11-24)` or `cargo 1.74.0 (ecb9851af 2023-10-18)`

`Linux  6.6.3-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 28 19:11:52 UTC 2023 x86_64 GNU/Linux`

## What you did

Tried to build a bevy program.

## What went wrong
Build error, as below.

## Additional information

```
error[E0063]: missing fields `grid_auto_columns`, `grid_auto_flow`, `grid_auto_rows` and 5 other fields in initializer of `taffy::prelude::Style`
  --> /home/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ui-0.10.1/src/flex/convert.rs:99:5
   |
99 |     taffy::style::Style {
   |     ^^^^^^^^^^^^^^^^^^^ missing `grid_auto_columns`, `grid_auto_flow`, `grid_auto_rows` and 5 other fields
```

**Comment by alice-i-cecile** [comment]
This is occurring because you have duplicate incompatible versions of Bevy in your dependency tree. Use `cargo tree` to help root out the problem.
