### ISSUE TITLE
Build error involving bevy_reflect_derive on current stable toolchain (1.74.1)

### ISSUE THREAD

**Issue by ksf** [bevyengine/bevy#10904]
## Heads up

Works on beta and nightly

## Bevy version

0.12.1

## Relevant system information

cargo 1.74.1 (ecb9851af 2023-10-18)
rustc 1.74.1 (a28077b28 2023-12-04)
rustup 1.26.0 (1980-01-01)
NixOS 23.11 (Tapir)

(That's the latest stable toolchain from rustup, started via rustup, everything's via rustup, which is from nixos hence the strange date)

## What you did

`cargo new`, no workspace or anything, then

```toml
[package]
name = "bevy-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
```

then `cargo check` or `run` or `build`, same issue.

## What went wrong
```
error[E0463]: can't find crate for `bevy_reflect_derive`
 --> /home/ksf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_reflect-0.12.1/src/type_uuid.rs:1:9
  |
1 | pub use bevy_reflect_derive::TypeUuid;
  |         ^^^^^^^^^^^^^^^^^^^ can't find crate
```

...repeated half a million times in different places followed up by a quadrillion of followup errors.

Tried `resolver = "2"` out of curiosity, didn't change anything.

Curiously enough though the single dependency `bevy_reflect = "0.12.1"` works, including

```rust
use bevy_reflect::Reflect;

#[derive(Reflect)]
struct Foo {}
```
above the standard hello world `main()`.

Which means that `bevy_reflect` actually compiles, and I'm completely at a loss as to what is, or even could be, wrong here.  

This all started happening after a nixos and rustup upgrade and `cargo update` (which switched the lock from 0.12.0 versions to 0.12.1) and `cargo clean` , this morning my actual project still built. Please don't ask me for the old versions.

I'm not entirely convinced it's even an issue with bevy, OTOH someone might have a clue as to what could possibly trigger this. Gremlins?

And just for completeness' sake, my flake.nix or the build would fail with alsa not found before getting to the juicy part. Mold or not doesn't make a difference.
<details>
<summary>flake.nix</summary>

```nix
{
  description = "dev flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/23.11";

    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    let supportedSystems = [ "x86_64-linux" ];
    in flake-utils.lib.eachSystem supportedSystems (system:
      let pkgs = import nixpkgs {inherit system;};
      in {
        inherit pkgs;
        devShell = with pkgs; mkShell.override {
          stdenv = stdenvAdapters.useMoldLinker clangStdenv;
        } rec {
          nativeBuildInputs = [
            pkg-config
          ];
          buildInputs = [
            udev alsa-lib
            gtk3 # panic handler msgbox
            vulkan-loader
            xorg.libX11 xorg.libXcursor xorg.libXi xorg.libXrandr
            libxkbcommon wayland
          ];
          LD_LIBRARY_PATH = lib.makeLibraryPath buildInputs;
        };
      }
    );
}
```
</details>

**Comment by alice-i-cecile** [comment]
Adding this to the 0.13 milestone: by then we will know if we need to scream upstream before our next release or if this has been fixed.

**Comment by ksf** [comment]
And of course I forgot to check on the 28th, 37c3 and all. Anyhow, works on `rustc 1.75.0 (82e1608df 2023-12-21)`, closing.
