### ISSUE TITLE
UI Node outlines are not clipped

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#10921]
## Bevy version

0.12.0

## What you did

I have a UI element with `ui::OverflowAxis::Clip`. Inside that element is a child which is clipped. However, if the child has an outline, the outline is not clipped.

## What went wrong

I realize that outlines are on a separate layer, but I still expect them to be clipped by the parent if the parent has clipping enabled.

<img width="253" alt="outline-clip" src="https://github.com/bevyengine/bevy/assets/1166135/fe5cf4c1-c3e1-4ff8-8965-8d583af7b837">

**Comment by ickshonpe** [comment]
I implemented clipping for outlines this way deliberately. I don't understand what I was thinking now, it's incorrect nonsense.
