### ISSUE TITLE
Re-export smallvec crate from bevy_utils

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#10932]
This is a useful type, and re-exporting it makes it easier for users (and other bevy sub-crates) to use, while ensuring the same version is used to prevent duplicate dependencies. 

Could also use arrayvec, which is what wgpu/taffy uses iirc.

**Comment by alice-i-cecile** [comment]
For beginners, can you add a bit of context on why we bother re-exporting types in Rust?

**Comment by DavJCosby** [comment]
First time contributing and I'd like to work on this.

@JMS55, just wanted to clarify: is the goal here to make bevy_utils the only place where smallvec is brought in as dependency, and then have the other sub-crates start using `bevy_utils::smallvec`?

Right now I just have bevy_utils re-exporting the crate in my PR, but it's not hooked up to anything else.

**Comment by JMS55** [comment]
Thanks for working on this! See https://github.com/bevyengine/bevy/pull/11006#issuecomment-1859205737
