### ISSUE TITLE
`ReflectMapEntities` on Resources

### ISSUE THREAD

**Issue by hankjordan** [bevyengine/bevy#10958]
## Bevy version

`0.12.1`

## What you did

```rust
#[derive(Resource, Reflect, Clone, Default)]
#[reflect(Resource, MapEntities)]
pub struct MyResource {
    entity: Entity
}

impl MapEntities for MyResource {
    fn map_entities(&mut self, entity_mapper: &mut EntityMapper) {
        *self.entity = entity_mapper.get_or_reserve(self.entity);
    }
}
```

## What went wrong

```
error[E0277]: the trait bound `app::MyResource: bevy::prelude::Component` is not satisfied
   --> src/main.rs:20:20
    |
500 | #[derive(Resource, Reflect, Clone, Default)]
    |                    ^^^^^^^ the trait `bevy::prelude::Component` is not implemented for `app::MyResource`
    |
    = help: the following other types implement trait `bevy::prelude::Component`:
              AccessibilityNode
              bevy::prelude::Name
              GlobalTransform
              Transform
              Children
              SceneInstance
              Parent
            and 170 others
    = note: required for `ReflectMapEntities` to implement `FromType<app::MyResource>`
    = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)
```

## Additional Information

Looks like this is caused by `ReflectMapEntities` having a Component bound on `FromType`.

**Comment by hankjordan** [comment]
I believe a workaround would be to derive `Component` in addition to `Resource`, this should still work with `bevy_scene`'s implementation of `MapEntities`.

**Comment by shousper** [comment]
I was just looking at this wrt. `DynamicScene`, which is missing the implementation to call `map_entities` for `Resource`s implementing the trait. Given the scene serializes with this information, and nothing prevents resources including entities, it'd be nice to add this.

For now, I'm considering:

1. Extending `DynamicScene` with an extra method I can use to perform this extra step.
2. Converting my resource to a sparse-set component 🙈

For context, I'm trying to use `bevy_save` or `moonshine_save`, which leverage `DynamicScene` but also don't cover this gap. So I'll probably choose option 2 😅
