### ISSUE TITLE
Add support for PreFixedUpdate/PostFixedUpdate

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#10974]
This might be another issue, but should we also add support for PreFixedUpdate/PostFixedUpdate? This same mechanism could be used for that too.

Someone in the discord was asking about PostFixedUpdate 😅

_Originally posted by @andriyDev in https://github.com/bevyengine/bevy/issues/10969#issuecomment-1854649364_

**Comment by Aceeri** [comment]
I actually was just talking about this as well and would be useful here: https://github.com/bevyengine/bevy/pull/10973

**Comment by andriyDev** [comment]
Ah thank you for making this @alice-i-cecile!

**Comment by alice-i-cecile** [comment]
"Reference in new issue" (the ... dots on each comment) is extremely convenient!
