### ISSUE TITLE
link problem on windows

### ISSUE THREAD

**Issue by coolit** [bevyengine/bevy#110]
On win10 with the "button" example, I think I have installed windows sdk. 
- But sometimes the link just failed during the build process.  The error was: 
Non-UTF-8 output: LINK : fatal error LNK1104: \xce\xde\xb7\xa8\xb4\xf2\xbf\xaa\xce\xc4\xbc\xfe\xa1\xb0D:\\rust_build\\all\\release\\examples\\button.exe\xa1\xb1\r\n

- And if I rebuild, it will fail again, unless I rename the target exe file and rebuild again. Btw, the target exe file cannot be deleted, but can be renamed.

**Comment by coolit** [comment]
After following this instructions:
https://github.com/rust-lang/book/pull/2389
The unstable link problem seems to be gone.

**Comment by cart** [comment]
This is very interesting. I'm curious if anyone else can repro this. I'll respond here if I can.

**Comment by cart** [comment]
I'm curious if you still have issues if you use pre-packaged rust version of LLD. We just switched our config to use that.

https://github.com/bevyengine/bevy/pull/150

**Comment by cart** [comment]
I booted into windows and I haven't been able to repro yet.

**Comment by coltontcrowe** [comment]
I haven't been able to reproduce it.  I believe I have SDK 10.0.18362.0

**Comment by cart** [comment]
Cool. im down to leave this open for a few days to see if anyone else hits the issue. Otherwise I'll probably close this.

**Comment by coolit** [comment]
After revisiting this post https://github.com/rust-lang/book/pull/2389 and add the English lang pack, now the err changed to:
``` fatal error LNK1104: cannot open file 'D:\rust_build\release\examples\button.exe'```
How to repro:
Using the button example, switch between the two fonts until the error occur (sometimes it will appear easily, sometimes after several tries). You can find the second font here: https://github.com/bevyengine/bevy/issues/112  
```// font: asset_server.load("assets/fonts/FiraSans-Bold.ttf").unwrap(),
font: asset_server.load("assets/fonts/simhei.ttf").unwrap(),```

**Comment by coolit** [comment]
But the interesting thing is no such error occurred to other projects when using Clion terminal.
