### ISSUE TITLE
bevy_reflect downcasting is unsound

### ISSUE THREAD

**Issue by bjorn3** [bevyengine/bevy#1100]
As of 3b2c6ce49b3b9ea8bc5cb68f8d350a80ff928af6 it is possible to cause UB in safe code using bevy_reflect. `Reflect::downcast` incorrectly assumes that `Reflect::any` returns an `&Any` representation of `self`. This is not necessarily the case. It is possible to return an `&Any` to a field of `self` with a different type. `Reflect::downcast` will then downcast to that specific type. This can be fixed by making `Reflect` an unsafe trait. The standard library avoids this problem by making it impossible to implement `Any` yourself using a blanket impl. See https://github.com/rust-lang/rust/blob/29e32120c33d30ff526fc7f4d94ec9fce0dc10c9/library/core/src/any.rs#L77

**Comment by DarkMara** [comment]
How do I work around this? I'm experiencing this when I push to a Vec in  a struct that implements Reflect. The error is `Attempted to push invalid value of type TYPE`, but the type is correct.

**Comment by cart** [comment]
@DarkMara  Yeah I think you're hitting a different issue

@bjorn3 yeah that makes sense. we should make it an unsafe trait. user code should generally be deriving it anyway (which will do the right thing on their behalf).
