### ISSUE TITLE
Gizmos do not work across all web browsers

### ISSUE THREAD

**Issue by dbidwell94** [bevyengine/bevy#11013]
## Bevy version

0.12.1

```ignore
AdapterInfo { name: "Radeon R9 200 Series", vendor: 4098, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
```

## What you did

Gizmos not working in Chrome, but working in Firefox.
https://github.com/dbidwell94/rimguard_realms/blob/master/src/pawn/systems.rs#L327-L343

This can be observed in the following build: https://dbidwell94.github.io/rimguard_realms/
In Firefox observe that when dragging walls you will see outline gizmos, and when pawns move you should see their paths as line gizmos. However, in Chrome neither is present.

## What went wrong

If it's not clear, break this out into:

## Expected
Gizmos to work in all web browsers

## Actual
Gizmos do not work in Chrome

**Comment by mockersf** [comment]
works for me on chromium on macos

**Comment by dbidwell94** [comment]
Odd, it does on both Chrome and Firefox. This is obviously a config issue on my end, my bad :)
