### ISSUE TITLE
Rendering fails when using WebGPU due to shader not compiling.

### ISSUE THREAD

**Issue by Roeliefantje** [bevyengine/bevy#11038]
## Bevy version

0.12.0

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
  - cargo 1.74.0
- the operating system or browser used, including its version
  -Windows 11 Education 22H2 22621.2861
  -Chrome 122.0.6196.0 (Officiële build) canary (64-bits)

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

AdapterInfo { name: "", vendor: 0, device: 0, device_type: Other, driver: "", driver_info: "", backend: BrowserWebGpu }

## What you did

I tried rendering my application using WebGPU as I want to use compute shaders in the future.
The problem seems to occur due to an issue with the PBR pipeline.
```rust
let boid_mesh = meshes.add(Mesh::from(shape::Cube {size: 0.1})); 
let boid_material = materials.add(Color::ANTIQUE_WHITE.into());
...
    let cube = CrowBundle {
            pbr: PbrBundle {
                mesh: boid_mesh.clone(),
                material: boid_material.clone(),
                ..Default::default()
            },
            ..default()
        };
        all_cubes.push(cube);
    }
    commands.spawn_batch(all_cubes);
```

## What went wrong
It can render some things from my scene, but when trying to render the Pbrbundle it gives an error
![image](https://github.com/bevyengine/bevy/assets/66168396/1b2da24e-4f2e-45cb-b5bd-d7b42add0686)
![image](https://github.com/bevyengine/bevy/assets/66168396/c38d06f4-be95-45f0-ab3b-cb69db3c7e1d)
I am not using any custom shaders in the example that is running.
![image](https://github.com/bevyengine/bevy/assets/66168396/6e3c24aa-bf1f-40e2-b919-f20babc32f55)

**Comment by mockersf** [comment]
Could you try updating to Bevy 0.12.1, and check if https://bevyengine.org/examples-webgpu/3D%20Rendering/3d-scene/ is working for you?

**Comment by Roeliefantje** [comment]
I have updated to Bevy 0.12.1 and it seems to have fixed the issue.
Running it on chrome 120.0.6099.110 (Official Build) worked fine, my own porject worked fine as well.
Canary did hang however, but I'm not sure that is bevy related.
