### ISSUE TITLE
High CPU usage when game is unfocused or on a different monitor

### ISSUE THREAD

**Issue by Giacom** [bevyengine/bevy#1105]
**Bevy version**

3b2c6ce49b3b9ea8bc5cb68f8d350a80ff928af6

**Operating system & version**

Windows 10

**What you did**

1. Ran the breakout example.
2. Put the game window on your primary monitor and focused on a different window app.
3. Put the game window on a secondary monitor.

**What you expected to happen**

I should expect the game to run at a consistent low CPU usage when unfocused or on a secondary monitor.

**What actually happened**

The game will run at 8% CPU usage when focused but as soon as it is unfocused, i.e you clicked on a different app window, it'll start running at a 25% CPU usage. This will also happen when moving the game window to a different monitor other than your primary one.

**Additional information**

I have a 240hz gsync 1080p (primary) and a 60hz 1080p (secondary) monitor. Maybe the game's frame limiter/vsync gets uncapped/turned off during the above conditions.

i7 7700K
1070 GTX

**Comment by r1sc** [comment]
This happens here as well with just one monitor and the app focused. 25% CPU utilization..

**Comment by seanlinsley** [comment]
On macOS, an empty Bevy app jumps ~4x CPU usage when the window is completely hidden behind other windows 🤔

**Comment by alice-i-cecile** [comment]
Closed by #3974.
