### ISSUE TITLE
Rename `ArchetypeEntity::entity` into `ArchetypeEntity::id`

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#11050]
## What problem does this solve or what need does it fill?

We have `EntityWorldMut`, `EntityMut` and `EntityRef` with method called `id` that returns `Entity`.
But it's inconsistent with  `ArchetypeEntity::entity`.

## What solution would you like?

I would suggest to rename `ArchetypeEntity::entity` into `ArchetypeEntity::id`.

**Comment by capt-glorypants** [comment]
I'll do it.
