### ISSUE TITLE
Allow running one-shot systems with output via Commands

### ISSUE THREAD

**Issue by pablo-lua** [bevyengine/bevy#11062]
## What problem does this solve or what need does it fill?

Adding an way to run system with output would easy the life of one that need to run the same one-shot system in multiple different systems, being it an exclusive system or not

## What solution would you like?

Add the function `Commands::run_system_with_output(system_out, system_in)`, with the first system being the system with the output, and the second being the system that would use the output, similar to piping systems

## What alternative(s) have you considered?

There is an actual way to use the Output from a one-shot system, being:
```rust
let id = // SystemId here;
commands.add(move |world: &mut World|) {
   let out = world.run_system(id);
   // Use your out as you want
}
```
but this is a "less elegant" way and can probably be improved

**Comment by irate-devil** [comment]
Is it not possible to use system piping with run_system?

**Comment by pablo-lua** [comment]
@irate-devil run_system is not expecting any function with output, so the pipe wouldn't go right with `Commands`.
And its not possible to do any kind of piping with run_system, the function doesn't return anything and is not expecting 2 systems or similar.

**Comment by pablo-lua** [comment]
That actually works, didn't expected it to go well. Thanks, if there is an actually way to register systems already piped, there is no need to add an function like that, so I'm closing this issue.
