### ISSUE TITLE
Hierarchical states (substates) through system ordering

### ISSUE THREAD

**Issue by MiniaczQ** [bevyengine/bevy#11073]
## What problem does this solve or what need does it fill?

Bevy's state API is good for flat states, but it's hard to work with nested/hierarchical states.

## What solution would you like?

Add API for adding substates and system ordering for propagating it same tick.
This also requires substates to be `inactive` when their parent isn't in the correct state.

[Prototype](https://github.com/MiniaczQ/bevy-design-patterns/tree/main/patterns/instant-states-hierarchy), tests double as examples.

## What alternative(s) have you considered?

- [State pattern matching](https://github.com/bevyengine/bevy/pull/10088)

- [Propagate it in multiple ticks](https://github.com/MiniaczQ/bevy-design-patterns/tree/main/patterns/propagating-states-hierarchy)

**Comment by SIGSTACKFAULT** [comment]
previous work: https://github.com/bevyengine/bevy/issues/9942

**Comment by MiniaczQ** [comment]
> previous work: #9942

Appears to be the source of #10088

**Comment by lee-orr** [comment]
@MiniaczQ - I'd consider this more of a compliment to #10088. That PR doesn't actually provide built in hierarchical states, instead focusing on allowing a wider array of pattern matching options for the currently supported state types (which can be structs or enums, but currently only have a built-in way to handle full equality for matches).

Overall I do like a lot of this approach, though I only had a cursory glance here. The text history around https://github.com/bevyengine/bevy/pull/9957 might give some context for how I ended up with #10088, and the removal of Conditional States (which were my attempt at handling hierarchy). - figured that older PR might be useful as a reference for prior work as well...

**Comment by MiniaczQ** [comment]
Yeah, the more I work on a solution the less it collides with the state matching PR.
While access to lower level states in a simple way is important, I run into a lot of cases where partial access, both for matching and updating, would be nice.
Pattern matching is certainly not something that can be done with schedules.

A complementary to matching would be partial update through `NextState`, which I'm considering the necessity of

**Comment by lee-orr** [comment]
@MiniaczQ - With the addition of SubStates to #11426 - do you think that would resolve this issue? Or would more work be necessary on that front?

**Comment by MiniaczQ** [comment]
I think this covers the use case :)
