### ISSUE TITLE
Cursor cannot be hidden in web

### ISSUE THREAD

**Issue by musjj** [bevyengine/bevy#11093]
## Bevy version
`0.12`

## What you did

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Update, hide_cursor)
        .run();
}

fn hide_cursor(
    mut windows: Query<&mut Window>,
    mouse: Res<Input<MouseButton>>,
    key: Res<Input<KeyCode>>,
) {
    let mut window = windows.single_mut();

    if mouse.just_pressed(MouseButton::Left) {
        window.cursor.visible = false;
    }

    if key.just_pressed(KeyCode::Escape) {
        window.cursor.visible = true;
    }
}
```

## What went wrong

- What were you expecting?
The cursor becomes hidden.

- What actually happened?
The cursor is not hidden

## Additional information

The cursor is correctly hidden in the desktop builds.

When you grab the cursor with:

```rust
window.cursor.grab_mode = CursorGrabMode::Locked;
```

Cursor hiding will work in the web build.

You can get around this issue by setting `cursor: none;` in the CSS, so at the very least there should be some sort of API to control this.

**Comment by daxpedda** [comment]
This was fixed in https://github.com/rust-windowing/winit/pull/2949, can try and backport it into Winit v0.29.7.

**Comment by daxpedda** [comment]
Okay, apologies, I got confused there. It was indeed fixed in https://github.com/rust-windowing/winit/pull/2949 which made it into v0.29.2 and is still correctly applied in v0.29.6.

I just forgot that Bevy v0.12 still depends on Winit v0.28. So this is already fixed on `main`, which I've confirmed.

**Comment by musjj** [comment]
Thanks, tested it on `main` and it works perfectly. Closing this issue.
