### ISSUE TITLE
Print a warning if a `CommandQueue` gets dropped with un-applied commands

### ISSUE THREAD

**Issue by JoJoJet** [bevyengine/bevy#11125]
## What problem does this solve or what need does it fill?

When dealing with exclusive world access, `SystemState` is useful for interfacing with the world with an interface similar to regular systems. However, it's very easy to forget to call `.apply()`, which can result in commands being lost.

## What solution would you like?

There should be a warning if a `SystemState` gets dropped without being applied. To accomplish this, we should be able to put a warning in the `Drop` impl for `CommandQueue`

## What alternative(s) have you considered?

None.

**Comment by hymm** [comment]
> We should also provide a way to drop the unapplied CommandQueue without the warning.

Note that any commands in unapplied CommandQueue actually have entities allocated to them that need to be cleaned up too.
