### ISSUE TITLE
Possible performance regression in WASM builds

### ISSUE THREAD

**Issue by eerii** [bevyengine/bevy#11122]
## Bevy version

* Original: 0.12.1
* Current: [8067e46](https://github.com/bevyengine/bevy/commit/8067e46049f222d37ac394745805bad98979980f)

## Relevant system information

Please include:

Cargo version: `cargo 1.76.0-nightly`

OS: `Arch Linux, Kernel 6.6.7`

CPU: `Intel(R) Core(TM) i7-4770HQ`

GPU: `None (integrated)`

Using trunk for builds.

## What's performing poorly?

Updating from 0.12.1 to `main` makes wasm builds very slow, they take 100% of the GPU and drop a lot of frames. This doesn't happen with native builds, they run the same as before. I tested it on an empty 2d scene with a camera.

## Before and After Traces

* Before: [before.zip](https://github.com/bevyengine/bevy/files/13789201/before.zip)
* After: [after.zip](https://github.com/bevyengine/bevy/files/13789251/after.zip)

## Additional information

Minimum example (2d shapes from the examples folder with minimum trunk setup)
[minimum_project.zip](https://github.com/bevyengine/bevy/files/13789437/minimum_project.zip)

100ms before

![100ms before](https://github.com/bevyengine/bevy/assets/22449369/aa79d53b-00d9-44d6-9d3c-f9b03361b52c)

100ms after

![100ms after](https://github.com/bevyengine/bevy/assets/22449369/fec37f8a-4c4c-4c16-b0c7-86848b656173)

100ms native (no lag) [tracy](https://github.com/bevyengine/bevy/files/13789350/native.zip)

![image](https://github.com/bevyengine/bevy/assets/22449369/cdfbc714-e056-4b94-90c8-509c69129025)

**Comment by alice-i-cecile** [comment]
Discussed in https://discord.com/channels/691052431525675048/1187849589764673586/1190010673145589791 previously.
