### ISSUE TITLE
Unexpected timings when using TimeUpdateStrategy::ManualDuration

### ISSUE THREAD

**Issue by 66OJ66** [bevyengine/bevy#11127]
## Bevy version

v0.12.1

## What you did

I was writing tests to validate my systems are working correctly after varying amounts of time have passed, but I encountered discrepancies between `Time<Real>` and `Time` (virtual).

Minimal example which demonstrates this:
```rust
use bevy::prelude::*;
use bevy::time::TimeUpdateStrategy;
use std::time::Duration;

fn main() {
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .insert_resource(TimeUpdateStrategy::ManualDuration(Duration::from_millis(
            600,
        )))
        .add_systems(Update, print_elapsed);

    app.update();
    app.update();
    app.update();
}

fn print_elapsed(time: Res<Time>) {
    println!("Time Elapsed: {:?}", time.elapsed());
}
```

## What went wrong
The code above produces the following output with incorrect timings:
```
Time Elapsed: 0ns
Time Elapsed: 250ms
Time Elapsed: 500ms
```
(using a different manual duration has no impact - the step is always 250ms as far as I can tell)

Changing from `Time` to `Time<Real>` produces this output which does have correct timings:
```
Time Elapsed: 0ns
Time Elapsed: 600ms
Time Elapsed: 1.2s
```

So there's a discrepancy between the `Real` and `Virtual` timings even though I haven't changed the time scale, paused etc.

As the systems in my App need to be affected by time scaling, I can't replace their usage of `Res<Time>` with `Res<Time<Real>>` as a workaround.

**Comment by maniwani** [comment]
What you're seeing is `Time<Virtual>` clamped by its default [`max_delta`](https://docs.rs/bevy/latest/bevy/time/struct.Time.html#method.max_delta) of 250ms. If you'd like to disable that behavior, you can access the `Time<Virtual>` resource and call [`time.set_max_delta(Duration::MAX)`](https://docs.rs/bevy/latest/bevy/time/struct.Time.html#method.set_max_delta).
