### ISSUE TITLE
Provide warning when adding UI entities as children of regular entities (since they don't show)

### ISSUE THREAD

**Issue by guyguy2001** [bevyengine/bevy#11151]
## What problem does this solve or what need does it fill?

Currently, when spawning a node (UI entity) as a child of a regular object, the node doesn't get rendered, with no indication of why that is the case:

## What solution would you like?

A warning (or maybe even a panic?) when adding a `Node` as a child of a non-node entity (or to a non-node ancestor)

## What alternative(s) have you considered?

I can't really think of anything else...
Maybe making it more obvious from the documentation, but I don't think that would have helped me, as I mostly learned from youtube.

## Additional context
Reproduction:
```rs
pub fn spawn_healthbar(commands: &mut ChildBuilder) {
    commands
        .spawn((
            NodeBundle {
                style: Style {
                    // width: Val::Percent(100.0),
                    // height: Val::Percent(30.0),
                    width: Val::Px(500.),
                    height: Val::Px(500.),
                    left: Val::Px(0.),
                    // top: Val::Px(0.),
                    border: UiRect::all(Val::Px(20.)),
                    justify_content: JustifyContent::SpaceAround,
                    position_type: PositionType::Absolute,
                    display: Display::Flex,
                    ..default()
                },
                background_color: Color::DARK_GRAY.into(),
                ..default()
            },
            // WorldUI,
            Name::new("WorldUI"),
        ))
        .with_children(|commands| {
...
});
}

fn setup_player(mut commands: Commands, asset_server: Res<AssetServer>) {
    let texture = asset_server.load("character.png");
    let sprite_size = 7.5;
    commands
        .spawn((
            SpriteBundle {
                sprite: Sprite {
                    custom_size: Some(Vec2::new(sprite_size, sprite_size)),
                    ..default()
                },
                texture,
                ..default()
            },
...
        ))
        .with_children(|commands| spawn_healthbar(commands));
}


```

Thank you!

**Comment by alice-i-cecile** [comment]
This is currently quite challenging to do without an expensive system that checks for this: bevy_hierarchy which handles the parenting is not aware of bevy_ui.

**Comment by pablo-lua** [comment]
> quite challenging
I was giving it a try and a check would be possible in the function update_ui_tree (thats the name? not sure) , however the first problem would be that this function run every frame, filter the warning would be probably impossible actually
A possibility for now is wait #10756, with this we can add a hook of some sort to Node itself and warn the use there maybe

**Comment by StrikeForceZero** [comment]
I think this was solved via https://github.com/bevyengine/bevy/commit/5989a845f0826483b55506e58e0d2e08cc094854 https://github.com/bevyengine/bevy/blob/aab36f39513bc30e148d106f6d2f11f4e85264b5/crates/bevy_ui/src/layout/mod.rs#L266-L271


```rust
    commands
        .spawn((
            Text2d::new("non ui text"),
        ))
        .with_children(|builder| {
            builder.spawn((
                Text::new("ui text"),
            ));
        });
```
triggers: 
```
WARN bevy_ui::layout: Node (9v1) is in a non-UI entity hierarchy. You are using an entity with UI components as a child of an entity without UI components, your UI layout may be broken.
```
