### ISSUE TITLE
Do not require a BackgroundColor for UI images

### ISSUE THREAD

**Issue by pablo-lua** [bevyengine/bevy#11157]
## What problem does this solve or what need does it fill?

Actually, in order to use an image with `Sprite` or even `UiImage`, you are forced to use a BackgroundColor that is different from transparent, and that is misleading, can lead to one to think "well, I don't want an color in my Image, so I'll set it to transparent, right?" and then being confused because the image disappeared

## What solution would you like?

The BackgroundColor, when being used with an image would apply an oppacity of determined color above the image. For example Rgb(255, 255, 0, 0.5) would taint the image slightly of yellow
but if one use Rgb(0, 0, 0, 1) the image would be tainted of black and the image itself would disappear (as alpha is 100%), leaving an black square on its place

## What alternative(s) have you considered?

For that purpose, probably adding an child or something above the child with the desired color and leaving color in the background as Color::WHITE and leaving it as it is.

## Additional context

- A possible problem that would appear from this is if one wants to make a image appear only a little, with alpha set to for example 0.5, that wouldn't be possible for that approach, and a possible solution to this is adding another component that specifies the Image oppacity

**Comment by alice-i-cecile** [comment]
The current design is quite confusing to me, as it conflates the background color with the tint of the image. IMO the node that stores the UI shouldn't have a background color by default: instead, it should have a distinct component / property that is used for tinting.

**Comment by benfrankel** [comment]
It would be nice to have a separate component that applies color tinting to `Sprite`, `TextureAtlasSprite`, `Text`, `UiImage`, etc. (anything rendered by the entity). That would make certain animations like fading away easy to implement, by just tweening an entity's color tint alpha from 1 to 0.

The individual components should probably still have their own `color` fields because you might want different colors for e.g. the `Sprite`, `Text`, `BorderColor`, `BackgroundColor`, etc. within the same entity. On that note, `UiImage` and `UiTextureAtlasImage` should probably have their own `color` fields too.

**Comment by pablo-lua** [comment]
the `ColorTint` idea is good, like you said. would take the old function of `BackgroundColor` and would give the BackgroundColor another function that I hope would be more intuitive. Like I said in the issue, like applying an oppacity over the Image or something like that. In that case, the Color role in various bundles would change (`Sprite` would now have ColorTint and use the Color for another purpose)

**Comment by benfrankel** [comment]
Btw, `BackgroundColor` doesn't tint `Sprite` currently, it only tints `UiImage` and `UiTextureAtlasImage` (and for other UI nodes, it's the actual background color).

**Comment by pablo-lua** [comment]
Yeah, in the `Sprite` case I'm talking about the `Color` element, In the Sprite case and maybe others, the `Color` do the role of tint the image, what IMO is a little misleading too.

**Comment by benfrankel** [comment]
I'm gonna try to make a PR decoupling `BackgroundColor` from `UiImage` and `UiTextureAtlasImage`.

`ColorTint` can be a separate issue and a separate PR.

**Comment by benfrankel** [comment]
I guess unrelated to this issue, but I noticed another inconsistency. The `Sprite`, `TextureAtlasSprite`, and `UiTextureAtlasImage` components all rely on a separate component for their image handles (`Handle<Image>` or `Handle<TextureAtlas>`). But `UiImage` for some reason has its own `UiImage::texture: Handle<Image>` field.

I'm not sure if there's a reason for this so I'm not gonna touch it.

**Comment by ickshonpe** [comment]
> The current design is quite confusing to me, as it conflates the background color with the tint of the image. IMO the node that stores the UI shouldn't have a background color by default: instead, it should have a distinct component / property that is used for tinting.

I think I put in a similar PR back for 0.10 or something that implemented this. Everyone agreed with it but it got no reviews and I forgot about it.

**Comment by ickshonpe** [comment]
Another reason I wanted this change was that it allowed for things like letter-boxing of images with a fixed aspect ratio.
I had a second PR I made for it, but turned it into a third-party crate instead because the color changes didn't get merged.

**Comment by ickshonpe** [comment]
> I guess unrelated to this issue, but I noticed another inconsistency. The `Sprite`, `TextureAtlasSprite`, and `UiTextureAtlasImage` components all rely on a separate component for their image handles (`Handle<Image>` or `Handle<TextureAtlas>`). But `UiImage` for some reason has its own field, `UiImage::texture: Handle<Image>`.
> 
> I'm not sure if there's a reason for this so I'm not gonna touch it.

This was because `UiImage` also had fields for flipping the image on its axes. This isn't need for sprites as you can just use the transform. 

For `UiTextureAtlasImage` it needs two components, the texture atlas and also an index into the texture atlas, so the implementation was different.

**Comment by pablo-lua** [comment]
>This was because UiImage also had fields for flipping the image on its axes. This isn't need for sprites as you can just use the transform.

This is only an idea, but maybe we can do this kind of transform on the image using style?

**Comment by ickshonpe** [comment]
> > This was because UiImage also had fields for flipping the image on its axes. This isn't need for sprites as you can just use the transform.
> 
> This is only an idea, but maybe we can do this kind of transform on the image using style?

I've thought that the `Style` component is misnamed for a long time. It's meant to be content agnostic, purely for use by Taffy to generate the layout geometry. It wouldn't make sense to add information about images to it.

**Comment by benfrankel** [comment]
> This was because `UiImage` also had fields for flipping the image on its axes. This isn't need for sprites as you can just use the transform.

`Sprite`, `TextureAtlasSprite`, `UiImage`, and `UiTextureAtlasImage` all have `flip_x` and `flip_y` fields.

**Comment by ickshonpe** [comment]
> > This was because `UiImage` also had fields for flipping the image on its axes. This isn't need for sprites as you can just use the transform.
> 
> `Sprite`, `TextureAtlasSprite`, `UiImage`, and `UiTextureAtlasImage` all have `flip_x` and `flip_y` fields.

Oh yeah of course they do, I forgot 😅  .
