### ISSUE TITLE
Text rendering is incorrect on some displays

### ISSUE THREAD

**Issue by TheRawMeatball** [bevyengine/bevy#1116]
Bevy 0.4.0

**Operating system & version**

Kubuntu 20.10

**What you did**

I ran the UI example

**What you expected to happen**

The text should be sharp and clean

**What actually happened**

It was pixelated

**Additional information**

I did a little probing in the UI source, and I think the issue is the scaling factor being applied to the text incorrectly. I have 2 monitors, the primary being 2560x1440 and the other being 1280x1024. It renders nicely on the second monitor with a scaling factor of one, but looks horrible on the first which has a scaling factor of 1.1666.. 

Clean
![Screenshot_20201221_122635](https://user-images.githubusercontent.com/6781733/102761363-dcdc4080-4387-11eb-872b-af6e856d5906.png)

Broken
![Screenshot_20201221_122444](https://user-images.githubusercontent.com/6781733/102761550-1ad96480-4388-11eb-9a0d-78508a65a6d7.png)

**Comment by DJMcNab** [comment]
I believe this is known about - from https://bevyengine.org/news/bevy-0-4/:

> There is still a bit more work to be done here. While Bevy UI renders images and boxes at crisp HIDPI resolutions, text is still rendered using the logical resolution, which means it won't be as crisp as it could be on HIDPI displays.

That being said, I don't think there's an issue open for it yet, so thanks for adding it :)

**Comment by zeh** [comment]
Seems to be fixed by [6531fcdfd27b3fbae050643116754916ca3f3b3d](https://github.com/bevyengine/bevy/commit/6531fcdfd27b3fbae050643116754916ca3f3b3d) (on `master`, not yet released).

**Comment by alice-i-cecile** [comment]
Closing as resolved.
