### ISSUE TITLE
Add PopChild and PopChildren command

### ISSUE THREAD

**Issue by MelonShooter** [bevyengine/bevy#11186]
## What problem does this solve or what need does it fill?

Currently, to remove children from a parent, `RemoveChildren` must be used on the parent. Neither of these are ideal in cases where the children are ordered in a particular manner and only the element(s) at the end needs to be popped off for 2 reasons. 

1. Using `RemoveChildren` in this case would require a separate query to get the children at the end to remove.
2. `RemoveChildren` would require two iterations through all the children, which wouldn't be efficient if there's a lot of children

## What solution would you like?

The solution I think would be best would be to add a `PopChild` and `PopChildren` command. `PopChildren` could use `drain` on the inner `SmallVec` while `PopChild` just uses `pop`, which solves both issues with using `RemoveChildren` above because this would only cause an iteration through the child or children to be popped. 

Also, having a `PopChild` and `PopChildren` keeps the API more consistent because there's already `AddChild` and `PushChildren` that adds element(s) to the end of the children. (On a separate note, it might be better to rename `AddChild` to `PushChild` but this would likely have to be in a separate issue.)

## What alternative(s) have you considered?

Removing a child or children from the end can be done with `RemoveChildren` but isn't ideal because the children to remove would need to be retreived in a separate query and isn't very efficient when there's a lot of children.

**Comment by MelonShooter** [comment]
If these proposed changes look good, I'd like to take this up (and #11187) and make a PR for it.

**Comment by TirushOne** [comment]
I am currnetley working on this but I am new so might take me a lille while to make the change. But no need for anyone else to spend time on this one because I'm doing that now

**Comment by alice-i-cecile** [comment]
I don't think we should add these without a clearer motivation. What sort of situation / architecture, concretely, do you want to remove the latest child, rather than "all children" or "a specific child"?
