### ISSUE TITLE
Add an OnSpawn method for components

### ISSUE THREAD

**Issue by pablo-lua** [bevyengine/bevy#11185]
## What problem does this solve or what need does it fill?

If some Components has to do some cleanup or even warning after entering the child, this kind of method could very much help
The main reason for me to think that was issue #11151, could be very useful it the entity parent was scanned and them warn if there is no nodes, just an example of how this could help.

## What solution would you like?

A possible Component::on_spawn that could be implemented by the user and the world would call that function as a little system and do the needed cleanup or similar.

## What alternative(s) have you considered?

You can do this yourself for you own implemented components, but external components wouldn't do the work / the user could not know what is the cleanup they need to before adding the child

## Additional context

This could be a little problematic to implement, as Component is implemented via proc macro. One way I could think is passing a function as an atribute in the macro

**Comment by alice-i-cecile** [comment]
This will be fixed by https://github.com/bevyengine/bevy/pull/10756 <3

**Comment by pablo-lua** [comment]
#10756 merged, closing this as completed
