### ISSUE TITLE
Some types in bevy_ui do not reflect the Default trait

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11197]
There is probably something missing here and there with the reflect. Noticed that some structs have Default and do not reflect it. Well, didn't touch it for now

_Originally posted by @pablo-lua in https://github.com/bevyengine/bevy/issues/11188#issuecomment-1874753508_

**Comment by Ato2207** [comment]
If it is ok, I'd like to make a PR for this issue and work on it.
