### ISSUE TITLE
Add ```in_any_state``` and ```in_all_states``` run conditions

### ISSUE THREAD

**Issue by ramirezmike** [bevyengine/bevy#11221]
## What problem does this solve or what need does it fill?

As games get more complex, users may find themselves wanting to setup a chain of systems to run in multiple separate states or on specific variant overlaps of multiple state types. While this is currently possible with combinator operations, it can be verbose and these patterns may be common enough to have dedicated run conditions. Searching for "or_else" on the discord yields [quite](https://discord.com/channels/691052431525675048/691052431974465548/1192648431563460798) [a](https://discord.com/channels/691052431525675048/691052431974465548/1183247743616024636) [few](https://discord.com/channels/691052431525675048/1175640997867307119/1175645113075118180) [instances](https://discord.com/channels/691052431525675048/742569353878437978/1156299973210673192) [of](https://discord.com/channels/691052431525675048/691052431974465548/1147387587347099710) [people](https://discord.com/channels/691052431525675048/691052431974465548/1141269161247506563) [asking](https://discord.com/channels/691052431525675048/1121438610512683139/1121438610512683139) (👀) how to do an OR with states.

## What solution would you like?

Add two run conditions for handling multiple states: in_any_state for OR and in_all_states for AND. There's a good example to start from [here](https://discord.com/channels/691052431525675048/742569353878437978/1156320222739976262) for the OR version.

## What alternative(s) have you considered?

Using or_else or and_then will suffice but again, it can get verbose
```rust
.run_if(in_state(AppState::InGame).or_else(in_state(OtherState::PreGame)).or_else(in_state(AppState::TitleScreen)))
```
versus
```rust
.run_if(in_any_state([AppState::InGame, OtherState::PreGame, AppState::TitleScreen]))
```

## Additional context

The "in_any_state" may be a bit more useful than the "in_all_states" as the latter is only useful if you're using multiple types of States. Additionally, depending on changes like #9942 this might get more complicated or be handled differently anyway?

**Comment by alice-i-cecile** [comment]
There are a number of proposed state changes in flight right now; I think we should land *some* of them, but we should do so with both eyes open and take a holistic view :)

**Comment by lee-orr** [comment]
@ramirezmike - Do you think #11426 would end up resolving this use case? If that PR is merged, you'd approach this by creating a `ComputedState` that defines this sequence of and/or releationships, and then you can use it as a single state.

**Comment by ramirezmike** [comment]
@lee-orr - That looks like it'd work well for this use case; I would say if that gets merged then this can be closed.

**Comment by benfrankel** [comment]
This is also fixed in [pyri_state](https://github.com/benfrankel/pyri_state) without the need for defining a second state:

```rust
add_systems(Update, MyState::on_update_and(|state| matches!(state, X | Y | ...), my_systems);
```

Or if you want to be conditional on states of different types (or literally anything else in the world), you can write your own custom run condition.

**Comment by alice-i-cecile** [comment]
I think that between the new computed states and a solid easy-to-swap-out third party solution the core need here is resolved.
