### ISSUE TITLE
Massively Degraded WebGPU performance

### ISSUE THREAD

**Issue by cshenton-work** [bevyengine/bevy#11220]
## Bevy version

`main#cf70f532`

## Relevant system information

Windows 11, Chrome

## What you did

Even a basically empty application has severely degraded performance on `main` on WebGPU. The following:

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins((DefaultPlugins,))
        .add_systems(Startup, (setup,))
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn((Camera3dBundle { ..default() },));
}
```

Results in a profile that looks like this:

<img width="502" alt="image" src="https://github.com/bevyengine/bevy/assets/151570269/49cb65fb-83a0-4230-bbe2-ba5d5aa9afb7">
<img width="788" alt="image" src="https://github.com/bevyengine/bevy/assets/151570269/7cfa2664-d9e3-4aac-84a3-44163a61f309">
<img width="840" alt="image" src="https://github.com/bevyengine/bevy/assets/151570269/9a412f80-74fc-442f-ad58-efbed453ba1c">

That `prepare_windows` system is one of the culprits but generally speaking just everything is taking ages.

If I instead build against the `0.12.1` release on crates.io, I get a clean profile:

<img width="750" alt="image" src="https://github.com/bevyengine/bevy/assets/151570269/7493d541-9254-47ed-aecf-173fce13eb87">

Something has clearly gone awry.

**Comment by alice-i-cecile** [comment]
Are you able to bisect the commit history? I suspect there was a single PR responsible.

**Comment by cshenton-work** [comment]
Yeah happy to, I shall report back if I find it.

**Comment by cshenton-work** [comment]
Afaict the regression was introduced by #10702 

`3b59dbd` has a clean profile
`3b59dbd` has the performance issues I see

**Comment by cshenton-work** [comment]
`3b59dbd`
<img width="242" alt="image" src="https://github.com/bevyengine/bevy/assets/151570269/b1338ed9-449b-460a-b3da-c574b850c86c">

`ced216f`
<img width="313" alt="image" src="https://github.com/bevyengine/bevy/assets/151570269/804aafac-9c99-465c-be7a-6284413d88b0">
Admittedly that is a _particularly_ bad profile, it typically looked like the original post.

**Comment by alice-i-cecile** [comment]
FYI @Vrixyz, who has been tracking follow-up tasks in https://github.com/bevyengine/bevy/issues/11052.

**Comment by Vrixyz** [comment]
Thanks for providing such detailed report!

I'll still ask for more information, how are you running your app ?

There's a thin chance you're hitting https://github.com/bevyengine/bevy/pull/10702#discussion_r1420567168, Are you setting explicitly the width/height of your canvas ?

**Comment by daxpedda** [comment]
I'm going to assume that this is still the same as https://github.com/bevyengine/bevy/issues/11122.
I noted how this can be fixed in https://github.com/bevyengine/bevy/issues/11052#issuecomment-1872498051: by using `WindowEvent::RedrawRequested`, otherwise drawing happens way too often.

**Comment by alice-i-cecile** [comment]
Closing as a duplicate :) Traces and replication were super useful though.
