### ISSUE TITLE
Rotated text is rendered outside of its container

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#11241]
## Bevy version

main, since 0483b69

This would probably be fixed in a roundabout way by #9341

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.6.2 ", kernel: "22.6.0", cpu: "", core_count: "10", memory: "64.0 GiB" }
```
`scale_factor` `1.0` and `2.0` were tested.

## What you did

`cargo run --example pbr`

## What went wrong

The "metallic" text on the right side should be aligned with the edge of the right column of spheres. But it is overlapping them.

I added `background_color: Color::RED.into()` in the screenshot below.

![image](https://github.com/bevyengine/bevy/assets/200550/d031a3e6-a4f9-48b4-a66a-ee963100a8b9)

## Additional information

It seems sort of like a coincidence that this worked before. I think that this https://github.com/ickshonpe/bevy/blob/99c43fabdfed9fe9fa161c2d4f3dfbdb8ea35a5b/crates/bevy_ui/src/render/mod.rs#L646 is the problem line, or close to it.

There may be other bits of rotated text in the examples that should be looked at.

**Comment by MaxiStev** [comment]
Text scaling also broken after the commit https://github.com/bevyengine/bevy/commit/0483b69a79f4c3324816d86abb05f9db87d44e87
before 
![bevy_11](https://github.com/bevyengine/bevy/assets/30327961/884260f2-d7d2-4af8-bae5-17fc2b508106)
after 
![bevy_12](https://github.com/bevyengine/bevy/assets/30327961/25e857a1-431c-4666-8541-d5ab5ec351ca)

**Comment by ickshonpe** [comment]
This is easy to fix, I'm just going to sort it out now, but we need a different solution for text orientation than hacking around with the transforms.

**Comment by ickshonpe** [comment]
<img width="961" alt="metallic" src="https://github.com/bevyengine/bevy/assets/27962798/537ec11c-1ea1-469c-8eec-2ad4ae012095">

**Comment by ickshonpe** [comment]
<img width="961" alt="scale" src="https://github.com/bevyengine/bevy/assets/27962798/dd04029d-8112-4fa5-89a2-56d7acab66df">

**Comment by ickshonpe** [comment]
> Text scaling also broken after the commit [0483b69]

Text scaling shouldn't really be used anyway as the glyphs textures will still be the original size was so the result will probably look really bad.
