### ISSUE TITLE
low_power example freezes

### ISSUE THREAD

**Issue by IceSentry** [bevyengine/bevy#11274]
## Bevy version

Bug started after https://github.com/bevyengine/bevy/pull/11245

## Relevant system information

```terminal
INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 4080", vendor: 4318, device: 9988, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "546.33", backend: Vulkan }
INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 10 Pro", kernel: "19045", cpu: "", core_count: "8", memory: "63.9 GiB" }
```

## What you did

`cargo run --example low_power`

## What went wrong

The example runs fine on startup, but as soon as I hit spacebar the window freezes.

**Comment by irate-devil** [comment]
I get the same result.

**Comment by nicopap** [comment]
* related: #11235
