### ISSUE TITLE
Add a "redirect" to the new plugin guidelines document

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#11272]
## What problem does this solve or what need does it fill?

The plugin guidelines that used to be in this repo were moved [here](https://bevyengine.org/learn/book/plugin-development/) in #11242, but many third party plugins linked to this document in their READMEs by way of their "bevy tracking badges."

[![Bevy tracking](https://img.shields.io/badge/Bevy%20tracking-released%20version-lightblue)](https://github.com/bevyengine/bevy/blob/main/docs/plugins_guidelines.md#main-branch-tracking)

Those existing links in other projects are now broken. (Some examples in the wild: [bevy_prototype_lyon](https://lib.rs/crates/bevy_prototype_lyon), [bevy-debug-text-overlay](https://lib.rs/crates/bevy-debug-text-overlay), [bevy_framepace](https://lib.rs/crates/bevy_framepace), [bevy_easings](https://lib.rs/crates/bevy_easings), [bevy_embedded_assets](https://lib.rs/crates/bevy_embedded_assets), [bevy_panorbit_camera](https://lib.rs/crates/bevy_panorbit_camera), [bevy_tweening](https://lib.rs/crates/bevy_tweening), [bevy_polyline](https://lib.rs/crates/bevy_polyline), [bevy_infinite_grid](https://lib.rs/crates/bevy_infinite_grid), [bevy_transform_gizmo](https://lib.rs/crates/bevy_transform_gizmo). Not comprehensive.)

Should we add a placeholder document in the old location that just links to the new document?

I have a separate issue open in the [bevy-website repo](https://github.com/bevyengine/bevy-website/issues/857) about the tags in the current document also having broken links. This issue is about old links in third party plugins being broken, and what we could do to fix that in this repo.

## What alternative(s) have you considered?

Do nothing about this in the Bevy repo. Leave the broken links broken. Maybe go on a quest to submit PRs to a bunch of plugin repos to fix them.

**Comment by alice-i-cecile** [comment]
Can you show me what those tracking badges look like? Your link doesn't seem correct.

We should definitely not host this in the main repo (the book is that right spot for discoverability), but I would like to avoid recreating a brittle link again.

**Comment by rparrett** [comment]
Oops. I mean to link to the "main track branching" section of the document, but was unable to because the new document doesn't have header anchors.

I am talking about these badges:
<img width="949" alt="image" src="https://github.com/bevyengine/bevy/assets/200550/cbd38c7e-8a42-4bd5-b97c-9d918d4ccfea">
([and one in the wild](https://github.com/fralonra/bevy-paperdoll))
<img width="908" alt="Screenshot 2024-01-09 at 12 35 44 PM" src="https://github.com/bevyengine/bevy/assets/200550/ce515aad-5051-4e90-b892-0e4e8b23adc1">

**Comment by rparrett** [comment]
Okay, improved the issue description. Sorry for the confusion.

**Comment by manankarnik** [comment]
I think we can go with the PR quest option. The change would be a single link in a README file.
For main tracking
```diff
- [![Bevy tracking](https://img.shields.io/badge/Bevy%20tracking-main-lightblue)](https://github.com/bevyengine/bevy/blob/main/docs/plugins_guidelines.md#main-branch-tracking)
+ [![Bevy tracking](https://img.shields.io/badge/Bevy%20tracking-main-lightblue)](https://bevyengine.org/learn/book/plugin-development/#main-branch-tracking#main-branch-tracking)
```
For released tracking
```diff
- [![Bevy tracking](https://img.shields.io/badge/Bevy%20tracking-released%20version-lightblue)](https://github.com/bevyengine/bevy/blob/main/docs/plugins_guidelines.md#main-branch-tracking)
+ [![Bevy tracking](https://img.shields.io/badge/Bevy%20tracking-released%20version-lightblue)](https://bevyengine.org/learn/book/plugin-development#main-branch-tracking)
```
In both cases, only the link needs to be updated.

We can also standardize the PR, like
> # Update bevy tracking link
> Bevy has moved its plugin guidelines to the Bevy Book on the website. As a result, the bevy tracking links are broken.
> See https://github.com/bevyengine/bevy/issues/11272

I could go ahead and draft a list of the projects on the assets page using the badge with the broken links if we're going ahead with this.

**Comment by rparrett** [comment]
Another option if going the PR quest route might be to remove the link entirely in favor of alt text.

Maybe this document is not a great landing spot for users clicking these badges. It is directly addressing the plugin author.

**Comment by manankarnik** [comment]
I can see 2 potential issues with that approach.
1. Even though intended for developers, the Main Branch Tracking section on the bevy website gives additional description/context for what the badge actually signifies. Maybe we can create a related issue stating that the Main Branch Tacking section of the document might be confusing for users as it is addressed directly to the plugin author instead, and suggest changes that would make sense when either is reading the section? (It is up to the bevy team to decide how to handle this)
2. As the plugin authors have decided to add the links themselves, they might consider it an unfavourable change if we replace the link with an alt text, and close the PRs/suggest changes which would be more work for us.

An alternative to consider is to create Issues instead, as well as suggest the two options. i.e. update the link or use alt text. The author can then decide what they want to go with. Though this method could take longer to fix the links and the author could simply ignore the issue in which case it is up to them how to deal with that.

**Comment by rparrett** [comment]
Agreed on both counts. It would be much easier to open issues that direct the repo owners to the new docs.

**Comment by rparrett** [comment]
I'm going to close this. I feel like opening github issues on active projects is the way to go, so there's nothing to be done in this repo.

If anyone's motivated to do / help do that, feel free to keep discussing here.

**Comment by manankarnik** [comment]
Alright, seems like this is indeed the best possible solution. Of course it would be a good practice to check the tracking links before opening issues to avoid false positives.

Here's a quick issue template I drafted, feel free to add to it or edit it if required.

> # Bevy tracking link in README badge is broken
>  ## Description
> Bevy has moved its plugin guidelines to the Bevy Book on the website. As a result, the bevy tracking link is broken. Willing to create a PR for the same if required.
> See https://github.com/bevyengine/bevy/issues/11272
> ## Possible Fixes
> - Update the tracking link in badge to https://bevyengine.org/learn/book/plugin-development/#main-branch-tracking
> - Provide a section in README explaining the badge and link to it
> - Remove the badge from README
> - Do nothing

## Checklist - Bevy community assets page categories
- [ ] 2D
- [ ] 3D
- [ ] AI
- [ ] Accessibility
- [ ] Animation
- [x] Asset Generation
- [ ] Asset Loading
- [ ] Audio
- [ ] Backends
- [ ] Camera
- [ ] Development tools
- [ ] Devices
- [ ] Helpers
- [ ] Input
- [ ] Networking
- [ ] Persistence
- [ ] Physics
- [x] Platform Integration
- [x] Scripting
- [ ] Shapes
- [x] Social
- [ ] Templates
- [ ] UI
- [x] Writing


I'll start creating issues in plugins from the 2D section for now.
