### ISSUE TITLE
2D Shapes Example does not compile

### ISSUE THREAD

**Issue by nwilson314** [bevyengine/bevy#11287]
# 2D Shapes Example does not compile

The 2D shapes example is missing some code (the compiler was actually very helpful here). During the spawning of the bundles, most of the shapes are missing an inner `.into()` call.

Code for the `setup()` function should be:

```rust
fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    commands.spawn(Camera2dBundle::default());
    
    // Circle
    commands.spawn(MaterialMesh2dBundle {
        mesh: meshes.add(shape::Circle::new(50.).into()).into(),
        material: materials.add(Color::PURPLE.into()),
        transform: Transform::from_translation(Vec3::new(-150., 0., 0.)),
        ..default()
    });

    // Rectangle
    commands.spawn(SpriteBundle {
        sprite: Sprite {
            color: Color::rgb(0.25, 0.25, 0.75),
            custom_size: Some(Vec2::new(50.0, 100.0)),
            ..default()
        },
        transform: Transform::from_translation(Vec3::new(-50., 0., 0.)),
        ..default()
    });

    // Quad
    commands.spawn(MaterialMesh2dBundle {
        mesh: meshes.add(shape::Quad::new(Vec2::new(50., 100.)).into()).into(),
        material: materials.add(Color::LIME_GREEN.into()),
        transform: Transform::from_translation(Vec3::new(50., 0., 0.)),
        ..default()
    });

    // Hexagon
    commands.spawn(MaterialMesh2dBundle {
        mesh: meshes.add(shape::RegularPolygon::new(50., 6).into()).into(),
        material: materials.add(Color::TURQUOISE.into()),
        transform: Transform::from_translation(Vec3::new(150., 0., 0.)),
        ..default()
    });
}
```

**Comment by nicopap** [comment]
It does compile.

if you `git clone https://github.com/bevyengine/bevy.git` and `cargo run --example 2d_shapes`, you'll notice it compile correctly. In fact, we have a fairly extensive CI setup to guarantee this doesn't occurs.

You might have tried to run a `main` example using the release bevy version. To get an example that compiles with the latest released version of bevy use the `latest` branch.

Here is a link the the 2d shape example that compiles on `0.12.1`: https://github.com/bevyengine/bevy/blob/latest/examples/2d/2d_shapes.rs

**Comment by nwilson314** [comment]
@nicopap Ahh yes this is exactly what happened. Thank you!
