### ISSUE TITLE
FixedTimestep should be exported in bevy::prelude

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1129]
This is common, useful functionality that will commonly be encountered by beginners. Timer is already in prelude, and it seems strange to have one without the other.

 Also the example in the 0.4 release notes doesn't compile as a result ;)

**Comment by KirmesBude** [comment]
In that case the RunOnce Criteria should also be exported in the prelude.

**Comment by alice-i-cecile** [comment]
Relevant to #1247

**Comment by james7132** [comment]
After schedule v3, `FixedTimestep` no longer exists. Closing this issue for now.
