### ISSUE TITLE
TEXTURE_BINDING_ARRAY required but not enabled on the device

### ISSUE THREAD

**Issue by atlasoft** [bevyengine/bevy#11299]
## How can Bevy's documentation be improved?

In the "getting started" page, instructions lead to clone the repo and "cargo run" the breakout example. However it is wasn't working. 

´´´
cargo run --example breakout
...
2024-01-11T14:42:51.532466Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon Graphics (radeonsi, renoir, LLVM 16.0.6, DRM 3.49, 6.1.71-1-lts)", vendor: 4098, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
2024-01-11T14:42:51.904746Z ERROR log: Handling wgpu errors as fatal by default    
thread 'main' panicked at /home/tokyo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.18.0/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_bind_group_layout
      note: label = `mesh_view_layout`
    Binding 14 entry is invalid
    Features Features(TEXTURE_BINDING_ARRAY) are required but not enabled on the device
´´´

Looking into wgpu crate for [TEXTURE_BINDING_ARRAY](https://docs.rs/wgpu/latest/wgpu/struct.Features.html#associatedconstant.TEXTURE_BINDING_ARRAY), it is mentioned that 
```
Supported platforms:
    DX12
    Metal (with MSL 2.0+ on macOS 10.13+)
    Vulkan
This is a native only feature.
```

So I suspected a missing package in the OS, so installed `extra/vulkan-radeon` and ran again, with success. 

I think it could be nice to have some hints about prerequisites on the documentation, for example here: 
Link: https://bevyengine.org/learn/book/getting-started/

It seems it only happens on HEAD: ce5bae55f64bb095e1516427a706a2622ccf2d23
Tried with v0.12.1 and package is not needed.

**Comment by mockersf** [comment]
this is new since https://github.com/bevyengine/bevy/pull/10057
