### ISSUE TITLE
startup time

### ISSUE THREAD

**Issue by coolit** [bevyengine/bevy#113]
A black and white background (this comes from winit I guess, but normally it should be totally white to look nicer)  would appear first, and then after about 1 sec the real content was displayed. Hopefully the startup time can be faster.
 
Please see the screenshot below for wni10:
![GIF](https://user-images.githubusercontent.com/13397709/89897914-5f9f0300-dc12-11ea-83a8-56b567b2f6c9.gif)

**Comment by cart** [comment]
Does this happen when you run in release mode?

```cargo run --example button --release```

Thats definitely much slower than what i experience

**Comment by coolit** [comment]
Sorry to mention. Yes, in release mode.

**Comment by cart** [comment]
Would you mind sharing your hardware configuration?

**Comment by coolit** [comment]
Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

**Comment by cart** [comment]
can you experience the same startup speeds when you run:
```
cargo run --example empty_defaults --release
```

**Comment by coolit** [comment]
I think it is pretty fast.
Please see the screenshot.
![GIF](https://user-images.githubusercontent.com/13397709/90000066-3f2e8180-dcc2-11ea-898f-1504e8de3e81.gif)

**Comment by Plecra** [comment]
Would it be possible to avoid creating the window until the application is ready to render something to it?

**Comment by alice-i-cecile** [comment]
Closing as this is not very actionable. Please feel free to open new issues with specific suggestions for fixes.
