### ISSUE TITLE
Better Debug support for Bevy ECS

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1130]
**What problem does this solve or what need does it fill?**

Debugging and troubleshooting ECS problems in 

**Describe the solution would you like?**

Derive Debug for query filters, World, App, AppBuilder etc.

**Describe the alternative(s) you've considered?**

Write custom wrappers every time to extract and then display the information that I care about each time that I'm debugging these parts of the core logic.

**Additional context**

Creating a sensible debug output for some of the larger objects (like App and World) seems challenging; a pattern for doing so in a more / less verbose fashion would be welcome.

**Comment by alice-i-cecile** [comment]
This is improved by #1525, with a Debug impl for World.

**Comment by targrub** [comment]
@alice-i-cecile  What remains to be coded to complete this issue for now?

**Comment by alice-i-cecile** [comment]
I would like debug impls for:

- `World`
- `App`
- `Query`
- `QueryState`

Once that's done I think we can close this out in favor of more specific issues.

**Comment by targrub** [comment]
I'll take a look to see if I can do any of those.

**Comment by alice-i-cecile** [comment]
WRT `App`, don't worry about doing anything fancy for the `Schedule`. We can and should wait until after the stageless rewrite settles.
