### ISSUE TITLE
Use `async fn` in trait instead of `BoxedFuture`

### ISSUE THREAD

**Issue by tguichaoua** [bevyengine/bevy#11308]
## What problem does this solve or what need does it fill?

`async fn` and return-position `impl Trait` in trait as been stabilized in `1.75` (https://github.com/rust-lang/rust/pull/115822/)

## What solution would you like?

Replace usage of `BoxedFuture` in traits like `AssetLoader` by `async fn`.

https://github.com/bevyengine/bevy/blob/ce5bae55f64bb095e1516427a706a2622ccf2d23/crates/bevy_asset/src/loader.rs#L33-L38

```rust
 async fn load<'a>( 
     &'a self, 
     reader: &'a mut Reader, 
     settings: &'a Self::Settings, 
     load_context: &'a mut LoadContext, 
 ) -> Result<Self::Asset, Self::Error>; 
```

## What alternative(s) have you considered?

Keep using `BoxedFuture` with `Box::pin(async move { /* */ });`.

## Current limitations

Because of the [send bound problem](https://smallcultfollowing.com/babysteps/blog/2023/02/01/async-trait-send-bounds-part-1-intro/), there is no way, yet, to add the `Send` bound on the returned future.
Alternatively it's possible to use `impl Future + Send`:
```rust
 fn load<'a>( 
     &'a self, 
     reader: &'a mut Reader, 
     settings: &'a Self::Settings, 
     load_context: &'a mut LoadContext, 
 ) -> impl Future<Output = Result<Self::Asset, Self::Error>> + Send + 'a; 
```

**Comment by james7132** [comment]
This was implemented in #12550 and follow-up PRs.
