### ISSUE TITLE
Fix and reimplement reflection probes

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11315]
Fix for reflection probes should be pretty simple. I believe we just need to add a check if the render device supports the texture binding array feature, rather than a conditional cfg for non wasm platforms.

_Originally posted by @JMS55 in https://github.com/bevyengine/bevy/issues/11307#issuecomment-1888088750_
            
Unfortunately https://github.com/bevyengine/bevy/pull/10057 broke several platforms. Revert the revert, then add a commit to fix the broken platforms on top.

**Comment by JMS55** [comment]
Closed by https://github.com/bevyengine/bevy/pull/11366
