### ISSUE TITLE
Animated GLTF models are incorrectly culled.

### ISSUE THREAD

**Issue by AxiomaticSemantics** [bevyengine/bevy#11314]
## Bevy version
0.9 -> 0.13

## What went wrong

Animated GLTF files do not update AABB's GPU-side leading to parts of models being incorrectly culled.
This can be worked around by adding a `NoFrustumCulling` component.

**Comment by nicopap** [comment]
Relevant: https://github.com/bevyengine/bevy/issues/4971

**Comment by nicopap** [comment]
duplicate
