### ISSUE TITLE
New warning message in WASM builds - possibly associated with inconsistent rendering issues.

### ISSUE THREAD

**Issue by miketwenty1** [bevyengine/bevy#11317]
## Bevy version
main - commit: https://github.com/bevyengine/bevy/commit/64a15f1b10ff5a4c0cb2ada1905baeb7125d16e4

`cargo 1.74.0 (ecb9851af 2023-10-18)`
MacBook Pro: macOS Ventura 13.3.1

Web browser console:
`
INFO .../.cargo/git/checkouts/bevy-f7ffde730c324c74/64a15f1/crates/bevy_render/src/renderer/mod.rs:144 AdapterInfo { name: "ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)", vendor: 4203, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
`

`
WARN .../.cargo/git/checkouts/bevy-f7ffde730c324c74/64a15f1/crates/bevy_pbr/src/ssao/mod.rs:92 ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
`

## What went wrong
New Warning in Web browser console and sometimes my game doesn't spawn the base map of the game. Have noticed this starting today while using latest commits.

**Comment by JMS55** [comment]
@alice-i-cecile I can't rename the issue, but the warning has been there since we added SSAO, it's just saying you can't attempt to use the SSAO plugin. 

As for the user's error, no idea, not enough info to go off of.

**Comment by miketwenty1** [comment]
You are correct I test several commits and and realized the WARN has been around for awhile. I'm also not sure what was causing the issues and the ability to reproduce is wildly inconsistent and uncommon. I'm going to close this issue for now.

Quick Followup @JMS55 .. Is this WARN safe to ignore long term?

**Comment by JMS55** [comment]
Yes, you can ignore it unless you plan to use ScreenSpaceAmbientOcclusionPlugin. It's simply stating that your GPU/target platform does not support features necessary to use the plugin.
