### ISSUE TITLE
See if removing a vec allocation in animation code improves performance

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11328]
do we need to make a whole new vec or can we just add/remove elements until the len is the same?

_Originally posted by @rodolphito in https://github.com/bevyengine/bevy/pull/11306#discussion_r1451151181_
            
This wasn't part of my PR, so I didn't change it there :)

**Comment by nicopap** [comment]
To quote myself

> It's possible to do a `clear()` followed by an `extend(…)`. The `Vec::new` here doesn't cause an allocation until something is pushed to it.

**Comment by nicopap** [comment]
I think I might have been misunderstood. the code in question is:

```rust
        animation.path_cache = vec![Vec::new(); animation_clip.paths.len()];
```
In this, we have to `Vec` constructors (1) `vec![…]`, (2) `Vec::new()`, (2) doesn't allocate, while (1) will probably.

Replacing the code by

```rust
        let new_len = animation_clip.paths.len();
        animation.path_cache.clear();
        animation.path_cache.extend((0..new_len).map(|_| Vec::new()));
```
Will likely result in better code generation.

**Comment by nicopap** [comment]
I'm an idiot, I misunderstood what the comment referred to. I've a PR coming where allocation is minimized as much as possible. What I suggest **isn't the optimal solution**.
