### ISSUE TITLE
Spawning a child TextBundle causes panic

### ISSUE THREAD

**Issue by suo** [bevyengine/bevy#1134]
**Bevy version**

0.4

**Operating system & version**

MacOS Big Sur (11.1)

**What you did**

Created a child entity with a `TextBundle`. Minimal repro:

```
use bevy::prelude::*;

struct Person;

fn setup(commands: &mut Commands) {
    commands
        .spawn(CameraUiBundle::default())
        .spawn((Person,))
        .with_children(|parent| {
            parent.spawn(TextBundle::default());
        });
}

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup.system())
        .run();
}
```
**What you expected to happen**

I expect the entities to be created, with the correct parent-child relationships.
**What actually happened**
Bevy panics. Stacktrace here:
https://gist.github.com/suo/c47a5695bfd036d6feff75c98734253b

**Comment by suo** [comment]
From the code, it looks like we expect the parents of every Node to be a Node in the layout engine? I just started playing with Bevy today, and I wanted to associate an entity with a bit of text (like a name rendered below a character's sprite). But it looks like I'm using the flexbox UI unintentionally here instead of…something else.

So perhaps this is user error—although I suppose the panic could be replaced by something more informative.

**Comment by TheRawMeatball** [comment]
You might want to look at this: #971

**Comment by Moxinilian** [comment]
Yeah this seems to be a recurring issue, thanks for the report. I'm closing this issue in favor of #971, please tell us if you think this one should stay open!

**Comment by suo** [comment]
Thanks folks!
