### ISSUE TITLE
Rendering to a Image no longer works since #10520

### ISSUE THREAD

**Issue by doonv** [bevyengine/bevy#11343]
## Bevy version

https://github.com/bevyengine/bevy/commit/44424391fe217d9b0b4b0be2649b44a994983a59

## What you did

I updated my library [bevy_smooth_pixel_camera](https://github.com/doonv/bevy_smooth_pixel_camera)  to https://github.com/bevyengine/bevy/commit/44424391fe217d9b0b4b0be2649b44a994983a59 (I know that it's caused by this exact commit)

## What went wrong

The viewport texture is no longer updated unless I move my cursor or resized the window.

This means **the viewport texture is not getting updated by the world camera** (Which is supposed to render to that texture via `RenderTarget::Image`). It updates when I move my cursor because of my `update_viewport_size` system, which only runs when the `Window` is changed. This system, among other things, resizes the viewport texture with `Image::resize`. And that appears to make the texture update for some reason.

## Additional information

[Here is the source code that reproduces this issue](https://github.com/doonv/bevy_smooth_pixel_camera/blob/temp-debug-update/src/systems.rs#L134).

**Comment by mockersf** [comment]
duplicate of https://github.com/bevyengine/bevy/issues/11240

**Comment by doonv** [comment]
Ah my bad
