### ISSUE TITLE
feature request: Enable/disable ANSI or colored output logging

### ISSUE THREAD

**Issue by simbleau** [bevyengine/bevy#11351]
## What problem does this solve or what need does it fill?

Some targets support ANSI, but the logs are aggregated into a source that doesn't, e.g. DataDog or AWS CloudWatch.

Specifically, I use CloudWatch on AWS, where ANSI is not supported.

Enter, this:
<img width="1700" alt="image" src="https://github.com/bevyengine/bevy/assets/48108917/18dc2936-9384-4c21-8d97-1e031d9f7c35">

## What solution would you like?

Additional field on LogPlugin:

```text
LogPlugin {
    filter,
    level,
    colored: true (default)
}
```

## What alternative(s) have you considered?

Without this, you have to install your own tracing subscriber and things get complicated with lots of cfg directives.

**Comment by mgi388** [comment]
I wonder if `NO_COLOR` / https://no-color.org/ is something to consider here?

**Comment by simbleau** [comment]
> I wonder if `NO_COLOR` / https://no-color.org/ is something to consider here?

This is a good option, I would prefer this.

**Comment by mockersf** [comment]
already supported by the logging library
