### ISSUE TITLE
`bevy_ui` does not compile without `bevy_text` feature

### ISSUE THREAD

**Issue by chrisjuchem** [bevyengine/bevy#11363]
## Bevy version

main (`ee9a1503edb6ff72cc69514c6336d9f624f0d600`)

## What you did
Run `cargo build -p bevy_ui`

## What went wrong

```
   Compiling bevy_ui v0.12.0 (/home/chrisjuchem/bevy/crates/bevy_ui)
error[E0425]: cannot find value `text_system` in module `widget`
   --> crates/bevy_ui/src/lib.rs:200:45
    |
200 |                     .ambiguous_with(widget::text_system),
    |                                             ^^^^^^^^^^^ not found in `widget`

error[E0425]: cannot find value `text_system` in module `widget`
   --> crates/bevy_ui/src/lib.rs:207:45
    |
207 |                     .ambiguous_with(widget::text_system),
    |                                             ^^^^^^^^^^^ not found in `widget`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `bevy_ui` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

## Additional information

Looks like this system only exists behind the `bevy_text` feature, but the ambiguity declaration was not put behind the same feature in #10411.
Building succeeds with `cargo build -p bevy_ui --features bevy_text`.

**Comment by nicoburns** [comment]
This just needs feature flagging. But it is a recurrent problem as a top-level build/test of bevy enable text by default and thus doesn't exercise this case (building only the bevy_ui crate does). Perhaps we should add a CI check for this?

**Comment by BD103** [comment]
My first thoughts are to feature flag it something like this, but it could be confusing:

```rust
{
    let system = ui_stack_system
        .in_set(UiSystem::Stack)
        // the systems don't care about stack index
        .ambiguous_with(update_clipping_system)
        .ambiguous_with(resolve_outlines_system)
        .ambiguous_with(ui_layout_system);

    #[cfg(feature = "bevy_text")]
    let system = system.ambiguous_with(widget::text_system);

    system
},
```

Any thoughts are making it easier to read?
