### ISSUE TITLE
Some examples need tweaks after new exposure settings

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#11376]
## Bevy version

main, since #11347 

## What you did

Caught by https://thebevyflock.github.io/bevy-example-runner/

## What went wrong

The following all seem much darker than intended:

- [ ] `render_ui_to_texture`
- [ ] `asset_loading`
- [ ] `hot_asset_reloading`

**Comment by JMS55** [comment]
@GitGhillie any interest in doing these 3 as well?

**Comment by GitGhillie** [comment]
Sure! I'll get to them after work today

**Comment by GitGhillie** [comment]
Thx for checking @rparrett! That example runner tool is great.
