### ISSUE TITLE
Panic range end index out of range, write_uniform_buffers

### ISSUE THREAD

**Issue by payload** [bevyengine/bevy#1138]
bevy 0.4.0 ubuntu 20.04
Happens intermittently. No minimal reproducer though I can send in a version of a project. 

```
thread 'main' panicked at 'range end index 16992 out of range for slice of length 1024',
/home/payload/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.4.0/src/render_graph/nodes/render_resources_node.rs:329:26
```

In write_uniform_buffers at

```
render_resource.write_buffer_bytes(
    &mut staging_buffer[self.current_staging_buffer_offset
        ..(self.current_staging_buffer_offset + size)],
);
```

**Comment by DJMcNab** [comment]
Direct code link:
https://github.com/bevyengine/bevy/blob/61ce3f7bcfbff808f2eb51e914f03d3807a8f92a/crates/bevy_render/src/render_graph/nodes/render_resources_node.rs#L328-L331

**Comment by tommygoris** [comment]
Might be related to #1056, which happens when the buffers are incorrectly resized due to the wrong item_size of the buffer array.

**Comment by programWhiz** [comment]
this is happening for me as well, same thing.  Mixture of Tilemap plus sprites, happens about 50% of the time, but if it makes it through a few frames, its seems fine (must be some random ordering or something that causes it).

**Comment by rmsc** [comment]
Could you please try #1509?

**Comment by james7132** [comment]
With #1509 merged, and `RenderResource::write_buffer_bytes` no longer existing, is this issue still relevant?
