### ISSUE TITLE
WGSL material example crash

### ISSUE THREAD

**Issue by 1ADIS1** [bevyengine/bevy#11384]
## Bevy version

0.12.1

## \[Optional\] Relevant system information

- cargo 1.74.0-nightly (2fc85d15a 2023-09-09)
- Windows 10

```ignore
`AdapterInfo { name: "AMD Radeon(TM) Graphics", vendor: 4098, device: 5686, device_type: IntegratedGpu, driver: "AMD proprietary driver", driver_info: "20.10.22.14", backend: Vulkan }`
```

## What you did

I have copied the material wgsl shader example, including the [shader](https://github.com/bevyengine/bevy/blob/main/assets/shaders/custom_material.wgsl) and [rust code](https://bevyengine.org/examples-webgpu/Shaders/shader-material/), and pasted them without changing anything. 

## What went wrong

I was expecting to observe working shader, but I've got Validation Error.

```
Caused by:
    In Device::create_render_pipeline
      note: label = `alpha_blend_mesh_pipeline`
    Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
    Shader global ResourceBinding { group: 2, binding: 2 } is not available in the layout pipeline layout
    Binding is missing from the pipeline layout
```

## Additional information

I have also copied some other examples, like animated [shader](https://bevyengine.org/examples-webgpu/Shaders/animate-shader/), and it was working properly, so I think, the problem is in the material wgsl shader example on bevy website.

![image](https://github.com/bevyengine/bevy/assets/60191045/f04e751c-5f5c-418b-acd2-6da0881a2a09)

**Comment by 1ADIS1** [comment]
I have observed the same crash in the [custom vertex attribute example](https://bevyengine.org/examples-webgpu/Shaders/custom-vertex-attribute/).

The problem is in the index of the group in the .wgsl file. I had to replace group index from 2 to 0.

```
@group(0) @binding(0) var<uniform> material: CustomMaterial;
```

For the [wgsl material example](https://bevyengine.org/examples-webgpu/Shaders/shader-material/), I had to replace group index from 2 to 1.

```
@group(1) @binding(0) var<uniform> material_color: vec4<f32>;
@group(1) @binding(1) var material_color_texture: texture_2d<f32>;
@group(1) @binding(2) var material_color_sampler: sampler;
```

**Comment by mockersf** [comment]
The example from the `main` branch on git are updated with the in-development version of Bevy.

For the 0.12.1 version, you should copy from the `release-0.12.1` branch: https://github.com/bevyengine/bevy/blob/release-0.12.1/assets/shaders/custom_material.wgsl

**Comment by 1ADIS1** [comment]
Got it, thank you!
