### ISSUE TITLE
Panic on ui without Cameras

### ISSUE THREAD

**Issue by pablo-lua** [bevyengine/bevy#11396]
## Bevy version

ea42d14 -> At least I think so. Well, for sure after Camera driven Ui

## What you did

```rust
fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup_camera)
        .run();
}

pub fn setup_camera(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(TextBundle::from_section(
        "My text",
        TextStyle {
            font: asset_server.load("font.ttf"),
            font_size: 24.,
            color: Color::WHITE,
        },
    ));
}
```

## What went wrong

- The code panics without cameras
- This panic doesn't occur if I use a NodeBundle, so it is only expected that the panic doesn't happen with TextBundle

## Additional information

This is the panic:
![image](https://github.com/bevyengine/bevy/assets/126117294/de860e65-2b7a-435a-90cd-c5e926181d52)
It leads to the function `UiSurface::update_measure`, which does an unsafe unwrap. The problem are the types with ContentSize component, they will all lead to this error.

**Comment by alice-i-cecile** [comment]
Ideally we emit a debounced warning for this. But panicking is bad and we should avoid it.

**Comment by doonv** [comment]
This only happens when a valid font is loaded. If `font.ttf` does not exist it shows a warning and does not panic.

**Comment by doonv** [comment]
`measure_text_system` might be the thing causing the issue.

**Comment by pablo-lua** [comment]
Useful to know. So this problem doesn't happens with UiImage? I didn't tested that part

**Comment by doonv** [comment]
I think I found the problem.
```rs
// In ui_layout_system

    // Resize all nodes
    for (entity, style, target_camera) in style_query.iter() {
        if let Some(camera) =
            camera_with_default(target_camera).and_then(|c| camera_layout_info.get(&c))
        {
            if camera.resized
                || !scale_factor_events.is_empty()
                || ui_scale.is_changed()
                || style.is_changed()
            {
                let layout_context = LayoutContext::new(
                    camera.scale_factor,
                    [camera.size.x as f32, camera.size.y as f32].into(),
                );
                ui_surface.upsert_node(entity, &style, &layout_context);
            }
        }
    }
```
If the `Some(camera)` pattern doesn't match, the ui_surface doesn't get the node properly, causing the unwrap later to fail.
