### ISSUE TITLE
Allow access to resource change ticks by resource id

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#11390]
## What problem does this solve or what need does it fill?

For building reactive systems that update in response to changing resources, we need to be able to detect whether a resource has changed - but the current API requires that you know the resource type. This is very cumbersome when dealing with type-erased resources, it means that instead of keeping around just the resource ids in a table, you have to create a bunch of dyn trait objects to check for changes to each type.

## What solution would you like?

Simply expose a World method such as `.is_resource_id_changed()` or possibly `.get_resource_change_ticks()`. (The latter is slightly preferred, having both would be nice).

## What alternative(s) have you considered?

The current solution involves making a boxed dyn trait object that contains a call to `.is_changed()`.

**Comment by alice-i-cecile** [comment]
Happy to see this sort of API exposed. We should check that equivalent APIs exist for components, and link between them.

**Comment by viridia** [comment]
Yes, components already have this: https://docs.rs/bevy/latest/bevy/ecs/world/struct.EntityMut.html#method.get_change_ticks_by_id
