### ISSUE TITLE
Add an example demonstrating how to modify the main schedule order

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11411]
## How can Bevy's documentation be improved?

Custom schedules can be added by users, and the order of the `Main` schedule can be changed to meet their needs.

However, the path used to do so is not obvious.

To insert a schedule, mutate the `Schedules` resource. Then, mutate the `MainSchedule` resource to set its ordering.

We should add an example demonstrating how to do this, and spot check the related API docs.

**Comment by Malax** [comment]
I'd like to tackle this if no one else is currently working on it!

**Comment by alice-i-cecile** [comment]
Awesome, thanks!
