### ISSUE TITLE
Environment map not working when using deferred rendering

### ISSUE THREAD

**Issue by DGriffin91** [bevyengine/bevy#11414]
## Bevy version 056b006d4eade8f1bf75e735ed5eda33d9505c9e

The deferred rendering example is missing environment map when set to use deferred.

The issue was introduced at 839d2f83536028386f270fea957f7057910fd536 with #11152

![b](https://github.com/bevyengine/bevy/assets/33357138/901228eb-fd9d-4dd0-8ff2-c10f7ad6e838)
![a](https://github.com/bevyengine/bevy/assets/33357138/d91b5c28-5e8d-43d0-8507-5f99d3cb8a6d)

**Comment by JMS55** [comment]
Oh btw, did we document anywhere that specular occlusion doesn't work on webgl2, and it'll use diffuse instead? If not, please add that to the StandardMaterial docs.
