### ISSUE TITLE
Use less confusing terminology for string parts in `DiagnosticPath`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11438]
Nit: can we swap "components" here to "parts" to be less confusing in a Bevy context?

_Originally posted by @alice-i-cecile in https://github.com/bevyengine/bevy/pull/9266#discussion_r1460005281_

**Comment by capt-glorypants** [comment]
I'll do it.

**Comment by mockersf** [comment]
Components is the standard way to decompose a path.

We could rename `DiagnosticPath` to `DiagnosticKey`, then use another word like section?

Alternatively, we could revert #9266 and model bevy_diagnostics on a time series database as that's pretty much what it is and most of them have moved away from using paths

**Comment by alice-i-cecile** [comment]
I don't think this is worth bikeshedding over. Going to close this and the linked PR as won't fix.

Working towards a time series model seems like a fine avenue to explore, but I don't have strong feelings there (as long as we can still support the use cases described in #9216).
