### ISSUE TITLE
Cursor position should reset when exiting a window.

### ISSUE THREAD

**Issue by visualcode-t** [bevyengine/bevy#1143]
**Bevy version**

0.4.0

**Operating system & version**

Windows 10

**What you did**

After placing multiple `ButtonBundle`s which change on `Interaction` I removed my cursor from the screen and began to resize the window.

**What you expected to happen**

I expect that the currently hovered `ButtonBundle` lose its hover.

**What actually happened**

Not only does the currently hovered `ButtonBundle` remain hovered, but, it also transfers that hover to other `ButtonBundle`s as the window resizes, if those buttons move to where the mouse had been.

**Additional information**

When the window is resized, I have the buttons scale and move to match the new window size. So, the placement and size of the buttons does move around.

**Comment by DJMcNab** [comment]
I think this should be fixed by #3926. If that's not correct, please comment and someone will re-open this (or re-open it if you have permissions to).
