### ISSUE TITLE
Use palette crate for color handeling (color spaces and conversions)

### ISSUE THREAD

**Issue by LU15W1R7H** [bevyengine/bevy#1146]
**What problem does this solve or what need does it fill?**

Most libraries which do some kind of rendering (which bevy surely does) are in need of having different color types, color spaces and color conversions to their disposal. Instead of implementing all of these again for bevy, I'd suggest using an already existing crate exactly made for this purpose.
I'm talking about [palette](https://github.com/Ogeon/palette). I'm not the maintainer or a contributor (so far) to this project, but I have been using palette before and enjoyed it's API. The Amethyst game engine also uses palette for handling colors.

***Palette provides the following***

The color types / spaces `Srgb`, `LinSrgb`, `Hsv`, `Hsl`, `Lab`, `Lch` and conversions between them and manipulation of the colors (`saturate`, `darken`, `blend` etc.). Palette provides a lot more but since I don't understand anything else, I don't dare to mention or describe it here.

**Describe the solution would you like?**

Drag in `palette` as a dependency of `bevy_render` and create some `pub use` re-exportes and integrate in tightly into bevy_render.  Maybe create some PRs in palette to fullfille additional needs of bevy or just write some helpers in bevy_render.

**Describe the alternative(s) you've considered?**

Use some other library.
Write own color handling in bevy_render.

**Comment by cart** [comment]
Definitely worth discussing! Theres some relevant discussion in #585

**Comment by LU15W1R7H** [comment]
There was some concern in the issue you mentioned about pulling in a new dependency with +10k lines.
Would it help to introduce more cargo features to palette to ensure that bevy only enables those which are really needed? I'm not quite sure what's the most concering about having anohter dependency, but I thought that having more features would at least solve the problem of compiing unnecessary code. There are other disadvantages, like having to download this crate for compiling bevy, but this might solve at least some problems.

**Comment by alice-i-cecile** [comment]
[colorgrad](https://github.com/mazznoer/colorgrad-rs) looks like another serious option to consider.

**Comment by nicopap** [comment]
There has been a lot of discussion around color handling

* <https://github.com/bevyengine/bevy/pull/1870>
* <https://github.com/bevyengine/bevy/discussions/1849>
* <https://github.com/bevyengine/bevy/discussions/4648>

To me, #4648 means the answer is "won't use an external crate". And in fact, since then, bevy pretty much relies on an internal color representation. Should this be closed?
