### ISSUE TITLE
Replace collision code in breakout example with code based `Aabb2d::intersects`

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#11479]
## What problem does this solve or what need does it fill?

After #11439, it seems like it might be possible to nuke the [breakout example](https://github.com/bevyengine/bevy/blob/main/examples/games/breakout.rs)'s custom collision code.

The breakout example makes use of [`bevy::sprite::collide_aabb::collide`](https://github.com/bevyengine/bevy/blob/6a3b059db917999b15ca032a4cab8cd31569b896/crates/bevy_sprite/src/collide_aabb.rs) which exists in Bevy solely to make this particular example work.

The current collision code also assumes that the ball is a rectangle, which is no longer true!

## What solution would you like?

Replace the code in `breakout` with code based on the new bounding volume intersection stuff introduced in #11439 and remove `bevy::sprite::collide_aabb::collide` from Bevy.

`breakout` is relying on `collide_aabb::collide` determining "which side of the thing was collided with," so this is slightly more involved than it sounds on the surface.

## What alternative(s) have you considered?

Maybe I've misjudged and it's not time for this yet.

**Comment by rparrett** [comment]
Pinging @Jondolf for an opinion.

**Comment by alice-i-cecile** [comment]
IMO we should remove the `aabb` methods from `bevy_sprite` as part of the same PR.

**Comment by Jondolf** [comment]
Yes, I agree we should remove the AABB and collision stuff from `bevy_sprite` and move `collide` to the breakout example.

`Aabb2d` can be used to replace `CollisionBox`, and `intersects` can be used for the initial intersection check, but the side-detection logic will still need to be done manually
