### ISSUE TITLE
Screenshot is never taken if AppExit is sent

### ISSUE THREAD

**Issue by banool** [bevyengine/bevy#11494]
## Bevy version

0.12.1

## Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
  - cargo 1.75.0 (1d8b05cdd 2023-11-20)
- the operating system or browser used, including its version
  - MacOS 14.2.1 (M1 ARM)

## What you did

Here's a minimal version of my program:
```rust
fn main() {
        let mut app = App::new();
        app.add_plugins(DefaultPlugins.build()/*.disable::<WinitPlugin>()*/);
        app.add_systems(Update, capture_frame);
}

fn capture_frame(
    main_window: Query<Entity, With<PrimaryWindow>>,
    mut screenshot_manager: ResMut<ScreenshotManager>,
    mut exit: EventWriter<AppExit>,
) {
    eprintln!("Taking screenshot");
    screenshot_manager.save_screenshot_to_disk(main_window.single(), "/tmp/screenshot.png").expect("Failed to take screenshot to disk");
    eprintln!("Took screenshot");
    exit.send(AppExit);
```
## What went wrong

As described, `exit.send(AppExit)` shuts down the app at the start of the next scheduling tick. Unfortunately, this means the screenshot is never taken. If I remove `exit.send` the screenshot is taken.

I would sort of expect taht there would be some Drop impl that takes the screenshot on shutdown.

## Additional Information
As you might be able to guess from https://github.com/bevyengine/bevy/issues/11493 as well, my high level intention is to run a Bevy app for a single rendering frame, take a screenshot, and then exit it (and then ultimately return that data as an image via an API but that's an aside).

**Comment by banool** [comment]
I've tried things like this btw:
```rust
let mut app = app_config.build(None, Some(CaptureConfig { sender }));
app.finish();
app.cleanup();
loop {
    app.update();
}
```

But the window never appears and the screenshot is never taken. I assume some init that Winit would normally do doesn't occur if I don't call `run`.

**Comment by rparrett** [comment]
`screenshot_manager.save_screenshot_to_disk` is only adding a screenshot request to a queue. The actual process of  saving a screenshot takes an arbitrary amount of time, so it is done in the `AsyncComputeTaskPool` where it won't block the execution of an app.

`take_screenshot` also runs its callback on the `AsyncComputeTaskPool`, but you have a little more control if you use it instead. Here's a very quick and dirty adaptation of the `screenshot` example using a channel to pass a message when the screenshotting is finished and exiting the app: https://gist.github.com/rparrett/090b85ce5b49bf8c6c35b96cc42d0c4a

**Comment by banool** [comment]
Awesome, that works a treat.

One complication with this is it seems like `exit.send(AppExit)` doesn't just exit the bevy app, but seems to exit the entire process. I gave an oversimplified example but in reality I'm trying to run the Bevy app for one frame, grab an image, then return it via an API. I can't do that if Bevy exits the whole process :/

But the code you gave does fix the problem I originally raised in the issue.

**Comment by banool** [comment]
Okay actually `return_from_run` does seem to do the trick, it means `exit.send(AppExit)` doesn't kill the whole process, just the app. Great!

**Comment by banool** [comment]
I'm asking about this next problem here: https://github.com/bevyengine/bevy/discussions/11496.
