### ISSUE TITLE
MouseMotion and CursorMove have subtle differences in position on Windows(one affected by mouse acceleration settings and the another not)

### ISSUE THREAD

**Issue by AllenPocketGamer** [bevyengine/bevy#1149]
**Bevy version**

0.4.0

**Operating system & version**

Windows 10

**What I did**

I create a program that will store the cursor position in a variable named anchor_point when I click the mouse left button;

The program will accumulate MouseMotion.delta to a variable named anchor_offset when keep pressing the mouse left button;

Because of MouseMotion is the difference between the mouse position in the two frames, so the following equation should hold: 
`anchor_offset = current_cursor_position - anchor_point`, but it is not.

The deviation(anchor_offset - (current_cursor_position - anchor_point)) is too big to be ignored.

This is very strange, because in most game engines, the equation(`MouseMotion.delta = current_cursor_position - last_cursor_position`) should be true(even if there is an deviation, it should not be so large).

(Maybe the program comes from winit crate, I guess.) 

**The Demo Code**

```Rust
use bevy::{input::mouse::MouseMotion, prelude::*};

// NOTE: Press MouseButton::Left to create a anchor point;
fn main() {
    App::build()
        .add_resource(WindowDescriptor {
            width: 1280f32,
            height: 720f32,
            ..Default::default()
        })
        .add_plugins(DefaultPlugins)
        .add_system(mouse_input.system())
        .run();
}

fn mouse_input(
    mut state: Local<State>,
    wnds: Res<Windows>,
    mouse_button_input: Res<Input<MouseButton>>,
    mouse_motion_events: Res<Events<MouseMotion>>,
) {
    let wnd = wnds.get_primary().unwrap();

    let cursor_position = wnd.cursor_position().unwrap_or_default();
    let mut sum_of_mouse_motion_delta = Vec2::zero();

    for event in state.mouse_motion_event_reader.iter(&mouse_motion_events) {
        sum_of_mouse_motion_delta += (event as &MouseMotion).delta;
    }

    if mouse_button_input.just_pressed(MouseButton::Left) {
        state.is_click = true;
        state.anchor_point = cursor_position;
        state.anchor_offset = Vec2::zero();
    } else if mouse_button_input.just_released(MouseButton::Left) {
        state.is_click = false;
    }

    if state.is_click {
        // NOTE: because of different coordinate (MouseMotion is in top-left
        // coordinate, Cursor Postion is in lower-left coordinate)
        state.anchor_offset += Vec2::new(sum_of_mouse_motion_delta.x, -sum_of_mouse_motion_delta.y);

        // FIXME: According to general expectations, the following equation
        // should hold: anchor_offset = cursor_position - anchor_point;
        // FIXME: But in fact, the deviation is very large!
        let anchor_offset_expected = cursor_position - state.anchor_point;
        let anchor_offset_calculated = state.anchor_offset;
        let deviation = anchor_offset_expected - anchor_offset_calculated;
        println!("anchor offset expected: {}", anchor_offset_expected);
        println!("anchor offset calculated: {}", anchor_offset_calculated);
        println!("deviation: {}",deviation);
        println!("--------");
    }
}

#[derive(Default)]
struct State {
    mouse_motion_event_reader: EventReader<MouseMotion>,

    is_click: bool,
    anchor_point: Vec2,
    anchor_offset: Vec2,
}

```

-----------------------------------------------------------------------------------
UPDATE
-----------------------------------------------------------------------------------
I finally figured out why the problem happened!

* The data(position) in winit::event::WindowEvent::CursorMove comes from Windows message: WM_MOUSEMOVE, 
    which is affected by the mouse settings in Control Panel;
* The data(delta) in winit::event::DeviceEvent::MouseMotion comes from Windows message: WM_INPUT(which contains raw input mouse events),
    in contrast to the legacy WM_MOUSEMOVE window message, Raw Input mouse events are not subject to the effect of the mouse speed set in the Control Panel's Mouse Properties sheet.

* Just follow the instructions below to change the mouse settings to solve the problem.
    (https://www.tomshardware.com/news/how-to-disable-mouse-acceleration-windows,36886.html)

**What I want**

* I think bevy should provide comments for InputEvent to inform users of the nuances of use, which can save users a lot of time.
* At the same time, I think bevy should provide InputEvent CursorMotion to distinguish MouseMotion.

**One more question**
* The bevy_input doesn't look like an idiomatic way to process the input message;
    To be honest, handling input events in bevy is very verbose, cumbersome and difficult to understand;
    Generally speaking, we prefer this usage to handle input events:

    ```Rust
    fn input_event_handler(input_device: Res<InputDevice>) {
        // About Mouse Device
        let mouse_position = input_device.mouse.position;
        let mouse_motion = input_device.mouse.motion;

        if input_device.mouse.just_pressed(MouseButton::Left) {
            // do something
        }

        if input_device.mouse.just_released(MouseButton::Left) {
            // do something
        }

        if input_device.mouse.pressed(MouseButton::Left) {
            // do something
        }
        ...

        // About Keyboard Device
        if input_device.keyboard.just_pressed(KeyCode::F) {
            // do something
        }

        if input_device.keyboard.just_released(KeyCode::F) {
            // do something
        }

        if input_device.keyboard.pressed(KeyCode::F) {
            // do something
        }
        ...

        // About Gamepad Device
        ...

        // About Touch Device
        ...
    }
    ```

* So the question which I want to ask is whether there are any follow-up plans to make bevy_input crate more idiomatic?
@DJMcNab @mockersf

**Comment by DJMcNab** [comment]
I made a more visual program to try to reproduce:
<details>
  <summary>Code hidden</summary>

  I make a red dot at `anchor_point`, and a green dot following `anchor_offset`.

```rust
use bevy::{input::mouse::MouseMotion, math::vec3, prelude::*};

// NOTE: Press MouseButton::Left to create a anchor point;
fn main() {
    App::build()
        .add_resource(WindowDescriptor {
            width: 1280f32,
            height: 720f32,
            ..Default::default()
        })
        .init_resource::<State>()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup.system())
        .add_stage_after(
            stage::UPDATE,
            "serial_update",
            SystemStage::serial()
                .with_system(position_reset.system())
                .with_system(update_offset.system())
                .with_system(log_offset.system()),
        )
        .run();
}

struct AnchorPoint;
struct ExpectedPoint;

fn setup(commands: &mut Commands, mut materials: ResMut<Assets<ColorMaterial>>) {
    commands
        // 2d camera
        .spawn(Camera2dBundle::default())
        .spawn(SpriteBundle {
            sprite: Sprite::new(Vec2::new(1., 10.)),
            material: materials.add(Color::rgb_u8(255, 0, 0).into()),
            ..Default::default()
        })
        .with(AnchorPoint)
        .spawn(SpriteBundle {
            sprite: Sprite::new(Vec2::new(1., 10.)),
            material: materials.add(Color::rgb_u8(0, 255, 0).into()),
            ..Default::default()
        })
        .with(ExpectedPoint);
}

fn position_reset(
    mouse_button_input: Res<Input<MouseButton>>,
    windows: Res<Windows>,
    mut state: ResMut<State>,
    mut icon: Query<&mut Transform, Or<(With<AnchorPoint>, With<ExpectedPoint>)>>,
) {
    if mouse_button_input.just_pressed(MouseButton::Left) {
        if let Some(primary) = windows.get_primary() {
            if let Some(real_pos) = primary.cursor_position() {
                state.anchor_point = real_pos;
                state.mouse_expected = Vec2::zero();
                for mut t in icon.iter_mut() {
                    t.translation = vec3(
                        real_pos.x - primary.width() / 2.,
                        real_pos.y - primary.height() / 2.,
                        1.,
                    );
                }
            }
        }
    }
}

fn update_offset(
    mut reader: Local<EventReader<MouseMotion>>,
    mut state: ResMut<State>,
    mut icon: Query<&mut Transform, With<ExpectedPoint>>,
    mouse_motion_events: Res<Events<MouseMotion>>,
) {
    let mut delta_since = Vec2::zero();
    for MouseMotion { delta } in reader.iter(&mouse_motion_events) {
        delta_since += *delta;
    }
    state.mouse_expected += delta_since;
    for mut t in icon.iter_mut() {
        t.translation += vec3(delta_since.x, -delta_since.y, 0.);
    }
}

fn log_offset(state: ResMut<State>, windows: Res<Windows>) {
    if let Some(real) = windows.get_primary().and_then(|p| p.cursor_position()) {
        if real.abs_diff_eq(state.mouse_expected, 1.0) {
            println!("{:?}", real - state.mouse_expected);
        }
    }
}

#[derive(Default)]
struct State {
    anchor_point: Vec2,
    mouse_expected: Vec2,
}

```
</details>

However, in my program and on my system the difference between the offset and the real is always less than 1 pixel. I use 125% scaling on my monitor, so I'm confident this is not a scaling issue.

**Comment by mockersf** [comment]
on macOS, with a scale factor of 200%, after dragging my mouse cursor across the window for a few minutes:
```
anchor offset expected: [1099, 682.875]
anchor offset calculated: [1100, 679]
deviation: [-1, 3.875]
```

**Comment by AllenPocketGamer** [comment]
> I made a more visual program to try to reproduce:
> 
> Code hidden
> I make a red dot at `anchor_point`, and a green dot following `anchor_offset`.
> 
> ```rust
> use bevy::{input::mouse::MouseMotion, math::vec3, prelude::*};
> 
> // NOTE: Press MouseButton::Left to create a anchor point;
> fn main() {
>     App::build()
>         .add_resource(WindowDescriptor {
>             width: 1280f32,
>             height: 720f32,
>             ..Default::default()
>         })
>         .init_resource::<State>()
>         .add_plugins(DefaultPlugins)
>         .add_startup_system(setup.system())
>         .add_stage_after(
>             stage::UPDATE,
>             "serial_update",
>             SystemStage::serial()
>                 .with_system(position_reset.system())
>                 .with_system(update_offset.system())
>                 .with_system(log_offset.system()),
>         )
>         .run();
> }
> 
> struct AnchorPoint;
> struct ExpectedPoint;
> 
> fn setup(commands: &mut Commands, mut materials: ResMut<Assets<ColorMaterial>>) {
>     commands
>         // 2d camera
>         .spawn(Camera2dBundle::default())
>         .spawn(SpriteBundle {
>             sprite: Sprite::new(Vec2::new(1., 10.)),
>             material: materials.add(Color::rgb_u8(255, 0, 0).into()),
>             ..Default::default()
>         })
>         .with(AnchorPoint)
>         .spawn(SpriteBundle {
>             sprite: Sprite::new(Vec2::new(1., 10.)),
>             material: materials.add(Color::rgb_u8(0, 255, 0).into()),
>             ..Default::default()
>         })
>         .with(ExpectedPoint);
> }
> 
> fn position_reset(
>     mouse_button_input: Res<Input<MouseButton>>,
>     windows: Res<Windows>,
>     mut state: ResMut<State>,
>     mut icon: Query<&mut Transform, Or<(With<AnchorPoint>, With<ExpectedPoint>)>>,
> ) {
>     if mouse_button_input.just_pressed(MouseButton::Left) {
>         if let Some(primary) = windows.get_primary() {
>             if let Some(real_pos) = primary.cursor_position() {
>                 state.anchor_point = real_pos;
>                 state.mouse_expected = Vec2::zero();
>                 for mut t in icon.iter_mut() {
>                     t.translation = vec3(
>                         real_pos.x - primary.width() / 2.,
>                         real_pos.y - primary.height() / 2.,
>                         1.,
>                     );
>                 }
>             }
>         }
>     }
> }
> 
> fn update_offset(
>     mut reader: Local<EventReader<MouseMotion>>,
>     mut state: ResMut<State>,
>     mut icon: Query<&mut Transform, With<ExpectedPoint>>,
>     mouse_motion_events: Res<Events<MouseMotion>>,
> ) {
>     let mut delta_since = Vec2::zero();
>     for MouseMotion { delta } in reader.iter(&mouse_motion_events) {
>         delta_since += *delta;
>     }
>     state.mouse_expected += delta_since;
>     for mut t in icon.iter_mut() {
>         t.translation += vec3(delta_since.x, -delta_since.y, 0.);
>     }
> }
> 
> fn log_offset(state: ResMut<State>, windows: Res<Windows>) {
>     if let Some(real) = windows.get_primary().and_then(|p| p.cursor_position()) {
>         if real.abs_diff_eq(state.mouse_expected, 1.0) {
>             println!("{:?}", real - state.mouse_expected);
>         }
>     }
> }
> 
> #[derive(Default)]
> struct State {
>     anchor_point: Vec2,
>     mouse_expected: Vec2,
> }
> ```
> 
> However, in my program and on my system the difference between the offset and the real is always less than 1 pixel. I use 125% scaling on my monitor, so I'm confident this is not a scaling issue.

Thanks for your reply!
I run the program on my device but the problem still exists.
Based on the feedback from `mockersf`, I think the problem comes from my device.
I will try to find the cause of the problem.

Thx Again!

**Comment by AllenPocketGamer** [comment]
I finally figured out why the problem happened!

* The data(position) in winit::event::WindowEvent::CursorMove comes from Windows message: WM_MOUSEMOVE, 
    which is affected by the mouse settings in Control Panel;
* The data(delta) in winit::event::DeviceEvent::MouseMotion comes from Windows message: WM_INPUT(which cotains raw input mouse events),
    in contrast to legacy WM_MOUSEMOVE window message Raw Input mouse events is not subject to the effect of the mouse speed set in the
    Control Panel's Mouse Properties sheet.

* Just follow the instructions below to change the mouse settings to slove the problem.
    (https://www.tomshardware.com/news/how-to-disable-mouse-acceleration-windows,36886.html)


**What I want**

* I think bevy should provide comments for InputEvent to inform users of the nuances of use, which can save users a lot of time.
* At the same time I think bevy should provide InputEvent CursorMotion to distinguish MouseMotion.

**One more question**
* The bevy_input doesn't look like an idiomatic way to process the input message;
    To be honest, handling input events in bevy is very verbose, cumbersome and difficult to understand;
    Generally speaking, we prefer this usage to handle input events:

    ```Rust
    fn input_event_handler(input_device: Res<InputDevice>) {
        // About Mouse Device
        let mouse_position = input_device.mouse.position;
        let mouse_motion = input_device.mouse.motion;

        if input_device.mouse.just_pressed(MouseButton::Left) {
            // do something
        }

        if input_device.mouse.just_released(MouseButton::Left) {
            // do something
        }

        if input_device.mouse.pressed(MouseButton::Left) {
            // do something
        }
        ...

        // About Keyboard Device
        if input_device.keyboard.just_pressed(KeyCode::F) {
            // do something
        }

        if input_device.keyboard.just_released(KeyCode::F) {
            // do something
        }

        if input_device.keyboard.pressed(KeyCode::F) {
            // do something
        }
        ...

        // About Gamepad Device
        ...

        // About Touch Device
        ...
    }
    ```

* So the question which I want to ask is whether there are any follow-up plans to make bevy_input crate more idiomatic?

**Comment by DJMcNab** [comment]
Ok, so you have pointer acceleration on?

The delta events are not actually trying to be delta of pointer position, it's a delta of mouse movement. That makes sense, so the real issue is that we don't document that - which would basically be copying the docs from <https://docs.rs/winit/0.24.0/winit/event/enum.DeviceEvent.html#variant.MouseMotion>

I personally don't see anything wrong with `bevy_input`, but I would say that you should move that last paragraph to a github discussion (here <https://github.com/bevyengine/bevy/discussions>)
