### ISSUE TITLE
Get Ref<Component> from a query by entity

### ISSUE THREAD

**Issue by ThomasAlban** [bevyengine/bevy#11517]
Currently, as far as I know, there's no API for getting a `Ref<Component>` from a `query.get(entity).unwrap()` without changing the query to be a `Query<Ref<Component>>` or having to do `Ref::from(query.get_mut(entity))`. Would be nice if this was added!

**Comment by alice-i-cecile** [comment]
We'll want this on `Query`, `QueryState`, `EntityRef`, `EntityMut`, and probably `EntityWorldMut` 🙃

**Comment by Adamkob12** [comment]
I'd like to try if that's ok.

**Comment by alice-i-cecile** [comment]
Sounds good! Don't hesitate to open a draft PR and then ask for help :)

**Comment by alice-i-cecile** [comment]
As discussed in #11545, the complexity is too high here relative to the value. Maybe one day with effects.
