### ISSUE TITLE
Main Branch running hot

### ISSUE THREAD

**Issue by miketwenty1** [bevyengine/bevy#11522]
## Bevy version (main)

Going from commit 9f8db0de0d74c744aa6758a62ab6886a32a90bcb to 98087139a1d5e2b62b89deb29ee2a40bf75419a9 causes my macbook pro to run hot. I haven't made any big changes to my code, this leads me to think there may be some regression bug? wanted to flag it for y'all, possible it's just my bad code but wanted to see if anyone else noticed this.

Running on a macbook m1,  1.75 rustc.

**Comment by torsteingrindvik** [comment]
Can't know if it's this bug or not but you could try cherry-picking this commit: https://github.com/bevyengine/bevy/pull/11383

Main is "running hot" for me too without that PR

**Comment by BD103** [comment]
When I get a chance I'll run [`git-bisect`](https://git-scm.com/docs/git-bisect) on my M1 Mac and see if I can find the commit.

**Comment by BD103** [comment]
@miketwenty1, #11383 has merged now. Could you try updating to the latest commit and see if that fixes the issue?

**Comment by miketwenty1** [comment]
@BD103 so far so good, i did notice now that the background flashes white for a split second on loading now and the overall background is a black where it used to be a dark grey. I'll be doing more testing throughout the week.

**Comment by miketwenty1** [comment]
I haven't noticed any issues specific to this since the patch. I'm going to close.
