### ISSUE TITLE
Add a simple `EntityMapper` struct for use in networking

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11549]
That's the behaviour I'd prefer to have for networking, as I don't want/need the complexities associated with the existing EntityMapper. (Having to use `EntityMapper::world_scope()` and needing access to `&mut World`)
I will remove this from the PR as users can implement it themselves

_Originally posted by @cBournhonesque in https://github.com/bevyengine/bevy/pull/11428#discussion_r1467883777_

**Comment by Shatur** [comment]
I'm not sure if it's possible to have a general enough struct for networking.
In replicon I have different mapper for events and components, for example. Since it's just a few lines of code, I would left it for libraries to implement.

**Comment by alice-i-cecile** [comment]
Mhmm. Might be more useful as an example? It's hard to say: networking is a nasty beast.

**Comment by Shatur** [comment]
Yes, an example would be good. But maybe worth to put into rustdoc to the trait description?

**Comment by alice-i-cecile** [comment]
Yeah, I like this a lot as a doc test.
