### ISSUE TITLE
Allow wasm init in a container div

### ISSUE THREAD

**Issue by linonetwo** [bevyengine/bevy#11558]
## What problem does this solve or what need does it fill?

Bevy, does not natively support rendering directly to a specified HTML div element out-of-the-box, since it handles window creation and rendering internally.

But sometimes we want to compose a game canvas with the existing website, so I hope we can provide a dom element to the `init` function, or at least allow providing a CSS selector to it.

## What solution would you like?

```ts
    import init from './target/wasm_example.js'

    const containerElement = $tw.utils.domMaker('div', {
      text: 'Loading game...',
    });
    init({ container: containerElement })
```

## What alternative(s) have you considered?

I'm not sure if this is a safe approach:

1. In your HTML, define a div with a specific id where you want to render your game.
1. After your Bevy app is initialized, use JavaScript to locate the canvas created by Bevy.
1. Move this canvas into the div using JavaScript.

## Additional context

I'm creating a [habitica](https://github.com/HabitRPG/habitica)
style game for my todo plugin in https://tiddlywiki.com/. So I need to make sure the created canvas works well with card flow in Tiddlywiki.

**Comment by mockersf** [comment]
you can pass a css selector during window creation: https://docs.rs/bevy/latest/bevy/prelude/struct.Window.html#structfield.canvas

**Comment by linonetwo** [comment]
Thanks, I'm going through doc to find how to set this when using `.add_plugins(DefaultPlugins)`...

**Comment by linonetwo** [comment]
Solution:

```rs
fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                canvas: Some("tw-gamification-bevy-container".to_string()),
                ..default()
            }),
            ..default()
        }))
        .add_systems(Startup, setup)
        .run();
}
```

But seems not working...
