### ISSUE TITLE
Ability to set Entity's ID

### ISSUE THREAD

**Issue by ThomasAlban** [bevyengine/bevy#11564]
it would be nice if there was a way to set an Entity's ID (on spawn), failing if there's already an Entity with that ID in the world. This would be very useful because it would allow for deleting and recreating an entity and maintaining the same ID, without having to implement another ID system on top of Bevy's.

**Comment by nosideeffects** [comment]
Can you give a full scenario where this would be helpful? Why would you delete an entity only to spawn an identical entity?

**Comment by doonv** [comment]
Why would you want to delete and recreate an entity while maintaining the ID?

**Comment by ThomasAlban** [comment]
A commands based undo system. I've been talking about it in [this thread on discord](https://discord.com/channels/691052431525675048/1200855122704613608). If I have an undo stack that looks something like this (bottom up):

Modify (stores entity ID, position before, positions after)
Create entity

if I undo, undo, redo, the modify command will store an invalid reference to the entity in question.
So when undoing the 'create entity' command I could save the entity ID, then respawn it with that same ID on redo.

**Comment by doonv** [comment]
I would replace the undo-ed entities with a empty entity. Then when its time to redo, replace the entity with what it was. That way it will always use the same id.

**Comment by ThomasAlban** [comment]
That's a pretty good solution to the problem that I hadn't thought of at all! I was wondering about the approach of having a `Dead` marker component but then this comes with the complexity of querying `Without<Dead>`, so this solution seems more elegant. Thanks, and unless there are any other reasons for this feature to be added I'll close this issue!
