### ISSUE TITLE
Insert gizmo configuration

### ISSUE THREAD

**Issue by Jondolf** [bevyengine/bevy#11569]
## What problem does this solve or what need does it fill?

With Bevy's new support for multiple gizmo configurations (#10342), it's possible to initialize configurations using `init_gizmo_group`. However, there doesn't seem to be an API to initialize it with a specific value.

The only way that I found outside of scheduling a startup system (which I can't do in my case) is to do this:

```rust
// In a plugin's build method

app.init_gizmo_group::<PhysicsGizmos>();

let mut store = app.world.resource_mut::<GizmoConfigStore>();
let config = store.config_mut::<PhysicsGizmos>().0;
config.line_width = 1.5;
```

which is not ideal. I think it also has issues if the plugin is added before the `GizmoPlugin`.

My use case is that bevy_xpbd has a `PhysicsDebugConfig` resource and a `PhysicsDebugRenderer` system parameter that renders colliders, joints, contacts, and so on. With the new gizmo API, I'm combining these into a single `PhysicsGizmos` gizmo config group that stores the config that was previously stored in `PhysicsDebugConfig` and has some methods for e.g. rendering colliders.

I need to (1) configure some properties of the `GizmoConfig` to non-default values, and (2) give people an easy API to configure `PhysicsGizmos` for e.g. disabling collider rendering. This should be doable during initialization, not just in a system. I can not make a `Startup` system for it as it could conflict with users' systems that use `GizmoConfigStore` in that schedule.

## What solution would you like?

Add an `insert_gizmo_group` method to `App`:

```rust
app.insert_gizmo_group(PhysicsGizmos {
    // ...
});
```

There must also be a way to set the `GizmoConfig` associated with the gizmo group. This could be an `insert_gizmo_config` or `configure_gizmo_config` method:

```rust
app.insert_gizmo_config::<PhysicsGizmos>(GizmoConfig {
    // ...
});
```

**Comment by pablo-lua** [comment]
> I think it also has issues if the plugin is added before the GizmoPlugin.

About this, this error doesn't seen to happen after #11420, or is there another error in this fields? 🤔

**Comment by Jondolf** [comment]
Ah, I didn't actually try if it errors there, I just assumed that it wouldn't add the group if done before the `GizmoPlugin`. Cool if it works!

**Comment by alice-i-cecile** [comment]
I like the naming, and think this should exist.
