### ISSUE TITLE
ui_focus_system crashes if UI Node is removed by clicking on it.

### ISSUE THREAD

**Issue by Hexorg** [bevyengine/bevy#11572]
## Bevy version

bevy_ui-0.12.1

## What you did

I have a UI interaction where a UI node gets deleted when it gets clicked on (Interaction::Pressed).

## What went wrong

Panic at bevy_ui-0.12.1/src/stack.rs:63:14:
called `Result::unwrap()` on an `Err` value: NoSuchEntity(2v0)

## Additional information

Minimal reproducible code below (crashes when you click on "click me"). If you only have one node crash doesn't happen.

```
use bevy::{prelude::*, ui::ui_focus_system};

fn on_interaction(query:Query<(Entity, &Interaction), Changed<Interaction>>, mut commands:Commands) {
    for (entity, interaction) in &query {
        if *interaction == Interaction::Pressed {
            commands.entity(entity).despawn();
        }
    }
}

fn setup(mut commands:Commands) {
    commands.spawn(NodeBundle::default()).with_children(|parent| {
        parent.spawn((Interaction::None, TextBundle::from_section("click me", TextStyle::default())));
    });
    commands.spawn(Camera3dBundle::default());
}

fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(Update, (ui_focus_system, on_interaction));
    app.run();
```

**Comment by alice-i-cecile** [comment]
This is the offending line: https://github.com/bevyengine/bevy/blob/22e39c4abf6e2fdf99ba0820b3c35db73be71347/crates/bevy_ui/src/stack.rs#L63

We shouldn't unwrap here: instead, we should just continue. Looks like an easy fix.
