### ISSUE TITLE
AlphaMode Blend - Z ordering errors

### ISSUE THREAD

**Issue by IDEDARY** [bevyengine/bevy#11608]
## Bevy version

Version 0.12.1 or Bevy main, latest commit: `e94297f`

```ignore
`AdapterInfo { name: "NVIDIA GeForce RTX 3060 Laptop GPU", vendor: 4318, device: 9504, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "535.154.05", backend: Vulkan }`
```

## What you did

I used `AlphaMode:Blend` on `Standard Material` slapped onto `Quad` mesh

https://github.com/bevyengine/bevy/assets/49441831/3eacad4a-682a-42f3-90ff-c13b81e9e6d5

## What went wrong

The Z-ordering is most likely breaking under different camera angles. Most likely a math error somewhere in the blending pipeline.
You can see the `semi-transparent texture` blinking in certain moments.
The text's alpha is `100%` and black background is `75%`.
The issue only happens when `AlphaMode` is set to `Blend`

## Additional information

The code for replicating this should be simple. I did not do anything to rendering, but I encountered it while developing UI library. The code is currently private and WIP, but I can provide it early if people are interested to fix this issue.

**Comment by IDEDARY** [comment]
This issue is also present in [billboard crate](https://github.com/kulkalkul/bevy_mod_billboard) for text. It happens whenever 2 or more transparent meshes are on top of each other. Just transparent background and billboard text mesh is enough to break things. 
![image](https://github.com/bevyengine/bevy/assets/49441831/c4159f86-6fa8-423d-8713-755142703620)

I thought that stacking transparent images is edge-case, but it turned out that it is also triggered by 3D non-transparent text, which I assume also uses blend mode under the hood.

This just bumped the issues severity and I now consider it a blocker for Bevy's future world-space UI.

**Comment by floppyhammer** [comment]
I cannot reproduce it with the `3d/texture` example. Could you provide a reproduction project?

**Comment by CptPotato** [comment]
> The Z-ordering is most likely breaking under different camera angles. Most likely a math error somewhere in the blending pipeline.

There is no way to correctly sort transparent objects correctly in all scenarios when drawing them separately. Bevy sorts transparent objects based on their distance to the camera, which is common practice.

From what I can tell this is working correctly in your example, even if the result looks odd. To get the expected behavior, either change the origin of the 3D models used or apply a depth bias in the material to force the desired sorting, see `bevy_pbr::StandardMaterial`:

https://github.com/bevyengine/bevy/blob/71be08af68e081cab466f3bbe3728c30db3a94f7/crates/bevy_pbr/src/pbr_material.rs#L374-L384

Related: #5656, #2223

**Comment by IDEDARY** [comment]
> I cannot reproduce it with the `3d/texture` example. Could you provide a reproduction project?

Of course, here it is https://github.com/IDEDARY/Bevycom



> > The Z-ordering is most likely breaking under different camera angles. Most likely a math error somewhere in the blending pipeline.
> 
> There is no way to correctly sort transparent objects correctly in all scenarios when drawing them separately. Bevy sorts transparent objects based on their distance to the camera, which is common practice.
> 
> From what I can tell this is working correctly in your example, even if the result looks odd. To get the expected behavior, either change the origin of the 3D models used or apply a depth bias in the material to force the desired sorting, see `bevy_pbr::StandardMaterial`:
> 
> https://github.com/bevyengine/bevy/blob/71be08af68e081cab466f3bbe3728c30db3a94f7/crates/bevy_pbr/src/pbr_material.rs#L374-L384
> 
> Related: #5656, #2223

Ok, that seems like it might be able to do something. I will try it later

**Comment by floppyhammer** [comment]
> This issue is also present in [billboard crate](https://github.com/kulkalkul/bevy_mod_billboard) for text. It happens whenever 2 or more transparent meshes are on top of each other. Just transparent background and billboard text mesh is enough to break things. ![image](https://private-user-images.githubusercontent.com/49441831/301611846-c4159f86-6fa8-423d-8713-755142703620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjA5NzQsIm5iZiI6MTcwODQyMDY3NCwicGF0aCI6Ii80OTQ0MTgzMS8zMDE2MTE4NDYtYzQxNTlmODYtNmZhOC00MjNkLTg3MTMtNzU1MTQyNzAzNjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA5MTc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MTM5MGZmMWIzNTVjYTgxNjFlZTJiZWY4MGM0NDExNzkwNDAyOGM2NjVhZGExN2I0N2I3YTlkZDdlYzE5NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qXdX61yopM5ADL0nG4ICY746OSET7iW6n8JQio_UjiE)
> 
> I thought that stacking transparent images is edge-case, but it turned out that it is also triggered by 3D non-transparent text, which I assume also uses blend mode under the hood.
> 
> This just bumped the issues severity and I now consider it a blocker for Bevy's future world-space UI.

@IDEDARY Could you help test the PR in this case?

**Comment by IDEDARY** [comment]
Update: The PR mentioned here was closed as it did not solve the issue completely.
I also made reproducible: [bare bones reproducible](https://github.com/IDEDARY/bevy-blend-depth-order-issue-reproducible)

**Comment by torsteingrindvik** [comment]
This still exists in 0.13.2:

https://github.com/bevyengine/bevy/assets/52322338/7c7d1030-3189-43b0-826c-9d42f2ab536d

These are basically just PBR bundles of cuboid meshes with standard materials set from colors, but with `AlphaMode::Blend` set.

@alice-i-cecile do you see any hope for this to get a fix for 0.14? Hoping to avoid waiting for 0.15 for using transparency.

**Comment by superdump** [comment]
The only way to fix this is order-independent transparency. Plain apps blending by ordering draws by their transform origins in view space only works up to a point. If you have intersecting triangles or situations like in the original video then what bevy currently supports out of the box will not be sufficient.

**Comment by zhuliang198754** [comment]
Excuse me, is this issue scheduled to be fixed? @alice-i-cecile

**Comment by IDEDARY** [comment]
@superdump Note that in the original video/reproducible I posted, there are no intersections. Nomeshes collide with each other, they are just stacked closely next to each other. It should be possible to fix that with order dependent draw calls.

**Comment by IDEDARY** [comment]
This issue has now been fixed by @IceSentry with his https://github.com/bevyengine/bevy/pull/14876 Order Independent PR.

![Image](https://github.com/user-attachments/assets/c0209bf1-cc3f-4b2c-998c-a189ba01228d)

To enable OIT, just modify your camera like this: (more info in the OIT example) ![Image](https://github.com/user-attachments/assets/116517ba-72fc-470d-9135-22ee90f4aba7)

@alice-i-cecile I'm closing this as completed :)
