### ISSUE TITLE
UIMaterial doesn't render the passed in color correctly

### ISSUE THREAD

**Issue by AngeloMateus** [bevyengine/bevy#11607]
## Bevy version
0.12.1

## \[Optional\] Relevant system information
Macbook M1 pro

## What you did

The example for custom UIMaterial doesn't render the correct color 

## What went wrong
When passing in a color to the custom material

```
material: ui_materials.add(CustomUiMaterial {
    color: Color::hex("#ff0000").unwrap().into(),
}),
```

the shader below (which as far as I understand it should do nothing but render the UI node with the passed in color) renders a brighter color:

```
#import bevy_ui::ui_vertex_output UiVertexOutput

struct CustomUiMaterial {
    @location(0) color: vec4<f32>
}

@group(1) @binding(0)
var<uniform> input: CustomUiMaterial;

@fragment
fn fragment(in: UiVertexOutput) -> @location(0) vec4<f32> {
    return input.color;
}
```

The rendered color is #FC0D1B, is there anything I'm missing?
This makes UI colors are inconsistent with the standard UI materials

**Comment by floppyhammer** [comment]
Could you provide a minimal reproduction project?

**Comment by floppyhammer** [comment]
Your code doesn't compile. You should use `color: Color::hex("#ff0000").unwrap().rgba_to_vec4()` to convert `Color` to `Vec4`. The result is correct that way.

**Comment by floppyhammer** [comment]
Sorry I was looking at the latest version of Bevy. On 12.1, `rgba_to_vec4` doesn't exist yet. But the result is still correct.

**Comment by AngeloMateus** [comment]
Hi @floppyhammer I did disable the system that updates the color. Turns out I was looking at the wrong values in the color picker, the stripped down example does work as expected. 

The color is still not displaying properly on my app but must be something else I'm doing.

**Comment by viridia** [comment]
I had a similar problem and realized I needed to do the sRGB -> LinearRGB conversion. Unlike standard materials, it doesn't happen automatically with UiMaterials.
