### ISSUE TITLE
Blurry output when rendered to low-res texture

### ISSUE THREAD

**Issue by Borcam-Tepsi** [bevyengine/bevy#11642]
I want to make a low-res 3D game (old Quake style). And to achieve that I want to render the scene to a texture and then render that texture onto a sprite which covers the whole screen. But the cube I draw has smoothed edges although I have not enabled any sort of anti aliasing. What may be causing this?

https://github.com/bevyengine/bevy/assets/70875909/6445c48f-fa39-45f1-a9d2-4ffe3d88620d

`
fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(ImagePlugin::default_nearest()))
        .add_systems(Startup, setup)
        .add_systems(Update, rotator_system)
        .run();
}

// Marks the first pass cube (rendered to a texture.)
#[derive(Component)]
struct FirstPassCube;

// Marks the main pass cube, to which the texture is applied.
#[derive(Component)]
struct MainPassCube;

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    mut images: ResMut<Assets<Image>>,
) {
    let size = Extent3d {
        width: 64,
        height: 64,
        ..default()
    };

    // This is the texture that will be rendered to.
    let mut image = Image {
        texture_descriptor: TextureDescriptor {
            label: None,
            size,
            dimension: TextureDimension::D2,
            format: TextureFormat::Bgra8UnormSrgb,
            mip_level_count: 1,
            sample_count: 1,
            usage: TextureUsages::TEXTURE_BINDING
                | TextureUsages::COPY_DST
                | TextureUsages::RENDER_ATTACHMENT,
            view_formats: &[],
        },
        sampler: ImageSampler::nearest(),
        ..default()
    };

    // fill image.data with zeroes
    image.resize(size);

    let image_handle = images.add(image);

    let cube_handle = meshes.add(Mesh::from(shape::Cube { size: 4.0 }));
    let cube_material_handle = materials.add(StandardMaterial {
        base_color: Color::rgb(0.8, 0.7, 0.6),
        reflectance: 0.0,
        unlit: false,
        perceptual_roughness: 1.0,
        diffuse_transmission: 0.0,
        specular_transmission: 0.0,
        thickness: 0.0,

        ..default()
    });

    // This specifies the layer used for the first pass, which will be attached to the first pass camera and cube.
    let first_pass_layer = RenderLayers::layer(1);

    // The cube that will be rendered to the texture.
    commands.spawn((
        PbrBundle {
            mesh: cube_handle,
            material: cube_material_handle,
            transform: Transform::from_translation(Vec3::new(0.0, 0.0, 1.0)),
            ..default()
        },
        FirstPassCube,
        first_pass_layer,
    ));

    commands.spawn(PointLightBundle {
        transform: Transform::from_translation(Vec3::new(0.0, 0.0, 10.0)),
        ..default()
    });

    commands.spawn((
        Camera3dBundle {
            camera_3d: Camera3d {
                clear_color: ClearColorConfig::Custom(Color::BLACK),
                ..default()
            },
            camera: Camera {
                // render before the "main pass" camera
                order: -1,
                target: RenderTarget::Image(image_handle.clone()),
                msaa_writeback: false,
                ..default()
            },
            dither: DebandDither::Disabled,
            transform: Transform::from_translation(Vec3::new(0.0, 0.0, 15.0))
                .looking_at(Vec3::ZERO, Vec3::Y),
            ..default()
        },
        first_pass_layer,
    ));

    commands.spawn(SpriteBundle {
        texture: image_handle.clone(),
        sprite: Sprite {
            custom_size: Some(Vec2{x: 1.0, y: 1.0}),
            ..default()
        },
        transform: Transform::from_xyz(0.5, 0.5, 0.0),
        ..default()
    });

    commands.spawn(Camera2dBundle {
        projection: OrthographicProjection { 
            near: -100.0,
            far: 100.0,
            viewport_origin: Vec2 {x: 0.0, y: 0.0},
            scaling_mode: ScalingMode::FixedVertical(1.0),
            scale: 1.0,
            ..default()
        },
        ..default()
    });

}

fn rotator_system(time: Res<Time>, mut query: Query<&mut Transform, With<FirstPassCube>>) {
    for mut transform in &mut query {
        transform.rotate_x(0.5 * time.delta_seconds());
        transform.rotate_z((1.3 / 3.0) * time.delta_seconds());
    }
}

`

**Comment by rparrett** [comment]
[MSAA](https://docs.rs/bevy/latest/bevy/prelude/enum.Msaa.html) is enabled by default. You can disable it with `app.insert_resource(Msaa::Off)`.

**Comment by Borcam-Tepsi** [comment]
> [MSAA](https://docs.rs/bevy/latest/bevy/prelude/enum.Msaa.html) is enabled by default. You can disable it with `app.insert_resource(Msaa::Off)`.

Yep, that did it. Thank you very much.

**Comment by xiahualiu** [comment]
Just want to update as of 05/24/2025.

`Msaa` is a component for `Camera`, like `Camera2d`, so you should add it when you spawn the camera entity.

For example,

```rust
fn setup_camera(mut commands: Commands) {
    commands.spawn((Msaa::Off, Camera { ..default() }));
}
```
