### ISSUE TITLE
WebAssembly mouse move is not working

### ISSUE THREAD

**Issue by chaoticgood1** [bevyengine/bevy#1166]
**Bevy version**

0.4

**Operating system & version**

Ubuntu 18.04

**What you did**

Ran these command line
```
cargo build --example winit_wasm --target wasm32-unknown-unknown --no-default-features --features="bevy_winit"
wasm-bindgen --out-dir examples/wasm/target --target web target/wasm32-unknown-unknown/debug/examples/winit_wasm.wasm
```

**What you expected to happen**

Should output the delta value in /bevy/examples/wasm/winit_wasm.rs line 81.

**What actually happened**

No logs of the mouse move

**Comment by smokku** [comment]
You need [pointer lock](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) to receive mouse movement events.

This is achievable via wasm-bindgen [request_pointer_lock](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Element.html#method.request_pointer_lock)

**Comment by Nickan** [comment]
We did the following code still we won't be able to get the delta, let us know what we did wrong, thanks.

```
let window = web_sys::window().expect("no global `window` exists");
let document = window.document().expect("should have a document on window");
let body = document.body();
if let Some(bod) = body {
  bod.request_pointer_lock();
  info!("Executed");
}
```

**Comment by samcarey** [comment]
> You need [pointer lock](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) to receive mouse movement events.
> 
> 
> 
> This is achievable via wasm-bindgen [request_pointer_lock](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Element.html#method.request_pointer_lock)

@smokku I got some code working (barely) using web-sys which you pointed me to earlier on discord. I can activate pointer lock and detect movement events *independently* (lock is not required for detecting movements). I'll try to polish and post an example later today (not at my computer now).

Btw your second link is broken.

**Comment by samcarey** [comment]
Ok, I made an example that makes a blank canvas that locks your mouse on click and logs mouse movements to the dev console.
So far it works best in Chrome/Edge.

[Online demo](https://sccarey.gitlab.io/bevy-web-mouse-example) and [Source](https://gitlab.com/sccarey/bevy-web-mouse-example)

**Comment by smokku** [comment]
This looks like the culprit may be in `winit` not supporting mouse movement in Browser environment.
It may be worth taking this issue upstream.

**Comment by minecrawler** [comment]
Just to throw in some more data: I tested the online demo using Firefox 84.0.1 (64-bit) on Win10. I got the information output with as well as without mouse lock.

**Comment by Nickan** [comment]
> Ok, I made an example that makes a blank canvas that locks your mouse on click and logs mouse movements to the dev console.
> So far it works best in Chrome/Edge.
> 
> [Online demo](https://sccarey.gitlab.io/bevy-web-mouse-example) and [Source](https://gitlab.com/sccarey/bevy-web-mouse-example)

Thanks for the example, this works, I just have to upgrade Chrome to latest version, closing this issue.

**Comment by samcarey** [comment]
@Nickan My example is just a workaround. I'm not sure if this issue should be closed until Bevy itself is changed such that the workaround is no longer necessary.

**Comment by cart** [comment]
Agreed!

**Comment by rparrett** [comment]
Looks like we've got mouse events working on the web these days.

Tested with the `mouse_input_events` example, and I am seeing both of:

[MouseMotion](https://docs.rs/bevy/latest/bevy/input/mouse/struct.MouseMotion.html)
[CursorMoved](https://docs.rs/bevy/latest/bevy/prelude/struct.CursorMoved.html)

So I'll close this out. Please feel free to open a new issue if you're having an issue with mouse motion in a more recent version of Bevy.
