### ISSUE TITLE
Keyboard Input logic

### ISSUE THREAD

**Issue by Rdna123** [bevyengine/bevy#1167]
**Bevy version**
0.4.0
The release number or commit hash of the version you're using.

**Operating system & version**

Windows 10 with msvn toolchain

**What you did**
<details>
<summary>Code Used</summary>

```Rust
use bevy::prelude::*;

fn main(){
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup.system())
        .add_system(player_movement.system())
        .run();
}

fn setup(commands: &mut Commands, mut materials: ResMut<Assets<ColorMaterial>>){
    print!("setup...");
    commands
        .spawn(Camera2dBundle::default())
        .spawn(SpriteBundle{
            material: materials.add(Color::rgb(0.2,0.2,0.8).into()),
            transform: Transform::from_translation(Vec3::new(0.0,0.0,0.0)),
            sprite: Sprite::new(Vec2::new(32.0, 32.0)),
            ..Default::default()
        })
        .with(Player{speed: 200.0});
    println!("  Complete");
}

struct Player{
    speed: f32,
}

fn player_movement(time: Res<Time>,keyboard_input: Res<Input<KeyCode>>,
                   mut query: Query<(&mut Transform, &Player)>){
    for (mut transform, player) in &mut query.iter_mut(){
        let translation = &mut transform.translation;
        let mut direction = Vec2::new(0.0, 0.0);
        
        if keyboard_input.pressed(KeyCode::Right) {direction.x += 1.0}
        if keyboard_input.pressed(KeyCode::Left) {direction.x -= 1.0}
        if keyboard_input.pressed(KeyCode::Up) {direction.y += 1.0}
        if keyboard_input.pressed(KeyCode::Down) {direction.y -= 1.0}

        translation.x += time.delta_seconds() * direction.x * player.speed;
        translation.y += time.delta_seconds() * direction.y * player.speed;
    }
}

```
</details>

**What you expected to happen**

If you press two opposites able to move in the other directions, ei right and left pushed movement up and down should be possible.

**What actually happened**

right and left pressed only able to move down
up and down pressed only able to move right

**Additional information**
Somethings that I thought would be my fault for Issue, boxes checked if I tried it.
- [X] Removed time and speed variables to test 
- [X] Tried if-statements in different orders
- [ ] Tried without Vec2

**Comment by eliasreid** [comment]
Just copied and pasted your code above. I'm on windows, bevy 0.4.0 as well. In release and debug builds it works as you've described in your expected behavior (up / down movement is possible with right and left held down).

**Comment by Devil-Ira** [comment]
It's likely that you've discovered the wonderful world of [n-key rollover](https://www.tomshardware.com/reviews/-n-key-rollover-nkro-definition,5751.html). Some keyboards, mainly old and non-gaming keyboards, are limited in what key combinations they can understand.

Try testing a game and see if pressing the arrow keys acts the same way it does in bevy. Maybe try WASD as well.

And to be fair to keyboard makers they are pretty smart about choosing what combinations do work. Holding two opposing arrow keys is almost always useless, so they assume you wouldn't do that c:

**Comment by Rdna123** [comment]
Changing to WASD fixes moving up and down while opposing side to side can't move when up and down at all.

@Devil-Ira Thanks did not know keyboard did that.

**Comment by Rdna123** [comment]
Yeah it is my keyboard
