### ISSUE TITLE
Unexpected Logical Key Value

### ISSUE THREAD

**Issue by Shute052** [bevyengine/bevy#11689]
## Bevy version

The main Bevy (currently, commit #08654ad), but the bug actually comes from [Bevy PR #10702: Update winit to 0.29](https://github.com/bevyengine/bevy/pull/10702)

## \[Optional\] Relevant system information

This might be able to reproduce on any machine in the version.

## What you did

I am working on the [updates](https://github.com/Leafwing-Studios/leafwing-input-manager/pull/463) of `leafwing_input_manager` to Bevy 0.13, but as the title says, the logical `Key` value seems to be incorrect.

### Simple Case for Reproduction

```rust
fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Update, read_keyboard_input)
        .run()
}

fn read_keyboard_input(mut keyboard_input: EventReader<KeyboardInput>) {
    for input in keyboard_input.read() {
        dbg!(input);
    }
}
```

## What went wrong

The situation is:
- If you just press any letter keys, e.g., W key and then you will get a `KeyboardInput(logical_key: "w")`, an expected lowercase w letter.
- However, if CapsLock is activated or Shift is pressing, like normal text input, you will get a `KeyboardInput(logical_key: "W")`, **"AN UPPERCASE W LETTER"**!

**Comment by alice-i-cecile** [comment]
Hmm. I'm not sure if this is incorrect behavior. The logical key value seems well-suited to things like text input. Instead, we might want a `to_uppercase` method or the equivalent, either in Bevy or winit. Then, consumers like LWIM who want to use this for input mapping can normalize their received values.

**Comment by Shute052** [comment]
> Hmm. I'm not sure if this is incorrect behavior. The logical key value seems well-suited to things like text input. Instead, we might want a `to_uppercase` method or the equivalent, either in Bevy or winit. Then, consumers like LWIM who want to use this for input mapping can normalize their received values.

In many game engines, logical keys are simply a named enum variant or an automatically normalized character. I believe Bevy game developers who aren't using LWIM also have to address both cases when dealing with commonly used letter keys.
