### ISSUE TITLE
Bundles nested components should be query-able

### ISSUE THREAD

**Issue by dmyyy** [bevyengine/bevy#11683]
## Bevy version

0.12

## What you did

I'm writing an orthographic camera. I want to change the orthographic perspective scale. Since `Camera3dBundle` has a projection component, and that projection enum component holds an OrthographicProjection component I was expecting to be able to query it.

## What went wrong

I expected 

```rust
mut q_camera: Query<(&mut Transform, &mut OrthographicProjection), With<Camera3d>>,
```

to give me an OrthographicProjection component - it crashed instead.

```rust
mut q_camera: Query<(&mut Transform, &mut Projection), With<Camera3d>>,
```

Just getting the projection and doing a match works okay but doesn't look great.

**Comment by Shute052** [comment]
Perhaps you could do this?

```rust
#[derive(Component, ...)
pub struct YourOrthographicCameraMarker;

mut q_camera: Query<(&mut Transform, &mut OrthographicProjection), With<YourOrthographicCameraMarker>>
```

**Comment by Kanabenki** [comment]
With your proposal, how would the query distinguish between the `OrthographicProjection` nested in a `Projection` enum, and an actual `OrthographicProjection` directly present on the entity or nested in another enum?

**Comment by alice-i-cecile** [comment]
Agreed, I don't think this is possible, or desirable if it is possible. Automatically tunneling down to the fields of components seems like it would badly complicate both the internals and the mental models for users.
