### ISSUE TITLE
Add delta to `CursorMoved` event

### ISSUE THREAD

**Issue by Sebbl0508** [bevyengine/bevy#11695]
## What problem does this solve or what need does it fill?
Since `MouseMotion` (afaik) intentionally doesn't take mouse acceleration or (maybe also?) scaling into account, one would have to use `CursorMoved` to stay "up-to-date" to the actual cursor position(s).  
Unfortunately the `CursorMoved` event doesn't contain deltas. That means if one needs that, they would need to implement that themselves in their code.

## What solution would you like?
If possible and/or wanted `delta` to be added to the `CursorMoved` event.

## What alternative(s) have you considered?
Implementing the delta calculation in my own game code or trying to solve my problem without using deltas.

## Additional context
If this is nothing against this addition, i'd like to try implementing this myself. I haven't gone into the bevy internals so idk how possible this is, but i'd like to try :)  

For additionaly context why i want this change: Added is a video of my WIP app, where i'm trying to implement a mouse-dragging camera controller. At the moment i'm using the deltas from `MouseMotion`, which causes issues since apparently on my laptop there's some kind of mouse acceleration or something.

https://github.com/bevyengine/bevy/assets/28149337/1e03e87d-36ae-46e6-be03-3127159afea1

**Comment by Sebbl0508** [comment]
For the moment, this is the approach i took in my own game code:

<details>

<summary>Code</summary>

```rust
use bevy::prelude::*;

pub struct CursorMovedDeltaPlugin;

impl Plugin for CursorMovedDeltaPlugin {
    fn build(&self, app: &mut App) {
        app.add_event::<CursorMovedWithDelta>()
            .init_resource::<LastCursorPosition>()
            .add_systems(PreUpdate, translate_cursor_moved_events);
    }
}

#[derive(Event, Debug)]
pub struct CursorMovedWithDelta {
    pub window: Entity,
    pub position: Vec2,
    pub delta: Vec2,
}

/// `None` if not set yet
#[derive(Resource, Debug, Default)]
pub struct LastCursorPosition(Option<Vec2>);

fn translate_cursor_moved_events(
    mut last_cursor_position: ResMut<LastCursorPosition>,
    mut cursor_motion: EventReader<CursorMoved>,
    mut cursor_motion_with_delta: EventWriter<CursorMovedWithDelta>,
) {
    for evt in cursor_motion.read() {
        if let Some(last_cursor_position) = last_cursor_position.0 {
            let delta = evt.position - last_cursor_position;
            cursor_motion_with_delta.send(CursorMovedWithDelta {
                window: evt.window,
                position: evt.position,
                delta,
            });
        }

        last_cursor_position.0 = Some(evt.position);
    }
}

```

</details>

**Comment by solis-lumine-vorago** [comment]
I agree that this might be useful, but since `CursorMoved` is a translated version of the `winit::CursorMoved` struct which does not include `delta`, I don't know if this is the place to add it.

**Comment by Sebbl0508** [comment]
> I agree that this might be useful, but since `CursorMoved` is a translated version of the `winit::CursorMoved` struct which does not include `delta`, I don't know if this is the place to add it.

That's what i thought too.
Nice PR btw. Thanks a lot. Hope it gets merged!
