### ISSUE TITLE
`SpawnScene` schedule is missing in `Main`

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#11696]
## How can Bevy's documentation be improved?

We need to reference [`SpawnScene`](https://docs.rs/bevy/latest/bevy/app/struct.SpawnScene.html) in [`Main`](https://docs.rs/bevy/latest/bevy/app/struct.Main.html).

Runs before `PostUpdate`. For the reference see https://github.com/bevyengine/bevy/pull/9451.

**Comment by alice-i-cecile** [comment]
Tackling this is tricky, since there's a circular dependency. Ultimately this feels like a case of "system ordering should be interactively viewable" 🤔

**Comment by Shatur** [comment]
Ah, I see. Closing then, I thought that docs are missing.
