### ISSUE TITLE
Embedded watcher only working if lib declares its own embedded_watcher feature

### ISSUE THREAD

**Issue by devnev** [bevyengine/bevy#11708]
## Bevy version

0.12.1

## \[Optional\] Relevant system information

```
$ cargo --version
cargo 1.75.0 (1d8b05cdd 2023-11-20)
$ uname -a
Darwin Marks-MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64
```

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```ignore
`AdapterInfo { name: "Intel(R) Iris(TM) Plus Graphics", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }`
```

## What you did

1. Create a new library for bevy

```sh
mkdir repro_lib && cd repro_lib
cargo init --lib
cargo add bevy --no-default-features --features bevy_asset,bevy_pbr,bevy_core_pipeline,bevy_render,multi-threaded
```

2. Create a plugin with an extended material with a custom fragment shader

`lib.rs`
```rust
use bevy::{
    asset::embedded_asset,
    pbr::{ExtendedMaterial, MaterialExtension},
    prelude::*,
    render::render_resource::AsBindGroup,
};

pub struct MyMaterialPlugin;

impl Plugin for MyMaterialPlugin {
    fn build(&self, app: &mut App) {
        // Explicit `src/` required because path is `src/frag.wgsl` so default
        // `/src/` doesn't work
        embedded_asset!(app, "src/", "frag.wgsl");
        app.add_plugins(MaterialPlugin::<MyMaterial>::default());
    }
}

pub type MyMaterial = ExtendedMaterial<StandardMaterial, MyMaterialExtension>;

#[derive(Asset, Default, Debug, Clone, TypePath, AsBindGroup)]
pub struct MyMaterialExtension {}

impl MaterialExtension for MyMaterialExtension {
    fn fragment_shader() -> bevy::render::render_resource::ShaderRef {
        "embedded://repro_lib/frag.wgsl".into()
    }
}
```

`frag.wgsl`
```wgsl
#import bevy_pbr::forward_io::{VertexOutput, FragmentOutput};

@fragment
fn fragment(in: VertexOutput) -> FragmentOutput {
    var out: FragmentOutput;
    out.color = vec4(0.2);
    return out;
}
```

3. Create an example for the library to help with prototyping and iterating:

```sh
cargo add --dev bevy --feature embedded_watcher,dynamic_linking
mkdir examples
```

`examples/example.rs`
```rust
use bevy::{prelude::*, render::mesh::shape::Plane};
use repro_lib::{MyMaterial, MyMaterialPlugin};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugins(MyMaterialPlugin)
        .add_systems(Startup, setup)
        .run();
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<MyMaterial>>,
) {
    commands.spawn(Camera3dBundle {
        transform: Transform::from_translation((0.0, 3.0, 10.0).into())
            .looking_at(Vec3::ZERO, Vec3::Y),
        ..default()
    });
    commands.spawn(MaterialMeshBundle {
        mesh: meshes.add(Plane::from_size(10.0).into()),
        material: materials.add(MyMaterial {
            // no Default for ExtendedMaterial
            base: default(),
            extension: default(),
        }),
        ..default()
    });
}
```

4. Run the example

```sh
cargo run --example example
```

5. Change the fragment shader while the example is running, e.g. changing the value assigned to `out.color`.

## What went wrong

When making changes to the fragment shader with the example running, I would expect the fragment shader to be hot-reloaded, due to the embedded_watcher feature - but it isn't. Even moving the feature setting from [dev-dependencies] to [dependencies] does not fix this.

## Additional information

I've debugged the code and the cause seems to be that in the `embedded_asset` macro, the feature attribute for `embedded_watcher` is evaluating to it being disabled.

```rust
        #[cfg(feature = "embedded_watcher")]
        let full_path = std::path::Path::new(file!()).parent().unwrap().join($path);
        #[cfg(not(feature = "embedded_watcher"))]
        let full_path = std::path::PathBuf::new();
```

I confirmed this by hacking print statements for the value of full_path and of `cfg!(feature="embedded_watcher")` to the macro code in bevy_asset. The output showed full_path was empty, and the feature off.

My suspicion is that that the cfg attribute in the macro is being evaluated in the context of the library. I think I've confirmed this by adding the it as a feature on the library itself, and enabling it for the example, which fixes the issue:

1. Change the library's Cargo.toml to include

```toml
[features]
embedded_watcher = []
```

2. Run the example with `cargo run --example example --features embedded_watcher`

3. Modify the shader - it is now reloaded.

**Comment by hymm** [comment]
This looks like it was already fixed in https://github.com/bevyengine/bevy/pull/11370
