### ISSUE TITLE
CI fails to build (no `Uid` in `unistd`)

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy#11702]
## Bevy version

Main branch (71be08af68e081cab466f3bbe3728c30db3a94f7)

## \[Optional\] Relevant system information

N/A, this is running in Github Actions.

## What you did

```shell
$ cargo run -p ci -- lints
```

## What went wrong

```shell
error[E0432]: unresolved import `nix::unistd::Uid`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-3.14.1/src/address.rs:9:5
   |
9  | use nix::unistd::Uid;
   |     ^^^^^^^^^^^^^^^^ no `Uid` in `unistd`
   |
note: found an item that was configured out
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.26.4/src/unistd.rs:73:12
   |
73 | pub struct Uid(uid_t);
   |            ^^^
   = note: the item is gated behind the `user` feature

error[E0432]: unresolved import `nix::unistd::Uid`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-3.14.1/src/handshake.rs:4:5
   |
4  | use nix::unistd::Uid;
   |     ^^^^^^^^^^^^^^^^ no `Uid` in `unistd`
   |
note: found an item that was configured out
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.26.4/src/unistd.rs:73:12
   |
73 | pub struct Uid(uid_t);
   |            ^^^
   = note: the item is gated behind the `user` feature
```

## Additional information

Issue seemed to start around 5 hours ago with [this Github Action run](https://github.com/bevyengine/bevy/actions/runs/7774668674). Every run since then has failed.

I'm unable to reproduce this on my personal laptop (Mac), but the issue seems to stem from the crates `zbus` and `nix`. It appears `nix`'s `user` feature flag is not enabled.

**Comment by alice-i-cecile** [comment]
https://github.com/dbus2/zbus/pull/568#issuecomment-1925893155

This should be fixed upstream shortly.

**Comment by BD103** [comment]
`zbus` 3.15.0 has been released, fixing this issue. The CI has not been run yet since the release, but I'm going to close this assuming that it works.
