### ISSUE TITLE
Use a &'static str inside of `Window::name`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11718]
Could this be a &'static str instead? Given that it's not supposed to be changed?

_Originally posted by @atornity in https://github.com/bevyengine/bevy/pull/7650#discussion_r1477332004_

**Comment by SludgePhD** [comment]
Wouldn't that make it impossible to compute/format the window name during creation without leaking memory?

**Comment by alice-i-cecile** [comment]
Yeah, fair point. Closing this out.

**Comment by ManevilleF** [comment]
Would a `Cow<&'static str>` work then ?
