### ISSUE TITLE
`Meshable` probably shouldn't require `Default`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11746]
`Meshable` probably shouldn't require `Default`, but imo the shapes should have (consistent) defaults. It can be useful at least for prototyping, and an editor (like Unity, Godot etc.) would need some defaults for shapes anyway

_Originally posted by @Jondolf in https://github.com/bevyengine/bevy/pull/11688#discussion_r1480456669_

**Comment by Jondolf** [comment]
I think this might've been a misunderstanding, as `Meshable` already doesn't seem to require `Default` now that I'm double-checking. So this doesn't seem to be an actual issue and can probably be closed?

(extra context: https://github.com/bevyengine/bevy/pull/11688#discussion_r1481858675)
