### ISSUE TITLE
Ordering constraints referencing `RenderUiSystem::ExtractAtlasNode` aren't doing anything

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11749]
It seems like removing `extract_atlas_uinodes` here also means that the ordering constraints referencing `RenderUiSystem::ExtractAtlasNode` aren't doing anything since nothing is in that set now. If its no longer needed we should remove it.

_Originally posted by @odecay in https://github.com/bevyengine/bevy/pull/5103#discussion_r1480569178_

**Comment by valenotary** [comment]
I'm just trusting that the ask to delete this allegedly vestigial section is _actually_ vestigial :P
