### ISSUE TITLE
Turn `Mesh::set_indices` into `Mesh::insert_indices`

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#11740]
## What problem does this solve or what need does it fill?

We have [`Mesh::insert_attribute`](https://docs.rs/bevy/latest/bevy/prelude/struct.Mesh.html#method.insert_attribute) and [`Mesh::remove_attribute`](https://docs.rs/bevy/latest/bevy/prelude/struct.Mesh.html#method.remove_attribute).

But for indices we have `Mesh::remove_indices` (added in #11733) and [`Mesh::set_indices`](https://docs.rs/bevy/latest/bevy/prelude/struct.Mesh.html#method.set_indices) which accepts `Option`. It's inconsistent with the attributes API.

## What solution would you like?

I would suggest to make [`Mesh::set_indices`](https://docs.rs/bevy/latest/bevy/prelude/struct.Mesh.html#method.set_indices) similar to [`Mesh::insert_attribute`](https://docs.rs/bevy/latest/bevy/prelude/struct.Mesh.html#method.insert_attribute), i.e. pass the value instead of `Option`.

Ping @solis-lumine-vorago since he may be interested in it.

**Comment by solis-lumine-vorago** [comment]
I think this is a good idea. Since  we have `Mesh::remove_indices` now, there is no need to pass an `Option` to `Mesh::set_indices`.
- Lynn (they/them)
