### ISSUE TITLE
`two_passes` example breaking on Windows

### ISSUE THREAD

**Issue by afonsolage** [bevyengine/bevy#11755]
## Bevy version

Main ([f514d5c](https://github.com/bevyengine/bevy/commit/f514d5cc1525a85bb459e1175e715d53ed7cca39))

## Relevant system information

```
AdapterInfo { name: "AMD Radeon RX 6750 XT", vendor: 4098, device: 29663, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "24.1.1 (AMD proprietary shader compiler)", backend: Vulkan }
SystemInfo { os: "Windows 11 Pro", kernel: "22631", cpu: "", core_count: "6", memory: "31.9 GiB" }
```

## What you did

`cargo run --example two_passes`

## What went wrong
Sometimes it crashes (in 5 runs, crashes 2 times). The problem is only on startup, after that, seems to be working fine.
```
thread '<unnamed>' panicked at crates\bevy_core_pipeline\src\msaa_writeback.rs:83:18:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in exclusive system `bevy_render::renderer::render_system`!
thread 'Compute Task Pool (5)' panicked at crates\bevy_render\src\pipelined_rendering.rs:145:45:
called `Result::unwrap()` on an `Err` value: RecvError
error: process didn't exit successfully: `target\debug\examples\two_passes.exe` (exit code: 101)
```

[backtrace.log](https://github.com/bevyengine/bevy/files/14192606/backtrace.log)

## Additional information

Seems to be related to #10812, since it works fine on commit [7705c1d](https://github.com/bevyengine/bevy/commit/7705c1dd6cba9857728104537d065ff4610638c6) but breaks on [9f7e61b](https://github.com/bevyengine/bevy/commit/9f7e61b81943a885f84e0e5bc9d6d8871f72274f)

**Comment by BorisBoutillier** [comment]
This is not specific to windows, I have reproduced the issue on Linux.

**Comment by mockersf** [comment]
I can't reproduce on macOS

This should be investigated for the 0.13 so we have an idea of the underlying issue

**Comment by BorisBoutillier** [comment]
Msaa_writeback is the only file that miss the checking of the result when getting the pipeline.
Doing a PR to fix that
