### ISSUE TITLE
Deprecate then remove bevy_render shapes in favor of bevy_math shapes

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11762]
The plan is to remove the render shapes in a follow up. We are temporally copying rather than replacing to make the patch smaller and more manageable.

_Originally posted by @NthTensor in https://github.com/bevyengine/bevy/issues/11688#issuecomment-1930606460_

**Comment by NthTensor** [comment]
Currently being worked on by @Jondolf. Would be nice to see in 0.13, ping me if you need help.

**Comment by Jondolf** [comment]
Yep, working on it right now! 250 deprecation warnings left in the examples...

**Comment by NthTensor** [comment]
Resolved by https://github.com/bevyengine/bevy/pull/11773.
