### ISSUE TITLE
Frame unstable in many_foxes example

### ISSUE THREAD

**Issue by re0312** [bevyengine/bevy#11787]
## Bevy version
main(#11781 )

## \[Optional\] Relevant system information
windows AMD R7-4800H NV 2060

## What you did
Run example "many_foxes"

## What went wrong
fps jump between 90- and 150+

## Additional information

Frame Time show
![image](https://github.com/bevyengine/bevy/assets/45868716/cd2fe669-f00a-4ee2-941d-5a094c45a5eb)

`prepare_windows `will block a long time sometimes
strangely, this phenomenon is intermittent(with an interval about 1 second in my computer)
![image](https://github.com/bevyengine/bevy/assets/45868716/a75b8e96-f488-4693-9d11-e9dcc87c900d)

Seems introduced by #10268

**Comment by NthTensor** [comment]
Could this be contention with other applications? Can you reproduce this issue on examples, or is it `many_foxes`?

**Comment by re0312** [comment]
> Could this be contention with other applications? Can you reproduce this issue on examples, or is it `many_foxes`?

looks like not application contention, I can reproduce this issue in example `many_foxes ` after pr 10268

**Comment by alice-i-cecile** [comment]
@re0312 did you bisect to determine that #10628 the exact cause of this?

**Comment by re0312** [comment]
> @re0312 did you bisect to determine that #10628 the exact cause of this?

yeah, but 10628（x)  10268(√）, I restart my computer and close unnecessary apps just now, It still happens to me  after 10268,TBH,the issue is reallly weird and I checked it for several times but got the same result . It would be greatly appreciated if anyone could try to reproduce it with other computer to provide convincing proof that this is a real bug versus an environmental fluke.

**Comment by NthTensor** [comment]
I have tried running many_foxes on current main and have not been able to reproducethis. Linux intel APU laptop.

**Comment by superdump** [comment]
Is that a laptop? Are you always running on AC power and with GPU clock frequencies locked?

**Comment by re0312** [comment]
> Is that a laptop? Are you always running on AC power and with GPU clock frequencies locked?

yeah,laptop with the power supply plugged in but without manually locking the GPU clock speed（default performance mod) , this issue only happens when I checkout  branch after 10268 .
