### ISSUE TITLE
Add a method to convert from `Mut` to `Ref`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11827]
Regarding access to `Ref<T>` from `Query<&mut T>`,  another option would be to allow `Mut<T>` to downgrade into a `Ref<T>` for a similar effect.

_Originally posted by @james7132 in https://github.com/bevyengine/bevy/issues/11545#issuecomment-1937901729_

**Comment by hymm** [comment]
there's already a `From` impl for it. https://dev-docs.bevyengine.org/bevy/ecs/change_detection/struct.Mut.html#impl-From%3CMut%3C'w,+T%3E%3E-for-Ref%3C'w,+T%3E

**Comment by alice-i-cecile** [comment]
I think that should cover most of the needs then. If we can find other targeted improvements to this I'm on board.
