### ISSUE TITLE
Camera with RenderTarget::Image renders despawned entities 

### ISSUE THREAD

**Issue by franklinblanco** [bevyengine/bevy#11844]
## Bevy version

`bevy = { version = "0.12.1" }`

## Relevant system information
`cargo 1.77.0-nightly (1ae631085 2024-01-17)`

`AdapterInfo { name: "Apple M1 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }`

### [CODE WITH START & UPDATE SYSTEM](https://gist.github.com/franklinblanco/44c25e473e91813e77de1b0061be3da3)

My goal was to create a system in which I could at runtime, create Images of 3D GLTF assets spawned from scenes. It's a very modular system, so it's impractical to create all combinations of items before the app runs. So the system needs to whenever an item is picked up or modified, spawn that item on a setup scene and create an Image, add it to the asset system, and store a handle to that image in a Hasmap resource with the item key.

Then, when the inventory is opened use the item as a key to retrieve the image from the hashmap Resource.

I accomplished that, and it works pretty well, except for one thing.

## What went wrong

I'll show it with screenshots as it's hard to explain with words.

On the first Item I pick up, this is how the image looks (Look at the rig slot). All good here.
![Screenshot 2024-02-13 at 11 58 23 AM](https://github.com/bevyengine/bevy/assets/72827992/e4489b03-76e3-46da-a3c1-b8ae9bbacb02)
I'll show how it looks in the scene where the camera is as well:
![Screenshot 2024-02-13 at 12 00 31 PM](https://github.com/bevyengine/bevy/assets/72827992/2bbeb2fd-0510-4a88-b4d8-92e9acb70bda)

That all looks good, as it should. So here comes the second item I pickup.
Keep in mind, I make sure to despawn the previous item from the image creation scene on every pickup.
As you can see, when I picked up the second item (Look at the Primary Firearm slot), it looks like the previous item (the rig), is still there
![Screenshot 2024-02-13 at 12 01 44 PM](https://github.com/bevyengine/bevy/assets/72827992/826f82ac-50ca-4a43-b6b1-bb117b67edba)
Here's the scene where the camera is. 
![Screenshot 2024-02-13 at 12 02 37 PM](https://github.com/bevyengine/bevy/assets/72827992/4d12080f-392e-46d9-984b-58b6f3d6153d)
You can clearly see that the rig isn't there. And just in case, I confirmed with debugging, 2 separate images are being used. And yes, there's only one image in the UI for each slot, so it's also not a problem of spawning two separate images on top of each other. I'm sure the problem is in the Rendering, as the camera isn't detecting the change of when I despawn the item, further proof of this is that the camera is still on and writing to the last image displayed, as it still holds that RenderTarget.

And it keeps happening with every item picked up after that. 

In this one I picked up a third item and you can see, the item picked up contains all the previous items picked up in the texture. 
![Screenshot 2024-02-13 at 12 06 23 PM](https://github.com/bevyengine/bevy/assets/72827992/ff2649f4-bb64-4c3e-89bc-38fbdeabae39)

So the 3rd Item Image contains the 3rd, 2nd and 1st items.
The 2nd item image contains the 2nd and 1st items.
The 1st item image only contains it's own.

I've tried despawning and respawning the Camera on every item pickup, and no luck. I could even move/rotate the items in front of the camera and they get updated in the inventory but the previous items are still there for some reason.

## Additional information
My theory is something to do with the GPU still having the items rendered for some reason or in a cache somewhere. Maybe the despawn_descendants isn't doing something right. But it doesn't make sense, as with a normal camera that renders to a window you can always see those changes updated. I tried doing a Perspective camera instead of orthographic, and same result...

(Thank you all for your hard work, sorry for putting you through all of this!)

**Comment by BorisBoutillier** [comment]
Have you tried to create the new `Image` using the `Image::new_fill(` function, l with a black data ? probably `[ 0,0,0,255]`
Because `Image::resize(` add all `0` in data, which means transparent pixel probably, and I wonder if this is rather the issue here.

**Comment by franklinblanco** [comment]
Hi, @BorisBoutillier Thanks for taking the time to write your reply. In my case having an image without a transparent background would be something I don't want. When I copied the example for rendering to an Image, the camera.clear_color was set to white and I didn't want that. The reason is that I need the image to be placed on top of grids, and the grids behind the item should be visible, as it is here:
![Screenshot 2024-02-13 at 12 53 01 PM](https://github.com/bevyengine/bevy/assets/72827992/6930c05c-d637-4ece-94fc-9d254b3103e8)

**Comment by Lommix** [comment]
I also encountered this bug. Changing the render target of a no-clearing camera at runtime in an update schedule for example instantly copies over the previews rendered view into the new target.
The expected behavior would be, that with a new render target the camera would clear its current buffer, but I guess the render target, is not the actual view buffer of the camera. Which makes sense, the real buffer image lives properly on the GPU and gets copied back to the game world. Have not found a solution yet, other than spawning a new camera.

**Comment by franklinblanco** [comment]
Hi @Lommix I tried doing that and I had no success, you mind going into a bit more detail? 
 Thanks for replying!

**Comment by Lommix** [comment]
You are right, I did some additional testing. I am now very confused as well. Even when letting the old camera persist with a dummy target, the same problem carries over to the new one. I have no solution.

**Comment by franklinblanco** [comment]
Thank you very much for the time anyways! @Lommix

**Comment by BorisBoutillier** [comment]
Hello,
Instead of using :
```
clear_color: ClearColorConfig::None,
```
Can you try:
```
clear_color: ClearColorConfig::Custom(Color::NONE)
```

With `ClearColorConfig::None` the render target is not cleared, only modify the pixel that are effectively rendered.
With `ClearColorConfig::Custom(Color::NONE)` the render target is first cleared with a transparent pixel color, then the rendered pixel are added.

**Comment by franklinblanco** [comment]
NO WAY!! Thank you so much @BorisBoutillier That worked perfectly. Is this expected behavior for some reason?

**Comment by BorisBoutillier** [comment]
Yes, I think this is the expected behaviour, as can be read from the [`ClearColorConfig`](https://docs.rs/bevy/latest/bevy/core_pipeline/clear_color/enum.ClearColorConfig.html) documentation:
``` No clear color is used: the camera will simply draw on top of anything already in the viewport.```

And I suppose that the GPU use the same memory zone to render the camera, only the copy from GPU to CPU goes to the new image handle when the render target is changed, and so some 'ghosting' happens with the previous content of the GPU memory.

Forcing an explicit  ClearColor, ensure a clearing of  the content of the GPU buffer.

**Comment by franklinblanco** [comment]
Perfect then, I'll close this. Again thank you very much for your time.
