### ISSUE TITLE
Missing type registrations for animation types

### ISSUE THREAD

**Issue by torsteingrindvik** [bevyengine/bevy#11848]
## What problem does this solve or what need does it fill?

In my app I have this type:

```rust
#[derive(Debug, Clone, Asset, Reflect, Default)]
pub struct CustomAnimation {
    name: String,
    curves: Vec<VariableCurve>,
}
```

This allows me to hot-reload a custom animation for any entity having a `&Handle<CustomAnimation>` component.

However, there were several missing type registrations in Bevy I had to add in order to do this.

## What solution would you like?

Add the missing type registrations in the appropriate places:

- `Vec<Vec3>`
- `Vec<VariableCurve>`
- `Vec<Quat>`
- `VariableCurve`
- `Interpolation`
- `Keyframes`

**Comment by ekropotin** [comment]
I want to work on this issue if it's OK

**Comment by torsteingrindvik** [comment]
> Hello @torsteingrindvik 
> So I'd understand it better, could you please provide a few code examples of how you add these type registrations? 

Hi, here is an example of a whole bunch of registrations:
 https://github.com/bevyengine/bevy/blob/bc98333d7c53e971b3fe0dd3122c98d99671b2a7/crates/bevy_ui/src/lib.rs#L100

If you search for the method name you can find similar uses sprinkled all over Bevy.

So the task is to add the ones mentioned in this issue in a similar way in the places most appropriate for the given types.
