### ISSUE TITLE
Asset server load state not working for individual assets

### ISSUE THREAD

**Issue by willcrichton** [bevyengine/bevy#1184]
**Bevy version**

0.4.0

**Operating system & version**

OSX

**What you did**

Patterned after [this example](https://github.com/bevyengine/bevy/blob/master/examples/2d/texture_atlas.rs), I tried to make an on-load event for a gLTF scene. The code:

```rust
use bevy::{asset::LoadState, prelude::*};

fn main() {
  App::build()
    .init_resource::<AssetHandles>()
    .add_plugins(DefaultPlugins)
    .add_resource(State::new(AssetState::Loading))
    .add_stage_after(stage::UPDATE, "assets", StateStage::<AssetState>::default())
    .on_state_enter("assets", AssetState::Loading, load_assets.system())
    .on_state_update("assets", AssetState::Loading, check_assets.system())
    .on_state_enter("assets", AssetState::Finished, init_assets.system())
    .run();
}

#[derive(Clone)]
enum AssetState {
  Loading,
  Finished,
}

[derive(Default)]
struct AssetHandles {
  scene: Handle<Scene>,
}

fn load_assets(
  commands: &mut Commands,
  mut asset_handles: ResMut<AssetHandles>,
  asset_server: Res<AssetServer>,
) {
  asset_handles.scene = asset_server.load("models/Monkey.gltf#Scene0");
  commands.spawn_scene(asset_handles.scene.clone());  
}

fn check_assets(
  mut state: ResMut<State<AssetState>>,
  asset_handles: ResMut<AssetHandles>,
  asset_server: Res<AssetServer>,
) {
  if let LoadState::Loaded = asset_server.get_load_state(&asset_handles.scene) {
    state.set_next(AssetState::Finished).unwrap();
  }
}

fn init_assets(
  asset_handles: Res<AssetHandles>,
  scenes: ResMut<Assets<Scene>>,
) {
  let scene = scenes.get(&asset_handles.scene).unwrap();
}
```

**What you expected to happen**

The `scenes.get(...)` call should return `Some`.

**What actually happened**

The `scenes.get(...)` call returned `None`, suggesting that the asset was not actually loaded (or that I'm using the API incorrectly somehow?).

**Comment by willcrichton** [comment]
After some debugging, if I use `load_folder` and `HandleUntyped` then the program works as expected. It seems the issue is not with gLTF, but rather loading individual assets vs. a folder of assets.

**Comment by mockersf** [comment]
This is working for me using current master.

Adding the `#Scene0` to load a scene from a gltf file is a recent change, and was not needed in bevy 0.4, check the [`load_gltf.rs`](https://github.com/bevyengine/bevy/blob/v0.4.0/examples/3d/load_gltf.rs) example from the release (instead of the [current one](https://github.com/bevyengine/bevy/blob/master/examples/3d/load_gltf.rs) - you can see the difference)

**Comment by willcrichton** [comment]
I think it was a version issue, I was able to get this working.
