### ISSUE TITLE
Run Compute shaders in the same binding context as vertex/fragment shaders  

### ISSUE THREAD

**Issue by davids91** [bevyengine/bevy#11853]
## What problem does this solve or what need does it fill?
Executing a compute shader is possible, e.g. :  https://github.com/Kjolnyr/bevy_app_compute
However, in order to do so some separate calls are required, and a different binding context, so buffers can not be shared. 

In complex calculations, e.g. raytracing or particle systems, compute shaders are an ideal way to execute code in a well defined massively parallel context.  However if the output of the compute shader is large, it creates a massive overhead to copy the data from GPU --> CPU and then back again just to display the rendered results. 

## What solution would you like?
Extend  the pipeline with dispatching the compute shaders in the same context, should there be a compute shader available, OR a flag is set to true in e.g. the Material trait.

## What alternative(s) have you considered?
- Copying data back and forth, which is slooow
- Running the compute shaders parallell to the fragment shader, but data did not transfer between them because they ran in a different context. 

## Additional context
Running compute shaders and the fragment shade in the same context but with different dispatch calls is possible, see(mildly related): https://forum.babylonjs.com/t/data-transfer-from-compute-shader-to-renderer/45576

---
Edit: under binding context/context I mean pipeline

**Comment by JMS55** [comment]
I'm not really sure what you mean by "context" here. You definitely can create a buffer, dispatch a compute shader to write some data to it, and then bind it in your material to read from during our mesh draws. You don't have to copy data back to the CPU, you can just bind the buffer you wrote to in the compute pass for your material.

Can you expand more on what you're trying to do, and what issues you're running into?

**Comment by davids91** [comment]
Sorry openGL stuck on me... I meant pipelines here. 

Specifically what I would like to do is to dispatch a compute shader, and then have the results being displayed by the fragment shader in a draw pipeline ( specifically in a Material ). 

An example of what I did with only the fragment shader: https://github.com/davids91/shocovox/blob/main/examples/bevy_wgpu_render.rs

**Comment by superdump** [comment]
Have you seen the compute shader game of life example? It uses a compute shader to simulate the game of life in a texture, and then that texture is rendered to the window as a fullscreen sprite. There is no copy back to the CPU. It’s just a compute pass and the transparent 2D main pass where the sprite is drawn.

**Comment by davids91** [comment]
I saw the example I just couldn't figure out how the texture itself is getting displayed. I see there are some bevy-relevant nodes, and a RenderLabel, which I assume is being displayed, but there are just too many nuts and bolts in play here. 

This example right?
https://github.com/bevyengine/bevy/blob/main/assets/shaders/game_of_life.wgsl
https://github.com/bevyengine/bevy/blob/main/examples/shader/compute_shader_game_of_life.rs


I see that the texture being rendered is being rendered by the compute shader, and there's no copy to CPU, thanks for the heads up, that I missed previously!

Even with the example  if I'm about to build a system like this I would rather extend the functionality of bevy, I just don't know that much about its inner workings.

**Comment by davids91** [comment]
Update! 
I've made it ... Should anyone be interested. This is totally possible as it is.
