### ISSUE TITLE
Support the KHR_texture_transform GLTF extension

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy#11869]
## What problem does this solve or what need does it fill?

In Blender, the default way of making sure a texture tiles `n` times is to add a `UV Map` and a `Mapping` node, like this;
![image](https://github.com/bevyengine/bevy/assets/9047632/9ffd7db8-7730-49af-88e2-d3ff66b95c74)
The above example tiles the texture exactly 5 times.

This transforms the UV. The Blender GLTF exporter [supports this](https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html#uv-mapping) by writing it to the [KHR_texture_transform](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_texture_transform/README.md) extension. So, setting the nodes up as follows, we get a nicely tiled GLTF:
![image](https://github.com/bevyengine/bevy/assets/9047632/6b7d5469-bb94-44fb-9be4-8b8c827f040c)
I have a simple greyboxing grid texture applied to a cube in this case. Viewing it through a GLTF viewer, I get this:
![image](https://github.com/bevyengine/bevy/assets/9047632/9effd565-8691-47cb-b8f6-723cafe27d98)
As you can see, the text in the grid is repeated 5 times per face. Opening this up in Bevy however... (ignore the poor lighting)
![image](https://github.com/bevyengine/bevy/assets/9047632/529fedee-4cf4-41f1-b1fe-02b75e83978c)
Oh no! Bevy does not support GLTF extensions yet, so it just stretches the texture instead of tiling it!

## What solution would you like?

Ideally, Bevy should apply the transforms to the UV automatically when encountering this extension. As the Khronos group link specifies, most implementations ignore the `rotation` value, so I think it's fine if we do too. Most important are the `offset` for texture atlases and `scale` for tiling.

## What alternative(s) have you considered?

Leave it to the user. https://github.com/bevyengine/bevy/pull/11138 allows us to read the extension manually, so a user could write a custom shader or a shader extension for this.

## Additional context

- Related issue: https://github.com/bevyengine/bevy/issues/399
- Fixes: https://github.com/bevyengine/bevy/issues/6335
- Implements a part of https://github.com/bevyengine/bevy/issues/5178 and https://github.com/bevyengine/bevy/issues/11350

**Comment by janhohenheim** [comment]
I'd be ready to implement this myself if anyone gave me some pointers on how/where to change the UVs :)

**Comment by alice-i-cecile** [comment]
It looks like the PR has been abandoned by the author: adopt it by forking the work and submitting a new PR, then ping the original reviewers for a re-review :)

**Comment by janhohenheim** [comment]
@alice-i-cecile, alright, I'll try to get it done later, quick enough for 0.13 💪
