### ISSUE TITLE
WebGL2 support broken: index out of bounds

### ISSUE THREAD

**Issue by DGriffin91** [bevyengine/bevy#11885]
## Bevy version fe777d5c3fba64bec250b8ced3a6ba98fbd07a64

The deferred rendering example is broken on WebGL2 (And will also be broken on WebGPU, I expect).

The issue was introduced at https://github.com/bevyengine/bevy/commit/4c15dd0fc52a539a9bd41452cdae7fd07ec77134 with https://github.com/bevyengine/bevy/pull/10268

```
panicked at [...]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-0.19.1\src\gles\command.rs:749:21:
index out of bounds: the len is 16 but the index is 16
```

**Comment by mockersf** [comment]
the error message is different with WebGPU, but it could be the same error with a more explicit log:
```
The number of sampled textures (17) in the Fragment stage exceeds the maximum per-stage limit (16).
 - While calling [Device].CreatePipelineLayout([PipelineLayoutDescriptor]).
```

**Comment by superdump** [comment]
https://github.com/bevyengine/bevy/pull/10268/files#r1468773590

**Comment by alice-i-cecile** [comment]
This should be fixed by https://github.com/bevyengine/bevy/pull/11893 correct?

**Comment by DGriffin91** [comment]
@alice-i-cecile No, this is a separate issue.
