### ISSUE TITLE
duplicate preregistration for type `bevy_render::texture::image::Image`

### ISSUE THREAD

**Issue by doonv** [bevyengine/bevy#11881]
## Bevy version

main (https://github.com/bevyengine/bevy/commit/dd619a1087ea3871a3744c7f6156194c4a81cf80)

## What you did

```rs
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run();
}
```

## What went wrong

There was a log message: `` INFO bevy_asset::server::loaders: duplicate preregistration for type `bevy_render::texture::image::Image`. `` This is caused by https://github.com/bevyengine/bevy/pull/11644 (see https://github.com/bevyengine/bevy/pull/11644#issuecomment-1926322050). And while it appears to be intentional after reading about #11644, having a warning-like message appear every time you use `DefaultPlugins` makes it look like a bug, this should be fixed.

Additionally the log level of the message should be changed to `WARN`.

**Comment by rparrett** [comment]
Would be fixed by #11870
