### ISSUE TITLE
Move gizmos examples

### ISSUE THREAD

**Issue by pablo-lua** [bevyengine/bevy#11899]
## What problem does this solve or what need does it fill?

With #9400, there is many things planned for gizmos, and we need examples to this new features, but the examples actually are inside the 2d and 3d folders, which can be hard to find and it may end up messing up the organization of the examples a little.

## What solution would you like?

Move gizmos examples to a dedicated `gizmos` folder inside `examples` 

## What alternative(s) have you considered?

Leave it as it is

**Comment by alice-i-cecile** [comment]
Speaking as SME-Docs: I'd really like a dedicated gizmos folder. We should do that in an initial PR, and then add more later.

**Comment by ekropotin** [comment]
I can do that
