### ISSUE TITLE
Published crates version is still 0.0.1

### ISSUE THREAD

**Issue by berkus** [bevyengine/bevy#119]
While 0.1.2 is available on crates.io, all tools including cargo still think "0.0.1" is the latest and install that.

```
You've successfully subscribed for updates on bevy (current version 0.0.1 [docs.rs] [crates.io] [lib.rs]) crate. Use /unsubscribe to unsubscribe.
```
^ bot using crates.io-index thinks latest is 0.0.1

```
❯ cargo add bevy
    Updating 'https://github.com/rust-lang/crates.io-index' index
      Adding bevy v0.0.1 to dependencies
```

Something is wrong.

**Comment by cart** [comment]
Uh oh. Looking now

**Comment by berkus** [comment]
Any ideas what's happening? Probably re-release as new version to force crates-index update?

**Comment by lberrymage** [comment]
Is this fixed now?

**Comment by cart** [comment]
This is fixed for me. This is probably some sort of caching issue thats out of our hands.
