### ISSUE TITLE
Replicating Getting Started from Bevy Webpage opens window that closes immediately

### ISSUE THREAD

**Issue by RaoulLuque** [bevyengine/bevy#11902]
## Bevy version
0.12.1

## Relevant system information
System information that shows up when starting bevy projects:
AdapterInfo { name: "AMD Radeon RX 470 Graphics (RADV POLARIS10)", vendor: 4098, device: 26591, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 23.0.4-0ubuntu1~22.04.1", backend: Vulkan }

Rust version: cargo 1.76.0 (c84b36747 2024-01-18)

## What you did

I followed the tutorial on the Bevy getting started [page](https://bevyengine.org/learn/quick-start/getting-started/) up to adding the plugins and the default plugins.

The code can be seen in additional information just like the cargo.toml.

## What went wrong

By this point a window should open when I cargo run the app. But: the window just opens for a split second and closes immediately. Also no messages show up in the console although having defined systems like the "hello world" from the tutorial.

## Additional information

The curios thing is that I can run bevy apps on my system and have developed an app. But start developing new apps does not seem to work for some reason. I tried a lot of different things (especially regarding the bevy features I included and didn't include for my projects) but was not able to fix the problem.

[This](https://github.com/RaoulLuque/rust-invasion) is the project I am referring to when I say that I can build bevy projects. I can rebuild it just fine and it works as intended. I have also tried copying the exact same Cargo.toml over and using it for the sample project from the bevy site but that doesn't work either (and takes an annoyingly long time to compile but that's something else and might be something on my end).

This is the code in the main.rs file:
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, add_people)
        .add_systems(Update, (hello_world, (update_people, greet_people).chain()));
}

#[derive(Component)]
struct Person;

#[derive(Component)]
struct Name(String);

fn add_people(mut commands: Commands) {
    commands.spawn((Person, Name("Elaina Proctor".to_string())));
    commands.spawn((Person, Name("Renzo Hume".to_string())));
    commands.spawn((Person, Name("Zayna Nieves".to_string())));
}

fn update_people(mut query: Query<&mut Name, With<Person>>) {
    for mut name in &mut query {
        if name.0 == "Elaina Proctor" {
            name.0 = "Elaina Hume".to_string();
            break; // We don’t need to change any other names
        }
    }
}

fn greet_people(query: Query<&Name, With<Person>>) {
    for name in &query {
        println!("hello {}!", name.0);
    }
}

fn hello_world() {
    println!("hello world!");
}

```

This is my Cargo.toml file (without the package header)

```TOML
# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies.bevy]
version = "0.12.1"
```

**Comment by RaoulLuque** [comment]
Well ... that's a rookie mistake I guess :sweat_smile: My bad. I've looked into the documentation/guide once again and it is clearly mentioned and I should've payed more attention I guess. Thanks :o

**Comment by alice-i-cecile** [comment]
No worries! I really appreciate people bringing up problems with our docs, even if sometimes it's just a silly mistake :)
