### ISSUE TITLE
CI "check-bans" check fails due to duplicate dependencies on raw-window-handle

### ISSUE THREAD

**Issue by ekropotin** [bevyengine/bevy#11917]
## Bevy version

Commit e6e25dead

## What went wrong
CI's `check-bans` check fails with the following error:
```
error[duplicate]: found 2 duplicate entries for crate 'raw-window-handle'
    ┌─ /home/runner/work/bevy/bevy/Cargo.lock:341:1
    │  
341 │ ╭ raw-window-handle 0.5.2 registry+https://github.com/rust-lang/crates.io-index
342 │ │ raw-window-handle 0.6.0 registry+https://github.com/rust-lang/crates.io-index
    │ ╰─────────────────────────────────────────────────────────────────────────────^ lock entries
    │  
    = raw-window-handle v0.5.2
      └── ndk v0.7.0
          ├── cpal v0.15.2
          │   └── rodio v0.17.3
          │       └── bevy_audio v0.12.0
          │           └── bevy_internal v0.12.0
          │               ├── bevy v0.12.0
          │               └── bevy_dylib v0.12.0
          │                   └── bevy v0.12.0 (*)
          └── oboe v0.5.0
              ├── bevy_audio v0.12.0 (*)
              └── cpal v0.15.2 (*)
    = raw-window-handle v0.6.0
      ├── accesskit_winit v0.17.0
      │   └── bevy_winit v0.12.0
      │       ├── bevy_asset v0.12.0
      │       │   ├── bevy_animation v0.12.0
      │       │   │   ├── bevy_gltf v0.12.0
```

### 1
Add version `0.5.2` of `raw-window-handle` into skip list in `deny.toml`:
```
skip = [
  {name = "raw-window-handle", version = "0.5.2" }
]
```

### 2
Remove `raw-window-handle` crate from deny list in `deny.toml`

**Comment by ekropotin** [comment]
I also pretty confused by the fact that `cpal v0.15.2` and `oboe v0.5.0` are bringing NDK version `0.7`, as per repos https://github.com/RustAudio/cpal/blob/master/Cargo.toml#L76 https://github.com/katyo/oboe-rs/blob/master/Cargo.toml#L26, these crates depend on NDK version `0.8`
I'm new to Rust, so I'd appreciate if anyone could explain it to me.

**Comment by alice-i-cecile** [comment]
This was introduced in the winit 0.29 update. Related: #11052

**Comment by ameknite** [comment]
@ekropotin the problem is that even when they updated ndk to 0.8 in the Cargo.toml, they haven't released a new version to crates.io, so it can't be used.

**Comment by mockersf** [comment]
> @ekropotin the problem is that even when they updated ndk to 0.8 in the Cargo.toml, they haven't released a new version to crates.io, so it can't be used.
> 
> I hope they publish a new versions to Crates.io. [RustAudio/cpal#841](https://github.com/RustAudio/cpal/issues/841) [katyo/oboe-rs#59](https://github.com/katyo/oboe-rs/issues/59)

It needs to happen in steps:

1. oboe gets published
2. cpal use the new oboe version
3. coal gets published
