### ISSUE TITLE
Remove dependency on `sysinfo` crate

### ISSUE THREAD

**Issue by SkiFire13** [bevyengine/bevy#11929]
## What problem does this solve or what need does it fill?

I just ran `cargo build --timings` on the current `main` branch (commit `abb8c353f49a6fe9e039e82adbe1040488ad910a`) on Windows and I noticed that while multiple version of the `windows` crate were being used, one was particularly slow to compile (taking 60 seconds, compared to an average of 20 seconds for the others) and was a bottleneck for whole crate compilation pipeline. That version was being depended on by two crates: `gpu-allocator` and `sysinfo`. `gpu-allocator` enables only a couple of GPU related features, `sysinfo` on the other hand enables **a lot** of general purpose features.

I then tried a small experiment of removing `bevy_diagnostic` (and thus `sysinfo`) from the dependency graph, and compile times improved by 20 seconds (from 1:58 to 1:38, which is a 15% improvement overall). By looking at the new timings result, that same version of the `windows` crate now only took 15 seconds to compile, confirming that the features included by `sysinfo` were the problem.

## What solution would you like?

`sysinfo` should be replaced with a more lightweight alternative.

## What alternative(s) have you considered?

- Ask `sysinfo`'s maintainers to reduce the number of `windows` features required
- Make `bevy_diagnostic`'s `sysinfo` usage optional

## Additional context

[cargo-timing.zip](https://github.com/bevyengine/bevy/files/14320080/cargo-timing.zip)

**Comment by AxiomaticSemantics** [comment]
I'm down for making this plugin optional, I've personally done so before in my fork of bevy, if upstream is willing I'll follow up with a PR.

**Comment by mockersf** [comment]
@GuillaumeGomez it seems `sysinfo` pulls the `windows` crate with a lot of features https://github.com/GuillaumeGomez/sysinfo/blob/master/Cargo.toml#L52-L86

Are they all needed for Bevy use case, or could some be behind feature flags?
