### ISSUE TITLE
AmbientLight docs doesn't specify units

### ISSUE THREAD

**Issue by fintelia** [bevyengine/bevy#11933]
## How can Bevy's documentation be improved?

The documentation for `AmbientLight`s brightness field says:

> A direct scale factor multiplied with `color` before being passed to the shader.

However, it would be helpful to know the units of the product of multiplying color and the scale factor. I suspect the unit is either lux or nits, but I haven't investigated

**Comment by BD103** [comment]
`brightness` is a multiplier, so it itself does not have any units. It was originally added in #1605, where it calculates:

```rust
(ambient_light_resource.color * ambient_light_resource.brightness)
```

Which is equivalent to a `Vec4 * f32`. On main, it currently looks like:

https://github.com/bevyengine/bevy/blob/a9ca8491aa3f2dc99116e63d67a0625afe6e738d/crates/bevy_pbr/src/render/light.rs#L983-L984

**Comment by fintelia** [comment]
You could say the same thing about the skybox's [`brightness`](https://docs.rs/bevy/0.13.0/bevy/core_pipeline/struct.Skybox.html#structfield.brightness) field. The documentation I'm looking for is the analog of this line:

> Scale factor applied to the skybox image. After applying this multiplier to the image samples, the resulting values should be in units of [cd/m^2](https://en.wikipedia.org/wiki/Candela_per_square_metre).

**Comment by BD103** [comment]
That's a very good point. So would `AmbientLight::brightness` also be in cd/m^2, or would it be some other unit?

**Comment by superdump** [comment]
Looking at the code I think @fintelia ’s last comment is the correct answer.

**Comment by BD103** [comment]
Marking this as a good first issue. [`AmbientLight`](https://dev-docs.bevyengine.org/bevy/pbr/struct.AmbientLight.html)'s brightness field should document that it is in [cd/m^2](https://en.wikipedia.org/wiki/Candela_per_square_metre), similar to [`Skybox::brightness`](https://dev-docs.bevyengine.org/bevy/core_pipeline/struct.Skybox.html#structfield.brightness), if I'm understanding @superdump's comment correctly.

**Comment by janhohenheim** [comment]
Maybe it would also be good to specify that this is *not* equivalent to Filament's [IBL](https://google.github.io/filament/Filament.md.html#lighting/imagebasedlights/iblunit), even though the units are the same and they are both used for global illumination.

**Comment by superdump** [comment]
@janhohenheim my understanding is that if one sets bevy’s ambient light brightness to 1 then it would be the same. Or you can consider the combination of color * brightness to be the same as Filament’s IBL.

**Comment by janhohenheim** [comment]
@superdump how would you then set the IBL intensity?
