### ISSUE TITLE
Disable system stepping feature by default

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#11931]
## What problem does this solve or what need does it fill?

This feature should not be included in shipped games, and adds small but measurable performance overhead to running schedules.

## What solution would you like?

Disable the feature by default, and document that you need to enable it in the example.

## What alternative(s) have you considered?

Add this to your `Cargo.toml`, and update it every release:

```rust
default-features = false
features = [
  "animation",
  "bevy_asset",
  "bevy_audio",
  "bevy_gilrs",
  "bevy_scene",
  "bevy_winit",
  "bevy_core_pipeline",
  "bevy_pbr",
  "bevy_gltf",
  "bevy_render",
  "bevy_sprite",
  "bevy_text",
  "bevy_ui",
  "multi-threaded",
  "png",
  "hdr",
  "vorbis",
  "x11",
  "bevy_gizmos",
  "android_shared_stdcxx",
  "tonemapping_luts",
  "default_font",
  "webgl2",
]
```

## Additional context

Any other information you would like to add such as related previous work,
screenshots, benchmarks, etc.

**Comment by iiYese** [comment]
Is disabled really the better default tho? Release builds are the exception not debug builds.

**Comment by alice-i-cecile** [comment]
Disabling features of your dependencies in Rust is particularly painful: if it's not on the core path I'd prefer to keep it out.
