### ISSUE TITLE
autodetecting the RGBA8  texture format is incorrect

### ISSUE THREAD

**Issue by ethereumdegen** [bevyengine/bevy#11951]
## Bevy version

The release number or commit hash of the version you're using.
0.12 
 
 
- what were you expecting?
- what actually happened?

```
 loading an Rgba8Unorm like this 

  let splat_image_handle: Handle<Image> = asset_server.load(splat_texture_path);

actually makes the texture descriptor be RGBA16
so bevy autodetecting the texture format is incorrect
it thinks a 8 bit texture is 16 bit
```

TO REPLICATE: go into gimp , make a png image that is 8bit and RGBA (sRGB)

load it into bevy like the above code and see what bevy says the texture descriptor is.  bevy will declare that it is 16 bit !

**Comment by rparrett** [comment]
I can't reproduce with Bevy 0.12.1, 0.13, or main using the following:

<details>
  <summary>Image</summary>

![rgba8](https://github.com/bevyengine/bevy/assets/200550/7dbe1f72-2cd6-418f-b271-33c3980e22da)
```
 identify rgba8.png 
rgba8.png PNG 100x100 100x100+0+0 8-bit sRGB 23949B 0.000u 0:00.001
```
<img width="291" alt="Screenshot 2024-02-18 at 9 45 00 AM" src="https://github.com/bevyengine/bevy/assets/200550/191e8969-d81a-4b01-9180-9f297e18ce05">

</details>

<details>
  <summary>Code</summary>

```rust
//! Repro issue #11951

use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .init_resource::<ImageHandle>()
        .add_systems(Update, print_format)
        .run();
}

#[derive(Resource)]
struct ImageHandle(Handle<Image>);
impl FromWorld for ImageHandle {
    fn from_world(world: &mut World) -> Self {
        let asset_server = world.resource::<AssetServer>();
        ImageHandle(asset_server.load("rgba8.png"))
    }
}

fn print_format(mut printed: Local<bool>, images: Res<Assets<Image>>, handle: Res<ImageHandle>) {
    if *printed {
        return;
    }

    let Some(image) = images.get(&handle.0) else {
        return;
    };

    info!("{:?}", image.texture_descriptor.format);
    *printed = true;
}
```
</details>

Could you please provide an image and code that reproduce the issue?
