### ISSUE TITLE
[0.13] Cannot build without explicit `bevy_gizmos_macros` dependency

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#11953]
## Bevy version

```
[dependencies.bevy]
version = "0.13"
default-features = false
features = [ "bevy_core_pipeline", "bevy_render", "bevy_asset", "x11" ]
```

## What you did

From https://github.com/djeedai/bevy_hanabi:

```
cargo b --example firework --features="bevy/bevy_winit bevy/bevy_pbr 3d"
```

Also did some `cargo clean`, `cargo update`. Crate itself builds without issue, but doesn't depend on `bevy_winit` nor `bevy_pbr`. Only the examples which need those extra features break.

## What went wrong

```
error: failed to select a version for the requirement `bevy_gizmos = "^0.13.0"`
candidate versions found which didn't match: 0.12.1, 0.12.0, 0.11.3, ...
location searched: crates.io index
required by package `bevy_internal v0.13.0`
    ... which satisfies dependency `bevy_internal = "^0.13.0"` (locked to 0.13.0) of package `bevy v0.13.0`
    ... which satisfies dependency `bevy = "^0.13"` (locked to 0.13.0) of package `bevy_hanabi v0.10.0 (F:\dev\bevy_hanabi)`
perhaps a crate was updated and forgotten to be re-vendored?
```

## Additional information

Adding an explicit reference to `Cargo.toml` fixes the issue. Note that the original `Cargo.toml` never explicitly references the `bevy_gizmos` feature or crate.

```diff
  [dependencies.bevy]
  version = "0.13"
  default-features = false
  features = [ "bevy_core_pipeline", "bevy_render", "bevy_asset", "x11" ]

+ # Bug in 0.13, need explicit dependency
+ bevy_gizmos_macros = "0.13"
```

**Comment by djeedai** [comment]
Note: `bevy_sprite` has the same issue:

```
> cargo b --example 2d --no-default-features --features="bevy/bevy_winit bevy/bevy_sprite 2d"

error: failed to select a version for the requirement `bevy_sprite = "^0.13.0"`
candidate versions found which didn't match: 0.12.1, 0.12.0, 0.11.3, ...
location searched: crates.io index
required by package `bevy_internal v0.13.0`
    ... which satisfies dependency `bevy_internal = "^0.13.0"` (locked to 0.13.0) of package `bevy v0.13.0`
    ... which satisfies dependency `bevy = "^0.13"` (locked to 0.13.0) of package `bevy_hanabi v0.10.0 (F:\dev\bevy_hanabi)`
perhaps a crate was updated and forgotten to be re-vendored?
```

Adding an explicit `bevy_sprite = "0.13"` to the `[dev-dependencies]` section (since it's for an example) solves it.

**Comment by voidentente** [comment]
For me it's `bevy_asset` that's borked

**Comment by voidentente** [comment]
Can't reproduce the issue anymore. Maybe this was caused by crates.io lag. Can anybody confirm?

**Comment by BD103** [comment]
> Can't reproduce the issue anymore. Maybe this was caused by crates.io lag. Can anybody confirm?

I was unable to reproduce it either. I had a blank `main.rs` and the following for `Cargo.toml`:

```toml
[package]
name = "bevy-experiments"
version = "0.1.0"
edition = "2021"

[dependencies.bevy]
version = "=0.13.0"
default-features = false
features = ["bevy_core_pipeline", "bevy_render", "bevy_asset", "x11"]
```

`cargo build` works just fine.

**Comment by james7132** [comment]
I can't seem to replicate this either. @djeedai could this be an issue with your Cargo.lock?

**Comment by james7132** [comment]
This looks like it's tentatively resolved by #11928.

**Comment by djeedai** [comment]
I can't test again because it looks like `main` has a bunch of breaking changes compared to 0.13, so I'd need to upgrade Hanabi to be able to build

**Comment by mockersf** [comment]
You can try on https://github.com/bevyengine/bevy/tree/release-0.13.1 which should have no breaking change from the 0.13.

If it's the release, it should work even on a published 0.13.0

**Comment by james7132** [comment]
0.13.1 has been published. Might be worth trying on the those published versions.

**Comment by djeedai** [comment]
I've just tried with a `cargo clean` and cannot repro. I've also tried with `0.13.1` and cannot repro either. Closing. Thanks for the updates/fix!
