### ISSUE TITLE
example post_processing doesn't work in Wasm

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#11977]
## Bevy version

0.13, since https://github.com/bevyengine/bevy/pull/10812

## What you did

Example post_processing doesn't work in Wasm https://bevyengine.org/examples/Shaders/post-processing/

## What went wrong

It should display some chromatic distortion. It doesn't.

**Comment by BD103** [comment]
I'm getting a 404 when accessing [`post_processing.wgsl.meta`](https://bevyengine.org/assets/examples/shaders/post_processing.wgsl.meta). That may be the problem.

<img width="1552" alt="image" src="https://github.com/bevyengine/bevy/assets/59022059/53d81e73-1c96-42ff-98b1-d67e3f4de2e6">

**Comment by mockersf** [comment]
> I'm getting a 404 when accessing [`post_processing.wgsl.meta`](https://bevyengine.org/assets/examples/shaders/post_processing.wgsl.meta). That may be the problem.

Nop, unrelated and expected. 404 on wasm is the "file not found" status which is expected for those meta files
