### ISSUE TITLE
Move AlphaMode out of bevy_pbr

### ISSUE THREAD

**Issue by spectria-limina** [bevyengine/bevy#11985]
## Bevy version

0.13

## What you did

Tried to remove `bevy_pbr` from my dependency tree, in a project that uses exclusively 2D graphics. This is to improve compile times, binary size, and runtime efficiently.

## What went wrong

I expected this would be easy, but I use the third-party crate `bevy_vector_shapes` which relies on the enum `AlphaMode` from `bevy_pbr`.

I would have submitted a PR to remove the dependency, but it's nontrivial to do because of this need for alpha blending support. So now my project is running a full 3D render pipeline just because it wants a semitransparent square.

Given that alpha blending is useful in rendering in any number of dimensions, this is a bevy issue and will likely be encountered in other crates.

The enum should most likely be moved to `bevy_render`, where most types common to 2d and 3d rendering are located.

**Comment by mweatherley** [comment]
I'd be happy to take a look at this!
