### ISSUE TITLE
Bevy 0.13 not being able to detect gpu

### ISSUE THREAD

**Issue by LeMinhThin** [bevyengine/bevy#11992]
# Bevy version
0.13

## Relevant system information
Rust version: 1.76.0
OS: Arch Linux x86_64
CPU: Intel i5 3427U
Integrated graphics

Expected behavior
Bevy compiles and run normally

Actual behavior
Bevy crashes at runtime, throwing out this error
```
thread 'main' panicked at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.0/src/renderer/mod.rs:141:10:
Unable to find a GPU! Make sure you have installed required drivers! For extra information, see: https://github.com/bevyengine/bevy/blob/latest/docs/linux_dependencies.md
```

I have followed the instruction listed in the link but the problem persisted.
Bevy 0.12.1 compiles and ran fine so my system should have all the drivers required

**Comment by hornyjailfish** [comment]
bevy 0.13 give me huge listing `Warning: .drectve ... unrecognized`  on `rust 1.78-nightly-x86_64-pc-windows-gnu`
and list of `error LNK2005:  already defined in libwgpu_core-....rlib()` on `rust 1.78-nightly-x86_64-pc-windows-msvc`

code is default plugins and run app

compiles without errors with 0.12.1

dual graphics laptop if this could matter

**Comment by james7132** [comment]
@hornyjailfish is that caused by the same issue? Looks like you're compiling for Windows, while this issue seems to mostly affect Linux.

**Comment by hornyjailfish** [comment]
@james7132 i am just search fresh issues that could be relevant to 0.13 release at first

**Comment by diolix** [comment]
I have the same problem, i'm on windows 11, NVIDIA GeForce RTX 3070 Laptop GPU. Work when i use Bevy v.0.12.1 and i get the error "Unable to find a GPU! Make sure you have installed required drivers!" when i run with Bevy. v.0.13

**Comment by kitamiq** [comment]
Similar issue. Arch Linux with AMD GPU and RADV driver (as discrete graphics alongside Intel integrated graphics). Funny thing is, before the panic it gives me the `WARNING: radv is not a conformant Vulkan implementation, testing use only.`, which suggests that it _did_ find the correct GPU, but for some reason failed to recognize that.
I suspect this is related to the unfixed bug introduced in wgpu 0.19.X, see https://github.com/gfx-rs/wgpu/issues/5164
Everything works fine with Bevy 0.12.1 which uses some pre-0.19 version of wgpu

**Comment by LeMinhThin** [comment]
I don't know if this will help anyone but I think I've found a workaround.

1. Change wgpu's backend to gl, this can be accomplished on linux by setting the WGPU_BACKEND environent variable to gl
2. if you're on wayland, enable the wayland feature of bevy in your Cargo.toml

on my machine, bevy now runs fine, your milage may vary

**Comment by OtienoSamwel** [comment]
> I don't know if this will help anyone but I think I've found a workaround.
> 
> 1. Change wgpu's backend to gl, this can be accomplished on linux by setting the WGPU_BACKEND environent variable to gl
> 2. if you're on wayland, enable the wayland feature of bevy in your Cargo.toml
> 
> on my machine, bevy now runs fine, your milage may vary

Elaborate step 2 please

**Comment by LeMinhThin** [comment]
> > I don't know if this will help anyone but I think I've found a workaround.
> > 
> > 1. Change wgpu's backend to gl, this can be accomplished on linux by setting the WGPU_BACKEND environent variable to gl
> > 2. if you're on wayland, enable the wayland feature of bevy in your Cargo.toml
> > 
> > on my machine, bevy now runs fine, your milage may vary
> 
> Elaborate step 2 please

bevy = { version="0.13.1", features=["wayland"] }

**Comment by OtienoSamwel** [comment]
> > > I don't know if this will help anyone but I think I've found a workaround.
> > > 
> > > 1. Change wgpu's backend to gl, this can be accomplished on linux by setting the WGPU_BACKEND environent variable to gl
> > > 2. if you're on wayland, enable the wayland feature of bevy in your Cargo.toml
> > > 
> > > on my machine, bevy now runs fine, your milage may vary
> > 
> > 
> > Elaborate step 2 please
> 
> bevy = { version="0.13.1", features=["wayland"] }

Thanks. This works.
