### ISSUE TITLE
Serialization of `Name` component may not be working correctly

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#12001]
## Bevy version

0.13

## What you did

Modified the `scene` example to include `Name::new("TEST")`.

Weirdly, I also had to `.register_type::<Name>()` in the example's `App`, despite it being registered in [bevy_core](https://github.com/bevyengine/bevy/blob/v0.13.0/crates/bevy_core/src/lib.rs#L42).

<details>
<summary>
Diff
</summary>

```rust
diff --git a/examples/scene/scene.rs b/examples/scene/scene.rs
index dac36e96d..3acb19f11 100644
--- a/examples/scene/scene.rs
+++ b/examples/scene/scene.rs
@@ -8,6 +8,7 @@ fn main() {
         .register_type::<ComponentA>()
         .register_type::<ComponentB>()
         .register_type::<ResourceA>()
+        .register_type::<Name>()
         .add_systems(
             Startup,
             (save_scene_system, load_scene_system, infotext_system),
@@ -114,6 +115,7 @@ fn save_scene_system(world: &mut World) {
         component_b,
         ComponentA { x: 1.0, y: 2.0 },
         Transform::IDENTITY,
+        Name::new("TEST"),
     ));
     scene_world.spawn(ComponentA { x: 3.0, y: 4.0 });
     scene_world.insert_resource(ResourceA { score: 1 });
```
</details>

`cargo run --example scene`

And observe the serialized scene in the logged output.

## What went wrong

`Name` is serialized as:

```plain
"bevy_core::name::Name": (
  hash: 778249913144375361,
  name: "TEST",
),
```

Which is contrary to this comment on name:
https://github.com/bevyengine/bevy/blob/abb8c353f49a6fe9e039e82adbe1040488ad910a/crates/bevy_core/src/name.rs#L23-L29

And the stated goal of #11447.

And the migration guide text which suggests that `Name` will be serialized as a plain string.

## Additional information

Scenes will properly **de**serialize without `hash`, but only as a struct with a `name` field. Not as a plain string.

See also: #1037 where we removed the migration guide entry related to #11447.

**Comment by alice-i-cecile** [comment]
@coreh, any clues on what happened here?

**Comment by MrGVSV** [comment]
Do you have the `serialize` feature enabled? I wonder if it's causing issues if it's not enabled

**Comment by rparrett** [comment]
However, deserialization only works with
`"bevy_core::name::Name": "TEST"`
if the `serialize` feature is included!

**Comment by coreh** [comment]
Sorry for missing this, and thanks @soqb for the investigation/solution!
