### ISSUE TITLE
[0.13] Multi-camera (split screen) broken for > 2 cameras

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#12006]
## Bevy version

0.13, and 1d0ea78f3

## Relevant system information

Win11

```ignore
 AdapterInfo { name: "NVIDIA GeForce RTX 4070", vendor: 4318, device: 10118, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "537.58", backend: Vulkan }
```

## What you did

Run `split_screen.rs` example with 3+ cameras

## What went wrong

Only the first and last cameras render anything.

![image](https://github.com/bevyengine/bevy/assets/6532395/990860ba-aee8-40c0-9094-44fb281107ce)

## Additional information

Reproduced with 2/4/8 cameras in Hanabi example. Pattern is consistent (always first/last only). This is a regression, 4 cameras was working fine until 0.13.

**Comment by djeedai** [comment]
Repro here:

https://github.com/bevyengine/bevy/compare/main...djeedai:bug_12006?expand=1

**Comment by rparrett** [comment]
Does #11968 fix this?

**Comment by djeedai** [comment]
@rparrett no it doesn't.

**Comment by djeedai** [comment]
Fix was merged, closing.
