### ISSUE TITLE
Globals binding not available in vertex shader.

### ISSUE THREAD

**Issue by Jessie8Bit** [bevyengine/bevy#12015]
## Bevy version

0.13

## What you did

Attempt to update a shader to bevy 0.13 and use: "mesh_view_bindings::globals.time" in my vertex shader.

## What went wrong

Caused by:
    In Device::create_render_pipeline
      note: label = 'premultiplied_alpha_mesh_pipeline'
    Error matching ShaderStages(VERTEX) shader requirements against the pipeline
    Shader global ResourceBinding { group: 0, binding: 9 } is not available in the pipeline layout
    Visibility flags don't include the shader stage

**Comment by JMS55** [comment]
What kind of shader is this? Material, Material2d, UiMaterial, or something else?

**Comment by Jessie8Bit** [comment]
Material with custom vertex shader for water waves

**Comment by platlas** [comment]
I had similar issue, instead of VERTEX error was for FRAGMENT. It was related to: https://github.com/bevyengine/bevy/pull/10485  could it be relevant here as well?

**Comment by Jessie8Bit** [comment]
I just imported mesh_view_bindings::globals.time, but it said it was not available in "premultiplied_alpha_mesh_pipeline" vertex.

is it because of [this](https://github.com/bevyengine/bevy/blob/release-0.13.0/crates/bevy_pbr/src/render/mesh_view_bindings.rs#L182) or are globals available on an other binding for "premultiplied_alpha_mesh_pipeline"?

**Comment by IceSentry** [comment]
Sorry, I missed a visibility modifier when introducing the bind group layout entries feature. Here's the fix https://github.com/bevyengine/bevy/pull/12032
