### ISSUE TITLE
Improve Github Releases Note

### ISSUE THREAD

**Issue by ameknite** [bevyengine/bevy#12011]
I would like the GitHub release notes to include links to the [Release announcement ](https://bevyengine.org/news/bevy-0-13/) and the [Migration Guide](https://bevyengine.org/learn/migration-guides/0-12-to-0-13/).

Right now it only show the last commit.

![Screenshot 2024-02-20 at 14 39 21](https://github.com/bevyengine/bevy/assets/104745335/4874587f-0901-4a0e-a418-54517b80388d)

Something similar to how Godot does it.
![Screenshot 2024-02-20 at 15 03 55](https://github.com/bevyengine/bevy/assets/104745335/4e856934-f026-4308-a30a-f6d1d2a5e963)

**Comment by mockersf** [comment]
added links to the release: https://github.com/bevyengine/bevy/releases/tag/v0.13.0

**Comment by ameknite** [comment]
fixed
