### ISSUE TITLE
Improve docs for ReceivedCharacter

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#12040]
## How can Bevy's documentation be improved?

Since #10702, [`ReceivedCharacter`] now contains [`SmolStr`], which is a bit confusing. Is it a character or multiple characters?

The [winit docs] for the underlying winit event that populates this have some info about why it is not a `char` and what else might be in there. (but surely this isn't a `str` just for stray deadkeys, right? we should look into what locales or settings or whatever would produce multiple `chars`.)

`ReceivedCharacter` is also not consistent cross-platform in other important ways. See https://github.com/rust-windowing/winit/issues/3381.

We might also want to point users to an alternative: [`KeyEvent::logical_key`] which is more consistent across platforms and is in a unified event stream with other keyboard events, which is important if you are developing a text input.

[winit docs]: https://docs.rs/winit/0.29.10/winit/event/struct.KeyEvent.html#structfield.text
[`SmolStr`]: https://docs.rs/smol_str/0.2.1/smol_str/struct.SmolStr.html
[`ReceivedCharacter`]: https://docs.rs/bevy/latest/bevy/prelude/struct.ReceivedCharacter.html
[`KeyEvent::logical_key`]: https://docs.rs/bevy/latest/bevy/input/keyboard/struct.KeyboardInput.html#structfield.logical_key

**Comment by james7132** [comment]
Closing as the type is to be deprecated and removed: #12639.
