### ISSUE TITLE
Add a feature to switch NativeActivity and GameActivity for winit in bevy_winit

### ISSUE THREAD

**Issue by Litttlefish** [bevyengine/bevy#12058]
## What problem does this solve or what need does it fill?

I saw #12026 so I forked one and edited bevy_winit to use `GameActivity`. After compile my game runs smoothly without changes to the code.

But `NativeActivity` is still useful, so I think bevy can add an option to switch that.

## What solution would you like?

Add an option to switch winit between `GameActivity` and `NativeActivity` on android.

These two are already implemented properly(?) on winit and android-activity, just need an extra feature to control them.

**Comment by Litttlefish** [comment]
Addendum:
I think bevy can remove default option and add two features to select between them, just like how `winit` and `android-activity` does.

**Comment by BD103** [comment]
I added a comment [here](https://discord.com/channels/691052431525675048/692572690833473578/1210657715274383371). Bevy is generally fine with breaking changes, I'm more concerned that a crate feature is not the right solution.

How is `GameActivity` / `NativeActivity` configured in `winit`?

**Comment by Litttlefish** [comment]
> I added a comment [here](https://discord.com/channels/691052431525675048/692572690833473578/1210657715274383371). Bevy is generally fine with breaking changes, I'm more concerned that a crate feature is not the right solution.
> 
> How is `GameActivity` / `NativeActivity` configured in `winit`?

By features, need to pick one when using, just like how android-activity crate does.
