### ISSUE TITLE
Can't get Rendering Assets to unload from RAM on wasm webgl2.0 build

### ISSUE THREAD

**Issue by egol** [bevyengine/bevy#12057]
## Bevy version
v0.13.0

## \[Optional\] Relevant system information
GPU: RTX 2080 Ti
Using Firefox 122 on Windows 10
```ignore
AdapterInfo { name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)", vendor: 4318, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
```
(Not sure why the adapter info shows GTX 980 for firefox but problem is persistent on chrome as well)

Using Chrome shows:
```ignore
 AdapterInfo { name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 Ti (0x00001E07) Direct3D11 vs_5_0 ps_5_0, D3D11)", vendor: 4318, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
```
## What you did

I am trying to get the new "[Unload Rendering Assets from RAM](https://bevyengine.org/news/bevy-0-13/#unload-rendering-assets-from-ram)" feature working. I have been successful on a `local cargo run --release` build but I have not been able to replicate the memory usage on a `wasm` `webgl` build. The attachment below shows the comparative ram usage of the local windows build and the `wasm` build. For some reason the `wasm` build never ends up offloading the memory and stays at the pictured amount.
For reference, I am loading 63 jpg images that are on average 2MB in size and have a resolution of 2587x3375 (obviously this could be optimized and I am currently perusing a workaround of drastically decreasing their resolution)

This is the code that sets my image assets to be offloaded:
```rust
fn check_asset_loading (
    mut next_state: ResMut<NextState<AppState>>,
    book_query: Query<&Book>,
    mut images: ResMut<Assets<Image>>,
    server: Res<AssetServer>,
    mut loading_progress: ResMut<LoadingProgress>
)
{
    let mut loaded = true;
    use bevy::asset::LoadState;
    for book in book_query.iter() {

        let mut num_loaded = 0;

        for handle in book.image_handles.iter() {
            let load_state = server.get_load_state(handle);

            if load_state.is_some() {
                if load_state.unwrap() != LoadState::Loaded {
                    loaded = false;
                }
                else {
                    num_loaded += 1;

                    if let Some(image) = images.get_mut(handle) {
                        image.asset_usage = RenderAssetUsages::RENDER_WORLD;
                    }
                }
            }
        }

        loading_progress.current = (100.0 / book.image_handles.len() as f32) * num_loaded as f32;

        if loaded && book.image_handles.len() == num_loaded {
            info!("all images loaded!");
            // window.single_mut().visible = true;
            next_state.set(AppState::Running);
        }
    }

}
```

this is my build pipeline for wasm:

```ignore
cargo build --profile wasm-release --target wasm32-unknown-unknown
wasm-bindgen --no-typescript --target web --out-dir ./out/ --out-name "mygame" ./target/wasm32-unknown-unknown/release/book1-0.wasm
```
relevant toml:
```ignore
[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
```

html used to run wasm:
```html
<!doctype html>
<html lang="en">

<body style="margin: 0px;">
  <script type="module">
    import init from './mygame.js'

    init().catch((error) => {
      if (!error.message.startsWith("Using exceptions for control flow, don't mind me. This isn't actually an error!")) {
        throw error;
      }
    });
  </script>

  <canvas id="mygame-canvas" width="1280" height="720"></canvas>
</body>

</html>
```

## What went wrong

Offloading to GPU memory works on a local windows build of my application but does not happen on a wasm build of the same application. 

## Additional information
Memory usage:
![image](https://github.com/bevyengine/bevy/assets/16660306/6d380de6-9bdf-44b9-881c-63fcc6577252)
Firefox performance graph:
![image](https://github.com/bevyengine/bevy/assets/16660306/364c4420-fcc4-4257-a7df-6841ae952487)

**Comment by egol** [comment]
After further testing on chrome it seems that this problem is actually isolated to Firefox and might be a browser related bug. I will close this issue as I no longer think it is bevy related.
this error also appears in the firefox console regularly:
```ignore
Uncaught Error: closure invoked recursively or after being dropped
    __wbindgen_throw http://localhost:3000/mygame.js:1126
    __wbg_adapter_52 http://localhost:3000/mygame.js:233
    real http://localhost:3000/mygame.js:210
    __wbg_addEventListener_2f891d22985fd3c8 http://localhost:3000/mygame.js:1207
    handleError http://localhost:3000/mygame.js:238
    __wbg_addEventListener_2f891d22985fd3c8 http://localhost:3000/mygame.js:1206
    __wbg_adapter_52 http://localhost:3000/mygame.js:233
    real http://localhost:3000/mygame.js:210
    __wbg_addEventListener_2f891d22985fd3c8 http://localhost:3000/mygame.js:1207
    handleError http://localhost:3000/mygame.js:238
....
```
Chrome having a reasonable amount of memory usage:
![image](https://github.com/bevyengine/bevy/assets/16660306/5375cd54-7fbe-4546-87b2-dafc70c33e1e)

**Comment by egol** [comment]
Chrome memory usage:
![image](https://github.com/bevyengine/bevy/assets/16660306/96b0aa5d-3aff-487c-a828-ae42c7afcfc5)

Apologies for randomly closing and reopening this issue as I was unsure of if this is a browser or bevy related bug.

**Comment by mockersf** [comment]
Fun fact I just learned: you can't free memory in WASM, once you allocated it you can't return it to the OS/browser 😄 

See https://webassembly.github.io/spec/core/syntax/instructions.html#memory-instructions, no instruction to deallocate. Read https://github.com/WebAssembly/design/issues/1397 for more details.

A workaround for your usage would be to load the images one by one, and unload them before loading the next one. that way you'll need only the memory for one image

**Comment by JMS55** [comment]
Not much we can really do to fix this, but I'd like to add a note to the documentation for 0.13.1.
