### ISSUE TITLE
bevy_color: migrate color conversion code from bevy_render

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#12068]
Currently, bevy_color uses color conversion functions contained in bevy_render. This means that bevy_color depends on bevy_render. This dependency should be the other way around - bevy_color should be a lower-level dependency of bevy_render.

To fix this, a number of modules will need to be moved:

* The `colorspace` module in bevy_render should be moved to `bevy_color`.
* The `From` impls that convert between the old legacy color type to the new color types should be moved to `bevy_render`.

**Comment by CptPotato** [comment]
Side question: With this change, is `bevy_render`'s dependency on `bevy_color` even needed, or could it simply use `wgpu::Color`?

**Comment by viridia** [comment]
An example where `bevy_render` uses color is `ClearColorConfig`. This needs to be a type which can easily be converted from a color via `.into()`.

Also, it looks like `wgpu::Color` uses f64, which seems like overkill for Bevy rendering pipelines.
