### ISSUE TITLE
Lighting of material weirdly angle dependent

### ISSUE THREAD

**Issue by Affinator** [bevyengine/bevy#12061]
## Bevy version

0.13

## Relevant system information

GPU: Radeon Vega 56
Kernel: 6.7.4
Mesa: 23.3.5
Rust: Stable 
AdapterInfo: { name: "AMD Radeon RX Vega (RADV VEGA10)", vendor: 4098, device: 26751, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 23.3.5-manjaro1.1", backend: Vulkan }

## What you did

I am procedurally generating a terrain. The vertex attributes (especially the vertex normals) seem to/should be correct (checked by using gizmos and bevy_mod_picking to get the normal of relevant positions; please ignore the visible normal averaging error between terrain clusters). 

I am using a custom normal map texture that is just a homogenous (0,0,1) or neutral normal map inside a StandardMaterial. So this is just a grass albedo texture with a neutral normal map.

## What went wrong

While the DirectionalLight moves around the terrain in a circle, I expect the darker parts of the terrain to also move in a circle. But currently the terrain is only darkening when the light shines from a specific quadrant.

It seems really weird that light seems to only work correctly from 25% of all possible angles.

I included a video to make it easier to understand.

## Additional information
[Screencast_20240223_145235.webm](https://github.com/bevyengine/bevy/assets/6897458/d63cf380-89c2-436e-a655-c0c8ed24c2df)

**Comment by hymm** [comment]
Looks like your normals are wrong. I think they should be (0,1,0) since bevy is y up

**Comment by Affinator** [comment]
I mean a neutral normal map like 
![th(5).jpg](https://github.com/bevyengine/bevy/assets/6897458/b60dabed-1115-4601-8071-77b03e9bc924), which should be correct?

The vertex normals are correct. I debugged them to hell that they are perpendicular to the ground.

But you are correct. The terrain is in the X-Y-plane (just out of curiosity to try it this way), but that should not effect rendering as long as the normals are perpendicular to the surface?

**Comment by hymm** [comment]
What is the default orientation of your plane?

**Comment by DGriffin91** [comment]
If the normals get loaded as sRGB there can be issues like this.

**Comment by Affinator** [comment]
YES! Setting the TextureFormat to Rgba8Unorm fixed it.

This is a real footgun that should be warned about...
