### ISSUE TITLE
Font rendering is blurry

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#12064]
## Bevy version

0.13

## \[Optional\] Relevant system information

Scale factor: 1.0
OS: ArchLinux.

## What you did

Updated from 0.12 to 0.13.

## What went wrong

Text sometimes looks blurry.

## Additional information

0.12:
![image](https://github.com/bevyengine/bevy/assets/22453358/992bf514-704d-4d96-a4d2-c51da6d4c832)

0.13:
![image](https://github.com/bevyengine/bevy/assets/22453358/4544b0c2-87b9-4855-bd42-f621b34b6eb6)

Minimal example to reproduce the issue: [bevy_ui_blurry.zip](https://github.com/bevyengine/bevy/files/14387376/bevy_ui_blurry.zip)
You can try to switch versions from 0.12 and 0.13 without changing any code and compare the results, should be as shown above.

**Comment by rparrett** [comment]
Bisected to #11326

**Comment by franklinblanco** [comment]
Reporting the same issue here.

**Comment by brandon-reinhart** [comment]
![blurry_growth](https://github.com/bevyengine/bevy/assets/106117615/9dc0199a-adcd-49a1-97b4-d417105cd47f)
![notblurry](https://github.com/bevyengine/bevy/assets/106117615/c90d9f23-78f3-4b82-bbb3-c528b52e9f73)
Seems to depend on the string length.

**Comment by leonidv** [comment]
Same issue
![image](https://github.com/bevyengine/bevy/assets/355630/42a415b7-8d7e-474c-895f-39d2f530b41f)
