### ISSUE TITLE
GLTF rendering is no longer predictable after 0.13

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#12066]
## Bevy version

0.13

## \[Optional\] Relevant system information

OS: ArchLinux
CPU: 32 × AMD Ryzen 9 5950X 16-Core Processor

## What you did

I rendering to texture in order to have preview for models in my game.

In 0.12 I discovered a bug #10688 that has been fixed in #10745.

## What went wrong

But after update to 0.13 it looks like it has been reintroduced. I have the same problem, sometimes it renders the asset, sometimes not.

## Additional information

Here is the minimal example to reproduce: [assets_render.zip](https://github.com/bevyengine/bevy/files/14389120/assets_render.zip).
If you disable `multi-threaded` feature, it will work as expected.

With the following changes the code compiles on 0.12 and works as expected with `multi-threaded` feature on:
```diff
diff --git a/Cargo.toml b/Cargo.toml
index 0d88782..6955489 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -4,7 +4,7 @@ version = "0.1.0"
 edition = "2021"
 
 [dependencies]
-bevy = { version = "0.13", default-features = false, features = [
+bevy = { version = "0.12", default-features = false, features = [
   "bevy_gltf",
   "bevy_ui",
   "bevy_sprite",
diff --git a/src/main.rs b/src/main.rs
index 190bc1c..7b5cd2f 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -12,7 +12,7 @@ fn main() {
     App::new()
         .insert_resource(AmbientLight {
             color: Color::WHITE,
-            brightness: 1000.0,
+            brightness: 1.0,
         })
         .add_plugins((
             DefaultPlugins.set(LogPlugin {
diff --git a/src/preview.rs b/src/preview.rs
index 7718258..3b55e72 100644
--- a/src/preview.rs
+++ b/src/preview.rs
@@ -14,7 +14,7 @@ pub(super) struct PreviewPlugin;
 
 impl Plugin for PreviewPlugin {
     fn build(&self, app: &mut App) {
-        app.init_state::<PreviewState>()
+        app.add_state::<PreviewState>()
             .add_systems(Startup, Self::spawn_camera_system)
             .add_systems(OnEnter(PreviewState::Inactive), Self::deactivation_system)
             .add_systems(
@@ -143,6 +143,7 @@ const PREVIEW_RENDER_LAYER: RenderLayers = RenderLayers::layer(1);
 #[derive(Bundle)]
 struct PreviewCameraBundle {
     name: Name,
+    ui_camera_config: UiCameraConfig,
     preview_camera: PreviewCamera,
     render_layer: RenderLayers,
     camera_bundle: Camera3dBundle,
@@ -153,6 +154,7 @@ impl Default for PreviewCameraBundle {
     fn default() -> Self {
         Self {
             name: "Preview camera".into(),
+            ui_camera_config: UiCameraConfig { show_ui: false },
             preview_camera: PreviewCamera,
             render_layer: PREVIEW_RENDER_LAYER,
             camera_bundle: Camera3dBundle {
```

**Comment by BD103** [comment]
I was unable to reproduce this on my machine, using the zipfile linked.

```shell
2024-02-23T19:33:07.795597Z  INFO log: Adapter Metal AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }    
2024-02-23T19:33:07.796343Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-02-23T19:33:08.136412Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-02-23T19:33:08.165192Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 14.2.1 ", kernel: "23.2.0", cpu: "Apple M1", core_count: "8", memory: "16.0 GiB" }
```

How many times did you have to run the program in order to see the incorrect behavior? All of the images rendered correctly for me.

**Comment by BD103** [comment]
Odd, there must be some architectural differences that makes the bug more common on your system. Let's wait for someone else to weigh in and test it...

**Comment by mockersf** [comment]
This is due to asynchronous pipeline compilation, which is disabled on macOS or without feature `multi-threaded`

What's happening is:
* gltf is loaded
* you try to display it
* displaying it trigger the pipeline compilation
* if the pipeline is compiled fast enough, or was compiled for a previously loaded asset, the gltf will be displayed. otherwise, nothing happens

This is most of the times not a problem because Bevy keeps trying to render things every frame, but in your case you're only rendering it once

**Comment by rparrett** [comment]
(async pipeline compilation can be disabled with [this setting on `RenderPlugin`](https://docs.rs/bevy/latest/bevy/render/struct.RenderPlugin.html#structfield.synchronous_pipeline_compilation).

**Comment by Shatur** [comment]
Thank you a lot, disabling async pipeline compilation fixed the issue.

**Comment by Shatur** [comment]
> Or you can try to make sure all pipelines are compiled before advancing from a loading state.

How can I do so?

**Comment by rparrett** [comment]
> How can I do so?

It's a bit of a pain. You need to create a "loading scene" that has every permutation of material properties or whatever so that all pipelines are created.

And then in the render app, check that status of all pipelines in `PipelineCache`.

There are advantages though -- on the web, pipeline compilation hangs the app and causes audio weirdness.

This tiny plugin can help a bit: <https://github.com/rparrett/bevy_pipelines_ready>.

See also: https://github.com/bevyengine/bevy/issues/10871

**Comment by Shatur** [comment]
Thanks!

**Comment by cart** [comment]
I think an important missing feature is a reasonable way to detect when everything in a scene is "fully ready to render".
