### ISSUE TITLE
Check `cfg` to catch feature typos

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy#12091]
Nightly Rust has added support for `-Zcheck-cfg`, which will show a warning if there is a `#[cfg(...)` for a nonexistant feature / cfg.

While not possible to add this to CI because it is currently nightly-only, it can be run locally to catch all current typos.

Please read [this comment](https://github.com/rust-lang/rfcs/pull/3013#issuecomment-1936648479) on how to use `-Zcheck-cfg`. Once you follow the setup, run:

```shell
cargo +nightly check -Zcheck-cfg --workspace
```

I found a few warnings related to missing features, but I currently don't have the time to work on it today.

**Comment by alice-i-cecile** [comment]
We can actually add this to CI: we run some checks on nightly already :)

**Comment by eerii** [comment]
I'm working on removing the warnings and adding the check to the CI. I'll make a pr in a bit once it is ready!
