### ISSUE TITLE
States are no longer showing in bevy-inspector-egui due to state no longer reflecting resource

### ISSUE THREAD

**Issue by LIMachi** [bevyengine/bevy#12129]
Bevy 0.13

Note before reading the issue: Reflection are still obscure to me and I might have misunderstood the reason my use case no longer works.

I upgraded my project from Bevy 0.12 to bevy 0.13, and I extensively use the crate bevy inspector egui to check my project.
One of the things I do is to register the states I use in the reflection system via this kind of code: ```app.init_state::<S>.register_type::<State<S>>.register_type::<NextState<S>>;``` and this used to make me able to check the current state and manually triggering a state transition via bevy inspector egui.

In bevy 0.13, due to this commit: https://github.com/bevyengine/bevy/commit/ba0f8f996f04ea7d2d25e3004cf0cb3ac7c9015b (file: crates/bevy_ecs/src/schedule/state.rs, line: 77), `State<S>` no longer reflects Resource or Debug, breaking this behavior.

Would it be possible to make `State<S>` reflect resource even without deriving Default?

**Comment by alice-i-cecile** [comment]
That should be a simple fix: are you comfortable trying your hand at a PR?

**Comment by LIMachi** [comment]
Well, quick was maybe an overstatement, I need to implement reflect resource manually (since state is no longer required to be default, and default implied from world)... So I'm not sure I will be able to finish this PR today :P

**Comment by alice-i-cecile** [comment]
Ah hmm 🤔 I'll ask in #reflection-dev about this on Discord.

**Comment by alice-i-cecile** [comment]
Unfortunately the fix requires a breaking change: bumping to the 0.14 milestone.
