### ISSUE TITLE
Fetching assets is broken in web workers

### ISSUE THREAD

**Issue by allsey87** [bevyengine/bevy#12125]
## Bevy version
0.13

## Relevant system information
WebAssembly/Web Worker

## What you did
Ran Bevy in a Web Worker with an OffscreenCanvas and routed events over postMessage.

## What went wrong
Everything was working nicely until I had to fetch a GLTF asset and I kept getting a panic. Turns out that `HttpWasmAssetReader::fetch_bytes` from `bevy_asset` assumes at [wasm.rs#41](https://github.com/bevyengine/bevy/blob/release-0.13.0/crates/bevy_asset/src/io/wasm.rs#L41) that it is running in a window and not in a worker.

Note that gloo-net used to have a similar issue but resolved the issue by probing the global object to see whether it was a `web_sys::Window` or a `web_sys::WorkerGlobalScope` in [request.rs#323](https://github.com/rustwasm/gloo/blob/0.9.0/crates/net/src/http/request.rs#L323-L338).

## Additional information
This issue could be resolved by either adding a dependency on gloo-net or duplicating its logic into bevy_asset. For the latter approach, it might also be an idea to then add an option field to the `HttpWasmAssetReader` that contains the probed global object type once it has been "resolved".

**Comment by mockersf** [comment]
Would you have an example project that you could share with this setup?
