### ISSUE TITLE
Add method in BoundingVolume trait to scale the volume relative to its center

### ISSUE THREAD

**Issue by unknownue** [bevyengine/bevy#12130]
## What problem does this solve or what need does it fill?

The `BoundingVolume` trait has `grow` and `shrink` method to change its size. In some case, it would be more convenient to introduce `scale` method to do this.

**Edit: The term "scale" refers to scale the size of bounding volume for given amount and keeps its center unchanged.**

## What solution would you like?

Add `scale` method to `BoundingVolume` trait and add implementation for `Aabb2d`, `Aabb3d`, `BoundingCircle`, `BoundingSphere`.

## What alternative(s) have you considered?

Do not change `BoundingVolume` trait but add `scale` method to each volume instead.

**Comment by chompaa** [comment]
Hi, could I work on this as my first issue?

**Comment by unknownue** [comment]
> Hi, could I work on this as my first issue?

Yes

**Comment by Jondolf** [comment]
This actually isn't that trivial in terms of what the scaling should do. It's not the same as `grow` and `shrink`, as the common use cases are quite different. See my comment here: https://github.com/bevyengine/bevy/pull/12142#issuecomment-1966098088

**Comment by unknownue** [comment]
I further clarify the problem in issue title and description. @Jondolf

**Comment by unknownue** [comment]
Fixed by https://github.com/bevyengine/bevy/pull/12142
