### ISSUE TITLE
Support triggering the winit render loop from an external source

### ISSUE THREAD

**Issue by R081n** [bevyengine/bevy#12159]
## What problem does this solve or what need does it fill?

We want to use Bevy to display data that is streamed from an external source. Additionally we want to save resources by using `WinitSettings::desktop_app()`. To do this we need a way to tell bevy to run the render loop from an external source.

## What solution would you like?

In version 0.12 it was possible to trigger the event loop, using the winit `EventLoopProxy` which is added as a `Resource` in the winit runner. Sending a  `UserEvent<()>` then triggered the event loop once. This seemed to be unintentional.

In version 0.13 the `UserEvent` no longer triggers the event loop.

A possible solution would be to explicitly handle the `UserEvent` in the winit runner by simply running an update or allow the default winit runner to be parameterized by a custom handler. I did not find a reason why the `EventLoopProxy` is currently added as a `Resource`.

Additionally the  `EventLoopProxy` should be reexported.

**Comment by alice-i-cecile** [comment]
I'd welcome a PR for this :) I don't think it's likely to be prioritized otherwise: this is relatively complex code in a niche use case.

**Comment by james7132** [comment]
@R081n is there anything remaining after #12197?

**Comment by R081n** [comment]
> @R081n is there anything remaining after #12197?

Not really, a way for the EventLoopProxy to carry data would be interesting, though i don't think it is really worth it when a channel can do it already. 👍
