### ISSUE TITLE
Run `cargo-machete` in CI

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy#12180]
## What problem does this solve or what need does it fill?

Sometimes a crate dependency becomes unused as the crate evolves. This is hard to spot manually because you have to check over the imports of every single `.rs` file. Removing unused dependencies is important because it can decrease compile times, which are prevalent to a large project such as Bevy.

## What solution would you like?

Run [`cargo-machete`] and remove all unused dependencies. (Make sure to verify that the affected crates still compile! There can be false positives!)

Then, either in the same PR or a follow-up one, add `cargo-machete` to [`ci`] so it can be checked for every pull request using Github Actions. For now this check will not be required to merge a PR, since there is a chance of false positives. False positives can be added to `Cargo.toml`'s `[package.metadata.cargo-machete]` section to ignore them.

[`cargo-machete`]: https://lib.rs/crates/cargo-machete
[`ci`]: https://github.com/bevyengine/bevy/tree/557e582ec55f325256011ee6e39e97a3d44b2fc3/tools/ci

## What alternative(s) have you considered?

I can't really think of any good alternatives.

## Additional context

I found a few false positives when first trying it out, such as:

- `ron` in `example_showcase`
- `thiserror` in `bevy_time`
- `rustc-hash` in `bevy_ecs`
- And more

**Comment by lewiszlw** [comment]
Can it be done by enabling rustc lint https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unused-crate-dependencies ?

**Comment by mockersf** [comment]
not a fan of cargo machete as it has false positive. it's been already talked about, see https://github.com/bevyengine/bevy/pull/7734.

For me this means that it's more in the controversial zone than "good first issue"

**Comment by BD103** [comment]
> Can it be done by enabling rustc lint https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unused-crate-dependencies ?

That would be interesting to test adding as a workspace lint and seeing how many false positives are raised.

> not a fan of cargo machete as it has false positive. it's been already talked about, see #7734.
> 
> For me this means that it's more in the controversial zone than "good first issue"
> 
> We're already checking for unused dependencies with `cargo-udeps` https://github.com/bevyengine/bevy/blob/main/.github/workflows/validation-jobs.yml#L265-L288

Ok, that all makes sense. I was not aware that `cargo-udeps` was in the build system. I'm going to close this as not planned, but it may be worth experimenting with `#![deny(unused_crate_dependencies)]`.
