### ISSUE TITLE
Add hue rotation traits

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12200]
Nit for future PR: We should add hue rotation traits to make this cleaner.

_Originally posted by @bushrat011899 in https://github.com/bevyengine/bevy/pull/12163#discussion_r1506997793_
            
            
Much like the `Alpha` trait, we should provide easy ways to "rotate" the hue of colors: shifting them by a provided number of degrees to rotate the metaphorical color wheel.

This trait should only be implemented for the color models (types) with an explicit hue element: other color types should be converted to one of those spaces first.

Once basic hue rotation is added, we can add nice color theory options: things like "complementary colors" (rotate by 180 degrees), "triadic colors" (rotate by 120 degrees), analogous colors and so on.

**Comment by oyasumi731** [comment]
If nobody is working on it, I'll give it a try.

**Comment by alice-i-cecile** [comment]
That would be lovely :) Feel free to open a draft PR and ping me if you run into difficulties.

**Comment by viridia** [comment]
We should be able to do #12632 and #12631 in the same PR.
