### ISSUE TITLE
Don't abort CI checks on first error

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12206]
## What problem does this solve or what need does it fill?

When working on complex PRs like #12163, it's frustrating to fix all of the errors reported by CI, only to be met with another round of failures in a follow-up crate.

## What solution would you like?

Pass the `--keep-going` flag to CI. See https://github.com/rust-lang/cargo/issues/10496 for the tracking issue. Apparently this is now stable as of Rust 1.74: https://doc.rust-lang.org/cargo/commands/cargo-build.html#option-cargo-build---keep-going

It looks like for `cargo test`, we also need to pass in `--no-fail-fast`: https://doc.rust-lang.org/cargo/commands/cargo-test.html#options

## What alternative(s) have you considered?

Always run CI repeatedly locally.

**Comment by mockersf** [comment]
The goal of CI is to fail fast in a case of errors, and to not do extra works when possible.

Changing that would need more changes than just passing `--keep-going` everywhere: reducing dependency between jobs, not cancelling everything on the first job failed

**Comment by alice-i-cecile** [comment]
That makes a lot of sense: I didn't think about dependent workflows. As a reviewer, I would still prefer it if all errors were caught, but enabling this option locally will be tremendously useful as an author.
