### ISSUE TITLE
Add `size` and `physical_size` to `Window`

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#12229]
## What problem does this solve or what need does it fill?

Users shouldn't need to manually construct vector types when they want to work with window sizes.

An example of some common code:

https://github.com/bevyengine/bevy/blob/499c978176435efaaf8ccfe3a1141efadfd340eb/examples/stress_tests/bevymark.rs#L512

## What solution would you like?

Provide

```rust
fn size() -> Vec2 {}
fn physical_size() -> UVec2 {}
```

## What alternative(s) have you considered?

Doing nothing is always an option, it is not terribly difficult to do this yourself.

## Discussion

Should these also be added to `WindowResolution`?

**Comment by chompaa** [comment]
I'd like to work on this :)
