### ISSUE TITLE
`axes_2d` gizmo

### ISSUE THREAD

**Issue by Jondolf** [bevyengine/bevy#12222]
## What problem does this solve or what need does it fill?

A follow-up item from #12211 by @mweatherley:

> Implement something similar for 2d. Honestly, I have no idea if this is desired/useful, but I could probably just implement it in this PR if that's the case.

#12211 added a gizmo for rendering the XYZ axes relative to a `Transform` (or `impl TransformPoint`). This is useful for 3D, but it'd also be useful to be able to draw just the XY axes in 2D. The 3D gizmo wouldn't look quite correct in 2D, and most other gizmo methods already have 2D variants.

## What solution would you like?

Add an `axes_2d` method that renders the XY axes.

## What alternative(s) have you considered?

Leave it up to the user, or use `axes` in 2D as well. It'd just look weird in 2D, because the arrows are 3D, and the Z arrow would probably look like a cross in the middle.

**Comment by lambertsbennett** [comment]
I would be interested in working on this if it's still an open issue?

**Comment by Jondolf** [comment]
> I would be interested in working on this if it's still an open issue?

Yep, it's open. Feel free to submit a PR if you're interested :)

**Comment by lambertsbennett** [comment]
Cool! I'll get to work then.
