### ISSUE TITLE
After 0.13 upgrade sometimes mouse clicks are completely missed

### ISSUE THREAD

**Issue by wilk10** [bevyengine/bevy#12227]
## Bevy version

0.13.0

## \[Optional\] Relevant system information

`SystemInfo { os: "Windows 11 Pro", kernel: "22631", cpu: "Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz", core_count: "8", memory: "31.9 GiB" }`

## What you did

I have upgraded my game to Bevy 0.13 and tested systems that were working fine in 0.12 and below. Unfortunately I have not been able to find a minimum reproducible example.

## What went wrong

Sometimes the game enters a state where mouse clicks are completely missed. Entering this state happens 50% or so of the time, once it's in that state, mouse clicks are completely missed until either a keyboad input is registered or the `GameState` changes.

Two flows that seem to reproduce it are:
- click on UI (works)
- enter a new `GameState` (placing new items on the map)
- click on the map (works)
- exit that `GameState` and back to previous one
- clicks on the map 100% of the time don't work any more (but on the UI are still fine)

The other:
- click on the UI (works)
- enter a different `GameState` than in the flow above
- 50% of the time clicks on the map consistently don't work any more, 50% of the time they keep on being fine.
- In this state without clicks, my game is stuck because of its logic. It can be unstuck via keyboard input (Enter or Backspace instead of Left / Right mouse click) but that's super inconvenient for the player.
- once unstuck via keyboard input, there's again a 50% chance that mouse clicks won't work again.

## Additional information

I'm using `Leafwing Input Manager` so it's one more layer where the bug could be.

I am trying to find a minimum reproducible example, but I haven't managed yet.

Clicks on the UI are unaffected.

The fact that is 50% or so of the time could be a system order issue, but the my game's logic hasn't changed from 0.12. I haven't touched systems ordering either. Can anything in Bevy have forced a different sorting of systems maybe when building the schedule graph? Just speculation though.

Possibly related issues: 
https://github.com/bevyengine/bevy/issues/12007: this is a 0.13 regression where there's a "ghost" UI node, maybe that's capturing clicks in some way? I have run into it with the upgrade, but in a different scenario.
~~https://github.com/bevyengine/bevy/issues/12150: this refers to keyboard inputs being sometimes missed.~~

(Sorry for not providing more specific info and mostly just speculation.)

Edit: 12150 seems unrelated.

**Comment by rlidwka** [comment]
> I have upgraded my game to Bevy 0.13 and tested systems that were working fine in 0.12 and below.

Is this issue present in 0.12.1?
