### ISSUE TITLE
`Oklcha` `with_` methods are inconsistent with other color spaces

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#12224]
## Bevy version

main

## What you did

Try to swap some code using `Hsla` to `Oklcha`.

## What went wrong

Expected `with_hue` calls to continue working, because `Oklcha` also has hue.

But for this color space, they are `with_h`, `with_l`, and `with_c`.

## Additional information

I think that `Oklcha` is the odd one out and that all other spaces use full names, but we should check them all and make them consistent.

Also, maybe this is intentional. I don't know much about `Oklch`. Are the `lch` strictly "lightless" "chroma" and "hue"?.

`Oklaba` also has "short `with_` methods" but if you expanded them, I assume they would end up like `lightness`, `a`, `b`.

**Comment by alice-i-cecile** [comment]
Yeah, we should expand these all out. `Oklaba`'s extended form is `lightness` + 'a' + 'b' as you say.
