### ISSUE TITLE
[0.13] split-screen example extended: Fail to render more than two cameras

### ISSUE THREAD

**Issue by BenedictWilkins** [bevyengine/bevy#12245]
bevy 0.13
Ubuntu 22.04
cargo 1.76.0 (c84b36747 2024-01-18)

AdapterInfo { name: "Intel(R) Graphics (RPL-P)", vendor: 32902, device: 42912, device_type: IntegratedGpu, driver: "Intel open-source Mesa driver", driver_info: "Mesa 23.2.1-1ubuntu3.1~22.04.2", backend: Vulkan }

## What you did

I was working with the bevy split-screen example: https://bevyengine.org/examples/3D%20Rendering/split-screen/ to try to render using a grid of cameras.

## What went wrong

I extended the example, but found that only two cameras were ever rendering (no matter how many I wanted to use).
The cameras that are rendered seem to only be the first two in the order. Any more than this and they will not be rendered.

If I change the rendering order of Right and Extra they will rendered differently, see below.

![Screenshot from 2024-03-01 22-53-12](https://github.com/bevyengine/bevy/assets/22711383/a97d05a5-0b3a-4e3c-bd1a-5ad8008ad2a9)

![Screenshot from 2024-03-01 22-55-19](https://github.com/bevyengine/bevy/assets/22711383/1add3710-41f2-431b-8395-718314a603f1)

Another thing to note is that occasionally all of the cameras will render properly in the first frame (whether this always happens or not I don't know, it might just be too fast to see sometimes).
It doesn't seem to matter whether the clear color is set, I have tried many combinations of orders/clear color with the same result.

Here is a MRE: [camera_grid_MRE.zip](https://github.com/bevyengine/bevy/files/14466771/camera_grid_MRE.zip)
it is just the linked example with an added camera and the fox asset removed (camera_leftright_extra.rs). With another file that extends the example to create a grid a cameras (camera_grid_minimal.rs)

**Comment by rparrett** [comment]
This is the same as #12006 which was fixed by #11968 and is slated for 0.13.1.
