### ISSUE TITLE
`Plane` is confusingly named: it should be renamed and an endless plane mesh primitive added

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12243]
## What problem does this solve or what need does it fill?

A [`Plane`](https://docs.rs/bevy/0.13.0/bevy/prelude/shape/struct.Plane.html) in Bevy is currently just a simple quad. This is surprising to new users, who don't understand why it's so small.

In mathematical terms, planes continue on endlessly.

## What solution would you like?

1. Rename `Plane` to something less confusing, like `Quad` or `FlatSurface`.
2. Add a true infinite plane.
3. Use the infinite plane in our examples.

## What alternative(s) have you considered?

Adding more doc comments could help, but beginners already don't think to check them and wonder why there's a `size` field.

## Additional context

Using very large single polygons for a ground plane causes weirdness and performance issues for both rendering and physics. Simply increasing the size of `Plane` to a very large number is a bad habit to teach. In most cases, you really do want a truly infinite, much simpler ground plane (or a modelled terrain surface).

**Comment by alice-i-cecile** [comment]
As @TrialDragon points out, this type is now called `Plane3d`: here's a usage in the wild.

The `Plane3d` type *correctly* represents planes as infinite, but the matching generated mesh doesn't correspond to the geometrical interpretation. To fix this, we'd want:

1. Another, better suited primitive for a simple flat surface, which can be used to generate the existing mesh.
2. A replacement for the `Meshable` implementation on `Plane2d` and `Plane3d` that generates an infinite plane.

**Comment by rparrett** [comment]
> 2. A replacement for the `Meshable` implementation on Plane2d and Plane3d that generates an infinite plane.

I guess this would have to take the form of a theoretical `InfinitePlaneBundle` combined with an `InfinitePlaneMaterial`.

Even if we had that, and we had a separate `FinitePlane3d` (not an actual name proposal), I think that users would still want to occasionally build a mesh for a `Plane3d`. And because it's a `Mesh`, it can't really be infinite.

So I am not sure if that is actually helping out with the confusion factor a great deal.

**Comment by alice-i-cecile** [comment]
Yeah, that's pretty valid 🤔 I think that using these in our examples would help avoid this footgun however.

**Comment by viridia** [comment]
In three.js, `Plane` is a mathematical object representing an infinite plane. `PlaneGeometry` is a mesh object representing a rectangular flat object.

* https://threejs.org/docs/index.html#api/en/math/Plane
* https://threejs.org/docs/index.html#api/en/geometries/PlaneGeometry

**Comment by Elabajaba** [comment]
> The Plane3d type correctly represents planes as infinite

It certainly isn't correct for a game engine (or any 3d software), where planes are bounded and optionally subdivided quads (and have never been infinite). The existing Plane3d is confusing for anyone who's ever used another game engine or 3d modeling software.

**Comment by viridia** [comment]
An infinite plane is very useful for certain kinds of geometric calculations, for example clipping operations on solid geometry. Such objects are typically defined by a normal vector + a distance from the origin, and have various methods to determine how far a point is from the plane, whether a line intersects the plane, and so on.

**Comment by DispairingGoose** [comment]
I think it comes to whether there is a need for mesh builders in general. For many mathematically représentable meshes such as spheres and planes their mesh() method returns a mesh builder such as PlaneMeshBuilder which I think is part of the confusion around this class.

I would suggest this changes to a PlaneMesh, which has a Plane3D field, and Vec2 half_size field, essentially identical to the current API, just presented in a different way that makes it more understandable, same for all other primitive meshes with a mathematical representation such as spheres. If this is the way forward, I am happy to do the PR for this.

**Comment by alice-i-cecile** [comment]
https://dev-docs.bevyengine.org/bevy/math/prelude/struct.InfinitePlane3d.html

This is now resolved.
