### ISSUE TITLE
`web-sys` doesn't need to be pinned any more

### ISSUE THREAD

**Issue by xStrom** [bevyengine/bevy#12246]
The `bevy_render` package has a [strict pin on `web-sys`](https://github.com/bevyengine/bevy/blob/cc32610543ff97794c3ee8ff7dd5ef58547a3ac5/crates/bevy_render/Cargo.toml#L110-L112):
```toml
# web-sys doesn't follow semver for the WebGPU APIs as they are unstable
# Make sure that WebGPU builds work when changing this!
web-sys = { version = "=0.3.67", features = [
```

This is because `wgpu` depends on unstable `web-sys` features which don't follow SemVer.

However things have changed, [`wgpu` has now vendored those bindings](https://github.com/gfx-rs/wgpu/pull/5325). This was also [backported and released as v0.19.3](https://github.com/gfx-rs/wgpu/pull/5327).

This means that pinning `web-sys` is no longer required. The following can be done:
* Update the `wgpu` requirement in `bevy_render` from `0.19.1` to `0.19.3`.
* Remove the `web-sys` pin.

Doing so will unlock the ability for unrelated projects that have `bevy_render` in their workspace to finally update their `web-sys`.

Also, an additional benefit of the aforementioned `wgpu` change is that `wgpu` no longer requires you to have `--cfg=web_sys_unstable_apis` in your `RUSTFLAGS`.

**Comment by alice-i-cecile** [comment]
Sounds good, can you make a PR to change this?
