### ISSUE TITLE
UI element positioning bug updating TargetCamera on cursor transition between Viewports in multi-camera setup

### ISSUE THREAD

**Issue by StrikeForceZero** [bevyengine/bevy#12255]
## Bevy version

0.13

## What you did

From [trying to upgrade bevy_mod_picking to support bevy 0.13](https://github.com/aevyrie/bevy_mod_picking/pull/314#issuecomment-1974034094) I noticed some odd behavior when using multiple active cameras and updating the `TargetCamera` for some text that follows the cursor.

clean room example: https://github.com/StrikeForceZero/bevy-cleanroom/blob/example/multi_camera_target_camera_update/src/main.rs

## What went wrong

- what were you expecting? 

The text to continue follow the cursor after changing TargetCamera when entering a new viewport

- what actually happened? 

The text gets stuck at an arbitrary location and stops updating until moving back into the other viewport

## Additional information

The workaround I have proposed in that PR for now is just maintaining a UI node for each camera and toggling their visibility when the cursor enters or leaves the viewport.

[See this comment for observation details](https://github.com/aevyrie/bevy_mod_picking/pull/314#issuecomment-1974034094)

Here is a video show casing the cleanroom example. 2 cameras split vertically.

https://github.com/bevyengine/bevy/assets/983413/6e7e5978-0a36-49fd-85b8-6822d14a20d7

**Comment by StrikeForceZero** [comment]
Poking at the engine source it might be related to somewhere near here https://github.com/bevyengine/bevy/blob/dedf66f72bd8659b744e12b341a7f8de4ed8ba17/crates/bevy_ui/src/layout/mod.rs#L420-L420

Logging `absolute_location` I can see it update normally as I move the mouse cursor around. Once I back to the side that it breaks for the value stops updating until I move back to the other viewport.

**Comment by StrikeForceZero** [comment]
This partially fixes it, but at the cost of incrementing the taffy ids each time the `TargetCamera` is updated.

```diff
Index: crates/bevy_ui/src/layout/mod.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/crates/bevy_ui/src/layout/mod.rs b/crates/bevy_ui/src/layout/mod.rs
--- a/crates/bevy_ui/src/layout/mod.rs	(revision HEAD)
+++ b/crates/bevy_ui/src/layout/mod.rs	(revision Staged)
@@ -370,8 +370,13 @@
     ui_surface.remove_entities(removed_nodes.read());
 
     // update camera children
-    for (camera_id, CameraLayoutInfo { root_nodes, .. }) in &camera_layout_info {
-        ui_surface.set_camera_children(*camera_id, root_nodes.iter().cloned());
+    for (camera_id, _) in cameras.iter() {
+        let root_nodes = if let Some(CameraLayoutInfo { root_nodes, .. }) = camera_layout_info.get(&camera_id) {
+            root_nodes.iter().cloned()
+        } else {
+            [].iter().cloned()
+        };
+        ui_surface.set_camera_children(camera_id, root_nodes);
     }
 
     // update and remove children
```

**Comment by StrikeForceZero** [comment]
Ok, I think this fixes it without extraneously incrementing the taffy ids. Not sure if there's any consequences to having the camera taffy nodes living on root of the tree along with the UI nodes, but for my clean room example it works. I'm gonna try to figure out how to run the tests and if they pass I'll make a PR.

```diff
Index: crates/bevy_ui/src/layout/mod.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/crates/bevy_ui/src/layout/mod.rs b/crates/bevy_ui/src/layout/mod.rs
--- a/crates/bevy_ui/src/layout/mod.rs	(revision HEAD)
+++ b/crates/bevy_ui/src/layout/mod.rs	(revision Staged)
@@ -167,6 +167,7 @@
             ..default()
         };
 
+        let camera_node = *self.entity_to_taffy.entry(camera_id).or_insert(self.taffy.new_leaf(viewport_style.clone()).unwrap());
         let existing_roots = self.camera_roots.entry(camera_id).or_default();
         let mut new_roots = Vec::new();
         for entity in children {
@@ -181,24 +182,16 @@
                         self.taffy.remove_child(previous_parent, node).unwrap();
                     }
 
+                    self.taffy.add_child(camera_node, node).unwrap();
+
                     RootNodePair {
-                        implicit_viewport_node: self
-                            .taffy
-                            .new_with_children(viewport_style.clone(), &[node])
-                            .unwrap(),
+                        implicit_viewport_node: camera_node,
                         user_root_node: node,
                     }
                 });
             new_roots.push(root_node);
         }
 
-        // Cleanup the implicit root nodes of any user root nodes that have been removed
-        for old_root in existing_roots {
-            if !new_roots.contains(old_root) {
-                self.taffy.remove(old_root.implicit_viewport_node).unwrap();
-            }
-        }
-
         self.camera_roots.insert(camera_id, new_roots);
     }
 
@@ -370,8 +363,13 @@
     ui_surface.remove_entities(removed_nodes.read());
 
     // update camera children
-    for (camera_id, CameraLayoutInfo { root_nodes, .. }) in &camera_layout_info {
-        ui_surface.set_camera_children(*camera_id, root_nodes.iter().cloned());
+    for (camera_id, _) in cameras.iter() {
+        let root_nodes = if let Some(CameraLayoutInfo { root_nodes, .. }) = camera_layout_info.get(&camera_id) {
+            root_nodes.iter().cloned()
+        } else {
+            [].iter().cloned()
+        };
+        ui_surface.set_camera_children(camera_id, root_nodes);
     }
 
     // update and remove children
```

**Comment by alice-i-cecile** [comment]
Please ping me on the PR: I'm keen to get this fixed.

**Comment by nicoburns** [comment]
> Ok, I think this fixes it without extraneously incrementing the taffy ids.

@StrikeForceZero Hmm... this seems to be creating one "implicit viewport node" per camera (viewport) rather than one for each direct child of the camera (viewport). I think this will break the case when there are multiple ui trees as children of a camera which are currently laid out independently (but I think the proposed patch will cause them to be laid out in a grid).

**Comment by StrikeForceZero** [comment]
Negative test here: https://github.com/bevyengine/bevy/pull/12268/commits/76426f6772a33c46b718b95f8d9651fdffde3413

> Please ping me on the PR: I'm keen to get this fixed.

@alice-i-cecile I've created a draft PR https://github.com/bevyengine/bevy/pull/12268 . It does fail a couple of tests that expect only UI nodes to exist in the `UiSurface.entity_to_taffy` hash. Gonna circle back after dinner.

> > Ok, I think this fixes it without extraneously incrementing the taffy ids.
> 
> @StrikeForceZero Hmm... this seems to be creating one "implicit viewport node" per camera (viewport) rather than one for each direct child of the camera (viewport). I think this will break the case when there are multiple ui trees as children of a camera which are currently laid out independently (but I think the proposed patch will cause them to be laid out in a grid).

I was concerned that stuffing those nodes in the root of taffy might have consequences. What is the ideal way to test this?

**Comment by StrikeForceZero** [comment]
> > Ok, I think this fixes it without extraneously incrementing the taffy ids.
> 
> @StrikeForceZero Hmm... this seems to be creating one "implicit viewport node" per camera (viewport) rather than one for each direct child of the camera (viewport). I think this will break the case when there are multiple ui trees as children of a camera which are currently laid out independently (but I think the proposed patch will cause them to be laid out in a grid).

Unless I'm not understanding, it appears to have no visible effect on the root child nodes. 

Below is an example of two text nodes height and width set to 100%, taking up the entire viewport.

![image](https://github.com/bevyengine/bevy/assets/983413/27500bb2-7925-4f33-8e96-4b8a0f90932b)

```rust
    commands.spawn((
            TextBundle {
                text: Text::from_section("hello world static", TextStyle { ..default() }),
                style: Style {
                    width: Val::Percent(100.),
                    height: Val::Percent(100.),
                    ..default()
                },
                background_color: Color::srgb(1., 0., 0.).into(),
                ..default()
            },
            TargetCamera(left_camera_entity),
        ));

    commands.spawn((
        TextBundle {
            text: Text::from_section("hello world static", TextStyle { ..default() }),
            style: Style {
                width: Val::Percent(100.),
                height: Val::Percent(100.),
                ..default()
            },
            background_color: Color::srgb(0., 0., 1.).into(),
            ..default()
        },
        TargetCamera(right_camera_entity),
    ));
```
    
and here's one with children on one side
    
    
![image](https://github.com/bevyengine/bevy/assets/983413/36c91742-4576-4402-9c98-5f7f5d03cce1)


```rust
    commands.spawn((
            TextBundle {
                text: Text::from_section("hello world static", TextStyle { ..default() }),
                style: Style {
                    display: Display::Flex,
                    width: Val::Percent(100.),
                    height: Val::Percent(100.),
                    ..default()
                },
                background_color: Color::srgb(1., 0., 0.).into(),
                ..default()
            },
            TargetCamera(left_camera_entity),
        ));

    commands.spawn((
        NodeBundle {
            style: Style {
                display: Display::Flex,
                flex_direction: FlexDirection::Column,
                width: Val::Percent(100.),
                height: Val::Percent(100.),
                ..default()
            },
            background_color: Color::srgb(0.5, 0.5, 0.5).into(),
            ..default()
        },
        TargetCamera(right_camera_entity),
    )).with_children(|children| {
        children.spawn((
            TextBundle {
                text: Text::from_section("b", TextStyle { ..default() }),
                style: Style {
                    display: Display::Flex,
                    height: Val::Percent(50.),
                    ..default()
                },
                background_color: Color::srgb(0., 0., 1.).into(),
                ..default()
            },
        ));
        children.spawn((
            TextBundle {
                text: Text::from_section("a", TextStyle { ..default() }),
                style: Style {
                    display: Display::Flex,
                    height: Val::Percent(50.),
                    ..default()
                },
                background_color: Color::srgb(0., 1., 0.).into(),
                ..default()
            },
        ));
    });
```

**Comment by StrikeForceZero** [comment]
@alice-i-cecile  PR is no longer in draft and ready for review.

**Comment by nicoburns** [comment]
Hmm... prior to the target camera changes it was possible to spawn multiple NodeBundle's at the root level of the viewport. I had thought this was still possible, but if you have to put the TargetCamera entity on the ui root node then I guess not. I had assumed that TargetCamera would get set on the *parent* of each ui root
