### ISSUE TITLE
Mobile Web keyboard does not open when clicking input

### ISSUE THREAD

**Issue by v-kat** [bevyengine/bevy#12262]
## Bevy version
0.13

## What you did
Try to touch a text input on a mobile web bevy game. No mobile keyboard appears. (Might still be an issue with IME and/or bevy_egui)

## Description
This seems to happen across all the mobile web platforms I tested (chrome, firefox, and brave on android). I was talking with someone on the bevy discord who mentioned that this was a bevy engine issue. I wasn't sure if it was a bevy_egui issue. Egui has a working mobile web keyboard and I believe https://github.com/emilk/egui/blob/master/crates/eframe/src/web/text_agent.rs is how it triggers the keyboard to open on mobile web.

LMK if you want a code example or more info

**Comment by mockersf** [comment]
Bevy doesn't have text inputs, so it's likely not a Bevy issue

**Comment by v-kat** [comment]
It might be something with IME but I'll look into bevy_egui more.
