### ISSUE TITLE
The OrthographicProjection has it's default values overriden in Camera2dBundle's default implementation, causing counter-intuitive problems

### ISSUE THREAD

**Issue by Gaspard--** [bevyengine/bevy#12267]
Hello!

I don't know if this should be a feature request or a bug. 

Since this is about unexpected behavior, I feel like a bug fits better.

## Bevy version

0.13

## What you did

Warning in advance: still a beginner at rust, so I might be using an anti-pattern somewhere.

I was messing around with different values to initialize the `Camera2dBundle` with, and noticed my rendering seems to disappear sometimes.
After looking at the source code, I found these lines:
https://github.com/bevyengine/bevy/blob/04ec10552c30615378205222a80aaca5ff82a4dc/crates/bevy_core_pipeline/src/core_2d/camera_2d.rs#L37-L42

This means, that when initializing the camera on your side using a camera 2d bundle, if you want a scale, you must be careful to also specify znear / zfar.
```rust
        Camera2dBundle{
            projection: OrthographicProjection {
                scaling_mode: ScalingMode::FixedVertical(2.0),
                // not specfying these 2 fields can break rendering
                far: 1000.0,
                near: -1000.0,
                ..OrthographicProjection::default()
            },
            ..default()
        }
```

## What went wrong

When not specifying znear / zfar, all sprites and text stop appearing.

I think it would be better if the defaults of `OrthographicProjection` work out of the box, but I don't know the internals of bevy enough to know if this is reasonnable. A warning in the docs would also may be a solution.

## Additional information

I saw https://github.com/bevyengine/bevy/issues/239, but I don't think it's related since any scale value breaks the rendering.

**Comment by the-az-dev** [comment]
I wrote about this in previous issue so, I will paste link to this comment [https://github.com/bevyengine/bevy/issues/239#issuecomment-2211712442](url)

**Comment by Azorlogh** [comment]
I think this can be closed this too :slightly_smiling_face:  https://github.com/bevyengine/bevy/pull/15073
@alice-i-cecile
