### ISSUE TITLE
Add conversion support for nalgebra

### ISSUE THREAD

**Issue by darthdeus** [bevyengine/bevy#1227]
**What problem does this solve or what need does it fill?**

Using bevy together with https://github.com/dimforge/nalgebra, e.g. because using Rapier (https://rapier.rs/) via https://github.com/dimforge/bevy_rapier/, means one has to constantly convert between bevy's [`Vec2`](https://docs.rs/bevy/0.4.0/bevy/math/struct.Vec2.html) and nalgebra's [`Point`](https://www.nalgebra.org/rustdoc/nalgebra/geometry/struct.Point.html).

**What solution would you like?**

Implement [`From`](https://doc.rust-lang.org/std/convert/trait.From.html) for `Vec2/3` hidden behind a feature flag so that bevy users that use `nalgebra` can simply enable the feature flag and use `.into()` in their code.

**What alternative(s) have you considered?**

Implementing conversion traits inside `bevy_rapier`.

**Comment by DJMcNab** [comment]
We can't add these impls, they would have to be either added in `nalgebra` or `glam` (or `std`, but that doesn't count) due to the orphan rules. `nalgebra` being more complicated, I'd be inclined to think that nalgebra should be the ones adding these impls.

**Comment by darthdeus** [comment]
Oh I didn't realize they weren't actually defined in `bevy` but came from `glam`, thanks for pointing that out! I guess no point in keeping this issue open.
