### ISSUE TITLE
Inconsistent Behavior: 'with_scale_factor_override' Method Fails to Adjust Window Size as Expected

### ISSUE THREAD

**Issue by Shadowcat650** [bevyengine/bevy#12282]
## Bevy version

0.13.0

**Description:**
The bug affects the window scaling functionality in Bevy version 0.13.0 when setting a scale factor override for the window resolution. 

**Reproduction Steps:**
1. Attempt to create a window with a specific resolution and scale factor using Bevy.
2. Set the scale factor using the `with_scale_factor_override` builder method.
3. Run the application and observe the window size.

```rust
fn main() {
    App::new()
        .add_plugins(
            DefaultPlugins
                .set(ImagePlugin::default_nearest())
                .set(WindowPlugin {
                    primary_window: Some(Window {
                        title: String::from("My Game"),
                        resolution: WindowResolution::new(200., 200.)
                            .with_scale_factor_override(8.),
                        ..default()
                    }),
                    ..default()
                })
        )
        .run();
}
```

**Expected Behavior:**
The window should display with a size adjusted according to the specified scale factor.

**Actual Behavior:**
The window retains its original size, disregarding the scale factor override.

**Additional Information:**
- The `set_scale_factor_override` method sets the scale factor override correctly.
```rust
fn main() {
    let mut resolution = WindowResolution::new(200., 200.);
    resolution.set_scale_factor_override(Some(8.));

    App::new()
        .add_plugins(
            DefaultPlugins
                .set(ImagePlugin::default_nearest())
                .set(WindowPlugin {
                    primary_window: Some(Window {
                        title: String::from("My Game"),
                        resolution,
                        ..default()
                    }),
                    ..default()
                })
        )
        .run();
}
```

**Resolution:**
The 'with_scale_factor_override' method should use 'self.set()' to set the physical pixels with the scaled resolution like the 'set_scale_factor_override' method does.

**Comment by LuisFigueiredo73** [comment]
I would like to try to fix this bug if possible!
