### ISSUE TITLE
Clean up type registrations

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#12304]
First party Bevy crates have accumulated a large number of type registrations as each type needed to be individually registered for it to work with scenes and reflection. With #4154 merged, we no longer need to manually register every type, just the top level ones that users are expecting to be registered (i.e. components and resources), as any any type dependencies will automatically be registered.

**Comment by alice-i-cecile** [comment]
Do you think we should register whole `Bundle` types? That would certainly be a simple way to get most of these.

**Comment by MrGVSV** [comment]
> Do you think we should register whole `Bundle` types? That would certainly be a simple way to get most of these.

This would require deriving `Reflect` on the bundles. That's something I'm definitely not opposed to (I had to hack around that limitation a couple times before), but it might also be something we want to consider in terms of compile times and binary size.
