### ISSUE TITLE
Error in PBR shader code when VERTEX_NORMALS is not defined

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#12326]
## Bevy version

0.13

## What you did

I have an ExtendedMaterial which calls `pbr_input_from_standard_material`. This produces a WGSL compilation error unless VERTEX_NORMALS is defined. The actual error is here:

https://github.com/bevyengine/bevy/blob/ba9d1eff41a5f0150bff43315fe0c46896049ce9/crates/bevy_pbr/src/render/pbr_fragment.wgsl#L44

This code should be surrounded with an `#ifdef VERTEX_NORMALS`.

## What went wrong

The shader produces an error message when compiling:

```
error: invalid field accessor `world_normal`
   ┌─ /Users/talin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_pbr-0.13.0/src/render/pbr_fragment.wgsl:45:12
   │
45 │         in.world_normal,
   │            ^^^^^^^^^^^^ invalid accessor
   │
   = invalid field accessor `world_normal`
```

**Comment by viridia** [comment]
BTW, rounded corners look particularly nice in segmented buttons, and are easy to do:

<img width="169" alt="segmented" src="https://github.com/bevyengine/bevy/assets/1166135/4294a76f-f11e-4dc2-88b0-acc42f5879a1">

**Comment by viridia** [comment]
Apparently this happened because I was using extended materials incorrectly.

**Comment by Inspirateur** [comment]
i'm using extended material and have the same issue lol :( would be nice to know what you did wrong if you still remember
