### ISSUE TITLE
`lighting` example emissive values need to be adjusted

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#12330]
## Bevy version

0.13 / main / after #11868

## What you did

`cargo run --example lighting`

## What went wrong

The sphere and capsules representing the red and green lights are dark and sad. They used to be bright.

The sphere representing the blue light doesn't seem to be visible in the scene at all, but it also has an emissive value that probably needs adjusting.

It seems like values in the ballpark of 100x the old values might work.

**Comment by andristarr** [comment]
Sadly I dont know its original value, but a 10x value seems okayish for me, what do you think? The 100x value seems to just burn out the whole render.

**Comment by rparrett** [comment]
I would check out the `v0.12.1` tag, run the example, and compare the output.

**Comment by andristarr** [comment]
V0.13 <img width="950" alt="image" src="https://github.com/bevyengine/bevy/assets/25829992/283077a1-08ea-40de-8e69-043e67e491c0">
V0.12 
<img width="951" alt="image" src="https://github.com/bevyengine/bevy/assets/25829992/a2fa4f81-849b-4aa4-a938-e9a552e575c1">

They actually seem kinda alike unless I am missing something

**Comment by rparrett** [comment]
This issue is referring specifically to the `emissive` property of the material for the meshes representing lights in the scene.

<img width="950" alt="310600855-283077a1-08ea-40de-8e69-043e67e491c0" src="https://github.com/bevyengine/bevy/assets/200550/0a275bb9-dd35-4ceb-9f50-c06151f85ac9">

**Comment by andristarr** [comment]
Sorry, absolutely missed that, now they are happy again! :)

<img width="617" alt="image" src="https://github.com/bevyengine/bevy/assets/25829992/75f5e353-bad3-4ab9-9b61-7e84d9f0d998">

**Comment by BD103** [comment]
I did change these values in #11982, but they were just estimates and not calculated.

**Comment by andristarr** [comment]
I think your changes there were for the lights like @rparrett mentioned.

This is for the emissive on the bodies acting like the lights

**Comment by rparrett** [comment]
Right. This is addressing something that was missed in #11982.
