### ISSUE TITLE
webp asset_server load error

### ISSUE THREAD

**Issue by v-kat** [bevyengine/bevy#12353]
## Bevy version

0.13.0

## \[Optional\] Relevant system information
WASM Linux Chromium web build with trunk

## What you did

Tried to use a webp image with `asset_server.load` and `.insert_resource(AssetMetaCheck::Never)` had the `webp` feature enabled in cargo along with `bevy_asset`

## What went wrong

The image doesn't load and there's a stacktrace

## Additional information

```
ERROR /home/name/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.13.0/src/server/mod.rs:302 Could not find an asset loader matching: Loader Name: None; Asset Type: None; Extension: None; Path: Some("char.webp");
```

**Comment by rparrett** [comment]
As a workaround, you can enable the `bmp` or `png` features as well.

**Comment by v-kat** [comment]
Thanks. Confirmed that using the `png` feature also fixes the problem.
