### ISSUE TITLE
`bevymark` hangs indefinitely when spawning many unique materials

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#12380]
## Bevy version

main, bisected to #11986

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 14.2.1 ", kernel: "23.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

`cargo run --release --example bevymark -- --benchmark --waves 130 --per-wave 1000 --mode mesh2d --vary-per-instance`

## What went wrong

On my machine, `--waves 120` takes about 4 seconds to the first birds showing up. With `--waves 130`, the app hangs indefinitely. I got bored waiting after 5+ minutes.

This "hanging threshold" was much higher prior to #11986.

|bevy|birds|hang?|
|-|-|-|
| main pre #11986 (51edf9c)| --waves 120 | OK |
| main pre #11986 (51edf9c)| --waves 130 | HANG |
| main post #11986 (5d941d5)| --waves 240 | OK |
| main post #11986 (5d941d5)| --waves 250 | HANG |

## Additional information

Discovered while bisecting #11946 which seems to be a separate issue that has been totally fixed on wgpu's end.

**Comment by mockersf** [comment]
regression needs to be investigated, but a general fix could be tracked in https://github.com/bevyengine/bevy/issues/12263
