### ISSUE TITLE
[bevy_ui][focus] distinguish mouse buttons

### ISSUE THREAD

**Issue by RostMyr** [bevyengine/bevy#1239]
**What problem does this solve or what need does it fill?**
`ui_focus_system` system currently handles only left button clicks/touches. It would be nice to be able to handle right button clicks too.

**What solution would you like?**
Well, probably `Interaction::Clicked` could be just replaced with `Interaction::Clicked(MouseButton)` or with `Interaction::Clicked(Option<MouseButton>)` to handle touches with `Option::None` 🤷🏻 .

**Comment by alice-i-cecile** [comment]
This is now complete due to `bevy_picking`'s creation and integration with `bevy_ui`.
