### ISSUE TITLE
Implement `QueryData` for `&Archetype`

### ISSUE THREAD

**Issue by urben1680** [bevyengine/bevy#12393]
## Description of the feature request

`&Archetype` is a reference that can be accessed with `EntityRef` and `EntityMut` in a query. These latter two however hurt parallization when queried. If one does that only to get `&Archetype`, that restriction is needless as the archetype reference alone does not require further access to the component data.
It would make sense to offer this type as a `QueryData` that can also be freely added to a query with `Query::transmute_lense`.
Also, since the number of archetypes a query accesses is most likely much smaller than the number of matched entites, one could consider giving `Query` a new method that returns an Iterator over `&Archetype`s.

## What problem does this solve or what need does it fill?

I have no personal use case, I just noticed that when looking through the docs to answer someone's question, what else than components can be queried. If someone can come up with an actual use case, please share it in this issue.

**Comment by alice-i-cecile** [comment]
I've seen this type of pattern used for efficient networking-based serialization and deserialization of entities.
