### ISSUE TITLE
Communicating wgpu/gfx issues upstream

### ISSUE THREAD

**Issue by kvark** [bevyengine/bevy#124]
We should establish a good workflow for communicating issues like this to us for investigation. The best way we can suggest is following https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure
Practically, that would mean:
  1. have a way to run with "trace" feature enabled in `wgpu`. There is no performance cost, but there may be a compile time cost, and I know you are sensitive to that too.
  2. have a path to the trace folder configurable by some means
  3. once you reproduce the problem, zip the trace folder, and attach it to a bug to https://github.com/gfx-rs/wgpu
  4. don't forget to specify the revision of `wgpu` used (e.g. from your lockfile) as well as platform info

**Comment by cart** [comment]
This is a _very good_ idea. Thanks!

Its worth noting that right now we're using a custom (but unmodified) wgpu crate while we wait for the next official wgpu crates.io release.

**Comment by cart** [comment]
I just added support for this and added a quick doc on it: https://github.com/bevyengine/bevy/blob/master/docs/debugging.md#wgpu-tracing

We will link to that doc whenever suspected wgpu issues come up.

@karroffel  @GabLotus keep this in mind when you're triaging issues.

@kvark would you consider this closed?
