### ISSUE TITLE
Asset Meta Files should have an example

### ISSUE THREAD

**Issue by tbillington** [bevyengine/bevy#12411]
## How can Bevy's documentation be improved?

Asset Meta Files were introduced in [0.12](https://bevyengine.org/news/bevy-0-12/#asset-meta-files) but do not have an example in the repository.

This was inspired by a [discord help question](https://discord.com/channels/691052431525675048/1216248019310346280/1216248019310346280) asking simply how to change texture filtering for a specific asset. Without meta files the answer to this is not simple. The docs for [`AssetLoader`](https://docs.rs/bevy/latest/bevy/asset/trait.AssetLoader.html) and [`ImageLoader`](https://docs.rs/bevy/latest/bevy/render/texture/struct.ImageLoader.html) do not provide straightforward guidance for users looking to utilize meta files.

An example in the repo would help users use meta files for simple tasks like changing texture filtering. Texture filtering would make a good example case, in my opinion.

**Comment by MTFT-Games** [comment]
If no one has started working on this yet, I would love to take a crack at it if someone can assign me to it. 

I actually tried using meta files for using nearest neighbor filtering for some pixel art back in December by just trial and error. I got it to work but only by tinkering with it until the errors went away. I'm sure I could make an example from what I figured out there but if anyone knows of any other resources I'd love to take a look at those as well.
