### ISSUE TITLE
Add euclidean division and euclidean modulo to bevy_math.

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#12414]
## What problem does this solve or what need does it fill?

Euclidean division and modulo, also known as "floor division" are operations where the remainder is always positive, and the quotient is always rounded down, even if the dividend is a negative number. This is easier to do in floating point using `.floor()`, but the solution for integers is less obvious.

This calculation has many uses, such as quantizing values to a grid.

## What solution would you like?

For reference, the answer for euclidean division of integers looks like this:

```rust
fn euclidean_division(n: i32, d: i32) -> i32 {
    if n >= 0 {
        n / d
    } else {
        (n - d + 1) / d
    }
}
```
However, this should be implemented as a trait. There should be implementations for the various primitive number types.

**Comment by alice-i-cecile** [comment]
It's an incredibly useful operation when working with tile-based games. However, `glam` types and Rust's numeric types already have `div_euclid` and `rem_euclid` methods on them. IMO we should stick to that convention, and just add matching methods on the assorted bevy_math types where this makes sense.

**Comment by viridia** [comment]
Dang, I searched for "rust euclidean division" and could not find anything. I wouldn't have filed a ticket if I had known they already existed.
