### ISSUE TITLE
Add a command to clear inexistence children

### ISSUE THREAD

**Issue by Multirious** [bevyengine/bevy#12438]
## What problem does this solve or what need does it fill?

Sometimes while using Bevy, user may receive an entity with some children that do not exist.

## What solution would you like?

New command that remove the given entity's children that do not exist from `Children` component.

## What alternative(s) have you considered?

The work around is recreate a `Children` component and check for child that do not exists.

## Additional context

Started from this [Discord discussion](https://discord.com/channels/691052431525675048/691052431974465548/1217076273994797096).

**Comment by Multirious** [comment]
I already have the solution implemented in my fork. Let me know if this feature is worth implementing so I could have my first contribution!

**Comment by iiYese** [comment]
This will be solved by #12235

**Comment by Multirious** [comment]
Oh, alright then. Not today I guess.
