### ISSUE TITLE
font_atlas_debug example not displaying updated texture

### ISSUE THREAD

**Issue by tigregalis** [bevyengine/bevy#1243]
**Bevy version**

master

**Operating system & version**

Windows 10

**What you did**

`cargo run --example font_atlas_debug`

**What you expected to happen**

It should show the font atlas with all of the glyphs in the top left.

**What actually happened**
Other than a handful, most of the glyphs are missing.
![image](https://user-images.githubusercontent.com/38416468/104620330-d6f92700-56c9-11eb-83ed-62f9b7e288a9.png)

**Additional information**
I believe it is successfully displaying the first character ("a"), then the first character for the first font atlas, then the first character for the second font atlas (when the first gets filled up), and so on. For some reason, each individual atlas doesn't get updated on screen after the first character.

**Comment by rparrett** [comment]
Seems to have been broken during 7699f8b6db0af6ca62fcd033e05df4f6c71ecb23

**Comment by rparrett** [comment]
Related? #1161

**Comment by tigregalis** [comment]
> 
> 
> Related? #1161

That seems likely!
