### ISSUE TITLE
Check example showcase patches in CI

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#12441]
## What problem does this solve or what need does it fill?

When PRs are merged, the "[example-showcase patches](https://github.com/bevyengine/bevy/tree/main/tools/example-showcase)" can go stale and break tooling that relies on `example-showcase`.

For example, the automated screenshot diffing happening at <https://thebevyflock.github.io/bevy-example-runner/>. I also hit this recently in my own local screenshot diffing infrastructure.

Motivated by:

#12440
#11596
#11058

## What solution would you like?

Add CI that checks to make sure the patches apply.

## What alternative(s) have you considered?

Add CI-only rust code / APIs for doing the overrides that these patches are doing.

**Comment by BD103** [comment]
I'm thinking something like `git apply path/to/foo.patch`, and then checking if it exits with a non-zero code. This sounds quite easy to do in Github Actions.

Should this be included in the `ci` tool, or just Github Actions?
