### ISSUE TITLE
Bevy 0.13 dependency tree add's two oboe crates when using bevy_audio and crashes on android

### ISSUE THREAD

**Issue by dgsantana** [bevyengine/bevy#12452]
## Bevy version

Bevy 0.13

## \[Optional\] Relevant system information

When building for android with bevy 0.13 and with bevy_audio, 2 versions of oboe are pull due to cpal 0.5.3 pulling oboe 0.6.x.

## What you did

Trying starting a android bevy 0.13 app that uses audio.

## What went wrong

Crash due to pure function call.

## Additional information

The issue is easy to solve by forcing to use cpal 0.5.2

**Comment by mockersf** [comment]
this will be fixed in Bevy 0.13.1 with https://github.com/bevyengine/bevy/pull/12316
