### ISSUE TITLE
Clamp and Bounds for colors

### ISSUE THREAD

**Issue by solis-lumine-vorago** [bevyengine/bevy#12463]
## What problem does this solve or what need does it fill?

Colors should implement a `Clamp`-like trait with a function `clamp` which clamps the color channels into their allowed ranges and a `WithinBounds` trait with a method which checks whether each channel of the color is within its allowed range.
These methods could use the gamut, optimally obtained from `wgpu`.

## Additional context

Originally proposed [in this comment](https://github.com/bevyengine/bevy/pull/12460#discussion_r1523942720)

**Comment by Gingeh** [comment]
We do need to be careful about how (or whether) these traits are implemented for color spaces whose components can't be clamped/bounded individually.

Another concern is with how automatically detecting the display gamut would interact with bevy's existing hdr/tonemapping system.

**Comment by solis-lumine-vorago** [comment]
> Another concern is with how automatically detecting the display gamut would interact with bevy's existing hdr/tonemapping system.

If that is not possible, we could also let users supply their own gamut values which they could then obtain elsewhere.

**Comment by SolarLiner** [comment]
Clamping within a gamut should be a method of a gamut type, if we have one; a `clamp` method on colors should clamp to their defined spaces regardless of gamut.
