### ISSUE TITLE
Transform not applied if its mutated by system that queries for just the Transform

### ISSUE THREAD

**Issue by fenduru** [bevyengine/bevy#1246]
**Bevy version**

cf0e9f9968bb1bceb92a61cd773478675d35cbd6 (working in a cloned repo - no modifications)

**Operating system & version**

Windows 10

**What you did**

Wrote a system that queries a single `&mut Transform` component and modifies it.

```rs
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup.system())
        .add_system(animate.system())
        .run();
}

struct Marker;

fn setup(
    commands: &mut Commands,
    asset_server: Res<AssetServer>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    let texture_handle = asset_server.load("branding/icon.png");
    commands
        .spawn(Camera2dBundle::default())
        .spawn(SpriteBundle {
            material: materials.add(texture_handle.clone().into()),
            ..Default::default()
        }).with(Marker);
}

fn animate(time: Res<Time>, mut query: Query<&mut Transform>) {
    for mut t in query.iter_mut() {
        println!("This value updates, but the sprite doesn't visually move: {}", t.translation.x);
        t.translation.x += 10. * time.delta_seconds();
    }
}

// fn animate(time: Res<Time>, mut query: Query<(&Marker, &mut Transform)>) {
//     for mut t in query.iter_mut() {
//         println!("Same as above: {}", t.translation.x);
//         t.translation.x += 10. * time.delta_seconds();
//     }
// }

// fn animate(time: Res<Time>, mut query: Query<&mut Transform, With<Marker>>) {
//     for mut t in query.iter_mut() {
//         println!("This works: {}", t.translation.x);
//         t.translation.x += 10. * time.delta_seconds();
//     }
// }
```

**What you expected to happen**

Sprite to slide across the screen.

**What actually happened**

Sprite doesn't move, though the updated value can be read/printed on subsequent frames.

**Additional information**

Changing the query to include another component fixes it, as does adding a `With<OtherComponent>` query filter.

**Comment by mockersf** [comment]
If you don't filter your query, you're changing the transform of every entity that has one.

Here, you spawned two: the camera and the sprite. As you change both with the same translation, they stay the same relative to each other, so the sprite actually didn't move from the camera point of view.

**Comment by fenduru** [comment]
*facepalm*
