### ISSUE TITLE
Performance Lag when focusing and unfocusing in WASM Firefox

### ISSUE THREAD

**Issue by newclarityex** [bevyengine/bevy#12471]
## Bevy version

0.13

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:
- Windows 10
- Firefox

## What you did
I tested a simple bevy wasm build in Firefox and Chrome. 

## What went wrong
In Chrome everything ran smoothly.
In Firefox, it initially ran smoothly but became extremely laggy after unfocusing/refocusing the game.

**Comment by james7132** [comment]
This could be a duplicate of #12126.
