### ISSUE TITLE
`ButtonInput` docs should contain a usage example

### ISSUE THREAD

**Issue by Blainegith** [bevyengine/bevy#12470]
The input struct `ButtonInput`'s docs page aren't contains usage examples of the input enum `KeyCode`.

https://docs.rs/bevy/latest/bevy/input/prelude/struct.ButtonInput.html

**Comment by alice-i-cecile** [comment]
Seems reasonable: this seems like a nice simple doc test to add.

**Comment by Earthmark** [comment]
I'll take a crack at this!

**Comment by Earthmark** [comment]
I'm noticing in the head version of this code, there's a time complexity table that I do not think is correct.

The table lists `any_just_pressed`, `any_just_released`, and `any_pressed` are listed as *O*(m*n), but they're implemented as an **m** folds against an *O*(1)~ inner function. I think they're supposed to be *O*(m)~ instead.

Would it be alright if I try to update that table in the same PR?

**Comment by Earthmark** [comment]
I'll make a separate PR for that.

**Comment by alice-i-cecile** [comment]
Yeah, separate PR is preferred :)
