### ISSUE TITLE
Document the need to recompute AABBs on methods that could change mesh geometry

### ISSUE THREAD

**Issue by ua-kxie** [bevyengine/bevy#12475]
## Bevy version

0.13.0

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```ignore
`AdapterInfo { name: "Intel(R) UHD Graphics 630", vendor: 32902, device: 16018, device_type: IntegratedGpu, driver: "Intel Corporation", driver_info: "Intel driver", backend: Vulkan }`
```

## What you did

I created a simple mesh using `with_inserted_attribute`
```rust
let mesh = meshes.add(
    Mesh::new(
        PrimitiveTopology::LineList,
        RenderAssetUsages::RENDER_WORLD | RenderAssetUsages::MAIN_WORLD,
    )
    .with_inserted_attribute(
        Mesh::ATTRIBUTE_POSITION,
        vec![
            Vec3::from(origin),
            Vec3::from(origin),
        ],
    ),
);
```

which I later mutate using `insert_attribute`

```rust
wire.insert_attribute(
    Mesh::ATTRIBUTE_POSITION,
    vec![
        Vec3::from(origin),
        Vec3::from(cursor_position),
    ],
);
```

## What went wrong

The new mesh renders only if the origin point is in view/clip space. i.e. the entire line disappears as soon as one end of it goes out of view.

## Additional information

I tried adding NoFrustumCulling with no effect. It seems like the geometry is being culled with the original data it was created with.

**Comment by aarthificial** [comment]
Did you update the bounding box of your mesh after modifying the vertices?
From [the docs](https://docs.rs/bevy/latest/bevy/render/primitives/struct.Aabb.html):
> [The bounding box] won’t be updated automatically if the space occupied by the entity changes, for example if the vertex positions of a [Mesh](https://docs.rs/bevy/latest/bevy/render/mesh/struct.Mesh.html) inside a Handle<Mesh> are updated.

Sounds like that could be the problem since culling uses the bounding box. You can update it by inserting a new `Aabb` component to the entity with the handle:
```rs
if let Some(aabb) = wire.compute_aabb() {
  entity.insert(aabb);
}
```

**Comment by ua-kxie** [comment]
This fixed the issue.

Although, I think it would be helpful to have this mentioned under functions such as [insert_attribute](https://docs.rs/bevy/latest/bevy/render/mesh/struct.Mesh.html#method.insert_attribute)

**Comment by SolarLiner** [comment]
Agreed. It would be nice to rename the issue to something along the lines of "Document the need to recompute AABBs on methods that could change mesh geometry"

**Comment by mghildiy** [comment]
I can give it a try if no one else is working on it.

**Comment by SolarLiner** [comment]
If there are no open PRs (including drafts) for this then that means nobody called dibs, you can go ahead and do it yourself!

**Comment by ua-kxie** [comment]
I created a PR for this with updated docstrings in two functions (with_)insert_attribute. Are there others which should reference Aabbs?

**Comment by aarthificial** [comment]
@ua-kxie I believe `merge`, `transform(ed)_by`, `translate(d)_by`, `rotate(d)_by`, and `scale(d)_by` all modify the `Mesh::ATTRIBUTE_POSITION`

**Comment by ua-kxie** [comment]
Just realized there's the <Changed> query filter; was there a deliberate decision not to use it for updating AABB or is it something that needs to be done?
