### ISSUE TITLE
Support perspective projections with shear

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#12488]
## What problem does this solve or what need does it fill?

The ability to create a camera with a sheared projection matrix is important for a number of use cases:
* Multi-monitor rendering. Imagine a 3x3 display of monitors, each being rendered by a separate processor, but the 3d scene spans the entire array. Now say you want to render the top-left monitor: the camera position is still centered on the middle monitor, the view frustum for the top left monitor is "sheared".
* Efficient rendering of portals - generally a portal will only want to render a small portion of the window (the 2d bounding box of the portal) to the render target, rather than rendering the entire screen, which would be slow.

## What solution would you like?

The [setViewOffset()](https://threejs.org/docs/#api/en/cameras/PerspectiveCamera.setViewOffset) API in three.js is fairly simple. It accepts six parameters:

* fullWidth — full width of multiview setup
* fullHeight — full height of multiview setup
* x — horizontal offset of subcamera
* y — vertical offset of subcamera
* width — width of subcamera
* height — height of subcamera

All this does is adjust the perspective projection, and the corresponding view frustum, to render a rectangular subregion of the normal frustum. This is not the same as a clip rect, the subregion is "spread" over the entire viewport rect.

While it's possible that this feature already exists, I could not find it. I would expect that if it did exist, it would be a property of either Camera, Camera3DBundle, or ProjectionMatrix, but I could find nothing in those types relevant to this.

## What alternative(s) have you considered?

I can't think of a workaround for this, other than rendering to a very large render target and then cutting out a small piece of it, which would destroy performance.

**Comment by viridia** [comment]
My motivation for wanting this, BTW, is that I am currently working on portals. Here's a screenshot showing my work in progress:

<img width="195" alt="portal-quad" src="https://github.com/bevyengine/bevy/assets/1166135/f9deed5e-bc84-4d0c-955a-bd1acc48f06d">

The red rectangle gizmo shows the bounding box of the portal quad, which is the green gizmo. I already have in place code to render a secondary camera to an offscreen buffer; however, that secondary camera is rendering the entire screen, when ideally it should only render a tiny section of the screen. This will require modifying both the perspective transform and the frustum of the secondary camera.

For portals, specifically, there's an additional requirement that I didn't mention, which is that the near plane of the frustum needs to be adjusted to align with the portal aperture, so that objects that are in front of the portal (that is, between the secondary camera and the target viewpoint) do not get included in the view. In my old three.js code, I used a auxiliary clipping plane for this, but Bevy doesn't have that feature.

**Comment by inodentry** [comment]
I would like to add another use case that could benefit from this: screen shake in 3D.

If you want to shake the camera in 2D, you can just translate the camera along x/y, it's simple.

But in 3D, there are many different ways to accomplish screen shake, which look different, and it can be an artistic choice which way to implement the effect:
 - Translating the camera (usually along the plane of the screen in 3D space)
 - Rotating the camera (either by keeping a fixed "looking at" point, or via pitch/yaw)
 - Shifting the projection, which can look very nice, because it maintains the perspective and makes the effect feel more intuitive
 
 The third option, obviously, needs the game engine to support shifting the perspective projection.
