### ISSUE TITLE
Area of icosphere mesh triangles is inconsistent

### ISSUE THREAD

**Issue by EmiOnGit** [bevyengine/bevy#12480]
## Bevy version
0.13

## What you did
I've noticed that the mesh generated by `Sphere` is not containing equally sized triangles.
See below for the minimal required code.

`Sphere::default().mesh()` creates a `SphereMeshBuilder` with `SphereMeshBuilder::kind == SphereKind::Ico`.
As normally expected, the documentation for `SphereKind::Ico` states: 
> An icosphere, a spherical mesh that consists of equally sized triangles.

However, I couldn't validate this with following code:
```rust
use bevy::{prelude::*, render::mesh::PrimitiveTopology};

fn main() {
    let sphere_mesh_builder = Sphere::default().mesh();
    // Make sure we use a `Icosphere`
    match sphere_mesh_builder.kind {
        SphereKind::Ico { .. } => {}
        _ => panic!(),
    }

    let mesh = sphere_mesh_builder.build();

    // indices of vertices
    let indices: Vec<usize> = mesh.indices().unwrap().iter().collect();
    // Extract position of vertices
    let positions = mesh
        .attribute(Mesh::ATTRIBUTE_POSITION)
        .unwrap()
        .as_float3()
        .unwrap();
    // Vertices 0,1,2,3,4,5 create triangles 0,1,2 and 3,4,5 since we have a `TriangleList`.
    assert_eq!(mesh.primitive_topology(), PrimitiveTopology::TriangleList);
    let areas: Vec<f32> = indices
        .chunks_exact(3)
        // triangle is &[usize;3]
        .map(|triangle| {
            let a = Vec3::from_array(positions[triangle[0]]);
            let b = Vec3::from_array(positions[triangle[1]]);
            let c = Vec3::from_array(positions[triangle[2]]);
            // a,b,c are the three corner points of the triangle
            (a, b, c)
        })
        .map(|(a, b, c)| area_of_triangle(a, b, c))
        .collect();
    println!("max area {:?}", areas.clone().into_iter().reduce(f32::max));
    println!("min area {:?}", areas.clone().into_iter().reduce(f32::min));
    println!("first 10 {:?}", &areas[..10]);
}
fn area_of_triangle(a: Vec3, b: Vec3, c: Vec3) -> f32 {
    let ab = b - a;
    let ac = c - a;
    ab.cross(ac).length() / 2.
}
```
```bash
max area Some(0.0743312)
min area Some(0.06445146)
first 10 [0.06445148, 0.064451486, 0.064451486, 0.06595752, 0.06595752, 0.06595753, 0.06482972, 0.0724672, 0.06482972, 0.07246719]
```
The formula for calculating the area of the triangle can be found here for example: [1](https://math.stackexchange.com/questions/2587133/computing-an-area-of-a-triangle-in-3d?noredirect=1&lq=1) [2](https://math.stackexchange.com/questions/128991/how-to-calculate-the-area-of-a-3d-triangle)

**Comment by alice-i-cecile** [comment]
Can you attach a screenshot of the wireframe of one of these generated icospheres? That may give us a better sense of what's wrong.

**Comment by Adamkob12** [comment]
> Vertices 0,1,2,3,4,5 create triangles 0,1,2 and 3,4,5

Couldn't there be defined indices?
So the triangles wouldn't necessarily be defined in order like that.

**Comment by EmiOnGit** [comment]
> Couldn't there be defined indices?

Yeah you're right, I didn't know about that so my fault.
When using the right indices, the area does still fluctuate but only by around 10%.
Not sure but this might be in the expected deviation, right?
Wireframe also looks as expected. I've also updated the code above.

![image](https://github.com/bevyengine/bevy/assets/95967983/5bf55a18-edad-46dd-b81e-66f25e56cc23)

**Comment by EmiOnGit** [comment]
Update:
It seems the triangles of icospheres are not designed to be exactely the same size to begin with. Therefore a change of following documentation for the `Icosphere` would be helpful to prevent further mistakes
> An icosphere, a spherical mesh that consists of equally sized triangles.
