### ISSUE TITLE
Gltf texture not rendering properly

### ISSUE THREAD

**Issue by hchockarprasad** [bevyengine/bevy#12496]
## Bevy version

Bevy main.

```
AdapterInfo { name: "NVIDIA GeForce 3060", device_type: DiscreteGpu, }
```

## What you did

Tried to use a glb scene exported from unreal.

## What went wrong
 I tried to use it in bevy and the textures looks odd.  Have tried in scene-viewer as well.
 But in GLTF viewer & blender it works well.

## Additional information

In bevy:

<img width="500" alt="Screenshot 2024-03-15 220427" src="https://github.com/bevyengine/bevy/assets/22501803/ae84fea8-397c-4ad8-b416-53304b9a8560">

In GLTF viewer
<img width="851" alt="Screenshot 2024-03-15 221437" src="https://github.com/bevyengine/bevy/assets/22501803/a8f9c026-e136-4f4a-b617-732517909973">

[wall.glb.zip](https://github.com/bevyengine/bevy/files/14618811/wall.glb.zip)

**Comment by alice-i-cecile** [comment]
Can you upload the glb file as an attachment to this issue so we can reproduce and investigate? You may need to zip it first.

**Comment by hchockarprasad** [comment]
The link to file
https://github.com/hchockarprasad/trybv/blob/main/assets/wall.glb

**Comment by bugsweeper** [comment]
You can make better image (I mean colors) if you play with key L (which switches animation of light direction) in bevy scene viewer, because darkness of wall is light problem. Looks like problem relates to coordinates of texture
![image](https://github.com/bevyengine/bevy/assets/17225606/a90b9e81-1a1d-48e7-9868-858ac634f6cd)

**Comment by bugsweeper** [comment]
I ensured that no KHR_texture_transform extension in this file. Blender plugin doesnt see it also. gltf crate inside bevy reads TEX_COORS without modifications (it's equal to coresponding buffer data from exported bin-file after read). Looks like some corrections is missing. For this file exact quarter `.map(|[u, v]| [u / 2.0 + 0.5, v / 2.0])` works pretty well but is too strange and ugly.

**Comment by geckoxx** [comment]
The glTF Validator reports TEXCOORD_0 is not used. The materials in that file are using TEXCOORD_1 instead. But the gltf loader ignores that: https://github.com/bevyengine/bevy/blob/ade70b3925b27f76b669ac5fd9e2c31f824d7667/crates/bevy_gltf/src/loader.rs#L825

**Comment by bugsweeper** [comment]
Got such view with #13153 change
![image](https://github.com/bevyengine/bevy/assets/17225606/9d1a0935-5656-43e0-b82c-3656892f8536)
