### ISSUE TITLE
Add serialize feature to `bevy_color`

### ISSUE THREAD

**Issue by pablo-lua** [bevyengine/bevy#12527]
## What problem does this solve or what need does it fill?

Make serde optional for users. If they don't want, they not require it

## What solution would you like?

Create the feature `serialize` for `bevy_color` and remove serde::Serialize and Deserialize bound from trait `StandardColor` (or recreate if feature is enabled)

## What alternative(s) have you considered?

Leave it as it is

## Additional context

Notice that bevy_render depends on bevy_color, and as bevy_render doesn't flag serde by now, bevy_color can't too (unless of course we add the feature by default in bevy_render importing of bevy_color).

**Comment by alice-i-cecile** [comment]
We should add a serde flag for both crates, but there's no need to block. We can add it to bevy_color first, and just enable it during import initially.

**Comment by mghildiy** [comment]
I may give it a try. Please let me know.

**Comment by pablo-lua** [comment]
> I may give it a try. Please let me know.

Feel free to solve this :D

**Comment by mghildiy** [comment]
So to summarize my understaning:

- bevy_color is a crate for which I need to create a new feature 'serialize'
- remove serde::Serialize and Deserialize from StandardColor(a traint defined in bevy_color)
- then use this new feature 'serialize' for StandardColor if enabled by user

Actually I am java pogrammer by experience and have just started learning Rust, so want to ensure things are clear to me.
Please bear with me.

**Comment by alice-i-cecile** [comment]
Yep: you'll also want to make sure that the `serialize` feature flag in `bevy_color` is toggled on if the corresponding feature on `bevy` is enabled.

**Comment by pablo-lua** [comment]
You can, too, have a look on prior work with similar tasks if that help: #11188 
About the thing with StandardColor, that can be strange in design decision: We can't have type bounds being configurable by feature AFAIK, so you'll have to literally recreate the struct if feature is on
something like:

```rust
#[cfg(feature = "serialize")]
struct StandardColor 
where // . . .
{
 // . . .
}

#[cfg(not(feature = "serialize"))]
struct StandardColor 
where // . . .
{
// . . .
}
```
Thats probably the gist of it.

**Comment by alice-i-cecile** [comment]
I think we should just remove the Serialize + Deserialize bounds from `StandardColor`: I don't think the complexity is worth it for an internal helper.

**Comment by mghildiy** [comment]
[PR](https://github.com/bevyengine/bevy/pull/12666)

**Comment by mghildiy** [comment]
Build is failing due to some IO error. Is it down to code changes?
