### ISSUE TITLE
Website-Examples with shaders don't start 

### ISSUE THREAD

**Issue by mineichen** [bevyengine/bevy#12537]
Examples including shaders on https://bevyengine.org/examples don't work.  The text above the loading-bar freezes with "*.wgsl.meta". The console shows a HTTP-404 for that file. This occurs in both WebGL and WebGPU versions.

**Comment by rparrett** [comment]
The main issue is being tracked here: #11977. It has been fixed, and is slated for 0.13.1.

The loading bar is a separate issue being tracked here: #1119 which may also be fixed.

**Comment by james7132** [comment]
0.13.1 has landed, is this still an issue?

**Comment by rparrett** [comment]
Sort of. The new examples have not been successfully deployed yet.

But there's a `bevy-website` issue here: #1123 that we could use for that.
