### ISSUE TITLE
Improve error messages when check-example-showcase-patches-still-work CI job fails

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12539]
>I was slightly worried about contributor experience here. A failure currently looks like:
<img width="919" alt="image" src="https://github.com/bevyengine/bevy/assets/200550/2d38d5d4-b0cd-4149-aeb0-3c4ad25353b6">

> - CI doesn't tell you which patch failed, so that needs to be cross-referenced
> - CI stops after the first failure
> 
> But with this running on `merge_group`, I guess it's mostly maintainers having to deal with / at least explain this to contributors?
> 
> Still, would something like this be helpful? (or maybe just a `set -x`)
> 

```bash
CODE=0
for patch in tools/example-showcase/*.patch; do
  git apply --ignore-whitespace $patch || { echo "::error::$patch failed to apply."; CODE=1; }
done
exit $CODE
```

> (output using that code here: https://github.com/rparrett/bevy/actions/runs/8286681390/job/22677245376#step:7:14)

_Originally posted by @rparrett in https://github.com/bevyengine/bevy/issues/12457#issuecomment-1994619378_

**Comment by rparrett** [comment]
Someone picking this up might also want to address this comment while they're in there. https://github.com/bevyengine/bevy/pull/12457#discussion_r1527612715
