### ISSUE TITLE
Explain the usage of seeded RNG in examples

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12544]
> Probably raised this in the wrong PR, since this one is meant for debug, but examples like alien cake addict (in #12515) probably deserves more mention as to why we choose to set it up that way.

_Originally posted by @james7132 in https://github.com/bevyengine/bevy/pull/12519#pullrequestreview-1941585566_
            
Ultimately these are intended to make CI runs of our examples deterministic. We should call this out in the examples via a comment to aid learners.

**Comment by rparrett** [comment]
Some other related commentary: https://github.com/bevyengine/bevy/pull/12515#discussion_r1527184796
