### ISSUE TITLE
Reconsider removing `WorldCell`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12549]
Our internal uses of `World::cell` outside of tests is now at 0. It might be a good time to revisit this now that we have `UnsafeWorldCell` and `DeferredWorld`.

_Originally posted by @james7132 in https://github.com/bevyengine/bevy/issues/3939#issuecomment-2002646629_

**Comment by AxiomaticSemantics** [comment]
I took some time and removed `ArchetypeComponentAccess` out of world and disconnecting world_cell module from the tree and things seemed to test out and work fine after.

**Comment by james7132** [comment]
Note that `WorldCell` is the primary way to (safely) fetch multiple resources (as requested in #2942) right now. Either that needs to be resolved in another way or we should flesh out `WorldCell`'s APIs. The third option is to encourage use of `SystemState` as it's both safe, and retains a cache to make fetches faster in the future.

I'm in favor of the third option. Though it's a bit unwieldy to use right now, it offers the best option to provide safe and performant access at runtime, it logically scales well as users are already familiar with the system param DSL, it lets us maintain less code (by removing the need for WorldCell), and supports more than just resources (really any arbitrary SystemParam, including Queries).

**Comment by alice-i-cecile** [comment]
Agreed on the third option as the standard migration path. This is what I use in my own code (or sometimes resource_scope if the pattern supports it).

A fully fleshed out version built out of `UnsafeWorldCell` might be a nice third-party crate for users who find themselves running into these problems regularly and are okay with panics. That work should likely be based on https://github.com/bevyengine/rfcs/pull/42.
