### ISSUE TITLE
`LogPlugin` silently overwrites the panic hook in WASM

### ISSUE THREAD

**Issue by simbleau** [bevyengine/bevy#12546]
The `LogPlugin` silently overwrites the panic handler on WASM. This means if you attempt to set your own panic handler, or use something like <https://github.com/vectorgameexperts/web_panic_report>, you have to overwrite it on Startup (thus, your panic handler can't be added until Startup)

Problematic code:

https://github.com/bevyengine/bevy/blob/5d0ff60a6bbfa54b68287c2cadb14a7c0328afb6/crates/bevy_log/src/lib.rs#L206-L212

This should not be considered acceptable default behavior.

3 options here, open to discussion.
- (1) Provide a hook to the LogPlugin
- (2) Take it out (my preferred answer - Logging really has nothing to do with panicking.)
- (3) Consume the previous hook and wrap it, e.g.
  https://github.com/bevyengine/bevy/blob/5d0ff60a6bbfa54b68287c2cadb14a7c0328afb6/crates/bevy_log/src/lib.rs#L136-L140

**Comment by alice-i-cecile** [comment]
Why was this added in the first place? Can you check through the git history and link the PR?

**Comment by simbleau** [comment]
> Why was this added in the first place? Can you check through the git history and link the PR?

I believe it was added as a default to give WASM users the stack trace in their console, instead of the cryptic `Unreachable` error.

It's been untouched since the original [LogPlugin PR](https://github.com/bevyengine/bevy/pull/836), 4 years ago, by @cart 

<img width="766" alt="image" src="https://github.com/bevyengine/bevy/assets/48108917/f20f4e6c-281a-4250-8ad3-afa82adc8930">

I think the reason it has gone unnoticed for so long is probably that it's uncommon and fairly technical to implement your own WASM panic handler. @Vrixyz and I just made the [`web_panic_report`](https://github.com/vectorgameexperts/web_panic_report) crate yesterday and we found no similar crates.

I would love to hear @cart 's original intention with this - and whether we can remove it. Should this logic be a separate `PanicHandlerPlugin` in the `DefaultPlugins` instead?

**Comment by alice-i-cecile** [comment]
Thanks for the detective work! Splitting this out so it can be disabled or overwritten seems like a sensible direction to me. No strong feelings on the exact architecture though.

**Comment by james7132** [comment]
> I think the reason it has gone unnoticed for so long is probably that it's uncommon and fairly technical to implement your own WASM panic handler. Vrixyz and I just made the [web_panic_report](https://github.com/vectorgameexperts/web_panic_report) crate yesterday and we found no similar crates.

This is probably the case. According to `console_error_panic_handler`'s README, the alternative is an opaque error message that is borderline unusable to figure out what caused a panic.

**Comment by simbleau** [comment]
> Thanks for the detective work! Splitting this out so it can be disabled or overwritten seems like a sensible direction to me. No strong feelings on the exact architecture though.

Went ahead with the separate plugin strategy outlined above. PR #12557
