### ISSUE TITLE
Add milestone to bevy patch release

### ISSUE THREAD

**Issue by ameknite** [bevyengine/bevy#12565]
Similar to #12011 

linking to the milestone https://github.com/bevyengine/bevy/milestone/21?closed=1 might help to figure it out what has changed

**Comment by alice-i-cecile** [comment]
You should actually be able to get a diff between e.g. the 0.13 and 0.13.1 tags, which will be much more reliable.

**Comment by ameknite** [comment]
oh yeah, this link could also be added
https://github.com/bevyengine/bevy/compare/v0.13.0...v0.13.1

**Comment by james7132** [comment]
Done! https://github.com/bevyengine/bevy/releases/tag/v0.13.1
