### ISSUE TITLE
Panic at runtime when adding CorePlugin::default

### ISSUE THREAD

**Issue by TFCx** [bevyengine/bevy#1256]
**Bevy version**

0.4

**Operating system & version**

Windows 10

**What you did**

```
use bevy::{core::CorePlugin, prelude::*, };

fn main() {
    App::build()
        .add_plugin(CorePlugin::default())
        .run();
}
```

**What you expected to happen**

It compiles ok but it should also run (it's the first gist of bevy chess example (https://caballerocoll.com/blog/bevy-chess-tutorial/ ))

**What actually happened**

```
PS D:\Code\conflict_cay> cargo run
   Compiling conflict_cay v0.1.0 (D:\Code\conflict_cay)
    Finished dev [unoptimized + debuginfo] target(s) in 2.02s
     Running `target\debug\conflict_cay.exe`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\JD\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_reflect-0.4.0\src\impls\bevy_app.rs:52:74
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35\/library\core\src\panicking.rs:92
   2: core::panicking::panic
             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35\/library\core\src\panicking.rs:50
   3: core::option::Option<bevy_ecs::resource::resources::ResourceRefMut<bevy_reflect::type_registry::TypeRegistryArc>>::unwrap<bevy_ecs::resource::resources::ResourceRefMut<bevy_reflect::type_registry::TypeRegistryArc>>
             at C:\Users\JD\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\option.rs:386
   4: bevy_reflect::impls::bevy_app::{{impl}}::register_type<core::option::Option<alloc::string::String>>
             at C:\Users\JD\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_reflect-0.4.0\src\impls\bevy_app.rs:52
   5: bevy_core::{{impl}}::build
             at C:\Users\JD\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_core-0.4.0\src\lib.rs:35
   6: bevy_app::app_builder::AppBuilder::add_plugin<bevy_core::CorePlugin>
             at C:\Users\JD\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.4.0\src\app_builder.rs:264
   7: conflict_cay::main
             at .\src\main.rs:4
   8: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\Users\JD\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\conflict_cay.exe` (exit code: 101)
```

**Additional information**

I've got another problem (another panic), this time related to Cpal, when adding DefaultPlugins (so i'm guessing, when adding the audio default plugin)
https://github.com/RustAudio/cpal/issues/533

**Comment by alice-i-cecile** [comment]
>    3: core::option::Option<bevy_ecs::resource::resources::ResourceRefMut<bevy_reflect::type_registry::TypeRegistryArc>>::unwrap<bevy_ecs::resource::resources::ResourceRefMut<bevy_reflect::type_registry::TypeRegistryArc>>


This looks to be the most informative line here. It seems like the `bevy_reflect::type_registry::TypeRegistryArc` was not found?

The example itself is a bit strange: usually `MinimalPlugins` is the smallest I tend to use. In this case, it looks like [MinimalPlugins](https://github.com/bevyengine/bevy/blob/72b2fc98437f39a8099efcc137697efc32a21800/crates/bevy_internal/src/default_plugins.rs) usually includes the `ReflectPlugins` as well, which might explain the error by itself. Going to try to reproduce on my own machine.

**Comment by alice-i-cecile** [comment]
Alright, I'm getting the same problem locally. And, as I suspected, adding the `ReflectPlugin` fixed the issue :)

The minimal fix is:
```rust
use bevy::{core::CorePlugin, reflect::ReflectPlugin, prelude::*, };

fn main() {
    App::build()
        .add_plugin(ReflectPlugin::default())
        .add_plugin(CorePlugin::default())
        .run();
}
```
But the better, more idiomatic fix is:
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(MinimalPlugins)
        .run();
}
```

This is more future-proof and will ensure that you also get the scheduler. I'll send a note to the person who made the tutorial (they probably just didn't test that bit of code since 0.4) but I think this issue can be safely closed :)

**Comment by alice-i-cecile** [comment]
Oh interesting: it looks like you were working off an old version of the tutorial. The current version that I see has:

```rust
use bevy::prelude::*;

fn main() {
    App::build().add_plugins(DefaultPlugins).run();
}
```
as the first snippet, which works perfectly fine :)

**Comment by TFCx** [comment]
I just checked, and yes :) it was my mistake.
DefaultPlugins don't work for me, as there is a problem with Clap (as mentioned at the end of my issue ;) ) but MinimalPlugins works ok (or reflect + default) :)
Should there be a more descriptive error message when loading a module that requires the "reflect" plugin ?

Anyway, i'm closing the issue. Thanks.
