### ISSUE TITLE
`Into<AssetId<T>>` is a massive footgun.

### ISSUE THREAD

**Issue by mintlu8** [bevyengine/bevy#12600]
## How can Bevy's documentation be improved?

This conversion is used a lot in `bevy_asset` and can be mimicked by users. Unfortunately this can be used drop a strong handle, thus the associated asset. For example

```
fn asset_command(mut commands: Commands, asset: impl Into<AssetId<T>>) {
    commands.add(MyCommand(asset.into()))
}
```

This may drop the asset before the command is applied, leading to hard to find bugs.

I think either document this or provide a better trait.

**Comment by alice-i-cecile** [comment]
I think we should probably remove this impl, and provide a nonconsuming method to get this.

**Comment by JMS55** [comment]
Such a method already exists: https://docs.rs/bevy/0.13.1/bevy/asset/enum.Handle.html#method.id

We'd simply have to remove the Into impl.
