### ISSUE TITLE
Move `PanicHandlerPlugin` into `bevy_app`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12603]
## What problem does this solve or what need does it fill?

A new crate was created in https://github.com/bevyengine/bevy/pull/12557: `bevy_panic_handler`. I spoke with @cart and @mockersf about this, and we agree that it makes more sense in `bevy_app` because:

1. Less administrative overhead to release the crate.
2. Less cognitive overhead for users and maintainers.

If and when this code becomes more significant, we can split it back out again.

## What solution would you like?

Move the code into a new module in `bevy_app`. Add the required optional dependencies. Get CI to pass.

## Additional context

This was discussed in #12557, but I didn't feel strongly enough to block forward progress: either solution was clearly better than `bevy_log`.

**Comment by theredfish** [comment]
I'll take a look to this one ✌️

**Comment by gabrielkryss** [comment]
@theredfish oh sorry maybe I should have spoken up sooner, but I was attempting this as my first issue. I was about to have a link to my fork PR soon and inquire about the process to integrate in changes from a forked repo.

**Comment by theredfish** [comment]
@gabrielkryss no problem ! I generally wait a bit to see if nobody else is working on issues so all good 👍

**Comment by gabrielkryss** [comment]
@theredfish I think I got stuck with some ci and workspace errors maybe you can help review the PR if you have the time 🙏.

https://github.com/bevyengine/bevy/pull/12640

**Comment by theredfish** [comment]
@gabrielkryss I'll pull your branch locally and check. Bevy repo is new to me too so I also need to get used to the workflow👍 maybe for the workspace issue you still have your `Cargo.lock` referencing the old dependency in which case it doesn't find it. A clean might help?
