### ISSUE TITLE
Standardize deterministic RNG in examples

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy#12613]
> If we are emphasising that the seeded rng is being used for deterministic purposes, then we kinda shouldn't be using `StdRng` in the first place. [`StdRng` is documented as being *deterministic* in output, but not *portable*](https://docs.rs/rand/latest/rand/rngs/struct.StdRng.html), so there is no assurance that the output will be the same on different platforms or different versions of `rand`. And if we are testing across different platforms, we'd then expect the output to match across all platforms. For further reference from the `rand` documentation, their[ documented expectations for portability/determinism](https://rust-random.github.io/book/portability.html).
>
> Given `rand` minor versions might in the future change the underlying algorithm for `StdRng`, end users might find their tests breaking if they used `StdRng` in their tests after basing them on our examples. Better to instead encourage using the algorithm crates directly if they want to have that extra assurance in determinism. Currently, `rand_chacha` is what is the underlying algorithm for `StdRng`, specifically `ChaCha12Rng`. For game dev purposes, `ChaCha8Rng` would be a better fit to provide higher throughput at the expense of some entropy quality (though it will still be far better than what is probably required).

_Originally posted by @Bluefinger in https://github.com/bevyengine/bevy/issues/12593#issuecomment-2011883060_

I think a good PR would be to replace all usage of `StdRng` with `ChaCha8Rng`, as suggested by @Bluefinger. There are also a few examples that use hashing instead of a proper RNG function that could benefit from switching too.

**Comment by TimLeach635** [comment]
I can take this one!

**Comment by BD103** [comment]
> I can take this one!

Feel free to open up a PR, then!

(By the way, we don't really do issue claiming; it's a first-come-first-serve system. I appreciate your enthusiasm, though!)

**Comment by TimLeach635** [comment]
Made a [PR](https://github.com/bevyengine/bevy/pull/12644) but I'm not sure how to add labels to it (if that's the correct workflow)?

**Comment by BD103** [comment]
Closed in #12644.
