### ISSUE TITLE
Make Bevy's compile-fail tests less fragile

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12627]
## What problem does this solve or what need does it fill?

Bevy uses compile fail tests in [bevy_ecs_compile_fail_tests](https://github.com/bevyengine/bevy/tree/main/crates/bevy_ecs_compile_fail_tests), `deref_derive`, `deref_mut_derive` and [reflect_derives](https://github.com/bevyengine/bevy/actions/runs/8378534423/job/22943464592?pr=12623#step:6:261) to help ensure that our trait implementations fail as we expect.

However, these regularly break (see #12620 for an example) whenever Rust's diagnostics outputs change.
These aren't real failures (caused by a violation of the invariants we're testing for): they're simply changes to the error messages.

Note that this will affect Bevy devs locally as well, if their version of the Rust toolchain doesn't exactly match the one used in CI.

## What solution would you like?

Parse the diagnostic output to ensure that the key bits of information are correct.

## What alternative(s) have you considered?

We could check only the error number, but this will reduce our ability to detect real and valid failures. We want to know *why* the various traits aren't implemented and ensure it's for the correct reason.

We could also include the rustc toolchain version used to generate the tests, and only run the comparison if the user is on that version. This would help with local failures, but result in a more complex setup and not help us when we update rustc versions in CI.

## Additional context

#12625 discusses how we can catch these errors sooner, but this issue covers how we can avoid them breaking at all.

Swapping from `trybuild` to `ui_test` might make this easier to do.

Thanks to @estebank, @workingjubilee and @compiler-errors for the suggestions and guidance here.

**Comment by compiler-errors** [comment]
Would recommend parsing the JSON output of diagnostics (https://doc.rust-lang.org/rustc/json.html) to make it easier to only identify the parts that are useful

**Comment by Brezak** [comment]
We could also run the ui tests against the rust beta once a week or so to get an early warning.

**Comment by alice-i-cecile** [comment]
Yep, early warning is better than nothing, but ideally we don't have to ever spend time fixing these false failures.

**Comment by workingjubilee** [comment]
A concern about "split-brained-ness" was raised, so it's worth noting that rustc also uses [FileCheck](https://llvm.org/docs/CommandGuide/FileCheck.html), a much more lax output checker, for output on things we fundamentally don't really care too hard about specific output matching on, like codegen and assembly tests, but still want to verify the output of. There's no plug-and-play harness for this though, and the syntax can be a bit vexing, especially if you aren't used to regexes.

**Comment by oli-obk** [comment]
ui_test can be set to ignore the output entirely and just rely on the annotations, which almost never break (and can be written in very lenient ways).

**Comment by mockersf** [comment]
Another option would be to make a CI job that opens a PR when it notices a change, then it would just be an approval and a merge to fix it

**Comment by oli-obk** [comment]
> Another option would be to make a CI job that opens a PR when it notices a change, then it would just be an approval and a merge to fix it, without contributors having issues because of the different rustc output based on their OS

Yea, with ui_test you can have the output, but ignore it unless a flag is set. Then the CI job can just run with the flag and open a PR if there is a diff

**Comment by Brezak** [comment]
Can `ui_test` handle path dependencies?
