### ISSUE TITLE
In bevy 0.13.1 , only a single NodeBundle will work.  spawning multiple UI node bundles will destroy the others ones 

### ISSUE THREAD

**Issue by ethereumdegen** [bevyengine/bevy#12624]
## Bevy version

The release number or commit hash of the version you're using.

0.13.1
 
 
## What you did

Describe how you arrived at the problem. If you can, consider providing a code snippet or link.

In bevy 0.13.1 , only a single NodeBundle will work.  spawning multiple UI node bundles will destroy the others ones

**Comment by alice-i-cecile** [comment]
Discussed in an unstructured way [on Discord](https://discord.com/channels/691052431525675048/691052431974465548/1220370540427219095) here, for those looking for more information / history.

**Comment by ethereumdegen** [comment]
the last menu that i spawn works and ONLY that one - no others one

 .fn_plugin(ui_menu_state::ui_menu_state_plugin)
        .fn_plugin(ui_button_events::ui_button_events_plugin)

        .fn_plugin(hud_menu::hud_menu_plugin)
        
        .fn_plugin(game_over_menu::game_over_menu_plugin )
        
        .fn_plugin( main_menu::main_menu_plugin )

        .fn_plugin( character_menu::character_menu_plugin )
        
        
        .fn_plugin(select_ability_menu::select_ability_menu_plugin)
        
        .fn_plugin( system_menu::system_menu_plugin )
        .fn_plugin( dialog_menu::dialog_menu_plugin )

so if i spawn my dialog menu last, that is the only one that works
so it seems kind of like.... NodeBundles are overwriting the previous ones and killign the previosuly spawned one s

**Comment by ethereumdegen** [comment]
some of my code ^^ .  Pretty standard Bevy UI stuff is what is breaking.  Basically only the last NodeBundle i spawn with commands.spawn()  actually works.. the others dont

**Comment by rparrett** [comment]
If someone is able to produce an MRE based on the information here, that would be helpful.

**Comment by extrawurst** [comment]
i am also running into this as it seems. just updated to `0.13.1` and almost all UI disappeared

**Comment by FylmTM** [comment]
After creating minimal example, it seems that we have different behaviour now.
Previously root nodes very sort of absolutely overlayed over each other.
But now they are stacked.

**Before (0.13.0**
![image](https://github.com/bevyengine/bevy/assets/626772/9ebfe944-3625-4c3f-ad87-84958db8a4aa)

**After (0.13.1)** 
![image](https://github.com/bevyengine/bevy/assets/626772/806a911b-4aac-48f5-b972-569b57c1e817)

Example (comment in/out dependencies in `Cargo.toml` to switch between version).

**Comment by nicoburns** [comment]
This might be https://github.com/bevyengine/bevy/issues/12255#issuecomment-1974961300. This is exactly the issue I was expecting from that change.

**Comment by StrikeForceZero** [comment]
> This might be [#12255 (comment)](https://github.com/bevyengine/bevy/issues/12255#issuecomment-1974961300). This is exactly the issue I was expecting from that change.

confirmed, reverting just my commit exhibits the 13.0 behavior.

**Comment by StrikeForceZero** [comment]
setting `PositionType::Absolute` on the root nodes seems to make it behave like it did in 13.0

![image](https://github.com/bevyengine/bevy/assets/983413/bcde58be-4fd6-4deb-8068-dfd87b78c717)


```rust
use bevy::app::{App, PreStartup};
use bevy::prelude::*;

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());

    let mut size = 150.;

    commands.spawn(NodeBundle {
        style: Style {
            position_type: PositionType::Absolute,
            width: Val::Px(size),
            height: Val::Px(size),
            ..default()
        },
        background_color: Color::RED.into(),
        ..default()
    });

    size -= 50.;

    commands.spawn(NodeBundle {
        style: Style {
            position_type: PositionType::Absolute,
            width: Val::Px(size),
            height: Val::Px(size),
            ..default()
        },
        background_color: Color::GREEN.into(),
        ..default()
    });

    size -= 50.;

    commands.spawn(NodeBundle {
        style: Style {
            position_type: PositionType::Absolute,
            width: Val::Px(size),
            height: Val::Px(size),
            ..default()
        },
        background_color: Color::BLUE.into(),
        ..default()
    });
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(PreStartup, setup)
        .run();
}
```

**Comment by RobertBrewitz** [comment]
> setting `PositionType::Absolute` on the root nodes seems to make it behave like it did in 13.0

Hello :wave: I can confirm this works :heavy_check_mark: 

As a consumer of Bevy, it makes sense that the 13.0 behavior only occurs when a root node is positioned absolute. Aligns with how Taffy and CSS treats absolute and relative positioning.
