### ISSUE TITLE
The CPU_USAGE diagnostic frequently reports NaN on Mac OS

### ISSUE THREAD

**Issue by inodentry** [bevyengine/bevy#12628]
## Bevy version

Bevy 0.13

## Relevant system information

```
SystemInfo { os: "MacOS 14.3.1 ", kernel: "23.3.0", cpu: "Apple M1 Pro", core_count: "10", memory: "32.0 GiB" }
```

## What you did

Read the value of the `SystemInformationDiagnosticsPlugin::CPU_USAGE` diagnostic.

## What went wrong

If I read the latest `value()`, it occasionally returns `NaN`. There are often sane values on most frame updates, but they are interspersed with lots of frequent `NaN`s.

If I read the `smoothed()` value, it shows `NaN` all the time. (due to presence of `NaN`s amongst measured values)

## Additional information

This issue is Mac OS specific. On Linux and Windows, there are no `NaN`s and the values are always sane.

**Comment by alice-i-cecile** [comment]
We should omit NaN values when computing smoothed diagnostics. However we should also report the NaNs upstream to sysinfo: I checked https://github.com/GuillaumeGomez/sysinfo/issues?q=is%3Aissue+is%3Aopen+macos and could not find a prior report.

**Comment by Brezak** [comment]
Do we want to store NaNs at all?

**Comment by alice-i-cecile** [comment]
Storing these is useful information for the developer: if something goes wrong, I'd rather have "we couldn't get this data" in my logs, rather than a mysterious gap. We just need to be robust to them in our methods.
