### ISSUE TITLE
CI is failing on Rust 1.77

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12620]
## Bevy version

`main` @ https://github.com/bevyengine/bevy/commit/7b842e373e990445ffb57d5f2fa97786d6d5acdb

## Problem

CI is failing on innocuous PRs: see https://github.com/bevyengine/bevy/commit/7b842e373e990445ffb57d5f2fa97786d6d5acdb for example.

```
error: field `0` is never read
   --> crates/bevy_asset/src/server/loaders.rs:311:14
    |
311 |     struct A(usize);
    |            - ^^^^^
    |            |
    |            field in this struct
    |
    = note: `A` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
    = note: `-D dead-code` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(dead_code)]`
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
    |
311 |     struct A(());
    |              ~~

error: field `0` is never read
```

Similarly, we're getting reports [on Discord](https://discord.com/channels/691052431525675048/692572690833473578/1220385676198019173) about lint failures elsewhere in `bevy_winit`.

These problems all look real (if trivial), this seems to just be the standard "new Rust version shipped lints that weren't caught earlier in CI".

**Comment by JohnTheCoolingFan** [comment]
Also putting the image from the linked discord message here:
![other CI error](https://github.com/bevyengine/bevy/assets/43478602/d05590bf-5a96-426f-941f-c6fd45cc10dd)
