### ISSUE TITLE
Periodically check Bevy's CI against the beta Rust channel

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12625]
## What problem does this solve or what need does it fill?

Most Rust releases, our CI breaks as new lints are stabilized, diagnostics change, or  causing confusion and work stoppage.

See #12620 for the latest.

## What solution would you like?

Run all CI jobs against the [beta channel](https://rust-lang.github.io/rustup/concepts/channels.html) of Rust every week.

It's not clear to me the best way to accomplish this or report it to the community at large. IIRC, Github's built-in feature for this only notifies a single person. Filing and tagging an issue would be ideal.

## What alternative(s) have you considered?

Add more checks to CI.

This adds even more time to our already long CI jobs, and will confuse contributors due to failing changes in unrelated code.

**Comment by Brezak** [comment]
There's a [github action](https://github.com/JasonEtco/create-an-issue) to create an issue, but I don't know if handing it our github token is a good idea safety wise.

**Comment by mockersf** [comment]
[this doc](https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation) shows how to open an issue without depending on a custom action

**Comment by DJMcNab** [comment]
My suggestion for this is to use discord webhooks

(I've been meaning to set the same thing up for Linebender, although of course with Zulip webhooks instead)
