### ISSUE TITLE
Add a loading screen example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12654]
## What problem does this solve or what need does it fill?

Loading and unloading assets on a per-level basis is a simple and generally effective strategy. Commonly, this process is masked from users, using loading screens.

We should teach users how to do this in Bevy.

## What solution would you like?

Requirements:

- use a simple state to track asset loading state: `Loading` vs `FullyLoaded`
- spawn some assets in a scene
- show a loading screen to users before assets are loaded
- swap to that scene once (but not before) all assets are loaded

Stretch goals:

- animate the loading screen
- show progress on the loading screen
- transition between multiple levels (may require #11426 to do nicely), unloading assets from the old level as you do so
- wait for shader pipelines to compile too

## What alternative(s) have you considered?

A more dynamic asset loading solution can work better for e.g. open world games, but is more complex to implement and optimize.

We could also implement a first-party solution for this, but I suspect that the complexity will not be high enough to warrant it and the added flexibility / transparency of doing this as an example will be better.

## Additional context

[bevy_asset_loader](https://github.com/NiklasEi/bevy_asset_loader) is a more sophisticated tool for this. You can see a simple implementation of this pattern [in my archived game Emergence](https://github.com/Leafwing-Studios/Emergence/blob/1dc8ab5050739f8047f24c7a3f60ab091cd46888/emergence_lib/src/asset_management/mod.rs#L53). [iyes_progress](https://github.com/IyesGames/iyes_progress) demonstrates how to track progress and transition states when work is complete.

**Comment by alice-i-cecile** [comment]
The [`game_menu` example](https://github.com/bevyengine/bevy/blob/main/examples/games/game_menu.rs) has a loading screen that we can learn from :)

**Comment by Remi-Godin** [comment]
Hi, I'd like to tackle this issue.

I've got a good idea of how to check if the assets are fully loaded in the asset server, but not sure about how to confirm that a spawned visual asset such as a model is fully rendered. I thought I could use the `SceneInstanceReady` event, but it seems to be broadcasted before the scene is actually rendered to the screen. Would this coincide with the completed compilation of the shader pipelines? Or is there other stuff going on between the `SceneInstanceReady` event and the actual rendering of the scene?

**Comment by alice-i-cecile** [comment]
I think if we wait for pipeline compilation we should be good.
