### ISSUE TITLE
Add an audio example demonstrating how to play a soundtrack

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12651]
## What problem does this solve or what need does it fill?

This is one of the most common actions done with audio in games. We should have an example that clearly demonstrates best practices.

## What solution would you like?

Requirements:

1. Plays a different sound track when the app state changes.
2. Loops the sound track.
3. Volume can be configured.

Stretch goals:

1. Fade in and out during transitions.
2. Don't load the audio track in all at once: instead, stream it from disk on an as-needed basis.

## Additional context

Bloating the repository with binary assets is a non-goal, so we should aim to have two small file-size tracks. This *must* be permissively licensed: update the CREDITS.md file.

Within those constraints, we should pick something that sounds half-decent: we want to make sure that any problems with the sound quality are Bevy problems, not the result of a terrible track.

**Comment by Remi-Godin** [comment]
Hi!

I would be interested in tackling this issue, but I'd like to get some clarification first.

When you mention streaming it from disk, is there a part of Bevy's existing asset or audio systems that allows for doing this relatively easily, or is it something I should implement from scratch? To confirm, this means that it should not be "loaded" by the asset server, correct?

**Comment by alice-i-cecile** [comment]
I think that this is not currently possible. I would leave it out for now, and investigate how to add that functionality in a separate PR that updates a basic example.

**Comment by Remi-Godin** [comment]
Sounds good! I'll try to build an example using what's available for now. Thanks for the clarification.
