### ISSUE TITLE
Sliced scaling does not play well with `Anchor`

### ISSUE THREAD

**Issue by Cyborus04** [bevyengine/bevy#12680]
## Bevy version

v0.13.1

## What you did

I was upgrading my RPG textboxes to use the new 9-slicing feature, but creating a sliced sprite with an anchor not set to `Anchor::Center` does not work right.

## What went wrong

Creating the textbox background with `Anchor::Center` works fine, and looks like this: 

![image](https://github.com/bevyengine/bevy/assets/87248184/eb6955fe-178c-4ca2-8c0a-42187b65470a)

Created with this code:

```rust
let sprite_child = commands
    .spawn(SpriteBundle {
        sprite: Sprite {
            custom_size: Some(vec2(296.5, 83.5)),
            ..default()
        },
        transform: Transform {
            translation: Vec3::new(0.0, -77.75, 4.9),
            rotation: Quat::IDENTITY,
            scale: Vec3::splat(1.0),
        },
        texture: asset_server.load("textbox.png"),
        ..default()
    })
    .insert(ImageScaleMode::Sliced(TextureSlicer {
        border: BorderRect::square(13.0),
        max_corner_scale: 1.0,
        ..default()
    }))
    .id();
```

Creating the textbox background with `Anchor::TopLeft` (with position adjusted correspondingly) does *not* work fine, and looks like this: 

![image](https://github.com/bevyengine/bevy/assets/87248184/118658a5-737e-4c69-9d67-e130a27141be)

Created with this code:
```rust
let sprite_child = commands
    .spawn(SpriteBundle {
        sprite: Sprite {
            anchor: Anchor::TopLeft,
            custom_size: Some(vec2(296.5, 83.5)),
            ..default()
        },
        transform: Transform {
            translation: Vec3::new(-148.25, -36.0, 4.9),
            rotation: Quat::IDENTITY,
            scale: Vec3::splat(1.0),
        },
        texture: asset_server.load("textbox.png"),
        ..default()
    })
    .insert(ImageScaleMode::Sliced(TextureSlicer {
        border: BorderRect::square(13.0),
        max_corner_scale: 1.0,
        ..default()
    }))
    .id();

```

## Additional information

My guess is that the anchor is being taken into consideration when scaling the center of the sliced texture, but not for the other parts.

**Comment by Cyborus04** [comment]
I'll try to get a small reproduction made tomorrow, but right now it is 1:51 AM and I need to sleep...

**Comment by james7132** [comment]
Looks like the same cause as #12408.
