### ISSUE TITLE
Use GitHub's issue forms to simplify issue triage

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#12685]
## What problem does this solve or what need does it fill?
Instead of requiring an organization member to manually apply common labels to issues, it'd be great if the person filing the issue could help label them.

## What solution would you like?
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

GitHub's issue forms should allow asking more targeted questions that we already have in our issue templates, and automate some parts like applying relevant labels to issues. For example, one of the questions may involve asking what kind of bug was seen, so we can ask if the problem is a crash, and it will automatically add `C-Crash` to the issue without a organization member triaging the issue.

## What alternative(s) have you considered?
Leaving it as is, use issue templates as we have been.

**Comment by rparrett** [comment]
Duplicate of #2462?

**Comment by james7132** [comment]
Yep, looks like a duplicate to me. Whoops.
