### ISSUE TITLE
Android logging may need reencoding of the logged values or may be unsound

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#12728]
Found in #12684. The call into `android_log_sys::__android_log_write` may be unsound here: 

https://github.com/bevyengine/bevy/blob/31d91466b4fb99786a8c61b82417372a42a3f531/crates/bevy_log/src/android_tracing.rs#L88-L95

This unsafe call is undocumented and casts two UTF-8 encoded strings as if they were using the OS encoding. They're properly null-terminated, but probably should be converted into `OsString` or `CString` before passing into the function.

**Comment by BD103** [comment]
Linking [docs.rs](https://docs.rs/android_log-sys/0.3.1/android_log_sys/fn.__android_log_write.html) and [Android's Docs](https://developer.android.com/ndk/reference/group/logging#group___logging_1ga32a7173b092ec978b50490bd12ee523b). I believe `CString` works best here.
