### ISSUE TITLE
PersistentGpuBufferable probably shouldn't be an unsafe trait

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#12727]
A good example of an unsafe trait is `TrustedLen` or `WorldQuery`, where the correct implementation of the trait is required to satisfy the safety invariants in its application, and currently PersistentGpuBufferable is not used in such a way. It is not used in any unsafe context CPU-side, and as far as I know, wgpu's validation should prevent any improperly uploading invalid inputs to the GPU.

Of the two implementations of the trait, the `Arc<[u8]>` implementation does not actually satisfy the safety invariants requiring proper alignment of the contents (it's min alignment is 1 and wgpu::COPY_BUFFER_ALGINMENT is currently 4 and this is not enforced in it's implementation), and both implementations do not document how they're satisfying the safety invariants.

Potential solutions here:

 * Make the trait not `unsafe`.
 * Remove the `Arc<[u8]>` implementation or enforce its safety invariants.
 * Document the safety invariants and enforce them properly.

**Comment by JMS55** [comment]
Arc<[u8]> is used for vertex data which is always in multiples of 48 bytes, so it satisfies the alignment.

**Comment by james7132** [comment]
However, that's not enforced as a part of the implementation, which means the trait implementation itself is unsound according to the safety invariants of the trait. 

IMO this should instead just be replaced with an assertion to validate instead of marking this as unsafe, as it's pretty clear that this isn't a memory safety issue, as far as the Rust compiler is concerned.
