### ISSUE TITLE
Kick `Quat` out of `VectorSpace`

### ISSUE THREAD

**Issue by mweatherley** [bevyengine/bevy#12762]
Follow-up for #12747 

I have filed this as a bug, but it's really more of a matter of philosophy than anything (and it's not really an enhancement...).

## What is the issue?

Currently, `Quat` implements `VectorSpace`; however, glam's `Quat` type is supposed to represent *unit* quaternions (i.e. versors), which do not meaningfully form a vector space over the reals, even though the full quaternion algebra does form a real vector space. 

The reason that this is bad is because a lot of vector space operations really don't make sense for `Quat`; chief among these is `VectorSpace::ZERO`, which always produces an invalid quaternion, but in general, vector space operations will cause unit quaternions to denormalize. In other words, `VectorSpace` is at best a collection of convenience methods for quaternions, but they have extremely poor semantics.

## What is the alternative?

Let's fall in line with the philosophy we landed on for colors: Unit quaternions are not a vector space, and if you want to pretend they are, you can embed them in `Vec4` and perform explicit conversions. e.g.:
```rust
let sum_quat = Quat::from_vec4(Vec4::from(quat1) + Vec4::from(quat2)).normalize()
```

**Comment by BD103** [comment]
Not sure how to label this kind of design issue, so I'm going to leave it marked as bug. :)

**Comment by rlidwka** [comment]
> glam's Quat type is supposed to represent unit quaternions (i.e. versors), which do not meaningfully form a vector space over the reals

Unit quaternions are isomorphic to rotations, and rotations do form a perfectly valid vector space.

In particular, unit quaternions form a vector space over R, where zero vector is `x=0, y=0, z=0, w=1`, vector addition is quaternion multiplication, and multiplication of vector by scalar is exponentiation of quaternion by said scalar.

----

That's not the semantics we have at the moment of course, and quaternion addition will usually denormalize it.

**Comment by mweatherley** [comment]
> In particular, unit quaternions form a vector space over R, where zero vector is `x=0, y=0, z=0, w=1`, vector addition is quaternion multiplication, and multiplication of vector by scalar is exponentiation of quaternion by said scalar.

For this to produce anything like a vector space, the quaternions would have to be Abelian. They are not; in fact, SU(2) has rank 1, and its Lie algebra su(2) doesn't even have any Lie subalgebras of dimension 2 (hence no Abelian ones). In other words: it has to be a miracle for addition between to elements to even commute.

**Comment by SolarLiner** [comment]
So the action here is to remove the `VectorSpace` impl from Quat, right? If so, I'm marking this as a good first issue as the changes are straightforward, and the impl hasn't been there long enough for it to be an effective breaking change.

**Comment by mweatherley** [comment]
> So the action here is to remove the `VectorSpace` impl from Quat, right? If so, I'm marking this as a good first issue as the changes are straightforward, and the impl hasn't been there long enough for it to be an effective breaking change.

Yep! Technically `NormedVectorSpace` too, but it's all in one place. We did release a version with `Quat` as a `Point`, so it's breaking in that sense (at least, either way it should probably be mentioned in release notes).
