### ISSUE TITLE
Ambient light added by Default plugins should not overwrite user supplied options

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12807]
Add it _after_ you add DefaultPlugins. DefaultPlugins will insert a new ambient light and overwrite the one you added.

_Originally posted by @JMS55 in https://github.com/bevyengine/bevy/discussions/12800#discussioncomment-8960462_

**Comment by alice-i-cecile** [comment]
We should be able to swap to an init_resource call.

**Comment by Brezak** [comment]
It seems to me like we're already using `init_resource`. https://github.com/bevyengine/bevy/blob/97f0555cb0674ed161be012100af3541b95a5877/crates/bevy_pbr/src/lib.rs#L276

**Comment by alice-i-cecile** [comment]
Hmm that's odd..
