### ISSUE TITLE
Add run criterias to StateStages

### ISSUE THREAD

**Issue by NiklasEi** [bevyengine/bevy#1281]
**What problem does this solve or what need does it fill?**

This feature would allow limiting the frames per second of a game using `StateStages`.

**What solution would you like?**

The way this can already be done for `SystemStages` would be a very nice to have on `StateStages` (e.g. `with_run_criteria`).

**What alternative(s) have you considered?**

I don't know of any alternatives appart from doing this manually with timers on each system, but would be interested in better options :)

**Comment by DJMcNab** [comment]
You can put a run criteria in the `SystemStage` of a `StateStage`
```rust
`my_state_stage.update_stage(MyState::MySubState, |it: &mut SystemStage| it.with_run_criteria(my_run_criterion));`
```

**Comment by NiklasEi** [comment]
I am not getting that to compile. Current code:
`impl Plugin for GamePlugin {
    fn build(&self, app: &mut AppBuilder) {
        let mut my_state_stage = StateStage::<AppState>::default();
        my_state_stage.update_stage(AppState::InGame, |it: &mut SystemStage| {
            it.with_run_criteria(FixedTimestep::steps_per_second(60.))
        });
        app
            .add_stage_after(stage::UPDATE, STAGE, my_state_stage)
    }
}`
Maybe I am just missing some rust knowledge here... The return type of the closure seems wrong (it expects &mut SystemStage), but if I return `&mut` in the closure that also fails to compile with `cannot return reference to temporary value`.

**Comment by DJMcNab** [comment]
Ok, so this issue can probably be repurposed for that issue, with a title and contents:

# `SystemStage` has no `add_run_criteria`

https://github.com/bevyengine/bevy/blob/0a39c81be6b5712c24a75a7c215dbe254097adff/crates/bevy_ecs/src/schedule/stage.rs#L67-L71
is the method used to add a system to a `SystemStage`, but there's no equivalent method when you only have a mutable reference.

The naïve implementation works fine:
```rust
    pub fn add_run_criteria<S: System<In = (), Out = ShouldRun>>(
        &mut self,
        system: S,
    ) -> &mut Self {
        self.run_criteria = Some(Box::new(system));
        self.run_criteria_initialized = false;
        self
    }
```
