### ISSUE TITLE
UV coords in `generate_custom_mesh` example are wrong

### ISSUE THREAD

**Issue by xxshady** [bevyengine/bevy#12822]
At [this line](https://github.com/bevyengine/bevy/blob/55215706f2e06afeb392fec95766facbf7bd221a/examples/3d/generate_custom_mesh.rs#L169) last coord of the top side should be `[1.0, 0.2]`, not `[1.0, 0.25]`

I have added yellow rectangle to texture to demonstrate this

<details>
  <summary>demo</summary>
  <img src="https://github.com/bevyengine/bevy/assets/54737754/d5527f92-b90b-488e-b7c0-ed3835a6830b">
</details>

<details>
  <summary>texture</summary>
  <img src="https://github.com/bevyengine/bevy/assets/54737754/4a173341-2ac7-4fa5-a8d9-fbdd32865ffc">
</details>

**Comment by jake8655** [comment]
Will make a quick PR in just a moment
