### ISSUE TITLE
Maybe `Entity` should be `bytemuck::PodInOption`

### ISSUE THREAD

**Issue by mintlu8** [bevyengine/bevy#12821]
## What problem does this solve or what need does it fill?

It would be useful for `Entity` to be usable with `bytemuck`.

## What solution would you like?

Implement `PodInOption` for `Entity`. Since generation index is `NonZero`,
this makes `Option<Entity>` `Pod`. 

A downside is this would potentially limit `Entity`'s future layout.

## What alternative(s) have you considered?

Use the conversion methods to and from u64. 

## Additional context

Not 100% sure this is sound on all platforms.

**Comment by james7132** [comment]
It can definitely implement `NoUninit`, which is something I think is feasible to support long term. Not sure about adding a dependency on `bytemuck`, even optional, to `bevy_ecs` though. What's the use case here?

**Comment by mintlu8** [comment]
> It can definitely implement `NoUninit`, which is something I think is feasible to support long term. Not sure about adding a dependency on `bytemuck`, even optional, to `bevy_ecs` though. What's the use case here?

I think having bytemuck support can help with some ergonomic serialization use cases. But I've changed my mind on this and u64 is definitely fine for most cases I need. Still might be worth the consideration though.
