### ISSUE TITLE
Normalize warning message when resizing on Linux with NVIDIA drivers

### ISSUE THREAD

**Issue by jake8655** [bevyengine/bevy#12830]
## Bevy version
The change was introduced in commit 70c69cdd51311e4f2be6f4ee245ff5ab89c1fc24

## What you did
The PR author initially provided this warning message (in commit https://github.com/bevyengine/bevy/pull/12542/commits/d2dbf53db3bdc486355bf7ccf1d11b0f867077a9):
```Couldn't get swap chain texture. This often happens with the Nvidia 550 driver. It can be safely ignored.```

This message appears twice in the codebase. One of these occurrences has been altered to the following text (in commit https://github.com/bevyengine/bevy/pull/12542/commits/93ea1535b5c48cbc96cd191e9bfb511cc6c5b301):
```Couldn't get swap chain texture. This often happens with the NVIDIA drivers on Linux. It can be safely ignored.```

## What went wrong
This change has not been made in the other place: https://github.com/bevyengine/bevy/blob/93fd02e8ea0361d9d58f2cc797d012216084b082/crates/bevy_render/src/view/window/mod.rs#L343-L344

Is this the intended behavior, or is it supposed to be changed as well?

If it was just forgotten and needs to be corrected let me know, I can make a quick PR to fix it.

**Comment by matiqo15** [comment]
It looks like it was forgotten - feel free to open a PR!
