### ISSUE TITLE
SystemInformationDiagnosticsPlugin is slow due to `sysinfo` crate

### ISSUE THREAD

**Issue by jannik4** [bevyengine/bevy#12848]
## Bevy version

0.13.1

## Relevant system information

- OS: Windows 11
- Processor: AMD Ryzen 9 7950X3D 16-Core Processor

## What you did

Add the `bevy::diagnostic::SystemInformationDiagnosticsPlugin` plugin.

## What went wrong

The `diagnostic_system` of the `SystemInformationDiagnosticsPlugin` takes around 4ms on my system, which makes it unsuitable to use while measuring performance.

## Additional information

Noticed this, as I used this with `iyes_perf_ui` and could not get more than 200FPS.

**Comment by alice-i-cecile** [comment]
Any indication if this is an upstream problem, versus something that Bevy is doing wrong? Is this just latency, or is there real work being done?

**Comment by jannik4** [comment]
For the CPU usage there seems to be a [`MINIMUM_CPU_UPDATE_INTERVAL`](https://docs.rs/sysinfo/latest/sysinfo/constant.MINIMUM_CPU_UPDATE_INTERVAL.html). This is definitively not respected when running at high frame rates.

Other than that I could not find information on how costly the refresh calls are. It might make sense to do the refreshes/measurements on an AsyncCompute task, so it does not block the frames.

**Comment by ChristopherBiscardi** [comment]
I ran into this today so here's the tracy graph I was looking at. Enabling the plugin can drop fps to 30 or less, while disabling the plugin lets this particular app run at 200+ fps.

![image](https://github.com/bevyengine/bevy/assets/551247/f47c0999-3c30-445d-8531-72be76236c72)

```
2024-05-30T17:46:01.222416Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 2080 Ti", vendor: 4318, device: 7687, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "551.23", backend: Vulkan }
2024-05-30T17:46:01.515482Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Pro", kernel: "22631", cpu: "AMD Ryzen 9 7950X 16-Core Processor", core_count: "16", memory: "63.2 GiB" }
```
