### ISSUE TITLE
Planes ignore transform

### ISSUE THREAD

**Issue by sburris0** [bevyengine/bevy#1285]
**Bevy version**
0.4

**Operating system & version**
Latest Void Linux

**What you did**
1. Spawn cube with size 1.0 at (0,0,0)
2. Spawn plane at (0,-5,0)

**What you expected to happen**
I expect the plane to be below the cube

**What actually happened**
The plane bisects the cube (as if it were at (0,0,0))

**Additional information**
Specifying a plane with translation (5, 3, 4) for example will still spawn it at (0,0,0)

Screenshot:
![bevy_plane](https://user-images.githubusercontent.com/58098832/105538979-11099080-5ca9-11eb-961a-48c30c6436af.png)

Minimum code to reproduce:
```Rust
use bevy::prelude::*;

pub fn setup_world(
    commands: &mut Commands,
    mut meshes: ResMut<Assets<Mesh>>,
) {
    commands
        .spawn(PbrBundle {
            mesh: meshes.add(Mesh::from(shape::Plane { size: 2.0 })),
            transform: Transform::from_translation(Vec3::new(0., -5., 0.)),
            ..Default::default()
        })
        .spawn(PbrBundle {
            mesh: meshes.add(Mesh::from(shape::Cube { size: 1.0 })),
            transform: Transform::from_translation(Vec3::new(0.,0.,0.)),
            ..Default::default()
        })
        .spawn(PbrBundle {
            mesh: meshes.add(Mesh::from(shape::Cube { size: 1.0 })),
            transform: Transform::from_translation(Vec3::new(1.,1.,0.)),
            ..Default::default()
        })
}


#[bevy_main]
fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup_world.system())
        .run();
}
```

**Comment by TheRawMeatball** [comment]
As a control case, can you try to reproduce this error on master? I haven't been able to recreate this error on the master branch.

**Comment by sburris0** [comment]
Appears to be fixed on master, closing.
