### ISSUE TITLE
Improve documentation and example around enabling audio formats in Cargo.toml

### ISSUE THREAD

**Issue by brianearwood** [bevyengine/bevy#12900]
### AudioSource documentation
In [AudioSource doc](https://docs.rs/bevy/latest/bevy/audio/struct.AudioSource.html), It's not clear that mp3, flac and wav are not initially enabled and that those features need to be added to the Cargo.toml

### audio.rs example
When referring to Bevy's [general audio example](https://github.com/bevyengine/bevy/blob/6c485c80e02af686c494fa3b0683b8e82c24e70b/examples/audio/audio.rs), it would be helpful to add more information that additional audio features need to be added to Cargo.toml when using mp3, wav, or flac formats.

### Suggested text: 
"Audio formats, wav, mp3 and flac, are not automatically enabled in Bevy and need to be added to Cargo.toml"

**Comment by targrub** [comment]
A more general issue is of attempts to load/process files but the filenames of those files that fail not being logged.  So in this case, a better error message would also note the name of the particular file that generated this error.  The same should apply IMHO to textures, images, 3d models...any other engine-loaded files that fail to load properly.
