### ISSUE TITLE
`DiagnosticsStore` should not be disabled with the `sysinfo` crate

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12911]
> @AxiomaticSemantics I just noticed you added the cfg to the line that inserts the DiagnosticsStore to the app. Was that intentional? There's a bunch of diagnostics that don't rely on the sysinfo_plugin.

_Originally posted by @IceSentry in https://github.com/bevyengine/bevy/issues/12164#issuecomment-2008294811_

**Comment by IceSentry** [comment]
That was fixed in a PR I did to make sysinfo a Resource. I just noticed it while working on that but since I didn't get an answer I fixed it assuming it wasn't intentional.
