### ISSUE TITLE
Sprite example broken after #12582: Divide the single `VisibleEntities` list

### ISSUE THREAD

**Issue by mgi388** [bevyengine/bevy#12935]
## Bevy version

The release number or commit hash of the version you're using.

5caf085da (from #12582)

## Relevant system information

```
INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 14.2.1 ", kernel: "23.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
```

## What you did

```
$ RUST_BACKTRACE=full MTL_HUD_ENABLED= cargo run --example sprite
```

## What went wrong

Looks like this:

<img width="1279" alt="image" src="https://github.com/bevyengine/bevy/assets/135186256/c8418ad5-581f-463a-9e0d-652322581adc">

## Additional information

Works before this commit on 5c3ae32ab:

```
$ git checkout 5c3ae32ab
$ RUST_BACKTRACE=full MTL_HUD_ENABLED= cargo run --example sprite
```

<img width="1284" alt="image" src="https://github.com/bevyengine/bevy/assets/135186256/3d68cf15-72c2-4de3-a70a-144cb272c8c0">

**Comment by pcwalton** [comment]
#12945 is a fix
