### ISSUE TITLE
C++ missing in docs, linux dependencies for Ubuntu

### ISSUE THREAD

**Issue by fossegutten** [bevyengine/bevy#1294]
**Bevy version**
0.4.0
The release number or commit hash of the version you're using.

**Operating system & version**
Ubuntu 20.04
Ex: Windows 10, Ubuntu 18.04, iOS 14.

**What you did**
Followed instructions in [linux dependencies](https://github.com/bevyengine/bevy/blob/master/docs/linux_dependencies.md)
Fixed it by installing this: `sudo apt install build-essential`

**What you expected to happen**
bevy to build when following instructions in the docs

**What actually happened**
Build failed because c++ was not installed

**Additional information**

```
error: failed to run custom build command for `spirv-reflect v0.2.3`

Caused by:
  process didn't exit successfully: `/home/fossegutten/Documents/repos/macroquad_test/target/debug/build/spirv-reflect-ae517a33d2ec2bb5/build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src" "-Wall" "-Wextra" "-std=c++11" "-o" "/home/fossegutten/Documents/repos/macroquad_test/target/debug/build/spirv-reflect-4368630b06c20c32/out/vendor/spirv_reflect.o" "-c" "vendor/spirv_reflect.c"

  --- stderr


  error occurred: Failed to find tool. Is `c++` installed?


warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by CleanCut** [comment]
Interesting. `build-essentials` installs `g++`, which is a C++ compiler.  The doc says if you want fast compiles to install `clang` ...which is _also_ a C++ compiler.  If you uninstall `g++` and install `clang`...does it still work? If so, maybe `clang` should be merged into the required installs?

**Comment by saveriomiroddi** [comment]
AFAIK g++ does install the C++ compiler, however, the binary name is `/usr/bin/g++`. The `c++` searched by the build system is called `c++`.

On my system, where `build-essential` is installed, there is the file `/usr/bin/c++` (which is a symlink to `/etc/alternatives/c++`, which in turn is a symlink to `/usr/bin/g++`. This is very likely added by the package, for compatibility purposes.

Installing `build-essential` is common practice, so IMO, it should be added to the list of dependencies.

**Comment by saveriomiroddi** [comment]
ok, so, I've inspected a stock Ubuntu MATE 20.04.1, and `build-essential` is preinstalled. @fossegutten which Ubuntu distro are you using?

**Comment by saveriomiroddi** [comment]
I've done a quick test on Ubuntu Server 20.04.x, where `build-essential` is not installed.

The file `/usr/bin/c++` is installed by the `g++` package. As a consequence, the instructions should have at least `g++` added.

In the issue reported, installing `build-essential` solves the problem because it installs `g++` as dependency.

I'd add `build-essential`, since it's common practice, and it also installs `make` as dependency.

Note: I've deleted my previous comment. Based on the current findings, the previous comment was just noise.
