### ISSUE TITLE
Expose `winit::monitor` as queryable component

### ISSUE THREAD

**Issue by tychedelia** [bevyengine/bevy#12955]
## What problem does this solve or what need does it fill?

Currently, Bevy allows window creation via [`MonitorSelection`](https://docs.rs/bevy/0.13.2/bevy/window/enum.MonitorSelection.html), but does not expose any information about what monitors are available. For [Nannou](https://github.com/nannou-org/nannou/), we need to expose monitor metadata to allows users to programmatically select the monitor. Creative coding applications tend have much more demanding multi-window/multi-monitor setups, and so this information is generally useful.

## What solution would you like?

We'd like to implement the following features:
- Expose the data provided by [`winit::monitor::MonitorHandle`](https://docs.rs/winit/0.29.15/winit/monitor/struct.MonitorHandle.html) as a user queryable component.
- Allow creation of a window via a monitor's `Entity`.

## What alternative(s) have you considered?

N/A

## Additional context

N/A

**Comment by alice-i-cecile** [comment]
Sounds reasonable :) I think that these should be monitor entities, and work just like window entities with a synchronization step.
