### ISSUE TITLE
multi-threaded feature name is kebab case but all others are snake case

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#12966]
## Bevy version

0.14

## What went wrong

See https://github.com/bevyengine/bevy/blob/62f2a73cac70237c83054345a26b19c9e0a0ee2f/Cargo.toml#L70

**Comment by alice-i-cecile** [comment]
Oh so there is. We should change all of the ones that aren't deliberately matching a dependencies' feature IMO.

**Comment by mockersf** [comment]
so, this issue doesn't mention the expected fix: should all features be kebab case?

**Comment by alice-i-cecile** [comment]
I would prefer all snake case for consistency with crate names :) But really I don't care, as long as it's consistent.
