### ISSUE TITLE
WireFrameColor component ignored 

### ISSUE THREAD

**Issue by galop1n** [bevyengine/bevy#13032]
## Bevy version

0.13.2

## What you did

Add `WireframeColor` to various `PbrBundle`
Set default_color to yellow in `WireframeConfig`
Set `global` to true in `WireframeConfig`

## What went wrong

`WireframeColor` is ignored and all wireframe is yellow as set in the global config. Documentation state that in the absence of the `Wireframe` component, it should still influence the wire color when global is set to true.

- what were you expecting?

The wire color of the pbr bundle should be the one set the `WireframeColor` component.

- what actually happened?

All PbrBundle used the global default color from  `WireframeConfig`

## Additional information

If I add the `Wireframe` component, the color is properly applied to the wireframe.

**Comment by IceSentry** [comment]
This will be fixed by https://github.com/bevyengine/bevy/pull/13034
