### ISSUE TITLE
Create CONTRIBUTING.md guidelines

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1303]
**What problem does this solve or what need does it fill?**

We should have one central place to point new (and old) contributors when they have questions about the contribution process, especially when it come to PRs.

I think this is particularly valuable for contributors who are new to Rust or open source development. This is more likely to be true with Bevy than other projects, due to its accessibility and broad interest.

**What solution would you like?**

Create a CONTRIBUTING.md file.

Current steps for making a PR:

1. Fork the repo.
2. Make changes locally.
3. ~~Run `cargo fmt`.~~ Run `cargo +nightly fmt`.
4. Run `cargo clippy`.  Take the clippy command from the workflows folder & run the same command.
5. Submit a pull request with a descriptive title and any important context about the changes.

**What alternative(s) have you considered?**

Continue to pass this information on one contributor at a time, or trust that they're experienced to know how to do so.

**Additional context**

[Prompt](https://discord.com/channels/691052431525675048/692572690833473578/802810610865143828) for this issue.

**Comment by rparrett** [comment]
Should that be `cargo +nightly fmt`?

**Comment by CleanCut** [comment]
Like this? #1309

**Comment by CleanCut** [comment]
Actually resolved by https://github.com/bevyengine/bevy-website/pull/85 -- the place to point to is https://bevyengine.org/learn/book/contributing/code/

#1309 continues down a different avenue...
