### ISSUE TITLE
cargo run --features bevy/dynamic_linking does not worK

### ISSUE THREAD

**Issue by GoodCoder27** [bevyengine/bevy#13042]
## Bevy version
I use bevy 0.13.2

## Relevant system information
OS: Fedora 39
cargo version 1.77.2

## What went wrong
After I write `cargo run --features bevy/dynamic_linking`

I get an error that says:
```error: failed to select a version for the requirement `bevy_dylib = "^0.13.2"`
candidate versions found which didn't match: 0.13.1, 0.13.0, 0.12.1, ...
location searched: crates.io index
required by package `bevy v0.13.2`
    ... which satisfies dependency `bevy = "^0.13.2"` (locked to 0.13.2) of package `rts_game v0.1.0 (/media/harddrive/rust/rts_game)`
perhaps a crate was updated and forgotten to be re-vendored?```

**Comment by alice-i-cecile** [comment]
Does this error persist after deleting your `Cargo.lock` and calling `cargo clean`?

**Comment by GoodCoder27** [comment]
This solved the issue. Thanks!
