### ISSUE TITLE
Module docs don't appear in monolithic docs.rs page

### ISSUE THREAD

**Issue by NthTensor** [bevyengine/bevy#13055]
Every bevy crate has it's own docs.rs page, and also appears as modules within [the monolithic bevy documentation page](https://docs.rs/bevy/latest/bevy/). Users are usually directed to the monolithic docs, and it's what we link to on the website.

Unfortunately module level docs (like [this](https://github.com/bevyengine/bevy/blame/13cac2eeff7e3c4da7ae636ba3766f59b4e343d0/crates/bevy_reflect/src/lib.rs#L9)) don't display properly on the monolithic module page ([here](https://docs.rs/bevy/latest/bevy/reflect/index.html) for example). They do render properly on the individual crate docs ([this](https://docs.rs/bevy_reflect/latest/bevy_reflect/) is how the rendered docs should look). This means most users are loosing out on important structural documentation.

**Comment by alice-i-cecile** [comment]
IMO we should use separate `.md` files for each of these, and `#![doc = include_str!("path/to/docs.md")]` in both locations.
