### ISSUE TITLE
`TextLayoutInfo` doesn't contain every processed glyph

### ISSUE THREAD

**Issue by eidloi** [bevyengine/bevy#13063]
## Bevy version

0.13

## What you did

Debug log any `TextLayoutInfo` to inspect the glyph list.

## What went wrong

The `TextLayoutInfo` only contains `PositionedGlyph`s that are from the outlined list.

## Additional information

Interacting with text (i.e. placing a caret, selection) is impossible without knowing the positions of individual glyph and their relation to the sections they came from. While the relation part can be worked around, the position and scale of the rendered glyph is necessary. This info is currently opaque and recalculating it is both expensive and needs copy/paste of private bevy code, such as the `GlyphPlacementAdjuster`

**Comment by alice-i-cecile** [comment]
Is this just a matter of exposing more of the internals?

**Comment by jordanhalase** [comment]
I'd just like to add that having access to the processed glyphs would be useful to implement the typewriter effect which is used nearly ubiquitously in RPGs or any game with dialogue boxes. Also in this space it could be used to make text glyphs "jiggle" or fly around the screen into place.

Ensuring that they are all present when you expect them makes this process easier, though I would like to do more testing to see if Bevy could make this process easier in the future.

**Comment by rparrett** [comment]
This was fixed by #10193
