### ISSUE TITLE
Loading a glTF scene doesn't use the correct UV map for ambient occlusion

### ISSUE THREAD

**Issue by jf908** [bevyengine/bevy#13086]
## Bevy version

0.13.2 and latest main (9592a40e1eb387f926b787cbb3a65d9db1dfb1a3)

## Relevant system information

```ignore
AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti Laptop GPU", vendor: 4318, device: 9440, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "546.33", backend: Vulkan }
```

## What you did

Load a gltf model with a ambient occlusion lightmap

## What went wrong

| Expected | Actual |
| --- | --- |
| https://gltf-viewer.donmccurdy.com/ | Bevy Scene Viewer Example |
| ![image](https://github.com/bevyengine/bevy/assets/2487520/bf392518-f9a4-4d47-ac9c-d2d72a227a37) | ![image](https://github.com/bevyengine/bevy/assets/2487520/bce273db-00a9-4e2f-ab04-2b36d2a6103d) |

In the example there is a cube mesh and a plane mesh, each with 2 UV maps. One UV map is used for the base colour and one is used for ambient occlusion. The gltf-viewer and three.js read and render the model correctly but not in bevy. The base texture can be seen properly rendered through the broken ambient occlusion texture so I suspect that the ambient occlusion is working but the 2nd UV map is not being used or being read incorrectly.

## Additional information

Model used to test: [gltf_model.zip](https://github.com/bevyengine/bevy/files/15097983/gltf_model.zip)

**Comment by bugsweeper** [comment]
[This](https://github.com/bevyengine/bevy/issues/12496) also has problems with UV-map, but may be different kind

**Comment by geckoxx** [comment]
It is a similar issue. The material in the file is using a specific texCoord for its occlusionTexture but this is ignored by the gltf loader: https://github.com/bevyengine/bevy/blob/ade70b3925b27f76b669ac5fd9e2c31f824d7667/crates/bevy_gltf/src/loader.rs#L856

**Comment by jf908** [comment]
I thought with the lightmap update in 0.13, bevy pbr supported 2 UV maps? three.js is hardcoded to use the 2nd UV map for ambient occlusion and lightmap textures and the 1st UV map for everything else. Perhaps bevy could follow the same convention until multiple UV maps become more flexible?

**Comment by bugsweeper** [comment]
> It is a similar issue. The material in the file is using a specific texCoord for its occlusionTexture but this is ignored by the gltf loader
Problem is that baseColorTexture uses TEXCOORD_0, but (!!!) occlusionTexture uses TEXCOORD_1, bevy_pbr does use same ATTRIBUTE_UV_0 for both of them, that's why loader can't load this glb in StandardMaterial with correct bevy_pbr interpretation
