### ISSUE TITLE
Likely overpadded motion blur struct

### ISSUE THREAD

**Issue by torsteingrindvik** [bevyengine/bevy#13097]
## Bevy version

Latest main.

## What you did

Had a look at the newly merged motion blur PR.

## What went wrong

https://github.com/bevyengine/bevy/blob/main/crates/bevy_core_pipeline/src/motion_blur/motion_blur.wgsl#L21

If I'm not mistaken the padding is meant to ensure the fields add up to 16 bytes.

Since there is a `f32` and a `u32` before the padding, the "hole" is 8 bytes, but the padding adds 12 bytes via `vec3<f32>`.

In this case the wgsl should change to `vec2<f32>` as well as the corresponding Rust side `ShaderType` struct.

**Comment by rparrett** [comment]
The example doesn't even seem to compile for wasm
```
error[E0063]: missing field `_webgl2_padding` in initializer of `bevy::bevy_core_pipeline::motion_blur::MotionBlur`
  --> examples/3d/motion_blur.rs:24:26
   |
24 |             motion_blur: MotionBlur {
   |                          ^^^^^^^^^^ missing `_webgl2_padding`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `bevy` (example "motion_blur") due to 1 previous error
```
