### ISSUE TITLE
Crash when using Camera2DBundle without HDR + TonyMcMapFace tonemapping

### ISSUE THREAD

**Issue by Zarthus** [bevyengine/bevy#13118]
## Bevy version

0.13.2, `main` branch (22d605c8)

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- Latest rust version
- Windows 11

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```ignore
AdapterInfo { 
  name: "NVIDIA GeForce RTX 3080", vendor: 4318, device: 8710, 
  device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "551.86", backend: Vulkan 
}
```

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

- [`wgpu`](https://github.com/gfx-rs/wgpu) for rendering problems
- [`winit`](https://github.com/rust-windowing/winit) for input and window management
- [`gilrs`](https://docs.rs/gilrs/latest/gilrs/) for gamepad inputs

## What you did

TL;DR:

- Spawn a `Camera2DBundle`
  - Set `HDR` = false
  - Set `tonemapping` = `Tonemapping::TonyMcMapFace` 
- Run Bevy

Minimal code snippet:

```rust
use bevy::{
    core_pipeline::tonemapping::Tonemapping,
    prelude::*
};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn((
        Camera2dBundle {
            camera: Camera {
                hdr: false,
                ..default()
            },
            tonemapping: Tonemapping::TonyMcMapface,
            ..default()
        },
    ));
}
```

```toml
[package]
name = "bevy_crash_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"

## What's maybe interesting is that this seems to be relevant to the feature `bevy_ui`:
## no crash:
# bevy = { version = "0.13.2", default-features = false, features = ["bevy_core_pipeline",  "tonemapping_luts", "bevy_winit"]} 

## crash:
# bevy = { version = "0.13.2", default-features = false, features = ["bevy_core_pipeline",  "tonemapping_luts", "bevy_winit", "bevy_ui"]} # crash
```

Describe how you arrived at the problem. If you can, consider providing a code snippet or link.

## What went wrong

```
2024-04-27T14:40:26.471379Z ERROR log: Device::create_render_pipeline error: Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline    
2024-04-27T14:40:26.471813Z ERROR log: Device::create_render_pipeline error: Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
2024-04-27T14:40:26.471844Z ERROR log: Handling wgpu errors as fatal by default
thread 'Async Compute Task Pool (1)' panicked at C:\Users\BuuGh\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.4\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `sprite_pipeline`
    Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
    Shader global ResourceBinding { group: 0, binding: 18 } is not available in the pipeline layout
    Binding is missing from the pipeline layout
```

Backtrace: https://github.com/bevyengine/bevy/issues/13118#issuecomment-2081120194

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- Things like `Reinhard` for tonemapping works fine, it seems specific to `TonyMcMapFace`.

**Comment by inodentry** [comment]
Strange, because you do have the `tonemapping_luts` feature enabled in both cases. That would have been my first guess as to the culprit for the crash, as you need that cargo feature if you want to use the fancier tonemapping algorithms. But since you have included it in the configuration where you say you get the crash, that's clearly not the problem.

We should investigate. Since you say the `bevy_ui` feature makes a difference, my initial gut feeling would be to look at how the render graph and camera configuration changes with vs without bevy_ui. Maybe look at setup code in the `bevy_ui` crate to see what it does to the camera and render graph and if it changes anything relevant.

**Comment by inodentry** [comment]
Also, since you say your bevy version is 0.13.2, can you please try and see if you can reproduce this issue with the current git main?

**Comment by Zarthus** [comment]
I checked quickly, also reproduces on the latest main (22d605c8):

```
2024-04-27T18:19:10.318074Z  INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
2024-04-27T18:19:10.666123Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3080", vendor: 4318, device: 8710, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "551.86", backend: Vulkan }
2024-04-27T18:19:11.156111Z ERROR wgpu_core::device::global: Device::create_render_pipeline error: Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline    
2024-04-27T18:19:11.156494Z ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default
thread 'main' panicked at C:\Users\BuuGh\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.4\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `sprite_pipeline`
    Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
    Shader global ResourceBinding { group: 0, binding: 18 } is not available in the pipeline layout
    Binding is missing from the pipeline layout


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_core_pipeline::upscaling::prepare_view_upscaling_pipelines`!
2024-04-27T18:19:11.158807Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped.
2024-04-27T18:19:11.158960Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped.
```

**Comment by arcashka** [comment]
I checked main and it fails both with `bevy_ui` and without it.
Looks like the issue is what bevy doesn't binds tonemapping LUT images for `SpritePipeline` and `Mesh2dPipeline`.
Here's how it looks with MeshPipeline https://github.com/bevyengine/bevy/blob/main/crates/bevy_pbr/src/render/mesh_view_bindings.rs#L521

I'm still very much uncertain if this is fully correct, I will investigate it a little more, and hopefully will come up with the PR
