### ISSUE TITLE
ERROR bevy_asset::server: Asset Source 'AssetSourceId::Name(embeded)' does not exist

### ISSUE THREAD

**Issue by AllenDang** [bevyengine/bevy#13129]
## Bevy version

0.13.2

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
  - cargo 1.77.2 (e52e36006 2024-03-26)
- the operating system or browser used, including its version
  - macOS 14

## What you did

1. I wrote a wgsl shader file and save it to "./assets/shader/shader_separate_channel.wgsl"
2. I embedded it with `embedded_asset!(app, "shader/shader_separate_channel.wgsl");`
3. I tried to get it's content via 
```rust
impl Material for MaterialSeparateChannel {
    fn fragment_shader() -> ShaderRef {
        "embeded://shader/shader_separate_channel.wgsl".into()
    }

    fn alpha_mode(&self) -> AlphaMode {
        AlphaMode::Blend
    }
}
```

## What went wrong

`cargo run` popup error message like below
```
❯ cargo run
   Compiling img_maniac v0.3.3 (/Users/allen/Documents/RustProjects/img_maniac)
    Finished dev [unoptimized + debuginfo] target(s) in 1.47s
     Running `target/debug/img_maniac`
2024-04-28T13:15:24.803752Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-04-28T13:15:25.173208Z ERROR bevy_asset::server: Asset Source 'AssetSourceId::Name(embeded)' does not exist
2024-04-28T13:15:25.187741Z  INFO bevy_winit::system: Creating new window "Image Maniac v0.3.3" (0v1)
2024-04-28T13:15:25.221368Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 14.4.1 ", kernel: "23.4.0", cpu: "Apple M1 Max", core_count: "10", memory: "32.0 GiB" }
```

**Comment by MilimTheTrueOne** [comment]
You misspelled the name, it should be `embedded`, your code says `embeded`.

**Comment by AllenDang** [comment]
@MilimTheTrueOne Thanks, my bad, not the error message changed to "ERROR bevy_asset::server: Path not found: shader/shader_separate_channel.wgsl"...

**Comment by MilimTheTrueOne** [comment]
take a look at these [docs](https://docs.rs/bevy/latest/bevy/asset/macro.embedded_asset.html).

**Comment by AllenDang** [comment]
@MilimTheTrueOne Thanks, I need to add the crate name to the embedded path, it's loaded now.

**Comment by MilimTheTrueOne** [comment]
No problem :)
