### ISSUE TITLE
example `shader_instancing` doesn't work after GPU frustum culling

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#13130]
## Bevy version

main since #12889 

## \[Optional\] Relevant system information

reproducing locally on an Apple M1 Max, but happening in CI on all platforms
```ignore
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

Run example `shader_instancing`

## What went wrong

Nothing is displayed. I was expecting cubes with pretty colors

There are no error in the logs or crash

**Comment by mockersf** [comment]
@pcwalton any idea?

**Comment by pcwalton** [comment]
The problem seems to be that mesh preprocessing isn't getting run anymore. I'm investigating.

**Comment by pcwalton** [comment]
#13144 is a fix. This was kind of subtle. Details in the PR.
