### ISSUE TITLE
The integration of Bevy into iOS/Android apps was broken.

### ISSUE THREAD

**Issue by jinleili** [bevyengine/bevy#13145]
## Bevy version

Bevy 0.13.2 or main branch.

## What you did

Integrate the Bevy engine into existing iOS / Android apps.

## What went wrong

In the [bevy-in-app](https://github.com/jinleili/bevy-in-app/tree/Update-to-Bevy-main-branch), I used the event loop of the iOS Android app to drive the Bevy app. It worked well before Bevy 0.13, but after upgrading to 0.13 and the main branch code, the `breakout` example can hear collision sounds but cannot see any visuals. From the screenshots of Xcode, it can be seen that the command queue did not submit any drawing commands.

## Additional information
<img width="1126" alt="截屏2024-04-30 16 03 13" src="https://github.com/bevyengine/bevy/assets/1001342/68963028-6527-4fe1-8128-850587423e87">

**Comment by jinleili** [comment]
[RUST_LOG Output.md](https://github.com/bevyengine/bevy/files/15162976/RUST_LOG.Output.md)

**Comment by alice-i-cecile** [comment]
Is this fixed using the https://github.com/bevyengine/bevy/pull/12669 branch?

**Comment by jinleili** [comment]
No, it did not fix my use case. I am trying to pinpoint the cause of the issue.

**Comment by jinleili** [comment]
It is a problem with my own program logic. The `apply` fn of `create_window_system_state` was not executed after creating the Window. It was not discovered before version 0.13 because the program ran without any issues.
