### ISSUE TITLE
Implement `Reflect` for `Events` type

### ISSUE THREAD

**Issue by ramon-bernardo** [bevyengine/bevy#13148]
## What problem does this solve or what need does it fill?

I'm trying to **integrate events** with scripts using **reflect**, but the **resource** does not implement reflect by default.

## Additional context

This discussion started on [discord](https://discord.com/channels/691052431525675048/1234673456491003914).

Similar issue https://github.com/bevyengine/bevy/issues/13111.

**Comment by alice-i-cecile** [comment]
Right, so we just need to slap a `Reflect` derive on the `Events` type, correct?
