### ISSUE TITLE
AlphaMode::Mask does not work as intended on StandardMaterial Extension when Depth prepass is enabled on the camera

### ISSUE THREAD

**Issue by naasblod** [bevyengine/bevy#13167]
## Bevy version
0.13.2

## What you did
I tried to create a standard material extension that utilizes `AlphaMode::Mask` to mask discarded fragments

## What went wrong
The discarded fragments was `ClearColor`'ed instead of transparent.
Turns out there might be a bug when `DepthPrepass` is enabled

## Additional information
here are two screenshots with `DepthPrepass` enabled and disabled
<img width="1272" alt="Screenshot 2024-05-02 at 00 12 51" src="https://github.com/bevyengine/bevy/assets/51246882/387bfabf-60c4-4b84-88ef-2a220f181828">
<img width="1263" alt="Screenshot 2024-05-02 at 00 12 58" src="https://github.com/bevyengine/bevy/assets/51246882/28d1c31a-f3dc-4e4c-8490-406f281256d2">

I copied the extended material example and made a small repository that reproduces the issue.

https://github.com/naasblod/alpha_repro

material:
```rust
#[derive(Asset, AsBindGroup, Reflect, Debug, Clone)]
struct MyExtension {}

impl MaterialExtension for MyExtension {
    fn fragment_shader() -> ShaderRef {
        "shaders/extended_material.wgsl".into()
    }

    fn deferred_fragment_shader() -> ShaderRef {
        "shaders/extended_material.wgsl".into()
    }
}
```

shader:
```
@fragment
fn fragment(
    in: VertexOutput,
    @builtin(front_facing) is_front: bool,
) -> FragmentOutput {
    // classic pbr extension stuff
    let distance_from_center = distance(vec2(0.0, 0.0), in.world_position.xy);
    if distance_from_center < 0.5 {
        discard;
    }
    return out;
}
```

**Comment by IceSentry** [comment]
You need to overwrite the `prepass_fragment_shader()` with your own fragment shader if you do the discarding yourself inside the fragment shader.

**Comment by naasblod** [comment]
That makes a lot of sense now that I think about it. 

Thanks a lot!
