### ISSUE TITLE
Result is reflected as a ReflectKind::Value, maybe could be an Enum instead?

### ISSUE THREAD

**Issue by TheNeikos** [bevyengine/bevy#13178]
Currently `Result` is treated as a `Value`. However `Option` is not. I feel that this is inconsistent, and that `Result` should also be encoded as an Enum with two variants. Maybe this could be added?

https://github.com/bevyengine/bevy/blob/961b24deaff15f88d2b5ec41385670576c0f5e19/crates/bevy_reflect/src/impls/std.rs#L99-L102

I tried to find an issue for this, so maybe this has been discussed before and I missed it.

**Comment by alice-i-cecile** [comment]
I agree: this should be consistent between `Option` and `Result`, and doing this as an enum is much more reasonable.

**Comment by TheNeikos** [comment]
I tested it with what I've encountered, and I think the changes in the PR seem sufficient.
