### ISSUE TITLE
Add a `Gray` color trait

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13206]
## What problem does this solve or what need does it fill?

Creating uniformly gray colors is a common task for prototyping and even some finished UIs.

Doing so is currently tedious and doesn't show intent well. Rather than `Srgba::gray(0.9)`, users must type `Srgba::rgb(0.9, 0.9, 0.9)`.

## What solution would you like?

Add an extension trait for the color spaces that support the creation of grey colors, and use that.

## What alternative(s) have you considered?

Using the clearly superior but not style-guide approved Canadian spelling of `Grey`.

## Additional context

Our examples use grays a *ton*: these could be cleaned up as part of the same PR.

**Comment by Earthmark** [comment]
I'll take a whack at this.

**Comment by Earthmark** [comment]
This came up when drafting the PR, but is the goal with this interface to have a specific input value (say `grey(0.5)`), to mean the same color in every color format?

What is the preferred behavior for this feature?

**Comment by NthTensor** [comment]
I don't think gray should mean the same color in every format. Using `mix` between the black and the whitepoint of the space is what I would expect.

Also `Color` probably shouldn't implement this (pointing this out only because we just added a bunch of extra methods to it.

**Comment by bugsweeper** [comment]
This issue should be closed due to [merge commit](https://github.com/bevyengine/bevy/commit/1d29f8e6f6103fab3bc3cbca4390575cf2cb0f4d)
