### ISSUE TITLE
Implement all non-trivial color traits on `Color` type

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13214]
## What problem does this solve or what need does it fill?

If #12212 is closed as won't fix, the developer experience of working with our assorted fields is much worse than it needs to be.

Rather than simply being able to call:

```rust
*color = color.lighten(0.2)
```

they must write

```rust
let hsla = Hsla::from(color);
let light_hsla = hsla.lighten(0.2);
*color = Color::from(light_hsla);
```

## What solution would you like?

If an operation is supported in the supplied color space, call the corresponding method.

If it is not, convert to the most reasonable color space for that operation (usually Oklaba), perform the operation, and then convert back.

## What alternative(s) have you considered?

We could choose a single opinionated perceptual color space for working with all parts of UI code.

This is limiting, and particularly painful since it would force const definitions for palettes to be done directly in that color space. This isn't feasible because of limitations on const float arithmetic and const traits.

**Comment by NthTensor** [comment]
If the color is wrapped in the polymorphic trait, do we need to convert back after the operation? I feel like maybe we can be lazy here. This behavior would have to be called out in the docs, obviously.

**Comment by alice-i-cecile** [comment]
I think converting it back is the least surprising thing to do: if people care about performance they can convert it to the "right" color space on initialization.
