### ISSUE TITLE
Add `bevy-cpal` crate to `bevy-audio`

### ISSUE THREAD

**Issue by tychedelia** [bevyengine/bevy#13226]
## What problem does this solve or what need does it fill?

As far as pure Rust crates go `cpal` is pretty much the defacto standard, comparable to `winit` but for audio. `kira`, our new proposed backend (https://github.com/bevyengine/bevy/issues/11168) has a modular architecture, but only supports `cpal` right now.

While `kira` seems awesome and well suited to games, there are lots of other applications that need more control over lower-level audio details or have use cases that aren't well suited to the game system model provided by `kira`. Presumably some games do too. It would be helpful to provide `cpal` ECS integration for those use cases.

## What solution would you like?

I'd like to propose adding a `bevy-cpal` sub-crate to `bevy-audio` that provides ECS data for devices, etc., as well as other lower level functionality where it makes sense.

This serves two functions:
- To allow configuring `kira` in an ECS forward way.
- Serving other use cases as noted above.

As far as I can tell `kira` already supports configuring the backend from raw `cpal` structs, so these crates should be interoperable. Additional `cpal` configuration options for `kira` could be up-streamed as needed. I'm imagining this as similar to the distinction between `bevy-window` and `bevy-winit`.

## What alternative(s) have you considered?

Only depend directly on Kira, don't expose the backend. This leaves users with other/lower-level needs to fend for themselves.

## Additional context

I am going to ECS-ify `cpal` for `nannou` either way, so this issue mostly serves to track whether `bevy` would like to upstream that work.

**Comment by SolarLiner** [comment]
I'm not too sure about the usefulness of making this a separate crate -- the only useful stuff to expose directly from cpal is the configuration structs, and it would make sense to expose (or abstract) those in `bevy_audio` directly. Other use-cases can be handled within Kira's model, or need to use cpal directly anyway (ie. using audio inputs or additional outputs).

The question is, do we abstract cpal away from the user in an ECS-forward way, should we, and in either case, why should we do it in another crate?

To me, the "`cpal` is the `winit` of audio" is kind of true, but irrelevant, as using `bevy_winit` has immediate benefits (ie. event handling, window management, etc.), but a `bevy_cpal` would give you nothing more than being able to query for avilable configurations. This means to me that this crate would be very light, and not provide any convenience, as audio processing would need to happen off the ECS any way, and so you'd be forced to work directly with `cpal` directly anyway.

For these reasons I'm going to give my thumbs down on this; audio configuration is something to consider for Bevy Audio v2, but I don't think we should spread ourselves thin over several crates, when this could easily be a (small) extra module on the main audio crate anyway. Besides, I don't think this should be part of the initial scope, as it can easily be added later without breaking changes.

**Comment by tychedelia** [comment]
Closing in favor of letting the audio team doing their thing. It sounds like features related to audio input won't be upstreamed in `kira` for a while though. We'll just do our own thing in Nannou.
