### ISSUE TITLE
Examples README.md is missing examples

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1326]
Currently ecs/fixed_time_step appears to be missing, but I haven't done a comprehensive scan for other examples.

The bevymark example could use the word "benchmark" in its description as well, to make sure it's easier to search for.

Verifying this would be an excellent item to put on a release checklist.

**Comment by Marruk-pixel** [comment]
Other examples that are missing in the examples/readme.md:

- 2d/text2d
- asset/custom_asset_io
- ecs/fixed_timestep
- ecs/state
- shader/hot_shader_reloading
- window/scale_factor_override

Maybe we could also list the android and iOS examples like it's done with wasm?

There are also a few examples in the wrong order in the readme.md, for example app/empty.rs comes after app/empty_default.rs. It's not really bad, I'm just a bit of a stickler with too much time.

I'll make a PR for it, I have nothing to do anyway.

**Comment by Marruk-pixel** [comment]
Made a [PR](https://github.com/bevyengine/bevy/pull/1338)

**Comment by Marruk-pixel** [comment]
The PR is merged, could anyone close this issue?
