### ISSUE TITLE
bevy::window::Window should support setting & Querying Focus status

### ISSUE THREAD

**Issue by huhlig** [bevyengine/bevy#1327]
**What problem does this solve or what need does it fill?**

Currently the window status is not easily available without tracking window events in a separate resource. 

**What solution would you like?**

Add a new system to bevy_window to process WindowFocused Events and keep track of which window is focused at any given time. Also create a new Window Command to force a window be brought to the front and focused.

**What alternative(s) have you considered?**

Maintaining a separate Resource and System to process these events. The workaround is not insurmountable and this feature is simply a quality of life improvement.

**Example**

```rust
fn look_around_system(
    mut windows: ResMut<Windows>,
    mouse_button: Res<Input<MouseButton>>,
    mouse_motion: Res<Events<MouseMotion>>,
) {
    let window = windows.get_primary_mut().unwrap();
    if window.is_focused() && mouse_button.pressed(MouseButton::Right) {
        for event in state.reader_motion.iter(&mouse_motion) {
            // Look Around with Camera
        }
    }
}
```

**Comment by nicopap** [comment]
bevy_winit now updates the `Window::focused` component (https://github.com/bevyengine/bevy/blob/09df19bcadb52d2f4dbbc899aef74cafa9091538/crates/bevy_winit/src/lib.rs#L547) So it's trivial to read the focus state of any window without managing mutable internal state.
