### ISSUE TITLE
transmission renders black on some GPU

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#13284]
## Bevy version

main since https://github.com/bevyengine/bevy/pull/13031

## \[Optional\] Relevant system information

```
{ os: "MacOS 14.4.1 ", kernel: "23.4.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
{ name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

Can also reproduce on Windows in CI, but people were not able to reproduce on Windows locally

## What you did

Run example `transmission`

## What went wrong

There seems to be no light transmission at all

<img width="1280" alt="Screenshot 2024-05-08 at 23 35 14" src="https://github.com/bevyengine/bevy/assets/8672791/11ff922c-87bf-42c9-b39e-3d6e9476ecf2">

**Comment by BD103** [comment]
I was able to reproduce this as well. An interesting side-effect is that the candle and large sphere now have a "trail" following them. (Look at the borders of both, compared to the floor.)

https://github.com/bevyengine/bevy/assets/59022059/d2a2b73f-88e5-4f75-af27-2a8fb80833d5

@pcwalton, do you have any ideas what may be happening here?

**Comment by Friz64** [comment]
Also happens here on Linux. 

`AdapterInfo { name: "AMD Radeon RX 7900 GRE (RADV NAVI31)", vendor: 4098, device: 29772, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.0.6-arch1.2", backend: Vulkan }`
