### ISSUE TITLE
Phantom key presses on window focus change (alt+tab, etc)

### ISSUE THREAD

**Issue by hut** [bevyengine/bevy#13299]
## Bevy version

0.13.2

## Relevant system information

ArchLinux with i3wm window manager alongside KDE using X11

## What you did

I press Alt+Tab to change focus to my bevy application.

## What went wrong

I expected this to change focus to my application, and nothing else.

What happend: It caused a key press event of the TAB key and triggered the application action associated with the TAB key.

This happens with any key that is used for focus switching. For example, if I use my window manager's "alt+w" key binding to switch to the workspace of the game, it registers as a key press of the "w" key, which causes my character to unintentionally move forward.

Worse yet, those keys get stuck in a "permanently pressed" state, triggering the actions forever, until I press the respective key once again.

This is driving me crazy as I switch focus back/forth between my bevy application a lot.

## Additional information / Cause

This is caused by bevy erroneously interpreting winit's "synthetic" key presses as real key presses.

If I add a check for [is_synthetic](https://docs.rs/winit/0.30.0/winit/event/enum.WindowEvent.html#variant.KeyboardInput.field.is_synthetic) in [bevy's winit KeyboardInput event handler](https://github.com/bevyengine/bevy/blob/aa80e2d658ed1b84787fd512839a8c84238979ef/crates/bevy_winit/src/lib.rs#L447):

```rust
WindowEvent::KeyboardInput { ref event, is_synthetic, .. } => {
    if !is_synthetic {
        if event.state.is_pressed() {
            if let Some(char) = &event.text {
                let char = char.clone();
                app.send_event(ReceivedCharacter { window, char });
            }
        }
        app.send_event(converters::convert_keyboard_input(event, window));
    }
}
```

then the phantom key press events disappear in my application.

This is likely not the full solution though. While the phantom key **press** events are a clear bug, the phantom key **release** events might serve a purpose and possibly should be exposed. See https://github.com/rust-windowing/winit/issues/3543#issuecomment-1973024673

If you decide to not filter out synthetic keys, please at least expose the fact that they are synthetic to the user so we can filter them out ourselves. This would be suboptimal solution, but better than nothing.

- Relevant winit example: [control_flow](https://github.com/rust-windowing/winit/blob/ab33fb8eda45f9a23587465d787a70a309c67ec4/examples/control_flow.rs) (or any other that responds to key presses)
- Relevant bevy example: [keyboard_input_events](https://github.com/bevyengine/bevy/blob/d9d305dab5b3b7a12a634ea7adb5c5a4c6406ec1/examples/input/keyboard_input_events.rs)
- Relevant winit bug report: https://github.com/rust-windowing/winit/issues/3691
- Relevant winit discussion: https://github.com/rust-windowing/winit/issues/3543

If I can help in any way with solving this, don't hesitate to ask.

Thank you.

P.S. here's an analogous fix in another UI framework: https://github.com/lapce/floem/pull/387

**Comment by hut** [comment]
Another analogous PR in the UI framework egui: https://github.com/emilk/egui/issues/4513

I would happily make a PR to fix this in bevy. Just say the word.

**Comment by alice-i-cecile** [comment]
Seconding the request for a PR :) Just make sure to branch on top of https://github.com/bevyengine/bevy/pull/13678, which is the adopted form of the PR linked above.
