### ISSUE TITLE
Can't compile bevy_dylib

### ISSUE THREAD

**Issue by Fidius-jko** [bevyengine/bevy#13328]
## Bevy version

0.13
## Relevant system information/What you did
![image](https://github.com/bevyengine/bevy/assets/95738553/63eb3bb5-6d84-4ef8-9521-37492a4698dc)

If i compile bevy i see this error

## What went wrong

bevy_dylib doesn't work

**Comment by SkiFire13** [comment]
Did you follow the instructions from https://bevyengine.org/learn/quick-start/getting-started/setup/#enable-fast-compiles-optional? In particular this part:

> *Important!* On Windows you _must_ also enable the [performance optimizations](https://bevyengine.org/learn/quick-start/getting-started/setup/#compile-with-performance-optimizations) or you will get a [`too many exported symbols`](https://github.com/bevyengine/bevy/issues/1110#issuecomment-1312926923) error.

**Comment by Fidius-jko** [comment]
Thanks, this note was not there before.
