### ISSUE TITLE
2d shapes demo Annulus not found

### ISSUE THREAD

**Issue by parallaxisjones** [bevyengine/bevy#13324]
## Bevy version
0.13.1
0.13.2

## Relevant system information

```
2024-05-10T21:00:50.169484Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M3 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-05-10T21:00:50.323233Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-05-10T21:00:50.347980Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 14.1 ", kernel: "23.1.0", cpu: "Apple M3 Pro", core_count: "12", memory: "36.0 GiB" }

cargo 1.78.0 (54d8815d0 2024-03-26)
```

## What you did
I copied the examples from 2d shapes, added bevy as a dependency, and then tried to run `cargo build` and `cargo run`

The following occurred

```sh
error[E0433]: failed to resolve: use of undeclared type `Annulus`
  --> src/main.rs:32:33
   |
32 |         Mesh2dHandle(meshes.add(Annulus::new(25.0, 50.0))),
   |                                 ^^^^^^^ use of undeclared type `Annulus`
```

## What went wrong

To "fix" the issue, to get the example to build I had to remove the Annulus from the example code. I could not find a working version or feature that included the shape. am I missing something? 

## Additional information

```toml
[package]
name = "candlehopper"
version = "0.1.0"
edition = "2021"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

[dependencies]
bevy = "0.13.1"
bevy_pancam = "0.11.0"
kd-tree = "0.5.3"
rand = "0.8.5"
typenum = "1.17.0"
```

**Comment by 13ros27** [comment]
The `Annulus` shape (2d ring) was added since 0.13 [pr](https://github.com/bevyengine/bevy/pull/12706) however the examples on main are updated with all changes. Annulus will be in 0.14, if you want to see examples from previous versions you can go to that branch and check it out there, for example the 0.13 [shapes](https://github.com/bevyengine/bevy/blob/release-0.13.2/examples/2d/2d_shapes.rs).

**Comment by parallaxisjones** [comment]
@13ros27 @alice-i-cecile Thank you for the info! Is there somewhere I can look to find information like that in the future? I'm just getting started with Bevy and was pulling my hair out for a moment trying to figure out what I was doing wrong. It seems a little strange to me to integrate unreleased features into the examples.

My hot take:  that kind of thing is for sure likely to lead to un-needed issues getting created (like this one), and trip up newcomers (me). It's not at all obvious that I should have to go to previous versions to find a stable example to start from (or if it is, please educate me).

Thank you again!

**Comment by alice-i-cecile** [comment]
Unfortunately this is largely a limitation of how Github works. The "default branch that contributors see and make PRs to" does not reflect the latest release. I've experimented elsewhere with a `dev` branch and it resulted in significant other confusion :(

We've attempted to make the warning as prominent as we can (see https://github.com/bevyengine/bevy/tree/main/examples#examples) and have even created our own examples outside of Github at https://bevyengine.org/examples/. On Github, looking at the `latest` tag resolves this as well.

**Comment by parallaxisjones** [comment]
That makes sense -- In the future I'll make sure to look at the latest tag for examples, that's good advice. Thank you for the patience with my liberal application of hot take. 😹

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Alice Cecile ***@***.***>
Sent: Sunday, May 12, 2024 12:12:02 PM
To: bevyengine/bevy ***@***.***>
Cc: Parker Jones ***@***.***>; Author ***@***.***>
Subject: [Ext] Re: [bevyengine/bevy] 2d shapes demo Annulus not found (Issue #13324)


Unfortunately this is largely a limitation of how Github works. The "default branch that contributors see and make PRs to" does not reflect the latest release. I've experimented elsewhere with a dev branch and it resulted in significant other confusion :(

We've attempted to make the warning as prominent as we can (see https://github.com/bevyengine/bevy/tree/main/examples#examples) and have even created our own examples outside of Github at https://bevyengine.org/examples/. On Github, looking at the latest tag resolves this as well.
