### ISSUE TITLE
Depth of field should be enabled on webgpu

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13353]
I believe this should just check for webgl, since webgpu should support depth textures. This currently disables it for webgpu too.

_Originally posted by @IceSentry in https://github.com/bevyengine/bevy/pull/13009#discussion_r1597707303_

**Comment by mnmaita** [comment]
Please correct me if I'm wrong, but this seems to be fixed already by https://github.com/bevyengine/bevy/pull/13374. If so, maybe we could close this issue?
