### ISSUE TITLE
Add the ability to append to a Bundle struct(or tuple)

### ISSUE THREAD

**Issue by RustyStriker** [bevyengine/bevy#1335]
While learning the engine, i stumbled across a thing I believe is slowing down and forcing you to write more code than necessary, you cannot append to a Bundle.

I suggest adding the ability to add something to a Bundle struct, either by putting it in a tuple(which feels like the most intuitive solution) or any other way.

I managed to hack it around using a macro I found on: https://stackoverflow.com/questions/57454887/how-do-i-append-to-a-tuple
and added a function to the SpriteBundle which makes it into a tuple.

The idea is to prevent boiler code and have the ability to not repeat the same variables(like Transform) and use the Bundle types as a base so you could do something like:
 `commands.spawn((Player,SpriteBundle));`
instead of: 
`commands.spawn((Player,Sprite,Mesh,...));`

**Comment by cart** [comment]
You can currently do this, which enables you to add components and bundles to spawned entities in a composable manner:

```rust
commands
    .spawn((Player, SomethingElse))
    .with_bundle(SpriteBundle {...})
    .with(SomeOtherComponent);
```

**Comment by RustyStriker** [comment]
oh, well, I did not know that, and currently finding info is kinda difficult without proper docs and tutorials...

**Comment by alice-i-cecile** [comment]
@RustyStriker, the docs are definitely lacking, but there are some good tutorials and unofficial docs listed on [awesome-bevy](https://github.com/bevyengine/awesome-bevy).

**Comment by alice-i-cecile** [comment]
For anyone else who runs across this, check out #792, which discusses another issue / set of proposals along these same lines.

**Comment by alice-i-cecile** [comment]
Is the functionality described in #1570 adequate for this, or do we need another method?

**Comment by cart** [comment]
I think the new "nested bundles", plus "bundle merging" as described in #792 covers the desired use cases. I'm closing this, but feel free to continue the discussion here if anyone has other ideas.
