### ISSUE TITLE
Gizmos drawing despawned entities

### ISSUE THREAD

**Issue by iiYese** [bevyengine/bevy#13383]
## Bevy version

f91fd32

## Relevant system information

Rust version: `1.78.0`
System info:
```rs
2024-05-15T18:44:46.562458Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux 39 Nobara Linux", kernel: "6.8.7-201.fsync.fc39.x86_64", cpu: "AMD Ryzen 7 7840HS w/ Radeon 780M Graphics", core_count: "8", memory: "30.6 GiB" }
```
Adapter info:  
```rs
AdapterInfo { name: "AMD Radeon RX 6650M (RADV NAVI23)", vendor: 4098, device: 29679, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.2.0-devel", backend: Vulkan }
```

## What you did

Setup a point to be deleted when the mouse button is pressed anywhere, draw the point with a circle gizmo.

## What went wrong

- Expecting gizmo to no longer draw despawned entity 
- Despawned entity is still drawn

```rs
use bevy::prelude::*;

#[derive(Component)]
struct Point(Vec2);

fn setup(mut cmds: Commands) {
    cmds.spawn(Camera2dBundle::default());
    cmds.spawn(Point(Vec2::new(0.0, 150.0)));
}

fn draw(mut gizmos: Gizmos, tree: Query<&Point>) {
    for Point(pos) in tree.iter() {
        gizmos.circle_2d(*pos, 40., Color::WHITE);
    }
}

fn despawn(
    mut cmds: Commands,
    points: Query<Entity, With<Point>>,
    mouse_buttons: Res<ButtonInput<MouseButton>>,
) {
    if mouse_buttons.just_pressed(MouseButton::Left) {
        for entity in points.iter() {
            println!("despawned");
            cmds.entity(entity).despawn();
        }
    }
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(Update, (draw, despawn).chain())
        .run();
}

```

**Comment by alice-i-cecile** [comment]
Does this occur on 0.13?

**Comment by alice-i-cecile** [comment]
This was likely introduced in https://github.com/bevyengine/bevy/pull/10973 by @Aceeri: I would appreciate a before/after test.

**Comment by iiYese** [comment]
> Does this occur on 0.13?
Nope.

**Comment by iiYese** [comment]
Video of behavior on f91fd32 [Screencast_20240515_195205.webm](https://github.com/bevyengine/bevy/assets/83026177/cbbd39c5-1e7c-413b-ac3f-310c5a801932)

**Comment by iiYese** [comment]
Additional behavior of bug: After despawning the entity, resizing or fullscreening the window causes whatever state is invalid to be updated making the gizmo no longer be drawn. 

Video: [Screencast_20240515_195748.webm](https://github.com/bevyengine/bevy/assets/83026177/ca752f55-6487-4a15-a4bb-a097e59b4195)

**Comment by IceSentry** [comment]
I just tested it with the #10973 commit and it works correctly. So it's something else. I'll run a git bisect

**Comment by iiYese** [comment]
Modifying the code to this:
```rs
use bevy::prelude::*;

#[derive(Component)]
struct Point(Vec2);

fn setup(mut cmds: Commands) {
    cmds.spawn(Camera2dBundle::default());
    cmds.spawn(Point(Vec2::new(0.0, 150.0)));
    cmds.spawn(Point(Vec2::new(100.0, 150.0)));
    cmds.spawn(Point(Vec2::new(200.0, 150.0)));
    cmds.spawn(Point(Vec2::new(300.0, 150.0)));
}

fn draw(mut gizmos: Gizmos, tree: Query<&Point>) {
    for Point(pos) in tree.iter() {
        gizmos.circle_2d(*pos, 40., Color::WHITE);
    }
}

fn despawn(
    mut cmds: Commands,
    points: Query<Entity, With<Point>>,
    mouse_buttons: Res<ButtonInput<MouseButton>>,
) {
    if mouse_buttons.just_pressed(MouseButton::Left) {
        for entity in points.iter().take(1) {
            cmds.entity(entity).despawn();
            println!("despawned");
        }
    }
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(Update, (draw, despawn).chain())
        .run();
}

```
Reveals that this happens when you go from exactly 1 gizmo being drawn -> 0 gizmos being drawn.
Video: [Screencast_20240515_203309.webm](https://github.com/bevyengine/bevy/assets/83026177/0b95a3d8-2c6e-4250-84d1-e32b8b54ebe4)

**Comment by iiYese** [comment]
My previous comment wasn't quite correct. Removing the `.take(1)` shows that it's actually when you go from any `N` gizmos being drawn -> exactly 0 gizmos being drawn where `0 < N`.

**Comment by IceSentry** [comment]
I'm currently running a bisect to figure out which commit introduced this bug

**Comment by IceSentry** [comment]
Seems like https://github.com/bevyengine/bevy/pull/12982 is causing the issue. I'm investigating, I'm really not sure how that PR could affect gizmos
