### ISSUE TITLE
slerp functions for directions (Vec2 and Vec3)

### ISSUE THREAD

**Issue by vveisard** [bevyengine/bevy#13407]
## What problem does this solve or what need does it fill?

Linear interpolation is unsuited for transitioning of directions.

## What solution would you like?

I would like a spherical interpolation function (slerp) for Vec2 and Vec3 directions.

## Additional context

This is a common feature in existing game engines:
https://docs.godotengine.org/en/stable/classes/class_vector3.html#class-vector3-method-slerp
https://docs.unity3d.com/ScriptReference/Vector3.Slerp.html

**Comment by rlidwka** [comment]
> Linear interpolation is unsuited for transitioning of directions.

Vec2 and Vec3 are unsuited for representing directions, so current implementation looks just fine to me.

*PS: use angle-as-f32 and Quat instead*

**Comment by bugsweeper** [comment]
[Vec2 and Vec3 is part of glam crate](https://github.com/bevyengine/bevy/blob/11f0a2dcdeb86651fdb6cdaf2c83ffd01df93149/crates/bevy_math/src/common_traits.rs#L1), this problem should be solved there, futhermore there is already [long living issue](https://github.com/bitshifter/glam-rs/issues/377)

**Comment by mweatherley** [comment]
@bugsweeper You're right that the vector types are owned by glam, but on the other hand, we could easily implement `slerp` functions for the `Dir2`/`Dir3` types that we *do* own, and I think those would be quite useful.
