### ISSUE TITLE
Inconsistent resolution/segments naming

### ISSUE THREAD

**Issue by solis-lumine-vorago** [bevyengine/bevy#13412]
`bevy_gizmos` uses the term `segments` to denote the amount of vertices/lines to draw for curved shapes whereas 
`bevy_render` uses the term `resolution` for this purpose and denotes the amount of "cuts" along the height of shapes like `Cylinder`s with `segments`.

This is kind of confusing when working with both gizmos and meshes.
```rust
let cylinder = Cylinder::default();
let mesh = cylinder.mesh().segments(5).build(); // This is a cylinder with 32 vertices per top/bottom cap
gizmos.primitive_3d(cylinder, ...).segments(5); // This is a cylinder with 5 vertices per top/bottom cap
```

I would prefer keeping the naming conventions of `bevy_render` since this would *just* introduce a breaking change (replacing all `segments` methods on gizmos with `resolution`) whereas keeping the naming convention of `bevy_gizmos` would effectively flip the meaning of `segments` and `resolution` in `bevy_render` and introduce a lot of silent bugs for users.

**Comment by mweatherley** [comment]
I agree that this is confusing; I want to also mention that in changing this, we should keep in mind that the mesh builders are also likely to have another parameter for subdivisions in the future (e.g. making a rectangle out of many triangles instead of just two).
