### ISSUE TITLE
Simplest possible Bevy app causing console to be full of errors.

### ISSUE THREAD

**Issue by Astamor** [bevyengine/bevy#13428]
## Bevy version

Bevy 0.13.2, 0.13.1, 0.13.0 - tested on those versions.

## Relevant system information

Cargo version: 1.76.0
AMD 5 3600
Radeon RX6800
Windows 11 Home

## What you did

I just built Bevy and wanted to test if it works so I've added code for the simplest possible app:

use bevy::prelude::*;

```
fn main() {
    App::new()
    .add_plugins(DefaultPlugins)
    .run();
}
```

## What went wrong

The console is full of errors from the start:

> 2024-05-19T11:34:34.457544Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x0000019A307DB1E0:'Internal DXGI CommandList'): Resource state (0x2B0FEBD0: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x0000019A30853A30:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x2B0FEBB0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x2B0FEB90: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
> 2024-05-19T11:34:34.462995Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x0000019A309438C0:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x2B0FEBD0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x0000019A3084EF00:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x2B0FEBB0: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x2B0FEB90: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
> 2024-05-19T11:34:34.464619Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x0000019A307DB1E0:'Internal DXGI CommandList'): Resource state (0x2B0FEBD0: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x0000019A3084EF00:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x2B0FEBB0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x2B0FEB90: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
> 2024-05-19T11:34:34.469943Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x0000019A30860A30:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x2B0FEBD0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x0000019A30852120:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x2B0FEBB0: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x2B0FEB90: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
> 2024-05-19T11:34:34.471598Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x0000019A307DB1E0:'Internal DXGI CommandList'): Resource state (0x2B0FEBD0: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x0000019A30852120:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x2B0FEBB0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x2B0FEB90: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
> 2024-05-19T11:34:34.476881Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x0000019A308D3D60:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x2B0FEBD0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x0000019A30853A30:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x2B0FEBB0: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x2B0FEB90: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
> 2024-05-19T11:34:34.478252Z ERROR log: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x0000019A307DB1E0:'Internal DXGI CommandList'): Resource state (0x2B0FEBD0: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x0000019A30853A30:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x2B0FEBB0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x2B0FEB90: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]

## Additional information

Not sure what to even include here since I didn't even write any code.

**Comment by alice-i-cecile** [comment]
These are graphic driver problems. Have you updated your graphics driver recently?

**Comment by Astamor** [comment]
Yes after running Bevy app and seeing all those errors I updated all my drivers.

**Comment by Astamor** [comment]
Any specific examples ?

**Comment by alice-i-cecile** [comment]
`hello_triangle` for wgpu and `window` for winit should work. Simplest that can test that things are fundamentally working IMO.

**Comment by Astamor** [comment]
hello_triangle console output:

> [2024-05-19T13:06:27Z ERROR wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
>         loader_get_json: Failed to open JSON file C:\Fps monitor\FPS Monitor\tools\fpsmonvk64.json
> [2024-05-19T13:06:27Z ERROR wgpu_hal::vulkan::instance]         objects: (type: INSTANCE, hndl: 0x18503665130, name: ?)
> [2024-05-19T13:06:27Z ERROR wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
>         loader_add_layer_properties: Multiple 'layer' nodes are deprecated starting in file version "1.0.1".  Please use 'layers' : [] array instead in C:\ProgramData\GOG.com\Galaxy\redists\overlay\injected\galaxy_overlay_vklayer_x64.json.
> [2024-05-19T13:06:27Z ERROR wgpu_hal::vulkan::instance]         objects: (type: INSTANCE, hndl: 0x18503665130, name: ?)
> [2024-05-19T13:06:27Z ERROR wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
>         loader_get_json: Failed to open JSON file C:\Program Files (x86)\Overwolf\0.218.0.8\ow-vulkan-overlay64.json
> [2024-05-19T13:06:27Z ERROR wgpu_hal::vulkan::instance]         objects: (type: INSTANCE, hndl: 0x18503665130, name: ?)
> [2024-05-19T13:06:27Z ERROR wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
>         loader_get_json: Failed to open JSON file C:\Program Files (x86)\Overwolf\0.218.0.8\ow-graphics-vulkan64.json
> [2024-05-19T13:06:27Z ERROR wgpu_hal::vulkan::instance]         objects: (type: INSTANCE, hndl: 0x18503665130, name: ?)
> [2024-05-19T13:06:27Z ERROR wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
>         loader_get_json: Failed to open JSON file C:\Program Files\Rockstar Games\Social Club\SocialClubVulkanLayer.json
> [2024-05-19T13:06:27Z ERROR wgpu_hal::vulkan::instance]         objects: (type: INSTANCE, hndl: 0x18503665130, name: ?)
> [2024-05-19T13:06:27Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x00000185113AD3C0:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0xB9354680: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x00000185113A1EE0:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0xB9354660: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0xB9354640: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
> [2024-05-19T13:06:27Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x00000185113394F0:'Internal DXGI CommandList'): Resource state (0xB9354210: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x00000185113A1EE0:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0xB93541F0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0xB93541D0: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]

**Comment by alice-i-cecile** [comment]
Okay, looks like a wgpu bug then :) Can you please open an issue there and link this one?

**Comment by valaphee** [comment]
https://github.com/gfx-rs/wgpu/issues/4247 Actually pretty easy fixable, it's because when initializing wgpu, it registers and VEH and it keeps the DX12 backend open, even though its not used.

Theoretically, either removing the dx12 feature, or setting WGPU_BACKEND=vulkan gets rid of this error

**Comment by GitGhillie** [comment]
Were you using a release build (e.g. `cargo run --release`) when you were checking performance? And make sure to follow this when building a debug build: https://bevyengine.org/learn/quick-start/getting-started/setup/#compile-with-performance-optimizations. With those it should be no problem to use that crate.

**Comment by Astamor** [comment]
I've checked both debug and release, I've went through all bevy docs including the link you provided. Like I said in previous post, performance issue was solved. Turned out it was world_inspector_egui crate, after removing it bevy handles maps 1000x1000 tiles with 100fps. Also I've noticed Bevy is using some kind of 2d "culling" by default. The only error remaining is fullscreen mode crashing the app

**Comment by alice-i-cecile** [comment]
>  The only error remaining is fullscreen mode crashing the app

Can you open up a new issue for this with details on the OS and hardware used? This is a nice clear problem that would be good to track :) The rest of this is largely resolved: I'm going to close this out now.
