### ISSUE TITLE
False positives for Added/Changed on first system run

### ISSUE THREAD

**Issue by SpecificProtagonist** [bevyengine/bevy#13426]
## Bevy version

2aed777

## What you did

I spawned an entity with a component:
```rust
#[derive(Component)]
struct Foo;
let mut world = World::new();
world.spawn(Foo);
```
Then ran a system that checks whether said component has been added since the last time it ran:
```rust
let sys = world.register_system(|query: Query<(), Added<Foo>>| assert!(query.is_empty()));
loop {
    world.run_system(sys).unwrap();
}
```

## What went wrong

From the documentation of `Added`:
> A filter on a component that only retains results added after the system last ran.

(and similarly for `Changed`: "[…] or mutably dereferenced after the system last ran.")

This never happened, yet the entity did not get filtered out the first time the system ran.

## Additional information

`SystemMeta::last_run` can not represent the case that the system hasn't been run yet and therefore falsely [gets initialized to 0](https://github.com/bevyengine/bevy/blob/2aed777435d26c357ed71cdb8c7b858de35e582e/crates/bevy_ecs/src/system/function_system.rs#L45).

**Comment by alice-i-cecile** [comment]
Definitely a bug. I wonder if we should be storing an `Option<NonZero<u64>>` or the equivalent inside of our ticks to resolve cases like this correctly.

**Comment by alice-i-cecile** [comment]
Oh, I see the problem here. I think the docs are wrong. The actual behavior (and the one that will generally be desired) is "detect added/changed components exactly once". Is there are reason why you want to exclude entities that were added before the system was run?
