### ISSUE TITLE
Trait fn returning `impl Fn()` cannot be used as a system when called from generic type

### ISSUE THREAD

**Issue by benfrankel** [bevyengine/bevy#13436]
## Bevy version

0.13.2

## What you did

```rust
trait Foo {
    fn foo() -> impl Fn() {
        || {}
    }
}

enum ConcreteFoo {}

impl Foo for ConcreteFoo {}

fn frobnicate<GenericFoo: Foo>(app: &mut App) {
    app.add_systems(Update, <ConcreteFoo as Foo>::foo()); // Is a system
    app.add_systems(Update, <GenericFoo as Foo>::foo()); // Is not a system
}
```

## What went wrong

The second `foo()` is not considered a system, so it doesn't compile.

## Additional information

This looks like a Rust bug, but I have no idea what the source of the bug is (something to do with RPITIT?), and this affects my usage of Bevy, so I'm creating an issue here for now.

**Comment by benfrankel** [comment]
Workaround:
```rust
trait Foo {
    fn foo() -> BoxedSystem {
        Box::new(IntoSystem::into_system(|| {}))
    }
}
```

**Comment by benfrankel** [comment]
This bug applies to run conditions as well, but `BoxedCondition` is not a proper workaround because it doesn't `impl Condition`, so you have to use `.run_if_dyn` instead of `.run_if`, but `.run_if_dyn` doesn't return `Self` so it's a real pain to use.

**Comment by chescock** [comment]
I think you need `fn foo() -> impl Fn() + Sync + Send + 'static {`.  

`System` requires those trait bounds, and for `ConcreteFoo` the compiler can see the actual type and validate them.  But for `GenericFoo` it has to protect against something like

```rust
struct EvilFoo;
impl Foo for EvilFoo {
    fn foo() -> impl Fn() {
        let x = Cell::new(0);
        // This is not `Sync` and so cannot be a `System`.
        move || {
            x.set(0);
        }
    }
}
```

**Comment by benfrankel** [comment]
Interesting. That works. I guess this isn't a bug in Rust or Bevy, but it is surprising.
