### ISSUE TITLE
Auto exposure breaks when object is too dark

### ISSUE THREAD

**Issue by GitGhillie** [bevyengine/bevy#13446]
## Bevy version

Tested on main commit 2aed777

## Relevant system information

Windows 10

```
AdapterInfo { name: "AMD Radeon RX 7900 XT", vendor: 4098, device: 29772, device_type: DiscreteGpu, driver: "", driver_info: "", backend: Dx12 }
```

## What you did

I have an object with just a base texture and a roughness map, exported from Blender to a gltf and then loaded in Bevy.
I'm using the AutoExposurePlugin with pretty much default settings.

## What went wrong

If I place the camera near a dark corner of the mesh, facing the dark corner, the image becomes darker instead of brighter.
You can see what I mean in this video: https://discord.com/channels/691052431525675048/743663924229963868/1242088583108624444

## Additional information

Removing the roughness map in Blender and setting the roughness to a fixed value 'fixes' the issue.
You can try it out in this fairly minimal reproduction: https://github.com/GitGhillie/bevy_repro/tree/auto-exposure

The camera will spawn roughly here:
![image](https://github.com/bevyengine/bevy/assets/23659539/2724d359-dc6a-4635-a509-ef85bcee1e65)
Move the camera into the dark corner where the arrow is and you should be able to reproduce the effect.

**Comment by alice-i-cecile** [comment]
FYI @Kurble, in case you have any ideas or are interested in putting together a fix :)

**Comment by Kurble** [comment]
Increasing the `AutoExposureSettings::range` to `-16.0..=16.0` will also fix the issue for this scene. It can be quite tricky to get auto exposure right, we might need some diagnostic tools for it, such as a widget to render out the histogram. 

When all samples are out of range (too dark), the shader now targets 0.0 (no correction) as exposure, I think it should maybe target `range.start` instead so I'll put up a fix for that.
