### ISSUE TITLE
Add a builder API to `LoadContext`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13445]
Future Work: The `LoadContext` _really_ needs a builder API:

- `load`
- `load_untyped`
- `load_with_settings`
- `load_direct`
- `load_direct_untyped`
- `load_direct_with_reader`
- `load_direct_with_settings`
- `load_direct_untyped_with_reader`
- `load_direct_with_reader_and_settings`

I feel like calling `context.loader().direct().typed::<A>().with_settings(...).load(...)` is much friendlier to code completion, and would allow for documentation on each of the individual options in the API.

_Originally posted by @bushrat011899 in https://github.com/bevyengine/bevy/pull/13415#discussion_r1606121632_

**Comment by ricky26** [comment]
I have a partial (second) implementation of this, so I'm happy to take this one.
