### ISSUE TITLE
Allow access to Arc<CustomAttributes>.

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#13457]
## What problem does this solve or what need does it fill?

The new bevy_reflect custom attributes feature is great, but I need to be able to pass the custom attributes to child widgets. This would be a lot easier if I could clone the `Arc`, but that is currently private.

## What solution would you like?

Add a method which allows access to the `Arc` containing the custom attributes instead of a reference to them.

## What alternative(s) have you considered?

The only alternative I can think of is cloning, which would be very inefficient.

**Comment by viridia** [comment]
OK looks like we can use `&'static CustomAttributes`, so this probably isn't needed.

**Comment by MrGVSV** [comment]
Closed due to the fact that `CustomAttributes` can be accessed as a `&'static CustomAttributes` (since `TypeInfo` is almost always a static reference). This should help with passing it around without having to worry about lifetimes.
