### ISSUE TITLE
Panic if changing browser zoom in WASM with an overridden scale factor

### ISSUE THREAD

**Issue by pietrosophya** [bevyengine/bevy#13487]
## Bevy version

Main and 0.13.

## What you did

Given:
* a WindowPlugin with a custom resolution and an overridden scale factor
* a WASM app
* the browser zoom is changed (CTRL + +/-)

the app crashes.

## What went wrong

The problem is that the `bevy_winit` plugin reacts to the `WindowEvent::ScaleFactorChanged`, that's received from `winit` holding a `borrow_mut` on the `ResizeScaleHandle`, and immediately [requesting](https://github.com/bevyengine/bevy/blob/main/crates/bevy_winit/src/lib.rs#L663) a new inner size.

Happens also on the [winit 0.30 PR](https://github.com/bevyengine/bevy/pull/13366), for the same reason.

**Comment by daxpedda** [comment]
This was fixed in https://github.com/rust-windowing/winit/pull/3727 which landed in [Winit v0.30.2](https://crates.io/crates/winit/0.30.2).

**Comment by pietrosophya** [comment]
I confirm this is fixed!
