### ISSUE TITLE
Ui border is 1 pixel too large, or is getting aliased.

### ISSUE THREAD

**Issue by ImDanTheDev** [bevyengine/bevy#13503]
## Bevy version

Main, commit 0ec634763ec378193eeea0cc38909e7d7251b272

## Relevant system information
- Windows 11
- Rust Nightly, 1.80.0 (8387315ab 2024-05-14)
- Also tested on Rust Stable, 1.78.0 (9b00956e5 2024-04-29)
```ignore
AdapterInfo { name: "NVIDIA GeForce RTX 2080 Ti", vendor: 4318, device: 7684, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "555.85", backend: Vulkan }
```

## What you did

Create a NodeBundle with a 1 pixel wide border on all sides.

## What went wrong

The border appears to be 1 pixel too large on all sides, or is getting aliased, causing it to blend into the node's background. I would expect a 1 pixel border to be exactly 1 pixel on the screen(see the 0.13.2 screenshot below).

[This gist](https://gist.github.com/ImDanTheDev/117be26a909bcc16a49b6247836eb4ed) reproduces the issue on commit 0ec6347.
[And this gist](https://gist.github.com/ImDanTheDev/887e0cc67a66f869e05534f1a7baf1e8) does not show the issue on 0.13.2.

### Possible Fix
I'm not at all fluent with shader code, but while poking around in [ui.wgsl](https://github.com/bevyengine/bevy/blob/0ec634763ec378193eeea0cc38909e7d7251b272/crates/bevy_ui/src/render/ui.wgsl#L161), I found that on line 161, changing `external_distance < internal_distance` to `external_distance > internal_distance` fixes the issue. After doing that, the border appears exactly the same as the 0.13.2 screenshot below. I have no idea what the implications are for making that change, so it may very well break other things.

True scale:
![true_scale](https://github.com/bevyengine/bevy/assets/2303421/144ba4bc-2757-4888-aced-bcfe50757817)

Scaled up to highlight issue:
![scaled_up](https://github.com/bevyengine/bevy/assets/2303421/bf31ba1b-1d38-4c23-b537-92760df3bfe5)

Expected(using bevy 0.13.2):
![image](https://github.com/bevyengine/bevy/assets/2303421/c61d9bef-5e25-46a1-90f7-c21a37c4530d)

**Comment by mockersf** [comment]
could you try before and after https://github.com/bevyengine/bevy/pull/12725?

commit before: debcf3fb1d0c8e0b259a3ea852eca7f702b7c21d
commit with that PR: 8da4fcb6167ced2aaa89cb92c4420d3be7eb0591

**Comment by ImDanTheDev** [comment]
The issue still exists on both of those commits, with debcf3f looking slightly different.
![image](https://github.com/bevyengine/bevy/assets/2303421/21764922-5b74-4ff6-8eb4-4dab55492b0c)

**Comment by ImDanTheDev** [comment]
#12500, commit e7a31d0 has this issue.
The commit before that PR, 7c7d1e8, does not.

**Comment by hymm** [comment]
looking into this rn. I think there's a bug with how the sdfs are calculated. Visualizing external_distance(left) and internal_distance(right).

![image](https://github.com/bevyengine/bevy/assets/2180432/3f8c6cb9-836d-48e7-b053-995dd896041b)

We see a darker red around the external_distance. It being darker is saying that the outside pixel is half in and half out of the border, but it should be bright red saying that the outside pixel is fully part of the border.

**Comment by hymm** [comment]
getting close. left is the border distance and right is the fwidth(border_distance). The border_distance looks correct, but the fwidth(border_distance) looks weird, which is making artifacts in the final rendering.

![image](https://github.com/bevyengine/bevy/assets/2180432/537e37e4-bde4-40be-9da9-055346d228a2)

**Comment by hymm** [comment]
looks like something weird is going on on the diagonals of the sdf

![image](https://github.com/bevyengine/bevy/assets/2180432/dfb07707-8b68-4ae7-bc59-5aa3da390412)

**Comment by hymm** [comment]
I think I got it. Will do a little more testing tomorrow and then open a pr.

**Comment by ImDanTheDev** [comment]
Thanks for working on this issue! That looks much better, but there is still 1px of the border bleeding into the middle on some sides of some of those squares. It is visible only on the top right black/white square, the 2 green/orange, and the 2 purple/yellow squares. Is this an artifact caused by the screenshot?

**Comment by hymm** [comment]
Not an artifact. Here's a blown up screenshot.

![image](https://github.com/bevyengine/bevy/assets/2180432/ce205cbe-3275-4a73-87c1-5ff4b32dcc4f)

For this I changed border_distance to be
```wgsl
let border_distance = select(external_distance, -internal_distance, internal_distance <= 0);
```
Which is more correct than it was before, but probably still a little wrong. I'll see if I can come up with a better formula.

**Comment by hymm** [comment]
Darn above formula is still pretty wrong. The red area should be darkening again in the below screenshot.
![image](https://github.com/bevyengine/bevy/assets/2180432/a3740411-a636-415d-96fa-b95f44f39f71)

**Comment by hymm** [comment]
Using
```wgsl
    let border_distance = select(max(external_distance, -internal_distance), -internal_distance, internal_distance <= 0);
```
got me 
![image](https://github.com/bevyengine/bevy/assets/2180432/ce4d5faf-bfbc-4c64-9423-ee264a245b8b)
just some single pixel artifacts left in the corners.
