### ISSUE TITLE
Audio getting progressively worse. (By default)

### ISSUE THREAD

**Issue by redstonerti** [bevyengine/bevy#13508]
## Bevy version

0.13.2

## \[Optional\] Relevant system information

Windows 11 x64, Ryzen 7 4700U with Radeon Graphics

## What you did

I searched up how to play a sound in bevy, and used this code from a bevy example to play some mp3 files for my pong clone.
https://github.com/bevyengine/bevy/blob/main/examples/audio/audio.rs
`commands.spawn(AudioBundle {
        source: asset_server.load("sounds/Windless Slopes.ogg"),
        ..default()
    });`

## What went wrong

Every time a sound plays, the audio quality gets worse. At 100 sounds played, it is unrecognisable. I have a video here to show it more clearly:

https://github.com/bevyengine/bevy/assets/48157961/30bd4af3-168e-498f-8897-c0fa1de946fc

**Comment by hymm** [comment]
I believe the audio entities by default don't get despawned. You can change the behavior to `PlaybackMode::Despawn` on the audio bundle https://docs.rs/bevy/latest/bevy/audio/enum.PlaybackMode.html

**Comment by redstonerti** [comment]
I have already tried that. Here is the full code:
https://github.com/redstonerti/pong/

**Comment by redstonerti** [comment]
Nevermind, I hadn't set it in every instance that I spawned an AudioBundle. May I ask why it isn't Despawn by default?

**Comment by mweatherley** [comment]
> Nevermind, I hadn't set it in every instance that I spawned an AudioBundle. May I ask why it isn't Despawn by default?

I think it's not the default because it creates very undesirable behavior when an `AudioBundle` is attached to a normal entity. (However, the default right now is also just very bad.)

**Comment by redstonerti** [comment]
It's possible that spawning audio as a component is not a good idea. Wouldn't it be better if it was a resource that could be accessed from anywhere, like Commands or something? 

Maybe something like this?

```
AudioManager.play(source_file,AudioSettings{volume,pitch,audio_type::Spatial(x,y,z)});
```

**Comment by hymm** [comment]
How would you do spatial audio with a resource?

**Comment by redstonerti** [comment]
> How would you do spatial audio with a resource?

I have no idea and no experience. I was just typing what I was thinking. Forget the spatial audio, I just thought it could be simpler to use a resource to play sounds

**Comment by rparrett** [comment]
See also https://github.com/bevyengine/bevy/issues/12359

**Comment by alice-i-cecile** [comment]
#12359 is much clearer to track: I'm going to close this out in favor of that issue.
