### ISSUE TITLE
Lightmaps break when deferred rendering is enabled

### ISSUE THREAD

**Issue by GitGhillie** [bevyengine/bevy#13552]
## Bevy version

Latest main

## Relevant system information

Windows 10

```
AdapterInfo { name: "AMD Radeon RX 7900 XT", vendor: 4098, device: 29772, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "24.5.1 (LLPC)", backend: Vulkan }
```

## What you did

- Go to the lightmaps example
- Add  `.insert_resource(Msaa::Off)` and `.insert_resource(DefaultOpaqueRendererMethod::deferred())` to the app.
- Add `.insert(DeferredPrepass)` or `.insert(ScreenSpaceReflectionsBundle::default())` to the camera.

## What went wrong

It looks like this:
![image](https://github.com/bevyengine/bevy/assets/23659539/573b706f-22d0-4f01-82d9-2156ef3a907d)

Other lights seem to work as normal.

**Comment by JMS55** [comment]
I can't edit the issue title, but @alice-i-cecile it's an issue with deferred, not SSR.

**Comment by alice-i-cecile** [comment]
Is this a regression since 0.13?

**Comment by GitGhillie** [comment]
No, looks like 0.13 has the same issue

**Comment by alice-i-cecile** [comment]
Thanks for checking. Unfortunate bug, but not blocking for the release of 0.14 then.
