### ISSUE TITLE
Panic when `bevy_pbr` feature is not included

### ISSUE THREAD

**Issue by jgayfer** [bevyengine/bevy#13571]
## Overview

When the `bevy_pbr` feature is omitted (as in the below example), the following error occurs:

```
thread 'main' panicked at /Users/jgayfer/.cargo/git/checkouts/bevy-f7ffde730c324c74/9d74e16/crates/bevy_ecs/src/system/system_param.rs:619:17:
Resource requested by bevy_core_pipeline::core_3d::extract_core_3d_camera_phases does not exist: bevy_render::render_phase::ViewBinnedRenderPhases<bevy_core_pipeline::core_3d::Opaque3d>
```

The error does not occur if `bevy_pbr` is included.

Possibly related to https://github.com/bevyengine/bevy/issues/13175, but I've opened a separate issue as the errors are not the same.

## Bevy version

[4065098586519a1764a462c02a63f299114c35c9](https://github.com/bevyengine/bevy/commit/4065098586519a1764a462c02a63f299114c35c9) (main)

## Relevant system information

```
AdapterInfo { name: "Apple M1 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## Minimal example

```
# Cargo.toml
[package]
name = "pbr_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = [
    "bevy_winit"
] }
```

```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run();
}
```

**Comment by knutsoned** [comment]
Can confirm this issue also happened for me on a project, and adding bevy_pbr fixed it

**Comment by aevyrie** [comment]
Ran into this when updating `bevy_framepace`.

**Comment by jgayfer** [comment]
Closed by https://github.com/bevyengine/bevy/pull/14020
