### ISSUE TITLE
Docs for `NextState` are outdated

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#13577]
## How can Bevy's documentation be improved?

https://dev-docs.bevyengine.org/bevy/prelude/enum.NextState.html

The docs say

> To queue a transition, just set the contained value to Some(next_state).

But `NextState` is no longer a struct containing an enum.

Relevant PR: https://github.com/bevyengine/bevy/pull/11426

I am not sure if the text about transitions below is correct -- I didn't follow these changes.

**Comment by alice-i-cecile** [comment]
I'll take this.
