### ISSUE TITLE
`Gizmos::arc_2d` uses clockwise angles for some reason

### ISSUE THREAD

**Issue by mweatherley** [bevyengine/bevy#13614]
## Bevy version

Current development branch.

## What you did / what went wrong

A wonderful PR author ran into this weird mismatch while writing gizmo code: the `arc_2d` method expects a clockwise angle, while the angle supplied for the `primitives_Nd` method is counterclockwise. As far as I can tell, this may be *literally* the only place in the entire codebase that uses clockwise angles, which seems needlessly confusing. The method could just use counter-clockwise angles like everything else.

**Comment by alice-i-cecile** [comment]
Encountered in #13610.

**Comment by Olle-Lukowski** [comment]
I can open a PR for this, and maybe merge both PR's at the same time so #13610 doesn't need to be changed?
