### ISSUE TITLE
CI: Make a check which ensures standalone crates actually are standalone

### ISSUE THREAD

**Issue by torsteingrindvik** [bevyengine/bevy#13611]
## What problem does this solve or what need does it fill?

A few crates:

- bevy_reflect
- bevy_math
- bevy_color
- (possiblye bevy_transform: https://github.com/bevyengine/bevy/pull/13533)

Are intended to be usable in isolation (or close to, i.e. they don't bring the whole Bevy dep tree with them).
This should have a CI check that ensures this is true.
For example if a crate garuantees that by turning off default features means it can be used standalone, this should be checked.

## What solution would you like?

An automated CI check.

## What alternative(s) have you considered?

Maintainers must bear the mental overhead of keeping these kinds of guaruantees, which is not good.

**Comment by alice-i-cecile** [comment]
The best way to do this might be to somehow examine the output of `cargo tree` 🤔 The `check-bans` tool may be a good source of inspiration.

**Comment by torsteingrindvik** [comment]
I pondered this a bit when working on https://github.com/bevyengine/bevy/pull/13533 which intends to allow `default-features = false` to mean only `bevy_transform` (and `bevy_math`) is pulled into your deps.

I think I found a possible way to ensure this.
`cargo tree` can list features, but it doesn't have structured output e.g. json.
But it has lots of other interesting (and _stable_) CLI flags.

Here is an example:

```sh
cargo tree --no-default-features
bevy_transform v0.14.0-dev (/home/togr/repos/bevy/crates/bevy_transform)
├── bevy_math v0.14.0-dev (/home/togr/repos/bevy/crates/bevy_math)
│   ├── approx v0.5.1
│   │   └── num-traits v0.2.18
│   │       [build-dependencies]
│   │       └── autocfg v1.2.0
│   ├── glam v0.27.0
│   │   ├── approx v0.5.1 (*)
│   │   └── bytemuck v1.15.0
│   ├── smallvec v1.13.2
│   └── thiserror v1.0.58
│       └── thiserror-impl v1.0.58 (proc-macro)
│           ├── proc-macro2 v1.0.79
│           │   └── unicode-ident v1.0.12
│           ├── quote v1.0.35
│           │   └── proc-macro2 v1.0.79 (*)
│           └── syn v2.0.57
│               ├── proc-macro2 v1.0.79 (*)
│               ├── quote v1.0.35 (*)
│               └── unicode-ident v1.0.12
└── thiserror v1.0.58 (*)
[dev-dependencies]
├── approx v0.5.1 (*)
├── bevy_math v0.14.0-dev (/home/togr/repos/bevy/crates/bevy_math) (*)
└── bevy_tasks v0.14.0-dev (/home/togr/repos/bevy/crates/bevy_tasks)
    ├── async-executor v1.11.0
    │   ├── async-task v4.7.0
    │   ├── concurrent-queue v2.4.0
    │   │   └── crossbeam-utils v0.8.19
    │   ├── fastrand v2.0.2
    │   ├── futures-lite v2.3.0
    │   │   ├── fastrand v2.0.2
    │   │   ├── futures-core v0.3.30
    │   │   ├── futures-io v0.3.30
    │   │   ├── parking v2.2.0
    │   │   └── pin-project-lite v0.2.14
    │   └── slab v0.4.9
    │       [build-dependencies]
    │       └── autocfg v1.2.0
    └── futures-lite v2.3.0 (*)
```

we can get rid of the dev deps like so:

```sh
cargo tree --edges normal,build --no-default-features 
bevy_transform v0.14.0-dev (/home/togr/repos/bevy/crates/bevy_transform)
├── bevy_math v0.14.0-dev (/home/togr/repos/bevy/crates/bevy_math)
│   ├── glam v0.27.0
│   │   └── bytemuck v1.15.0
│   ├── smallvec v1.13.2
│   └── thiserror v1.0.58
│       └── thiserror-impl v1.0.58 (proc-macro)
│           ├── proc-macro2 v1.0.79
│           │   └── unicode-ident v1.0.12
│           ├── quote v1.0.35
│           │   └── proc-macro2 v1.0.79 (*)
│           └── syn v2.0.57
│               ├── proc-macro2 v1.0.79 (*)
│               ├── quote v1.0.35 (*)
│               └── unicode-ident v1.0.12
└── thiserror v1.0.58 (*)
```

we can make it less noisy:

```sh
cargo tree --edges normal,build --no-default-features --format {lib}
bevy_transform
├── bevy_math
│   ├── glam
│   │   └── bytemuck
│   ├── smallvec
│   └── thiserror
│       └── thiserror_impl
│           ├── proc_macro2
│           │   └── unicode_ident
│           ├── quote
│           │   └── proc_macro2 (*)
│           └── syn
│               ├── proc_macro2 (*)
│               ├── quote (*)
│               └── unicode_ident
└── thiserror (*)
```

no prefix:

```sh
cargo tree --edges normal,build --no-default-features --format {lib} --prefix none
bevy_transform
bevy_math
glam
bytemuck
smallvec
thiserror
thiserror_impl
proc_macro2
unicode_ident
quote
proc_macro2 (*)
syn
proc_macro2 (*)
quote (*)
unicode_ident
thiserror (*)
```

some unix piping:

```sh
cargo tree --edges normal,build --no-default-features --format {lib} --prefix none | sort | uniq
bevy_math
bevy_transform
bytemuck
glam
proc_macro2
proc_macro2 (*)
quote
quote (*)
smallvec
syn
thiserror
thiserror (*)
thiserror_impl
unicode_ident
```

then we can lastly do a grep for example of stuff we _don't_ want:

```sh
cargo tree --edges normal,build --no-default-features --format {lib} --prefix none | sort | uniq | grep -E "(bevy_ecs|bevy_reflect)"
```

**Comment by alice-i-cecile** [comment]
This seems like a good fit for root-level integration tests in our `tests` folder.

**Comment by BD103** [comment]
Define "standalone." Does it mean:

1. Can compile by itself without raising any errors.
2. Does not pull in any other Bevy dependencies.
3. Does not pull in any other dependencies at all, even non-Bevy ones.
4. Can optionally be turned into a standalone crate with one of the above criteria, e.g. with feature flags.

**Comment by alice-i-cecile** [comment]
For most of the crates listed, 2. For `bevy_transform`, 4.

**Comment by mockersf** [comment]
I don't think this should be part of Bevy CI. It would add complexity to an already not simple setup, without a lot of value for Bevy itself

**Comment by alice-i-cecile** [comment]
I'm going to defer to Francois here. I've spent a while thinking about the problems this saves us from that won't be readily caught in review, and I don't think it's many.

By contrast, there's quite a bit of complexity involved in checking this.
