### ISSUE TITLE
Add a compass direction enums

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13647]
> My main comment is that I’d want to be able to get a compass direction from a given rotation/direction. The defines are useful but saying “What compass ‘pie slice’ is this rotation/direction in” is more useful IMO. 

_Originally posted by @BobG1983 in https://github.com/bevyengine/bevy/issues/13636#issuecomment-2143994914_
            
I've made enums like this before: they're very useful for working with 2D directions, especially when mapping control stick inputs into 4 or 8 directional motion.

## Design proposal

Create two enums:

1. `CompassQuadrant`: north/south/east/west
2.`CompassOctant:` also include northeast and so on

These enums correspond to a centered wedge of the unit circle (i.e. they assign the area on both sides of the axis to the same wedge).

There are two key APIs for each of these types: converting both to and from `Dir2`. This should be done using two `From` impls.

Other than that, just derive the standard traits: Debug, PartialEq, Eq, Clone, Copy, Hash, Reflect and so on.

**Comment by bugsweeper** [comment]
@alice-i-cecile Looks like we can close this issue as resolved by #13653
