### ISSUE TITLE
Move all asset paths in examples to constants at the top of the example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13645]
## How can Bevy's documentation be improved?

Users frequently forget to grab the required assets when trying to build the examples locally.

https://github.com/bevyengine/bevy/pull/13624 had a nice approach to this, by moving the example paths into constants at the top of the file with a comment. We should do this universally.

**Comment by alice-i-cecile** [comment]
It's not clear how we would best do that. Would you want us to make a folder for each?

**Comment by Wuketuke** [comment]
i am currently working on doing that. while at it, im also checking if the files exist

**Comment by mockersf** [comment]
I would prefer to not move the assets to the examples directory

**Comment by alice-i-cecile** [comment]
I think that moving the assets to the example directory will make it much harder for folks writing new examples to reuse assets across examples. It will also make them much harder to browse.

**Comment by Wuketuke** [comment]
i have moved every path i could find into a constant on top of the file, and committed it to [my fork](https://github.com/Wuketuke/bevy/tree/issue_13645). I have not implemented any testing yet, since this is really tedious work. i think im taking a break from this issue

**Comment by mockersf** [comment]
done for shaders in #13824

**Comment by cart** [comment]
I don't think we should embrace this pattern. I've left some thoughts here: https://github.com/bevyengine/bevy/pull/14056#pullrequestreview-2146523977
