### ISSUE TITLE
Panic "the given key does not support hashing" should indicate the type.

### ISSUE THREAD

**Issue by brandon-reinhart** [bevyengine/bevy#13646]
The reflection panic "the given key does not support hashing" raised by insert_boxed needs to indicate the type that it is trying to use as a key. Otherwise, it is difficult to track down the source of the panic.

**Comment by Cioraz** [comment]
Hi, Im new to rust and bevy, in this particular issue I managed to figure the we need the debug msg to be more descriptive. However I cant seem what exactly keeps track of the type. Any advice?
