### ISSUE TITLE
the render of AmbientLight is not display correctly

### ISSUE THREAD

**Issue by Tom-Jim** [bevyengine/bevy#13665]
i have code like this that be copied at https://github.com/marcelchampagne/bevy-basics.git 
![Screenshot 2024-06-04 105905](https://github.com/bevyengine/bevy/assets/83345710/50a929be-57a7-42df-9274-c9c68cdd5cce)
but when it is running the display is not as my mind,the spaceship is't brighter than before but darkily
![Screenshot 2024-06-04 105921](https://github.com/bevyengine/bevy/assets/83345710/1e9949a4-2358-43dc-a26b-eba94879586d)
i want to know whether my code problem or just bevy bug?

**Comment by GitGhillie** [comment]
Try increasing the `brightness` into the hundreds or even thousands. Looks like you followed a tutorial from an older Bevy version where exposure worked differently, hence why you need bigger values now for it to show up

**Comment by Tom-Jim** [comment]
> Try increasing the `brightness` into the hundreds or even thousands. Looks like you followed a tutorial from an older Bevy version where exposure worked differently, hence why you need bigger values now for it to show up

thanks，it's work,i stop to try just up it to 10

**Comment by bugsweeper** [comment]
Both [lld](https://docs.rs/bevy/latest/bevy/pbr/struct.AmbientLight.html) and [new](https://dev-docs.bevyengine.org/bevy/pbr/struct.AmbientLight.html) AmbientLight docs contain example with value 100.0. Do you want to propose some better description of AmbientLight behaviour?

**Comment by GitGhillie** [comment]
> Both [old](https://docs.rs/bevy/latest/bevy/pbr/struct.AmbientLight.html) and [new](https://dev-docs.bevyengine.org/bevy/pbr/struct.AmbientLight.html) AmbientLight docs contain example with value 100.0. Do you want to propose some better way to describe of AmbientLight behaviour?

There's not much we can do here, people run into this issue because they follow this tutorial with Bevy 0.13:
https://www.youtube.com/watch?v=R-u1EY9fOJQ

Looks like someone did open a PR to update the code to 0.13 but there hasn't been a response from the author yet: https://github.com/marcelchampagne/bevy-basics/pull/2

**Comment by Tom-Jim** [comment]
> Both [old](https://docs.rs/bevy/latest/bevy/pbr/struct.AmbientLight.html) and [new](https://dev-docs.bevyengine.org/bevy/pbr/struct.AmbientLight.html) AmbientLight docs contain example with value 100.0. Do you want to propose some better way to describe of AmbientLight behaviour?

no,i just be mistaked by tutorials,i thought the brightness is 0-1 scale ,and it is my mistake not to see the api document carefully,i usually search at google directly

**Comment by bugsweeper** [comment]
@Tom-Jim Are you abble to close this issue?

**Comment by Tom-Jim** [comment]
> @Tom-Jim Are you abble to close this issue?

ok

**Comment by Tom-Jim** [comment]
fixed
