### ISSUE TITLE
Add an illustration to the compass direction docs

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13664]
> These docs would benefit from an illustration.

_Originally posted by @NthTensor in https://github.com/bevyengine/bevy/issues/13636#issuecomment-2146434371_

Maybe ASCII art?

**Comment by alice-i-cecile** [comment]
We should replicate these on the `CompassQuadrant` and `CompassOctant` types, or maybe just include them there.

**Comment by mgi388** [comment]
You want something more fancy than these?

```
         N (North)
         |
         |
         |
W (West) +-----+ E (East)
         |
         |
         |
         S (South)
```

```
         N (North)
         |
    NW   |   NE
         |
W (West) +-----+ E (East)
         |
    SW   |   SE
         |
         S (South)
```

**Comment by Wuketuke** [comment]
@mgi388 keep in mind that you can get fancier formatting if you position your compass between two triple engrave symbols (`)

**Comment by mgi388** [comment]
@Wuketuke wdym? In my comment above the suggestion is already inside backticks / code fences.
