### ISSUE TITLE
closing the main window change UI in the second window

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#13687]
## Bevy version

main

## What you did

* launch the example `multiple_windows`
* take note of the text in the second window
* close the first window
* check the text in the second window

https://github.com/bevyengine/bevy/assets/8672791/0364fb06-44e0-4083-9534-ca7e3db0c503

## What went wrong

text in the second window changed size and in content

**Comment by rparrett** [comment]
Presumably, an incorrect scale factor is being applied. I can only reproduce at `scale_factor != 1.0`.

**Comment by mockersf** [comment]
text rendering wasn't updated for #10559  so it's still using the primary window, and getting to default value if it can't find one
