### ISSUE TITLE
In `0.14.0-rc.2`, minimal app with `bevy_core_pipeline` crashes without `ktx2`, `zstd`, and `bevy_pbr`

### ISSUE THREAD

**Issue by benfrankel** [bevyengine/bevy#13728]
## Bevy version

0.14.0-rc.2

## What you did

Note: The following setup runs fine in bevy 0.13.

In `Cargo.toml`:

```toml
[dependencies]
bevy = { version = "0.14.0-rc.2", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_winit",
    "x11",
] }
```

In `main.rs`:

```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run();
}
```

## What went wrong

It runs but immediately crashes with error message:

> Failed to load SMAA area LUT: UnsupportedTextureFormat("Ktx2")

After enabling the `ktx2` feature, we get a new crash:

> Failed to load SMAA area LUT: SuperDecompressionError("Unsupported supercompression scheme: Zstandard")

After enabling the `zstd` feature, we get a new crash:

> Resource requested by bevy_core_pipeline::core_3d::extract_core_3d_camera_phases does not exist: bevy_render::render_phase::ViewBinnedRenderPhases<bevy_core_pipeline::core_3d::Opaque3d>

After enabling the `bevy_pbr` feature, there is no crash.

**Comment by benfrankel** [comment]
Some type of "minimal bevy app compiles and doesn't crash" CI test could help prevent this type of issue in the future.

**Comment by jgayfer** [comment]
Related to https://github.com/bevyengine/bevy/issues/13571, though at the time I created that ticket it was only `bevy_pbr` that needed to be included.

**Comment by ChristopherBiscardi** [comment]
This happened in the bevy_ecs_tilemap upgrade I'm working on when running the examples -- https://github.com/StarArawn/bevy_ecs_tilemap/pull/537

**Comment by bugsweeper** [comment]
> at the time I created that ticket it was only `bevy_pbr` that needed to be included.

That because you enabled only `bevy_winit` feature, but in this task `bevy_core_pipeline` is also enabled, which [adds SmaaPlugin](https://github.com/bevyengine/bevy/blob/ecdd1624f302c5f71aaed95b0984cbbecf8880b7/crates/bevy_core_pipeline/src/lib.rs#L101C22-L101C23), which [loads ktx2 textures](https://github.com/bevyengine/bevy/blob/ecdd1624f302c5f71aaed95b0984cbbecf8880b7/crates/bevy_core_pipeline/src/smaa/mod.rs#L293)

**Comment by bugsweeper** [comment]
The question is: Do we want Smaa to be optional, or bevy_core_pipeline require ktx2?

**Comment by aevyrie** [comment]
Ideally the SMAA LUTs should be behind a feature flag. I should be able to turn off default features and be able to run with a minimal feature set.

**Comment by knutsoned** [comment]
Using the published v0.14.0-rc.3 crate, I am seeing this issue if bevy_core_pipeline and multi_threaded are the only features enabled. Minimal reproduction: https://github.com/knutsoned/rc3-winit-example

**Comment by djeedai** [comment]
Confirming I'm also hitting this in a trivial empty integration test for Hanabi.

**Comment by rparrett** [comment]
This is an issue for several of my apps -- I don't want to compile `bevy_pbr` for a 2d game.

**Comment by Multirious** [comment]
I've read Alice post about this issue being hard to test. Have anyone considered https://github.com/frewsxcv/cargo-all-features ? I used it in my crate. all the time in my GitHub workflow.
