### ISSUE TITLE
Rendering Stutter/Ghosting on Vulkan Renderer

### ISSUE THREAD

**Issue by igorlp** [bevyengine/bevy#13742]
## System information
```ignore
`SystemInfo { os: "Windows 11 Home", kernel: "22635", cpu: "AMD Ryzen 7 5800X3D 8-Core Processor", core_count: "8", memory: "31.9 GiB" }`
`AdapterInfo { name: "NVIDIA GeForce RTX 4060 Ti", vendor: 4318, device: 10243, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "552.44", backend: Vulkan }`
```

## What you did
- Spawned a mesh. 
- When W/A/S/D is pressed, a `transform.translation` will occur on the mesh based on input. 
- `transform.translation` is affected by `time.delta_seconds()`
 
Here is a snippet of the movement code:
```
fn handle_movement(
    mut query: Query<(&mut Velocity, &mut Transform, &Acceleration)>,
    time: Res<Time>,
) {
    for (mut velocity, mut transform, acceleration) in query.iter_mut() {
        velocity.x = (velocity.x + acceleration.x)
            .min(velocity.max)
            .max(velocity.max * -1.);
        velocity.y = (velocity.y + acceleration.y)
            .min(velocity.max)
            .max(velocity.max * -1.);

        velocity.x *= 1. / (1. + (time.delta_seconds() * 25.));
        velocity.y *= 1. / (1. + (time.delta_seconds() * 25.));

        transform.translation.x += velocity.x * time.delta_seconds();
        transform.translation.y += velocity.y * time.delta_seconds();
    }
}
```

## What went wrong
When Wgpu backend is set to Backends::VULKAN, there is significant jittering and ghosting around the mesh as it's translated. This does not occur when the Wgpu backend is set to Backends::DX12. 

## Additional information

- Have attached two videos that show the difference between the two backends. There's no change in the code other than the Wgpu backend setting
- Example repo can be found [here](https://gitlab.com/igorlp/bevy-game). Change the backend on setup.rs.

DX12: https://github.com/bevyengine/bevy/assets/12466943/9df4e660-b27d-4abe-ba5d-7675385d6dab
VULKAN: https://github.com/bevyengine/bevy/assets/12466943/b76bb36f-9127-4bec-a4df-2972a8b915d5

**Comment by alice-i-cecile** [comment]
I expect this is a bug upstream in `wgpu`. Two questions:

1. Can you reproduce this on https://github.com/bevyengine/bevy/pull/13186?
2. Can you reproduce this in `wgpu`?

**Comment by igorlp** [comment]
Looks like it works fine on #13186 for both Backends::DX12 and Backends::VULKAN, so seems like it will be fixed once wgpu is updated in Bevy
