### ISSUE TITLE
Shader Error in Array Texture Example: Invalid Field Accessor clip_from_view

### ISSUE THREAD

**Issue by altunenes** [bevyengine/bevy#13751]
## Bevy version
bevy = "0.13.2"

## System information

win 11, rtx 3060m, ryzen 7 6800h, rust 1.78

## What you did

I followed the official Bevy example for creating a texture for use with a texture_2d_array<f32> shader uniform variable.

https://github.com/bevyengine/bevy/blob/latest/examples/shader/array_texture.rs

shader:
https://github.com/bevyengine/bevy/blob/3bfc42766621d12749c09eca3bfd9911dc0dc3f5/assets/shaders/array_texture.wgsl

## What went wrong
I encountered an error in the shader code:
```rust

error: invalid field accessor `clip_from_view`
   ┌─ shaders/array_texture.wgsl:39:100
   │
39 │     pbr_input.is_orthographic = bevy_pbr::mesh_view_bindings::view.clip_from_view[3].w == 1.0;
   │                                                                                                    ^^^^^^^^^^^^^^ invalid accessor
   │
   = invalid field accessor `clip_from_view`
 ```

## My Solution

To resolve this, I changed the line:

https://github.com/bevyengine/bevy/blob/3bfc42766621d12749c09eca3bfd9911dc0dc3f5/assets/shaders/array_texture.wgsl#L39

with this:
```wgsl
pbr_input.is_orthographic = view.projection[3][3] == 1.0;
 ```

After making this change, the example worked as expected.

**Comment by JMS55** [comment]
You need to look at the 0.13.2 tag, not the main branch which contains unreleased changes

https://github.com/bevyengine/bevy/blob/release-0.13.2/assets/shaders/array_texture.wgsl
