### ISSUE TITLE
Bevy drawing behavior changes based on the window-size.

### ISSUE THREAD

**Issue by visualcode-t** [bevyengine/bevy#1379]
**Bevy version**

"0.4.0" - Crates.io

**Operating system & version**

Windows 10 -19042.782

**What you did**

If you draw images next to each-other with Bevy, it seems that if the window size is odd, they are not placed as expected. As an example, I created an image that is 10 x 10 pixels. I then set them next to each-other.

<details>
<summary>See Code</summary>

```
use bevy::{prelude::*, transform};

fn main() {
    App::build()
        .add_resource(ClearColor(Color::BLACK))
        .add_resource(WindowDescriptor{
            width: 799.0,
            height: 600.0,
            title: String::from("Draw"),
            ..Default::default()
        })
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup.system())
        .run();
}

fn draw_thing(commands: &mut Commands, asset_server: &Res<AssetServer>,texture_atlases: &mut ResMut<Assets<TextureAtlas>>,pos_x: f32, pos_y: f32,index: u32) -> Option<Entity> {
    let texture_handle = asset_server.load("images/draw.png");
    let texture_atlas = TextureAtlas::from_grid(texture_handle,Vec2::new(10.0,10.0),10,1);
    let texture_atlas_handle = texture_atlases.add(texture_atlas);
    Some(commands
        .spawn(SpriteSheetBundle{
            texture_atlas: texture_atlas_handle,
            sprite: TextureAtlasSprite {
                color: Color::WHITE,
                index: index,
            },
            transform: Transform {
                translation: Vec3::new(pos_x,pos_y,0.0),
                ..Default::default()
            },
            ..Default::default()
        }).current_entity().unwrap())
}

fn setup(
    commands: &mut Commands,
    asset_server: Res<AssetServer>,
    mut texture_atlases: ResMut<Assets<TextureAtlas>>,
) {
    commands.spawn(Camera2dBundle::default());
    for i in 1..20 {
        draw_thing(commands,&asset_server,&mut texture_atlases,i as f32 *10 as f32,0.0, 0);
    }
}
```

</details>

**What you expected to happen**

I expect that the images will be lined up perfectly next to each other despite window size.

**What actually happened**

What happens is depending on the size of the window, the display is different.
![Bevy](https://user-images.githubusercontent.com/70065256/106544256-142c2a00-64bc-11eb-9cfb-017ee006f2fe.png)

**Comment by DJMcNab** [comment]
Here is a reproduction of draw.png:

![draw](https://user-images.githubusercontent.com/36049421/106585081-dae8ce00-653e-11eb-9474-00d9b6ee23bd.png)

I haven't tested the reproduction code, but it does appear that it should draw the correct thing 

@visualcode-t what is your monitor scale factor? This seems likely to be a result of window scaling

**Comment by visualcode-t** [comment]
Here is a sample image for `draw.png`
![draw](https://user-images.githubusercontent.com/70065256/106616552-88011d80-6522-11eb-90fe-7ad14ae6d42e.png)

Originally, I was running this at 2560x1440. I am not currently at that location, at my current location I am running 1920x1080. But, I was able to make a sample image (seen above) and use the source previously posted to reproduce the issue. Both systems are using the same operating system.

**Comment by visualcode-t** [comment]
I've tested this on more PCs (all Windows). None of them have had correct results for this example.

**Comment by visualcode-t** [comment]
Despite having previously tested this on multiple computers, I am no longer able to duplicate this issue using the code and image samples in this post. I am marking this closed.
