### ISSUE TITLE
Scene spawning doesn't take transform into account anymore

### ISSUE THREAD

**Issue by pcwalton** [bevyengine/bevy#13796]
STR:

* `cargo run --example deferred_rendering`

The flight helmet shouldn't be in the center.

This is a regression in the last few days.

**Comment by pcwalton** [comment]
This doesn't even work if you make a parent object and put the scene inside it.

**Comment by rparrett** [comment]
Bisected to #13714

**Comment by pcwalton** [comment]
This breaks `deferred_rendering` among a lot of other test cases probably.

**Comment by alice-i-cecile** [comment]
I'm in favor of a revert PR if we can't fix this readily.
