### ISSUE TITLE
breakout example has no ball

### ISSUE THREAD

**Issue by lazybean** [bevyengine/bevy#138]
`cargo run --example breakout` on windows 10, there isn't any ball.

![image](https://user-images.githubusercontent.com/529333/90013260-38dddc80-dca5-11ea-9ae8-ae22bf9c0298.png)

**Comment by ftk** [comment]
It seems like the ball is falling through the floor because delta time step is too high

**Comment by lazybean** [comment]
Oh yes  you are right!
If I decrease the ball's velocity it then stays in the rectangle!

**Comment by reidbhuntley** [comment]
I've updated #132 to clamp the timestep in the ball movement system to prevent this, thanks @ftk !

**Comment by alexanderuv** [comment]
can this be closed then? since the fix has been merged to master

**Comment by cart** [comment]
@lazybean can you confirm that you dont hit this on the master branch?

**Comment by lazybean** [comment]
Yes thanks a lot!
