### ISSUE TITLE
MeshletMesh material textures not rendering sometimes

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#13811]
Bevy `d659a1f7d506c5c6eba9dfe2a6e878a8c72ecef6`.

I used a MeshletMeshMaterialBundle with a normal_map_texture loaded from disk via the asset server. Sometimes, it would render without the normal map. Sometimes it would render _with_ the normal map. It was inconsistent across runs, but not between frames. 

Regular MeshMaterialBundles do not seem to have this problem.

Presumably this applies to all kinds of textures, not just normal maps.

**Comment by alice-i-cecile** [comment]
I've removed this from the milestone as it's a) not a regression b) has no fix ready to review and c) a bug with an explicitly experimental feature.
