### ISSUE TITLE
Remake PRs targeting 0.14 branch

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13825]
Some PRs can't be trivially cherrypicked by @mockersf to the 0.14 release due to merge conflicts. These are:

- [ ] #13808
- [ ] #10839 (not yet merged)

To fix each of these, redo their changes, branched off of https://github.com/bevyengine/bevy/tree/release-0.14.0 and then make a PR on the `bevyengine/bevy` repo targeting the release branch.

**Comment by alice-i-cecile** [comment]
This issue mostly exists to make sure we don't forget to do this, but help here would be lovely.

**Comment by mnmaita** [comment]
I suppose this can be closed now.

**Comment by alice-i-cecile** [comment]
Yep! Thanks again for tackling this: it really helped Francois and I move the release forward.
