### ISSUE TITLE
EventReader:par_read doesn’t mark events as read

### ISSUE THREAD

**Issue by BobG1983** [bevyengine/bevy#13821]
## Bevy version

Main (probably 0.14)

## \[Optional\] Relevant system

bevy_ecs

## What you did

Rewrote the test for par_read so it ran twice and checked the output after the second run to make sure that no events remained. 

## What went wrong

par_read saw the same events on the second system run. 

Check the recent failed builds for my peekable and mutator pull requests for examples of the failing tests.

**Comment by mockersf** [comment]
fixed in #13836
