### ISSUE TITLE
SSAO does not work with orthographic projections

### ISSUE THREAD

**Issue by aevyrie** [bevyengine/bevy#13838]
## Bevy version

0.13

## What you did

Use an orthographic camera.

## What went wrong

SSAO stopped working properly.

## Additional information

This is visible in the `bevy_editor_cam` `cad` example. Switch between projections to see it.

https://github.com/bevyengine/bevy/assets/2632925/054d3ee7-d5ed-4a84-9e6a-1f5f4688c1e5

**Comment by JMS55** [comment]
It's due to this https://github.com/bevyengine/bevy/blob/2cffd14923c9e217dc98881af6c8926fe4dc65ea/crates/bevy_pbr/src/ssao/gtao.wgsl#L76-L81. 

We should probably switch this to use the view transformation code.

**Comment by Affinator** [comment]
> It's due to this
> 
> https://github.com/bevyengine/bevy/blob/2cffd14923c9e217dc98881af6c8926fe4dc65ea/crates/bevy_pbr/src/ssao/gtao.wgsl#L76-L81
> .
> 
> We should probably switch this to use the view transformation code.

Could you point me in the right direction, why this code is not working? Is t.w equal to zero?
I am just starting to learn the purpose of the different transformation matrices, but I would be willing to invest some time to learn and fix this. 

(*all glory to orthographic projection*)

**Comment by Soulghost** [comment]
In this example, the zfar is too big, which results in very low accurary of the depth map in orthographic projection.

**Comment by Affinator** [comment]
Hi,
I am testing the current main branch and with careful tuning of the near and far plane SSAO is working just fine (without TAA). It is just really hard to find suitable values given more dynamic scenes. 

For this example please try: 
```
projection: Projection::Orthographic(OrthographicProjection {
    near: 0.0,
    far: 10.0,
    viewport_origin: Vec2::new(0.5, 0.5),
    scaling_mode: ScalingMode::WindowSize(150.0),
    area: Rect::new(-1.0, -1.0, 1.0, 1.0),
}),
```

When the near and far planes are not adjusted to the shown scene, the precision of the depth texture is too low (as mentioned by @Soulghost) I am currently thinking about adjusting the near and far plane based on the AABBs of the currently visible objects/meshes, which should solve this problem in cases where clipping isn't desired.

**Comment by Affinator** [comment]
I checked this also against VBAO (https://github.com/bevyengine/bevy/pull/13454). SSAO is working when the near and far plane are chosen with care. This can be closed. 

But some documentation for this footgun would not hurt.

**Comment by aevyrie** [comment]
I'm not seeing this working still. I have a near `0.0` and far `1.23`, automatically  computed from the scene `Aabb`s, and SSAO is still broken.

**Comment by Affinator** [comment]
This is what it looks like on tag release-0.14.2 with ortho (near: 0.0, far: 10.0):
![grafik](https://github.com/user-attachments/assets/9ba8c71b-bf81-48f8-b1a0-cbcbe58bb48a)

Of course it is a bit noisy due to lack of TAA, but that's another issue.

**Comment by Affinator** [comment]
And now in bevy_editor_cam with ortho (near: 0.0, far: 2.0):
![grafik](https://github.com/user-attachments/assets/bd0a76a6-66aa-4550-af23-6d9f72715bdc)

But it is only working when zoomed in enough.
Perspective:
![grafik](https://github.com/user-attachments/assets/3b2ba304-fe15-4642-8c5a-b7d4028a8fba)

Orthographic:
![grafik](https://github.com/user-attachments/assets/2ac098fa-e67e-4a49-a286-a88b6372e15c)

Also there are clear steps in the calculated occlusion. 
I can confirm that it works "enough" for my private project, but this issue is still relevant.

**Comment by aevyrie** [comment]
It seems like maybe SSAO is breaking when the ortho projection scale factor changes?

**Comment by IceSentry** [comment]
Can you try your last video with the VBAO PR? It might handle the transition a bit better.

**Comment by aevyrie** [comment]
Not really, bevy main has broken a number of things since 0.14, there is a branch on the editor cam but it isn't working fully yet.
