### ISSUE TITLE
Links to schedules and conditions are broken in various state docs

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#13845]
## How can Bevy's documentation be improved?

https://dev-docs.bevyengine.org/bevy/prelude/trait.AppExtStates.html#tymethod.init_state

Links to `OnEnter`, `in_state`, etc are broken.

**Comment by kettei-sproutty** [comment]
Hi, I would like to take this issue, should i include [`insertState`](https://dev-docs.bevyengine.org/bevy/prelude/trait.AppExtStates.html#tymethod.insert_state) that have the same broken links too?

**Comment by rparrett** [comment]
Yes, please!
