### ISSUE TITLE
Add MainScheduleOrder::insert_before()

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#13866]
## What problem does this solve or what need does it fill?

Complements MainScheduleOrder::insert_after().

## Additional context

I'd like to add a new schedule before First, as it's something I really want to run before _any_ other system.

**Comment by alice-i-cecile** [comment]
While we're here, we should add equivalents for the startup and FixedMain schedule orders.

**Comment by kettei-sproutty** [comment]
Hi, I will take this if nobody is working on it :)

**Comment by JMS55** [comment]
Please do!
