### ISSUE TITLE
[Bug?] State is not updated when manually updating App

### ISSUE THREAD

**Issue by not-elm** [bevyengine/bevy#13874]
## Bevy version

v0.14.0-rc.2

## What you did

My library has a similar to the following test code, but it failed after I updated the bevy version from v0.13.2 to v0.14.0-rc2.

```rust
use bevy::prelude::*;

fn main() {
    let mut app = App::new();
    app.add_plugins(MinimalPlugins);
    app.init_resource::<StateChanged>();
    app.init_state::<GameState>();
    app.add_systems(Update, wait_state);
    app.update();
    assert!(!app.world().resource::<StateChanged>().0);
    app.insert_state(GameState::InGame);
    app.update();
    // panic!! 
    assert!(app.world().resource::<StateChanged>().0);
}

#[derive(Resource, Default, Debug)]
struct StateChanged(bool);

#[derive(Eq, PartialEq, Debug, Default, Copy, Clone, Hash, States)]
enum GameState {
    #[default]
    Title,
    InGame,
}

fn wait_state(
    mut changed: ResMut<StateChanged>,
    state: Res<State<GameState>>,
) {
    if matches!(state.get(), GameState::InGame) {
        changed.0 = true;
    }
}
```

## What went wrong

Console output: 
```shell
thread 'main' panicked at src\main.rs:19:5:
assertion failed: app.world().resource::<StateChanged>().0
```

**Comment by alice-i-cecile** [comment]
FYI @lee-orr @benfrankel @MiniaczQ

**Comment by lee-orr** [comment]
@alice-i-cecile - I believe the source of this is App::new() doesn't set up the main schedule, so `StateTransition` isn't added in.

Do you think a good solution here is documenting the need to set up that schedule when you aren't building on the main schedule, or ensuring it's run by default even if no meta-schedule has been added?

**Comment by alice-i-cecile** [comment]
I agree with your diagnosis of the problem. IMO we should warn about this during `.init_state` / `insert_state`. Users won't read the docs for this sort of weirdness, but they *will* check for warnings.

**Comment by MiniaczQ** [comment]
> I believe the source of this is App::new() doesn't set up the main schedule, so `StateTransition` isn't added in.

Not quite, `StateTransition` is no longer part of the default main schedule, it's added through `StatesPlugin`

Can the state installation methods check for plugin existence?

**Comment by alice-i-cecile** [comment]
[is_plugin_added](https://dev-docs.bevyengine.org/bevy/app/struct.App.html#method.is_plugin_added) is the method you want :)

**Comment by MiniaczQ** [comment]
Great, I'll have a fix in 10 min

**Comment by MiniaczQ** [comment]
For the author, you want to add `StatesPlugin` manually when using `MinimalPlugins`
