### ISSUE TITLE
Loading a .glb or .gltf with a jpeg throws an error

### ISSUE THREAD

**Issue by marijnz0r** [bevyengine/bevy#1391]
**Bevy version**

0.4.0

**Operating system & version**

Ubuntu 20.10

**What you did**

Create a new project and load a .glb or .gltf file through the asset server:

`let terrain_handle: Handle<Mesh> =
        asset_server.load("some_terrain.glb");`

**What you expected to happen**

The asset will be loaded and no errors will be thrown.

**What actually happened**

An error was thrown:

```thread 'IO Task Pool (0)' panicked at 'called `Result::unwrap()` on an `Err` value: AssetLoaderError(The image format Jpeg is not supported)', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.4.0/src/asset_server.rs:298:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Additional information**

I'm just starting game development and Rust. Let me know if I can improve my bug report or code.

**Comment by jamadazi** [comment]
JPEG support is an optional cargo feature (only PNG and HDR are enabled by default). There are also features for DDS, TGA, BMP.

It is a similar thing with audio formats. MP3 is enabled by default, but others such as FLAC, WAV, and OGG Vorbis can be enabled with cargo features.

Try adding the `jpeg` cargo feature. If it works, then we can close this issue.

**Comment by marijnz0r** [comment]
Thanks for your answer. Enabling the `jpeg` feature for the bevy dependency worked.

Example:
```
[dependencies]
bevy = { version = "0.4", features=["jpeg"] }
```

Is this mentioned in the documentation somewhere? Would it be nice to add this? I can help if needed.

**Comment by h4df13ld** [comment]
thanks for this post. This solution worked for me too !

> Thanks for your answer. Enabling the `jpeg` feature for the bevy dependency worked.
> 
> Example:
> 
> ```
> [dependencies]
> bevy = { version = "0.4", features=["jpeg"] }
> ```
> 
> Is this mentioned in the documentation somewhere? Would it be nice to add this? I can help if needed.

Thanks for this comment. This fixed my issue too.
