### ISSUE TITLE
Add resources for accumulated mouse motion and mouse scroll

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13915]
## What problem does this solve or what need does it fill?

When working with inputs from mice for gameplay purposes, it is very common to want an aggregate view of "how much did the mouse move this frame?" or "how much did the player scroll?".

This is primarily used for controlling camera positions, such as when zooming or panning a map, or when working with 

## What solution would you like?

Add two resources, each of which stores a simple `Vec2`: `AccumulatedMouseMotion` and `AccumulatedMouseScroll`. Reset them to zero at the start of each frame in a system, then sum the corresponding events.

## What alternative(s) have you considered?

Users can sum these events themselves, and replicate the code listed above. This is a waste of time / confusing to them, and it's quite possible to get the timing of this wrong, leading to laggy or buggy input data.

It's also quite plausible that users (like me, historically) end up doing this computation multiple times across different parts of their app, leading to wasteful and inconsistent results.

## Additional context

I needed this functionality in `leafwing-input-manager`, and decided to solve it the right way in https://github.com/Leafwing-Studios/leafwing-input-manager/pull/543. The code associated with the `AccumulatorPlugin` can be ripped out and ported quite directly to `bevy_input`.

`MouseScroll` is a bit of a wrinkle: there's two possible units that could be sent. Ultimately, for the context of "gameplay data about what the player's mouse did", I don't think we care, as long as the same amount of physical motion results in about the same amount of accumulation. We may want to apply some sort of scaling factor to convert, but I'm not familiar enough with this behavior to know how to test it to check.

**Comment by BackupMiles** [comment]
Hi! I am interested in working on this issue, may it be assigned to me?

**Comment by bugsweeper** [comment]
@BackupMiles , usualy nobody assigns tasks in bevy, just write that you are working on it, and nobody else will wast their time. Just don't forget to write message if you change your mind

**Comment by BackupMiles** [comment]
Thank you for clarifying @bugsweeper, then I will gladly work on this issue 👍

**Comment by BackupMiles** [comment]
Just a quick question: where would be a good place to ask more info about the project/code?

**Comment by alice-i-cecile** [comment]
Either in this issue or in #input-dev :) Just ping me.
