### ISSUE TITLE
Custom material importing function error

### ISSUE THREAD

**Issue by hasbonahad** [bevyengine/bevy#13922]
## Bevy version
bevy version 0.13.2

## What you did
I tried to make a custom material in bevy with trait Material.
When I tried to import wgsl function from another file bevy_pbr::mesh_functions It crashed
error: no definition in scope for identifier: 'bevy_pbr::mesh_functions::get_world_from_local'.

it only happens when I try to call it.

## My code
wgsl 

#import bevy_pbr::mesh_functions::{
    get_world_from_local, 
    mesh_position_local_to_clip
}

struct VertexIn{
    @builtin(instance_index) instance_index: u32,
    @location(0) position: vec3<f32>,
    @location(1) uv_index: vec3<f32>,
}
struct VertexOutput{ 
    @builtin(position) world_position: vec4<f32>
}

@vertex 
fn vertex(in: VertexIn) -> VertexOutput{
    // var foo = get_world_from_local(); this function can not be called
    var out: VertexOutput;
    out.world_position = vec4<f32>(in.position, 1.0);
    return out;
}

@fragment
fn fragment(in: VertexOutput) -> @location(0) vec4<f32> {
    return vec4<f32>(1.0,1.0,1.0,1.0);
}

  const ATTRIBUTE_UV_INDEX: MeshVertexAttribute =
      MeshVertexAttribute::new("uv_index", 988540917, VertexFormat::Float32x3);
  
  impl Material for CustomMaterial {
  
      fn vertex_shader() -> ShaderRef {
          "shader\\main.wgsl".into()
      }
  
      fn fragment_shader() -> ShaderRef {
          "shader\\main.wgsl".into()
      }
  
      
      fn specialize(
          _pipeline: &MaterialPipeline<Self>,
          descriptor: &mut RenderPipelineDescriptor,
          layout: &MeshVertexBufferLayout,
          _key: MaterialPipelineKey<Self>,
      ) -> Result<(), SpecializedMeshPipelineError> {
          let vertex_layout = layout.get_layout(&[
              Mesh::ATTRIBUTE_POSITION.at_shader_location(0),
              ATTRIBUTE_UV_INDEX.at_shader_location(1)
          ])?;
          descriptor.vertex.buffers = vec![vertex_layout];
          Ok(())
      }
  
  }

**Comment by bugsweeper** [comment]
I think you should include code example for better description, there is similar [issue](https://github.com/bevyengine/bevy/issues/13680#issuecomment-2149291502), I hope it helps

**Comment by JMS55** [comment]
You're looking at bevy main, which has new code not yet released. Make sure to look at the bevy 0.13.2 branch.
