### ISSUE TITLE
Add `EntityCommands::observe_self` for easier self-targeting observers

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#13936]
## What problem does this solve or what need does it fill?

Attaching an observer to an entity is a commonplace and intuitive pattern.
This is effectively a callback, and is particularly nice because the behavior will be cleaned up when the entity is despawned.

However, the existing API for this is pretty icky.

```rust
// Observers are stored as components on entities,
// and can be set up to watch specific entities.
fn spawn_player(mut commands: Commands){
    let player_entity = commands
        // Setting up some ordinary components
        .spawn((Player, Life(10), Defense(2))).id();

    // Now, we're adding some callback-style behavior using observers,
    // watching the entity itself.
    // By attaching the observer to the entity it's watching, we ensure that it gets cleaned up.
    commands.insert(Observer::new(respond_to_damage_taken).with_entity(player_entity));
    commands.insert(Observer::new(respond_to_life_lost).with_entity(player_entity));
}
```

## What solution would you like?

```rust
// Observers are stored as components on entities,
// and can be set up to watch specific entities.
fn spawn_player(mut commands: Commands){
    commands
        // Setting up some ordinary components
        .spawn((Player, Life(10), Defense(2)))
        .observe_self(respond_to_damage_taken)
        .observe_self(respond_to_life_lost);
}
```

## What alternative(s) have you considered?

Simply adding the `Observer` component can't be done in the same method call, since there's no clear

## Additional context

We should consider renaming `EntityCommands::observe` to the more explicit `observe_global`.

We can also add `observe_targets` while we're at it.

**Comment by QueenOfSquiggles** [comment]
I'm still learning the intricacies of rust, but I wager I can at least make a simple implementation of this functionality. At the very least I'm going to give it my best :heart:

**Comment by alice-i-cecile** [comment]
Awesome, thanks! Let us know if you need any help.

**Comment by QueenOfSquiggles** [comment]
From a failure to compile on the examples, I found this chunk of code in the Observers example 

(`examples/ecs/observers.rs:93-98`)
```rust
    commands
        .spawn(Mine::random(&mut rng))
        // Observers can watch for events targeting a specific entity.
        // This will create a new observer that runs whenever the Explode event
        // is triggered for this spawned entity.
        .observe(explode_mine);
```

This seems to imply the desired functionality has already been merged? Unless I'm misunderstanding, which is definitely possible.

**Comment by alice-i-cecile** [comment]
Oh! I must have misinterpreted the API: it was changing last minute. Are you able to verify and then update the example at https://github.com/bevyengine/bevy-website/blob/main/release-content/0.14/release-notes/10756_hooks_and_observers.md for me @QueenOfSquiggles?

**Comment by QueenOfSquiggles** [comment]
Sure thing @alice-i-cecile . I'll get that started in a bit here

**Comment by QueenOfSquiggles** [comment]
Just for tracing the PR for the website example is [here](https://github.com/bevyengine/bevy-website/pull/1451)
