### ISSUE TITLE
Add i64 and u64 implementations for bevy_render::render_resource::ShaderType

### ISSUE THREAD

**Issue by Phil-hacker** [bevyengine/bevy#13938]
## Bevy version

0.14-rc.3

## Bug

`i64` and `u64` should implement `bevy_render::render_resource::ShaderType` because wgpu added support for them in wgpu 0.20

**Comment by Phil-hacker** [comment]
this needs to be fixed in the `encase` crate
relevant issue: https://github.com/teoxoy/encase/issues/74

**Comment by janhohenheim** [comment]
Vulkan and DX12 don't support this and WGPU might revert their support: https://github.com/gfx-rs/wgpu/issues/5857
Closing for now, feel free to reopen when things change :)
