### ISSUE TITLE
Improve `CommandQueue has un-applied commands being dropped.` warning message

### ISSUE THREAD

**Issue by Swoorup** [bevyengine/bevy#13944]
## What problem does this solve or what need does it fill?

Originated from discord question: [Link](https://discord.com/channels/691052431525675048/1253173927556153348). I was having an issue as to why entities weren't spawned, resources weren't mutated using `SystemState`. 

```shell
2024-06-20T13:54:12.328157Z  WARN bevy_ecs::system::commands::command_queue: CommandQueue has un-applied commands being dropped.
```

It is not immediately obvious when this warning comes from bevy where to rather look. I personally spent an evening trying different things, crawling github issues. Before I realized I was missing a single line: `state.apply(world);` after applying mutations ie spawning entities via the commands. 

## What solution would you like?

@alice-i-cecile proposed something like `did you forget to call SystemState::apply` message so it can be useful to track it down the place of issue.

## What alternative(s) have you considered?

N/A

## Additional context

Reproduction code.

```rust
use bevy::{
    ecs::system::{SystemParam, SystemState},
    log::LogPlugin,
    prelude::*,
};

fn main() {
    App::new()
        .add_plugins(LogPlugin::default())
        .insert_resource(PlayerCount(0))
        .add_systems(Startup, spawn)
        .add_systems(Update, count_players)
        .run();
}

#[derive(Component)]
struct Player;

#[derive(Resource)]
struct PlayerCount(usize);

#[derive(SystemParam)]
struct PlayerCounter<'w, 's> {
    players: Query<'w, 's, &'static Player>,
    count: ResMut<'w, PlayerCount>,
}

impl<'w, 's> PlayerCounter<'w, 's> {
    fn count(&mut self) {
        self.count.0 = self.players.iter().len();
    }
}

fn spawn(world: &mut World) {
    let mut system_state: SystemState<Commands> = SystemState::new(world);
    let mut commands = system_state.get_mut(world);
    commands.spawn(Player);
    commands.spawn(Player);
    commands.spawn(Player);

    // uncomment the following to fix the warnings:
    // system_state.apply(world);
}

fn count_players(mut counter: PlayerCounter) {
    counter.count();

    println!("{} players in the game", counter.count.0);
}
```

**Comment by waynr** [comment]
My code doesn't (as far as I can see) reference any CommandQueue instances anywhere and now I'm just seeing the even more confusing new error message.

**Comment by waynr** [comment]
I think I figured out my issue...I'm using a `Commands` in one of my systems then calling `remove_resource` on that, but there doesn't seem to be a way after I call that method to apply it so I get the mysterious reference to a CommandQueue that I never touched in my code.
