### ISSUE TITLE
GLTF: different rendering when loaded from GLB vs. GLTF/ascii

### ISSUE THREAD

**Issue by jamadazi** [bevyengine/bevy#1396]
I have tested this using several models from the [glTF sample models repo](https://github.com/KhronosGroup/glTF-Sample-Models), for example WaterBottle.

The same model is available in multiple versions, specifically, an ASCII GLTF file with the textures as external PNG files, and a binary GLB file with everything integrated.

Both of them load and render, but the rendering looks visually different between the two:

From GLTF:

![2021-02-04-163031](https://user-images.githubusercontent.com/40234599/106915638-898b3b00-6706-11eb-9288-e32c60a90d1e.png)

From GLB:

![2021-02-04-163118](https://user-images.githubusercontent.com/40234599/106915645-8e4fef00-6706-11eb-9203-08b864fbd730.png)

**Comment by jamadazi** [comment]
[Coral model](https://3d.si.edu/object/3d/goniastrea-favulus:009463d3-6f58-4f5b-8e60-915805a876ee):

GLTF:

![2021-02-04-181421](https://user-images.githubusercontent.com/40234599/106929772-10dfab00-6715-11eb-8039-637096eccb3e.png)

GLB:

![2021-02-04-181451](https://user-images.githubusercontent.com/40234599/106929879-34a2f100-6715-11eb-92ab-17d3ea2bf4ae.png)

I don't know which is "more correct".

**Comment by JonahHenriksson** [comment]
Looks like the lighting is different, but probably something different between the files. I tried this out using a scene I created in blender and exported as GLB and GLTF and found no difference. First one is GLTF, second is GLB. Doesn't seem like an issue with Bevy.
![image](https://user-images.githubusercontent.com/33059163/107865880-f15a2800-6e62-11eb-90d0-bef23ef9fbf4.png)
![image](https://user-images.githubusercontent.com/33059163/107865882-f8813600-6e62-11eb-9dfc-43516637d2ea.png)

**Comment by JonahHenriksson** [comment]
It could also be an issue with whatever you did to get the GLTF file to run. I couldn't because it said that Jpegs aren't supported by Bevy. If you converted the textures to a different format, it could have had some affect on the color. It would be good if you explained what you did and uploaded some code.

**Comment by JonahHenriksson** [comment]
Nevermind, I see that it is a feature flag that I hadn't enabled.

**Comment by JonahHenriksson** [comment]
Ok, got both versions to work and got your problem with the coral model. Since the same setup works still with my Suzanne files, it must just be the textures differ in the coral files, since it can't be lighting since Bevy doesn't support lights from GLTF/GLB files.
