### ISSUE TITLE
`OnEnter` state schedules are now executed immediately

### ISSUE THREAD

**Issue by eidloi** [bevyengine/bevy#13968]
## Bevy version

[v0.14.0-rc.3](https://github.com/bevyengine/bevy/releases/tag/v0.14.0-rc.3)

## What you did

I have an example in which I use a state to (destructively) switch between pages, There is a setup system to prepare a container for these while keeping a menu and footer around them, and `OnEnter` / `OnExit` systems to manage cleanup and spawning.

## What went wrong

In bevy 0.13.x, adding `OnEnter(MyState::StateOne)` would have been executed _after_ `Startup`.
Since the extraction of States, these are immediately executed which means a start up state cannot be guaranteed in the systems.

## Additional information

To work around this one must either add a default `None` state or similar to each state or remove setup entirely since the `OnEnter` will not be repeated. Also, updating the state resource need mutable access to the Resource, but if a chain of commands is used to setup the
world state, changing the resource will always be too early. A `Command` + `EntityCommand` should be provided that can be plugged
into a setup chain to properly schedule the state update, but I haven't seen this yet.

**Comment by eidloi** [comment]
I made a command extension like so:

```rust
pub trait UpdateStatesExt<'w, 's, 'a> {
    fn next_state<C: States + FreelyMutableState>(&mut self, state: C);
}

impl<'w, 's, 'a> UpdateStatesExt<'w, 's, 'a> for Commands<'w, 's> {
    fn next_state<C: States + FreelyMutableState>(&mut self, state: C) {
        self.add(|world: &mut World| {
            if let Some(mut old_state) = world.get_resource_mut::<NextState<C>>() {
                old_state.set(state);
            } else {
                warn!(
                    "Failed to set state: {}, state not initialized!",
                    std::any::type_name::<C>()
                );
            }
        });
    }
}
```

and I can use it with `commands.next_state(Page::Layout);` in the appropriate place in my `setup` system.

**Comment by benfrankel** [comment]
I'm confused by the "What you did" section of this issue. There seems to be some missing context.

**Comment by eidloi** [comment]
> I'm confused by the "What you did" section of this issue. There seems to be some missing context.

Updated, sorry about that I am worked on the upgrade while sick.

**Comment by alice-i-cecile** [comment]
IMO this is an intended part of the design: there should never be a gap (including at startup) where you are in a state but its invariants have not been applied. I definitely understand that it's frustrating to migrate, but I much prefer the existing design.

@lee-orr @MiniaczQ, I value your opinion here, but I'm leaning towards closing as wont-fix.

**Comment by eidloi** [comment]
> IMO this is an intended part of the design: there should never be a gap (including at startup) where you are in a state but its invariants have not been applied. I definitely understand that it's frustrating to migrate, but I much prefer the existing design.
> 
> @lee-orr @MiniaczQ, I value your opinion here, but I'm leaning towards closing as wont-fix.

I understand the design decision around it, my main issue was that out of the box it was not possible to synchronize system generated content with the state-generated ones. With the command extension I can solve my sync issues, but bevy doesn't (or at least I haven't seen) offer a good way to do it.

**Comment by lee-orr** [comment]
I think the actual solution you may be looking for is using sub states or computed states.

The way these work, the parent states OnEnter runs before the child state's one, so you can do the parent state set up, and then the child state stuff.

**Comment by eidloi** [comment]
> I think the actual solution you may be looking for is using sub states or computed states.
> 
> The way these work, the parent states OnEnter runs before the child state's one, so you can do the parent state set up, and then the child state stuff.

yeah that works for me, it's just most cases need to introduce an extra (single-variant) state to govern as a root since the overall container needs to be managed (at least for UI it is quite usual)

**Comment by lee-orr** [comment]
> > IMO this is an intended part of the design: there should never be a gap (including at startup) where you are in a state but its invariants have not been applied. I definitely understand that it's frustrating to migrate, but I much prefer the existing design.
> > 
> > @lee-orr @MiniaczQ, I value your opinion here, but I'm leaning towards closing as wont-fix.
> 
> I understand the design decision around it, my main issue was that out of the box it was not possible to synchronize system generated content with the state-generated ones. With the command extension I can solve my sync issues, but bevy doesn't (or at least I haven't seen) offer a good way to do it.

I think the current "intended approach" is that, when using states, they form the structural basis for setup and teardown rather than relying on Startup. I immediately jump to something like a loading state as the "classic" example of the situation we're in here.

The other option, which was discussed but we never implemented, is the ability to remove a mutable state (basically set it to None) at will, and re insert it later. If we added this, it would enable you to do the Startup stuff while those states are None, and then set them to their initial values.

**Comment by eidloi** [comment]
> > > IMO this is an intended part of the design: there should never be a gap (including at startup) where you are in a state but its invariants have not been applied. I definitely understand that it's frustrating to migrate, but I much prefer the existing design.
> > > @lee-orr @MiniaczQ, I value your opinion here, but I'm leaning towards closing as wont-fix.
> > 
> > 
> > I understand the design decision around it, my main issue was that out of the box it was not possible to synchronize system generated content with the state-generated ones. With the command extension I can solve my sync issues, but bevy doesn't (or at least I haven't seen) offer a good way to do it.
> 
> I think the current "intended approach" is that, when using states, they form the structural basis for setup and teardown rather than relying on Startup. I immediately jump to something like a loading state as the "classic" example of the situation we're in here.
> 
> The other option, which was discussed but we never implemented, is the ability to remove a mutable state (basically set it to None) at will, and re insert it later. If we added this, it would enable you to do the Startup stuff while those states are None, and then set them to their initial values.

Nah, the additional variant and the command extension works miracles for me. It lets me bridge the two approaches as needed and I have fine control over what's in the world when the state changes regardless of schedule

**Comment by benfrankel** [comment]
For what it's worth, I think the `StateTransition` schedule running twice in the same frame, but only on the very first frame (in `Startup` and then after `PreUpdate`), doesn't make sense and should be changed.

If we consider a state type like `enum Foo { A, B, C }` to be defining three mutually exclusive states that the app can be in, then before the initial state transition, the app is just... not in any of them yet. Which is fine. With state disabling / enabling, this will become more obvious.
