### ISSUE TITLE
UiSystem::Layout is run too late in the schedule

### ISSUE THREAD

**Issue by eidloi** [bevyengine/bevy#13966]
## Bevy version

[v0.14.0-rc.3](https://github.com/bevyengine/bevy/releases/tag/v0.14.0-rc.3)

## What you did

I had a system sets configured as:

```rust
app.configure_sets(
    PostUpdate,
    (ThemeUpdate, CustomThemeUpdate.after(ThemeUpdate)).before(UiSystem::Layout),
)
```

## What went wrong

Starting an app with the above configuration results in a panic!

```
Error when initializing schedule PostUpdate: `ui_layout_system (in set Layout)` and `Layout` have both `in_set` and `before`-`after` relationships (these might be transitive). This combination is unsolvable as a system cannot run before or after a set it belongs to.
```

## Additional information

This was not an issue in the previous 0.13 versions. Also, sometimes it just works, which leads me to believe it is an async issue.

Also note I had a system that was scheduled before the above mentioned `ThemeUpdate`: 
```rust
.add_systems(
    PostUpdate,
    propagate_visibility_to_pseudo_state
        .after(VisibilitySystems::VisibilityPropagate)
        .before(ThemeUpdate),
)
```

**Comment by eidloi** [comment]
This issue can be reproduced in `sickle_ui`:

Checkout https://github.com/UmbraLuminosa/sickle_ui/tree/55405d0c4bc39be0a7937d936eb9235b11916a7b
uncomment line https://github.com/UmbraLuminosa/sickle_ui/blob/55405d0c4bc39be0a7937d936eb9235b11916a7b/crates/sickle_ui_scaffold/src/theme/pseudo_state.rs#L22 (and import the enum)

Start the example `cargo run --example simple_editor`

If the line is commented out it will start normally.

**Comment by benfrankel** [comment]
Adding a system that is both `.after(VisibilityPropagate)` and `.before(ThemeUpdate)` implicitly requires that `VisibilityPropagate` should run before `ThemeUpdate`, which in turn runs before `UiSystem::Layout`. This creates a cycle:

1. `TransformPropagate`
2. `VisibilityPropagate
3. `propagate_visibility_to_pseudo_state`
4. `ThemeUpdate`
5. `UiSystem::Layout`, which contains `ui_layout_system`
6. `TransformPropagate`

**Comment by eidloi** [comment]
> Adding a system that is both `.after(VisibilityPropagate)` and `.before(ThemeUpdate)` implicitly forces `VisibilityPropagate` to run `.before(ThemeUpdate)`, which in turn runs `.before(UiSystem::Layout)`.
> 
> This creates a cycle:
> 
>     1. `TransformPropagate`
> 
>     2. `VisibilityPropagate`
> 
>     3. `propagate_visibility_to_pseudo_state`
> 
>     4. `ThemeUpdate`
> 
>     5. `UiSystem::Layout`, which contains `ui_layout_system`
> 
>     6. `TransformPropagate`

Yes, and looking at `VisibilityPropagate` it is set only after `TransformPropagate`. Does this mean `TransformPropagate` moved later in the schedule in 0.14 or was `UiSystem::Layout` moved earlier? I didn't have this issue before.

**Comment by eidloi** [comment]
BTW this is not blocking for the moment, It just means that the theme in `sickle_ui` will be updated a frame later in some cases, but I have to see how much noticeable flicker it introduced.
