### ISSUE TITLE
Log window/monitor info on startup

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#13979]
## What problem does this solve or what need does it fill?

Helps debugging performance like the existing system and adapter info.

## What solution would you like?

At startup in bevy_winit for the primary window, log the window resolution, dpi, color space, min+max refresh rate, etc.

## What alternative(s) have you considered?

Log monitor info, instead of window info.
screenshots, benchmarks, etc.

**Comment by killercup** [comment]
Maybe easier to implement after #13669
