### ISSUE TITLE
Regression on string representation of entities

### ISSUE THREAD

**Issue by eidloi** [bevyengine/bevy#13980]
## Bevy version

https://github.com/bevyengine/bevy/releases/tag/v0.14.0-rc.3

## What you did

I used the `Debug` implementation in various logging and displaying of Entities, such as `info!("My enetity: {:?}", entity)`.

## What went wrong

In the RC version the `Debug` implementation was replaced to be in sync with the serialized version, HOWEVER, the `Display` implementation does not match that of the previous `Debug`.

- Before: `737v1`
- After `737v1|4294968033`

This means that the previous short version no longer exists and if someone wishes to debug they will have a really long text, if they use display (such as in an editor) the text is needlessly long too.

**Comment by alice-i-cecile** [comment]
Would you be okay with a `short_id` method? Or do you feel strongly that `Display` should be changed?

**Comment by eidloi** [comment]
> Would you be okay with a `short_id` method? Or do you feel strongly that `Display` should be changed?

I would go with display since that integrates with all tracing macros (`info!`, `warn!`) and `format!` so logs aren't cluttered or need too much work updating. The number after the pipe is also generally useless for most use cases, unless you specifically need to track that number. 

But now that you have suggested, it does make sense to have a version that is like the current `Display` with the number after it as a function. In that rare case when it matters. (Also `Debug` doesn't have the long integer in it so it should not disappear entirely)
