### ISSUE TITLE
`AnyOf` does not behave correctly with `()` params

### ISSUE THREAD

**Issue by iiYese** [bevyengine/bevy#13994]
## Bevy version
0.13

## What you did
Query for `AnyOf<((), &Foo)>`.

## What went wrong
Query did not match the single entity that only had a component `Foo` correctly.

## Additional information
```rs
use bevy::prelude::*;

#[derive(Component)]
struct Foo;

fn setup(mut cmds: Commands) {
    cmds.spawn(Foo);
}

fn update(sanity_check: Query<&Foo>, bug: Query<AnyOf<((), &Foo)>>) {
    if sanity_check.get_single().is_ok() {
        println!("I exist!");
    }
    let _ = bug.single();
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(Update, update)
        .run();
}
```
```
I exist!
thread 'Compute Task Pool (4)' panicked at src/main.rs:14:17:
called `Result::unwrap()` on an `Err` value: MultipleEntities("bevy_ecs::query::state::QueryState<bevy_ecs::query::fetch::AnyOf<((), &bevy_bug::Foo)>>")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_bug::update`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

**Comment by Gingeh** [comment]
The query _is_ finding the entity, the reason your code panics is because it actually finds the entity _twice_. (See where the error says `value: MultipleEntities`).

If you change the code to print each match then you see that it matches: `[(Some(()), None), (Some(()), Some(Foo))]`

**Comment by iiYese** [comment]
That's still Incorrect. It should have a single entity.

**Comment by Gingeh** [comment]
The documentation for `AnyOf` says: 
> `Query<AnyOf<(&A, &B, &mut C)>>` is equivalent to `Query<(Option<&A>, Option<&B>, Option<&mut C>), Or<(With<A>, With<B>, With<C>)>>`.

So  `AnyOf<((), &Foo)>` should be equivalent to `Option<&Foo>`, which also matches the entity twice.

**Comment by iiYese** [comment]
Bit unintuitive but guess that makes sense.
