### ISSUE TITLE
Running example gets "STATUS_ACCESS_VIOLATION"

### ISSUE THREAD

**Issue by huangjj27** [bevyengine/bevy#140]
codes:
```
// the default example
use bevy::prelude::*;

fn main() {
    App::build()
        .add_default_plugins()
        .run();
}
```
gets errors:
```
error: process didn't exit successfully: `target\debug\game_demo.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

rustc version:
```
> rustc --version
rustc 1.45.2 (d3fb005a3 2020-07-31)
```

maybe this is caused by wgpu's bug as in  https://github.com/hecrj/iced/issues/447。

**Comment by huangjj27** [comment]
I get the same error running either `cargo run` or `cargo run --no-default-features`, which indicates the bug is not  caused by these plugins:
```rust
        #[cfg(feature = "bevy_audio")]
        self.add_plugin(bevy_audio::AudioPlugin::default());

        #[cfg(feature = "bevy_gltf")]
        self.add_plugin(bevy_gltf::GltfPlugin::default());

        #[cfg(feature = "bevy_winit")]
        self.add_plugin(bevy_winit::WinitPlugin::default());

        #[cfg(feature = "bevy_wgpu")]
        self.add_plugin(bevy_wgpu::WgpuPlugin::default());
```

**Comment by huangjj27** [comment]
When I move out the default plugins like this, I get a different error.
```rs
fn main() {
    App::build()
        // .add_default_plugins()
        .add_plugin(bevy::type_registry::TypeRegistryPlugin::default())
        .add_plugin(bevy::core::CorePlugin::default())
        .add_plugin(bevy::transform::TransformPlugin::default())
        .add_plugin(bevy::diagnostic::DiagnosticsPlugin::default())
        .add_plugin(bevy::input::InputPlugin::default())
        .add_plugin(bevy::window::WindowPlugin::default())
        .add_plugin(bevy::asset::AssetPlugin::default())
        .add_plugin(bevy::scene::ScenePlugin::default())
        .add_plugin(bevy::render::RenderPlugin::default())
        .add_plugin(bevy::sprite::SpritePlugin::default())
        .add_plugin(bevy::pbr::PbrPlugin::default())
        .add_plugin(bevy::ui::UiPlugin::default())
        .add_plugin(bevy::text::TextPlugin::default())
        .run();
}
```

error goes:
```log
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'Resource does not exist alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>Resource does not exist alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>', ', C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src\libstd\macros.rsC:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src\libstd\macros.rs::1616::99

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\game_demo.exe` (exit code: 101)
```

**Comment by cramt** [comment]
I managed to reproduce the exact same bug.
I fixed it by updating my graphics drivers.

windows 10 build 19041
NVIDIA GeForce 940M, currently with drivers version 451.67, dont know what the driver version was previously

**Comment by huangjj27** [comment]
## Environment

OS: Windows 10 Pro 1909
Processer: AMD A10-5750M with Radeon(tm) HD graphics
Graphics: AMD Radeon HD 8650G + AMD Radeon HD 8790M (Microsoft detected dirvers, date to 2019/8/16, driver version: 26.20.12028.2) (Not update to AMD drivers for the super slow download.)

NOTE that my graphics don’t support newer drivers.

**Comment by huangjj27** [comment]
## Environment

OS: Windows 10 Pro 1909
Processer: AMD A10-5750M with Radeon(tm) HD graphics
Graphics: AMD Radeon HD 8650G + AMD Radeon HD 8790M (Microsoft detected dirvers, date to 2019/8/16, driver version: 26.20.12028.2) (Not update to AMD drivers for the super slow download.)

NOTE that my graphics don’t support newer drivers.

**Comment by huangjj27** [comment]
I update my computer with a newer graphics card, which support Vulkan/DX12. I think there is no other way to solve this problem on graphics that can't not support Vulkan/DX12. I'm closing this issue.
