### ISSUE TITLE
Make cargo clippy and cargo fmt pre-commit hooks

### ISSUE THREAD

**Issue by BobG1983** [bevyengine/bevy#14002]
## What problem does this solve or what need does it fill?

Currently cargo-clippy is not the default for a lot of people. That can lead to PRs failing because of cargo-clippy errors. This costs the foundation compute and space. If clippy was a pre-commit hook then many issues that are picked up by the CI run would be picked up at commit time rather than during github actions.

## What solution would you like?

Add cargo clippy as a pre-commit hook. While we're there, do the same with cargo fmt. Most of us do this automatically, but if we're doing one, why not both?

**Comment by alice-i-cecile** [comment]
What are the pros and cons of a pre-commit hook vs a triggerable bot? @BD103 @mockersf do either of you have opinions here?

**Comment by IceSentry** [comment]
I'm heavily against pre-commit hooks. It's really annoying to have to wait on hooks before comitting anything. Most contributors are already aware of clippy and CI currently doesn't cost anything.

**Comment by BobG1983** [comment]
Mostly cost I would assume.

I get the response when I try and commit locally, including on my own branches, rather than having to wait till a PR is opened.

---
"Of all the things I've lost, I miss my mind the most" - Ozzy Osbourne

**Comment by mockersf** [comment]
Pre commit hooks offer no guarantee, as they have to be installed by the contributor to do anything...

I'm also heavily against them, they're mostly an added annoyance without bringing anything
