### ISSUE TITLE
SubApp::extract cannot be called due to borrow checker

### ISSUE THREAD

**Issue by anlumo** [bevyengine/bevy#14003]
## Bevy version

0.14.0-rc.3

## What you did

I'm trying to call extract/update on a single SubApp instead of all at once.

## What went wrong

Here is the code:

```rust
fn run_sub_app(app: &mut App, label: impl AppLabel) {
    let world = app.world_mut();
    if let Some(sub_app) = app.get_sub_app_mut(label) {
        sub_app.extract(world);
        sub_app.update();
    }
}
```

- what were you expecting?

I'd like to run extract.

- what actually happened?

Compiler error in the `if let` line: cannot borrow app mutable more than once, first borrow happens in the line defining the `world` variable.

I don't see a way to use the `extract` function at all, since the world I have to pass is always part of the enclosing context, and thus the borrow checker will never allow that.

## Additional information

`SubApps::update` works, because it can do a partial borrow of `self`, but since I don't have access to `SubApps`, I can't do the same from outside the bevy\_app crate.

This is an inherent limitation of Rust's borrow checker, because it can't do partial borrows on references returned from function calls.

**Comment by alice-i-cecile** [comment]
Can you give a bit more context on why you're using this pattern? I'd like to remove sub-apps completely, and want a better sense of the advanced use cases.

**Comment by anlumo** [comment]
I have a UI system (not bevy's!) and want to display bevy views as UI views, and there might be multiples of them. There's a place in the app where I have to tell bevy to render that specific view to wgpu's queue right now (synchronously), which should be achievable by running `sub_app.update();`. This shouldn't render the other views, only the one I want right now (because there might be UI elements between two views).

It would be nice to have separate worlds for these views. I thought about using completely separate bevy Apps for this, but then I couldn't share entities when necessary. Also, I'd have to set up all systems for every App again and again.

**Comment by alice-i-cecile** [comment]
Okay, so pretty standard multi-world / entity partitioning stuff. Thanks!

As for this issue, please feel free to make a simple PR to expose an API to do so.

**Comment by Soulghost** [comment]
I have made a simple PR to expose an API called `update_sub_app_by_label ` to resolve this issue, could you please verify if this is in line with our expectations?

**Comment by anlumo** [comment]
> I have made a simple PR to expose an API called `update_sub_app_by_label ` to resolve this issue, could you please verify if this is in line with our expectations?

Yes, thank you!
