### ISSUE TITLE
Allow rotating the skybox/environment map

### ISSUE THREAD

**Issue by Azorlogh** [bevyengine/bevy#14036]
## What problem does this solve or what need does it fill?

Some users need to use Z as the vertical axis. As a result, skyboxes & environment maps will be rotated for them.

## What solution would you like?

It would be useful to have a way to specify a rotation for skyboxes & environment maps.

## What alternative(s) have you considered?

Rotating the textures directly. This is inconvenient and not straightforward (rotating an equirectangular HDRI requires resampling, and for .ktx2 cubemaps there's no tool to do it that I could find).

**Comment by Soulghost** [comment]
Given the complexity of the environment map rotation, I'll submit a separate PR for it later.
