### ISSUE TITLE
Rename bevy_core::name::DebugName to better fit its implementation

### ISSUE THREAD

**Issue by ItsDoot** [bevyengine/bevy#14039]
## What problem does this solve or what need does it fill?

The name of the `DebugName` struct is a bit of a misnomer: we don't have a separate struct for entity "debug names", and it just reuses the standard `Name` component, falling back to displaying the entity's ID if it doesn't have a name. We should rename `DebugName`.

## What solution would you like?

I suggest `NameOrId`: it remains short to spell out, and directly reflects its intentions. Welcome to other bikeshed names!

**Comment by JMS55** [comment]
I like `DebugLabel` personally.
