### ISSUE TITLE
Crash in rc.4 using skinned meshes

### ISSUE THREAD

**Issue by torsteingrindvik** [bevyengine/bevy#14059]
## Bevy version

RC.4

## What you did

Started my app, crashes on loading a particular GLTF containing an animated model.

## What went wrong

```
wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `morphed_skinned_mesh_bind_group`
    Number of bindings in bind group descriptor (4) does not match the number of bindings defined in the bind group layout (6)
```

## Additional information

I did a bisect and ended up with:

> be053b1d7cc84d6687459da304ebca6a84782a14 is the first bad commit

The GLTF I'm using is a paid asset so I can't easily share it, but if there is anything I should inspect/look into on it I can.

**Comment by alice-i-cecile** [comment]
Can you try with a few other skinned meshes? I want both a reproduction case and to get a sense of how widespread this is.

**Comment by janhohenheim** [comment]
Can you maybe edit the paid asset to the point were it's just a cube with a single-color texture and share that?

**Comment by torsteingrindvik** [comment]
Just so you know there is activity @mockersf offered to help on discord so they have access to a slightly edited but still crashing asset.
Let's see if that pans out, in the mean time I can try to run misc examples on rc.4 to see if I get crashes.
