### ISSUE TITLE
Update examples to use accumulated mouse input

### ISSUE THREAD

**Issue by mweatherley** [bevyengine/bevy#14066]
#14044 adds accumulated mouse inputs in the form of resources. I know some of the examples in `bevy_math` and `bevy_transform` (e.g. `align`, `random_sampling`, `sampling_primitives`) manually accumulate mouse inputs to handle camera movement, so those should probably be updated in light of the linked PR. There might be some others outside `bevy_math` as well. Updating these would help set a good example for making proper use of the new tool!

**Comment by janhohenheim** [comment]
[`first_person_view_model`](https://github.com/bevyengine/bevy/blob/main/examples/camera/first_person_view_model.rs) should probably use accumulated mouse input as well

**Comment by richchurcher** [comment]
I might give this a crack if no-one's looking at it, just to dip my toes in the project 🙂
