### ISSUE TITLE
UI_PASS constant is not public

### ISSUE THREAD

**Issue by glfmn** [bevyengine/bevy#1408]
| Version | |
|------------------|-----|
| Bevy | 0.4 |
| OS | Ubuntu 20.04.1|

# Context

I'm working on a plugin which adds an immediate mode drawing context for debugging purposes with simple shapes, arrows, etc, to avoid needing to spawn and manage entities.

I have implemented this functionality in a render node which I have running after the main pass, taking as input the color texture and the depth texture.

[Discord](https://discordapp.com/channels/691052431525675048/742884593551802431/806647375950381097).

# The problem

My render pass is randomly missing depth information from the main pass.  I noticed a render pass which has no draw calls but which clears the depth texture seems to be the culprit.  Sometimes it runs in the same color pass as, but after, my debug node and things look fine.  Sometimes it appears as a separate color pass that happens before my render pass.  Where does this render pass come from?  Am I missing a node I need to add a dependency on?

| Frame | Capture | Description |
|---------|-------------|-----------------|
| ![Shapes have expected depth test results][well-integrated] | ![Capture shows color pass #2 has my draw calls before the render pass which clears the depth buffer.][well-integrated-capture]  | The blue and green cubes appear as desired, and the depth texture from the main pass is cleared immediately after my draw calls. |
| ![Shapes appear superimposed above main pass][superimposed] |  ![Capture shows color pass 2 which cleared the depth texture][superimposed-capture]  | The blue and green cubes appear superimposed, and the depth texture from the main pass seems to have been cleared by Color Pass 2  (which is in-between the main pass and my debug pass)|

# Render Graph Setup

[From bevy_debug_draw/src/renderer.rs:312](https://github.com/glfmn/bevy_debug_draw/blob/84ab57c3ee163a8330032efd25e3eb9ffac88f5f/src/renderer.rs#L312)

```rust

use bevy_render::render_graph::base;
render_graph.add_node(node::DEBUG_DRAW, DebugDrawNode::new());
render_graph
    .add_slot_edge(
        base::node::PRIMARY_SWAP_CHAIN,
        WindowSwapChainNode::OUT_TEXTURE,
        node::DEBUG_DRAW,
        DebugDrawNode::COLOR_ATTACHMENT_SLOT,
    )
    .expect("Failed to link node to color output");

render_graph
    .add_slot_edge(
        base::node::MAIN_DEPTH_TEXTURE,
        WindowTextureNode::OUT_TEXTURE,
        node::DEBUG_DRAW,
        DebugDrawNode::DEPTH_ATTACHMENT_SLOT,
    )
    .expect("Failed to link node to depth texture");

render_graph
    .add_node_edge(base::node::MAIN_PASS, node::DEBUG_DRAW)
    .expect("Failed to schedule debug node after main pass");
```

Pass descriptor is found [here](https://github.com/glfmn/bevy_debug_draw/blob/84ab57c3ee163a8330032efd25e3eb9ffac88f5f/src/renderer.rs#L73).  Pipeline descriptor is found [here](https://github.com/glfmn/bevy_debug_draw/blob/84ab57c3ee163a8330032efd25e3eb9ffac88f5f/src/renderer.rs#L240).

[well-integrated]: https://user-images.githubusercontent.com/14112725/107102344-41444980-67e8-11eb-8aa1-1ec0b32f8624.png
[well-integrated-capture]:  https://user-images.githubusercontent.com/14112725/107102783-86b54680-67e9-11eb-83fa-d5832f3fce85.png

[superimposed]: https://user-images.githubusercontent.com/14112725/107102420-7355ab80-67e8-11eb-8513-8e28d8a317b3.png
[superimposed-capture]:  https://user-images.githubusercontent.com/14112725/107102489-96805b00-67e8-11eb-9cd7-2cd6b33f23b7.png

**Comment by glfmn** [comment]
I took another look through the base render graph but I don't see anything other than the main pass node which actually creates a render pass.  I have updated to bevy master and the depth texture seems to always be cleared before the debug pass can run.

**Comment by glfmn** [comment]
I think it was the `UI_PASS` which also runs after main pass.

Adding `render_graph.add_node_edge(node::DEBUG_DRAW, "ui_pass");` seems to have solved the issue.

However, on master I was unable to find the actual `UI_PASS` constant.  It seems like it should be exported from `bevy_ui` but I don't see it anywhere when I use `cargo doc --open` and I can't get my program to compile using what it seems should be the path to the `node` module.

**Comment by james7132** [comment]
It does seem to be public as of #3312. Does this resolve this issue?

**Comment by glfmn** [comment]
I am indeed able to see [`UI_PASS`](https://docs.rs/bevy/0.10.1/bevy/ui/draw_ui_graph/node/constant.UI_PASS.html) in docs.rs

**Comment by glfmn** [comment]
I am indeed able to see [UI_PASS](https://docs.rs/bevy/0.10.1/bevy/ui/draw_ui_graph/node/constant.UI_PASS.html) in docs.rs
