### ISSUE TITLE
API inconsistency with `Handle` as component or field of component

### ISSUE THREAD

**Issue by benfrankel** [bevyengine/bevy#14124]
# Question

Should components with associated assets (e.g. `Sprite` + `Handle<Image>`) include their `Handle` as a field, or as a separate component on the same entity, or something else?

- `Handle`-as-field: May make certain generic systems impossible (see the `asset_decompression` example).
- `Handle`-as-component: May create ambiguity (see `EnvironmentMapLight`).

From the [Discord discussion](https://discord.com/channels/691052431525675048/692572690833473578/1215068019299065927), this is blocked on Bevy scenes before a design decision can be made.

# Status quo

Bevy's answer to this question is inconsistent (as of March 6th, 2024):

> Component with a wrapped `Handle` field:
> - `UiImage::texture: Handle<Image>`
> - `TextureAtlas::layout: Handle<TextureAtlasLayout>`
> - `Skybox::image: Handle<Image>`
> - `Mesh2dHandle::0: Handle<Mesh>`
> - `SkinnedMesh::inverse_bindposes: Handle<SkinnedMeshInverseBindposes>`
> - `Lightmap::image: Handle<Image>`
> - `IrradianceVolume::voxels: Handle<Image>`
> - `EnvironmentMapLight::diffuse_map: Handle<Image>`
> - `EnvironmentMapLight::specular_map: Handle<Image>`
> 
> Component with an associated `Handle`-as-component:
> - `Sprite` + `Handle<Image>`
> - more? hard to ripgrep for this
> 
> Bundle with a `Handle`-as-component field:
> - `SpriteBundle::texture: Handle<Image>`
> - `SceneBundle::scene: Handle<Scene>`
> - `DynamicSceneBundle::scene: Handle<DynamicScene>`
> - `MaterialMesh2dBundle<M>::material: Handle<M>`
> - `MaterialMeshBundle<M>::material: Handle<M>`
> - `MaterialMeshBundle<M>::mesh: Handle<Mesh>`
> - `MaterialNodeBundle<M>::material: Handle<M>`
> - `AudioSourceBundle<Source>::source: Handle<Source>`

**Comment by alice-i-cecile** [comment]
I agree; this design has annoyed me since the Component trait was implemented. I think these should all be newtyped personally.

**Comment by benfrankel** [comment]
This seems to be unblocked now, with required components landed and the scene overhaul generally being underway.

**Comment by alice-i-cecile** [comment]
This was discussed informally today, with both @cart and I being broadly on board with moving to wrapper components: https://discordapp.com/channels/691052431525675048/1264881140007702558/1278098028536008827

**Comment by bushrat011899** [comment]
Resolved in #15796. `Handle` should now be used as a field in a `Component`.
