### ISSUE TITLE
docs.rs claims that `bevy_state` 0.14.0 (+ 0.14.0-rc.4) depends on a yanked dependency

### ISSUE THREAD

**Issue by Themayu** [bevyengine/bevy#14136]
## Bevy version

0.14.0

## What you did

Went to https://docs.rs/crate/bevy_state/0.14.0 to try to view the documentation for `bevy_state`.

## What went wrong

The documentation cannot be built because `bevy_state` 0.14.0 depends on a yanked dependency.

## Additional information

Build log:

```
Build #1281410
# pre-build errors
the crate depends on yanked dependencies

Stack backtrace:
0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
1: docs_rs::docbuilder::rustwide_builder::RustwideBuilder::build_package
2: prometheus::histogram::Histogram::observe_closure_duration
3: docs_rs::build_queue::BuildQueue::build_next_queue_package
4: docs_rs::utils::queue_builder::queue_builder
5: cratesfyi::CommandLine::handle_args
6: cratesfyi::main
7: std::sys_common::backtrace::__rust_begin_short_backtrace
8: std::rt::lang_start::{{closure}}
9: std::rt::lang_start_internal
10: main
11: __libc_start_main
at /build/glibc-uZu3wS/glibc-2.27/csu/../csu/libc-start.c:310
12: _start
```

No additional information is provided by docs.rs, so I have no additional information to report here except for a screenshot of the page:

![docs.rs failed to build bevy_state 0.14.0](https://github.com/bevyengine/bevy/assets/16105710/8ca9a48a-ec6e-4b2f-a39a-9622d3036262)

**Comment by Themayu** [comment]
Updated title to reflect that this is came from docs.rs. I tried checking if I could replicate it, but I'm getting permission denied errors from `pkg-config` under WSL and I don't have a native Linux install to test with.

**Comment by paul-hansen** [comment]
Same with bevy_asset: https://docs.rs/crate/bevy_asset/0.14.0

**Comment by mockersf** [comment]
fixed in docs.rs after a rebuild: https://github.com/rust-lang/docs.rs/issues/2556
