### ISSUE TITLE
Regression: gizmos panicking given bad output from `GlobalTransform::to_scale_rotation_translation`

### ISSUE THREAD

**Issue by aevyrie** [bevyengine/bevy#14142]
## Bevy version

0.14

## What you did

Draw a big circle

## What went wrong

Bevy panicked.

```
Error: The vector given to `Dir3::new_unchecked` is not normalized. The length is 0.25.
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: bevy_math::direction::assert_is_normalized
   3: bevy_math::direction::Dir3::new_unchecked
   4: <bevy_gizmos::circles::SphereBuilder<Config,Clear> as core::ops::drop::Drop>::drop::{{closure}}
```

## Additional information

This is a regression not present in 0.13.

**Comment by rparrett** [comment]
> Draw a big circle

Could you elaborate on this?

I modified the `3d_gizmos` example so that the spheres were very large, and also tried `f32::max` for a radius, but did not see this panic.

**Comment by aevyrie** [comment]
Repro is the `big_space` demo. I was trying to repro in a test in a PR to fix, but I can't figure out how to test this with the current setup, bevy_gizmo has no tests as far as I can tell.

**Comment by aevyrie** [comment]
Ah, found the issue. The quat from `GlobalTransform::to_scale_rotation_translation` is not normalized, and the `sphere` gizmo is exploding on that.

Almost certain I hit the same exact failure on the initial release of 0.13/12

```
[examples/demo.rs:155:13] scale.x * 0.505 = 5.05e18
[examples/demo.rs:153:13] translation = Vec3(
    8.431322e19,
    4.7312953e19,
    -7.1763914e19,
)
[examples/demo.rs:154:13] rotation = Quat(
    0.5,
    0.0,
    0.0,
    0.0,
)
```

**Comment by aevyrie** [comment]
Yup:

```
    // Ignore rotation due to panicking in gizmos, as of bevy 0.13
    let (scale, _, translation) = transform.to_scale_rotation_translation();
```

**Comment by aevyrie** [comment]
Deja vu: https://github.com/bevyengine/bevy/issues/12360

**Comment by aevyrie** [comment]
Looks like `sphere` was moved, and the normalize was removed. We really need tests.

**Comment by aevyrie** [comment]
It's very large and far from the origin. Converting the affine to trs is lossy.
