### ISSUE TITLE
Crash on Android on 0.14

### ISSUE THREAD

**Issue by Litttlefish** [bevyengine/bevy#14146]
## Bevy version

0.14

## What you did

I updated bevy version to 0.14

## What went wrong
Android game will crash, which didn't on 0.13

## Additional information
Here is the crash dump
[org.bevyengine.roundyproduction_2024-07-05T13_59_.log](https://github.com/user-attachments/files/16105479/org.bevyengine.roundyproduction_2024-07-05T13_59_.log)

**Comment by mockersf** [comment]
Could you also share the console log?

**Comment by Litttlefish** [comment]
> Could you also share the console log?

https://discord.com/channels/691052431525675048/757316314845937785/1258474648333455400
I'm not at my computer right now, this message has the same issue with console log

**Comment by mockersf** [comment]
Those are not usable for me, I'll wait for something in text form rather than screenshots of logs when you can

**Comment by Litttlefish** [comment]
> Those are not usable for me, I'll wait for something in text form rather than screenshots of logs when you can

[Xiaomi-2206122SC-Android-14_2024-07-05_174638.log](https://github.com/user-attachments/files/16108085/Xiaomi-2206122SC-Android-14_2024-07-05_174638.log)
I grabbed some console information from logcat

**Comment by BaituLime** [comment]
@mockersf  It's mine.
[app.log](https://github.com/user-attachments/files/16109761/app.log)

**Comment by extrawurst** [comment]
I think the key is:

```
[31m07-05 20:33:31.467 21914 18555 E event /home/bunny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/pCannot get the native window, it's null and will always be null before Event::Resumed and after Event::Suspended. Make sure you only call this function between those events.[0m
```

**Comment by mockersf** [comment]
This seems to be https://github.com/bevyengine/bevy/issues/13038 but on more GPUs that we identified at the time
it's fix for Adreno 6xx, but you are on Adreno 730

**Comment by Litttlefish** [comment]
I'll try disabling gpu processing on adreno 7 as #13323 did, let's see if it's really caused by that

**Comment by Litttlefish** [comment]
Yup, it's caused by this, can confirm disabling it fixed my game
