### ISSUE TITLE
0.14 - `ViewVisibility.get()` now returning `false` on custom renderable

### ISSUE THREAD

**Issue by simbleau** [bevyengine/bevy#14145]
## Bevy version

0.14

## Summary

In bevy_vello, we had a render loop for several asset types, inclusing scenes, svg, lotties, etc.

A typical render prepare looked like this:

```rust
pub fn scene_instances(
    mut commands: Commands,
    query_scenes: Extract<
        Query<(
            &VelloScene,
            &CoordinateSpace,
            &GlobalTransform,
            &ViewVisibility,
            &InheritedVisibility,
            Option<&Node>,
        )>,
    >,
) {
    for (scene, coord_space, transform, view_visibility, inherited_visibility, ui_node) in
        query_scenes.iter()
    {
        if view_visibility.get() && inherited_visibility.get() {
            commands.spawn(ExtractedRenderScene {
                transform: *transform,
                render_mode: *coord_space,
                scene: scene.clone(),
                ui_node: ui_node.cloned(),
            });
        }
    }
}
```

For some reason, `view_visibility.get()` started returning `false` this bevy version.

I am assuming this is because a `VelloScene` is one of our types, has no analytic bounding box, etc. I would like to ensure it always returns true for that reason.

Likewise, we do also offer SVG and Lottie support, which does have a bounding box that can be computed. It would be great to know how I can properly add support for culling for view visibility as well, or simply make ViewVisibility return true every frame as a temporary measure.

I tried checking the docs, but not finding anything substantial, especially to add real view visibility calculation to my types.

For now, I'm ok with a bandaid "render everything pls" approach.

Thanks

**Comment by simbleau** [comment]
Ok, so I think I have a temporary bandaid, if anyone stumbles upon this.

You essentially need to set the view visibility yourself from now on, overriding it.
It must be done in the `VisibilitySystems::CheckVisibility` set.

```rust
        fn bandaid_visibility(
            mut query_scenes: Query<&mut ViewVisibility, With<crate::VelloScene>>,
        ) {
            for mut v in query_scenes.iter_mut() {
                v.set();
            }
        }
        app.add_systems(
            PostUpdate,
            bandaid_visibility.in_set(VisibilitySystems::CheckVisibility),
        );
```

I still am not sure how I would do "correct" Aabb style ViewVisibility, or if there's an example for this.

**Comment by hymm** [comment]
you need to add a check_visibility system for you custom renderable https://bevyengine.org/learn/migration-guides/0-13-to-0-14/#store-lists-of-visibleentities-separately

**Comment by simbleau** [comment]
> you need to add a check_visibility system for you custom renderable https://bevyengine.org/learn/migration-guides/0-13-to-0-14/#store-lists-of-visibleentities-separately

Yeah, I saw that. Couldn't seem to get it to work, but finally did!

Here's what I was missing:
```rust
        // Check asset visibility
        app.add_systems(
            PostUpdate,
            check_visibility::<Or<(With<VelloScene>, With<Handle<VelloAsset>>)>>
                .in_set(VisibilitySystems::CheckVisibility),
        );
```
