### ISSUE TITLE
Allow Creating Custom AssetIO Implementations That Support Hot Reload

### ISSUE THREAD

**Issue by zicklag** [bevyengine/bevy#1414]
**What problem does this solve or what need does it fill?**

Currently, when creating your own `AssetIo` implementation, it is actually impossible to implement a custom equivalent to the `filesystem_watcher_sysem`, because that function depends on `asset_server.server.asset_io`, which is a private field of `AssetServer`.

In my use-case, I am creating a custom `AssetIo` implementation that allows loading assets from zip bundles, but I want to fall back completely to the default asset loader. Unfortunately, when I did this, I lost the ability to do hot reload, because the built-in `filesystem_watcher_system` will only work when the current `AssetIo` implementation is `FileAssetIo`.

**What solution would you like?**

I don't have a specific idea for the implementation, but however necessary, I need a way to be able to copy the exact functionality of the current `filesystem_watcher_system` in my own `AssetIo` implementation.

**What alternative(s) have you considered?**

Waiting on the Distil integration? :man_shrugging: But I would like to get this into my app now, so I'd hope there's at least a short-term solution would could come up with now. 

**Additional context**

If the strategy doesn't require a ton of work, I'd be willing to try to do this, but I'm not exactly sure what the best strategy is. The obvious easy techinque would just be to make the types that are necessary to access public types instead of private, but I'm not sure that is the best long-term design. Also, with the integration with Distil comming up, I'm not sure if we need it to be a great long term solution?

Anyway, I need some directional guidance on how we want to go about this.

**Comment by johanhelsing** [comment]
Was struggling with this today. @zicklag did you figure out a way around it?

**Comment by zicklag** [comment]
No, I never made any progress with this.

**Comment by Neopallium** [comment]
It is now possible to re-implement "watch for changes" support in custom `AssetIo` implementations.  It should be possible to reuse the `FilesystemWatcher` in custom `AssetIo` impls, but it does require copying some code from `FileAssetIo`.

This PR  merged a public method `AssetServer::reload_asset` which can be used to trigger the reloads as is done in `filesystem_watcher_system`.  The `reload_asset` method can be used for more specialized reloaders too (network event, editor "deploy" trigger, etc..).

I have this working in my custom `AssetIo` that works like `bevy_web_asset` crate.

**Comment by zicklag** [comment]
Sounds good, thank you!
