### ISSUE TITLE
High CPU Usage on examples

### ISSUE THREAD

**Issue by Master0r0** [bevyengine/bevy#1415]
**Bevy version**
Github latest & 0.4.0 Crate

**Operating system & version**
WIndows 10 20H2

**What you did**
Running 2d sprite example using `cargo run --example sprite`

**What you expected to happen**
A sprite rendered with little to no CPU usage

**What actually happened**
A sprite rendered while using around 20% CPU

**Additional information**
System Details:
AMD FX-8350
24GB DDR3 Memory
GTX 1660 Graphics Card

**Comment by cart** [comment]
Cpu usage should go way down if you use `cargo run --example sprite release`

**Comment by alice-i-cecile** [comment]
This is also linked to #1343.

**Comment by cart** [comment]
Ah yeah it might not go down if your particular gpu setup supports mailbox vsync (which doesn't limit framerate).

**Comment by Master0r0** [comment]
Yeah it still jumps around from 13-23% usage on a release build

**Comment by Master0r0** [comment]
Ok thanks, if this is a WIP situation then I'll just have to deal with the high usage while working on a project till it gets fixed unless theres a quick fix available?

**Comment by cart** [comment]
The quick fix is for us to revert to FIFO vsync until we have in-engine framelimiting. I'll throw together a pr now.

**Comment by cart** [comment]
#1416

**Comment by Master0r0** [comment]
That's far better thanks, will be looking forward to in-engine framelimiting and decoupled rendering.
