### ISSUE TITLE
Piping values does not work on observers

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy#14157]
## Bevy version

0.14.0

## What you did

```rust
fn main() {
    App::new().observe(a.pipe(b));
}

fn a(_: Trigger<OnAdd, Transform>) -> u32 { 3 }
fn b(_: In<u32>) {}
```

## What went wrong

I get the following compile error:
```
method not found in `fn(Trigger<'a, OnAdd, Transform>) -> u32 {a}`
```

## Additional information

Note that this works:
```rust
fn main() {
    App::new().observe(a.pipe(b));
}

fn a(_: Trigger<OnAdd, Transform>) {}
fn b() {}
```

**Comment by alice-i-cecile** [comment]
FYI, we reserve the compile failure tag for "Bevy failed to compile completely". A missing feature that *should* compile is just a bug :) The reasoning is that the former is much higher priority, due to being impossible to work around.

**Comment by janhohenheim** [comment]
@alice-i-cecile ah, I didn't know! Thanks for pointing it out.

**Comment by mrchantey** [comment]
In case anybody's looking for an alternative pattern in the meantime, triggering observers from other observers has a similar effect to system piping.

```rust
fn system1(trigger: Trigger<A>, mut commands: Commands){
  commands.trigger(B);
}

fn system2(trigger: Trigger<B>){
  //etc
}
```
