### ISSUE TITLE
Thin line in 9-sliced texture when sprite resolution is high

### ISSUE THREAD

**Issue by Litttlefish** [bevyengine/bevy#14183]
## Bevy version

0.14

## What you did

Update to 0.14

## What went wrong
![图片](https://github.com/bevyengine/bevy/assets/38809254/75d8014c-6a9c-4a90-a022-e4f53b426e4b)
As the picture shown, there are thin lines in the background.

## Additional information

The original picture resolution is 4x larger than the sprite, I don't know if this is the reason

**Comment by extrawurst** [comment]
Running into the same issue. @Litttlefish did you find a workaround for it?

**Comment by Litttlefish** [comment]
> Running into the same issue. @Litttlefish did you find a workaround for it?

nope, no idea why this happens

**Comment by marcelchampagne** [comment]
Also running into the exact same issue after upgrading to 0.14.0. Smaller buttons using 9-slices have the lines as shown in the image.

**Comment by MScottMcBee** [comment]
Bisecting the issue, I think it's caused by [the shader changes from this pr](https://github.com/bevyengine/bevy/pull/13523). It's reproducible in the `ui_texture_slice` example if you add `with_scale_factor_override`. I used `4.`.

**Comment by Jaso333** [comment]
I observe this in the examples rendered in WebGL on the bevyengine website:

![image](https://github.com/user-attachments/assets/0df75cc3-51ec-4a07-9a08-d06e92319e18)

At default UiScale, I also observe this with my own 9patch button on 0.14.1. It is even worse at higher UI scales.

**Comment by StarArawn** [comment]
I noticed this same issue but worse in a non UI or sprite renderer. I noticed the resulting slices from the slicer can have a lot of precision this can easily result in errors like this.

**Comment by Jaso333** [comment]
> Bisecting the issue, I think it's caused by the shader changes from #13523. It's reproducible in the `ui_texture_slice` example if you add `with_scale_factor_override(4.0)`
> 
> Digging in more it looks like the fact I'm using a scale factor if 4 is important. It doesn't happen if I use 1 or 2. Finding #13814, I changed the aliasing in my local branch to be `return clamp(0.0, 1.0, 0.5 - 4.0 * distance);` and it fixed the issue for me.
> 
> I'm wondering if we could have AA be a flag or something in that shader. My game has pixel art so I want to turn all AA off.

I did the same thing, except I changed the "0.5" to "1.0", as I think you need to double all terms in this calculation to change the AA threshold on the distance. This seemed to fix the problem, but I don't really know why. Maybe this change effectively disabled the anti-aliasing.

To highlight the change at UI scale factor of 8:

with "0.5" and "2.0" (the original values):
![image](https://github.com/user-attachments/assets/09f43915-05a8-40f8-97f3-a0ec27f921ce)

with "1.0" and "4.0" (this is precisely how my button should look):
![image](https://github.com/user-attachments/assets/ab38ece5-de97-4a58-92f1-b28e0463ff65)

I agree with @MScottMcBee, anti-aliasing is hard-coded to be enabled in bevy_ui, but probably shouldn't be? However, this form of anti-aliasing doesn't seem to be effective anyway, as the artifacts show for any scale or art style (not just pixel-art), so maybe it just needs correcting.

**Comment by MarcoMeijer** [comment]
This issue also applies to non 9-sliced textures

In my game I have this issue with regular ui images that are close to each other:
<img width="458" alt="Screenshot 2024-08-17 at 16 18 46" src="https://github.com/user-attachments/assets/ba530ebc-de5f-4f21-9c6d-39520d5ebd58">

This issue was not there in 0.13

**Comment by brandon-reinhart** [comment]
Ah, I saw something like this happen when my desktop scale was not 1.0.

**Comment by Litttlefish** [comment]
> This issue also applies to non 9-sliced textures
> 
> In my game I have this issue with regular ui images that are close to each other: <img alt="Screenshot 2024-08-17 at 16 18 46" width="458" src="https://private-user-images.githubusercontent.com/46689298/358850582-ba530ebc-de5f-4f21-9c6d-39520d5ebd58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjIzOTYsIm5iZiI6MTcyNTMyMjA5NiwicGF0aCI6Ii80NjY4OTI5OC8zNTg4NTA1ODItYmE1MzBlYmMtZGU1Zi00ZjIxLTljNmQtMzk1MjBkNWViZDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAwMDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwY2NmMGQ5MDkzYmU2N2U1NWFkMTRkNzY2NjZiYmJiMjBiMDY0MGIyZGU0MTQzMDEwMjRiNzUyZDVkMWY3N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lJ39s2Vagnfmne3XpSFNyp8Kb_9WtC38VMfdLnK1Z8A">
> 
> This issue was not there in 0.13

Now this issue is closed, you can try on 0.14.2🤔
if it stays still you can open a new issue I think

**Comment by alice-i-cecile** [comment]
Well, once we release 0.14.2 😂 Not out yet!

**Comment by DidItWork** [comment]
Hi, I seem to have a similar issue on Bevy 0.14.2 using a `NodeBundle` with `Display::Grid` Style and all flex columns and rows. Thin lines appear at some window sizes.

![Image](https://github.com/user-attachments/assets/7dbb0728-7c37-474a-a289-75ea8cb6e377)

![Image](https://github.com/user-attachments/assets/3b8e7a7c-a4c7-4066-8654-57c93d67fce7)

**Comment by alice-i-cecile** [comment]
That's a different bug: it's an off-by-one in our grid layout likely caused by rounding. Try updating, and it if it persists please open a new issue :)
