### ISSUE TITLE
[Feature] Runtime Dynamic Components and Systems ( To Support Scripting Initiatives )

### ISSUE THREAD

**Issue by zicklag** [bevyengine/bevy#142]
This continues from https://github.com/bevyengine/bevy/issues/114#issuecomment-672622816.

### The Goal

First off, for this issue, the purpose is **not** to create a scripting system for bevy. A scripting system that allows you to use other languages for programming Bevy games is, in the context of the official Bevy engine, outside of scope ( reference: https://github.com/bevyengine/bevy/issues/114#issuecomment-672397351 ). This will not include an FFI, or anything other than a Rust API.

What we *are* trying to do is add to the existing bevy Rust API the ability to register components and systems at runtime with the purpose of allowing *other projects* to implement different forms of scripting/modding/FFI themselves.

### Next Steps

The next step is to come up with an API proposal. The goal is to make a simple API and avoid imposing any extra cruft or otherwise stuff to think about for users that have absolutely no interest in scripting. Keep things ergonomic whether you are scripting or not.

I'm going to do some looking into the `bevy_ecs` and getting a feel for how things are currently setup. I'll probably be creating a draft PR as soon as I can, regardless of how unready it is, that will show what I'm thinking.

---

**Edit:** There's now a PR for this: #623.

**Comment by StarArawn** [comment]
I'm interested in this as I would like to create a `bevy_wren` plugin for my own purposes and perhaps share for other people to use.

We would need a way of registering and un-registering ecs at runtime if we want to support hot-reloading I think.

**Comment by joseluis** [comment]
I'm interested in this too, specialy if that means I can unregister the ECS in order to use an alternative solution.

**Comment by zicklag** [comment]
I think #623 is getting pretty close to addressing the bulk of this! :tada: I think it manages a design that will allow for runtime queries and systems without hurting the typical static queries and systems. It could use review from anybody who can manage to take a look!

**Comment by zicklag** [comment]
Latest updates on this ( see https://github.com/bevyengine/bevy/pull/623#issuecomment-796337355 for details ): some thought has gone into dynamic components ( https://github.com/bevyengine/bevy/issues/1527,  [notes](https://hackmd.io/PvQqDLUPS-iEN6wfjrPf1Q#Guide-level-feature-overview) ) and #623 is being closed in favor of more targeted developments.

**Comment by zicklag** [comment]
With the release of Bevy 0.8 and it's addition dynamic ECS features, and the demonstration of them in  https://github.com/jakobhellermann/bevy_mod_js_scripting, we're well on our way to full blown scripting and modding ability!

Things I haven't tested just yet:
  - Adding components from external languages
    - I believe this already works. I just haven't tested nor seen it demonstrated yet.
  - Adding new systems at runtime
    - This is tracked in https://github.com/bevyengine/bevy/issues/279 and work-in-progress in https://github.com/bevyengine/bevy/pull/2507

That said, I think we can close this in favor of tracking specific issues, and we can open new issues if necessary.

I'm super excited that this is becoming possible! 🥳

Thank you everybody for all your great work! 🌟
