### ISSUE TITLE
Component Lifecycle Hook for replaced values

### ISSUE THREAD

**Issue by Pixelstormer** [bevyengine/bevy#14202]
## What problem does this solve or what need does it fill?

> [Relevant Discord Discussion](https://discord.com/channels/691052431525675048/742569353878437978/1259223920825995305)

There are currently three component lifecycle hooks: `on_add`, `on_insert` and `on_remove`. Of these, only `on_insert` runs when a component is replaced with a new value, e.g. with `EntityCommands::insert()`, and only the new value is accessible to the hook. This means there is no easy way to run cleanup code for the old value in this scenario, as `on_remove` by design is not ran for this operation.

## What solution would you like?

I propose a new component lifecycle hook that runs in all cases that `on_remove` runs, as well as the above scenario. It can be thought of as a counterpart to `on_remove` in the same way that `on_insert` is a counterpart to `on_add`, in that they are mostly the same except for also running for replace operations. This new hook would run before the replace actually occurs, allowing it to access and perform cleanup for the old value, which is not possible with `on_insert`. The name can of course be bikeshed, but I think it should be called `on_drop`, as the intention is for it to run in any scenario that would result in the component value being dropped. If there are other ways a component value can be dropped that `on_remove` does not trigger for, this new hook should trigger for all those as well.

## What alternative(s) have you considered?

One workaround that is currently possible is to create a wrapper component type that has hooks to handle adding/replacing/removing the 'actual' component type, but this adds a lot of complexity and requires unavoidably cloning the component value.

**Comment by alice-i-cecile** [comment]
Great: I like the conceptual clarity of this. I think this should be done; just make sure to add the corresponding observer too.

I think `on_replace` is the name here.
