### ISSUE TITLE
Bevy Math traits don't appear on docs.rs due to only being exported via the hidden prelude

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#14243]
## Problem

The entirety of `bevy_math/common_traits` doesn't appear on docs.rs: see [searching for StableInterpolate](https://docs.rs/bevy/latest/bevy/math/trait.NormedVectorSpace.html?search=StableInterpolate) for example.

It can however be used though, if and only if you know what you're looking for!

EDIT: I don't seem to be able to use these in my own projects; I have no idea how the example is working 😅 

## Solution

This is because we only export it through the prelude, which is correctly doc hidden.

The module itself should be made `pub`, so then it shows up correctly in the docs.

**Comment by ChristopherBiscardi** [comment]
I'm pretty sure StableInterpolate didn't make it into 0.14's release

* Where it would be: https://github.com/bevyengine/bevy/blob/b231ebbc195e12ae47616748e532c8dbc24218dd/crates/bevy_math/src/common_traits.rs
* Where it is on main: https://github.com/bevyengine/bevy/blob/d0e606b87cc9ce68d16b9c31b852b5e7a02adaf3/crates/bevy_math/src/common_traits.rs#L215

**Comment by alice-i-cecile** [comment]
Okay, well, I suppose we can bump it to 0.15 and make release notes about it then :)

Easy to vendor for now at least.
