### ISSUE TITLE
Wildly inconsistent documentation on Dir2 <-> Rot2 conversion methods.

### ISSUE THREAD

**Issue by IQuick143** [bevyengine/bevy#14301]
## How can Bevy's documentation be improved?

https://github.com/bevyengine/bevy/blob/d7080369a7471e6aa9747bad41a4469092f9967b/crates/bevy_math/src/direction.rs#L219-L245

```rust
    /// Get the rotation that rotates this direction to the Y-axis.
    #[inline]
    pub fn rotation_from_y(self) -> Rot2 {
```
This docstring is imho completely backwards to what it should say, notably, it is backwards to what the docstring for `rotation_from_x` says.

## Solution

Figure out which way the methods *actually* go, and update the docstrings appropriately. (Imo the semantics on the x-axis functions are correct, and the doc strings on the y-axis functions are wrong.)

**Comment by mweatherley** [comment]
Yeah it looks like I made a copy-paste error here, the docs for the `x` versions should be correct.
