### ISSUE TITLE
State docs should inform the need for the StatePlugin to be used

### ISSUE THREAD

**Issue by Commathingy** [bevyengine/bevy#14329]
Currently the docs for using States make no mention of needing the StatePlugin to be added (Either on it's own or as part of DefaultPlugins) before initialising a state in app setup. The resulting error message is then not informative of the issue (see https://github.com/bevyengine/bevy/issues/14151)

**Comment by alice-i-cecile** [comment]
I think this should be added to `.init_state`, since this is where the error will generally originate.
