### ISSUE TITLE
3D line example broken on web

### ISSUE THREAD

**Issue by ShadowMitia** [bevyengine/bevy#14353]
## Bevy version

Bevy 0.14

## What you did

Go to 3D lines example here: https://bevyengine.org/examples/3d-rendering/lines/

## What went wrong

I only see the gray background and nothing else.

Console log shows a lot of things, I think the relevant part is:

> ERROR  Device::create_render_pipeline error: Features Features(POLYGON_MODE_LINE) are required but not enabled on the device log.target = "wgpu_core::device::global";
> log.module_path = "wgpu_core::device::global";
> log.file = "/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.21.1/src/device/global.rs";
> log.line = 1636; [wasm_example.js:435:21](https://bevy-webgl2-examples.pages.dev/3D%20Rendering/lines/wasm_example.js)
> ERROR  Handling wgpu errors as fatal by default log.target = "wgpu::backend::wgpu_core";
> log.module_path = "wgpu::backend::wgpu_core";
> log.file = "/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs";
> log.line = 2995;

I can provide more info if necessary.

## Additional information

Using Firefox 128 on Linux desktop.
Also didn't work on Firefox 128 on Android.

**Comment by ShadowMitia** [comment]
It is possible it's just fully broken, I'm trying to create lines in 2D on desktop, and I'm also not seeing anything. But no errors... And I was hoping to see what I was supposed to be getting from the web example :sweat_smile:

**Comment by mockersf** [comment]
the error is
```
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `opaque_mesh_pipeline`
    Features Features(POLYGON_MODE_LINE) are required but not enabled on the device
```

this can't work in WebGL2, `POLYGON_MODE_LINE` is not supported there

**Comment by mosure** [comment]
I see these warnings when drawing line gizmos on WebGPU /w RenderLayer specified:

```
Attribute offset (12) with format VertexFormat::Float32x3 (size: 12) doesn't fit in the vertex buffer stride (12).
 - While validating attributes[0].
 - While validating buffers[1].
 - While validating vertex state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor "LineGizmo Pipeline"]).
 ```

```
[Invalid RenderPipeline "LineGizmo Pipeline"] is invalid.
 - While encoding [RenderPassEncoder "main_transparent_pass_3d"].SetPipeline([Invalid RenderPipeline "LineGizmo Pipeline"]).
```

e.g.

```rust
        app.insert_gizmo_config(
            EditorCameraGizmoConfigGroup,
            GizmoConfig {
                render_layers: EDITOR_CAMERA_RENDER_LAYER,
                ..default()
            },
        );

...

fn draw(mut gizmos: Gizmos<EditorCameraGizmoConfigGroup>) {
        ....
        gizmos.line(
            start,
            end,
            color,
        );
}
```
