### ISSUE TITLE
`Viewport::default()` produces a viewport that always crashes

### ISSUE THREAD

**Issue by SludgePhD** [bevyengine/bevy#14355]
## Bevy version

0.11

## What you did

Set `Camera.viewport` to `Some(Viewport::default())`.

(I use `ReflectDefault` to create values in an editor, so this can't be easily worked around except by remembering not to click the wrong button)

## What went wrong

An invalid viewport is returned which promptly causes a wgpu validation error:

```
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `main_opaque_pass_3d_command_encoder`
    In a set_viewport command
    Viewport has invalid rect Rect { x: 0.0, y: 0.0, w: 0.0, h: 0.0 }; origin and/or size is less than or equal to 0, and/or is not contained in the render target (1664, 936, 1)
```

**Comment by TrialDragon** [comment]
(Marking as `S-Needs-Design` since it needs to be figured out what exactly we want to the default to be in this case since the obvious one of zero is erring / invalid).

**Comment by SludgePhD** [comment]
I believe the only viewport valid for all render target sizes is one with size 1x1 and origin (0,0)
