### ISSUE TITLE
Possibly unneccessary .system()

### ISSUE THREAD

**Issue by SpecificProtagonist** [bevyengine/bevy#1436]
**What problem does this solve or what need does it fill?**

I'm trying out Bevy for the first time. To add a system to a stage, one has to convert a function to a system using the IntoSystem trait which is automatically imported via the prelude. That confused me for a moment (where does the .system() come from? - I'm not a huge fan of extension traits being imported via wildcards) and I'm not sure that it's necessary. Of course, this is isn't a big deal, but since Bevy strives for great ergonomics, it might be worth mentioning.

**What solution would you like?**
`add_system` and similar methods could just take an `impl IntoSystem` instead of a system. Maybe that also means IntoSystem can be removed from the prelude.

**What alternative(s) have you considered?**

Leaving it as is.

**Additional context**

I'm completely new to bevy, so I might have missed a reason this isn't done.

**Comment by DJMcNab** [comment]
My expectation is that this will be a 0.6.0 feature - basically, rustc has a weird bug, but I've managed to work around it using some trickery. But I don't want to land it in 0.5.0 in case it needs to be reverted, it would create a significant amount of churn.

So this is in the pipeline. But yes, there are reasons why it wasn't done

**Comment by SpecificProtagonist** [comment]
Thanks for the prompt answer!

**Comment by jamadazi** [comment]
The reason this isn't done is because it turned out to be very tricky/difficult to do it safely without possible unsoundness.

It actually was tried briefly (in the 0.3 -> 0.4 development cycle) and then reverted due to safety issues.

People are trying to figure this out. It's hard.

**Comment by sherlockdk** [comment]
why
