### ISSUE TITLE
`Mesh` should allow iterating over the stored `MeshVertexAttribute`s

### ISSUE THREAD

**Issue by SludgePhD** [bevyengine/bevy#14365]
## What problem does this solve or what need does it fill?

Editors trying to inspect `Mesh`es currently can only iterate over the contained `MeshVertexAttributeId`s, which don't contain enough information for a decent UI (eg. the attribute name is missing).

## What solution would you like?

`Mesh` should allow iterating over the contained `MeshVertexAttribute`s.

## What alternative(s) have you considered?

A workaround is to hardcode a list of attributes to show in the editor.

**Comment by IceSentry** [comment]
One solution would be to update `Mesh::attributes()` to use `Item = (MeshVertexAttributeId, &MeshAttributeData)`, but `attributes_mut()` shouldn't do that. So I think a better solution would be to add `Mesh::atributes_data()` with not `_mut` variant and it would return `Item = (MeshVertexAttributeId, &MeshAttributeData)`
