### ISSUE TITLE
3d shapes web example crashes when enabling wireframes

### ISSUE THREAD

**Issue by aevyrie** [bevyengine/bevy#14371]
## Bevy version

https://bevyengine.org/examples/3d-rendering/3d-shapes/

WebGL and WebGPU backends are affected.

## What you did

Press space.

## What went wrong

Example freezes, logs show that the app is panicking.

```
panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `prepass_pipeline`
    Features Features(POLYGON_MODE_LINE) are required but not enabled on the device
```

**Comment by mockersf** [comment]
same as https://github.com/bevyengine/bevy/issues/14353, this can't work in wasm
