### ISSUE TITLE
bevy_reflect: Consider API for getting kind info

### ISSUE THREAD

**Issue by torsteingrindvik** [bevyengine/bevy#14378]
## What problem does this solve or what need does it fill?

Let's say I have this:

```rust
if let bevy_reflect::ReflectMut::Struct(s) = reflected.reflect_mut() {
  let Some(bevy_reflect::TypeInfo::Struct(info)) = s.get_represented_type_info() else {
    return;
  }
}
```

In order to get the `StructInfo` type I need to do this extra match where I specifically ask for a `StructInfo`.
But since I already got `s` from `Struct(s)`, from a usage perspective it feels like it should be implied that I want a `StructInfo` and not an e.g. `EnumInfo`.

## What solution would you like?

```rust
if let bevy_reflect::ReflectMut::Struct(s) = reflected.reflect_mut() {
  let Some(info) = s.get_kind_info() else {
    return;
  }
}
```

Something along the lines of the above, but also for `MapInfo`, `ListInfo`, etc.

**Comment by alice-i-cecile** [comment]
Seems reasonable. Want to put together a PR?

**Comment by MrGVSV** [comment]
Yeah this would be a good improvement. Although, rather than `get_kind_info` maybe we should call it `get_represented_kind_info` since it's the info of the represented type that we want (and for parity with the method on `Reflect`).

**Comment by torsteingrindvik** [comment]
> Seems reasonable. Want to put together a PR?

Taking a look.

> maybe we should call it `get_represented_kind_info`

Sounds good

**Comment by torsteingrindvik** [comment]
I did a draft of the impl for struct. Is `Option<&KindInfo>` ok? I see `TypeInfoError` exists too.

If the quick draft doesn't raise any immediate concerns I'll add impls for the other kinds
