### ISSUE TITLE
Animation: Layered Blend Per Bone / Additive Blending

### ISSUE THREAD

**Issue by ethereumdegen** [bevyengine/bevy#14395]
## What problem does this solve or what need does it fill?

 I want to be able to have apply a normal 'running' animation to my characters whole body,  but then also be able to apply a bone-layer-masked animation to just the torso of the character on TOP of that running animation at will.  

## What solution would you like?

I would like for the bevy animation system to be able to support 'Layered Blend Per Bone' , the ability to apply an animation to a particular set of bones (  by bone [node] name ).   Ideally, I  also want the blend to apply in such a way that my layered animation is FULLY expressed,  not averaged down by a division of the total weights of all animations.    This is because I want the sword slash on the torso to look complete and not weird like it does when trying to blend it in 0.14 . 

To be honest, an example with a humanoid who is running and sometimes doing a sword slash would be preferable to the fox example because i dont think the fox example is powerful enough to full express and capture what is needed.

**Comment by ethereumdegen** [comment]
One way we could do this simply is by allowing for the animation system to define a 'BoneSet' which is a group of bones, and then you can have   weights PER bone set as opposed to weights per the entire AnimGraph .

**Comment by pcwalton** [comment]
#15013 implements most of this, but not the additive blending part.

**Comment by pcwalton** [comment]
https://github.com/bevyengine/bevy/pull/15631 implements this.
