### ISSUE TITLE
0.14 Windows 11 bug: Invisible App Window stuck at frame 1 and never render after

### ISSUE THREAD

**Issue by wentao** [bevyengine/bevy#14398]
## Bevy version

0.14 Release

## \[Optional\] Relevant system information

- Rust version: cargo 1.79.0 (ffa9cf99a 2024-06-03)
- os: "Windows 11 Pro", kernel: "22631", cpu: "AMD Ryzen 9 7900X3D 12-Core Processor", core_count: "12", memory: "31.1 GiB"
- "NVIDIA GeForce RTX 4090", vendor: 4318, device: 9860, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "536.99", backend: Vulkan

## What you did

I run the following setup

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                visible: false,
                ..default()
            }),
            ..default()
        }))
        .add_systems(Update, make_visible)
        .run();
}

fn make_visible(mut window: Query<&mut Window>, mut frames: Local<u32>) {
    *frames += 1;
    info!("count {}", *frames);
    if *frames == 3 {
        window.single_mut().visible = true;
    }
}
```
## What went wrong

I'm not seeing the app Window showing up, and the log was like

```
2024-07-19T18:21:46.423720Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Pro", kernel: "22631", cpu: "AMD Ryzen 9 7900X3D 12-Core Processor", core_count: "12", memory: "31.1 GiB" }
2024-07-19T18:21:46.666424Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 4090", vendor: 4318, device: 9860, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "536.99", backend: Vulkan }
2024-07-19T18:21:46.817481Z  INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
2024-07-19T18:21:46.827137Z  INFO scene_viewer: count 1
```

The app doesn't exit and it stuck with frame count 1. No more output.

This is not the case on Mac 0.14, or Windows 0.13

**Comment by alice-i-cecile** [comment]
Can you try to reproduce this further? Does this occur with just `DefaultPlugins`? Does this occur in `winit`'s examples?

**Comment by wentao** [comment]
I'm not sure if I follow your recommendation. My current setup is using `DefaultPlugins`. What are the changes do you refer to?

Also where can I find the `winit` example?

**Comment by alice-i-cecile** [comment]
Your example has many other lines of code. We should eliminate all of the extra ones to try and figure out why this is failing.

For the `winit` examples, please see https://github.com/rust-windowing/winit/tree/master/examples

**Comment by wentao** [comment]
Ok. I've simplified the code by removing the `LogPlugin` setup. I don't know how much I can reduce lines of code further. The key logic to reproduce the bug is setting the window visibility to false and then reset it to true after a few frames.

I haven't used rust-windowing/winit before, I don't quite understand what do you want me to do by pointing me to winit examples. If your intention is to ask me to digging into whether this is a winit bug, I'm probably not the right person to do that at the moment since I'm busy with building my game on bevy engine.

As far as I can tell: The above code works fine with bevy 0.13, but not with bevy 0.14.

**Comment by alice-i-cecile** [comment]
> The key logic to reproduce the bug is setting the window visibility to false and then reset it to true after a few frames.

Fantastic, that's what I was hoping for. Thanks for the report; we should be able to investigate this further from here :)

**Comment by Katsutoshii** [comment]
I'm running into the same issue. From my testing, it seems like when the window is invisible on Windows the Update schedule runs only once, so if you don't set the window to visible withing that first frame the app gets stuck.

**Comment by mockersf** [comment]
fixed in https://github.com/bevyengine/bevy/pull/14155
