### ISSUE TITLE
Allow bundle to be inserted without overwriting duplicate components

### ISSUE THREAD

**Issue by jpetkau** [bevyengine/bevy#14397]
## What problem does this solve or what need does it fill?

Say you have a simulation that can run headless. In headless mode, entities still get a `TransformBundle`, but don't need any rendering info. In normal mode, they get a full `PbrBundle`.

Or maybe you don't have headless, but just want the simulation-related code to not have to depend on rendering stuff like materials and meshes.

A nice way to implement this is to have the simulation code add the TransformBundle with positions etc., and have a rendering system with `Query<Entity, Added<MyThing>>` which inserts a `PbrBundle` when active.

But `PbrBundle` contains `Transform`, so if you do this, it will clobber the existing transform.

[Note that `Transform` is just an example here, albeit the most common one. The issue applies to Bundles in general.]

## What solution would you like?

It would be helpful to have a variant of `insert()` that gives precedence to the *existing* components instead of the new ones. E.g. maybe `insert_if_new()`.

## What alternative(s) have you considered?

The name could be bikeshedded of course.

`insert()` could be changed to just never overwrite an existing component. Personally I've never encountered a situation where the "replace" behavior is what I want, but changing `insert`'s behavior now would certainly be a large and disruptive change and probably isn't feasible even if everyone agreed it was desirable.

Instead of a new method name, the "noclobber" behavior could come from some magic wrapper in the bundle arguments. E.g.

    e.insert(PbrBundle { ... }.no_clobber());

One advantage of this approach is you could have *three* choices: clobber, no_clobber, and error. But it's more complex (e.g. you would have to define what happens in case of nested combinations of different clobber choices. Yuk.)

Instead of changing `insert`, bundles could gain a "subtract" operation. E.g. `PbrBundle { ... }.without::<TransformBundle>()`.

A workaround for now is to have your `add_rendering_components` system from the example above also query for `Transform` and any similar components, and explicitly copy them into the newly inserted bundle. The downside of this is that you have to know about a bunch of specific fields in the bundle, and if the simulation starts using other components you have to update the renderer to manually avoid clobbering those too. It also makes a spurious change to the `Transform` (or whatever components are involved), which the simulation has to be careful not to be affected by.

An alternative workaround is to not insert e.g. `PbrBundle`, but instead the various components it uses. But this is fragile since the bundle components tend to change between Bevy versions.

## Additional context

https://github.com/bevyengine/bevy/issues/6622 - related discussion of documenting the existing behavior.

I think the implementation would be pretty straightforward:
* In `BundleInserter`, add a field `if_exists` for whether keep/replace behavior is desired.
* Add new `insert_if_new` methods, which set `BundleInserter.if_exists = Keep`
* In `BundleInfo::write_components`, in the `ComponentStatus::Mutated` case, if `if_exists==Keep`, do nothing instead of calling `column.replace`.

I'd be happy to make this change if there's a chance it'll be accepted.

**Comment by alice-i-cecile** [comment]
I would accept an additional method that did this (on World, EntityWorldMut and Commands). In the long-term, I expect that required components (see https://github.com/bevyengine/bevy/discussions/14437) will have large implications for this space.

**Comment by ariofrio** [comment]
Is this the same as #2054?

**Comment by jpetkau** [comment]
> Is this the same as #2054?

Yes, it looks basically the same. (I did search for duplicates before filing this, honest!)

**Comment by jpetkau** [comment]
@alice-i-cecile I have a PR for this (#14646), if you're still ok accepting it.
