### ISSUE TITLE
Generate warnings when incorrectly accessing Transform or GlobalTransform

### ISSUE THREAD

**Issue by aevyrie** [bevyengine/bevy#1439]
**What problem does this solve or what need does it fill?**

Updating `Transform` late or reading `GlobalTransform` early are very common issues that result in a number of help requests and bugs in general.

**What solution would you like?**

Generate a warning in debug mode any time a `Transform` is ever mutated after `GlobalTransform` is propagated or a `GlobalTransform` is accessed before it has been updated that frame.

**What alternative(s) have you considered?**

1. Do nothing, accept this as a source of error.
2. Develop some general method of specifying component dependencies.
3. Keep positions from the last frame in `GlobalTransform` and propagate `Transform`s at the end of the frame to ensure that worst case, systems accessing it will be a frame out of date, but still work. This could be accompanied with an error message.

**Comment by MinerSebas** [comment]
Something else to consider is that most User Code should only read from GlobalTransform, as the Value is managed and overrriden by Bevy itself.

**Comment by mockersf** [comment]
> Generate a warning in debug mode

With the general recommendation being "run in release", I wonder if it wouldn't be better to add a "debug" feature enabled by default (probably with a better name though... "training-wheels"? "clippy"?)
I think disabling default features to pick only the ones you want when you release a game is the good thing to do (anyway it's what I do)

**Comment by Ratysz** [comment]
> Something else to consider is that most User Code should only read from GlobalTransform, as its Values are managed and overrriden by Bevy itself.

#1460 should take care of that.

**Comment by alice-i-cecile** [comment]
For reference, this should be improved by #68.

**Comment by nicopap** [comment]
`GlobalTransform` doesn't have a `Transform` field anymore, and since, #7134 it's not even possible to mutate it.

The 1-frame lag issue is still an open question, but  it seems very difficult to design a system to catch it and warn users about it.
