### ISSUE TITLE
Segmentation fault trying to run 2d_shapes example on NixOs wayland with AMD GPU

### ISSUE THREAD

**Issue by reDpz** [bevyengine/bevy#14425]
## Bevy version
0.14.0

## \[Optional\] Relevant system information

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```ignore
`AdapterInfo { name: "AMD Radeon RX 5600 XT", vendor: 4098, device: 29471, device_type: DiscreteGpu, driver: "AMD open-source driver", driver_info: "2023.Q4.2 (LLPC)", backend: Vulkan }`
```

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

- [`wgpu`](https://github.com/gfx-rs/wgpu) for rendering problems
- [`winit`](https://github.com/rust-windowing/winit) for input and window management
- [`gilrs`](https://docs.rs/gilrs/latest/gilrs/) for gamepad inputs

## What you did

Create a new project where main.rs is just the [2d_shapes.rs example](https://github.com/bevyengine/bevy/blob/latest/examples/2d/2d_shapes.rs)

## What went wrong

The program has a segmentation fault almost immediately after launching. Sometimes there is an empty window that manages to come up (no shapes drawn yet) that crashes instantly. While segfaulting the audio output begins repeating.

Here is the log from running it:
```
❯ cargo run
    Finished dev [optimized + debuginfo] target(s) in 0.15s
     Running `target/debug/square-test`
2024-07-21T21:32:04.879817Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux 24.05 NixOS", kernel: "6.6.40", cpu: "AMD Ryzen 5 5600X 6-Core Processor", core_count: "6", memory: "15.5 GiB" }
2024-07-21T21:32:04.933958Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 5600 XT", vendor: 4098, device: 29471, device_type: DiscreteGpu, driver: "AMD open-source driver", driver_info: "2023.Q4.2 (LLPC)", backend: Vulkan }
2024-07-21T21:32:05.010923Z  INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
zsh: segmentation fault (core dumped)  cargo run
```

## Additional information

I've tried running the same project on my Arch machine and it runs just fine on it, seems this is just an issue related to NixOS

Flake i used:
```nix
{
  description = "Bevy flake";

  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system};
      in {
        devShell = with pkgs; mkShell
          rec {
            nativeBuildInputs = [
              makeWrapper
              pkg-config
            ];

            buildInputs = [
              zstd
              alsa-lib
              libxkbcommon
              udev
              vulkan-loader
              wayland
              xorg.libX11
              xorg.libXcursor
              xorg.libXi
              xorg.libXrandr
            ];

            LD_LIBRARY_PATH = lib.makeLibraryPath buildInputs;
          };
      });
}
```

- workarounds that you used
    - I tried enabling the "wayland" feature since I was on hyprland, the issue persists. I switched to xorg and enabled the x11 feature and the issue persists there too.
- links to related bugs, PRs or discussions
    - #13753
    - Should note that the default application does compile and run for me.

**Comment by BD103** [comment]
Could you please run this through `gdb` to find the location of the segfault? I can probably find a link explaining how to do it, if you need help. :)

**Comment by reDpz** [comment]
that would be nice if you could send that link

**Comment by BD103** [comment]
Yup!

Open up the repository in the terminal and run the following:

```bash
# Build the example into an executable.
cargo build --example 2d_shapes

# Open up the executable in LLDB, a debugger. (GDB is another one, but I don't have it installed.)
rust-lldb target/debug/examples/2d_shapes

# You will know that the interactive program works when it runs a bunch of commands, then leaves you with
# a prompt that starts with `(lldb)`. Let's run the executable:
(lldb) run

# You should see a message that it segfaulted. Now, let's print the backtrace:
(lldb) bt

# Copy that, and you're good to go! Let's exit out of LLDB:
(lldb) exit
```

The backtrace will tell us what functions were run before the program segfaulted, so we can figure out where to look for the bug.

Tell me if you have any issues, like if LLDB isn't installed!

**Comment by reDpz** [comment]
Running the program with lldb results in the following:
```sh
rust-lldb target/debug/examples/2d_shapes

(lldb) run
Process 12504 launched: '/home/redpz/nixprojects/bevy/target/debug/examples/2d_shapes' (x86_64)
2024-07-22T21:13:35.056570Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux 24.05 NixOS", kernel: "6.6.41", cpu: "AMD Ryzen 5 5600X 6-Core Processor", core_count: "6", memory: "15.5 GiB" }
2024-07-22T21:13:35.076879Z  WARN winit::platform_impl::linux::x11::xdisplay: error setting XSETTINGS; Xft options won't reload automatically
Process 12504 stopped and restarted: thread 1 received signal: SIGCHLD
Process 12504 stopped and restarted: thread 1 received signal: SIGCHLD
2024-07-22T21:13:35.657447Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 5600 XT", vendor: 4098, device: 29471, device_type: DiscreteGpu, driver: "AMD open-source driver", driver_info: "2023.Q4.2 (LLPC)", backend: Vulkan }
Process 12504 stopped and restarted: thread 1 received signal: SIGCHLD
2024-07-22T21:13:36.181646Z  INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
2024-07-22T21:13:36.182129Z  INFO winit::platform_impl::linux::x11::window: Guessed window scale factor: 1
Process 12504 stopped
* thread #5, name = 'Async Compute T', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x8)
    frame #0: 0x00007fffb549fdcd amdvlk64.so`___lldb_unnamed_symbol50394 + 29
amdvlk64.so`___lldb_unnamed_symbol50394:
->  0x7fffb549fdcd <+29>: movzbl 0x8(%rsi), %esi
    0x7fffb549fdd1 <+33>: movslq (%rdx,%rsi,4), %rax
    0x7fffb549fdd5 <+37>: addq   %rdx, %rax
    0x7fffb549fdd8 <+40>: jmpq   *%rax
```

Looks like it can't find amdvlk64.so?
I did a cursory google search "nixos amdvlk64.so" and found this [reddit thread](https://www.reddit.com/r/NixOS/comments/17i7zeb/vulkan_on_amdgpu_drivers_partially_not_working/) where one user points out that adding
```nix
VK_ICD_FILENAMES="/run/opengl-driver/share/vulkan/icd.d/radeon_icd.x86_64.json:/run/opengl-driver-32/share/vulkan/icd.d/radeon_icd.i686.json"
```
fixed the issue for them.

So the updated `flake.nix` would look like: 
```nix
{
  description = "Bevy flake";

  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system};
      in {
        devShell = with pkgs; mkShell
          rec {
            nativeBuildInputs = [
              makeWrapper
              pkg-config
            ];

            buildInputs = [
              zstd
              alsa-lib
              libxkbcommon
              udev
              vulkan-loader
              wayland
              xorg.libX11
              xorg.libXcursor
              xorg.libXi
              xorg.libXrandr
            ];

            LD_LIBRARY_PATH = lib.makeLibraryPath buildInputs;
            VK_ICD_FILENAMES="/run/opengl-driver/share/vulkan/icd.d/radeon_icd.x86_64.json:/run/opengl-driver-32/share/vulkan/icd.d/radeon_icd.i686.json";
          };
      });
}
```
Running now I get the expected output without any segfaults.
![image](https://github.com/user-attachments/assets/0194e144-9149-49c0-afab-afa673c9ef1a)


Full backtrace: https://pastebin.com/f7qQp8bi if it helps in any way.

Thank you so much for telling me to use rust-lldb again since it helped solve the problem myself.

I think it would be helpful for others to include the line `VK_ICD_FILENAMES="/run/opengl-driver/share/vulkan/icd.d/radeon_icd.x86_64.json:/run/opengl-driver-32/share/vulkan/icd.d/radeon_icd.i686.json";`  in shell.nix in the [docs/linux_dependencies.md](https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md#nix)

**Comment by BD103** [comment]
I'm glad you were able to figure it out! Could you open up a pull request adding a note to the NixOS section on your fix? It might be happen to all NixOS users, but it would be great to have it documented.

**Comment by BD103** [comment]
For now, I'm going to mark this as solved. Have a great day!
