### ISSUE TITLE
Add `AssetPath::exists`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#14427]
## What problem does this solve or what need does it fill?

Conditionally loading assets if a matching pattern exists is useful for data-driven behavior: you may only want to load a sound effect if a file with a matching name exists.

Checking whether the file is present `Path::exists` is the obvious solution, but is actually a footgun.
`Path` is an absolute path, relative to filesystem, while `AssetPath` is returned relative to the `assets` folder that Bevy is configured to use.

## What solution would you like?

Add `AssetPath::exists`, which pre-parses the path.

## What alternative(s) have you considered?

We could also spin out something that returns a check further down the asset pipeline: whether an asset exists and whether a correct loader is found for example.

That would need to be a method on `AssetServer`.

**Comment by viridia** [comment]
See #12210

**Comment by ShreyK** [comment]
Hello, 

@alice-i-cecile  I wish to take this issue on as my first PR.
I was thinking of using a default transparent/opaque image along with outputting an ERROR message indicating the AssetPath does not exist.

I found some small, base64 encoded strings online:
# Gif
`data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=`
![image](https://github.com/user-attachments/assets/167c5332-3127-4ed2-b41c-64d07ae75cf5)

# Png: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=`
![image](https://github.com/user-attachments/assets/0f021cf8-e624-4101-a943-9550d6767455)

Let me know what you think

**Comment by alice-i-cecile** [comment]
Hey, thanks! I think more fallback assets are reasonable, but we should open a new issue to discuss that :)

For now, feel free to add the simple `AssetPath::exists` and we can close this one out.

**Comment by alice-i-cecile** [comment]
#15671 has a much better design to this core problem. Do that instead.
