### ISSUE TITLE
Add a rect field to UiImage

### ISSUE THREAD

**Issue by MarcoMeijer** [bevyengine/bevy#14424]
## What problem does this solve or what need does it fill?

Currently it is impossible to render a region of an image in the UI without using a texture atlas.

## What solution would you like?

Adding an optional rect field to UiImage that works the same as the rect field in Sprite.

## What alternative(s) have you considered?

Using a texture atlas, but this doesn't make sense in all cases.

**Comment by benfrankel** [comment]
A few steps away from `UiImage == Sprite` convergence :smile:

`Text` is the same component for both UI and world-space, so I _think_ it would make sense for image as well. Anyways this is off-topic :p

**Comment by MarcoMeijer** [comment]
@benfrankel I would also be in favor if they are the same component. I think custom_size could work in the UI, but I don't think anchor makes sense at all. So that either needs to be put in a seperate component, or it would just be ignored by the ui.
