### ISSUE TITLE
Unify `CursorIcon` management.

### ISSUE THREAD

**Issue by mintlu8** [bevyengine/bevy#14433]
## What problem does this solve or what need does it fill?

Having multiple sources of `CursorIcon` management (like `bevy_egui`) in a project can lead to confusing bugs. 

## What solution would you like?

Have `CursorIcon` be reverted by bevy on `First` based on a resource like `DefaultIcon`. "Backends" should only write to it if needed to minimize conflicts.

## What alternative(s) have you considered?

Keep things as is?

**Comment by alice-i-cecile** [comment]
I think this will be covered with a proper solution to #14351 / #9557.
