### ISSUE TITLE
Bevy UI: image doesnt work with width: Val::Auto

### ISSUE THREAD

**Issue by aMyTimed** [bevyengine/bevy#14452]
## Bevy version

0.14

## What you did

```rust
builder.spawn((
    NodeBundle {
        style: bevy::prelude::Style {
            height: Val::Px(logo_height),
            width: Val::Auto,
            flex_shrink: 0.,
            ..default()
        },
        ..default()
    },
    UiImage::new(asset_server.load("logo.png")),
));
```

## What went wrong

Doesn't show up with width set to auto, when i specify specific pixel value it does show up indeed

It's in a flex row with width set to 100%

**Comment by ickshonpe** [comment]
Not a bug I think. You need to add the `UiImageSize::default()` and `ContentSize::default()` components to your bundle, then it should work. Without those two components, the UI layout system doesn't account for the dimensions of the image and just allots it zero space in the layout.

**Comment by aMyTimed** [comment]
ahh i see that makes sense
