### ISSUE TITLE
Slow memory leak

### ISSUE THREAD

**Issue by re0312** [bevyengine/bevy#14463]
## Objective
bevy_main

Windows11,Nv 4070ti ,13600kf

## What you did
cargo run --release --example many_cubes

I went to have a meal and when I came back, I discovered that the memory usage had increased significantly.
after profiling , I identified a memory leak of approximately 100 KB/s (at 400 fps).

The memory leak appears to be positively correlated with frame rate.

This issue can also be reproduced in the 3d_scene , resulting in a faster leak (500KB/s 1600fps) if you enable AutoNoVsync.

**Comment by alice-i-cecile** [comment]
Does this occur on our 2D examples?

**Comment by re0312** [comment]
@alice-i-cecile  looks like a wgpu bug ,bisect to #13186

**Comment by Friz64** [comment]
I bet this will be resolved by an update to wgpu 22. There have been lots of fixes/improvements to resource tracking in that release.

**Comment by re0312** [comment]
fixed by #14401
