### ISSUE TITLE
Workflow for working with prefab entities

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1446]
**What problem does this solve or what need does it fill?**

Prefabs allow users to rapidly add copies of predefined entities to their game, and create variations on them.

**What solution would you like?**

The basic workflow would be:
1. Create some interesting prefab entities in their own `World` either using its own systems, directly from code or by reading in a serialized format.
2. Turn an entity into its component bundle.
3. Create a new entity from that component bundle, with variations as needed.
4. Use addition-detecting systems (or maybe `State` on_enter systems?) to finish initializing the entity in the main game world.

There are a few things we'd need to have this work:
1. Multiple, interacting `Worlds`.
2. A way to turn a created entity back into a bundle. 
3. A nice pattern for cloning an entity that allows you to change some of its components. If you have a bundle from 2., you could probably get away with `.spawn(cloned_entity_bundle).with(modified_component)`, but it would need to be clear that `.with` is overwriting.

**What alternative(s) have you considered?**

Use component bundles with the struct-update Default pattern used in e.g. `SpriteBundle`.

This works quite well for statically defined prefabs, which can each get their own type. I'm not sure it works correctly (or naturally) for prefabs that are created dynamically or loaded from a serialized format. You would need to create new Bundles at runtime, which I'm not sure you could do.

The functionality needed all seems useful for other purposes though, and the pattern seems quite natural, so it may still be worthing pushing users towards it even if those barriers can be overcome.

**Additional context**

This issue ties into discussion in #255, although it doesn't actually use `Scenes` to accomplish its goals.

This issue was prompted by [this](https://discord.com/channels/691052431525675048/742884593551802431/810349051115077652)  conversation on Discord. 

Multiple interacting `Worlds` was mentioned in #1343 for decoupling graphics and physics.

**Comment by alice-i-cecile** [comment]
In order to turn a created entity into a bundle again, we can borrow from the approach taken in [`DynamicScene`](https://github.com/bevyengine/bevy/blob/a880b5450829411b0248e47cc066915234371d86/crates/bevy_scene/src/dynamic_scene.rs#L30)

**Comment by TheRawMeatball** [comment]
Something to consider is how this would interact with #1442.

**Comment by Davier** [comment]
I believe that scenes are the intended solution for that, what feature are they missing?

**Comment by DarkMara** [comment]
> I believe that scenes are the intended solution for that, what feature are they missing?

That's what I tried initially, but when you spawn a scene, there is no way to edit components on the Entity, or even to know what entity was spawned. Scenes are spawned through [SceneSpawner::spawn_dynamic](https://github.com/bevyengine/bevy/blob/d021a3c3748ca921fa7c0aa94bfb09e6f30090d0/crates/bevy_scene/src/scene_spawner.rs#L50).

For example, if you want to spawn a prefab that you saved as a scene, there is no way to spawn it at a specific location.

**Comment by Davier** [comment]
> That's what I tried initially, but when you spawn a scene, there is no way to edit components on the entity, or even to know what entity was spawned. Scenes are spawned through [SceneSpawner::spawn_dynamic](https://github.com/bevyengine/bevy/blob/d021a3c3748ca921fa7c0aa94bfb09e6f30090d0/crates/bevy_scene/src/scene_spawner.rs#L50).
> 
> For example, there is no way to spawn a scene at a specific location, which is a common thing to do with prefabs.

You can do the following:
1. load a `Scene` from a file
2. use `DynamicScene::from_scene`
3. the dynamic scene contains all entities that will be spawned and their components, they can be reflected on and modified (for instance to change their `Transform`)
4. use `DynamicScene::apply_to_world` to actually spawn the entities

Step 3 definitely needs a better API, but it's already possible. How would you want to do it? How about a method to get an entity from its name, and a component from its type?

Step 4 needs to be in an exclusive system, we should look into using commands to queue it instead.

Aside from that, there are still some issues when spawning a deserialized scene. I'm working on it in #1395 but it's waiting for review.

**Comment by Davier** [comment]
Actually, it seems it would be easier to use `Scene` instead of `DynamicScene`. They contain their own world that you can query and modify, and when done you spawn them with a `SpawnScene` or `SpawnSceneAsChild` command.

**Comment by DarkMara** [comment]
I am loading my prefabs from a JSON file and then converting each one into a dynamic scene at runtime. I am doing this because Bevy does not have an editor, so I use an editor to set up my entities and then save it as JSON. Is it possible to do this with a Scene instead of DynamicScene?

I think the idea is that prefabs always have a root entity. In Unity they do at least. Not sure about Godot. Would it be worth it to have a special type of scene for prefabs, that are always guaranteed to have a single root entity? Then you won't have to get the entity by name at least.

**Comment by DarkMara** [comment]
Also, would that workflow work if you wanted to spawn hundreds of copies of a prefab? It seems like you'd have to make hundreds of scenes (so that you can modify the Transform on each one), and then spawn a single entity from each one. I could be wrong but it doesn't sound efficient.

**Comment by Davier** [comment]
> Is it possible to do this with a Scene instead of DynamicScene?

You can convert a `DynamicScene` to a `Scene` with `get_scene`.  At a glance I also don't see why you couldn't directly convert your JSON into a `Scene`.

>I think the idea is that prefabs always have a root entity.

You can use the `SpawnSceneAsChild` command to spawn a `Scene` as a child of the current entity.

>Also, would that workflow work if you wanted to spawn hundreds of copies of a prefab? 

The scene is not changed when you spawn it, its entities are just copied into the app's `World`, so it can be reused. However, if you want to spawn a lot of copies at the same time, and modify each of them, you will need to use an exclusive system and call `SceneSpawner::spawn_sync` directly.

**Comment by DarkMara** [comment]
I don't understand why `SceneSpawner::spawn_sync` returns an `InstanceId`, but `spawn_dynamic_sync` doesn't. At least now that I know I can use a `Scene` instead, I have a way to get the entities that were spawned. 

I think there should be a way to do this without using an exclusive system though. It would be best to be able to do all of this with `Commands` and queue the modifications after spawning the prefab.

**Comment by alice-i-cecile** [comment]
Closing in favor of #3887.
