### ISSUE TITLE
Shader hot reloading does not work for shader loaded in FromResources

### ISSUE THREAD

**Issue by guimcaballero** [bevyengine/bevy#1449]
**Bevy version**

Master

**Operating system & version**

MacOs 10.14.6

**What you did**

Loaded a shader in `FromResources` instead of in a startup system. 

`AssetServer::watch_for_changes` is being called, both on the `FromResources` method and on a startup system.

**What you expected to happen**

Shader should have hot reloading, as when loaded from a startup system.

**What actually happened**

Shader isn't being reloaded.

Other shaders that are being loaded from a system do have reloading enabled.

**Additional information**

Here's a minimal example, which is a changed version of the current `hot_shader_reloading.rs` example:

```rust
use bevy::{
    prelude::*,
    render::{
        mesh::shape,
        pipeline::{PipelineDescriptor, RenderPipeline},
        shader::ShaderStages,
    },
};

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .init_resource::<ShaderResource>()
        .add_startup_system(setup.system())
        .run();
}

struct ShaderResource {
    vertex: Handle<Shader>,
    fragment: Handle<Shader>,
}
impl FromResources for ShaderResource {
    fn from_resources(resources: &Resources) -> Self {
        let asset_server = resources.get_mut::<AssetServer>().unwrap();

        // Does nothing
        asset_server.watch_for_changes().unwrap();

        ShaderResource {
            vertex: asset_server.load::<Shader, _>("shaders/hot.vert"),
            fragment: asset_server.load::<Shader, _>("shaders/hot.frag"),
        }
    }
}

fn setup(
    commands: &mut Commands,
    asset_server: ResMut<AssetServer>,
    mut meshes: ResMut<Assets<Mesh>>,
    material: Res<ShaderResource>,
    mut pipelines: ResMut<Assets<PipelineDescriptor>>,
) {
    // Does nothing
    asset_server.watch_for_changes().unwrap();

    let pipeline_handle = pipelines.add(PipelineDescriptor::default_config(ShaderStages {
        vertex: material.vertex.clone(),
        fragment: Some(material.fragment.clone()),
    }));
    commands
        .spawn(MeshBundle {
            mesh: meshes.add(Mesh::from(shape::Cube { size: 2.0 })),
            render_pipelines: RenderPipelines::from_pipelines(vec![RenderPipeline::new(
                pipeline_handle,
            )]),
            transform: Transform::from_xyz(0.0, 0.0, 0.0),
            ..Default::default()
        })
        .spawn(PerspectiveCameraBundle {
            transform: Transform::from_xyz(3.0, 5.0, -8.0)
                .looking_at(Vec3::default(), Vec3::unit_y()),
            ..Default::default()
        });
}
```

As a side note, adding another system that loads the shader but doesn't use the handle, activates hot reloading. For example:

```rust
fn asset_server_changes(asset_server: ResMut<AssetServer>) {
    asset_server.watch_for_changes().unwrap();

    // HACK To get hot reloading
    asset_server.load::<Shader, _>("shaders/hot.frag");
    asset_server.load::<Shader, _>("shaders/hot.vert");
}
```

**Comment by guimcaballero** [comment]
I've done a bit of digging, and here's what I've found: `FileAssetIo::watch_for_changes` seems to be called correctly before any of the shaders are loaded, and `FileAssetIo::watch_path_for_changes` is being also called for both the fragment and vertex shader when loaded in `FromResources`. This seems to be called correctly too:

https://github.com/bevyengine/bevy/blob/d021a3c3748ca921fa7c0aa94bfb09e6f30090d0/crates/bevy_asset/src/io/file_asset_io.rs#L84-L86

As I understand it, the watcher is set up successfully, and the issue is in actually reloading the asset. I don't understand the asset section of Bevy enough to know if this is true though.

I'd be very glad if anyone can point me in the right direction for trying to implement a fix for this issue.

**Comment by SecretPocketCat** [comment]
It also doesn't work when loading the shaders from a `SystemSet::on_enter` system, only when using the startup system (both for 0.5 and main).

> thread 'Compute Task Pool (1)' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\SecretPocketCat\.cargo\git\checkouts\bevy-f7ffde730c324c74\4fed2ee\crates\bevy_render\src\pipeline\pipeline_compiler.rs:82:49

**Comment by james7132** [comment]
`FromResources` is no longer a part of the rendering system. If you can still reproduce this in the post-0.6 rendering system, please reopen this issue or file a new one.
