### ISSUE TITLE
`BorderColor` should impl `From<Color`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#14497]
## What problem does this solve or what need does it fill?

This is a common and convenient idiom elsewhere in the engine to make working with colors easier.

## What solution would you like?

Implement the `From` trait.

**Comment by 68317fa2** [comment]
Isn't It already implemented?
https://github.com/bevyengine/bevy/blob/ca3d8e8760f46d4308ba2fdc00435d00afd96989/crates/bevy_ui/src/ui_node.rs#L1736C1-L1740

**Comment by 68317fa2** [comment]
Isn't it already implemented?
https://github.com/bevyengine/bevy/blob/ca3d8e8760f46d4308ba2fdc00435d00afd96989/crates/bevy_ui/src/ui_node.rs#L1734-L1740

**Comment by alice-i-cecile** [comment]
Hmm, evidently. I wonder why that wasn't getting picked up.
