### ISSUE TITLE
Unlabelled closure system in `Startup` created by `setup_state_transitions_in_world`

### ISSUE THREAD

**Issue by bravely-beep** [bevyengine/bevy#14504]
## Bevy version

0.14.0

## What you did

Create a system that takes `&mut World` as a parameter, add it to the `Startup` schedule, and turn on ambiguity detection.

## What went wrong

Bevy reports an ambiguity between my system and `{{closure}}`. I cannot mark this ambiguity as intentional as the `{{closure}}` system is not part of any system sets.

## Additional information

I traced the source of this unlabelled system to [here](https://github.com/bevyengine/bevy/blob/b231ebbc195e12ae47616748e532c8dbc24218dd/crates/bevy_state/src/state/transitions.rs#L205).

**Comment by alice-i-cecile** [comment]
We can add a `SystemSet` label to this, which should resolve the problem easily.

**Comment by reima** [comment]
It seems that this has been fixed incidentally in https://github.com/bevyengine/bevy/pull/14208 by removing said `{{closure}}` system.

**Comment by alice-i-cecile** [comment]
Thanks!
