### ISSUE TITLE
alien_cake_addict example - game board does not appear

### ISSUE THREAD

**Issue by The5-1** [bevyengine/bevy#1450]
**Bevy version**

master 7be096a

**Operating system & version**

Windows 10

**What you did**

Running the alien alien_cake_addict sample multiple times.

**What you expected to happen**

Tile game board appears every time.

**What actually happened**

Running the alien alien_cake_addict sample multiple times does not show the game board at all times.
Rather, all boxes are piled up in what appears to be the world origin.

**Additional information**

There may be a race condition.

**Comment by cart** [comment]
Yeah this is probably related to the recently merged #1144. Does it work if you check out a commit prior to that?

**Comment by cart** [comment]
We anticipate a number of "system order" related issues due to the new executor logic, which we plan on fixing over the next week or so.

**Comment by The5-1** [comment]
Thanks for the heads up!
Indeed it works on b71ada03465a0343b4ead1b2896f44587e719a47

**Comment by cart** [comment]
Thanks for checking! Knowing that is super helpful.
