### ISSUE TITLE
System order ambiguity `time_system` and `event_update_system`

### ISSUE THREAD

**Issue by thmxv** [bevyengine/bevy#14524]
## Bevy version

0.14.0 and git `main` branch most recent commit ca3d8e8

## What you did

My app crashes because of a system order ambiguity.
My app has the following code to detect ambiguity:
```Rust
fn main() {
    let mut app = App::new();
    app.configure_schedules(ScheduleBuildSettings {
        ambiguity_detection: LogLevel::Error,
        ..default()
    });
    ...
}
```
I reproduced this error/crash in bevy only by adding this code to the `time/time.rs` example.

## What went wrong

```
thread 'main' panicked at crates/bevy_ecs/src/schedule/schedule.rs:383:33:
Error when initializing schedule First: Systems with conflicting access have indeterminate run order.
1 pairs of systems with conflicting data access have indeterminate execution order. Consider adding `before`, `after`, or `ambiguous_with` relationships between these:
 -- time_system (in set TimeSystem) and event_update_system (in set EventUpdates)
    conflict on: bevy_ecs::world::World
```

## Additional information

My app does have this crash but with 2 pairs of systems, not just the one. This crash comes from a dependency of a dependency of my app: `bevy_mod_raycast` 
```
2 pairs of systems with conflicting data access have indeterminate execution order. Consider adding `before`, `after`, or `ambiguous_with` relationships between these:
 -- time_system (in set TimeSystem) and event_update_system (in set EventUpdates)
    conflict on: bevy_ecs::world::World
 -- update_cursor_ray and event_update_system (in set EventUpdates)
    conflict on: bevy_ecs::world::World
```
The `update_cursor_ray` system comes from `bevy_mod_raycast`. But because `event_update_system` comes from Bevy and is common to the 2 pairs of systems, I do not know if I should report a similar issue there.

**Comment by alice-i-cecile** [comment]
I don't mind resolving the ambiguity either way: do you have a preference?

**Comment by thmxv** [comment]
I do not have preference. I suppose the `time_system` and `event_update_system` are ambiguous but this is not a problem. In this case maybe using `ambiguous_with()` and not `before()` nor `after()` is the "correct" way. But I have no real knowledge of those systems and new to Bevy, so you sure know better than me what is better.

**Comment by alice-i-cecile** [comment]
Hmm yeah, I actually think that these two systems aren't actually ambiguous in meaningful ways, since the event system work won't touch time despite having world access. Yeah, marked as ambiguous with is the right approach here.

For the actual crash, you need an ordering in bevy_mod_raycast :)

**Comment by thmxv** [comment]
Thanks. To avoid the crash, I changed from `LogLevel::Error` to `LogLevel::Warn`, which only prints warning messages but do no crash the app. I will report the issue in `bevy_mod_raycast`.

**Comment by richchurcher** [comment]
As this issue is marked with `trivial`, I might take a stab at closing it 🤞
