### ISSUE TITLE
Add `Mesh::invert_winding`

### ISSUE THREAD

**Issue by Azorlogh** [bevyengine/bevy#14547]
## What problem does this solve or what need does it fill?

Use case: I need a mesh composed of two parallel rectangles with a slight offset. The UVs of both should go in the same direction.
![image](https://github.com/user-attachments/assets/359e2468-d8f4-4778-83a2-a67e44df87af)

## What solution would you like?

`Mesh::flip_winding` or `Mesh::invert_winding` which takes all triangles indices `a, b, c` and turns them into `a, c, b`.
(I would then be able to offset the bottom rectangle, then calling `Mesh::flip_winding` on it.)

## What alternative(s) have you considered?

If I were to only offset the bottom rectangle, its faces would still point upward.
If I were to rotate it, its UVs would be inverted.

**Comment by DasLixou** [comment]
Other name idea: `flip_winding`

**Comment by alice-i-cecile** [comment]
I would expect a `flip_normal` method to leave the winding / vertex order intact, but invert the direction of all of the normal vectors. I like `flip_winding` or `invert_winding` better as names.

Anyways, both seem reasonable to add.

**Comment by Azorlogh** [comment]
Oh yeah of course! :facepalm: `Mesh::flip_winding` or `Mesh::invert_winding` makes a lot more sense. I'll fix the issue description/title

**Comment by DasLixou** [comment]
I'll try to do this :D

**Comment by mnmaita** [comment]
Fixed by https://github.com/bevyengine/bevy/pull/14555.
