### ISSUE TITLE
Texture atlas example needs tweaking

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#14550]
It is but the slicer `border_rect` should be increased from `22` to `24` @s-puig , the fifth texture in the sheet is drooling on the border

_Originally posted by @ManevilleF in https://github.com/bevyengine/bevy/pull/13620#discussion_r1698255052_

**Comment by extrawurst** [comment]
I cannot reproduce any problem with `ui_texture_atlas_slice`:
<img width="1392" alt="Screenshot 2024-08-26 at 11 18 30" src="https://github.com/user-attachments/assets/b9b29804-bb16-4515-96e2-f7285ada9211">

or `ui_texture_slice`:
<img width="1392" alt="Screenshot 2024-08-26 at 11 20 11" src="https://github.com/user-attachments/assets/449f7671-e094-4593-beb3-cb70fa4cf043">

both of these examples are the only once using `BorderRect::square(22.0)` the only other example using `BorderRect` at all is `sprite_slice` which also looks good on my machine (MacOs)

**Comment by ManevilleF** [comment]
What's weird is that it still happens with the new shader version by @ickshonpe

**Comment by extrawurst** [comment]
@ManevilleF not happening on my machine.

<img width="1392" alt="Screenshot 2024-09-04 at 18 14 18" src="https://github.com/user-attachments/assets/e46fac6d-897e-493e-893a-7556da791110">

what specs can you reproduce this on?

**Comment by ManevilleF** [comment]
@extrawurst It happense on my Mac so it might be related to pixel resolution.

But to reproduce you need to click enough times on the `ui_texture_atlas_slice` buttons to reach the same textures I displayed on my comment

**Comment by extrawurst** [comment]
@ManevilleF oh you are right, i never toggled them, had no idea that is what one can do 🙈

**Comment by ickshonpe** [comment]
The problem is just the linear sampling. There shouldn't be any artifacts if the texture is loaded with
```
let image = asset_server.load_with_settings(
        "textures/fantasy_ui_borders/panel-border-010.png",
        |settings: &mut ImageLoaderSettings| {
            settings.sampler = ImageSampler::nearest();
        },
    );
```

**Comment by ManevilleF** [comment]
Or we can just make the border 2px wider in the example

**Comment by tjlaxs** [comment]
Seems like this would be an easy fix to start from. Is it ok, if I do it?

**Comment by alice-i-cecile** [comment]
Yep I'm fine with the simple fix getting merged.
