### ISSUE TITLE
Link more aggressively to `.chain`

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy#14552]
## How can Bevy's documentation be improved?

`.before` and `.after` are more cumbersome to use and more error prone than `.chain`. [Especially for scheduling](https://docs.rs/bevy/latest/bevy/ecs/prelude/trait.IntoSystemConfigs.html#method.before):

> Note: The given set is not implicitly added to the schedule when this system set is added. It is safe, but no dependencies will be created.

imo that paragraph is a bit arcane for people who are not in the know about how schedules and co. exactly work
So maybe outright saying "you probably meant to use .chain()" would be good.

See [this Discord question](https://discord.com/channels/691052431525675048/691052431974465548/1268198882001817620) for an example of a user in the wild using `.before` in code that *looks* like it would do the right thing, but actually does not.

**Comment by benfrankel** [comment]
IMO `.before` and `.after` can almost be considered an anti-pattern at this point. If you're adding the systems in the same place, use `.chain`. If you're not, use a system set.

**Comment by janhohenheim** [comment]
I heavily agree with @benfrankel on this. This issue is primarily about removing a footgun, but I'm definitely also fine with a PR advocating chain everywhere in general.

**Comment by kivi** [comment]
How about change the Note for `.after` and `.before` to something like:

Note: If you're adding systems in the same location, it's recommended that you use `.chain`. You can also add a set of systems.  You may want to use `.after` or `.before` for advanced scheduling and perhaps exceptional cases.

**Comment by janhohenheim** [comment]
@kivi I like that :)

**Comment by kivi** [comment]
Ok, I can change the Note or keep the sentence and add the new on.

> Note: The given set is not implicitly added to the schedule when this system set is added. It is safe, but no dependencies will be created.

I am beginning with Bevy and Rust. So That sentence seems like containing useful information. Would somebody mind to explain it to me or point me to examples or similar concepts, so I could figure it out.

Thanks to this ticket and the comments here, I could understand scheduling better and how to (not) use .after/.before.

**Comment by janhohenheim** [comment]
@kivi yeah, that note in particular is nearly impossible to decipher as a beginner, I think. I'd dramatically rephrase it or extend it with an explanation.
Let me explain by example for you. Say you have the following system set:
```rust
enum GameSystem {
  Loading,
  Playing,
}
```
you naturally want to configure your set such that systems in `Loading` always run before systems in `Playing` and never the other way around. So you might do this:
```rust
app.configure_sets(
  Update,
  GameSystem::Loading.before(GameSystem::Playing)
);
```
looks good, but you just ran into a trap! The above registers `GameSystem::Loading` to run in `Update` before *something*, but does *not* register `GameSystem::Playing` in `Update`. Currently, it is valid to have nonsense configurations when the involved sets are in different schedules. Let's do a sub-example:
```rust
struct ThisRunsInUpdate;
struct ThisRunsInStartup;

app
  .configure_sets(Startup, ThisRunsInStartup)
  .configure_sets(Update, ThisRunsInUpdate);

// watch closely, here comes a magic trick
app.configure_sets(
  Update,
  ThisRunsInUpdate.before(ThisRunsInStartup)
);
```

Since `Update` always runs *after* `Startup`, scheduling `ThisRunsInUpdate` *before* `ThisRunsInStartup` is pure nonsense. But since they are in two different schedules anyways, Bevy will simply ignore this. Now let's go back to our example from before:

```rust
app.configure_sets(
  Update,
  GameSystem::Loading.before(GameSystem::Playing)
);
```
This registers ` GameSystem::Loading` in the schedule `Update`, but does *not* register `GameSystem::Playing` in *any* schedule. This means that the `.before` is completely ignored, as it concerns two system sets that are not in the same schedule. As such, it *looks* like you have ordered your stuff, but you did not. For comparison, the following variants all do the *correct* and expected thing and are functionally equivalent.

```rust
app.configure_sets(
  Update,
  // this is the easiest variant, you probably always want this
  (GameSystem::Loading, GameSystem::Playing).chain()
);

app.configure_sets(
  Update,
  (
    GameSystem::Playing,
    GameSystem::Loading.before(GameSystem::Playing))
  )
);

app
  .configure_sets(Update, GameSystem::Playing)
  .configure_sets(
    Update,
    GameSystem::Loading.before(GameSystem::Playing)
);
```

Does this help?

**Comment by kivi** [comment]
@janhohenheim Thanks for taking time. I am thinking about a concise note to describe this and replace it. I am not sure with a few things here.

You say there is a magic tric:

> ```
> struct ThisRunsInUpdate;
> struct ThisRunsInStartup;
> 
> app
>   .configure_sets(Startup, ThisRunsInStartup)
>   .configure_sets(Update, ThisRunsInUpdate);
> 
> // watch closely, here comes a magic trick
> app.configure_sets(
>   Update,
>   ThisRunsInUpdate.before(ThisRunsInStartup)
> );
> ```

And later you explain since they are in different schedules, it will be ignored. The magic trick is, that even though this could seem to work - it just won't work as one may read? Or is the magic trick is something else?

**Comment by janhohenheim** [comment]
@kivi yeah, the "trick" here is that this looks correct but does absolutely nothing.

**Comment by kivi** [comment]
I got something (thanks to all participants of this ticket participants), that could work without example or we could add a simple small example with SetA, SetB or sample code as suggested in earlier comment.

Note: If you configure two groups of systems (let's call them 'Set A') in a Schedule, another group referencing `.after` or `.before` (let's call it 'Set B') will not be added automatically.
It's safe and won't cause any problems or errors. But no dependencies are created: Adding Set A does not automatically create any connections or relationships with Set B. They remain independent of each other.
If you're adding systems in the same location, it's **recommended** that you use **`.chain`**. You can also add a set of systems. You may want to use `.after` or `.before` for advanced planning and perhaps exceptional cases.


Please double check:
> It is safe, but no dependencies will be created.

I changed it to
> It's safe and won't cause any problems or errors. But no dependencies are created: Adding Set A does not automatically create any connections or relationships with Set B. They remain independent of each other.

The word **_safe_** could be misleading or maybe it's just me.
