### ISSUE TITLE
Document how to toggle individual `bevy_diagnostic` plugins at runtime

### ISSUE THREAD

**Issue by benfrankel** [bevyengine/bevy#14569]
## What problem does this solve or what need does it fill?

It's hard for users to discover that diagnostics plugins can be toggled at runtime.

## What solution would you like?

In the docs for diagnostics plugins (and the plugin for logging them), link to and/or explain how they can be toggled via `DiagnosticsStore`.

**Comment by mockersf** [comment]
it's already possible to disable logging at runtime:

```rust
use std::time::Duration;

use bevy::{
    diagnostic::{DiagnosticsStore, FrameTimeDiagnosticsPlugin, LogDiagnosticsPlugin},
    prelude::*,
    time::common_conditions::on_timer,
};

fn main() {
    App::new()
        .add_plugins((
            DefaultPlugins,
            FrameTimeDiagnosticsPlugin,
            LogDiagnosticsPlugin::default(),
        ))
        .add_systems(
            Update,
            toggle.run_if(on_timer(Duration::from_secs_f32(10.0))),
        )
        .run();
}

fn toggle(mut store: ResMut<DiagnosticsStore>) {
    for diag in store.iter_mut() {
        info!("toggling diagnostic {}", diag.path());
        diag.is_enabled = !diag.is_enabled;
    }
}
```

in my opinion this is preferred over stopping collection as it means better stats when starting to log them

**Comment by benfrankel** [comment]
I see. That's really hard to find in the documentation.
