### ISSUE TITLE
Alias violations for EntityMut/EntityRef

### ISSUE THREAD

**Issue by re0312** [bevyengine/bevy#14575]
## Bevy version

main

## What you did

```rust
use bevy::prelude::*;

fn sys(_a: Query<EntityMut>, _b: Query<EntityMut>) {}

fn main() {
    let mut app = App::new();
    app.add_systems(Update, sys).run();
}
```

## What went wrong

this code should panic due to runtime alias violation checks, but it didn't.

**Comment by thebluefish** [comment]
My train of thought is that multiple `EntityMut` should theoretically only fail if they attempt to alias the same data - so that filters work, like in the example docs for `EntityMut` - but they technically don't in an empty world with no data to conflict on. I wrote this MVCE to test aliasing of real data, and it does appear to break aliasing rules. This MVCE works as far back as bevy 0.12, when `EntityMut` became a query parameter.

```rust
fn main() {
    use bevy::prelude::*;

    #[derive(Component, Debug)]
    struct Foo(pub bool);

    App::new()
        .add_systems(Startup, |mut commands: Commands| { commands.spawn(Foo(true)); })
        .add_systems(Update, |mut foo: Query<EntityMut>, mut bar: Query<EntityMut>| {
            let mut foo = foo.single_mut();
            let foo_id = foo.id();

            let mut bar = bar.single_mut();
            let bar_id = bar.id();

            // Entity { index: 0, generation: 1 } == Entity { index: 0, generation: 1 }
            println!("{:?} == {:?}", foo_id, bar_id);

            let foo_component = foo.get_mut::<Foo>().unwrap();
            let mut bar_component = bar.get_mut::<Foo>().unwrap();

            // Entity { index: 0, generation: 1 }: Foo(true)
            println!("{:?}: {:?}", foo_id, *foo_component);

            bar_component.0 = false;

            // Entity { index: 0, generation: 1 }: Foo(false)
            println!("{:?}: {:?}", foo_id, *foo_component);
        })
        .run();
}
```

**Comment by SkiFire13** [comment]
Ok, so:

- `Query` checks that it is compatible with previous `SystemParam`s using `assert_component_access_compatibility`
  https://github.com/bevyengine/bevy/blob/0c7df881e72c1167060c170b09e02586fc74d85f/crates/bevy_ecs/src/system/system_param.rs#L222

- `assert_component_access_compatibility` in turn checks that the previous access is compatible with the new one by checking if `FilteredAccessSet::get_conflicts_single` returns an empty `Vec`
  https://github.com/bevyengine/bevy/blob/0c7df881e72c1167060c170b09e02586fc74d85f/crates/bevy_ecs/src/system/system_param.rs#L295-L298

- `FilteredAccessSet::get_conflicts_single` in turn checks if the `FilteredAccess` for the whole set is compatible with the new one, and if not it gathers the conflicts. Note that in this case the access are actually not compatible, so it does end up gathering the conflicts with each `FilteredAccess` in the set using `FilteredAccess::get_conflicts`
  https://github.com/bevyengine/bevy/blob/0c7df881e72c1167060c170b09e02586fc74d85f/crates/bevy_ecs/src/query/access.rs#L697-L706

- `FilteredAccess::get_conflicts` in turn checks again if they are compatible, which in this case again they are not, then proceeds to gather the conflicts using `Access::get_conflicts`
  https://github.com/bevyengine/bevy/blob/0c7df881e72c1167060c170b09e02586fc74d85f/crates/bevy_ecs/src/query/access.rs#L497-L502

- Finally, `Access::get_conflicts` tries to gather a list of components that both `Access` want to access. The problem however is that neither of them has an explicit list of such components, instead they both have a `read_all = true` and `write_all = true`. Notice how this method does have some unresolved questions about how `write_all` should be handled! How did they remain there unanswered?
  https://github.com/bevyengine/bevy/blob/0c7df881e72c1167060c170b09e02586fc74d85f/crates/bevy_ecs/src/query/access.rs#L272-L298

So finally, there are two solutions:
- somehow fix `Access::get_conflicts` to return something (but what?) in the `write_all` cases;
- add a `is_compatible` check in `assert_component_access_compatibility`, just like it's used in all the other methods seen here; again it's unclear what the error should be in case there's no list of components they conflict on.

**Comment by hymm** [comment]
Maybe get_conflicts should return an enum?

```rust
enum AccessConflicts<T> {
  All // if self and other set reads_all or writes_all
  Components<Vec<T>>
}
