### ISSUE TITLE
Resource that is auto-removed at end of exclusive system/command

### ISSUE THREAD

**Issue by ThomasAlban** [bevyengine/bevy#14571]
## What problem does this solve or what need does it fill?

I have a number of traits implemented on components which take in `&mut World`, and in some of the implementations certain data is required. I have solved this problem by inserting resources into the world inside the exclusive system that the functions are called, but all these resources need to be manually removed (otherwise they will be sitting in `world` for the lifetime of the program wasting memory), which is tedious if there are lots of resources.

## What solution would you like?

`world.insert_scoped_resource(x)` and `world.init_scoped_resource::<X>()`

These would work the same as `world.insert_resource(x)` / `world.init_resource::<X>()`, except the resource inserted would be automatically removed from the world at the end of the exclusive system / command they were called in

## What alternative(s) have you considered?

- Manually removing the resources at the end of the exclusive system or command (annoying + error prone if there are a lot)
- Taking in all the possible things the trait implementations may need as args to the trait method (not really feasible)
- Using a `Local` (this would waste memory, as the data would always be stored in the world. This is particularly wasteful if the exclusive system is not called every frame, and only when some event triggers it. This would also mean it would manually have to be passed in to functions that use it, which defeats the purpose anyway.)

**Comment by alice-i-cecile** [comment]
I don't think we should do this. This is an extremely unusual pattern: I've never seen anyone attempting anything similar. What, specifically, are you using this for?

There's several good workarounds: remove the resource yourself manually at the end of the system or don't insert it into the world at all and just use a locally scoped variable. I suspect that if you got particularly clever you could probably implement this with a `Drop` impl?

Using a `Local` is going to be better unless you're very memory constrained: large allocations are expensive and will lead to stuttering. I'm also not sure how we would implement this.

**Comment by alice-i-cecile** [comment]
```rust
 pub trait WorldScopedResourceExt {
    fn scoped_resource<R: Resource>(self, res: R, f: impl FnOnce(&mut World));
}

impl WorldScopedResourceExt for &mut World {
    fn scoped_resource<R: Resource>(self, res: R, f: impl FnOnce(&mut World)) {
        self.insert_resource(res);
        f(self);
        self.remove_resource::<R>();
    }
}
```

From [s33n](https://discord.com/channels/691052431525675048/691052431974465548/1268574108560392325). This is a good, ready-to-use workaround. Closing out.
