### ISSUE TITLE
error: failed to select a version for the requirement `bevy_dylib = "^0.14.0"`

### ISSUE THREAD

**Issue by eckz** [bevyengine/bevy#14585]
## Bevy version

0.14.0

## Relevant system information

System:
 - Apple M1 Pro
 - macOS Sonoma 14.5

Toolchain
- cargo 1.80.0 (376290515 2024-07-16)
- rustc 1.80.0 (051478957 2024-07-21)
- target: aarch64-apple-darwin

## What you did

Just using a new bevy repository with minimal configuration:
```sh
> mkdir bevy_empty && cd bevy_empty
> cargo new --bin .
> cargo add bevy
```
Replace `main.rs` with 

```rust
use bevy::prelude::*;

fn main() {
    App::new()
    .add_plugins(DefaultPlugins)
    .run();
}
```

## What went wrong

Running `cargo run` works a expected.

When I run using `cargo run --features bevy/dynamic_linking` I get the following error:

```

error: failed to select a version for the requirement `bevy_dylib = "^0.14.0"`
candidate versions found which didn't match: 0.14.0-rc.2, 0.14.0-rc.1, 0.13.2, ...
location searched: crates.io index
required by package `bevy v0.14.0`
    ... which satisfies dependency `bevy = "^0.14.0"` (locked to 0.14.0) of package `bevy_empty v0.1.0 (/Volumes/code/rust/bevy_empty)`
if you are looking for the prerelease package it needs to be specified explicitly
    bevy_dylib = { version = "0.14.0-rc.2" }

```

**Comment by Olle-Lukowski** [comment]
I have had this exact issue before (always on macOS, interestingly), and deleting `Cargo.lock` and `target/` resolved it for me every time.

**Comment by Olle-Lukowski** [comment]
In that case I have no clue what is going on, sorry.

**Comment by jtmusselman** [comment]
I have this occurring currently with `0.14.2`

**Comment by jurisk** [comment]
> I have this occurring currently with `0.14.2`

Same here, @jtmusselman, but clearing caches under `~/.cargo/registry` solved it.

**Comment by mmatvein** [comment]
You can try running `cargo info bevy_dylib`. This refreshed the registry for bevy_dylib for me and fixed the issue.

**Comment by coltonw** [comment]
`cargo info bevy_dylib` didn't work for me.  The specific file I had to delete was `~\.cargo\registry\index\index.crates.io-6f17d22bba15001f\.cache\be\vy\bevy_dylib` on windows.
