### ISSUE TITLE
Normal Maps for 2D Textures

### ISSUE THREAD

**Issue by DispairingGoose** [bevyengine/bevy#14586]
## What problem does this solve or what need does it fill?

Lighting in 2D games is often very flat.

## What solution would you like?

Adding normal maps to 2d sprites

## What alternative(s) have you considered?

 - Baking lighting into sprite itself in an external editor - has the downside that lights cannot move

## Additional context

Other Engine Implmentations:
 - [Godot](https://docs.godotengine.org/en/stable/classes/class_canvastexture.html#class-canvastexture)
 - [Unity](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.0/manual/SecondaryTextures.html)

**Comment by alice-i-cecile** [comment]
My understanding is that `MaterialMesh2d` is the intended path for these more complex use cases. Sprite should be kept very light and fast for the "just render my pixels" users. What does Bevy's existing 2D lighting ecosystem do?

**Comment by zaycev** [comment]
@DispairingGoose there is no built-in support, but as @alice-i-cecile mentioned you can use `MaterialMesh2d` with few modifications. Essentially all you need to do is add atlas info into the material – texture handle and list of rectangle infos. After that you can pass your current atlas rectangle id into `MaterialMesh2d` shader and then sample corresponding pixel data inside of your shader. Based on how lighting / shading works in your game you should be able to use normal maps in `MaterialMesh2d` without any problems. This is what I was experimenting with in [BML2D](https://github.com/zaycev/bevy-magic-light-2d), but I haven't open source that part yet.
