### ISSUE TITLE
Shadow clipped/not shown for split_screen example on WebGL

### ISSUE THREAD

**Issue by akimakinai** [bevyengine/bevy#14595]
## Bevy version

Bevy 0.14

## Relevant system information

Confirmed on Firefox and Edge at least. Does not happen on WebGPU or native Windows.

![image](https://github.com/user-attachments/assets/c7ad43f7-401f-4ed5-bee4-9c1a2663f7d1)

```ignore
`AdapterInfo { name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0), or similar", vendor: 4318, device: 0, device_type: Other, driver: "WebGL", driver_info: "2.0", backend: Gl }`
```

## What you did

Run https://bevyengine.org/examples/3d-rendering/split-screen/
(also I rotated foxes to show clipping effect)

## Additional information

This warning was logged:
> crates/bevy_pbr/src/render/light.rs:593 The number of cascades configured for a directional light exceeds the supported limit of 1.

I tried running the example with `num_cascades` changed to 1, and the shadow indeed seems to be fixed.

**Comment by TrialDragon** [comment]
Can also confirm on Chromium WebGL it has the same issue, but WebGPU it doesn't. (Also the buttons are pure white on WebGL for me).
