### ISSUE TITLE
`embedded_watcher` doesn't work for crates outside of the main crate directory

### ISSUE THREAD

**Issue by ricky26** [bevyengine/bevy#14606]
## Bevy version
v0.14.1

## What you did

- Added a shader asset with `embedded_asset!(app, "shaders/my_shader.wgsl");`.
- Enabled the `bevy/asset_processing` & `bevy/embedded_watcher` features.
- Boot game.
- Edited shader.

## What went wrong

No reload is detected, but changes are taken into account when restarting (& building).

## Additional information

It looks like this is caused by `EmbeddedWatcher` only watching the asset root directory (in my example below, `crates/main/`). In practice it should probably watch the workspace root and ideally be independently overridable without having to move `assets/`.

For completeness my project layout looks something like this:

```
crates/
  main/
    src/
    assets/
    Cargo.toml
  my_lib/
    src/
      shaders/
        my_shader.wgsl
    Cargo.toml
Cargo.toml
```

**Comment by SludgePhD** [comment]
I think this is the same as https://github.com/bevyengine/bevy/issues/10575

**Comment by ricky26** [comment]
Oh, you might well be right - I don't know why but I thought the embedded watcher wasn't that old, so I hadn't looked that far back when looking for dupes.

**Comment by BD103** [comment]
If that's the case, I'm going to close this as a duplicate.
