### ISSUE TITLE
From<PathBuf> for AssetPath does not work with labels.

### ISSUE THREAD

**Issue by kartonrad** [bevyengine/bevy#14618]
## Bevy version

0.14.1

## What you did

```
AssetServer::load(asset_server, PathBuf::from("Spaceship.glb#Scene0");
```

## What went wrong

Error Message:
```
ERROR bevy_asset::server: Path not found: C:\Users\<path to working dir>\assets\Spaceship.glb#Scene0
```

## Additional information
The Path does include a label, but in the conversion from PathBuf, it is simply not taken into account.
This leads to unexpected behaviour.
I'd expect to get an error `use AssetPath! not PathBuf` or i'd expect the label to get stripped from the last component.

![image](https://github.com/user-attachments/assets/7978a29f-d9f4-4e68-bb01-4c2bf17d26a1)

**Comment by kartonrad** [comment]
@DasLixou hm, sorry, that's totally my bad for not rtfm

I do wonder if a # in the filename is actually the more common case 
Or if an associated Method on AssetPath to use the path as-is would be more clear.

The Documentation definetely could not be any clearer, so this is definetely not an issue, and probably not worth discussing either.

**Comment by DasLixou** [comment]
@kartonrad No problem. FYI you dont need to create the Path, you can just use a string in the load function, where it then parses the label correctly. See any example that loads an asset.
Could I ask why you came to the conclusion you would need a Path?
