### ISSUE TITLE
`build-wasm-atomics` job is failing

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#14659]
See https://github.com/bevyengine/bevy/actions/runs/10302522522/job/28516746068?pr=14656

> error: "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

Started this morning or so.

**Comment by BD103** [comment]
Closing this as a duplicate, in favor of #14662.
