### ISSUE TITLE
`build-wasm-atomics` CI check failing

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy#14662]
The [`build-wasm-atomics`](https://github.com/bevyengine/bevy/blob/8c2e70b7446ecab3c08f62e288de294f605c6100/.github/workflows/ci.yml#L153) check has started failing CI.

```
  Downloading crates ...
  Downloaded cc v1.1.8
  Downloaded serde_derive v1.0.205
  Downloaded serde v1.0.205
error: "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
Error: Process completed with exit code 101.
```

[This](https://github.com/bevyengine/bevy/actions/runs/10296616148/job/28498425637) is the run that first had this issue. I believe the cause was updating from Rust nightly `60d146580 2024-08-06` to `8b3870784 2024-08-07`.

I'm going to do further investigation to find which Rust commit is responsible.

**Comment by BD103** [comment]
I opened up https://github.com/rust-lang/rust/issues/128840 with the bisection. https://github.com/rust-lang/cargo/pull/14370 should fix this, which will be merged in https://github.com/rust-lang/rust/pull/128827.

Ideally, next nightly will include the fix. I'm going to wait until tomorrow and see if CI starts passing.

**Comment by BD103** [comment]
Looks like we'll need to [wait one more day](https://github.com/rust-lang/rust/pull/128827#issuecomment-2277729356) before this is released.

**Comment by mockersf** [comment]
back to working now. thanks!
