### ISSUE TITLE
Add a SystemParam that gives a resource and the previous value of that resource

### ISSUE THREAD

**Issue by wainwrightmark** [bevyengine/bevy#14678]
## What problem does this solve or what need does it fill?

When using resources it is often helpful to know what the value of the resource was the last time the system was run. 
A simple example might be: if the player's score changed you could trigger a particle effect if it increased by more than a certain amount.

## What solution would you like?

A `SystemParam` called `WithPrevious` that works exactly like `Res` except that it also has a method to access the previous value.

```rust
#[derive(Resource, Clone)]
struct Score {
    pub points: usize,
}

fn track_score(score: WithPrevious<Score>){
    if let Some(previous) = score.previous_if_changed(){
        if score.points > previous.points + 100{
            // Trigger cool effect
        }
    }
}
```

## What alternative(s) have you considered?

This could easily be in an external crate but it is relatively short (~100  lines) and requires unsafe code (`SystemParam` is an unsafe trait). 

Users can achieve this behavior themselves using `Local<T>` but it is quite fiddly and error prone.

The exact interface for accessing the previous value is up for grabs. I favour `pub fn previous_if_changed(&self) -> Option<&'s T>`

An alternative formulation might involve writing something like `WithPrevious<Res<T>>`, and that could support other inner system parameters (such as `NonSend<T>`) but that might not be possible to implement.

## Additional context

I have written and tested the code for this and am happy to contribute a PR.

**Comment by alice-i-cecile** [comment]
IMO this should be done externally. The `SystemParam` impl can be derived, making this a pretty approachable little helper :)
