### ISSUE TITLE
Poor performance with Query::iter_combinations_mut compared to a similar algorithm in a Nannou project

### ISSUE THREAD

**Issue by polaris64** [bevyengine/bevy#14679]
I'm currently experiencing some poor performance in Bevy, specifically with `Query::iter_combinations_mut`. I'm aware that this is quite a costly operation however I am implementing the same algorithm in another project using Nannou and with the same number of combinations it is much faster.

I'm quite new to Bevy and Nannou so I decided to try implementing one of my projects (Verlet Physics Playground, <https://codeberg.org/polaris64/verlet-physics-playground>) in Nannou first, then a game engine. For the game engine I chose Bevy.

The specific performance issue I have experienced is when handling collisions between objects. In the Nannou version, this algorithm is implemented here: <https://codeberg.org/polaris64/verlet-physics-playground/src/commit/e631f4b43e758872f753383d358f0f1322c57ca4/src/main.rs#L147>. With 1,000 objects I count 499,500 (999th triangular number) collision checks with this algorithm, but the frame rate is high (well over 60fps). In Bevy, I'm handling the collisions like this: -

```rust
  fn handle_verlet_collisions(
      mut query: Query<(&mut Transform, &VerletProperties)>,
  ) {
      let mut combinations = query.iter_combinations_mut();
      while let Some([
          (
              mut tr1,
              pr1
          ),
          (
              mut tr2,
              pr2
          )
      ]) = combinations.fetch_next() {
          let mut norm = tr2.translation - tr1.translation;
          let dist = norm.length();
          if dist < pr1.radius + pr2.radius {
              let overlap = (pr1.radius + pr2.radius) - dist;
              norm = norm.normalize();
              if !pr1.pinned {
                  tr1.translation.x -= norm.x * overlap * 0.5f32;
                  tr1.translation.y -= norm.y * overlap * 0.5f32;
              }
              if !pr2.pinned {
                  tr2.translation.x += norm.x * overlap * 0.5f32;
                  tr2.translation.y += norm.y * overlap * 0.5f32;
              }
          }
      }
  }
```

Counting the number of checks per update again shows 499,500, however when run with Bevy the frame rate is extremely low, probably in the range of around 1-2fps. Removing this system causes the frame rate to become very high again, showing that it's not a rendering issue, just an issue with this collision check system.

I have implemented the advice given about Bevy performance optimisation and I have tried running the project in both `dev` and `release` profiles, however the performance never gets better than around 1-2fps with 1,000 objects.

As I say, I know that iterating combinations is expensive (499,500 iterations per update in this case), however I'm not sure why the same number of checks in Bevy are so much slower than those in my Nannou project.

## Bevy version

0.14.1

## \[Optional\] Relevant system information

`cargo 1.80.0 (376290515 2024-07-16)`

`AdapterInfo { name: "NVIDIA GeForce RTX 2060", vendor: 4318, device: 7957, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "555.58.02", backend: Vulkan }`

`Linux tikal 6.10.3-arch1-2 #1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:21:19 +0000 x86_64 GNU/Linux`

**Comment by alice-i-cecile** [comment]
@Victoronz @re0312 one of you may be interested in investigating this.

**Comment by alice-i-cecile** [comment]
What does the performance of the `unsafe` equivalent look like?

**Comment by polaris64** [comment]
Hi @alice-i-cecile,

I'm not sure how I'd use `Query::get_unchecked` in this situation but I've tried `Query::iter_combinations_unsafe` and that seems to have the same performance.

I hope that helps, but if you want me to try `Query::get_unchecked` then could you let me know how to modify the algorithm in question?

**Comment by re0312** [comment]
Can you try #14680 to see if it solves your problem?

**Comment by polaris64** [comment]
Thanks @re0312, this does actually seem quite a bit faster. Still not quite as fast as the Nannou version, but better! Sorry, I don't have actual performance figures to back up these claims, but visually it is definitely "faster".

**Comment by re0312** [comment]
> Thanks @re0312, this does actually seem quite a bit faster. Still not quite as fast as the Nannou version, but better! Sorry, I don't have actual performance figures to back up these claims, but visually it is definitely "faster".

yeah,I tested Bevy and Nannou, even with 14680 Bevy is still about 2x slower than Nannou. our current iter_combinations still has a lot of room for optimization

**Comment by polaris64** [comment]
> yeah,I tested Bevy and Nannou, even with 14680 Bevy is still about 2x slower than Nannou. our current iter_combinations still has a lot of room for optimization

Thanks for investigating and testing it for me :+1:
