### ISSUE TITLE
Custom Asset IO example not loading assets on website

### ISSUE THREAD

**Issue by akimakinai** [bevyengine/bevy#14689]
## Bevy version

Currently hosted version for web examples

## What you did

Running [Custom Asset IO example](https://bevyengine.org/examples/assets/custom-asset-reader/) (on Firefox and Chrome).

## What went wrong

It doesn't show anything, because it tries to load icon.png from non-existent path:
https://bevyengine.org/examples/assets/custom-asset-reader/assets/branding/icon.png

![image](https://github.com/user-attachments/assets/cbd80631-9fc3-4983-9c88-1e618705b8d9)

instead of:
https://bevyengine.org/assets/examples/branding/icon.png

## Additional information

bevy_asset is [patched](https://github.com/bevyengine/bevy/blob/main/tools/example-showcase/asset-source-website.patch) to load from particular path when building for the website, instead of the default behavior of using `asset` directory relative from the current url. Probably the use of custom AssetReader is bypassing it.

**Comment by akimakinai** [comment]
I was going to patch HttpWasmAssetReader instead, which is lower-level than user-added AssetReader, this should work for custom_asset_reader example. But then I noticed [Extra asset source](https://bevyengine.org/examples/assets/extra-asset-source/) example has been broken too and this one actually need to override asset root path. Its assets in the custom path (under `examples/asset/files` in this repo) [may not even be copied to website](https://github.com/bevyengine/bevy-website/blob/e0a45e1be37fc8edb50592c0319d7a3ff11e0131/generate-wasm-examples/generate_wasm_examples.sh#L43)...

Perhaps asset directories should be symlinked to every example directory, like https://bevyengine.org/examples/assets/extra-asset-source/assets, to rely on the default behavior, and the patch should be removed. I expect many people will look into Network tab of browser developer tools for asset examples. Examples showing non-standard behavior there that does not match the presented code and the engine code in repository look confusing to me.

**Comment by alice-i-cecile** [comment]
We may need to just disable this on web builds. @mockersf may have opinions here.

**Comment by mockersf** [comment]
the example can be marked as not wasm compatible 👍
