### ISSUE TITLE
Consider using `fake_variadic` to improve docs

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy#14697]
## How can Bevy's documentation be improved?

`fake_variadic` allows docs on `docs.rs` to pretend they use variadics to hide tuple implementation spam.
It requires `#![cfg_attr(docsrs, feature(doc_cfg, rustdoc_internals))]` on `lib.rs`.

This is an secret, undocumented internal feature for the standard library, as far as I know. *Buuuuuut* there is a precedent of popular crates using it... namely serde!

See https://docs.rs/serde/latest/src/serde/de/impls.rs.html#1480-1509 for a usage example and https://docs.rs/serde/latest/serde/trait.Deserialize.html#impl-Deserialize%3C'de%3E-for-(T,) for how it is rendered:

<img width="961" alt="image" src="https://github.com/user-attachments/assets/a8d1f518-8b82-457b-86a6-7f41ca91fe8a">

The exact usage is:
- Use the following annotation for the first impl:
```rust
#[cfg_attr(docsrs, doc(fake_variadic))]
#[cfg_attr(
    docsrs,
    doc = "This trait is implemented for tuples up to 16 items long."
)]
```
- use `#[cfg_attr(docsrs, doc(hidden))]` on the other impls

**Comment by alice-i-cecile** [comment]
I love it we should do this.

**Comment by bash** [comment]
I'd be interested in working on this :)

Would adding an option to the `all_tuples!` macro be an acceptable solution?
Usage would look something like this:
```rust
all_tuples!(#[doc(fake_variadic)] impl_plugins_tuples, 0, 15, P, S);
```

**Comment by alice-i-cecile** [comment]
IMO we should just do this unconditionally there :)

**Comment by bash** [comment]
Ah dang it. `#[doc(fake_variadic)]` only works on actual tuples and fn pointers.

For example this:
```rust
pub trait Example {}

macro_rules! impl_example {
    (($P:ident, $p:ident)) => {
        #[cfg_attr(docsrs, doc(fake_variadic))]
        #[cfg_attr(docsrs, doc = "This trait is implemented for tuples up to 16 items long.")]
        impl<P> Example for std::marker::PhantomData<(P,)> {}
    };
    ($(($P:ident, $p:ident)),*) => {
        #[cfg_attr(docsrs, doc(hidden))]
        impl<$($P,)*> Example for std::marker::PhantomData<($($P,)*)> {}
    };
}

bevy_utils::all_tuples!(impl_example, 0, 16, P, p);
```

fails with:
```
error: `#[doc(fake_variadic)]` must be used on the first of a set of tuple or fn pointer trait impls with varying arity
```

I guess this busts my dream of putting this in `all_tuples!` directly

**Comment by cart** [comment]
> I guess this busts my dream of putting this in all_tuples! directly

Could you add an additional parameter to it that adds it in an opt-in way?
