### ISSUE TITLE
Commands is missing a RemoveComponent command

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#147]
People will want this and its a relatively straightforward addition to Commands:
https://github.com/bevyengine/bevy/blob/master/crates/bevy_ecs/src/system/commands.rs

**Comment by coltontcrowe** [comment]
Has this been addressed by #178 ? Or is there still more work to be done?

**Comment by cart** [comment]
Yup this is resolved. Thanks for helping us maintain backlog hygiene!
