### ISSUE TITLE
links in bevy/crates/bevy_ecs/README.md does not exist.

### ISSUE THREAD

**Issue by ozqs** [bevyengine/bevy#14707]
## How can Bevy's documentation be improved?

links in bevy/crates/bevy_ecs/README.md does not exist.

If open it in GitHub, it works well. But if we access this link in crates.io or docs.rs, it will not work properly.

For example.
In crates.io 
> The [resources.rs](https://github.com/bevyengine/bevy/blob/HEAD/examples/resources.rs) example illustrates how to read and write a Counter resource from Systems.

In docs.rs
> The [resources.rs](https://docs.rs/bevy_ecs/latest/bevy_ecs/examples/resources.rs) example illustrates how to read and write a Counter resource from Systems.

**Comment by alice-i-cecile** [comment]
I think swapping to an absolute link will solve this.

**Comment by wiggleforlife** [comment]
Hi, I begun working on this and noticed a few things.

1. Switching to an absolute link means using GitHub, which won't work offline (but if someone is using rustdocs offline, there is reason to believe they know how to navigate to an example).
2. Linking to GitHub means either using a versioned link to the examples, or simply linking to latest, which wouldn't be ideal should one be viewing older documentation. 
3. The scraped example rustdoc feature exists and has been enabled on Bevy's docs, but it only works on functions. 

Is it worth needing to update these links in the docs every time Bevy updates, or should we just use the latest link?

**Comment by alice-i-cecile** [comment]
IMO these examples aren't important enough to link to be worth the hassle. We should just remove these links.
