### ISSUE TITLE
Move all benchmarks to the root level `benches` folder

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1472]
Location: https://github.com/bevyengine/bevy/tree/master/benches

There are currently several benchmarks scattered elsewhere, and they should be consolidated. 

During this process, we need to be sure we remove the relevant benchmark dev-dependencies from the "real" crates, in order to reduce their dependency trees and improve compile and CI times.

[Discord](https://discord.com/channels/691052431525675048/692572690833473578/812059596054200340) context.

**Comment by alice-i-cecile** [comment]
[bevy_ecs/benches](https://github.com/bevyengine/bevy/tree/d5a733043108972c51a785d61ad1a04c70d51d42/crates/bevy_ecs/benches) appears to be the only outstanding benchmark location that uses the Criterion crate.

**Comment by alice-i-cecile** [comment]
According to @cart, [bevymark](https://github.com/bevyengine/bevy/blob/master/examples/tools/bevymark.rs) should probably still live in `examples`, rather than `benches` due to being interactive and not producing quantitative output to compare against.

**Comment by YohDeadfall** [comment]
Since am interested in that, might I be assigned to it? Should be the transform benchmark be uncommented?

**Comment by cart** [comment]
Sure thing! Lets just remove the transform benchmark. Its out of date and we should come up with a new one that uses the new system (but I'd say thats not in scope for this issue).

**Comment by YohDeadfall** [comment]
Then I think that using a single framework for all of them makes sense too in a follow up.
