### ISSUE TITLE
Check benchmarks in CI

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#14723]
#14677 reported a compile failure to our benchmarks that was missed by CI. This is bad, as it will cause them to slowly rot. We should be able to check that these compile pretty easily, although runtime panics may be harder.

**Comment by hymm** [comment]
There's a command for it, but I think it's broken because bevy has the benches in a separate crate from the main repo.

https://github.com/bevyengine/bevy/blob/main/tools/ci/src/commands/bench_check.rs
