### ISSUE TITLE
Adding proc_macro `#[required(TransformComponent, ...)]` for Component.

### ISSUE THREAD

**Issue by Jerrody** [bevyengine/bevy#14737]
## What problem does this solve or what need does it fill?

A `required` proc_macro will add automatically specified components along with component that has this proc_macro.

## What solution would you like?

Don't know.

## What alternative(s) have you considered?

None.

## Additional context

This is similiar to the Unity's `RequieredComponent` attribute. If we specify this attribute, then, with adding component to the GameObject, will be also added specified components (by components I mean `MonoBehaviour`s).

**Comment by MrGVSV** [comment]
This is actually being discussed/designed over in https://github.com/bevyengine/bevy/discussions/14437! 😄

**Comment by Jerrody** [comment]
> This is actually being discussed/designed over in #14437! 😄

Oh, thanks. Didn't see it.

**Comment by alice-i-cecile** [comment]
Closing as a duplicate of https://github.com/bevyengine/bevy/issues/7272. Being added in https://github.com/bevyengine/bevy/pull/14791.
