### ISSUE TITLE
Implementation of bone masks

### ISSUE THREAD

**Issue by Sirmadeira** [bevyengine/bevy#14747]
## What problem does this solve or what need does it fill?
Imagine you have a character that has an attack animations really focused on the upper body. And you want him to still walk while he is doing such animation. That is why bone masks, exist. It basically say hey run two animation_clips at the same time one solely affecting the upper bones while the other affects the lower body.  

## What solution would you like?
1 - I think we should create a bone mask struct, that points out the bones that can be affected by multiple animations. 

```
struct BoneMask {
    bones: HashSet<Entities>, // Dont know what would be more optimal
    animation_clip:  // Animation clip that will override.
    weight// Weight of how much the alternative clip will affect the specific bone
}
```

2- Create a function that grab those bones, and override their variable curves. With the new variable curves from the given animation clip or the in between weighted values among them.

3- Make it so it is nodable (like you can make a node that will do that for you, kinda like blend node) in animation graph . 

## What alternative(s) have you considered?

There is none, the current blend node affects all bones at once

## Additional context

This will really help my game, and since i already implemented in it I dont see a problem implementing it here

**Comment by janhohenheim** [comment]
Possible duplicate of https://github.com/bevyengine/bevy/issues/14395

**Comment by Sirmadeira** [comment]
@janhohenheim Pretty similar indeed. By defining weights per bone you can easily make a bone mask feature

**Comment by Sirmadeira** [comment]
I am just gonna close and concentrate on 14395
