### ISSUE TITLE
Regression involving padding

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#14792]
## Bevy version

main, after #14777 

## Relevant system information

m1 mac, scale factor 2

## What went wrong

Updated `bevy_simple_text_input` to bevy main, and found my text inexplicably lower and further right than it should be.

Also observed many examples change in [this run](https://pixel-eagle.com/project/b25a040a-a980-4602-b90c-d480ab84076d/run/4213/compare/4204?screenshot=UI%20(User%20Interface)/display_and_visibility.png) of the [bevy example runner](https://thebevyflock.github.io/bevy-example-runner/).

![image](https://github.com/user-attachments/assets/50e12f8c-1257-4bf9-ad27-661b96dda8d2)

**Comment by alice-i-cecile** [comment]
We *can* just revert the linked PR, but I would really like to fix padding still!
