### ISSUE TITLE
Inputs clash in 3d_gizmos example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#14811]
@alice-i-cecile  This broke the `3d_gizmos` example, which relies on many of the same key bindings to demonstrate it's functionality.

_Originally posted by @tychedelia in https://github.com/bevyengine/bevy/issues/13973#issuecomment-2295401395_
            
            
We should just be able to rebind these, keeping the camera controller binds consistent.

**Comment by mgi388** [comment]
I’ll hopefully look at this in a couple of hours. My bad.
