### ISSUE TITLE
Make toggling visibility easier

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#14825]
## What problem does this solve or what need does it fill?

Quickly toggling visibility is a common operation. We should make it even easier.

## What solution would you like?

Implement `Not` for `Visibility`. Document the behavior of `Visibility::Inherited` (left unchanged) in the doc comment for the impl block.

## What alternative(s) have you considered?

Convert to and from a bool using https://github.com/bevyengine/bevy/pull/14784. This is likely slower, and much more verbose.

Similarly, writing your own match statement is tedious and verbose.

We could also (or instead) add a `.toggle` method, and have one variant which converts Inherited -> Hidden, and one which leaves it alone.

**Comment by Stanleeeeey** [comment]
I'm not sure if that's exactly what You meant, so I'm posting it as a comment not PR


```rs
use std::ops::Not;

/// Converts `Visibility` to the opposite (`Visible` -> `Hidden`, `Hidden` -> `Visible`), does nothing to  `Visibility::Inherited`
impl Not for Visibility {
    type Output = Self;

    fn not(self) -> Self::Output {
        match self {
            Visibility::Inherited => Visibility::Inherited,
            Visibility::Visible => Visibility::Hidden,
            Visibility::Hidden => Visibility::Visible,
        }
    }
}


impl Visibility {
    /// Changes `Visibility` to the opposite (`Visible` -> `Hidden`, `Hidden` -> `Visible`), does nothing to `Visibility::Inherited`
    pub fn toggle(&mut self) {
        match self {
            Visibility::Inherited => *self = Visibility::Inherited,
            Visibility::Visible => *self = Visibility::Hidden,
            Visibility::Hidden => *self = Visibility::Visible,
        };
    }

    /// Changes `Visibility` to the opposite (`Visible` -> `Hidden`, `Hidden` -> `Visible`), changes `Visibility::Inherited` to `Visibility::Hidden`
    pub fn toggle_inherited(&mut self) {
        match self {
            Visibility::Inherited => *self = Visibility::Hidden,
            Visibility::Visible => *self = Visibility::Hidden,
            Visibility::Hidden => *self = Visibility::Visible,
        };
    }
}

```

**Comment by Lubba-64** [comment]
> I'm not sure if that's exactly what You meant, so I'm posting it as a comment not PR
> 
> ```rust
> use std::ops::Not;
> 
> /// Converts `Visibility` to the opposite (`Visible` -> `Hidden`, `Hidden` -> `Visible`), does nothing to  `Visibility::Inherited`
> impl Not for Visibility {
>     type Output = Self;
> 
>     fn not(self) -> Self::Output {
>         match self {
>             Visibility::Inherited => Visibility::Inherited,
>             Visibility::Visible => Visibility::Hidden,
>             Visibility::Hidden => Visibility::Visible,
>         }
>     }
> }
> 
> 
> impl Visibility {
>     /// Changes `Visibility` to the opposite (`Visible` -> `Hidden`, `Hidden` -> `Visible`), does nothing to `Visibility::Inherited`
>     pub fn toggle(&mut self) {
>         match self {
>             Visibility::Inherited => *self = Visibility::Inherited,
>             Visibility::Visible => *self = Visibility::Hidden,
>             Visibility::Hidden => *self = Visibility::Visible,
>         };
>     }
> 
>     /// Changes `Visibility` to the opposite (`Visible` -> `Hidden`, `Hidden` -> `Visible`), changes `Visibility::Inherited` to `Visibility::Hidden`
>     pub fn toggle_inherited(&mut self) {
>         match self {
>             Visibility::Inherited => *self = Visibility::Hidden,
>             Visibility::Visible => *self = Visibility::Hidden,
>             Visibility::Hidden => *self = Visibility::Visible,
>         };
>     }
> }
> ```

I think you should probably make this a PR, since the requested behavior is pretty well fulfilled, the only ambiguity from the issue is  the name of `toggle_inherited`, which is a good name.

**Comment by notmd** [comment]
I would not implement this kind of abstraction. It just makes the code more confusing, I will have to read the source to figure out what the method does instead of looking at its name. Toggling the enum with 3 states doesn't make sense at all.

**Comment by rparrett** [comment]
Beating a dead issue, but additionally, the default value of `Visibility` is `Inherited`.

But there's no reasonable one-size-fits-all behavior for toggling or negating `Inherited`, so by default this can't do anything. That seems potentially very confusing. The thing I personally find myself doing most is toggling between `Inherited` and `Hidden`, but this is going to be situational.

Maybe a set of well named convenience methods could work.

**Comment by alice-i-cecile** [comment]
Yeah, a full set of really clear convenience methods would be nice, but I'm not personally dying for it. Inherited visibility makes this *way* more complex!

**Comment by alice-i-cecile** [comment]
For the record, my preference is the `toggle_inherited_visible` naming. No panics though!
