### ISSUE TITLE
Bevy has no clear schedule for updating a camera's `Transform` when using a fixed time step

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy#14873]
## What problem does this solve or what need does it fill?

I'm writing primarily first-person 3D games. My physics engine of choice, Avian, has recently switched from their custom fixed update schedule that ran after `Update` to the real Bevy `FixedMain` schedule, which runs *before* `Update`. Running before update makes sense, as you want to set rendering transforms *after* running the physics.

Now this results in an issue. In first person games, many things are dependent on the current camera rotation. For example, I am currently writing a plugin for picking up props. These want to be as close to the center of the screen as possible while held. This means that I need to update my camera's transform *before* running the physics. So, my order becomes:

1. Read the player's inputs
2. Rotate the camera
3. Run physics

Let's think schedules. The physics need to run in fixed update. The camera rotation *could* run there as well, but ideally, if your framerate allows it, a player should be allowed to update their camera more often. So it needs to be in a variable timestep schedule before fixed update. Hmm, the only one available is `PreUpdate`. But that one also populates the resources needed to read inputs. It's also a popular place to run networking. This means we need to be really careful about our system ordering. Meh. Also, its description says the following:
> [PreUpdate](https://docs.rs/bevy/latest/bevy/app/struct.PreUpdate.html) exists to do “engine/plugin preparation work” that ensures the APIs consumed in [Update](https://docs.rs/bevy/latest/bevy/app/struct.Update.html) are “ready”. [PreUpdate](https://docs.rs/bevy/latest/bevy/app/struct.PreUpdate.html) abstracts out “pre work implementation details”.

The player's camera being rotated while moving the mouse is definitely more than just "pre work implemention details"! In fact, it is part of the core gameplay experience! 
This means that we have no good place to rotate our camera in while following best practices using a very popular camera style.

-----

Bonus issue: what if our physics need to react to `just_pressed` to e.g. shoot a gun when clicking? The fixed update loop will only sometimes catch these events, as it may happen to run 0 times on the frame when we clicked. This means we need to cache the `just_pressed` event somewhere. In which schedule do we do that? `PreUpdate` is more correct for this, as it is "pre work implementation details", but we still need to be careful about ordering.

## What solution would you like?

There are many possibilities. One of them is to add a new schedule between `StateTransition` and `RunFixedMainLoop` called `PreFixedMainLoop` for this use-case.
See @alice-i-cecile's comment below for other options.

## What alternative(s) have you considered?

Leave it as-is and force users to manually add such a schedule.
This is a bit of an issue for me, as I'm trying to write minimal use-case examples for my libraries. If they happen to be first-person and use physics, I need to somehow deal with the fact that I need systems rotating the camera and reading `just_pressed` events. 
I can currently only handle these cleanly by introducing extremely distracting boilerplate to the example or bypassing the issue by letting everything lag one frame behind, which would be teaching the user an antipattern.

## Additional context

See the discussion [started on Discord](https://discord.com/channels/691052431525675048/1124043933886976171/1275886728309375001) and the [continuation](https://discord.com/channels/691052431525675048/749335865876021248/1276190908458598401) for the full context.

In particular, here is a side-by-side demonstration of what happens when you ignore all of this nuance and simply update the camera's transform in `Update`, as I think most people's instinct would be. Left is the version updating stuff correctly as described above, right is the one updating the camera in `Update`:

https://github.com/user-attachments/assets/e569118b-c7fb-4093-b422-e3130b386779

The very noticeable jitter is due to the camera being "one step ahead" of the physics.

**Comment by janhohenheim** [comment]
@alice-i-cecile I intentionally phrased the issue this way to allow for any options, so I don't think this is controversial at all. There *should* be a place to put camera transforms. I can edit the description to make it more clear that adding a new schedule is just one option.

**Comment by janhohenheim** [comment]
For those wanting a quick and very dirty way of hacking this right now, this is option number 7 of that list above:

```rust
use bevy::{app::RunFixedMainLoop, prelude::*, time::run_fixed_main_schedule};

fn main() -> AppExit {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(
            RunFixedMainLoop,
           update_camera.before(run_fixed_main_schedule),
        )
        .add_systems(FixedUpdate, do_physics_stuff))
        .run()
}
```

**Comment by janhohenheim** [comment]
Per discussion with @maniwani, #12465 would also fix this by making it safe to run camera update code inside `FixedUpdate`.

**Comment by cBournhonesque** [comment]
I'm not sure I fully understand the issue.
Why doesn't the order:
- PreUpdate or FixedPreUpdate: read inputs
- FixedPostUpdate: physics
- Update: camera update
work?

Could you provide more detail about
```
In first person games, many things are dependent on the current camera rotation. For example, I am currently writing a plugin for picking up props. These want to be as close to the center of the screen as possible while held. This means that I need to update my camera's transform before running the physics. 
```

You're saying that the physics systems depend on the camera transform, so physics should run only after camera transform?

**Comment by janhohenheim** [comment]
@cBournhonesque my physics depend on the camera position. In the video, you can see that I'm trying to make a cube follow the player's camera for a prop pickup plugin. This means that my order must be:

- Read player input
- Update camera `Transform`
- Update physics

Updating the camera transform in `FixedPreUpdate` would make it run fewer times than the refresh rate allows, which is something one should avoid with cameras.
Reading the input in `PreUpdate` definitely works (if you order stuff correctly), but updating the camera there would be quite the antipattern imo. Also consider that any update in there runs before state transitions, which might make your logic invalid.
