### ISSUE TITLE
Remove duplicated CONTRIBUTING information

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#14884]
This information is now found at https://bevyengine.org/learn/contribute/introduction/. We should remove:

1. https://github.com/bevyengine/bevy/blob/main/CONTRIBUTING.md
2. https://github.com/bevyengine/bevy/blob/main/docs/release_checklist.md
3. https://github.com/bevyengine/bevy/blob/main/docs/the_bevy_organization.md
4. https://github.com/bevyengine/bevy/tree/main/.github/contributing

While we're there, we should also be sure that the README links to the Contributing Guide.

**Comment by alice-i-cecile** [comment]
Only with CONTRIBUTING.md IMO. Everything else should just be removed.

**Comment by TrialDragon** [comment]
> [!NOTE]
> We should also modify `github-actions` bot's "new contributor" message to link to `https://wwww.bevyengine.org/learn/contribute/introduction` rather than `CONTRIBUTING.md`.
