### ISSUE TITLE
Memory usage keeps growing

### ISSUE THREAD

**Issue by linkstar0513** [bevyengine/bevy#1488]
**Bevy version**
Bevy 0.5 main

**Operating system & version**
 Windows 10 20H2

**What you did**
cargo run --example load_gltf

**What you expected to happen**

The memory usage keeps steady

**What actually happened**
The memory usage keeps growing fast

**Additional information**

All examples happens

**Comment by mockersf** [comment]
didn't notice this issue on macOS 10.15.7, usage remained stable around 234MB during 10 minutes

**Comment by linkstar0513** [comment]
> didn't notice this issue on macOS 10.15.7, usage remained stable around 234MB during 10 minutes

![屏幕截图 2021-02-20 215253](https://user-images.githubusercontent.com/38552164/108597905-53b4aa80-73c6-11eb-8ff7-94848c3af1ed.png)
![屏幕截图 2021-02-20 215342](https://user-images.githubusercontent.com/38552164/108597907-5911f500-73c6-11eb-8fa4-9e5e1384bdb7.png)
That's the memory usage on my computer Windows system, and it didn't notice on Linux  system. But it happens on Windows

**Comment by FrankenApps** [comment]
Is this with the DirectX 12 back-end of wgpu?

**Comment by linkstar0513** [comment]
> Is this with the DirectX 12 back-end of wgpu?

I don't specify the back-end，and I open the log. There is  log `Buffer Valid((7, 1, Dx12)) is detached`, I think it's the DirectX 12 back-end of wgpu.

**Comment by visualcode-t** [comment]
Using Windows 20H2 (19042.844) I do not have this issue. Stable at ~65MB.

**Comment by bjorn3** [comment]
Which graphics card and driver version are you both using? Maybe it is a driver specific issue?

**Comment by visualcode-t** [comment]
Tested two versions:
GTX 1080 (27.21.14.5671)
GTX 1080 (27.21.14.6140)

Both work well.

**Comment by linkstar0513** [comment]
> Which graphics card and driver version are you both using? Maybe it is a driver specific issue?

Lenovo notebook.
CPU: AMD R5-4600U
GPU: Integrated Graphics (27.20.11028.5001)

I will update driver, and test again.

**Comment by FrankenApps** [comment]
Can you try to run the wgpu-rs cube sample with version 0.6 and version 0.7 on your AMD computer and check if there is a difference? I think I have recently also stumbled upon this, when I ran it on a system with only the Standard DirectX12 Drivers (no GPU support).

**Comment by linkstar0513** [comment]
> Can you try to run the wgpu-rs cube sample with version 0.6 and version 0.7 on your AMD computer and check if there is a difference? I think I have recently also stumbled upon this, when I ran it on a system with only the Standard DirectX12 Drivers (no GPU support).

Yes, I think you're right. I run the cube sample with the version 0.7. When I set the `WGPU_BACKEND=dx12`, the memory growing fast,  I set `WGPU_BACKEND=vulkan`, the memory usage remained stable.
And it's so on, set the `BEVY_WGPU_BACKEND="vulkan"` it works well. But set the `BEVY_WGPU_BACKEND="dx12"`, the memory usage growing fast. 

So I think it's an issue about wgpu-rs can't work well with the backend of dx12 on the AMD GPU.

**Comment by FrankenApps** [comment]
Did you also try it with version 0.6 and the dx12 backend?
If it works there it might be worth opening an Issue in the upstream `wgpu-rs` repo.

**Comment by linkstar0513** [comment]
> also

On the version of `wgpu-rs`, I set `WGPU_BACKEND="dx12"`, It also render by vulkan. It seems that dx12 backend isn't available on 0.6.

I will open an issue in the `wgpu-rs`, maybe the next release will resolve it.

**Comment by linkstar0513** [comment]
> Did you also try it with version 0.6 and the dx12 backend?
> If it works there it might be worth opening an Issue in the upstream `wgpu-rs` repo.


On the version of wgpu-rs, I set WGPU_BACKEND="dx12", It also render by vulkan. It seems that dx12 backend isn't available on 0.6.

I will open an issue in the wgpu-rs, maybe the next release will resolve it.

**Comment by FrankenApps** [comment]
I think the dx12 backend is available on 0.6: [see here](https://github.com/gfx-rs/wgpu/tree/v0.6). But you will not be able to force it with WGPU_BACKEND="dx12". I try to find out how it can be done with 0.6.

**Comment by linkstar0513** [comment]
> I think the dx12 backend is available on 0.6: [see here](https://github.com/gfx-rs/wgpu/tree/v0.6). But you will not be able to force it with WGPU_BACKEND="dx12". I try to find out how it can be done with 0.6.
> Edit: It should work if you only allow this `BackendBit` in the code: [docs](https://docs.rs/wgpu/0.6.0/wgpu/struct.BackendBit.html#associatedconstant.DX12).
> Just use this [tutorial / example](https://github.com/sotrh/learn-wgpu/tree/0.6/code/beginner/tutorial3-pipeline) and change [that line](https://github.com/sotrh/learn-wgpu/blob/be261244663eb2e543719d9921995cf5352d136e/code/beginner/tutorial3-pipeline/src/main.rs#L24) to
> 
> ```rust
> let instance = wgpu::Instance::new(wgpu::BackendBit::DX12);
> ```

I change  [this line](https://github.com/gfx-rs/wgpu-rs/blob/v0.6/examples/framework.rs#L98) to enable dx12 and run the example `cube`.
The memory usage keeps stable about 308MB. So it's an issue about `wgpu`.

**Comment by alice-i-cecile** [comment]
See also: #1804

**Comment by mockersf** [comment]
this should have been fixed after a dependency update, could you check after a `cargo update`?

**Comment by alice-i-cecile** [comment]
Closed following #1804. Feel free to reopen if you still have an issue.

**Comment by linkstar0513** [comment]
I test it on the latest, it works well. The memory usage remained stable
