### ISSUE TITLE
`ActiveAnimation::set_weight` doesn't return `&mut Self`

### ISSUE THREAD

**Issue by aecsocket** [bevyengine/bevy#14907]
## What problem does this solve or what need does it fill?

All other functions in `bevy_animation`'s `ActiveAnimation` which modify self return `&mut Self`:
- `pub fn pause(&mut self) -> &mut Self {`
- `pub fn set_repeat(&mut self, repeat: RepeatAnimation) -> &mut Self {`
- `pub fn set_speed(&mut self, speed: f32) -> &mut Self {`

`set_weight` returns `()`:
- `pub fn set_weight(&mut self, weight: f32) {`

This harms ergonomics when chaining function calls.

## What solution would you like?

`pub fn set_weight(&mut self, weight: f32) -> &mut Self`

## What alternative(s) have you considered?

Extracting out the `&mut ActiveAnimation` to its own local variable binding, which hurts ergonomics.

## Additional context

Any other information you would like to add such as related previous work,
screenshots, benchmarks, etc.

**Comment by alice-i-cecile** [comment]
I'd welcome a PR here.
