### ISSUE TITLE
Don't count picking hits on button rounded corners

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#14941]
## What problem does this solve or what need does it fill?

In Bevy 0.14, areas removed from buttons via rounded corners still count as hits, changing the value of `Interaction` components incorrectly.

## What solution would you like?

The picking backend should exclude these by default, by getting information about the actual shape of the button.

## What alternative(s) have you considered?

We could use alpha testing, but that's likely slower and generally not desirable in the context of UI.

## Additional context

Related to but distinct from https://github.com/bevyengine/bevy/issues/14929, which is for sprites and uses a slower but more general algorithm.

**Comment by ickshonpe** [comment]
If we just use the same border radius SDF function from the UI shader this should be trivial . We should probably store the resolved border radius values in a field in Node, so it only has to be calculated once.

**Comment by mgi388** [comment]
@alice-i-cecile in #14929 I’m using a UiImage which happens to be mostly rounded but in fact the art has a bit of a decorative frame around it. Are you thinking the way to solve that is that I’d need to enable rounded borders on my button and then get a “close enough” result once this ticket is done? I think that’s why the sprite backend alpha testing stood out to me as the solve since for my decorative rounded images it would only trigger interactions when clicking the non alpha parts of the image.

**Comment by ickshonpe** [comment]
There's nothing to stop us adding alpha testing for UiImage nodes as well that would override the SDF check.

**Comment by mgi388** [comment]
I suppose more generally, it’s not rounded button support I was particularly after, but arbitrary UiImage shape support. Eg I also have some chunky arrow images as buttons and was expecting the alpha part to not be clickable. 

As above, if the recommendation is going to be “just add rounded borders to your image button to get an approximation” that’s probably fine and better than what is there now (a rectangular hit space).

**Comment by alice-i-cecile** [comment]
Yep, I'd prefer three options for UI: just AABB, rounded corners and alpha testing. Default to either rounded corners or alpha testing, depending if alpha testing's cost can be measured.

**Comment by ickshonpe** [comment]
https://github.com/user-attachments/assets/5c14d9c7-84f4-4c22-90c3-274f12c05923
