### ISSUE TITLE
Bevy doesn't build on macOS

### ISSUE THREAD

**Issue by lynn-lumen** [bevyengine/bevy#14956]
## Bevy version

latest main (#14916)

## \[Optional\] Relevant system information

I am using `cargo 1.82.0-nightly (ba8b39413 2024-08-16)` on an Apple M1 running macOS Sonoma 14.2.1 

## What you did

Using the setup mentioned above, bevy does not compile with the following error:
error[E0308]: mismatched types
  --> /Users/raphael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/accesskit_macos-0.17.0/src/patch.rs:44:13
   |
44 |             focus_forwarder as unsafe extern "C" fn(_, _) -> _,
   |             ^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected fn pointer `unsafe extern "C" fn(&NSWindow, objc2::runtime::Sel) -> _`
              found fn pointer `unsafe extern "C" for<'a> fn(&'a NSWindow, objc2::runtime::Sel) -> _`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `accesskit_macos` (lib) due to 1 previous error

I assume this is not bevy's fault but it prevents bevy from being built.

**Comment by alice-i-cecile** [comment]
I think the next step here is reproducing this on access_kit alone and filing an issue there.

**Comment by zhaop** [comment]
I have the same issue on MacOS.

https://github.com/rust-lang/rust/issues/129285 is fixed by https://github.com/rust-lang/rust/pull/129288 and added to rust 1.82.0 (planned for October 17, 2024).

In the mean time I was able to get Bevy to build again by choosing rust 1.79.0.

**Comment by DataTriny** [comment]
I can reproduce the error on `nightly-2024-08-21-x86_64-apple-darwin` but not on `nightly-2024-11-16-x86_64-apple-darwin`. So I guess https://github.com/rust-lang/rust/pull/129288 helped.

**Comment by alice-i-cecile** [comment]
Marking as fixed thanks to the upstream Rust nightly release :D Very relieved to see that resolved before it hit stable.
