### ISSUE TITLE
Put some docs on proc-macros.

### ISSUE THREAD

**Issue by mintlu8** [bevyengine/bevy#14965]
## What problem does this solve or what need does it fill?

In VSCode with RA, hovering over proc macros shows its associated docs, in bevy this is.. nothing, which is bad! Most of these docs are on the traits, which is not accessible when you are deriving things.

## What solution would you like?

Document how to use these macros on the macros themselves.

For example, the `QueryData` macro should document how to use
```rust
#[query_data(mutable)]
```

## What alternative(s) have you considered?

Don't document these macros.

**Comment by ItsDoot** [comment]
Related, possibly duplicate: #6195

**Comment by alice-i-cecile** [comment]
Yep, closing as duplicate. I do think we should fix this though.
