### ISSUE TITLE
Wrong type returned when trying to access component that is a Vec of entities

### ISSUE THREAD

**Issue by angelorodem** [bevyengine/bevy#15002]
## Bevy version

0.14.1

Win 11 - nightly

## What you did 
```rust
// i have a snake that has internal nodes of the body, the body are other entities that needs to be accessed and updated,
#[derive(Component)]
struct SnakeAnchor {
    snake_nodes: Vec<Entity>,
}

#[derive(Component)]
struct SnakeNode;

fn chain_nodes(
    mut query: Query<(&mut SnakeAnchor, &Transform)>,
    node_transforms: Query<&mut Transform, With<SnakeNode>>,
) {
    for (anchor, anchor_transform) in &mut query {
        let mut point_A = anchor_transform.translation;
        for node in anchor.snake_nodes.iter() {
            let mut node_transform = node_transforms.get_mut(node);
            if let Ok(transform) = node_transform {}
        }
    }
}

```
Describe how you arrived at the problem. If you can, consider providing a code snippet or link.

## What went wrong
When querying for a component that has a Vec of Entities, the returned value when trying to iterate over it is &dyn Reflect instead of entity

If it's not clear, break this out into:

- what were you expecting?
 an iterator over the Entities
- what actually happened?
 an iterator over &dyn Reflect???

## Additional information

Error message:
**mismatched types
expected struct `bevy::prelude::Entity`
found reference `&dyn bevy::prelude::Reflect`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B8%5D?8#file%3A%2F%2F%2Fq%253A%2Fgit%2Fbevy_chain%2Fsrc%2Fmain.rs)
main.rs(106, 54): arguments to this method are incorrect
query.rs(963, 12): method defined here**

**Comment by alice-i-cecile** [comment]
I've seen this error before when importing various reflection traits. Can you show your imports for this file?

**Comment by SkiFire13** [comment]
I think you have imported [`bevy::reflect::List`](https://docs.rs/bevy/latest/bevy/reflect/trait.List.html), which takes precedence over the `iter` method for slices due to you having a `Vec`.

If you avoid importing it, it should compile.

---

On a sidenote, your queries conflict because there could be an entity with both `SnakeAnchor` and `SnakeNode`, in which case you would get access to the same `Transform` both mutably and immutably, which is not allowed.

**Comment by angelorodem** [comment]
No, i dont have any other imports but prelude

**Comment by angelorodem** [comment]
> I think you have imported [`bevy::reflect::List`](https://docs.rs/bevy/latest/bevy/reflect/trait.List.html), which takes precedence over the `iter` method for slices due to you having a `Vec`.
> 
> If you avoid importing it, it should compile.
> 
> ---
> 
> On a sidenote, your queries conflict because there could be an entity with both `SnakeAnchor` and `SnakeNode`, in which case you would get access to the same `Transform` both mutably and immutably, which is not allowed.

You are right, it got auto imported, i feel dumb, sorry to waste your time, thanks.

**Comment by alice-i-cecile** [comment]
It's okay, it's nice to have the fix available in a searchable way!
