### ISSUE TITLE
Examples with Rendering Crash on main (#f0560b8)

### ISSUE THREAD

**Issue by cryscan** [bevyengine/bevy#15005]
## Bevy version

Main ([f0560b8](https://github.com/bevyengine/bevy/commit/f0560b8e78528afd70ca913cbebf2ed459fa2716))

## Relevant system information

```
SystemInfo {
    os: "Windows 11 Home China",
    kernel: "22631",
    cpu: "AMD Ryzen 7 7840HS w/ Radeon 780M Graphics",
    core_count: "8",
    memory: "15.2 GiB"
}
```

Rust version: rustc 1.80.1 (3f5fd8dd4 2024-08-06) stable

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

## What you did

Compile from source and run any of the examples.

## What went wrong

After the window and background color (and also UI) appears, the program crashes.

## Additional information

```
PS D:\Projects\bevy> cargo r -r --features=bevy_debug_stepping --example alien_cake_addict
    Blocking waiting for file lock on package cache
warning: unused import: `align_of`
  --> crates\bevy_ptr\src\lib.rs:14:11
   |
14 |     mem::{align_of, ManuallyDrop},
   |           ^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `bevy_ptr` (lib) generated 1 warning (run `cargo fix --lib -p bevy_ptr` to apply 1 suggestion)
   Compiling bevy v0.15.0-dev (D:\Projects\bevy)
    Finished `release` profile [optimized] target(s) in 10.67s
     Running `target\release\examples\alien_cake_addict.exe`
2024-09-01T09:14:05.617675Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Home China", kernel: "22631", cpu: "AMD Ryzen 7 7840HS w/ Radeon 780M Graphics", core_count: "8", memory: "15.2 GiB" }
2024-09-01T09:14:06.012003Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon 780M Graphics", vendor: 4098, device: 5567, device_type: IntegratedGpu, driver: "AMD proprietary driver", driver_info: "22.40.05.25 (LLPC)", backend: Vulkan }
2024-09-01T09:14:06.194995Z  INFO bevy_winit::system: Creating new window "App" (0v1#4294967296)
error: process didn't exit successfully: `target\release\examples\alien_cake_addict.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

**Comment by cryscan** [comment]
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void) (@boost::serialization::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>::singleton<class boost::serialization::extended_type_info_typeid<union _E_SC_SI_OPT_IR_MODE_SELECTOR>>(void):1724)
DllMain (@DllMain:3410)
1800AE58A (@7ff98f01e58a..7ff98f01e61c:3)
vk_icdNegotiateLoaderICDInterfaceVersion (@vk_icdNegotiateLoaderICDInterfaceVersion:1066)
vk_icdNegotiateLoaderICDInterfaceVersion (@vk_icdNegotiateLoaderICDInterfaceVersion:1066)
1800F84D6 (@7ff98f0684d6..7ff98f06852b:3)
wgpu_hal::vulkan::device::<impl wgpu_hal::Device for wgpu_hal::vulkan::Device>::create_render_pipeline (@wgpu_hal::vulkan::device::<impl wgpu_hal::Device for wgpu_hal::vulkan::Device>::create_render_pipeline:698)
wgpu_core::device::resource::Device<A>::create_render_pipeline (@wgpu_core::device::resource::Device<A>::create_render_pipeline:2078)
wgpu_core::device::global::<impl wgpu_core::global::Global>::device_create_render_pipeline (@wgpu_core::device::global::<impl wgpu_core::global::Global>::device_create_render_pipeline:732)
<wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::device_create_render_pipeline (@<wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::device_create_render_pipeline:221)
<T as wgpu::context::DynContext>::device_create_render_pipeline (@<T as wgpu::context::DynContext>::device_create_render_pipeline:17)
wgpu::Device::create_render_pipeline (@wgpu::Device::create_render_pipeline:24)
141201048 (@7ff75d911048..7ff75d9110d1:3)
std::panicking::try (@std::panicking::try:27)
14148B9DC (@7ff75db9b9dc..7ff75db9ba6c:3)
futures_lite::future::block_on (@futures_lite::future::block_on:844)
std::sys_common::backtrace::__rust_begin_short_backtrace (@std::sys_common::backtrace::__rust_begin_short_backtrace:118)
1420C0759 (@7ff75e7d0759..7ff75e7d07cf:3)
static void std::sys::pal::windows::thread::impl$0::new::thread_start() (@7ff75e84fd7d..7ff75e84fdf7:3)
BaseThreadInitThunk (@BaseThreadInitThunk:12)
RtlUserThreadStart (@RtlUserThreadStart:12)

**Comment by alice-i-cecile** [comment]
Do the wgpu examples work for you?

**Comment by alice-i-cecile** [comment]
Bisecting this would be very useful to us as a next step. I can't reproduce this locally on my Windows laptop or in CI unfortunately.

The other troubleshooting step is updating your graphics drivers, which often fixes this sort of thing in an unsatisfying way.

**Comment by cryscan** [comment]
Thanks. Will have a try.

**Comment by cryscan** [comment]
It works after upgrading the deiver.
