### ISSUE TITLE
Crash on Camera Initialization

### ISSUE THREAD

**Issue by WilliamLin062** [bevyengine/bevy#15006]
## Bevy version

 0.14.1

## Relevant system information

OS   : Window 10 
CPU : intel i5 6400
GPU : AMD Radeon RX 7600
RAM : 16GB

AMD Windows Driver Version  : 31.0.21029.6002
Vulkan™ API Version                 : 1.3.250
Direct3D API Version                : 12.1

## What you did

```
use bevy::prelude::*;

fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}
fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
}

```

## What went wrong

I'm encountering a crash issue in Bevy 0.14.x when adding a camera, but downgrading to 0.13.x resolves the issue.

## Additional information
Log

` bool boost::serialization::singleton<class std::set<class boost::serialization::void_cast_detail::void_caster const *, struct boost::serialization::void_cast_detail::void_caster_compare, class std::allocator<class boost::serialization::void_cast_detail::void_caster const *>>>::is_destroyed(void) + 1195520`

Exception 0xc0000005 encountered at address 0x7fffd9094eb4: Access violation reading location 0x00000008

**Comment by alice-i-cecile** [comment]
Do the wgpu examples run for you?

**Comment by WilliamLin062** [comment]
> wgpu 範例適合您運行嗎？

As a Bevy beginner, I'm not quite sure if I'm following the correct steps. When trying to build a Bevy project for WebAssembly using cargo build --target wasm32-unknown-unknown --release, I encountered the error: error: could not compile 'bevy_render' (lib) due to 33 previous errors. My Rust version is 1.80.1 (3f5fd8dd4 2024-08-06).

**Comment by cryscan** [comment]
Hey this may related to #15005 as I also use an AMD card. I went to AMD's official website and download the latest driver from there, installing this resolved that issue.

**Comment by alice-i-cecile** [comment]
Closing as a duplicate, but let me know if the driver update doesn't fix this.
