### ISSUE TITLE
9-slice images have seams at certain sizes

### ISSUE THREAD

**Issue by Seldom-SE** [bevyengine/bevy#15019]
## Bevy version

0.14.1

## \[Optional\] Relevant system information

On Linux: `AdapterInfo { name: "AMD Radeon RX 570 Series (RADV POLARIS10)", vendor: 4098, device: 26591, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.1.6-arch1.1", backend: Vulkan }`
On Mac: `AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }`

I've also seen the issue on a Google Pixel. I can get the `AdapterInfo` for that if it helps.

## What you did

Spawned a 9-slice image with a certain size:
```rust
use bevy::prelude::*;

pub fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup_scene)
        .run();
}

fn setup_scene(mut commands: Commands, assets: Res<AssetServer>) {
    commands.spawn(Camera2dBundle::default());

    commands.spawn((
        ImageScaleMode::Sliced(TextureSlicer {
            border: BorderRect::square(16.),
            // Bug also occurs with `SliceScaleMode::Stretch`
            sides_scale_mode: SliceScaleMode::Tile { stretch_value: 1. },
            ..default()
        }),
        ImageBundle {
            image: assets.load("9slice.png").into(),
            style: Style {
                align_self: AlignSelf::Center,
                justify_self: JustifySelf::Center,
                width: Val::Px(80.),
                height: Val::Px(40.),
                // This height doesn't repro the bug
                // height: Val::Px(50.),
                ..default()
            },
            ..default()
        },
    ));
}
```

## What went wrong

The image has seams!

![seamful_9-slice](https://github.com/user-attachments/assets/7c0ac292-bf62-4ac2-8333-ce02bf2ce282)

## Additional information

The image is seamless at other sizes:

![seamless_9-slice](https://github.com/user-attachments/assets/4ed3c7d4-7f9b-4bd6-95de-046d74204702)

If I change the background, the color of the seams change with it, so the seams are transparent. Smaller sizes tend to have seams more often. A way to get a feel for it is to change the width and height to `Val::Percent` and resize the window. [Here's my repro](https://github.com/Seldom-SE/testetst/blob/f5dd3113acb84a635d5499fa1c38e542bb1d7dc1/src/main.rs).

**Comment by ickshonpe** [comment]
Duiplicate of #14183, PR here: https://github.com/bevyengine/bevy/pull/14990, needs reviews.
