### ISSUE TITLE
game_menu example doesnt change button colour with mouse interaction

### ISSUE THREAD

**Issue by Liam19** [bevyengine/bevy#15079]
## Bevy version

0.14.2

## What you did

Ran the game_menu example using 'cargo run --example game_menu'

## What went wrong
When hovering and clicking on UI buttons, the colour doesn't change.

## Additional information

Using bevy_inspector_egui I could see that UiImage::color correctly reacts to mouse interaction, but this doesn't translate into the buttons looking different.

**Comment by ickshonpe** [comment]
Yep, colours not changing and the layout is messed up as well:
<img width="843" alt="menu" src="https://github.com/user-attachments/assets/ae55eaa9-827e-4e64-bc4c-f21e1a1182f0">
