### ISSUE TITLE
`add_child` and `push_children` are inconsistently named

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15101]
> Could be interesting to mention in docs that `push_children` is the plural version of `add_child`, or improve naming

_Originally posted by @mockersf in https://github.com/bevyengine/bevy/pull/15096#pullrequestreview-2288560335_

**Comment by alice-i-cecile** [comment]
I don't particularly care which way this goes: `push` is clearer about the behavior (added to the back of the list) but `add` sounds nicer.

**Comment by ickshonpe** [comment]
`push_child/ren` seems like the clearer and more intuitive of the two to me, but `add` is probably okay. Whatever everything should be homogenized the whole way down, there is `push_child_unchecked` also and `add_child` itself queues the command `PushChild`. And then the docs for `PushChild` describe it as a `Command that adds a child to an entity.`  and it calls `add_child` on the `EntityWorldMut` 😕

**Comment by crvarner** [comment]
Personally when I hear `push` I think of queues and stacks and wonder where the `pop` is. I prefer add, but will do whatever.

Should the order of children matter in most instances?
