### ISSUE TITLE
Rename `EntityCommands::add` to `EntityCommands::queue`

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy#15106]
## What problem does this solve or what need does it fill?

The difference between these two is very hard to grasp from a naming point of view:

```rust
commands
  .entity(entity)
  .insert(Foo)
```

```rust
commands
  .entity(entity)
  .add(Foo)
```

## What solution would you like?

Rename `add` to `queue`. That also reflects that the changes happen *later*, not *now*.

## What alternative(s) have you considered?

Just leave it

## Additional context

@alice-i-cecile likes this as well :P

**Comment by SkiFire13** [comment]
Nit: I feel like `enqueue` would be more appropriate, since the method is putting something into a queue, it is not/does not return the queue itself.

**Comment by janhohenheim** [comment]
IME, `enqueue` is fairly obscure for non-English natives, so I'd avoid it. But that's not a strong opinion.

**Comment by SkiFire13** [comment]
This is funny because I'm also a non-native english speaker and I've never heard "queue" used as a verb. I guess it depends on where you live and how you learned english.

**Comment by janhohenheim** [comment]
Hehe, very good argument. I suppose this is regional then. I'll defer to what native speakers recommend in that case :D

**Comment by alice-i-cecile** [comment]
"queue something up" is reasonably common in my dialect of Canadian English, and I think I'd prefer the shorter name to break ties :)

**Comment by Shatur** [comment]
We also have `Commands::push` which is exactly the same as `Commands::add` (which just calls `push`). Maybe just remove it?

**Comment by janhohenheim** [comment]
@Shatur huh, that's weird, you're right. Note that said duplication is *not* present on `EntityCommands`.

**Comment by benfrankel** [comment]
This will also require renaming a few other methods on various types / traits. For example, `ChildBuild::add_command` -> `ChildBuild::queue_command`.
