### ISSUE TITLE
Add missing insert APIs for predicates

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy#15105]
## What problem does this solve or what need does it fill?

For consistency, we are missing the following methods:
- `insert_if_new_and`  (`insert_if_new` + `insert_if`)
- `try_insert_if_new_and` (`try_insert` +`insert_if_new` + `insert_if`)

## Additional context

https://github.com/bevyengine/bevy/pull/14897 added the predicate methods, and we decided to leave these out for some naming bikeshed. This bikeshed happened on [Discord](https://discord.com/channels/691052431525675048/749335865876021248/1282499667619217529). This is a rather uncontroversial result that does not require any big changes.

**Comment by benfrankel** [comment]
Technically there are 4 modifiers for `insert`: `try_`, `_by_id`, `_if_new`, and `_if`. Adding _all_ the missing methods would mean having 16 different insert methods. I assume this issue is not proposing to add all of those methods, but some subset of them. What would that subset be?

**Comment by janhohenheim** [comment]
I didn't know about `by_id`, huh.
This issue was primarily for the `_if` variants that were missing
