### ISSUE TITLE
Resource doesn't get dropped on panic in system. Is this expected?

### ISSUE THREAD

**Issue by navneetankur** [bevyengine/bevy#15144]
## Bevy version
0.14.2
debug build.

## What you did
```
use bevy_ecs::system::{Resource, RunSystemOnce};
#[derive(Resource)]
struct DropyResource(pub u8);
impl Drop for DropyResource {
    fn drop(&mut self) {
        println!("dropy {} dropped.", self.0);
    }
}
fn panicy_system() { panic!("ima panicing"); }
fn main() {
    let d = DropyResource(1);
    let mut world = bevy_ecs::world::World::new();
    world.insert_resource(DropyResource(2));
    world.run_system_once(panicy_system);
}
```

Output:
```
thread 'main' panicked at src/main.rs:9:22:
ima panicing
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
dropy 1 dropped.
```
## What went wrong
DropyResource added to world didn't get "Dropped".

- what were you expecting?
I was expecting to see 
dropy 1 dropped.
dropy 2 dropped.

- what actually happened?

only "dropy 1 dropped."  was printed.

**Comment by SkiFire13** [comment]
This seems to be a deliberate choice

https://github.com/bevyengine/bevy/blob/4de67b5cdb2aee4e6961c75db0f3a0d147585421/crates/bevy_ecs/src/storage/resource.rs#L27-L36

This could however be relaxed to leak only when `SEND` is `false`, since when it's `true` the `validate_access` always immediately returns.

**Comment by navneetankur** [comment]
That seems correct.

@james7132
 Will replacing the condition with
`if !SEND && std::thread::panicking()`
be ok?

**Comment by SkiFire13** [comment]
I believe you need something like:

```rs
if !SEND && self.is_present() {
     if std::thread::panicking() { 
         return; 
     } 
     self.validate_access(); 
}
```

**Comment by navneetankur** [comment]
Thanks
