### ISSUE TITLE
Command to clone entities

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1515]
## What problem does this solve or what need does it fill?

Creating copies of an entity is a powerful but simple abstraction. It's obviously useful for prefab workflows, but I'm also running into it when trying to create multiple copies of attacks and in similar gameplay code.

## What solution would you like?

Create a `fn clone_entity(entity: Entity)` method for `Commands`. It would create a new entity with the same components and the same value of those components as the entity passed in. 

## What alternative(s) have you considered?

You can copy-paste the entity cloning code, but this is a lot of boilerplate and doesn't work well at all if the components in the entity aren't constant.

## Additional context

Solving this is one of the proposed steps to resolve #1446.

This would only work on entities whose components all implement `Clone`, which is common and not onerous, but requires some cleverness to capture. Alternatively, it could clone only those components that do implement clone, although you'd want a warning there.

Initial discussion on solving this in [Discord](https://discord.com/channels/691052431525675048/742884593551802431/814256213567078471).

**Comment by alice-i-cecile** [comment]
I think the correct behavior is actually to try to `Clone` every attached component, and then omit an error (that can either be handled or panic) if it fails. It's unfortunate that it probably has to be runtime, but it should fail very quickly, and you'll want clone on most of your components anyways.

You can further enhance safety by adding archetype invariants (#1481) to the components that can't implement Clone to make them incompatible with the components found on entities you'll want to clone.

**Comment by alice-i-cecile** [comment]
## Desired API

```rs
/// Clones components from the each entity in `source_entities` onto a new entity
/// If the length of cloned_components is > 0, only the components in that bundle are cloned, if they exist
/// Otherwise, all clone-registered components are used
fn clone_entities(source_entities: Vec<Entity>, cloned_components: Vec<ComponentId>)
```

Components can be added to each cloned entity using a chained method with the builder pattern. This is commonly needed for differentiating the clone from the orginal.

Joint effort from @cart, @TheRawMeatball and myself on [Discord](https://discord.com/channels/691052431525675048/749335865876021248/817468564347945003).

**Comment by alice-i-cecile** [comment]
Mock-up implementation by @TheRawMeatball from [Discord](https://discord.com/channels/691052431525675048/749335865876021248/817475419422064660)

```rs
type CloneRegistry = Vec<fn(&mut World, Entity, &mut Commands)>
// in impl AppBuilder
fn register_clonable<T: Clone>(&mut self) {
  self.get_resource_mut::<CloneRegistry>().push(|world, entity, commands| {
    if let Ok(c) = world.get::<T>(entity) {
      commands.with(c.clone());
    }
  })
}

struct CloneEntityCommand {
  list: Vec<Entity>
}

impl Command for CloneEntityCommand {
  fn apply(self: Box<Self>, world: &mut World) {
    let registry = world.get_resource_mut::<CloneRegistry>().clone();
    let mut commands = Commands::new();
    commands.spawn();
    for f in registry.into_iter() {
      for e in self.list.into_iter() {
        (f)(world, e, &mut commands);
      }
    }
  }
}
```

**Comment by TheRawMeatball** [comment]
Can you please use \`\`\`rust code fences?

**Comment by alice-i-cecile** [comment]
> Can you please use ```rust code fences?

Done. I'd missed that "rs" works on Discord, but not on Github.

**Comment by Davier** [comment]
I think the `Clone` registration could be part of `Reflect`, like for `Hash`, `PartialEq` and `Serialize`

**Comment by Davier** [comment]
Actually, it may already be possible using this: <https://github.com/bevyengine/bevy/blob/3a2a68852c0a1298c0678a47adc59adebe259a6f/crates/bevy_ecs/src/reflect.rs#L57>
It doesn't use `Clone` at all, instead it applies a reflected component on a new defaulted component.

**Comment by alice-i-cecile** [comment]
More [follow-up](https://discord.com/channels/691052431525675048/692572690833473578/829446945189396541) on related ideas.

**Comment by alice-i-cecile** [comment]
Relevant [discussion from Amethyst](https://community.amethyst.rs/t/atelier-legion-integration-demo/1352), discussing the traits needed to get asset serialization / deserialization working.

The ideas around component definitions and data transformation seem particularly transferrable here.

**Comment by alice-i-cecile** [comment]
Another Meatball-y draft impl:
```rust
struct EntityCloneSystems(Vec<fn(&mut World, Entity, Entity)>);

fn clone_system<T: Clone + Component>(world: &mut World, target: Entity, reference: Entity) {
    if let Some(v) = world.entity(reference).get::<T>() {
        let v = v.clone();
        world.entity_mut(target).insert(v);
    }
}

// do fancy trait method extension stuff instead
impl AppBuilder {
    pub fn register_clonable<T: Clone + Component>(&mut self) -> &mut Self {
        self.world_mut()
            .get_resource_mut::<EntityCloneSystems>()
            .unwrap()
            .0
            .push(clone_system::<T>);
        self
    }
}
struct CloneEntityCommand(Entity);

impl Command for CloneEntityCommand {
    fn write(self: Box<Self>, world: &mut World) {
        world.resource_scope(|world, systems: Mut<EntityCloneSystems>| {
            let target = world.spawn().id();
            for s in systems.0.iter() {
                s(world, target, self.0);
            }
        })
    }
}
```
1. You register a clonable component.
2.  That pushes a cloning function into a resource.
3. When you go to clone each function is called and attempts to pull out a component, cloning it over if it exists.

**Comment by GianpaoloBranca** [comment]
For anyone struggling with this, here is a gist on how I solved this using the reflections API:
https://gist.github.com/GianpaoloBranca/17e5bd6ada9bdb04cca58182db8505d4

**Comment by nwtnni** [comment]
> For anyone struggling with this, here is a gist on how I solved this using the reflections API: https://gist.github.com/GianpaoloBranca/17e5bd6ada9bdb04cca58182db8505d4

Thanks for the reference! I found a way to modify your solution to remove the unsafe code and the `&World` and `&mut World` aliasing, but at the cost of a *lot* more copying and allocating: https://gist.github.com/nwtnni/85d6b87ae75337a522166c500c9a8418.

In particular, this version has to:
- Clone all of the source components' `ReflectComponent` structs (9 function pointers each at time of writing).
- Clone each source component via [`clone_value`](https://docs.rs/bevy_reflect/latest/bevy_reflect/trait.Reflect.html#tymethod.clone_value) and `clone_dynamic`, which seems expensive.

**Comment by GianpaoloBranca** [comment]
Nice approach! I did some quick benchmark and, at least for my use case, it's slower but it's not that slower. Cloning around 100 entites with 2-4 components each takes roughly 0.5ms for the unsafe version and 1ms for the safe route.

**Comment by LIMachi** [comment]
Minor fix for the safe version: the aggressive usage of unwrap on the type registry will result in a crash if a component is not reflect, here is a fix (and should probably send an optional warning): `.filter_map(|type_id| {
                    registry
                        .get(type_id)
                        .and_then(|registered_type| { registered_type.data::<ReflectComponent>() })
                        .map(|component| { component.clone() })
                })` (by using a filtermap and removing the unwraps, I managed to skip invalid components, but I'm unsure if this the best way of doing this)

**Comment by Multirious** [comment]
I'ved modified the unsafe version a bit to account for children.
Updated `clone_entity_components` to skip children component to stop from cloning invalidate children.
```rust
pub fn clone_entity_components(
    world: &mut World,
    source: Entity,
    destination: Entity,
) {
    let wc = world.as_unsafe_world_cell();
    unsafe {
        let registry = wc.world().get_resource::<AppTypeRegistry>().unwrap();
        let type_registry = registry.read();

        let entity_ref = wc.world().get_entity(source).unwrap();
        let archetype = entity_ref.archetype();
        let components = wc.world().components();

        for component_id in archetype.components() {
            let component_info = components.get_info(component_id).unwrap();
            let type_id = component_info.type_id().unwrap();
            if TypeId::of::<Children>() == type_id {
                continue;
            }
            let registration =
                type_registry.get(type_id).unwrap_or_else(|| {
                    panic!(
                        "expected {} to be registered to type registry",
                        component_info.name()
                    )
                });
            // here is where the magic happens
            let reflect_component =
                registration.data::<ReflectComponent>().unwrap();
            reflect_component.copy(
                wc.world_mut(),
                wc.world_mut(),
                source,
                destination,
            );
        }
    }
}

/// Clone entity including their children.
pub fn clone_entity_recursive(
    world: &mut World,
    source: Entity,
    destination: Entity,
) {
    clone_entity_components(world, source, destination);
    let source = world.get_entity(source).unwrap();
    let source_children = match source.get::<Children>() {
        Some(o) => o,
        None => return,
    };
    let source_children: Vec<Entity> =
        source_children.iter().copied().collect();
    for child in source_children {
        let child_cloned = world.spawn_empty().id();
        clone_entity_recursive(world, child, child_cloned);
        world
            .get_entity_mut(destination)
            .unwrap()
            .add_child(child_cloned);
    }
}
```

**Comment by blueforesticarus** [comment]
Slightly different from this issue, but related and simpler: is there a way to merge entities.

ie. *move* all components of entity A into entity B, and destroy entity A

**Comment by alice-i-cecile** [comment]
Not easily. Might be possible by playing with the internals however.
