### ISSUE TITLE
Paniced with Pen tablet Input

### ISSUE THREAD

**Issue by ptircylinder** [bevyengine/bevy#1516]
## Bevy version
0.4.0

## What you did
Input with a pen tablet in [examples/input/touch_input_event.rs](https://github.com/bevyengine/bevy/blob/main/examples/input/touch_input_events.rs)

## What you expected to happen
It works.

## What actually happened
It paniced if the value of "force" is None.

## Additional information
Ad hoc : [crates/bevy_input/src/touch.rs#L190](https://github.com/bevyengine/bevy/blob/bc4fe9b186db3f32eef38fc4241289df480fa949/crates/bevy_input/src/touch.rs#L190) 
```rust
fn process_touch_event(&mut self, event: &TouchInput) {
    if event.force.is_none() {
        return;
    }
    ...
}
```

**Comment by mockersf** [comment]
👋 

Would you have the line where it panicked? With a quick read of the code, I didn't find where that could happen

**Comment by ptircylinder** [comment]
I should have written it here, sorry.

```
thread 'Compute Task Pool (3)' panicked at 'called `Option::unwrap()` on a `None` value', crates\bevy_input\src\touch.rs:197:74
```

It panicked when the pen is in midair.
