### ISSUE TITLE
Grayscale PNG spritesheet causes blue tints to be ignored

### ISSUE THREAD

**Issue by JeanMertz** [bevyengine/bevy#1518]
## Bevy version

main (c2a427f1a38db6b1d9798e631a7da7a8507fe18c)

## Operating system & version

macOS 11.2.1

## What you did

Load a Greyscale PNG spritesheet (via `from_grid`), set any colours with blue in them.

## What you expected to happen

The blue tint should be applied.

## What actually happened

Blue is ignored, producing inaccurate colour representations.

## Additional information

Opening the png file and re-exporting it as an sRGB file solves the problem.

**Original Spritesheet** (white glyphs with transparent background)

![](https://cdn.discordapp.com/attachments/742884593551802431/814604591999352872/sprite_64x64.png)

**Before**

![](https://cdn.discordapp.com/attachments/742884593551802431/814603559965294642/unknown.png)

**After**

![](https://cdn.discordapp.com/attachments/742884593551802431/814606267623407666/unknown.png)

**Comment by bjorn3** [comment]
The original spritesheet shows as white on black for me. I don't see any blue tint. (using firefox for android)

**Comment by JeanMertz** [comment]
> The original spritesheet shows as white on black for me. I don't see any blue tint.

I probably should have been more clear in my issue description, but this is key:

> Load a Greyscale PNG spritesheet (via `from_grid`), **set any colours with blue in them**.

The original sprite sheet is white (with a transparent background, not black), but when setting the `color` option on `TextureAtlasSprite` to a color with a blue tint, that tint is ignored.

It seems https://github.com/bevyengine/bevy/pull/1524 will fix this though 🎉
