### ISSUE TITLE
Delay in text-update vs layout-update, creating wiggling text

### ISSUE THREAD

**Issue by tjlaxs** [bevyengine/bevy#15197]
## Bevy version

Using main to dev (`1fd478277`)

##  Relevant system information

- cargo 1.80.1 (376290515 2024-07-16)
- Linux terska-2k24 6.8.0-44-generic 44-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 13 13:35:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

## What you did

Started the _text_debug_ example.

## What went wrong

Texts that are on right wiggle one pixel back and forth horizontally.

## Additional information

Not sure if it is related to the texts at the bottom that move around a lot because of the FPS and frame time numbers. You would think the text in the top right would stay still but it still wiggles.

**Note**: You can not see the fps/frame time text until #15190 has been merged because they are pushed out of frame unless you make the window larger.

**Comment by kfjustis** [comment]
Confirmed this happens to me as well.

### My Info
 Bevy: `main, b36443b6`

```SystemInfo { os: "Linux 22.04 Pop!_OS", kernel: "6.9.3-76060903-generic", cpu: "Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz", core_count: "4", memory: "31.3 GiB" }```

Cargo: ```cargo 1.81.0 (2dbb1af80 2024-08-20)```

### Description
Text on the right side wiggled just like the description when I first ran the example. Then I tried resizing the window and different nodes started wiggling for me. When I made the window really narrow, the wiggle stopped, but the wiggle came back when I made the window larger again.

**Comment by tjlaxs** [comment]
Seems like the wiggling is removed when the widest _TextSection_ with changing numbers does not have numbers that change. So my guess is that this is related to the fact that children don't act fast enough to the width changes. Or children of children or something like that.
![image](https://github.com/user-attachments/assets/f8fc14e4-e39a-4259-8145-79567199847f)

**Comment by tjlaxs** [comment]
Looking at the debug outlines:
![image](https://github.com/user-attachments/assets/10ac4dba-3749-452b-bb61-2a93a5bb2c87)
You would think the children of right_column would stay inside the right column, but it looks like not in the wiggle state.

**Comment by alice-i-cecile** [comment]
I bet that the order of our systems is wrong, and we're getting a one-frame delay.
