### ISSUE TITLE
The program statements in the novice tutorial are no longer applicable in the latest version. It is recommended to modify them  |  新手教程中的程序语句在最新版本中不在适用，建议修改。

### ISSUE THREAD

**Issue by molinghu** [bevyengine/bevy#15195]
新手教程中的程序语句在最新版本中已经不再适用，建议修改。
App::build().run();方法在最新版本(0.14.2)中不再可用，根据API Doc中的描述build()已经被new()替代，请对这个问题对教程进行更新否则新手会被教程误导

The program statements in the novice tutorial are no longer applicable in the latest version. It is recommended to modify them.
The App::build().run() method is no longer available in the latest version (0.14.2). According to the description in the API Doc, build() has been replaced by new(). Please update the tutorial for this issue, otherwise novices will be misled by the tutorial.

**Comment by rparrett** [comment]
Could you please provide a link to the tutorial you're discussing?

**Comment by atornity** [comment]
I think it's here https://bevyengine-cn.github.io/learn/book_cn/getting-started/apps/, is that official?

**Comment by rparrett** [comment]
No, you may want to report the issue here: https://github.com/bevyengine-cn/bevyengine-cn.github.io

**Comment by molinghu** [comment]
> 不，您可能想在这里报告问题：https://github.com/bevyengine-cn/bevyengine-cn.github.io

I see. I will submit the issue again at this link. Thank you.
