### ISSUE TITLE
`bevy_color`'s operations are not stable across all hardware due to use of trigonometric float methods

### ISSUE THREAD

**Issue by BenjaminBrienen** [bevyengine/bevy#15236]
## Bevy version

Commit 87afa98167b67e09d5701e49b02e185c8f09439d

## \[Optional\] Relevant system information

[DxDiag.txt](https://github.com/user-attachments/files/17007220/DxDiag.txt)

Lenovo Thinkbook Pro Gen 3
Razer Core X Chroma with an RTX 2060
Samsung Odyssey Neo G9 54"

## What you did

Ran cargo run -p ci -- test

## What went wrong

```
---- oklcha::tests::test_to_from_srgba_2 stdout ----
thread 'oklcha::tests::test_to_from_srgba_2' panicked at crates\bevy_color\src\oklcha.rs:415:13:
gray: Oklcha { lightness: 0.5981808, chroma: 2.3841858e-7, hue: 0.0, alpha: 1.0 } != Oklcha { lightness: 0.5981807, chroma: 9.424322e-8, hue: 18.434948, alpha: 1.0 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

failures:
    oklcha::tests::test_to_from_srgba_2

## Additional information

This is not on main. It is on https://github.com/BenjaminBrienen/bevy/tree/rename-add-to-enqueue

**Comment by alice-i-cecile** [comment]
This is super mysterious: my guess is on a floating point implementation or something being inconsistent.

**Comment by BenjaminBrienen** [comment]
Also happens on the (currently) latest commit ca6056d6d292874e5da57bc4de68429fed1af8ad

**Comment by alice-i-cecile** [comment]
So it's probably not a cosmic ray 😂

**Comment by workingjubilee** [comment]
@BenjaminBrienen What OS?

**Comment by workingjubilee** [comment]
This test involves [transcendental functions](https://github.com/bevyengine/bevy/blob/5a0c09d38fd63383281991da9d6c353ad7228f50/crates/bevy_color/src/oklcha.rs#L263-L283) which have an implementation which varies from operating system to operating system, because they are implemented within software and do not have a specific degree of precision they are evaluated to.

**Comment by workingjubilee** [comment]
It actually should be relatively stable across hardware, ironically, just not software.

**Comment by BenjaminBrienen** [comment]
It happens on bevy/main as well

**Comment by alice-i-cecile** [comment]
@Jondolf says that we should be using https://github.com/bevyengine/bevy/blob/5a0c09d38fd63383281991da9d6c353ad7228f50/crates/bevy_math/clippy.toml, and forbidding the use of the std version of these methods.

IMO we should enable this lint at the workspace level, and allow specific crates to opt-out if they *really* need the performance.

**Comment by BenjaminBrienen** [comment]
I'll try my hand at this

**Comment by BenjaminBrienen** [comment]
All of the math has been moved to bevy_math, but of course I get the same result since libm is not enabled by default. Should I add libm to the default features of bevy_math?

**Comment by alice-i-cecile** [comment]
IMO no; we should enable that by default later after serious benchmarks.
