### ISSUE TITLE
bevy_reflect fails to build

### ISSUE THREAD

**Issue by BenjaminBrienen** [bevyengine/bevy#15242]
## Bevy version

5a0c09d38fd63383281991da9d6c353ad7228f50

## Relevant system information

cargo 1.81.0 (2dbb1af80 2024-08-20)
stable-x86_64-pc-windows-gnu (default)
Windows 11

## What you did

`cargo build --all`

## What went wrong

[output.txt](https://github.com/user-attachments/files/17007895/output.txt)

**Comment by BenjaminBrienen** [comment]
I don't get the error if I just `cargo build`. Only with `cargo build --all`.

**Comment by workingjubilee** [comment]
what's the version of your windows-gnu toolchain?

**Comment by BenjaminBrienen** [comment]
> what's the version of your windows-gnu toolchain?

gcc --version
gcc.exe (x86_64-win32-seh-rev1, Built by MinGW-W64 project) 12.2.0

**Comment by BenjaminBrienen** [comment]
Duplicate of #4758
