### ISSUE TITLE
`init_state` calls done before StatePlugin is added lead to an unwrap error.

### ISSUE THREAD

**Issue by BorisBoutillier** [bevyengine/bevy#15257]
Using Bevy 0.14.2

The following piece of code:
```rust
use bevy::prelude::*;

#[derive(States, Clone, Copy, Default, PartialEq, Eq, Hash, Debug)]
pub enum GameState {
    #[default]
    Main,
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .init_state::<GameState>()
        .run();
}
```

Will fail at runtime with:
```rust
thread 'main' panicked at .cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_state-0.14.2/src/app.rs:70:67:
called `Option::unwrap()` on a `None` value
```

The reason is that `init_state` is called before the `StatePlugin` is added. There are similar `unwrap` calls that will fail with in other state method if the StateSchedule has not yet been added by the StatePlugin before the method call.

I find this error quite unhelpful for standard users.

Should we at least convert these `unwrap` calls to `expect` with a message stating that the StatePlugin should have been added before this method call ? To direct the user to a solution. Or is there a standard way in bevy to report these kind of 'ordering' errors ?

I'll happily provides an associated PR when someone confirms the best course of action to improve the user experience here.

**Comment by MiniaczQ** [comment]
using `expect` and referencing `StatePlugin` seems like the best option

**Comment by alice-i-cecile** [comment]
Agreed, we should do that.

**Comment by BorisBoutillier** [comment]
My bad, I did not search on closed issues, and did not check on main first.
This issue has already been reported, and already been fixed in main.

Same as #14151,  #14237
