### ISSUE TITLE
Audio not always played ?

### ISSUE THREAD

**Issue by ThomasCartier** [bevyengine/bevy#15273]
Hi,
I have a bevy app running via an iframe in a Dioxus app (maybe that's the core of my issues).

The issue I face is that the audio is not always triggered, same for the animation.
As for the animation , I have to reload multiple times my window for it to work fine (load properly, otherwise, it's a black screen).
But the audio may happen once every 20-30 tries.

Latest chromium on Debian Linux.

Is the issue the fact that I run Bevy via an iframe ?

Simplified excerpt:
```
let mut app = App::new();

        app.add_plugins((
                DefaultPlugins
                        .set(AssetPlugin {
                                meta_check: AssetMetaCheck::Never,
                                ..default()
                        })
                        .set(WindowPlugin {
                                primary_window: Some(Window {
                                        fit_canvas_to_parent: true,
                                        canvas: Some(canvas_name),
                                        ..Default::default()
                                }),
                                ..default()
                        })
                        .set(bevy::log::LogPlugin {
                                // Uncomment this to override the default log settings:
                                // level: bevy::log::Level::TRACE,
                                // filter: "wgpu=warn,bevy_ecs=info".to_string(),
                                ..default()
                        })
                        .set(AudioPlugin::default()),
        ));

app.add_systems(Update, play_sound.run_if(runifs_common::run_if_play_audio));
app.run();

```

my audio setup :
```
#[derive(Resource, Default)]

pub(crate) struct Audio {
        pub(crate) url:               Vec<String>,
        pub(crate) current_offset:    usize,
        pub(crate) currently_running: bool
}


pub(crate) fn play_sound(mut commands: Commands, asset_server: Res<AssetServer>, mut audio_bank: ResMut<Audio>) {

        info!("AUDIO IN");

        audio_bank.currently_running = true;

        commands.spawn(AudioBundle {
                source: asset_server.load(format!("sounds/{}", audio_bank.url[audio_bank.current_offset])),
                ..default()
        });

        audio_bank.current_offset += 1;

        audio_bank.current_offset %= audio_bank.url.len();
}

```

the console:

```
found the format marker [49, 44, 33] @ 0+2 bytes. log.target = "symphonia_core::probe";log.module_path = "symphonia_core::probe";log.file = "index.crates.io-6f17d22bba15001f/symphonia-core-0.5.3/src/probe.rs";log.line = 275;
found the format marker [ff, fb] @ 119+2 bytes. log.target = "symphonia_core::probe";log.module_path = "symphonia_core::probe";log.file = "index.crates.io-6f17d22bba15001f/symphonia-core-0.5.3/src/probe.rs";log.line = 275;
using xing header for duration log.target = "symphonia_bundle_mp3::demuxer";log.module_path = "symphonia_bundle_mp3::demuxer";log.file = "index.crates.io-6f17d22bba15001f/symphonia-bundle-mp3-0.5.3/src/demuxer.rs";log.line = 122;
```

and the cargo.toml for bevy:
`bevy = { version = "0.14.2", features = ["mp3", "jpeg"] }`

Are there people running bevy via an iframe experiencing the same thing ?
Bevy inside a canvas in dioxus is not a clean take.

**Comment by ThomasCartier** [comment]
Again, the sound may play once, then when reloading the window, the speaker symbol disappears. Sound gone.

**Comment by ThomasCartier** [comment]
I simplified the stack and remove the iframe in favor of the canvas approach. Animations work better, but still no sound:
`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. `
and 
`Uncaught (in promise) NotAllowedError: A user gesture is required to request Pointer Lock.`

Even clicking on screen won't change anything.

Please note that I animate the camera myself programmatically.

Networking pane show that everything is properly loaded from the server.

When the sound works, which if it has decied to work, only works on the first run of a newly created app.
The beginning of the music is weird (distorted and hashed) and the sound becomes normal 3 seconds  later approx.

I am pretty sure now that the sound is considered autoplay and not muted, requiring approval of the user ? But even clicking on the screen doesn't solve this.

Bevy in release mode, on Chromium, linux.

**Comment by ThomasCartier** [comment]
Adding a button to force user interaction has no effect either..

**Comment by ThomasCartier** [comment]
Putting
```
<audio controls autoplay muted>

      <source src="/sounds/my_sound.mp3" type="audio/mpeg">
      Your browser does not support the audio element.
</audio>
```
in the root html plays the sound when the control is clicked.

The last point of investigation is the combo Dioxus + Bevy.
Maybe Dioxus catch the sound signal after all.
Troubles..

**Comment by ThomasCartier** [comment]
Progress: 
![sound_chromium_default_option](https://github.com/user-attachments/assets/67529220-5a3d-444b-bac7-8ae09bba1cf6)

The issue is that Chromium puts the permission on auto, which I can't enable by code or user interaction. Once I click on "allow", it works without issue.

So I have to find a way to force this option to allow somehow.

**Comment by ThomasCartier** [comment]
O-K. Let me avoid anyone the full headache I went through and here is the answer:
in your js file, [put this code](https://developer.chrome.com/blog/web-audio-autoplay#moving-forward) at the top and let the magic operate.

I will close now and move on.

**Comment by trilltino** [comment]
thanks for this
