### ISSUE TITLE
'bevy_render::pipeline::state_descriptors::PrimitiveTopology\' does not support ReflectValue serialization

### ISSUE THREAD

**Issue by Dmajster** [bevyengine/bevy#1528]
## Bevy version

bc4fe9b186db3f32eef38fc4241289df480fa949

## Operating system & version

Windows 10

## What you did

spawn a PbrBundle and try to serialize it like in the example (https://github.com/bevyengine/bevy/blob/main/examples/scene/scene.rs)

## What you expected to happen

get a serialized RON string of my scene

## What actually happened

My game crashed and produced the following error message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Message("Type \'bevy_render::pipeline::state_descriptors::PrimitiveTopology\' does not support ReflectValue serialization"), position: Position { line: 0, col: 0 } }', src\shared\gameplay\scene_loading.rs:9:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Additional information

Discord user Bd#4705 on Bevy discord server said:

> It's missing #[reflect_value(Serialize, Deserialize, PartialEq, Hash)], all reflected enums should have it. There are a few places where the reflection of bevy types is not complete, you should probably open a broader issue for that.

**Comment by CleanCut** [comment]
@Dmajster Please see if #1533 solves this issue for you.

**Comment by Dmajster** [comment]
Hey, this has indeed solved the issue of saving the scene. But now if I try to load the same scene back into the game I receive the following unrelated error.

`Feb 28 22:54:16.854  WARN bevy_asset::asset_server: encountered an error while loading an asset: No registration found for std::collections::hash::set::HashSet<alloc::string::String, ahash::random_state::RandomState>`

**Comment by CleanCut** [comment]
Hmm. From a glance that appears to be different sort of problem, but I am not very familiar with the asset system. Just in case, would you mind testing with #1536 and see if the more comprehensive reflection cleanup work I did happened to help?

**Comment by mockersf** [comment]
> Hey, this has indeed solved the issue of saving the scene. But now if I try to load the same scene back into the game I receive the following error.
> 
> `Feb 28 22:54:16.854 WARN bevy_asset::asset_server: encountered an error while loading an asset: No registration found for std::collections::hash::set::HashSet<alloc::string::String, ahash::random_state::RandomState>`

You have to register the types of your components in your app builder for them to be usable in a scene.
For example, a lot of basic types are registered in `bevy_app`: https://github.com/bevyengine/bevy/blob/3319195f9036e9ee301545632b98f1090a3ba3b0/crates/bevy_reflect/src/impls/bevy_app.rs#L11-L15
Types used for render are registered in `bevy_render` https://github.com/bevyengine/bevy/blob/89a41bc62843be5f92b4b978f6d801af4de14a2d/crates/bevy_render/src/lib.rs#L129-L134
and so on...

Is this from only default components of Bevy, or are you adding a custom component that is using a `HashSet`?

**Comment by CleanCut** [comment]
As part of #1536 I have started going through the default components in Bevy that derive`Reflect` and making sure they are registered. I've already found a couple that were not being registered.

**Comment by Dmajster** [comment]
> 
> 
> > Hey, this has indeed solved the issue of saving the scene. But now if I try to load the same scene back into the game I receive the following error.
> > `Feb 28 22:54:16.854 WARN bevy_asset::asset_server: encountered an error while loading an asset: No registration found for std::collections::hash::set::HashSet<alloc::string::String, ahash::random_state::RandomState>`
> 
> You have to register the types of your components in your app builder for them to be usable in a scene.
> For example, a lot of basic types are registered in `bevy_reflect`:
> 
> https://github.com/bevyengine/bevy/blob/3319195f9036e9ee301545632b98f1090a3ba3b0/crates/bevy_reflect/src/impls/bevy_app.rs#L11-L15
> 
> Types used for render are registered in `bevy_render`
> 
> https://github.com/bevyengine/bevy/blob/89a41bc62843be5f92b4b978f6d801af4de14a2d/crates/bevy_render/src/lib.rs#L129-L134
> 
> and so on...
> 
> Is this from only default components of Bevy, or are you adding a custom component that is using a `HashSet`?

This issue came up while trying to load the saved scn.ron scene with 0 custom types. This is the scene setup code 

```
fn scene_setup(
    commands: &mut Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    commands
        .spawn(PbrBundle {
            mesh: meshes.add(Mesh::from(shape::Cube { size: 1.0 })),
            material: materials.add(Color::rgb(1.0, 0.0, 0.0).into()),
            ..Default::default()
        })
        .with(Transform::from_xyz(0.0, 8.0, 0.0))
        .with_children(|parent| {
            parent.spawn(PerspectiveCameraBundle {
                transform: Transform::from_xyz(0.0, 0.0, 0.0),
                ..Default::default()
            });
        });

    commands
        .spawn(PbrBundle {
            mesh: meshes.add(Mesh::from(shape::Cube { size: 1.0 })),
            material: materials.add(Color::rgb(0.8, 0.7, 0.6).into()),
            ..Default::default()
        })
        .with(Transform::from_xyz(0.0, 100.0, 0.0));

    commands.spawn(LightBundle {
        transform: Transform::from_xyz(4.0, 8.0, 4.0),
        ..Default::default()
    });
}
```

it produces this .scn.ron structure https://gist.github.com/Dmajster/1388706cee3617648b6c62bc5888b62d

the field it's complaining about is part of bevy_render::pipeline::render_pipelines::RenderPipelines

**Comment by mockersf** [comment]
@CleanCut what do you think about adding in your PR #1536  to [`bevy_render`](https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/lib.rs) (only place it's used in a public component I think) or [`bevy_core`](https://github.com/bevyengine/bevy/blob/main/crates/bevy_core/src/lib.rs) (it's a core type after all)
```rust
.register_type::<bevy_utils::HashSet<String>>()
```
after a quick search it seems it's the only `HashSet` used in something public, no other `HashSet<T>`

There's also a `HashMap` in `bevy_sprite` that would probably error when loading a scene with a `TextureAtlas`: https://github.com/bevyengine/bevy/blob/main/crates/bevy_sprite/src/texture_atlas.rs#L25

**Comment by CleanCut** [comment]
@mockersf It sounds like a good idea to me.
- ✅ Registered `HashSet<String>` in `bevy_core`
- ❌ Attempting to register `<HashMap<Handle<Texture>, usize>>` crashes with an error about the trait `GetTypeRegistration` not being implemented for it. It looks like that trait is implemented as part of a `#[reflect(...)]` or a `#[reflect_value(...)]`, so I _think_ this cannot be registered because `<HashMap<Handle<Texture>, usize>>` is not being reflected in the first place.

**Comment by mockersf** [comment]
oh right, my bad, the texture atlas itself is a ressource, so probably not serialised in a scene

**Comment by Davier** [comment]
The manual `Reflect` implementations for `Vec`, `Hashmap` and `Cow` are in `bevy_reflect/src/impl/std.rs`, and they should be implementing `GetTypeRegistration` too

**Comment by CleanCut** [comment]
> The manual `Reflect` implementations for `Vec`, `Hashmap` and `Cow` are in `bevy_reflect/src/impl/std.rs`, and they should be implementing `GetTypeRegistration` too

This feels like a good place to start a new PR. Can you check out this PR on my fork and let me know if I'm heading in the right direction? https://github.com/CleanCut/bevy/pull/2
