### ISSUE TITLE
bevy_ui: Implement CSS-like calculations for Style API 

### ISSUE THREAD

**Issue by vveisard** [bevyengine/bevy#15307]
## What problem does this solve or what need does it fill?

When styling UI elements we often need to calculate styles properties using multiple values with mixed units (eg, a mixture of percents and pixels).

## What solution would you like?

I propose implementing `Val::Calc` for `bevy_ui::geometry::Val` which represents a calculation to be evaluated. This should resemble the calc API in the web: https://developer.mozilla.org/en-US/docs/Web/CSS/calc

I would like to use plain arithmetic operators to create such calculations.

Usage of this API would look like:
```rust
NodeBundle {
  style: Style {
    position_type: PositionType::Absolute,
    height: Val::Percent(100.0) - Val::Px(10.0),
    ..default()
  },
  ..default()
},
```

## What alternative(s) have you considered?

Workarounds without calculations resemble workarounds present in the web before calc: ie, dummy elements, manual calculation by measuring using JavaScript (which means you have to do your layout twice), etc. All poor solutions.

**Comment by alice-i-cecile** [comment]
Changes to layout like this first need to be implemented upstream in `taffy`, then exposed to users in Bevy :)

**Comment by nicoburns** [comment]
Taffy issue for this feature is https://github.com/DioxusLabs/taffy/issues/225

**Comment by vveisard** [comment]
I see.

This issue is a duplicate of #5893, closing.
