### ISSUE TITLE
Introduce `Populated` system param

### ISSUE THREAD

**Issue by MiniaczQ** [bevyengine/bevy#15302]
## What problem does this solve or what need does it fill?

There have been many requests to not run systems if there is nothing to process (in a query).
The `Populated` system param would do exactly that.

## What solution would you like?

Add `Populated` system param that fails validation if query is empty.

**Comment by alice-i-cecile** [comment]
I'm in favor of this existing: seems quite useful once #15276 is merged. This is a sibling to #15264.

I'd be interested in adding a `NonEmptyEventReader` as well, either in the same PR or in a separate one.

**Comment by benfrankel** [comment]
Bikeshedding, but would `QueryNonEmpty` be a better name? It'd be next to `Query` and `QuerySingle` alphabetically and in code-completion.

**Comment by alice-i-cecile** [comment]
I think that's a bit better, yeah.

**Comment by MiniaczQ** [comment]
I prefer proper spelling, all of them will show up when typing "Query"
I'm fine either way
