### ISSUE TITLE
Feature gate picking backends.

### ISSUE THREAD

**Issue by brandon-reinhart** [bevyengine/bevy#15306]
## What problem does this solve or what need does it fill?

A user may want to turn on picking, but disable specific picking back ends. In my case, I'd rather turn off sprite picking and use a custom, fine-grained bounding box picking backend instead. At the moment there is no way to opt-in to picking but opt-out of particular backends.

## What solution would you like?

Features seem like the right way to do this.

## What alternative(s) have you considered?

Could use a configuration resource or something, but that seems excessive. Most users probably don't need runtime configuration of picking?

**Comment by BenjaminBrienen** [comment]
I'm trying this now
