### ISSUE TITLE
Implement TODO

### ISSUE THREAD

**Issue by BenjaminBrienen** [bevyengine/bevy#15300]
https://github.com/bevyengine/bevy/blob/main/crates%2Fbevy_render%2Fsrc%2Frender_graph%2Fcontext.rs#L84

Should there be a check in the CI to ensure code quality in this regard? We could use [ripgrep](https://github.com/BurntSushi/ripgrep) to detect these comments.

**Comment by MiniaczQ** [comment]
It'd be good to keep track of TODOs, but I wouldn't stop PRs from being merged because of them.
They're often QoL and performance improvements which aren't immediately necessary

**Comment by alice-i-cecile** [comment]
Agreed, I'd rather have these exist than just not being listed.
