### ISSUE TITLE
.exclusive_system() does not fail if the system has the wrong signature

### ISSUE THREAD

**Issue by alec-deason** [bevyengine/bevy#1530]
## Bevy version

bc4fe9b (latest main)

## Operating system & version

Arch linux

## What you did

I accidentally registered a system with a signature including `&mut Commands` and a Query using `.exclusive_system()`

## What you expected to happen

Compile failure, or maybe for it to just work normally.

## What actually happened

The program compiled and the system ran apparently as normal. The query returned results but commands scheduled with Commands never got applied.

## Additional information

In this example you can see that a component is removed using Commands which should cause the Query to stop returning results after the first frame but instead the same entity is returned every frame:

```rust
 use bevy::prelude::*;

 fn main() {
     App::build()
         .add_plugins(DefaultPlugins)
         .add_startup_system(setup.system())
         .add_system(removal.exclusive_system())
         .run();
 }

 struct MyMarkerA;
 struct MyMarkerB;

 fn setup(
     commands: &mut Commands,
 ) {
     commands.spawn((MyMarkerA, MyMarkerB));
 }

 fn removal(
     commands: &mut Commands,
     query: Query<(Entity, &MyMarkerA, &MyMarkerB)>,
 ) {
!    for (entity, a, b) in query.iter() {
         println!("{:?}", entity);
         commands.remove_one::<MyMarkerA>(entity);
     }
 }
 ```

**Comment by Ratysz** [comment]
Parallel systems can be constructed as exclusive systems, this is intended. The commands not being applied is a bug, invesigating.

**Comment by Ratysz** [comment]
Looks like an oversight on my part, which is odd, as I remember thinking about just this problem. #1531 should fix this.
