### ISSUE TITLE
Deny bevy subcrate imports in examples

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15319]
existing CI is
https://github.com/bevyengine/bevy/blob/612897becd415b7b982f58bd76deb719b42c9790/.github/workflows/ci.yml#L418-L438

it currently only checks for `bevy_internal` imports, it could be extended to others

_Originally posted by @mockersf in https://github.com/bevyengine/bevy/issues/15317#issuecomment-2362251757_

**Comment by JMS55** [comment]
I very much would like this.
