### ISSUE TITLE
Screenshot example shouldn't use `bevy_render` directly

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15317]
probably for another PR: this example shouldn't use bevy_render directly. we used to have a CI that errored when that happens

_Originally posted by @mockersf in https://github.com/bevyengine/bevy/pull/15281#discussion_r1767620312_
            
            
Instead these should be `bevy::render` imports.

**Comment by mockersf** [comment]
existing CI is
https://github.com/bevyengine/bevy/blob/612897becd415b7b982f58bd76deb719b42c9790/.github/workflows/ci.yml#L418-L438

it currently only checks for `bevy_internal` imports, it could be extended to others
