### ISSUE TITLE
Use `StableInterpolate` in the camera examples

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15324]
## How can Bevy's documentation be improved?

[StableInterpolate] is a powerful, easy to use tool for stably interpolating movement, avoiding inconsistency due to timestep instability. This should be our default tool for tasks like moving cameras, following players and more.

**Comment by moOsama76** [comment]
this should be already closed right?

**Comment by moOsama76** [comment]
I think #13907 closes this

**Comment by moOsama76** [comment]
#13907 uses this for 2d_top_down_camera.rs but I don't think that any other camera examples need this
