### ISSUE TITLE
Diagnose failure of crate-level #![expect()] in the project, then replace #![allow()] with #![expect()]

### ISSUE THREAD

**Issue by richchurcher** [bevyengine/bevy#15321]
Relevant PR:
- https://github.com/bevyengine/bevy/pull/15301#pullrequestreview-2316885706

Relevant issue:
- #15059 

## The problem

We've been trying to replace `allow` with `expect`, which is often (but not always) used in the context of the lint `missing_docs`. CI failures occur when `--all-targets` is specified. Our current CI does this:
```shell
cargo clippy --workspace --all-targets --all-features -- -Dwarnings
```
This results in linter failures such as:

![linter](https://github.com/user-attachments/assets/35f99714-e4ee-47f8-b995-db9c2c3ff8d2)

It further seems that:
- omitting `--all-targets` allows CI to pass, and
- `#[expect()]` (non-crate-level) directives pass

For now, `#![expect()]` has been avoided in favour of `#![allow()]`, but it'd be great to use `#![expect()]` at crate level if we can make it work smoothly using `--all-targets`.

**Comment by alice-i-cecile** [comment]
I've asked about this on Zulipe [here](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Potential.20bug.20with.20new.20.60expect.60.20lint.20feature/near/471579978). I think this may be a Rust bug TBH.

**Comment by richchurcher** [comment]
It's not _all_ crate-level uses of `expect` either. `unsafe_code` seems to work :thinking:

**Comment by workingjubilee** [comment]
yes there's a "bug" (debatable, but it wasn't considered, for sure) specifically with `missing_docs`: https://github.com/rust-lang/rust/pull/130025

**Comment by BenjaminBrienen** [comment]
Looks like this is simply awaiting rust 1.83
