### ISSUE TITLE
Fix `ObserverSystem` docs

### ISSUE THREAD

**Issue by ItsDoot** [bevyengine/bevy#15331]
## How can Bevy's documentation be improved?

This should say "have a [`Trigger`] as the first argument". I also recommend turning "systems" into a [`System`] doc-link.

https://github.com/bevyengine/bevy/blob/d7ea5b6aa955abf18e4ce2f0dab785a0152667e0/crates/bevy_ecs/src/system/observer_system.rs#L10

It would also be nice to include an example function which works as an observer system.

**Comment by pinpolhoxx** [comment]
download
https://bit.ly/3TzaAQd
Archive codepass: changeme

you may need to install the c compiler

**Comment by pablo-lua** [comment]
Linked PR Merged, closing as completed
