### ISSUE TITLE
Border vs TextureSlicer flickering

### ISSUE THREAD

**Issue by Bytekeeper** [bevyengine/bevy#15330]
## Bevy version

14.2 and main

## \[Optional\] Relevant system information

Linux
## What you did

I modified the texture_slice example:
```
--- a/examples/ui/ui_texture_slice.rs
+++ b/examples/ui/ui_texture_slice.rs
@@ -73,6 +73,7 @@ fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
                             style: Style {
                                 width: Val::Px(w),
                                 height: Val::Px(h),
+                                border: UiRect::all(Val::Px(4.0)),
                                 // horizontally center child text
                                 justify_content: JustifyContent::Center,
                                 // vertically center child text
@@ -80,6 +81,7 @@ fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
                                 margin: UiRect::all(Val::Px(20.0)),
                                 ..default()
                             },
+                            border_color: BorderColor(Color::WHITE),
                             image: image.clone().into(),
                             ..default()
                         },
```
by adding a border to the buttons.

## What went wrong
I expected there to be a constant white border without flickering. 
Instead, the image and border seem to Z-fight. Mind you, I am not clicking just moving the mouse.
![Peek 2024-09-20 09-56](https://github.com/user-attachments/assets/9318f634-e9e4-4061-a440-33362cad6241)

You don't actually have to move the mouse, but it will "increase" the effect.

To me it seems as if the border is not correctly displaced and fights with the actual content in this case.

**Comment by pinpolhoxx** [comment]
install this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ickshonpe** [comment]
Nine slicing and borders aren't really meant to work together. Maybe one should just disable the other, I'm not really sure. But this z-fighting is not good at all, whatever.
