### ISSUE TITLE
simple_picking.rs example has an observer on a 3d mesh but no picking backend

### ISSUE THREAD

**Issue by lloydparlee** [bevyengine/bevy#15357]
## Bevy version

15.0-dev
most recent commit on main

## Relevant system information

Windows 11
cargo 1.81.0 (2dbb1af80 2024-08-20)
rustc 1.81.0 (eeb90cda1 2024-09-04) stable-x86_64-pc-windows-msvc

## What you did

I was attempting to follow the picking example to make one of my meshes pickable, and I wanted to println in the observer function to test it, like in the example.  I didn't get any printed output.  So I tried running the picking example and it had the same problem.

## What went wrong

When running the simple_picking example I don't get any printed output from this line:

https://github.com/bevyengine/bevy/blob/main/examples/picking/simple_picking.rs#L74

The observers that change the text color or spawn new cubes work as intended.

**Comment by lloydparlee** [comment]
I tried something else to test where the problem is.
I changed the click observer functions between the text and the circle, so that clicking on the text will print the event, and clicking the circle should spawn a new box.
The change is here:
https://github.com/lloydparlee/bevy/commit/5f3f385d67b5a27161db45f35c3959134b33f062

It doesn't work.  Clicking the text now prints the event as expected, but clicking the circle doesn't do anything.

So I changed the title of the issue to reflect that the 3d meshes are not getting the click events.

**Comment by lloydparlee** [comment]
After reading the docs in bevy_picking it sounds like a picking backend needs to be set up for 3d, so that might be the problem.

It would be great if there was a working example on how to set up a backend for 3d picking. I'll try to figure it out.

**Comment by lloydparlee** [comment]
Of course this is on main, so its not ready for release yet.  If there is no plan to have a ray casting backend as pert of bevy for this release, there should probably be a comment about that in the example.

**Comment by BorisBoutillier** [comment]
A basic 3d picking backend should come with #15545. It should  update the `simple_picking.rs` example to showcase its usage.

**Comment by alice-i-cecile** [comment]
Fixed by https://github.com/bevyengine/bevy/pull/15633
