### ISSUE TITLE
`ShortName` should work without depending on bevy_reflect

### ISSUE THREAD

**Issue by BenjaminBrienen** [bevyengine/bevy#15351]
## What problem does this solve or what need does it fill?

ShortName was moved into `bevy_reflect` because it seemed logical, but there is one place where it created a "regression" of sorts. `bevy_render` is an optional dependency of `bevy_ecs`, and it didn't used to be necessary for the error reporting functionality of `ScheduleGraph`.

## What solution would you like?

[`ShortName` should be its own crate external to bevy because it solves a problem that is not specific to bevy.](https://github.com/bevyengine/bevy/pull/15340#issuecomment-2365336636)

## What alternative(s) have you considered?

Having it be its own crate within bevy would be possible, but weird.

## Additional context

https://github.com/bevyengine/bevy/pull/15340#issuecomment-2365329191

**Comment by alice-i-cecile** [comment]
I'm in favor of the atomiccow treatment. Ping me if you'd like to tackle this.
