### ISSUE TITLE
Improve diagnostics for or interdict the panic "font size cannot be 0"

### ISSUE THREAD

**Issue by brandon-reinhart** [bevyengine/bevy#15366]
bevy-0.15-dev (main)

There is a panic in cosmic text:

```rust
thread 'Compute Task Pool (21)' panicked at c:\dev\tools\cargo\registry\src\index.crates.io-6f17d22bba15001f\cosmic-text-0.12.1\src\buffer.rs:651:13:
assertion `left != right` failed: font size cannot be 0
  left: 0.0
 right: 0.0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_ui::widget::text::measure_text_system`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

This is tough to track down without systematically commenting out code and doing run cycles to try and binary search for the offending line. It would be great to see this caught further up so that more useful information could be conveyed to the user.

Ideally, this wouldn't panic, but maybe emit a warn or error with diagnostic information?

**Comment by alice-i-cecile** [comment]
Let's swap this to a warning for now.
