### ISSUE TITLE
`run_system_cached` API will reject systems created by `pipe` and `map`

### ISSUE THREAD

**Issue by benfrankel** [bevyengine/bevy#15373]
From https://github.com/bevyengine/bevy/pull/14920#pullrequestreview-2320905305:

> The only maybe issue I can see is that the ZST check won't work for systems created by `pipe` and `map`, even when the systems and closures involved are ZSTs. This is due to `pipe` and `map` eagerly calling `into_system` on their receiver, which will result in non-ZST types even when called on ZST types. The solution would be changing them to be lazy and call `into_system` on their receiver only when `into_system` is directly called on them.

\- @SkiFire13

**Comment by alice-i-cecile** [comment]
(This will be blocked until the linked PR is merged but I don't want to have to change the labels)
