### ISSUE TITLE
Framerate drop after turning on WinitSettings::desktop_app()

### ISSUE THREAD

**Issue by CommonDrum** [bevyengine/bevy#15390]
## Bevy version

0.14.2

## Relevant system information

AdapterInfo { name: "Apple M2", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }

However, the problem showed up on x64 as well.

## What you did

I've added this line to my application:
```        
 .insert_resource(WinitSettings::desktop_app())
```

## What went wrong

After inserting the wininit settings resource, the performance of the application dropped significantly.

## Additional information

I have created a shrunk down version of my original application. The original used bevy rapier for character control. It had other entities that were mobile, and every single one was affected. Removing the line of code fixes all unwanted behavior.

Here is the repository with recreated problem: https://github.com/CommonDrum/wininit_issue

**Comment by alice-i-cecile** [comment]
Isn't the point of setting that value to `desktop_app` to slow the redraw rate? Why did you set it in the first place? This is primarily intended for using Bevy for things like editors and CAD software, not games.

**Comment by CommonDrum** [comment]
I was learning about event systems, and a tutorial/example mentioned this as a way of optimizing an application. I'm new and when facing the low frame rate problem I was instructed to create an issue because it should not work like this. Now I see that it might be a misunderstanding on my part.

**Comment by alice-i-cecile** [comment]
No worries :) Yeah, this is working as intended: this setting does "optimize" applications, but it's optimized for power consumption, not frame rate.
