### ISSUE TITLE
Respect `SystemParam::validate_param` for observers and other non-executor system runners

### ISSUE THREAD

**Issue by MiniaczQ** [bevyengine/bevy#15394]
## What problem does this solve or what need does it fill?

Currently only schedule executors respect the `SystemParam::validate_param` to prevent panics when running systems with unavailable resources.
As a follow up to #15276 this should be implemented for other places that run systems like:
- observers,
- manually executed systems through `&mut World`

## What solution would you like?

Check `validate_param` directly before running the systems and if it fails, don't run them.

**Comment by MiniaczQ** [comment]
Trying to implement this, few topics to resolve:
1. Where to store the warning mechanism (#15391). Right now it's a macro in the executors, but we need it in observers and `run_once` world methods. Should I put it in `system_param.rs`?
2. There is a lot of `validate` -> `run` patterns. The only reason this is separated is for multithreaded executor, where we want to save on task spawning. This would also help us centralize the warnings.
3. Observers don't return values, so validate support is trivial. The problem is in `run_once` methods, which can return a value. We can either:
a) Add `Option` to all return values.
b) Add a new family of methods with `try_` prefix.
The latter is less intrusive, but in the long run it prevents us from **requiring** `validate_param` before running the systems.

**Comment by alice-i-cecile** [comment]
Now that we're actually shipping `Single` and friends, this is a blocker to the 0.15 release: https://discord.com/channels/691052431525675048/749335865876021248/1289685595676868661
