### ISSUE TITLE
Horizontal scroll does not work in `scroll` example

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#15401]
## Bevy version

main

## Relevant system information

```
SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

`cargo run --example scroll`

- Hover over horizontal scroll pane
- Hold left shift and use scroll wheel

## What went wrong

No scrolling occurs.

## Additional information

It seems that the scroll axis is already being changed when the shift key is used at the OS or possibly winit level.

Commenting out https://github.com/bevyengine/bevy/blob/55dddaf72e9c14bf044b3ff2114aac8a92e9fb30/examples/ui/scroll.rs#L394-L397 makes the behavior correct.

**Comment by alice-i-cecile** [comment]
I'd prefer to swap to an alternate hot key for this to avoid clashing, rather than exposing users to this weird platform stuff.

**Comment by rparrett** [comment]
Related: https://github.com/rust-windowing/winit/issues/2387
