### ISSUE TITLE
Vec2.angle_between() returns NaN

### ISSUE THREAD

**Issue by SamJBarney** [bevyengine/bevy#1540]
## Bevy version
0.4.0

## Operating system & version

OSX 11.2.1

## What you did

I created two vectors, one at (0.0, 0.0) and one at (0.1, 1.0).
I then called `angle_between` on the first one passing the second one as an argument.

## What you expected to happen

A valid angle should have been returned.

## What actually happened

The value returned was NaN.

## Additional information

This occurs when either the argument or the caller is at the origin point. It also occurs with Vec3.

**Comment by cart** [comment]
Our VecX types come from the `glam` math lib. Can you file this bug there?
https://github.com/bitshifter/glam-rs/issues

**Comment by SamJBarney** [comment]
Will do

**Comment by bjorn3** [comment]
I think this is expected. When either point is at the origin, there is no sensible angle and as such NaN is returned.

**Comment by SamJBarney** [comment]
How could there be no valid angle? The way you get the angle between the two points is by treating one as the origin. If it can't handle (0,0), then it's programmed wrong. Unless angle_between is calculating something different.

**Comment by mrec** [comment]
I'd expect an `angle_between` function to return the angle between two vectors (these are vectors not points!) applied to an implicit (0,0) origin. If one of the vectors **is** (0,0) then it has no length, which means it doesn't have a meaningful direction, which means there's nothing for the other vector to have an angle *with*.

**Comment by scottmcm** [comment]
> The way you get the angle between the two points is by treating one as the origin. 

Perhaps you're looking for `let v = (p1 - p0); v.y.atan2(v.x)`?

**Comment by alice-i-cecile** [comment]
> I'd expect an angle_between function to return the angle between two vectors (these are vectors not points!) applied to an implicit (0,0) origin. If one of the vectors is (0,0) then it has no length, which means it doesn't have a meaningful direction, which means there's nothing for the other vector to have an angle with.

This explanation sounds correct to me. @cart can we close this?

**Comment by cart** [comment]
Yup thats correct. This can be closed.
