### ISSUE TITLE
Try optimizing animate_targets system

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15412]
> Will it faster if we keep the `&AnimationTarget` here instead of checking if entity has `AnimationTarget` at line 1114？I think it could help reduce the search scope.

_Originally posted by @pyhinox in https://github.com/bevyengine/bevy/pull/15282#discussion_r1773404917_

**Comment by alice-i-cecile** [comment]
Try it, see if it's faster on `many_foxes` and report back!

**Comment by chescock** [comment]
I did not do that in only three minutes :).  I had noticed the issue yesterday and was making a PR anyway when I saw this issue to attach it to.

**Comment by alice-i-cecile** [comment]
@phyinox I'd appreciate your review here if you have the time :)
