### ISSUE TITLE
UI Grid Placement Styles should hold the calculated values during runtime.

### ISSUE THREAD

**Issue by Atlas16A** [bevyengine/bevy#15437]
## What problem does this solve or what need does it fill?
The Getter functions on UI Grid Styles is effectively useless for any form of reactive behaviors as it only gives the set value rather than what was computed the previous frame.

## What solution would you like?
Getter functions on UI Grid styles, such as the grid_placement styles, should return the computed values, not the values set by the setter/at spawn.

## What alternative(s) have you considered?
An Alternative getter function would also work. Perhaps `get_recent` or `get_state`

**Comment by alice-i-cecile** [comment]
Computed values will be non-trivial to get here, since they can depend on the context. I agree that we should expose these though!

**Comment by Atlas16A** [comment]
In general, I'd like to be able to get *all* computed/assumed values for styles during runtime in the future but I figured a more focused area like grid would be good testing ground for difficulty in implementation first.

**Comment by Atlas16A** [comment]
After digging through the UI code i think this might have to be implemented on taffy's end, i dont see anywhere we can save the data on bevy side, but perhaps im missing something?

**Comment by Atlas16A** [comment]
Moving issue to taffy repo.
