### ISSUE TITLE
Consider removing `Return::Unit`

### ISSUE THREAD

**Issue by MichalGniadek** [bevyengine/bevy#15447]
## What problem does this solve or what need does it fill?

Currently the return type of `DynamicFunction` has four variants:
```
pub enum Return<'a> {
    Unit,
    Owned(Box<dyn PartialReflect>),
    Ref(&'a dyn PartialReflect),
    Mut(&'a mut dyn PartialReflect),
}
```

In my opinion a small improvement stop special casing the unit variant and instead just return the equivalent of `()`. This is analogous to rust functions returning `()` instead of some badly-defined `void` "type" like in C++.

## What solution would you like?

- Remove the `Unit` variant
- Instead use `Return::Owned(Box::new(()))`
- Update `Return::is_unit` to check if it's an owned value holding a reflected value representing a unit

## What alternative(s) have you considered?

In my code I currently just have a special case for the unit variant:
```
// where `ret: Return`
if ret.is_unit() {
    ().into()
} else {
    ret.unwrap_owned()
}
```

**Comment by MrGVSV** [comment]
On top of this, we could replace the `Unit` variant with a `unit` convenience function and/or constant:

```rust
// BEFORE:
let value = Return::Unit;

// AFTER:
let value = Return::unit();
// OR
let value = Return::UNIT;
// OR
let value = Return::Owned(Box::new(()));

```
