### ISSUE TITLE
Add `init_resource_with_descriptor`

### ISSUE THREAD

**Issue by MichalGniadek** [bevyengine/bevy#15448]
## What problem does this solve or what need does it fill?

I'm making a scripting language and I would like to be able define resources from it dynamically. I can already do this with components by calling `init_component_with_descriptor` with a `ComponentDescriptor::<Box<dyn PartialReflect>>` but there is no equivalent for resources.

## What solution would you like?

Add `init_component_with_descriptor`
- takes in `ComponentDescriptor`
- a unique `ComponentId` should be returned for each call

## What alternative(s) have you considered?

I have a `Wrapper(Box<dyn PartialReflect>)` and I call `let id = init_resource::<Wrapper>(); remove_resource_by_id(id)` but that doesn't allow for multiple resources with the same underlying type.

**Comment by chompaa** [comment]
Am I misunderstanding something here? Can't you just use [register_component_with_descriptor](https://docs.rs/bevy/latest/bevy/ecs/prelude/struct.World.html#method.init_component_with_descriptor) in conjunction with [insert_resource_by_id](https://docs.rs/bevy/latest/bevy/ecs/prelude/struct.World.html#method.insert_resource_by_id) to achieve this already? Shouldn't that allow for multiple resources with the same type?

I saw [this test](https://github.com/bevyengine/bevy/blob/7ee5143d45f9246f9cffc52e916ae12d85a71779/crates/bevy_ecs/src/world/mod.rs#L3229) when working on a PR for this, which demonstrates what I mean.

I'm not super familiar with ECS internals, so apologies in advance 😅.

**Comment by MichalGniadek** [comment]
> Am I misunderstanding something here?

Nope, I just didn't look hard enough. I thought that because there were some differences between component/resource registration that there were separate id namespaces for resources and components...
