### ISSUE TITLE
Follow up on Retained Rendering

### ISSUE THREAD

**Issue by Trashtalk217** [bevyengine/bevy#15459]
Merging #15320 leaves behind a couple of gaps that can be easily filled in a follow-up PR(s).

### Implement `WorldQuery` for `RenderEntity` and `MainEntity`

When querying `&RenderEntity` currently from within the main world (or `Extract` systems in the render world), you constantly have to call `.id()` on every thing you query, because `RenderEntity` is a component that contains an entity. This indirection is annoying and makes the migration to 0.15 more cumbersome (more line changes), so we can implement a custom `WorldQuery` so that this happens automatically (think of querying `Entity`).

The same is true for `MainEntity`.

### Using required components

There are a couple of places, mainly in `bevy_render/src/extract_component.rs` where `SyncToRenderWorld` is automatically added to certain components. This is currently done with observers, but it's much better to do this with required components. This is being tackled in https://github.com/bevyengine/bevy/pull/15582.

### Deprecating `get_or_spawn`

`get_or_spawn` Is quite often used in extraction systems, given how things used to work. But with a retained rendering world, the entity should always already exist, so just `get` should suffice.

**Comment by hymm** [comment]
We should probably also remove to in-engine uses of TemporaryRenderEntity if possible.

**Comment by Trashtalk217** [comment]
> We should probably also remove the in-engine uses of TemporaryRenderEntity if possible.

Yes, definitely a good idea. Although I expect the solutions for that to be more specific to the rendering context in which they are used.

**Comment by alice-i-cecile** [comment]
> Spawning a specific entity value is rarely the right choice. Most apps should favor [Commands::spawn](https://dev-docs.bevyengine.org/bevy/ecs/prelude/struct.Commands.html#method.spawn). This method should generally only be used for sharing entities across apps, and only when they have a scheme worked out to share an ID space (which doesn’t happen by default).

From `get_or_spawn`'s docs. `insert_or_spawn_batch` has the same warning. Since we're no longer using this internally, we should deprecate this pattern completely as a footgun.

**Comment by JMS55** [comment]
I think we've covered everything but https://github.com/bevyengine/bevy/issues/15704 now?

**Comment by alice-i-cecile** [comment]
> I have a strong motivation to use shared entity ids for multiple worlds

Can you explain this use case? What are you ultimately trying to achieve, and why is this strategy important to do this? The `EntityMapper` trait is designed for the serialization / networking use cases, and has been how Bevy serializes and deserializes scenes since Bevy 0.1 as far as I'm aware.

**Comment by chengts95** [comment]
> > I have a strong motivation to use shared entity ids for multiple worlds
> 
> Can you explain this use case? What are you ultimately trying to achieve, and why is this strategy important to do this? The `EntityMapper` trait is designed for the serialization / networking use cases, and has been how Bevy serializes and deserializes scenes since Bevy 0.1 as far as I'm aware.
```Rust
  
    clone_entities(app.world(), app2.world_mut());
    reg.clone_world(app.world(), app2.world_mut());
```
I simply want to clone worlds, the worlds should have identical IDs for multiple algorithm designs, and I want native performance. The serialized and deserialized scenes are too heavy. Generally, bevy relies on reflection to serialize and deserialize, which is an overkill solution. The serialization is not an option for cloning a world for high-performance applications.

**Comment by Trashtalk217** [comment]
As a bit of extra context, because it's not explained in the warning. One of the issues with spawning arbitrary entities is the fact that under the hood, entity information is stored as a
```
Vec<EntityMeta>
```
see also https://docs.rs/bevy/0.14.2/bevy/ecs/entity/struct.Entities.html. This works well when your entity range is dense, but if you spawn in entity 1,000,000 out of the blue, you need to allocate a lot of memory for this one vector.

Moreover, if you're using this for a save system where you just spawn in the entities by id, this is incredibly brittle when dealing with updating bevy / plugins. If a plugin decides to spawn in an extra entity, you can't load old saves anymore.

These are the primary reasons why we removed / are removing this feature.

**Comment by alice-i-cecile** [comment]
I'm definitely interested in supporting that pattern! I've created #16559 to discuss how this can be best achieved; let's move this over there.
