### ISSUE TITLE
regression in GLTF Scene loading

### ISSUE THREAD

**Issue by eidloi** [bevyengine/bevy#15508]
## Bevy version

0.15.0-dev

## What you did

Migrated code base with a SceneView example to 0.15.0-dev.

## What went wrong

`let scene: Handle<Scene> = asset_server.load(asset);` causes Bevy to hang and never load the asset. This is in a regular system with `asset_server: Res<AssetServer>`.
On the previous version (0.14.2), the asset loaded correctly. There is no error message.

## Additional information

Asset in question: https://github.com/UmbraLuminosa/sickle_ui/blob/main/assets/examples/Low_poly_scene.gltf#Scene0

**Comment by BenjaminBrienen** [comment]
Can you `git bisect` the issue?

**Comment by eidloi** [comment]
> Can you `git bisect` the issue?

It is this commit: https://github.com/bevyengine/bevy/commit/f06cd448db9171bda656ded1e63c68581d6e19aa
NOTE: even before this commit there was a 50-50 chance that the asset would not load either. It would not hang Bevy, you would just get a black screen.

**Comment by eidloi** [comment]
The 50/50 render bug seems to be a side effect of https://github.com/bevyengine/bevy/commit/d9527c101c2f49c6884763cce36ea1d27dd6a597

**Comment by eidloi** [comment]
CC @robtfm, @tychedelia ⬆️

**Comment by eidloi** [comment]
To reproduce I created a new project with toml:

```toml
[package]
name = "find_gltf_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "d9527c101c2f49c6884763cce36ea1d27dd6a597", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_color",
    "bevy_gltf",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "bevy_pbr",
    "bevy_scene",
    "bevy_picking",
    "png",
    "tonemapping_luts",
] }

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
```
And main.rs:
```rust
use bevy::prelude::*;

fn main() {
    let mut app = App::new();

    app.add_plugins(DefaultPlugins.set(WindowPlugin {
        primary_window: Some(Window {
            title: "Find GLTF Bug!".into(),
            resolution: (1280., 720.).into(),
            ..default()
        }),
        ..default()
    }))
    .add_systems(Startup, setup)
    .run();
}

fn setup(asset_server: Res<AssetServer>, mut commands: Commands) {
    commands.spawn((
        Camera3dBundle {
            camera: Camera {
                clear_color: ClearColorConfig::Custom(bevy::color::palettes::css::DARK_GRAY.into()),
                order: 0,
                ..default()
            },
            transform: Transform::from_xyz(0., 2., -3.)
                .looking_at(Vec3::new(0.0, 0.0, 0.0), Vec3::Y),
            ..default()
        },
        FogSettings {
            color: Color::srgb(0.25, 0.25, 0.25),
            falloff: FogFalloff::Linear {
                start: 7.0,
                end: 12.0,
            },
            ..default()
        },
    ));

    let transform = Transform::from_xyz(0., 10., 3.).looking_at(Vec3::new(0.0, 0.0, 0.0), Vec3::Y);
    commands.spawn((DirectionalLightBundle {
        directional_light: DirectionalLight {
            color: Color::srgb(1., 0.953, 0.886),
            shadows_enabled: true,
            ..default()
        },
        transform,
        ..default()
    },));

    commands.spawn((SceneBundle {
        scene: asset_server.load("Low_poly_scene.gltf#Scene0"),
        ..default()
    },));
}
```
(You need to copy the gltf + bin asset from the link in the description to the `assets` folder)

**Comment by robtfm** [comment]
I recently found something similar which I (temporarily) fixed by always using the wasm path for processing texture loads in the gltf loader (around line 400). 

Could you please check if that works for you? If so I think it might be an issue in the task pool/async std stack … or at least it’ll help narrow down the real issue.

**Comment by eidloi** [comment]
> I recently found something similar which I (temporarily) fixed by always using the wasm path for processing texture loads in the gltf loader (around line 400).
> 
> Could you please check if that works for you? If so I think it might be an issue in the task pool/async std stack … or at least it’ll help narrow down the real issue.

didn't make a difference (I tried forcing both branch)

**Comment by robtfm** [comment]
it's a deadlock on `asset_server.infos`, only in the no "multi-threaded" feature case. will make a PR shortly.

thanks for the clean test case.

**Comment by tychedelia** [comment]
I can look into the screenshot issue later if it's still happening after #15522.
