### ISSUE TITLE
Border / radius doesn't respect full Node size.

### ISSUE THREAD

**Issue by eidloi** [bevyengine/bevy#15502]
## Bevy version

0.14.2

## What you did

I use rounded borders on UI elements.

## What went wrong

When there is not enough space for the entire Node to be visible, the node is squished. This is extremely visible with rounded borders, as the rounding gets distorted and remain fully on screen.

- what were you expecting?

Node should be clipped

- what actually happened?

Node get squished.

## Additional information

This is with flex shrink: 0. I think rendering uses the visible clip rect as if it was the full UV 0-1 range, rather than clamping the UV to the visible portion.

The effect is clearly visible on the radio buttons in the gif below, but also notice the button corners remaining on-screen as well:

![border_radius_squish](https://github.com/user-attachments/assets/f307c6de-2d62-4069-be91-2bf3539a2291)

**Comment by alice-i-cecile** [comment]
Can you test this on `main`? @ickshonpe has done a great job fixing a number of small bugs.

**Comment by alice-i-cecile** [comment]
FYI @nicoburns; this may be a taffy bug instead.

**Comment by eidloi** [comment]
> Can you test this on main?

geeez, this might take a hot minute:

```
warning: `sickle_ui_scaffold` (lib) generated 2 warnings
error: could not compile `sickle_ui_scaffold` (lib) due to 178 previous errors; 2 warnings emitted
```

**Comment by alice-i-cecile** [comment]
Well on the bright side the release candidate for 0.15 is slated for October 4th, so you can use this to start the migration 😅

**Comment by eidloi** [comment]
> Well on the bright side the release candidate for 0.15 is slated for October 4th, so you can use this to start the migration 😅

`EntityCommands` consuming itself needs me to rewrite the entire library... again..., so it might take a while.

**Comment by ickshonpe** [comment]
It's still a problem in main, I noticed this as well a day or two ago when I was working on improving `Overflow` support. It's not to do with Taffy, it's just that the renderer isn't changing the coordinates to account for clipping. This wasn't a problem in the border-radius implementation I wrote, I guess that part got lost in the adopted simplified version. I'll work out a fix.

**Comment by eidloi** [comment]
Well, fixing all the build errors got me here, so I am afraid I won't be able to provide further input for the time being.

![Screenshot_226](https://github.com/user-attachments/assets/6f767fd4-77ff-43de-96e5-7ca9b8827467)

**Comment by ickshonpe** [comment]
There are more problems as well, you can see them in this screenshot:

<img width="727" alt="overflow-bugs" src="https://github.com/user-attachments/assets/7368af22-293f-4517-81fe-6dacaf78a3bc">

It's from a modified version of the outlines examples where I added a border radius of 25px to the images. The outline radius should be clipped and the rendered border-radius is elliptical even though we don't support it.
