### ISSUE TITLE
Ambiguous system order and Changed<Component>

### ISSUE THREAD

**Issue by sdfgeoff** [bevyengine/bevy#1551]
## Bevy version

source = "git+https://github.com/bevyengine/bevy?branch=main#d9fb61d474518eba06d0c3dce5cb81db9f7ed66a"

## Operating system & version

Linux

## What you did

Updated from bevy 0.4.0 to latest main and played my game

## What you expected to happen

That my systems would continue to run as before

## What actually happened

Many of my systems became unreliable - they weren't executing or were executing late (causing timeouts on a networking system). Different builds adding `dbg!()` commands changed behaviour etc. etc.

After some digging, I discovered this is likely due to the change: https://github.com/bevyengine/bevy/pull/1144

This change means that systems no longer execute in the order you declare them in. Coupled with the fact that the original Changed<component> issue explicitly states that order independance is a non goal: https://github.com/bevyengine/bevy/issues/54#issuecomment-662750622
This means systems with Changed appeared unreliable.

## Additional information

Technically this isn't a problem. The program is doing as documented: `Changed<component>` states it only works when systems are in order, AppBuilder explicitly states that systems aren't added in any sort of order. Both of those rules are fine. The issue is that the interaction between them is non-obvious to first-time users.

A minimum solution could be documentation on Changed<> noting this interaction and suggesting that any use of it requires explicit system order.

**Comment by Ratysz** [comment]
This is a known problem with heaps of discussion/action around it: #68, #1471.

I think this issue could be scoped to documenting this "effect", both as a stop-gap and as a note on performance for when this is no longer unmanageably flaky.
