### ISSUE TITLE
Sprite example needs type annotations for asset_server.load("path")

### ISSUE THREAD

**Issue by TheLeonsver1** [bevyengine/bevy#1552]
## Bevy version

current bevy main

## Operating system & version

Windows 10

## What you did

tried to replicate the example in https://github.com/bevyengine/bevy/blob/main/examples/2d/sprite.rs

## What you expected to happen

it would "Just Work" after replacing the path string.

## What actually happened

rust analyzer complains, "type annotations needed for `bevy::prelude::Handle<T>`
cannot infer type for type parameter `T` declared on the associated function `load`rustcE0282
systems.rs(15, 9): consider giving `texture_handle` the explicit type `bevy::prelude::Handle<T>`, where the type parameter `T` is specified"

## Possible solution:

I think this line: 
`let texture_handle = asset_server.load("branding/icon.png");`
should be replaced with
`let texture_handle:Handle<Texture> = asset_server.load("branding/icon.png");`
I don't know if this happens only for this example or other examples as well so I didn't open a pr for just this case...

**Comment by rparrett** [comment]
I am unable to reproduce using macOS / vscode / rust-analyzer 2021-03-01 (5df3ee8).

Could you give us some more information about your setup?

**Comment by TheLeonsver1** [comment]
thank you, that solved my issue :), this issue can be closed :)
