### ISSUE TITLE
Created scene_to_nodes on bevy::gltf::Gltf (tracking issue for closed PR #3512)

### ISSUE THREAD

**Issue by richchurcher** [bevyengine/bevy#15534]
> [!NOTE]
_This issue is a reference to an older PR (#3512) which has now been closed. If it could still be valuable to the project, it can be adopted and worked on in a new PR. If you feel that the target PR is no longer viable, and the feature is unwanted or already exists, this issue can be closed. The original PR description is included below._

# Objective

Closes #3511

## Solution

We now keep the mapping from Scene to GltfNodes, by storing the nodes as they are iterated.

**Comment by richchurcher** [comment]
(The PR isn't actually closed yet, the above is in order to refine the message/format/title before we create many more such issues :slightly_smiling_face: )

**Comment by richchurcher** [comment]
Belatedly discovered I can close PRs, so that solves part of my problem :laughing:

**Comment by alice-i-cecile** [comment]
Closing out; this is already tracked in the linked issue.
