### ISSUE TITLE
Make `World::flush_commands` private

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15540]
> Is there a situation where you would want to call `flush_commands` instead of `flush`? If not then it might be made private to avoid potential confusions or misuses.

_Originally posted by @SkiFire13 in https://github.com/bevyengine/bevy/issues/15411#issuecomment-2371606888_

**Comment by nilsiker** [comment]
A lurker here, looking to contribute, and at face value this *looks* harmless. I would be happy to take a look at this, if we're not suspecting any odd implications that might be unclear for a bevy rookie!

It looks to me like `World::flush_commands` should have crate-level visibility (much like `World::flush_entities`). This way we won't disrupt any tests that are setup, while hiding the function for end-users.

**Comment by alice-i-cecile** [comment]
Yes please, that sounds like a perfect approach. Given that `flush_entities` is already private, I think this should be too.
