### ISSUE TITLE
Add CORS header configuration for BRP `RemoteHttpPlugin`

### ISSUE THREAD

**Issue by villor** [bevyengine/bevy#15551]
## What problem does this solve or what need does it fill?

To fully utilize the BRP functionality using web hosted tools, we need a way to set the [`Access-Control-Allow-Origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) header in the responses.

Without being able to set that header, we would have to resort to reverse proxies to get around the issue.

## What solution would you like?

Add a `with_cors` method to `RemoteHttpPlugin`. The method would ensure that  `Access-Control-Allow-Origin` is added to all responses, with the origin provided as a param.

## What alternative(s) have you considered?

We could add the option to set _any_ headers during setup. But I don't know if that is really needed.

## Additional context

See [bevy_react_inspector](https://github.com/villor/bevy_react_inspector) which currently needs a reverse proxy to function.

**Comment by JMS55** [comment]
I'd rather a custom header in general vs specifying cors specifically.

**Comment by spacemen0** [comment]
I think `with_cors` probably make sense? Enabling cors might be the most common in terms of user cases.

**Comment by villor** [comment]
Ideally, we would have both configurable headers and a with_cors for conveniency IMO.

I also believe cors will be the most common use case by far. So an initial solution could be to implement just that method.

**Comment by spacemen0** [comment]
I'm new to bevy but I think I can try working on this

**Comment by villor** [comment]
Solved!

Can now set CORS headers like this:
```rust
app.add_plugins(
    RemoteHttpPlugin::default()
        .with_header("Access-Control-Allow-Origin", "http://localhost:5173"),
)
```
