### ISSUE TITLE
Ability to easily load assets from within a dependency crate 

### ISSUE THREAD

**Issue by ethereumdegen** [bevyengine/bevy#15555]
## What problem does this solve or what need does it fill?

 I would REALLY really like to be able to somehow use assets in an asset folder of a rust dependency as 'assets' that i load with bevy .
for multiple reasons...

 1) i could use this crate shared between my editor and my game 
 
  2) i could make it private in git while keeping my editor public in git
  
  
is there -any- way I can use  assets in an asset folder of a dependency as normal enshrined assets in my bevy project?  AS WELL as also use assets in the normal root asset folder too ?

## What solution would you like?
I would like to be able to put some of my game assets in the assets folder of a dependency crate and be able to load them with bevy assets (like load_folder) as well as still being able to load assets that are in the root /assets folder of the project 

## What alternative(s) have you considered?

Currently I am having to use a git submodule which sucks and has many issues, its very annoying to deal with - i want to be able to keep my games editor open source while also NOT exposing my licensed game assets and also not having to deal with sooo many headaches

## Additional context

 I am using the bevy_asset_loader crate to load assets but i believe the root issue goes deeper than this

**Comment by andriyDev** [comment]
I suspect you don't actually want your crate's assets to "mix" with your binary's assets. Would just making an asset source for your dependencies be sufficient? For that we'd need something like a build script to copy the assets somewhere next to the `assets` folder, and then just have each crate create its own asset source.

Please correct me if you need crate assets and binary assets to be in the same asset source!

**Comment by ethereumdegen** [comment]
Hmmm yeah i think there are many different ways to go about this and approach this and i cant say for sure what i "need" , im not exactly sure what to prescribe here.  

If it were possible to be able to include/access an assets folder of specific dependency crates , such that sub-crates could be providers (sources) of bevy assets , yes.  That would solve my problem.  If that involves copying (?) im not sure .   


I say this would solve my problem because: my games map editor is open source (while i am actively making my game w it ) but i dont want to make my games Assets be open source.   Its hard to juggle rn as im like.. gitignoring stuff out of my assets folder which is a giant pain .  If i could put my games assets in a different git repo, that solves my problem.   And the cleanest way ( besides submodules which i tried and is also messy and a pain ) i can see would be to somehow be able to allow the bevy asset system to load assets not only from the root asset folder, but from some sort of dependency asset folders.   Which could be am asset folder of a dependency crate or some other solution.

**Comment by ethereumdegen** [comment]
To elaborate on your comment , are you suggesting i run a build script to copy assets from a subcrate to my assets folder ?  This perhaps could work yes --  i guess it would be nice to have the functionality as more enshrined though so my build pipeline isnt as messy .   

I think this is going to crop up its head again as the official bevy editor gets built -- there is going to need to be an assets folder for the assets of the editor and a different one for the assets of the game --- right ?  Thats my issue

**Comment by andriyDev** [comment]
First, for your real-life problem, have you tried separate asset sources? Instead of having fine-grained gitignores, you can just have `assets` and `game-assets` or something, and gitignore all of `game-assets`. Or alternatively, just make your asset source point to a completely different folder path which is like your "assets" Git repo. Your specific case may be 

As for this issue (the more general problem of assets in crates), I absolutely agree that this should be something Bevy should do or at least help with. If Bevy could provide like a `bevy_build` crate with utility functions like `create_crate_assets_folder`, that would be nice.

**Comment by ethereumdegen** [comment]
Thats a great idea!! I was thinking abt out other engines like unity or unreal do this ... yeah they do like you describe : theres some other gameassets folder somewhere , could be in .local or appdata or otherwise .    

What is frustrating to me is how its not really possible to do this in bevy / the bevy_asset_loader crate .   If you have used that crate , it only can assume all of your assets are in /assets and i believe this is due to a limitation of bevy itself

**Comment by andriyDev** [comment]
Does bevy_asset_loader not support other asset sources? I would be very surprised. That seems like a bug if true. Bevy does support custom asset sources already, so there should be nothing else Bevy needs to do on its side.

**Comment by ethereumdegen** [comment]
Huh.. okay so you are saying that its possible for me to load assets from /assets and from another folder like /game-assets .    I dont see any docs or examples or anything about that .  

And when i try to load anything w bevy asset loader , it auto prepends (assumes) my paths with /assets soooo .. i feel stuck

**Comment by andriyDev** [comment]
Sorry, here's the example that shows it off. https://github.com/bevyengine/bevy/blob/main/examples/asset/extra_source.rs

**Comment by ethereumdegen** [comment]
Ahhh okay amazing . Thanks ill give this a spin

**Comment by ethereumdegen** [comment]
Okay yes you can close this I got it all working !! 

For anyone else, what I did was i made a separate repo to hold my game assets and that is a private repo.   Each time my editor loads up, I copy the files from that repo into a .gitignored folder ("artifacts")   . It is adjacent to /assets, not inside of it . 

I also configure the artifacts folder as an 'extra source' like the example. 

Then when i use bevy_asset_loader, i can set my path to point at stuff in that 'artifacts' folder by using "../artifacts/game_assets/ ...."  

So now my game assets are totally separate from my editor assets; they have a private git repo while my editor uses a public repo .
