### ISSUE TITLE
Expand WorldCell to support queries

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1555]
# Description
`WorldCell` allows split mutable access to the `World`, via panicking runtime borrows checking. Right now, it can only do so for resources, but it would be nice to be able to have the same functionality for queries too.

# Context
Originally from the Future Work section of #1525.

Personally, I think the API should be removed instead (#3939) and we should implement #4157. However if `WorldCell` *does* exist, it should have this feature.

https://github.com/bevyengine/rfcs/pull/42 proposes this functionality in more depth, and an implementation is linked there.

**Comment by ItsDoot** [comment]
WorldCell was removed in #12551, visit the linked PR for the rationale.
