### ISSUE TITLE
Add a screen shake example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15564]
> Yep, that's fine. We should add a dedicated "screen_shake" example at some point, but that's totally fine to leave for follow-up.

_Originally posted by @alice-i-cecile in https://github.com/bevyengine/bevy/pull/15537#discussion_r1781236731_
            
Use the tools added in #15537 to do this.

**Comment by alice-i-cecile** [comment]
I think this belongs in the `camera` examples folder :)

**Comment by moOsama76** [comment]
May I ask how to link my my file?
![Screenshot 2024-10-01 175516](https://github.com/user-attachments/assets/4da53c36-0444-4e78-b26f-6a73ec4d3b1a)
