### ISSUE TITLE
Add `EntityRef::get_components_dyn()` and `EntityMut::get_components_dyn()` to query multiple components

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#15577]
## What problem does this solve or what need does it fill?

The dynamic query API [`World::get_many_entities_dynamic_mut()`](https://docs.rs/bevy/latest/bevy/ecs/prelude/struct.World.html#method.get_many_entities_dynamic_mut) returns an `EntityMut` which can access all components of an entity... but only one by one. Often you need to access 2+ components at once.

## What solution would you like?

Add the proposed methods which allow retrieving more than 1 component at once.

## What alternative(s) have you considered?

There's no alternative possible from user code I think.

**Comment by hymm** [comment]
One alternative would be a unsafe `get_mut_by_id_unchecked` that takes an `&self`. It'd be a little more awkward to use, but would be maximally flexible.

**Comment by djeedai** [comment]
True. I'd rather have a safer API which validates that I don't request twice the same component though. `get_components_dyn()` can do that, and we can provide an `HashSet`-based variant to skip the check like [`World::get_many_entities_from_set_mut()`](https://docs.rs/bevy/latest/bevy/ecs/prelude/struct.World.html#method.get_many_entities_from_set_mut).

**Comment by hymm** [comment]
I still think there should be a `get_mut_by_id_unchecked`. The apis added in #15593 could end up allocating in some tight loops which would be a perf footgun. The unchecked version would allow users to implement their own versions in userspace that could reuse the allocations.
