### ISSUE TITLE
macOS: camera with shear not working

### ISSUE THREAD

**Issue by BenjaminBrienen** [bevyengine/bevy#15576]
> This is still broken on macOS and will minimally need a quick follow up for that.

_Originally posted by @tychedelia in https://github.com/bevyengine/bevy/pull/15537#issuecomment-2386389530_

**Comment by alice-i-cecile** [comment]
I suspect that this is a scale factor bug, not a MacOS bug, but Mac is the most common platform with scale factors on by default.

**Comment by m-edlund** [comment]
Its reproducible on Linux by adding the following to the Window initialization.
```Rust
resolution: WindowResolution::new(WINDOW_WIDTH, WINDOW_HEIGHT)
                        .with_scale_factor_override(2.0),
```

Will start work on making the example more robust now 👍
