### ISSUE TITLE
Replace SparseArray Option<T> with T::MAX to cut down on branching

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1558]
> would enable cheaper get_unchecked() operations

From Future Work of #1525.

**Comment by bjorn3** [comment]
Cranelift has [`PackedOption`](https://docs.rs/cranelift-entity/0.71.0/cranelift_entity/packed_option/struct.PackedOption.html). This preserves an `Option` like api while using a reserved value of your choice as `None`.

**Comment by cart** [comment]
Ooh I dig that!

**Comment by NathanSWard** [comment]
Is it worth bringing in `cranelift-entity` for `PackedOption` or should we roll our own. 
I've been messing around with `PackedOption`, however it's quite limiting and missing quite a few features including `as_ref` for example.

**Comment by cart** [comment]
The code is small enough that I think rolling our own is probably the move for maximum flexibility / keeping dep count low. Afaik Wrapper would get compiled out, so thats largely just a question of ergonomic right?

**Comment by NathanSWard** [comment]
> The code is small enough that I think rolling our own is probably the move for maximum flexibility / keeping dep count low.
Cool, this is the path I was planning on.

> Wrapper would get compiled out, so thats largely just a question of ergonomic right?
Yep, performance shouldn't be an issue. It was more so a code-cleanliness/ergonomic issue ahah :)

**Comment by james7132** [comment]
This was implemented for non-component SparseSets for all ECS metadata stores (i.e. Resources, Tables, etc.) in #12083. ComponentSparseSet not supporting the full index range of entities will likely be a correctness error. Closing this out as completed.
