### ISSUE TITLE
Add `EntityMut::get_mut_by_id_unchecked`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15603]
> I still think there should be a `get_mut_by_id_unchecked`. The apis added in #15593 could end up allocating in some tight loops which would be a perf footgun. The unchecked version would allow users to implement their own versions in userspace that could reuse the allocations. 

 _Originally posted by @hymm in [#15577](https://github.com/bevyengine/bevy/issues/15577#issuecomment-2389567100)_

**Comment by BenjaminBrienen** [comment]
I intend to work on this

**Comment by mockersf** [comment]
it was also suggested that a variant checking unicity though a hashset could be better:  https://github.com/bevyengine/bevy/issues/15577#issuecomment-2387108509
