### ISSUE TITLE
A Pitch and Yaw camera option would be nice.

### ISSUE THREAD

**Issue by MountainLabsYT** [bevyengine/bevy#15605]
## What problem does this solve or what need does it fill?

Most game engines use a pitch and yaw camera instead of a camera with a position and a looking at position.
I think pitch and yaw camera is superior in most cases.

## What solution would you like?

Add a camera/camera-option that uses pitch and yaw instead of the current implementation.

## What alternative(s) have you considered?

You could just use quaternions for stuff from what i've seen, but that's not as ideal as just having a camera that uses pitch and yaw natively.

**Comment by alice-i-cecile** [comment]
Does the example in https://github.com/bevyengine/bevy/blob/main/examples/camera/camera_orbit.rs meet your needs? IMO cameras are too flexible and heavily customized to ship directly as a library: it's better to give users code to copy-paste :)

**Comment by MountainLabsYT** [comment]
Ehh, I guess. I simply think the implementation shouldn't be so complicated. afterall, there are people genuinely trying to build something worthwhile. 157 LOC is a bit much for a pitch and yaw camera. but whatever works.
