### ISSUE TITLE
`Events::oldest_event_count` and `Events::oldest_id` don't make the difference to each other clear enough

### ISSUE THREAD

**Issue by urben1680** [bevyengine/bevy#15617]
I am not certain if this is a docs issue, but I found this by looking at the source, not by encountering some bug. That is why for now I focused on how the API appears while there are more issues.

The methods [`Events::oldest_event_count`](https://docs.rs/bevy/latest/bevy/ecs/event/struct.Events.html#method.oldest_event_count) and [`Events::oldest_id`](https://docs.rs/bevy/latest/bevy/ecs/event/struct.Events.html#method.oldest_id) seem to do the same thing when looked at the docs or the source.

Also the API itself is confusing. Instead of returning `usize` it should return an `Option<EventId<E>>` because no oldest event might be available currently if the sequences `events_b` and `events_a` are empty.

As a side note, the implementation of `oldest_event_count` looks like that:

```rs
/// Returns the index of the oldest event stored in the event buffer.
pub fn oldest_event_count(&self) -> usize {
    self.events_a
        .start_event_count
        .min(self.events_b.start_event_count)
}
```

When it should be clear that `self.events_b` as the more recent sequence cannot contain the oldest count.

- `oldest_event_count` was added by https://github.com/bevyengine/bevy/pull/5730
- `oldest_id` was added by https://github.com/bevyengine/bevy/pull/5735

**Comment by urben1680** [comment]
Tagging @Aceeri as the author of both methods. 👋

**Comment by Aceeri** [comment]
Ya `oldest_id` should just be renamed to `oldest_event_count` and it's implementation is generally better. Probably just missed this during merging + the reverting of the warning message.
