### ISSUE TITLE
Consider a rename of the `Pickable` component

### ISSUE THREAD

**Issue by tim-blackbird** [bevyengine/bevy#15632]
The `Pickable` component used to be required in `bevy_mod_picking` for an entity to be 'pickable', hence the name.
This requirement has since been lifted and now it is only used to override picking behavior.

The naming is now misleading, making users and [bevy contributors](https://github.com/bevyengine/bevy/blob/main/examples/picking/simple_picking.rs#L32) believe it's still required and so it's proposed to change it. Suggestions welcome

**Comment by mnmaita** [comment]
`PickingBehavior`, `PickingBehaviorOverride`, `PickingOverride` are the names that come to mind based on what it does now.
