### ISSUE TITLE
No method named `reborrow` found for struct `QueryIter` 

### ISSUE THREAD

**Issue by C-Entropy** [bevyengine/bevy#15647]
I want to use the cool `reborrow()`,  so I configure bevy to using the git one:
`bevy = { git = "https://github.com/bevyengine/bevy.git", features = ["wayland", "dynamic_linking"]} # , features = ["dynamic_linking"]
`
then run `cargo clean` and rebuild the code.

However, when build the following code:
```
fn update_cells(mut query: Query<(&CellIndex, &mut CellState, &mut Transform, &mut Sprite)>) {
    let mut iter = query.iter();
    while let Some((cell_index, mut cell_state_, mut transtraom, mut sprite)) = iter.next() {
        for (world_cell_index, world_cell_state, _, _) in iter.reborrow() {
            dbg("here");
        }
    }
}
```

 cargo said:
```
cargo run
   Compiling cell_auto_game v0.1.0 (/home/nil/projects/playground/cell_auto_game)
error[E0599]: no method named `reborrow` found for struct `QueryIter` in the current scope
   --> src/main.rs:119:64
    |
119 |         for (world_cell_index, world_cell_state, _, _) in iter.reborrow() {
    |                                                                ^^^^^^^^
    |
help: there is a method `borrow` with a similar name
    |
119 |         for (world_cell_index, world_cell_state, _, _) in iter.borrow() {
    |                                                                ~~~~~~

For more information about this error, try `rustc --explain E0599`.
error: could not compile `cell_auto_game` (bin "cell_auto_game") due to 1 previous error
```

Please, point me out what I should do to  work it out.

_Originally posted by @C-Entropy in https://github.com/bevyengine/bevy/discussions/14685#discussioncomment-10838997_

I have tried to update the bevy crate:
`cargo update -p bevy`
but the error remains.

**Comment by VitalyAnkh** [comment]
[`reborrow`](https://github.com/bevyengine/bevy/blob/25bfa80e60e886031dd6eb1a3fe2ea548fc0a6c6/crates/bevy_ecs/src/query/iter.rs#L1773) is not `pub`. You should use [`remaining`](https://dev-docs.bevyengine.org/bevy/ecs/query/struct.QueryIter.html#method.remaining).

**Comment by VitalyAnkh** [comment]
You should use the [`reborrow` from `bevy_ecs::system::Query`](https://dev-docs.bevyengine.org/bevy_ecs/system/struct.Query.html#method.reborrow), not that one from `bevy_ecs::query::iter`.
