### ISSUE TITLE
TextBundle should derive Clone

### ISSUE THREAD

**Issue by Jaso333** [bevyengine/bevy#15668]
## What problem does this solve or what need does it fill?

Being able to use preconfigured bundles as templates is something that I find very useful for flexible entity spawning strategies. In all cases so far, I havent had an issue calling `clone` on any bundle, but for some reason `TextBundle` does not drive `Clone`. This makes it difficult to provide a preconfigured template bundle for re-use.

## What solution would you like?

Simply `derive(Clone)` on `TextBundle`.

## What alternative(s) have you considered?

N/A

## Additional context

N/A

**Comment by ItsDoot** [comment]
Bevy is moving away from `Bundle` structs as the primary tool for inserting multiple things at once onto an entity, replacing it with "Required Components". See here for more information: #14791

**Comment by Jaso333** [comment]
> Bevy is moving away from `Bundle` structs as the primary tool for inserting multiple things at once onto an entity, replacing it with "Required Components". See here for more information: [#14791](https://github.com/bevyengine/bevy/pull/14791)

Fair enough, but I do understand that Required Components are not immediately replacing the built-in bundles.

**Comment by arovge** [comment]
It's true that bundles will only be deprecated in 0.15, but it looks like `TextBundle` will be removed with the text rework: https://github.com/bevyengine/bevy/pull/15591

I think I read it's likely the text rework lands in time for 0.15, but others closer to the work can confirm that. I'm not familiar enough with the new text design to know if it helps address your issue - hopefully it does!

**Comment by VitalyAnkh** [comment]
We could close this since `TextBundle` is deprecated with https://github.com/bevyengine/bevy/pull/15591 in Bevy 0.15 and `Text` has derived `Clone`.
