### ISSUE TITLE
Prefer iterator over Vec::push where it makes sense to

### ISSUE THREAD

**Issue by bas-ie** [bevyengine/bevy#15660]
## What problem does this solve or what need does it fill?

Now-closed PR #5775 from `NathanSWard` suggests replacing many instances of `push()` in a loop with an iterator, citing efficiency.

This will not necessarily be a blanket change, as [cart points out](https://github.com/bevyengine/bevy/pull/5775#pullrequestreview-1089488861) and should be benchmarked.

The closed PR is now 2 years old and may have significant bit rot, but could be used as a starting point.

**Comment by BenjaminBrienen** [comment]
This doesn't really have a defined scope. We should just improve specific examples as they are identified instead of having a generic code style enhancement as an issue.
