### ISSUE TITLE
Start using aHash where it makes sense.

### ISSUE THREAD

**Issue by GabLotus** [bevyengine/bevy#157]
There are performance benefits to using aHash over FNVHash. It would be interesting to find out where we can have significant gains and make the necessary changes.

**Comment by denismaxim0v** [comment]
I could probably take a look with some guidance if that's still valid

**Comment by cart** [comment]
#258 largely solved this. There might be a few cases we missed, but I'm comfortable closing this out. If you can find missed cases feel free to open a pr.
