### ISSUE TITLE
Remove `Component` trait impl from `Handle<T>`

### ISSUE THREAD

**Issue by tim-blackbird** [bevyengine/bevy#15716]
# Objective
Remove the `Component` trait implementation from `Handle<T>` as its usage is now considered an anti-pattern.

The move to required components has notably made porting error prone both internally and for the code of early adopters. Due a lack of errors on the usage of high-profile but now no longer relevant `Handle` components like `Handle<Mesh>` and `Handle<StandardMaterial>`.

**Comment by benfrankel** [comment]
This will also resolve https://github.com/bevyengine/bevy/issues/14124

**Comment by tim-blackbird** [comment]
I thought I remembered there already being an issue related to this already :)

I haven't created an issue for `Handle<Image>` since the sprite migration to required components is well on it's way already

**Comment by mgi388** [comment]
@tim-blackbird I think the new handle wrapper components need to be registered in the type registry. I tried locally myself changing one of my own `Handle<Foo>`s to `FooHandle<Foo>` and confirmed in egui inspector if we don't `app.register_type::<FooHandle>()`, then you cannot inspect the component. 

Separately, I was also wondering if the engine should have a macro for this boilerplate? https://github.com/bevyengine/bevy/blob/700123ec647d153b5d6cce70b94ea30efa5c1d86/crates/bevy_animation/src/graph.rs#L133-L149 Fine if not (or if it's not generic enough to be a macro generated for every component wrapper), or if it could come later, but I just wondered if it would help the ecosystem migrate.

**Comment by tim-blackbird** [comment]
I always forget to add those calls to `register_type` 😔
- #15784

We could potentially make use of the `derive_more` crate to cut down on some boilerplate

**Comment by smer44** [comment]
So how to query to get specific Mesh pls?

**Comment by freddycansic** [comment]
> So how to query to get specific Mesh pls?

I managed to do it like this, bear in mind this is for `MeshMaterial2d`, I have not experimented with the regular `MeshMaterial`, but I would assume it works the same.
 
```
fn custom_material_system(
    mut custom_material: ResMut<Assets<CustomMaterial>>,
    specific_mesh: Single<&MeshMaterial2d<CustomMaterial>, With<SpecificMeshComponent>>,
) {
    if let Some(material) = custom_material.get_mut(specific_mesh.0.id()) {
        // Your logic here
    }
}

```
