### ISSUE TITLE
alien_cake_addict example lighting issues

### ISSUE THREAD

**Issue by LiamGallagher737** [bevyengine/bevy#15729]
## Bevy version

e7b83ac

## Relevant system information

```ignore
SystemInfo { os: "Linux 24.05 NixOS", kernel: "6.6.34", cpu: "AMD Ryzen 7 5800X 8-Core Processor", core_count: "8", memory: "31.2 GiB" }
AdapterInfo { name: "NVIDIA GeForce RTX 3060 Ti", vendor: 4318, device: 9353, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "550.78", backend: Vulkan }
```

## What you did

```ingore
cargo r --example alien_cake_addict
```

## What went wrong

At first the lighting is fine, but after losing the game and starting again by pressing space on the game over screen the lighting is messed up.

Here is a video showing it: https://youtu.be/dLpKSMGyS-M

**Comment by LiamGallagher737** [comment]
Currently bisecting the issue.

**Comment by BenjaminBrienen** [comment]
![Image](https://github.com/user-attachments/assets/ad299827-63b7-49d2-be44-4ded13f571ee)
