### ISSUE TITLE
Text is the wrong color

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#15788]
## Bevy version

main, since #14848

## Relevant system information

SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }

## What you did

`cargo run --example text`

## What went wrong

Text in bottom left and top left should be white, but it is grey instead

**Comment by alice-i-cecile** [comment]
FYI @ickshonpe

**Comment by ickshonpe** [comment]
on it

**Comment by ickshonpe** [comment]
Fixed

**Comment by ickshonpe** [comment]
Forgot about setting the corner flags and that caused the antialiasing to misbehave or something.
