### ISSUE TITLE
UI flicker on some MediaTek SoCs

### ISSUE THREAD

**Issue by Litttlefish** [bevyengine/bevy#15792]
## Bevy version

0.14.2

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

Rust version: 1.81.0

Operating systems:
ColorOS 13, Magic UI 6.1

Devices:
OPPO A97 5G, Huawei Honor X40i

SoC used:
MediaTek Dimensity 810, MediaTek Dimensity 700

## What you did

Played the test version of the game that I sent to them

## What went wrong

The game flickers constantly

## Additional information

Other information that can be used to further reproduce or isolate the problem.

Problem screen records:
https://github.com/user-attachments/assets/5987f9d0-e67d-4b24-9151-c4f5821a8ae3
https://github.com/user-attachments/assets/14cfb595-b2e8-4834-8676-969469e2e445

My game mostly uses UI, so probably this is a UI side issue, but citation needed

**Comment by Litttlefish** [comment]
Probably duplicate with #14710 , I'll close this one

**Comment by Litttlefish** [comment]
I'll try to reopen this one

**Comment by Litttlefish** [comment]
Also some information from #14710 :

Android version mentioned: Android 11-14
Compile methods mentioned:
xbuild
cargo-apk
cargo-ndk+Android Studio

Phones mentioned(with SoCs):
Samsung Galaxy A34: MediaTek Dimensity 1080
Redmi Note 8 Pro: MediaTek Helio G90T
Redmi Note 11s Pro: MediaTek Dimensity 920
Phone mentioned in my issue:
OPPO A97 5G: MediaTek Dimensity 810
Huawei Honor X40i: MediaTek Dimensity 700

**Comment by analytik** [comment]
+1, I can reproduce this on 3 of my devices with Bevy 0.17.3, neither using the default settings (Vulkan), nor downlevel_webgl2_defaults and suggesting OpenGL over Vulkan in the AndroidManifest.xml does anything, using the following snippet

```
    <uses-feature android:glEsVersion="0x00030002" android:required="true" />
    <uses-feature android:name="android.hardware.vulkan.version" android:required="false" />
```

For me this flickering happens with the Bevy UI button in the GameActivity variant of the bevy mobile example.

**Comment by Litttlefish** [comment]
> +1, I can reproduce this on 3 of my devices with Bevy 0.17.3, neither using the default settings (Vulkan), nor downlevel_webgl2_defaults and suggesting OpenGL over Vulkan in the AndroidManifest.xml does anything, using the following snippet
> 
> ```
>     <uses-feature android:glEsVersion="0x00030002" android:required="true" />
>     <uses-feature android:name="android.hardware.vulkan.version" android:required="false" />
> ```
> 
> For me this flickering happens with the Bevy UI button in the GameActivity variant of the bevy mobile example.

you can check https://github.com/bevyengine/bevy/issues/14710 for more info
