### ISSUE TITLE
Add CI that checks whether new Examples are in readme

### ISSUE THREAD

**Issue by MinerSebas** [bevyengine/bevy#1581]
## What problem does this solve or what need does it fill?

Many Contributors don't realize that all examples are documented in the [README.md](https://github.com/bevyengine/bevy/blob/main/examples/README.md) inside the examples folder.
Because of this sometimes PR's are merged that forgot this, like #562 where a separate Example was a last-minute change.

## What solution would you like?

Add a CI task, that checks whether all examples are in the readme.

## What alternative(s) have you considered?

Do not automatically check for this and risk missing this Problem.

**Comment by alice-i-cecile** [comment]
There's been several cases of this: I'm in favor.

**Comment by Weibye** [comment]
I would like to try my hand at this, though being new to Rust, Bevy and Github Actions I might need some guidance. I'll dig around a bit and will come back with more succinct questions once I have something more concrete.

**Comment by Weibye** [comment]
I've started working on this and it is coming along nicely. I've used the following as core assumptions / rules for this:

1.  All examples will be within the ./example folder
2.  All examples are required to be listed in the examples/README.md file
3.  Every single .rs file inside the examples folder represents a unique example to be listed

Seeing my current output (below), it is clear that 3. is incorrect. 

**Q: What would be good rules for what files to include or exclude from this check?** 

```Exist in readme: mouse_input_events.rs
Exist in readme: touch_input.rs
Exist in readme: touch_input_events.rs
Does not exist in readme: ./examples/ios/src/lib.rs
Exist in readme: generic_reflection.rs
Exist in readme: reflection.rs
Exist in readme: reflection_types.rs
Exist in readme: trait_reflection.rs```

**Comment by alice-i-cecile** [comment]
@Weibye Files named `lib.rs` are almost certainly correct to exclude. That should be sufficient for now.

**Comment by mockersf** [comment]
The iOS example is specific, as it needs a lot of things and is not considered an example in the Cargo sens.

Rather than ignoring `lib.rs` files, I think we should ignore the `ios` folder.

Also, if it's not too hard to add, could you also check if the example is registered in Bevy's [`Cargo.toml`](https://github.com/bevyengine/bevy/blob/main/Cargo.toml)? This can be done later if you prefer

**Comment by Weibye** [comment]
Pretty confident I now have the core functionality in place, checking examples in folders, in the README and in the Cargo. Currently checking both names and paths and doing so was able to detect some broken links in readme as a result. 

Now, this is written as a custom javascript github action, so I'm now wondering what is the best way of hosting this action?

1. Public repo, under me (i.e weibye/bevy_examples_checker_action)
2. public repo under the Bevy umbrella org
3. Published to the github marketplace (Can't see anyone else have much use for this as it is highly specific to Bevy's needs)
4. Other option that I don't know about

Still have some edge cases to sort out, but I'll set up a draft pull request for the changes needed in the workflow files.

**Comment by mockersf** [comment]
Oh, cool that you're doing it as a standalone action 👍 

As we discussed here, there are probably some specific-to-Bevy hardcoded decisions, but if your willing to do some work to parameterise things (put README/cargo.toml checks behind a parameter flags, add a parameter "ignore" that would be set to "ios" in our case, ...) you could probably talk with this org https://github.com/actions-rs if that would interest them
