### ISSUE TITLE
Systems no longer support up to 16 params

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#1582]
## Bevy version

most recent main branch commit,
ecs v2 commit

## What you did

I don't know where exactly, but somewhere along the way something told me I could have up to 16 params in my systems. After updating bevy, I am finding this to no longer be the case.

```rust
use bevy::prelude::*;

struct One;
struct Two;
struct Three;
struct Four;
struct Five;
struct Six;
struct Seven;
struct Eight;
struct Nine;
struct Ten;
struct Eleven;
struct Twelve;

fn system(
    one: Query<&One>,
    two: Query<&Two>,
    three: Query<&Three>,
    four: Query<&Four>,
    five: Query<&Five>,
    six: Query<&Six>,
    seven: Query<&Seven>,
    eight: Query<&Eight>,
    nine: Query<&Nine>,
    ten: Query<&Ten>,
    eleven: Query<&Eleven>,
    twelve: Query<&Twelve>,
) {
}

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_system(system.system())
        .run();
}
```

## What actually happened

> error[E0599]: no method named `system` found for fn item `for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14, 't15, 't16, 't17, 't18, 't19, 't20, 't21> fn(bevy::prelude::Query<'r, &'s One>, bevy::prelude::Query<'t0, &'t1 Two>, bevy::prelude::Query<'t2, &'t3 Three>, bevy::prelude::Query<'t4, &'t5 Four>, bevy::prelude::Query<'t6, &'t7 Five>, bevy::prelude::Query<'t8, &'t9 Six>, bevy::prelude::Query<'t10, &'t11 Seven>, bevy::prelude::Query<'t12, &'t13 Eight>, bevy::prelude::Query<'t14, &'t15 Nine>, bevy::prelude::Query<'t16, &'t17 Ten>, bevy::prelude::Query<'t18, &'t19 Eleven>, bevy::prelude::Query<'t20, &'t21 Twelve>) {system}` in the current scope

## Additional information

The only "official" mention I can find of the old constraint is in the bevy 0.4 announcement post.

I didn't see any explicit mention of this in the ecs v2 commit message or docs introduced by the ecsv2 commit, but I may have missed it.

## What you expected to happen

If this is intentional some sort of documentation explaining this limitation somewhere would be nice. I'd help, but I'm afraid I don't actually understand the new limitation.

**Comment by alice-i-cecile** [comment]
@cart can we add the 0.5 milestone to this? It's a regression, and I don't immediately see any obvious reason why we can't fix this.

**Comment by tigregalis** [comment]
It's worth mentioning that you can use tuples or the SystemParam derive macro to work around the limit:
```rust
use bevy::{prelude::*, ecs::SystemParam};

struct One;
struct Two;
struct Three;
struct Four;
struct Five;
struct Six;
struct Seven;
struct Eight;
struct Nine;
struct Ten;
struct Eleven;
struct Twelve;
struct Thirteen;
struct Fourteen;
struct Fifteen;
struct Sixteen;
struct Seventeen;
struct Eighteen;
struct Nineteen;
struct Twenty;

#[derive(SystemParam)]
pub struct LastThree<'a> {
    eighteen: Query<'a, &'a Eighteen>,
    nineteen: Query<'a, &'a Nineteen>,
    twenty: Query<'a, &'a Twenty>,
}

fn system(
    one: Query<&One>,
    two: Query<&Two>,
    three: Query<&Three>,
    four: Query<&Four>,
    five: Query<&Five>,
    six: Query<&Six>,
    seven: Query<&Seven>,
    eight: Query<&Eight>,
    nine: Query<&Nine>,
    ten: Query<&Ten>,
    eleven: Query<&Eleven>,
    twelve: Query<&Twelve>,
    thirteen: Query<&Thirteen>,
    fourteen: Query<&Fourteen>,
    (fifteen, sixteen, seventeen): (Query<&Fifteen>, Query<&Sixteen>, Query<&Seventeen>),
    LastThree {
        eighteen,
        nineteen,
        twenty,
    }: LastThree,
) {
}

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_system(system.system())
        .run();
}

```

**Comment by rparrett** [comment]
Yeah, that's a great thing to point out. And big mega-systems are likely a bit of a smell anyway.

Just calling this out in case there's some missing documentation or (unlikely) it's an unanticipated regression.

**Comment by cart** [comment]
This was anticipated (although not communicated explicitly in the v2 pr)

The issue is that SystemParams now have Config, which must implement Default. Rust only implements Default for tuples of length <= 12.

The "fix" would be to add a new ExtendedTupleDefault trait that we impl for all (Default, Default, ...) tuples up to the desired length.

Context in code: https://github.com/bevyengine/bevy/blob/2b0a48d945ec9d10f326f4c97e55b107ab97b054/crates/bevy_ecs/src/system/system_param.rs#L787

**Comment by cart** [comment]
The cost is longer compile times and code complexity, which I opted not to do. But its worth discussing.

**Comment by rparrett** [comment]
I saw mention of a planned 0.4 -> 0.5 migration guide, which seems like the appropriate place to document this sort of thing.

That would resolve the issue for me, so I'll close this.
