### ISSUE TITLE
2d meshes don't render

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#15835]
## Bevy version

main, since #15756

## Relevant system information

SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }

Can't be sure if this is platform-specific at the moment

## What you did

Run an example that uses `Mesh2d`

`cargo run --example mesh2d`
`cargo run --example gamepad_viewer`
`cargo run --example spatial_audio_2d`

## What went wrong

The `Mesh2d` is not displayed.

**Comment by tychedelia** [comment]
@rparrett Gizmos is a separate issue and is being addressed atm.
