### ISSUE TITLE
Make methods on `Time`, `Timer`, and `Stopwatch` more consistent

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#15834]
## Bevy version

0.14 / main

## What you did

Noticed some small inconsistencies between `Time`, `Timer` and `Stopwatch` while refactoring. 

## What went wrong

This may not be totally comprehensive.

| `Time` | `Timer` | `Stopwatch` |
|-|-|-|
[elapsed_seconds](https://docs.rs/bevy/latest/bevy/prelude/struct.Time.html#method.elapsed_seconds) | [elapsed_secs](https://docs.rs/bevy/latest/bevy/prelude/struct.Timer.html#method.elapsed_secs) | [elapsed_secs](https://docs.rs/bevy/latest/bevy/time/struct.Stopwatch.html#method.elapsed_secs)
| [elapsed_seconds_f64](https://docs.rs/bevy/latest/bevy/prelude/struct.Time.html#method.elapsed_seconds_f64) | DNE  | [elapsed_secs_f64](https://docs.rs/bevy/latest/bevy/time/struct.Stopwatch.html#method.elapsed_secs_f64) | 
[is_paused](https://docs.rs/bevy/latest/bevy/prelude/struct.Time.html#method.is_paused) | [paused](https://docs.rs/bevy/latest/bevy/prelude/struct.Timer.html#method.paused) | [paused](https://docs.rs/bevy/latest/bevy/time/struct.Stopwatch.html#method.paused)

At a glance, it seems like we should
- Add `_f64` stuff to `Timer`
- Rename `*_seconds` to `*_secs` or vice versa
- Rename `paused` to `is_paused` or vice versa

## Additional information

When deciding on renames there may be other methods to look at (animation, audio, whatever) with similarly-named methods. e.g. [`AudioSink::is_paused`](https://docs.rs/bevy/latest/bevy/audio/trait.AudioSinkPlayback.html#tymethod.is_paused), [`Duration::from_secs`](https://docs.rs/bevy/latest/bevy/utils/struct.Duration.html#method.from_secs).

**Comment by tim-blackbird** [comment]
> * Rename `*_seconds` to `*_secs` or vice versa

I think we should follow the [rust standard library](https://doc.rust-lang.org/stable/std/?search=_secs) and go with `*_secs`

> * Rename `paused` to `is_paused` or vice versa

The [`std`](https://doc.rust-lang.org/stable/std/?search=-%3E%20bool) shows a clear preference for `is_*`
