### ISSUE TITLE
Add `no_std` Checks to CI

### ISSUE THREAD

**Issue by bushrat011899** [bevyengine/bevy#15840]
## What problem does this solve or what need does it fill?

Bevy contains a number of `no_std` crates (with more hopefully on the way!), but there are currently no tests in the CI to ensure they actually _are_ `no_std` compatible. If any `std` dependency is added (even transiently!), it will break this guarantee.

## What solution would you like?

- Add one or more `no_std` targets to a specific `no_std` `cargo build` CI action. The most obvious platform would be `x86_64_unknown-none`, since Bevy is known to work on `x86_64` across many operating systems. However, more could be added based on community usage (e.g., Raspberry Pi, STM32, etc.). This would ensure it is possible to build Bevy and/or its crates without the `std` library being linked.
- Add a test CI action which disables the `std` feature (and possibly `alloc` as well) to ensure unit tests pass in a `no_std` environment. Note that these tests can be run on a platform _with_ the `std` library, since the above test ensures that the `std` library isn't _used_ directly or transiently.

## What alternative(s) have you considered?

We could do nothing for now. Since the Bevy `no_std` community is just starting, there are currently no users to complain if `no_std` support is broken.

**Comment by joelsa** [comment]
> there are currently no users to complain if `no_std` support is broken

If it is broken, it will stay that way, so these tests are great.
