### ISSUE TITLE
`mesh2d_manual` example doesn't render correctly

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#15847]
## Bevy version

main, since #15524

## Relevant system information

SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }

Also tested win11+4080

## What you did

`cargo run --example mesh2d_manual`

## What went wrong

Example should display a yellow star. But instead it displays some wispy blue lines.

**Comment by LiamGallagher737** [comment]
Same issue on Linux

**Comment by awtterpip** [comment]
i have isolated the commit that caused this issue. its because of the commit 54006b107b921c7339df4e87a407b348effc4009

**Comment by awtterpip** [comment]
should be fixed in #15862

**Comment by awtterpip** [comment]
should be fixed with that pr
