### ISSUE TITLE
CI workflow for breaking changes needs to be updated to match the new label

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15859]
https://github.com/bevyengine/bevy/blob/60a9a81602a5718e683e17b43c8889b607b71ce0/.github/workflows/action-on-PR-labeled.yml#L17

This needs to use the newly renamed `M-Needs-Migration-Guide` label. Spotted in https://github.com/bevyengine/bevy-website/pull/1646

**Comment by ItsDoot** [comment]
Fixed in #15958
