### ISSUE TITLE
`pbr` example is missing one of it labels

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#15853]
## Bevy version

main
bisected to #14848

## Relevant system information

SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }

also tested win11+4080

## What you did

`cargo run --example pbr`

## What went wrong

The vertical "Metallic" label on the right side is missing.

**Comment by ickshonpe** [comment]
Oh yeah, I checked through all the UI examples with this but forgot that none of them feature text rotation. I'll add some slanted text to one of the UI text examples so it doesn't get missed next time.
