### ISSUE TITLE
Replace all uses of `Query::single` with `Single`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15866]
## What problem does this solve or what need does it fill?

`Query::single` and `Query::single_mut` are convenient lazy helpers with a nasty side effect: they panic unless exactly one matching entity is found!

While this is fine, in theory, for polished, tiny example code, it teaches bad habits to our users.

## What solution would you like?

We should swap over all panicking uses over to the shiny new [`Single`](https://dev-docs.bevyengine.org/bevy/ecs/prelude/struct.Single.html) system param.

In rare cases, swapping to `Query::get_single` or even `Option<Single<&Component>>` might be preferred, to allow for more detailed error handling or to ensure the system runs to do secondary work even if the single entity it's looking for isn't found.

## What alternative(s) have you considered?

We could remove these methods entirely, per #14275. This is a much larger and more controversial change. Even if this is chosen, this migration needs to be done anyways, so we might as well do it now.

## Additional context

The nascent `bevy_cli` project introduced a lint to check for this class of error: https://github.com/TheBevyFlock/bevy_cli/pull/95. At some point, we'll want to run that Bevy-specific linter in CI for this project, but it's not ready yet.

**Comment by BD103** [comment]
I opened https://github.com/TheBevyFlock/bevy_cli/issues/136, would would make the `bevy::panicking_query_methods` lint suggest `Single` when `query.single()` and related are used. I'm not sure whether the Bevy Linter should support unstable APIs before they are released, but it's certainly something to look into.

**Comment by MiniaczQ** [comment]
> About this issue, is there a plan for migrate QueryState::single methods? Or only Query::single methods?

*from @pablo-lua in https://discord.com/channels/691052431525675048/749335865876021248/1294672821687025707*

> Both

*from @alice-i-cecile*
