### ISSUE TITLE
Hovering entity in game

### ISSUE THREAD

**Issue by itsmeagainlamo** [bevyengine/bevy#15876]
## New way checking entity is hovered
Today we don't have any good way to check if the entity is hovered in the game. Although it is possible to use AABB for each one for example sprite that would be **exhausting** and **not useful for other purposes**  for example sprite that has a lot of alpha pixel

## What solution would you like for users?
I think the engine should have a friendly function that can query the hovered object in the engine like `Query<(..values), With<HoveredObject>>`.  

## How it should be implemented

1. At the back would iter for each entity that is render 
2. Checking if the mouse is hovering over an entity  
3. Checking if the alpha value of an entity at a specific point is less than x 

## Another alternative for implmenting at back 
There is another option for detecting, where there is a big transparent area by using some AABB to mark that area. It won't be a good sprite that has a complex image

**Comment by alice-i-cecile** [comment]
This is largely implemented in Bevy 0.15, as part of the new `bevy_picking` crate. `HoverMap` is the key type :) I'm going to close this out as completed, but feel free to open up new issues for problems you encounter.
