### ISSUE TITLE
Conditional extraction to render world can cause desync

### ISSUE THREAD

**Issue by akimakinai** [bevyengine/bevy#15871]
In retained render world, despawning the main world entity or removing its components (#15582) are the only way to remove already inserted components from render world.
Some extraction systems seem to rely on the previous behavior by extracting components conditionally, expecting render entities to be wiped out every frame.

- [x] Bloom
#15856
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_core_pipeline/src/bloom/settings.rs#L222-L229
Turning HDR off causes crash because `Bloom` component is not removed.

- [x] ChromaticAberration
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_core_pipeline/src/post_process/mod.rs#L499
Setting `intensity = 0` will not be synchronized to render world if you have non-zero value currently, for example.

- [x] ContrastAdaptiveSharpening
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs#L88

- [ ] extract_depth_of_field_settings
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_core_pipeline/src/dof/mod.rs#L825

- [ ] extract_taa_settings
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_core_pipeline/src/taa/mod.rs#L376

- ~~extract_camera_prepass_phase~~
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_core_pipeline/src/core_3d/mod.rs#L589

- [ ] extract_clusters
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_pbr/src/cluster/mod.rs#L533

- [ ] extract_camera_previous_view_data
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_pbr/src/prepass/mod.rs#L587

- [ ] extract_lights
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_pbr/src/render/light.rs#L381

- [ ] extract_ssao_settings
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_pbr/src/ssao/mod.rs#L538

- [ ] extract_volumetric_fog
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_pbr/src/volumetric_fog/render.rs#L278

- [x] extract_visible_components
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_render/src/extract_component.rs#L222

- [ ] extract_cameras
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_render/src/camera/camera.rs#L1056
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_render/src/camera/camera.rs#L1073-L1075

- [ ] extract_default_ui_camera_view
https://github.com/bevyengine/bevy/blob/813c75958df8a518353c6b50cb62a27353bbfd51/crates/bevy_ui/src/render/mod.rs#L521

Most of them looks like optimization. Unfortunate but won't cause visual desync probably.

**Comment by rafalh** [comment]
Related to #15822
