### ISSUE TITLE
`specialized_mesh_pipeline` example has wrong colors half the time

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#15892]
## Bevy version

main

This is difficult to bisect. But here's how this example's behavior has evolved since it was added.

commit bfcb19a871559d988f4452cd9c60898ef186bdda
Date:   Wed Jul 31 14:24:58 2024 -0400
example added, works fine

commit 54006b107b921c7339df4e87a407b348effc4009
Date:   Wed Oct 2 00:33:17 2024 +0300
example now renders nothing 100% of the time

commit 3da0ef048ecaddfad2b8441918a5a8842098b5a9
Date:   Wed Oct 9 21:10:01 2024 +0000
example working again, but wrong colors half the time

## Relevant system information

SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }

## What you did

- `cargo run --example specialized_mesh_pipeline`
- run several times

## What went wrong

Colors are different / darker on some runs.

![Image](https://github.com/user-attachments/assets/e9e3d43b-6d51-45f4-851d-1bef10d557e3)

## Additional information

Note: the example currently panics when you hover over the mesh.

This is a separate issue tracked here: #15891

**Comment by alice-i-cecile** [comment]
I bet there's a system order ambiguity here. There's still a ton in the rendering code: I didn't have the time and expertise to resolve them so the checks are off for the render subapp.

**Comment by baldraven** [comment]
Seems like https://github.com/bevyengine/bevy/pull/15930 fixed the issue.

**Comment by rparrett** [comment]
> Seems like https://github.com/bevyengine/bevy/pull/15930 fixed the issue.

I am seeing the same thing on my end -- bad before that commit, good after.
