### ISSUE TITLE
Newly opened app shows a flash of the window with default settings

### ISSUE THREAD

**Issue by jakerr** [bevyengine/bevy#159]
On application start, when a new window is created with `bevy_winit`, it shows a window of default size for a brief moment and then updates to the requested settings in a flash.

I have a fix for this locally. Will send a PR.

**Comment by GabLotus** [comment]
Hey @jakerr we're really grateful for your involvment!

**Comment by jakerr** [comment]
> Hey @jakerr we're really grateful for your involvment!

Thank you for the warm welcome. I'm happy to pitch in. This is an awesome project!
