### ISSUE TITLE
Reading malformed DDS file is a panic instead of an error result

### ISSUE THREAD

**Issue by zbx1425** [bevyengine/bevy#15928]
## Bevy version

0.13.1

## What you did

Loading a DDS file for rendering that happens to be malformed.

## What went wrong

![Image](https://github.com/user-attachments/assets/712e804f-87b8-476b-896d-7ff6a58f7355)

https://github.com/bevyengine/bevy/blob/de08fb2afa5e8da1d910ed6be424649b6fbe9f0e/crates/bevy_image/src/dds.rs#L19

As use cases might involve loading DDS files specified by the user, this behavior makes it hard to properly handle an incorrect input from the caller's side. 
Or if I'm not using this the correct way?

**Comment by BenjaminBrienen** [comment]
I'll put this on my to-do.
