### ISSUE TITLE
Directional lights and spot lights do not have shadow on WebGL on chromium. Shader compilation failed on Firefox.

### ISSUE THREAD

**Issue by newDINO** [bevyengine/bevy#15944]
## Bevy version
0.14.2 and the version used for demos on bevyengine.org

## \[Optional\] Relevant system information
cargo 1.81.0 (2dbb1af80 2024-08-20)
Arch Linux rolling, Linux 6.11.3-arch1-1
Chromium Version 129.0.6668.100 (Official Build) Arch Linux (64-bit)
Firefox 131.0.2 (64-bit)

```ignore
` AdapterInfo { name: "ANGLE (AMD, AMD Radeon RX 480 Graphics (radeonsi polaris10 LLVM 18.1.8), OpenGL 4.6)", vendor: 4098, device: 0, device_type: Other, driver: "WebGL 2.0 (OpenGL ES", driver_info: "3.0 Chromium)", backend: Gl }`
```

## What you did

1. Running a program containing directional light with shadow enabled in both native and web platform.
2. Running the demo at https://bevyengine.org/examples/3d-rendering/spotlight/.
3. Running other demos with only point lights.

## What went wrong

1. Native build shows clear shadow, while wasm doesn't.
2. When running on chromium, it doesn't show the shadow as the cover of the demo shows. When running on firefox, the shader translation failed(Seems to be a wgpu issue).
3. Point light shadows are normal.

## Additional information
![Image](https://github.com/user-attachments/assets/37537db0-373f-4563-a8eb-e1361b3a6e39)
![Image](https://github.com/user-attachments/assets/85c787e1-6dd4-4a95-aa66-21633c426a7a)

**Comment by mockersf** [comment]
Firefox is generally broken, the fix will come in Firefox 132: https://github.com/bevyengine/bevy/issues/14415

**Comment by BenjaminBrienen** [comment]
It just hangs for me.
![Image](https://github.com/user-attachments/assets/d4d7c966-0529-454a-92d9-40ffe59dc76a)

**Comment by newDINO** [comment]
> > Native build shows clear shadow, while wasm doesn't.
> 
> On webgl, IIUC at most 1 directional-or-spot light can be shadow-mapped actually. I think this matches your screenshot where there's slight shadows in top-left. [WebGPU version](https://bevyengine.org/examples-webgpu/3d-rendering/spotlight/) should render missing shadows.
> 
> [bevy/crates/bevy_pbr/src/render/light.rs](https://github.com/bevyengine/bevy/blob/9930df83ed42008f7eb2c02cc7350040f0250c2e/crates/bevy_pbr/src/render/light.rs#L722-L723)
> 
> Lines 722 to 723 in [9930df8](/bevyengine/bevy/commit/9930df83ed42008f7eb2c02cc7350040f0250c2e)
> 
>  #[cfg(all(feature = "webgl", target_arch = "wasm32", not(feature = "webgpu")))] 
>  let max_texture_array_layers = 1; 
> [bevy/crates/bevy_pbr/src/render/light.rs](https://github.com/bevyengine/bevy/blob/9930df83ed42008f7eb2c02cc7350040f0250c2e/crates/bevy_pbr/src/render/light.rs#L793-L797)
> 
> Lines 793 to 797 in [9930df8](/bevyengine/bevy/commit/9930df83ed42008f7eb2c02cc7350040f0250c2e)
> 
>  let spot_light_shadow_maps_count = point_lights 
>      .iter() 
>      .filter(|(_, light, _)| light.shadows_enabled && light.spot_light_angles.is_some()) 
>      .count() 
>      .min(max_texture_array_layers - directional_shadow_enabled_count * MAX_CASCADES_PER_LIGHT);

Indeed, and my first problem can be solved by increasing the maximum distance of CascadeShadowConfigBuilder.
thx.
