### ISSUE TITLE
Remove broken AVIF support from `bevy_image`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#15968]
> I feel like it'd be best as a third option, opt for an embedded AVIF implementation, but in the absence of that, removing it feels better.

I don't think this is an important enough feature for that. I'd prefer to remove it and let third-party solutions cover this.

_Originally posted by @alice-i-cecile in https://github.com/bevyengine/bevy/issues/15959#issuecomment-2418310800_

**Comment by clarfonthey** [comment]
If @brianreavis is okay with it I can take this on myself later today.
