### ISSUE TITLE
Incoherent behaviour possible with `ConvexPolygon`

### ISSUE THREAD

**Issue by lynn-lumen** [bevyengine/bevy#15963]
## Bevy version

main ([7495d68](https://github.com/bevyengine/bevy/commit/7495d68b415149ec845b1c4fc1faaf7ab1397e16))

## What you did

Create a `ConvexPolygon`. Modify any of the vertices so the polygon is no longer convex. 

This should not be possible since it violates the invariants of the type and leads to incorrect meshing.

## What you expected

I expected either `vertices` to not be exposed or the type to document that incoherent behaviour is possible.

## Example

```rust
let mut poly = ConvexPolygon::new([Vec2::ZERO, Vec2::X, Vec2::ONE, Vec2::Y]).unwrap();
poly.vertices[0] = Vec2::new(0.75, 0.75);
```

**Comment by alice-i-cecile** [comment]
I would prefer to expose only read-only access, and then have a way to turn it back into a non-convex polygon.
