### ISSUE TITLE
`pbr` example 3d camera doesn't render anything

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#15976]
## Bevy version

main
bisected to #15969

## Relevant system information

SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
(scale factor 2.0)

## What you did

`cargo run --example pbr`

## What went wrong

A bunch of spheres of varying roughness/metallicness should be visible, but no sphere are visible.

## Additional info

https://pixel-eagle.com/project/b25a040a-a980-4602-b90c-d480ab84076d/run/5268/compare/5259?screenshot=3D%20Rendering/pbr.png

**Comment by alice-i-cecile** [comment]
Can you check the other examples that I modified? I initially didn't understand that you need to invert it

**Comment by rparrett** [comment]
It seems that the direction you scroll to zoom in has been reversed in `projection_zoom` as well.

**Comment by alice-i-cecile** [comment]
@rparrett reversing the scroll direction was deliberate in this case :) Scroll up to zoom in is the universal convention.

**Comment by aevyrie** [comment]
> [@rparrett](https://github.com/rparrett) reversing the scroll direction was deliberate in this case :) Scroll up to zoom in is the universal convention.

@alice-i-cecile this is definitely not universal. Scroll down is often used to zoom, like you are pulling the objects toward you. Similar how with dragging to pan, you are dragging the object, not the camera.
