### ISSUE TITLE
Controls in `ssao` example have no effect

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#15997]
## Bevy version

main
bisected to #15320

## Relevant system information

SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }

Also

SystemInfo { os: "Windows 11 Home", kernel: "22631", cpu: "13th Gen Intel(R) Core(TM) i7-13700KF", core_count: "16", memory: "31.8 GiB" }
AdapterInfo { name: "NVIDIA GeForce RTX 4080 SUPER", vendor: 4318, device: 9986, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "560.94", backend: Vulkan }

## What you did

- `cargo run --example ssao`
- press `1` and `5` to toggle SSAO off and on.

## What went wrong

No visual evidence of anything happening.

Prior to #15320, there were obvious visual changes.

**Comment by floppyhammer** [comment]
SystemInfo { os: "Windows 11 Enterprise", kernel: "27729", cpu: "AMD Ryzen 5 5600X 6-Core Processor", core_count: "6", memory: "15.9 GiB" }

AdapterInfo { name: "AMD Radeon RX 6500 XT", vendor: 4098, device: 29759, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "24.10.27.01 (AMD proprietary shader compiler)", backend: Vulkan }

The controls work for me.

**Comment by rparrett** [comment]
Looks like this was fixed by #15948 the day after I opened this. Yay.
