### ISSUE TITLE
Adding utility functions like degrees to radians and the opposite to bevy_math

### ISSUE THREAD

**Issue by TheLeonsver1** [bevyengine/bevy#1600]
## What problem does this solve or what need does it fill?
there are no utility functions that give the radians required for Quat's functions, and angles are perhaps easier for people to think in, so converting from them would be helpful

## What solution would you like?
add these 2 functions and perhaps ask if anyone missed any other functions in bevy_math on discord

## What alternative(s) have you considered?
I don't think there are any... except maybe asking glam to add those..?

**Comment by cart** [comment]
Rust already has these as built in functions for floats: https://doc.rust-lang.org/std/primitive.f64.html#method.to_degrees. That feels suitable?

**Comment by TheLeonsver1** [comment]
oh nevermind, that exists for f32 too, sorry, so probably just let people easily know that exists in rust?

**Comment by alice-i-cecile** [comment]
> oh nevermind, that exists for f32 too, sorry, so probably just let people easily know that exists in rust?

Yep: this might be a good bevy-cheatbook issue, or something that could be addressed by tutorials.
