### ISSUE TITLE
cosmic_text Query re-export degrades autocomplete UX

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#16006]
>  When typing Query, RA autocomplete suggests text::cosmic_text::fontdb::Query

Reported by @JMS55 [here](https://discord.com/channels/691052431525675048/692572690833473578/1297054382084456489).

I think we should change how we're re-exporting (probably alias the offending `Query`) to avoid this problem.

**Comment by nicoburns** [comment]
I propose that this is renamed to `FontQuery`

**Comment by VitalyAnkh** [comment]
I don't think this really hurt UX. After typing "Que", rust-analyzer's suggestion is as follows:
![Image](https://github.com/user-attachments/assets/dbec383f-8e2d-463a-8d5a-ace229cd13b3).
The `Query` we usually want is at the first suggestion and `text::cosmic_text::fontdb::Query` is at the fourth.

After typing "Query":
![Image](https://github.com/user-attachments/assets/5234fd82-726e-4ab1-afce-b07ab4eac9e7)
The `Query` we usually want is still at the first and `text::cosmic_text::fontdb::Query` is at the second.

**Comment by cart** [comment]
This does currently violate our "global namespace" principle. Aliasing feels like a reasonable path. But I think the `cosmic_text` re-export is unnecessary. It seems to exist to allow `bevy_ui` to pass the CosmicFontSystem resource into our various text computation apis. However why force the cosmic_text dependency in our "wrapper apis" when we can just pass in CosmicFontSystem directly instead? That would allow us to remove the reexport entirely.

Putting that changeset together now.
