### ISSUE TITLE
Resource requested does not exist

### ISSUE THREAD

**Issue by ivnsch** [bevyengine/bevy#16033]
## Bevy version

0.14.2

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
1.82.0

- Relevant system information
Mac m1, macOS 14.6.1

## What you did

Building WASM with (see instructions in readme):
(note that for the https://github.com/bevyengine/bevy/issues/16030 workaround to work, it has to be built in release mode)
https://github.com/ivnsch/mol/tree/wasm_debug_re_enable_ui

Use it in a next app:
https://github.com/ivnsch/mol_next_app_tmp
(start with `npm run dev`, navigate to http://locahost:3000)

## What went wrong
Error:
> Resource requested by mol::linear_alkane::run_if_carbon_count_changed does not exist: bevy_ecs::event::Events<mol::ui::UiInputsEvent>

This relates to [this struct](https://github.com/ivnsch/mol/blob/wasm_debug_re_enable_ui/src/ui.rs#L10-L15)
```rust
#[wasm_bindgen]
#[derive(Event, Default, Debug)]
pub struct UiInputsEvent {
    pub carbon_count: u32,
    pub carbon_count_changed: bool,
}
```
Adding the `wasm_bindgen` macro was just a wild guess, the same error occurs without or with the macro. The only way I could get rid of this is by removing the struct entirely (and probably other similar ones - I removed all the UI code).

**Comment by alice-i-cecile** [comment]
This doesn't seem like a Bevy bug. You probably forgot to call `.add_event` on your `UiInputsEvent`.

**Comment by ivnsch** [comment]
@alice-i-cecile I forgot to mention that it works on desktop (`cargo run`, no changes).

**Comment by alice-i-cecile** [comment]
Can you try to make a minimal reproduction for us?

**Comment by ivnsch** [comment]
Ah, you were right. I was adding `UiInputsEvent` but had commented another place calling that.. and I've a bunch of warnings due to the wasm export so missed that. Thank you.
