### ISSUE TITLE
Commands queued by component hooks are not applied during exclusive world access

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#16034]
# Problem

When an entity is spawned (or other structural changes occur) as part of exclusive world access, commands to apply changes via hooks are generated, but are not immediately applied.

In order to apply these commands, we must call `world.flush`, as demonstrated [here](https://github.com/Leafwing-Studios/i-cant-believe-its-not-bsn/blob/8e5783dd164f99960f6c33cc3f83b99174c84ce2/src/maybe.rs#L150).

This allows users to accidentally observe the state of the world *before* component lifecycle hooks are applied, but *only* when working with exclusive world access. As a result, we must be extremely careful if we are relying on hooks for soundness.

## Bevy version

0.14.1

## Additional context

This is related to #14621, but is intended as a clearer demonstration of a specific problem.

#12235 may end up being blocked on this, as otherwise we could get UB by calling unsafe code on an invalid entity hierarchy.

**Comment by alice-i-cecile** [comment]
Of course, it's not clear that this is fully undesirable behavior! Better control over when hooks are applied in the context of exclusive world access exposes more power for users, particularly around performance optimizations (e.g. #10154).

We could decide that this is intended behavior, and simply clearly document it. Relying on fully valid hierarchies for soundness is *very* challenging already (see #15575), we should consider making this code robust or marking the system itself as unsafe.

**Comment by alice-i-cecile** [comment]
>  I would have preferred to always apply them, but it's very difficult to make work with EntityWorldMut since you can't risk despawning the entity so you have to run them after dropping it. The problem is you can't implement drop for EntityWorldMut without UX regressions due to it borrowing &mut World until end of scope

From @james-j-obrien [on Discord](https://discord.com/channels/691052431525675048/749335865876021248/1297614494557536476).

**Comment by urben1680** [comment]
This sounds like the chicken-or-egg problem. These commands that are desired to be applied here may also trigger hooks and observers, right?

Generally, if I am not mistaken, sync points are

1. Commands
2. Hooks
3. Observers

And after that there may be queued commands.

Possible one wants to take these three steps in a loop that keeps going as long it produces commands.
