### ISSUE TITLE
Skip systems that require a non-existing resource instead of panicking.

### ISSUE THREAD

**Issue by Victov** [bevyengine/bevy#1604]
## What problem does this solve or what need does it fill?
Right now (release 0.4.0), when a system is registered that requires are resource. and that resource is not yet inserted, then you get a panic. I propose that the scheduler would simply skip systems whose resource needs are unfulfilled instead of panicking.
This would make it easy to keep systems registered, even though they might occasionally not be useful. For example: 

I have a permanently registered network polling system, which requires a Socket resource.
In the main menu the user must select Join or Host, and after this choice a Socket is added as resource.

## What solution would you like?

Let the scheduler skip systems whose resource needs are not met.

## What alternative(s) have you considered?

Only run the required systems in specific app states where you know that the resource will be available. However, this is not ideal, since the app states are app-specific, which would disallow me to bundle my networking logic in a separate module or crate and make a bevy Plugin out of it.

## Additional context

I was expecting this behaviour since I wanted to make something similar to amethyst_networking for bevy. In amethyst_networking you simple include a NetworkBundle which registers all sorts of polling systems for you. They automatically kick into action when you insert the resource for the socket manually.

I saw that in 0.5 a rewrite of the resources is coming, so excuse me if this issue is already solved for 0.5! 
Really enjoying Bevy so far. Thanks a lot :)

**Comment by jakobhellermann** [comment]
Since https://github.com/bevyengine/bevy/pull/1494 you can write 
```rust
fn system(resource: Option<Res<Resource>>) {
  let resource = match resource {
    Some(res) => res,
    None => return,
  };

  // continue
}
```

which solves your problem without silently failing in case you forget to insert a resource.

**Comment by Victov** [comment]
Ah that's great! Thanks. 

Just out of curiosity, how could I have known this? I believe I checked the examples and learning material quite thoroughly, so I'm surprised now that this feature exists.

**Comment by alice-i-cecile** [comment]
@Victov the PR was merged 18 hours ago, so it's very understandable that you didn't see this. It does need better documentation though.

In the meantime, the Discord is very active and has a ton of informal development activity and help. Issues like this are very helpful, but you can also try asking on Discord and we can point you to solutions and ongoing development work :)
