### ISSUE TITLE
Add the description on how to run bevy examples from user's project

### ISSUE THREAD

**Issue by fhgaha** [bevyengine/bevy#16054]
After using bevy for several weeks I have found that I can run examples from my project with `cargo run --example <Example file name>`. Please add this to the top of [example page](https://bevyengine.org/examples/).

**Comment by rparrett** [comment]
This is the first step in our [quick start guide](https://bevyengine.org/learn/quick-start/getting-started/), and also gets a mention after following the first link on the [example pages](https://bevyengine.org/examples/).
> You can also view these examples (and others) in the [Bevy repo](https://github.com/bevyengine/bevy/tree/latest/examples#examples).

For running examples *in your own project*, it would be more common to 
- [Add `bevy` as a dependency](https://bevyengine.org/learn/quick-start/getting-started/#add-bevy-as-a-dependency) in a new rust project
- copy/paste example code into `src/main.rs`
- run with `cargo run`

**Comment by mockersf** [comment]
This is a feature from Rust, not from Bevy. As said above, how to use it with Bevy examples is already documented

**Comment by fhgaha** [comment]
Ah, indeed. My bad.
