### ISSUE TITLE
`TextureAtlas` is still a component

### ISSUE THREAD

**Issue by benfrankel** [bevyengine/bevy#16064]
## Bevy version

0.15.0-rc.1

## What you did

Migrated to bevy 0.15.0-rc.1, fixed errors until code compiled.

## What went wrong

The `TextureAtlas` component on a sprite entity was silently ignored, because `TextureAtlas` should now be a field of `Sprite` instead -- but `TextureAtlas` still impls `Component`. This is because `UiImage` still expects it as a component, which is inconsistent / confusing and should be fixed for 0.15.

**Comment by cart** [comment]
Picking this up now
