### ISSUE TITLE
Consider reverting #14387 "Deprecate is_playing_animation" for 0.15

### ISSUE THREAD

**Issue by mgi388** [bevyengine/bevy#16098]
https://github.com/bevyengine/bevy/pull/14387 deprecates `is_playing_animation`. 

But #15962 PR merged after that prefers the `is_` format following the std lib preferences (ref: https://github.com/bevyengine/bevy/issues/15834#issuecomment-2406102500). In that PR, the change was:

- `Stowatch::paused` -> `Stopwatch::is_paused`

So it seems like `is_playing_animation` should be undeprecated.

**Comment by cart** [comment]
I agree. `is_playing_animation` is more idiomatic.
