### ISSUE TITLE
Rendering after switching to a 2nd camera is broken.

### ISSUE THREAD

**Issue by Elabajaba** [bevyengine/bevy#16106]
## Bevy version

Since retained render world.

## What you did

Run scene viewer with this scene [test1.zip](https://github.com/user-attachments/files/17528043/test1.zip) (`cargo run --example scene_viewer -- assets/test1.glb`). Toggle shadows on (press `u`), then change cameras (`c`) and move the viewport around.

edit: Toggling shadows isn't necessary, but it makes it more obvious when the meshes are rendering in the wrong positions (because the shadows are correct).

## What went wrong

Meshes are rendering in the wrong places.

## Additional information

Log is being spammed with `WARN bevy_pbr::render::gpu_preprocess: The preprocessing index buffer wasn't present`

![Image](https://github.com/user-attachments/assets/11872b6a-9393-4cc4-8bde-dda9fe29343c)

![Image](https://github.com/user-attachments/assets/b6458997-c364-4e61-9829-c6ea2abd04bc)

**Comment by BenjaminBrienen** [comment]
A bisect would help here

**Comment by Elabajaba** [comment]
> A bisect would help here

As noted in the OP, it broke with retained render world (56f8e526dde49b4e4ad62efb7ad27bfe0bd6f617). Technically it just straight up crashed with a panic until fe7f98f7f07403accb34b7912e16bb99bb831339, then it started rendering wrong. Pre-retained render world it worked properly.

**Comment by Elabajaba** [comment]
Just re-tested this and it appears to have been fixed by https://github.com/bevyengine/bevy/pull/16188.

**Comment by alice-i-cecile** [comment]
That's a relief. Thanks for testing.
