### ISSUE TITLE
Hope to get some advise for develop game

### ISSUE THREAD

**Issue by fengqi2019** [bevyengine/bevy#1610]
Hi,our team want to redevelop game《Command & Conquer: Red Alert 2》with bevy.but we are all beginner in game development, so we specially hope to get some advise from you. e.g which plugin for rendering (Tiled) maps we should better use and so on.thank you very much!

there ara some information and video  about 《Command & Conquer: Red Alert 2》: 

[wiki](https://en.wikipedia.org/wiki/Command_%26_Conquer:_Red_Alert_2)
[video](https://www.youtube.com/watch?v=zTNPsHLqxPI)

**Comment by Byteron** [comment]
Github issues are more for the development of bevy itself.
If you are looking for help on projects, feel free to join the bevy discord server: https://discord.gg/Z7frCWzwP7
There are many helpful people online who can help you get started with bevy. :)

**Comment by fengqi2019** [comment]
Ok,thanks.
