### ISSUE TITLE
Content missing from `font_atlas_debug`, `overflow_debug`, and `game_menu` examples

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#16136]
## Bevy version

main, bisected to #16083

## Relevant system information

SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }

## What you did

`cargo run --example font_atlas_debug`
`cargo run --example overflow_debug`
`cargo run --example game_menu`

## What went wrong

Upper text is missing in both text examples.

Icons are missing from buttons in `game_menu` example.

## Additional information

pixel-eagle links

[overflow_debug.png](
https://pixel-eagle.com/project/b25a040a-a980-4602-b90c-d480ab84076d/run/5331/compare/5322?screenshot=UI%20(User%20Interface)/overflow_debug.png)
[font_atlas_debug.png](https://pixel-eagle.com/project/b25a040a-a980-4602-b90c-d480ab84076d/run/5331/compare/5322?screenshot=UI%20(User%20Interface)/font_atlas_debug.png)
[game_menu.png](https://pixel-eagle.com/project/b25a040a-a980-4602-b90c-d480ab84076d/run/5331/compare/5322?screenshot=Games/game_menu.png)

**Comment by ickshonpe** [comment]
Should be fixed by #16138
