### ISSUE TITLE
error: linking with rust-lld failed: exit code: 1

### ISSUE THREAD

**Issue by fhgaha** [bevyengine/bevy#16140]
Bevy version 0.14.2

rustc 1.80.1 (3f5fd8dd4 2024-08-06)

Windows 10

It started to appear after adding `if verts.len() == 96 && tri_indices.len() == 336 {...}`.
`cargo check` passes, `cargo build` and `cargo run` causes the error.
Here is my project https://github.com/fhgaha/water_slides and here is the commit `e5bd063373bb227446015d7cb87d1cc9f8160361` in branch `mesh-gen-tube` with the error if interested. Also I am noob and have no idea what am I doing.
And here is error output https://pastebin.com/vqwtx4Ld

**Comment by alice-i-cecile** [comment]
Can you make sure dynamic linking is off? And try `cargo clean`.

**Comment by fhgaha** [comment]
> Can you make sure dynamic linking is off? And try `cargo clean`.

I turned off dynamic linking and it works now. I haven't run `cargo clean`.
