### ISSUE TITLE
If an asset fails to load, emit an event like AssetLoadError Event

### ISSUE THREAD

**Issue by ethereumdegen** [bevyengine/bevy#16149]
## What problem does this solve or what need does it fill?

I am loading a ton of RON files and I want to show on the UI if one fails and why it fails .  I have to scroll through a horrid amount of useless console logs (another story...) to figure out what is wrong with my assets and its a bad  bad  experience for me. 

## What solution would you like?
If this error is printed to the console log (for example) 

```
2024-10-29T01:16:05.497121Z ERROR bevy_asset::server: Failed to load folder. Failed to load asset 'item_system_types/vendor_tables/basic.vendor.ron' with asset loader 'bevy_common_assets::ron::RonAssetLoader<broken_spirit::file_system_interaction::vendor_table::VendorTable>': Could not parse RON: 7:81: Expected integer

```
Then an event should be emitted like 'AssetLoadErrorEvent' with the handle of the asset and the error message string like ' Could not parse RON: 7:81: Expected integer ' so i can display it on the UI programmatically. 

## What alternative(s) have you considered?

I considered implementing something like this 

 https://bevy-cheatbook.github.io/assets/ready.html 

But it is absolutely horrid that i have to manually register all asset handles and that is impossible because i am using bevy_asset_loader which kind of hides all of that from me .  I cant register the asset handles... nor do i want to loop through them like that every frame .

**Comment by ethereumdegen** [comment]
OKAY ! I tried doing this and it is suuuuper close 

```

fn update_asset_loading_failure_resource(
 
        mut asset_load_error_events: EventReader< InternalAssetEvent >,

     ) {

    
    for evt in asset_load_error_events.read(){


        match evt {


            InternalAssetEvent::Failed { id, error, path } => {

                panic!( error );

            } 
            _ => {}
        }

    }




}

```

but for some absolutely silly reason, the id, error, and path are marked private so i cant access them... i should be able to imo !

**Comment by BenjaminBrienen** [comment]
Feel free to create a PR!

**Comment by ethereumdegen** [comment]
Okay i found this and it is getting closer but still no dice 

```
fn update_asset_loading_failure_resource(
 
      //  mut asset_load_error_events: EventReader< InternalAssetEvent >,
        mut asset_load_error_events: EventReader< UntypedAssetLoadFailedEvent >,

     ) {

    
    for evt in asset_load_error_events.read(){


        match evt {
 

             UntypedAssetLoadFailedEvent ::Failed { 
               id, path ,error 
                //PR open to make these available ! 
            } => {

                panic!( "asset loading failed " );

            } 
            _ => {}
        }

    }




}

```



ERROR 


```
error[E0223]: ambiguous associated type
   --> src/file_system_interaction/asset_loading.rs:643:14
    |
643 |              UntypedAssetLoadFailedEvent ::Failed { 
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: if there were a trait named `Example` with associated type `Failed` implemented for `UntypedAssetLoadFailedEvent`, you could use the fully-qualified path
    |
643 |              <UntypedAssetLoadFailedEvent as Example>::Failed { 


```

**Comment by ethereumdegen** [comment]
WAIT i think i got it 

```
fn update_asset_loading_failure_resource(
  
        mut asset_load_error_events: EventReader< UntypedAssetLoadFailedEvent >,

     ) {

    
    for evt in asset_load_error_events.read(){

        let id = &evt.id ;
        let path = &evt.path; 
        let error = &evt.error; 
               

       panic!( "asset loading failed {}" , error );
 

    } 


}

```

**Comment by ethereumdegen** [comment]
Yep this is how you do it.  Someone should put in docs ;D
