### ISSUE TITLE
Consider removing headless plugins

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#16152]
I'm not sure this is a good idea to have in Bevy. "Headless" meaning will change depending on the use case, and controlling it with a plugin rather than features means longer compile time and a lot of code that can't be used, events not registered, component not reflected, but still available when developing which will mean a less good developer experience.

_Originally posted by @mockersf in https://github.com/bevyengine/bevy/issues/15260#issuecomment-2443551735_

**Comment by alice-i-cecile** [comment]
I'm sympathetic to this perspective, but I'm really unhappy about how complex it is for users to solve a common request: "please just run my app headless for a server or CI" state. Without this type, controlling this with plugin disabling and/or feature flags currently requires pretty arcane knowledge of the every plugin and feature flag in Bevy.

**Comment by alice-i-cecile** [comment]
Sounds great: I'll tackle this.

**Comment by heydocode** [comment]
Excellent issue, I'm not using headless plugins but it will be great if the compile-time of CI/server side projects will compile faster and will have less bloat in the final binaries (that also concerns games with visuals, please track your dependencies & its features, guys). In the current state of rust, its linker cannot predict with absolute precision which dependencies won't be used at runtime, so I think only 85% of the final binary will contain the code you really need if you import too heavy dependencies without setting the only features you need.
