### ISSUE TITLE
Sprite pivot (offset)

### ISSUE THREAD

**Issue by DarkMara** [bevyengine/bevy#1616]
## What problem does this solve or what need does it fill?
It allows each sprite to be drawn at a different offset on the texture. For example, on a character sprite sheet, the pivot is often put at the character's feet, so that they always appear in the same place even if the sprites are different sizes or the pixels do not line up exactly.

## What solution would you like?

There should be a `Vec2` on both `Sprite` and `TextureAtlasSprite` that determines the offset the sprite should be drawn at. It could be called pivot or offset. 

## What alternative(s) have you considered?
The alternative is to offset the transform every time you change the sprite. It's tedious.

## Additional context

Unity includes [an enum](https://docs.unity3d.com/ScriptReference/SpriteAlignment.html) that lets you to automatically put the pivot at certain parts of the sprite, like TopLeft or Center. I'm not sure if that should be on the sprite or should just be handled in the editor.

**Comment by mockersf** [comment]
This could be solved by using a hierarchy of entity:
- children would specify translation so that the sprite is displayed in the offset you want of its parent
- parent would specify rotation

Would that work for you?

**Comment by DarkMara** [comment]
That doesn't solve the issue. Each sprite could have a different pivot, so as I said, you'd have to change the child's transform every time the sprite changes. That's what I'm doing currently as a workaround, but it's not a good solution. This feature is present in both Godot and Unity, and it should be in Bevy also.

**Comment by DarkMara** [comment]
I attempted to implement this myself, but I didn't know how to apply the offset to the `SpriteTransform` matrix in the shader.

**Comment by ManevilleF** [comment]
+1

Since we can generate sprites programatically it would be nice to specify a pivot.
Using hierarchy as an anchor works but it adds complexity both in code and the runtime, moving/rotating a single sprite with a custom pivot would be faster than moving/rotating a parent object

**Comment by drakmaniso** [comment]
An easily configurable offset would also be really useful for pixel-art sprites. With the current centered behavior, odd-sized textures requires an offset of 0.5 to be aligned on screen pixels.
