### ISSUE TITLE
Rename `PointerInput::button_just_down` and `just_up` methods

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#16178]
> should these be called `pressed` and `released` instead of `down` and `up` to match the methods on `ButtonInput`? https://dev-docs.bevyengine.org/bevy/input/struct.ButtonInput.html#method.just_pressed

_Originally posted by @hymm in https://github.com/bevyengine/bevy/issues/16176#issuecomment-2448285515_

**Comment by skimmedsquare** [comment]
What work is pending here?

`PointerInput::button_just_down` / `just_up` don't seem to exist as of 9a0c9b9e8f0408add03c1527a71612ebef34c329, is the requested change the following comment? (https://github.com/bevyengine/bevy/pull/16176#issuecomment-2448327505)

> Can we rename PointerAction::Pressed to PointerAction::Button?

**Comment by alice-i-cecile** [comment]
I think this is resolved; I just forgot to update the issue status.
