### ISSUE TITLE
Shadows in 3D scene are flickering

### ISSUE THREAD

**Issue by lonegamedev** [bevyengine/bevy#16185]
## Bevy version

0.14.2

## \[Optional\] Relevant system information

Arch Linux

AdapterInfo { name: "AMD Radeon RX 7900 XTX", vendor: 4098, device: 29772, device_type: DiscreteGpu, driver: "AMD open-source driver", driver_info: "2024.Q3.3 (LLPC)", backend: Vulkan }

## What you did

Just run plain 3D scene example.

## What went wrong

Shadows are flickering.

## Additional information

![Image](https://github.com/user-attachments/assets/df84a0ea-1c19-46c1-b7b9-95020029a1c1)

**Comment by jpteb** [comment]
I experience the same issue under NixOS and `bevy v0.15.0-dev`.

```
SystemInfo { os: "Linux 24.11 NixOS", kernel: "6.11.5", cpu: "AMD Ryzen 7 5800X 8-Core Processor", core_count: "8", memory: "31.3 GiB" }
AdapterInfo { name: "AMD Radeon RX 7800 XT", vendor: 4098, device: 29822, device_type: DiscreteGpu, driver: "AMD open-source driver", driver_info: "2024.Q3.2 (LLPC)", backend: Vulkan }
```

**Comment by paholg** [comment]
I am also seeing this after updating from Bevy 0.13 to 0.14. I am also on NixOS.

Using `git bisect` in the bevy repo and repeatedly running `cargo run --example 3d_shapes`, I have found that this commit introduced the flicker: f4dab8a.

Strangely, that commit is included in the 0.13.0 release, yet in my project the shadows don't flicker until the 0.14 update. If desired, you can test it: https://github.com/paholg/gam/tree/216cd246c8c8984cf913b5ffb30c67a269e09571, run with `cargo run --bin client`.

Finally, if I compile my project for windows and run it with wine, the shadows do not flicker. However, if I take a version compiled on Ubuntu and run it with steam-run, there is flickering.

I would be happy to investigate further, but I am afraid that I am miles out of my league when it comes to anything related to rendering.

```
AdapterInfo { name: "AMD Radeon RX 7900 XTX", vendor: 4098, device: 29772, device_type: DiscreteGpu, driver: "AMD open-source driver", driver_info: "2024.Q3.3 (LLPC)", backend: Vulkan }
```

**Comment by jpteb** [comment]
I have tested this again, and I'm quite sure this is an `amdvlk` bug. With the `radv` driver the shadows do not flicker.

**Comment by paholg** [comment]
I can confirm there is no flickering when I switch from `amdvlk` to `radv`.

```
AdapterInfo { name: "AMD Radeon RX 7900 XTX (RADV NAVI31)", vendor: 4098, device: 29772, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.2.5", backend: Vulkan }
```

**Comment by dmyyy** [comment]
For others - you can do this via
```
AMD_VULKAN_ICD=RADV cargo run
```

**Comment by lonegamedev** [comment]
Switching a driver to RADV fixes the problem. Thank you.

**Comment by Pybounce** [comment]
Any chance we can do for linux, what was done for windows here?
https://github.com/bevyengine/bevy/blob/release-0.14.2/crates/bevy_render/src/renderer/mod.rs#L393-L400
