### ISSUE TITLE
Consistently use pressed / released terminology in `bevy_picking`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#16192]
>> should these be called pressed and released instead of down and up to match the methods on ButtonInput? https://dev-docs.bevyengine.org/bevy/input/struct.ButtonInput.html#method.just_pressed

> If we're doing this, it should be a global concept rename (ex: `Pointer<Down>` and `Pointer<Up>` types, all of the methods)

_Originally posted by @cart in https://github.com/bevyengine/bevy/issues/16176#issuecomment-2448311264_

**Comment by cart** [comment]
Given that `just_pressed` is literally capturing the same concept as `Pointer<Down>`, it seems odd to me to use different terminology. Consistency here seems desirable.
