### ISSUE TITLE
AccessKit `Node` Re-export is Confusing with Bevy's `Node`

### ISSUE THREAD

**Issue by bushrat011899** [bevyengine/bevy#16235]
## Bevy version

`main`/0.15 RC

## Description

The `bevy_a11y` re-exports AccessKit's `Node`, but that can be confusing since `bevy_ui` _also_ defines a `Node`. Since #16234, there is now a way to use AccessKit without importing `accesskit::Node`. Now that it is optional, we should reconsider the way Bevy re-exports AccessKit. For example, only re-exporting `Role`.

## Context

This was raised by @alice-i-cecile in [this Discord message](https://discord.com/channels/691052431525675048/692572690833473578/1303095959529721896).

**Comment by alice-i-cecile** [comment]
I think we should not re-export at all here, and state in the docs that the versions must match.
