### ISSUE TITLE
Re-export `bevy_image::image::Volume`

### ISSUE THREAD

**Issue by chompaa** [bevyengine/bevy#16251]
## What problem does this solve or what need does it fill?

In Bevy `0.14.2`, `Volume` was available via `bevy::render::texture::Volume`. In `main`, it is no longer available. This appears to be a regression since e.g. `bevy_image::image::TextureFormatPixelInfo` is exported.

## What solution would you like?

Re-export `bevy_image::image::Volume`.

**Comment by BenjaminBrienen** [comment]
This conflicts with https://github.com/bevyengine/bevy/issues/15940

**Comment by cart** [comment]
Resolved by #16163
