### ISSUE TITLE
Switching active cameras causes warning log `The preprocessing index buffer wasn't present` to be spammed.

### ISSUE THREAD

**Issue by Elabajaba** [bevyengine/bevy#16285]
## Bevy version

cdc18ee886205ecf64964206caf0cc46e7506134 (started somewhere in the 0.15 dev cycle but don't have time to bisect currently)

## What you did

Change the active camera by settings `.is_active` to false on the current camera, and `.is_active` to true on the camera view I'm switching to.

## What went wrong

Log is being spammed with WARN bevy_pbr::render::gpu_preprocess: The preprocessing index buffer wasn't present

## Additional information

TODO

**Comment by atlv24** [comment]
bisected this and [not a surprising result](#15320):
```
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[56f8e526dde49b4e4ad62efb7ad27bfe0bd6f617] The Cooler 'Retain Rendering World' (#15320)
```

**Comment by atlv24** [comment]
furthermore, the message changed from
```
Camera order ambiguities detected for active cameras with the following priorities: {(0, Some(Window(NormalizedWindowRef(0v1#4294967296))))}. To fix this, ensure there is exactly one Camera entity spawned with a given order for a given RenderTarget. Ambiguities should be resolved because either (1) multiple active cameras were spawned accidentally, which will result in rendering multiple instances of the scene or (2) for cases where multiple active cameras is intentional, ambiguities could result in unpredictable render results.
```
to
```
The preprocessing index buffer wasn't present
```
after #15946
```
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[fe7f98f7f07403accb34b7912e16bb99bb831339] Fix deactivated camera still being used in render world (#15946)
```

**Comment by mockersf** [comment]
I can't reproduce on the example `render_primitives` which alternates between a 2d and a 3d cameras
