### ISSUE TITLE
Integrate cargo fmt into CI (Github Actions)

### ISSUE THREAD

**Issue by thefuntastic** [bevyengine/bevy#163]
According to discord user `@karroffel` there is are two barriers:
1. Github actions has a resource limit
2. `cargo fmt` currently depends on rust nightly

Original message
https://discord.com/channels/691052431525675048/692572690833473578/743415634943017002

**Comment by cart** [comment]
Yup this is desperately needed!

**Comment by DJMcNab** [comment]
People can always use `cargo +nightly fmt` to run the formatting
Additionally, to use nightly `rustfmt` in `rust-analyzer`, you can use
```json
{
    "rust-analyzer.rustfmt.overrideCommand": [
        "rustup",
        "run",
        "nightly",
        "rustfmt",
        "--edition",
        "2018"
    ]
}
```
in settings.json (if you are using vscode). It's not ideal, but it's not too bad to set up

**Comment by Moxinilian** [comment]
cargo fmt check is now part of CI
