### ISSUE TITLE
GlobalTransform should be mutable

### ISSUE THREAD

**Issue by UkoeHB** [bevyengine/bevy#16317]
## Problem

In 0.15, GlobalTransform was changed to be immutable. This breaks use-cases like [extol_sprite_layer](https://github.com/deifactor/extol_sprite_layer) and UI hacks around repositioning nodes after layout (e.g. having a UI tooltip that follows the cursor but gets stuck on window boundaries).

## Solution

Allow GlobalTransform to be mutated, perhaps with a suitable 'use at your own risk' disclaimer.

**Comment by mweatherley** [comment]
It wasn't changed, so I'm closing this.

**Comment by UkoeHB** [comment]
Looks like this was a false alarm. The API has not changed, only the docs now claim it is immutable (when you can still reassign it, since `From<Mat4>` and `From<Affine3A>` are still implemented).

**Comment by MiniaczQ** [comment]
Yup, can't expose mutable references since it's a different representation, sorry for the confusion
