### ISSUE TITLE
Clone and IntoIter support for queries

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1631]
## What problem does this solve or what need does it fill?

[Itertools](https://docs.rs/itertools/0.10.0/itertools/trait.Itertools.html) has a great number of fantastic, ergonomic ways to work with iterators, like cartesian product, combinations etc that would be regularly used in games. I would love to be able to use this with my queries, but I can't due to lacking trait impls.

## What solution would you like?

impl Clone, IntoIter and any other necessary traits on both Query and QueryIter.

## What alternative(s) have you considered?

Write replacements for these methods by hand, either in the engine itself or in each game's code.

## Additional context

One of the features of itertools (`exactly_one`) was reinvented in #1263 already.

Here's a nice code snippet that I would like to be able to compile showing the building block methods:

```rust
   use bevy::prelude::*;
   
    struct Foo;
    fn my_system(query: Query<&Foo>) {
        query.clone();
        query.into_iter();
        query.iter();
        query.iter().clone();
    }
```

**Comment by alice-i-cecile** [comment]
Two more interesting use cases:
1. Reduce boilerplate by enabling the `for e in query:` sugar
2. Free ordered iteration ala #1470.

**Comment by alice-i-cecile** [comment]
Followup [conversation](https://discord.com/channels/691052431525675048/749335865876021248/824724330637688873) with @cart and @TheRawMeatball on this topic. Conclusions:
- IntoIter isn't the only blocker on using iter_tools: we would also need Clone, which isn't feasible for mutable queries
- iter_tools like functionality is very much desired because it's currently very frustrating to work with more than one entity at once in queries, like for collisions
- IntoIter support is desirable anyways
- IntoIter should resolve to iter_mut, because it's supported for both mutable and immutable queries

**Comment by Esteth** [comment]
I'm a relative rust noob, but will this require Generic Associated Types?

AFAICT you want a signature like this:

```
impl<'w, 's, Q: WorldQuery, F: WorldQuery> IntoIterator for QueryState<Q, F> {
    type Item = <Q::Fetch as Fetch<'w>>::Item;
    type IntoIter = QueryIter<'w, 's, Q, F>; 

    fn into_iter(self) -> Self::IntoIter {
```

That leaves w and s unconstrained.

**Comment by alice-i-cecile** [comment]
Related to #2042, which would provide building blocks for iter_tools-like functionality.

**Comment by alice-i-cecile** [comment]
Closing in favor of directly implementing these methods as use cases come up: the `Clone` bound is unworkable.

**Comment by Mathspy** [comment]
Is the `Clone` bound unworkable even on `QueryIter`?

**Comment by alice-i-cecile** [comment]
> Is the Clone bound unworkable even on QueryIter?

No, this should be quite simple to add and probably reasonably useful. If you'd like it, feel free to make a simple PR for it :)

**Comment by TheRawMeatball** [comment]
It'd only be valid if the query in question is read only.

**Comment by Mathspy** [comment]
> No, this should be quite simple to add and probably reasonably useful. If you'd like it, feel free to make a simple PR for it :)

Gotcha! I’ll definitely PR it if I find a usecase where I need Cartesian product where one of the two sides is immutable.

> It'd only be valid if the query in question is read only.

[This is in regards to acquiring a `QueryIter` from a mutable query via `.iter()`](https://github.com/bevyengine/bevy/pull/2305)? “Read-only” here being immutable query? Or does that term mean something else?

**Comment by TheRawMeatball** [comment]
yes, read only as in an immutable query.
