### ISSUE TITLE
bevy_text feature is required to run bevy_ui tests

### ISSUE THREAD

**Issue by UkoeHB** [bevyengine/bevy#16316]
## Bevy version

0.15-dev

## What you did

Ran `cargo test -p bevy_ui`

## What went wrong

Compile errors saying `bevy_text` is missing.

## Additional information

Works if you use `cargo test -p bevy_ui --features bevy_text`. The need to pass the feature here is unexpected and @mockersf says it's a bug.

**Comment by BenjaminBrienen** [comment]
@alice-i-cecile is this 0.15 milestone?

**Comment by mockersf** [comment]
not a blocker for the 0.15, but nice to have if there's a PR for it

**Comment by StrikeForceZero** [comment]
Ran into this updating one of my PR's. I think its just a [few cargo config related tweaks](https://github.com/bevyengine/bevy/pull/16358) missed from 396aff906e401957507726e3af7d997004117c60
