### ISSUE TITLE
Compile error in bevy_core_pipeline/smaa when running gltf tests

### ISSUE THREAD

**Issue by greeble-dev** [bevyengine/bevy#16352]
## Bevy version

Main branch [40640fd](https://github.com/bevyengine/bevy/commit/40640fdf42be1cf13eb651bd6816d742c369241a)

## What you did

```
git checkout 40640fdf42be1cf13eb651bd6816d742c369241a
cargo test --lib --package=bevy_gltf
```

## What went wrong

```
error[E0425]: cannot find function `lut_placeholder` in this scope
   --> crates\bevy_core_pipeline\src\smaa\mod.rs:332:56
    |
332 |             .insert(SMAA_AREA_LUT_TEXTURE_HANDLE.id(), lut_placeholder());
    |                                                        ^^^^^^^^^^^^^^^ not found in this scope
    |
help: consider importing this function
    |
33  + use crate::tonemapping::lut_placeholder;
    |
```

## Additional information

The error does not occur when running the CI tests (`cargo run -p ci -- test`).

I think the bug is a combination of:

1. The smaa_luts feature is disabled when running that isolated test.
2. The changes in [40640fd](https://github.com/bevyengine/bevy/commit/40640fdf42be1cf13eb651bd6816d742c369241a) accidentally removed some code related to smaa_luts. [Direct link to removed code](https://github.com/bevyengine/bevy/commit/40640fdf42be1cf13eb651bd6816d742c369241a#diff-f0a339d5d21b91db295f544748e6cfdf1988ecd304cf6cf6bbaaac5e1ac1f7a5L82).

Restoring the following code in smaa/mod.rs fixes the compile error, but I haven't visually confirmed if smaa still works.

```rust
#[cfg(not(feature = "smaa_luts"))]
use crate::tonemapping::lut_placeholder;
```

Commit in my fork: (https://github.com/greeble-dev/bevy/commit/21d09d08bc76b082f4376eb1c7c44d9e79a77ef0). I can submit a PR if desired.

**Comment by BenjaminBrienen** [comment]
Already addressed in https://github.com/bevyengine/bevy/pull/16337

You can help by reviewing the PR
