### ISSUE TITLE
Is shadow or global illumination on 0.5?

### ISSUE THREAD

**Issue by HyeokSuLee** [bevyengine/bevy#1637]
1. This is one of the important feature for 3D.
I think Voxel cone global illumination like godot, would be perfect for bevy.
Is there any plan?

2. someone plz tell me, some ways to approach to handle renderers.
I know how to use wgpu-rs, but bevy renderer is totally different structure and even the version is old( wgpu-0.6.0).

**Comment by bjorn3** [comment]
1. No, shadows are not yet supported. The rendering is pretty primitive as most attention has been towards other areas like the core ecs system.
2. In Bevy the rendering is split into two parts. First of there is bevy_render, which allows you to define render graphs in a render backend independent way. Then there is the actual render backend. By default this bevy_wgpu, which is backed by wgpu. There is also the unofficial bevy_webgl2 when compiling to wasm for usage in the browser. The documentation of bevy_render is very much lacking. I haven't used it myself, so I can't help you with it. I believe there is an example in the example directory though. You may also want to join the [discord](https://discord.gg/gMUk5Ph) to ask for help there.

**Comment by alice-i-cecile** [comment]
Looks like this question has been answered :) Shadows and global illumination are definitely on the broad roadmap, but won't be ready for 0.5. You may be interested in the PBR features that should be ready in time from #1554.

Closing this out; feel free to post in the Discussions or on Discord if you have other questions.

**Comment by jamadazi** [comment]
> even the version is old( wgpu-0.6.0)

Well, that's in the last bevy release (0.4), which is quite old. In the git main branch, we have updated to the latest wgpu a while ago. The upcoming 0.5 release will have everything up to date.

We also have someone actively working on PBR support, and it is likely that at least PBR materials will be supported in the upcoming 0.5 release, maybe even complete with support for normal maps and other texture maps.

See #1554 and #1632 for the work in progress.

The 0.5 release is coming very soon (maybe in about a week).

Real-time shadows and global illumination are big renderer features that will take some time to be implemented, so it is not going to be in 0.5. The same person working on PBR has expressed interest to work on at least shadows as well, so they might do that after the release.

If you are interested in contributing to bevy, consider joining on Discord; people will be happy to help you get up to speed on what you need to know. The community is very friendly. :)
