### ISSUE TITLE
Observer entities should have names

### ISSUE THREAD

**Issue by msvbg** [bevyengine/bevy#16384]
## What problem does this solve or what need does it fill?

Observers are spawned as entities. When using a tool like the egui inspector, observer entities are listed under the generic "Entity" name which makes it difficult to understand what they are at a glance

## What solution would you like?

Observers should spawn with a `Name` component which indicates that they are observers.

**Comment by alice-i-cecile** [comment]
This is *partly* a bug with bevy-inspector-egui, in that it should special-case Observer entities like it does for other classes of objects. But yeah, we should use the system name ideally.

**Comment by mgi388** [comment]
This should be easy to fix in inspector egui. See my recent commit fixing lights associations. https://github.com/jakobhellermann/bevy-inspector-egui/commit/8b684b3608aa321c01b3eb730fefc8307e9a30c6

If someone doesn’t get to it first I’ll try and do a PR over there, separately to this ticket.

**Comment by BenjaminBrienen** [comment]
Does adding a Name component to every Observer create significant overhead for the sake of a a feature which could be implemented instead by the editor GUI? In other words, can the editor just see what the system name is and use that for Observers? (Special-cased)

**Comment by msvbg** [comment]
> Does adding a Name component to every Observer create significant overhead for the sake of a a feature which could be implemented instead by the editor GUI? In other words, can the editor just see what the system name is and use that for Observers? (Special-cased)

I sincerely doubt it! Observers are not spawned often and there should not be that many of them in a game. Personally I think it's good practice for every entity to have a name, and strive to enforce this in my projects, but this may not be standard in the community.

**Comment by alice-i-cecile** [comment]
I think we should aim to use `Name` more aggressively. Long-term, I'd like to move more of our name-like identifiers (like system names) out into the proper `Name` component.

**Comment by BenjaminBrienen** [comment]
In that case, maybe bevy_cli could recommend that with a lint?

**Comment by alice-i-cecile** [comment]
Yeah, I would say that's a good `style` level lint.

**Comment by mockersf** [comment]
Putting names on everything means allocating strings for everything. They are nice to debug, but will have a cost

**Comment by benfrankel** [comment]
FWIW it's possible to include `Name` components behind a feature flag with one extra line:

```rust
commands.spawn((
    #[cfg(feature = "entity_names")]
    Name::new("Foo"),
    Foo,
));
```

**Comment by msvbg** [comment]
> Putting names on everything means allocating strings for everything. They are nice to debug, but will have a cost

This cost should be very minimal in the grand scheme of things. In my project I have a few dozen observers, and the total memory allocation for names would probably be somewhere south of 1kb. I struggle to see how this would be significant even for a much larger project.

> FWIW Rust makes it easy to put Name components behind a feature flag:

It could be feature gated but I don't think this should be this big of a big deal, and Bevy should not offer more obscure flags than it has to. I could see it being gated by `#[cfg(debug_assertions)]`.

**Comment by alice-i-cecile** [comment]
Yeah, I'd love to see this unified under a `dev_mode` feature or something.

**Comment by mockersf** [comment]
Should this use the same `Name` component we already have? This component is used for animations, and fast lookup (faster than string comparison). The `Name` component we already have could actually not hold a name and still work the same way.

Maybe a `QueryableName` and a `DisplayName` components?

**Comment by alice-i-cecile** [comment]
Yeah, I would prefer to avoid using the component named `Name` for animations if the performance/UX requirements are distinct.

**Comment by msvbg** [comment]
As far as I'm concerned this was fixed in https://github.com/jakobhellermann/bevy-inspector-egui/pull/223. Closing.
