### ISSUE TITLE
ChildBuilder does not respect required components

### ISSUE THREAD

**Issue by Hexorg** [bevyengine/bevy#16380]
## Bevy version

"0.15.0-rc.3"

## What you did

I ran this setup function for Startup schedule:

```rust
fn setup(mut commands:Commands) {
    let mut e = commands.spawn_empty();
    e.insert(Transform::default());
    e.with_children(|b| {
        b.spawn((PointLight::default(), Transform::IDENTITY));
    });
}
```

## What went wrong

Expected result: No warning messages.

Result I get: 

```
2024-11-13T22:31:15.585476Z  WARN bevy_hierarchy::valid_parent_check_plugin: warning[B0004]: Entity 7v1 with the InheritedVisibility component has a parent without InheritedVisibility.
This will cause inconsistent behaviors! See: https://bevyengine.org/learn/errors/b0
```

I checked and Entity 7v1 is the child

**Comment by alice-i-cecile** [comment]
I bet this is https://github.com/bevyengine/bevy/issues/16034 again. Can you test this on #16219?

**Comment by cart** [comment]
This isn't broken behavior. The parent doesn't have `InheritedVisibility`. `Transform` does not require `Visibility`. You need to insert `Visibility` on the parent, which will pull in InheritedVisibility.
