### ISSUE TITLE
Add a `TimedCommand` helper

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#16442]
## What problem does this solve or what need does it fill?

Performing a gameplay action after a specific amount of time has elapsed is a common and simple pattern.

Right now, this kind of sucks, because you need to make custom systems, components and tick timers for each effect (or build your own abstraction).

## What solution would you like?

Add a `TimedCommand` helper in `bevy_time`.

```rust
struct TimedCommand { 
    timer: Timer, 
    command: Box<dyn Command> 
}
```

These would be stored as a `Vec` in a `TimedCommands` resource, and then all of the commands ticked (probably in `First`?) during a system.

Proposed by @cart on [Discord](https://discord.com/channels/691052431525675048/774027865020039209/1308590379700064408).

## What alternative(s) have you considered?

We could cannibalize `bevy_animation`'s system for animation events, but that requires a weird dependency and isn't designed for this.

## Additional context

This was prompted by my review of https://github.com/bevyengine/bevy/pull/16440 :)

**Comment by Vrixyz** [comment]
I feel like this would be adding specifics for something that could be modeled with a component containing a Timer + leveraging Trigger observer:
- when timer just_finished, send an event with this entity as target
- store any other data on component on that
- observe the trigger event, add any other systemparam needed to react.
- it could even have a component marker to customize auto ticking behaviour

example API:

```rs
command.spawn(
  TimerWithEvent(
    Timer::new(Duration::from_secs(1),TimerMode::Once)
  )
).observe(|trigger: Trigger<TimerFinished>, mut commands: Commands| {
  // TODO: anything useful
  commands.entity(trigger.entity).despawn();
}
```

**Comment by alice-i-cecile** [comment]
Using an observer is nice! It does mean that we can't tick all of the timers in a single system. Maybe that's okay?

**Comment by alice-i-cecile** [comment]
Closing as a duplicate of #15129; we should consolidate discussion there.
