### ISSUE TITLE
Error when running Bevy app on windows

### ISSUE THREAD

**Issue by Keithcat1** [bevyengine/bevy#1646]
Sometimes it panics as soon as I start the program, sometimes it runs for a second or 2 and panics, and rarely it doesn't panic it all.
Note that I'm only using minimal plugins plus what is needed for windowing and input to reduce binary size, and also because anything that uses Bevy rendering crashes on my computer #1147
My code is:
use bevy::prelude::*;
use tts::TTS;
fn main() {
	App::build()
        .insert_resource(WindowDescriptor {
            title: "I am a window!".to_string(),
            width: 500.,
            height: 300.,
            ..Default::default()
        })
        .add_plugins(MinimalPlugins)
	.add_plugin(bevy::window::WindowPlugin::default())
	.add_plugin(bevy::winit::WinitPlugin::default())
	.add_plugin(bevy::input::InputPlugin::default())
	.add_system(key_checker.system())
	.insert_resource(TTS::default().unwrap())
	.run();
}
fn key_checker(mut speech: ResMut<TTS>, keyboard: Res<Input<KeyCode>>) {
	if keyboard.just_pressed(KeyCode::Right) {
		speech.speak("Hello!", true).unwrap();
	}
}

The panic stack trace is:
    Finished dev [unoptimized + debuginfo] target(s) in 0.50s
     Running `target\debug\examples\simple_tts.exe`
thread 'main' panicked at 'assertion failed: flush_paint_messages(None, &subclass_input.event_loop_runner)', C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:1967:21
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\core\src\panicking.rs:92
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\core\src\panicking.rs:50
   3: winit::platform_impl::platform::event_loop::thread_event_target_callback::{{closure}}<tuple<>>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:1967
   4: std::panic::{{impl}}::call_once<isize,closure-0>
             at C:\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:322
   5: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
   6: winit::window::{{impl}}::eq
   7: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
             at C:\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
   8: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:396
   9: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:152
  10: winit::platform_impl::platform::event_loop::thread_event_target_callback<tuple<>>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:2151
  11: DefSubclassProc
  12: DefSubclassProc
  13: CallWindowProcW
  14: DispatchMessageW
  15: SendMessageTimeoutW
  16: KiUserCallbackDispatcher
  17: NtUserDispatchMessage
  18: DispatchMessageW
  19: CoGetMalloc
  20: Ordinal153
  21: WindowsGetStringLen
  22: WindowsGetStringLen
  23: CoWaitForMultipleHandles
  24: WindowsCompareStringOrdinal
  25: CoWaitForMultipleHandles
  26: CoGetStandardMarshal
  27: CStdStubBuffer_Invoke
  28: Ndr64AsyncServerCallAll
  29: PropVariantClear
  30: ObjectStublessClient32
  31: CoUnmarshalInterface
  32: CoUnmarshalInterface
  33: CoUnmarshalInterface
  34: CoUnmarshalInterface
  35: CoUnmarshalInterface
  36: CoGetCurrentLogicalThreadId
  37: CoGetCurrentLogicalThreadId
  38: Ordinal153
  39: DllCanUnloadNow
  40: DllCanUnloadNow
  41: DllCanUnloadNow
  42: UiaReturnRawElementProvider
  43: <unknown>
  44: <unknown>
  45: Ordinal2712
  46: SendMessageTimeoutW
  47: KiUserCallbackDispatcher
  48: NtUserMessageCall
  49: CallNextHookEx
  50: unregisterWindowsHook
  51: Ordinal2712
  52: SendMessageTimeoutW
  53: KiUserCallbackDispatcher
  54: NtUserPeekMessage
  55: PeekMessageW
  56: PeekMessageW
  57: winit::platform_impl::platform::event_loop::flush_paint_messages::{{closure}}<tuple<>>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:683
  58: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::owned_windows<tuple<>,closure-0>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:190
  59: winit::platform_impl::platform::event_loop::flush_paint_messages<tuple<>>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:678
  60: winit::platform_impl::platform::event_loop::thread_event_target_callback::{{closure}}<tuple<>>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:1967
  61: std::panic::{{impl}}::call_once<isize,closure-0>
             at C:\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:322
  62: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  63: winit::window::{{impl}}::eq
  64: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
             at C:\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  65: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:396
  66: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:152
  67: winit::platform_impl::platform::event_loop::thread_event_target_callback<tuple<>>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:2151
  68: DefSubclassProc
  69: DefSubclassProc
  70: CallWindowProcW
  71: DispatchMessageW
  72: SendMessageTimeoutW
  73: KiUserCallbackDispatcher
  74: NtUserDispatchMessage
  75: DispatchMessageW
  76: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run_return<tuple<>,closure-1>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:218
  77: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:188
  78: winit::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
             at C:\Users\Keith\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\event_loop.rs:154
  79: bevy_winit::run<closure-1>
             at .\crates\bevy_winit\src\lib.rs:151
  80: bevy_winit::winit_runner_with
             at .\crates\bevy_winit\src\lib.rs:475
  81: bevy_winit::winit_runner
             at .\crates\bevy_winit\src\lib.rs:191
  82: core::ops::function::Fn::call<fn(bevy_app::app::App),tuple<bevy_app::app::App>>
             at C:\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:70
  83: alloc::boxed::{{impl}}::call<tuple<bevy_app::app::App>,Fn<tuple<bevy_app::app::App>>,alloc::alloc::Global>
             at C:\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\boxed.rs:1342
  84: bevy_app::app::App::run
             at .\crates\bevy_app\src\app.rs:66
  85: bevy_app::app_builder::AppBuilder::run
             at .\crates\bevy_app\src\app_builder.rs:50
  86: simple_tts::main
             at .\examples\simple_tts.rs:4
  87: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\simple_tts.exe` (exit code: 101)

**Comment by MinerSebas** [comment]
Bevy currently requires a Vulcan compatible GPU.
What GPU do you have?

**Comment by bjorn3** [comment]
On Windows wgpu uses DirectX 12 by default.

I noticed that just before the panicking frame there is a `std::panic::catch_unwind` frame. This should catch the unwind. Did you compile with `-Cpanic=abort`? That would explain why the panic is not catched.

**Comment by Keithcat1** [comment]
The compilation command I used was:
cargo run --example simple_tts
I think this problem has something to do with the TTS crate. I'm using version 0.15.0. Can you try building it?
I'll get you the GPU info when I get home.

**Comment by Keithcat1** [comment]
OK, the computer where this example is crashing is running windows 10, and has DirectX 12.
The graphics card is Intel(R) HD Graphics 4600

**Comment by alice-i-cecile** [comment]
Many versions of Bevy and wgpu have since been released, and this is effectively impossible to check on newer Bevy versions due to the hardware dependency.
