### ISSUE TITLE
`DirectionalLight` added via required components does not contribute to rendering

### ISSUE THREAD

**Issue by Jaso333** [bevyengine/bevy#16466]
## Bevy version

0.15.0-rc.3

## \[Optional\] Relevant system information

`AdapterInfo { name: "NVIDIA GeForce RTX 4090", vendor: 4318, device: 9860, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "560.94", backend: Vulkan }`

## What you did

I create a simple marker component that represents the light configuration for my game:

```
#[derive(Component)]
#[require(
    DirectionalLight,
    Transform(|| Transform::from_xyz(-1., 1., 1.).looking_at(Vec3::ZERO, Vec3::Y))
)]
pub struct GameLight;
```

I spawn this in using solely the marker component, alongside a camera and a 3D scene:

```
commands.spawn(GameCamera);
commands.spawn(GameLight);
commands.spawn(BoardCell);
```

## What went wrong

The light does not affect the scene. If change the `commands.spawn(GameLight)` to just spawn the `DirectionalLight` and `Transform` components, it works.

Spawning `GameLight`:

![Image](https://github.com/user-attachments/assets/6efa8ff6-2159-4230-88c7-af3dd7e39275)

Spawning the same components directly:

![Image](https://github.com/user-attachments/assets/60a43a25-58bd-46e6-9bdb-422b798fbb54)

I also put a debug system in to check the components are actually there by printing the debug string of both the `DirectionalLight` and `Transform`:

Spawning `GameLight`:

`(DirectionalLight { color: LinearRgba(LinearRgba { red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0 }), illuminance: 10000.0, shadows_enabled: false, soft_shadow_size: None, shadow_depth_bias: 0.02, shadow_normal_bias: 1.8 }, Transform { translation: Vec3(-1.0, 1.0, 1.0), rotation: Quat(-0.27984813, -0.36470518, -0.11591689, 0.88047624), scale: Vec3(1.0, 1.0, 1.0) })`

Spawning the same components directly:

`(DirectionalLight { color: LinearRgba(LinearRgba { red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0 }), illuminance: 10000.0, shadows_enabled: false, soft_shadow_size: None, shadow_depth_bias: 0.02, shadow_normal_bias: 1.8 }, Transform { translation: Vec3(-1.0, 1.0, 1.0), rotation: Quat(-0.27984813, -0.36470518, -0.11591689, 0.88047624), scale: Vec3(1.0, 1.0, 1.0) })`

Both seem to have the required data for the light to affect the scene in the exact same way.

**Comment by rparrett** [comment]
Seems like this should be fixed by #16441.

**Comment by alice-i-cecile** [comment]
Yep, can you test again on `main`?

**Comment by Jaso333** [comment]
> Yep, can you test again on `main`?

not sure if I'm doing something wrong, but main doesn't seem to build for me:

```
  = note: lib.def : error LNK2001: unresolved external symbol _ZN14bevy_animation1_100_$LT$impl$u20$bevy_reflect..reflect..PartialReflect$u20$for$u20$bevy_animation..AnimationEventFn$GT$18reflect_partial_eq17h224300b8f1b6ad01E␍
          lib.def : error LNK2001: unresolved external symbol _ZN14bevy_animation1_102_$LT$impl$u20$bevy_reflect..from_reflect..FromReflect$u20$for$u20$bevy_animation..AnimationEventFn$GT$12from_reflect17hd24476b2b492cc50E␍
          lib.def : error LNK2001: unresolved external symbol _ZN14bevy_animation1_102_$LT$impl$u20$bevy_reflect..tuple_struct..TupleStruct$u20$for$u20$bevy_animation..AnimationEventFn$GT$13clone_dynamic17h702eeb5ba47044d0E␍
          lib.def : error LNK2001: unresolved external symbol _ZN14bevy_animation1_111_$LT$impl$u20$bevy_reflect..type_registry..GetTypeRegistration$u20$for$u20$bevy_animation..AnimationEventFn$GT$21get_type_registration17h7e3257af40cd8c36E␍     
          lib.def : error LNK2001: unresolved external symbol _ZN14bevy_animation1_111_$LT$impl$u20$bevy_reflect..type_registry..GetTypeRegistration$u20$for$u20$bevy_animation..AnimationEventFn$GT$26register_type_dependencies17h9ff23eaddfe3d65eE␍
          C:\Projects\sinking_stones_bevy\target\debug\deps\bevy_dylib-a9d92d77dd1856ea.dll.lib : fatal error LNK1120: 5 unresolved externals␍
```

**Comment by Jaso333** [comment]
update: this fixes my above problem with main: https://github.com/bevyengine/bevy/pull/16476

**Comment by Jaso333** [comment]
@alice-i-cecile i tested on https://github.com/pcwalton/bevy/tree/animation-event-fn-reflect-opaque and the problem appears to be fixed- the light now contributes to rendering.

**Comment by BenjaminBrienen** [comment]
Marking as completed since the fix is already merged, even though testing it requires an open PR tk be merged
