### ISSUE TITLE
There are flashing color brick on the text when running breakout example.

### ISSUE THREAD

**Issue by C-Entropy** [bevyengine/bevy#16487]
## Bevy version
```
git log -1
commit 636e99c9fb384fc28ae522fac10ab8811f14c9ff (HEAD -> main, origin/main, origin/HEAD)
```

The release number or commit hash of the version you're using.

## \[Optional\] Relevant system information

```
uname -a
Linux Gentoo 6.12.0-gentoo #1 SMP PREEMPT_RT Fri Nov 22 17:12:16 CST 2024 x86_64 AMD Ryzen 9 5900HX with Radeon Graphics AuthenticAMD GNU/Linux
```
If you cannot get Bevy to build or run on your machine, please include:

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```ignore
`AdapterInfo { name: "NVIDIA GeForce RTX 2070", vendor: 4318, device: 7938, device_type: DiscreteGpu, backend: Vulkan }`
```

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

- [`wgpu`](https://github.com/gfx-rs/wgpu) for rendering problems
- [`winit`](https://github.com/rust-windowing/winit) for input and window management
- [`gilrs`](https://docs.rs/gilrs/latest/gilrs/) for gamepad inputs

## What you did

```
cargo run --features wayland --example breakout
```

## What went wrong

If it's not clear, break this out into:

- what were you expecting?
- what actually happened?
![Image](https://github.com/user-attachments/assets/004a8a64-1328-48d3-aac6-811f414115ea)

There are flashing color brick(sorry I don't know what exactly it should be called) on the text part.
## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used
- links to related bugs, PRs or discussions

**Comment by rparrett** [comment]
Looks like https://github.com/bevyengine/bevy/issues/7944

**Comment by C-Entropy** [comment]
I think they may be same, close this for now.
