### ISSUE TITLE
Contrastive adaptive sampling calls invalid accessor

### ISSUE THREAD

**Issue by Hexorg** [bevyengine/bevy#16528]
## Bevy version

master branch

## What you did

Launched anti_aliasing example and pressed 0 key to enable sharpening. 

## What went wrong

Upon hitting the key this got logged into the console.

```
2024-11-27T20:42:40.591680Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: invalid field accessor `rgbw`
   ┌─ crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/robust_contrast_adaptive_sharpening.wgsl:68:55
   │
68 │     let e = textureSample(screenTexture, samp, in.uv).rgbw;
   │                                                       ^^^^ invalid accessor
   │
   = invalid field accessor `rgbw`

```

**Comment by cart** [comment]
Interesting that this is failing now given that the file hasn't been touched in a year. I'm guessing this has to do with wgpu being more spec compliant. `rgbw` is mixing `rgba` and `xyzw` and maybe thats out of spec.
