### ISSUE TITLE
Nested text spans are not rendered if the `default_font` feature is disabled

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#16521]
## Bevy version

`0.15.0-rc.3`, also current main

## Relevant system information

```
SystemInfo { os: "MacOS 14.5 ", kernel: "23.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

- Disable `default-features`
- Decline to enable `default_font` feature
- Use nested text spans where the (empty) root node uses `TextFont::default()` either by omission of the component, or by explicitly setting it to that value.

https://github.com/rparrett/bevy-default-font-bug

```
git clone https://github.com/rparrett/bevy-default-font-bug
cd bevy-default-font-bug
cargo run
```

## What went wrong

No text is displayed

## Additional Information

Relevant snippet pasted here for convenience

```rust
let font = asset_server.load("FiraSans-Bold.ttf");
commands
    .spawn((
        Text::default(),
        // Uncommenting this makes things work
        // TextFont {
        //     font: font.clone(),
        //     ..default()
        // },
    ))
    .with_children(|parent| {
        parent.spawn((
            TextSpan::new("span, should be visible"),
            TextFont { font, ..default() },
        ));
    });
```

**Comment by rparrett** [comment]
This could potentially be rephrased like "if any text span has an invalid font handle, the entire text does not render."

**Comment by UkoeHB** [comment]
`TextPipeline::update_buffer` exits early if any font is not available. It will wait until all fonts are loaded.

**Comment by cart** [comment]
Investigating our options now

**Comment by cart** [comment]
I think the biggest issue to resolve for 0.15 is "spans with valid fonts nested under empty Text not rendering by default if there is no default font".

A fix that feels reasonable for that would be to skip empty spans / not fail out for "not yet loaded" fonts when text is empty. I'll give that a try.

The long term (likely harder) and more controversial fix would be to more effectively iteratively render text as fonts load. However this would result in unnecessary re-layouts + pop in. Idk if thats desirable.
