### ISSUE TITLE
Toggling sharpening on then off results in a massively oversharpened image despite sharpening being disabled.

### ISSUE THREAD

**Issue by Elabajaba** [bevyengine/bevy#16531]
## Bevy version

2a66bf0909992b280420442ecda42a38d37de326 with https://github.com/bevyengine/bevy/pull/16530 so sharpening actually works

## What you did

Run the `anti_aliasing` example, then toggle sharpening on and off. Wait a bit and it starts glitching out.

## What went wrong

Image ends up being oversharpened to the point of looking broken, with the oversharpening artifacts changing over time as well despite sharpening being disabled.

![Image](https://github.com/user-attachments/assets/46804700-ae96-4f8d-82fb-6db7a0ec23b3)

**Comment by alice-i-cecile** [comment]
This is almost certainly a retained rendering world bug. We need to make sure that the component responsible is getting removed correctly.
