### ISSUE TITLE
Bevy crashes when attempting to use font with limited number of glyphs.

### ISSUE THREAD

**Issue by RylanYancey** [bevyengine/bevy#16569]
## Bevy version

0.15.0

## \[Optional\] Relevant system information

- Ubuntu 24.04
- cargo 1.84.0-nightly

```
SystemInfo { os: "Linux 24.04 Ubuntu", kernel: "6.8.0-49-generic", cpu: "AMD Ryzen 5 7640U w/ Radeon 760M Graphics", core_count: "6", memory: "30.7 GiB" }

AdapterInfo { name: "NVIDIA GeForce RTX 4060", vendor: 4318, device: 10370, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "560.35.03", backend: Vulkan }
```

## What you did

I have a font that I use for my title screen that has a limited number of glyphs. [See here](https://fontstruct.com/fontstructions/show/2473268/mojangcraft-1). In bevy 0.14.2, the font loads fine, but in 0.15.0, an error occurs. 

Below is the _only_ location the font is used in the program. 
```rs
parent.spawn((
    Text::new("JANZEN"),
    TextFont {
        font: assets.load("fonts/company.otf"), // < bevy fails because of this font.
        font_size: 150.0,
        ..default()
    },
    TextColor(Color::WHITE),
));
```

## What went wrong

```
Fatal error when processing text: failed to get scaled glyph image for cache key: CacheKey { font_id: ID(InnerId(1v1)), glyph_id: 43, font_size_bits: 1125515264, x_bin: Zero, y_bin: Zero, flags: CacheKeyFlags(0x0) }.
```

## Additional information

When I use a different font, such as `Handle::default()`, no such error occurs.

I believe that bevy is trying to cache glyphs that are commonly used, but this font does not support. If that is the case, then bevy should have better error messages to communicate exactly what those glyphs are so I can fix it in a font editor.

You can find the repository [here](https://github.com/RylanYancey/Minecraft-Rust-Edition.git).

**Comment by rparrett** [comment]
I think that your font file may be malformed in some other way. I have an app that uses a font with a single glyph, and I am not experiencing this with Bevy 0.15.

**Comment by RylanYancey** [comment]
> I think that something else could be going on here. I have an app that uses a font with a single glyph, and I am not experiencing this with Bevy 0.15.

I added the repository to the bottom of my original message. Is there any other information I could provide to assist you?

**Comment by rparrett** [comment]
This only seems to happen with the `otf` version of the font. The `ttf` downloaded from the link in the PR description doesn't crash. To me, this suggests a potential issue in the font itself, but it could also be an issue with `cosmic-text` or `ttf-parser`.

<details>
<summary>Here's a runnable minimal repro</summary>

```rust
//! Issue 16569
//! https://fontstruct.com/fontstructions/show/2473268/mojangcraft-1

use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera2d);

    commands.spawn((
        Text::new("JANZEN"),
        TextFont {
            // ttf version of the font does not crash
            font: asset_server.load("fonts/mojangcraft.otf"),
            font_size: 150.0,
            ..default()
        },
    ));
}
```
</details>

**Comment by RylanYancey** [comment]
You're right, swapping out for a TTF does work. I have other OTF fonts that work fine so it must just be with this font. Weird.
