### ISSUE TITLE
Runtime error when using `bevy_winit` feature without explicitly adding `bevy_window`

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#16568]
## Bevy version

`0.15`. This issue appeared at some point during the RC process. LIkely https://github.com/bevyengine/bevy/pull/16401.

## What you did

```toml
[dev-dependencies.bevy]
version = "0.15"
default-features = false
features = [
    "android_shared_stdcxx",
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_render",
    "bevy_state",
    "bevy_ui",
    "bevy_winit",
    # "bevy_window",
    "default_font",
    "hdr",
    "multi_threaded",
    "tonemapping_luts",
    "ktx2",
    "zstd",
    "x11",
]
```

And start an app using `DefaultPlugins` that creates a window.

## What went wrong

App immediately crashes with this error, which is produced by a system outside of my app / inside of Bevy.

`
Resource requested by (bevy_ecs::system::commands::Commands, bevy_ecs::system::query::Query<(bevy_ecs::entity::Entity, &mut bevy_window::window::Window, core::option::Option<&bevy_window::raw_handle::RawHandleWrapperHolder>), bevy_ecs::query::filter::Added<bevy_window::window::Window>>, bevy_ecs::event::writer::EventWriter<bevy_window::event::WindowCreated>, bevy_ecs::change_detection::NonSendMut<bevy_winit::winit_windows::WinitWindows>, bevy_ecs::change_detection::NonSendMut<bevy_winit::accessibility::AccessKitAdapters>, bevy_ecs::change_detection::ResMut<bevy_winit::accessibility::WinitActionRequestHandlers>, bevy_ecs::change_detection::Res<bevy_a11y::AccessibilityRequested>, bevy_ecs::change_detection::Res<bevy_winit::winit_monitors::WinitMonitors>) does not exist: bevy_ecs::event::collections::Events<bevy_window::event::WindowCreated>
`

**Comment by alice-i-cecile** [comment]
`bevy_winit` should have a required dependency on `bevy_window`.
