### ISSUE TITLE
Can not add bevy, bevy_render depends on wgpu missing features

### ISSUE THREAD

**Issue by TomMD** [bevyengine/bevy#16579]
## Bevy version

git head

## \[Optional\] Relevant system information

Generic linux

## What you did

Try 1:

```
cargo new foobar
cd foobar
cargo add bevy
```

Try 2, edit the Cargo.toml directly then `cargo build`:

```
[package]
name = "bevy-hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
# bevy = "0.15" 
bevy = { git = "https://github.com/bevyengine/bevy", commit = "c425c32064b81b8bf23f882c97f818309c48bded" }
wgpu = { git = "https://github.com/gfx-rs/wgpu", commit = "1ea5498038b2fd0392bd6cbd81ec71b2438e5c95" }
```

Try 3, use bevy examples:

```
git clone https://github.com/bevyengine/bevy
cd bevy
cargo run --example hello_world # or try with various related --features
```

## What went wrong

I'm seeing:

```
error: failed to select a version for `wgpu`.
    ... required by package `bevy_render v0.15.0-dev (/home/tommd/dev/bevy/crates/bevy_render)`
    ... which satisfies path dependency `bevy_render` of package `bevy_animation v0.15.0-dev (/home/tommd/dev/bevy/crates/bevy_animation)`
versions that meet the requirements `^23.0.1` are: 23.0.1

the package `bevy_render` depends on `wgpu`, with features: `naga` but `wgpu` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
```

or replace `naga` with `hal` or various other features depending on invocation.

**Comment by mockersf** [comment]
The code is built successfully in CI, and I can't reproduce locally.

When looking at the wgpu dependency of bevy_render, it doesn't add those features
https://github.com/bevyengine/bevy/blob/c425c32064b81b8bf23f882c97f818309c48bded/crates/bevy_render/Cargo.toml#L71-L77

I don't know how you're having that error 🙁

**Comment by BenjaminBrienen** [comment]
Why is bevy_render version 0.15-dev?

**Comment by mockersf** [comment]
Bevy requirements tend to be very close to "latest stable rust", but that error was very not clear
