### ISSUE TITLE
Web examples don't run.

### ISSUE THREAD

**Issue by Fidius-jko** [bevyengine/bevy#16582]
## Bevy version

0.15 

## \[Optional\] Relevant system information
Chrome 131.0.6778.86

## What you did

Open web example on webgl2
![Image](https://github.com/user-attachments/assets/d974db1c-b816-4f2f-8144-e058eb36ea1b)

## What went wrong

Don't run.

## Additional information

![Image](https://github.com/user-attachments/assets/22d3b03f-4a73-4281-9c0f-02e63d8b34be)

invalid link to runner.

**Comment by mockersf** [comment]
I can't reproduce on my side, could it be a problem with your internet provider connecting to cloudflare (who is hosting those files)

**Comment by lomirus** [comment]
I can't reproduce either.

**Comment by Fidius-jko** [comment]
Most likely this applies to me, since I am from Russia and Cloudflare by default uses an extension that violates Russian law and this extension is blocked in Russia.
