### ISSUE TITLE
Borrow mutable resource and components at the same time with the world object.

### ISSUE THREAD

**Issue by xiemeilong** [bevyengine/bevy#1660]
## What problem does this solve or what need does it fill?

I need borrow mutable resource and components at the same time , but after resource merged to world . That become  impossiable.

## What solution would you like?

I don’t know.

## What alternative(s) have you considered?

The component type I need to query is selected depend on network data, so  I can only use the world object .

**Comment by jakobhellermann** [comment]
You can use the `World::resource_scope` method for that:
https://github.com/bevyengine/bevy/blob/ac661188c8679e767c4f2abebee22b4db3128e99/crates/bevy_ecs/src/world/mod.rs#L599-L615

**Comment by xiemeilong** [comment]
@jakobhellermann Would I must nest call of resource_scope  if I want multiple resource?

**Comment by jakobhellermann** [comment]
If you need access to multiple entire resources, then yes, nesting `resource_scope` is the way to go.
In many cases you don't need access to your resource and the component at the same time though, so you can do all your mutable accesses at the top, and then modify your component at the bottom.

**Comment by xiemeilong** [comment]
> In many cases you don't need access to your resource and the component at the same time though, so you can do all your mutable accesses at the top, and then modify your component at the bottom.

There is loop in my case, so the mutable resource is reused.
