### ISSUE TITLE
Change detection with interior mutability

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1661]
## What problem does this solve or what need does it fill?

Because we rely on `DerefMut` to detect changes, we can't 

## What solution would you like?

Best practices and advice are clearly documented for end users.

## What alternative(s) have you considered?

> Yup not much we can do about this short of making it easy for developers to trigger a change manually. In cases where interior mutability is needed, deref_mut() can't be called anyway (because interior mutability enables mutations from read-only contexts). Maybe adding a commands.set_changed::&lt;T&gt;(entity) command to make it easy for people to queue up changes in read only contexts without actually needing to mutate the component?.

- @cart in [comments](https://github.com/bevyengine/bevy/pull/1471#issuecomment-799750865) of #1471.

## Additional context

First brought up in the context of #1471. This behavior exists both before and after the changes in that PR.

**Comment by Ratysz** [comment]
I posit that anyone understanding what "interior mutability" is also realises that it will not set a "this was accessed mutably" flag. More documentation is good, but just a "this only works on full mutable access, so interior mutability will not trigger it" should do here.

A form of `commands.set_changed::<T>(entity)` is not an alternative: it's a new feature that should probably be a thing anyway.
