### ISSUE TITLE
bevy_mobile_example crashes during runtime

### ISSUE THREAD

**Issue by Valetoriy** [bevyengine/bevy#16634]
## Bevy version

Bevy 0.15

## What you did

`cargo apk run -p bevy_mobile_example`

## What went wrong

The Android app crashes whenever I try to open it
For some reason it expects Android Native Activity to be present (I'm not a Bevy expert, but I think it should be using Game Activity instead)

## Additional information
![Image](https://github.com/user-attachments/assets/e95b46d4-aed0-4ca7-8dd7-aad3eace80d2)
![Image](https://github.com/user-attachments/assets/326506aa-10db-4218-a4b6-bcf3028848ed)

 Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.56s
 'lib/arm64-v8a/libc++_shared.so'...
 'lib/arm64-v8a/libbevy_mobile_example.so'...
Verifying alignment of /home/spff/gitimport/gamedev/bevy/target/debug/apk/bevy_mobile_example.apk (4)...
      49 AndroidManifest.xml (OK - compressed)
     880 lib/arm64-v8a/libc++_shared.so (OK)
 1795728 lib/arm64-v8a/libbevy_mobile_example.so (OK)
Verification succesful
Signing `/home/spff/gitimport/gamedev/bevy/target/debug/apk/bevy_mobile_example.apk` with keystore `/home/spff/.android/debug.keystore`
Performing Incremental Install
Serving...
All files should be loaded. Notifying the device.
Success
Install command complete in 10070 ms
Starting: Intent { act=android.intent.action.MAIN cmp=rust.bevy_mobile_example/android.app.NativeActivity }
--------- beginning of crash
12-03 23:41:58.397 14248 14248 E AndroidRuntime: FATAL EXCEPTION: main
12-03 23:41:58.397 14248 14248 E AndroidRuntime: Process: rust.bevy_mobile_example, PID: 14248
12-03 23:41:58.397 14248 14248 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/~~u7LYJwMXeuKx2UW2zu2Bpw==/rust.bevy_mobile_example-GdI1rOOlUWXBzRt9TtmPLg==/lib/arm64/libbevy_mobile_example.so": undefined symbol: ANativeActivity_onCreate
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.app.NativeActivity.onCreate(NativeActivity.java:178)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8661)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8639)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1457)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3845)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4003)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:110)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2523)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:245)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:364)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8424)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
12-03 23:41:58.397 14248 14248 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: FATAL EXCEPTION: main
12-04 00:00:09.102 15180 15180 E AndroidRuntime: Process: rust.bevy_mobile_example, PID: 15180
12-04 00:00:09.102 15180 15180 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/~~laLQSoKVYbo0yIHGLoOdRg==/rust.bevy_mobile_example-jhpwq3XjS-wt4h7KoFUqqg==/lib/arm64/libbevy_mobile_example.so": undefined symbol: ANativeActivity_onCreate
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.app.NativeActivity.onCreate(NativeActivity.java:178)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8661)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8639)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1457)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3845)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4003)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:110)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2523)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:245)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:364)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8424)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
12-04 00:00:09.102 15180 15180 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: FATAL EXCEPTION: main
12-04 00:00:58.758 15564 15564 E AndroidRuntime: Process: rust.bevy_mobile_example, PID: 15564
12-04 00:00:58.758 15564 15564 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/~~9CI4MVgxQ1GS1yIQq5REzQ==/rust.bevy_mobile_example-c8kK1lTxvkxhaiv0-2IA0g==/lib/arm64/libbevy_mobile_example.so": undefined symbol: ANativeActivity_onCreate
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.app.NativeActivity.onCreate(NativeActivity.java:178)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8661)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8639)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1457)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3845)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4003)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:110)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2523)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:245)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:364)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8424)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
12-04 00:00:58.758 15564 15564 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
--------- beginning of main
12-04 00:18:16.267 20536 20536 I _mobile_example: Late-enabling -Xcheck:jni
12-04 00:18:16.294 20536 20536 I _mobile_example: Using CollectorTypeCMC GC.
12-04 00:18:16.320 20536 20536 D nativeloader: Load libframework-connectivity-tiramisu-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity-t.jar: ok
12-04 00:18:16.344 20536 20536 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10349; state: DISABLED
12-04 00:18:16.344 20536 20536 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10349; state: DISABLED
12-04 00:18:16.355 20536 20536 W System  : ClassLoader referenced unknown path: 
12-04 00:18:16.356 20536 20536 D nativeloader: Configuring clns-4 for other apk . target_sdk_version=30, uses_libraries=, library_path=/data/app/~~xniVjPOZcdaVbRt661cItA==/rust.bevy_mobile_example-c4dgICS5R0E6ktd9l_jngQ==/lib/arm64:/data/app/~~xniVjPOZcdaVbRt661cItA==/rust.bevy_mobile_example-c4dgICS5R0E6ktd9l_jngQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/rust.bevy_mobile_example
12-04 00:18:16.356 20536 20536 D nativeloader: Extending system_exposed_libraries: libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libQOC.qti.so:libupdateprof.qti.so:libthermalclient.qti.so:libQOC.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
12-04 00:18:16.362 20536 20536 D nativeloader: Load libframework-connectivity-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity.jar: ok
12-04 00:18:16.365 20536 20536 I Perf    : Connecting to perf service.
12-04 00:18:16.368 20536 20536 V GraphicsEnvironment: Currently set values for:
12-04 00:18:16.368 20536 20536 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
12-04 00:18:16.368 20536 20536 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
12-04 00:18:16.369 20536 20536 V GraphicsEnvironment: ANGLE GameManagerService for rust.bevy_mobile_example: false
12-04 00:18:16.369 20536 20536 V GraphicsEnvironment: rust.bevy_mobile_example is not listed in per-application setting
12-04 00:18:16.369 20536 20536 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
12-04 00:18:16.371 20536 20536 V Monotype: SetAppTypeFace- try to flip, app = rust.bevy_mobile_example
12-04 00:18:16.374 20536 20536 V Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
12-04 00:18:16.378 20536 20536 D CompatibilityChangeReporter: Compat change id reported: 247079863; UID 10349; state: DISABLED
12-04 00:18:16.604 20536 20536 D nativeloader: Load /data/app/~~xniVjPOZcdaVbRt661cItA==/rust.bevy_mobile_example-c4dgICS5R0E6ktd9l_jngQ==/lib/arm64/libbevy_mobile_example.so using ns clns-4 from class loader (caller=<unknown>): ok
12-04 00:18:16.605 20536 20536 W NativeActivity: ANativeActivity_onCreate not found: undefined symbol: ANativeActivity_onCreate
12-04 00:18:16.605 20536 20536 D AndroidRuntime: Shutting down VM
12-04 00:18:16.606 20536 20536 E AndroidRuntime: FATAL EXCEPTION: main
12-04 00:18:16.606 20536 20536 E AndroidRuntime: Process: rust.bevy_mobile_example, PID: 20536
12-04 00:18:16.606 20536 20536 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/~~xniVjPOZcdaVbRt661cItA==/rust.bevy_mobile_example-c4dgICS5R0E6ktd9l_jngQ==/lib/arm64/libbevy_mobile_example.so": undefined symbol: ANativeActivity_onCreate
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.app.NativeActivity.onCreate(NativeActivity.java:178)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8661)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8639)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1457)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3845)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4003)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:110)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2523)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:245)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:364)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8424)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
12-04 00:18:16.606 20536 20536 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
12-04 00:18:16.614 20536 20536 I Process : Sending signal. PID: 20536 SIG: 9

**Comment by BUGO07** [comment]
same thing happens to me too

**Comment by mockersf** [comment]
Did you follow the instructions from https://github.com/bevyengine/bevy/blob/main/examples/mobile/android_basic/readme.md?

https://github.com/bevyengine/bevy/blob/a6b5f807159433e393ee478682f5074e1d5efa32/examples/mobile/android_basic/readme.md?plain=1#L16

before running the `cargo apk` command, you need to replace the `Cargo.toml` file from the mobile project by this one: https://github.com/bevyengine/bevy/blob/main/examples/mobile/android_basic/Cargo.toml

**Comment by Valetoriy** [comment]
> Did you follow the instructions from https://github.com/bevyengine/bevy/blob/main/examples/mobile/android_basic/readme.md?
> 
> [bevy/examples/mobile/android_basic/readme.md](https://github.com/bevyengine/bevy/blob/a6b5f807159433e393ee478682f5074e1d5efa32/examples/mobile/android_basic/readme.md?plain=1#L16)
> 
> Line 16 in [a6b5f80](/bevyengine/bevy/commit/a6b5f807159433e393ee478682f5074e1d5efa32)
>  When using `cargo-apk`, it must use `NativeActivity`, so you need to edit it in `Cargo.toml` manually like this: 
> 
> Before running the `cargo apk` command, you need to replace the `Cargo.toml` file from the mobile project by this one: https://github.com/bevyengine/bevy/blob/main/examples/mobile/android_basic/Cargo.toml
> 
> If you want to use a game activity, you'll have to use the new setup using gradle described in https://github.com/bevyengine/bevy/blob/main/examples/README.md#android

Thanks, that helped
