### ISSUE TITLE
0.15 Regression of border rendering when rendering a filled `ImageNode`

### ISSUE THREAD

**Issue by ActuallyHappening** [bevyengine/bevy#16643]
## Bevy version

0.15

## \[Optional\] Relevant system information

Linux pop!OS, bevy 0.15, `cargo --version` returns `cargo 1.83.0 (5ffbef321 2024-10-29)`, using stable

```ignore
`AdapterInfo { name: "AMD Radeon RX 7800 XT (RADV NAVI32)", vendor: 4098, device: 29822, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319", backend: Vulkan }`
```

## What you did

Applied a [`border`](https://docs.rs/bevy/latest/bevy/prelude/struct.Node.html#structfield.border) in the `Node` component that was `UiRect::all(Val::Px(10.))` and added the [`BorderColor`](https://docs.rs/bevy/latest/bevy/prelude/struct.BorderColor.html) component to the same entity.

This rendered the border fine.

## What went wrong

I then added an [`ImageNode`](https://docs.rs/bevy/latest/bevy/prelude/struct.ImageNode.html) to the same entity, with a `Handle<Image>` that took up all the space available.

The border disappeared.
I didn't expect the border to disappear, in bevy 0.14 the border was not overridden. Its not the end of the world for my current projects that this behavior exists, but it is a regression from 0.14.

## Additional information

0.15 code:
```rust
use bevy::prelude::*;

fn main() -> impl std::process::Termination {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, bug)
        .run()
}

fn bug(mut commands: Commands) {
    commands.spawn(Camera2d);
    commands.spawn((
        ImageNode::solid_color(bevy::color::palettes::css::BLANCHED_ALMOND.into()), // un/comment to observe border bug
        Node {
            border: UiRect::all(Val::Px(10.)),
            width: Val::Percent(100.),
            height: Val::Percent(100.),
            ..default()
        },
        // using green to show that the camera does indeed show the (transparent) ImageNode
        BackgroundColor(bevy::color::palettes::css::GREEN.into()),
        // should display a yellow border
        BorderColor(bevy::color::palettes::css::YELLOW.into()),
    ));
}
```

With `ImageNode` commented out:
(Yellow border renders fine)
![Image](https://github.com/user-attachments/assets/8b463d04-2316-4711-83cf-0a5e3bfa434a)

With `ImageNode` included (not commended out):
(Yellow border and green background do not render at all)
![Image](https://github.com/user-attachments/assets/0f81d222-6aa1-47a6-98d8-415a44eaf12b)

I would write some 0.14 code to demonstrate this same behaviour, but I can't work out how to construct a solid `Handle<Image>` like the convenient `ImageNode::solid_color` call above does. I'm currently porting `bevy_cosmic_edit` from 0.14 to 0.15 which has its own code to render an `Image` of an exact size which is where I originally noticed this regression (in example `every_option`).

Also, I know that `ImageNode.color` exists and that `ImageNode::solid_color` doesn't construct a non-default `Image<Handle>`, so this problem may be with [`ImageNode.color`](https://docs.rs/bevy/latest/bevy/prelude/struct.ImageNode.html#structfield.color)

**Comment by marioferpa** [comment]
I'm pretty sure it's not a bug. You need to spawn everything except the ImageNode, ant then the ImageNode as a children.

**Comment by ickshonpe** [comment]
This is a bug, it's my fault probably, all the changes with required components got pretty confusing. It's easy to fix, I'll put in a pr later this evening.

**Comment by ActuallyHappening** [comment]
Ahh thanks very much
I read through the bevy 0.15 blog post about required components, my only uncertain aspect is the expected behaviour of stacking multiple 'driving components' together. What if you put a `ImageNode` and a `Mesh3d` together? Anyway thats a larger more open question

**Comment by ickshonpe** [comment]
> Ahh thanks very much I read through the bevy 0.15 blog post about required components, my only uncertain aspect is the expected behaviour of stacking multiple 'driving components' together. What if you put a `ImageNode` and a `Mesh3d` together? Anyway thats a larger more open question

Mixing together different `driving components` in unintended ways will probably result in an unpedictable mess or panic and it's not a good idea unless you have a deep knowledge of all the possible interactions of the components.

**Comment by ickshonpe** [comment]
Right looked at this properly now, doesn't look like a bug after all.
It's a measure func thing. You need to set `NodeImageMode::Stretch` otherwise it'll override the border width.

Modified your example so it draws the border over the solid image color:

```rust
use bevy::prelude::*;

fn main() -> impl std::process::Termination {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, bug)
        .run()
}

fn bug(mut commands: Commands) {
    commands.spawn(Camera2d);
    commands.spawn((
        ImageNode::solid_color(bevy::color::palettes::css::BLANCHED_ALMOND.into())
            .with_mode(NodeImageMode::Stretch), 
        Node {
            border: UiRect::all(Val::Px(10.)),
            width: Val::Percent(100.),
            height: Val::Percent(100.),
            ..default()
        },
        // using green to show that the camera does indeed show the (transparent) ImageNode
        BackgroundColor(bevy::color::palettes::css::GREEN.into()),
        // should display a yellow border
        BorderColor(bevy::color::palettes::css::YELLOW.into()),
    ));
}
```

**Comment by ickshonpe** [comment]
The documentation about this is really poor. I'm sure we used to have a UI image example, but it seems to have got lost somewhere?

**Comment by ActuallyHappening** [comment]
Oh OK thanks
Maybe some version of my example code should be added to that enum variant for future travelers? Anyway this fixed my issue thanks :)
