### ISSUE TITLE
`DebugUiPlugin` doesn't respect scale factor properly

### ISSUE THREAD

**Issue by JeanMertz** [bevyengine/bevy#16666]
## Bevy version

0.15

## What you did

Enable `DebugUiPlugin`'s outline drawing.

## What went wrong

Outline is twice the size of the actual nodes.

## Additional information

This seems to be introduced by https://github.com/bevyengine/bevy/pull/16375, which did not update the debug implementation here: https://github.com/bevyengine/bevy/blob/83c729162f9079b592ee7dce66df599a7e32f6e0/crates/bevy_dev_tools/src/ui_debug_overlay/mod.rs#L40-L48

**Comment by alice-i-cecile** [comment]
> But it's not applying the inverse scale factor introduced in that PR.

As noted on [Discord](https://discord.com/channels/691052431525675048/885021580353237032/1314326805674463444).

**Comment by ickshonpe** [comment]
Yeah I just completely forgot this plugin existed 😅
