### ISSUE TITLE
`EaseFunction::ExponentialIn` jumps at the beginning

### ISSUE THREAD

**Issue by scottmcm** [bevyengine/bevy#16676]
## Bevy version

2024-12-05 https://github.com/bevyengine/bevy/commit/bc572cd27

## What you did

Called `ExponentialIn.eval(0)`, expecting it to be essentially 0, but it returned about 1‰ instead.

See tests in https://github.com/bevyengine/bevy/pull/16675/files#diff-91e5390dd7a24ce92750ba40df5ef8d7a2466401ef7d3e50eb3d8861b8bc52d6R486-R501
```
EaseFunction.ExponentialIn(0) was 0.0009765625
```

## Additional information

It's only the `Exponential*` functions that fail these tests; the rest of them all pass.

TBH, the definition feels very arbitrary to me in comparison to the other things:

https://github.com/bevyengine/bevy/blob/72f096c91ea1056c41f2da821d310765c4482c00/crates/bevy_math/src/curve/easing.rs#L327-L330

Why `10`, for example?

It makes me wonder if it should be something more like <https://en.wikipedia.org/wiki/Non-analytic_smooth_function#Smooth_transition_functions> instead.

**Comment by mockersf** [comment]
from the definition in https://easings.net/#easeInExpo
we're missing a `if t == 0.0 { return 0.0;}`

**Comment by IQuick143** [comment]
To be precise the formula should be something like:
```
(exp(at) - 1) / (exp(a) - 1)
```
where a is whatever parameter you like
What happened was a bunch of approximations:
```
// choose a to be some "large" number, like 10
(exp(at) - 1) / (exp(a) - 1)
// exp(a) >> 1, so the -1 got neglected
(exp(at) - 1) / exp(a)
exp(at - a) - exp(-a)
// exp(-a) is very small, so it got neglected as well
exp(at - a)
// finally in this case a = 10 ln(2), so we get
2^(10t - 10)
```
For t = 1 the two approximations cancelled out, for t = 0, the second approximation introduced the error.

Personally not a huge fan of the special case for t = 0.0, seems to me like it just shunts the issue to the next floating point number.

**Comment by mweatherley** [comment]
Well, upstream isn't really a problem; we own `EaseFunction`, so we can do whatever we deem best. Personally, I think just ditching some of the approximations is probably fine, but I also don't feel strongly about this (other than it certainly should produce zero at `t = 0.0`).

**Comment by IQuick143** [comment]
My proposal would be to just use the formula I posted earlier, it effectively incurs a cost of one division and one subtraction (as opposed to one branch), which is imo negligible. The code is a bit uglier, but it would at least (with a proper doc comment) explain how you can adapt the code for other parameters than `10 ln(2)`

**Comment by mockersf** [comment]
there's no really "upstream" or "standard" here, the page I linked (and used when creating the functions) is what people coming from the web are used to

**Comment by IQuick143** [comment]
Yeah, I don't think web people will notice us using a slightly different function (the difference is on the order of thousands), it will still have the exponential shape and feel.

**Comment by IQuick143** [comment]
Very ugly, but completely valid.
