### ISSUE TITLE
create_surfaces is unsound

### ISSUE THREAD

**Issue by spectria-limina** [bevyengine/bevy#16683]
## Bevy version

0.15

## What went wrong

In [`create_surfaces`](https://github.com/bevyengine/bevy/blob/24c3bd5f005867aa483237071e3add4f13a43904/crates/bevy_render/src/view/window/mod.rs#L328), the underlying `create_surface_unsafe` is called under the assumption that any surface target inside of `ExtractedWindows` is guaranteed to be valid.

This isn't true, however. The fields on [`RawHandleWrapper`](https://github.com/bevyengine/bevy/blob/24c3bd5f005867aa483237071e3add4f13a43904/crates/bevy_window/src/raw_handle.rs#L52) are public, so any user could insert garbage data and cause the call to `create_surface_unsafe` to use invalid data.

## Propose solution

Make `RawHandleWrapper`'s fields private, replacing them with accessors and `unsafe` constructors.

**Comment by alice-i-cecile** [comment]
I think that solution is good.
