### ISSUE TITLE
Hard lock using State across stages

### ISSUE THREAD

**Issue by siler** [bevyengine/bevy#1671]
## Bevy version

main: 284889c6

## Operating system & version

Windows 10 20H2

## What you did

```rust
use bevy::{
    prelude::*,
    input::{
        keyboard::KeyboardInput,
        ElementState
    }
};

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_state(GameState::Start)
        .add_system_set(SystemSet::on_update(GameState::Start).with_system(transition_check.system()))
        .add_system_set_to_stage(CoreStage::PreUpdate, SystemSet::on_update(GameState::Freeze).with_system(do_something.system()))
        .run();
}

#[derive(Clone, Eq, PartialEq)]
pub enum GameState {
    Start,
    Freeze
}

fn transition_check(mut state: ResMut<State<GameState>>, mut keyboard_event_reader: EventReader<KeyboardInput>) {
    for event in keyboard_event_reader.iter() {
        if event.key_code == Some(KeyCode::Return) && event.state == ElementState::Pressed {
            state.set_next(GameState::Freeze).unwrap();
        }
    }
}

fn do_something() {}

```

## What you expected to happen

When the return key is pressed the state transitions to `GameState::Freeze` and the `do_something` system begins firing.

## What actually happened

When the return key is pressed the application hard locks and enters "not responding".

## Additional information

If I try to use a state that I added with `add_state(..)` as a run criteria for a system I add to any stage other than update (via `add_system_set_to_stage(..)`, the application freezes as soon as the state transition occurs.

**Comment by rparrett** [comment]
Able to reproduce on macos. It seems that the `do_nothing` system executes over and over, but probably no other systems do after the transition.

**Comment by mockersf** [comment]
this freeze for me:
```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_state(GameState::Freeze)
        .add_system_set_to_stage(
            CoreStage::PreUpdate,
            SystemSet::on_update(GameState::Freeze).with_system(do_something.system()),
        )
        .run();
}

#[derive(Clone, Eq, PartialEq)]
pub enum GameState {
    Freeze,
}

fn do_something() {}
```

it does not freeze if the system set is added to stage `CoreStage::Update`

**Comment by mockersf** [comment]
this is because the system set `make_driver` is added only to stage `Core::Update`
https://github.com/bevyengine/bevy/blob/284889c64b2a4a4f67018e42a14062392edbd0aa/crates/bevy_app/src/app_builder.rs#L180-L183
https://github.com/bevyengine/bevy/blob/284889c64b2a4a4f67018e42a14062392edbd0aa/crates/bevy_app/src/app_builder.rs#L139-L141

**Comment by rparrett** [comment]
Indeed, this patch to the code from the original issue seems to make things work properly

```rust
         .add_state(GameState::Start)
+        .add_state_to_stage(CoreStage::PreUpdate, GameState::Start)
```

**Comment by cart** [comment]
Removing this from the 0.5 milestone in favor or #1746

**Comment by djeedai** [comment]
Can confirm both bug and workaround from @rparrett (thanks!).

**Comment by james7132** [comment]
Checking in, is this still relevant after stageless? States now work across base sets and the run conditions have significantly simplified the mental model for states.

**Comment by alice-i-cecile** [comment]
This is no longer possible.
