### ISSUE TITLE
Make `extract_mesh_materials` and `MaterialBindGroupAllocator` public

### ISSUE THREAD

**Issue by jadedbay** [bevyengine/bevy#16730]
In Bevy 0.14 I had copied the `MaterialPlugin` but changed the draw commands as I needed custom ones, now in 0.15 the `ExtractInstancesPlugin` seems to have changed and is no longer added in but instead there is `extract_mesh_materials` system and `MaterialBindGroupAllocator` resource but both are private.

These should be made public so it's possible for users to copy the material abstraction easily.

**Comment by mockersf** [comment]
could you provide an example code that would use what you need? or open a PR

that would make it easier to be sure it does what you need

**Comment by jadedbay** [comment]
I basically just have to be able to recreate the `MaterialPlugin` in my own project.

`extract_mesh_materials` is as easy as just making it public.

`MeshBindGroupAllocator` is inside a private module, I can open PR if you want, but if you could give some guidance if I should just make the entire module public or change everything inside it that's currently `pub` to be `pub(crate)` (besides the `MeshBindGroupAllocator`). Cheers.

**Comment by mockersf** [comment]
does #16982 works for you?

**Comment by jadedbay** [comment]
The `matierial_bind_groups` mod is still private though so I don't think I'd be able to initialize `MaterialBindGroupAllocator` in the plugin.
