### ISSUE TITLE
Add support to the `animated_field!` macro for tuple structs

### ISSUE THREAD

**Issue by yonzebu** [bevyengine/bevy#16736]
## What problem does this solve or what need does it fill?

Components like `TextColor` and `BackgroundColor` cannot currently be easily animated without creating a custom `AnimatableProperty`.

## What solution would you like?

Add support to the `animated_field!` macro (and consequently `AnimatedField`) for tuple structs. I'm not sure what the cleanest way to do this is from an implementation perspective, since the `$ident` pattern doesn't match tuple struct field indices and I'm not sure if it makes sense to use `$literal`, as that matches more than just field indices.

## What alternative(s) have you considered?

- Add an alternative easy way to animate tuple structs (e.g. a separate macro/type)
- Maybe something could be done with `Deref` and a blanket implementation of `AnimatableProperty`? But this puts the burden on components to implement `Deref`, only works for tuple structs with single fields, and also introduces potential conflicts with trait implementations because it would be a blanket implementation

## Additional context

I was specifically trying to animate UI color alpha when I ran into this, and I wonder if it's worth considering if there should be easy ways to get a `&mut` to a `Color`'s alpha and also possibly animate individual fields of a component's fields (e.g. animating `Transform::translation::x`), but that's a separate issue and probably a little more complicated.

**Comment by alice-i-cecile** [comment]
Can you use `_0` and so on? That's the field name of tuple structs.

**Comment by yonzebu** [comment]
`_0` and friends don't seem to work with the macro, Rust complains about incorrect field names because the macro does field access via the provided field name.
You can try to construct an `AnimatedField` directly (the below compiles):
```rust
#[derive(Clone, Debug, Component, Reflect)]
struct MyTupleStruct(f32);
    
let mut clip = AnimationClip::default();
clip.add_curve_to_target(
    AnimationTargetId::from_name(&Name::new("target")),
    AnimatableCurve::new(
        AnimatedField::new_unchecked(
            "_0", 
            |my_tuple_struct: &mut MyTupleStruct| &mut my_tuple_struct.0
        ),
        EasingCurve::new(0., 1., EaseFunction::Linear),
    )
);
```
...but running it panics because `AnimatedField` only supports non-tuple structs. I could probably draft a PR to make it possible to manually construct an `AnimatedField` (it seems like a trivial fix, just check for tuple structs as well), but I'm not as sure what the "correct" way to change the macro would be, or if changing `AnimatedField` would be useful without also fixing the macro.

**Comment by alice-i-cecile** [comment]
Let's start with that and get more feedback in review.
