### ISSUE TITLE
Bevy UI nodes are always pixel-aligned and there is no way to disable it

### ISSUE THREAD

**Issue by MatrixDev** [bevyengine/bevy#16731]
## Bevy version

- 0.15.0

## \[Optional\] Relevant system information

```
- cargo 1.83.0 (5ffbef321 2024-10-29)
- MacOS Sonoma 14.1.1 (23B81)
- SystemInfo { os: "MacOS 14.1.1 ", kernel: "23.1.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
- AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

Made UI follow 3d entity. Bascially I want to make health bar (and some more info) to stick above/belove each unit.

## What went wrong

It seams that Bevy UI nodes are always aligned to pixels. This is a good thing for static UI to make it sharper but introduces jaggines when UI is smoothly moved. This is especially noticeable when UI is placed near the object.

I think default behaviour is correct but there should be a way to disable it and allow sub-pixel positions/sizes for UI. It probably should be some component added to the root node or a flag in the `TargetCamera`.

## Additional information

Here is example from the game in question:
![Image](https://github.com/user-attachments/assets/3d80b4d3-eb3d-41fd-81ae-42df816f0c95)

As you can see model moves smoothly but green borders and red rect (all are nodes within a single root node) are always jumping here and there. If you just look/focus at the model, it becomes much more noticeable.

UI position is calculated by projecting each corner of the hexagon and taking min/max x/y values:
```rust
let corners = Map::get_layout().hex_corners(agent.hex)
    .map(|e| e.extend(0.0).xzy())
    .map(|e| camera.world_to_viewport(camera_transform, e))
    .map(|e| e.unwrap_or(Vec2::INFINITY));

if corners.iter().any(|e| !e.is_finite()) {
    continue;
}
let Some((min_x, max_x)) = corners.iter().minmax_by_key(|e| e.x).into_option() else {
    continue;
};
let Some((min_y, max_y)) = corners.iter().minmax_by_key(|e| e.y).into_option() else {
    continue;
};

node.top = Val::Px(min_y.y);
node.left = Val::Px(min_x.x);
node.width = Val::Px(max_x.x - min_x.x);
node.height = Val::Px(max_y.y - min_y.y);
```

Here is simpler example:
![Image](https://github.com/user-attachments/assets/6783b587-9f08-438b-889c-661e07e6eabb)

UI scaling in this case is 2, so it takes half of the logical pixel to see UI moving.

**Comment by alice-i-cecile** [comment]
Hmm. I see your point. I'm not sure where the best place to expose a setting for this would be. @ickshonpe may have ideas.

**Comment by JeanMertz** [comment]
NyIt would be great if this could be defined on a node and have it apply to that node and all nodes down the tree, but I guess that’s technically not possible?

**Comment by ickshonpe** [comment]
> It would be great if this could be defined on any node and have it apply to that node and all nodes down the tree, but I guess that’s technically not possible?

Nope I ended up implementing the per-node setting, it was easier. I had some vague concerns with mixing up unrounded and rounded layouts but they probably aren't worth worring about. 

The other problem with the per-node approach is that generating a rounded layout is more expensive as it walks the layout tree a second time. With a per-root approach you can skip generating the rounded layout.
