### ISSUE TITLE
Registry Types schema endpoint in Bevy Remote Protocol

### ISSUE THREAD

**Issue by Leinnan** [bevyengine/bevy#16745]
Basically `export_types` functionality from [blenvy](https://github.com/kaosat-dev/Blenvy) package adapted for Bevy Remote Protocol. Extra points if there would be a in game functionality that would allow to save that export types at runtime.

**Comment by alice-i-cecile** [comment]
This [looks like the code](https://github.com/kaosat-dev/Blenvy/blob/d5f14bc03790678f0d5d8bc3bd35a44609c5ac58/crates/blenvy/src/registry/export_types.rs#L10). This seems like a schema using reflection information to encode the information about all of the registered types; is that correct?

**Comment by Leinnan** [comment]
@alice-i-cecile Yep, that is my understanding as well.
