### ISSUE TITLE
derive Copy for Stopwatch/Timer

### ISSUE THREAD

**Issue by mirsella** [bevyengine/bevy#16743]
## What problem does this solve or what need does it fill?

Easier usage of Stopwatch/Timer, including custom struct wrapping a Timer.
Personally im using a macro to generate components with derive and more, and one of them has a timer, which mean all the other components can't be Copy even if they dont use timer.

## Additional context

from https://doc.rust-lang.org/std/marker/trait.Copy.html:
`(Copy) Types whose values can be duplicated simply by copying bits.`
`Generally speaking, if your type can implement Copy, it should.`
`A type can implement Copy if all of its components implement Copy.`

all theses a true, and all the field of Stopwatch/Timer impl copy.

i can open a PR, thanks !

**Comment by BenjaminBrienen** [comment]
The general advice is to implement common traits when possible for this reason, so I'm in agreement.

**Comment by rparrett** [comment]
I think that implicit duplication of these specific types could be pretty confusing.

**Comment by mirsella** [comment]
I thought of that, but i guess its exactly the same with most rust types like Duration ? i agree it can lead to non-wanted duplication, but it seems to be widely used in rust.
in what case (code) would an accidental “hidden” copy happen ? sorry im new and can't seems to find a examples, apart from some that are not really "hidden" so i would count them.

my use case is special and i don't think is revelant:
```rust
define_components! {
    struct TroopHealth { pub current: u32, pub max: u32 },
    struct Cost(pub u32),
    struct GoldGeneration(pub u32, pub Timer),
    struct Damage(pub u32),
    struct AttackCooldown(pub Timer),
```
i have a simple macro like this to create the components, derive things on them, add them to a struct with a builder that allows simple constructions of stats, this struct has a method to insert all of its stats on a entity and bevy_replicon::replicate them.
i have a single derive statement for all the components in the macro, and so they all need to be the same. at Timer doesn't implement Copy, all other Components can't. in most systems that use these components, i need to clone() simple struct even like Damage, or Cost to send events, and create more entity, as they don't implement Copy.

**Comment by rparrett** [comment]
> i have a simple macro like this to create the components, derive things on them

It seems sort misguided to derive `Copy` for all of the components in an entire app unconditionally.

> its exactly the same with most rust types like Duration

The difference between e.g. `Stopwatch` and `Duration` is the `is_paused` field which we expect users to mutate. An unintentional copy isn't just a performance concern, but also a potential source of bugs.

**Comment by mirsella** [comment]
> It seems sort of misguided to derive Copy for all of the components in an entire app unconditionally.

for my use case its to build a stat sheet for some Cards, and only use it in this context. personally, I prefer having Copy for simpler (shorter) code, and with inlay types there's no problem, but i understand this can be a problem for some persons.

> The difference between e.g. Stopwatch and Duration is the is_paused field which we expect users to mutate

i think its still mostly the same for Duration, just less used: both need mut to be modified. both have getter to get the internal state (Duration have dozens of getter method like `.as_secs()`) so logic issue occurring by having Copy on Stopwatch would happen the same using a `Duration`: increase a Duration, and latter check if it has depassed a threshold.

going further, its the same with any struct: even `Transform` already impl `Copy` ! and we could say the same thing: it can cause issue: if the user accidentally copy a transform or one of its field !

**Comment by mirsella** [comment]
got another comment on the pr disagreeing with this, closing
