### ISSUE TITLE
Panic when calling `EntityWorldMut::insert` after adding two observers

### ISSUE THREAD

**Issue by Zoomulator** [bevyengine/bevy#16760]
## Bevy version

0.14.2 and 0.15.0

## What you did

The following minimal reproduction will panic on the insert:
```
use bevy::prelude::*;

#[derive(Event)]
pub struct A;

#[derive(Event)]
pub struct B;

fn setup(world: &mut World) {
    let mut x = world.spawn_empty();
    x.observe(|_trigger: Trigger<A>| {});
    x.observe(|_trigger: Trigger<B>| {});
    x.insert(Transform::default()); // Panic!
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}
```

Version 0.15.0 gives this error:
```
thread 'main' panicked at [...]/alloc/src/vec/mod.rs:1528:13:
swap_remove index (is 1) should be < len (is 1)
```
Version 0.14.2
```
thread 'main' panicked at [...]/bevy_ecs-0.14.2/src/archetype.rs:533:38:
attempt to subtract with overflow
```

Calling `x.update_location()` before the `insert` resolves the problem.

**Comment by alice-i-cecile** [comment]
Can you reproduce on `main`? https://github.com/bevyengine/bevy/pull/16219 might have fixed this.

**Comment by Diddykonga** [comment]
Interesting observation but, the errors are slightly different.
In 0.15:
The archetype.entities.len() is actually 1, but the row.index() is also 1
In 0.14:
The archetype.entities.len() is actually 0, which the `is_last` condition attempts to subtract causing the overflow.

0.15 has technically already made progress, its one more statement ahead xD

**Comment by Zoomulator** [comment]
> Excellent minimal reproduction. Can you reproduce on `main`? [#16219](https://github.com/bevyengine/bevy/pull/16219) might have fixed this.

Just checked `main` and it's not panicking there. You guys fix bugs so fast you break causality.
