### ISSUE TITLE
Visual tearing with `ImageFilterMode::Nearest`

### ISSUE THREAD

**Issue by musjj** [bevyengine/bevy#16773]
## Bevy version

`0.15.0`

## What you did

When `ImageFilterMode::Nearest` is set as the default sampler, tearing occurs to text, sprites, etc. when the window resolution is an odd number (`101x303`, etc.). You can test by spawning a sprite and then resizing the window:

```rust
use bevy::prelude::*;

fn main() -> AppExit {
    App::new()
        .add_plugins(DefaultPlugins.set(ImagePlugin::default_nearest()))
        .add_systems(Startup, setup)
        .run()
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera2d);

    commands.spawn(Sprite::from_image(asset_server.load("grid_480x270.png")));
}
```

The notable exception is that it doesn't happen to sprites with dimensions that is the power of two (`512x256`, etc.).

You can test a more elaborate, interactive reproduction here: https://github.com/musjj/nearest_filter_bug. Slowly and gradually resize the window and you should be able to see the artifacts popping in and out.

## What went wrong

Visual tearing occurs.

## Additional information

An example of **no** tearing:

![Image](https://github.com/user-attachments/assets/e710f492-ae55-45f7-be54-8a0efa1ad830)

An example of tearing:

![Image](https://github.com/user-attachments/assets/07b73db3-03f3-4c45-89a3-6be8ca004463)

A closeup of the tearing (the lines are supposed to be perfectly straight):

![Image](https://github.com/user-attachments/assets/3482fa54-c955-4367-9843-f84aa70c2490)

**Comment by sophrosyne97** [comment]
I did happen to notice this back right before 0.15.0 was released, specifically in 0.15.0-rc3 when running the pixel_grid_snap.rs example. When I did a git bisect to see which commit it started it on, it ended up on this particular one: #15969.

It still happens to me on release-0.15.0 as well, although strangely I can only reproduce it on Linux; on Windows I can't seem to ever produce the effect (although resizing the window doesn't update quite the same where I can see it resize to each pixel as I drag, I'd have to drag and let go to see it which means I might be missing it at some particular window size)

As for the System and Adapter info:
```SystemInfo { os: "Linux rolling Arch Linux", kernel: "6.12.3-arch1-1", cpu: "AMD Ryzen 9 5900X 12-Core Processor", core_count: "12", memory: "31.3 GiB" }```
```AdapterInfo { name: "AMD Radeon RX 6900 XT (RADV NAVI21)", vendor: 4098, device: 29615, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.3.1-arch1.2", backend: Vulkan }```

![Image](https://github.com/user-attachments/assets/03eec606-68b7-48ce-9522-b4f71df1d6e6)

You can see the tearing near the bottom left of the mesh in the pixel_grid_snap.rs example

![Image](https://github.com/user-attachments/assets/33081915-1341-462f-b132-90f04e6b7b23)

**Comment by musjj** [comment]
@sophrosyne97 

THANK YOU for the bisect, that was it! It looks like that it's a rounding bug, applying this patch fixes the issue:

```patch
diff --git a/crates/bevy_render/src/camera/projection.rs b/crates/bevy_render/src/camera/projection.rs
index 7deb061..05271c1 100644
--- a/crates/bevy_render/src/camera/projection.rs
+++ b/crates/bevy_render/src/camera/projection.rs
@@ -494,10 +494,10 @@ impl CameraProjection for OrthographicProjection {
         let origin_y = projection_height * self.viewport_origin.y;
 
         self.area = Rect::new(
-            self.scale * -origin_x,
-            self.scale * -origin_y,
-            self.scale * (projection_width - origin_x),
-            self.scale * (projection_height - origin_y),
+            (self.scale * -origin_x).round(),
+            (self.scale * -origin_y).round(),
+            (self.scale * (projection_width - origin_x)).round(),
+            (self.scale * (projection_height - origin_y)).round(),
         );
     }
```

But I'm not sure how "correct" this patch is. If you want to open a PR, go ahead!

**Comment by sophrosyne97** [comment]
@musjj 

No problem! That patch does solve the tearing issue for me, but I still unfortunately seem to get some form of pixel distortion when I resize the window. Specifically, as I resize the window I can see some of the pixels changing in size such that one pixel can appear more "smushed" than another, and all the pixels of a sprite seem to be kind of shifting around in size which I didn't experience in 0.14.2. Unfortunately I have to leave for work soon, but when I come back I'll try to take some webms to make things more clear and try to tinker with it.

**Comment by musjj** [comment]
You're right, I'm noticing that too. I tried to reproduce it in `0.14` and it works perfectly there like you said. No tearing, no pixel shifting. You can try out my repro here: https://github.com/musjj/nearest_filter_regression. There's a `0.14` and `0.15` branch.

I first thought that the pixel shifting is necessary because the sprite and window pixels aren't aligned. But I guess there's a better way to deal with this as shown in `0.14`.

**Comment by musjj** [comment]
Ok I think I got it, just needed to copy-paste the logic that the PR left out for some reason:

```patch
diff --git a/crates/bevy_render/src/camera/projection.rs b/crates/bevy_render/src/camera/projection.rs
index 7deb061..8d6caf9 100644
--- a/crates/bevy_render/src/camera/projection.rs
+++ b/crates/bevy_render/src/camera/projection.rs
@@ -490,14 +490,16 @@ impl CameraProjection for OrthographicProjection {
             ScalingMode::Fixed { width, height } => (width, height),
         };
 
-        let origin_x = projection_width * self.viewport_origin.x;
-        let origin_y = projection_height * self.viewport_origin.y;
+        let origin_x =
+            (projection_width * self.viewport_origin.x * self.scale).round() / self.scale;
+        let origin_y =
+            (projection_height * self.viewport_origin.y * self.scale).round() / self.scale;
 
         self.area = Rect::new(
-            self.scale * -origin_x,
-            self.scale * -origin_y,
-            self.scale * (projection_width - origin_x),
-            self.scale * (projection_height - origin_y),
+            -origin_x,
+            -origin_y,
+            projection_width - origin_x,
+            projection_height - origin_y,
         );
     }
```

I'm not sure why it was removed in the PR though. Hopefully, this won't cause any regressions somewhere else.

**Comment by sophrosyne97** [comment]
Yep, works for me as well! 

Much appreciated, this issue was bothering me quite a bit :smiling_face_with_tear: 

Nice job!
