### ISSUE TITLE
Allow me to configure bevy to panic if a resource doesnt exist, like it did in 0.14 (infallible resources)

### ISSUE THREAD

**Issue by ethereumdegen** [bevyengine/bevy#16793]
## What problem does this solve or what need does it fill?

bevy 0.15 is very annoying for me now because if i forget to register a resource, the code just wont work and i dont know why without digging through my logs.  

## What solution would you like?
I would prefer if I could make it works like in 0.14 where it would panic when a resource is not registered.   

## What alternative(s) have you considered?
  na

**Comment by mockersf** [comment]
duplicate of #16578
