### ISSUE TITLE
Possibility to limit number of used CPU cores?

### ISSUE THREAD

**Issue by BafDyce** [bevyengine/bevy#168]
My machine has 24 logical cores. All of them spin up and run a workload, even for the simplest application. It would be great if there was a possibility to limit the number of actively used cores. This would have the following benefits:

* Dont waste power/dont heat up your room when you're only doing basic stuff
* Dont impact other applications in the background too much
* Allows to do benchmarks for lower end systems without having to spin up VMs / containers with cgroups.

This is probably also related to #111 

I was already poking around in `ParallelExecutor` but couldnt identify any obvious place where this could be added.

**Comment by Ratysz** [comment]
This is due to `rayon` defaulting to as many threads as there are cores when initializing it's global thread pool. Perhaps resource+behavior akin to the window settings can be implemented to tune the global thread pool without requiring users to invoke `rayon` directly?

**Comment by karroffel** [comment]
#188 was merged, so this can be closed :tada:
