### ISSUE TITLE
Manually insert `RenderEntity` / reverse extract

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#16850]
## What problem does this solve or what need does it fill?

The new retained render world allows (and, forces) synchonizing entities between both worlds. This can be done via the `entity_sync_system()` with the `SyncToRenderWorld` component, but there's no way to manually insert the `RenderEntity` component on an entity of the `MainWorld`. The reverse is possible; you simply use the extract phase to read the `RenderEntity` from the main world, and write the `MainEntity` in the render world. But since there's no (as I know) "reverse extract" where the render world is read-only and the main world can be mutated, it's impossible to manually insert the `RenderEntity` into the main world with custom logic.

## What solution would you like?

One of:
- Have a `ReverseExtract` phase at the end of rendering, and helper system param to do render->main sync.
- Allow the extract phase to mutate the main world (incidentally, this allows stealing resources from main to render without copying them, which can't be done simply if the main world is immutable, and requires workarounds like interior mutability).

## What alternative(s) have you considered?

I'm kind of stuck because I looked at `entity_sync_system()` and it's using a hard-coded hook into the `SubApp`, where it's explicitly called before the `extract(main, render)` call. Since I can neither 1) read the existing `SubApp::extract` function (to be able to call it from a custom one which would replace it); nor 2) add a second custom extract function to the render app, as a consequence I cannot install my own sync system with custom logic because I would overwrite the default Bevy one and break all extract systems.

## Additional context

I'm trying to convert Hanabi to use the retained render world, and need to sync the particle effect on the main world and the cache one on the render world, both pointing to each other. I believe this should greatly simplify/clarify the code, by leveraging ECS to store the data instead of custom containers, and allow more granular and clear systems to operate on partial effect data (as opposed to know, few systems doing many different things on one giant blob of data per effect). However I want to run custom logic when creating the render app entity, because I only want to do so if the main world component passed a few basic validations, to prune potentially invalid effects. I also hate having that `SyncToRenderWorld` marker component which is unrelated to my library, and is redundant with the fact all entities with my particle component should already synchronize by design. Finally, the `SyncWorldPlugin` says the sync is done at the very beginning of the frame, but I want this sync done just before extract, because I don't want to incur a one frame delay on newly spawned effects.

**Comment by alice-i-cecile** [comment]
I don't have strong feelings here, but @pcwalton or @tychedelia might. If you can come up with a non-breaking solution here I'll make sure it gets into a 0.15 point release.

**Comment by djeedai** [comment]
Re-thinking about this, I think part of my answer is in my question 🤡 since I found the `entity_sync_system()` is called right before extract, so the sentence in the docs "at the very beginning of the frame" is misleading (should read "of the _render_ frame"), but indeed the entities are sync'ed once you start extraction and after the main world ticked.

For the requirements, I forgot to mention that several components on the render entity contain references to GPU resources, so I need a hook to read those _before_ the entity and its components are despawned. Otherwise I will have GPU memory leaks. I didn't look into the observers API; maybe there's a way to do that?

As for the minimal non-breaking solution, I think adding the ability to inject a custom pre-extract system via _e.g._ `SubApp::add_pre_extract()` or be able to replace the default one with an override which calls it (so, needs read access on replace, maybe `SubApp::set_extract()` should return the previous function?).

**Comment by alice-i-cecile** [comment]
Yeah, OnRemove observers (or hooks) will work perfectly to catch the memory leaks.

> As for the minimal non-breaking solution, I think adding the ability to inject a custom pre-extract system via e.g. SubApp::add_pre_extract() or be able to replace the default one with an override which calls it (so, needs read access on replace, maybe SubApp::set_extract() should return the previous function?).

Can we expose a system set to allow you to inject logic at the right time?

**Comment by djeedai** [comment]
> Can we expose a system set to allow you to inject logic at the right time?

Well, I believe that's what #16862 would do? Or are you thinking about something else @alice-i-cecile? This is a bit specific because it needs mutable access to both the main and render worlds, so I don't think a normal system registered inside an existing schedule would allow that, would it?
