### ISSUE TITLE
Split up `bevy_core`

### ISSUE THREAD

**Issue by ItsDoot** [bevyengine/bevy#16892]
## What problem does this solve or what need does it fill?

Title. This crate is basically a utilities crate, which we would like to avoid (`bevy_utils` is slowly being split up, for example). See here for its current API surface: https://docs.rs/bevy_core/latest/bevy_core/

## What solution would you like?

We should:
- Move `FrameCount` and its plugin to `bevy_diagnostics` or `bevy_window`
- Move other plugins to `bevy_app`
- Move everything else to `bevy_ecs`

## What alternative(s) have you considered?

Leave it as-is.

## Additional context

Related to #11478 and #16877.

[Originally brought up on the Bevy Discord.](https://discord.com/channels/691052431525675048/692572690833473578/1319072745010761749)

**Comment by alice-i-cecile** [comment]
Related to #11478.

**Comment by bushrat011899** [comment]
Recording here for visibility:

My list of little restructures I'd like:
* Move bevy_core::Name  into bevy_ecs
* Move bevy_core::TypeRegistrationPlugin and bevy_core::TaskPoolPlugin into bevy_app
* Move bevy_core::FrameCountPlugin into bevy_diagnostic
* Merge bevy_log into bevy_diagnostic (significant overlap between the two crates conceptually IMO)
* Move platform compatibility stuff out of bevy_utils and out of being inlined in crates and into its own new crate, bevy_platform_support (portable-atomic-util, hashbrown, web_time, etc.)
* Take all the Future and parallel stuff out of bevy_utils and put it in bevy_tasks
* Remove all the tracing/log stuff out of bevy_utils entirely, maybe putting some of it into bevy_diagnostic.
* Put things like bevy_utils::default and bevy_utils::assert_object_safe in a pair of micro-crates that'll never be updated ever again.

That'd remove bevy_utils, bevy_log, and bevy_core and replace them with 2 micro crates that can be moved out of the repo, and 1 more targeted crate bevy_platform_support

_Originally posted on [Discord](https://discord.com/channels/691052431525675048/692572690833473578/1319097890739716210)_

**Comment by bushrat011899** [comment]
Also related to #16877
