### ISSUE TITLE
Consider renaming `NodeImageMode` to `ImageNodeMode`

### ISSUE THREAD

**Issue by mgi388** [bevyengine/bevy#16909]
- In 0.15, we now have `ImageNode`, and I just noticed it has a field `image_mode` of type `NodeImageMode` (notice the inconsistency):

```rust
pub struct ImageNode {
    /// Controls how the image is altered to fit within the layout and how 
    /// the layout algorithm determines the space to allocate for the image.
    pub image_mode: NodeImageMode,
}
```

- Looks like `image_mode` was added in https://github.com/bevyengine/bevy/pull/16088 and merged on 5 Nov.
- `UiImage` was renamed by cart in https://github.com/bevyengine/bevy/pull/16271 and merged on 8 Nov.
- It's possible the close timing here meant it was missed.
- I can't see `NodeImageMode` used by anything else that would suggest keeping this name was deliberate.

**Comment by ickshonpe** [comment]
It was a deliberate name choice.  Originally there was only one `ImageMode` which was used by both `Sprite` and `Node`. But `Node` requires some different options to support automatic sizing within a UI layout so we removed it and added two new types instead, `SpriteImageMode` and `NodeImageMode` instead.

The API changes were a bit rushed and I wasn't entirely happy with them, but I don't think the name `NodeImageMode` is a problem and I prefer it to the suggested alternative.

**Comment by mgi388** [comment]
@ickshonpe I’m happy to defer to your judgement. I don’t feel strongly! It did stand out to me as odd looking but not fussed.
