### ISSUE TITLE
commands.spawn_batch() causes panic

### ISSUE THREAD

**Issue by Ixentus** [bevyengine/bevy#1692]
## Bevy version

main#348e2a3d

## Operating system & version

Arch Linux 5.11.6

## What you did

```
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_system(setup.system())
        .run();
}

fn setup(
    mut commands: Commands,
) {
    commands.spawn(());

    let mut tiles = Vec::new();

    for _ in 0..=20 {
        tiles.push(SpriteBundle {
            ..Default::default()
        })
    }

    commands.spawn_batch(tiles);
}
```

## What you expected to happen

No panic

## What actually happened

thread 'main' panicked at 'assertion failed: len <= self.capacity()', ~/.cargo/git/checkouts/bevy-f7ffde730c324c74/348e2a3/crates/bevy_ecs/src/storage/blob_vec.rs:120:9

## Additional information

Doesn't happen when changing the 20 to any number over 62 or 1

**Comment by alice-i-cecile** [comment]
We should ensure that this is fixed as part of #1562. Adding the 0.5 milestone to this as a result.

**Comment by cart** [comment]
Looking now. This isn't specific Commands. It behaves the same way for direct World access:

```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup.exclusive_system())
        .run();
}

fn setup(world: &mut World) {
    // does not panic on upper bounds of 0..63, panics on 64...
    for _ in 0..64 {
        let mut tiles = Vec::new();

        for _ in 0..=20 {
            tiles.push(SpriteBundle {
                ..Default::default()
            })
        }

        world.spawn_batch(tiles);
    }
}
```

**Comment by cart** [comment]
Note that I changed the `add_system` to `add_startup_system` to show that this fails after spawn_batch is repeated X times.
