### ISSUE TITLE
Perfectionism

### ISSUE THREAD

**Issue by suprohub** [bevyengine/bevy#16927]
Can someone fix this??? Why arguments goes in reverse order?

![Image](https://github.com/user-attachments/assets/bf76a77c-64b1-4ce2-b4b3-4d7cf2e7b88e)

**Comment by bushrat011899** [comment]
I believe that `Collider` component is from a 3rd party library (e.g., Avian), so it's not unexpected that there would be some inconsistencies in function signatures. Perhaps you should verify which library is providing that type and open a PR to fix it!

**Comment by Jondolf** [comment]
This is the order used by bevy_rapier, Avian uses the same argument order as Bevy. Rapier's order is like that because of Parry's shape types.

I recommend making an issue about this for bevy_rapier if one doesn't already exist.
