### ISSUE TITLE
Ambiguity checker is unaware of run criteria (including States)

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1693]
## Bevy version

[348e2a3d404bc61afe534371b100dc173f6d076f](https://github.com/bevyengine/bevy/commit/348e2a3d404bc61afe534371b100dc173f6d076f)

## Operating system & version

Irrelevant.

## What you did
```rust
use bevy::ecs::schedule::ReportExecutionOrderAmbiguities;
use bevy::prelude::*;

#[derive(Clone, Eq, PartialEq)]
enum AppState {
    Menu,
    InGame,
}

#[derive(Default)]
struct Data;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_state(AppState::Menu)
        .init_resource::<Data>()
        .insert_resource(ReportExecutionOrderAmbiguities)
        .add_system_set(SystemSet::on_update(AppState::Menu).with_system(menu.system()))
        .add_system_set(SystemSet::on_update(AppState::InGame).with_system(game.system()))
        .run();
}

fn menu(mut _data: ResMut<Data>) {}
fn game(mut _data: ResMut<Data>) {}
```

## What you expected to happen

No ambiguities should be found.

## What actually happened

A system-order ambiguity between `menu_system` and `gameplay_system` was found.

```
 * Parallel systems:
 -- "&bevy_scratchpad::game" and "&bevy_scratchpad::menu"
    conflicts: ["bevy_scratchpad::Data"]
```

## Additional information

First reported [here](https://discord.com/channels/691052431525675048/742569353878437978/822519321283919902).

**Comment by alice-i-cecile** [comment]
Obviously, the state case is the most important example of this. But it also occurs with other run criteria:

```
use bevy::ecs::schedule::{ReportExecutionOrderAmbiguities, ShouldRun};
use bevy::prelude::*;
#[derive(Default)]
struct Data;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .init_resource::<Data>()
        .insert_resource(ReportExecutionOrderAmbiguities)
        .add_system_set(
            SystemSet::new()
                .with_system(never.system())
                .with_run_criteria(never_run.system()),
        )
        .add_system_set(SystemSet::new().with_system(always.system()))
        .run();
}

fn never_run() -> ShouldRun {
    ShouldRun::No
}

fn never(mut _data: ResMut<Data>) {}
fn always(mut _data: ResMut<Data>) {}
```

```
 * Parallel systems:
 -- "&bevy_scratchpad::always" and "&bevy_scratchpad::never"
    conflicts: ["bevy_scratchpad::Data"]
```

**Comment by alice-i-cecile** [comment]
As @cart said, I think the correct answer for the short and probably medium term is to just hard-code the systems associated with each enum variant of a state / each "step" (e.g. on_enter, on_update) as being disjoint. 

That said, this might automatically be fixed by a stageless approach (#1375), where we determine ambiguities via hard sync points instead (of which you should get between each state / step within a state).

**Comment by Ratysz** [comment]
> That said, this might automatically be fixed by a stageless approach (#1375), where we determine ambiguities via hard sync points instead (of which you should get between each state / step within a state).

No, sync points have nothing to do with states. Sync points (dependencies, ambiguities...) are about execution order, states are about execution fact.

We could slightly-less-hard-code a fix for states: automatically define explicit execution order between systems with the appropriate run criteria. This is not that different, in the end, but it makes sure these relationships are reflected in the chached data instead of being simply hard-coded in the ambiguity checker. This won't reduce parallelization potential: systems in question are by definition not supposed to be executable at the same time.

This is solvable for states because we actually know the relationships systems with those run criteria will have. A general solution is impossible if we don't won't to overcomplicate the API by requiring users to provide relationship tables of some kind.

A form of "define stuff by doing things to a label" API (lets call that "label properties"?) could make this more elegant, but we shouldn't be considering that as a thing-that-could-happen yet. (Stageless and label properties are orthogonal.)

**Comment by alice-i-cecile** [comment]
> We could slightly-less-hard-code a fix for states: automatically define explicit execution order between systems with the appropriate run criteria. This is not that different, in the end, but it makes sure these relationships are reflected in the chached data instead of being simply hard-coded in the ambiguity checker. This won't reduce parallelization potential: systems in question are by definition not supposed to be executable at the same time.

I like this: it solves the problem and provides more useful information in other places we may want to display / work off of execution order.

**Comment by JoJoJet** [comment]
What's the status of this now that we have Schedule v3? `OnEnter`/`OnExit` systems now live in separate schedules so there should be no ambiguities. And of course, `OnUpdate` no longer exists.

**Comment by alice-i-cecile** [comment]
This is still technically true, but no longer a practical or fixable concern.

**Comment by JoJoJet** [comment]
True. If we had some way of adding metadata to run conditions, we could hard-code `in_state` (and `state_exists_and_equals`) to mark systems as mutually exclusive with one another. We could add metadata by changing `fn in_state() -> impl FnMut()` to return an `impl Condition` wrapper type that includes the extra metadata.

**Comment by hymm** [comment]
We could maybe add a implicit set somehow for each in_state<T> value and add ambiguous with for all those sets with each other. Might be tricky now that we removed the iterator over all the states.

**Comment by hukasu** [comment]
managed to get the message on both 0.10 and 0.16, but i don't know if my reproduction is equivalent to what was done here

**Comment by alice-i-cecile** [comment]
This is still an issue: we haven't added anything that would allow for smarter behavior here.

**Comment by laundmo** [comment]
I think this is just... doable now. We have Systems::conditions which stores the `ConditionWithAccess` which at least makes this work for run-conditions, if not states.

**Comment by laundmo** [comment]
I mocked up a very basic implementation, its cloning and merging `FilteredAccessSet` and doesn't report the conflict in any nice way (errors should probably mention run conditions if they're involved), but shows its possible and not too difficult to implement.

diff for schedule/node.rs `get_conflicting_systems`
```rs
let system_a = &self[a];
/*+*/ let conditions_a = self.conditions.get(a).map(Vec::as_slice).unwrap_or(&[]);
let system_b = &self[b];
/*+*/ let conditions_b = self.conditions.get(b).map(Vec::as_slice).unwrap_or(&[]);
if system_a.is_exclusive() || system_b.is_exclusive() {
    conflicting_systems.push((a, b, Box::new([])));
} else {
/*+-*/   let mut access_a = system_a.access.clone();
/*+*/    conditions_a
/*+*/        .iter()
/*+*/        .for_each(|cond| access_a.extend(cond.access.clone()));
/*+-*/   let mut access_b = system_b.access.clone();
/*+*/    conditions_b
/*+*/        .iter()
/*+*/        .for_each(|cond| access_b.extend(cond.access.clone()));
    if !access_a.is_compatible(&access_b) {
        match access_a.get_conflicts(&access_b) {
            AccessConflicts::Individual(conflicts) => {
```
test for schedule/mod.rs
```rs
#[test]
fn resources_condition() {
    let mut world = World::new();
    world.insert_resource(R);

    let mut schedule = Schedule::default();
    schedule.set_build_settings(ScheduleBuildSettings {
        ambiguity_detection: LogLevel::Error,
        ..Default::default()
    });
    schedule.add_systems((
        resmut_system,
        empty_system.run_if(|_res: Res<R>| -> bool { false }),
    ));

    let res = schedule.initialize(&mut world);

    assert_eq!(schedule.graph().conflicting_systems().len(), 1);
    if let Err(e) = res {
        std::println!("{}", e.to_string(schedule.graph(), &world));
    }
}
```
