### ISSUE TITLE
SystemSets and run criteria need an example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1694]
No publicly facing examples are given, even in the [doc strings](https://github.com/bevyengine/bevy/blob/284889c64b2a4a4f67018e42a14062392edbd0aa/crates/bevy_ecs/src/schedule/system_set.rs).

Should be an easy improvement; stick it in the `examples/ecs` folder.

**Comment by alice-i-cecile** [comment]
#1693 provides a simple demonstration of the syntax that can be easily adapted.

**Comment by Ratysz** [comment]
Best wait until #1675: there will be more features.
