### ISSUE TITLE
Using .set_parent on an entity whose parent was Visibility:Hidden fails to refresh visibility

### ISSUE THREAD

**Issue by ethereumdegen** [bevyengine/bevy#17024]
## Bevy version
0.15 

 I found a super annoying bug !!

```
   commands
                        .entity(*equipment_link_node)
                        .set_parent(*parent_entity);

                        //this doesnt refresh inherited visibility !
```

If you use set_parent and the entity had a 'false' inherited visibility, then the inherited visibility doesnt refresh!
what gives ? is this a bug in bevy or am i supposed to handle this
i think it is because of this 

```
fn visibility_propagate_system(
    changed: Query<
        (Entity, &Visibility, Option<&Parent>, Option<&Children>),
        (With<InheritedVisibility>, Changed<Visibility>),
    >,
    mut visibility_query: Query<(&Visibility, &mut InheritedVisibility)>,
    children_query: Query<&Children, (With<Visibility>, With<InheritedVisibility>)>,
) {
```

doesnt account for changed<parent>   ... ?   seems like it doesnt

**Comment by ethereumdegen** [comment]
I am able to fix my issue for now by doing this 

```
      commands
                        .entity(*equipment_link_node)
                        .set_parent(*parent_entity);

                        //this doesnt refresh inherited visibility !

                        //a dirty hack to fix a bevy bug.. ? 
                    if let Some(mut cmd) = commands.get_entity( *equipment_link_node ){
                        cmd.insert(Visibility::Inherited); // a hack for now 
                    }
```

**Comment by ethereumdegen** [comment]
i believe adding Changed<Parent> to the visibility propogate may fix this.. feel free to chime in

**Comment by BenjaminBrienen** [comment]
You should try it and make a PR :)

**Comment by ethereumdegen** [comment]
how can i test it in my game?  i tried this to no avail 

```
[patch.crates-io]
bevy = { git="https://github.com/ethereumdegen/bevy" , rev = "1b2afeb4b"   }
```

**Comment by BenjaminBrienen** [comment]
Normally I just set the dependency path to a local folder. See the `path` property.

**Comment by ethereumdegen** [comment]
Yeah no matter how i set up patch, it errored.  I got it super close to where it only had 23 errors but they were all related to Reflect.  Anyways i made this PR 

https://github.com/bevyengine/bevy/pull/17025  

Hopefully someone else can test it

**Comment by BenjaminBrienen** [comment]
Bevy doesn't have specific instructions for testing local changes with a test project because it isn't any different from any other rust library crate.

**Comment by ethereumdegen** [comment]
Hmm. well apparently i need to learn more about rust patching because no matter what i do i cant get the patching to work -- it seems like its "reflection" that is messing it up for me somehow.  so, anyways. sad.
