### ISSUE TITLE
Intermittent panic in Alien Cake Addict example

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#1704]
## Bevy version

Found this while testing #1703, but it turned out to maybe be an existing system order ambiguity thing.

dd4a19632928556b88ffd53a9f8c3f615fce0095
7b64840bdaa6069eb71d8ed93e2eae84f35915c5 (#1703)

## Operating system & version

macOS

## What you did

`cargo run --example alien_cake_addict` and wait. If cake appears, restart and try again.

## What actually happened

```
thread 'Compute Task Pool (5)' panicked at 'called `Result::unwrap()` on an `Err` value: NoSuchEntity', examples/game/alien_cake_addict.rs:333:61
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /Users/robparrett/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: alien_cake_addict::rotate_bonus
             at ./examples/game/alien_cake_addict.rs:333:34
```

**Comment by rparrett** [comment]
Oops, that's the same stack trace twice. One moment.

**Comment by rparrett** [comment]
Fix incoming

**Comment by rparrett** [comment]
There are two separate panics going on here. I'll open another issue for the other one later.

**Comment by alice-i-cecile** [comment]
Added to the milestone due to frustrating intermittent crash that seems to be a regression.
