### ISSUE TITLE
Picking: Make it easier to check if no pickable entity is clicked/hovered currently

### ISSUE THREAD

**Issue by laundmo** [bevyengine/bevy#17042]
## What problem does this solve or what need does it fill?

Currently, picking events are only observers and only on the interacted-with entities. This requires using PointerInput, PointerMap, and PointerInteraction together to figure out that a click happened and that it did not hit any pickable entities.

Theres also (seemingly) no way to map between ButtonInput and picking Pointers, making a non-observer approach less intuitive due to having to use purely picking types.

## What solution would you like?

Ideally, i feel there should be a unified API for input handling be that picking or not. I'm not sure how this would look, since i think it should be accessible from both systems and observers (which picking is currently not, at least its documented that EventReaders won't work).

Ultimately, i'm not sure what a good solution would look like.

## What alternative(s) have you considered?

Allowing picking events to be listened to by a EventReader, to enable simple "if just_pressed and no picking events" or similar to understand if theres no entities during a click etc.

Providing a resource-based access to pointers, their current state (just_released), and the list of entities under each pointer.

A SystemParam which acts like that resource by providing utility methods which extract this information from the query/events/resources required.

Spawning a giant (invisible) entity behind everything, and use observers on it which mean that no (foreground) entity was hit.

## Additional context

There is a implementation with PointerInput, PointerMap, and PointerInteraction to check for clicks which don't interact with any entity here:
https://discord.com/channels/691052431525675048/1323319768693870682/1323343640424091699
which is the question which led me to write this issue.

**Comment by aevyrie** [comment]
Fixed by https://github.com/bevyengine/bevy/pull/16103

**Comment by laundmo** [comment]
Thanks, i was not aware of this work.

re:
> Also note that picking events can already be listened to with event readers.

The docs for bevy::picking::events read:
> To receive events from this module, you **must** use an [Observer](https://docs.rs/bevy/latest/bevy/ecs/prelude/struct.Observer.html)
(emphasis mine)

which is quite clearly wrong if you can also use EventReaders.

**Comment by aevyrie** [comment]
Huh, not sure when that comment was added during the upstream.

**Comment by aevyrie** [comment]
@laundmo fix here https://github.com/bevyengine/bevy/pull/17055

**Comment by aevyrie** [comment]
Also https://github.com/bevyengine/bevy/pull/17057
