### ISSUE TITLE
Eliminate use of glob imports in examples

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1721]
## What problem does this solve or what need does it fill?

Glob imports (aka `use bevy::prelude::*) are very convenient in real games, especially simple ones.

However, in example code, it makes it very hard to understand where imports are coming from (and risks running into namespace mangling when the boilerplate is used in real code).

## What solution would you like?

Replace glob imports in the examples with explicit imports. Do not import from the prelude (or other re-exported locations), instead use full paths so users can find the original location.

This rule should be ignored in the `games` example folder and the Bevy book. The increased brevity / lowered conceptual overhead is more valuable there.

## What alternative(s) have you considered?

Use github1s.com + go to definition to track down the places where the functions are actually defined. This is only a workaround.

## Additional context

Related to #1247.

Discussed on Discord [here](https://discord.com/channels/691052431525675048/743559241461399582/823352806500466688).

**Comment by mockersf** [comment]
I think it's better to keep using the prelude in examples. Switching to explicit imports would bloat them.

To explore, your local IDE/rust-analyzer, github1s.com, https://docs.rs/bevy (or a local build for main) fill that need.

Maybe we could look into deploying a doc build for main somewhere?

**Comment by alice-i-cecile** [comment]
> Maybe we could look into deploying a doc build for main somewhere?

I definitely want this regardless :)

**Comment by jpryne** [comment]
I'm new to Bevy and would be willing to dig into this if it is decided upon.

**Comment by alice-i-cecile** [comment]
Closing; this needs more discussion per #2047. See #1247 for more conversation.
