### ISSUE TITLE
Online docs for main

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1731]
## What problem does this solve or what need does it fill?

docs.rs doesn't provide documentation for main; which can lag behind the latest release.

This also makes it hard to show off new merged documentation improvements.

## What solution would you like?

Host the latest nightly docs on bevyengine.org, rebuilt after every merged PR.

## What alternative(s) have you considered?

Clone the bevy repo and use cargo doc. This can't be linked, goes stale, takes a while to build and is harder for beginners.

## Additional context

Discussed in #1721 and on [Discord](https://discord.com/channels/691052431525675048/692572690833473578/823626607403073566).

**Comment by mockersf** [comment]
Why not host on GitHub pages for this repo ? That would be the simplest

**Comment by alice-i-cecile** [comment]
> Why not host on GitHub pages for this repo ? That would be the simplest

I like this actually. It also makes it less discoverable for beginners, which is a benefit in this case.

**Comment by james7132** [comment]
Seems like this is resolved by #3535 and followup PRs. Closing this.
