### ISSUE TITLE
Unable to access windows in a startup system

### ISSUE THREAD

**Issue by troligtvis** [bevyengine/bevy#175]
I am trying to access primary window from a `startup_system` to be able to calculate `SpriteComponents` position based on window size. But I am getting `None` from it.

```rust
fn main() {
    App::build()
        .add_default_plugins()
        .add_startup_system(setup.system()) 
        .run();
}

fn setup(windows: Res<Windows>) {
    if let Some(window) = windows.get_primary() {
        println!("w:{} h:{}", window.width, window.height);
    } else {
        println!("no window!");
    }
}
```

Edit: Running on Windows 10 (if that might help investigation on the cause of it all)

**Comment by Bobox214** [comment]
Winit rendering is implemented as a plugin.
The window is created during the initialize phase of the winit_runner.
And the runner is started by the app after all the startup_system have been executed, explaining the behaviour.

Looking at the bevy code, it does not seem trivial to move the initial window creation out of the runner and in a startup_system of the WinitPlugin. And I don't think this will fully solve the issue as their will still be dependencies on the order of execution of the startup systems.

I wonder if here the way to go would rather be to have  a system that listen to the WindowCreated event or WindowResized event.

The following system works as expected ( probably not the most idiomatic way to handle event_reader)
```rust
use bevy::window::WindowResized;
fn test_system(windows: Res<Windows>, window_created: Res<Events<WindowResized>>) {
    let mut event_reader = EventReader::<WindowResized>::default();
    for (my_event) in event_reader.iter(&window_created) {
        if let Some(window) = windows.get_primary() {
            println!("w:{} h:{}", window.width, window.height);
        } else {
            println!("no window!");
        }
    }
}
```

**Comment by troligtvis** [comment]
Thx for looking in to this. I am new to this framework and I thought that during a startup system you could access the window. But I guess it make sense in what you say and that I could initiate my components during winit as well? Will try that :)

**Comment by IceSentry** [comment]
You can do this to access the window_descriptor in a startup_system

```rust
fn startup_system(world: &mut World, resources: &mut Resources) {
    let window_descriptor = resources
        .get::<WindowDescriptor>()
        .map(|descriptor| (*descriptor).clone())
        .unwrap_or_else(WindowDescriptor::default);
    println!("{:?}", window_descriptor);
}
```

This is what's called a thread local system since it accesses the entire resources.
https://github.com/bevyengine/bevy/blob/master/examples/ecs/ecs_guide.rs#L146

**Comment by alice-i-cecile** [comment]
Closing thanks to the solution posted. These are now called "exclusive systems", for anyone stumbling across this thread in the future <3
