### ISSUE TITLE
Inconsistent systems update timing

### ISSUE THREAD

**Issue by Jercik** [bevyengine/bevy#1751]
## Bevy version

https://github.com/bevyengine/bevy/commit/1d7196da4fff00bbc15fe75a04849de915f587d5

## Operating system & version

macOS 10.15.7

## What you did

I've run `fixed_timestep` example with `cargo run --example fixed_timestep` command.

## What you expected to happen

I've expected that `update` system will be run very close to every 1/60 seconds as the app is doing almost nothing.

## What actually happened

Update times are very inconsistent. Here is a sample of the terminal output:
```
update: 0.01669161499999916
update: 0.016214201000000372
update: 0.017137575999999655
update: 0.016843220000001935
update: 0.016607908000001004
update: 0.019092407999998784
update: 0.015112401999999747
update: 0.015805434000000673
update: 0.016627809999999243
update: 0.018651158000000834
update: 0.015467748999999031
update: 0.015830253000000738
update: 0.01877776499999939
update: 0.015447184999999308
```

`0.019092407999998784` is over 14% longer than 1/60 second. Is this expected? Wouldn't this affect animation smoothness negatively?

**Comment by alice-i-cecile** [comment]
That's very interesting: there's actually some frames that are too *short*, which is very surprising behavior, given that FixedTimeStep [should simply skips the system](https://github.com/bevyengine/bevy/blob/6121e5f933bfa215576a83cbed65292a498e2b52/crates/bevy_core/src/time/fixed_timestep.rs#L127) if not enough time has passed.

How exactly were you timing this?

**Comment by YohDeadfall** [comment]
Checked the output again and it looks like the detail about the example might lead to misunderstanding. The `FixedTimestep` works accurate enough, but the question is about drifting FPS.

**Comment by alice-i-cecile** [comment]
Ah, I see now. The problem is that the example itself is somewhat misleading, and deserves more comments. You're getting an approximately 60 FPS frame rate, likely due to vsync, and confusing that with the "once every 2 seconds" fixed_update system.

This example definitely needs to be improved for clarity (and ideally to eliminate the update spam) to avoid confusing more users like this in the future.

**Comment by YohDeadfall** [comment]
Remove printing `"update: {}"` or tweak it a bit to `"frame_update: {}"` to disambiguate it from fixed time step changes (`"fixed_update: {}"`)?

**Comment by alice-i-cecile** [comment]
> Remove printing "update: {}" or tweak it a bit to "frame_update: {}" to disambiguate it from fixed time step changes ("fixed_update: {}")?

Former is a good quick fix. I don't think it adds enough to the example for the confusion it brings.

**Comment by Jercik** [comment]
Setting aside if printing `"update: {}"` is confusing for this particular example, shouldn't it be more consistent?

**Comment by YohDeadfall** [comment]
What do you mean?

**Comment by Jercik** [comment]
Sorry, I'm new to the bevy engine, but I still don't understand why I was seeing this:
```
update: 0.019092407999998784
update: 0.015112401999999747
update: 0.015805434000000673
update: 0.016627809999999243
```
instead of something **closer** to this:
```
update: 0.016666667
update: 0.016666667
update: 0.016666667
update: 0.016666667
```

**Comment by YohDeadfall** [comment]
It depends on rendering options. For example, you can turn off vsync and see the difference (you need a GPU which can outperform the demand, i.e. render frames at a higher rate than the display can show you):

```
App::build()
        .insert_resource(WindowDescriptor {
        vsync: false,
            ..Default::default()
        })
        // ...
```

**Comment by Jercik** [comment]
Thanks for your response. I'm running an unmodified `fixed_timestep` example in release mode, so it's a super simple app without any complex logic. So these inconsistencies must be coming from OS or GPU drivers? Or is it possible that there is something wrong with bevy?

Out of curiosity, I've disabled VSync, and this is what I see in the console: 
```
update: 0.0044064759999997705
update: 0.012508828000001415
update: 0.007258220000000648
update: 0.004523580999997279
update: 0.005397581000000429
update: 0.022531852000000185
update: 0.011178918000002369
update: 0.004274413999997506
update: 0.018106995000000126
update: 0.0033840950000012526
update: 0.006826916000001404
update: 0.004534426999999397
update: 0.01933638799999926
update: 0.00343399099999786
update: 0.00869369800000186
update: 0.019853697999998587
update: 0.004462820000000534
update: 0.006669418000001315
update: 0.005347784999997884
update: 0.011312360000001576
update: 0.004236660000000114
```
Isn't it weird that I see 19-22 ms frames next to 5 ms ones in the app that does almost nothing?

**Comment by alice-i-cecile** [comment]
> So these inconsistencies must be coming from OS or GPU drivers? Or is it possible that there is something wrong with bevy?

These are definitely both possible! The last test that you ran without vsync is particularly interesting.

I wouldn't be surprised to see the variation being caused by *other* things your machine is doing in the meanwhile, limiting access for Bevy. But still, tracking down long frames might be a worthwhile question for another issue.
