### ISSUE TITLE
Unbound uniforms don't cause an error

### ISSUE THREAD

**Issue by aristaeus** [bevyengine/bevy#1752]
## Bevy version

1d7196d

## Operating system & version

n/a

## What you did

Take the `shader/array_texture` example, and change the name of `MyArrayTexture` in the shader or the Rust code (but not both!). When you run the example you see a gray screen.

## What you expected to happen

If your shader has a uniform which is not bound correctly, it should fail loudly ([Discord](https://discord.com/channels/691052431525675048/774027865020039209/824515466085138522))

**Comment by YohDeadfall** [comment]
@alice-i-cecile, I will take this one too.

**Comment by YohDeadfall** [comment]
@cart explained me why it doesn't produce any runtime error (see https://github.com/bevyengine/bevy/pull/1015#issuecomment-741491247 for details). It's possible that an asset might be not loaded yet, but referencing it entities have to be drawn. We don't to crash the application in such cases and don't want to pollute output with noise (more heavy game you have with numerous asynchronously loading assets, more notices you get). Therefore, the current behavior is desired, but there's a room for improvements.

My thoughts on it is to have an event to notify the user about a missing resource like `ResourceLost". Perhaps, there should be another event stating that resource was found, i.e. `ResourceFound`. It should be raised only in case if the resource was previously lost.

At the moment, we already have two `debug!` lines producing events using the `tracing` crate:

https://github.com/bevyengine/bevy/blob/f520a341d5737600dbf89015b7729109d67cf041/crates/bevy_render/src/render_graph/nodes/pass_node.rs#L257-L278

Maybe it makes sense to document it, so it would be easier to discover.

**Comment by cart** [comment]
Theres also a pretty good chance that the renderer rework will sort this out. The RenderResources abstraction will likely go away (at least in its current form) in favor of a more explicit binding process.

**Comment by cart** [comment]
Removing the assignment because the render architecture is in flux right now and this will likely change soon.

**Comment by james7132** [comment]
Coming back to this 2 years later, is this issue still relevant? RenderResources has been removed with the renderer rework.

**Comment by cart** [comment]
I think this is safe to close out now.
