### ISSUE TITLE
Better tools for accessing multiple entities in Query iterables

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1758]
## What problem does this solve or what need does it fill?

Within a mutable query iteration, we can't access more than one entity at a time, because of the borrow checker. This is frustrating when trying to do things like write your own collision detection or handling other entity-entity interactions.

## What solution would you like?

Provide a Bevy-native tool (with a simple game example) to allow careful mutable access to more than one entity within a loop.

Here's some [initial discussion](https://discord.com/channels/691052431525675048/742569353878437978/824729007694151750) of what that might look like.

## What alternative(s) have you considered?

Fully solving #1631 would allow us to use iter_tools directly for this sort of thing, but Clone on mutable queries is probably a hard no.

As a workaround, you can record which entities you need to access, then use `query.get()` to pull out their components separately. This is not super obvious and very cumbersome.

## Additional context

First raised on [Discord](https://discord.com/channels/691052431525675048/742569353878437978/824576451688792101).

**Comment by mockersf** [comment]
related to #1763

**Comment by alice-i-cecile** [comment]
Duplicate of #2042.
