### ISSUE TITLE
Frustum culling problem

### ISSUE THREAD

**Issue by TheLeonsver1** [bevyengine/bevy#1760]
## Bevy version
https://github.com/bevyengine/bevy?branch=main#1d7196da4fff00bbc15fe75a04849de915f587d5

## Operating system & version
Windows 10

## What you did
tried to use frustum culling

I spawn a camera like this:
```Rust
let mut orth_camera = OrthographicCameraBundle::new_2d();
    orth_camera.transform.scale = Vec2::new(2.0, 2.0).extend(1.0);
commands
    .spawn()
    .insert_bundle(orth_camera)
    .insert(MainCamera);
```
I spawn the sprites like this: 
```Rust
local_commands.spawn().insert_bundle(HarvestableResouce {
    pickable: PickableBundle::default(),
    sprite: SpriteSheetBundle{
        texture_atlas:game_sprites.atlas_handle.clone(),
        sprite:TextureAtlasSprite { index: map[&texture_names[1].to_string()].index_in_atlas as u32,..Default::default()},
                                        transform:Transform::from_translation(
                                            area_cells[j].as_f32().mul(UNIT_TO_WORLD).extend(0.0)
                                                + Vec2::new(
                                                    thread_rng.gen_range(-15.0..15.0),
                                                    thread_rng.gen_range(-15.0..15.0),
                                                )
                                                .extend(0.0),
                                        ),
                                        ..Default::default()
                                    } 
                                });
```

## What you expected to happen
![expected](https://user-images.githubusercontent.com/19693783/112537345-3b65f000-8db7-11eb-87d6-49a4d4ee6be7.gif)

## What actually happened
![problem](https://user-images.githubusercontent.com/19693783/112537034-df9b6700-8db6-11eb-9c06-3b3c2f8e5c1c.gif)

## Additional information
not really..

**Comment by cart** [comment]
Removing this from the 0.5 milestone in favor of #1761

**Comment by Byteron** [comment]
From Discord:

> the example works, so the math seems correct (at least for normal sprites).
> Though I realize the math should probably use global transforms rather than local transforms. That would break when sprites or camera is child of some other entity.
> 
> Also, given the issue uses texture_atlas I suspect there is something odd going on in bevy_sprite/src/frustum_culling.rs inside of the atlas system. That would be my starting point for looking for issues.

**Comment by rparrett** [comment]
Here is a simple test case involving sprite scaling.

https://github.com/rparrett/bevy-test/tree/culling

With culling disabled, you get a blue bar on the left side rotating into view. Enabled, nothing.

**Comment by alice-i-cecile** [comment]
@cart do you think we should try to tackle this for 0.6? It feels very much in the flavor of "rendering performance and usability optimizations" that the rest of the release is about.

**Comment by cart** [comment]
There is a chance that we'll add a proper frustum culling implementation prior to 0.6, but I don't want to block the release on it. Imo we need to start narrowing focus to get 0.6 out asap instead of expanding it.

**Comment by fuzzbuck** [comment]
> 
> 
> Here is a simple test case involving sprite scaling.
> 
> https://github.com/rparrett/bevy-test/tree/culling
> 
> With culling disabled, you get a blue bar on the left side rotating into view. Enabled, nothing.

submitted PR based on this example ^
https://github.com/bevyengine/bevy/pull/2753

**Comment by nicopap** [comment]
The new 2d renderer doesn't do frustrum culling as far as I can tell. Culling happen in bevy_pbr for light meshes and in bevy_render for things that have an Aabb. Sprites do not have an `Aabb`.

`Mesh2d` doesn't have an Aabb either, so nothing that has to do with 2d rendering is culled.
