### ISSUE TITLE
Bevy example does not build

### ISSUE THREAD

**Issue by martinellison** [bevyengine/bevy#1766]
## Bevy version

latest (0.4.0)

## Operating system & version

Fedora 5.11.8-200.fc33.x86_64 #1 SMP Mon Mar 22 01:35:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## What you did

cloned bevy from github

cargo run --example hello_world 

## What you expected to happen

Example builds and runs

## What actually happened

Build failed

## Additional information

```
error: failed to run custom build command for `libudev-sys v0.1.4`

Caused by:
  process didn't exit successfully: `/home/martin/extgit/bevy/target/debug/build/libudev-sys-ee6a5de081f0ae93/build-script-build` (exit code: 101)
...
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit code: 1\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc\'\nto the PKG_CONFIG_PATH environment variable\nPackage \'libudev\', required by \'virtual:world\', not found\n"', /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/libudev-sys-0.1.4/build.rs:38:41

```

**Comment by MinerSebas** [comment]
When you read your error, you will see that you are missing the `libudev` package

To get all Linux Dependencies look here: https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md#fedora-33

**Comment by martinellison** [comment]
OK that worked thanks.
