### ISSUE TITLE
Weird limits on tuple parameters

### ISSUE THREAD

**Issue by jamadazi** [bevyengine/bevy#1772]
After the new ECSv2 overhaul, the limit for the number of system and query parameters was reduced from the old limit of 16. See here: https://github.com/bevyengine/bevy/issues/1582

Supposedly, the new limit should be 12 (explained by limitations with the trait impls in the Rust standard library).

However, now I am actually investigating it, and it seems like the actual limit for system parameters in current bevy main is 11, not 12. The actual limit for query parameters is 14.

These numbers seem weird? Is this a bug/oversight? If yes, it should probably be fixed before releasing 0.5.

**Comment by alice-i-cecile** [comment]
@cart sanity check on whether this should block 0.5? Also to make sure migration guide advice is correct.

**Comment by jamadazi** [comment]
@cart Will this be addressed before 0.5? It seems like a weird minor oversight?

**Comment by cart** [comment]
Yeah if SystemParams aren't lined up with the Default impls for rust tuples, they should be. WorldQuery impls shouldn't have the same limitations, so we can pick whatever makes sense there.
