### ISSUE TITLE
An easier way to register multiple components' storage at once

### ISSUE THREAD

**Issue by piedoom** [bevyengine/bevy#1794]
## What problem does this solve or what need does it fill?

Registering many components as `SparseSet` at once is not ergonomic, as it requires a lot of repetition.

For my specific context, I am creating a state machine that uses a wrapper with different types to represent the current state. This also means I'd like to register these all as `SparseSet` as they will be added/removed frequently. For the following examples, I have a lot of `CombatState<_>` component types representing a state.

## What solution would you like?

@alice-i-cecile proposed a [`register_bundle`](https://discord.com/channels/691052431525675048/742884593551802431/827015177882959892) name. I'm not exactly sure what that might look like, but I would guess it could look like

```rs
world.register_bundle::<(CombatState<Peaceful>, CombatState<Searching>, CombatState<Chasing>)>(component_descriptor)
```

But I don't think that works 100%...

## What alternative(s) have you considered?

Currently, I am manually registering these components, which is not ideal.

```rs
world
    .register_component(ComponentDescriptor::new::<CombatState<Peaceful>>(
        StorageType::SparseSet,
    ))
    .unwrap();
world
    .register_component(ComponentDescriptor::new::<CombatState<Chasing>>(
        StorageType::SparseSet,
    ))
    .unwrap();
world
    .register_component(ComponentDescriptor::new::<CombatState<Searching>>(
        StorageType::SparseSet,
    ))
    .unwrap();
world
    .register_component(ComponentDescriptor::new::<CombatState<Evading>>(
    // ... etc.
```

---

It's also possible that this request is also related to changing the storage type in general. Will users generally want to access the entire `ComponentDescriptor` struct? In my case, I think something like `.register_component_storage::<TargetComponent>(StorageType::SparseSet)` may be worth investigating, but I haven't given it more thought than that.

Additionally, it's further possible that this exists and I just missed it!

**Comment by mockersf** [comment]
not sure I like the name `register_bundle`, as a bundle of components here doesn't have the same meaning as the bundle of components added to an entity

**Comment by alice-i-cecile** [comment]
Yeah, that's a sensible point. `register_components` would be another obvious choice, and I don't mind the similarity.

**Comment by ahmedcharles** [comment]
There was an attempt at merging this which didn't succeed, so is this still relevant? If so, what alternative solution is desired?

**Comment by alice-i-cecile** [comment]
#2254 should improve the matter dramatically, if I understand correctly :)

**Comment by alice-i-cecile** [comment]
Resolved with the new derive(Component) changes in #2254.
