### ISSUE TITLE
Feature request: Use a fancy color library like Palette.

### ISSUE THREAD

**Issue by anchpop** [bevyengine/bevy#1797]
## What problem does this solve or what need does it fill?

I often find myself doing adding materials like `materials.add(Color::rgb(0.2, 0.3, 0.3).into())`. This seems simple enough... or is it? `Color::rgb(0.2, 0.3, 0.3)` is actually not an unambiguous description of a color, because it doesn't describe the color space. (I suspect Bevy assumes sRGB for the color space, but I haven't looked into the code to check.) One alternative to sRGB is Linear sRG, and the same "color values" can look substantially different in each:

![image](https://user-images.githubusercontent.com/3711047/113356335-12da7a80-9310-11eb-88cf-8d44d7b9867f.png)

The apparent difference is caused by how our eyes work. Increasing the intensity of a light by 10% doesn't always make it look 10% brighter. sRGB has something called "gamma correction", where they stretch out the darks (where our eyes are more sensitive) and compress the lights.  

Many people are familiar with this because they've played with the "linear color" setting in their game engine. Doing lighting calculations on gamma-corrected values leads to physically inaccurate results:

![image](https://user-images.githubusercontent.com/3711047/113356803-de1af300-9310-11eb-8ed9-298ff775bff1.png)

So when I write `Color::rgb(0.2, 0.3, 0.3)`, it's genuinely unclear to me what that represents (the [docs](https://docs.rs/bevy/0.1.2/bevy/prelude/struct.Color.html) don't say either). And ambiguities like that lead to [extremely common bugs](http://www.ericbrasseur.org/gamma.html?i=1) by people who should know better (MS Paint, Photoshop, Firefox) when people do calculations like blending gamma-corrected values. 

## What solution would you like?

There are some libraries designed to make it easy to work with colors, and a good one is [palette](https://github.com/Ogeon/palette). Using the structs provided by palette, you would write `Srgb::new(0.2, 0.3, 0.3)`. It also comes with many useful `impl`s on those structs. From the docs:

```rust
use palette::{FromColor, Saturate, Shade, Srgb, Lch};

let color = Srgb::new(0.8, 0.2, 0.1).into_linear();
let lighter = color.lighten(0.1);
let desaturated = Lch::from_color(color).desaturate(0.5);
```

**Comment by alice-i-cecile** [comment]
See also #1146, #1402.

**Comment by rparrett** [comment]
Also, bevy 0.5 (via #1572) will have
```
Color::Rgba
Color::RgbaLinear
Color::Hsla
```

**Comment by mockersf** [comment]
closing for #1146
