### ISSUE TITLE
Avoid locking the world when encoding a pass

### ISSUE THREAD

**Issue by kvark** [bevyengine/bevy#18]
The compute/render pass lifetime restrictions require the user to have resources alive while the pass is recorded. This introduces a problem when:
  - you have a mutable structure (even a `Vec`), and it's hard to express to Rust that your elements will not be removed from it
  - you want to create elements on the fly

A solution recently discovered is an [Arena](https://docs.rs/typed-arena/2.0.1/typed_arena/). When adding elements to it, it gives you bback the references with the same lifetime as the arena. So you can have `Arc<Something>` (where `Something` contains wgpu resources) that is put into the arena, which is cleared/initialized before the pass recording starts (and cleared after), i.e. this will work:
```rust
let mut arena = TypedArena::new();
let mut pass = encoder.begin_render_pass(...);
let something = Arc::new(Something::new(wgpu_device.create_something())));
let something_ref = arena.alloc(something);
pass.set_vertex_buffer(something_ref.slice(..)); // allowed now!
```

Hopefully, this can help refactoring the engine in a way that doesn't need to lock the world like it's currently done in [wgpuResources](https://github.com/bevyengine/bevy/blob/9a51b3e0fdef00dbef4168650b3dd312968d46c1/crates/bevy_wgpu/src/wgpu_resources.rs#L88).

**Comment by alice-i-cecile** [comment]
This is "pipelined rendering", correct?
