### ISSUE TITLE
Use CI to ensure that features list stays up to date

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1800]
This [list](https://github.com/bevyengine/bevy/blob/15aaa2b29700932867e12d6f477eb4e5ea58703f/docs/cargo_features.md) is very helpful, but seems easy to forget to update when we add new feature flags.

We should use CI to ensure that they stay in sync.

**Comment by DJMcNab** [comment]
Rust-analyzer handles this style of problem by having some code which runs in `cargo test`. This would also be a reasonable solution.
