### ISSUE TITLE
WGPU shader validation warning

### ISSUE THREAD

**Issue by mtsr** [bevyengine/bevy#1812]
## Bevy version

main 3e285d5c0bd49cf1aff11cf3848270bafdd48646

## Operating system & version

Windows 10

## What you did

Run Bevy main with RUST_LOG=WARN

## What you expected to happen

No warnings.

## What actually happened

```
Apr 04 10:53:05.044  WARN Device::create_shader_module: wgpu_core::device: Failed to parse shader SPIR-V code: UnsupportedInstruction(Function, LogicalAnd)
Apr 04 10:53:05.045  WARN Device::create_shader_module: wgpu_core::device: Shader module will not be validated or reflected
```

## Additional information

Removing the `&&` from `crates\bevy_pbr\src\render_graph\pbr_pipeline\pbr.frag:345` fixes this warning.
```glsl
    for (int i = 0; i < int(NumLights.x) && i < MAX_LIGHTS; ++i) {
```

**Comment by jakobhellermann** [comment]
Looks like this was implemented in naga in https://github.com/gfx-rs/naga/commit/f563b5810bac6458809899c5563af7c89140ece5, which isn't released yet.

**Comment by mtsr** [comment]
Thanks for that!

The PR removes an unnecessary comparison, so I think we can still do it.
