### ISSUE TITLE
renderdoc API validation errors on 3d_scene

### ISSUE THREAD

**Issue by mtsr** [bevyengine/bevy#1813]
## Bevy version

main 3e285d5c0bd49cf1aff11cf3848270bafdd48646

## Operating system & version

Windows 10

## What you did

Capture the first 2 frames of `--example 3d_scene` using renderdoc with API validation enabled.

## What you expected to happen

No API validation errors.

## What actually happened

These are the unique errors that occurred:

- [ ] Attemped to call vkGetPhysicalDeviceFeatures2() with an effective API version of 1.0.0 (0x00400000), which is the minimum of version requested in pApplicationInfo (1.2.168 (0x004020a8)) and supported by this physical device (1.0.0 (0x00400000)), but this API was not promoted until version 1.1.0 (0x00401000).
- [ ] Attemped to call vkGetPhysicalDeviceProperties2() with an effective API version of 1.0.0 (0x00400000), which is the minimum of version requested in pApplicationInfo (1.2.168 (0x004020a8)) and supported by this physical device (1.0.0 (0x00400000)), but this API was not promoted until version 1.1.0 (0x00401000).
- [ ] Cannot call vkDestroySemaphore on VkSemaphore 0xf00fbe00000000db[] that is currently in use by a command buffer. The Vulkan spec states: All submitted batches that refer to semaphore must have completed execution (https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/1.2-extensions/vkspec.html#VUID-vkDestroySemaphore-semaphore-01137)
- [x] ~~vkCreateImage(): Format VK_FORMAT_B8G8R8A8_SRGB is not supported for this combination of parameters and VkGetPhysicalDeviceImageFormatProperties returned back VK_ERROR_FORMAT_NOT_SUPPORTED. The Vulkan spec states: Each of the following values (as described in Image Creation Limits) must not be undefined imageCreateMaxMipLevels, imageCreateMaxArrayLayers, imageCreateMaxExtent, and imageCreateSampleCounts (https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/1.2-extensions/vkspec.html#VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251)~~
- [x] ~~vkCreateImage(): usage contains VK_IMAGE_USAGE_STORAGE_BIT and the multisampled storage images feature is not enabled, image samples must be VK_SAMPLE_COUNT_1_BIT The Vulkan spec states: If the multisampled storage images feature is not enabled, and usage contains VK_IMAGE_USAGE_STORAGE_BIT, samples must be VK_SAMPLE_COUNT_1_BIT (https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/1.2-extensions/vkspec.html#VUID-VkImageCreateInfo-usage-00968)~~
- [x] ~~vkCreateImageView(): pCreateInfo->format VK_FORMAT_B8G8R8A8_SRGB with tiling VK_IMAGE_TILING_OPTIMAL does not support usage that includes VK_IMAGE_USAGE_STORAGE_BIT. The Vulkan spec states: If usage contains VK_IMAGE_USAGE_STORAGE_BIT, then the image view's format features must contain VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT (https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/1.2-extensions/vkspec.html#VUID-VkImageViewCreateInfo-usage-02275)~~
- [x] ~~vkCmdBeginRenderPass(): Image view #0 created from an image with flags set as 0x8, but image info #0 used to create the framebuffer had flags set as 0x0 The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView of an image created with a value of VkImageCreateInfo::flags equal to the flags member of the corresponding element of VkFramebufferAttachmentsCreateInfo::pAttachmentImageInfos used to create framebuffer (https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/1.2-extensions/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-03209)~~
- [x] ~~vkCmdBeginRenderPass(): Image view #0 created from an image with usage set as 0x1F, but image info #0 used to create the framebuffer had usage set as 0x10 The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView with an inherited usage equal to the usage member of the corresponding element of VkFramebufferAttachmentsCreateInfo::pAttachmentImageInfos used to create framebuffer (https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/1.2-extensions/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-04627)~~

## Additional information

It's quite possible not all of these originate with Bevy itself. But I think it's worth checking them.

I can't convey all the relevant info here, because it refers back to specific Render Pass #'s etc in renderdocs capture. To get that info it's probably best to run renderdoc with API validation yourself.

**Comment by bjorn3** [comment]
Can you re-open this on https://github.com/gfx-rs/wgpu? Wgpu is to blame for some of there errors I think and all other errors should result in wgpu unconditionally giving an error or even panicking. Wgpu should be impossible to mis-use in ways that could be UB or could otherwise cause problems as it is meant to be used as backed for the WebGPU implementation in Firefox and as such it exposed to untrusted users.

**Comment by mtsr** [comment]
vkCreateImage() errors are caused by renderdoc: https://github.com/baldurk/renderdoc/issues/582#issuecomment-295180765

**Comment by mtsr** [comment]
Closing this, because WGPU is requestion the gfx vulkan backend with validation layers and there are no errors logged there.
