### ISSUE TITLE
Make a "Are We Bevy Yet" website

### ISSUE THREAD

**Issue by ValorZard** [bevyengine/bevy#1818]
## What problem does this solve or what need does it fill?

This would be a nice easy to use tracker for the big game engine areas assets, ui, editor, rendering stuff.

## What solution would you like?

We could buy the website arewebevyyet.org and make that similar to arewegameyet.rs

## What alternative(s) have you considered?

I guess this could also just be a section on the bevy website.

## Additional context

Some examples: https://arewegameyet.rs/
https://www.arewewebyet.org/

**Comment by alice-i-cecile** [comment]
I can definitely see the value in tracking this sort of thing in a more transparent way. We get a good chunk of users asking "has X happened yet / how good is Y / when should we expect to see Z", and there's not a great central place to point them.

How should this relate to the [project boards](https://github.com/bevyengine/bevy/projects/1) and focus area issues? Can this be supplanted by improving the project board?

**Comment by ValorZard** [comment]
The main reason I thought this was a good issue is that not every wants to dig into a github page to learn stuff about a project. Most people who get into bevy will probably look at its website, not at the github issues/discussions.

**Comment by alice-i-cecile** [comment]
> The main reason I thought this was a good issue is that not every wants to dig into a github page to learn stuff about a project. Most people who get into bevy will probably look at its website, not at the github issues/discussions.

I definitely agree with that. IMO whatever solution we end up on should be linked prominently from the Bevy website.

**Comment by mockersf** [comment]
Project board and issues tends to be updated with development, this should be updated for released versions.

I think this should be opened on https://github.com/bevyengine/bevy-website

**Comment by ValorZard** [comment]
did it over here: https://github.com/bevyengine/bevy-website/issues/114
