### ISSUE TITLE
Warn on startup when Bevy itself is built without optimizations

### ISSUE THREAD

**Issue by bjorn3** [bevyengine/bevy#1827]
## What problem does this solve or what need does it fill?

Without optimizations Bevy is slow. Not everyone realizes that they can use `--release` to drastically improve performance. This is a frequent topic on the Discord.

## What solution would you like?

See title. This can be implemented by adding a build script to a crate like `bevy_app` that reads the `OPT_LEVEL` env var. And when the value is 0 causes a startup system to be enabled that prints a warning suggesting to pass `--release`.

## What alternative(s) have you considered?

Somehow teach Cargo to always optimize Bevy and it's dependencies.

## Additional context

https://discord.com/channels/691052431525675048/742884593551802431/828710614721363969

**Comment by cart** [comment]
This is a _really_ good idea!

**Comment by mockersf** [comment]
I thing logging a message under [`#[cfg(debug_assertions)]`](https://doc.rust-lang.org/cargo/reference/profiles.html#debug-assertions) rather than a build script would be nicer

**Comment by bjorn3** [comment]
You can enable debug assertions and optimizations at the same time. Using the `env!` macro doesn't work here as `OPT_LEVEL` is only set for build scripts. Not when building with rustc.

**Comment by mockersf** [comment]
I would like to avoid a build script as they often make compilation longer / harder to cache...

**Comment by bjorn3** [comment]
Using `println!("cargo:rerun-if-changed=build.rs");` should ensure that the build script doesn't run on any changes to the crate source by switching from the legacy "any source change => re-run" to "specified source change => re-run". The build script is very simple so it doesn't require any dependencies. This allows it to run at the start of the compilation at the same time as other crates without dependencies.

**Comment by alice-i-cecile** [comment]
Closing per #7698. The complexity here is too high for the benefits.
