### ISSUE TITLE
 Example "window" compilation error on Qubes OS 

### ISSUE THREAD

**Issue by w4i6d** [bevyengine/bevy#1832]
## Bevy version
commit/3e285d5c0bd49cf1aff11cf3848270bafdd48646

## Operating system & version

Qubes OS R4.0 with template Debian 11

## What you did

A compilation error occurred when trying to compile the "ui" example on Qubes OS (Xen virtualization based) on the Debian 11 template. It probably appeared because Qubes OS does not provide information about the existence of a physical monitor through virtualization.

1. Install Qubes OS on home PC
2. Upgrade default template Debian 10 to Debian 11
3. Try compile Bevy example "ui"

# Logs
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
thread 'main' panicked at 'Error in Device::create_swap_chain: surface does not support the adapter's queue family', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:129:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Apr 06 09:30:48.696 ERROR gpu_descriptor::allocator: `DescriptorAllocator` is dropped while some descriptor sets were not deallocated
Apr 06 09:30:48.697 ERROR gpu_alloc::block: Memory block wasn't deallocated
Apr 06 09:30:48.697 ERROR gpu_alloc::block: Memory block wasn't deallocated
Segmentation fault

# Source:
https://pastebin.com/VSaTmkjV

## Additional information

It is understandable that the Bevy engine has problems with Qubes OS as it is a very specific home system that relies on virtualization for security reasons.

**Comment by bjorn3** [comment]
QubesOS doesn't allow VM's to use the GPU unless you setup GPU passthrough for the VM. This requires a separate GPU for this VM. Without GPU passthrough the only options are to use virtio-gpu (currently no vulkan support in mesa: https://www.phoronix.com/scan.php?page=news_item&px=VirtIO-GPU-Vulkan-Mesa-RFC) or to use software rendering. For vulkan this requires lavapipe, which is still experimental.

> WARNING: lavapipe is not a conformant vulkan implementation, testing use only.

The actual problem here is

> vulkan: No DRI3 support detected - required for presentation
> Note: you can probably enable DRI3 in your Xorg config

Which makes it impossible to actually show something on the screen, hence the

> thread 'main' panicked at 'Error in Device::create_swap_chain: surface does not support the adapter's queue family', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:129:9

I am not sure if DRI3 can be enabled at all without either a real or virtio gpu being used.

**Comment by w4i6d** [comment]
@bjorn3 
Of course, I know that Qubes OS does not allow easy access to the GPU due to the problem with secure virtualization of this object, but then how to force software rendering? It would be nice to add detection to Bevy in such a case that would atumatically force software rendering.

**Comment by bjorn3** [comment]
Mesa tried to use lavapipe for software rendering automatically. It is currently experimental. The problem you have may be one of the reasons.

**Comment by mockersf** [comment]
Bevy works with lavapipe, it is used in CI. Not sure we can do much more for Qubes OS, please reopen if you have an actionable issue
