### ISSUE TITLE
Confusing error message if using `ResMut` with a non-`Component` type

### ISSUE THREAD

**Issue by concave-sphere** [bevyengine/bevy#1838]
## Bevy version

0.5.0

## Operating system & version

Debian GNU/Linux "buster'

## What you did

Wrote a function accepting `ResMut<T>` without declaring `T: Component`, such as:

```
fn demonstration_broken_system<T>(r: ResMut<T>) {
    &*r;
}
```

## What you expected to happen

I should have gotten an error like

```
  `T` cannot be sent between threads safely
```

## What actually happened

I got the error

```
error[E0614]: type `bevy::prelude::ResMut<'_, T>` cannot be dereferenced
  --> src/lib.rs:13:6
   |
13 |     &*r;
   |      ^^
```

and wasn't able to track the problem down until I invoked `std::ops::Deref::deref` on the offending `ResMut`.

## Additional information

Sample code: [test.tar.gz](https://github.com/bevyengine/bevy/files/6268127/test.tar.gz)

**Comment by bjorn3** [comment]
This can be fixed by adding a `T: Component` bound to the definition of the `ResMut` struct.
