### ISSUE TITLE
Infinite loop if states are inserted as Resources

### ISSUE THREAD

**Issue by concave-sphere** [bevyengine/bevy#1847]
## Bevy version

0.5

## Operating system & version

Debian GNU/Linux "buster"

## What you did

Ported a Bevy 0.4 program that had a modal state-driven UI.  The current program state is represented as an enum.  I didn't realize I needed to change `.insert_resource(State::new(MyState::Initial))` to `.add_state(MyState::Initial)`.

## What you expected to happen

One of:

 1. The program launches as normal.
 2. The program runs but the state can't be changed.
 3. The program runs but nothing connected to a state works.
 4. The program panics at startup.

## What actually happened

I get a blank screen.  `gdb` shows all threads apparently idle.  Hacking up Bevy to print messages when it starts and finishes running systems produces this output:

```
done running: "&bevy_ecs::schedule::state::State<gridded_demo::GridInteractionMode>::on_update::{{closure}}"
running: "&bevy_ecs::schedule::state::should_run_adapter<gridded_demo::GridInteractionMode>"
done running: "&bevy_ecs::schedule::state::should_run_adapter<gridded_demo::GridInteractionMode>"
running: "&bevy_ecs::schedule::state::State<gridded_demo::GridMode>::on_exit::{{closure}}"
done running: "&bevy_ecs::schedule::state::State<gridded_demo::GridMode>::on_exit::{{closure}}"
running: "&bevy_ecs::schedule::state::should_run_adapter<gridded_demo::GridMode>"
done running: "&bevy_ecs::schedule::state::should_run_adapter<gridded_demo::GridMode>"
running: "&bevy_ecs::schedule::state::State<gridded_demo::GridInteractionMode>::on_update::{{closure}}"
done running: "&bevy_ecs::schedule::state::State<gridded_demo::GridInteractionMode>::on_update::{{closure}}"
```

It looks like Bevy has gone into some kind of infinite loop checking if the state is up to date.

If I comment out all state-dependent systems, my screen is still blank (since the program does nothing) but my debugging output changes to show that other systems are running, for instance:

```
running: "&bevy_app::event::Events<bevy_input::touch::TouchInput>::update_system"
done running: "&bevy_app::event::Events<bevy_window::event::CloseWindow>::update_system"
done running: "&bevy_app::event::Events<bevy_window::event::WindowResized>::update_system"
done running: "&bevy_app::event::Events<bevy_input::touch::TouchInput>::update_system"
running: "&bevy_app::event::Events<bevy_input::mouse::MouseMotion>::update_system"
running: "&bevy_app::event::Events<bevy_app::app::AppExit>::update_system"
running: "&bevy_app::event::Events<bevy_input::mouse::MouseWheel>::update_system"
done running: "&bevy_app::event::Events<bevy_input::mouse::MouseMotion>::update_system"
done running: "&bevy_app::event::Events<bevy_input::mouse::MouseWheel>::update_system"
```

Changing `insert_resource` to `add_state` makes everything work (or at least fixes this problem :smile:)

**Comment by alice-i-cecile** [comment]
Could you make an issue or PR on [bevy-website](https://github.com/bevyengine/bevy-website) to add this to the migration guide? :) This mostly seems like a one-time pain, rather than a true bug. Might be wise to panic still though.

**Comment by concave-sphere** [comment]
PR created.

I realize this is "pilot error", but I think it's important for APIs to fail gracefully when users screw up, whenever possible.  That doesn't necessarily mean "hide the problem", but at least failing loudly with a message that points at the issue is really useful, or breaking just the part of the system that involves that API (e.g, not running any systems connected to the State and maybe loudly complaining about it on the console).

**Comment by alice-i-cecile** [comment]
Thanks for the PR!

> I realize this is "pilot error", but I think it's important for APIs to fail gracefully when users screw up, whenever possible. That doesn't necessarily mean "hide the problem", but at least failing loudly with a message that points at the issue is really useful, or breaking just the part of the system that involves that API (e.g, not running any systems connected to the State and maybe loudly complaining about it on the console).

I agree with this: I think this deserves an appropriate panic, at least in debug mode. 
The `user-error` tag is unfortunately hostile, sorry if it came across poorly.

**Comment by james7132** [comment]
Checking in, with stageless merged, is this still a common footgun? We can still insert states as resources, but the run conditions should act in predictable ways now.

**Comment by alice-i-cecile** [comment]
Yep, this is fixed.
