### ISSUE TITLE
Add system sets for startup stages

### ISSUE THREAD

**Issue by TehPers** [bevyengine/bevy#1852]
## What problem does this solve or what need does it fill?

Currently, `AppBuilder` has functions for adding system sets, optionally to stages. However, there are no functions for easily adding system sets as startup systems. One way to add system sets for startup stages is to use `AppBuilder::stage` like how the other startup system functions do:

```rs
fn build(&self, app: &mut AppBuilder) {
    app.stage(CoreStage::Startup, |schedule: &mut Schedule| {
        schedule.add_system_set_to_stage(StartupStage::Startup, SystemSet::new())
    });
}
```

This is less intuitive than the other functions for adding system sets (`AppBuilder::add_system_set` and `AppBuilder::add_system_set_to_stage`).

## What solution would you like?

Two functions added:

- `AppBuilder::add_startup_system_set` - startup system equivalent of `AppBuilder::add_system_set`
- `AppBuilder::add_startup_system_set_to_stage` - startup system equivalent of `AppBuilder::add_system_set_to_stage`

## What alternative(s) have you considered?

Using `AppBuilder::stage`.

**Comment by alice-i-cecile** [comment]
Long-term, this is a sign of the issues with the current API design of system building. It's not composable, leading to this combinatorial explosion of required methods that are annoying to remember to use and implement.

For now though, I think just adding the missing methods is a good stop-gap.

**Comment by Sheepyhead** [comment]
Correct me if I'm wrong, but `AppBuilder::add_startup_system_set_to_stage` doesn't make much sense as a startup system is a system added to the StartupStage::Startup stage, can you meaningfully add a startup system to another stage than startup?

**Comment by alice-i-cecile** [comment]
Yes: you can have multiple startup stages. The idea would be to create a parallel API to [add_startup_system_to_stage](https://docs.rs/bevy/0.5.0/bevy/app/struct.AppBuilder.html#method.add_startup_system_to_stage). 

That said, taking a second look, it may be more correct to simply remove `add_startup_system_to_stage`, and then leave a note on both `add_system_set` and `add_system_to_stage` that you can add to any stage, including `Startup`, with the stage controlling the startup-like behavior.

**Comment by TehPers** [comment]
> That said, taking a second look, it may be more correct to simply remove `add_startup_system_to_stage`, and then leave a note on both `add_system_set` and `add_system_to_stage` that you can add to any stage, including `Startup`, with the stage controlling the startup-like behavior.

Would it make sense at that point to move all the startup stages outside of their own scheduler? In that case, it'd be the same as adding any other system to a stage:

```rust
app.add_system_to_stage(CoreStage::PreStartup, my_system.system());
```

It seems a little unusual to me that the startup systems have their own scheduler, and I'm not really sure why that's the case. Moving those stages to the normal scheduler seems like it could unify the API a little bit more, removing the need for `add_startup_*` functions.

**Comment by alice-i-cecile** [comment]
> Would it make sense at that point to move all the startup stages outside of their own scheduler? In that case, it'd be the same as adding any other system to a stage:

It would be very nice if we can do this; although @Ratysz has some Grand Plans for reducing the prominence of stages (#1375) that this might conflict with. I would try doing so if it's easy, but skip it if it's not.

> It seems a little unusual to me that the startup systems have their own scheduler, and I'm not really sure why that's the case. Moving those stages to the normal scheduler seems like it could unify the API a little bit more, removing the need for add_startup_* functions.

I wouldn't be surprised if it's to ensure that startup systems run exactly once, but you should verify.

**Comment by TehPers** [comment]
> It would be very nice if we can do this; although @Ratysz has some Grand Plans for reducing the prominence of stages (#1375) that this might conflict with. I would try doing so if it's easy, but skip it if it's not.

If stages are being removed soon, then it might be worth leaving things as is. In that case, it might be a good idea to close this issue if that's the planned direction.

> I wouldn't be surprised if it's to ensure that startup systems run exactly once, but you should verify.

As far as I can tell, `CoreStage::Startup` is a schedule stage with the `RunOnce` run criteria on it. I actually create my own startup stages just by using `SystemStage::parallel()` and adding the `RunOnce` run criteria to them:

```rust
app.add_stage_after(
    CoreStage::Startup,
    GameStage::PreStartup,
    SystemStage::parallel().with_run_criteria(RunOnce::default()),
)
// ...
```

This lets me add system sets to the startup stages the same way I would with other stages:

```rust
.add_system_set_to_stage(
    GameStage::Startup,
    SystemSet::new()
        .after(MyLabel1)
        .label(MyLabel2)
        .with_system(my_system1.system())
        .with_system(my_system2.system()),
)
```

**Comment by kerkmann** [comment]
It's already in bevy, so it can be closed. :)

See [add_startup_system_set_to_stage](https://github.com/bevyengine/bevy/blob/main/crates/bevy_app/src/app.rs#L543-L577) and [add_startup_system_set](https://github.com/bevyengine/bevy/blob/main/crates/bevy_app/src/app.rs#L491-L513)
