### ISSUE TITLE
Add marker components for different camera types

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1854]
## What problem does this solve or what need does it fill?

Selecting particular camera types is frustrating, relying on checking the name field within a system.

## What solution would you like?

Add a simple marker components for  `UiCamera` and `GameplayCamera`.

Various rendering systems should use this mechanism, instead of the camera's name.

## What alternative(s) have you considered?

Users can add their own marker components manually.

Only tag `UiCamera` and use `Without<UiCamera>`.

Add a unique marker component for each of `2dCamera`, `3dCamera` and so on. This is less clear, and it seems extremely rare that you will have more than one different type of gameplay camera at once.

## Additional context

Example of this problem in [#help](https://discord.com/channels/691052431525675048/742884593551802431/829574545040080916)

**Comment by alice-i-cecile** [comment]
As part of the PR to fix this issue, it might be nice to demonstrate how to use it in a small example (or as part of one of the games). Combine it with `query.single_mut()` to show idiomatic usage.

**Comment by alice-i-cecile** [comment]
While we're fixing this, we should probably just rework how Bevy's internal systems manage cameras as well.

It's probably worth removing the name field entirely, to avoid exposing / using an inferior API. Now that sparse set storage exists, there's no reason not to use marker components for all of the "name X" use cases.

**Comment by alice-i-cecile** [comment]
This resulted in a confusing problem for a [user trying to make their own camera variant](https://discordapp.com/channels/691052431525675048/742884593551802431/830117968603119665).

**Comment by alice-i-cecile** [comment]
#3412 will significantly impact how this is handled and add complexity, so this should wait until after it's merged.

**Comment by james7132** [comment]
Is this still relevant after #4745? `UiCamera` and it's bundle are no longer a thing.
