### ISSUE TITLE
Panic/segfault with opt-level=3

### ISSUE THREAD

**Issue by inodentry** [bevyengine/bevy#1858]
Bevy version: can reproduce on both 0.5.0 and commit bc13d11c
3rd-party plugins used: `bevy_tilemap` 0.4.0 (latest)
Operating System and Hardware: Linux 5.11.10 (gentoo) + AMDGPU RADV vulkan driver on AMD Vega 64

When I build my game with `opt-level=3`, I get a panic+segfault related to rendering.

`opt-level=1` works fine.

No idea if the problem is in Bevy, wgpu, or `bevy_tilemap`, but I doubt `bevy_tilemap` touches stuff low-level enough to cause this.

The problem is triggered by compiler optimizations. If I add `opt-level=3` to my debug builds, the problem also occurs, not just in release builds. Hence, it is not caused by the lack of debug assertions or some debug-only logic.

I smell UB.

Output:

[paste.txt](https://github.com/bevyengine/bevy/files/6282334/paste.txt)

**Comment by james7132** [comment]
@inodentry: Is this still reproducible with the 0.6 render rework? If not, please close this issue.

**Comment by inodentry** [comment]
I don't know and cannot test. I don't have that project anymore. This issue is not specific enough to be actionable. Closing.
