### ISSUE TITLE
File release 1.0

### ISSUE THREAD

**Issue by mpeeps27** [bevyengine/bevy#1860]
## What problem does this solve or what need does it fill?

A description of why this particular feature should be added.

## What solution would you like?

The solution you propose for the problem presented.

## What alternative(s) have you considered?

Other solutions to solve and/or work around the problem presented.

## Additional context

Any other information you would like to add such as related previous work,
screenshots, benchmarks, etc.

**Comment by mpeeps27** [comment]
First release of 1.0

**Comment by alice-i-cecile** [comment]
I appreciate the sentiment :) Closing as invalid though <3
