### ISSUE TITLE
Memory leak on AMD CPUs

### ISSUE THREAD

**Issue by PandaCommando** [bevyengine/bevy#1862]
## Bevy version
0.5

OS: Windows 10
CPU: AMD Ryzen 7 4800HS with Radeon Graphics 2.90 GHz
GPU: RTX 2060 with Max-Q Design

Any bevy project with default plugins has a memory leak of about 200mb/s I think it might also be influenced by framerate.

## Additional information
I ran the same executable on two computers with Intel chips and it runs perfectly.

**Comment by mockersf** [comment]
maybe related to #1488 

Could you check with [wgpu-rs](https://github.com/gfx-rs/wgpu-rs) examples? [See this comment](https://github.com/bevyengine/bevy/issues/1488#issuecomment-782821449) about an example to run and how to change the backend used between dx12 and vulkan

**Comment by PandaCommando** [comment]
I tried setting "BEVY_WGPU_BACKEND=vulkan" and I get:
"thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!'"

This is because there is a known bug with AMD integrated graphics not allowing Vulkan to initialize. [https://github.com/KhronosGroup/Vulkan-Loader/issues/552](url)

setting "DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1" fixed it for me

However, I don't know if this is related to the DX12 memory leak.

**Comment by adsick** [comment]
hello, guys, I came here from #1804 (I am using Ryzen 3500U with its Vega 8 on Windows 10) and I also have a memory leak-like behavior except for it is less 'tragic' (but leak is leak) although setting rendering backend to vulkan actually helps (but who wants to use env variables)

**Comment by mockersf** [comment]
this should have been fixed after a dependency update, could you check after a `cargo update`?

**Comment by alice-i-cecile** [comment]
Closed following #1804. Feel free to reopen if you still have an issue.
