### ISSUE TITLE
Deriving `Bundle` fails for nested bundles with generic parameters

### ISSUE THREAD

**Issue by concave-sphere** [bevyengine/bevy#1873]
## Bevy version

0.5

## Operating system & version

Debian GNU/Linux "buster"

## What you did

Tried to derive `Bundle` for a struct containing a type with generic parameters:

```
#[derive(Bundle)]
struct Bar<T: bevy::ecs::component::Component> {
    f: T,
}

#[derive(Bundle)]
struct Foo {
    #[bundle]
    bar: Bar<String>,
}
```

## What you expected to happen

I should get a `Bundle` implementation for `Foo` that includes `Bar` as a sub-bundle.

## What actually happened

The code produced by the macro fails to compile:

```
error: comparison operators cannot be chained
  --> src/main.rs:13:13
   |
13 |     bar: Bar<String>,
   |             ^      ^
   |
help: use `::<...>` instead of `<...>` to specify type or const arguments
   |
13 |     bar: Bar::<String>,
   |             ^^

error: proc-macro derive produced unparseable tokens
  --> src/main.rs:10:10
   |
10 | #[derive(Bundle)]
   |          ^^^^^^

error: aborting due to 2 previous errors
```

## Additional information

Using a type alias is a workaround:

```
#[derive(Bundle)]
struct Bar<T: bevy::ecs::component::Component> {
    f: T,
}

type BarString = Bar<String>;

#[derive(Bundle)]
struct Foo {
    #[bundle]
    bar: BarString,
}
```

(edited to remove an unrelated bug from my example code and add the workaround)

**Comment by YohDeadfall** [comment]
While another issue awaits some clarification on change from Carter, I can take this one.
