### ISSUE TITLE
View all resources with World.resources()

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1891]
## What problem does this solve or what need does it fill?

It would be useful to be able to see which Resources exist in the world, for debugging, discovery and editor purposes.

## What solution would you like?

Expose a `.resources()` method on `World`.

## What alternative(s) have you considered?

This may exist and I missed it. In that case, organization or documentation needs work instead.

## Additional context

~~This appears to have been lost in #1525; this functionality exists in [0.4](https://docs.rs/bevy/0.4.0/bevy/app/struct.App.html), but not in [0.5](https://docs.rs/bevy/0.5.0/bevy/app/struct.App.html).~~ Edit: I was mistaken about behavior in 0.4; this is new functionality.

Resources are now a part of `World`, but it doesn't seem to be accessible from [that](https://docs.rs/bevy/0.5.0/bevy/ecs/world/struct.World.html).

**Comment by mockersf** [comment]
there is `get_resource` https://docs.rs/bevy/0.5.0/bevy/ecs/world/struct.World.html#method.get_resource (and `get_resource_mut`)

**Comment by Sheepyhead** [comment]
It's not really obvious what this .resources() method should actually return, as a resource can be any type. Clarification is needed on what the returned values of this function needs to be used for, and what data should be returned

**Comment by concave-sphere** [comment]
It might be worth having a set of debug specific APIs that return types that are easy to dump to stdout or logs.  e.g, `get_all_resource_names(&self) -> String`.  I've also had cause to implement my own code to get a `String` showing which components are attached to an `Entity`.

**Comment by Frizi** [comment]
I don't think there is any actual regression. There never was a way to access a list of resources. As far as I can tell not even a Debug impl. All methods on the [`Resources`](https://docs.rs/bevy/0.4.0/bevy/ecs/struct.Resources.html) struct were generic over a resource type, thus serving the same purpose as existing World. So, maybe we want something like that, but I would argue it should be designed as targeted for specific use case (probably editor).

**Comment by alice-i-cecile** [comment]
Closely related to #1130.

**Comment by alice-i-cecile** [comment]
There's some nice user-facing example code that does approximately this over on https://github.com/bevy-cheatbook/bevy-cheatbook/pull/61 :)

**Comment by alice-i-cecile** [comment]
Duplicate of #3007, which has more progress.
