### ISSUE TITLE
`Commands` can't insert components to spawned entities if injected via a `SystemParam`

### ISSUE THREAD

**Issue by concave-sphere** [bevyengine/bevy#1896]
## Bevy version

0.5

## Operating system & version

Debian GNU/Linux "buster"

## What you did

I created a `SystemParam` struct that embeds a `Commands`, and used it to spawn entities (full code archive with `main` at the end of the post):

```rust
fn create_entities_with_tags(commands: Commands) {
    ParamThatInserts { commands }.commit("normal insert");
}

#[derive(SystemParam)]
pub struct ParamThatInserts<'a> {
    commands: Commands<'a>,
}
impl<'a> ParamThatInserts<'a> {
    fn commit(&mut self, name: &str) {
        self.commands.spawn().insert(Tag(name.into()));
    }
}

fn create_entities_with_param(mut param: ParamThatInserts) {
    param.commit("insert via param");
}

fn list_entities_with_tags(query: Query<(Entity, Option<&Tag>)>) {
    for (entity, tag) in query.iter() {
        println!("tagged entity: {:?} => {:?}", entity, tag);
    }
}
```

## What you expected to happen

The program should print something like:

```
tagged entity: 1v0 => Some(Tag("insert via param"))
```

Or if this isn't a "proper" use of `SystemParam`, I should get an error of some sort telling me that I misused the API.

## What actually happened

Entities get spawned, but they only have components when Commands is injected directly into the system (not via a param):

```
tagged entity: 1v0 => None
tagged entity: 0v0 => Some(Tag("normal insert"))
```

## Additional information

Full code: 
[test.tar.gz](https://github.com/bevyengine/bevy/files/6297635/test.tar.gz)

**Comment by adsick** [comment]
suggestion: use ```rust 
for markdown syntax highlighting 
```rust
println!("nice text here");
let a = 1 + 2;
```

**Comment by DJMcNab** [comment]
This is a known bug

*Someone* forgot to add the `appply` method on the derived SystemParam (*cough* @cart *cough*)

Last I knew of this bug, someone on discord expressed interest in fixing it, although I don't think it came through
