### ISSUE TITLE
Confusing labeling problems

### ISSUE THREAD

**Issue by TheLeonsver1** [bevyengine/bevy#1912]
## What problem does this solve or what need does it fill?

The labeling process currently can create confusing issues,
for example for this code:
```
system_set

.with_system(init_tileset.system().label(SystemLabels::InitTileset))

.with_system(init_tile.system().label(SystemLabels::InitTile).after(SystemLabels::InitTileset))

.with_system(update_textures_for_changed_tile_data.system().label(SystemLabels::UpdateTexturesForVisual).after(SystemLabels::InitTile))        

.with_system(change_state_after_creating_new_tileset.system()).label(SystemLabels::ChangeStateToEditing).after(SystemLabels::UpdateTexturesForVisual)
```
where you confuse putting a label on a `System`, and put it accidentally on the `SystemSet`
you'll get the panic
```
thread 'main' panicked at 'Found a dependency cycle in parallel systems:
 - &sprite_editor::data::systems::init_tile
    wants to be after (because of labels: {InitTileset})
 - &sprite_editor::data::systems::init_tileset
    wants to be after (because of labels: {UpdateTexturesForVisual})
 - &sprite_editor::data::systems::update_textures_for_changed_tile_data
    wants to be after (because of labels: {InitTile})
 - 3
```
you'll maybe notice something weird on this part
```
- &sprite_editor::data::systems::init_tileset
    wants to be after (because of labels: {UpdateTexturesForVisual})
```
but the issue is not obvious enough...

## What solution would you like?
There are two options, 
either giving everything that could get a label its own labeling function, for example,
`label_system()` and `label_system_set()`
this solution would probably require an RFC since it's a breaking change probably

Or, having better panics that tell what's going wrong in a less ambiguous manner...

I think the first solution would make things more readable, but then again, it's more boilerplate I guess...
## Additional context
none..

**Comment by Ratysz** [comment]
`rustfmt` disambiguates this for all but most contrivedly concise cases.

**Comment by TheLeonsver1** [comment]
hmm i guess it does, just tried it, maybe suggest doing that in the panic?
