### ISSUE TITLE
ECS Guide exclusive system (thread local system) is not useful because of dead code

### ISSUE THREAD

**Issue by Fedcomp** [bevyengine/bevy#1917]
## How can Bevy's documentation be improved?

ECS Guide exclusive system (thread local system) is not useful because of dead code:
https://github.com/bevyengine/bevy/blob/v0.5.0/examples/ecs/ecs_guide.rs#L203
It has example of thread local system, but no add_system call in app builder.

It was probably 2 times i had to look in examples to find what was the syntax for thread local system (when it was bevy 0.3/4). Now when they are renamed to exclusive access i had to look once again to see new registration syntax. I found it in scenes.
I also found no usage of exclusive/thread local system in any example in `examples/ecs`.

I suggest to either make it actual part of ecs guide or extract it into additional example in ecs folder.

**Comment by alice-i-cecile** [comment]
This should also not be called a "thread-local system": these have been renamed to "exclusive systems".
