### ISSUE TITLE
RemovedComponents is missing documentation

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1920]
## How can Bevy's documentation be improved?

[RemovedComponents](https://docs.rs/bevy/0.5.0/bevy/ecs/system/struct.RemovedComponents.html) is missing documentation.

We should provide reference docs on what it does, and a quick example in `examples/ecs` demonstrating how you might use it in practice.

As I understand it, what this does is return all components of type `T` that were removed since the start of the frame. Using this in concert with a more complex query would be a great fit for the full example.

**Comment by MJohnson459** [comment]
While I was searching for how `RemovedComponents` works, I found an example already exists:
https://github.com/bevyengine/bevy/blob/81b53d15d4e038261182b8d7c8f65f9a3641fd2d/examples/ecs/removal_detection.rs

Also this is a more complex example which might be useful for others:
https://github.com/dimforge/bevy_rapier/blob/6de85b0a7949d91aa32b78be0d51b2d08bbd13af/src/physics/systems.rs#L382
