### ISSUE TITLE
Add frame count to logging

### ISSUE THREAD

**Issue by aclysma** [bevyengine/bevy#193]
Sometimes frame count can be a useful debug tool. It can help line information up from other sources:
 * Logs
 * Screenshots/Video
 * External tools like renderdoc and profilers

Other helpful fields:
 * Thread ID
 * Posix time (for networking)
 * Millisecond resolution

I guess logging is kind of up to the end-user's application to setup so potentially the outcome of this bug is to verify that the necessary hooks to get this kind of information is available and to document how to do it. Possibly also add it to examples.

**Comment by Xavientois** [comment]
Would this make sense to create a plugin for? Like, the plugin would count frames (along with those other fields) and be accessible as a resource?

**Comment by JayHelton** [comment]
Is this still available to work on?

If so, @cart are you open to giving advice on where to start for hacking away at this? I do think a plugin sounds like a good idea

**Comment by cart** [comment]
I think it makes sense to add frame count as another diagnostic. We can probably just add it to the current FrameTimePlugin for simplicity.

**Comment by cart** [comment]
Definitely feel free to work on this!

**Comment by JayHelton** [comment]
Awesome! Ill be looking to pick this up this coming week.

**Comment by mkhan45** [comment]
Should this issue be closed?

**Comment by cart** [comment]
Yup! Thanks for helping us keep the issue tracker clean :)
