### ISSUE TITLE
Red Colour for all PBR pipeline materials.

### ISSUE THREAD

**Issue by flmng0** [bevyengine/bevy#1930]
## Bevy version

Bevy 0.5.0 via crates.io

## Operating system & version

Windows 10 19041.867

## What you did

This bug only effects the PBR pipeline by the looks of it. Sprites and 2D shapes are unaffected.

To re-create the bug, all I need to do is to create a new bevy app with any 3D mesh in the scene.
e.g:

```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup.system())
        .run();
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    commands.spawn_bundle(PbrBundle {
        mesh: meshes.add(Mesh::from(shape::Cube { size: 1.0 })),
        material: materials.add(Color::rgb(0.0, 0.3, 0.8).into()),
        ..Default::default()
    });
    
    commands.spawn_bundle(PerspectiveCameraBundle {
        transform: Transform::from_xyz(-3.0, 3.0, 5.0).looking_at(Vec3::ZERO, Vec3::Y),
        ..Default::default()
    });
}
```

## What you expected to happen

I would expect an output of a green/blue cube on the screen.

## What actually happened

I'm unable to post a screenshot, but I get a bright red cube outputted to the window instead.
The specific colour is Hex B3071E

Importantly, when a light is added to the scene, the effect completely changes.
I tested this by mapping the Cursor's X and Y position to the material's green and blue colour value respectively. 

With lighting, it is a little easier to see that the effect is as if there is a colour mask on the material, where the red channel is favoured.

## Additional information

There are no associated warnings from bevy, and changing the material colour when there is no lighting doesn't change the output at all (or at least, it is un-noticeable).

I will attach a screenshot as soon as I can.

I tried running this for 0.4, and got a normal looking output instead. 

The issue is also present in all of the Bevy 0.5 official examples.

**Comment by mockersf** [comment]
This is what the code above looks like on my mac:
![red](https://user-images.githubusercontent.com/8672791/114831176-5da6c880-9dcd-11eb-8c87-14e057c7feff.png)

Is this what you're seeing?

**Comment by flmng0** [comment]
@mockersf No that's not what I'm seeing.

[This link](https://imgur.com/a/Kb65DQA) is what is output when I run exactly the example code I posted.

**Comment by CptPotato** [comment]
I'm getting the same results as @mockersf but on Windows 10.

**Comment by mockersf** [comment]
maybe related to #1941, do you see the same result? Are you also on dx12?

If that's the case, there has been a dependency update related, could you check if it's fixed after a `cargo update`?

**Comment by flmng0** [comment]
Yes. I ran it using Vulkan and it works perfectly fine now. Very curious issue

**Comment by mtsr** [comment]
Found it, will see if I can figure out why:

![image](https://user-images.githubusercontent.com/1319584/116825081-e2476400-ab8d-11eb-918e-3c4272e1fa51.png)

**Comment by mtsr** [comment]
Some observations from trying to fix this and discussing in #general:

> Metallic is correct, Reflectance uses the value for Roughness, Emissive uses the value for Reflectance and Roughness has 0 which could be the first float from Emissive.

This sort of excludes packing rules, because it's complete buffers that are shuffled.

> since this is not on LightsUniform (like some previous pbr bugs, red.), this is just handled by AssetRenderResourcesNode::<StandardMaterial>

> Akorian — Today at 10:05 PM
the bindings seem to be rearranged on hlsl (all sequential registers) while the source glsl leaves some of them empty (depending on what textures are being used).. that might have something to do with it

Moving all optional uniforms after the non-optional ones does nothing for 3d_scene, but does make load_gltf worse.

I'll capture a wgpu trace and log with wgpu-rs unless somebody else spots the issue first.

**Comment by CptPotato** [comment]
A few additional things that came up as we tested:

If a material uses ***all*** textures of the PBR shader the problem disappears (*) [image](https://user-images.githubusercontent.com/3957610/116849380-f1123300-abee-11eb-8090-fc841139b5cd.png). This makes it more plausible that the binding order of `uniforms` when some of them are skipped could be the problem.

(*) there still are noisy artifacts as you can see in the image. It almost looks like they appear at vertices of the mesh (?) and disabling MSAA gets rid of them completely, so I'd say this is unrelated to the `uniform` problem in this issue.
I have the hunch that it might have something to do with MSAA not resolving the alpha channel correctly but it could also be something completely different (rasterization, etc).

**Comment by alice-i-cecile** [comment]
This is fixed now.
