### ISSUE TITLE
Bevy 0.4 -> 0.5 broke aarch64-unknown-linux-gnu

### ISSUE THREAD

**Issue by skhameneh** [bevyengine/bevy#1942]
On `armv8.2a`, 0.5 fails on `bevy-glsl-to-spirv` not supporting ` aarch64-unknown-linux-gnu`.  
I added ` aarch64-unknown-linux-gnu` to the supported platforms locally for `bevy-glsl-to-spirv` and `bevy-glsl-to-spirv` will build, but `bevy` fails on linking with various glsl components.  
  
It's not clear if Bevy 0.4 was using `shaderc` or something else in `bevy_render` broke the build.

**Comment by MinerSebas** [comment]
Bevy 0.4 should have never been able to successfully compile on `aarch64-unknown-linux-gnu`, as Bevy currently uses `bevy-glsl-to-spirv`, except for `ios` and `aarch64 macos` where `shaderc` is used instead.

This Issue can be closed once #1819 makes `shaderc` the Default.

**Comment by skhameneh** [comment]
Confirming https://github.com/bevyengine/bevy/commit/a46c35a7a050440fa3e672d46bad97c94ed8a0a9 from https://github.com/bevyengine/bevy/pull/1819 fixes this issue.
