### ISSUE TITLE
Investigate new incremental compile improvements

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1952]
As described in [Reducing Rust Incremental Compilation Times on macOS by 70%
](https://jakedeichert.com/blog/reducing-rust-incremental-compilation-times-on-macos-by-70-percent/), Rust 1.51 has a new compilation option that is designed to reduce incremental compile times.

This is very relevant to Bevy's goals for fast, iterative game development, and IMO deserves investigation to see how it interacts with our other fast compilation options.

[Associated reddit thread](https://www.reddit.com/r/rust/comments/msymvm/reducing_rust_incremental_compilation_times_on/), in case some relevant details are found there.

**Comment by bjorn3** [comment]
The unstable version of this option has been used for ages. Now that cargo even enables it by default on nightly, https://github.com/bevyengine/bevy/pull/1913 removed the explicit setting of this option in the fast compile config.

**Comment by alice-i-cecile** [comment]
Great. Thanks @bjorn3; I'm closing this now.
