### ISSUE TITLE
Hide re-exported docs

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1957]
## How can Bevy's documentation be improved?

When we search for common items in Bevy's docs, we often see two or three duplicate entries due to re-exporting.

This can be disabled using `#[doc(hidden)]` above the re-exports. See: <https://doc.rust-lang.org/beta/rust-by-example/meta/doc.html#hidden>.

IMO the re-exports should be hidden, as the root path is the most informative about what the function does and where to find it. We should verify that this doesn't break tools like Rust analyzer in IDEs when using prelude imports however.

**Comment by bjorn3** [comment]
Using `#[doc(hidden)]` in the prelude will make it harder to find what is in the prelude and what is not. I think `#[doc(no_inline)]` on the re-exports does prevent the duplicate entries though by showing just `use ...` inside the prelude module instead of embedding the actual items. This is what libstd does for it's prelude.

**Comment by CaelumLaron** [comment]
Can I try to do this @ alice-i-cecile?

**Comment by CaelumLaron** [comment]
Can I try to do this @alice-i-cecile ?

**Comment by alice-i-cecile** [comment]
@CaelumLaron absolutely; I'll assign you to this issue. Link to it on your PR once it's up :)

**Comment by CaelumLaron** [comment]
Hey @alice-i-cecile 
![sprie](https://user-images.githubusercontent.com/43704839/115593281-520e4280-a2a2-11eb-8812-1557735fcd06.png)
In the case of `Sprite` in this image, the result that we want is that only `bevy::sprite::Sprite` appears, right?

**Comment by alice-i-cecile** [comment]
I'm not convinced one way or the other about whether we want to hide the bundle fields, so those can remain.

I also think bevy::sprite::node::SPRITE is a conceptually different object.

**Comment by CaelumLaron** [comment]
Sorry for the dumb questions @ alice-i-cecile 😣, but can you send me an example? I think I am doing something wrong

**Comment by zicklag** [comment]
> Using #[doc(hidden)] in the prelude will make it harder to find what is in the prelude and what is not. I think #[doc(no_inline)] on the re-exports does prevent the duplicate entries though by showing just use ... inside the prelude module instead of inlining the actual definition of the re-exported items. This is what libstd does for it's prelude.

I just tried this in my Bevy plugin and it worked great!

> Sorry for the dumb questions @ alice-i-cecile persevere, but can you send me an example? I think I am doing something wrong

@CaelumLaron here's what I did: for every `prelude` module, you will need to add the `#[doc(no_inline)]` annotation above each `pub use` statement. For example:

**`prelude.rs`:**

```rust
// ...
#[doc(no_inline)] // Add this above every `pub use`
#[cfg(feature = "bevy_audio")]
pub use crate::audio::prelude::*;
// ...
```

**Comment by alice-i-cecile** [comment]
Thanks @zicklag; I appreciate you answering for me <3

**Comment by zicklag** [comment]
Actually, I think I just found out that the `no_inline` annotation stops working when you inline the sub-crates like Bevy does to make all of the docs pup up like `bevy::core` without docs.rs linking to `bevy_core` as a separate crate. So I don't think that it will help us in this case. It seems like if you inline one module, then all of the modules under it, including the `prelude`'s, have to be inlined.

I'm not 100% sure I'm understanding it properly, but that's what issue I'm getting in my crate.

**Comment by CaelumLaron** [comment]
Thanks, @zicklag 👾 I am a little slow DX!

**Comment by janus-culsans** [comment]
Is this done? #1985 had "Solves #1957" as a message, so that's probably why bors didn't close this?
