### ISSUE TITLE
Missing collision detection

### ISSUE THREAD

**Issue by geckoblu** [bevyengine/bevy#1980]
Function _collide_ in _collide_aabb_ misses to detect a collision if the two objects are intersecting but not by a side.
Maybe is my idea of collision but the two following objects should be detected as colliding:

```
let a_pos = Vec3::new(8.0, 0.0, 0.0);

let a_size = Vec2::new(10.0, 10.0);

let b_pos = Vec3::new(8.0, 0.0, 0.0);
let b_size = Vec2::new(6.0, 100.0);

let collision = collide(a_pos, a_size, b_pos, b_size);
println!("collision {:?}", collision); // ... I expect to have a collision here
```
It's more evident if we check the behavior on moving objects:

``` 
let mut a_pos = Vec3::new(0.0, 0.0, 0.0);
let a_size = Vec2::new(10.0, 10.0);

let b_pos = Vec3::new(8.0, 0.0, 0.0);
let b_size = Vec2::new(6.0, 100.0);

loop {	
	let collision = collide(a_pos, a_size, b_pos, b_size);
	println!("a_pos.x {:?} => collision {:?}", a_pos.x, collision);
	a_pos.x += 1.0;
	if a_pos.x > 16.0 {
		break;
	}
}
```
The problem is the heuristics to determine the side of collision.
An easy solution is to add a generic Collision::Intersecting collision.

I attach my proposed patch here (with tests)
[collide_aabb.patch.txt](https://github.com/bevyengine/bevy/files/6356914/collide_aabb.patch.txt)

**Comment by mockersf** [comment]
first look seems good, could you open a PR as you have a patch ready?

**Comment by geckoblu** [comment]
Thanks, I created the PR.

**Comment by mockersf** [comment]
thanks!
