### ISSUE TITLE
Split CI into multiple files

### ISSUE THREAD

**Issue by qarmin** [bevyengine/bevy#1993]
Currently CI contains only one file with different platforms inside.

It should be divided to few files, because this will allow to easily find interesting CI reports/failings etc.

This is actions tab in Godot
![Screenshot from 2021-04-23 19-04-23](https://user-images.githubusercontent.com/41945903/115905819-eaedbb00-a466-11eb-8cbe-ca39561bc0ef.png)
 
and in Bevy
![Screenshot from 2021-04-23 19-05-02](https://user-images.githubusercontent.com/41945903/115905964-2be5cf80-a467-11eb-8602-3b0f78d676f3.png)

**Comment by bjorn3** [comment]
Having a separate workflow for each OS increases duplication and thus the risk of CI configuration going out of sync. In addition IMHO it makes it harder to show the status of all checks on a single commit. It also makes it very hard to cancel further checks once one failed. And finally it becomes impossible to run some steps once all other steps are done. (this may be useful in the future for automation)

**Comment by cart** [comment]
Hmm yeah. I do like the extra organization, but I think @bjorn3's points outweigh the benefits.

**Comment by mockersf** [comment]
CI evolved since then, jobs are now grouped by when they run (on PR, on toml file change, on bors validation) and jobs inside a file often have dependencies to help with parallelism
