### ISSUE TITLE
Change system set builder to force users to put the "config" first

### ISSUE THREAD

**Issue by hymm** [bevyengine/bevy#1994]
## What solution would you like?

`with_system` on the SystemSet builder returns something that only implements `with_system`, so config things like labeling, run_criteria, etc. must be placed before the systems.

## What problem does this solve or what need does it fill?

This would fix https://github.com/bevyengine/bevy/issues/1912.

This would explicitly enforce @cart's preference on this comment https://github.com/bevyengine/bevy/pull/1909#discussion_r619411332

## What alternative(s) have you considered?

We can just keep things as they are.  Cargo fmt disambiguates this decently.

**Comment by Ratysz** [comment]
I prefer this style as well, but outright forbidding alternatives seems needlessly restrictive. Not to mention the small but non-negligible API complication that would be necessary.

**Comment by cart** [comment]
Agreed. Adopting the "type state" approach here would over-complicate the api and adopting an internal "state tracker" also feels pretty messy.

I'd rather just encourage it as a "best practice" in official examples.

**Comment by cart** [comment]
(feel free to continue discussing if you want, I'll reopen if any major dissenting opinions show up)
