### ISSUE TITLE
Implement ToString for KeyCode

### ISSUE THREAD

**Issue by billyb2** [bevyengine/bevy#1995]
## What problem does this solve or what need does it fill?

By implementing ToString for each KeyCode, it would make it possible to easily display the keybindings for a game.

## What solution would you like?

A pretty long `impl std::fmt::Display for KeyCode` with every KeyCode either having their literal character printed out, or a description (like Backspace)

## What alternative(s) have you considered?

Possibly just implementing `std::fmt::Display, though I feel as though ToString wouldn't be very difficult once that is implemented`

Other solutions to solve and/or work around the problem presented.

Limiting the possible charaters used, and then having a display for each of those characters, though that feels like implementing ToString and Display with extra steps.

## Additional context

Any other information you would like to add such as related previous work,
screenshots, benchmarks, etc.

**Comment by alice-i-cecile** [comment]
As I understand it a clean mapping from KeyCode's to string / characters / glyphs doesn't exist :(

See #782, #804, #805, #1392 for some previous discussion on these lines. #805 was implemented; does it provide what you need?

**Comment by billyb2** [comment]
Yea that works perfectly, I'll close this, thank you.
