### ISSUE TITLE
Query in a run criteria system doesn't work

### ISSUE THREAD

**Issue by engiwengi** [bevyengine/bevy#2000]
## Bevy version

Bevy main 38feddb87850424df3a0b08bae8dc32c57004798

## Operating system & version

Windows 10

## What you did
```rust
struct Foo;

fn number_of_entities_system(mut commands: Commands, query: Query<&Foo>) {
    println!("num entities from dummy: {}", query.iter().count());
    commands.spawn_bundle((Foo,));
}

fn number_of_entities_critiera(query: Query<&Foo>) -> ShouldRun {
    println!("num entities from criteria: {}", query.iter().count());
    ShouldRun::Yes
}

App::build()
    .add_plugins(MinimalPlugins)
    .add_system(
        number_of_entities_system
            .system()
            .with_run_criteria(number_of_entities_critiera.system()),
    )
    .run();
```

## What you expected to happen

Both systems print the same number of entities

## What actually happened

Run criteria reports zero entities, system reports correct number.

## Additional information

Console log on my machine:

```
num entities from dummy: 1695
num entities from criteria: 0
num entities from dummy: 1696
num entities from criteria: 0
num entities from dummy: 1697
num entities from criteria: 0
num entities from dummy: 1698
```

**Comment by cart** [comment]
I'm guessing this is probably caused by `SystemStage` not calling `System::new_archetype()` on its run criteria systems.

**Comment by cart** [comment]
Pulling in @Ratysz.

**Comment by Ratysz** [comment]
Sounds plausible. I'm not sure when I'll have the time to take a proper look.
