### ISSUE TITLE
Factor ECS into a Separate Generic Project

### ISSUE THREAD

**Issue by sirinath** [bevyengine/bevy#2002]
Can ECS be factored into a separate project for general computation use.

**Comment by TheRawMeatball** [comment]
The ECS is already designed with the possibility of general computation in mind, and can be used without any part of the engine. I don't think this requires the ECS to be moved into a separate project.

**Comment by sirinath** [comment]
It's in one crate?

**Comment by TheRawMeatball** [comment]
Yes, the `bevy_ecs` crate can already be used standalone.

**Comment by cart** [comment]
Yup I think the biggest missing piece here is a "complete" readme in the bevy ecs crate. We could also consider moving bevy_ecs into its own repo, but I think have it in the main bevy repo provides a ton of benefits. Namely shared pr and issue feeds, centralized changelog, and unified statistics. For better or for worse, people will look at the main bevy repo to determine the health and activity of the project, so I think it makes sense to keep bevy ecs in a high visibility spot.

**Comment by sirinath** [comment]
Another idea is if they are willing and this project is willing give the non gaming parts like ECS, scheduler, linear algebra, SIMD parts to [DimFiorge](https://github.com/dimforge) and jointly develop it.

**Comment by bjorn3** [comment]
Honestly I don't think data flow, ECS and the scheduler make sense as part of DimForge given that they have nothing to do with physics. Linear algebra and SIMD do though, but they already have nalgebra and we use glam which is just another dependency of Bevy and not a part of it.

**Comment by cart** [comment]
Agreed. Bevy ECS is one of the most central parts of this project. I won't be giving up control of it any time soon :smile: 

I think we can close this. I've opened #2008 to track the "bevy_ecs" readme work.
