### ISSUE TITLE
System::on_enter, access to resources added by other systems?

### ISSUE THREAD

**Issue by Luminoth** [bevyengine/bevy#2003]
Apologies for the poor title, I'm not really sure how best to describe my use case here. Basically, I want to split up the systems that I'm using for my game state's on_enter() so that one system can add resources that subsequent on_enter() systems can then have access to. It doesn't seem to matter if I explicitly label and order the systems, it always panics when I try it.

## Bevy version

0.5.0

## Operating system & version

Ubuntu 20.04

## What you did

Here is the code I'm looking at:

```
use bevy::prelude::*;

#[derive(Debug, Copy, Clone, Eq, PartialEq, Hash)]
enum GameState {
    Game,
}

struct Resource;

fn setup_game_resources(mut commands: Commands) {
    info!("setup resource");

    commands.insert_resource(Resource);
}

fn setup_game_systems(_res: Res<Resource>) {
    info!("systems");
}

#[bevy_main]
fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_state(GameState::Game)
        .add_system_set(
            SystemSet::on_enter(GameState::Game)
                .with_system(setup_game_resources.system().label("resources"))
                .with_system(setup_game_systems.system().after("resources")),
        )
        .run();
}
```

## What you expected to happen

I would expect that because I've set an ordering on the on_enter() systems that I would have access to the resources added by setup_game_resources() and things would work without a panic.

## What actually happened

Bevy panics:

```
thread 'Compute Task Pool (2)' panicked at 'Requested resource does not exist: bevy_issue::Resource', /home/shane/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/system_param.rs:244:17
```

It's unclear from the documentation if there is a more appropriate way to be doing what I'm going for here.

**Comment by alice-i-cecile** [comment]
This is the problem of "commands cannot be processed instantly", discussed in #1613.

We'd very much like a solution to that, although doing so with Resources is hard too.

In your case, I would suggest using the `FromWorld` trait on your resource to handle complex resource initialization without needing a hard-sync point (aka end of stage).

**Comment by Ratysz** [comment]
> I would suggest using the FromWorld trait on your resource

Or, set up the resource in a startup system, once. If you need to "de-initialize" it later for some reason, make it an `Option<MyResource>` or some equivalent.

**Comment by alice-i-cecile** [comment]
I think we can close this out; I don't see any immediately actionable way to handle this and the suggestions given are quite good.
