### ISSUE TITLE
Bevy ECS crate needs a readme

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#2008]
Many people would like to use bevy_ecs outside of the context of Bevy, but it isn't immediately clear that it can be used standalone (#2002). The crates.io page is pretty bare:

![image](https://user-images.githubusercontent.com/2694663/116002644-9570f580-a5af-11eb-93d6-3cb6eec0e51b.png)

We should give `bevy_ecs` a nice readme that introduces the project (in an ECS-only context) and lets people know that it can be used by itself.

**Comment by ColdIce1605** [comment]
I think it should be clear also in the readme that it can be used standalone with a message like "This crate can be used standalone".

**Comment by cart** [comment]
Haha I agree:

> a nice readme that introduces the project (in an ECS-only context) and lets people know that it can be used by itself.

**Comment by ColdIce1605** [comment]
Whoops. Hahaha

**Comment by alice-i-cecile** [comment]
I mentioned the stand-alone use in #2040 as well :)
