### ISSUE TITLE
WithBundle missing WorldQuery implementation

### ISSUE THREAD

**Issue by CGMossa** [bevyengine/bevy#2023]
While fiddling with bundles, I wanted to do `Query<(My, Components), WithBundle<MyBundle>>`
but instead I'm met with this compilation error: 

```rust
error: the trait `WorldQuery` is not implemented for `bevy::prelude::WithBundle<CattleFarmBundle>` 
```

According to @TehPers, it might only need this

```rust
impl<T: Bundle> WorldQuery for WithBundle<T> {
    type Fetch = WithBundleFetch<T>;
    type State = WithBundleState<T>;
}
```

I was asked to create this issue, so here it is.

**Comment by cart** [comment]
Yup it looks like we lost the WorldQuery impl during the ECS V2 rewrite. We should add it back :)

**Comment by cart** [comment]
(and then check the new implementation for correctness because clearly that hasn't been done since the rewrite)
