### ISSUE TITLE
Cannot run after `cargo install`

### ISSUE THREAD

**Issue by MichaelMcDonnell** [bevyengine/bevy#2051]
## Bevy version

Bevy v0.5.0

## Operating system & version

Debian testing

## What you did

1. Set up my project to use dynamic linking as described in the book
2. Published my project with `cargo publish`
3. Installed my project with `cargo install buzzy`
4. Ran `buzzy` from the command line and got the following error message:
```
michael@DEBIAN-DESKTOP:~/src/buzzy$ buzzy
buzzy: error while loading shared libraries: libbevy_dylib-46bdaea1d41f3083.so: cannot open shared object file: No such file or directory
```

## What you expected to happen

I expected my project to start.

## What actually happened

My project didn't start and I got the following error message:
```
michael@DEBIAN-DESKTOP:~/src/buzzy$ buzzy
buzzy: error while loading shared libraries: libbevy_dylib-46bdaea1d41f3083.so: cannot open shared object file: No such file or directory
```

**Comment by alice-i-cecile** [comment]
Does this work without dynamic linking?

**Comment by mockersf** [comment]
If you publish your game with dynamic loading configured, you will need to provide the dynamic library... This is intended to speed up development but should probably not be used in a release (that is, until you can `apt-get install libbevy`)

**Comment by MichaelMcDonnell** [comment]
Thanks for all the replies! I just realize I deviated from the book. I had added `dynamic` in features to avoid having to specify it every time in run the project:
```toml
[dependencies]
bevy = { version = "0.5", features = ["dynamic"] }
```
Is there a way to just enable it for dev builds and not release? Then running it after doing a `cargo install` should work (it uses release builds by default).

I tried adding a dev profile:
```toml
[dependencies]
bevy = { version = "0.5"}

[profile.dev]
features = ["bevy/dynamic"]
```
but got "warning: unused manifest key: profile.dev.package.bevy.features" while building.

**Comment by cart** [comment]
I generally just use `cargo run --features bevy/dynamic` for dev and `cargo run --release` for releases. I don't think theres a way to enable features in a profile.

**Comment by MichaelMcDonnell** [comment]
What about when running a debugger? I now remember that's why I added "bevy/dynamic" in the `Cargo.toml` file. VS Code will not debug the executable if I use cargo in the `launch.json` file:
```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug",
            "program": "cargo",
            "args": ["run", "--features", "bevy/dynamic"],
            "cwd": "${workspaceFolder}"
        }
    ]
}
```
It seems like cargo could use a feature to allow per profile features?

**Comment by cart** [comment]
Hmm yeah using the debugger complicates things. Maybe rust analyzer (which its own "debug execution settings/lenses") will let you pass in bevy/dynamic?

I definitely think cargo would benefit from per-profile features. No clue why they don't do that already.

**Comment by MichaelMcDonnell** [comment]
Closing this issue since I was getting things wrong, and it morphed into probably needing a feature in cargo.

**Comment by hsandt** [comment]
So published/released games should indeed remove `dynamic`, but for those who are still doing debug builds (not release/publish), intentionally using the `dynamic` feature and have the same issue when running the app, I found this workaround on https://saveriomiroddi.github.io/ :

1. add the path to temporary libbevy_dylib-[number].so to LD_LIBRARY_PATH
2. in addition, also add the path to your toolchain lib, otherwise you'll get the same error but with libstd-[number].so next

In terminal, that gives:

$ LD_LIBRARY_PATH="${workspaceFolder}/target/debug/deps:${HOME}/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib" ./game

(replace ${workspaceFolder} and game with project folder and app name)

Note: the article gives the solution specifically for VS code, but you can adapt it to your code editor launch/run system:

> add this entry to the launch configuration (in `launch.json`):

```
"env": {
  "LD_LIBRARY_PATH": "${workspaceFolder}/target/debug/deps:${env:HOME}/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib",
}
```
