### ISSUE TITLE
Use thiserror instead of anyhow in bevy_asset

### ISSUE THREAD

**Issue by mtsr** [bevyengine/bevy#2058]
## What problem does this solve or what need does it fill?

`bevy_asset` currently uses `anyhow`, whereas `bevy_gltf` uses `thiserror`. But because of the `AssetLoader` trait, `bevy_gltf` (and anything else implementing `AssetLoader`) is forced to use `anyhow`.

https://github.com/bevyengine/bevy/blob/cf221f9659127427c99d621b76c8085c4860e2ef/crates/bevy_asset/src/loader.rs#L17-L24

## What solution would you like?

As the docs for anyhow and thiserror state:

> Use Anyhow if you don't care what error type your functions return, you just want it to be easy. This is common in application code. Use thiserror if you are a library that wants to design your own dedicated error type(s) so that on failures the caller gets exactly the information that you choose.

## What alternative(s) have you considered?

Use `anyhow` everywhere instead (easier, but not recommended).

## Additional context

Any other information you would like to add such as related previous work,
screenshots, benchmarks, etc.

**Comment by bjorn3** [comment]
`AssetServer::add_loader` requires the asset loader to be object safe. Using thiserror would however require making the error type an associated type of the asset loader as different asset loaders may return different errors. There is no fixed known set of errors that will work for third party asset loaders too.

**Comment by mtsr** [comment]
Sure, but then AssetLoader is nicely encapsulated, and the AssetServer can deal with it however it wants. It's not a huge difference, though, agreed.

**Comment by mtsr** [comment]
Oh well. Not important enough to fix, right now. Thanks for helping me see the point of the current construction.
