### ISSUE TITLE
Move Bevy's fork of the ecs_bench_suite to the appropriate folder

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2062]
I went looking for the latest bevy-specific `ecs_bench_suite` code and could not quickly find it.

Ideally, this should be found (or linked) in our [benches/bevy_ecs](https://github.com/bevyengine/bevy/tree/main/benches/benches/bevy_ecs) folder.

The most up-to-date version is currently found on @cart's GitHub page here: https://github.com/cart/ecs_bench_suite/tree/bevy-benches. The latest upstream code is here: https://github.com/rust-gamedev/ecs_bench_suite

Once this is done, please also update CONTRIBUTING.md (see #2040) with directions to the benchmarks and add appropriate documentation on how to run the benchmarks in the README of the benches folder.

I'm also not entirely sure why we have two layers of `benches` folders; perhaps someone else can chime in.

**Comment by cart** [comment]
I think it makes sense to have in-tree benches that are easy to run. We can probably just copy the benches from my ecs_bench_suite fork. However we should also drive the new benchmarks upstream. I'll probably get to it eventually, but if anyone else wants to pick that up, I'm cool with it.
