### ISSUE TITLE
Add #[non_exhaustive] to public API structs

### ISSUE THREAD

**Issue by multun** [bevyengine/bevy#207]
https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute

That's a cool backward compat tool, but it also prevent users from using struct expressions
https://internals.rust-lang.org/t/pre-rfc-relaxed-non-exhaustive-structs/11977/16

**Comment by cart** [comment]
Yeah we rely pretty heavily on the ..Default::default() to make the entity building api nice, so we can't lose that. Definitely worth looking into though.

**Comment by lachlansneff** [comment]
wgpu-rs was running into the same issue. I did a little bit of investigative work to see how difficult it would be to add support for `#[non_exhaustive(pub)]` to rustc. It didn't seem too hard, but the timeline involved was unfortunate.

**Comment by NathanSWard** [comment]
Curious, is there any update here on to what path we'd like to take?
As I see it 

- Adding `#[non_exhaustive]`
  - Pros:  Helps with backwards compatibility
  - Cons: Verbose, can actually lead to user error. If a new field is introduced and some does `MyStruct { some_value, .. }` the new value will get consumed via `..`. This could cause hard to track down errors.

**Comment by cart** [comment]
Yeah I'm also in favor of not adding this. Its too disruptive to "normal use cases". I'm personally ok with the default behavior / new fields breaking downstream code (which is made less of an issue by encouraging the `..Default::default()` pattern).
