### ISSUE TITLE
Note that the log_diagnostics example shows how to check FPS in description

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2076]
## How can Bevy's documentation be improved?

For discoverability from users searching, this should mention that it shows the "frames per second (FPS)"

**Comment by NathanSWard** [comment]
Is this in the example itself in the comments or in the readme?

**Comment by alice-i-cecile** [comment]
This is quite clear once you reach the example. My intent was that this should just be added to the readme.
