### ISSUE TITLE
Bevy logo doesn't fit well with GitHub dark themes

### ISSUE THREAD

**Issue by Nilirad** [bevyengine/bevy#2079]
## How can Bevy's documentation be improved?

In [README.md](https://github.com/bevyengine/bevy/blob/main/README.md) the Bevy logo is shown. However it is barely visible with dark GitHub themes, especially Dimmed Dark.

![logo_with_gh_theme](https://user-images.githubusercontent.com/32368687/116818564-583ad380-ab6c-11eb-9d6d-0779ccc41eda.png)

Maybe it can be adjusted by adding a thin contrast outline (2-3 px) to the letters and the image.

**Comment by cart** [comment]
Yeah this has been bothering me for awhile. I'd like for github to give us the ability [switch out the svg based on the theme](https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981) but until then I think the proposed solution is the way to go.

**Comment by mccludav** [comment]
I have submitted a pull request #2288 for this issue.  It would be my 1st contribution ever, so I hope it is accepted.  I did add a thin border to the blackbird, B, E, V, and Y letters.
