### ISSUE TITLE
Drag and drop example does not react

### ISSUE THREAD

**Issue by lukors** [bevyengine/bevy#2096]
## Bevy version
tag v0.5.0
Also tested on current main 2390bee6474cd9bef3b24e2c276e789d3c31c455

## Operating system & version
Windows 10

## What you did
1. Ran `cargo run --example drag_and_drop` in the bevy repo.
2. Dragged and dropped a file onto the window.

## What you expected to happen
Stuff should get printed in the terminal window.

## What actually happened
Nothing gets printed.

## Additional information
Nope.

**Comment by lukors** [comment]
It works for me on Pop!_OS on latest main: 7d0e98f34c43eb62522c0c65de64f7b458b899be

So it seems like a Windows issue.

**Comment by P0ntiuS** [comment]
Windows's realization WinitWindow use Builder with drag_and_drop flag off, because AudioPlugin(for windows) use multithreaded COM library (rodio->cpal), and it would crush your application if the drag_and_drop flag is on.

https://github.com/bevyengine/bevy/blob/7d0e98f34c43eb62522c0c65de64f7b458b899be/crates/bevy_winit/src/winit_windows.rs#L20-L24

See, [my changes](https://github.com/P0ntiuS/bevy/pull/1) makes it works.

More information:
[Winit Issue](https://github.com/rust-windowing/winit/issues/1255),
[Problem place in cpal](https://github.com/RustAudio/cpal/blob/1b2469d0c1175250e1c7944b51e53f613671e987/src/host/wasapi/com.rs)

**Comment by lukors** [comment]
Thanks a lot for the explanation and the fix!

Is this a limitation in Windows? Is it impossible to have a Windows application that can both output sound and have files dropped on it?

Here are some solutions that come to mind for this issue:

1. If possible, implement some solution to the root cause of the issue.
2. Add in something like a feature flag or runtime configuration to allow people to turn on drag and drop for their project, and document this in the example and documentation.
3. Update the example and documentation for drag and drop to point out that it doesn't work on Windows.

**Comment by bjorn3** [comment]
> Is this a limitation in Windows?

Yes

> Is it impossible to have a Windows application that can both output sound and have files dropped on it?

As I understand it winit uses OLE for drag and drop support, which only works when initializing COM single-threaded. Cpal however initializes COM as multi-threaded. Supporting single-threaded COM in cpal wouldn't be easy I guess as most things implement `Send` and `Sync` and can thus be used on multiple threads.

**Comment by lukors** [comment]
Thanks! So that leaves alternatives 2 and 3.

I'll consider looking into feature flags to see if that might be a good solution.

Adding an input parameter to the function that decides if drag/drop support should be enabled—and that input parameter just being used on one platform—doesn't feel right. And I don't know of another way to do it.

**Comment by P0ntiuS** [comment]
1 It would be possible if cpal implement optional single threading initialization. I coped cpal com.rs and did single threading initialization, and it works.

Other options, create AudioPlugin in a different thread. I made an example of how to bring together drag and drop and play sound.
https://github.com/P0ntiuS/drag_and_drop_with_audio

The question is, how to move AudioPlugin to another thread in bevy?

**Comment by lukors** [comment]
@P0ntiuS very nice that you are looking into this!

Hm, so the deal with COM is that you can have either multi-threaded COM or single-threaded COM for each thread? So it's not per application, but per thread?

I don't really know anything about this, but I have a feeling that if we wanted to move AudioPlugin to its own thread this would need its own feature in bevy. Because Bevy is heavily threaded, right?

It would be neat if cpal could allow the user to choose single threaded COM. But perhaps there is some issue with audio then? Did you try to play sound in the single-threaded cpal sound+drag/drop example to make sure it works?

I've been trying to get the feature flag to work, but haven't been able to yet.

I also asked about this in the cpal GitHub to see if it would be possible and make sense enable the user to choose how to initialize COM: https://github.com/RustAudio/cpal/issues/572

**Comment by lukors** [comment]
It seems like a fix for this was just merged into cpal? https://github.com/RustAudio/cpal/pull/597

And they are going to make a new release for it.
