### ISSUE TITLE
Return Vec<Entity> from spawn_batch

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2098]
## What problem does this solve or what need does it fill?

`commands.spawn()` returns the `Entity` that was just created. This is useful for all number of reasons when working with more complex workflows. `spawn_batch` however does not.

## What solution would you like?

Return the appropriate `Vec<Entity>` of entity ids when `spawn_batch` is called.

## What alternative(s) have you considered?

Always just use loops of spawn when you need the `Entity`.

Make `spawn` faster and deprecate `spawn_batch`

## Additional context

@StarArawn needed this to be able to migrate `bevy_ecs_tilemap` to `spawn_batch`.

**Comment by TheRawMeatball** [comment]
This would likely be a separate command, as reserving entities preemptively requires consuming the iterator, and has the additional overhead of reserving a large amount of entities.

**Comment by NathanSWard** [comment]
> This would likely be a separate command, as reserving entities preemptively requires consuming the iterator, and has the additional overhead of reserving a large amount of entities.

Any suggestions for this new method's name?

**Comment by alice-i-cecile** [comment]
> Any suggestions for this new method's name?

How about `spawn_allocated_batch` or `spawn_batch_reserve`?

**Comment by james7132** [comment]
Is this use case not covered by `Commands::insert_or_spawn_batch` now? (http://dev-docs.bevyengine.org/bevy/ecs/system/struct.InsertOrSpawnBatch.html)

**Comment by alice-i-cecile** [comment]
> Is this use case not covered by Commands::insert_or_spawn_batch now? (http://dev-docs.bevyengine.org/bevy/ecs/system/struct.InsertOrSpawnBatch.html)

Partially. I think this plus `Added` filters is the way to go.
