### ISSUE TITLE
Docs: ambiguity involving the feature "dynamic"

### ISSUE THREAD

**Issue by marcospb19** [bevyengine/bevy#2102]
I was reading the getting-started section, and found this.

![image](https://user-images.githubusercontent.com/38900226/117078748-e18b0b00-ad10-11eb-9b9b-fafee492c716.png)

So, it is unclear to me if I need to run with the flag every time, or no.

The bottom part of this page says:
![image](https://user-images.githubusercontent.com/38900226/117078861-0c755f00-ad11-11eb-805a-c1cd6fb30e63.png)

---

So my suggestion is to make clear is this is persistent or no.

Also, is there a way to add this feature to the Cargo.toml file to be always used, maybe only when in `dev/debug` mode?

I am not 100% sure, but If it is, I would suggest to teach the user how to do it via Cargo.toml, instead of the CLI, someone could forget the flag.

**Comment by bjorn3** [comment]
> So, it is unclear to me if I need to run with the flag every time, or no.

It needs to be used every time.

> Also, is there a way to add this feature to the Cargo.toml file to be always used, maybe only when in dev/debug mode?

Cargo doesn't provide a way to enable package features only on certain profiles. You can enable it permanently by using something like `bevy = { version = "0.5.0", features = ["dynamic"] }` instead of `bevy = "0.5.0".

**Comment by cart** [comment]
Or you could include it in the Cargo.toml and just remember to comment it out when publishing your game.
