### ISSUE TITLE
Add system to quit games to default plugins

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2110]
## What problem does this solve or what need does it fill?

A description of why this particular feature should be added.

## What solution would you like?

A system should be added to a plugin within DefaultPlugins that listens to keyboard inputs and creates an [AppExit](https://docs.rs/bevy/0.5.0/bevy/app/struct.AppExit.html) event when it notices `CTRL+Q` ~~or `CTRL+C`~~ being called.

## What alternative(s) have you considered?

Users can manually implement this, but a) it's common b) it reduces new user friction.

We could also enable this behavior on `Esc`, but that's commonly used for menus and it would be nice to not have to turn this off until you're near a finished game.

## Additional context

Raised in #2109.

**Comment by bjorn3** [comment]
I don't think ctrl+c should quit the game. That makes sense on the terminal where it would already happen, but in a gui it normally means copy.

**Comment by alice-i-cecile** [comment]
Okay, that seems like a nice base to work off of. It doesn't look like it's added anywhere by default though :(

**Comment by alyti** [comment]
I am not sure this is a behavior that should be in the default plugin set, its only useful for demos and alike, in actual games this would be an unwanted behavior, and excluding systems is harder than adding them as far as I know.

**Comment by forbjok** [comment]
Personally, I'm not convinced this should be a default plugin. In a finished game, you'd probably want to put the quit option in a menu or something, rather than having it as a hotkey, and during development, Alt-F4 or just closing the window is sufficient. Also, if you do want a hotkey for it, it's trivial to add as shown in the code @mockersf posted above.

**Comment by alice-i-cecile** [comment]
> Also, if you do want a hotkey for it, it's trivial to add as shown in the code @mockersf posted above.

Maybe the solution is to add these systems to our game examples then?

**Comment by visualcode-t** [comment]
@alice-i-cecile I agree with others, I think `ctrl + c` is enough for a terminal and standard operating system escapes for GUI. I also think adding escapes to game examples could be useful, for those that need more.

**Comment by alice-i-cecile** [comment]
Great, let's go with that. That will be a very simple first issue for anyone interested <3

**Comment by alice-i-cecile** [comment]
Closed by #2121.
