### ISSUE TITLE
Naga not compiling and causing build to fail.

### ISSUE THREAD

**Issue by bentheperson1** [bevyengine/bevy#2113]
## Bevy version

0.5.0

## Operating system & version

Windows 10

## What you did

I tried to run 'cargo run' but the build failed saying that a crate called naga couldn't be compiled.

## What you expected to happen

It should've just compiled and ran normally.

## What actually happened

The build failed and spat out a bunch of errors.

## Additional information

![Screenshot 2021-05-05 160751](https://user-images.githubusercontent.com/57081234/117209544-14d6a400-adbc-11eb-9309-1ff24ac829ab.png)

**Comment by alice-i-cecile** [comment]
`spirv_headers` published an update that broke semver today :( We're working on getting this fixed ASAP.

**Comment by alice-i-cecile** [comment]
Relevant documentation on their end: <https://github.com/gfx-rs/rspirv/blob/4419db432d90cd333e62aae9669dd263acff0499/MAINTENANCE.md> Looks like we may need to fix this with Bevy 0.5.1?

**Comment by mockersf** [comment]
https://github.com/gfx-rs/naga/issues/836

**Comment by MinerSebas** [comment]
You can fix your local build by opening the `Cargo.lock` file, go to the `spirv_headers` entry, edit the version from `1.5.1` back to `1.5.0` and delete the checksum of `spirv_headers`.

**Comment by Jasper-Bekkers** [comment]
I've yanked 1.5.1 and we've started work on switching the spirv_headers crate to follow SemVer instead. For more information see the discussion in https://github.com/gfx-rs/rspirv/issues/197

**Comment by mockersf** [comment]
thanks!

**Comment by alice-i-cecile** [comment]
Closing as resolved <3
