### ISSUE TITLE
Bevy's HashSet missing some functionality

### ISSUE THREAD

**Issue by TheLeonsver1** [bevyengine/bevy#2115]
## Bevy version

0.5

## Operating system & version

Windows 10.

## What you did

tried to initiate a `HashSet` with `with_capactity()`

## What you expected to happen

A `HashSet` to be initiated with the wanted capacity.

## What actually happened

rustc error https://doc.rust-lang.org/error-index.html#E0599

## Additional information

no.

**Comment by TehPers** [comment]
The standard implementations for `HashSet` and `HashMap` implement `new()` and `with_capacity()` only for std's `RandomState`. Since bevy re-exports them with ahash's `RandomState`, we lose those implementations. This could be worked around by creating an extension trait when working with ahash versions of those data structures.

**Comment by cart** [comment]
We actually used to have this, but @bjorn3 removed it in https://github.com/bevyengine/bevy/pull/1235 to cut down on compile times. I'll let them respond here with rationale for / against.

**Comment by bjorn3** [comment]
It was just a slight improvement if I recall correctly. The majority of the change was in the last commit of that PR. I replaced a `HashMap::with_capacity(size)` (where `with_capacity` came from `AHashExt`) with `HashMap::with_capacity_and_hasher(size, Default::default())`. The former is more elegant than the later so I guess it is fine to reintroduce `AHashExt` for just `with_capacity`. `HashMap::new()` is not significantly nicer than `HashMap::default()` so I have a slight preference for not reintroducing `AHashExt::new`.

**Comment by cart** [comment]
Cool cool. Then I think its worth adding it back, as the whole point is to abstract out the hasher. I also agree that we don't need `new()`.
