### ISSUE TITLE
Storage type lookup utility function from World

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2117]
## What problem does this solve or what need does it fill?

While trying to write a new Query parameter, I need to figure out which storage type a specific component has.

I can only search over the `tables` field of my `Storages`, rather than being able to check directly.

This is frustratingly indirect and will result in subtle bugs if and when we add more storage types.

## What solution would you like?

Create a `lookup(ComponentId) -> StorageType` method on [Storages](https://docs.rs/bevy/0.5.0/bevy/ecs/storage/struct.Storages.html).

## What alternative(s) have you considered?

I would prefer to just be able to pass in the type directly, but that's not possible :(

## Additional context

Discovered during #2116.

When adding this functionality, we should check all other code accessing Storages to see if it applies to future-proof our work.

**Comment by cart** [comment]
This is already possible from World:

```rust
let components = world.components();
let id = components.get_id(TypeId::of::<Transform>()).unwrap();
let storage_type = components.get_info(id).unwrap().storage_type();
```

You can also do it from systems:

```rust
fn system(components: &Components) {
    let id = components.get_id(TypeId::of::<Transform>()).unwrap();
    let storage_type = components.get_info(id).unwrap().storage_type();
}
```

**Comment by alice-i-cecile** [comment]
Aha! Thank you <3
