### ISSUE TITLE
Could not compile bevy_ecs causing build to fail

### ISSUE THREAD

**Issue by bentheperson1** [bevyengine/bevy#2118]
## Bevy version

0.5

## Operating system & version

Windows 10

## What you did

I tried to compile and I got an error saying that bevy_ecs could not be compiled because of an unstable library.

## What you expected to happen

It should have compiled and ran normally.

## What actually happened

It gave me an error saying that bevy_ecs could not compile because of an unstable library.

## Additional information

![image](https://user-images.githubusercontent.com/57081234/117233786-6a757580-ade9-11eb-93a8-10137c0c3f89.png)

**Comment by alice-i-cecile** [comment]
What's your current Rust version? You likely need to update it to latest stable.

**Comment by alice-i-cecile** [comment]
(Sorry about the label, that's not intended to be hostile <3)

**Comment by bentheperson1** [comment]
1.48

**Comment by alice-i-cecile** [comment]
`rustup update` and then `cargo clean` should solve your issues <3

Bevy uses new Rust features aggressively on release; our MSRV tends to be "latest stable"; 1.48 is 4 versions behind.

See https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html for more detailed instructions as needed.

**Comment by bentheperson1** [comment]
alright thanks!
