### ISSUE TITLE
Panic when using odd number of Indices::U16s (buffer range size must be multiple of 4)

### ISSUE THREAD

**Issue by geckoxx** [bevyengine/bevy#2124]
## Bevy version

Since update to wgpu 0.8 (afaf4ad3)

## Operating system & version

Windows 10

## What you did

Creating a mesh using odd number of u16 indices.

## What you expected to happen

It should work like before wgpu 0.8

## What actually happened

It panics with `Error in Buffer::get_mapped_range: buffer range size invalid: range_size 42 must be multiple of 4`.

**Comment by RedlineTriad** [comment]
Is this related to: #156?

**Comment by geckoxx** [comment]
Yes it seems so, but the mentioned commit is not part of any branch 🤔

**Comment by geckoxx** [comment]
is fixed with wgpu 0.8.1

**Comment by RedlineTriad** [comment]
@geckoxx I am not sure but can the issue I linked also be closed again?

**Comment by geckoxx** [comment]
yes, it was the same issue
