### ISSUE TITLE
SystemParam with only ignored parameters

### ISSUE THREAD

**Issue by CGMossa** [bevyengine/bevy#2125]
I wanted to add a system parameter that contains to fields that should not be part of the ECS.
The `SystemParam`-macro has an option to mark fields as `#[system_param(ignore)]` to do this.

But then the `SystemParam` requires a lifetime. Find, so I got a tip that the equivalent to
`PhantomData` but for lifetimes is `PhantomData<&'a ()>`, e.g.

```rust
#[derive(SystemParam)]
pub struct ActiveSurveillance<'a> {
    _secret: PhantomData<&'a ()>,
    #[system_param(ignore)]
    detection_rate: f64,
}
```

Anyways, this doesn't work at all:

```rust
error[E0277]: the trait bound `PhantomData<&'a ()>: SystemParam` is not satisfied
  --> src\regulator_active_surveillance.rs:19:10
   |
19 | #[derive(SystemParam)]
   |          ^^^^^^^^^^^ the trait `SystemParam` is not implemented for `PhantomData<&'a ()>`
   |
```

So anyways, anyone got a tip for this?

By the way, I still think that `SytemParam` from `bevy::ecs::system` should be included in the `prelude`-module.

**Comment by mockersf** [comment]
didn't try, but the `#[system_param(ignore)]` go over the param to ignore, not under

**Comment by alice-i-cecile** [comment]
The following snippet fails:

```rust
use bevy::ecs::system::SystemParam;
use std::marker::PhantomData;

fn main() {}

#[derive(SystemParam)]
pub struct ActiveSurveillance<'a> {
    #[system_param(ignore)]
    _secret: PhantomData<&'a ()>,
    #[system_param(ignore)]
    detection_rate: f64,
}
```

The errors are:

> use of undeclared lifetime name `'w`
> use of undeclared lifetime name `'s`

**Comment by alice-i-cecile** [comment]
Closing as a duplicate of #2711 now that it's been reproduced and investigated.
