### ISSUE TITLE
Add safety check in QueryState::new_archetype

### ISSUE THREAD

**Issue by BoxyUwU** [bevyengine/bevy#2128]
In QueryState::validate_world_and_update_archetypes we check that the world used to populate the matching archetypes/tables is the world associated with the QueryState- we dont do this for QueryState::new_archetype which while shouldnt be necessary- caused a subtle, hard to track down bug for someone hacking a `OtherWorldQuery` onto bevy_ecs. We probably ought to add a small check that the `Archetype` passed into `QueryState::new_archetype` is from the same world as `QueryState.world_id`

**Comment by james7132** [comment]
Is this still relevant? `QueryState::validate_world_and_update_archetypes` doesn't seem to exist anymore.

**Comment by galkowskit** [comment]
In the `new_archetype` I don't see any obvious way to get the `world.id()`. We only have `QueryState.world_id` but nothing to compare it to.

**Comment by targrub** [comment]
@BoxyUwU Could you comment on the present state of this issue?  Should it be closed?  Is it ready for implementation?

**Comment by BoxyUwU** [comment]
this issue is kind of out of date yeah, the footgun still remains about `QueryState::new_archetype` though. I am not immediately coming to a conclusion of what would be good way of fixing this
