### ISSUE TITLE
Input error when using shortcut keys in windows10

### ISSUE THREAD

**Issue by iijunxz** [bevyengine/bevy#2129]
## Bevy version

0.5.0

## Operating system & version

Windows10

## What you did

Run

```rust
use bevy::{
    input::Input,
    prelude::{App, IntoSystem, KeyCode, Res},
    DefaultPlugins,
};
fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_system(sys.system())
        .run();
}
fn sys(input: Res<Input<KeyCode>>) {
    input.get_pressed().for_each(|x| println!("{:?}", x));
}
```

And press LWin+Space

## What you expected to happen

Program stop printing after release keys.

## What actually happened

After release keys,it still printing "LWin".

## Additional information

It stops printing after press LWin and then select the window.

**Comment by iijunxz** [comment]
The reason is when pressing LWin+space, the window lose focus, so bevy can't detect the key release.The same problem also happened when using other shortcuts.

**Comment by cart** [comment]
I'm guessing this is related to #2068
