### ISSUE TITLE
Issue build error on warnings

### ISSUE THREAD

**Issue by GabLotus** [bevyengine/bevy#213]
In the spirit of keeping the bevy codebase awesome, we should issue errors on warnings.

**Comment by Ratysz** [comment]
Perhaps *some* warnings, not all of them? This alleviates the risk of new Rust version introducing new warnings and breaking builds of all client apps, until they downgrade their compiler or a new Bevy version addresses the new warnings.

One does not have to turn a yellow line into a red one to stop ignoring it.

**Comment by multun** [comment]
That's unfortunately a huge no-no of building, for the reason mentionned above: the project should still build with newer compilers

**Comment by multun** [comment]
There's a PR to add clippy to the CI, which ensures code with compiler and linter warnings can't be merged

**Comment by karroffel** [comment]
I think the idea is to do this only on CI, so users or even developers will be unaffected. This would only concern checking in code into this repository (which then needs to be made sure compiles on the used toolchain).

This might go well together with a MSRV commitment where Rust version updates are considered breaking changes (to the MSRV at least) and might need fixes for the new warnings too, but again *would not affect users*.

**Comment by coltontcrowe** [comment]
> 
> 
> There's a PR to add clippy to the CI, which ensures code with compiler and linter warnings can't be merged

Here's the PR mentioned above: #206

**Comment by Moxinilian** [comment]
Implemented in #206
