### ISSUE TITLE
SystemSet - Ordering with labels

### ISSUE THREAD

**Issue by Geams** [bevyengine/bevy#2131]
## Bevy version

0.5

## Operating system & version

Windows 10 64bit

## What you did
I create gobal ressources in one system and access them in another system, both system are in the same SystemSet
`.add_system_set(
            SystemSet::on_enter(AppState::MainMenu)
            .with_system(main_menu::setup.system().label("uisetup"))
            .with_system(main_menu::spawn_ui.system().after("uisetup"))
        )`

Reddit: [SystemSet - Ordering with labels](https://www.reddit.com/r/bevy/comments/n7shxx/systemset_ordering_with_labels/)

## What you expected to happen

I expect the  system `spawn_ui` to run after the system `setup` .

## What actually happened

Ressource not found by the 2nd  system:
 `thread 'main' panicked at 'Requested resource does not exist: my_game::main_menu::BtnMaterials'`

## Additional information
Please check my reddit post (link above).

**Comment by MinerSebas** [comment]
Commands are only processed at the end of a Stage.
There are three possible Solutions here:
* Either initialize the Resource earlier (in appbuilder, startup system)
* move your `main_menu::setup` to an earlier stage
* request a `Option<Res<T>>`, which doesn't Panic compared to a `Res<T>`.

**Comment by TheRawMeatball** [comment]
I'd recommend adding a in-between state: many states can be traversed within a single state, and states flush commands after entry and exit.

**Comment by Geams** [comment]
Ok, just learned that system ordering within the same state, e.g.  `CoreStage::Update` has no impact with commands.
So this is by design and not a bug, sorry.

**Comment by alice-i-cecile** [comment]
Yep :) It could definitely be more clearly documented and taught though; this is a common beginner stumbling block.
