### ISSUE TITLE
[wasm] Attempting to get an EventWriter for an unregistered event type panics with an unhelpful message

### ISSUE THREAD

**Issue by lukewestby** [bevyengine/bevy#2138]
## Bevy version

0.5.0

## Operating system & version

wasm

## What you did

1. Create a system like so:
```
struct Event;

fn system(mut events: EventWriter<Event>) {}
```

Set up the app, but do not register the event
```
App::build()
    .with_system(system.system())
    .run();
```

## What you expected to happen

The application is misconfigured so I expect this to panic, and ideally the message for the panic would explain that a system attempted to fetch an `EventWriter` for an unregistered event type.

## What actually happened

The application panics with the following:
```
panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex',

## Additional information

Any additional information you would like to add such as screenshots, logs, etc.

**Comment by lukewestby** [comment]
idk what happened here. github bug, maybe.

**Comment by alice-i-cecile** [comment]
Re-opening, since this isn't actually resolved.

That's an exceptionally unhelpful error message; I'd like to see if we can improve that.

**Comment by lukewestby** [comment]
@alice-i-cecile i closed this one because github double-submitted my issue. this one is a duplicate of #2139.
