### ISSUE TITLE
Add generic systems example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2142]
## How can Bevy's documentation be improved?

Generic systems (like those created with `AppBuilder::add_event<T>`) are a powerful but non-obvious abstraction for repeating functionality across many related types.

Bevy should have an example demonstrating how to create systems that accept type parameters, and how to register multiple of them to an app. 

I've provided a loose example on [Discord](https://discord.com/channels/691052431525675048/742569353878437978/841428238274002956), and the [Cheatbook page](https://bevy-cheatbook.github.io/patterns/generic-systems.html?highlight=generic#generic-systems) is another good place to borrow from.

The code itself should be quite easy to write following those examples; feel free to ping me if you want to tackle this and would like guidance.

**Comment by AmrDhaliwal** [comment]
HI @alice-i-cecile,
I am new here and would like to tackle this.

**Comment by alice-i-cecile** [comment]
Awesome :) Feel free to comment here / on your PR or over in #dev-general on Discord if you need any help.

**Comment by willolisp** [comment]
Hello there! Anyone currently working on this one? If not, can I?

**Comment by Ratysz** [comment]
#2191, #2636. You're welcome to try youself, though, seeing as both seem to be abandoned.

**Comment by mockersf** [comment]
I don't think it's fair calling #2636 abandoned, with it being only 20-ish days old and given our current backlog... first look seems good, maybe you could help review it? 🙂

**Comment by james7132** [comment]
Looks like this was completed as of #2636 and just forgot to link the issue to the PR. Closing this out now.
