### ISSUE TITLE
Events should use .extend internally

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2146]
Should improve perf due to better memory allocation vs repeatedly pushing.

See https://github.com/bevyengine/bevy/pull/2145#discussion_r630544462 by @NathanSWard for more details.

If you want to tackle this, either wait until #2145 is merged or work off that branch, as it changes the code organization of that file.

**Comment by NathanSWard** [comment]
I have a branch for this but will wait until #2145 either gets merged or becomes a little more stable :)

**Comment by NathanSWard** [comment]
This was fixed by #2149
