### ISSUE TITLE
Make on SystemSet .with_run_criteria() work with ShouldRun input

### ISSUE THREAD

**Issue by bayswaterpc** [bevyengine/bevy#2151]
## What problem does this solve or what need does it fill?
Making with_run_criteria() easier to use with ShouldRun outputs directly.  Currently I am able to access more complex should run states with FixedTimestep like so

```rust code blocks
fn food_timestep_system_set() -> SystemSet {
    SystemSet::new()
        .with_run_criteria(
            FixedTimestep::step(1.0 as f64).chain(
                (|In(input): In<ShouldRun>, state: Res<State<AppState>>| {
                    if state.current() == &AppState::Snake {
                        input
                    } else {
                        ShouldRun::No
                    }
                })
                .system(),
            ),
        )
        .with_system(food_spawner.system())
}
```

but I don't see any way to accomplish this without FixedTimestep  conditions

## What solution would you like?

Add an implimentation for with_run_criteria() which can take a ShouldRun parameter and not just IntoRunCriteria impl

so

```rust code blocks
    pub fn with_run_criteria<Marker>(mut self, run_criteria: ShouldRun) -> Self {
        self.run_criteria = Some(run_criteria.into());
        self
    }
```

or create an impl of IntoRunCriteria for ShouldRun

## What alternative(s) have you considered?

Looked into creating my own RunCriteria object but it doesn't look like the api has anything for directly creating a run_criteria
[run_criteria.rs](https://github.com/bevyengine/bevy/blob/3af3334cfeb551782cc5b33389d6a9898908e170/crates/bevy_ecs/src/schedule/run_criteria.rs)

Looked into the src\time\fixed_timestep.rs step() function to see how it satisifies the  IntoRunCriteria() impl, but couldn't find IntoRunCriteria impl in that file

## Additional context
The code block I'm trying to make work

```rust code blocks
fn snake_state_shouldrun(In(input): In<ShouldRun>, state: Res<State<AppState>>) -> ShouldRun {
    if state.current() == &AppState::Snake {
        input
    } else {
        ShouldRun::No
    }
}

fn post_update_system_set() -> SystemSet {
    SystemSet::new()
    .with_run_criteria(snake_state_shouldrun.system())
    .with_system(position_translation.system())
    .with_system(size_scaling.system())
}
```

And it is getting used in this app builder which is trying to add a minigame, to an egui hub which can demo the many bevy minigames which are out in the wild [bevy_egui_paneled_playground](https://github.com/bayswaterpc/bevy_egui_paneled_playground)

```rust code blocks
pub fn add_snake(app: &mut AppBuilder) {
    App::build()
        .insert_resource(SnakeSegments::default())
        .insert_resource(LastTailPosition::default())
        .add_event::<GrowthEvent>()
        .add_event::<GameOverEvent>()
        .add_system_set(
            SystemSet::on_enter(AppState::Snake)
            .with_system(setup.system())
            .with_system(spawn_snake.system())
        )
        .add_system_set(
            SystemSet::on_update(AppState::Snake)
            .with_system(snake_movement_input
                .system()
                .label(SnakeMovement::Input)
                .before(SnakeMovement::Movement))
            .with_system(game_over.system().after(SnakeMovement::Movement))
        )
        .add_system_set(snake_timestep_system_set())
        .add_system_set(food_timestep_system_set())
        .add_system_set_to_stage(
            CoreStage::PostUpdate,
            post_update_system_set(),
        )
        .add_system_set(
            SystemSet::on_exit(AppState::Breakout)
            .with_system(game_state_teardown.system())
        );
}

```

Yields the following error

```
error[E0277]: the trait bound `FunctionSystem<ShouldRun, ShouldRun, (bevy::prelude::Res<'_, bevy::prelude::State<AppState>>,), InputMarker, &for<'r> fn(bevy::prelude::In<ShouldRun>, bevy::prelude::Res<'r, bevy::prelude::State<AppState>>) -> ShouldRun {snake_state_shouldrun}>: IntoRunCriteria<_>` is not satisfied
   --> src\bevy_minigames\snake.rs:397:24
    |
397 |     .with_run_criteria(snake_state_shouldrun.system())
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `IntoRunCriteria<_>` is not implemented for `FunctionSystem<ShouldRun, ShouldRun, (bevy::prelude::Res<'_, bevy::prelude::State<AppState>>,), InputMarker, &for<'r> fn(bevy::prelude::In<ShouldRun>, bevy::prelude::Res<'r, bevy::prelude::State<AppState>>) -> ShouldRun {snake_state_shouldrun}>`

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0277`.
error: could not compile `bevy_egui_paneled_playground`
```

Maybe I'm approaching this wrong but API I'm proposing seems intuitive

**Comment by TheRawMeatball** [comment]
Hmm, first off - can you please use \`\`\`rust code blocks?

Then, I'm not sure what this API accomplishes. What does the input to the `snake_state_shouldrun` mean? Where would it come from? If you just want to make an independent run criteria, you need to omit the `In` since there's no one to give it an input. If you want to make a run criteria that depends on another, you can use `.pipe` and run criteria labels, or you can use .chain like you do with FixedTimestep. And also, what would implementing `IntoRunCriteria` for `ShouldRun` accomplish? the AppBuilder is only invoked once at startup, meaning the systems will either always run or never run - in which case just putting an if block that conditionally adds the systems is much easier.

**Comment by bayswaterpc** [comment]
Thanks for the ```rust code blocks tip game changer.

The stated logic of `snake_state_shouldrun` is specific to the app which I'm working on where you're flipping between different minigames / bevy apps.

![gameSwitching](https://user-images.githubusercontent.com/78702667/117992080-a1c5b400-b30c-11eb-8dfd-203af03969e4.gif)
The main app logic is like so
```rust code blocks
fn main() {
    let mut app = AppBuilder::default();
    app.add_plugins(DefaultPlugins)
        .add_plugin(EguiPlugin)
        .add_state(AppState::CentralPanelState)
        .add_system(egui_ui.system());

    add_breakout(&mut app);
    add_contributors(&mut app);
    add_snake(&mut app);
    app.run();
}

```

 I always want the systems loaded into the app, but I only need them running when I've set the app state to play that game.

For most of the other systems I use the `SystemSet::on_update`, `SystemSet::on_enter` etc.. but since the call for the ` post_update_system_set() ` is going into        ` .add_system_set_to_stage(CoreStage::PostUpdate, ...` I don't know if that will hold up.

So the meaning of `snake_state_shouldrun` is only to apply this system set in the `CoreStage::PostUpdate` when the AppState is on Snake.

Thanks for the tip on the "omit the `In`"

For using `chain` with this logic I don't have any other checks aside from checking my custom `AppState`, so I don't what I can chain it to.

For using `pipe` with labelled run criteria, I'm not sure how I'd do that with the `CoreStage::PostUpdate`. 

 I tried to lay out an equivalent setup following the format laid out in the announcement [example](https://bevyengine.org/news/bevy-0-5/) using pipe I get build errors.
```rust code blocks
        .add_system(
            position_translation
            .with_run_criteria("dummyLabel".pipe(snake_state_shouldrun.system()))
        )
        .add_system(
            size_scaling
            .with_run_criteria("dummyLabel".pipe(snake_state_shouldrun.system()))
        )
```
```
error[E0271]: type mismatch resolving `<FunctionSystem<(), ShouldRun, (bevy::prelude::Res<'_, bevy::prelude::State<AppState>>,), (), &for<'r> fn(bevy::prelude::Res<'r, bevy::prelude::State<AppState>>) -> ShouldRun {snake_state_shouldrun}> as bevy::prelude::System>::In == ShouldRun`
   --> src\bevy_minigames\snake.rs:428:54
    |
428 |             .with_run_criteria("bogus doesn't exist".pipe(snake_state_shouldrun.system()))
    |                                                      ^^^^ expected `()`, found enum `ShouldRun`

error: aborting due to 3 previous errors; 1 warning emitted
```

So in my use case of always having the system added, trying to add a set of systems to conditionally run on a CoreStage, having an easy `ShouldRun` api which works with `SystemSet::with_run_criteria`  would be excellent.

**Comment by TheRawMeatball** [comment]
The thing is, I don't think you fully understand how should run works - if a system is added, it will run as long as it's run criteria evaluates to saying yes. Here's a nice resource for this btw: https://bevy-cheatbook.github.io/programming/run-criteria.html. The thing is, there isn't a sensible way where a static `ShouldRun` dictates control flow. And your use case is actually pretty easily solved by just removing the `In` like this: 
```rust
fn snake_state_shouldrun(state: Res<State<AppState>>) -> ShouldRun {
    if state.current() == &AppState::Snake {
        ShouldRun::Yes
    } else {
        ShouldRun::No
    }
}
```
So I still don't understand what you're trying to do with a new API.
