### ISSUE TITLE
gltf extras component

### ISSUE THREAD

**Issue by bytebuddha** [bevyengine/bevy#2153]
## What problem does this solve or what need does it fill?

In my game i would like to store a few variables in the gltf "extras" field in blender and use them to set physics properties on the created entities.

## What solution would you like?

Create a struct to store extras data, something like:
```rust
pub struct GltfExtras(pub serde_json::Map<String, serde_json::Value>)
```
and add it when creating entities in the gltf loader. I'm not sure as to what the best type to store the data would be,
according to the [gltf spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#extras) they should be represented as an object whenever possible, so either a hashmap or something similar.

## What alternative(s) have you considered?

I don't think there is another way to do this, but i would like suggestions if there are.

**Comment by bjorn3** [comment]
An alternative would be to register extras with the gltf loadet such that every extra results in a typed component specific for such extra. This would be similar to `app.register_type::<C>()` that allows deserializing .ron scenes to concrete components.

**Comment by bytebuddha** [comment]
Yeah that would work. 
Now that you mention it all of these types would have to have `register_type<T>()` called on them already in order
to be used with in a '$scene.ron' file correct?
In that case would it be possible for the gtlf loader and just load each extra against the types
registered with the scene type registry?

I'm very new to bevy so forgive me if that isn't phrased correctly

**Comment by mockersf** [comment]
Could you share a GLTF file with those extra set?

**Comment by bytebuddha** [comment]
The One i'm working on is very large so i made a simple example file of a cube with 1 'String' property and 1 array property. (As well as one from blenderkit). I have no problem sharing the larger one if that helps it but only has a single property set on one of the mesh objects.

Github wouldn't let me upload a gltf file so here it is as txt.
[custom_prop.txt](https://github.com/bevyengine/bevy/files/6468908/custom_prop.txt)

I'm not sure exactly what schema i would use for now i only want to create simple Colliders with rapier3d
