### ISSUE TITLE
Finer control over the `DefaultTaskPoolOptions`

### ISSUE THREAD

**Issue by ElliotB256** [bevyengine/bevy#2163]
## What problem does this solve or what need does it fill?

I would like finer control over the thread pool and I'm not sure how to modify the `DefaultTaskPoolOptions` to achieve this.
Following the examples, it seems I can use some methods to create a `DefaultTaskPoolOptions`, e.g.:
```
DefaultTaskPoolOptions::with_num_threads(4)
```
but this doesn't provide enough flexibility to e.g. disable the `io` pool or change the ratio of `async_compute` to `compute` threads.

I can create a `DefaultTaskPoolOptions` struct, but assigning values to some of the fields is not possible.
The `task_pool_options` mod in the core lib is not marked as pub, which prevents defining e.g. a `TaskPoolThreadAssignmentPolicy`.
Ideally, I would do something like:
```
    let mut pool = DefaultTaskPoolOptions::default();
    pool.io = bevy::core::task_pool_options::TaskPoolThreadAssignmentPolicy { min_threads: 0, max_threads: 2, percent: 0.2};
```

## What solution would you like?

Define the `task_pool_options` mod as `pub` to allow construction of a `DefaultTaskPoolOptions` with all fields defined.

## What alternative(s) have you considered?

Alternatively, there could be more methods for the `DefaultTaskPoolOptions` which modifies the `compute`, `async_compute` and `io` pools. Perhaps a `DefaultTaskPoolBuilder` could provide a way to configure a `DefaultTaskPoolOptions`?

**Comment by TanTanDev** [comment]
I agree!
I'm currently only utilizing an AsyncComputeTaskPool, and I would greatly benefit if I could increase the threads it's using.
Since my computer only allows for 4 threads, I only ever get to utilize 1 thread since AsyncComputeTaskPool is assigned 25% threads.

Opening up customization would greatly benefit my project I believe.

**Comment by bjorn3** [comment]
All fields are already public. `DefaultTaskPoolOptions` is also exported so you can do something like `pool.io.min_threads = 0;`. I do agree that `TaskPoolThreadAssignmentPolicy` should be exported too.

**Comment by TanTanDev** [comment]
II see, so this is what we currently have to do to modify the `DefaultTaskPoolOptions`
```
    let mut task_pool_settings = DefaultTaskPoolOptions::default();
    task_pool_settings.async_compute.percent = 1.0f32;
    task_pool_settings.compute.percent = 0.0f32; // i currently only use async_compute
    task_pool_settings.io.percent = 0.0f32; // always use 1
    .... app setup code
    .insert_resource(task_pool_settings)
```
I don't think that is the most 'elegant' way to write it, if the `TaskPoolThreadAssignmentPolicy` was pub in the namespace
We would then be able to write it this way:
```
        .insert_resource(DefaultTaskPoolOptions{
            async_compute: TaskPoolThreadAssignmentPolicy{
                min_threads: 1,
                max_threads: 4,
                percent: 0.25,
            },
            ..Default::default()
        })
```
I guess we can get around it by doing the first method, but I feel like the second way is more what I would expect.
