### ISSUE TITLE
thread 'main' panicked at 'Stage 'Startup' does not exist or is not a SystemStage'

### ISSUE THREAD

**Issue by yzt123** [bevyengine/bevy#2164]
## Bevy version

0.5

## Operating system & version

Windows 10 LTSC 1809

## What you did
```
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_system_to_stage(CoreStage::Startup, startup_system.system())
        .run();
}

fn startup_system() {
    println!("startup");
}
```

## What you expected to happen

`startup_system` should run in `CoreStage::Startup` stage, then print "startup" once, like `StartupStage::Startup`.

## What actually happened

thread 'main' panicked at 'Stage 'Startup' does not exist or is not a SystemStage'.

**Comment by cart** [comment]
The Startup stage is a Schedule, not a SystemStage. It has multiple sub-stages. Either use `app.add_startup_system(startup_system.system())` or get access to the startup Schedule like this method does;

```rust
    pub fn add_startup_system_to_stage(
        &mut self,
        stage_label: impl StageLabel,
        system: impl Into<SystemDescriptor>,
    ) -> &mut Self {
        self.app
            .schedule
            .stage(CoreStage::Startup, |schedule: &mut Schedule| {
                schedule.add_system_to_stage(stage_label, system)
            });
        self
    }
```

**Comment by alice-i-cecile** [comment]
I'm going to close this as user-error for now <3 Totally understandable, given the sparse documentation. I'd suggest we work on making that clearer, but I don't think our existing stage API has long left for this world.
