### ISSUE TITLE
Add parallel iteration benchmarks

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2173]
https://github.com/ElliotB256/bevy_bench/issues/2 reveals that while Bevy can be quite competitive with the performance of other Rust ECS backends it's parallel iteration performance is quite poor.

This is likely to be particularly true with unpredictable workloads.

Once we have a good benchmark suite for this we can work on improving the performance in other issues.

**Comment by mockersf** [comment]
bench from https://github.com/ElliotB256/bevy_bench/blob/master/examples/bevy.rs looks not that far from https://github.com/cart/ecs_bench_suite/blob/bevy-benches/src/bevy/heavy_compute.rs, are there specific things to add?

**Comment by alice-i-cecile** [comment]
Adding that benchmark suite to Bevy itself will help reduce the need for this issue for sure.

The other concern that I have is that perfectly predictable and uniform workloads like those shown in both of those examples are not always representative and will underestimate the potential gains of more sophisticated strategies.

Parallel pathfinding might be a good example of an unpredictable but highly parallelizable task to supplement the example you linked.

**Comment by ElliotB256** [comment]
Is it worth noting that my bench is using a simpler operation - e.g. multiplying a couple of floats, instead of inverting a matrix 100 times? Each parallel task is much smaller.

**Comment by alice-i-cecile** [comment]
Yep: ideally we could vary the weight of the tasks to try and assess the relative overhead in each engine.

**Comment by ElliotB256** [comment]
I'd be happy to make a PR for adding some benchmarks for this issue

**Comment by ElliotB256** [comment]
Apologies I was away from this for so long.

I've added an example of a `parallel_light_compute` benchmark to https://github.com/ElliotB256/ecs_bench_suite/tree/parallel_light_compute. This benchmark is for the case where some very short task must be performed for each entity - a realistic example would be updating position of an entity based on velocity. It compares to the existing `heavy_compute` benchmark as follows:
| Benchmark | Description |
|-------------|-------------|
| `heavy_compute` | 1,000 entities. Parallel iter inverts a matrix 100 times. |
| `parallel_light_compute` | 10,000 entities. Parallel iter inverts a matrix once. |

The numbers on my PC are as follows:
| Benchmark | time |
|-------------|------|
| [parallel_light_compute/legion](https://github.com/ElliotB256/ecs_bench_suite/blob/parallel_light_compute/target/criterion/parallel_light_compute/legion/report/index.html) | 106.60 us |
| [parallel_light_compute/legion (packed)](https://github.com/ElliotB256/ecs_bench_suite/blob/parallel_light_compute/target/criterion/parallel_light_compute/legion%20(packed)/report/index.html) | 112.58 us |
| [parallel_light_compute/bevy](https://github.com/ElliotB256/ecs_bench_suite/blob/parallel_light_compute/target/criterion/parallel_light_compute/bevy/report/index.html) | 1.0066 ms |
| [parallel_light_compute/hecs](https://github.com/ElliotB256/ecs_bench_suite/blob/parallel_light_compute/target/criterion/parallel_light_compute/hecs/report/index.html) | 100.08 us |
| [parallel_light_compute/shipyard](https://github.com/ElliotB256/ecs_bench_suite/blob/parallel_light_compute/target/criterion/parallel_light_compute/shipyard/report/index.html) | 142.53 us |
| [parallel_light_compute/specs](https://github.com/ElliotB256/ecs_bench_suite/blob/parallel_light_compute/target/criterion/parallel_light_compute/specs/report/index.html) | 108.00 us |

**Comment by ElliotB256** [comment]
The batch size used for bevy in the above tests was 64. Changing to a batch size of 1024 offers an improvement to `907.58us`, but still behind the other libraries.

For different batch sizes:
| Batch Size | Time |
|------------|-------|
| 8 | 1.9473ms |
|  64 |  1.0444ms  |
| 256 | 1.0048ms |
| 1024 |  960.13us |
| 4096 | 1.0296ms |
| 10,000 | 1.2633ms |

It's not clear to me what the equivalent batch size is for the other tests. legion and specs (maybe the others too?) use rayon for parallel iteration, but I'm unfamiliar with the internals. Some information claims by default it splits every time (see e.g. [this PR](https://github.com/rayon-rs/rayon/pull/260) and [this SO](https://stackoverflow.com/questions/54605692/will-rayon-avoid-spawning-threads-for-a-small-amount-of-work) - but that doesn't seem quite right, and the [Rayon](https://github.com/rayon-rs/rayon) page says:
> Parallel iterators take care of deciding how to divide your data into tasks; it will dynamically adapt for maximum performance.

**Comment by ElliotB256** [comment]
@mockersf pointed out on discord that my example was creating a new task pool every iteration. Changing it so the task pool is initialised before hand, the results are:

| Batch Size | Time |
|------------|-----|
| 8 | 1.177ms | 
| 64 | 234.13us |
| 256 | 149.48us |
| 1024 | 130.48us |
| 4096 | 207.13us |
| 10,000 | 485.55us |

This is much better. It is still not quite as good as the others, but at optimum batch sizes bevy is at least competitive.

**Comment by ElliotB256** [comment]
https://github.com/ElliotB256/ecs_bench_suite/commit/0ad6a442b70f9819b837a543cef1bbf5d80d1400

**Comment by ElliotB256** [comment]
By chance I just saw on the discord:
> iamseb: I'm trying to run query.par_for_each across a large set of entities, and noticing that my CPU is only engaging half my available cores. I tried running https://github.com/bevyengine/bevy/blob/main/examples/async_tasks/async_compute.rs and setting the sleep timer to 1 sec for all tasks and noticed the same thing, with the example taking twice the expected time to run. In previous versions of bevy that used rayon it would max out the CPU. Is this a design decision, or is there some config I'm missing for the task scheduler?
> MinerSebas: Bevy splits has three diferent Thread pools which together use the whole CPU .(https://github.com/bevyengine/bevy/blob/main/crates/bevy_core/src/task_pool_options.rs#L56-L81).
You can adjust the used ratios by inserting the DefaultTaskPoolOptions Resource before adding the default plugins.

Does anyone know if this is relevant for the benchmark?

**Comment by ElliotB256** [comment]
Checked and it isn't, All cores used in profiler.

```
use bevy_ecs::prelude::*;
use bevy_tasks::TaskPool;
use cgmath::*;

#[derive(Copy, Clone)]
struct Position(Vector3<f32>);

#[derive(Copy, Clone)]
struct Rotation(Vector3<f32>);

#[derive(Copy, Clone)]
struct Velocity(Vector3<f32>);

pub struct Benchmark(World, TaskPool);

fn main() {
    
    let mut world = World::default();

        world.spawn_batch((0..10_000).map(|_| {
            (
                Matrix4::<f32>::from_angle_x(Rad(1.2)),
                Position(Vector3::unit_x()),
                Rotation(Vector3::unit_x()),
                Velocity(Vector3::unit_x()),
            )
        }));

    let pool = TaskPool::new();
    
    for _ in 0..100_000 {
        let mut query = world.query::<(&mut Position, &mut Matrix4<f32>)>();    
        query.par_for_each_mut(&mut world, &pool, 1024, |(mut pos, mut mat)| {
            *mat = mat.invert().unwrap();
            pos.0 = mat.transform_vector(pos.0);
        });
    }
}
```

![image](https://user-images.githubusercontent.com/7041164/143687483-08629c97-8c1e-4e29-bf67-cd8e0792b95a.png)
![image](https://user-images.githubusercontent.com/7041164/143687494-f243e615-cb15-4279-b90f-3d54df05104f.png)
![image](https://user-images.githubusercontent.com/7041164/143687512-cb91f41b-43ff-4f73-b4ef-ba815f785391.png)

**Comment by james7132** [comment]
With the inclusion of cart's ecs_bench_suite in #4225, do we need to cover this more? `busy_systems`, `contrived`, and `heavy_compute` seems to cover it fairly well already.
