### ISSUE TITLE
add DirectionalLightBundle similar to PointLightBundle

### ISSUE THREAD

**Issue by jakobhellermann** [bevyengine/bevy#2184]
## What problem does this solve or what need does it fill?

The PR https://github.com/bevyengine/bevy/pull/2112 added the `DirectionalLight` component, but in order to use it you need to spawn an entity with a `Transform`, `GlobalTransform` and `DirectionalLight`. This is cumbersome and can difficult to understand for an unexperienced bevy user.

## What solution would you like?

A `DirectionalLightBundle` should be added similar to the `PointLightBundle`:
https://github.com/bevyengine/bevy/blob/cf221f9659127427c99d621b76c8085c4860e2ef/crates/bevy_pbr/src/entity.rs#L43-L49

**Comment by HAL22** [comment]
Hey, new to rust. Will take a look at this

**Comment by mnmaita** [comment]
This issue should be closed since there's now a [DirectionalLightBundle](https://github.com/bevyengine/bevy/blob/add1818a05ad4b8d4672197afd477ab29f8446b5/crates/bevy_pbr/src/bundle.rs#L70-L78) struct.
