### ISSUE TITLE
Commands doesn't seem to work inside of a SystemParam.

### ISSUE THREAD

**Issue by StarArawn** [bevyengine/bevy#2188]
## Bevy version
0.5.0

## Operating system & version
Windows 10

## What you did
I have a small working demo here:
https://github.com/StarArawn/bevy-commands-bug

## What you expected to happen
Commands should spawn an entity?

## What actually happened
Commands doesn't spawn the entity.

## Additional information
N/A

**Comment by TheRawMeatball** [comment]
This was fixed in #1899.

**Comment by DJMcNab** [comment]
Closing as a duplicate of #1896
