### ISSUE TITLE
Headless rendering to images

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#22]
The RenderGraph should already be able to handle headless rendering scenarios. The only missing pieces are:

* Adapt WindowTextureNode to a TextureNode, which produces a texture output for configured dimensions instead of window dimensions
* Write code to copy texture data from the gpu to an image file so headless rendering can be verified

**Comment by rmsc** [comment]
It definitely does: https://github.com/mrk-its/bevy/tree/render_to_texture and https://github.com/rmsc/bevy/tree/render_to_file.

There are however a few open questions, namely:

- The camera system expects a WindowId. Maybe change that to an Enum to also support a TextureId?
- There is a Res<Windows> for WindowId-to-Window mapping, perhaps there should also be one for TextureId -> Texture?
- To me it's not clear how to properly interface with the ECS to move the texture from the GPU to the CPU (possibly also related to #1234)

**Comment by alice-i-cecile** [comment]
Complete! See #1927.

**Comment by mockersf** [comment]
> Complete! See #1927.

Not really. It's not possible to render to an image file as the issue was saying

**Comment by DGriffin91** [comment]
I made a little [example](https://gist.github.com/DGriffin91/7478cfcc654176d202230758f7606c2d) of this awhile back. If it would be helpful, I could update it. 

> Write code to copy texture data from the gpu to an image file so headless rendering can be verified

Are we looking for an example or a test here?

**Comment by mockersf** [comment]
Nice!

Ideally we would need to have a nice api in Bevy to:
* move data from gpu to cpu
* move data from render app to main app

**Comment by hymm** [comment]
Fixed in #7163

**Comment by mockersf** [comment]
@hymm does it work in headless mode? this issue was kept for that

**Comment by hymm** [comment]
probably not. will reopen.

**Comment by bes** [comment]
Hello! Would this also cover the case where a pure headless pipeline could be built by outputting to a OpenGL (or Vulkan) texture?

Specifically, I am looking to do something like

```
              -------
Texture  --> | Bevy | --> Texture
              -------
```

Where Texture is a native (OpenGL, Vulkan) texture that can be fed into Bevy and then I can get a native texture out of Bevy (I expect there to be some manual wgpu steps involved, too).

I guess wgpu needs to be able to handle native textures in / out (which I don't think it does currently).

So for the Bevy part I think what's most important is to be able to render to a texture (and not be limited to an image on file).

I already have custom, non-Bevy, pipeline doing this, but there are a lot of `unsafe { gl::... ` calls going on 😅, so getting this all into bevy would be a dream come true.

**Comment by jeertmans** [comment]
Hello! Is there any update on this?
I would be super interested in being able to use `bevy_image_export` in headless more :-)

**Comment by DGriffin91** [comment]
@jeertmans This PR https://github.com/bevyengine/bevy/pull/5550 runs without a window. It may or may not be a helpful reference.

**Comment by jeertmans** [comment]
Thanks, @DGriffin91! I'll take a look at it when I have some time :-)
I'm quite new to Bevy, so I might reach back to you for questions ^^'
