### ISSUE TITLE
Extremely unhelpful error messages on asset load failure

### ISSUE THREAD

**Issue by Algorhythm-sxv** [bevyengine/bevy#2201]
## Bevy version

0.5

## Operating system & version

Windows 10

## What you did

`asset_server.load("pieces/cburnett/bK100.png")`

## What you expected to happen

The image was loaded into memory and the texture displayed on the relevant sprite

## What actually happened

The image failed to load and this extremely unhelpful error message was emitted:

``WARN bevy_asset::asset_server: encountered an error while loading an asset: Error reading image file pieces/cburnett/bK100.png: failed to load an image, this is an error in `bevy_render`.``

## Additional information

The file `bK100.png` was created by opening `bK.png` (500px, also exported from GIMP) in GIMP, downscaling it to 100px and exporting as PNG. As far as I can tell the image properties (colour depth etc.) are all identical except the dimensions.

The original 500px image works correctly with `asset_server.load(...)`.

Both images are viewable in image viewing and editing software.

**Comment by mockersf** [comment]
I tried loading your image and got the following error with main:
```
May 17 21:21:28.753  WARN bevy_asset::asset_server: encountered an error while loading an asset: Error reading image file bk100.png: failed to load an image: Format error decoding Png: CRC error, this is an error in `bevy_render`.
```

So... good news is error message has already been improved, bad news is your image has a CRC error. Most software nowadays just ignore those errors, but we can't do much on Bevy side, we're dependent on https://github.com/image-rs/image for that

Re-exporting the image, it loads fine

your `bK100.png`:
![bK100](https://user-images.githubusercontent.com/8672791/118546989-05127480-b759-11eb-99d9-6a39218a5d3d.png)

**Comment by Algorhythm-sxv** [comment]
I see, I was running with `--release`, perhaps that removes information from the error?

**Comment by NathanSWard** [comment]
@mockersf was this also fixed by the solution to #2257 and if so are we ok to close this issue?

**Comment by mockersf** [comment]
> I see, I was running with `--release`, perhaps that removes information from the error?

No, the error message was improved in current git main, you'll have it in next version 🙂 

Were you able to fix your image?

**Comment by Algorhythm-sxv** [comment]
Opening the image in Paint 3D (because regular MS Paint doesn't support transparency) and re-exporting seemed to fix whatever CRC issue was breaking them earlier.
