### ISSUE TITLE
`More blocks deallocated than allocated` message

### ISSUE THREAD

**Issue by OfficialURL** [bevyengine/bevy#2232]
## Bevy version

Latest commit (653c10371e546176059bb779844c0569c0190b6b)

## Operating system & version

Windows 10

## What you did

I ran `cargo update`, which made `gpu-alloc` update to `0.4.6`, among other things.

## What you expected to happen

No noticeable changes in the application.

## What actually happened

Every time I close my application, the message in the title is printed to the console.

## Additional information

I've confirmed the message is coming from the `gpu-alloc` crate, and I've filed a [bug](https://github.com/zakarumych/gpu-alloc/issues/49) over there in case it's a problem within that crate. I'm posting here mostly so that others are aware of this issue.

**Comment by Ixentus** [comment]
Looks like it should be fixed already in `0.4.7`

**Comment by OfficialURL** [comment]
Yep, the latest version of `gpu-alloc` solves this issue for me.
