### ISSUE TITLE
Run criteria should be composable; states should act more like other run criteria

### ISSUE THREAD

**Issue by masonk** [bevyengine/bevy#2233]
## What problem does this solve or what need does it fill?

The 0.5 StatesV2 system is a huge leap forward, but it still has some weaknesses.

One of the biggest weaknesses is that it doesn't compose well with other run criteria.

To give an example, suppose a user wants to handle input on a `FixedTimeStep`, but differently on a per-state basis.

Today, it's not clear how to do that. It probably involves building a custom run criteria that manually composes the logic of FixedTimeStep and the logic of Statesv2. 

## What solution would you like?

I would like RunCriteria to become logically composable, so that:

- Users can group them
- Users can AND, OR, and NOT them

Additionally, to make the motivating use-case work, it would be necessary to expose state-based run criteria as regular run criteria so they can be composed with other run criteria.

**Comment by masonk** [comment]
If I have `Criteria1.And(Criteria2)` there's a table of possible states:

In the table I will omit the states where both returned the same thing, as then it's trivial that output should return that.

"Don't Check Again" beats CheckAgain.
No beats yes.

System1 ShouldRun | System2 ShouldRun | Output ShouldRun
---------------------------------------------------------------------
Yes | No | No
Yes | YesAndCheckAgain | Yes
Yes | NoAndCheckAgain | NoAndCheckAgain
No | NoAndCheckAgain | No

**Comment by Ratysz** [comment]
Combining criteria raised quite a few arguments a while ago... We settled on a minimal version for now, criteria [piping](https://docs.rs/bevy/0.5.0/bevy/ecs/schedule/struct.RunCriteria.html#method.pipe).

Criteria created by states are fully-interoperable with that, too: use the `State::on_update()` and similar methods that produce a criteria descriptor. It will also automatically make sure that you don't end up with multiple copies of the same state-related criteria hanging around in the stage by virtue of [this descriptor feature](https://docs.rs/bevy/0.5.0/bevy/ecs/schedule/trait.RunCriteriaDescriptorCoercion.html#tymethod.label_discard_if_duplicate).

We might eventually have built-in combinators, and/or piping in from arbitrary amounts of criteria without needing to express it all as a long "chain" of pipes. I don't think these plans are explicitly  documented anywhere, though. cc @TheRawMeatball?

**Comment by masonk** [comment]
It's not straightforward, but I think I found the rules that work.

So, how would you run a FixedTimeStep with State::on_update(GameState::InGame), today in bevy 0.5?

**Comment by Ratysz** [comment]
> I think I found the rules that work.

What about when the first system returns any of the `*AndCheckAgain` variants?

> So, how would you run a FixedTimeStep with State::on_update(GameState::InGame), today in bevy 0.5?

You would have to, unfortunately, partially [replicate](https://github.com/bevyengine/bevy/pull/1675/files#diff-94232711f7c793290a933e061078cd7f20eed60eed5d98a9da0e6df33a803e97R1442) the function of one of them to create a pipeable version. This is why we want to pipe from more than one criteria.

**Comment by masonk** [comment]
The problem with the piping is that it doesn't actually compose, right?

The system you pass to `pipe()` doesn't have the same function signature as system you'd install as a standalone run criteria.

**Comment by masonk** [comment]
> > I think I found the rules that work.
> 
> What about when the first system returns any of the `*AndCheckAgain` variants?
> 
> > So, how would you run a FixedTimeStep with State::on_update(GameState::InGame), today in bevy 0.5?

Flip the table. The logic commutes.

**Comment by Ratysz** [comment]
> Flip the table. The logic commutes.

Oh, right, we are talking about just `and`. Seems to check out so far.

> The problem with the piping is that it doesn't actually compose, right?

Not in a pleasant way, no.

I see two options here:
 * Generalize, then specialize: implement piping from arbitrary amount of criteria, then build some combinators on top of that.
 * Specialize, then generalize: implement some straightforward combinators, then consider generalizing them if/when we get arbitrary piping.

**Comment by masonk** [comment]
I think Yes & YesAndCheckAgain -> Yes is the most tendentious rule in the table. Everything else seems very clear to me but that might be a bad one that kills the whole idea.

**Comment by Ratysz** [comment]
It does make sense if we look at this combinator as strictly logical and - although, that doesn't check out for `Yes` && `NoAndCheckAgain` -> `NoAndCheckAgain`. Things like this is why we decided to omit built-in combinators back then.

**Comment by masonk** [comment]
I agree that automatic combinators is something that's quite hard to convince ourselves we can always get right and I support waiting on that (for now, but with experience we might get more confidence about what the correct truth table is (or learn that there isn't one).

But `pipe()` is just very limited in usefulness. It doesn't make even simple things easy.

If there were a way to just toss the logic over the wall to the dev and say, "here's two ShouldRuns; we don't know how to combine them, you combine them", that would be composable.

```rust

// These two systems are supplied by other crates, e.g. by Bevy core
fn a(..) -> ShouldRun {}
fn b(..) -> ShouldRun {}

// There is no way to pipe() a and b, they don't have the signature for that.
type CriteriaSystem = BoxedSystem<(), ShouldRun>;

fn merge(a: CriteriaSystem , b: CriteriaSystem , mergeFn: fn(ShouldRun, ShouldRun)  -> ShouldRun) -> CriteriaSystem {}


```

**Comment by Ratysz** [comment]
That's exactly what I'm referring to with "piping from arbitrary amount of criteria". The idea was to generalize the implementation to fully cover criteria with no piped input, criteria with one piped input, and criteria with N piped inputs.

**Comment by masonk** [comment]
I really like this approach. Rather than choosing one truth table we can offer combinators that implement different truth tables. And the user always has the choice of fully custom logic.

I think we only need to handle the case of merging two systems. You can handle everything that way.

**Comment by alice-i-cecile** [comment]
See also #1295. This is one of the larger pain points outside of areas that are simply missing functionality like UI, and seems to come up again and again. I'm going to add the high-impact label to this, in the hopes that we can work out a better solution in time for 0.6.

**Comment by masonk** [comment]
It occured to me that there's nothing really specific about run criteria in the merge function I proposed. It's just a way of combining two systems that don't fit into a pipeline. It could be generalized to this:

`fn compose_systems(a: BoxedSystem<(), A>, b: BoxedSystem<(), B>, by: fn(A, B) -> C) -> BoxedSystem<(), C>;`

(Or a macro that lets us do this for n systems).

When trying to articulate why I need bevy itself to do something, it's because I can't write a function that calls systems itself: bevy always calls them. All I can do is copypasta the logic inside the systems and run it myself in my own system. That's what painful about the current situation. So, another way to do a similar thing is to allow systems to call other systems inline. If I had that, I could roll my own combinator just by calling two systems myself and doing logic on their output(s). That would probably be the most general way to solve the problem. However that might be too far afield.

**Comment by alice-i-cecile** [comment]
Deduplicating in favor of #1295.
