### ISSUE TITLE
Add `With<Camera>` query filter to `many_sprites` example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2253]
https://github.com/bevyengine/bevy/blob/052094757aee671c66190b63a640900f15ee300d/examples/2d/many_sprites.rs#L76

We don't want to move *everything*, just the camera.

**Comment by mockersf** [comment]
the camera is the only entity with a `Position` component in the example

**Comment by minecrawler** [comment]
Apparently, the code is confusing, or there would be no issue. That's problematic, since the examples are most likely used to learn bevy! After taking a look, I too think that it's not directly clear how that query yields only the camera. Maybe a comment why the query is like this will help :)

**Comment by mockersf** [comment]
duplicate of #2075, fixed by #2078
