### ISSUE TITLE
bevy_asset WARN when loading .png

### ISSUE THREAD

**Issue by ThomasCaio** [bevyengine/bevy#2257]
I created a 100x100 square in Paint, saved it as a .png and tried to load it into bevy, but I got the following Warning

`[WARN bevy_asset :: asset_server: encountered an error while loading an asset: Error reading image file redsquare.png: failed to load an image, this is an error in 'bevy_render'.`

# Code
```
fn add_people(mut commands: Commands, asset_server: Res<AssetServer>, mut materials: ResMut<Assets<ColorMaterial>>) {
    let texture_handle = asset_server.load("redsquare.png");
    commands.spawn()
        .insert_bundle(SpriteBundle {
            sprite: Sprite {
                size: Vec2::new(100.0, 10.0),
                ..Default::default()
            },
            material: materials.add(texture_handle.into(),
            ),
            transform: Transform::from_xyz(10., 20., 0.),
            ..Default::default()
        });
```

Then, when I tried to load another .png from the [github](https://github.com/bevyengine/bevy/blob/main/assets/branding/icon.png) repository, it worked perfectly.

bevy = "0.5"
Windows 10

My redsquare.png
![redsquare](https://user-images.githubusercontent.com/35676825/119584809-cb1c2080-bd9f-11eb-8be7-2f37fea06b92.png)

**Comment by alice-i-cecile** [comment]
> I think I understand the problem. I hadn't created the file directly in Paint. I created the file using VsCode with a .png extension, edited and saved it with Paint. I did the same thing again and received the same Warning.

Cool, so it's a malformed file issue as I suspected. I wonder if we can repair this, or at least report a better error. Given that it *renders*, it sounds repairable.

**Comment by mockersf** [comment]
Message has been improved in current main:
```
WARN bevy_asset::asset_server: encountered an error while loading an asset: Error reading image file red.png: failed to load an image: Format error decoding Png: invalid signature, this is an error in `bevy_render`.
```

The png is not valid. In our case, it's done by https://github.com/image-rs/image that often rejects invalid files instead of trying it's best to render them.

Most browsers or image viewers often try their best to display even invalid image...

related to #2201 

In your case, your image is actually not a png but a bmp (try changing the extension and running with `--features bmp`)
