### ISSUE TITLE
Change Scale component from Scale(f32) to Scale(Vec3)

### ISSUE THREAD

**Issue by atsuzaki** [bevyengine/bevy#226]
Other game engines have scale as Vector3, as there are many usecases where you only want to scale a single dimension. I think this should be a fairly simple change to make.

**Comment by karroffel** [comment]
There is a `NonUniformScale` type too that has 3 components, that should work I think.

**Comment by karroffel** [comment]
I'll mark this as `documentation` because I think this needs to be made more visible, this is not the first time this came up.

If `NonUniformScale` does not work for you then let me know and I'll re-tag this issue.

**Comment by atsuzaki** [comment]
Thanks! It does work with one nitpicky caveat.

Quite a bunch of bundled components are bundling Scale in. Is there a way to override it? I tried slapping NonUniformScale on top and it just breaks all transformations. Of course, I could just copy paste the SpriteSheetComponents and the defaults provided and make my own bundle, but I'll end up with quite a bunch of duplicated code by doing this if I wish to always use NonUniformScale!

**Comment by DJMcNab** [comment]
I wonder if it would make sense to add a `#[bundle(option)]` attribute in `#[derive(Bundle)]` to make optional components work.

**Comment by DJMcNab** [comment]
I think this has been fixed in the move to the `Transform` component
