### ISSUE TITLE
Separate bevy tests from the example on how to run tests

### ISSUE THREAD

**Issue by Weibye** [bevyengine/bevy#2281]
## What problem does this solve or what need does it fill?

The tests currently within `./tests` are _also_ listed in the `./examples/README.md` and the `Cargo.toml` as **the example** on how to test systems. 
* The fact that an example does not reside within `./examples` is currently blocking #1650 
* I would also argue that it reduces cohesion / clarity as it is an exception from an otherwise consistent rule: That examples are always found within `./examples`

## What solution would you like?
Assuming `./tests` will become a much more involved test suite for bevy in the future, I propose a separation of concerns and would like to split these into two. 
1. Leave ./tests/how_to_test_systems.rs as it currently is
2. Create a near-identical copy and keep in `./examples/testing` which then could be elaborated on for user-friendliness if needed
3. Have this new one listed in `./examples/README.md` and `Cargo.toml`

This way `./tests` is free to change and evolve as needed without also having to be considered an approachable and user-friendly entry into testing within Bevy.

## What alternative(s) have you considered?

* To add `./tests` to the ignored folders of the example-validation action. 
This reduces cohesion and can create confusion for users as there exists examples that does not reside within ./examples

* Expand the example-doc-validation action to support multiple locations for examples to be in.
This would further delay #1650, and again reduce cohesion.

**Comment by mockersf** [comment]
> Assuming `./tests` will become a much more involved test suite for bevy in the future,

There are no plans to increase much the `./tests` folder
* We favour tests for each individual crates
* Having several test suites in there can severely impact build time and size as it creates a separate binary for each
* Integration tests for a game engine often means running with the renderer, but having `cargo run` actually starts a test game isn't nice

**Comment by Weibye** [comment]
Thanks for you input! I'm closing this as it is not the right solution, as discussed in #1650
