### ISSUE TITLE
Add a cylinder mesh to bevy_render

### ISSUE THREAD

**Issue by allsey87** [bevyengine/bevy#2282]
## What problem does this solve or what need does it fill?
Cylinders are a fundamental shape and we should have a means of generating cylinder meshes in Bevy. Currently the closest option to this is a capsule shape.

## What solution would you like?
The addition of a `Cylinder` shape and implementation of `From<Cylinder>` for `Mesh`. 

## What alternative(s) have you considered?
- Modify the capsule so that the ends could have zero radius?
- Import a GLTF

## Additional context
PR #305 implemented this feature but was closed before merge. I would like to bring this PR back to life and get it merged, however, meshes, normals, UVs etc are not my area of expertise and I am having some problems with the UVs/normals I think (see below). Perhaps I can open a new PR for this? Some more commits will be necessary to get the rendering working.

![cylinder](https://user-images.githubusercontent.com/3796345/120106609-0af75500-c15e-11eb-8b87-994f46dd13c3.png)

**Comment by alice-i-cecile** [comment]
Have you seen the geometric primitives RFC? :) 
https://github.com/bevyengine/rfcs/pull/12

It's ready for community comment, so your input on this topic  would be valuable.

**Comment by JayPavlina** [comment]
I attempted this, but I don't think it's possible to create a cylinder from a capsule. The `radius` controls both the radius of the capsule section and the radius of the spheres on the ends. Setting `radius` to 0 makes it invisible. Modifying `latitudes` and `longitudes` just changes the resolution. `depth` changes the distance between the spheres.

Also I experimented with `RegularPolygon`, and it could be used to create the caps, but not sure how to create the column connecting them.

I think a cylinder needs to be a separate shape.

**Comment by alice-i-cecile** [comment]
Sounds good, I'd be happy to have this implemented as a seperate shape.

**Comment by JayPavlina** [comment]
I'll take a look at #305 and see if I can revive it, but I'll probably have the same problems that @allsey87 had with UVs/normals. But I'll see how it goes.

**Comment by rparrett** [comment]
I'd be happy to donate the cylinder code here: https://github.com/rparrett/typey_birb/blob/main/src/cylinder.rs

**Comment by rparrett** [comment]
Yeah, feel free to PR that code if you want. Maybe add the author of #305 and me as co-authors if you want. IIRC, my code was very loosely based on that one (docs still seem pretty similar) but I abandoned most of it when the UVs weren't behaving and referenced... some textbook somewhere.
