### ISSUE TITLE
Loading glTF while bevy window is not active freezes bevy

### ISSUE THREAD

**Issue by lassade** [bevyengine/bevy#2303]
## Bevy version
main branch c4b8210

## Operating system & version
Fedora 33 using Wayland

## What you did
Tried to load an glTF, while waiting I clicked in another windown to wait;

## What you expected to happen
The glTF to be loaded and spawned;

## What actually happened
Nothing, I do think bevy froze, gnome asked to kill the program because it wasn't responding.

## Additional information
This bug sometimes happens sometimes doesn't, I did launch bevy from the VScode terminal if that makes any difference;
Alt+Tab back doesn't unfreeze bevy;

**Comment by NathanSWard** [comment]
Would you have any stack traces or anything that was printed for better context?

**Comment by alice-i-cecile** [comment]
@lassade Is this isolated to only some models? If so, could you link or upload one where you see this occurring?

> This bug sometimes happens sometimes doesn't,

That sounds like either a system ordering issue or a malformed asset that we're not handling properly.

**Comment by mockersf** [comment]
I can't reproduce, and this hasn't been reported recently.
Please reopen if you have more information on how to reproduce
