### ISSUE TITLE
System are not executed when using State, custom stage and system set.

### ISSUE THREAD

**Issue by ledyba** [bevyengine/bevy#2312]
## Bevy version

`0.5`

## Operating system & version

Windows 10 + Rust 1.52.1

## What you did

I would like to use custom stage and custom system state, and would like to switch them using by `State<T>`.

Here is a complete example: [__report__bevy_scheduing_sample/main.rs](https://github.com/ledyba/__report__bevy_scheduing_sample/blob/d13265889c3f89b4df92774d3d9bc85183a7f362/src/main.rs)

Here is a main function:

```rust
fn main() {
  let before_system_set = SystemSet::on_update(MyState::UpdateState)
    .with_system(print_before_system.system());
  let after_system_set = SystemSet::on_update(MyState::UpdateState)
    .with_system(print_after_system.system());
  let update_system_set = SystemSet::on_update(MyState::UpdateState)
    .with_system(print_system.system());
  App::build()
    .add_plugins(DefaultPlugins)
    .add_state_to_stage(CoreStage::Update, MyState::UpdateState)
    .add_stage_before(
      CoreStage::Update,
      MyStage::BeforeRound,
      SystemStage::parallel(),
    )
    .add_stage_after(
      CoreStage::Update,
      MyStage::AfterRound,
      SystemStage::parallel(),
    )
    .add_system_set_to_stage(MyStage::BeforeRound, before_system_set)
    .add_system_set_to_stage(CoreStage::Update, update_system_set)
    .add_system_set_to_stage(MyStage::AfterRound, after_system_set)
    .run();
}
```

## What you expected to happen

I have expected this app prints: 

```
Before Update
Update
AfterUpdate
Before Update
Update
AfterUpdate

....(Repeats forever)
```

## What actually happened

```
% cargo run
   Compiling bevy_scheduing_sample v0.1.0 (C:\Users\kaede\src\sample)
    Finished dev [unoptimized + debuginfo] target(s) in 3.81s
     Running `target\debug\bevy_scheduing_sample.exe`
Jun 07 01:39:44.564  WARN bevy_ecs::schedule::graph_utils: Chain(&bevy_ecs::schedule::state::State<bevy_scheduing_sample::MyState>::on_update::{{closure}}, &bevy_ecs::schedule::state::should_run_adapter<bevy_scheduing_sample::MyState>) wants to be after unknown label: DriverLabel(TypeId { t: 11331299601305256830 })
error: process didn't exit successfully: `target\debug\bevy_scheduing_sample.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
```

## Additional information

I would like to use custom stage (in this example, `MyStage::BeforeRound` and `MyStage::AfterRound`) to interact with components spawned in `CoreStage::Update`. Any other solution is available to do that?  According to https://github.com/bevyengine/bevy/issues/1613, I understood that we have to use custom stages.

**Comment by Ixentus** [comment]
You don't need custom stages, you can use `CoreStage::PreUpdate` and `CoreStage::PostUpdate`.

Every stage which has system(set)s which use states needs a `StateDriver`, this is why you're getting an error. You can use `.add_state_to_stage(MyStage::BeforeRound, MyState::UpdateState)` to add it.

**Comment by NathanSWard** [comment]
@ledyba does @Ixentus 's answer suit your use case?

**Comment by ledyba** [comment]
@Ixentus Thanks! By adding those lines, it works as expected.
@NathanSWard Yes, but I still have something to ask.

I also would like to make also another state, such as `Loading` state and loading system.

If loading is done, I would like update the state from `Loading` to `InGame`.

```rust
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
enum MyState {
  Loading, // <- Added
  InGame,
}

fn load_system(mut state: ResMut<State<MyState>>) {
  // Prepare something (such as texture loading) and wait until done.
  // ...

  // if loading.is_done() {
    state.replace(MyState::InGame).unwrap();!
  //}
}
```

[I added this feature to previous example](https://github.com/ledyba/__report__bevy_scheduing_sample/commit/7751d3e0c2351bcaf0ce1066cdd43a3e9dfbbe18) ([full source](https://github.com/ledyba/__report__bevy_scheduing_sample/blob/7751d3e0c2351bcaf0ce1066cdd43a3e9dfbbe18/src/main.rs)), and also it works as expected.

```rust
fn main() {
  let loading_system_set = SystemSet::on_update(MyState::Loading)
    .with_system(load_system.system());
  let before_system_set = SystemSet::on_update(MyState::InGame)
    .with_system(print_before_system.system());
  let after_system_set = SystemSet::on_update(MyState::InGame)
    .with_system(print_after_system.system());
  let update_system_set = SystemSet::on_update(MyState::InGame)
    .with_system(print_system.system());
  App::build()
    .add_plugins(DefaultPlugins)
    .add_stage_before(
      CoreStage::Update,
      MyStage::BeforeRound,
      SystemStage::parallel(),
    )
    .add_stage_after(
      CoreStage::Update,
      MyStage::AfterRound,
      SystemStage::parallel(),
    )
    .add_state_to_stage(MyStage::BeforeRound, MyState::Loading)
    .add_state_to_stage(CoreStage::Update, MyState::Loading)
    .add_state_to_stage(MyStage::AfterRound, MyState::Loading)
    .add_system_set_to_stage(CoreStage::Update, loading_system_set)
    .add_system_set_to_stage(MyStage::BeforeRound, before_system_set)
    .add_system_set_to_stage(CoreStage::Update, update_system_set)
    .add_system_set_to_stage(MyStage::AfterRound, after_system_set)
    .run();
}
```

It prints:

```
Before Update
Update
After Update
(... forever)
```

But I can't understand why it works.
If I understood correctly, `loading_system_set` is added just to `CoreStage::Update`, so the states of `MyStage::BeforeRound` and `MyStage::AfterRound` are still `MyState::Loading`.

Why I don't have to call `state.replace(MyState::InGame).unwrap();` three times?

**Comment by Ixentus** [comment]
There is only 1 state (which can be Loading or InGame). So don't replace it in every stage. The docs say that should fail if the new state matches the current state.

Now the reason "Update" is ran before "Before Update" is that the Loading system is ran in the Update stage. When it sets the state to InGame, it is still in the update stage. So `before_system_set` won't be ran till the next tick.

**Comment by ledyba** [comment]
> There is only 1 state (which can be Loading or InGame). So don't replace it in every stage. The docs say that should fail if the new state matches the current state.

I see, thanks. I read the source and I found State is just a resource, and not owned by each stages:

https://github.com/bevyengine/bevy/blob/73ae6af6efc3e8e525e8068fa6f58bfd0d03cc8c/crates/bevy_app/src/app_builder.rs#L260-L271

As written in doc, this style also works (For me, this style makes me relieved, because I don't need to insert the same status for many times.):

```rust
    .insert_resource(State::new(MyState::Loading))
    .add_system_set_to_stage(MyStage::BeforeRound, State::<MyState>::get_driver())
    .add_system_set_to_stage(CoreStage::Update, State::<MyState>::get_driver())
    .add_system_set_to_stage(MyStage::AfterRound, State::<MyState>::get_driver())
```

> Now the reason "Update" is ran before "Before Update" is that the Loading system is ran in the Update stage. When it sets the state to InGame, it is still in the update stage. So before_system_set won't be ran till the next tick.

I see... So I tried to move`loading_system_set` from `CoreStage::Update` to `CoreStage::First`.
([Here is an complete source](https://github.com/ledyba/__report__bevy_scheduing_sample/blob/cbfe961a43a17cd99d3039b58e6b0fd7fa1105ab/src/main.rs))

Then, it works perfectly!
```
% cargo run
   Compiling bevy_scheduing_sample v0.1.0 (C:\Users\kaede\src\sample)
    Finished dev [unoptimized + debuginfo] target(s) in 3.95s
     Running `target\debug\bevy_scheduing_sample.exe`
Loading is done
Before Update
Update
After Update
Before Update
Update
After Update
...
```

**Comment by ledyba** [comment]
Thank you, @Ixentus and @NathanSWard !
I can resolve my issue perfectly, so I will close this issue.
(And sorry for reporting as a bug...)

**Comment by Ixentus** [comment]
Glad we could help. Hopefully the next iteration of States and Stages will be easier to use :)

**Comment by ledyba** [comment]
Oh, I'm really looking forward it!
