### ISSUE TITLE
Bevy 0.5.0 can't run with DefaultPlugins: BackendSpecificError

### ISSUE THREAD

**Issue by kugiyasan** [bevyengine/bevy#2314]
## Bevy version

bevy = "0.5.0"

## Operating system & version

Arch Linux x86_64 5.10.42-1-lts
DE: KDE Plasma

## What you did

```sh
cargo new cant_load_default_plugin
cd cant_load_default_plugin
printf 'use bevy::prelude::*;\nfn main() { App::build().add_plugins(DefaultPlugins).run(); }' > src/main.rs
echo 'bevy = "0.5.0"' >> Cargo.toml
cargo run
```

## What you expected to happen

The program should build

## What actually happened

5 compilation errors about `use of unstable library feature`

I then tried
```sh
rustup override set nightly
RUST_BACKTRACE=1 cargo run
```
but then
```sh
thread 'main' panicked at 'build_output_stream failed with all supported formats: BackendSpecific { err: BackendSpecificError { description: "ALSA function 'snd_pcm_start' failed with error 'EBADFD: File descriptor in bad state'" } }', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.1/src/stream.rs:208:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::expect
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/core/src/result.rs:997:23
   4: <cpal::platform::platform_impl::Device as rodio::stream::CpalDeviceExt>::try_new_output_stream::{{closure}}
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.1/src/stream.rs:204:17
   5: core::result::Result<T,E>::unwrap_or_else
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/core/src/result.rs:821:23
   6: <cpal::platform::platform_impl::Device as rodio::stream::CpalDeviceExt>::try_new_output_stream
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.1/src/stream.rs:200:12
   7: rodio::stream::OutputStream::try_from_device
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.1/src/stream.rs:31:32
   8: rodio::stream::OutputStream::try_default
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.1/src/stream.rs:45:9
   9: <bevy_audio::audio_output::AudioOutput<P> as core::default::Default>::default
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_audio-0.5.0/src/audio_output.rs:22:39
  10: <T as bevy_ecs::world::FromWorld>::from_world
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/world/mod.rs:928:9
  11: bevy_app::app_builder::AppBuilder::init_non_send_resource
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/app_builder.rs:272:28
  12: <bevy_audio::AudioPlugin as bevy_app::plugin::Plugin>::build
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_audio-0.5.0/src/lib.rs:23:9
  13: bevy_app::plugin_group::PluginGroupBuilder::finish
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/plugin_group.rs:104:21
  14: bevy_app::app_builder::AppBuilder::add_plugins
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/app_builder.rs:295:9
  15: cant_load_default_plugin::main
             at ./src/main.rs:1:35
  16: core::ops::function::FnOnce::call_once
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I also tried this `src/main.rs`, and this runs and exits instantly without any error, while I expected it to never exit
```rs
use bevy::prelude::*;
fn main() {
    App::build()
        .add_plugin(bevy::log::LogPlugin::default())
        .add_plugin(bevy::core::CorePlugin::default())
        .add_plugin(bevy::transform::TransformPlugin::default())
        .add_plugin(bevy::diagnostic::DiagnosticsPlugin::default())
        .add_plugin(bevy::input::InputPlugin::default())
        .add_plugin(bevy::window::WindowPlugin::default())
        .add_plugin(bevy::asset::AssetPlugin::default())
        .add_plugin(bevy::scene::ScenePlugin::default())
        .run();
}
```

**Comment by MinerSebas** [comment]
1. Bevy requires latest stable, thats the reason for your compilation errors
2. Seems like your ALSA install is broken: `"ALSA function 'snd_pcm_start' failed with error 'EBADFD: File descriptor in bad state'"`
Did you take a look here? https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md#arch--manjaro

**Comment by kugiyasan** [comment]
Thanks for the quick answer!
1. Yes, I was on the latest stable, but like I briefly said, I got 5 unstable features compilation errors, like the one below, and that's why I tried the nightly toolchain
```sh
rustup override set stable
cargo run
[...]
error[E0658]: use of unstable library feature 'unsafe_cell_get_mut'
   --> $HOME.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/storage/sparse_set.rs:217:32
    |
217 |         let ticks = self.ticks.get_mut().iter_mut();
    |                                ^^^^^^^
    |
    = note: see issue #76943 <https://github.com/rust-lang/rust/issues/76943> for more information

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `bevy_ecs`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
2. I already looked at the dependencies, I reinstalled `libx11 pkgconf alsa-lib`, same results

**Comment by MinerSebas** [comment]
Realy strange 🤔 , that Feature was stabilised in 1.50.0: https://github.com/rust-lang/rust/pull/79485

**Comment by NathanSWard** [comment]
What is your output from `cargo --version` and `rustc --version`?

**Comment by kugiyasan** [comment]
Oops noob mistake, my stable was 1.49.0, I just had to `rustup update`. I somehow thought that rust would magically keep my stable always up to date...

```sh
$ cargo --version
cargo 1.52.0 (69767412a 2021-04-21)
$ rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)
```

>     For now, you could disable the `bevy_audio` and `mp3` Features to still compile
I still need to disable `bevy_audio` and `mp3` to be able to run the program. It's not a problem for me, since I don't have intentions to touch the audio for now, but this still needs further investigation ig

**Comment by NathanSWard** [comment]
@kugiyasan 
Is it ok then if we close out this issue since your primary concern was solved?

**Comment by MinerSebas** [comment]
#2269 also should have fixed that bevy panicks in your case. (Though you will still be missing audio)

**Comment by bjorn3** [comment]
> ALSA function \'snd_pcm_start\' failed with error \'EBADFD: File descriptor in bad state\'

This is a problem with initializing the sound plugin. Since https://github.com/bevyengine/bevy/pull/2269 this no longer causes a crash. Just missing sound.

**Comment by Pomegranate123** [comment]
What do you mean with 'no longer causes a crash'? My code isn't compiling because of it, isn't that a crash? What would I need to do to fix it?

**Comment by bjorn3** [comment]
Your code does compile. It just crashed when actually running it due to failed initialization of the sound plugin. The fix would be to either disable the sound plugin (`.add_plugins_with(DefaultPlugins, |plugins| plugins.disable::<bevy::audio::AudioPlugin>())`) or switch to the main branch.

**Comment by bjorn3** [comment]
Not that I know. Some people have this issue, most don't so it is hard to reproduce.

**Comment by kugiyasan** [comment]
@Pomegranate123 I finally found a fix! I tried a bunch of things, and I discovered that I couldn't play sound with ALSA. Test your ALSA with `aplay -v a_random_sound.wav`. If you don't hear any sound, make sure the printed output device matches the one you're using. Mine didn't match, so I changed my default alsa output device like explained [here](https://forum.mxlinux.org/viewtopic.php?t=46693), and boom, bevy audio worked!

**Comment by lafi-99** [comment]
> ## Bevy version
> 
> 
> 
> bevy = "0.5.0"
> 
> 
> 
> ## Operating system & version
> 
> 
> 
> Arch Linux x86_64 5.10.42-1-lts
> 
> DE: KDE Plasma
> 
> 
> 
> ## What you did
> 
> 
> 
> ```sh
> 
> cargo new cant_load_default_plugin
> 
> cd cant_load_default_plugin
> 
> printf 'use bevy::prelude::*;\nfn main() { App::build().add_plugins(DefaultPlugins).run(); }' > src/main.rs
> 
> echo 'bevy = "0.5.0"' >> Cargo.toml
> 
> cargo run
> 
> ```
> 
> 
> 
> ## What you expected to happen
> 
> 
> 
> The program should build
> 
> 
> 
> ## What actually happened
> 
> 
> 
> 5 compilation errors about `use of unstable library feature`
> 
> 
> 
> I then tried
> 
> ```sh
> 
> rustup override set nightly
> 
> RUST_BACKTRACE=1 cargo run
> 
> ```
> 
> but then
> 
> ```sh
> 
> thread 'main' panicked at 'build_output_stream failed with all supported formats: BackendSpecific { err: BackendSpecificError { description: "ALSA function 'snd_pcm_start' failed with error 'EBADFD: File descriptor in bad state'" } }', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.1/src/stream.rs:208:22
> 
> stack backtrace:
> 
>    0: rust_begin_unwind
> 
>              at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/std/src/panicking.rs:515:5
> 
>    1: core::panicking::panic_fmt
> 
>              at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/core/src/panicking.rs:92:14
> 
>    2: core::result::unwrap_failed
> 
>              at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/core/src/result.rs:1355:5
> 
>    3: core::result::Result<T,E>::expect
> 
>              at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/core/src/result.rs:997:23
> 
>    4: <cpal::platform::platform_impl::Device as rodio::stream::CpalDeviceExt>::try_new_output_stream::{{closure}}
> 
>              at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.1/src/stream.rs:204:17
> 
>    5: core::result::Result<T,E>::unwrap_or_else
> 
>              at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/core/src/result.rs:821:23
> 
>    6: <cpal::platform::platform_impl::Device as rodio::stream::CpalDeviceExt>::try_new_output_stream
> 
>              at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.1/src/stream.rs:200:12
> 
>    7: rodio::stream::OutputStream::try_from_device
> 
>              at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.1/src/stream.rs:31:32
> 
>    8: rodio::stream::OutputStream::try_default
> 
>              at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.1/src/stream.rs:45:9
> 
>    9: <bevy_audio::audio_output::AudioOutput<P> as core::default::Default>::default
> 
>              at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_audio-0.5.0/src/audio_output.rs:22:39
> 
>   10: <T as bevy_ecs::world::FromWorld>::from_world
> 
>              at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/world/mod.rs:928:9
> 
>   11: bevy_app::app_builder::AppBuilder::init_non_send_resource
> 
>              at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/app_builder.rs:272:28
> 
>   12: <bevy_audio::AudioPlugin as bevy_app::plugin::Plugin>::build
> 
>              at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_audio-0.5.0/src/lib.rs:23:9
> 
>   13: bevy_app::plugin_group::PluginGroupBuilder::finish
> 
>              at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/plugin_group.rs:104:21
> 
>   14: bevy_app::app_builder::AppBuilder::add_plugins
> 
>              at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/app_builder.rs:295:9
> 
>   15: cant_load_default_plugin::main
> 
>              at ./src/main.rs:1:35
> 
>   16: core::ops::function::FnOnce::call_once
> 
>              at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/core/src/ops/function.rs:227:5
> 
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> 
> ```
> 
> 
> 
> I also tried this `src/main.rs`, and this runs and exits instantly without any error, while I expected it to never exit
> 
> ```rs
> 
> use bevy::prelude::*;
> 
> fn main() {
> 
>     App::build()
> 
>         .add_plugin(bevy::log::LogPlugin::default())
> 
>         .add_plugin(bevy::core::CorePlugin::default())
> 
>         .add_plugin(bevy::transform::TransformPlugin::default())
> 
>         .add_plugin(bevy::diagnostic::DiagnosticsPlugin::default())
> 
>         .add_plugin(bevy::input::InputPlugin::default())
> 
>         .add_plugin(bevy::window::WindowPlugin::default())
> 
>         .add_plugin(bevy::asset::AssetPlugin::default())
> 
>         .add_plugin(bevy::scene::ScenePlugin::default())
> 
>         .run();
> 
> }
> 
> ```

**Comment by Pomegranate123** [comment]
> @Pomegranate123 I finally found a fix! I tried a bunch of things, and I discovered that I couldn't play sound with ALSA. Test your ALSA with `aplay -v a_random_sound.wav`. If you don't hear any sound, make sure the printed output device matches the one you're using. Mine didn't match, so I changed my default alsa output device like explained [here](https://forum.mxlinux.org/viewtopic.php?t=46693), and boom, bevy audio worked!

Sadly didn't work. I was already using the correct device and could play audio fine. The only issue is when I try to use bevy. I'm also using pulseaudio, if that changes anything.
