### ISSUE TITLE
Failed compiling `bevy-glsl-to-spirv v0.2.1` to target `x86_64-pc-windows-gnu` from Ubuntu 20.04 (WSL2)

### ISSUE THREAD

**Issue by zylkowski** [bevyengine/bevy#2317]
## Bevy version
0.5.0

## Operating system & version
Ubuntu 20.04 WSL2 

## What you did
Tried to build [this example](https://github.com/bevyengine/bevy/blob/main/examples/shader/shader_defs.rs) for target `x86_64-pc-windows-gnu` on Linux. I have every dependency installed.

## What you expected to happen
To compile properly.

## What actually happened
Build failed for `bevy-glsl-to-spirv v0.2.1` as it is `Missing target support x86_64-pc-windows-gnu`

## Additional information
```
error: failed to run custom build command for `bevy-glsl-to-spirv v0.2.1`

Caused by:
  process didn't exit successfully: `/root/dev/rust/bevy-shaders-test/target/debug/build/bevy-glsl-to-spirv-ea21dca2a4b6ae86/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Missing target support x86_64-pc-windows-gnu', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy-glsl-to-spirv-0.2.1/build/build.rs:24:9
```

**Comment by mockersf** [comment]
This should be fixed on git main since #1819 got merged, could you check?

**Comment by zylkowski** [comment]
> This should be fixed on git main since #1819 got merged, could you check?

Tried main from git (had to install `cmake`, which should be listed as dependency btw) but still got [error](https://pastebin.com/avdPGrd7)

**Comment by mockersf** [comment]
In this case it's trying to build `shaderc` which is a little harder to setup... You can download a prebuilt version, or follow instructions here: https://github.com/google/shaderc#getting-and-building-shaderc

**Comment by zylkowski** [comment]
So there is no "simple" way of building bevy for Windows? If no I still consider this an issue.

**Comment by bjorn3** [comment]
The simple way is to use the MSVC toolchain on Windows directly and not use WSL2 I think.

**Comment by NathanSWard** [comment]
> The simple way is to use the MSVC toolchain on Windows directly and not use WSL2 I think.

^this

Using it with WSL2 is more difficult to setup/configure since its a linux VM running on windows. 
I've been developing on Windows using the MSVC toolchain and haven't run into any problems (just as an example)

**Comment by zylkowski** [comment]
> The simple way is to use the MSVC toolchain on Windows directly and not use WSL2 I think.

It doesn't change a fact that building for Windows from Linux is not possible the way it should work. That just a workaround and for time until fixing I will of course use it this way.

**Comment by mockersf** [comment]
`bevy-glsl-to-spirv` is no longer needed
