### ISSUE TITLE
Breakout example has memory leaks

### ISSUE THREAD

**Issue by fuchsnj** [bevyengine/bevy#232]
I was testing out the breakout example, and noticed the movement wasn't very smooth. I checked the CPU, and noticed it was using ~70% across all 8 cores! (i7-4710HQ CPU @ 2.50GHz)

I also noticed the memory usage started around 20 MB (which already seemed high) and it slowly increased to over 57 MB about 15 minutes later (when I killed it)

Probably not as important, but I did want to note the ball in breakout somehow managed to leave the boundaries and never came back.

Overall, it was a pretty poor first impression for the game engine. 

This was running in release mode on Ubuntu 20.04.1 LTS
The only thing odd I noticed was this warning in the terminal: `INTEL-MESA: warning: Haswell Vulkan support is incomplete`

If there is anything I can give that might help with some of these issues, just ask.

**Comment by 0x22fe** [comment]
I noticed the same issue (same platform), but it happened with all examples I tested, not just breakout.

**Comment by DGriffin91** [comment]
Just tested the breakout example with --release on Windows 10 with Core i7-6700K, Nvidia GTX 1060:

- Start: CPU 8%, Memory 59MB
- After all blocks gone: CPU 7%, Memory 59MB
- After around 15min: CPU 7%, Memory 60MB

**Comment by multun** [comment]
The high CPU usage is a recently fixed bug of rayon, one of the dependencies of the project. It hasn't yet reached a release, [but should soon](https://github.com/rayon-rs/rayon/issues/784).

> Probably not as important, but I did want to note the ball in breakout somehow managed to leave the boundaries and never came back.

Yeah that was pretty bad, I think that's fixed on master.

> Overall, it was a pretty poor first impression for the game engine.

The project is very, very young, and unfortunately still contains many bugs, and new bugs will be added and fixed as the project grows. The current state of the project isn't what made me want to contribute: bugs can be fixed easily, the code looks pretty good, and the architecture is better than everything else I could find.

I'll investigate that memory leak as soon as I have time

**Comment by cart** [comment]
Thanks for the feedback!

I can comfortably say that if you're looking for a production-ready engine, we aren't even remotely close. We will lose on most benchmarks, probably by a wide margin. Fortunately we are also generally aware of most issues and have plans to resolve them. I'm also relatively confident that we're laying good foundations here. It will just take time.


Theres already a similar issue on general performance and cpu usage / rayon. I left more details there: #111 

Lets leave this open, but scope this issue to the memory leaks.

**Comment by cart** [comment]
Also master should have a fix for the ball leaving the bounds.

**Comment by CastilloDel** [comment]
> Also master should have a fix for the ball leaving the bounds.

The ball still leaves the bounds in my machine as of commit 028a22b 
In Debian with Wayland

**Comment by alice-i-cecile** [comment]
High CPU usage has been solved by us removing Rayon.
Ball escapes was solved by #1541.
Memory leak: unsure if this still applies; there's been a number of relevant changes that could have fixed this.

Closing for now; please open a new issue if you still experience a memory leak <3
