### ISSUE TITLE
Right click button interactions

### ISSUE THREAD

**Issue by billyb2** [bevyengine/bevy#2322]
## What problem does this solve or what need does it fill?

Allowing right clicking on buttons would allow for unique behaviors on buttons depending on the type of click.

## What solution would you like?

Instead of Clicked being a type of an enum, clicked itself uses the MouseButton enum so that a click can be left, right, middle, or otehr

## What alternative(s) have you considered?

Having a RightClicked type, though it feels like code bloat since MouseButton exists.

## Additional context

Any other information you would like to add such as related previous work,
screenshots, benchmarks, etc.

**Comment by alice-i-cecile** [comment]
This would be very well handled with per-entity events, see #2116. The impl there is not far from complete, but needs perf optimization.

**Comment by billyb2** [comment]
> This would be very well handled with per-entity events, see #2116. The impl there is not far from complete, but needs perf optimization.

So we would have to wait for that to be merged?

**Comment by mockersf** [comment]
I pushed a quick fix for that in #2324 

It will probably change how that works with the UI rework, but it's a small enough fix to do it now 👍

**Comment by alice-i-cecile** [comment]
This is now complete due to `bevy_picking`'s creation and integration with `bevy_ui`.
