### ISSUE TITLE
filters:: module for query filter suggestions

### ISSUE THREAD

**Issue by TCROC** [bevyengine/bevy#2328]
## What problem does this solve or what need does it fill?

Currently you have to remember all of the different filter options for writing a query.  It would be nice if the queries either belonged to or had a mapping from a module.

Example:

![image](https://user-images.githubusercontent.com/24307049/121430987-d26a2f00-c946-11eb-957e-5d4b4beeea13.png)

It is cool that the ``With`` and ``Without`` can be written as they are.  It would also be cool if you could type something to get all filter suggestions like ``filters::`` and then ``With``, ``Without``, and other filter options appear in the suggestions by the IDE.

The filter options would appear in this dropdown:

![image](https://user-images.githubusercontent.com/24307049/121431404-57eddf00-c947-11eb-8acb-4c33cae9ceda.png)

I'm coming from C# to rust and was inspired by how C#'s LINQ works in regards to suggesting different filter options while writing queries.

**Comment by TCROC** [comment]
The original conversation for it can be found here: https://discord.com/channels/691052431525675048/691052431974465548/852292173181091881

**Comment by mockersf** [comment]
not something we want to do for now, feel free to reopen if you disagree or have a good argument for it
