### ISSUE TITLE
Entity cmp::Eq improvement

### ISSUE THREAD

**Issue by tower120** [bevyengine/bevy#2346]
## What problem does this solve or what need does it fill?

Current Entity comparison relies on rust's `#derive(Eq, ...)`

It now actually makes two comparisons (see asm code)

https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=38662860685c22c6cbaf0a14a7e38b8b

## What solution would you like?

If treat whole Entity struct as u64 (through pointer cast on comparison, or even by store generation+id as u64) this could become one bitwise comparison.

https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=3351c4c203e76073de253b3301ed8d13

**Comment by NathanSWard** [comment]
I'm surprised the compiler didn't optimize this 😢

**Comment by mockersf** [comment]
Bevy very rarely rely on entity equality so I don't think it would change much in performances

**Comment by NathanSWard** [comment]
This also seems to greatly affect the assembly for the `Ord` trait as well :(
https://godbolt.org/z/GKqYnee4h

**Comment by alice-i-cecile** [comment]
#2372 can and should be revived if this is worth pushing forward.

FWIW, I'm in favor of those changes; I tend to use Entity equality quite a bit in my code, and suspect that it will be important for relation-like features.
