### ISSUE TITLE
CI Enhancements 

### ISSUE THREAD

**Issue by qarmin** [bevyengine/bevy#238]
With good CI, a lot of bugs and regression can be caught and also things like bad formatting
- [x] Check formatting in code by `cargo fmt`
- [x] Unit tests(are in CI, but seems that are missing in code)
- [ ] Integration tests
- [x] Build Bevy also on Windows and MacOS (#129)
- [x] Cache for faster building (https://github.com/godotengine/godot/blob/f568cede8d8a4a3f7051afd2ae8502deb09bc157/.github/workflows/linux_builds.yml#L30-L40) (https://github.com/bevyengine/bevy/pull/357)
- [ ] Benchmarks and performance regression testing
- [ ] Testing project for regression(panics etc.) - project should use as much as possible elements(This is not available now, since there isn't exists for now any tool that provide software rendering of Vulkan apps)
- [ ] Sanitizers support(ASAN, LSAN, TSAN, MSAN) - Bevy use some amount of unsafe code which may be invalid, but also some valid code may cause some leaks or bugs - https://github.com/rust-lang/rust/pull/38699
I think, that same project from above should be running but this time with sanitizers support.

**Comment by cart** [comment]
These are all great ideas!

* unit tests: we do have tests. not as many as i would like, but make sure you're running `cargo test --workspace` to run everything.
* cache: i had the cache wired up in the past, but due to the large size of build artifacts, the save/restore steps ended up being more expensive than just rebuilding.


>  Testing project for regression(panics etc.) - project should use as much as possible elements
could you elaborate on this?

**Comment by multun** [comment]
Can you add some merge queue management to the list, like [bors](https://bors.tech/)?

**Comment by cart** [comment]
yup that is actually priority 1 as far as CI is concerned. right now we dont have strong safety guarantees that a build is clean. we really need to fix that asap.

**Comment by multun** [comment]
I'd also remove caching and regression testing from the list, it doesn't seem yet worth it, the build isn't big nor long enough, and regressions not a big deal until things are a bit more setttled

**Comment by erlend-sh** [comment]
Looking at Amethyst’s recent [CI migration to GitHub actions](https://github.com/amethyst/amethyst/pull/2382) would probably be informative here.

I dunno what’s the best place to look to get the full picture of how it works, but @cleancut probably does.

**Comment by duncanrhamill** [comment]
Hey not sure if this is the right place but would also be nice to have a build status tag in the readme, since the book actually suggests using the git dependency and it would be nice to see if that's immediately going to break a build. Maybe a "last commit that passed" tag would be helpful too?

**Comment by AngelOnFira** [comment]
@duncanrhamill Good idea, I added that in #325

**Comment by AngelOnFira** [comment]
@cart in the CI workflow, I see this:
```
  # NOTE: temporarily disabled because on-push currently uses up too many resources
  # push:
  #   branches: [master]
```
Since the repo is now public, you get unlimited Action minutes, and up to 20 concurrent jobs. I believe this is enough to allow running on every push?

**Comment by CleanCut** [comment]
> Since the repo is now public, you get unlimited Action minutes, and up to 20 concurrent jobs. I believe this is enough to allow running on every push?

That's correct, public repositories get unlimited minutes.  I wrote a comment to this effect several days ago, but must have forgotten to hit the submit button. 😊

**Comment by cart** [comment]
Well thats fantastic news. Thanks for the heads up. Time to heat up some datacenters :smiling_imp:

**Comment by cart** [comment]
Hmm I'm still seeing a 2000 minute limit for the Bevy Organization.

![image](https://user-images.githubusercontent.com/2694663/91142226-4613a780-e665-11ea-967e-39fe640cb856.png)

**Comment by AngelOnFira** [comment]
I think that just includes any minutes that are from repos that aren't public. To test it, it might be worth seeing if it increases past 86 once there is another push to master. But there have also been so many CI jobs running, that I don't imagine it could only be 86 minutes. It's not eating into my personal minutes when I make a PR, so that should mean that forks only use CI minutes at the expense of the org (and not at all in the case of public repos) :100:

**Comment by CleanCut** [comment]
![91142226-4613a780-e665-11ea-967e-39fe640cb856](https://user-images.githubusercontent.com/5838512/91223793-66337d00-e6de-11ea-9b93-9c4c2de20a70.png)

Yes, you still have a limit for _private_ repos.  `bevyengine/bevy` is a public repo, so it is not subject to those restrictions.

**Comment by cart** [comment]
Bawhaha thanks for pointing out what (should be) obvious. I totally missed that 😅

**Comment by AngelOnFira** [comment]
:laughing: I didn't see that either :stuck_out_tongue: I'll make a PR to get CI running hot :fire:

**Comment by lberrymage** [comment]
Something like GitHub's [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) (not dependabot-preview anymore!) would be nice to use as well so we don't have to manually make periodic "Update xxx dependency to x.y.z" commits. Not sure how well that fits under the CI umbrella, but it would be useful to automate (most) dependency upgrades nonetheless.

**Comment by memoryruins** [comment]
If dependabot is used, I suggest setting the [interval](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#scheduleinterval) to monthly or weekly to minimize PR opening/closing noise.

**Comment by cart** [comment]
I think we dont always want to upgrade asap because we want to stay synced up our dependencies to avoid mismatches / reduce dependency counts.

**Comment by lberrymage** [comment]
That makes sense. dependabot could be nice for the sake of having a tracking issue of sorts though; that way certain dependency upgrades have a mention in the issue tracker and (theoretically) don't get forgotten for long periods of time. I agree that automatic merges aren't a good idea if that's what you're talking about specifically.

**Comment by CleanCut** [comment]
Dependabot's killer feature for me is the quick reporting of security vulnerabilities in your dependencies.  Non-security updates can be configured down to only alert monthly (and specific entries can be set to be ignored), but can't be turned off entirely as far as I can tell.

**Comment by lberrymage** [comment]
I'm pretty sure you can disable non-security updates by just not checking in a `dependabot.yml`. Security updates are enabled through repository settings. It's explained in detail in the first paragraph [here](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates#about-version-updates-for-dependencies) (plus the page that links for [configuring security updates](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates)).

**Comment by cart** [comment]
Ok i think im sold on dependabot (with a decently long check timer to avoid noise and manual-only merges). And we should always verify that our "redundant dep count" doesnt go up before merging. We've already regressed a bit in this area, but that was largely unavoidable. Can't wait for winit `0.22.3` :)

**Comment by lberrymage** [comment]
How long of a check timer are you thinking? The options we have are one week or one month, but consider that there's also [`open-pull-requests-limit`](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#open-pull-requests-limit) (which is five by default) to prevent noise. Sadly [cron-like schedule syntax](https://github.com/dependabot/dependabot-core/issues/2038) isn't implemented yet.

I'm happy to say that the [last major blocker for winit `0.23.0`](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#open-pull-requests-limit) is under active review!

**Comment by cart** [comment]
hmm i guess lets try one week with the default pr limit. we can always bump it up to a month if theres too much noise.

**Comment by lberrymage** [comment]
Sounds good. I'll make a PR.

**Comment by lberrymage** [comment]
One more question: do we want dependabot to try to update GitHub Actions in the CI configuration?

**Comment by cart** [comment]
Sure! We can always disable it if it becomes a problem.

**Comment by alice-i-cecile** [comment]
These are largely complete, although we can't run benchmarks in CI due to reliability, or sanitizers due to time. Closing this out, feel free to make more targeted issues to resolve anything that I missed.
