### ISSUE TITLE
Add a `reset` API to `State`

### ISSUE THREAD

**Issue by tbarusseau** [bevyengine/bevy#2385]
## What problem does this solve or what need does it fill?

If I want to reset the game's current state (to trigger both the `on_exit` and `on_enter` systems, or just reinitialize everything within the state), I must manually exit the state and then re-enter it.

## What solution would you like?

A built-in method in the API that would allow me to do `state.reset()`.

I'm not familiar with the project's source code and have no idea how feasible that is.

## What alternative(s) have you considered?

It can be done without much overhead by reserving a `ResetCurrentState` state that's only used for this, doesn't trigger any startup systems/systems, and immediatly `state.push`es the last active state on enter, but this is cumbersome to setup and really seems like boilerplate code that could be avoided.

**Comment by NathanSWard** [comment]
Hmm this is interesting, however what do we plan to have reset set the state to?
Current you construct a state and give it the initial state, however that state can be lost, so having a `reset` function might be difficult. 

One possibilty is providing `reset` for states that implement `Default` and resetting them to the default value.

**Comment by tsoutsman** [comment]
> Hmm this is interesting, however, what do we plan to have reset set the state to?

I think he means "reenter" the current state and rerun its `on_enter` and `on_exit` systems. For example, suppose you have a `Level` state. To advance to the next level, you could increment a `LevelNum` resource and then "reset" the state, which will call the `on_enter` and `on_exit` systems regenerating the level, etc., and the difficulty could scale based on the `LevelNum` resource.

Currently, calling `push` or `set` with the current state does nothing.
