### ISSUE TITLE
Use flat normals if normal attribute is not found 

### ISSUE THREAD

**Issue by PravinKumar95** [bevyengine/bevy#2396]
## What problem does this solve or what need does it fill?

Most cad/cae files does not contain normals to reduce data. Bevy panics if normals aren't found 

## What solution would you like?

Use flat normals if normal attribute is not found

## What alternative(s) have you considered?

Using a custom shader would solve the issue

## Additional context

![image](https://user-images.githubusercontent.com/24854653/123502211-3fc8d000-d668-11eb-8156-c915bc5c2d5e.png)

**Comment by jakobhellermann** [comment]
This is already done in the `main` branch: https://github.com/bevyengine/bevy/pull/1808

**Comment by mockersf** [comment]
As mentioned above, this is done in the GLTF loader, but it still fails for a mesh from another source

**Comment by PravinKumar95** [comment]
Why not calculate flat normals in the shader if normal attribute is not found

**Comment by PravinKumar95** [comment]
I think this addressed in 0.6 release. Closing for now
