### ISSUE TITLE
Roadmap update?

### ISSUE THREAD

**Issue by MouseProducedGames** [bevyengine/bevy#2399]
The roadmap has not been updated since November 24th, 2020.

https://github.com/bevyengine/bevy/projects/1

**Comment by james7132** [comment]
As of a few moments ago, the roadmap has been retired. The decision was to have more targetted project boards to keep track of smaller targeted features for each focus area of the engine. A new one under the "beta projects category at the org level will be made soon with more actionable items on each card.
