### ISSUE TITLE
Support for creating cameras with custom projections

### ISSUE THREAD

**Issue by inodentry** [bevyengine/bevy#240]
I saw that both of the included `PerspectiveProjection` and `OrthographicProjection` implement a common trait called `Projection`, with methods to generate the `Mat4` matrix and to handle window resizing. This seems like a convenient interface for implementing a custom projection type in my game.

Since I could not use the predefined `Camera{2d,3d}Components` bundle, I tried to spawn a camera entity using a tuple with the components that those predefined bundles have, but with my own projection type.

I couldn't get anything to render on the screen.

My unconfirmed suspicion is that perhaps bevy includes some systems to process the camera which are not generic and only work with the predefined projection types.

I need some way to create a camera with an orthographic projection that is not based on window pixels. Such use cases are common, so bevy's camera support should be improved to give the user more flexibility.

**Comment by DJMcNab** [comment]
You need to add a `bevy_render::camera::camera_system::<MyCameraSystemHere>.system()` to the `POST_UPDATE` stage.
See below:
https://github.com/bevyengine/bevy/blob/979a1346a16898335bf1fe130c81d20297cd45e0/crates/bevy_render/src/lib.rs#L128-L134

**Comment by aevyrie** [comment]
Is there any reason the camera 3d components must be constrained to using a perspective matrix?
E.g., couldn't the more general case be used?
```rust
pub struct Camera3dComponents {
    pub camera: Camera,
    pub projection: Mat4,
    pub visible_entities: VisibleEntities,
    pub transform: Transform,
    pub global_transform: GlobalTransform,
}
```

**Comment by DJMcNab** [comment]
The matrix needs to be updated using the window width and height when that changes, when the window is resized. This has different effects on different projections

In future I expect it to become generic over the projection type.

**Comment by DJMcNab** [comment]
Triage: 
- `.system()` is no longer needed in the suggested fix.
- These bundles are now split into `PerspectiveCameraBundle` and `OrthographicCameraBundle`, with different constructor sets for each.
- We have `#[bundle]` for nested bundles, so we could create a shared 'BaseCameraBundle' (which is the `Camera3dComponents` suggested above)
- The documentation has not improved

**Comment by nicopap** [comment]
As far as I can tell, this is fixed.

Now bevy has a [`CameraProjection`](https://docs.rs/bevy/latest/bevy/render/camera/trait.CameraProjection.html) trait one can derive, and it can be added to bevy using the [`CameraProjectionPlugin`](https://docs.rs/bevy/latest/bevy/render/camera/struct.CameraProjectionPlugin.html).

An example of custom projection can be found on @Selene-Amanita's [`bevy_basic_portals`](https://github.com/selene-amanita/bevy_basic_portals) project.
