### ISSUE TITLE
Add a transform and Quaternion example section. 

### ISSUE THREAD

**Issue by jak6jak** [bevyengine/bevy#2400]
## How can Bevy's documentation be improved?
Currently there is not really a specific place to add transformation examples other than 2d or 3d. I think this would encourage more examples to be created about this topic. 

Examples that could be included:

- translation of object
- rotation of objects
- scaling of objects
-  translation, rotation, and scaling at the same time
- show the difference between global transform and Transform
- the 3d parenting example could be moved into here.
- more examples showcasing the various methods on Transform and Quaternion.

**Comment by alice-i-cecile** [comment]
This is largely complete, so I'm going to close it out :)
