### ISSUE TITLE
Replace the font renderer with one without the issues of anti-aliasing/hinting/subpixel/baseline

### ISSUE THREAD

**Issue by dasifefe** [bevyengine/bevy#2404]
## Bevy version

Bevy 0.5.0.

## What you did

Comparison between the font rendered by Bevy (ab_glyph) and Firefox (with subpixel disabled and subpixel enabled).

## What you expected to happen

The font rendered with anti-aliasing in Bevy should be as rendered as close as possible as in Firefox (readable in small sizes, sharp, and correct positioning of glyphs).

### Issue 1: aliasing

Font in Bevy is "bulkier". It is possible to notice that the anti-aliasing in Bevy generates a pixel with higher lightness than in the other implementations, that it is possible to notice single pixels without zooming-in (look at the letter `e`, for example).

The line on the top is Bevy, the line in the middle is Firefox with subpixel disabled, and the line bellow is Firefox with subpixel enabled:
![f](https://user-images.githubusercontent.com/59259533/123550812-a374fb00-d745-11eb-8f8f-3b7d02e8ac73.png)
![f2](https://user-images.githubusercontent.com/59259533/123550962-13838100-d746-11eb-9d99-8752c8cb5db9.png)

The values indicated are the values of LCh lightness (using the color picker from GIMP). The lightness of the anti-alias in the Bevy implementation is 3-5 times than in the other implementations.

### Issue 2: vertical positioning

Another issue is the positioning of the glyphs on the baseline. In Bevy, with certain fonts at certain font sizes, the glyphs will be rendered on the incorrect vertical position:

![image](https://user-images.githubusercontent.com/59259533/123551320-a40e9100-d747-11eb-8908-d2d324559534.png)

It only happens with certain sizes, but not others. The examples above (showing the aliasing issues) are rendered in the correct vertical position, but not at size 15.

### Possible issue 3: sizing

The size defined in `TextStyle` does not match the size in other implementations. On the first image (showing the aliasing issues), for example, I had to use the size `14.5` to match the font size `12` in Firefox.

## Additional information

I did this experiment using the font "Fredoka One" on Google Fonts for comparison.

## Proposal

Replace the Bevy implementation with one of two existing solutions: [`fontdue`](https://github.com/mooman219/fontdue/) or [`swash`](https://github.com/dfrg/swash). It seems that these two libraries are the best options for font rendering in pure Rust. We should evaluate which features that both have or don't have that are important for Bevy.

**Comment by MinerSebas** [comment]
Could you also test Bevy with its [`subpixel_glyph_atlas`](https://github.com/bevyengine/bevy/blob/main/Cargo.toml#L76) Feature enabled?

**Comment by mockersf** [comment]
> Issue 2: vertical positioning

Good ol' wavy text... https://github.com/bevyengine/bevy/issues/283, https://github.com/bevyengine/bevy/pull/725, https://github.com/bevyengine/bevy/pull/765

**Comment by alice-i-cecile** [comment]
I noticed 1 and 2 while working on my Sudoku game, and strongly support this proposal. Clean text rendering is important and basically impossible to fix as an end user.

**Comment by dasifefe** [comment]
> Could you also test Bevy with its subpixel_glyph_atlas Feature enabled?

I will give a try.

Akoriam ([on Discord](https://discord.com/channels/691052431525675048/730525730601041940/858785304940904529) showed that the first issue might be solved by applying (2.2) gamma correction in the font renderer and the aliasing of Bevy will look like the anti-aliasing of non-subpixel anti-aliasing of Firefox. What remains to determine if it is worth switching to `fontdue` or `swash` to 1) solve the bug with vertical positioning or to 2) have the features of those libraries (`fontdue`/`swash`) in Bevy.

**Comment by kirawi** [comment]
Swash would also allow shaping.

**Comment by alice-i-cecile** [comment]
> Has there been any further discussion on this?

Not a great deal, but it seems clear that our current font rendering solution is inadequate. IMO, opening up a draft PR with a 
 backend swap and showing the before / after results would help us come to a concrete decision sooner.

**Comment by kirawi** [comment]
A few weeks ago https://github.com/pop-os/cosmic-text was released.

**Comment by alice-i-cecile** [comment]
Yep I'm in favor of exploring a migration to this.

**Comment by rparrett** [comment]
Bevy now uses `swash` by way of `cosmic-text`.

As far as I can tell, all three issues enumerated in the description are now resolved.
