### ISSUE TITLE
QuerySet does not appear to trigger change detection properly

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2408]
## Bevy version

0.5

## What you did

From a user's system on [Discord](https://discord.com/channels/691052431525675048/742884593551802431/859143303000621088):

```rust

pub fn check_tasks(
    mut commands: Commands,
    sim_params: Res<SimParams>,
    physical_object_query: Query<&PhysicalObject>,
    physical_object_id_query: Query<Entity, With<PhysicalObject>>,
    mut resource_carrier_query: Query<&mut ResourceCarrier>,
    mut resource_storage_query: Query<(&mut ResourceStorage, Entity)>,
    mut tasks_queries: QuerySet<(Query<&mut TaskQue>, Query<Entity, Changed<TaskQue>>)>,
    mut ev_check_task_event: EventReader<CheckTaskEvent>,
) {
    let creature_ids: Vec<Entity> = tasks_queries
        .q1()
        .iter()
        .chain(
            ev_check_task_event
                .iter()
                .map(|CheckTaskEvent(creature_id)| *creature_id),
        )
        .collect();
    println!("Something was updated for {}", creature_ids.len());

    for creature_id in creature_ids {
        if let Ok(mut task_que_component) = tasks_queries.q0_mut().get_mut(creature_id) {
            if let Some(task) = task_que_component.0.front() {
                println!("Something was updated");
                if try_accomplish_task(
                    &mut commands,
                    &sim_params.world_rect,
                    &physical_object_query,
                    &physical_object_id_query,
                    &mut resource_carrier_query,
                    &mut resource_storage_query,
                    &creature_id,
                    &task,
                ) {
                    task_que_component.0.pop_front();
                    *task_que_component = TaskQue(task_que_component.0.clone());
                    println!("dereferenced");
                }
            }
        }
    }
}
``` 

`TaskQue` contains a standard `VecDeque`, and the method called is [pop_front](https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.pop_front).

## What you expected to happen

The `TaskQue` component should be marked as changed.

## What actually happened

The `TaskQue` component is not marked as changed.

## Additional information

This needs a minimal reproduction still. 

```rust
        if let Ok(mut task_que_component) = tasks_queries.q0_mut().get_mut(creature_id) {
```

I think that `QuerySet` is the most likely candidate, but `get_mut` may be responsible instead.

Even if `pop_front` doesn't trigger change detection, setting an entirely new value certainly should.

**Comment by rgripper** [comment]
Here is the log
```
Something was updated for 0
Arrived to a target located at [93.286224, -113.35399]
Something was updated for 1
Something was updated
try_accomplish_task CutTree(1296v0)
At the tree. Ready to cut
dereferenced
Something was updated for 0
Something was updated for 0
Something was updated for 0
Something was updated for 0
```

**Comment by NathanSWard** [comment]
What is a `TaskQue`?
Or more specifically, what are the definitions of it's methods?

**Comment by NathanSWard** [comment]
Wait, what's the purpose of even using a `QuerySet` here?
Can't you just do
```rust
mut tasks_queries: Query<(Entity, &mut TaskQue), Changed<TaskQue>>,
```

**Comment by NathanSWard** [comment]
I can't seem to reproduce this, even with the following test:
```rust
#[test]
    fn or_query_set_system() {
        // Regression test for issue #762
        fn query_system(
            mut ran: ResMut<bool>,
            set: QuerySet<(
                Query<(), Or<(Changed<A>, Changed<B>)>>,
                Query<(), Or<(Added<A>, Added<B>)>>,
            )>,
        ) {
            let changed = set.q0().iter().count();
            let added = set.q1().iter().count();

            assert_eq!(changed, 1);
            assert_eq!(added, 1);

            *ran = true;
        }

        let mut world = World::default();
        world.insert_resource(false);
        world.spawn().insert_bundle((A, B));

        run_system(&mut world, query_system.system());

        assert!(*world.get_resource::<bool>().unwrap(), "system ran");
    }
```

Is it possible that `try_accomplish_task` is returning false, which would then cause change detection to **not** be triggered?

**Comment by Guvante** [comment]
I did a minimal repro and certainly saw the behavior but after adding a bunch of tracing found that change tracking was triggering as expected. However change tracking tracks "changed since last system run" which seems to be exclusive of changes made by the system itself.

`is_changed()` is roughly `last_change_tick < change_tick` which in the context of the above program you will just get `last_change_tick == change_tick`.

**Comment by alice-i-cecile** [comment]
> However change tracking tracks "changed since last system run" which seems to be exclusive of changes made by the system itself.

Correct: that's the intended behavior for it. See #2681, which would cause it to be inclusive of the changes made by the system itself. Does the user's code rely on that behavior? It's simple to add: we're just short on compelling reasons to do so.

**Comment by Guvante** [comment]
Certainly, it is looking for `Changed<TaskQue>` to "trigger" based on the modification to `Query<&mut TaskQue>`. In fact this cyclical relationship appears to be the reason they are using a `QuerySet`.

As an alternative sending a `CheckTaskEvent` using an `EventWriter` should be mostly equivalent in this snippet. Of course there isn't enough here to know if that is an acceptable workaround.

**Comment by rgripper** [comment]
Indeed, using `CheckTaskEvent` is how I ended up notifying about the update. It's just the `Changed<>` query felt more declarative, but more magical, it was hard to believe that all sorts of changes are detected as Changed. In the end imperative but simple solution won over declarative "gray" magic. That's for the explanation!
