### ISSUE TITLE
spawn_batch using empty bundle panics

### ISSUE THREAD

**Issue by TheRawMeatball** [bevyengine/bevy#2435]
Bevy version: b52edc1

```rs
use bevy::ecs::prelude::*;

fn main() {
    let mut world = World::new();
    world.spawn_batch((0..1).map(|_| ()));
}
```
This code panics.
## Additional information

Initially found on discord: https://discord.com/channels/691052431525675048/742884593551802431/861612284945891339

**Comment by iobtl** [comment]
Hello, what would be a reasonable intended behaviour for spawning of an empty bundle? Should it simply return with no underlying changes applied to the `world` instance?

**Comment by mockersf** [comment]
it should work the same way as `world.spawn().insert(())`, so it should still spawn the entities

**Comment by Davier** [comment]
The issue seems to be that at [this point](https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/src/world/spawn_batch.rs#L52), `archetype_id == ArchetypeId::empty()`. However I don't know how to fix it.

**Comment by james7132** [comment]
This no longer seems to panic as of c3c4088317f0ea09de8d96e22fa5beb28e486c30.
