### ISSUE TITLE
Performance degradation over time due to UI

### ISSUE THREAD

**Issue by ISibboI** [bevyengine/bevy#2451]
## Bevy version

0.5

## Operating system & version

Windows 10

## What you did

Create a custom camera for my scene (not sure if this is related).
Add the `UiCameraBundle`.
Create some UI.
Compile with `--release`.

## What you expected to happen

Framerate is always at 60, since my project is so simple

## What actually happened

Frame rate starts at 60 but degrades to 40 after a few seconds, and after a minute or two it is at 20.

## Additional information

This does not happen when the line adding the `UiCameraBundle` is commented out, even though the other UI stuff is still active.

I used the profiling feature, and it seems like the time is lost in the post_update stage.

Here is the project in question: https://github.com/ISibboI/santa-game

Please ask for more details, as describing my whole project would be a whole lot of work, and I have no idea which parts are relevant.

**Comment by mockersf** [comment]
You are spawning the UI Camera in every frame

You should add your system `dialogue_setup_system` as a startup system to avoid that: https://github.com/ISibboI/santa-game/blob/c39b752d2533a33e9ba1af3e989f40186cb569f9/src/dialogue.rs#L183

**Comment by ISibboI** [comment]
Thanks, I did not realise! That solved it.

Hm, to prevent others from making the same mistake, maybe there should be a warning logged when more than one UICameraBundle is spawned?

**Comment by cart** [comment]
In the future there will be Good Reasons:tm: to have more than one UI camera (ex: rendering a second ui to a texture, multiple windows, etc). I don't think that should be a warning case.

**Comment by alice-i-cecile** [comment]
Closing this now as I don't think there's anything to be done right now. Better inspection tools in the future will help catch issues like this though.
