### ISSUE TITLE
TextureAtlasBuilder does not preserve order of inserted textures leading to incorrect animations

### ISSUE THREAD

**Issue by DiDeoxy** [bevyengine/bevy#2459]
## Bevy version

0.5.0

## Operating system & version

Windows 10, Ubuntu 20.04

## What you did

Built a TextureAtlas using TextureAtlasBuilder
Used the TextureAtlas to animate a Sprite by incrementing the index

## What you expected to happen

The Textures would play in the order inserted as the index is incremented

## What actually happened

The Textures play in an arbitrary order determined seemingly at runtime (different runs of the game have different frame orders)

## Additional information

None

**Comment by joshuajbouw** [comment]
This imo is intended and means incorrect usage of the tilemap. You need to keep track of which index it gets mapped to. I had a similar issue but getting rid of the HashSet (iirc that was what was being used) inside will only provide a negative impact on texture storage.

**Comment by DiDeoxy** [comment]
Hey, Thanks for the reply!

I'm not using a tilemap, I am adding individual textures to the builder using add_texture() and then building the texture atlas with finish(). I don't see a way to get the internal index of each texture in the TextureAtlas, could you elaborate?

**Comment by DJMcNab** [comment]
[`get_index_texture`]( https://docs.rs/bevy/0.3.0/bevy/sprite/struct.TextureAtlas.html#method.get_texture_index) lets you get the index for the texture.
