### ISSUE TITLE
 Need to list a set of dependencies for linux clients

### ISSUE THREAD

**Issue by Dispersia** [bevyengine/bevy#246]
Many linux clients require different dependencies to be able to run base bevy, such as ubuntu needing libx11-dev (for x11) and libasound2-dev. This should be listed in an obvious spot for those to see before encountering the issues, or at least can find fast

**Comment by cart** [comment]
The "Setup" section in The Bevy Book covers this. But we should probably link to that directly from the readme.

https://bevyengine.org/learn/book/getting-started/setup/

**Comment by Dispersia** [comment]
Fixed under #257
