### ISSUE TITLE
Proposal for bringing SnowFS to Bevy

### ISSUE THREAD

**Issue by seb-mtl** [bevyengine/bevy#2483]
Hello, I am the creator of an open-source project called [SnowFS](https://github.com/snowtrack/snowfs). SnowFS is a lightweight and performant VCS with a focus on graphic projects and binary files.

The project is developed in TypeScript because it was initially developed for an Electron app. Due to my C++ roots, I planned to port SnowFS back to C++, but I am more and more eye-balling with Rust these days.

I heard there is a demand for a VCS in Bevy, and I would love to hear your thoughts on the following proposal.  Would you be interested in helping out bringing SnowFS to Rust / Bevy? If you think there is a potential fit, I would be happy to hear your thoughts on this either here or on Discord.

Any ideas or feedbacks on this topic is highly appreciated!

**Comment by alice-i-cecile** [comment]
Cool! Yes, version control integration is very much needed for both scenes and assets: Git is not really up to the task.

@cart could you convert this to a discussion? We can hash out the basic plan there (and in #editor on Discord) and then if there's buy-in I'd be happy to help out with the RFC process.
