### ISSUE TITLE
Window scale_factor_override() doesn't affect cursor position

### ISSUE THREAD

**Issue by AidanBlair** [bevyengine/bevy#2501]
## Bevy version

0.5

## Operating system & version

Windows 10

## What you did

Because my screen has a high DPI and scales applications to 125%, I created a window with scale_factor_override: Some(1.0). I also added a button in the middle of the window.

## What you expected to happen

The window will display at 100% scale (rather than 125%) and the cursor's position will update accordingly.

## What actually happened

While the window did display correctly at 100% scale, the cursor position seems to still behave as if it was scaled to 125%. To click on the button, I had to click above and to the right of the button, and when I printed out the cursor position the top right corner's position was (480, 360) rather than the actual size of the window, (640, 480).

**Comment by AidanBlair** [comment]
I've attached an example program. If you don't have a font installed you can tell when the button is selected by the colour changing. Also, I have it printing out the cursor's location, to show that it doesn't match up with the actual size of the window.

`use bevy::prelude::*;
use bevy::window::{CursorMoved};

fn main() {
    App::build()
        .insert_resource(WindowDescriptor {
            title: "Scaling Example".to_string(),
            width: 640.0,
            height: 480.0,
            scale_factor_override: Some(1.0),
            ..Default::default()
        })
        .add_plugins(DefaultPlugins)
        .init_resource::<ButtonMaterials>()
        .add_startup_system(setup.system())
        .add_system(button_system.system())
        .add_system(mouse_event_system.system())
        .run();
}

struct ButtonMaterials {
    normal: Handle<ColorMaterial>,
    hovered: Handle<ColorMaterial>,
    pressed: Handle<ColorMaterial>,
}

impl FromWorld for ButtonMaterials {
    fn from_world(world: &mut World) -> Self {
        let mut materials = world.get_resource_mut::<Assets<ColorMaterial>>().unwrap();
        ButtonMaterials {
            normal: materials.add(Color::rgb(0.15, 0.15, 0.15).into()),
            hovered: materials.add(Color::rgb(0.25, 0.25, 0.25).into()),
            pressed: materials.add(Color::rgb(0.35, 0.75, 0.35).into()),
        }
    }
}

fn button_system(
    button_materials: Res<ButtonMaterials>,
    mut interaction_query: Query<
        (&Interaction, &mut Handle<ColorMaterial>, &Children),
        (Changed<Interaction>, With<Button>),
    >,
    mut text_query: Query<&mut Text>,
) {
    for (interaction, mut material, children) in interaction_query.iter_mut() {
        let mut text = text_query.get_mut(children[0]).unwrap();
        match *interaction {
            Interaction::Clicked => {
                text.sections[0].value = "Press".to_string();
                *material = button_materials.pressed.clone();
            }
            Interaction::Hovered => {
                text.sections[0].value = "Hover".to_string();
                *material = button_materials.hovered.clone();
            }
            Interaction::None => {
                text.sections[0].value = "Button".to_string();
                *material = button_materials.normal.clone();
            }
        }
    }
}

fn setup(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    button_materials: Res<ButtonMaterials>,
) {
    // ui camera
    commands.spawn_bundle(UiCameraBundle::default());
    commands
        .spawn_bundle(ButtonBundle {
            style: Style {
                size: Size::new(Val::Px(150.0), Val::Px(65.0)),
                // center button
                margin: Rect::all(Val::Auto),
                // horizontally center child text
                justify_content: JustifyContent::Center,
                // vertically center child text
                align_items: AlignItems::Center,
                ..Default::default()
            },
            material: button_materials.normal.clone(),
            ..Default::default()
        })
        .with_children(|parent| {
            parent.spawn_bundle(TextBundle {
                text: Text::with_section(
                    "Button",
                    TextStyle {
                        font: asset_server.load("fonts/FiraSans-Bold.ttf"),
                        font_size: 40.0,
                        color: Color::rgb(0.9, 0.9, 0.9),
                    },
                    Default::default(),
                ),
                ..Default::default()
            });
        });
}

fn mouse_event_system(
    mut cursor_moved_events: EventReader<CursorMoved>,
) {
    for event in cursor_moved_events.iter() {
        println!("{:?}", event.position);
    }
}`

**Comment by alice-i-cecile** [comment]
Doing a bit of digging, this issue seems like it might have promising breadcrumbs from winit, our upstream dependency for windowing: https://github.com/rust-windowing/winit/issues/1491

Now, let's track how cursor position is set... 

[`update_cursor_position_from_backend`](https://github.com/bevyengine/bevy/blob/85ab55a05b3386275c9ff6c3cf34bbea0fc6b43d/crates/bevy_window/src/window.rs#L488
) seems to be the function in question. Let's see where that's called: [here](https://github.com/bevyengine/bevy/blob/927973ce6aeab62e65fe8bf2584c4f26b8904df8/crates/bevy_winit/src/lib.rs#L315), in the `bevy_winit` module.

We have access to the scale factor information in that function already; it looks like it's just a matter of adding a multiplication step just above L315 (and adding some tests).
