### ISSUE TITLE
no function or associated item named `new_immediate` found for trait object `dyn Watcher` in the current scope

### ISSUE THREAD

**Issue by bigidea-kz** [bevyengine/bevy#2530]
## Bevy version

0.5.0

## Operating system & version

macOS Catalina (10.15.7)

## What you did

```
use bevy::prelude::*;

fn main() {
    App::build().run();
}
```

```
cargo run
```

## What actually happened

It took me 14 hours and nothing worked

## Additional information

![Снимок экрана 2021-07-24 в 07 55 28](https://user-images.githubusercontent.com/44386084/126854452-d68a1948-3b59-464c-92dc-2164de9b1219.png)

**Comment by mockersf** [comment]
Thank you for the report!

A new version of `bevy_asset` (0.5.1) has been released that should fix this issue, cargo should pick it up if you run `cargo update`

**Comment by bigidea-kz** [comment]
Thank you)

**Comment by johanhelsing** [comment]
This also happens when checking out the bevy `latest` branch and running the `hello_world` example (as per the instructions in the readme).

The `main` branch works fine, though.

**Comment by cart** [comment]
Ah yeah `latest` should be updated to point to release-0.5.1

**Comment by cart** [comment]
Done!
