### ISSUE TITLE
HandleUntyped as a system param?

### ISSUE THREAD

**Issue by Dapeos** [bevyengine/bevy#2562]
Hi, (might be dumb) 
I am trying to use HandleUntyped as a parameter to a system as a Local<HandleUntyped>. But because HandleUntyped doesn't implement Default, I am unable to. Honestly I am not sure how a default impl of HandleUntyped should work.

Currently I have similar separate systems for each unique Handle Type but I am wondering if I am missing something simple. 
Thanks,

**Comment by Dapeos** [comment]
I organized things differently.

**Comment by alice-i-cecile** [comment]
For future reference, #2491 should provide an excellent solution to this going forward by allowing you to include non-defaultable Local resources.
