### ISSUE TITLE
Remove () as a valid bundle

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2567]
From #2522, the 0-element-tuple creates a bundle currently. This is always user error in some form, and should be caught at compile time.

To change this, modify the 0 in this line to a 1: https://github.com/bevyengine/bevy/blob/86cc70b9028e04014f9248792041b25602a1d0b1/crates/bevy_ecs/src/bundle.rs#L96

**Comment by james7132** [comment]
`all_tuples` currently has a bug where it errors out when the start is anything other than 0. This was caught and fixed as a part of #2381, but that hasn't been merged yet.

I can split that out if need be.

**Comment by alice-i-cecile** [comment]
Closing this as I found a good use of the empty tuple! When combined with `spawn_batch` it can be used to quickly make large numbers of empty entities. If nothing else, that's useful for benchmarking.
