### ISSUE TITLE
#[derive(SystemParam)] only works with lifetime named exactly 'a

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2587]
## Bevy version

0.5

## What you did

I renamed 'a to 'b in the [SystemParam example](https://docs.rs/bevy/0.5.0/bevy/ecs/system/trait.SystemParam.html).

```rust
use bevy::ecs::system::SystemParam;
use bevy::prelude::*;

fn main() {
    App::build().add_system(my_system.system()).run();
}

#[derive(SystemParam)]
pub struct MyParam<'b> {
    foo: Res<'b, usize>,
}

fn my_system(param: MyParam) {
    // Access the resource through `param.foo`
}
```

## What you expected to happen

The code continues to compile.

## What actually happened

`use of undeclared lifetime name `'a``

## Additional information

The relevant macro can be found at https://github.com/bevyengine/bevy/blob/5ffff03b33d72bfc4ef81ca9228bf5c3c19fbd8c/crates/bevy_ecs/macros/src/lib.rs#L311

**Comment by Ratysz** [comment]
Does #2605 fix this?

**Comment by alice-i-cecile** [comment]
> Does #2605 fix this?

Yes and no. It gives the hard-coded lifetime names a much better reason to exist (easy, low-boilerplate lifetime differentiation), but they're still necessarily hard-coded. I'm going to close this still; as discussed in #2633, I think that this behavior is as good as we get.
