### ISSUE TITLE
Transform looking_at its different to Mat4 look_at_rh

### ISSUE THREAD

**Issue by superdump** [bevyengine/bevy#2592]
## Bevy version

main as of 2021-08-03.

## Operating system & version 

macOS 

## What you did

Compare `Transform::from_xyz(eye).looking_at(target, up).compute_matrix()` with `Mat4::look_at_rh(eye, target, up)`.

## What you expected to happen

They are the same.

## What actually happened

They seem to be each other’s inverse! At least in cases of 90-degree rotations for cube map faces.

**Comment by DJMcNab** [comment]
Likely a duplicate of https://github.com/bevyengine/bevy/issues/1153

**Comment by alice-i-cecile** [comment]
Closing as duplicate :)
