### ISSUE TITLE
Drop called multiple times if drop panics.

### ISSUE THREAD

**Issue by mahkoh** [bevyengine/bevy#2597]
## Bevy version

Master

## Operating system & version

Arch Linux

## What you did

```rust
use bevy::prelude::*;

struct Dropper(i32);

impl Drop for Dropper {
    fn drop(&mut self) {
        println!("drop {}", self.0);
        if self.0 == 0 {
            panic!();
        }
    }
}

fn main() {
    App::new()
        .add_startup_system(setup.system())
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn()
        .insert(Dropper(0))
        .insert(Dropper(1));
}
```

## What you expected to happen

`drop 0` is printed at most once.

## What actually happened

`drop 0` is printed twice.

## Additional information

Several functions in https://github.com/bevyengine/bevy/blob/43d99bb583866c1adb4aa88f19b88637df0a7f33/crates/bevy_ecs/src/storage/blob_vec.rs do not handle `self.drop` unwinding (nor require their callers to do so.)

**Comment by bjorn3** [comment]
Only `replace_unchecked` doesn't handle it I think: https://github.com/bevyengine/bevy/blob/43d99bb583866c1adb4aa88f19b88637df0a7f33/crates/bevy_ecs/src/storage/blob_vec.rs#L101-L106

`swap_remove_and_drop_unchecked` calls `self.drop` as last action before returning: https://github.com/bevyengine/bevy/blob/43d99bb583866c1adb4aa88f19b88637df0a7f33/crates/bevy_ecs/src/storage/blob_vec.rs#L160-L164

`clear` sets `self.len = 0` first before dropping anything, ensuring a leak in case of a panicking drop: https://github.com/bevyengine/bevy/blob/43d99bb583866c1adb4aa88f19b88637df0a7f33/crates/bevy_ecs/src/storage/blob_vec.rs#L183-L196

**Comment by mahkoh** [comment]
> `swap_remove_and_drop_unchecked` calls `self.drop` as last action before returning:

It depends on what the callers do. In the code path I've looked at, the entity is [removed](https://github.com/bevyengine/bevy/blob/43d99bb583866c1adb4aa88f19b88637df0a7f33/crates/bevy_ecs/src/world/entity_ref.rs#L489-L492) from the world before [drop](https://github.com/bevyengine/bevy/blob/43d99bb583866c1adb4aa88f19b88637df0a7f33/crates/bevy_ecs/src/world/entity_ref.rs#L514-L516) is called. So there is no problem.

Without the additional knowledge that `swap_remove_unchecked` can panic and leave memory in a half-dropped state, it might also seem valid to swap the relative positions of the linked lines.

**Comment by bjorn3** [comment]
`swap_remove_and_drop_unchecked` and `clear` should be fine. Only `replace_unchecked` has a bug.

**Comment by mahkoh** [comment]
Like I said it depends on what the contract between `swap_remove_and_drop_unchecked` and its callers is. For example, the following program also prints `drop 0` twice but `replace_unchecked` is never called.

```rust
use bevy::prelude::*;

struct Dropper(i32);

impl Drop for Dropper {
    fn drop(&mut self) {
        println!("drop {}", self.0);
        if self.0 == 0 {
            panic!();
        }
    }
}

fn main() {
    let mut world = World::new();

    let e1 = world.spawn().insert(Dropper(0)).id();

    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        world.despawn(e1);
    }));

    world.spawn().insert(Dropper(1)).id();
}
```

**Comment by bjorn3** [comment]
That did be a bug in `World`, not `BlobVec` I think.
