### ISSUE TITLE
Rustfmt on Windows changes line endings

### ISSUE THREAD

**Issue by AmionSky** [bevyengine/bevy#260]
Running `cargo fmt` on windows changes all line endings from `LF` to `CRLF`.
The `rustfmt.toml` contains `newline_style = "Unix"`, could it be a rustfmt issue?

**Comment by AmionSky** [comment]
I just updated nightly to that version but it is still happening for me.
`cargo fmt --version` gives me: `rustfmt 1.4.20-nightly (48f6c32e 2020-08-09)`

**Comment by DJMcNab** [comment]
I get the same version information. What is your `git config core.autocrlf` (you can just run that command)? I don't know if rustfmt looks at that, but it might
For the record, mine is `input`

**Comment by AmionSky** [comment]
It's `true`, it might be the issue

**Comment by DJMcNab** [comment]
I think what is actually happening then is that git is checking out the files as `CRLF`, then rustfmt sees that and converts them to `LF`, then git sees that it is changed. But I think when you add the files to the index, (using `git add`), it will see that they are the same as on HEAD and so will remove those changes. So in theory it would be fine to leave it that way (as in the commits you make will have LF), but it just makes things painful for you.
Line endings are weird.
Hopefully that's fixed it.
