### ISSUE TITLE
unwrap() fails in an AssetServer::update_asset_storage() if two assets are registered with the same uuid

### ISSUE THREAD

**Issue by TheLeonsver1** [bevyengine/bevy#2610]
## How can Bevy's documentation be improved?

The unwrap here:
https://github.com/bevyengine/bevy/blob/43d99bb583866c1adb4aa88f19b88637df0a7f33/crates/bevy_asset/src/asset_server.rs#L501-L503

fails when two asset types are registered with the same UUID, the stack trace of the crash isn't assisting a lot in understanding why that might happen. I would like it If it could be documented.

**Comment by alice-i-cecile** [comment]
My first impression is that this could be improved by changing the unwrap to an `.expect` with a useful error message. It looks like this should fail if the [`downcast_ref`](https://doc.rust-lang.org/std/any/trait.Any.html#method.downcast_ref) results in the boxed value not actually being of the appropriate type.

In this case, that means a failure in type registration: I suspect you'll get a panic at the same place if you fail to register it at all.

**Comment by alice-i-cecile** [comment]
@TheRawMeatball points out that this core issue of duplicate type registration can (and should) first be caught at the `add_asset` call [here](https://github.com/bevyengine/bevy/blob/b724a0f586e6186f2a6ce4eb7903be0e340649e9/crates/bevy_asset/src/assets.rs). Following the chain, it looks like this is actually an issue with `register_type`, which should fail around [here](https://github.com/bevyengine/bevy/blob/19799b8d94de9057cbf2fba3077cf9cd0f26a9a4/crates/bevy_reflect/src/type_registry.rs#L41) if a duplicate exists. IMO this should be a `Result`, but I'm not sure that plays nice with our builder pattern API for App...

 That said, even improving the panic with a real error message would help folks debug.

**Comment by ShadowCurse** [comment]
Hi everyone. I have looked into this issue and it seems that problem lies [here](https://github.com/bevyengine/bevy/blob/e30d600dbf4ea76cf8bc4f87ce830202a8e741d2/crates/bevy_asset/src/asset_server.rs#L96). Basically when we register a new asset type there is no check if entry with the same UUID exists. If two types have the same UUID, the later type will overwrite the previous one. This is why `downcast_ref` fails later.
I think a simple check with an error message would be fine for now.
Something like this:
```rust
if self.server.asset_lifecycles.read().contains_key(&T::TYPE_UUID) {
    panic!("Asset with UUID: {:?} already registered. Can not register another type with the same UUID", T::TYPE_UUID);
}
```
