### ISSUE TITLE
Generate links to definition in rustdoc source code pages

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2611]
## How can Bevy's documentation be improved?

https://github.com/rust-lang/rust/pull/84176 (just merged) allows rustdoc to generate links to definitions in source code pages. This new feature is disabled by default. Once this moves off nightly we should enable the feature with the `--generate-link-to-definition` option.

**Comment by mockersf** [comment]
Doesn't this need to be enabled by the one building the docs which is not us but docs.rs?

The doc built during CI are not published anywhere, having the links there wouldn't be visible

**Comment by bjorn3** [comment]
docs.rs uses nightly rustdoc. It also allows you to pass arbitrary flags to rustdoc using a section in `Cargo.toml` I believe.

**Comment by mockersf** [comment]
https://docs.rs/about/metadata

**Comment by BD103** [comment]
Marking this as unblocked. We now use nightly to build our docs, and so does docs.rs.

**Comment by NthTensor** [comment]
Closing as fixed.
