### ISSUE TITLE
How should I remove a specific component from the entity.

### ISSUE THREAD

**Issue by grislux55** [bevyengine/bevy#262]
The usage of bevy-ecs makes me feel very comfortable. But when using Commands to modify the World, I did not find a method for removing only one components, so how should I remove only one component from the entity? Do I have to use the thread local system to get the world then remove it?

**Comment by JohnDoneth** [comment]
I wrote that function and that is the correct use case. :+1: 
```rust
commands.remove_one::<SomeComponent>(entity);
```

**Comment by DJMcNab** [comment]
Ah, close enough. I still haven't internalised the turbofish rules

**Comment by memoryruins** [comment]
Note that `Commands::remove_one` is not on a released version of bevy yet.

**Comment by multun** [comment]
Note this should be avoided if possible, this is by design a pretty slow function: bevy tracks groups of entities that have the same components (such a group is called an archetype). When you remove a component, the entity will change archetype

**Comment by drmason13** [comment]
Is there a god alternative to recommend? (For better performance) I am admittedly new to game design using ECS, but would plan on using components to add/remove statuses. E.g. add a poison component to deal damage over time and remove when healed or after some amount of time.

In cases like these (multiple seconds between adding/removing components for maybe a hundred entities), is the performance hit from changing hit a concern?

**Comment by multun** [comment]
> In cases like these (multiple seconds between adding/removing components for maybe a hundred entities), is the performance hit from changing archetypes a concern?

Probably not if it's the scale of a second, if you're doing that a few thousands of times a second it's going to start to take a toll
Another option would be to just add an `Option<Poison>` component from the beginning

**Comment by cart** [comment]
Yup Option<Poison> is a good approach. You could also add a `StatusEffect` component, which then contains things like Poison inside.

**Comment by grislux55** [comment]
Thank you everyone, I made a mistake.  I forgot to check the master branch, so actually this should be what the next version will have.

**Comment by FelixSelter** [comment]
This has changed to: `commands.entity(entity).remove::<SomeComponent>();`
