### ISSUE TITLE
Filter queries within systems

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2621]
## What problem does this solve or what need does it fill?

You may need to access a query in both unfiltered and filtered forms within the same query.

## What solution would you like?

Add a `filter::<F>()` method to `Query`, allowing you to take new subsets of a query.

If you want to get really clever, ideally you'd be able to have safe access to multiple mutually exclusive parts of the query at once.

## What alternative(s) have you considered?

Filter over the entities one at a time using `Option` components and `.is_changed` methods. This is much slower, and less clear.

## Additional context

This is somewhat more complex than it might first appear. [Summarizing the discussion with @cart on this](https://discord.com/channels/691052431525675048/872974416403910697/873692739219378197):

1. Archetypes are currently locked during parallel system execution, so we can freely add new `With`, `Without` or `Changed` filters.
2. We can't access new `Changed` filters using a naive implementation of this, as other systems running in parallel could flip those flags.

We could add another trait to differentiate this and then disallow `Changed` filtering. Alternatively, we could force any user to explicitly request read-access to the relevant information by adding an `Info<T>` query parameter, which would communicate intent to the schedule correctly.

**Comment by james7132** [comment]
Is this doable now with `QueryLens`?

**Comment by alice-i-cecile** [comment]
Yep, calling this completed.

**Comment by hymm** [comment]
This looks more like the join functionality which isn't merged yet
