### ISSUE TITLE
Orthographic camera as a child prevents rendering any entities behind its parent

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#2626]
## Bevy version
0.5

## Operating system & version

Windows 10

## What you did

1. Create an entity with a SpriteBundle with a Z translation of A. 
2. Create another entity with a SpriteBundle with a Z translation of B, smaller than A.
3. Create an OrthographicCameraBundle using new_2d(), and set it to be a child of the entity created in step 1.

## What you expected to happen

The first sprite would render on top of the second.

## What actually happened

The Camera's Z local translation gets set to (far - 1.0) = 999.99. The global translation is than adjusted to be even higher up, because of it's parent.

This causes the lower sprite to be outside of the clipping plane, causing it to not render.

## Additional information

This is technically not a bug, but it's really unexpected. Perhaps there's a way to tell camera's to "only track this entity's XY translations, not Z".

**Comment by superdump** [comment]
Can you give concrete values for the A and B translations where you observe the problem? At first glance it sounds like you're putting a camera as a child, which translates it by the parent, and then the other sprite bundle is translated to be behind the camera, and so is not visible. It sounds like it's working as intended.

**Comment by JMS55** [comment]
I opened this issue years ago, and no longer am working on the game that had this problem. Nothing was really bugged, but it was just unexpected behavior to me. Perhaps I should have used a system to manually sync the camera with the player, rather than use parenting.
