### ISSUE TITLE
bevy_ecs example from README does not compile

### ISSUE THREAD

**Issue by vks** [bevyengine/bevy#2643]
## Bevy version

- bevy_ecs 0.5.0
- rustc 1.56.0-nightly (ccffcafd5 2021-08-11)

## Operating system & version

Windows 10

## What you did

I tried to compile [the example from the bevy_ecs README](https://github.com/bevyengine/bevy/tree/main/crates/bevy_ecs#using-bevy-ecs).

## What you expected to happen

The example compiles.

## What actually happened

The example failed to compile with the following error:

```
error[E0277]: the trait bound `for<'r, 's, 't0> fn(bevy_ecs::system::Query<'r, (&'s mut Position, &'t0 Velocity)>) {movement}: From<for<'r, 's, 't0> fn(bevy_ecs::system::Query<'r, (&'s mut Position, &'t0 Velocity)>) {movement}>` is not satisfied
   --> src\main.rs:118:22
    |
118 |         .with_system(movement)
    |                      ^^^^^^^^
    |                      |
    |                      expected an implementor of trait `From<for<'r, 's, 't0> fn(bevy_ecs::system::Query<'r, (&'s mut Position, &'t0 Velocity)>) {movement}>`
    |                      help: consider borrowing here: `&movement`
    |
    = note: required because of the requirements on the impl of `From<for<'r, 's, 't0> fn(bevy_ecs::system::Query<'r, (&'s mut Position, &'t0 Velocity)>) {movement}>` for `SystemDescriptor`
    = note: required because of the requirements on the impl of `Into<SystemDescriptor>` for `for<'r, 's, 't0> fn(bevy_ecs::system::Query<'r, (&'s mut Position, &'t0 Velocity)>) {movement}`

For more information about this error, try `rustc --explain E0277`.
```

**Comment by MinerSebas** [comment]
That readme contains changes from the `0.6` Release.
The change you encountered was that the `.system()` call is now optional.
Changing that line to `.with_system(movement.system())` should stop that error.
(Though there could still be other changes)

**Comment by bjorn3** [comment]
The examples on the main branch only work with the bevy version on the main branch. For bevy 0.5.0 you will need to look at https://github.com/bevyengine/bevy/tree/v0.5.0/examples

**Comment by alice-i-cecile** [comment]
Closing out for now <3 I do wish we had better tools to communicate this, but this isn't quite the place for that.

**Comment by vks** [comment]
@MinerSebas Thanks, that fixes it.
