### ISSUE TITLE
bevy_audio no device error cannot start without audio output devices

### ISSUE THREAD

**Issue by GameDevBhavesh** [bevyengine/bevy#2646]
## I run the command 'cargo run --example breakout'

I was just following the getting started section from the official site and then I tried to run the example.

it can be fixed by plugging the speaker or earphone but I don't usually prefer using any audio output devices while coding.

![image](https://user-images.githubusercontent.com/38570988/129313042-912f9923-545e-485d-a8a4-eaa09d1c2974.png)

**Comment by mockersf** [comment]
It should have been fixed on main with #2269, could you check?

**Comment by SolarLiner** [comment]
Closing as completed, as it should not panic anymore, only issue a warning.
