### ISSUE TITLE
Create a par_iter method on Query

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2649]
## What problem does this solve or what need does it fill?

Getting data out of parallel iterators over Queries using `par_for_each` is very complex, due to limitations on ownership.

## What solution would you like?

Create a `par_map` method on `Query`, which returns an iterator.

## What alternative(s) have you considered?

Pre-allocate the data, then use `par_for_each_mut` to mutate the pre-allocated data.

**Comment by TheRawMeatball** [comment]
If it's returning an iterator, then it'd be more accurate to call it par_iter. Also, this is already pretty much there iny unkempt PR #2088

**Comment by TheRawMeatball** [comment]
It's currently waiting on some sort of resolution to the problems outlined here: https://github.com/bevyengine/bevy/pull/2093#issuecomment-832197862

**Comment by rparrett** [comment]
Can this be closed?

**Comment by alice-i-cecile** [comment]
https://docs.rs/bevy/latest/bevy/ecs/system/struct.Query.html#method.par_iter

Yep!
