### ISSUE TITLE
How about replace `Commands` with `WorldBuilder`?

### ISSUE THREAD

**Issue by J-F-Liu** [bevyengine/bevy#265]
```rust
// this system spawns entities with the Position and Velocity components
fn setup(mut world: WorldBuilder) {
    world
        .spawn((Position(0.0), Velocity(1.0),))
        .spawn((Position(1.0), Velocity(2.0),));
}
```
When reading code, this feels more natural in concept.

I think the commands queue is an implementation detail, it should be contained in the world builder, and also insert resources by the world builder.

**Comment by TehPers** [comment]
This could be a nice step towards good type-safe commands too. You could also have EntityBuilder, ChildBuilder (already exists), etc. which would remove the need for panics in some of the functions.

**Comment by J-F-Liu** [comment]
Then I can think of the following options:
1. Rename `Commands` to `Commander`.
2. Replace `Commands` with `AppBuilder`,  which can access all the entities, systems, resources and app itself.
3. Rename current `World` to `EntityStorage`, current `App` to `World`.

Just for discussing, maybe either of the options not worth the effert.

**Comment by J-F-Liu** [comment]
After thinking more, I convinced myself to against these options:
1. `Commands` and `Commander` make not so much difference.
2. With `Res` and `Query` we are decomposing `App` for ease of access.
3. Bevy supports both games and tools, so `App` is more appropriate.

**Comment by Waridley** [comment]
So "Commands' controls the World and everything surrounding it? Sounds like a Universe :stuck_out_tongue_winking_eye:

**Comment by cart** [comment]
Yeah I _think_ I'm happy with the names as they are. I'll close this issue for now, but feel free to create new issues if you have new name ideas.
