### ISSUE TITLE
v0.5.0 doesn't compile

### ISSUE THREAD

**Issue by PorkSausages** [bevyengine/bevy#2660]
## Bevy version

v0.5.0

## Operating system & version

macOS 11.5

## What you did

Cloned bevy, ran `git checkout v0.5.0`, ran `cargo build`

## What you expected to happen

The code to compile

## What actually happened

The code did not compile due to these compiler errors:
```
Compiling bevy_asset v0.5.0 (/Users/tom/Documents/Git/bevy/crates/bevy_asset)
error[E0599]: no function or associated item named `new_immediate` found for trait object `dyn Watcher` in the current scope
  --> crates/bevy_asset/src/filesystem_watcher.rs:15:52
   |
15 |         let watcher: RecommendedWatcher = Watcher::new_immediate(move |res| {
   |                                                    ^^^^^^^^^^^^^ function or associated item not found in `dyn Watcher`

error[E0308]: mismatched types
  --> crates/bevy_asset/src/filesystem_watcher.rs:25:28
   |
24 |     pub fn watch<P: AsRef<Path>>(&mut self, path: P) -> Result<()> {
   |                  - this type parameter
25 |         self.watcher.watch(path, RecursiveMode::Recursive)
   |                            ^^^^ expected `&Path`, found type parameter `P`
   |
   = note:   expected reference `&Path`
           found type parameter `P`

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `bevy_asset` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by bjorn3** [comment]
Version 0.5.0 was broken by an upstream dependency. You need version 0.5.1. See the release-0.5.1 branch.

**Comment by PorkSausages** [comment]
Thank you. Is the v0.5.0 crate still ok to use?

**Comment by bjorn3** [comment]
If you add bevy 0.5.0 as new dependency or you run `cargo update`, cargo will automatically choose bevy_asset 0.5.1 which has the fix as that is the latest published version.

**Comment by PorkSausages** [comment]
Perfect, thank you for your help

**Comment by bestouff** [comment]
FWIW I have the very same compilation error on today's `master` branch.

**Comment by cart** [comment]
We switched from `master` to `main` awhile back. `master` is old, you should use `main` now.

**Comment by bestouff** [comment]
Oh, strange. Thanks for the hint !
