### ISSUE TITLE
Add advice on how to convince Git not to break line endings to CONTRIBUTING.md

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2664]
## How can Bevy's documentation be improved?

From time to time, new contributors will end up with their first PR resulting in 100s of files changed but no apparent changes. This seems to be due to line ending setting defaults controlled by Git, and is most prevalent on Windows.

We should have instructions for contributors on how to work around this.

**Comment by bjorn3** [comment]
I believe you can forcefully set the right newline mode using .gitattributes inside the repo.

**Comment by mockersf** [comment]
fixed by #2040 and #3197
