### ISSUE TITLE
TextureAtlas textures field has confusing name

### ISSUE THREAD

**Issue by DarkMara** [bevyengine/bevy#268]
The [TextureAtlas](https://github.com/bevyengine/bevy/blob/db1bf6478c98d822292415179cb0d69863c8bc5b/crates/bevy_sprite/src/texture_atlas.rs#L13) struct in bevy_sprites has a field named `textures` which is of type `Vec<Rect>`. I think this field should be named `sprites`, since it holds the rectangles of the sprites in the atlas. I also think the function `add_texture` should be renamed to `add_sprite`.

Is there any particular reason the field is called textures instead of sprites?

**Comment by alice-i-cecile** [comment]
> Perhaps a new label called api should be created. I'm sure I will not be the only person to suggest API changes. This issue isn't related to documentation.

This tag now exists, and is called "Usability"! IMO we should rename these fields and add to the documentation while we're there.

**Comment by superdump** [comment]
I disagree. The TextureAtlas should not be specific to sprites even if it is only used for sprites currently. If sprites needs some special case functionality then it should probably build on texture atlas.

**Comment by HPRIOR** [comment]
Should the issue be closed then if TextureAtlas is to remain generic?

**Comment by superdump** [comment]
Probably but I want to see if anyone else who is more familiar with or texture atlas implementation thinks differently to me.

**Comment by cart** [comment]
Yeah I think this should be closed. A texture atlas is a "texture that has stored textures inside of it". The type should be "generic" / not specific to sprites, so the current naming makes sense to me.
