### ISSUE TITLE
Handle multiple loaders with the same filetype when loads disambiguate by asset type parameter

### ISSUE THREAD

**Issue by Neurrone** [bevyengine/bevy#2680]
## Bevy version

0.5

## Operating system & version

Windows 10

## What you did

I'm working on integrating Bevy with the Synthizer audio library. I have 2 assets which I'm creating custom asset loaders for:

* `Buffer` for representing buffers of audio data, these are decoded upon load
* `Stream` for audio streams. These are decoded on demand, useful for long music tracks and the like

## What you expected to happen

Both asset loaders return the same file extensions, because I figured that as long as I disambiguated which one I wanted to use by providing a type parameter to load that it would use the right one.

## What actually happened

I registered the asset loader for loading buffers first, then streams. The second one was always chosen.

```rust
let h: Handle<Buffer> = asset_server.load("music/main menu.mp3");
```

I would expect this to correctly use the asset loader for buffers, as the type parameter provides enough information to disambiguate.

## Additional information

Any additional information you would like to add such as screenshots, logs, etc.

**Comment by Neurrone** [comment]
I realized this is the same as #367.

**Comment by NiklasEi** [comment]
Looking at #378 (which would have closed this issue), would we still hold off on a merge like that because of a potential move to atelier?

**Comment by Neurrone** [comment]
It looks like PRs have been raised and not merged due to concerns of building on top of the current solutions. However, its already been at least a year since this problem has been reported. So if an overhaul of the assets system is not going to be done soon, I'd appreciate a not ideal but workable solution being available in the meantime.

**Comment by alice-i-cecile** [comment]
Closing in favor of #367 :)
