### ISSUE TITLE
Hot reloading fires 2 asset modified events instead of one when a single file is overridden

### ISSUE THREAD

**Issue by Neurrone** [bevyengine/bevy#2689]
## Bevy version

0.5

## Operating system & version

Windows 10

## What you did

This is probably more noticeable because the asset I happened to be modifying was background music. I created a custom asset and asset loader for an audio library integration and listened to the asset modified events to update the sound in response to reloads.

## What you expected to happen

When I override a single file (my background music), the asset loader for it is called only once. I'm doing so by copying and pasting in windows explorer, and choosing yes if it asks me if I would like to override the file.

## What actually happened

I see the following logged:

```
Aug 19 19:05:37.114  WARN bevy_asset::asset_server: encountered an error while reading an asset: encountered an io error while loading asset: The process cannot access the file because it is being used by another process. (os error 32)                               
```

After that error, I'm able to see that the asset loader for the file is called, followed by the asset modification event, this is what I expected. 

However a few seconds later, I see logs indicating that the asset is being loaded a second time, then the asset modification event fires again.

I'm expecting this to only happen once. Although perhaps this may have to do with that error message that was also logged, perhaps some sort of retry mechanism? Am not sure what could be the cause of that error, since I have nothing else reading that folder.

## Additional information

Any additional information you would like to add such as screenshots, logs, etc.

**Comment by aloucks** [comment]
How are you saving the asset? Multiple writes to a file may trigger multiple notifications (in general). However, moves are atomic. How many notifications do you get if you save the file to a temp file and then move it to the final destination?

**Comment by mockersf** [comment]
[notify](https://github.com/notify-rs/notify) is used for filesystem watching, could you check with that library directly how it works for you? 

[This example](https://github.com/notify-rs/notify/blob/main/examples/monitor_raw.rs) looks close to how it's used in Bevy.
