### ISSUE TITLE
Improve release tag/branch organization

### ISSUE THREAD

**Issue by rukai** [bevyengine/bevy#2697]
branch/tag organization for different releases is currently very confusing.

My experience looks like:
1. The bevy book recommends running `git checkout v0.4.0` to checkout a released version of bevy: https://bevyengine.org/learn/book/getting-started/
2. 0.4 is a little out of date but its easy to change to 0.5.
3. So I do `git checkout v0.5.0` but then bevy fails to build because v0.5 is actually broken by notify's custom versioning system.
4. Then I go through much adventuring where I attempt to file a PR to fix this issue against the v0.5.0 tag which turns out to be impossible to make a PR against a tag. PRs need to be made against a branch.
5. Finally realize that there is already a branch made that fixes this issue release-0.5.1. I can build the 0.5 examples now.

A quick fix to make this easier for people trying to follow the book would be to make a tag for v0.5.1 and use that in the book.

A proper fix to make development easier for everyone would be to create a branch for each minor release instead of a tag.
That is, a branch for v0.4 a branch for v0.5 and so on.
Development for all patch releases for 0.5 (0.5.1, 0.5.2, 0.5.3 etc) would go into the v0.5 branch.
This makes it easier to check out the latest working examples for v0.5 and makes it easier to track development of patch releases for 0.5.
wgpu is an example of a project that follows this strategy and it works well for them.

**Comment by galkowskit** [comment]
Especially that 0.5 is broken, when using `git checkout v0.5.0`. There is a thread somewhere about using 0.5.1 but 0.5.1 is not available, you have to use `latest` instead.
https://githubmemory.com/repo/bevyengine/bevy/issues/2530

**Comment by rukai** [comment]
Looking at this again I can see that there is actually a `latest` branch which I totally missed!

I still think having a branch per minor release would be a good way to manage fixes for them.
But what bevy has atm does have some advantages so feel free to close this issue if you are happy with the current system.
