### ISSUE TITLE
Clippy emits some warnings on the nightly toolchain

### ISSUE THREAD

**Issue by sarkahn** [bevyengine/bevy#2698]
I forked the repo to contribute and was reading through CONTRIBUTE.md, one of the steps instructs you how to run CI validation. When I do so I get this error:

![clippy-error](https://user-images.githubusercontent.com/477520/130310398-9f56aee1-87f1-40ce-930a-50fdc843c333.png)

**Comment by bjorn3** [comment]
Which rustc version are you using? If you are using beta or nightly clippy probably added a new lint or changed one to trigger in more cases.

**Comment by sarkahn** [comment]
> Which rustc version are you using? If you are using beta or nightly clippy probably added a new lint or changed one to trigger in more cases.

You're right, I was using the nightly (1.56). When I switched back to 1.54 the error went away.

The getting started guide does list switching to nightly as a way to improve compilation times, so maybe this should still be fixed? I'm still new-ish to rust so wasn't sure how to fix the warning, google wasn't any help.

**Comment by alice-i-cecile** [comment]
Yep, we should have a warning that small things of this nature may be broken when using nightly. That belongs in the book IMO, over on https://github.com/bevyengine/bevy-website.

**Comment by sarkahn** [comment]
As of the last rust update the false positive for collapsible-match has been fixed. I update my pr to remove the #allows, and performing the steps from CONTRIBUTING.md no longer gives any errors:

```
cargo fmt --all -- --check (remove --check to let the command fix found problems)
cargo clippy --workspace --all-targets --all-features -- -D warnings -A clippy::type_complexity
```
