### ISSUE TITLE
Run Rudra on Bevy to improve correctness and safety

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2709]
[Rudra](https://github.com/sslab-gatech/Rudra#readme) is a new Rust tool to help audit unsafe code.

Bevy, and `bevy_ecs` in particular, contains quite a lot of tricky unsafe code. We should run this and fix issues it detects.

**Comment by bjorn3** [comment]
I already ran it on bevy_ecs. There were no issuws detected.

**Comment by alice-i-cecile** [comment]
Awesome; closing this for now. We can re-run it in the future if major rewrites occur, or if Rudra gets more features / is integrated into other safety tools.
