### ISSUE TITLE
Function naming effects Bevy systems and/or objects

### ISSUE THREAD

**Issue by kacystocks** [bevyengine/bevy#2715]
## Bevy version = 0.5

Release = 62e4e59

## Operating system & version

Windows 10 Build 21390.co_release.210521-1658

## What you did

```rust
use bevy::prelude::*;

struct Person;
struct Name(String);

fn main() {
   App::build()
		// adds system to the app's schedule
		.add_system(add_people.system())
		.add_system(hello_world_system.system())
		.add_system(greet_people.system())
		.run();
}

fn hello_world_system() {
   println!("hello world");
}

fn add_people(mut commands: Commands) {
	commands.spawn().insert(Person).insert(Name("Elaina Proctor".to_string()));
	commands.spawn().insert(Person).insert(Name("Renzo Hume".to_string()));
	commands.spawn().insert(Person).insert(Name("Zayna Nieves".to_string()));
	println!("huh?");
}

fn greet_people(query: Query<&Name, With<Person>>) {
    for name in query.iter() {
        println!("hello {}!", name.0);
    }
}
```

## What you expected to happen

Print to screen:
> hello world
> huh?
> hello Elaina Proctor
> hello Renzo Hume
> hello Zayna Nieves

But not necessarily in that order.

## What actually happened

Print to screen:
> hello world
> huh?

## Additional information

I noticed changing the name of 'hello_world_system' to 'hello_world' produced the expected outcome.

Any additional information you would like to add such as screenshots, logs, etc.

**Comment by alice-i-cecile** [comment]
I suspect this is actually a "non-deterministic system ordering" issue.

By default, the order that systems in Bevy run in is unspecfied: each time Bevy is run the order may differ. Try running both versions of the code several times: you should see both behaviors periodically.

To fix this, you want:

```rust
fn main() {
   App::build()
		// adds system to the app's schedule
		.add_system(add_people.system().label("add_people"))
		.add_system(hello_world_system.system())
		.add_system(greet_people.system().after("add_people"))
		.run();
}
```

which will ensure that `greet_people` always runs after `add_people`.

**Comment by kacystocks** [comment]
Ah, I also noticed- if I change the first add_system to an add_startup_system, it works as intended. My bad. Sowry.
