### ISSUE TITLE
collide_aabb is completely broken

### ISSUE THREAD

**Issue by rukai** [bevyengine/bevy#2720]
## Bevy version

v0.5

## What you did

the provided AABB is broken.
https://docs.rs/bevy/0.5.0/bevy/sprite/collide_aabb/fn.collide.html

Consider this example which should clearly collide but returns None.
```
println!("{:?}", collide_aabb::collide(Vec3::new(160.0, 275.0, 0.0), Vec2::new(80.0, 50.0), Vec3::new(232.0, 294.0, 0.0), Vec2::new(20.0, 20.0)));
```

Here is an example app which you can use to help diagnose the problem.
https://github.com/rukai/bevy_collision_bug_demo/blob/main/src/main.rs

**Comment by alice-i-cecile** [comment]
Yep, looks like Bevy's bug. This should have proper tests and be rewritten, even if it's not being used for anything serious yet.

**Comment by rukai** [comment]
Ah!
Looking at the code I sudenly realized the implementation is correct.
The real problem is that the expected format of the args is not documented and I expected them to be in the traditional AABB format.

**Comment by alice-i-cecile** [comment]
Ah, that makes sense :) Taking a look at https://github.com/bevyengine/bevy/blob/b724a0f586e6186f2a6ce4eb7903be0e340649e9/crates/bevy_sprite/src/collide_aabb.rs, it looks like we need a) quick docs b) some basic tests.

Not super urgent, but still worth doing as a nice first issue for whoever wants it :)
