### ISSUE TITLE
Add .with_system_set method to SystemSet

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2722]
## What problem does this solve or what need does it fill?

Reusing system sets is currently challenging: users may for example want to run a collection of systems in several states at once.

## What solution would you like?

Add `with_system_set` to match [`with_system`](https://docs.rs/bevy/0.5.0/bevy/prelude/struct.SystemSet.html#method.with_system) on the `SystemSet` struct.

## What alternative(s) have you considered?

More completely overhaul / reorganize system sets and scheduling.

## Additional context

This should be relatively straightforward for newcomers who want to get to know the ECS a bit better. Follow the impl here:
https://github.com/bevyengine/bevy/blob/c893b992240fc058fd118c8247c70233931ec759/crates/bevy_ecs/src/schedule/system_set.rs#L94

and push the systems from the new system set into `self`'s corresponding field instead.

**Comment by Zengor** [comment]
Hi, looking into this. Two questions:
- What should be done when both system sets have run criteria? Prioritize `self`'s?
- Should the other system set be consumed? Or taken as a reference + cloning its members? If the idea is to make reuse easier I guess the later is preferable but I'm not sure if this implicit cloning would be a problem.

**Comment by alice-i-cecile** [comment]
> What should be done when both system sets have run criteria? Prioritize self's?

Hmm. Prioritize self IMO? That will need to be clearly documented though.

> Should the other system set be consumed? Or taken as a reference + cloning its members? If the idea is to make reuse easier I guess the later is preferable but I'm not sure if this implicit cloning would be a problem. (actually it doesn't seem like SystemDescriptor even implements Clone)

I don't mind implicit cloning here: this should be a one-time cost. IMO we should try to `impl Clone for SystemDescriptor` in this PR and then use that. I could see it being useful elsewhere as well for similar reuse patterns.

**Comment by Zengor** [comment]
wrt implementing `Clone`, I ran into the issue that `BoxedSystem` and `Box<dyn ExclusiveSystem>` are not clonable and I'm not quite sure how to work around that (the systems themselves are functions using the function traits so I don't think they are clonable at all). Maybe there is some workaround that could be done with an `Arc` but I'm not sure where to go from here.

**Comment by alice-i-cecile** [comment]
Hmm. I think we should table this for the moment then; we can review it as the schedule and state story improves.

**Comment by james7132** [comment]
SystemSets, as used prior to stageless, no longer exists. Closing this issue for now.
