### ISSUE TITLE
Per entity texture modifications 

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#2734]
## What problem does this solve or what need does it fill?

Currently, there's no easy way to set the opacity of one entity's sprite.

## What alternative(s) have you considered?

Modifying the texture directly would modify it for all entities sharing that texture.

**Comment by VVishion** [comment]
Possibly related to #64?
Sorry, if drawing this relation by this comment is unnecessary or they are unrelated.

**Comment by mockersf** [comment]
Entities that share the same handle for a component will all link to the same data underneath, that's the point of handles...

It could be a nice addition to be able to duplicate an handle and get a new handle pointing to the cloned data.

**Comment by cart** [comment]
Specifically for sprites we have been discussing removing materials and just directly exposing "color" and "texture handle" on the sprite type. Not quite sure what we'll land on yet, but I do agree that in the case of sprites, the material abstraction might not be worth it. Currently the new `pipelined-rendering` branch doesn't use materials for sprites, but I haven't made up my mind yet :)
Curious to hear what everyone else thinks. Godot does "both". Every sprite has a local "color modulation"  and "texture handle" value. They can also optionally define "canvas item materials", which can define the color.

**Comment by nickfla1** [comment]
I think that the ability to individually set the color or, at least, the alpha component of a sprite without continuously creating new handles would be a really nice addition!

**Comment by rparrett** [comment]
Sprites can now be tinted!

<https://github.com/bevyengine/bevy/blob/latest/examples/2d/transparency_2d.rs>
