### ISSUE TITLE
Lack of ability to inspect mutable queries via &self receiver in 0.6 breaks Rapier integration

### ISSUE THREAD

**Issue by pcwalton** [bevyengine/bevy#2744]
## Bevy version

0.6 prerelease, f6b42b86691bdea92613df3e1e754dbc9455dbc2

## Details

The Rapier physics library abstracts over scene graphs with traits called ComponentSet and ComponentSetMut, where ComponentSetMut requires that ComponentSet be implemented. ComponentSet allows immutable lookup of physics-related properties with a `fn get(&self, ...) -> Option<&T>`, while ComponentSetMut allows mutation of those properties with `fn set(&mut self, ...)`. The `bevy_rapier` crate targeting Bevy 0.5 implements this trait on a QuerySet that performs immutable and mutable versions of the query, and takes advantage of the fact that `fn q0(&self)` and `fn q0_mut(&mut self)` are separate methods. But in Bevy 0.6 as of #2605, the `fn q0(&self)` method has been removed in favor of the mutable version. This means that it's not possible to safely simultaneously implement ComponentSet and ComponentSetMut anymore on a query.

The best safe workaround I can think of is to copy all the physics-related data for every entity out to a temporary collection every frame and then copy it back in after the physics code has run. This is obviously not shippable :) Even the Bevy 0.5 workaround isn't great, because it performs the query twice.

It'd be very nice if temporary immutable access to mutable queries were possible, by borrowing the mutable query. I'm not familiar enough with all the lifetimes involved to be able to propose a concrete API here, though.

**Comment by alice-i-cecile** [comment]
@cart I'd prefer not to break a major plugin with the launch. Should we add this to the 0.6 milestone?

**Comment by alice-i-cecile** [comment]
#2305 tackles a related issue; perhaps there's techniques we can share?

**Comment by pcwalton** [comment]
> #2305 tackles a related issue; perhaps there's techniques we can share?

Oh, interesting. Would it be helpful to see if I can successfully port Rapier on top of that PR?

**Comment by alice-i-cecile** [comment]
> Oh, interesting. Would it be helpful to see if I can successfully port Rapier on top of that PR?

Yes! I would start by resolving the merge conflicts and submitting them as a PR to @guvante's branch.

In general, Bevy needs to be able to convert mutable accesses into immutable ones. The reverse is obviously illegal, but the weakening of access restrictions should always be allowed.

There's a number of places where this comes to mind: queries, query iteration, resource access and entity access to start. It's probably not correct to handle them all in one PR, but the broader context is helpful to bear in mind as you investigate to see if you can identify common techniques or a unified API.

**Comment by pcwalton** [comment]
> Yes! I would start by resolving the merge conflicts and submitting them as a PR to @Guvante's branch.

Done: https://github.com/Guvante/bevy/pull/1 Though it's probably easier for @Guvante to just do this via a rebase, since it was trivial.

I'm happy to report that `bevy_rapier` works with #2305. I've submitted the changes needed as a PR: https://github.com/dimforge/bevy_rapier/pull/98.

**Comment by cart** [comment]
Brilliant. Glad to hear that the new apis compose so well. I agree that this is something that should be included in the 0.6 release, so I just added #2305 to the 0.6 milestone.

**Comment by NiklasEi** [comment]
Can this issue be closed now that #2305 is merged?
