### ISSUE TITLE
Question about Audio<P=AudioSource>

### ISSUE THREAD

**Issue by harrypunk** [bevyengine/bevy#2764]
## Associate type P of Audio
I was looking into how to customize audio playing and I found the struct Audio.
```rust
/// The external struct used to play audio
pub struct Audio<P = AudioSource>
where
    P: Asset + Decodable,
{
    pub queue: RwLock<VecDeque<Handle<P>>>,
}
```
I don't quite understand what is the point of ```P=AudioSource``` because there is a where bound; and Audio is not a trait, so it can't have an associate type. As far as I know, rust compiler ignores ```P=AudioSource``` as long as ```Asset + Decodable``` is satisfied.
Does it mean I have to use ```struct AudioSource``` to create a new instance of ```Audio```?

**Comment by bjorn3** [comment]
The `= AudioSource` indicates a default value of `P`. If you write `Audio` as type it will use `Audio<AudioSource>` due to this. You can still override it using for example `Audio<MyAudioAource>` for as long as `MyAudioSource` implements `Asset` and `Decodable`.
