### ISSUE TITLE
Convert exclusive systems in Bevy to ordinary systems wherever possible

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2767]
I recently noticed that several exclusive systems in Bevy no longer need to be exclusive systems: `change_window` and `play_queued_audio_system` were the two I initially noticed. These were originally exclusive systems due to an inability to use `NonSend` resources in parallelizable systems: this limitation has since been removed.

These and any other similar cases should be converted to ordinary parallel systems (in the same stage) to improve the performance of Bevy's apps by reducing unnecessary blocking, and better communicate intent (we really don't need access to *everything* in the world).

[bevy_mod_debug_dump](https://lib.rs/crates/bevy_mod_debugdump) may be able to assist you in grabbing a list of all of the systems to inspect. Or just search for uses of `.exclusive_system` in the code base using your IDE of choice.

**Comment by cart** [comment]
Good call!

**Comment by devil-ira** [comment]
There are no instances of `.exclusive_system()` anymore since its no longer required, and I couldn't find any systems that accessed `&mut World` or used `at_end`/`at_start` without needing it.
This can probably be closed :)
