### ISSUE TITLE
Access Diagnostic::history field

### ISSUE THREAD

**Issue by bytebuddha** [bevyengine/bevy#2771]
## What problem does this solve or what need does it fill?

I would like to access the history data of a diagnostic for drawing a graph using egui.

## What solution would you like?

The history field should be made public. Or a function to access the underlying history data.

## What alternative(s) have you considered?

Currently I'm storing the Diagnostic value in separate resource but this would be unnecessary if i could access the history stored with the diagnostic.

**Comment by alice-i-cecile** [comment]
@cart, can we get a `A - Diagnostics` label?

**Comment by alice-i-cecile** [comment]
Taking a look at https://github.com/bevyengine/bevy/blob/main/crates/bevy_diagnostic/src/diagnostic.rs, I think this would be very reasonable to expose in a read-only fashion. I'd be reluctant to make the field fully `pub`; this doesn't feel like something end users should be manually editing.

@bytebuddha if you'd like to make a PR for this, I'd be happy to review it.

**Comment by bytebuddha** [comment]
Thank you for your quick response @alice-i-cecile

**Comment by cart** [comment]
Displaying graphs of diagnostics was one of my primary motivators for building the diagnostics crate. We just haven't gotten around to actually doing it yet / exposing the relevant data. I agree that this should be a proper "function" API and not just making the field public.

@alice-i-cecile I just added the A-Diagnostics label.
