### ISSUE TITLE
Incorrect doc syntax on World get and get_mut

### ISSUE THREAD

**Issue by afonsolage** [bevyengine/bevy#2787]
## How can Bevy's documentation be improved?

Just noticed that `World.get` and `World.get_mut` docs are missing the closing ```

https://github.com/bevyengine/bevy/blob/e3170586776b165f40e446780fc4f9a4ed04187d/crates/bevy_ecs/src/world/mod.rs#L372-L386

https://github.com/bevyengine/bevy/blob/e3170586776b165f40e446780fc4f9a4ed04187d/crates/bevy_ecs/src/world/mod.rs#L393-L407

**Comment by alice-i-cecile** [comment]
If you're tackling this, make sure to check for conflicts with #2365.

**Comment by afonsolage** [comment]
Checked and seems to have no conflict, but if no ones picks it until the weekend, I may address it.
