### ISSUE TITLE
Add a way to test systems that requires Assets<T> component

### ISSUE THREAD

**Issue by afonsolage** [bevyengine/bevy#2788]
## What problem does this solve or what need does it fill?

When creating unity tests to systems that requires `Assets<T>` it's not possible to insert `Assets<T>` resources on world, since `Assets<T>::new()` and `AssetServer::register_asset_type<T>()` are private (`pub(crate)`).

## What solution would you like?

Add a way to insert or mock `Assets<T>` resources when testing systems.

## What alternative(s) have you considered?

I've tried to create my own `AssetServer` but even so I can't call `register_asset_type` since it's internal to `bevy_ecs` crate.

**Comment by kroltan** [comment]
As far as I understand, you are supposed to call [`App#add_asset<T>`](https://docs.rs/bevy/0.5.0/bevy/app/struct.AppBuilder.html#method.add_asset).

This will register the type and insert the `Assets<T>` resource into the world.

**Comment by afonsolage** [comment]
> As far as I understand, you are supposed to call [`App#add_asset<T>`](https://docs.rs/bevy/0.5.0/bevy/app/struct.AppBuilder.html#method.add_asset).
> 
> This will register the type and insert the `Assets<T>` resource into the world.

Yes, but I would have to use `App` to run tests (with `CorePlugin` and `AssetPlugin`), which will add many entities and stages just for the default bootstrap. When testing, you need the minimum viable setup to just test your code.

It's already very verbose to test a single system, if we would have to relay on `App` to test every system, that would be unreliable.

here is an example of setup for testing a simple system, that just takes a `ResMut`, `EventReader` and `EventWriter`

```rust
        // Arrange
        let mut events = Events::<CmdChunkAdd>::default();
        events.send(CmdChunkAdd((1, 2, 3).into(), vec![]));

        let mut world = prelude::World::default();
        world.insert_resource(storage::VoxWorld::default());
        world.insert_resource(events);
        world.insert_resource(Events::<EvtChunkAdded>::default());

        let mut stage = SystemStage::parallel();
        stage.add_system(super::process_add_chunks_system);

        // Act
        stage.run(&mut world);
        
        // Do the asserts.
```
