### ISSUE TITLE
Docstrings for enum `bevy_app::CoreStage` are not consistent

### ISSUE THREAD

**Issue by alterae** [bevyengine/bevy#2806]
## How can Bevy's documentation be improved?

All the other docstrings for [the variants](https://docs.rs/bevy_app/0.5.0/bevy_app/enum.CoreStage.html#variants) use the phrasing "Name of app stage X", while the docstring for `CoreStage::Startup` simply describes the stage.

While I personally am not a fan of the "Name of app stage" phrasing, if it is being used it should be used consistently.

Phrasing of either the `Startup` docstring or the other docstrings should be adjusted to match.  Probably `Startup` should be changed in order to match both the other variants of `CoreStage` and the docstrings for `StartupStage`.

### Relevant source code

https://github.com/bevyengine/bevy/blob/51a5070cd2d3d7262616b2efc8a6cd3b1991d7e6/crates/bevy_app/src/lib.rs#L23-L39

**Comment by Alterae** [comment]
I did not realize this while I was writing this issue but PR #2434 renders this issue meaningless by removing the enum variant in question.
