### ISSUE TITLE
CONTRIBUTING.md access restricted Triage Team link

### ISSUE THREAD

**Issue by VVishion** [bevyengine/bevy#2810]
## How can Bevy's documentation be improved?

Make the link to Triage Team (https://github.com/orgs/bevyengine/teams/triage-team) accessable.

**Comment by VVishion** [comment]
Another option would be to cut the link, but I dont know about that.

**Comment by alice-i-cecile** [comment]
@cart, I think you're the only one with the power to maybe-fix this.

**Comment by cart** [comment]
Sadly the most visible I can make this is "visible to organization members" (and it already is):
![image](https://user-images.githubusercontent.com/2694663/133553394-736ffca3-e62c-481d-ae8f-8bd45bad5da3.png)

Those interested in joining the triage team will need to join the Bevy org first, so at the very least those people aren't blocked.

**Comment by VVishion** [comment]
CONTRIBUTING.md is mostly read by new people wanting to know how to contribute. I don't know whether this is enough to cut the link, but it is a dead link for almost everyone. Additionally, I doubt that Org members try to figure out how to contribute.

In the end a dead link doesn't matter. Closing this for now.
