### ISSUE TITLE
Unable to use bevy after wgpu was updated to 0.8

### ISSUE THREAD

**Issue by nobbele** [bevyengine/bevy#2812]
## Bevy version

b399a374cb407ac94aaeb6755c06b9a3a559ec6a compiles
afaf4ad3daa01a2be529c19fc183ae8ddd2a330f doesn't compile

## Operating system & version

Windows 10

## What you did

cargo new <project_name>
add 
```toml
bevy = { git = "https://github.com/bevyengine/bevy", rev = "afaf4ad3daa01a2be529c19fc183ae8ddd2a330f" }
```
to Cargo.toml

## Additional information

```
PS C:\Projects\<project_name>> cargo run
    Updating git repository `https://github.com/bevyengine/bevy`
    Updating crates.io index
error: failed to select a version for `web-sys`.
    ... required by package `wgpu v0.8.0`
    ... which is depended on by `bevy_wgpu v0.5.0 (https://github.com/bevyengine/bevy?rev=afaf4ad3daa01a2be529c19fc183ae8ddd2a330f#afaf4ad3)`
    ... which is depended on by `bevy_internal v0.5.0 (https://github.com/bevyengine/bevy?rev=afaf4ad3daa01a2be529c19fc183ae8ddd2a330f#afaf4ad3)`
    ... which is depended on by `bevy v0.5.0 (https://github.com/bevyengine/bevy?rev=afaf4ad3daa01a2be529c19fc183ae8ddd2a330f#afaf4ad3)`
    ... which is depended on by `<project_name> v0.1.0 (C:\Projects\<project_name>)`

all possible versions conflict with previously selected packages.

  previously selected package `web-sys v0.3.46`
    ... which is depended on by `bevy_app v0.5.0 (https://github.com/bevyengine/bevy?rev=afaf4ad3daa01a2be529c19fc183ae8ddd2a330f#afaf4ad3)`
    ... which is depended on by `bevy_asset v0.5.0 (https://github.com/bevyengine/bevy?rev=afaf4ad3daa01a2be529c19fc183ae8ddd2a330f#afaf4ad3)`
    ... which is depended on by `bevy_audio v0.5.0 (https://github.com/bevyengine/bevy?rev=afaf4ad3daa01a2be529c19fc183ae8ddd2a330f#afaf4ad3)`
    ... which is depended on by `bevy_internal v0.5.0 (https://github.com/bevyengine/bevy?rev=afaf4ad3daa01a2be529c19fc183ae8ddd2a330f#afaf4ad3)`
    ... which is depended on by `bevy v0.5.0 (https://github.com/bevyengine/bevy?rev=afaf4ad3daa01a2be529c19fc183ae8ddd2a330f#afaf4ad3)`
    ... which is depended on by `<project_name> v0.1.0 (C:\Projects\<project_name>)`

failed to select a version for `web-sys` which could resolve this conflict```

**Comment by bjorn3** [comment]
Wgpu 0.8 pins web-sys to 0.3.50. I don't know where the requirement for a different version comes from though. In any case pinning dependencies often causes errors like this. IMHO cargo shouldn't have allowed dependencies to pin their own dependencies.

**Comment by afonsolage** [comment]
Don't know if is the same issue, but I got a similar issue when switching between commits on bevy main. The fix was to do a `cargo clean` and remove the `Cargo.lock`. After building everything from scratch, it worked.

**Comment by james7132** [comment]
With the release of Bevy 0.6, which depends on wgpu 0.12, is this still an issue @nobbele? If so, can you close this issue?

**Comment by jmonasterio** [comment]
I still get a similar problem:

Updating crates.io index
error: failed to select a version for `web-sys`.
    ... required by package `wgpu v0.12.0`
    ... which satisfies dependency `wgpu = "^0.12.0"` of package `bevy_render v0.6.0`
    ... which satisfies dependency `bevy_render = "^0.6.0"` of package `bevy_core_pipeline v0.6.0`
    ... which satisfies dependency `bevy_core_pipeline = "^0.6.0"` of package `bevy_internal v0.6.0`
    ... which satisfies dependency `bevy_internal = "^0.6.0"` of package `bevy v0.6.0`
    ... which satisfies dependency `bevy = "^0.6.0"` of package `ast4 v0.1.0 (C:\Users\jmonasterio\rust\ast4)`       
versions that meet the requirements `^0.3.53` are: 0.3.55, 0.3.54, 0.3.53

all possible versions conflict with previously selected packages.

  previously selected package `web-sys v0.3.39`
    ... which satisfies dependency `web-sys = "^0.3.39"` of package `wgpu v0.6.0`
    ... which satisfies dependency `wgpu = "^0.6"` of package `bevy_wgpu v0.2.1`
    ... which satisfies dependency `bevy_wgpu = "^0.2.1"` of package `bevy v0.2.1`
    ... which satisfies dependency `bevy = "^0.2.1"` of package `physme v0.2.4`
    ... which satisfies dependency `physme = "^0.2.4"` of package `ast4 v0.1.0 (C:\Users\jmonasterio\rust\ast4)`

**Comment by NiklasEi** [comment]
@jmonasterio It looks like you have Bevy 0.6 and Bevy 0.2.1 in your dependency tree. Looks like `physme`/`ast4` need to update to Bevy 0.6.

**Comment by cart** [comment]
Closing this as it appears to be resolved. Feel free to continue discussing if you think otherwise.
