### ISSUE TITLE
Can't do nested mutation queries. Any alternative?

### ISSUE THREAD

**Issue by themaxhero** [bevyengine/bevy#2820]
## Bevy version
`0.5`
## What you did
Here are the custom types:
```rust
/* Physics and Collision */

struct StaticBody;
struct DynamicBody;

struct RectCollider {
    position: Vec2,
    size: Vec2,
}

struct Speed {
    value: Vec3,
}

struct Direction {
    value: Vec3,
}

struct CircleCollider {
    radius: f32,
    position: Vec3,
}

/* Game Specifics */

#[derive(Clone, Copy)]
enum BlockType {
    White,
    Orange,
    Cyan,
    Green,
    Red,
    Blue,
    Magenta,
    Yellow,
    Silver(i8, u16), // Silver(Lives,  Score for Destroying)
    Gold,
}
struct PlayerScore(u16);
struct Player;
struct ScoreCounter;
struct Ball(bool); // bool = isLocked to the player?
#[derive(Clone, Copy)]
struct Block(BlockType, bool); // bool = destroyed
```
Here is my system.
```rust
fn block_ball_collision(
    mut blocks: Query<(&mut Block, &Transform)>,
    mut balls: Query<(
        &Ball,
        &mut Transform,
        &mut Speed,
        &mut Direction,
        &CircleCollider,
    )>,
) {
    for (mut block, block_tf) in blocks.iter_mut() {
        for (_ball, mut ball_transform, mut ball_speed, mut ball_direction, ball_collider) in
            balls.iter_mut()
        {
            let ball_potential_position =
                ball_transform.translation + (ball_speed.value * ball_direction.value);
            let clamped: Vec3 = collided(&block_tf, ball_potential_position.clone());
            let did_collide = clamped.length() <= ball_collider.radius;
            match (did_collide, &*block) {
                (false, _) => {}
                (true, Block(BlockType::Silver(0, score_adding), false)) => {
                    *block = Block(BlockType::Silver(0, *score_adding), true);
                }
                (true, Block(BlockType::Silver(lives, score_adding), _)) => {
                    *block = Block(BlockType::Silver(lives - 1, *score_adding), false);
                }
                (true, Block(block_type, _)) => *block = Block(*block_type, true),
            };
            if did_collide {
                let normalized_reverse_clamped = clamped.normalize() * -1.;
                ball_transform.translation = ball_transform.translation
                    + (normalized_reverse_clamped * (ball_collider.radius - clamped.length()));
                ball_speed.value = ball_speed.value * BALL_SPEED_MULTIPLIER;
                ball_direction.value = normalized_reverse_clamped;
            };
        }
    }
}
```
## What you expected to happen
The query to find the balls occurs inside the query to find the blocks.

## What actually happened 
![image](https://user-images.githubusercontent.com/4708337/133103804-780139a3-d063-4679-ba1a-4cc2663bd34b.png)

**Comment by bjorn3** [comment]
You will have to use `QuerySet` as suggested by the panic message.

**Comment by themaxhero** [comment]
@bjorn3 When i use a QuerySet I can't call both queries nested. I would get an error due to using query_set twice.

**Comment by MinerSebas** [comment]
Is it valid that a Entity could have a `Ball` **and** `Block` component at the same time?

IF its not, you can rewrite your function signature like this, to create a disjoint querys:

```rs
fn block_ball_collision(
    mut blocks: Query<(&mut Block, &Transform), Without<Ball>>,
    mut balls: Query<
        (
            &Ball,
            &mut Transform,
            &mut Speed,
            &mut Direction,
            &CircleCollider,
        ),
        Without<Block>,
    >,
) {
```

**Comment by themaxhero** [comment]
> Is it valid that a Entity could have a `Ball` **and** `Block` component at the same time?
> 
> IF its not, you can rewrite your function signature like this, to create a disjoint/non-overlapping queries:
> 
> ```rust
> fn block_ball_collision(
>     mut blocks: Query<(&mut Block, &Transform), Without<Ball>>,
>     mut balls: Query<
>         (
>             &Ball,
>             &mut Transform,
>             &mut Speed,
>             &mut Direction,
>             &CircleCollider,
>         ),
>         Without<Block>,
>     >,
> ) {
> ```

So, Yes. It's not valid to the same entity have both `Ball` and `Block`
But this approach did not work as well :(

![image](https://user-images.githubusercontent.com/4708337/133106534-423107bb-14c9-401f-909b-7f6c31b50d27.png)

**Comment by MinerSebas** [comment]
The new panic message is now about a different system: `arkanoid_rs::player_ball_collision`

**Comment by themaxhero** [comment]
Oh, I'm sorry.

**Comment by MinerSebas** [comment]
There is also another Solution if both QuerySet and simple `Without` don't work.

```rs
fn block_ball_collision(
	mut transforms: Query<&mut Transform>,
    mut blocks: Query<(Entity, &mut Block), (With<Transform>, Without<Ball>)>,
    mut balls: Query<
        (
			Entity,
            &Ball,
            &mut Speed,
            &mut Direction,
            &CircleCollider,
        ),
        (With<Transform>, Without<Block>),
    >,
) {
```

And then inside the system you can call `.get()` or `.get_mut()`on `transform` with the Entity you got from `blocks` or `balls`.

**Comment by alice-i-cecile** [comment]
Great work <3 I'm going to mark this as closed since we've resolved the issue. Hopefully we can continue to improve docs and examples to teach new users this pattern better.
