### ISSUE TITLE
Placing an imagebundle with transparent pixels over a node bundle cuts through the node bundle

### ISSUE THREAD

**Issue by Sheepyhead** [bevyengine/bevy#2822]
## Bevy version
Main as of time of writing, commit hash b91541b6efff2236f6aefca0f2baa09aba54f505

## Operating system & version

Windows 10

## What you did

I spawned an ImageBundle with an image that contains transparent pixels, then spawned a visible nodebundle 

## What you expected to happen

I expected the transparent pixels to reveal the underlying nodebundle

## What actually happened

The transparent pixels revealed the background instead

## Additional information

Minimal recreation [here](https://github.com/Sheepyhead/bevy_test), press any key on the keyboard to spawn the nodebundle and notice how the image cuts through it to the pink background

**Comment by rparrett** [comment]
As far as I can tell, this was fixed in Bevy 0.6ish and definitely doesn't seem to be an issue in 0.11.
