### ISSUE TITLE
bevy::utils::HashMap API is a bit unexpected compared to std::collections::HashMap

### ISSUE THREAD

**Issue by pcone** [bevyengine/bevy#2823]
## Bevy version

b91541b6efff2236f6aefca0f2baa09aba54f505

## Operating system & version

Win10/Debian, nightly rust

## What you did
I spent a while trying to initialize a bevy::utils::HashMap, expecting it to be similar to the std lib one, but there is no new function, and the signature of from takes another HashMap, instead of letting you initialize from an array of (key, value) like in std::utils. The latter is really useful for inline initialization of known data into a HashMap.

## What you expected to happen
I only had the 0.5 docs to go off and those made me think ::new and ::from worked the same way here (they just link to the std::utils::HashMap docs). This probably needs some specific documentation if it's changed intentionally. I think keeping the same ::from() behaviour as std::utils should be considered too as it's rather useful when creating HashMaps from already known data.

## What actually happened
N/A

**Comment by bjorn3** [comment]
You can use `HashMap::default()` instead of `HashMap::new()`. `HashMap::new()` is only defined for the default hasher used by libstd. `HashMap::default()` works for any hasher that implements `Default`, like the ahash hasher in this case.

**Comment by pcone** [comment]
I can write docs/code examples for this if someone can drop a vague outline of what needs to be done
