### ISSUE TITLE
app.world().is_resource_added::<T>() panics instead of returning false

### ISSUE THREAD

**Issue by RustyStriker** [bevyengine/bevy#2828]
## Bevy version

0.5

## Operating system & version

Arch(tho not relevant)

## What you did

Calling `app.world().is_resource_added::<T>()` on a resource that wasn't added.

## What you expected to happen

function to return false

## What actually happened

It paniced

## Additional information

Crashed at this line

```
bevy_ecs/src/world/mod.rs:574:79
```

because of the `unwrap()` at the end.

**Comment by dixonwille** [comment]
https://github.com/bevyengine/bevy/blob/v0.5.0/crates/bevy_ecs/src/world/mod.rs#L574 for the original commit
https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/src/world/mod.rs#L666-#L680 for main branch. I'll look at opening a PR soon.
