### ISSUE TITLE
rustc complains about missing dependencies on debian even though they're installed

### ISSUE THREAD

**Issue by pm065** [bevyengine/bevy#2836]
Bevy: 5.0

OS: Debian GNU/Linux Bullseye (v11)

Expected: Build succeeds after following setup.

Actual: Build fails with an error message telling me that 'Package libudev was not found in the pkg-config search path'. libuvdev is installed, as are the other dependencies specified in 
https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md

This is probably an apt issue, since it should have installed the packages properly. I think I fixed an issue like this before by installing the problematic package with linuxbrew, but libudev-dev does not appear to be downloadable that way.

**Comment by nelsontkq** [comment]
Do you have libudev-dev installed as well?

**Comment by pm065** [comment]
> Why isn't libudev-dev downloadable? It should be in the debian repository. Try `apt search libudev`

I meant not via linuxbrew. I already have libudev-dev (and even libudev1) installed via apt, but it doesn't seem to be recognized, which is why I tried Linuxbrew. 

It doesn't really matter anymore since I've moved on to a slightly lower-level approach, but thanks for trying to help :)

**Comment by ning-y** [comment]
Googlers: I had this same issue where the developmental libraries were installed via apt, but cargo still complained that they were missing. In my case, I had to deactivate my conda environment. If you also have conda running, you should deactivate it too.
