### ISSUE TITLE
Running examples is confusing when they are breaking changes on `main`

### ISSUE THREAD

**Issue by gbip** [bevyengine/bevy#2837]
Hello everyone !

I just discovered bevy and while trying to play with an example I discovered that some of them can't be run on the latest version from crates.io and required some changes.

For example to run `examples/2d/contributors.rs` (from `git : bevy/main`) I had to perform the following changes :

```rust
  fn main() {
      App::new()
          .add_plugins(DefaultPlugins)
          .add_startup_system(setup)
          .add_system(velocity_system)
          .add_system(move_system)
          .add_system(collision_system)
          .add_system(select_system)
          .run();
  }
```

To 
```rust
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup.system())
        .add_system(velocity_system.system())
        .add_system(move_system.system())
        .add_system(collision_system.system())
        .add_system(select_system.system())
```

`Cargo.toml` :

```toml
[dependencies]
bevy = { version = "0.5", features = ["dynamic"] }
```

However on the `latest` branch I don't need to modify the example to run it as it is compiling correctly.

**Comment by alice-i-cecile** [comment]
Yeah, we've run into this repeatedly. We stuck this warning at the top of the examples' readme.

> ⚠️ Note: for users of releases on crates.io!
> There are often large differences and incompatible API changes between the latest crates.io release and the development version of Bevy in the git main branch!

But, as you discovered, this doesn't always work! I'm not entirely sure how we could improve the situation further :(

**Comment by DJMcNab** [comment]
Additionally, in the top level readme, our link to the examples points to the latest branch. The method given for running the examples also state to check out the latest branch.

**Comment by gbip** [comment]
Maybe this is issue will solve itself once bevy get a bit more stable ?

**Comment by alice-i-cecile** [comment]
> Maybe this is issue will solve itself once bevy get a bit more stable ?

It should improve over time, although we're a very long way off "true" stability. 

More documentation in the book and tutorials will also help beginners.

In any case, I don't think there's much actionable to be done here and this is a known challenge, so I'm going to close this out. Thanks for reporting your difficulties though, it's still a useful data point!
