### ISSUE TITLE
Breakout example doesn't limit frames, maxing all threads

### ISSUE THREAD

**Issue by Jerald** [bevyengine/bevy#284]
I have an absolutely overkill Ryzen 9 3900XT with 12c/24t. Running the breakout example turns it into a jet engine, maxing every thread. I've not dug into the examples enough to know what sort of frame limiting features exist in the default plugins, but it definitely needs to be enabled for this example, especially since it's billed as a form of "complete" example.

![image](https://user-images.githubusercontent.com/7739085/90946833-adbbbf80-e3e5-11ea-8957-7ad2104e051c.png)

**Comment by Tiagojdferreira** [comment]
@Jerald this issue seems to have been fixed:
https://github.com/bevyengine/bevy/issues/111#issuecomment-688653529
Do you still reproduce it? If not, could you close it?

**Comment by alice-i-cecile** [comment]
Closed as fixed. Reopen or file a new issue if needed <3
