### ISSUE TITLE
Panics when window is minimized in Windows 10

### ISSUE THREAD

**Issue by molor824** [bevyengine/bevy#2866]
## Bevy version

v0.5.0

## Operating system & version

Windows 10

## What you did

Tried to minimize window

## What you expected to happen

Minimizes window

## What actually happened

Paniced
```
thread 'main' panicked at 'Handling wgpu errors as fatal by default'
Sep 25 20:06:36.098 ERROR gpu_descriptor::allocator: `DescriptorAllocator` is dropped while some descriptor sets were not deallocated
Sep 25 20:06:36.133 ERROR gpu_alloc::block: Memory block wasn't deallocated
...
```

## Additional information

In wgpu getting started docs, function for resizing/minimizing was using if statement to check if new window size is 0 or not
```rs
    pub fn resize(&mut self, new_size: PhysicalSize<u32>) {
        if new_size.width > 0 && new_size.height > 0 {
            self.size = new_size;
            self.surface_config.width = new_size.width;
            self.surface_config.height = new_size.height;

            self.surface.configure(&self.device, &self.surface_config);
        }
    }
```
removing the if statement resulted in
```
thread 'main' panicked at 'Error in Surface::configure: Both `Surface` width and height must be non-zero. Wait to recreate the `Surface` until the window has non-zero area.
```

**Comment by DJMcNab** [comment]
Possible duplicate of #899,  #2018, #170, #1882.

Can you confirm whether this crash still occurs on the current `main` branch?

**Comment by molor824** [comment]
> 
> 
> Possible duplicate of #899, #2018, #170, #1882.
> 
> Can you confirm whether this crash still occurs on the current `main` branch?

im not sure, im using latest version from crates.io

**Comment by DJMcNab** [comment]
The easiest way to test this out with bevy main (currently at https://github.com/bevyengine/bevy/commit/d158e0893ea88b6acf523a4264f076d6e0b540c6) would be to clone the repository and run any example.

**Comment by molor824** [comment]
> 
> 
> The easiest way to test this out with bevy main (currently at [d158e08](https://github.com/bevyengine/bevy/commit/d158e0893ea88b6acf523a4264f076d6e0b540c6)) would be to clone the repository and run any example.

ah i see, the latest main branch has fixed it, im closing the issue now
