### ISSUE TITLE
Add MSRV to Cargo.toml

### ISSUE THREAD

**Issue by ohAitch** [bevyengine/bevy#288]
https://rust-lang.github.io/rfcs/2495-min-rust-version.html

I'm not sure how to _determine_ said version, but apparently `u64::MAX`(vs `std::u64::MAX`) was added sometime after 1.41.1

**Comment by alice-i-cecile** [comment]
We've discussed this elsewhere several times; the churn of updating this isn't worth it right now. For the foreseeable future, Bevy will be on "latest stable" due to our ravenous appetite for new Rust fixes and features.
