### ISSUE TITLE
Events<GamepadEventRaw> appears to be getting updated twice per world tick (gilrs)

### ISSUE THREAD

**Issue by CAD97** [bevyengine/bevy#2893]
## Bevy version

git master

## What you did

Looked at the code (I'm playing around with building a custom mini engine using bevy ECS, for learning purposes).

## What you expected to happen

`Events::update` says it should be called once per tick, to manage the double buffer correctly.

## What actually happened

`update` appears to be getting called twice per tick:

- `bevy_input` calls `add_event::<GamepadEventRaw>`
  https://github.com/bevyengine/bevy/blob/99199338ad5e3d89d767f639ef4cd7b6da52ed83/crates/bevy_input/src/lib.rs#L65
  and this registers the `Event::update_system`
  https://github.com/bevyengine/bevy/blob/99199338ad5e3d89d767f639ef4cd7b6da52ed83/crates/bevy_app/src/app.rs#L583-L589
- `bevy_gilrs`'s `gilrs_event_system` calls `event.update` on the `Events<GamepadEventRaw>`
  https://github.com/bevyengine/bevy/blob/99199338ad5e3d89d767f639ef4cd7b6da52ed83/crates/bevy_gilrs/src/gilrs_system.rs#L19-L23

## Additional information

It's possible I'm just misunderstanding what's going on here, but this seems wrong at first glance. At the very least, the `update` call in `bevy_gilrs` probably deserves a comment calling out that it's a second `update` call in the simulation tick explaining why we want to discard the double buffer in this case.

**Comment by alice-i-cecile** [comment]
Good find. These events should not be cleared twice. Removing the update from gilrs is the correct way to fix this.

Incidentally, that system looks like it no longer need to be exclusive: we should fix that in the same PR.

**Comment by CAD97** [comment]
AIUI systems that access non-send resources (like `Gilrs` is) still need to be exclusive. Or if they don't, I didn't find the correct way to request access.

**Comment by alice-i-cecile** [comment]
Nope, they'll work fine in ordinary systems :) Just use NonSend as a system parameter.
