### ISSUE TITLE
Refactor away the `bool` argument of `Timer`

### ISSUE THREAD

**Issue by Masterhigure** [bevyengine/bevy#2926]
The `bool` argument to the `Timer` constructors should be refactored away.

A function that takes in a `bool` argument almost necessarily has an internal `if`-test that can be refactored into two separate functions. And the significance of the `bool` argument is almost never self-explanatory from reading the function call. (Consider, for instance, the first time you read `Timer::from_seconds(2.0, true)` in chapter 2.5 of the [current Bevy book](https://bevyengine.org/learn/book/getting-started/resources/): The meaning of `2.0` is obvious, but what does a `true` `Timer` mean? How can a `Timer` be false?) These are code smells. In addition, the name `Timer`, at least to me, does not imply an automatic looping capability, because that's not how the timers you buy in hardware stores work (although I'm willing to concede this particular point).

Also, if someone would want to extend `Timer` in the future to include more modes, this `bool` approach is unfeasible.

I propose that `Timer` is split into two separate timer structs. For instance `Timer` and `LoopingTimer`, or `TimerOnce` and `TimerRepeating`. (I am not terribly attached to these particular names, and other suggestions are welcome.)

Other solutions (from comments below) include splitting the constructors, or swapping the `bool` for a more verbose `enum TimerMode`, both of which are self-explanatory at point of call, and also extensible should other kinds of `Timer`s be desired.

This is related to issue #1127 that wants a `Cooldown`-type timer.

**Comment by NiklasEi** [comment]
Another option would be to replace the boolean with an enum `TimerMode`. That could then also be extended with e.g. `TimerMode::Cooldown`.

**Comment by Masterhigure** [comment]
Maybe if we resolve this in one of the "no struct-splitting" ways, `Timer` and `Stopwatch` could be merged? I haven't looked too hard at the available functionalities on either to see if it would make sense.
