### ISSUE TITLE
Allow users to fetch multiple resources at once in `get_resource` APIs

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2942]
## What problem does this solve or what need does it fill?

Requesting multiple resources from the world in simple ways is more onerous and less discoverable than it should be.

`resource_scope` is a solid approach, but requires lots of complex manual boilerplate and rightward drift for something that we can just check if multiple resources are requested at once.

## What solution would you like?

Allow users to request tuples of resources from `World::get_resource` and related APIs.

For example,

```rust
let (mut pipelines.unwrap(), mut shaders.unwrap()) = world.get_resource_mut::<(Assets<PipelineDescriptor>,Assets<Shader>)>();
```

should result in a check that the two resources have compatible fetches, then grab both of the resources structured as a tuple of options, which can then be destructured.

## What alternative(s) have you considered?

Use `resource_scope` manually. This is boilerplate heavy, and less immediately clear.

Use `SystemState` to easily access arbitrary combinations of resources is less clear, and less efficient, as it constructs unneeded secondary state.

## Additional context

Initially discussed on [Discord](https://discord.com/channels/691052431525675048/896445633626538024/896445635279073330) with @TheRawMeatball.

**Comment by Adamkob12** [comment]
@alice-i-cecile is this still relevant? It seems the current PR is abandoned and I would like to take a look at this.

**Comment by alice-i-cecile** [comment]
Yep feel free.

**Comment by alice-i-cecile** [comment]
I don't currently feel that this is worth the added API surface or internal complexity.
