### ISSUE TITLE
Normals should be multiplied by the transposed inverse of the transform matrix.

### ISSUE THREAD

**Issue by HackerFoo** [bevyengine/bevy#2955]
I noticed that normals are not transformed correctly when scaled non-uniformly:

https://github.com/bevyengine/bevy/blob/f4776f2ec413bb80ff4ee51e04bb57f0a44d9983/crates/bevy_pbr/src/render_graph/pbr_pipeline/pbr.vert#L30

https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/transforming-normals

Example (a sphere stretched along one axis) with incorrect normals:
<img width="689" alt="Screen Shot 2021-10-11 at 3 23 04 PM" src="https://user-images.githubusercontent.com/1069462/136862454-4eacf0e1-aaf4-41a6-a075-fe17dedef195.png">

Corrected normals:
<img width="526" alt="Screen Shot 2021-10-11 at 3 26 59 PM" src="https://user-images.githubusercontent.com/1069462/136862663-0b4e8034-179c-4e43-a0d2-483362b9a50a.png">

I used this as a quick fix, but computing the inverse in the shader isn't a great idea:
https://github.com/HackerFoo/bevy/commit/a711633fa8f889b06434adc8d17f7b549dc61bab

The proper fix would pass the precomputed transposed inverse into the shader.

**Comment by jakobhellermann** [comment]
This is already fixed in the `pipelined-rendering` branch:
https://github.com/bevyengine/bevy/blob/43e8a156fb4739abee3060c53140f4a94cab9ae5/pipelined/bevy_pbr2/src/render/pbr.wgsl#L46-L50
https://github.com/bevyengine/bevy/blob/43e8a156fb4739abee3060c53140f4a94cab9ae5/pipelined/bevy_pbr2/src/render/mod.rs#L85

**Comment by Weibye** [comment]
@alice-i-cecile Since pipelined is merged, this can be closed right?
