### ISSUE TITLE
External components with #[derive(Component)]

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#2966]
With the introduction of an opt-in `Component` trait in #2254, external types can no longer be directly included as components.

In the standard scenario, we have 4 parties:

- Bevy
- the external crate (e.g. Rapier)
- the interface crate (e.g. bevy_rapier)
- the end user who just wants to make a game

Due to Rust's [orphan rules](https://github.com/Ixrec/rust-orphan-rules), only Bevy or the external crate can implement `Component` for arbitrary external crate structs directly. The interface crate or end user can only bypass this using a wrapper type, and using a technique known as [extension traits](http://xion.io/post/code/rust-extension-traits.html).

Users need to be able to use external types as components, in one form or another.

There are several options for this:

1. Bevy implements `Component` for external types. This is impossible, as this set is unknowable, and using overly broad blanket impls causes all of the issues that #2254 solved. 
2. The external crate implements `Component` for the relevant types, possibly hidden behind a feature flag. This is the solution used for `serde` and other ecosystem crates. This is ideal, but not always going to happen, as it is outside of the control of anyone who cares about Bevy.
3. The interface crate or end user writes a manual wrapper type around the external component. This prevents accidental conflicts between different uses of the same component, but is heavy on boilerplate and conceptual indirection.
4. The interface crate or end user writes an `ExternalComponent<T, StorageType>` struct and implements component on it. This avoids accidental conflicts and reduces boilerplate, but reduces the type safety of the API in some of the ways that #2254 solved.
5. Bevy writes an `ExternalComponent<T, StorageType>` struct and implements component on it. This avoids ecosystem fragmentation, but has most of the same problems as 4. Extending this becomes increasingly onerous as we add more configuration to component types.

Given that 1 is impossible, and 2 is not enforceable, we are left with a choice between 3-5.
The tentative consensus from the active ECS contributors is that 3 is the least bad option, with the encouragement to use `Deref` and `DerefMut` on the wrapper types until [delegation](https://github.com/rust-lang/rfcs/pull/2393) is one day (🤞🏽) added to Rust.

4 is a particularly bad solution due to the impact on type safety and difficulty extending it. 5 is less bad than 4 in some ways, as getting 4 correct is going to be frustrating for new users and its easy to screw up and make a completely unconfigurable wrapper type. However, by including an `ExternalComponent` type in Bevy itself, we are effectively endorsing that solution.

Thus we should:
- [ ] clearly document how to include external component types in the documentation for both end users and plugin authors
- [ ] investigate disabling the naive use of 4 by forbidding unconstrained generic derives of the Component trait (credit to @DJMcNab)
- [ ] investigate publishing a tool / crate to more quickly allow users to wrap types in Bevy components (and resources, as the same issues exists for `Reflect` even without a `Resource` trait), credit to @BoxyUwU

**Comment by cart** [comment]
I think reconsidering (1) is worth it, given that ecosystem compatibility wasn't a (major) part of the discussion in the RFC. I think we should weigh "ecosystem compatibility" / "everything is a component" vs the various reasons for adopting `derive(Component)`. "Impossible" seems like too drastic of a framing. It isn't too late to revert imo.

**Comment by alice-i-cecile** [comment]
> I think reconsidering (1) is worth it, given that ecosystem compatibility wasn't a (major) part of the discussion in the RFC. I think we should weigh "ecosystem compatibility" / "everything is a component" vs the various reasons for adopting derive(Component). "Impossible" seems like too drastic of a framing. It isn't too late to revert imo.

Fair enough; while I disagree with doing so, reversion is an option. The "impossible" part of 1 was specifically for implementing `Component` for specific types, rather than a blanket impl. This is impossible because the set of possible components is unbounded.

**Comment by alice-i-cecile** [comment]
There's actually a sixth option: we get negative trait bounds into `rustc` and do a blanket impl ruling out the really awful user footguns.

This is probably my personal favorite on a lot of levels, but isn't happening for a good long while, no matter how much effort the Bevy community throws at the problem :(

**Comment by mockersf** [comment]
About (1) "Bevy implements `Component` for external types"

We could setup a process where a library author can submit the components into Bevy. With an appropriate code owner file and directory structure, the author could "own" this part of the code even though its in Bevy repo

**Comment by MiniaczQ** [comment]
If it's like alice is saying, I think 1 should be excluded from options, this restraint should be put in place as early as possible, as it will be much more difficult to change later.
Out of options 3-5, I think a modified 5 would be the best, because once the rust `delegate` comes out, it will be the closest thing resembling it, hence easier to change it for users.
To prevent the issue of it being a 'standard' I propose making a crate juts for it, which main goal is to become deprecated.

**Comment by cart** [comment]
Removed from the 0.6 milestone because we have resolved to use `#[derive(Component)]`, encourage upstream Component impls where possible, and encourage DerefMut / Deref wrapper Components when upstream support isn't possible. Still plenty to do to make this all easier on people (like potentially including Deref/DerefMut derives), so we shouldn't close this yet.

**Comment by alice-i-cecile** [comment]
Closing this out. The migration seems to have gone relatively smoothly.
