### ISSUE TITLE
Swap chain independent rendering resolution

### ISSUE THREAD

**Issue by VVishion** [bevyengine/bevy#2976]
## What problem does this solve or what need does it fill?

Rendering in resolutions other than the swap chains' one.
This is needed for e.g. pixel art renderings.

## What solution would you like?

I guess the most intuitive solution is rendering to an intermediate texture and then rendering that to the screen.

## Additional context

I have taken a look at it myself. But unfortunatelly I am still massively uncertain how the renderer will evolve - iirc it is currently sync, but will get async - Will a node edge from main_pass_driver garantuee the subgraphs to be completed before the appended node? Is a node even the proper way to include this functionality?
Furthermore, rendering to a texture depends on an implementation of RenderTargets and maybe this is intended to be solved by Viewports..?

**Comment by bjorn3** [comment]
Another use would be benchmarks where you need to render at a fixed resolution independent of the display size for reproducible benchmark scores.

**Comment by nicopap** [comment]
Bevy now supports this since camera driven rendering (#4745). There is even an example: <https://github.com/bevyengine/bevy/blob/main/examples/3d/render_to_texture.rs>
