### ISSUE TITLE
Rework TextureAtlasBuilder APIs for asset loaders

### ISSUE THREAD

**Issue by B-Reif** [bevyengine/bevy#2987]
## What problem does this solve or what need does it fill?

Currently the TextureAtlasBuilder API requires the use of the Assets API, tracking its constituent textures through `Handle`s and `Assets<Texture>`. This limits atlas construction to contexts where the Assets API is available. Specifically, it would help to be able to construct an Atlas during `Asset::load` where only the `load_context` API is available.

## What solution would you like?
Expand or modify the TextureAtlasBuilder API to work with lower-level types or with a load context.

## What alternative(s) have you considered?

Currently the only options are to 
- move atlas construction into Systems, which isn't ideal for conveniently loading Asset types, or
- re-implement the TextureAtlasBuilder internals externally

**Comment by adtennant** [comment]
https://github.com/bevyengine/bevy/issues/8633 currently prevents "re-implement the TextureAtlasBuilder internals externally".
