### ISSUE TITLE
Add rust-version to the Cargo.toml files

### ISSUE THREAD

**Issue by bjorn3** [bevyengine/bevy#2998]
## What problem does this solve or what need does it fill?

This ensures that you will get an error from cargo if your rustc is too old instead of having an error from rustc when compiling a crate that needs a newer rustc version. The rustc error doesn't explain that updating rustc will fix the error.

## What solution would you like?

Add

```toml
rust-version = "1.56"
```

or whichever version of rustc we require in the `Cargo.toml` of all bevy crates.

## What alternative(s) have you considered?

Other solutions to solve and/or work around the problem presented.

## Additional context

This was stabilized in rust 1.56.0 today. https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html#cargo-rust-version

**Comment by mockersf** [comment]
We should also add a CI job with the specified Rust version

**Comment by mnmaita** [comment]
Is this one closeable? I see an update to edition 2021 but I'm not sure if the need for `rust-version` persists.

**Comment by JayPavlina** [comment]
I think `good-first-issue` tag should be removed, because according to [this comment](https://github.com/bevyengine/bevy/pull/2997#issuecomment-949004121), a CI job is also required. IMO this issue seems to be stale though, so either the description should be updated, or it should be closed.
