### ISSUE TITLE
Touch input support

### ISSUE THREAD

**Issue by jamadazi** [bevyengine/bevy#300]
We should add support for multi-touch touchscreen input.

EDIT: this should be independent of the mouse or mouse input. They are not the same.

**Comment by Waridley** [comment]
I will say I like that Godot can *optionally* emulate mouse events from touch events or vice-versa. But as long as those events are implemented well separately, it shouldn't be too hard to make an optional system that translates them.

**Comment by jamadazi** [comment]
Yeah, I agree that there should be an easy way to treat them equally for simple games that just need some "basic pointer input", but that should be a separate kind of input event. Independent first-class support for the different input devices should be the primary focus. Touch and mouse each offer unique features and it should be possible to make full use of them. 

Games designed for touchscreen in mind (important if we want bevy to become viable for mobile and web games) should be able to take full advantage of multitouch, etc. without having to deal with anything to do with the mouse. And vice versa for desktop games designed for mouse input with multiple mouse buttons, scroll wheel, etc., which might not want to work with a touchscreen.

As for the "basic pointer input", this use case is already be partly covered by the `CursorMoved` events, which can give you the position of "the cursor" regardless of what input device is used to move it. We just need to also offer a general way to detect clicks/presses at the cursor location, which can similarly be triggered regardless of the input device. An easy way to add this could be just adding another field to `CursorMoved` to indicate the pressed state. Or there could be a separate event type for "cursor presses" that is triggered when clicking with the mouse / tapping the touchscreen. I am in favour of a new event type personally, because "detecting motion" and "detecting presses" are two different use cases.

**Comment by aclysma** [comment]
We could go through all the input events that winit and SDL2 can produce and make a list of the ones that we want and decide how to abstract them. Could do the same for windowing as well.

**Comment by TheRawMeatball** [comment]
This is a concern, but there are more important blockers atm.

#86

**Comment by Waridley** [comment]
"More important", sure, but is it really a blocker?
Phones aren't the only devices that have touch screens.
Heck, even Wacom tablet support would be nice.

**Comment by jamadazi** [comment]
Yeah, touch input is not limited to mobile. My laptop and many of my friends' laptops nowadays have touchscreens and it is great when software can support touch input properly. I certainly care about it and want to develop things with touch support.

**Comment by endragor** [comment]
Regarding the Godot options for emulation of mouse from touch and vice versa. It's actually an annoying hack that does more harm than good when you want to support devices with touch input. Instead, the base UI controls (buttons) should support both Mouse and Touch events. In such case, there would be no need in translating them. And multi-touch would work seamlessly as the base controls would distinguish between finger indexes.

**Comment by CleanCut** [comment]
Relevant blog post on [Event Chaining as a Decoupling Method in Entity-Component-System](https://www.jojolepro.com/blog/2020-08-20_event_chaining/) by @jojolepro

**Comment by cart** [comment]
resolved by #696
