### ISSUE TITLE
How to get the coordinates of a mouse click?

### ISSUE THREAD

**Issue by ahfuckme** [bevyengine/bevy#301]
Hi, I've checked through the docs and the source code and I cannot seem to figure out how I would get the x & y coordinates of a mouse click. Is it currently possible to do this with bevy?

**Comment by GabLotus** [comment]
@ahfuckme 
Thanks a lot for raising these kind of issues. It's important for bevy to know where people encounter friction in their experience and it helps us prioritize work. Would you be ok with continuing that specific discussion on https://stackoverflow.com/questions/63541917/reading-the-position-of-a-mouse-click-in-bevy . We could close this current issue and raise a different one thats focused on improving the experience and creating the upcoming axis api that will make that kind of work simpler in the future.

**Comment by ahfuckme** [comment]
Works for me!
