### ISSUE TITLE
Opengl backend not recognized (Nvidia Quadro 2000) Unable to find a GPU

### ISSUE THREAD

**Issue by bekraoui** [bevyengine/bevy#3016]
## Bevy version

0.5

## Operating system & version

Manjaro Linux

## What you did

Just trying to compile the examples for instance the (3d_scene)

## What you expected to happen

a window with the 3D scene should show up.

## What actually happened

thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!', crates/bevy_wgpu/src/wgpu_renderer.rs:47:14

## Additional information

i tested also the latest bench but i get the same result

**Comment by bekraoui** [comment]
i forced using the OpenGl backend using (BackendBit::GL) in the following files (don't know if this is the right way but it seems to enable the OpengGl backend):
piplined/bevy_rendrer2/lib.rs :
`
impl Plugin for RenderPlugin {
    fn build(&self, app: &mut App) {
        let (instance, device, queue) =
            futures_lite::future::block_on(renderer::initialize_renderer(
                BackendBit::GL, //BackendBit::PRIMARY,
                &wgpu::RequestAdapterOptions {
                    power_preference: wgpu::PowerPreference::HighPerformance,
                    ..Default::default()
                },
                &wgpu::DeviceDescriptor::default(),
            ));
...
`

running the  3d_scene_pipelined gives a new error (i can't figure out how ti debug it) this is the full backtrace:

`
     Running `target/debug/examples/3d_scene_pipelined`
Nov 01 03:07:08.475  INFO gfx_backend_gl::window::egl: Client extensions: "EGL_EXT_platform_base EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_x11 EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_KHR_platform_x11 EGL_MESA_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless"    
Nov 01 03:07:08.475  INFO gfx_backend_gl::window::egl: Loading Wayland library to get the current display    
Nov 01 03:07:08.475  INFO gfx_backend_gl::window::egl: Loading X11 library to get the current display    
Nov 01 03:07:08.478  INFO gfx_backend_gl::window::egl: Using X11 platform    
Nov 01 03:07:08.488  INFO gfx_backend_gl::window::egl: Display vendor "NVIDIA", version (1, 4), extensions: "EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_output_base EGL_EXT_stream_acquire_mode EGL_IMG_context_priority EGL_KHR_config_attribs EGL_KHR_create_context_no_error EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_display_reference EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_partial_update EGL_KHR_swap_buffers_with_damage EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_reusable_sync EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_KHR_stream_cross_process_fd EGL_KHR_stream_fifo EGL_KHR_stream_producer_eglsurface EGL_KHR_surfaceless_context EGL_NV_nvrm_fence_sync EGL_NV_post_sub_buffer EGL_NV_stream_metadata EGL_NV_stream_reset EGL_NV_stream_sync EGL_NV_stream_consumer_gltexture_yuv EGL_NV_stream_attrib EGL_NV_sync EGL_NV_system_time EGL_NV_output_drm_flip_event EGL_WL_bind_wayland_display EGL_WL_wayland_eglstream"    
Nov 01 03:07:08.489  INFO gfx_backend_gl::window::egl: Trying native-render    
Nov 01 03:07:08.490  WARN gfx_backend_gl::window::egl: No config found!    
Nov 01 03:07:08.490  INFO gfx_backend_gl::window::egl: Trying presentation    
Nov 01 03:07:08.625  INFO gfx_backend_gl: Vendor: "NVIDIA Corporation"    
Nov 01 03:07:08.625  INFO gfx_backend_gl: Renderer: "Quadro 2000/PCIe/SSE2"    
Nov 01 03:07:08.625  INFO gfx_backend_gl: Version: 3.2, NVIDIA 390.144    
Nov 01 03:07:08.625  INFO gfx_backend_gl: Shading Language: 3.2    
Nov 01 03:07:08.625  INFO gfx_backend_gl: Supported Features: INDEPENDENT_BLENDING | SAMPLER_ANISOTROPY | INSTANCE_RATE | MUTABLE_COMPARISON_SAMPLER | NDC_Y_UP    
Nov 01 03:07:08.625  INFO gfx_backend_gl: Legacy Features: DRAW_INSTANCED | DRAW_INDEXED_INSTANCED | VERTEX_BASE | SRGB_COLOR | CONSTANT_BUFFER | COPY_BUFFER | SAMPLER_OBJECTS | EXPLICIT_LAYOUTS_IN_SHADER | INSTANCED_ATTRIBUTE_BINDING    
Nov 01 03:07:08.626  INFO gfx_backend_gl: Memory types: [
    (
        MemoryType {
            properties: CPU_VISIBLE | COHERENT | CPU_CACHED,
            heap_index: 1,
        },
        Buffer(
            TRANSFER_SRC | TRANSFER_DST | UNIFORM_TEXEL | STORAGE_TEXEL | UNIFORM | STORAGE | INDEX | VERTEX | INDIRECT,
        ),
    ),
    (
        MemoryType {
            properties: CPU_VISIBLE | COHERENT,
            heap_index: 1,
        },
        Buffer(
            TRANSFER_SRC | TRANSFER_DST | UNIFORM_TEXEL | STORAGE_TEXEL | UNIFORM | STORAGE | INDEX | VERTEX | INDIRECT,
        ),
    ),
    (
        MemoryType {
            properties: DEVICE_LOCAL,
            heap_index: 0,
        },
        Buffer(
            TRANSFER_SRC | TRANSFER_DST | UNIFORM_TEXEL | STORAGE_TEXEL | UNIFORM | STORAGE | INDEX | VERTEX | INDIRECT,
        ),
    ),
    (
        MemoryType {
            properties: DEVICE_LOCAL,
            heap_index: 0,
        },
        Image,
    ),
]    
Nov 01 03:07:08.626  INFO gfx_backend_gl: Debug output is enabled    
Nov 01 03:07:08.626  INFO gfx_backend_gl::device: 	Created frame buffer 1    
Nov 01 03:07:08.634  INFO gfx_backend_gl::device: 	Compiled shader 2    
Nov 01 03:07:08.635  INFO gfx_backend_gl::device: 	Compiled shader 3    
Nov 01 03:07:08.635  INFO gfx_backend_gl::device: 	Linked program 1    
Nov 01 03:07:08.680  INFO gfx_backend_gl::device: 	Compiled shader 5    
thread 'main' panicked at 'internal error: entered unreachable code', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/naga-0.5.0/src/back/glsl/mod.rs:584:22
stack backtrace:
   0:     0x5556b4af7290 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5556b4af7290 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5556b4af7290 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5556b4af7290 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5556b4b1a23f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x5556b4af4505 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x5556b4af92fb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5556b4af92fb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5556b4af92fb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x5556b4af8dcd - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x5556b4af990d - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x5556b4af9477 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:495:13
  12:     0x5556b4af772c - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5556b4af9409 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x5556b31f5481 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x5556b31f53cd - core::panicking::panic::h60569d8a39169222
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
  16:     0x5556b401185f - naga::back::glsl::Writer<W>::write_array_size::h44e62d37729c1427
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/naga-0.5.0/src/back/glsl/mod.rs:584:22
  17:     0x5556b400d9b3 - naga::back::glsl::Writer<W>::write_struct::hbb9f377e47d90427
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/naga-0.5.0/src/back/glsl/mod.rs:1152:21
  18:     0x5556b400b068 - naga::back::glsl::Writer<W>::write_type::h6685c7d16259a6db
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/naga-0.5.0/src/back/glsl/mod.rs:675:18
  19:     0x5556b400c5bf - naga::back::glsl::Writer<W>::write_global::h058f6f86acc38245
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/naga-0.5.0/src/back/glsl/mod.rs:762:9
  20:     0x5556b40160b8 - naga::back::glsl::Writer<W>::write::h5c2aa38bb162d15b
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/naga-0.5.0/src/back/glsl/mod.rs:525:21
  21:     0x5556b402d30f - gfx_backend_gl::device::Device::compile_shader_library_naga::h4d34a7c087d38335
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-gl-0.9.0/src/device.rs:617:15
  22:     0x5556b402dfac - gfx_backend_gl::device::Device::compile_shader::h40f47ba700627ddb
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-gl-0.9.0/src/device.rs:658:31
  23:     0x5556b402a523 - gfx_backend_gl::device::Device::create_shader_program::h160d2d2949f43822
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-gl-0.9.0/src/device.rs:158:30
  24:     0x5556b402fb69 - <gfx_backend_gl::device::Device as gfx_hal::device::Device<gfx_backend_gl::Backend>>::create_graphics_pipeline::h21882828295913d1
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-gl-0.9.0/src/device.rs:1018:38
  25:     0x5556b38ea291 - wgpu_core::device::Device<B>::create_render_pipeline::h92effea76f4850ba
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.9.2/src/device/mod.rs:2571:22
  26:     0x5556b3a73133 - wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_render_pipeline::hfefc7da0ce0bfb20
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.9.2/src/device/mod.rs:4220:34
  27:     0x5556b393398e - <wgpu::backend::direct::Context as wgpu::Context>::device_create_render_pipeline::hcfbdaf9078b71ffc
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.9.0/src/backend/direct.rs:1040:27
  28:     0x5556b3b09b37 - wgpu::Device::create_render_pipeline::hc5c8a08196c82140
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.9.0/src/lib.rs:1608:17
  29:     0x5556b32a92c5 - bevy_render2::renderer::render_device::RenderDevice::create_render_pipeline::hfdf06fa2abd2720b
                               at /run/media/user/2ad43a53-2f50-4f3d-801b-2a6938cc4a18/Projects/PixelCAE/experiment/opengl/bevy/pipelined/bevy_render2/src/renderer/render_device.rs:100:36
  30:     0x5556b32dc271 - <bevy_pbr2::render::PbrShaders as bevy_ecs::world::FromWorld>::from_world::hf0e6198a0197946b
                               at /run/media/user/2ad43a53-2f50-4f3d-801b-2a6938cc4a18/Projects/PixelCAE/experiment/opengl/bevy/pipelined/bevy_pbr2/src/render/mod.rs:243:24
  31:     0x5556b3249118 - bevy_app::app::App::init_resource::h8e3048f6ef955bd0
                               at /run/media/user/2ad43a53-2f50-4f3d-801b-2a6938cc4a18/Projects/PixelCAE/experiment/opengl/bevy/crates/bevy_app/src/app.rs:433:28
  32:     0x5556b32662e4 - <bevy_pbr2::PbrPlugin as bevy_app::plugin::Plugin>::build::h4b9d39c4d2dfe997
                               at /run/media/user/2ad43a53-2f50-4f3d-801b-2a6938cc4a18/Projects/PixelCAE/experiment/opengl/bevy/pipelined/bevy_pbr2/src/lib.rs:35:9
  33:     0x5556b483d754 - bevy_app::plugin_group::PluginGroupBuilder::finish::hf92e161ff21cd5f6
                               at /run/media/user/2ad43a53-2f50-4f3d-801b-2a6938cc4a18/Projects/PixelCAE/experiment/opengl/bevy/crates/bevy_app/src/plugin_group.rs:104:21
  34:     0x5556b3207d3b - bevy_app::app::App::add_plugins::hc84e55e871026965
                               at /run/media/user/2ad43a53-2f50-4f3d-801b-2a6938cc4a18/Projects/PixelCAE/experiment/opengl/bevy/crates/bevy_app/src/app.rs:522:9
  35:     0x5556b31fabcc - _3d_scene_pipelined::main::h86550980c6e13b3c
                               at /run/media/user/2ad43a53-2f50-4f3d-801b-2a6938cc4a18/Projects/PixelCAE/experiment/opengl/bevy/examples/3d/3d_scene_pipelined.rs:21:5
  36:     0x5556b320503b - core::ops::function::FnOnce::call_once::h61ee9e81b1a54e36
                               at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  37:     0x5556b320bf4e - std::sys_common::backtrace::__rust_begin_short_backtrace::h0a0d972ec57f0217
                               at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  38:     0x5556b3204e61 - std::rt::lang_start::{{closure}}::h7c9a125f7423e4d3
                               at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:49:18
  39:     0x5556b4af9d0a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  40:     0x5556b4af9d0a - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  41:     0x5556b4af9d0a - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  42:     0x5556b4af9d0a - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  43:     0x5556b4af9d0a - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  44:     0x5556b3204e40 - std::rt::lang_start::h09da89c7844bc331
                               at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:48:5
  45:     0x5556b31fecac - main
  46:     0x7f0bc1a1db25 - __libc_start_main
  47:     0x5556b31f724e - _start
  48:                0x0 - <unknown>
`

**Comment by mockersf** [comment]
closing to centralise in #3191
