### ISSUE TITLE
ERROR gpu_alloc::block: Memory block wasn't deallocated 

### ISSUE THREAD

**Issue by SaathwikDasari** [bevyengine/bevy#3020]
cargo.toml

[package]
name = "first_rust_project"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
rand = "0.8"

main.rs

#![allow(unused)]

use bevy::prelude::*;

const PLAYER_SPRITE: &str = "player_a_01.png";

fn add_people() {
    println!("Hello World");
}

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(add_people.system())
        .run();}

**Comment by Shatur** [comment]
Have the same error, but in integrations tests. Opened a separate issue with the minimal project to reproduce: #3091.

**Comment by alice-i-cecile** [comment]
Closing this out following #3091. Feel free to reopen if you can reproduce.
