### ISSUE TITLE
Low performance? 

### ISSUE THREAD

**Issue by Wandalen** [bevyengine/bevy#3027]
Hello! I like Bevy and I am thinking to start to use it, but it looks for me like a questionable move after my recent findings. 
I ran several examples and encountered that one:
```
cargo run --example alien_cake_addict
```
For me and 2 my colleagues it gives ~10fps what is insane for such a simple scene.
Why is that so? Is that possible to get 60fps? What is wrong with my logic?

## Bevy version

v0.5.0

## Operating system & version

Windows 10, Ubuntu 20, OSx. All.

## What you did

Just run the example

## What you expected to happen

60 fps

## What actually happened

10 fps

**Comment by GioPat** [comment]
I'm running on Windows 10 (10.0.19042) with a GeForce GTX 1050M and in release mode hitting ~35 FPS 🤔 
![image](https://user-images.githubusercontent.com/9217515/149468604-252306bf-d999-4547-95ec-72083e80afe5.png)

**Comment by GioPat** [comment]
I'm running the test with [this GPU](https://www.notebookcheck.net/NVIDIA-GeForce-GTX-1050-Notebook.178614.0.html) (inferred from the output of the console log).

Hitting ~18 FPS with the many_sprites test in release mode.
I tried also to run from the Godot UI (debug mode) [this test](https://github.com/cart/godot3-bunnymark) and I was able to get ~6k sprites @ 60 FPS with GLES3
Get ~6k sprites @ 60 FPS also for the bevymark example in **release**.

**Comment by Droggelbecher** [comment]
On my setup (WSL2 with a RTX 3070), I get ~250-ish FPS for an empty game, but adding a `OrthographicCameraBundle::new_2d()` (with nothing to show), reduces the FPS to ~70. Thats on bevy 0.7.0, compiling both variants in release mode.
