### ISSUE TITLE
Manually created meshes are oriented wrong on `pipelined-rendering`

### ISSUE THREAD

**Issue by sweepline** [bevyengine/bevy#3030]
## Bevy version

running on commit 9f47697e408c018ec27174308394c9376c57183d

## Operating system & version

Arch Linux

## What you did

Generate a Mesh with a single triangle, using render2 and pbr2.

A snippet can be seen here.

```rust
    vertices.push([0.0, 0.0, 0.0]);
    vertices.push([50.0, 0.0, 0.0]);
    vertices.push([0.0, 100.0, 0.0]);
    indices.push(0);
    indices.push(1);
    indices.push(2);
```

Using a camera with the following transform to look at it:
```rust
Transform::from_xyz(0.0, 30.0, 100.0).looking_at(Vec3::new(0.0, 0.0, 0.0), Vec3::Y),
```

## What you expected to happen

I expected the triangle to be perpendicular to the X,Z plane and having a face towards +Z. Like so:
![triangle_main](https://user-images.githubusercontent.com/2910395/138957154-4bec943a-e7db-4d4b-b2f9-42545bc5b075.png)

An minimal example of this can be found here: https://github.com/sweepline/bevy-mesh-bug/tree/working-main

## What actually happened

The triangle is positioned flatly on the X,Z plane facing towards +Y. Like so:
![triangle_pipelined](https://user-images.githubusercontent.com/2910395/138957392-b9b59624-52c0-459b-ae77-17d6a5e2ec58.png)

An minimal example of this can be found here: https://github.com/sweepline/bevy-mesh-bug/tree/master

**Comment by robojeb** [comment]
Just to add, it might be worth updating the documentation for Mesh to indicate which attributes need to be provided. 
I just ran into this issue and spent a whole night wondering what was up when my math printed by debug was all correct. 

It seems the minimum to be set is `ATTRIBUTE_POSITION`, `ATTRIBUTE_NORMAL` and `ATTRIBUTE_UV_0` or else you encounter problems. 

The docs on main only show setting `ATTRIBUTE_POSITION` in the example for creating a custom mesh.
