### ISSUE TITLE
Pipelined Rendering: App crashes when there is no camera

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#3043]
Crashes with the following:

```
Oct 28 16:01:38.927 ERROR present_frames: wgpu_core::present: No work has been submitted for this frame    
Oct 28 16:01:38.932 ERROR present_frames: wgpu_core::present: No work has been submitted for this frame    
thread 'main' panicked at 'Failed to acquire next swap chain texture!: Timeout', pipelined/bevy_render2/src/view/window.rs:151:24
```

We should choose one of the following behaviors:

1. Don't call "present" when there is nothing to draw for a camera
2. Run a "clear color" pass anyway. 

We should also print an error (once) when a camera is missing.

**Comment by cart** [comment]
Yup definitely feel free to pick this up. Sorry for the delay!

**Comment by Davier** [comment]
This panic also occurs for me in the pipelined_texture_atlas when compiled in debug mode (even though there is a camera). I believe it's fine in release mode because the texture is loaded in less than a few frames, so that there is something to draw.
