### ISSUE TITLE
14.3

### ISSUE THREAD

**Issue by lafi-99** [bevyengine/bevy#3047]
## Bevy version

The release number or commit hash of the version you're using.

## Operating system & version

Ex: Windows 10, Ubuntu 18.04, iOS 14.

## What you did

The steps you took to uncover this bug. Please list full reproduction steps if
feasible.

## What you expected to happen

What you think should've happened if everything was working properly.

## What actually happened

The actual result of the actions you described.

## Additional information

Any additional information you would like to add such as screenshots, logs, etc.

**Comment by cart** [comment]
Closing because this appears to be a bot
