### ISSUE TITLE
Double Precision Translations

### ISSUE THREAD

**Issue by NicoHarg** [bevyengine/bevy#3068]
## What problem does this solve or what need does it fill?

It's good for large worlds. Building games with planetary scales or bigger will benefit greatly from the reduced simplicity.

## What solution would you like?

Change the transform component to use double precision floats for the translation vector part.

## What alternative(s) have you considered?

Origin rebasing is a thing, but introduces a lot of complexity on its own.

**Comment by alice-i-cecile** [comment]
Duplicate of #1680 <3 Closing this out, but feel free to discuss further there.
