### ISSUE TITLE
Make serde serialize enum variants as snake_case

### ISSUE THREAD

**Issue by JonahPlusPlus** [bevyengine/bevy#3074]
## What problem does this solve or what need does it fill?

This is not a huge issue, but when making a TOML or JSON file that use `KeyCode`s as values, it's annoying to see CamelCase.
Compare TOML:
```
[[profile.action]]
event = "run"
digital = "LShift"
```

to
```
[[profile.action]]
event = "run"
digital = "l_shift"
```
And JSON:
```
{
  "profile": {
    "action": [
      {
        "event": "run",
        "digital": "LShift"
      }
    ]
  }
}
```
to
```
{
  "profile": {
    "action": [
      {
        "event": "run",
        "digital": "l_shift"
      }
    ]
  }
}
```
It just looks more consistent with the rest of the data.

## What solution would you like?

Just change `#[cfg_attr(feature = "serialize", derive(serde::Serialize, serde::Deserialize))]` to `#[cfg_attr(feature = "serialize", derive(serde::Serialize, serde::Deserialize), serde(rename_all = "snake_case"))]` and serde will do it automatically.

## What alternative(s) have you considered?

I could try to use a huge `match` statement with another enum that does convert fields to snake_case, but that would stupid way of doing it compared to just putting this in.

## Additional context

I can make a pull request; I just wanted to make sure that people approve of this change.

**Comment by JonahPlusPlus** [comment]
I also wouldn't just be updating `KeyCode`. I think all serializable types with CamelCase fields should get this treatment, so all enums.

**Comment by minecrawler** [comment]
Did you mean kebab-case (as in your code), or should the code actually read `l_shift`?

To be honest, especially in this case I am happy about the uppercase L, because it makes it easier to read (I easily confuse l and I, but when it's L and I then it's clear)

Also, according to the official [Rust naming conventions](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html) enums should be CamelCase, and when serializing an enum value, keeping the enum notion keeps the consistency with the guide and the code, so for me the CamelCase looks good...

**Comment by JonahPlusPlus** [comment]
Fixed that, sorry for the confusion, I was using kebab-case first, but changed it to snake_case. Guess I missed that with the example I copied at 3;30 AM... 

I think the Rust naming conventions are great for Rust, but for a data format, you don't see the names of structs, so fields often act like them, and field names are in snake_case. To make it look consistent, enum variants, which we do see, should be snake_case as well.

Here is a better example to compare (can't do it in TOML, since externally tagged enum variant structs don't work):
```
{
  "Hello":
    {
      "x" : 5
    }
}
```
to
```
{
  "hello":
    {
      "x" : 5
    }
}
```
If the enum variant (Something::Hello in this case) wasn't unit-like, it would be the key for some value, and that would be inconsistent with the rest of the document. I rest my case. ;)

**Comment by cart** [comment]
CamelCase doesn't bother me personally and it has a number of benefits:
* 1-1 parity with the rust types, making it easier for users to mentally map between configured values and the rust types 
* Default: we are consistent by default for all of our types, no need to override defaults for very serde derive
* Provides a visual distinction between "field names" and "value / type names" 
* I agree that `L` is clearer than `l`

**Comment by JonahPlusPlus** [comment]
Alright, I'll close this then. 👍
