### ISSUE TITLE
Add info about the need for `'static + Send + Sync` as a trait restraint for generic resources to the Res and ResMut docs

### ISSUE THREAD

**Issue by JonahPlusPlus** [bevyengine/bevy#3085]
## How can Bevy's documentation be improved?

Generic resources (ex: `SomeResource<T>`) require the trait constraint of `'static + Send + Sync` to run, otherwise you'll get an error like `method not found`. 

[`Res`](https://docs.rs/bevy/0.5.0/bevy/prelude/struct.Res.html) and [`ResMut`](https://docs.rs/bevy/0.5.0/bevy/ecs/prelude/struct.ResMut.html) lack this little bit of info, making debugging a pain to figure out.

Please add this bit of info to the docs.

**Comment by alice-i-cecile** [comment]
Seemingly resolved by #1962. We should verify that this fully prevents the creation of malformed resources, and then close this out.

**Comment by JonahPlusPlus** [comment]
👍
