### ISSUE TITLE
Add `Query::contains` method to check if an entity matches a query

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3089]
## What problem does this solve or what need does it fill?

Users commonly want to check if an entity is matched by a query.

## What solution would you like?

Add `Query::contains(entity) -> bool` method.

## What alternative(s) have you considered?

Use `query.get(entity).is_some()`, which does unnecessary work and is less clear.

**Comment by louisgjohnson** [comment]
Seems like a relatively easy task, I'd be happy to give it a look
