### ISSUE TITLE
Examples to demonstrate changing a sprite and texture

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3130]
## How can Bevy's documentation be improved?

Newcomers are often a bit lost when trying to learn how to idiomatically work with assets and handles.

The most common stumbling block is "how do I change a sprite once loaded?".

We should add two sibling examples, one for sprites, and one for meshes:

- show how to query for sprite / mesh handles, and change what they point to
- show how to programatically change the properties of a sprite / mesh (e.g. color, reflectance, translucency or so on)
- show how to mutate the underlying asset to e.g. add more vertexes

**Comment by richchurcher** [comment]
This looks like good learning material for me, I'll pick this up.

**Comment by alice-i-cecile** [comment]
Awesome. https://github.com/bevyengine/bevy/pull/15056 gets into the strategies a little bit, but it would be very nice to have a hands-on example or two.

**Comment by richchurcher** [comment]
This is possibly an obvious question, but do we mean an example for `Mesh2d` or `Mesh` here?

**Comment by alice-i-cecile** [comment]
Either is fine: I think `Mesh` is more common.
