### ISSUE TITLE
Add documentation for `bevy_window::window::WindowMode::Fullscreen`

### ISSUE THREAD

**Issue by alterae** [bevyengine/bevy#3136]
## How can Bevy's documentation be improved?

In the `Fullscreen` variant of the [`WindowMode`](https://docs.rs/bevy/0.5.0/bevy/window/enum.WindowMode.html) enum, the `use_size` field is undocumented, and it is not clear what it does

**Comment by DJMcNab** [comment]
The full_size field appears to be described on the very page you have linked.

It's to do with whether the full screen window should be created at the given size (e.g. automatically stretched out by the display to make the aspect ratio outputted by the OS fit - depends on how clever your monitor/OS combination wants to be) or created at whatever the screen resolution is.

**Comment by alterae** [comment]
> The full_size field appears to be described on the very page you have linked.
> 
> It's to do with whether the full screen window should be created at the given size (e.g. automatically stretched out by the display to make the aspect ratio outputted by the OS fit - depends on how clever your monitor/OS combination wants to be) or created at whatever the screen resolution is.

Ah, I see.  Thank you for pointing that out, I missed it.

I feel it would be useful for that to be documented directly on the field itself.

**Comment by DJMcNab** [comment]
Certainly, adding some documentation for that would be welcome.
