### ISSUE TITLE
Implement `ExactSizeIterator` for queries that are only filtered by With and Without

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3142]
## What problem does this solve or what need does it fill?

The `ExactSizeIterator` is useful on queries for learning the exact length of queries.

It's currently implemented for unfiltered queries, but not filtered queries.

## What solution would you like?

Separate query filters into "entity-level filters"  (`Added`, `Changed`) and "archetype-level filters" (`With`, `Without`).

Implement `ArchetypeFilter` for filter tuples that only have archetype-level filters. Do the same for `Or`.

Implement `ExactSizeIterator` for queries that only contain `ArchetypeFilter` filters.

## What alternative(s) have you considered?

Clone the query and then count it slowly :(

Use `With` and `Without` in the first `Query` type parameter and discard the bools returned 😱

## Additional context

We can't comfortably do this for all filtered queries, as the length of a query that includes `Changed` etc. is slow to compute.

Idea credit to @Davier and @TheRawMeatball. I just write the tickets!

**Comment by TheRawMeatball** [comment]
I don't think we need something like `DynamicFilter`

**Comment by mockersf** [comment]
> Separate query filters into DynamicFilter (Added, Changed) and StaticFilter (With, Without).

Rather than using global terms like dynamic and static, could we think about more specific terms?

Maybe ArchetypeFilter for static, and StatusFilter for dynamic?

**Comment by alice-i-cecile** [comment]
> Rather than using global terms like dynamic and static, could we think about more specific terms?
> Maybe ArchetypeFilter for static, and StatusFilter for dynamic?

Right, that's a valid point. `ArchetypeFilter` is very good. I think I would probably prefer `EntityFilter` over `StatusFilter`, to indicate that it's performing a O(n) filter over the retrieved entities (in contrast to over the archetypes) but I like `StatusFilter` better than `DynamicFilter` and would happily accept it.
