### ISSUE TITLE
Demonstrate how to run a schedule in `bevy_ecs` README

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3143]
## How can Bevy's documentation be improved?

Running schedules in a standalone `bevy_ecs` context is a fundamental tool when working with the library. However, it is not demonstrated in the readme.

A simple demonstration should be added.

**Comment by NiklasEi** [comment]
The ["Using Bevy ECS" example](https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/README.md#using-bevy-ecs) actually demonstrates how to build and run a schedule.

Would you like an additional example?

**Comment by alice-i-cecile** [comment]
Ah; I'd missed that! Nope, all good.
