### ISSUE TITLE
Schedule causes a panic when run criteria returns NoAndCheckAgain

### ISSUE THREAD

**Issue by vmednis** [bevyengine/bevy#3144]
## Bevy version

0.5.0, looking at the code still happens at `main` 

## Operating system & version

N/A will happen on all Operating Systems

## What you did

Had a run criteria returning `NoAndCheckAgain` in some cases on a Schedule

## What you expected to happen

I expected the run criteria to be reevaluated immediately

## What actually happened

The code panicked

## Additional information

The panic is raised in [bevy_ecs/src/schedule/mod.rs](https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/src/schedule/mod.rs#L366) with text "`NoAndCheckAgain` would loop infinitely in this situation.". I believe that this is an incorrect assumption as the state may be modified (in my case I change a resource) by the run criteria and go down a different code path on the rerun of it. This would make some code easier to read.

**Comment by alice-i-cecile** [comment]
Related to #2841.

**Comment by james7132** [comment]
With stageless merged, run conditions no longer return an enum but a single boolean. Closing as this issue is no longer actionable.
