### ISSUE TITLE
`mp3` cargo feature causes iOS apps to get rejected from app store

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#3145]
Quoting @HackerFoo from discord:

> Heads up, using the mp3 Bevy feature will cause your iOS app to get rejected because minimp3 depends on slice_deque which uses an internal API for memory allocation.

@Ixentus 
> Rodio has an extra backend "Symphonia" which can also do mp3. Should be easy to enable if you need it

Sounds like we should evaluate Symphonia as a backend.

**Comment by alice-i-cecile** [comment]
Ping @tesselode, who was also investigating Symphonia for the `kira` audio crate that the community has largely been using for audio.

**Comment by HackerFoo** [comment]
The offending symbols were: `_mach_vm_allocate`, `_mach_vm_deallocate`, and `_mach_vm_remap`.

I worked around this by converting to .ogg and replacing the `mp3` feature with `vorbis`.

**Comment by mockersf** [comment]
mp3 now use `symphonia` instead of `minimp3` and should be accepted
