### ISSUE TITLE
Split current `World::clear_entities` into separate methods for clearing entities and resources

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3157]
## What problem does this solve or what need does it fill?

[World::clear_entities](https://github.com/bevyengine/bevy/blob/f4776f2ec413bb80ff4ee51e04bb57f0a44d9983/crates/bevy_ecs/src/world/mod.rs#L1139) currently wipes out all entities and resources (please correct me if my understanding of storages is horribly flawed).

This is unintuitive, and not as useful for testing (or advanced ECS architectures) as it could be; where treating resources and entities separately is common.

## What solution would you like?

1. Keep the existing behaviour, but rename to `clear_all`.
2. Add `clear_resources`.
3. Add `clear_entities`.

**Comment by cart** [comment]
`clear_entities` does not clear resources. We use it in the pipelined renderer to only clear entities/components while leaving resources intact (and that was the purpose it was developed for).

**Comment by alice-i-cecile** [comment]
> clear_entities does not clear resources.

Awesome; I'll close this issue and open up a new one for `clear_resources`.
