### ISSUE TITLE
Add `World::clear_resources`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3158]
## What problem does this solve or what need does it fill?

`World::clear_entities` allows users to clear all entities. See
https://github.com/bevyengine/bevy/blob/f4776f2ec413bb80ff4ee51e04bb57f0a44d9983/crates/bevy_ecs/src/world/mod.rs#L1139

Clearing all resources is a natural parallel, and likely to be useful for various testing purposes.

## What solution would you like?

Add `World::clear_resources`.

Optionally, add a `clear_all` method that simply wraps `clear_entities` and `clear_resources`.

## What alternative(s) have you considered?

Awful manual iteration or type registration.

Creating a new world, moving all entities into it, then swapping them back?

## Additional context

Mechanics of `clear_entities` clarified by #3157.

**Comment by 2ne1ugly** [comment]
If we cleared all the resource components
Wouldn't it cause panics in `Res<T>` then? 🤔 Or am I missing something?
`clear_all` seems to be implementable but I'm not sure if `clear_resources` can standalone.

**Comment by alice-i-cecile** [comment]
> If we cleared all the resource components,
wouldn't it cause panics in Res<T> then? 🤔 Or am I missing something?

It will: this would be a specialized API intended for writing tests (or rather unusual multi-world architectures) :)
