### ISSUE TITLE
Cannot compile bevy_wgpu for WASM

### ISSUE THREAD

**Issue by TheButlah** [bevyengine/bevy#3162]
## Bevy version

0.5

## Operating system & version

Ubuntu 20.04 on WSL2

## What you did

Add bevy_wgpu to Cargo.toml, and compile with `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo check --target wasm32-unknown-unknown`

## What you expected to happen

It compiles

## What actually happened

```
error[E0432]: unresolved import `bevy_render::shader::glsl_to_spirv`
  --> /home/ryan/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_wgpu-0.5.0/src/renderer/wgpu_render_resource_context.rs:13:14
   |
13 |     shader::{glsl_to_spirv, Shader, ShaderError, ShaderSource},
   |              ^^^^^^^^^^^^^ no `glsl_to_spirv` in `shader`

error[E0599]: no method named `get_spirv` found for reference `&Shader` in the current scope
   --> /home/ryan/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_wgpu-0.5.0/src/renderer/wgpu_render_resource_context.rs:331:40
    |
331 |         let spirv: Cow<[u32]> = shader.get_spirv(None).unwrap().into();
    |                                        ^^^^^^^^^ method not found in `&Shader`

```

## Additional information

Any additional information you would like to add such as screenshots, logs, etc.

**Comment by bjorn3** [comment]
Bevy 0.5 doesn't natively support compiling for wasm. You need bevy-webgl for that. The pipelined-renderer branch does support it with the newel renderer that uses the latest wgpu version.

**Comment by alice-i-cecile** [comment]
Near-duplicate of #88. :)

**Comment by TheButlah** [comment]
@bjorn3 I tried using bevy_webgl2 as well and it did not solve the compilation issue

**Comment by bjorn3** [comment]
Maybe you need to disable the bevy_wgpu feature of bevy?

**Comment by TheButlah** [comment]
Sorry, I see what you mean - bevy_webgl2 is intended to be a replacement for bevy_wgpu. So my issue would be better restated as "I cannot figure out how to use bevy and bevy_webgl2 together on WASM". I can close and reopen a different issue

**Comment by alice-i-cecile** [comment]
@TheButlah see https://bevy-cheatbook.github.io/platforms/wasm.html for an excellent guide.
