### ISSUE TITLE
Misleading comment on Text rotation

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3163]
https://github.com/bevyengine/bevy/blob/9d453530fac9202691c797184ad0b220b2ea37b3/crates/bevy_text/src/text2d.rs#L58 is no longer correct following the addition of non-UI text.

See https://github.com/bevyengine/bevy/blob/main/examples/2d/text2d.rs.

**Comment by Wcubed** [comment]
Looks like the current main branch no longer contains the function in question: https://github.com/bevyengine/bevy/blob/main/crates/bevy_text/src/text2d.rs. I'd say this can be closed.

**Comment by alice-i-cecile** [comment]
Good eye, thank you!
