### ISSUE TITLE
Improve code quality of contributors.rs example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3181]
Current issues:

1. Some variable names are too terse and are very unclear (e.g. `tq`, `sel`).
2. The `contributors` function should fall back to a hard-coded default so that it can be copy-pasted onto a user's machine. A result may be a nice fit here.
3. Setup could be split into two or more reasonably sized systems.

For additional guidance, you can check out the initial attempt started by @DJMcNab here: https://github.com/DJMcNab/bevy/commit/6a5451e24ffe40fd6761d65100601ed8bdf03543.

**Comment by CrazyRoka** [comment]
@alice-i-cecile I added a PR to fix 1st and 3rd issue. I don't fully understand about 2nd issue. Can you explain it a little bit more? You can suggest directly into #3258

**Comment by devil-ira** [comment]
@CrazyRoka. Currently the function 'contributors' will panic if not run as an example from this repo.
So if someone wants to make something with this example as a base and they copy it into their main.rs it would stop working 😞

It would be nice if the 'contributors' function instead returned a Result and if it returns an Err a hard-coded list of contributors is used instead.

**Comment by alice-i-cecile** [comment]
> `@CrazyRoka`. Currently the function 'contributors' will panic if not run as an example from this repo.
So if someone wants to make something with this example as a base and they copy it into their main.rs it would stop working 😞

Precisely :)

> Just realized it also uses 'branding/icon.png'. I can't think of a solution to that. What do you think @alice-i-cecile ?

I think that forcing users to download assets is relatively unavoidable: many of our other examples need it.

Down the road, I would like to have better tools for gracefully handling asset loading failures (and display placeholder models), but that's well beyond the scope of this issue.
