### ISSUE TITLE
Improve advice for finding Linux GPUs

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3191]
## How can Bevy's documentation be improved?

'Unable to find a GPU! Make sure you have installed required drivers!' 

This error is one of our most common install issues (particularly on Linux), but it's often hard to know where to go next.

See #3016, #807, #509, #387 and #924 for examples.

**Comment by y1j2x34** [comment]
https://linuxconfig.org/install-and-test-vulkan-on-linux

**Comment by Elabajaba** [comment]
Pretty much all of these are running on very old hardware that doesn't support Vulkan, and in some of them you even have users that uninstalled the Vulkan driver and ignored the linked docs in the error message.

I don't know how much more you can do, unless you want to kneecap bevy's renderer to Opengl on desktop.
