### ISSUE TITLE
Major visual artifacts when running the pipelined renderer examples

### ISSUE THREAD

**Issue by setzer22** [bevyengine/bevy#3194]
## Bevy version

Using the `main` branch, as of today: `f512c853d7e5bcf91c8d411aa4c5ae3058220da8`

## Operating system & version

OS: Manjaro (rolling), kernel version: `5.13.19-2`, using the `amdgpu` open source driver.
GPU: Radeon RX 6600XT

## What you did

1. Clone latest `main` branch, after the pipelined renderer has been merged.
2. Compile and run one of the examples, e.g. `cargo run --example 3d_scene_pipelined`.

## What you expected to happen

A regular-looking 3d scene would be visible on screen.

## What actually happened

The 3d scene shown was full of visual artifacts and incorrect colors:
![bevy_error](https://user-images.githubusercontent.com/7241990/143577356-2045ee3b-b8b8-4654-8a31-c9c790cf2954.gif)

## Additional information

I have verified that other wgpu-based applications work fine on my machine by testing the examples in https://github.com/gfx-rs/wgpu

**Comment by mockersf** [comment]
@superdump could it be related to #3186?

**Comment by setzer22** [comment]
I have tested this on two other machines:

- On a laptop with same OS, but with a Amd Vega 7 integrated graphics, I get very similar artifacts.
- On a different laptop, also same OS, but with a Nvidia 1050Ti (mobile) GPU, I didn't get any artifacts.

**Comment by superdump** [comment]
> @superdump could it be related to #3186?

Yup. Certainly could be given the bug fixed by that simply means that it reads the shadow map value from uninitialised memory.

**Comment by superdump** [comment]
Or it could be just a holiday disco ball mode. :)

**Comment by mockersf** [comment]
#3186 has been merged, could you retry with latest main?

**Comment by setzer22** [comment]
Looks like it's fixed! :+1: 
![bevy_working](https://user-images.githubusercontent.com/7241990/143593251-26c17f96-dca2-4413-af14-ac931f74a3a7.gif)
