### ISSUE TITLE
problems with pipelined 3d examples

### ISSUE THREAD

**Issue by adsick** [bevyengine/bevy#3198]
## Bevy version
latest (f3d4be31)

## Operating system & version

Fedora 35

## What you did

Ran new pipelined 3d examples

## What happened

Summary: most examples work as intended, but others are 'wrong' or strange (look like something is missing)

# Screenshots

### pbr_pipelined:
![image](https://user-images.githubusercontent.com/24528839/143627333-a772bf44-97f6-40f7-bf85-d9ac16ab2b7b.png)
note: regular pbr example works just fine.

### shadow_caster_receiver_pipelined:
in this one pressing C or R has no effect on what is being displayed on screen.
![image](https://user-images.githubusercontent.com/24528839/143627459-86b80142-c452-4834-8348-bdd9308abb64.png)

### texture_pipelined:
![image](https://user-images.githubusercontent.com/24528839/143627642-e83f6a8b-3d1c-4ea6-9672-a8108883ee79.png)
transparency doesn't work.

## Additional information
hardware: Ryzen 5 3500u, iGPU: Vega 8, 12G Ram.

**Comment by MinerSebas** [comment]
The `pbr_pipelined` example will be fixed by #3182

**Comment by mockersf** [comment]
`pbr_pipelined` issue is a regression introduced by #3192...

**Comment by superdump** [comment]
> `pbr_pipelined` issue is a regression introduced by #3192, fixed in #3200
> 
> `shadow_caster_receiver_pipelined` is a known "issue", examples were not updated after decision to disable shadows by default in #3126, fixed in #3201
> 
> `texture_pipelined` is from #3072, fixed in #3202

Thanks for noting these! And for submitting fixes. I have been testing with more advanced scenes which make specific use of these features or demonstrate issues with them and I missed updating the examples that they affect.

**Comment by adsick** [comment]
after git pull I see beautiful shadows in ```3d_scene_pipelined```
but also not so beautiful artifacts in ```shadow_biases_pipelined```
![image](https://user-images.githubusercontent.com/24528839/143720956-0078cc9b-9ac4-4628-86b3-4b17e5e6afa0.png)

**Comment by superdump** [comment]
The artifacts in shadow_biases_pipelined are intentional. It’s a bit of a playground to let people get a feel for adjusting the depth and normal biases for shadow maps. The instructions printed to the terminal tell you how you can adjust them. This has confused other people too so we should make the example’s intent clearer.

**Comment by adsick** [comment]
yesterday it was looking fine (so I didn't report here) but today I tested again and was surprised))

**Comment by adsick** [comment]
shadows in ```shadow_biases_pipelined``` still look kinda odd tho, I tried adjustments but they don't seem to make it better

**Comment by superdump** [comment]
The default values that I found to work quite well are: depth bias 0.02, normal bias 0.6. Hopefully that helps you to see how adjusting the biases behaves.

**Comment by mockersf** [comment]
#3200 was merged which should fix example `pbr_pipelined`, and it should also impact `shadow_biases_pipelined`

how it renders with the default values for me:
![default-values](https://user-images.githubusercontent.com/8672791/143766193-23eac169-229d-42ec-929d-fbae132425e3.png)

and with the values from Superdump:
![superdump-values](https://user-images.githubusercontent.com/8672791/143766208-6cb02518-ddbb-4b37-8260-5e3032168bea.png)

**Comment by adsick** [comment]
I confirm that ```pbr_pipelined``` works (for me)

**Comment by mockersf** [comment]
`texture_pipelined` should be fixed too now on main 🎉 

Do you still have an issue with `shadow_biases_pipelined`?

**Comment by adsick** [comment]
I'll test ```texture_pipelined``` and this issue will probably be closed soon.
Speaking of ```shadow_biases_pipelined``` I guess mine looks just the same as yours, but shadows are kinda blocky. Isnt that a problem?

**Comment by superdump** [comment]
> I'll test `texture_pipelined` and this issue will probably be closed soon.
> Speaking of `shadow_biases_pipelined` I guess mine looks just the same as yours, but shadows are kinda blocky. Isnt that a problem?

Absolutely. It’s not a bug though, rather that the shadow resolution is necessarily low with the current solution. I was working on a technique called cascaded shadow maps that will significantly improve the directional light shadow quality, but I thought it would need some more time to get it working well and have instead focused on getting my chain of branches merged so we could get to this point and move closer to a 0.6 release. Improvements will continue to come. :)

**Comment by mockersf** [comment]
You can also increase (a little) shadow resolution with those two resources:
```rust
    App::new()
        .add_plugins(PipelinedDefaultPlugins)
        .insert_resource(bevy::pbr2::PointLightShadowMap {
            size: 2_usize.pow(13),
        })
        .insert_resource(bevy::pbr2::DirectionalLightShadowMap {
            size: 2_usize.pow(13),
        })
```

![Uploading Screenshot 2021-11-30 at 09.27.55.png…]()

I didn't find any example showing this, should we add one?

**Comment by adsick** [comment]
![image](https://user-images.githubusercontent.com/24528839/144104901-1f2da802-b765-41cd-8509-de81d2ed3f82.png)
```texture_pipelined``` works, I think the issue can be closed.

**Comment by adsick** [comment]
I think that's cool (tweaking the system with resources) maybe it worth describing in examples.

**Comment by adsick** [comment]
And yeah, ```texture_pipelined``` works so I've closed the issue. Good job!
