### ISSUE TITLE
window_settings example makes computer unresponsive 

### ISSUE THREAD

**Issue by Raymond26** [bevyengine/bevy#320]
Hi, I ran the `window_settings` example in macOS Catalina and could not kill the program without a forced restart of my laptop by holding the power button.  Could not use the usual command+q, alt+tab, ctrl+c, etc.. Was running dual monitor so I could click around on my other screen in some places and but no keyboard presses were being read - ex. Chrome was shown to be in focus but could not type into the URL bar - only click.  I could not click the visible OS dock and could not click the Apple icon to gracefully shut down.  

After a restart I tried running the example in a separate terminal window on my other monitor and the only way to stop the program was to click on the close-tab button.  again, ctrl+c, ctrl+d didn't work

**Comment by D1plo1d** [comment]
I'm seeing a similar issue on Ubuntu 20.04 / XPS15 / Proprietary NVIDIA Drivers. In my case running once I got to the point of adding `DefaultPlugins` in the bevy book if I tried to alt tab the window would freeze my computer for ~20 to 40 seconds. During that time moving the mouse updated the screen maybe once every 10 seconds? and keyboard inputs were similarly delayed. Then the window would finish alt + tabbing and I would be unfrozen.

My workaround was the same: Never alt tab. Always hit the exit X button on the window and it will exit quickly and without hanging the computer.

**Comment by D1plo1d** [comment]
Terminal Warning:
```
Dec 06 23:45:32.142  WARN wgpu_core::device: Failed to parse shader SPIR-V code: UnsupportedBuiltIn(4)
Dec 06 23:45:32.142  WARN wgpu_core::device: Shader module will not be validated
Dec 06 23:45:32.149  WARN wgpu_core::device: Surface does not support present mode: MAILBOX, falling back to FIFO
Dec 06 23:45:32.174  WARN wgpu_core::device: Surface does not support present mode: MAILBOX, falling back to FIFO
```

**Comment by mockersf** [comment]
can't reproduce

**Comment by mockersf** [comment]
please open another, it's unlikely to be related to a 4 year old issue on macOS 🙂

**Comment by adsick** [comment]
It seems to be gone after some update (drivers?)
