### ISSUE TITLE
wgpu-hal causes

### ISSUE THREAD

**Issue by thechubbypanda** [bevyengine/bevy#3205]
## Bevy version

`main` branch, commit: https://github.com/bevyengine/bevy/commit/e8412df0211f5684aa03459e1f47a5c40035f6c1

## Operating system & version

Arch Linux fully up to date

## What you did

```
[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", branch = "main", features = ["dynamic"]}
```

`cargo run`

## What you expected to happen

Runs correctly

## What actually happened

```
   Compiling wgpu-hal v0.11.4
   Compiling bevy_render v0.5.0 (https://github.com/bevyengine/bevy.git?branch=main#e8412df0)
   Compiling bevy_scene v0.5.0 (https://github.com/bevyengine/bevy.git?branch=main#e8412df0)
   Compiling bevy_audio v0.5.0 (https://github.com/bevyengine/bevy.git?branch=main#e8412df0)
error: Metal API enabled on non-Apple OS. If your project is not using resolver="2" in Cargo.toml, it should.
  --> /home/keval/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.11.4/src/lib.rs:49:1
   |
49 | compile_error!("Metal API enabled on non-Apple OS. If your project is not using resolver=\"2\" in Cargo.toml, it should.");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: DX12 API enabled on non-Windows OS. If your project is not using resolver="2" in Cargo.toml, it should.
  --> /home/keval/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.11.4/src/lib.rs:51:1
   |
51 | compile_error!("DX12 API enabled on non-Windows OS. If your project is not using resolver=\"2\" in Cargo.toml, it should.");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved import `super::dx12`
  --> /home/keval/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.11.4/src/lib.rs:72:20
   |
72 |     pub use super::dx12::Api as Dx12;
   |                    ^^^^ could not find `dx12` in the crate root

error[E0432]: unresolved import `super::metal`
  --> /home/keval/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.11.4/src/lib.rs:83:20
   |
83 |     pub use super::metal::Api as Metal;
   |                    ^^^^^ could not find `metal` in the crate root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `wgpu-hal` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

## Additional information

I saw #2712 but I'm completely up to date so I don't know what else to do.

**Comment by DJMcNab** [comment]
Does the error persist when you add resolver="2" to your package/workspace properties (which is suggested in the error message)

**Comment by thechubbypanda** [comment]
Where am I supposed to add that?

I tried putting it in the cargo.toml but the problem persisted

**Comment by mockersf** [comment]
you should add it here https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions

alternatively, if you are on latest rust, you can select edition 2021 which will select it by default

**Comment by thechubbypanda** [comment]
Cheers @mockersf, 2021 did the trick. I was using 2018 still for some reason lol

**Comment by DJMcNab** [comment]
I think we should work with the wgpu team to provide more actionable guidance there.

Hopefully compile_error can accept a multiline string.

**Comment by thechubbypanda** [comment]
Agreed, that error message doesn't really point you to a solution

**Comment by thechubbypanda** [comment]
Cheers @alice-i-cecile XD

**Comment by riverfr0zen** [comment]
Just a note for those new to Rust like me that if your packages are in a workspace, you need to indicate the resolver in the workspace's Cargo.toml file also. But in the workspace's Cargo.toml, it *has* to be " `"resolver = 2"`, NOT `edition = "2021"`. [This page](https://issueexplorer.com/issue/rust-lang/cargo/9956) goes into it.

**Comment by twe4ked** [comment]
> [This page](https://issueexplorer.com/issue/rust-lang/cargo/9956) goes into it.

404s for me now.

https://github.com/rust-lang/cargo/issues/9956
