### ISSUE TITLE
Pipelined rendering doesn't work on DX12

### ISSUE THREAD

**Issue by Elabajaba** [bevyengine/bevy#3208]
## Bevy version

main branch, e8412df0211f5684aa03459e1f47a5c40035f6c1

## Operating system & version

Windows 11

## What you did

Run any of the pipelined examples with WGPU_BACKEND="dx12" env variable. 

(For those who don't know, in powershell you can enter `$env:WGPU_BACKEND="dx12"` (including the $) to change the env variable for that terminal session).

## What you expected to happen

I expect them to crash, as this is an upstream issue in wgpu.

## What actually happened

They crashed.

## Additional information

Upstream issue: https://github.com/gfx-rs/wgpu/issues/2185

This is due to bevy enabling the TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES wgpu feature, which is implemented for DX12 but they forgot to expose it as a DX12 feature.

I tried adding the feature to the DX12 feature list and testing it with https://github.com/bevyengine/bevy/pull/3041's game_of_life_pipelined example (it uses a ReadWrite StorageTexture), but it still crashes.

My wgpu 0.11 branch that enables the feature: https://github.com/Elabajaba/wgpu/tree/dx12-feature-0.11

**Comment by cart** [comment]
Probably worth working around if this isn't fixed upstream prior to the next bevy release (maybe by just disabling TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES). `3d_scene_pipelined` works without it for me.
