### ISSUE TITLE
I'm not sure why it's different here

### ISSUE THREAD

**Issue by Cupnfish** [bevyengine/bevy#321]
```rust
pub fn get_mut(&mut self, handle: &Handle<T>) -> Option<&mut T> {
        self.events.send(AssetEvent::Modified { handle: *handle });
        self.assets.get_mut(&handle)
    }
```
```rust
    pub fn get_id_mut(&mut self, id: HandleId) -> Option<&mut T> {
        self.assets.get_mut(&Handle::from_id(id))
    }
```

I'm working on Bevy's code,Then I found this place here, I think it should be rewritten like this
```rust
    pub fn get_id_mut(&mut self, id: HandleId) -> Option<&mut T> {
        self.get_mut(&Handle::from_id(id))
    }
```

**Comment by DJMcNab** [comment]
Canonical links:
https://github.com/bevyengine/bevy/blob/d00ce1c61c2938c35c495bb7d1af71346f9ee46e/crates/bevy_asset/src/assets.rs#L75-L78

https://github.com/bevyengine/bevy/blob/d00ce1c61c2938c35c495bb7d1af71346f9ee46e/crates/bevy_asset/src/assets.rs#L67-L69

And I think I agree it should be changed to call the former.
