### ISSUE TITLE
Make `KeyCode` impl `Copy`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3213]
`KeyCode` is a quintessential example of tiny stateless data that is routinely and quickly cloned. IMO we can implement `Copy` on it safely to improve end user ergonomics.

**Comment by ickk** [comment]
I think [ `KeyCode` does implement `Copy`](https://github.com/bevyengine/bevy/blob/e8412df0211f5684aa03459e1f47a5c40035f6c1/crates/bevy_input/src/keyboard.rs#L35), however `KeyboardInput` does not

**Comment by NiklasEi** [comment]
As pointed out above, `Keycode` does implement `Copy`. Implementing `Copy` on `KeyboardInput` [was discussed and decided against](https://github.com/bevyengine/bevy/pull/3214#issuecomment-981932640), so I will close this for now.

If there are any strong opinions, we can open a new issue specifically about `Copy` for `KeyboardInput` :slightly_smiling_face:
