### ISSUE TITLE
Direction pad buttons not working

### ISSUE THREAD

**Issue by adam-becker** [bevyengine/bevy#3229]
## Bevy version

`bab4ee962d88a5576d7f045d22129e8d20645f14`

## Operating system & version

Host: `Arch Linux`
Guest `Debian 10 (rust:buster docker image)`

## What you did

Here is a (sort of)-minimal repro:

```rust
struct Buttons {
  jump: GamepadButtonType,
  shoot: GamepadButtonType,
  up: GamepadButtonType,
  down: GamepadButtonType,
  left: GamepadButtonType,
  right: GamepadButtonType,
}

impl Default for Buttons {
  fn default() -> Self {
    Self {
      jump: GamepadButtonType::South,
      shoot: GamepadButtonType::West,
      up: GamepadButtonType::DPadUp,
      down: GamepadButtonType::DPadDown,
      left: GamepadButtonType::DPadLeft,
      right: GamepadButtonType::DPadRight,
    }
  }
}

fn input_system(
  button_inputs: Res<Input<GamepadButton>>,
  buttons: Res<Buttons>
) {
  let just_pressed = |button_type| {
    button_inputs.just_pressed(GamepadButton(Gamepad(0), button_type))
  };

  if just_pressed(buttons.jump) {
    println!("jump");
  }

  if just_pressed(buttons.shoot) {
    println!("shoot");
  }

  if just_pressed(buttons.up) {
    println!("up");
  } else if just_pressed(buttons.down) {
    println!("down");
  }

  if just_pressed(buttons.left) {
    println!("left");
  } else if just_pressed(buttons.right) {
    println!("right");
  }
}
```

With this code in place, I can press `A`/`X` on my gamepad and see `jump`/`shoot` print to the console, respectively. However, I see nothing print when pressing any of the directional buttons.

## What you expected to happen

When I press a button, the corresponding `println!` should execute.

## What actually happened

Nothing happens.

## Additional information

The controller in question is rock solid, and works on any steam games and/or emulators.

**Comment by adam-becker** [comment]
Okay. I've just noticed that there is a `GamepadAxisType::{DPadX, DPadY}`, and these seem to work. I'm genuinely curious why `GamepadButtonType::{DPadLeft, DPadRight, DPadUp, DPadDown}` exist if they are also (only?) available on the `GamepadAxisType` enum?

This seems counter-intuitive to me. Most APIs treat the directional pad buttons as _at least_ buttons, a few supporting an analog API (axis here) in addition to this.

Is this intended behavior, or a bug? If intended then API documentation would help, and removing the buttons from the `GamepadButtonType` would be great.

**Comment by alice-i-cecile** [comment]
> Okay. I've just noticed that there is a GamepadAxisType::{DPadX, DPadY}, and these seem to work. I'm genuinely curious why GamepadButtonType::{DPadLeft, DPadRight, DPadUp, DPadDown} exist if they are also (only?) available on the GamepadAxisType enum?

The difference is that the buttons return a binary output, while the axes will return a float showing intensity :)

The DPad buttons are working for me on Windows 10 with an XBox controller: which gamepad are you using?

Could you test the gamepad on a different tool to verify that it's our (or more likely, [gilrs](https://github.com/Arvamer/gilrs)'s) issue? Perhaps https://gamepad-tester.com/ ?

**Comment by adam-becker** [comment]
> > Okay. I've just noticed that there is a GamepadAxisType::{DPadX, DPadY}, and these seem to work. I'm genuinely curious why GamepadButtonType::{DPadLeft, DPadRight, DPadUp, DPadDown} exist if they are also (only?) available on the GamepadAxisType enum?
> 
> The difference is that the buttons return a binary output, while the axes will return a float showing intensity :)

But digital pads are .. digital 😅 

> The DPad buttons are working for me on Windows 10 with an XBox controller: which gamepad are you using?

XBOX One S Wireless

> Could you test the gamepad on a different tool to verify that it's our (or more likely, [gilrs](https://github.com/Arvamer/gilrs)'s) issue? Perhaps https://gamepad-tester.com/ ? I would also test our upstream examples: https://github.com/Arvamer/gilrs/tree/master/gilrs/examples

Tried gamepad tester and everything was nice and flickery there. I can try `gilrs` examples maybe this weekend.

**Comment by bjorn3** [comment]
> Tried gamepad tester and everything was nice and flickery there.

How does it report the d-pad? Can you show a screenshot while pressing one or more of the d-pad buttons?

**Comment by adam-becker** [comment]
> > Tried gamepad tester and everything was nice and flickery there.
> 
> How does it report the d-pad? Can you show a screenshot while pressing one or more of the d-pad buttons?

Hopefully this table will suffice, as it'll cover all of the buttons.

| Button | Axis 6 | Axis 7 |
|--------|--------|--------|
| - | 0 | 0 |
| Up | 0 | -1 |
| Down | 0 | 1 |
| Left | -1 | 0 |
| Right | 1 | 0 |

For an "at rest" reference, here's an image from the gamepad tester:

![image](https://user-images.githubusercontent.com/47185607/144523805-fa28fb0c-b54c-4e46-891a-a44aea43e9a6.png)

It might also be worth mentioning that this particular setup is using the standard USB kernel module not the custom bluetooth ones like [xpadneo](https://github.com/atar-axis/xpadneo). I have the controller plugged in directly via USB cable.

**Comment by bjorn3** [comment]
It reports the d-pad as two axis and not as four d-pad buttons. This matches how bevy responds.

**Comment by adam-becker** [comment]
> It reports the d-pad as two axis and not as four d-pad buttons. This matches how bevy responds.

Noted. I wonder why this controller behaves differently than the one that @alice-i-cecile has.. Also this will prevent me from having simple `just_pressed` checks for digital pad :(

I guess it's a [known issue](https://bbs.archlinux.org/viewtopic.php?id=237892) though. I'm okay with closing this as it doesn't appear to be a problem with `bevy` and/or `gilrs`. Hopefully anyone googling for this in the future stumbles on this issue.

**Comment by adam-becker** [comment]
Since I just found [this](https://www.kernel.org/doc/html/v4.12/input/devices/xpad.html#notes), I'm going to add it here.

Recognized devices always have digital pad mapped as axes on Linux if using the `xpad` module, which is the default configuration. This can be confirmed by running `systool -vm xpad`.

To reiterate, even if you set the parameter the module outright ignores it for recognized devices. This is my configuration and I still have digital pad as axes instead of buttons.

```
$ systool -vm xpad
Module = "xpad"

  Attributes:
    coresize            = "45056"
    initsize            = "0"
    initstate           = "live"
    refcnt              = "0"
    srcversion          = "487C2C241DADE10B46F23B8"
    taint               = ""
    uevent              = <store method only>

  Parameters:
    auto_poweroff       = "Y"
    dpad_to_buttons     = "Y"
    sticks_to_null      = "N"
    triggers_to_buttons = "N"

  Sections:

```

Cheers.
