### ISSUE TITLE
Document and rename bevy::scene::Entity

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3233]
## How can Bevy's documentation be improved?

This type ([docs](https://docs.rs/bevy/latest/bevy/scene/struct.Entity.html),  [source](https://github.com/bevyengine/bevy/blob/main/crates/bevy_scene/src/dynamic_scene.rs#L17)) appears to be used to store reflected entities, along with their components in scenes. However, it is a) completely lacking documentation b) very confusingly named: `Entity` is one of our most important types, and this is closely-related but distinct in important ways.

At a glance, this seems to be a reflection-powered serializable representation of an entity and its components. The `entity: u32` field  is likely for use with `Entity::new()` (the standard `Entity` type), and the entire `DynamicScene` type is used to spawn groups of entities which contain a number of entities, each with their own run-time defined set of components. These `DynamicScenes` can be written to file, but not read from.

Later in the same file, [`EntityMap`](https://github.com/bevyengine/bevy/blob/cf221f9659127427c99d621b76c8085c4860e2ef/crates/bevy_ecs/src/entity/map_entities.rs) is used, which contains a map between entities, in the standard `bevy_ecs` sense. This naming convention seems to be fine.

My first impulse would be to call this `DynamicEntity`, but please, bikeshed me if you disagree.

**Comment by cart** [comment]
Yup I generally try to treat Bevy as a "global namespace" and this very clearly breaks that rule of thumb.

**Comment by Davier** [comment]
`DynamicEntity` seems very appropriate.

>These DynamicScenes can be written to file, but not read from.

We get a `Handle<DynamicScene>>`  when loading a serialized scene from file:
<https://github.com/bevyengine/bevy/blob/ccee658436be3d8bd721bbdda4a02f47235799da/examples/scene/scene.rs#L53>

(However, we get a  `Handle<Scene>` type when loading a glTF scene, which might be confusing).
