### ISSUE TITLE
All pipelined examples crash with "non-filterable float texture"

### ISSUE THREAD

**Issue by NiklasEi** [bevyengine/bevy#3235]
## Bevy version

Latest main 02b8a782e5977a0211cd7b3821026f7d5c06281c

## Operating system & version

Ubuntu 18.04

## What you did

Run any pipelined example. E.g. `cargo run --example msaa_pipelined` (the result is the same with `--release`).

## What you expected to happen

The examples to run

## What actually happened

All pipelined examples that I tried crashed with
```
ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `sprite_pipeline`
    error matching FRAGMENT shader requirements against the pipeline
    unable to filter the texture (ResourceBinding { group: 1, binding: 0 }) by the sampler (ResourceBinding { group: 1, binding: 1 })
    non-filterable float texture
```

## Additional information

[stacktrace_msaa_pipelined.txt](https://github.com/bevyengine/bevy/files/7640079/stacktrace.txt)

**Comment by Weasy666** [comment]
I get the same error on a Windows 10 Pro 21H2 Build 19044.1387 machine.

**Comment by NiklasEi** [comment]
@Weasy666 could you check if you still get this with wgpu pinned to version `0.11.0`? Version `0.11.1` is very new, maybe that's why the crash showed up just now?

**Comment by mockersf** [comment]
reproduced on macOS when updating `wgpu-core`  from 0.11.2 to 0.11.3

**Comment by NiklasEi** [comment]
> `bevy_wgpu` is already pinned to `0.11.0`. Where else should i pin it?

The dependency is not pinned in `bevy_wgpu` ([no requirement defaults to caret](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio). To really pin it, it would need to be `version = "= 0.11.0"`.

But mockersf already answered the question that I was hoping to answer with this request to you :slightly_smiling_face:

**Comment by Weasy666** [comment]
Ah...well...nevertheless, i tested with the pinned version with the expected result/error.
