### ISSUE TITLE
Rename `KeyCode::*Win` to `KeyCode::*Meta`

### ISSUE THREAD

**Issue by MrGVSV** [bevyengine/bevy#3240]
## What problem does this solve or what need does it fill?

The KeyCode's `LWin` and `RWin` can be somewhat confusing/difficult to find for us Mac users. They seem like they should only work for Windows-style keyboards.

## What solution would you like?

Rename `KeyCode::LWin` and `KeyCode::RWin` with the more generic `KeyCode::LMeta` and `KeyCode::RMeta`.

**Comment by adsick** [comment]
'Meta' feels foreign for Windows and Linux users and also note that there are a lot more people on Windows than on MacOS.
On Linux we sometimes refer to it as 'Super' key, but that is probably the rarest one. 

Imho this key won't be used in most games and apps so no need to bother.

**Comment by bjorn3** [comment]
What emacs calls the meta key is the alt key on most keyboards or option on apple keyboards. Same for vim.

**Comment by MrGVSV** [comment]
> On Linux we sometimes refer to it as 'Super' key, but that is probably the rarest one.

Super is another possibility. I've  made apps in Electron and I think they use both.

> Imho this key won't be used in most games and apps so no need to bother.

That's probably true. Although, shortcuts like <kbd>Super</kbd>+<kbd>W</kbd> might be handy for multi-window applications. Or <kbd>Super</kbd>+<kbd>C</kbd> to copy text. And things like that.

But if these are seen to be unlikely cases, then I suppose we could just stick with the `*Win` terminology.

**Comment by MrGVSV** [comment]
> What emacs calls the meta key is the alt key on most keyboards or option on apple keyboards. Same for vim.

Oh didn't know that. Maybe `Meta` isn't the best then? `Super` is now seeming like it might be the better option then, if we want to still change it. 

Otherwise, like I said in my other comment, we can just leave this as is if the community doesn't see any merit in it currently.

**Comment by adsick** [comment]
how about ```SuperMetaWin```?

**Comment by MrGVSV** [comment]
> how about SuperMetaWin?

This is the one! 😂

**Comment by bouncepaw** [comment]
`Meta` can and will confuse Emacs and Vim users. It happened to me, actually, in a different project.

`Super` is a good and classic choice.

The QMK keyboard firmware uses the word `GUI` for this key. `LGUI` and `RGUI`.

`Win` and `Cmd` are platform-specific choices and thus should be avoided.

**Comment by visualcode-t** [comment]
Is having an alias an option? The problem is most keyboards have a "Windows" key regardless of your OS. So, simply changing it from one to another only moves the confusion, it doesn't really *solve* anything.

**Comment by MrGVSV** [comment]
> Is having an alias an option?

While it could be nice (again, this is how Electron handles it I think), it could be an issue when matching the KeyCode. We'd probably have to write something like:

```rust
match keycode {
  KeyCode::LWin | KeyCode::LMeta => { /* Do something */ },
  // ...
}
```

So I think an alias might not be the proper solution. 

> The problem is most keyboards have a "Windows" key regardless of your OS. So, simply changing it from one to another only moves the confusion, it doesn't really _solve_ anything.

Yeah, that's what I think it comes down to. Most people are either on Windows or using a keyboard with a Windows key. A change like this might not be favored by the majority then, even if it does agnosticize the OS/hardware terminology.

**Comment by MrGVSV** [comment]
Closing for now, as it seems a change to `Meta` or `Super` might cause more confusion.

**Comment by adsick** [comment]
I guess we might just leave this discussion for now and make a poll on this topic in the future. I've did a small poll in my blog and people preferred Super to Meta and no one wanted Win. (only 14 people participated)

also thought of an idea that there are a lot of gamers on Windows, but the majority of developers are on Linux/MacOS which might be an interesting point to consider in this context.

**Comment by aloucks** [comment]
Why not just add some documentation to `LWin` and `RWin` that describes what they map to on other platforms?

**Comment by MrGVSV** [comment]
> Why not just add some documentation to `LWin` and `RWin` that describes what they map to on other platforms?

This a easy compromise for the time being and should at least help
