### ISSUE TITLE
Time::time_since_startup is inconsistent

### ISSUE THREAD

**Issue by fluffysquirrels** [bevyengine/bevy#3259]
## Bevy version

master@2021-12-05, or 4423a2fa2dc82fad71525ed3f44e16b8481a4902

## The issue

Time.seconds_since_startup() ([source](https://github.com/bevyengine/bevy/blob/4423a2fa2dc82fad71525ed3f44e16b8481a4902/crates/bevy_core/src/time/time.rs#L65-L68)) and Time.time_since_startup() ([source](https://github.com/bevyengine/bevy/blob/4423a2fa2dc82fad71525ed3f44e16b8481a4902/crates/bevy_core/src/time/time.rs#L82-L84)) are inconsistent, which is unexpected.

The former returns the time from startup to the last update(), the latter returns the time from startup to Instant::now().

## What you expected to happen

I think Time.time_since_startup() should return the time from startup to the last update(), because that is consistent with the rest of the struct and a similarly named method.

If users truly want to compare to Insant::now they can do so with `Instant::now - time.startup()`.

This would be a breaking change; if that is undesirable then at least the discrepancy can be documented to try and avoid surprising users.

**Comment by fluffysquirrels** [comment]
In the case where .last_update is None, I expect time_since_startup to return Duration::from_secs(0), like seconds_since_startup.

**Comment by alice-i-cecile** [comment]
That's a perfectly reasonable API change, and I think returning the time to the last update is generally more useful.

This should be an easy change, so I've added the `good-first-issue` tag for anyone who'd like to make a small PR :)

**Comment by fluffysquirrels** [comment]
I'm working on this now.
