### ISSUE TITLE
Issue ordering exclusive systems accross SystemSet

### ISSUE THREAD

**Issue by NiklasEi** [bevyengine/bevy#3293]
## Bevy version

`main`  58474d7c4a2dcd0684730500def03f30e5ebc0e6

## Operating system & version

Ubuntu 18.04

## What you did

I tried ordering exclusive systems based on labels. Some of them are in a `SystemSet`, but all are in the same `Stage` and have the default location.

## What you expected to happen

The systems should run in the correct order.

## What actually happened

The first frame has the wrong order. Later frames are correct.

## Additional information

[Minimal example
](https://github.com/NiklasEi/bevy_playground)

Here the ordering should be `1.`, `A`, `2.`, but the first frame prints `A`, `1.`, `2.`.  Removing the SystemSet fixes this and prints the correct order from the first frame on.

**Comment by hymm** [comment]
This is a states issue. On the first frame the state needs to run on_enter, so in the loop in runs the a system first, then loops to run the on_update systems.  Basically it has to ignore the ordering. After the first frame it no longer needs to do the on_enter, so starts with the on_update systems and is able to respect the ordering.

**Comment by alice-i-cecile** [comment]
Unfortunately this gets the `needs-rfc` tag, because of the mess that is states powered by run criteria. See #2801 for bread crumbs.

**Comment by alice-i-cecile** [comment]
Fixed by #7267.
