### ISSUE TITLE
Shader `Color` uniform wrongly serialized to GPU

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#3295]
## Bevy version

0.5

## Operating system & version

Windows 10 (Vulkan)

## What you did

I've essentially followed https://gist.github.com/StarArawn/f4da80e06dfcefda90fde11d7f2d2c5d, adding a custom uniform block with a `Color` field in it.

```glsl
layout(set = 2, binding = 0) uniform ProgressBarUniform {
    vec4 back_color;
    vec4 fill_color;
    float loading_fraction;
};
void main() {
    float threshold = step(loading_fraction, v_Uv.x);
    vec3 mixed = mix(back_color.rgb, fill_color.rgb, threshold);
    o_Target = vec4(mixed, 1.0);
}
```

```rust
#[derive(RenderResource, RenderResources, Default, TypeUuid)]
#[uuid = "463e4b8a-d555-4fc2-ba9f-4c880063ba92"]
#[render_resources(from_self)]
struct ProgressBarUniform {
  back_color: Color,
  fill_color: Color,
  loading_fraction: f32,
}
// -------------
[...].insert(ProgressBarUniform {
    back_color: Color::rgba(0.0, 1.0, 0.0, 1.0), // GREEN
    fill_color: Color::rgba(1.0, 0.0, 0.0, 1.0), // RED
    loading_fraction: 0.0, // later modified in system based on time
}
```

## What you expected to happen

`Color` is serialized to GPU correctly.

## What actually happened

- Data is serialized as 4 bytes in the buffer
- The data structure reads the color as 4 `f32` from the buffer

## Additional information

Debugged with @StarArawn ([Discord thread](https://discord.com/channels/691052431525675048/742884593551802431/919202214071926815)) and we couldn't find anything wrong. The RenderDoc capture clearly shows (to my uneducated eye) the data being serialized in a different way that it's read back.

![image](https://user-images.githubusercontent.com/6532395/145678374-9189e611-cce7-49c6-89da-a01ec65b03a5.png)

**Comment by djeedai** [comment]
RenderDoc capture (1 frame) : [bevy_bug_shader_swizzle.zip](https://github.com/bevyengine/bevy/files/7697110/bevy_bug_shader_swizzle.zip)

**Comment by djeedai** [comment]
I found a workaround by looking at `StandardMaterial` and `pbr.frag`. It seems `#[render_resources(from_self)]` is the culprit. Removing it and splitting into separate bindings make things work as intended, although the colors are uploaded as 4 floats, which is probably way overkill for most use cases:

```rust
#[derive(RenderResources, Default, Debug, TypeUuid)]
#[uuid = "463e4b8a-d555-4fc2-ba9f-4c880063ba92"]
//#[render_resources(from_self)] //< Removed
//#[repr(C)] //< Doesn't seem necessary
struct ProgressBarUniform {
    back_color: Color,
    fill_color: Color,
    loading_fraction: f32,
}

//unsafe impl Byteable for ProgressBarUniform {} //< Not necessary either (expected)
```

```glsl
layout(set = 2, binding = 0) uniform ProgressBarUniform_back_color {
    vec4 back_color;
};
layout(set = 2, binding = 1) uniform ProgressBarUniform_fill_color {
    vec4 fill_color;
};
layout(set = 2, binding = 2) uniform ProgressBarUniform_loading_fraction {
    float loading_fraction;
};
```

![image](https://user-images.githubusercontent.com/6532395/145681046-91121b82-5c91-41e2-9e30-81fce8e8b5b3.png)
![image](https://user-images.githubusercontent.com/6532395/145681058-c6aac555-0eef-415e-808f-6ccdc42b5c36.png)

**Comment by cart** [comment]
Yeah thats indeed a bit of a nasty situation. The new renderer coming in Bevy 0.6 (replacing the one in Bevy 0.5) doesn't use a the RenderResources derive (we now use a more explicit CPU->GPU data layer that gives users more control), so I'm hoping this will be a non-issue soon.

**Comment by james7132** [comment]
Is this still relevant now that the 0.6 renderer has landed?

**Comment by djeedai** [comment]
I don't think it is no, but I'd ask confirmation from someone with better understanding of the new renderer. @bevyengine/rendering-team ?

**Comment by inodentry** [comment]
I don't think it is. The entire mechanism for how to pass data into shaders has been overhauled since this issue was filed. Even if there turns out to be a similar problem with the new renderer, I think it should be filed as a new issue. Closing.
