### ISSUE TITLE
Build fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by r1walz** [bevyengine/bevy#330]
Bevy requires `alsa` (provided by `libsdl2-dev` on Ubuntu) to be compiled
on Linux based platforms as mention by the following error:

<details>
<summary>Error Log</summary>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit code: 1\n--- stderr\nPackage alsa was not found in the pkg-config search path.\nPerhaps you should add the directory containing `alsa.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'alsa\' found\n"', /home/r1walz/.cargo/registry/src/github.com-1ecc6299db9ec823/alsa-sys-0.1.2/build.rs:4:5
```

</details> 

But I was unable to find this in the docs or anywhere else. Please, investigate and
provide a list of such dependencies for different platforms.

**Comment by multun** [comment]
It's pretty well documented already https://bevyengine.org/learn/book/getting-started/setup/
(there's a link to this page in the readme)

**Comment by karroffel** [comment]
This could probably be made a bit clearer in the README then

**Comment by Zooce** [comment]
I get a similar failure but for `libudev`. The Linux dependencies document does not include either `libudev-dev` or `libsdl2-dev`.

**Comment by alice-i-cecile** [comment]
Documented in [Linux dependencies](https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md) now <3 Credit to @MinerSebas.
