### ISSUE TITLE
Possible to define a system as generic over SystemParam and provide concrete type?

### ISSUE THREAD

**Issue by shelbyd** [bevyengine/bevy#3300]
Here's a minimal example of what I'm trying to do:

```rs
#![allow(dead_code)]

use bevy::prelude::*;
use bevy::ecs::system::SystemParam;

fn main() {
    App::build()
        .add_system(generic_system::<NullImpl>.system())
        .add_system(bound_generic_system.system())
        .run()
}

fn generic_system<T>(t: T) {}
fn bound_generic_system(t: NullImpl) {}

#[derive(SystemParam)]
pub struct NullImpl<'a> {
    marker: Res<'a, ()>,
}
```

AFAIU, the problem is that `generic_system::<NullImpl>` is implicitly binding `NullImpl<'_>`, so that it doesn't satisfy `for<'a>`. I would think it should work if I were able to write something like: `generic_system::<for<'a> NullImpl<'a>>.system()`, but that doesn't parse.

Is there something I can do to make this compile? I've tried to make a non-bevy example to ask the broader Rust community, but I haven't been able to reproduce.

**Comment by DJMcNab** [comment]
Your reasoning that it implicitly binds a concrete version, i.e. the `'static` version is correct

I think one way to work around this would be would be to create a `struct StaticSystemParam<'a, T>(<T as SystemParam<'a>>::Item)` (or whatever the right syntax is)

The alternative is to use `RunSystem` instead, which should work as required.

**Comment by shelbyd** [comment]
I'm looking into how to do this in `0.5.0`. I've tried making a wrapping type with the goal of erasing the lifetime of the normal system param. It looks like even if I were to get it working, rust would still complain. I can't figure out a lifetime to add in the creation of the system that makes rust not complain about the lifetimes. Even adding `'static` doesn't work, because it needs to be `for<'all>`. 

It's possible that there is a doable lifetime change to the `IntoSystem` impls that will let `'static` work.

Also, I don't understand the way the lifetimes work out to reproduce without bevy. If anyone can make a reproduction, I'll ask the broader rust community for help.
