### ISSUE TITLE
Document the exotic double buffered Event system

### ISSUE THREAD

**Issue by MiniaczQ** [bevyengine/bevy#3305]
## How can Bevy's documentation be improved?

[here](https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/src/event.rs#L106)

The term `double buffer` is used.
Although it's not wrong, the way the buffer is read is very different to what's normally done with double buffers.

When reading `Events` we get all the unread events from **both** buffers.

In the most typical case of a double buffer (screen buffer) only a single buffer's data will be available for reading.

I think this should be explicitly stated despite all the hints.

I want to know whether this is a good idea or not.

**Comment by alice-i-cecile** [comment]
I agree; this should be more clearly documented :) And your explanation is correct.
