### ISSUE TITLE
Ability to draw meshes in 2d with the new renderer

### ISSUE THREAD

**Issue by Ixentus** [bevyengine/bevy#3326]
## What problem does this solve or what need does it fill?

Using the old renderer it was possible to draw shapes using meshes with `SpriteBundle`s. However with the new renderer `SpriteBundle`s no longer have `Mesh`es and `Material`s. I've tried to convert them to `PbrBundle`s instead, but nothing gets drawn. This might be because there is no lighting. François said on Discord that custom meshes in 2d are not supported by default anymore.

## What solution would you like?

I'm not sure what the best solution to fix this would be since I'm very new to rendering, but one of the following might do:

* Automatic lighting for 2d
* A new bundle for 2d meshes
* A modified pipeline for 2d

## Additional context

Alternative ways to draw custom shapes also exist. However both `bevy_lyon` and `bevy_svg` also use meshes in their implementations and haven't been updated yet.

**Comment by Nilirad** [comment]
It may be possible that you don't see nothing because of backface culling. In PBR pipeline, the vertex order for a front face is counterclockwise. If you draw shapes clockwise (e.g. using Lyon) you won't see nothing despite the data being present in the GPU.

**Comment by Ixentus** [comment]
> It may be possible that you don't see nothing because of backface culling. In PBR pipeline, the vertex order for a front face is counterclockwise. If you draw shapes clockwise (e.g. using Lyon) you won't see nothing despite the data being present in the GPU.

I tried flipping a mesh a 180 degrees around X, no effect.

**Comment by Weasy666** [comment]
`PbrBundle`s only work with a 3D camera, because a `Mesh` only registers a draw function to `DrawFunctions<Transparent3d>`. At least that is what i have seen so far.

**Comment by cart** [comment]
I think a new Mesh2dBundle is probably the move here. The biggest challenge will be ensuring that it interacts with sprite batches properly (which in practice just means that we need to split sprite batches at the z-index of every non-batched 2d entity ... shouldn't be too hard).

**Comment by cart** [comment]
Fixed by #3460
