### ISSUE TITLE
println seems to prevent proper App exit

### ISSUE THREAD

**Issue by aktaboot** [bevyengine/bevy#3334]
## Issue Encountered:
Trying to exit the game with exit.send(AppExit).
The window closes but the program's process is still running and terminal window hangs.

After removing all println() from the code, the App exits properly.

Code that might help to reproduce :

```rust
fn quit(
    keys: Res<Input<KeyCode>>,
    mut exit: EventWriter<AppExit>
) {
    if keys.pressed(KeyCode::LControl) && keys.pressed(KeyCode::C) {
        println!("Exiting...");
        exit.send(AppExit);
    }
}
```

Bevy 0.5.0
OS: Linux

**Comment by DJMcNab** [comment]
Are you able to reproduce on `main`. I can't point to any specific reason this would fail, and indeed this seems really strange.

Maybe something is holding a lock on `stdout`? Do any of the prints happen?

**Comment by bjorn3** [comment]
For me

```diff
diff --git a/examples/2d/contributors.rs b/examples/2d/contributors.rs
index cefce614..54cb40a9 100644
--- a/examples/2d/contributors.rs
+++ b/examples/2d/contributors.rs
@@ -1,4 +1,4 @@
-use bevy::{prelude::*, utils::HashSet};
+use bevy::{prelude::*, utils::HashSet, app::AppExit};
 use rand::{prelude::SliceRandom, Rng};
 use std::{
     env::VarError,
@@ -15,9 +15,20 @@ fn main() {
         .add_system(move_system)
         .add_system(collision_system)
         .add_system(select_system)
+        .add_system(quit)
         .run();
 }
 
+fn quit(
+    keys: Res<Input<KeyCode>>,
+    mut exit: EventWriter<AppExit>
+) {
+    if keys.pressed(KeyCode::LControl) && keys.pressed(KeyCode::C) {
+        println!("Exiting...");
+        exit.send(AppExit);
+    }
+}
+
 // Store contributors in a collection that preserves the uniqueness
 type Contributors = HashSet<String>;
```

works just fine as of add1818a05ad4b8d4672197afd477ab29f8446b5. What did you do to reproduce it @DJMcNab?

**Comment by aktaboot** [comment]
I couldn't reproduce on another pc !

**Comment by aktaboot** [comment]
> Do any of the prints happen?
Yes they do happen!

This might be a minor issue that I randomly encountered after all !

**Comment by alice-i-cecile** [comment]
I'm going to close this out then: if anyone else encounters this or can reproduce we'll reopen it :)

**Comment by bzar** [comment]
Hi, encountering this as well on Bevy 0.6. Removing `println`s makes my pong exit cleanly, reintroducing them keeps the process running after exit.

**Comment by jakoschiko** [comment]
> The window closes but the program's process is still running and terminal window hangs.
I have the same problem without any println. I'm using Arch Linux and bevy 0.8. Is there an issue that addresses this problem?

**Comment by Bobox214** [comment]
@jakoschiko is it similar to #5524 ?
