### ISSUE TITLE
running examples in CI got a lot slower since using the new renderer

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#3344]
## Bevy version

Latest from main `add1818a05ad4b8d4672197afd477ab29f8446b5`

## Operating system & version

Ubuntu from GitHub actions

## What you did

Run CI

## What you expected to happen

Examples run in an acceptable time (1 mins to build, 8 mins to run)

## What actually happened

As noted by @cart in https://github.com/bevyengine/bevy/pull/3312#issuecomment-993133114, it takes more time to run examples: 1 mins to build, 33 mins to run

## Additional information

Before the merge: https://github.com/bevyengine/bevy/runs/4499607967?check_suite_focus=true
After the merge: https://github.com/bevyengine/bevy/runs/4532054231?check_suite_focus=true

`run-examples` CI should be made faster, or it should run less examples. Ideally it's run time should be around 10 minutes total

**Comment by alice-i-cecile** [comment]
Can we limit running some of the examples based on which code was modified?

**Comment by mockersf** [comment]
I captured a trace in CI: [trace-1639616852.json.zip](https://github.com/bevyengine/bevy/files/7723885/trace-1639616852.json.zip), you can view it in https://ui.perfetto.dev.

It seems the culprit is `present_frames`: It's taking around 600ms each frame.
