### ISSUE TITLE
Reflection allows users to clone arbitrary reflected components, but Reflect does not have a Clone bound

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3372]
## Problem

1. [ReflectComponent::copy_component](https://github.com/bevyengine/bevy/blob/11f52b8c72fc3a568e8bb4a4cd1f3eb025ac2e13/crates/bevy_ecs/src/reflect.rs#L65) allows users to copy any arbitrary component data to different entities, and across worlds, as long as it is reflect-able.
2. Neither `Reflect` nor `Component` has a `Clone` bound, and so we can sneakily clone components that are not expecting to be cloned. I'm pretty sure this is ultimately done by just copying their raw memory.
3. Components are effectively cloned in a way that bypasses the `Clone` method, which can cause issues with things like ref-counting (used for `Handle`).

## Possible Solutions

1. Give `Reflect` and/or `Component` a `Clone` bound. This fixes problem 2, but not problem 3, and may be painful in niche use cases (although I have not seen any concrete use cases for components that cannot be cloned raised, see #1515).

Furthermore, not all fields of a component should be reflected. Cloning components with some cloneable field and defaulting the others is a reasonable strategy here, but does not permit a `Clone` bound.

2. Use the appropriate `Clone` methods when they exist.

3. Leave the existing behavior in place, and very clearly document what's going on and how to use it safely.

**Comment by DJMcNab** [comment]
I believe this copy would happen based on creating a new default, then reflecting the old onto the new

**Comment by alice-i-cecile** [comment]
@mockersf points out that this `Clone`-bypassing behavior is not uniquely isolated to this reflection method.

If we implement both `Serialize` and `Deserialize` for a type (which we need to, for reflection to be useful to store scenes), we can (tediously) clone arbitrary structs, bypassing any limitations. I've documented this behavior in #3366 at least, and I suspect that's *probably* the best we can do.

This does however make me increasingly convinced that we should have either `Reflect: Clone` or `Component: Clone`, as uncloneable structs cannot be reasonably reflected, and almost all components should be both reflected and cloneable.

**Comment by Davier** [comment]
> This does however make me increasingly convinced that we should have either `Reflect: Clone` or `Component: Clone`, as uncloneable structs cannot be reasonably reflected, and almost all components should be both reflected and cloneable.

`FromWorld`, which is a superset of `Default`, is required to use `ReflectComponent`:
<https://github.com/bevyengine/bevy/blob/ed9d45fae57e8f01d13ca3a6c12a5f3005b6c610/crates/bevy_ecs/src/reflect.rs#L81>
<https://github.com/bevyengine/bevy/blob/ed9d45fae57e8f01d13ca3a6c12a5f3005b6c610/crates/bevy_ecs/src/world/mod.rs#L1171-L1175>

**Comment by alice-i-cecile** [comment]
> FromWorld, which is a superset of Default, is required to use ReflectComponent:

Yes, which is a nice feature (although I still like `FromReflect` from #1395). This should avoid unsoundness, but won't save us from logic errors around things like ref-counting. `Handle` for example could easily implement `Default`, but handles cloned in this fashion wouldn't keep assets alive in the proper feature.

**Comment by alice-i-cecile** [comment]
Yeah, this is just an ecosystem-wide "problem". Closing.
