### ISSUE TITLE
Some examples do not work under the new renderer

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#3379]
## Environment

* Bevy version: commit #340957994 (main as of Dec 19 2021)
* OS & graphic stack: ArchLinux kernel 5.15.4; mesa/vulkan-radeon lib: v21.3.1; GPU: AMD ATI Radeon RX 5600

## Bug

The following examples do not render things on screen as expected:
* `shader_material`: Shows a gray screen with 8 green points forming the vertexes of a cube
* `shader_def`: Just show a default gray window
* `shadow_biases`: Shows a very interesting Moiré pattern with very pixelated shadows on the plane
* `wireframe`: I see the default `3d_scene` but the vertexes are a green pixel 

Note: Other examples seem to work as intended.

#### Wireframe

![Screenshot_12-19_10-27](https://user-images.githubusercontent.com/26321040/146670156-093fb397-3fbc-43a9-8f57-27b6b747ba06.png)

#### shader_material

![Screenshot_12-19_10-28](https://user-images.githubusercontent.com/26321040/146670170-4f72ca64-9f56-4d44-8919-5d2014d3cbe1.png)

#### shadow_biases

![Screenshot_12-19_10-30](https://user-images.githubusercontent.com/26321040/146670255-ef65a7bc-ce5e-4073-953b-e8ae4802e17f.png)

More precision. I moved the camera and the shadows look way better. I do not see the same artifacts, though there is still more subtle artifacts such as a black grind on top of the plane.

##### shader_def

just a gray square.

**Comment by Davier** [comment]
The issues with `wireframe`, `shader_material` and `shader_defs` seem to be introduced by #3349

**Comment by nicopap** [comment]
Can confirm, those three examples work on my machine on commit #6eb8e15e3d34f1c4171

**Comment by Davier** [comment]
The issue is that we need to specialize the pipeline for each entity in the `queue_*` functions, I'm working on a fix.
