### ISSUE TITLE
ImageMagick `import` utility causes examples to panic on Linux

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#3380]
## Environment

* Bevy version: commit #340957994 (main as of Dec 19 2021)
* OS & graphic stack: ArchLinux kernel 5.15.4; mesa/vulkan-radeon lib: v21.3.1; GPU: AMD ATI Radeon RX 5600
* imagemagick: 7.1.0.17

## What you did

I attempted to take a screenshot with the `import` utility.

## What you expected to happen

The example would keep running and I get the screenshot.

## What actually happened

Both the `import` utility and the bevy example crash. If I run `import ./some/target.png`, the bevy windows goes black, and as soon as I click a mouse button, `import` stops with the following message:
```
import: unable to read X window image '': Resource temporarily unavailable @ error/xwindow.c/XImportImage/5041.
```

While the example panics with the following message:
```
thread 'main' panicked at 'Failed to acquire next swap chain texture!: Timeout', crates/bevy_render/src/view/window.rs:159:24
```

## Workaround

This doesn't happen with OBS. OBS has a screenshot feature and I used it instead of the `import` utility.

ImageMagick is very dumb, but still this creates a panic, so worth a check...

**Comment by bjorn3** [comment]
Does the same thing happen for the examples of [wgpu](https://github.com/gfx-rs/wgpu)?

**Comment by nicopap** [comment]
The `wgpu` examples do not crash. I tested `shadow`, `water`, `boids`, `mipmap`, `msaa-lines`, `conservative-raster`, `texture-arrays` and `hello-triangle`. The `import` utility works.
