### ISSUE TITLE
Input should perhaps implement the clone method

### ISSUE THREAD

**Issue by thephet** [bevyengine/bevy#3382]
## What problem does this solve or what need does it fill?

I am doing some code that read the keyboard, and then resets it. This is because I am using keys to change between states, and as suggested in the cheat book, you need to reset it. The problem is that you cannot borrow input first to read it, and then mutate it. So for example code like this won't work:
```
        if let Some(key) = keyboard_input.get_pressed().next() {

            match key {
                KeyCode::Left => new_position.x -= 1,
                KeyCode::Right => new_position.x += 1,
                KeyCode::Down => new_position.y -= 1,
                KeyCode::Up => new_position.y += 1,
                _ => (),
            }
            keyboard_input.reset(*key);
        }
```

## What solution would you like?

If we could clone input, I would be able to clone keyboard_input, and thus the previous code would work with a clone.

## What alternative(s) have you considered?

What I have now is code like:
```
        if keyboard_input.just_pressed(KeyCode::Left) {
            new_position.x -= 1;
            keyboard_input.reset(KeyCode::Left);
        }
```

But I think the previous non-working code makes more sense. I also tried to clone the key itself, but it didnt work.

**Comment by alice-i-cecile** [comment]
For newcomers: this is a super easy first issue to implement. Just add the `Clone` derive to https://github.com/bevyengine/bevy/blob/main/crates/bevy_input/src/input.rs#L32, and move the trait bound from the `impl` block below onto `T` in the type itself.

There's no point in implementing `Input` for types where we can't use any of its methods, so those should just be part of the type itself.

**Comment by mockersf** [comment]
I don't think `Input` should implement `Clone` as even though it may make some code easier to write, it doesn't make sense to be able to clone it.

For the situation of the ticket, it has been improved on current main, with method `clear_just_pressed` that will return if a button has been just pressed, and remove it
https://github.com/bevyengine/bevy/blob/340957994dc2c85f7a3ebc5ea6a5ad1b161e0041/crates/bevy_input/src/input.rs#L87-L92

**Comment by thephet** [comment]
But my code needs to know the key pressed, while that function returns bool.

**Comment by alice-i-cecile** [comment]
> I don't think Input should implement Clone as even though it may make some code easier to write, it doesn't make sense to be able to clone it.

Being able to clone iterators is a fairly fundamental quality-of-life issue IMO: it's required by pretty much all of the methods on `itertools` for example, and reducing borrow-checker pain in common user-facing APIs is important.

That said, I had missed that you could generate new copies of `input.get_pressed` (and similar) iterators by calling the methods repeatedly, as they're generated off of the internal `HashMaps` and only take `&self`. That's helpful as a workaround, but makes me feel  like the restriction on `Clone` is particularly silly.

**Comment by mockersf** [comment]
> But my code needs to know the key pressed, while that function returns bool.

Rereading your original scope, the issue is in the lifetimes of your variables, if you scope them differently it should work:
```rust
    let key = keyboard_input.get_pressed().next().cloned();
    if let Some(key) = key {
        match key {
            KeyCode::Left => new_position.x -= 1.0,
            KeyCode::Right => new_position.x += 1.0,
            KeyCode::Down => new_position.y -= 1.0,
            KeyCode::Up => new_position.y += 1.0,
            _ => (),
        }
        keyboard_input.reset(key);
    }
```
By setting up the `key` variable first and cloning it (`KeyCode` derives `Clone`), Rust is able to drop the immutable borrow to `keyboard_input`

**Comment by mockersf** [comment]
by the way, the need to reset input when using it to change between states is when you use one of the methods on [`State`](https://docs.rs/bevy/latest/bevy/ecs/prelude/struct.State.html#implementations), not when you change the state of some of your entities

**Comment by thephet** [comment]
Thanks your code worked!

I changed the state of the game, as in turn_state.set(TurnState::PlayerTurn).unwrap();

**Comment by wilk10** [comment]
Can this be closed?
