### ISSUE TITLE
Add Input::reset_all

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3383]
## What problem does this solve or what need does it fill?

Sometimes, all of the inputs of a given type need to be reset at once.

## What solution would you like?

Add a `Input::reset_all` method.

## What alternative(s) have you considered?

Manually set the `Input<T>` resource to its default value.

E.g.
```rs
*keyboard_input = Input::<KeyCode>::default();
```

## Additional context

Used in a workaround for #1700, as documented in https://bevy-cheatbook.github.io/programming/states.html#with-input

**Comment by mockersf** [comment]
it already exists on main:
https://github.com/bevyengine/bevy/blob/340957994dc2c85f7a3ebc5ea6a5ad1b161e0041/crates/bevy_input/src/input.rs#L118-L122

**Comment by james7132** [comment]
Should we close this? Or do we need `clear` to also clear `pressed` as well?

**Comment by alice-i-cecile** [comment]
You also need to clear pressed, so this isn't a full fix.

**Comment by KDecay** [comment]
Reopening because this got closed by #4410 which is now reverted.
