### ISSUE TITLE
Multi-monitor causing app hanging

### ISSUE THREAD

**Issue by sY9sE33** [bevyengine/bevy#340]
### Bug description
It seems as though some multi-monitor configurations cause bevy to hang.

### What is the expected behavior?
Examples launch

### What is the actual behavior?
(breakout)
![image](https://user-images.githubusercontent.com/9271353/91123794-bc1b0d00-e66b-11ea-8cbf-bb0fa3b20f51.png)
Examples that spawn windows show a blank, unresponsive window that cannot be closed with the window's 'x'

### System configuration 
AMD Ryzen 9 4900HS
NVIDIA RTX 2060 max-Q 452.06/ video bios 90.06.58.40.03
16GB 3200mhz RAM
Pluggable USB-C 4K dock
Windows 10 Pro 1909 - 18363.1016 
Laptop Display resolution - 1920x1080
Monitor 1: ASUS V248QE - 1920x1080 - HDMI
Monitor 2: Benq BL3200PT - 2550x1440 - DP - bottom port in dock
Monitor 3: ASUS V248Q - 1080x1920 (portrait) - DP - top port in dock

### Display combinations
Laptop only ✔️
Laptop + M1 ✔️
Laptop + M2 ❌
Laptop + M3 ✔️
Laptop + M2 + M3 ✔️
Laptop + M1 + M2 ❌
Laptop + M1 + M3 ✔️

### Additional notes
Setting the primary display to displays other than M2 seems to sometimes fix the issue but this is something I'll need to investigate further.

**Comment by fopsdev** [comment]
Encountering a similar if not the same issue:
In addition here is my backtrace if its of any use
```
C:\dev\test\bevy\bevy>cargo run --example breakout
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target\debug\examples\breakout.exe`
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `-2005270523`', C:\Users\fopsd\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.6.2\src\device.rs:2242:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f44c6e4e288e4f49c5c257b2e2cb2ad5918f26a3\/library\std\src\panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/f44c6e4e288e4f49c5c257b2e2cb2ad5918f26a3\/library\std\src\panicking.rs:429
   2: gfx_backend_dx12::device::{{impl}}::bind_buffer_memory
             at C:\Users\fopsd\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.6.2\src\device.rs:2242
   3: wgpu_core::device::Device<gfx_backend_dx12::Backend>::create_buffer<gfx_backend_dx12::Backend>
             at C:\Users\fopsd\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.6.0\src\device\mod.rs:438
   4: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_buffer<wgpu_core::hub::IdentityManagerFactory,gfx_backend_dx12::Backend>
             at C:\Users\fopsd\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.6.0\src\device\mod.rs:969
   5: wgpu::backend::direct::{{impl}}::device_create_buffer
...
...
````

**Comment by alice-i-cecile** [comment]
@sY9sE33, can you reproduce this on Bevy 0.6? There have been several relevant rewrites since this issue was filed.
