### ISSUE TITLE
Validate ButtonSettings and AxisSettings using getter / setter pattern

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3418]
## Problem

AxisSettings and GamepadButtonSettings can easily end up in a nonsensical or broken state, as the values are fully pub.

## Proposed solution

Correctness should be enforced through `get` and `new` methods, and the fields should not be public.

Correctness rules:
1. The ordering must be correct; check the default settings for guidance.
2. All values must be in the appropriate range.

**Comment by mfdorst** [comment]
@alice-i-cecile There doesn't seem to be a type named `GamepadButtonSettings`.

I assume by "nonsensical or broken state" you mean that `negative_low` could be larger than `negative_high`, for instance? Or that any of them could be set to values outside of `[-1.0,1.0]`?

I am not sure what you mean by "the ordering must be correct".

Besides the things I mentioned are there any other rules that should be enforced on those fields?

**Comment by mfdorst** [comment]
What should be done in the event that someone sets one of these to an invalid value? Should it:
1. Silently do nothing (could be very frustrating to debug)
2. Return a `bool` (could still be very frustrating to debug, since most people will not check the return value)
3. Return a `Result` (seems very un-ergonomic for an operation that will _usually_ either always succeed or always fail)
4. Panic (Could be quite frustrating if there is say, a slider in the game so the end-user can choose the value they want - in that case returning a Result seems better)
5. Panic by default, but have `_try` variants of each setter which return `Result` (Best of 3 and 4 I think)

**Comment by mfdorst** [comment]
Are we sure this is a good idea in the first place? I have not seen a lot of getter/setter patterns in Rust. It's a very OOP kind of thing to do, and as far as I know it is not considered idiomatic rust. Here is a redit thread on the topic: https://www.reddit.com/r/rust/comments/d7w6n7/is_it_idiomatic_to_write_setters_and_getters/

**Comment by mfdorst** [comment]
The names of `negative_high` and `negative_low` are very confusing. One would expect `negative_high` to be the highest negative value before rounding up to `0.0` and `negative_low` to be the lowest negative value before rounding down to `-1.0`, but they are reversed. `negative_high` is lower (lesser) than `negative_low`. Should this be addressed or left as-is?

**Comment by alice-i-cecile** [comment]
> There doesn't seem to be a type named GamepadButtonSettings.

My apologies, the type is named `ButtonSettings`. Could you follow suite and update #3446 to include that type as well?

> I assume by "nonsensical or broken state" you mean that negative_low could be larger than negative_high, for instance? Or that any of them could be set to values outside of [-1.0,1.0]?
> I am not sure what you mean by "the ordering must be correct".
> Besides the things I mentioned are there any other rules that should be enforced on those fields?
There are two rules to enforce:

- All values must be in `[-1.0, 1,0]` 
- `negative_high < negative_low <= 0.0 <= positive_low < positive_high`

For `ButtonSettings` this becomes:
- All values must be in `[0.0, 1,0]` 
- `pressed >= released`

**Comment by alice-i-cecile** [comment]
> What should be done in the event that someone sets one of these to an invalid value?

I think my preference would to have two versions of each setter method. The first group, called `set_negative_low_threshold` etc, should be infallible, altering the values as necessary to ensure that things work properly, returning the value that was actually applied.

The second set, called `try_set_negative_low_threshold` and so on, should be fallible and return a result.

**Comment by alice-i-cecile** [comment]
> The names of negative_high and negative_low are very confusing. One would expect negative_high to be the highest negative value before rounding up to 0.0 and negative_low to be the lowest negative value before rounding down to -1.0, but they are reversed. negative_high is lower (lesser) than negative_low. Should this be addressed or left as-is?

Agreed on the confusion. The "high" and "low" here refer to the absolute value, so they shouldn't be swapped. Let's see if we can find some better names...

So what they're doing here is controlling when we round to the extreme values, and creating a "deadzone" around zero 🤔 I think I like:

1. `positive_low` / `negative_low` => `positive_deadzone_threshold` / `negative_deadzone_threshold`
2. `postive_high` / `negative_high` => `positive_end_of_livezone` / `negative_end_of_livezone`

**Comment by mfdorst** [comment]
@alice-i-cecile it looks like this is a public facing API. Is it okay to just go changing stuff around like this? Do I need to document it somewhere (other than on the types themselves)?

**Comment by mfdorst** [comment]
@alice-i-cecile Those names are certainly better. I was also thinking maybe:
`positive_high` => `livezone_upperbound`
`positive_low` => `deadzone_upperbound`
`negative_low` => `deadzone_lowerbound`
`negative_high` => `livezone_lowerbound`

Those names make sense to me, but not everyone thinks like me. If you prefer your names I'll stick with those.

**Comment by mfdorst** [comment]
Since users won't now be able to create structs directly i.e. `ButtonSettings { press: 0.5, release: 0.4 }`, I think we should add `new` methods for both types. Otherwise the ergonomics of setting your own defaults become worse:
```rust
let mut button_settings = ButtonSettings::default();
button_settings.set_release_threshold(0.4);
button_settings.set_press_threshold(0.5);
```
vs
```rust
let button_settings = ButtonSettings::new(0.5, 0.4);
```
Of course, this begs the question, how would one handle the error case of `ButtonSettings::new(0.4, 0.5)` (not allowed)?

1. `new` returns `Result<ButtonSettings>`
2. `new` returns `Option<ButtonSettings>`
3. `new` returns `ButtonSettings` but panics on bad input
4. `new` returns `ButtonSettings` but returns `ButtonSettings::default()` on bad input

**Comment by alice-i-cecile** [comment]
> Is it okay to just go changing stuff around like this? Do I need to document it somewhere (other than on the types themselves)?

Yep! Bevy is explicitly unstable (for now), so that we can fix these things. I'll add the `Needs-Migration-Guide` label to your PR so it can be added to the big change log.

>  I think we should add new methods for both types.

Agreed!

> new returns Result<ButtonSettings>

I like this one best. Explicitly constructing these should be rare enough that I'm okay with forcing error handling.

**Comment by mfdorst** [comment]
@alice-i-cecile Cool. Yeah and if you know the values will work you can do `ButtonSettings::new(0.5, 0.4).unwrap()` which is still fairly ergonomic.
