### ISSUE TITLE
Panic in font_atlas_set.rs

### ISSUE THREAD

**Issue by 7h3qu1rkyb1t** [bevyengine/bevy#343]
**System**

- Linux 64 bit
- Wayland (sway)

**Description**

On Running 

> Cargo  run --features wayland --example breakout
> INTEL-MESA: warning: Haswell Vulkan support is incomplete
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/bevy_text/src/font_atlas_set.rs:53:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

On x11 client it is working fine. (tested on i3wm)

**Debug**
> examples(master)$ RUST_BACKTRACE=1 cargo run --features wayland --example breakout
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
     Running `/home/gireesh/Trash/bevy/target/debug/examples/breakout`
INTEL-MESA: warning: Haswell Vulkan support is incomplete
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/bevy_text/src/font_atlas_set.rs:53:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5180f3da5fd72627a8d38558ad1297df38793acd/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/5180f3da5fd72627a8d38558ad1297df38793acd/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/5180f3da5fd72627a8d38558ad1297df38793acd/library/core/src/panicking.rs:50
   3: core::option::Option<T>::unwrap
             at /home/gireesh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:370
   4: bevy_text::font_atlas_set::FontAtlasSet::add_glyphs_to_atlas
             at /home/gireesh/Trash/bevy/crates/bevy_text/src/font_atlas_set.rs:53
   5: bevy_ui::widget::text::text_system
             at /home/gireesh/Trash/bevy/crates/bevy_ui/src/widget/text.rs:40
   6: core::ops::function::Fn::call
             at /home/gireesh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:70
   7: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /home/gireesh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:247
   8: <Func as bevy_ecs::system::into_system::IntoQuerySystem<(),(Ra,Rb,Rc,Rd),(A,)>>::system::{{closure}}
             at /home/gireesh/Trash/bevy/crates/bevy_ecs/src/system/into_system.rs:186
   9: <bevy_ecs::system::into_system::SystemFn<State,F,ThreadLocalF,Init,SetArchetypeAccess> as bevy_ecs::system::system::System>::run
             at /home/gireesh/Trash/bevy/crates/bevy_ecs/src/system/into_system.rs:61
  10: bevy_ecs::schedule::parallel_executor::ExecutorStage::run_ready_systems::{{closure}}
             at /home/gireesh/Trash/bevy/crates/bevy_ecs/src/schedule/parallel_executor.rs:313
  11: rayon_core::scope::ScopeFifo::spawn_fifo::{{closure}}::{{closure}}
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/scope/mod.rs:495
  12: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/gireesh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:308
  13: std::panicking::try::do_call
             at /home/gireesh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:373
  14: __rust_try
  15: std::panicking::try
             at /home/gireesh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:337
  16: std::panic::catch_unwind
             at /home/gireesh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:379
  17: rayon_core::unwind::halt_unwinding
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/unwind.rs:17
  18: rayon_core::scope::ScopeBase::execute_job_closure
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/scope/mod.rs:561
  19: rayon_core::scope::ScopeBase::execute_job
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/scope/mod.rs:549
  20: rayon_core::scope::ScopeFifo::spawn_fifo::{{closure}}
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/scope/mod.rs:495
  21: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/job.rs:167
  22: rayon_core::job::JobRef::execute
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/job.rs:59
  23: <rayon_core::job::JobFifo as rayon_core::job::Job>::execute
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/job.rs:211
  24: rayon_core::job::JobRef::execute
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/job.rs:59
  25: rayon_core::registry::WorkerThread::execute
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/registry.rs:753
  26: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/registry.rs:730
  27: rayon_core::registry::WorkerThread::wait_until
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/registry.rs:704
  28: rayon_core::registry::main_loop
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/registry.rs:837
  29: rayon_core::registry::ThreadBuilder::run
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/registry.rs:56
  30: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /home/gireesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.8.0/src/registry.rs:101
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by cart** [comment]
This is actually expected behavior. The example adds characters to an atlas until it runs out of space (not the message that indicates that the atlas has run out of space). I guess capturing the error and failing gracefully would be better.

**Comment by 7h3qu1rkyb1t** [comment]
> This is actually expected behavior. The example adds characters to an atlas until it runs out of space (note the message that indicates that the atlas has run out of space). I guess capturing the error and failing gracefully would be better.

Why it is happening only in Wayland?

**Comment by 7h3qu1rkyb1t** [comment]
Solved:
sorry to it was kind of my fault. while running examples i have to be in bevy root directory. I was running it from examples directory that was causing this issue.
