### ISSUE TITLE
Check for for missing back-ticks in doc links in CI

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3435]
Unfortunately, docs.rs renders [Foo] and [\`Foo\`] differently. https://cdn.discordapp.com/attachments/743559241461399582/924406539584942100/unknown.png

We want the latter, and our CI should check for this.

**Comment by DJMcNab** [comment]
Image inline: 
![image](https://user-images.githubusercontent.com/36049421/147394222-817ec9c5-0c8e-47db-9f67-4cf0f435d521.png)

**Comment by mfdorst** [comment]
@alice-i-cecile is there a clippy config file somewhere? We don't seem to have a `clippy.toml`.

**Comment by mfdorst** [comment]
Nevermind, I guess we don't need one

**Comment by mockersf** [comment]
There isn't one yet

For this ticket there is this pedanting lint in clippy: https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown

**Comment by mfdorst** [comment]
Might this be a good moment to add a `clippy.toml`? That way one doesn't have to remember all of
```
cargo clippy -- -D warnings -A clippy::type_complexity -W clippy::doc_markdown
```
you should be able to just run `cargo clippy` right?

**Comment by mfdorst** [comment]
[I was wrong](https://github.com/rust-lang/rust-clippy/issues/1313). `clippy.toml` does not provide a way to turn lints on or off. They must be passed at the command line.

**Comment by mockersf** [comment]
yup that's why there is the `ci` package so that people can run `cargo run -p ci` to use the lints Bevy wants
