### ISSUE TITLE
bevy_crevice derive macro doesn't work properly in external crate

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3436]
## Bevy version

`main`

## Proplem

The `bevy_crevice_path` macro returns the `render_resource` path segment two times if one uses the `bevy_derive` macros in a local project.

## Proposed patch

```rust
diff --git a/crates/bevy_crevice/bevy-crevice-derive/src/lib.rs b/crates/bevy_crevice/bevy-crevice-derive/src/lib.rs
index e0cc77a8..421c4aa9 100644
--- a/crates/bevy_crevice/bevy-crevice-derive/src/lib.rs
+++ b/crates/bevy_crevice/bevy-crevice-derive/src/lib.rs

@@ -47,14 +47,17 @@ fn bevy_crevice_path() -> Path {
                 segments,
             }
         })
-        .or_else(|| bevy_manifest.maybe_get_path(crate::BEVY_RENDER))
-        .map(|bevy_render_path| {
-            let mut segments = bevy_render_path.segments;
-            segments.push(BevyManifest::parse_str("render_resource"));
-            Path {
-                leading_colon: None,
-                segments,
-            }
+        .or_else(|| {
+            bevy_manifest
+                .maybe_get_path(crate::BEVY_RENDER)
+                .map(|bevy_render_path| {
+                    let mut segments = bevy_render_path.segments;
+                    segments.push(BevyManifest::parse_str("render_resource"));
+                    Path {
+                        leading_colon: None,
+                        segments,
+                    }
+                })
         })
         .unwrap_or_else(|| bevy_manifest.get_path(crate::BEVY_CREVICE))
 }
```

## Additional information

Submitted on behalf of a user on [Discord](https://discord.com/channels/691052431525675048/924430606966849596/924430795026870272).

**Comment by DJMcNab** [comment]
@alice-i-cecile I know you're the ticketmain, but you are also allowed to create pull requests

That would make this proposed patch easier to review

Fwiw, I'm surprised by this patch; I'd expect the fix to be making the `bevy::render::render_resources` which the `map` is operating on be just `bevy::render`

But again, I can't review it easily on mobile, so it's challenging to check my assumptions there.

**Comment by DJMcNab** [comment]
As I mentioned on discord (in the linked thread) the correct fix is to just delete line 44 (I think), as explained above.

I'm not too bothered about attribution for that fix, but can create a pr if no-one else does before I get around to it.

**Comment by mockersf** [comment]
oh I was testing that fix locally too @DJMcNab 👍
