### ISSUE TITLE
Add `Cone` and `Cylinder` shapes to `bevy_render::mesh::shape`

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#3456]
## What problem does it solve

I plan to create a debug shape bevy plugin. It would simply just spawns meshes with a special line drawing shader. But currently the default mesh library in bevy is very limited, I would have to implement separately a few of even the most basic shapes! The Bevy `shape` module misses such basic shapes as a cylinder or cone.

## What solution would you like?

I already have working implementation of algorithms to compute cylinder and cone vertices and edges ([in the heron debug view implementation](https://github.com/jcornaz/heron/blob/main/debug/src/shape3d_wireframe.rs))

I only suggest that I personally port those to the bevy shape module. But I first want to know if the addition is welcome, so that it doesn't turn into wasted efforts.

## What alternative(s) have you considered?

The other solution is simply that everyone copy the cylinder and cone mesh generation algorithms when they need it. For me it's not a problem given I already did this. But I don't see why the torus gets a pass and not cylinders!

## Additional context

Future additions could include a rounded cuboid or arbitrary convex vertex collections. But that's not on the radar currently.

**Comment by mockersf** [comment]
there has been a lot of discutions around shapes in https://github.com/bevyengine/rfcs/pull/12
