### ISSUE TITLE
Lights don't respect RenderLayer

### ISSUE THREAD

**Issue by HackerFoo** [bevyengine/bevy#3462]
## What problem does this solve or what need does it fill?

From manko [on Discord](https://discord.com/channels/691052431525675048/924727274958381116/925369774886772796): "by the way, is there a way to make light sources not affect some meshes? I'm noticed RenderLayers does not affect light sources and the lights are shared between my worlds, which is mildly annoying"

Also encountered in https://github.com/bevyengine/bevy/pull/3412

## What solution would you like?

`RenderLayers` control visibility of lights as they do for other entities.

**Comment by dcz-self** [comment]
I reported this, for the record. Tested on 0.5.0, and with 80% certainty that I didn't mess up anything.

**Comment by asafigan** [comment]
I ran into this issue when working on my Bevy Jam 2 submission. I would be willing to work on this but I would probably need help because I have only done some basics graphic programming mostly in OpenGL.

**Comment by alice-i-cecile** [comment]
Checking in just before the launch of Bevy 0.10; this is still an issue.
