### ISSUE TITLE
Scene reloading does not work on windows.

### ISSUE THREAD

**Issue by shelbyd** [bevyengine/bevy#348]
This can be reproduced with the "scene" example.

## Reproduction
Clone bevy repo.
Run `cargo run --example scene`.
Change property `x` of entity `328997855` from `3.0` to `5.0`.
Save the file.

## Expected
Console message indicating the value was changed.

## Actual
No console message.

## Extra Info
Commit tested: 9aff0bcc2a8a39beda159f81bd7e8729f38f9773
Windows version: 10.0.18362 Build 18362

**Comment by Xavientois** [comment]
Same behaviour is occurring for me on mac.

### Extra Info
macOS 10.14.2

**Comment by DJMcNab** [comment]
This can be fixed by changing
https://github.com/bevyengine/bevy/blob/63fd4ae33324e1720d2b473f3619cf314b7a7044/crates/bevy_asset/src/asset_server.rs#L201
to
```rust
 kind: EventKind::Modify(_),
```
but I haven't tested for unintended consequences yet.
