### ISSUE TITLE
Document how to mock user input

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3494]
## How can Bevy's documentation be improved?

Simulating user input for use in tests is very important, but it's not always obvious how to do so.

We should document how to do this in two different places:

1. The root `tests` directory, as part of an integration test.
2. In a doc example in each of the input methods.

A user provided the following example for touch input, which should be helpful to get started.

```rust
pub fn mock_touch(
    mouse: Res<Input<MouseButton>>,
    windows: Res<Windows>,
    mut touch_events: EventWriter<TouchInput>,
) {
    let window = windows.get_primary().unwrap();
    let touch_phase = if mouse.just_pressed(MouseButton::Left) {
        Some(TouchPhase::Started)
    } else if mouse.just_released(MouseButton::Left) {
        Some(TouchPhase::Ended)
    } else if mouse.pressed(MouseButton::Left) {
        Some(TouchPhase::Moved)
    } else {
        None
    };
    if let (Some(phase), Some(cursor_pos)) = (touch_phase, window.cursor_position()) {
        touch_events.send(TouchInput {
            phase: phase,
            position: cursor_pos,
            force: None,
            id: 0,
        })
    }
    ```

**Comment by mockersf** [comment]
There is already an example in the tests for keyboard input:
https://github.com/bevyengine/bevy/blob/d8d3fdf2cfa53c511e8e8156fe1c8a749a20f159/tests/how_to_test_systems.rs#L79-L81

**Comment by alice-i-cecile** [comment]
Closing as redundant to #2896.
