### ISSUE TITLE
Rendering two 3d passes to the same window only shows the last pass when MSAA is enabled

### ISSUE THREAD

**Issue by HackerFoo** [bevyengine/bevy#3499]
## Bevy version

https://github.com/HackerFoo/bevy/tree/two_passes_main

## Operating system & version

MacOS 12.1

## What you did

This will show a red and a green cube spinning:

    cargo run --example two_passes

Setting the MSAA samples to 4 will only show one cube.

**Comment by HackerFoo** [comment]
It looks like the clear pass is creating two separate attachments that are being fed through the two passes in parallel instead of combining them when using MSAA. This doesn't happen when MSAA is disabled.

From the Metal debugger:
<img width="1101" alt="Screen Shot 2022-01-03 at 18 08 12" src="https://user-images.githubusercontent.com/1069462/148000367-ef69b9a6-77de-408d-8d3f-e18209ceb203.png">

<img width="652" alt="Screen Shot 2022-01-03 at 18 11 14" src="https://user-images.githubusercontent.com/1069462/148000458-92065d82-270e-46be-bee7-6685c9cea52e.png">

**Comment by HackerFoo** [comment]
The bug seems to be in how the resolve textures are handled; the same texture should be used for both passes. Changing the test on this line to `true` gives the intended behavior: https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/texture/texture_cache.rs#L44

**Comment by superdump** [comment]
@HackerFoo can this be closed since the camera-driven rendering PR was merged? I don't remember if it addressed MSAA or not.

**Comment by HackerFoo** [comment]
Does MSAA work with multiple passes on main?

**Comment by cart** [comment]
> Does MSAA work with multiple passes on main?

It does, but it isn't configurable per-pass yet (still a global). Given that this issue isn't talking about that, I think we can close it.
