### ISSUE TITLE
Strange behaviour while rendering sprite with PNG texture

### ISSUE THREAD

**Issue by antonKalinin** [bevyengine/bevy#350]
First, thanks for this project!

I am trying to create a parallax background, so I started from [this 2d sprite example](https://github.com/bevyengine/bevy/blob/master/examples/2d/sprite.rs) and then changed the PNG image to my one. 
But my one is not rendering property:

![image](https://user-images.githubusercontent.com/3993255/91270170-e7435080-e780-11ea-96f2-e9f123d8c717.png)

Though image itself looks fine:

![image](https://user-images.githubusercontent.com/3993255/91270267-0c37c380-e781-11ea-9ea8-e0cfc3851684.png)

I don't know is it bug or I am just missing something, so I would label it as a question.
Can you help me to understand where I need to dig to?

**Comment by sunwukonga** [comment]
I ran `examples/2d/sprites.rs` with your image and the result was:
![screenshot_result](https://user-images.githubusercontent.com/12194690/91372221-a5301280-e845-11ea-89d2-7643fa954f55.png)

**Comment by antonKalinin** [comment]
Yeah, I did some changes in system including updating MacOS to latest and restarting everything and now I also have good render result. @sunwukonga thanks for testing. Something strange was with my case, but looks like it is not engine problem, so closing this issue.
