### ISSUE TITLE
Handle<T>::as_weak() takes a type U which is potentially bad

### ISSUE THREAD

**Issue by colepoirier** [bevyengine/bevy#3522]
On discord <https://discord.com/channels/691052431525675048/749332104487108618/927078698035855420> while working on documenting bevy_assets @manokara noticed Handle<T>::as_weak() takes a type U and wondered if "the handle would be invalid if U is different from T?"

@mockersf noted that "there's one place where that is used to convert a Handle<Font> to a Handle<FontAtlasSet>," and upon further investigation concluded that "the FontAtlasSet asset storage is handled manually, to have its handles in sync with fonts."

@mockersf said that this is "potentially bad and would require more thinking to improve," so I have created this issue to see what others think of the degree to which this is potentially bad and be a starting point for discussions of how to improve this.

**Comment by mockersf** [comment]
https://github.com/bevyengine/bevy/blob/ffecb05a0ab423b46ab991b49c54516bcaf2ea7b/crates/bevy_text/src/glyph_brush.rs#L99
In this line a `Handle<Font>` is changed to a `Handle<FontAtlasSet>`. This is used for easy correspondence between fonts assets and font atlas assets as they share the same handle

**Comment by manokara** [comment]
> This is used for easy correspondence between fonts assets and font atlas assets as they share the same handle

Indeed. But since this is the only use case for it, I think what this method needs is a new name to make its intent more clear: `transmute`. And for correctness, if the handle id is `HandleId::Id` we should update the type uuid as well to match `U`'s.

**Comment by cart** [comment]
Imo we should avoid `transmute` for the sole reason that it is a "dirty word" in Rust generally indicating gross unsafety.

I do think its worth trying to sort out a way to make font atlas set UX reasonable without requiring handle casting.

**Comment by manokara** [comment]
> Imo we should avoid transmute for the sole reason that it is a "dirty word" in Rust generally indicating gross unsafety.

I have renamed it to `cast` in #3536, which is what it does and it's not as unsafe as something like `transmute` would imply.

> I do think its worth trying to sort out a way to make font atlas set UX reasonable without requiring handle casting.

Yeah. Since this is currently the only use case for that method, I think there's two ways we could go about this:

1) Make handle casting idiomatic and encourage that pattern if different assets share the same logic or "working space".
2) Remove the method and rework font atlas UX as cart said.

And then we should probably rename this issue accordingly.

**Comment by james7132** [comment]
I can't find `Handle::as_weak` or `Handle::cast_weak` anymore. Likely was removed as a part of #8624. Closing this out.
