### ISSUE TITLE
breakout example from cargo new my_breakout : `Component` is imported here, but it is only a trait, without a derive macro

### ISSUE THREAD

**Issue by pyweeker** [bevyengine/bevy#3529]
hi,

i am beginner, 
this works : cargo run --example breakout
this doesn't :
cargo new my_breakout
cd my_breakout
cargo run
===>
error: cannot find derive macro `Component` in this scope
  --> src/main.rs:27:10
   |
27 | #[derive(Component)]
   |          ^^^^^^^^^

error: cannot find derive macro `Component` in this scope
  --> src/main.rs:32:10
   |
32 | #[derive(Component)]
   |          ^^^^^^^^^

error: cannot find derive macro `Component` in this scope
  --> src/main.rs:37:10
   |
37 | #[derive(Component)]
   |          ^^^^^^^^^

error[E0599]: no function or associated item named `new` found for struct `bevy::prelude::App` in the current scope
  --> src/main.rs:10:10
   |
10 |     App::new()
   |          ^^^ function or associated item not found in `bevy::prelude::App`

error[E0277]: the trait bound `for<'r, 's, 't0, 't1> fn(bevy::prelude::Res<'r, bevy::prelude::Input<bevy::prelude::KeyCode>>, bevy::prelude::Query<'s, (&'t0 Paddle, &'t1 mut bevy::prelude::Transform)>) {paddle_movement_system}: From<for<'r, 's, 't0, 't1> fn(bevy::prelude::Res<'r, bevy::prelude::Input<bevy::prelude::KeyCode>>, bevy::prelude::Query<'s, (&'t0 Paddle, &'t1 mut bevy::prelude::Transform)>) {paddle_movement_system}>` is not satisfied
  --> src/main.rs:18:30
   |
18 |                 .with_system(paddle_movement_system)
   |                  ----------- ^^^^^^^^^^^^^^^^^^^^^^ expected an implementor of trait `From<for<'r, 's, 't0, 't1> fn(bevy::prelude::Res<'r, bevy::prelude::Input<bevy::prelude::KeyCode>>, bevy::prelude::Query<'s, (&'t0 Paddle, &'t1 mut bevy::prelude::Transform)>) {paddle_movement_system}>`
   |                  |
   |                  required by a bound introduced by this call
   |
   = note: required because of the requirements on the impl of `From<for<'r, 's, 't0, 't1> fn(bevy::prelude::Res<'r, bevy::prelude::Input<bevy::prelude::KeyCode>>, bevy::prelude::Query<'s, (&'t0 Paddle, &'t1 mut bevy::prelude::Transform)>) {paddle_movement_system}>` for `SystemDescriptor`
   = note: required because of the requirements on the impl of `Into<SystemDescriptor>` for `for<'r, 's, 't0, 't1> fn(bevy::prelude::Res<'r, bevy::prelude::Input<bevy::prelude::KeyCode>>, bevy::prelude::Query<'s, (&'t0 Paddle, &'t1 mut bevy::prelude::Transform)>) {paddle_movement_system}`
help: consider borrowing here
   |
18 |                 .with_system(&paddle_movement_system)
   |                              +
18 |                 .with_system(&mut paddle_movement_system)
   |                              ++++

error[E0277]: the trait bound `for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5> fn(bevy::prelude::Commands<'r>, bevy::prelude::ResMut<'s, Scoreboard>, bevy::prelude::Query<'t0, (&'t1 mut Ball, &'t2 bevy::prelude::Transform)>, bevy::prelude::Query<'t3, (bevy::prelude::Entity, &'t4 Collider, &'t5 bevy::prelude::Transform)>) {ball_collision_system}: From<for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5> fn(bevy::prelude::Commands<'r>, bevy::prelude::ResMut<'s, Scoreboard>, bevy::prelude::Query<'t0, (&'t1 mut Ball, &'t2 bevy::prelude::Transform)>, bevy::prelude::Query<'t3, (bevy::prelude::Entity, &'t4 Collider, &'t5 bevy::prelude::Transform)>) {ball_collision_system}>` is not satisfied
  --> src/main.rs:19:30
   |
19 |                 .with_system(ball_collision_system)
   |                  ----------- ^^^^^^^^^^^^^^^^^^^^^ expected an implementor of trait `From<for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5> fn(bevy::prelude::Commands<'r>, bevy::prelude::ResMut<'s, Scoreboard>, bevy::prelude::Query<'t0, (&'t1 mut Ball, &'t2 bevy::prelude::Transform)>, bevy::prelude::Query<'t3, (bevy::prelude::Entity, &'t4 Collider, &'t5 bevy::prelude::Transform)>) {ball_collision_system}>`
   |                  |
   |                  required by a bound introduced by this call
   |
   = note: required because of the requirements on the impl of `From<for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5> fn(bevy::prelude::Commands<'r>, bevy::prelude::ResMut<'s, Scoreboard>, bevy::prelude::Query<'t0, (&'t1 mut Ball, &'t2 bevy::prelude::Transform)>, bevy::prelude::Query<'t3, (bevy::prelude::Entity, &'t4 Collider, &'t5 bevy::prelude::Transform)>) {ball_collision_system}>` for `SystemDescriptor`
   = note: required because of the requirements on the impl of `Into<SystemDescriptor>` for `for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5> fn(bevy::prelude::Commands<'r>, bevy::prelude::ResMut<'s, Scoreboard>, bevy::prelude::Query<'t0, (&'t1 mut Ball, &'t2 bevy::prelude::Transform)>, bevy::prelude::Query<'t3, (bevy::prelude::Entity, &'t4 Collider, &'t5 bevy::prelude::Transform)>) {ball_collision_system}`
help: consider borrowing here
   |
19 |                 .with_system(&ball_collision_system)
   |                              +
19 |                 .with_system(&mut ball_collision_system)
   |                              ++++

error[E0277]: the trait bound `for<'r, 's, 't0> fn(bevy::prelude::Query<'r, (&'s Ball, &'t0 mut bevy::prelude::Transform)>) {ball_movement_system}: From<for<'r, 's, 't0> fn(bevy::prelude::Query<'r, (&'s Ball, &'t0 mut bevy::prelude::Transform)>) {ball_movement_system}>` is not satisfied
  --> src/main.rs:20:30
   |
20 |                 .with_system(ball_movement_system),
   |                  ----------- ^^^^^^^^^^^^^^^^^^^^ expected an implementor of trait `From<for<'r, 's, 't0> fn(bevy::prelude::Query<'r, (&'s Ball, &'t0 mut bevy::prelude::Transform)>) {ball_movement_system}>`
   |                  |
   |                  required by a bound introduced by this call
   |
   = note: required because of the requirements on the impl of `From<for<'r, 's, 't0> fn(bevy::prelude::Query<'r, (&'s Ball, &'t0 mut bevy::prelude::Transform)>) {ball_movement_system}>` for `SystemDescriptor`
   = note: required because of the requirements on the impl of `Into<SystemDescriptor>` for `for<'r, 's, 't0> fn(bevy::prelude::Query<'r, (&'s Ball, &'t0 mut bevy::prelude::Transform)>) {ball_movement_system}`
help: consider borrowing here
   |
20 |                 .with_system(&ball_movement_system),
   |                              +
20 |                 .with_system(&mut ball_movement_system),
   |                              ++++

error[E0560]: struct `bevy::prelude::Sprite` has no field named `color`
  --> src/main.rs:63:17
   |
63 |                 color: Color::rgb(0.5, 0.5, 1.0),
   |                 ^^^^^ `bevy::prelude::Sprite` does not have this field
   |
   = note: available fields are: `size`, `flip_x`, `flip_y`, `resize_mode`

error[E0560]: struct `bevy::prelude::Sprite` has no field named `color`
  --> src/main.rs:79:17
   |
79 |                 color: Color::rgb(1.0, 0.5, 0.5),
   |                 ^^^^^ `bevy::prelude::Sprite` does not have this field
   |
   = note: available fields are: `size`, `flip_x`, `flip_y`, `resize_mode`

error[E0560]: struct `bevy::prelude::Sprite` has no field named `color`
   --> src/main.rs:136:17
    |
136 |                 color: wall_color,
    |                 ^^^^^ `bevy::prelude::Sprite` does not have this field
    |
    = note: available fields are: `size`, `flip_x`, `flip_y`, `resize_mode`

error[E0560]: struct `bevy::prelude::Sprite` has no field named `color`
   --> src/main.rs:151:17
    |
151 |                 color: wall_color,
    |                 ^^^^^ `bevy::prelude::Sprite` does not have this field
    |
    = note: available fields are: `size`, `flip_x`, `flip_y`, `resize_mode`

error[E0560]: struct `bevy::prelude::Sprite` has no field named `color`
   --> src/main.rs:166:17
    |
166 |                 color: wall_color,
    |                 ^^^^^ `bevy::prelude::Sprite` does not have this field
    |
    = note: available fields are: `size`, `flip_x`, `flip_y`, `resize_mode`

error[E0560]: struct `bevy::prelude::Sprite` has no field named `color`
   --> src/main.rs:181:17
    |
181 |                 color: wall_color,
    |                 ^^^^^ `bevy::prelude::Sprite` does not have this field
    |
    = note: available fields are: `size`, `flip_x`, `flip_y`, `resize_mode`

error[E0560]: struct `bevy::prelude::Sprite` has no field named `color`
   --> src/main.rs:209:25
    |
209 |                         color: brick_color,
    |                         ^^^^^ `bevy::prelude::Sprite` does not have this field
    |
    = note: available fields are: `size`, `flip_x`, `flip_y`, `resize_mode`

error[E0308]: mismatched types
   --> src/main.rs:228:9
    |
228 |     let (paddle, mut transform) = query.single_mut();
    |         ^^^^^^^^^^^^^^^^^^^^^^^   ------------------ this expression has type `Result<(&Paddle, Mut<'_, bevy::prelude::Transform>), QuerySingleError>`
    |         |
    |         expected enum `Result`, found tuple
    |
    = note: expected enum `Result<(&Paddle, Mut<'_, bevy::prelude::Transform>), QuerySingleError>`
              found tuple `(_, _)`

error[E0308]: mismatched types
   --> src/main.rs:246:9
    |
246 |     let (ball, mut transform) = ball_query.single_mut();
    |         ^^^^^^^^^^^^^^^^^^^^^   ----------------------- this expression has type `Result<(&Ball, Mut<'_, bevy::prelude::Transform>), QuerySingleError>`
    |         |
    |         expected enum `Result`, found tuple
    |
    = note: expected enum `Result<(&Ball, Mut<'_, bevy::prelude::Transform>), QuerySingleError>`
              found tuple `(_, _)`

error[E0609]: no field `sections` on type `Result<Mut<'_, bevy::prelude::Text>, QuerySingleError>`
   --> src/main.rs:252:10
    |
252 |     text.sections[1].value = format!("{}", scoreboard.score);
    |          ^^^^^^^^

error[E0308]: mismatched types
   --> src/main.rs:261:9
    |
261 |     let (mut ball, ball_transform) = ball_query.single_mut();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^   ----------------------- this expression has type `Result<(Mut<'_, Ball>, &bevy::prelude::Transform), QuerySingleError>`
    |         |
    |         expected enum `Result`, found tuple
    |
    = note: expected enum `Result<(Mut<'_, Ball>, &bevy::prelude::Transform), QuerySingleError>`
              found tuple `(_, _)`

Some errors have detailed explanations: E0277, E0308, E0560, E0599, E0609.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `breakout` due to 18 previous errors

=====> i read this : [Verified: not a bug]Importing a macro and a trait with the exact same name, potential compiler bug?
so i tried that , not working : 
//use bevy::{Component};
//use bevy::ecs::{Component};
//use bevy::ecs::{component};
//use bevy::{component};

//use bevy::ecs::component::{Component};

===>
What can i do to duplicate breakout game strating from cargo new my_breakout command ?

**Comment by DJMcNab** [comment]
I think that you are using version 0.5 of bevy with the example from `main`?

Your version of bevy and the version which the example was made for need to match. That is, if you wish to use 0.5, you should use examples from https://github.com/bevyengine/bevy/tree/latest instead of from `main`. If you want to use main, depend on the commit directly.

**Comment by pyweeker** [comment]
Thanks !!!
