### ISSUE TITLE
Expose more of the Vec API on BufferVec

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#3531]
## What problem does this solve or what need does it fill?

More efficient mutation APIs for `BufferVec` than just `push`, `reserve`, and `clear`.  Repeatedly `push`ing large quantities can be quite inefficient due to needing to repeatedly do size and capacity checks on the underlying Vec.

## What solution would you like?

Expose more of the mutation APIs to more efficiently build `BufferVecs`. Most notably `append` for grouping chains of `Vec`s together. 

## What alternative(s) have you considered?

 - Repeatedly `push`ing the items onto the `BufferVec`.
 - `DerefMut` on the underlying `Vec`.

## Additional context

This would both simplify and speed up the "prepare" stage of rendering of entities with large quantities of mutable values, including but not limited to particle systems and large scale batching.

**Comment by Jdogstar** [comment]
Out of curiosity, besides append, what other API's would you consider effective to add?

**Comment by james7132** [comment]
#6833 requires adding `Vec::truncate` to the API, `Vec::append`/`Vec::extend` are also other options worth considering as well.
