### ISSUE TITLE
Weird looking Torus with 

### ISSUE THREAD

**Issue by Sebbl0508** [bevyengine/bevy#3547]
## Bevy version
v0.5.0

## Operating system & version
Windows 10

## What you did
Spawn a Torus & a Light

## What you expected to happen
The Torus to have a normal colour

## What actually happened
The Half of the torus is a weird gray-ish colour

## Additional information
- [Screenshot 1](https://imgur.com/pEuBOEO)
- [Screenshot 2](https://imgur.com/ZqrRUKo)

This happens with other Meshes nearby, but also when the torus is spawned alone with the light

```rust
    commands.spawn_bundle(PbrBundle {
        mesh: meshes.add(Mesh::from(shape::Torus {
            radius: 2.0,
            ring_radius: 1.5,
            subdivisions_segments: 64,
            subdivisions_sides: 64,
        })),
        material: materials.add(Color::rgb_u8(0, 0, 255).into()),
        transform: Transform::from_xyz(-1.0, 2.5, -5.0),
        ..Default::default()
    });

    // Light
    commands.spawn_bundle(LightBundle {
        transform: Transform::from_xyz(0.0, 16.0, 1.0),
        light: Light {
            color: Color::WHITE,
            range: 40.0,
            intensity: 400.0,
            ..Default::default()
        },
        ..Default::default()
    });
```

**Comment by alice-i-cecile** [comment]
We suspect that this is an issue with the normals: that's probably the best place to start digging into this issue.

**Comment by alice-i-cecile** [comment]
@jakobhellermann adapted the code from http://apparat-engine.blogspot.com/2013/04/procedural-meshes-torus.html originally. We should check for obvious differences between this and our implementation.
