### ISSUE TITLE
Use builder pattern with setter methods to simplify code

### ISSUE THREAD

**Issue by haselkern** [bevyengine/bevy#355]
Looking at the [breakout example](https://github.com/bevyengine/bevy/blob/9aff0bcc2a8a39beda159f81bd7e8729f38f9773/examples/game/breakout.rs#L81) we can see the following code:

~~~rust
Style {
    position_type: PositionType::Absolute,
    position: Rect {
        top: Val::Px(5.0),
        left: Val::Px(5.0),
        ..Default::default()
    },
    ..Default::default()
}
~~~

While using the struct update syntax works, I think it would be more elegant to have a setter method for each attribute, so that above code could be rewritten as such:

~~~rust
Style::default()
    .position_type(PositionType::Absolute)
    .position(Rect::default()
        .top(Val::Px(5.0))
        .left(Val::Px(5.0)))
~~~

This is (in my opinion) more elegant and removes noise from the code. There are *a lot* of Default::default() calls sprinkled throughout the init code of the breakout game:
![..Default::default() ..Default::default() ..Default::default()](https://user-images.githubusercontent.com/7420740/91322166-b33b5000-e7bf-11ea-94c3-85f01078b16d.png)

**Comment by Waridley** [comment]
Honestly I kind of like the struct syntax, and when you want a builder, you probably want it to be a separate type. This lets you have a mutable struct that you can perform setup on, and then get a "finalized" version that is immutable.

**Comment by skairunner** [comment]
I disagree -- semantically the defaults pattern fits more with all these plain data types. You usually see builders for things that need more complicated configuration.

Re: noise, I happen to think the builder pattern is much noiser :)

**Comment by cart** [comment]
I'm pretty firmly anti builder in this case. Too much additional boilerplate and complexity for extremely marginal (and debatable) public api wins. The current "default initializer" approach also encourages fully data-oriented contracts. The builder pattern allows side effects.

I'm willing to consider builders on a case by case basis where side effects are necessary, but in general I'm against this change.

**Comment by cart** [comment]
I think im going to close this issue as I am against the builder pattern in the general case. Feel free to open new issues if you think specific apis merit exceptions.
