### ISSUE TITLE
Failed assert with Metal API validation: texture view creation not allowed from frameBufferOnly textures

### ISSUE THREAD

**Issue by HackerFoo** [bevyengine/bevy#3557]
## Bevy version

https://github.com/bevyengine/bevy/commit/a1e3c5c1001b06d23195cd94c8ae7b524c992c4c

## Operating system & version

MacOS 12.1

## What you did

Setup Xcode for the Metal debugger as detailed [here](https://github.com/gfx-rs/wgpu/wiki/Debugging-with-Xcode), with Metal API validation enabled:

<img width="997" alt="Screen Shot 2022-01-05 at 10 05 40" src="https://user-images.githubusercontent.com/1069462/148266946-e9a03c09-a605-4a43-989a-9c975cf38117.png">

I compiled the `3d_scene` example with `cargo run --example 3d_scene`, and then ran it with Xcode.

## What you expected to happen

No assertion failures.

## What actually happened

```
2022-01-05 09:56:45.121402-0800 3d_scene[34922:6183863] Metal GPU Frame Capture Enabled
2022-01-05 09:56:45.121680-0800 3d_scene[34922:6183863] Metal API Validation Enabled
[2m2022-01-05T17:56:45.134485Z[0m [32m INFO[0m [2mbevy_render::renderer[0m[2m:[0m AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: DiscreteGpu, backend: Metal }
2022-01-05 09:56:45.154988-0800 3d_scene[34922:6183863] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x126a185a0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
_validateTextureView:557: failed assertion `Texture View Validation
texture view creation not allowed from frameBufferOnly textures.
'
_validateTextureView:557: failed assertion `Texture View Validation
texture view creation not allowed from frameBufferOnly textures.
'
```

The window appears briefly before hitting the assertion.

## Additional information

I hit the same assertion with other examples. They run as expected without API validation enabled.

**Comment by HackerFoo** [comment]
I've used `git bisect` to find that this first occurred on https://github.com/bevyengine/bevy/commit/9a89295a1741da0258c56c326aecfcad37ae6b41, the upgrade to wgpu 0.12. So the bug might be upstream.

**Comment by NiklasEi** [comment]
Have you tried running the `wgpu` examples like this?

**Comment by HackerFoo** [comment]
Not yet. I just tried running `3d_scene` using the latest `wgpu` (10a07e4807930d4bbae043b35394a1f5e2c1cfab), and the validation error is gone.

**Comment by HackerFoo** [comment]
Here's the commit that fixed it: https://github.com/gfx-rs/wgpu/commit/55cbbdea625b9fffa770fa617db1848c45d5808f

**Comment by Gordon-F** [comment]
> Here's the commit that fixed it: gfx-rs/wgpu@55cbbde

@HackerFoo fix published in wgpu-core-0.12.2. `cargo update` should fix this issue.

**Comment by superdump** [comment]
@HackerFoo perhaps if you could test and confirm the fix is working with just a `cargo update` then we can close this?

**Comment by HackerFoo** [comment]
I've verified that 0.12.2 has fixed this.
