### ISSUE TITLE
Adding assets in plugin can overwrite assets from another plugin

### ISSUE THREAD

**Issue by aevyrie** [bevyengine/bevy#3559]
## Bevy version

main ~0.6

## Operating system & version

N/A

## What you did

1. Call `add_asset::<MyAsset>()` in `PluginA`, `add()` an asset to `MyAsset`, and get a `Handle`
2. Call `add_asset::<MyAsset>()` in `PluginB`
3. Add PluginA to the app, then add PluginB to the app.
4. Run the app

## What you expected to happen

All added assets with a `Handle` remain valid.

## What actually happened

The `Handle` generated in step 1 is dropped when plugin B calls `add_asset()`.

## Additional information

I found this when debugging a hard-to-find runtime error, where an asset failed to load even though I had a handle to it. This seems like a pretty major footgun, especially because it breaks the encapsulation that plugins are supposed to provide. This is a subset of #1255.

**Comment by cart** [comment]
Sounds like we could fix this pretty easily by just adding a check to `add_asset` that does nothing if the asset collection already exists.
