### ISSUE TITLE
Fast add/remove components via bit flipping.

### ISSUE THREAD

**Issue by CooCooCaCha** [bevyengine/bevy#356]
It's well known that adding/removing components is a slow operation in archetype-based ECS systems. One solution that Unity is working on for their ECS (also archetype-based) is using bit flipping to enable/disable components quickly at runtime. 

Here's the CTO of Unity describing their approach:
https://forum.unity.com/threads/dots-skill-system-repo-available.894007/#post-5875804

I imagine something like this could be useful for Bevy.

**Comment by alice-i-cecile** [comment]
This should be (largely) addressed with the new sparse component storage that we're targeting for 0.5 :)

**Comment by alice-i-cecile** [comment]
This was added via sparse set supports in #1525 :D

**Comment by alice-i-cecile** [comment]
This was *not* added in the end, and would be very useful for fast component add / removals. Making another issue for that topic though.
