### ISSUE TITLE
Tracing spans include "noisy" characters

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#3563]
We should probably fix this (maybe in upstream tracing libs)?

![image](https://user-images.githubusercontent.com/2694663/148304064-08663e8b-250f-43bd-9cb2-b3ba762cb6f1.png)

**Comment by rparrett** [comment]
The ansi escape codes seem to be introduces by https://github.com/bevyengine/bevy/blob/main/crates/bevy_log/src/lib.rs#L123

It seems like either removing those two lines or adding `.with_ansi(false)` to the first helps the situation. But I'm not familiar enough with tracing / tracy to know if that has any undesirable side ffects.

**Comment by rparrett** [comment]
Is it acceptable to lose ansi output in logging sent to stdout when one of the `trace_chrome` or `trace_tracy` features is used?

**Comment by mockersf** [comment]
yes for me 👍

**Comment by infmagic2047** [comment]
This seems like the upstream bug https://github.com/tokio-rs/tracing/issues/1817. Does the workaround of swapping layers work here?

**Comment by rparrett** [comment]
> This seems like the upstream bug [tokio-rs/tracing#1817](https://github.com/tokio-rs/tracing/issues/1817). Does the workaround of swapping layers work here?

That seems to describe "we still get ansi in files even with `.with_ansi(false)`.

But bevy does not use `.with_ansi` (except where I potentially add it in #3583).

I'm pretty sure that (at least when I was working on that PR), our chrome/tracy subscribers were already being added last, so I don't think that bug affected us?

**Comment by infmagic2047** [comment]
> That seems to describe "we still get ansi in files even with .with_ansi(false)."

That issue says an early layer with `.with_ansi(true)` causes ansi escape codes in later layers, even if those have `.with_ansi(false)`. It seems similar to our case here.

**Comment by rparrett** [comment]
I am actually no longer able to reproduce this issue at all, seemingly since 258f49535278a524ed8e6d82fd1721703fb26287

**Comment by mockersf** [comment]
fixed upstream
