### ISSUE TITLE
Fix broken links in private docs

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3566]
~~We sometimes link to private items in our public docs.~~ Sometimes, our links our broken in our private docs. By default, these are not checked by our CI.

You can check this with `cargo doc --open --document-private-item`.

We should fix these broken links. Once these are all cleaned up, we should add this to our CI in the same PR.

Noted by @killercup in #3473.

**Comment by mockersf** [comment]
This helps checking the documentation on private items, but I don't think it checks if the links are to something private

**Comment by mfdorst** [comment]
Yeah I think it's just that there are some broken links in the docs for private items that don't get caught by CI because CI ignores the private docs. Might have misunderstood though.

**Comment by killercup** [comment]
Sorry for the confusion! The issues I found were indeed in the documentation of private items. This documentation is usually not visible, so it's not a big deal. They only become an annoyance when we expose these items in public API.

I don't have time to confirm this but I assume that linking _to_ private items throws an error/warning when just running `cargo doc`, and `--document-private-item` might actually hide that warning. So to test this, you'd have to run it twice.

**Comment by alice-i-cecile** [comment]
Thanks, I fixed the issue description. Sorry for the confusion; I should have double-checked what the command did!
