### ISSUE TITLE
Render a 3D pass on top of another

### ISSUE THREAD

**Issue by HackerFoo** [bevyengine/bevy#3567]
## What problem does this solve or what need does it fill?

When building a 3D UI, it's desirable to always render object in the UI on top regardless of depth.

## What solution would you like?

Add a `renders_on_top` flag to `Camera` that causes the depth texture to clear at the start of a 3D render pass.

## What alternative(s) have you considered?

I considered creating a depth-only clear pass, which could be done without modifying Bevy, but this would be an extra pass and a lot of code in the application.

## Additional context

![IMG_0168](https://user-images.githubusercontent.com/1069462/148327041-1661513d-f06f-45d8-bb09-8b2fecff3c39.jpg)

**Comment by alice-i-cecile** [comment]
This ties into some of my thoughts on "UI is a collection of properties". This is a solid idea, and attaching it to the camera is a reasonable strategy.

How do we determine which entities are rendered by each camera?

**Comment by HackerFoo** [comment]
The `RenderLayers` component is a 32-bit mask such that each object is visible to a camera if the bitwise-and of the camera and object are nonzero.

**Comment by HackerFoo** [comment]
A higher-level API would be to assign a layering order to each camera, and each unique layer would require a pass after clearing the depth buffer. I'd wait on this, though, because it's somewhat complicated and might not be useful.

**Comment by HackerFoo** [comment]
Another reason to render on top of another pass is to implement a skybox, since the skybox should be behind everything else.

**Comment by aevyrie** [comment]
Some relevant discussion from cart here: https://discord.com/channels/691052431525675048/931614194229477417/931974884534415380

**Comment by superdump** [comment]
@HackerFoo I assume this can be closed now that camera-driven rendering was merged?

**Comment by HackerFoo** [comment]
Maybe? I'm using my PRs until I'm able to test cart's solution, but I can always reopen the issue if I need to.
