### ISSUE TITLE
Timer API inconsistency with Duration

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#3572]
## What problem does this solve or what need does it fill?

[Duration.as_secs()](https://doc.rust-lang.org/std/time/struct.Duration.html#method.as_secs) returns `u64`. But [Timer.elapsed_secs()](https://github.com/bevyengine/bevy/blob/507441d96f83355cdab578d85f804f4bf8d835c9/crates/bevy_core/src/time/timer.rs#L105) and [Stopwatch.elapsed_secs()](https://github.com/bevyengine/bevy/blob/507441d96f83355cdab578d85f804f4bf8d835c9/crates/bevy_core/src/time/stopwatch.rs#L83) return `f32`. It's confusing.

## What solution would you like?

I would suggest to return `u64` from these functions and add additional helpers `elapsed_secs_f32` and `elapsed_secs_f64` as in `Duration`. Should be an easy change.

**Comment by DJMcNab** [comment]
The suggestion to make those methods return `u64` is strange. That creates quite a significant footgun, since that will in many cases just return `0`, likely leading to incorrect behaviour.

I guess if we want this consistency, we should rename the methods to `elapsed_secs_f32`, but I firmly oppose adding the methods which return `u64` as the default name.

**Comment by Shatur** [comment]
I would expect seconds in unsigned integer. Probably this is why Duration returns `u64` in standard Rust library.

**Comment by mockersf** [comment]
From my point of view, Bevy exposes an api that is often better for games, with seconds as a f32 being a common expectation.

To have a more general Rust like api, you can access `Timer.elapsed.as_secs()`which will give you the `u64`.

**Comment by Shatur** [comment]
Okay, makes sense.

> To have a more general Rust like api, you can access Timer.elapsed.as_secs()which will give you the u64.

Yes, this is how I use it when I need only seconds.
