### ISSUE TITLE
Make it possible to remove a resource from the ECS and get full ownership of it

### ISSUE THREAD

**Issue by yusdacra** [bevyengine/bevy#359]
It should be possible to remove a resource from the ECS and get full ownership of it.

**Comment by Telzhaak** [comment]
Just out of interest,

what would that be useful for?
Why was it a resource if you plan on taking ownership of it? Does a copy/clone of the information not suffice?

**Comment by yusdacra** [comment]
> Just out of interest,
> 
> what would that be useful for?
> Why was it a resource if you plan on taking ownership of it? Does a copy/clone of the information not suffice?

I first wanted it so that I could remove a resource a plugin added so that I could add it to my own (related) resource, but figured out I didn't really need to do that. I can't think of any use-case that isn't already solved by other solutions, to be honest.

**Comment by chemicstry** [comment]
Even though there may not be use cases for this now, I think this must be supported by the API. Currently resources are insert only with no way to remove them.

One such use case would be a custom rendering system that is inserted into resource and later you would like to move it somewhere else without destroying window.

**Comment by MichaelHills** [comment]
Would loading different maps with different game modes be another example?

**Comment by alice-i-cecile** [comment]
#1478 creates an API for this, but doesn't allow you to hand it off. I think that's worth implementing still.

**Comment by cart** [comment]
Close by #1525, via `world.remove_resource()`
