### ISSUE TITLE
Panic in bevy_pbr when resizing window too small with mouse

### ISSUE THREAD

**Issue by Sheepyhead** [bevyengine/bevy#3596]
## Bevy version

0.6

## Operating system & version

Windows 10

## What you did

I started my game and then grabbed the corner of the window with my mouse and resized it as small as it would go

## What you expected to happen

The window resizes down to minimum and back up without issue

## What actually happened

The game panicked with the following message 

`
thread 'Compute Task Pool (5)' panicked at 'assertion failed: self.axis_slices.x * self.axis_slices.y * self.axis_slices.z <= 4096', C:\Users\Sheepyhead\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_pbr-0.6.0\src\light.rs:254:9
` (backtrace omitted)

## Additional information

`INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce GTX 1080", vendor: 4318, device: 7040, device_type: DiscreteGpu, backend: Vulkan }`

There seems to be some talk about it being related to #3399 but I decided to make a fresh issue on it since the actual panic is different

**Comment by HackerFoo** [comment]
I think I have a fix for this - I'll work on a PR: https://github.com/HackerFoo/bevy/commit/2e5d1a0672660d4e7f546994d1566dc4bc63d381

**Comment by alice-i-cecile** [comment]
Closed by #4148.
