### ISSUE TITLE
Handle repeating KeyboardInput events

### ISSUE THREAD

**Issue by jngbsn** [bevyengine/bevy#360]
Currently there is no way to determine if a KeyboardInput pressed event is the result of the initial press, or the result of the key being held and triggering repeating pressed events. Currently winit doesn't have a way of tracking this either, but could be done with storing some state in Bevy itself. I feel this is something a game engine should be able to track.

**Comment by ashneverdawn** [comment]
For anyone who needs this 'now', one way to do this is to hold the previous frame's input state in a Local<> resource. 

I know ts the initial press if:
`last_frame == false && this_frame == true`
Similarly, I know its the last press if:
`last_frame == true && this_frame == false`

But indeed it would really simplify the code required to be able to use a match on an enum instead. For example:
```
match press_state {
  PressState::OnDown => {...},
  PressState::OnUp => {...},
  PressState::Down => {...},
  PressState::Up => {...},
}
```

**Comment by sunwukonga** [comment]
Apologies if I'm misinterpreting the question, but doesn't the `keyboard_input_system` handle this?

It clears the `just_pressed` and `just_released` fields of an `Input<Keycode>` with a call to `Input<Keycode>::update()` and then populates them again from the current input. If the keycode already exists in `Input<Keycode>`, it isn't inserted into `just_pressed`.

**Comment by ashneverdawn** [comment]
@sunwukonga Awesome I didn't know about this, thanks! 😄

**Comment by jngbsn** [comment]
You are correct, this does do what I was looking for! At the time I was processing keyboard input events manually, which doesn't have that ability. Either way, I'll close this for now, thanks for the input!
