### ISSUE TITLE
`DynamicUniformVec` element alignment is always 256, but could be smaller depending on device limits

### ISSUE THREAD

**Issue by jakobhellermann** [bevyengine/bevy#3607]
## What problem does this solve or what need does it fill?

The `DynamicUniform<T>` wrapper in `bevy_crevice` has an alignment of 256 as that is the minimum guaranteed `min_uniform_buffer_offset_alignment` by webgpu.

On my Ryzen 4600U integrated gpu the actual limit is `4`, so buffers with an element size `<256` could be made more efficient.

## What solution would you like?

Query the device limits (at least on `WgpuOptionsPriority::Functionality`) and use that limit as buffer element alignment.

**Comment by superdump** [comment]
This was addressed a while ago.
