### ISSUE TITLE
Change `bevy_core::Name` to implement `Deref<Target = str>`

### ISSUE THREAD

**Issue by JoJoJet** [bevyengine/bevy#3613]
## What problem does this solve or what need does it fill?

Currently, `Name` implements `Deref`, targeting `Cow<'static, str>`. This poses ergonomic issues, as it means there are two levels of indirection if one wishes to dereference to an `&str`. Additionally, it does not play well with generic code that expects `Deref<Target = str>`.  

## What solution would you like?

Change the `Deref` target to `str`. As far as I can tell, an immutable reference to a `Cow` does not offer any more functionality than a `&str` -- the `Cow` would need to be either mutable or owned in order to allow `Cow`-specific behavior. Thus, we should not lose any functionality by making this change.

**Comment by cart** [comment]
Yup this stems from my initial misconception that `Cow<'static, str>` gave you true "copy on write" behavior for Strings. This is not entirely true (cloning an Owned cow results in another Owned reference). We've slowly been untangling code built around that assumption, but we missed this one. Thanks!
