### ISSUE TITLE
link "some benchmarks" to sources

### ISSUE THREAD

**Issue by matkoniecz** [bevyengine/bevy#3622]
## What problem does this solve or what need does it fill?

Improve onboarding and initial impression for visitor of https://bevyengine.org/

## What solution would you like?

"some benchmarks" at https://bevyengine.org/ link to said benchmarks - or even better an overview of performance compared to alternatives

## What alternative(s) have you considered?

None

## Additional context

"some benchmarks" without anything specific or link to anything specific is not very impressive. Everyone knows that anything can win at some benchmark.

I would also note that starting from performance claims would have negative effects if performance will not turn out to be great in practice.

(is performance really primary strength of Bevy?)

**Comment by alice-i-cecile** [comment]
Moved to https://github.com/bevyengine/bevy-website/issues/262
