### ISSUE TITLE
https://bevyengine.org/learn/book/introduction/ links directly to the book end as the next step

### ISSUE THREAD

**Issue by matkoniecz** [bevyengine/bevy#3623]
https://bevyengine.org/learn/book/introduction/

has

> This official book is still very incomplete. It will help you get started with the setup and learning the basics, but it does not yet cover most of Bevy's features. See the Next Steps page for links to other, more exhaustive, learning resources you can use.

"See the Next Steps" is linking to the https://bevyengine.org/learn/book/next-steps/ with 

> You have reached the end of The Bevy Book!

maybe linking to https://bevyengine.org/learn/book/getting-started/ would be superior

**Comment by ickk** [comment]
From the context of the sentence it seems to me like the intention to link to the "Next Steps" page is correct ("Next Steps" is indeed a page with links to alternative learning resources). Perhaps the wording or name of that section could be improved for clarity though.

**Comment by matkoniecz** [comment]
I would expect "next steps" after some steps - at the end of https://bevyengine.org/learn/book/getting-started/

Or at least make an actual content here more clear - the stylized next/before does not really look like next/previous pagination

Right now leaving tutorial (standard link) is easier to find than the next tutorial step (pagination highly styled into unrecognizability)

![screen](https://user-images.githubusercontent.com/899988/148726033-4c8a889f-92a0-4981-aca6-47ad10152a8d.png)

**Comment by alice-i-cecile** [comment]
Moved to https://github.com/bevyengine/bevy-website/issues/261
