### ISSUE TITLE
Segmentation fault running any bevy code

### ISSUE THREAD

**Issue by Grant1219** [bevyengine/bevy#3630]
## Bevy version

v0.6.0 

## Operating system & version

Debian
```
> uname -a
Linux lemon 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

> rustc -V
rustc 1.57.0 (f1edd0429 2021-11-29)

> cargo -V
cargo 1.57.0 (b2e52d7ca 2021-10-21)
```

## What you did

```
git clone https://github.com/bevyengine/bevy
cd bevy
cargo run --example hello_world
```

I also tried creating a brand new project and depending on bevy and copied the `hello_world` example:
```
> cargo new bevy_test --bin
     Created binary (application) `bevy_test` package

> cat Cargo.toml 
[package]
name = "bevy_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.6"
```

## What you expected to happen

The program should run normally.

## What actually happened

Segmentation fault immediately after starting (no stacktrace output).
```
grant@lemon ~/projects/bevy ((HEAD detached at v0.6.0))
> RUST_BACKTRACE=full cargo build --example hello_world
Segmentation fault
grant@lemon ~/projects/bevy ((HEAD detached at v0.6.0))
> RUST_BACKTRACE=full cargo run --example hello_world
Segmentation fault
```

## Additional information

I use i3 window manager.
```
> i3 --version
i3 version 4.19.1-non-git © 2009 Michael Stapelberg and contributors
```

I see the following logs from `cargo` in `dmesg`:
```
[ 2649.866600] traps: cargo[11184] general protection fault ip:55b80d69d97b sp:7ffe74182900 error:0 in cargo[55b80d200000+e39000]
[ 2746.503898] traps: cargo[11208] general protection fault ip:56315a09d97b sp:7ffcbe6d74d0 error:0 in cargo[563159c00000+e39000]
```

GFX information:
```
0b:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7)
	Subsystem: ASUSTeK Computer Inc. Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1043:0517]
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

**Comment by manokara** [comment]
Try to [run it in lldb](https://dev.to/bmatcuk/debugging-rust-with-rust-lldb-j1f) to see if you can get a backtrace. It's likely to be driver related.

**Comment by alice-i-cecile** [comment]
Just to double-check: can you try running with default features disabled?

```
bevy = {version = "0.6", default-features = false}
```

Being able to isolate this to a specific module / subsystem would be very useful.

**Comment by Grant1219** [comment]
Alright well I don't have lldb installed but I did get more helpful output from GDB:
```
(gdb) run run --example hello_world
Starting program: /home/grant/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo run --example hello_world
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after vfork from child process 14621]
[Detaching after vfork from child process 14622]
[Detaching after vfork from child process 14624]

Program received signal SIGSEGV, Segmentation fault.
0x000055555589d97b in cargo::core::compiler::fingerprint::calculate::hafc6b250b695c233 ()
```
This seems like not a bevy problem, but a crash that's happening before cargo finishes initializing. If you want we can continue digging into this, but I won't fault you for closing it either.

**Comment by dataphract** [comment]
> This seems like not a bevy problem, but a crash that's happening before cargo finishes initializing.

Does the build succeed? And if so, are you able to run the binary without cargo? It should show up at `target/debug/examples/hello_world`.

**Comment by Grant1219** [comment]
> > This seems like not a bevy problem, but a crash that's happening before cargo finishes initializing.
> 
> Does the build succeed? And if so, are you able to run the binary without cargo? It should show up at `target/debug/examples/hello_world`.

The build does not succeed and results in the same error, which makes debugging more difficult since I can't take a look at the resulting binary.
```
Starting program: /home/grant/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo build --example hello_world
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after vfork from child process 14629]
[Detaching after vfork from child process 14630]
[Detaching after vfork from child process 14632]

Program received signal SIGSEGV, Segmentation fault.
0x000055555589d97b in cargo::core::compiler::fingerprint::calculate::hafc6b250b695c233 ()
```

**Comment by turboMaCk** [comment]
it seems to me that panic doesn't happen in bevy app but in cargo or rustc. So this issue doesn't seem to be related to bevy. Are you able to combile non bevy rust projects using cargo? Perhaps you should open issue in cargo for this.

> This seems like not a bevy problem, but a crash that's happening before cargo finishes initializing.

agree

**Comment by james7132** [comment]
Closing this out as this seems to be unrelated to Bevy and unactionable on Bevy's end.
