### ISSUE TITLE
Why does Color::rgb use f32 instead of u8?

### ISSUE THREAD

**Issue by wyhaya** [bevyengine/bevy#364]
u8:
```rust
Color::rgb(0, 0, 0);
Color::rgb(255, 255, 255);
Color::rgb(3, 169, 244);
```

In many cases, rgb uses numbers from 0-255, and using u8 will not appear invalid colors

f32:
```rust
Color::rgb(312312321.312, 312312.0, 654645.1231);
```

f32 cannot verify the correctness of the value

**Comment by karroffel** [comment]
What values are useful depends on the situation. HDR rendering and HDR images for example (high dynamic range) *need* to be able to go above `1.0`, so going with `f32` means you can have higher dynamic range than when using a normalised `u8`.

**Comment by wyhaya** [comment]
@karroffel Thank you for your reply. 
 
This is a very common one. Is it necessary to add `Color:from_u8(255, 255, 255)` or similar methods?  It should be more convenient to use `rgb` in this way.

**Comment by karroffel** [comment]
I'm sure a function like that can be added, I wouldn't think that should be a problem :)

I personally don't use normalised `u8`s often to describe colour values, to me a range from `0.0` to `1.0` is more intuitive, unless you are dealing with serialisation code or direct image formats. But if a `from_u8` methods makes code clearer in some cases then I would expect that to be a welcome addition

**Comment by cart** [comment]
Yeah we do need floats in some cases. But `from_u8` would be very welcome!

**Comment by ncallaway** [comment]
I'd suggest normalizing with the `Color::rgb` and `Color::rgba` functions, so something like `Color::rgb_u8()` and `Color::rgba_u8()`
