### ISSUE TITLE
Keys not being detected while keyboard layout is in not english

### ISSUE THREAD

**Issue by Okirshen** [bevyengine/bevy#3641]
## Bevy version

0.6

## Operating system & version

Archlinux

## What you did

Switched keyboard layout from en-US to he-IL.

## What you expected to happen

Expected bevy to capture keys and operate without a difference.

## What actually happened

Bevy captures key events (tested with `EventReader<KeyboardInput>`) but `input.pressed` returns false while in a non english layout.

## Additional information

Currently only tested with Russian and Hebrew without success. 

Edit: Testing more I found that the `scan_code` in the event doesn't change but the `key_code` is `None` while in Hebrew layout.

**Comment by mockersf** [comment]
probably related to #2052, #1666, #862

**Comment by Okirshen** [comment]
I think its #2052, the scan code woks but key code is not english so its not recognized. its pretty annoying for people with other layouts,
