### ISSUE TITLE
Android crashing with enabled bevy_audio

### ISSUE THREAD

**Issue by Gordon-F** [bevyengine/bevy#3648]
## Bevy version

bevy#bc499591c2d090e17c95d2c59bc6e16ba60a023d

## Operating system & version

Android  8

## What you did

Enable `bevy_audio` on android.

```
2022-01-12 18:05:15.946 14333-14393/rust.android D/event crates\bevy_app\src\plugin_group.rs:117:  added plugin: bevy_audio::AudioPlugin
2022-01-12 18:05:15.946 14333-14392/rust.android I/RustStdoutStderr: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\ndk-glue-0.6.0\src\lib.rs:59:39
```

**Comment by manokara** [comment]
The panic comes from here: 

https://github.com/rust-windowing/android-ndk-rs/blob/f4dc7265aaa3e51f355ff1cb298e18167685fc7f/ndk-glue/src/lib.rs#L58-L60

For some reason it can't get the activity for the app, it must be something on `rodio` or `cpal` causing it.

**Comment by Gordon-F** [comment]
> I wonder if there's a way to do that it bevy automatically?

It's a part of `bevy_main` - https://github.com/bevyengine/bevy/blob/a6d3cd92fe2be55032c2e63a1ed983543d28143b/crates/bevy_derive/src/bevy_main.rs#L19

**Comment by manokara** [comment]
Oh, right. Are you using it though? From reading the code in `ndk_glue` it should set the activity handle to `Some`, even if it's invalid somehow, because the panic would be somewhere else.

**Comment by Gordon-F** [comment]
> Oh, right. Are you using it though? 

Yep, this is init problem with `bevy_audio` and potentially with `bevy_assets` (they get native_activity in Plugin build step too). But this should be a part of startup system, that running after native activity is available. 

So, if you have a powerful device, maybe you didn't see this errors at all.

**Comment by b333z** [comment]
Think this might be https://github.com/rust-windowing/android-ndk-rs/issues/211

**Comment by mockersf** [comment]
winit is bringing in ndk 0.5, and rodio is using both ndk 0.3 and 0.6... so it's probably not possible to get audio working with bevy_audio...
