### ISSUE TITLE
Renderer slowness (low FPS) for about three minutes with vsync enabled.

### ISSUE THREAD

**Issue by HeavyRain266** [bevyengine/bevy#3665]
## Bevy version

0.6

## Operating system & version

Windows 11

## What you did

Ran [my game](https://github.com/HeavyRain266/space_invaders) with DirectX 12 and Vulkan backends. Using both, `debug` and `release` modes.

## What you expected to happen

Game should automatically use FPS set by vsync, not wait few minutes.

## What actually happened

After you run game, there is tearing for character and low fps in any counter for up to three minutes.

**Comment by bjorn3** [comment]
What gpu are you using and which driver version?

Bevy enables vsync when configuring the surface (which happens immediately after opening a window and after every resize, in both cases before rendering anything for the current frame) so it seems to me like the driver isn't immediately respecting it. https://github.com/bevyengine/bevy/blob/458cb7a9e93dab3127bb99ce7bf8cfc3af18851d/crates/bevy_render/src/view/window.rs#L141-L143

**Comment by HeavyRain266** [comment]
Issue is no longer present in Bevy 0.7.
