### ISSUE TITLE
Shame on you, Cart

### ISSUE THREAD

**Issue by ghost** [bevyengine/bevy#3668]
Shame on you @cart for selling yourself as a cheap and worthless slave . Shame on you for using that disgusting and silly "titles" before names in one of your older godot networking video (music credits). Bevy is trash, and your mentality is disgusting. Death to people who use these stupid "titles" with names. Death to "univeristies". Death to the stupid and garbage so called "health sector". Hope you get punished severely.

**Comment by DraftedDev** [comment]
Is this Twitter or Github?
