### ISSUE TITLE
Vulkan Validation Issue on breakout example 

### ISSUE THREAD

**Issue by mwbryant** [bevyengine/bevy#3670]
## Bevy version
0.6.0

## Operating system & version

Ubuntu 20.04

## What you did

git clone https://github.com/bevyengine/bevy
cd bevy
cargo run --example breakout

## What you expected to happen

Breakout example should run

## What actually happened

A window is created and immediately closes and crashes

## Additional information

The example runs perfectly in release mode and this happens on most examples.  Tested with nvidia drivers 495 and 470 and with the default ubuntu window manager and i3.

>   Finished dev [unoptimized + debuginfo] target(s) in 0.07s
>      Running `target/debug/examples/breakout`
> 2022-01-14T06:30:16.640702Z  INFO winit::platform_impl::platform::x11::window : Guessed window scale factor: 1    
> 2022-01-14T06:30:16.696271Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3070", vendor: 4318, device: 9348, device_type: DiscreteGpu, backend: Vulkan }
> 2022-01-14T06:30:17.037929Z  INFO gilrs_core::platform::platform::gamepad: Gamepad /dev/input/event3 (ASRock LED Controller) connected.    
> 2022-01-14T06:30:17.147512Z ERROR wgpu_hal::vulkan::instance: VALIDATION [VUID-VkRenderPassBeginInfo-framebuffer-03209 (0x0)]
> 	VkRenderPassBeginInfo: Image view #1 created from an image with flags set as 0x400, but image info #1 used to create the framebuffer had flags set as 0x0 The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView of an image created with a value of VkImageCreateInfo::flags equal to the flags member of the corresponding element of VkFramebufferAttachmentsCreateInfoKHR::pAttachments used to create framebuffer (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-03209)    
> 2022-01-14T06:30:17.147560Z ERROR wgpu_hal::vulkan::instance: 	objects: (type: RENDER_PASS, hndl: 0x5d000000005d, name: ?)    
> Segmentation fault (core dumped)
>

**Comment by Dessix** [comment]
Repros at least as early as `507441d96f83355cdab578d85f804f4bf8d835c9` for me (about 20 commits back), and shows up on the `ui` example as well.

**Comment by mwbryant** [comment]
I found a solution for my issue from this closed wgpu issue (https://github.com/gfx-rs/wgpu/issues/1906) which instructs to use the most recent version of the vulkan sdk (currently 1.2.198 found at https://vulkan.lunarg.com/sdk/home#linux)
