### ISSUE TITLE
Advanced Audio

### ISSUE THREAD

**Issue by undersquire** [bevyengine/bevy#3676]
NOTE: I could not find any existing issues about this so I decided to open one. If there is one I missed please let me know.

## What problem does this solve or what need does it fill?

The current audio system in bevy is very lacking and in most cases not enough. I am proposing that a more advanced audio system that allows for volume control, pitch modifications, custom playback speed, and also 3D audio (based on 3D coordinates). This would greatly improve the usability of Bevy's audio API and make it suitable for full 2D and 3D games.

## What solution would you like?

Possibly add functions for directly altering an `AudioSource`'s pitch and playback speed:

```rs
fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    let music: Handle<AudioSource> = asset_server.load("sounds/test.wav");

    music.set_playback_speed(...);
    music.set_pitch(...);
}
```

Add an extended `audio.play()` function (maybe `audio.play_ex()`) that takes in a playback config struct:

```rs
fn some_system(audio: Res<Audio>) {
    let some_audio = ...; // pretend this has a Handle<AudioSource>

    // we could wrap this into a struct of some kind
    let playback_options = AudioPlayback {
        volume: 1.0, // default volume
        pitch: 1.0, // default pitch
        speed: 1.0, // default speed,
        position: Some(Vec3::new(0.0, 0.0, 0.0)) // center of world
    };

    // if position == None, then it will play it without a position (meaning it wont be altered by position)
    
    audio.play_ex(some_audio, playback_options);
}
```

## What alternative(s) have you considered?

There is a plugin called bevy_kira_audio which integrates Kira into bevy, but it does not seem to support 3D (position based) audio which I find necessary for 3D games. I also find it inconvenient to have to use a plugin for something as common as audio.

## Additional context

This is just an idea, this does not need to be the final API. If there already are plans for this then this can be closed; I only opened this because I didn't see any previous issues open about this.

**Comment by alice-i-cecile** [comment]
See also #1304 :) Audio is very much lacking, and most of the ecosystem is using `bevy_kira_audio` at the moment. It's likely that we'll upstream it, and work with the Kira team to add positional audio support.

**Comment by undersquire** [comment]
Oh thank you, I did not see that issue. Should I close this one?

**Comment by alice-i-cecile** [comment]
Yep, I'll close this out in favor of #1304 :)
