### ISSUE TITLE
Lowering the window panics!

### ISSUE THREAD

**Issue by kakoeimon** [bevyengine/bevy#368]
Run for example the breakout example and lower the window and Bevy panics.
this is the panic from the breakout:

`
thread 'main' panicked at 'extent state Extent { width: 1, height: 1, depth: 1 } must match extent from view Extent { width: 0, height: 0, depth: 1 }', C:\Users\kakoeimon\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323:35       
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\breakout.exe` (exit code: 101)
`

P.S. I am on Windows 10.

**Comment by DJMcNab** [comment]
Duplicate of #170

**Comment by kakoeimon** [comment]
Closing as it is a Duplicate of #170
