### ISSUE TITLE
Hot reloading is not working on 6.0 version

### ISSUE THREAD

**Issue by SmallNibbler** [bevyengine/bevy#3683]
## Bevy version

[package]
edition = "2021"

[dependencies.bevy]
version = "0.6.0"
default-features = false
features = [
  "bevy_dynamic_plugin",
  "render",
  "bevy_winit",
  "png",
  "x11",
]

## Operating system & version

Operating System: Manjaro Linux
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.15.12-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Pentium® CPU 3825U @ 1.90GHz
Memory: 7.7 Gb of RAM
Graphics Processor: Mesa Intel® HD Graphics

## What you did

1. cargo run
2. Change file "./assets/slides/first.rs"

Why is the AssetEvent::Modified not triggering?
On version 5.0 it worked.

```
use bevy::prelude::*;

pub (crate) struct TestPlugin;

impl Plugin for TestPlugin {
    fn build(&self, app: &mut App) {
        app
        .add_plugin(CodeAssetPlugin)
        .init_resource::<HandlesStorage>()
        .add_startup_system(assets_load)
        .add_system(assets_manage);
    }
}

#[derive(Default)]
struct HandlesStorage {
    storage: Vec<HandleUntyped>
}

fn assets_load (
    asset_server:       Res<AssetServer>,
    mut handles_storage:ResMut<HandlesStorage>
) {
    handles_storage.storage = asset_server
        .load_folder(&"./slides").unwrap();
    asset_server.watch_for_changes().unwrap();
}

fn assets_manage (
    mut asset_events:   EventReader<AssetEvent<Code>>
) {
    for event in asset_events.iter() {
        match event {
            AssetEvent::Created { handle } => {
                println!("Created handle {:#?}", handle);

            },
            AssetEvent::Modified { handle } => {
                println!("Modified handle {:#?}", handle);
            },
            AssetEvent::Removed { .. } => { println!("Removed!"); }
        }
    }
}

use bevy::asset::{AssetLoader, LoadContext, LoadedAsset};
use bevy::utils::BoxedFuture;
use bevy::reflect::TypeUuid;

#[derive(Debug, TypeUuid, Clone)]
#[uuid = "39cadc56-aa9c-4543-8640-a018b74b5052"]
pub (crate) struct Code {
    pub (crate) content: String
}

#[derive(Default)]
struct CodeAssetLoader;

impl AssetLoader for CodeAssetLoader {
    fn extensions(&self) -> &[&str] {
        &["rs"]
    }

    fn load<'a>(&'a self, bytes: &'a [u8], load_context: &'a mut LoadContext) -> BoxedFuture<'a, Result<(), anyhow::Error>> {
        Box::pin(async move {
            use std::str;

            let loaded_content = str::from_utf8(bytes)?;
            load_context.set_default_asset(LoadedAsset::new(Code{ content: loaded_content.to_string() }));
            Ok(())
        })
    }
}

pub struct CodeAssetPlugin;

impl Plugin for CodeAssetPlugin {
    fn build(&self, app: &mut App) {
        app.add_asset::<Code>()
            .init_asset_loader::<CodeAssetLoader>();
    }
}
```

## What you expected to happen

Created handle WeakHandle<Code>(AssetPathId(AssetPathId(SourcePathId(13027041954229367283), LabelId(6298619649789039366))))
Created handle WeakHandle<Code>(AssetPathId(AssetPathId(SourcePathId(9312919904264361102), LabelId(6298619649789039366))))
Modified handle  WeakHandle<Code>(AssetPathId(AssetPathId(SourcePathId(13027041954229367283), LabelId(6298619649789039366))))
Modified handle  WeakHandle<Code>(AssetPathId(AssetPathId(SourcePathId(9312919904264361102), LabelId(6298619649789039366))))

## What actually happened

Created handle WeakHandle<Code>(AssetPathId(AssetPathId(SourcePathId(13027041954229367283), LabelId(6298619649789039366))))
Created handle WeakHandle<Code>(AssetPathId(AssetPathId(SourcePathId(9312919904264361102), LabelId(6298619649789039366))))

**Comment by DJMcNab** [comment]
You have disabled the `filesystem_watcher` feature, so how could hot reloading run?

I'll make a PR to add a warning for this case though
