### ISSUE TITLE
Expose simple method for current size of image

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3689]
## Problem

Since the release of Bevy 0.6, many users are confused about how to fetch the current size of an image.

## Proposed solution

~~My personal preference would be to add a `size() -> Extent3d` method to `Image`.~~

We should create a pair of methods: `size_2d -> Vec2` and `size_3d() -> Vec3`

It [looks like](https://docs.rs/bevy/latest/bevy/prelude/struct.Image.html) the docs for `TextureDescriptor` aren't working properly, but I'm not immediately sure how to solve that: the type alias is pub.

~~`From` impls for `Vec3` and `Vec2` for `Extent3d` would be a nice bonus.~~ Edit: can't be done due to orphan rules.

## Current workaround

This can be fetched as `image.texture_descriptor.size`.

**Comment by PaperCow** [comment]
I can throw a PR together for this tomorrow if no one gets to it first.

I don't think we can do the `From` impls suggested since Extent3d and Vec2/3 are external types. Since the most common case people seem to be looking for is Vec2 would it be appropriate to make both `size() -> Extent3d` and something like `size_2d() -> Vec2`?

As for the doc issue with `TextureDescriptor`, I am pretty sure it is[ this very ancient rustdoc bug](https://github.com/rust-lang/rust/issues/15823) :(

**Comment by Bobox214** [comment]
Effectively I also think we can't have any `From` impls.
In bevy_math there is the `Size` type, would it be appropriate for `size_2d()` ?

**Comment by PaperCow** [comment]
> In bevy_math there is the `Size` type,

I asked about this the other day. There is [a PR](https://github.com/bevyengine/bevy/pull/3503) waiting for final review that shifts `Size` to bevy_ui with the idea that Size is a UI size and Vec2 is used elsewhere to represent 2D sizes.

**Comment by Bobox214** [comment]
I wonder if we should just provide `size_2d()`. As I feel  users needing the `Extent3d` version probably already have enough knowledge to directly get the `texture_descriptor.size`, and having `size()` and `size_2d()` will still slightly confuse standard users ?

**Comment by alice-i-cecile** [comment]
Hmm, yeah. I think I agree with you @Bobox214. The Vec2 / Vec3 versions are just better in most use cases. And then we can point users to how to get an Extent3D in the doc comments.

**Comment by zimzat** [comment]
I just ran into this problem when updating a project from 0.5 to 0.6. The tutorial I originally followed was using the sprite's size and the transform's scale to determine collision areas. The migration guide doesn't specify how to work with `custom_size`, doesn't mention that `sprite.size` went away or what replaced it, and all of the examples either only involve transform scale or use a global size constant so there's no example showing usage of the work-around outlined above either. There's only two usages of `Assets<Image>` I can find in the examples, in the game of life and texture_atlas, but neither are specifically about working with the size.

So far I've had to replace `&Sprite` with `&Handle<Image>`, add `images: Res<Assets<Image>>`, fetch the image using `let image = images.get(image_handle).unwrap();`, convert `laser_sprite.size` to `Vec2::from((image.texture_descriptor.size.width as f32, image.texture_descriptor.size.height as f32))` and switch from `Vec2::from(laser_transform.scale).abs();` to `laser_transform.scale.truncate().abs()`, all for what used to be `let laser_size = laser_sprite.size * Vec2::from(laser_transform.scale).abs();`

That's a lot of work just to get _one_ parameter of the inputs necessary to compare for collisions, which suggests I'm doing something wrong. Was there a better way to handle this? Was the original premise of using `sprite.size` wrong? Should I have stored the image size in `sprite.custom_size` or a separate Component at creation instead so it's easier to retrieve?

**Comment by rparrett** [comment]
I don't think you were wrong to use `sprite.size`. Bevy 0.5 had this system: https://github.com/bevyengine/bevy/blob/v0.5.0/crates/bevy_sprite/src/sprite.rs#L80 that would set that size for you if your sprite had an image. As far as I can tell, bevy 0.6 has no equivalent thing.

I do think that `Image` should have a `size` method, but that doesn't completely fix the confusion about how to determine a sprite's size in bevy 0.6.

In my case specifically, I am dealing with sprites that both do and don't have images. I have an example of dealing with this in [this question I posted](https://github.com/bevyengine/bevy/discussions/3620).

**Comment by BGR360** [comment]
Can this be closed? Seems PR was merged
