### ISSUE TITLE
Spawing many Entities and then despawing them leads to NoSuchEntity.

### ISSUE THREAD

**Issue by kakoeimon** [bevyengine/bevy#369]
I was trying to create a minimal project for another problem an I came upon this.
The minimal example project is the example ui/text with those lines:

`struct Item {
    max_time: f32,
    time: f32,
}

fn add_items(mut commands: Commands) {
    for _ in 0..1000 {
        commands.spawn((Item {max_time: 1.0, time: 0.0}, ));
    }
    

    
}

fn update_items(mut commands: Commands, time: Res<Time>, mut query: Query<(&mut Item, Entity)>) {
    let mut num = 0;
    for (mut item, e) in &mut query.iter() {
        num += 1;
        item.time += time.delta_seconds;
        if item.time >= item.max_time {
            commands.despawn(e);
        }
    }
    println!("number of items : {}", num);
}`

After a while I get:

`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoSuchEntity', C:\Users\kakoeimon\.cargo\git\checkouts\bevy-f7ffde730c324c74\89a1d36\crates\bevy_ecs\src\system\commands.rs:75:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\no_such_entity.exe` (exit code: 101)
`

The minimal example project

[no_such_entity.zip](https://github.com/bevyengine/bevy/files/5136120/no_such_entity.zip)

**Comment by CleanCut** [comment]
I confirmed I see the same thing on mac with the current master commit of https://github.com/bevyengine/bevy/commit/3efbaca10452427385822f79208ff3a78ab9edda

Here is an even more stripped down example (I just deleted more things from the example provided above).

[no_such_entity.zip](https://github.com/bevyengine/bevy/files/5146330/no_such_entity.zip)

**Comment by Ratysz** [comment]
Most likely related to #117.

**Comment by kakoeimon** [comment]
The example project I provided still panics.
I know it is not a real life test but...

**Comment by EllenNyan** [comment]
Are you using the git version of bevy or the crates.io version?

**Comment by kakoeimon** [comment]
The git, have you tried the example project?

**Comment by EllenNyan** [comment]
Yeah it was what I used to check that the PR fixed the issue x)
Could you try running `cargo clean` and then rebuilding and see if that fixes it?

**Comment by memoryruins** [comment]
Be sure to `cargo update` the example project too. The sample project's `Cargo.lock` is behind in changes. Without doing so, I recreate the panic, but after updating, it goes away for me.

**Comment by kakoeimon** [comment]
Everything look OK!
cargo clean and cargo update did the trick!
Sorry for my ignorance, I will keep that in mind.
Thanks.

**Comment by EllenNyan** [comment]
Ah oops cargo update, yeah this makes sense. Glad it's working for you now ^-^

**Comment by kakoeimon** [comment]
Just to inform you, I got the bug again in my project. 
Looks like it was a bad luck, but I thought it will be good to inform you.

**Comment by EllenNyan** [comment]
You'll get the same error message if you despawn the same entity twice. Could be that

**Comment by kakoeimon** [comment]
I just found the problem and it was mine. 
As you said I despawned the entity twice.
Sorry for bothering you.

**Comment by cart** [comment]
Not a problem! I'm glad you followed up, even if it ended up being on your side. It could have been an issue with bevy, and we want to fix issues with bevy :smile:
