### ISSUE TITLE
Can we also impl the other standard smartpointers? `Rc` and `Arc` in particular seem useful.

### ISSUE THREAD

**Issue by lafi-99** [bevyengine/bevy#3702]
Can we also impl the other standard smartpointers? `Rc` and `Arc` in particular seem useful.

__Originally posted by @alice-i-cecile in https://github.com/bevyengine/bevy/pull/3694#discussion_r785470657__

__Originally posted by @lafi-99 in https://github.com/AppTapp/Installer-Issues/issues/216__

**Comment by alice-i-cecile** [comment]
I am not sure what you were trying to do here 😅 Closing this out, as it seems like a misclick.

**Comment by DJMcNab** [comment]
I'm fairly confident that this user is a bot. We've seen them do something similar here before.
