### ISSUE TITLE
Periodic Stutters on some Mac hardware

### ISSUE THREAD

**Issue by CleanCut** [bevyengine/bevy#3709]
## Bevy version

The problem is on both:
- `0.6.0`
- The current `main` branch (3fcdc5a4926dcad89a3346977d862c505993d265 at the moment)

Bevy `0.5.0` did not exhibit this problem.

If I add the plugins from either of the projects below, then I get periodic stuttering / dropped frames.  I'm speculating this has something to do with the big rendering overhaul plus these plugins using custom shaders (?).
- `bevy_prototype_debug_lines`
- `bevy_prototype_lyon`

**Note:** I don't have to _use_ the plugins to see the problem (though I _do_ use them in the code provided)! Just adding the plugin `app.add_plugin( ... )` is enough to trigger the problem in my testing.

## Operating system & version

Here's the specs for my workstation with the problem.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/5838512/149678581-8a447bf8-b441-4db1-ba62-fb9379a5e741.png">

```
$ rustc --version
rustc 1.58.0 (02072b482 2022-01-11)
```

I also tried Rust 1.57 -- no change.  I've run `cargo update` to make sure I'm using the latest crates.io dependencies -- no change.

**NOTE:** This very similar system does NOT show the problem, or at least I can't reproduce it. I don't know whether the difference is the OS revision, the specific hardware, or something else.

<img width="239" alt="mbpro-screenshot" src="https://user-images.githubusercontent.com/5838512/149679193-d9337d74-6ba4-4b8e-ba49-ec8b16f9f0f3.png">

## What you did

```
$ git clone https://github.com/CleanCut/rusty_engine.git
$ cd rusty_engine
$ git checkout choppy
$ cargo run --release --example road_race

# Use the arrow keys to avoid obstacles, just so the game proceeds long enough to observe
# the periodic stutters on some hardware. In my experience, every 0.25 to 5 seconds there
# will be a stutter. The length of the stutter is variable--I've observed stutter durations of
# maybe a single frame to nearly a full second (my guesstimate -- I don't know how to
# measure it!).

# Compare to...

$ git checkout smooth -- Update: no stutters on my Intel boxen, still stutters on my M1 & @mockersf's M1 Max
$ cargo run --release --example road_race
```

## What you expected to happen

No stutters.

## What actually happened

Stutters.

## Additional information

I originally thought this was a bug in `bevy_prototype_debug_lines`, so I filed an [issue with that project](https://github.com/Toqozz/bevy_debug_lines/issues/14).

There are 5 tags/branches in the `CleanCut/rusty_engine` repository you can check out if you like. They're all exhibit the stutter for me except the first one:
- The `smooth` tag uses neither plugin - Update: Though this didn't stutter on my Intel machines, we discovered it still stutters on Apple M1 and M1 Max machines.
- The `choppy` tag is `bevy_prototype_debug_lines` with Bevy `0.6.0`
- The `bevy-main-debug-lines` branch is `bevy_prototype_debug_lines` with Bevy `main`
- The `choppy-lyon` tag is `bevy_prototype_lyon` with Bevy `0.6.0`
- The `bevy-main-lyon` branch is `bevy_prototype_lyon` with Bevy `main`
 
If you prefer an example where you don't have to dodge obstacles, you can run:
- `cargo run --release --example collision`
- (optional) Press the `C` key to turn on the debug lines (it doesn't make a difference, but the debug lines are what I'm trying to implement nicely)
- Hold down the left mouse button to rotate the sprite -- then just wait for stutters.

**Comment by mockersf** [comment]
I tried running branches `choppy` and `smooth` on my mac (macOS Monterey 12.1, m1 max) and both run the same for me... they both stutter

**Comment by CleanCut** [comment]
Whoah! `smooth` didn't stutter for me on Intel Montery 12.1 (hence the name). 🤔 Do you normally get stutter with Bevy 0.6? Is there something I can do to help narrow down the issue? Maybe try out that "tracy" profiler? I know little to nothing about the guts of rendering, but I'm more than willing to do some legwork if it'll help.

I've got access to an first-gen M1 -- I can try that as well for another data point.

**Comment by CleanCut** [comment]
I confirmed that I see stutter on all five branches I mentioned on an M1. I guess it's just the current state of the new renderer?

<img width="201" alt="image" src="https://user-images.githubusercontent.com/5838512/149850607-78c5b75d-685b-4a6a-b1d9-9d2008c55fea.png">

**Comment by rparrett** [comment]
That particular long frame was captured some number of nanoseconds after startup, so maybe that's not interesting. Here's another "long frame" from 9 seconds into play:

![image](https://user-images.githubusercontent.com/200550/149963733-ae826c4a-9d42-4f78-88c4-770cf71033fe.png)

where there seems to be a lot of action in the post_update stage, but not in a named span.

**Comment by CleanCut** [comment]
@rparrett Is there a doc somewhere that I can read to learn how to get set up with the tracing stuff? The 0.6 news post just mentions the `trace_tracy` feature and links to https://github.com/wolfpld/tracy - I'm having trouble figuring out how to get/build/run tracy to get the profile. I skimmed through the whole tracy PDF user guide...and it's not helping with the "get started" stuff.

**Comment by rparrett** [comment]
Yeah, no kidding. It's not too bad though:

1. https://dev.to/stein/build-the-tracy-profiler-server-on-macos-36k6
2. enable the `trace_tracy` feature on your bevy dependency
3. run the profiler and click connect
4. run your app

But if anyone has any tips for actually using Tracy well with a touchpad, I'm all ears.

**Comment by CleanCut** [comment]
Thanks! Now I've just got to figure out which older version of Tracy corresponds to "protocol version 46"

**Comment by mockersf** [comment]
I'm using tracy tag v0.7.8 to build locally and it works with Bevy

**Comment by CleanCut** [comment]
> I'm using tracy tag v0.7.8 to build locally and it works with Bevy

Thanks! I updated my instructions above.

Now my challenge will be to learn how to use this thing. I get the feeling that this will be a valuable skill in my future life using Bevy.

Maybe I can find some helpful info to add to this issue tonight.

**Comment by CleanCut** [comment]
Any tips on how best to use the Tracy Profiler UI?

**Comment by CleanCut** [comment]
Last night I profiled on the M1 for about 20 minutes. Ironically, it ran much more smoothly with the tracing enabled. At the end I figured out how to use the search to identify the longest frame, which was only ~42ms. 🤷🏻‍♂️  I need to try it on the Intel box.

**Comment by CleanCut** [comment]
Just enabling the `trace_tracy` feature on both my M1 and Intel boxes decreases the amount of stutter by quite a bit, but it does still occasionally occur. [Here's the dump](https://github.com/bevyengine/bevy/files/7919517/intel_11s_34ms_frame.tracy.zip) of a quick trace I did. About 11s in a frame took 34ms. Does this shed any light on the subject for anyone? It appears suspiciously like the threads in green and/or yellow are the culprits, but I really don't have any clue how Bevy's (or wgpu's) rendering works.  The names on those bars are:

- (green) `bevy_render::render_component::prepare_uniform_components<bevy_sprite::mesh2d::mesh::Mesh2dUniform>`
- (yellow) `bevy_ecs::change_detection::ResMut<bevy_render::render_asset::ExtractedAssets<bevy_render::mesh::mesh::Mesh>>, bevy_ecs::change_detection::ResMut<std::collections::hash::map::HashMap<bevy_asset::handle::Handle<bevy_render::mesh::mesh::Mesh>, bevy_render::mesh::mesh::GpuMesh, ahash::random_state::RandomState>>, bevy_ecs::change_detection::ResMut<bevy_render::render_asset::PrepareNextFrameAssets<bevy_render::mesh::mesh...` (I can't find a way to get the rest of it)
- ﻿

<img width="2626" alt="image" src="https://user-images.githubusercontent.com/5838512/150659625-a6d51fff-c455-42ac-819a-515fe8f3e307.png">

If you zoom out a bit, you'll notice that those two threads are not active with those two items at the same time in any of the well-timed frames:

<img width="2668" alt="image" src="https://user-images.githubusercontent.com/5838512/150659746-335f140e-5eb1-4e14-9d35-49ef0d39af30.png">

I have no idea where to go from here.

**Comment by adsick** [comment]
I don't think this is something Mac-specific: https://github.com/Toqozz/bevy_debug_lines/issues/14#issuecomment-1042871298

**Comment by CleanCut** [comment]
Resolved in Bevy 0.8

**Comment by adsick** [comment]
@CleanCut which PR is the fix for this?

**Comment by rparrett** [comment]
Likely https://github.com/bevyengine/bevy/pull/4744
