### ISSUE TITLE
We need a useful error message when two materials have the save UUID

### ISSUE THREAD

**Issue by eliotbo** [bevyengine/bevy#3731]
## Bevy version

0.6, 

## What you did

Take the shader_material example and add second material to it with the same UUID, but different name.

## What you expected to happen

I expected either a run time error message or a warning about having two identical UUID.

## What actually happened

There was a runtime error with not much information:
```
thread 'Compute Task Pool (20)' panicked at 'called `Option::unwrap()` on a `None` value', /home/eliotbolduc/Documents/rust/bevy_fork/crates/bevy_asset/src/asset_server.rs:505:14
```

It refers to this line in asset_server.rs:
```
let channel = asset_lifecycle
       .downcast_ref::<AssetLifecycleChannel<T>>()
       .unwrap(); ```

**Comment by rparrett** [comment]
Related: #2610

**Comment by ByAlu** [comment]
@alice-i-cecile This is my first time contributing. I don't know rust language but I have some programming experience. May I work on this issue?

**Comment by alice-i-cecile** [comment]
@ByAlu absolutely! Just open a PR and then link this issue :)

**Comment by mockersf** [comment]
@ByAlu there is already a pr for this issue: https://github.com/bevyengine/bevy/pull/3739

**Comment by ZainlessBrombie** [comment]
On latest main (b3a2cbbc):  
`thread 'main' panicked at 'Error while registering new asset type: "shader_material::CustomMaterial2" with UUID: f690fdae-d598-45ab-8225-97e2a3f056e0. Another type with the same UUID is already registered. Can not register new asset type with the same UUID', /tmp/bevy/crates/bevy_asset/src/asset_server.rs:110:13`

I think this can be closed then?
