### ISSUE TITLE
NaN when `looking_at` is called with `Transform`'s origin as target

### ISSUE THREAD

**Issue by elfein727** [bevyengine/bevy#3736]
## Bevy version
0.5 and 0.6

## Operating system & version
Linux Mint 20.2

## What you did

I modified the 3D Scene example so line 42 read as,
`transform: Transform::from_xyz(0.0, 0.0, 0.0).looking_at(Vec3::ZERO, Vec3::Y),`

As you can see, the origin of the transform is the same as where it's set to look.

## What you expected to happen

Default to either current Quat or the unit matrix.

## What actually happened

Printing the debug value of that particular transform produced,
`Mut(Transform { translation: Vec3(NaN, NaN, NaN), rotation: Quat(NaN, NaN, NaN, NaN), scale: Vec3(1.0, 1.0, 1.0) })`

and attempting to further modify it resulted in no change (as expected, given what's happening).

## Additional information

-

**Comment by HackerFoo** [comment]
Why should this be defined?

Using the current or identity rotation is not correct if the up vectors don't match, such as:

```rust
Transform::identity().looking_at(Vec3::ZERO, Vec::Z)
```

**Comment by elfein727** [comment]
You're right, there are an unlimited number of rotations that satisfy those constraints. Perhaps a bit of documentation for those who aren't aware of the effect and what the proper method for doing what they want is (they might just want a default `Transform`)?

**Comment by rparrett** [comment]
While we're here, is this also expected?

```
[examples/3d/lighting.rs:32] Transform::from_xyz(0.0, 5.5, 0.0).looking_at(Vec3::ZERO, Vec3::Y) = Transform {
    translation: Vec3(
        0.0,
        5.5,
        0.0,
    ),
    rotation: Quat(
        NaN,
        NaN,
        NaN,
        NaN,
    ),
    scale: Vec3(
        1.0,
        1.0,
        1.0,
    ),
}
```
