### ISSUE TITLE
Touch release input not working on WASM/Web

### ISSUE THREAD

**Issue by samcarey** [bevyengine/bevy#3752]
## Bevy version

Whichever version is used for the site: I think `main`, currently 514754d6503b2416e5266a24b39c884ab5d90d2f.

## Operating system & version

Firefox on Windows, Chrome on Windows, Firefox on iOS.

## What you did

Go here on a device with a touch screen: https://bevyengine.org/examples/ui/button/.
Touch the button then stop touching it.

## What you expected to happen

When you stop touching it, the displayed text should return to displaying "Button".

## What actually happened

When you stop touching it, the button continues to display "Press", as if you never stopped touching it.

## Additional information

I think this is making it impossible to properly touch buttons with `bevy_egui` on WASM. I first noticed the problem when touching the buttons on this example had no effect, although it does seem to register hover events: https://mvlabat.github.io/bevy_egui_web_showcase/index.html

**Comment by mockersf** [comment]
Could you try with this PR: #3599

**Comment by samcarey** [comment]
> Could you try with this PR: #3599

Yes! That fixes it!

**Comment by forbjok** [comment]
Having the same issue in browser on Android. Will this fix get merged and released in a 0.6 bugfix release?
