### ISSUE TITLE
The ability to create fake windows

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#3754]
## What problem does this solve or what need does it fill?

When writing unit tests for the UI, access to the window is required. But since the tests run in parallel by default, it's impossible to create a real window outside of the main thread. For details, see #1720. 

## What solution would you like?

But for unit testing, a real window is not needed, it is enough to create a fake one. Currently users can add windows manually using [add](https://github.com/bevyengine/bevy/blob/514754d6503b2416e5266a24b39c884ab5d90d2f/crates/bevy_window/src/windows.rs#L10) on `Windows` resource and pass a `Window` struct to it. But to create a `Window` I need to provide [RawWindowHandle](https://github.com/bevyengine/bevy/blob/514754d6503b2416e5266a24b39c884ab5d90d2f/crates/bevy_window/src/window.rs#L212). I would suggest to turn this field into `Option`. This way users will be able to create dummy windows and UI plugins will know necessary stuff, like window size and scale. Currently UI plugins such as Egui work in headless mode, but crashes on any access to context because there is no associated window.

**Comment by bjorn3** [comment]
https://github.com/bevyengine/bevy/pull/3439 implemented a headless mode.

**Comment by Shatur** [comment]
> #3439 implemented a headless mode.

Unfortunately no. I only make it work without renderer in that PR. But there is no "headless window" for now.

**Comment by Wcubed** [comment]
I am looking at implementing this, and was wondering: in bevy_render, the `RenderPlugin` requires a window handle to get a valid drawing surface.
https://github.com/bevyengine/bevy/blob/44d09dc46db356d22f3f232d16398c36db4e3d10/crates/bevy_render/src/lib.rs#L127

When a window doesn't have a handle, we need to skip at least the bits of the RenderPlugin that rely on the handle for information. However, it could mean that resources and such are missing that other components rely on.
We could even forgo adding RenderPlugin in the first place, but that probably breaks even more stuff.

What is your opinion on this? I'm at this point not all to familiar with the rendering side of things to know how much I can "cut out" when there is no window without strange behavior occurring.

**Comment by Shatur** [comment]
> What is your opinion on this?

I think it should work with `RenderPlugin`. We just need to skip everything that relies on this handle.

**Comment by Wcubed** [comment]
It turned out I didn't even need to skip any of the RenderPlugin code, as the `Surface` was already used there as an `Option`.

I can now run an app in a test with almost all of the `DefaultPlugins` added. The only one that messes things up is the `WinitPlugin` which doesn't want to be started in a separate thread.

Being able to do `.add_plugins(DefaultPlugins)`, in a test would be quite nice. As the alternative is to add each plugin (except for the WinitPlugin) separately, and that just makes it a long list :P.

Is there a way to skip the WinitPlugin (without setting the feature flag)? Or would it be better to add an option to the plugin to allow running in a separate thread?

**Comment by bjorn3** [comment]
> Is there a way to skip the WinitPlugin (without setting the feature flag)?

You can use something like `.add_plugins_with(DefaultPlugins, |group| { group.disable::<bevy::winit::WinitPlugin>() });`

> Or would it be better to add an option to the plugin to allow running in a separate thread?

On some platforms the OS requires that the event loop runs on the main thread.

**Comment by Shatur** [comment]
> It turned out I didn't even need to skip any of the RenderPlugin code, as the Surface was already used there as an Option.

Awesome!

> Is there a way to skip the WinitPlugin (without setting the feature flag)?

Sure can: https://github.com/bevyengine/bevy/blob/44d09dc46db356d22f3f232d16398c36db4e3d10/examples/app/without_winit.rs#L6

For unit tests I would recommend to setup minimal set of plugins for each test ([here](https://github.com/gardum-game/gardum/blob/088493837227dfa7c59dfcc29cfe39d633346727/src/characters/cooldown.rs#L88) is how I set things up).
For tests that require a `RenderPlugin` (for example, that runs systems that use `Mesh` or `StandardMaterial`), I create a custom [HeadlessPlugin](https://github.com/gardum-game/gardum/blob/088493837227dfa7c59dfcc29cfe39d633346727/src/test_utils.rs#L33) that adds `RenderPlugin`, but disables GPU.
With the ability to fake windows, we will be able to test UI in similar way. So looking forward to your work.

**Comment by Shatur** [comment]
Solved by ddfafab971e335ce5a47d4e4b3fcf51f124d999f.
