### ISSUE TITLE
Better Way to Distinguish Between UICameraBundle and OrthoGraphicCameraBundle

### ISSUE THREAD

**Issue by chrisburnor** [bevyengine/bevy#3756]
## What problem does this solve or what need does it fill?

Given that UiCameras and GameCameras will serve very different purposes, there should be a queryable way to distinguish between the UiCamera and other Cameras.

## What solution would you like?

A component like `UiCamera` on the UiCamera that would distinguish it from other Orthographic camera(s)

## What alternative(s) have you considered?

Current workaround is to query on the presence of the `Frustum` component, but that is brittle, as it relies on an implementation detail of OrthographicCamera

## Additional context
N/A

**Comment by alice-i-cecile** [comment]
Duplicate of #1854 :) It's a good and important idea!

**Comment by chrisburnor** [comment]
No idea how I missed that one. Will follow #1854 !
