### ISSUE TITLE
Shader compilation errors are cryptic

### ISSUE THREAD

**Issue by luke-biel** [bevyengine/bevy#3760]
## What problem does this solve or what need does it fill?

During wgsl shader compilation errors that bevy emits are only partial. Compare:
```
2022-01-24T15:17:42.140124Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader: 
error: 


```
to `naga` equivalent:
```
error:

Entry point vertex at Vertex is invalid:
	Argument 0 varying error
	Entry point arguments and return values must all have bindings
```
when missing `[[builtin(vertex_index)]]` in `fn vertex(vertex_index: u32) -> VertexOutput {`

or
```
2022-01-24T15:24:32.360440Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader: 
error: 
  ┌─ wgsl:8:9
  │
8 │     if (vertex_index == 0) {
  │         ^^^^^^^^^^^^^^^^^ naga::Expression [4]

```
vs `naga`:
```
error:
  ┌─ static_grid_copy.wgsl:8:9
  │
8 │     if (vertex_index == 0) {
  │         ^^^^^^^^^^^^^^^^^ naga::Expression [4]

Entry point vertex at Vertex is invalid:
	Expression [4] is invalid
	Operation Equal can't work with [1] and [3]
```
when trying to compare u32 vs signed value.

## What solution would you like?

I'd like last part provided by `naga` that describes what's happening to be attached along with rest of the error.

## Additional context

https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/render_resource/pipeline_cache.rs#L463
looks identical to 
https://github.com/gfx-rs/naga/blob/master/cli/src/main.rs#L500

In `naga` there's second function https://github.com/gfx-rs/naga/blob/master/cli/src/main.rs#L150 that prints remainder of the error. Simply copy pasting `print_err` body expanded my error to:

```
2022-01-24T15:24:32.342290Z ERROR naga::valid::expression: Right: Constant([1]) of type Scalar { kind: Sint, width: 4 }    
Entry point vertex at Vertex is invalid: 
	Expression [4] is invalid
	Operation Equal can't work with [1] and [3]
2022-01-24T15:24:32.360440Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader: 
error: 
  ┌─ wgsl:8:9
  │
8 │     if (vertex_index == 0) {
  │         ^^^^^^^^^^^^^^^^^ naga::Expression [4]
```
which is sufficient.

I can provide a PR if this is acceptable solution.

**Comment by jakobhellermann** [comment]
There's a PR that includes the causes in the error message: <https://github.com/bevyengine/bevy/pull/3724>.

**Comment by luke-biel** [comment]
Missed that. Great news then :)

**Comment by mockersf** [comment]
#3724 has been merged, is it ok for you now?
would #3675 also improve error reporting?

**Comment by luke-biel** [comment]
In this issue I focused purely on #3724. #3675 isn't directly connected to problems I had so I'm gonna close the issue.

**Comment by ErichDonGubler** [comment]
In case anybody still thinks that errors are cryptic, like we on the Firefox team do, we're planning on doing some work to make diagnostics nicer: https://github.com/gfx-rs/naga/issues/2317
