### ISSUE TITLE
Texture transparent with base colored teint on a sprite Bevy 0.6

### ISSUE THREAD

**Issue by pyweeker** [bevyengine/bevy#3804]
Hello, could you update your answer for Bevy 0.6 from discussion

https://github.com/bevyengine/bevy/discussions/2869
https://github.com/bevyengine/bevy/pull/3202/commits/fc70c20a8147eb096ac635385aa1b4c842591d8f

and give it in bevy/examples/2d/

please ?

**Comment by NiklasEi** [comment]
Are you looking for something like this: https://github.com/bevyengine/bevy/blob/main/examples/2d/contributors.rs#L205?

**Comment by pyweeker** [comment]
You are right.
a snippet to hover one bird and select it by clicking on it without using  UI button ?
