### ISSUE TITLE
Window and WindowDescriptor should specify present_mode instead of vsync

### ISSUE THREAD

**Issue by aloucks** [bevyengine/bevy#3807]
## What problem does this solve or what need does it fill?

Allow the user to control the present mode rather than interpreting it. A boolean value for `vsync` allows for two options where as the actual `PresentMode` has three: `Mailbox`, `Fifo`, and `Immediate`.

## What solution would you like?

Replace `vsync: bool` with `present_mode: wgpu::PresentMode` on `Window` and `WindowDescriptor`. 

## What alternative(s) have you considered?

There is currently no way to use `PresentMode::Mailbox`.

## Additional context

I'll submit a PR for the change if it's welcomed. I think the default should remain `Fifo` and documentation can be added to describe that `Fifo` represents `vsync = true`.

**Comment by alice-i-cecile** [comment]
Neat, this seems like a reasonable suggestion. I'm on board with this change, especially if it's accompanied by good docs.
