### ISSUE TITLE
Gamepads::register and deregister methods should be public

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3808]
## What problem does this solve or what need does it fill?

Gamepad registration and deregistration methods are not pub, making it challenging to write realistic external unit tests for libraries that extend the input methods.

In addition, this makes alternative approaches to gamepad management 

A full app can be generated, and then 

## What solution would you like?

Make `register` and `deregister` methods on `Gamepads` resource `pub`.

## What alternative(s) have you considered?

1. Use workaround methods that assume a fixed gamepad ID, and test those. This is limiting and flaky.
2. Make the entire `HashSet` field public. This is less clear, and more limiting in the future.
3. Create a public method on `Gamepads` to handle gamepad events, and use that in `gamepad_connection_system`. This is less direct and clear, and more of a nuisance when testing.

**Comment by BlondeBurrito** [comment]
Can I pick this up? Seems straight forward and a nice chance to poke around the input crate

**Comment by alice-i-cecile** [comment]
@BlondeBurrito absolutely. Link back to this issue when you open a PR.

**Comment by cart** [comment]
I don't think this is the right direction to take this. The state of `Gamepads` is automatically managed by  `gamepad_connection_system`. The point of the `Gamepads` collection is to contain the exact list of "actually connected" gamepads. Public `register` and `deregister` methods make it possible for app developers (or plugin developers) to invalidate that promise. "Making external unit testing easier" isn't a good enough reason to expose internals. And alternative gamepad management solutions can build their own apis that feed off of Gamepad events.
