### ISSUE TITLE
Fieldless component data should be stored more efficiently

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3834]
## What problem does this solve or what need does it fill?

The data of Zero-Sized Type (ZST) components is always the same. We currently store it in the ECS regardless, and track changes to it.

## What solution would you like?

ZST components are stored as sparse-set components by default: they should almost never appear in the first query parameter, so faster insertion / removal speed is more valuable. The only exception is `Option<&Marker>`, which may be feasible to special-case.

## What alternative(s) have you considered?

Don't store the data at all: instead, generate a new ZST each time they're asked for.

This breaks change and addition detection completely, as there's no place to put the time stamps. Change detection itself is very niche on ZST (you can use it as a minimal event flag...), but addition detection is critical. 

## Additional context

Opt-out change detection would help reduce the overhead of these types, and should be disabled on them by default.

**Comment by alice-i-cecile** [comment]
> [1:20 PM] nile 🧪: BlobVecs spend less memory on zst s than sparse sets would
> [1:20 PM] nile 🧪: blobvecs, for zsts, spend zero bytes per element
> [1:21 PM] nile 🧪: with a sparse set, you'd pay one byte per entity, regardless of if that entity has the marker or not
TIL.

**Comment by colepoirier** [comment]
@alice-i-cecile to clarify, do we currently use BlobVecs as @TheRawMeatball was talking about in the discord messages you posted?

**Comment by alice-i-cecile** [comment]
Yes. We use those for the table stored components.
