### ISSUE TITLE
Add non-circular docs to `ClearColor`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3837]
## How can Bevy's documentation be improved?

[ClearColor](https://docs.rs/bevy/0.6/bevy/core_pipeline/struct.ClearColor.html) helpfully explains that it is the "Resource that configures the clear color". Unfortunately, this doesn't help users who don't know what a "clear color" is, and thus may be looking at these docs.

More helpfully:

> It’s the color that is used when you clear the screen between frames.

This color appears as the "background" color for simple apps, when there are portions of the screen with nothing rendered over top.

**Comment by mockersf** [comment]
fixed by #3842
