### ISSUE TITLE
examples run fail  tips Unable to find a GPU! Make sure you have installed required drivers!

### ISSUE THREAD

**Issue by littlekite** [bevyengine/bevy#387]

**Comment by schrauf** [comment]
Hi,
I ran into the same issue, had to install some drivers:
followed instruction [here](https://software.intel.com/content/www/us/en/develop/articles/enabling-vulkan-vk-intel-performance-query-extension-in-ubuntu.html) (I have Intel integrated graphics).

In particular this line:
```sudo apt-get install git libvulkan1 mesa-vulkan-drivers vulkan-utils ```

Hope it help folks in the same situation (beware I don't have much idea).
