### ISSUE TITLE
Consider building a Material abstraction

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#39]
I was hoping this wouldn't be necessary because I like the simplicity of the current process: "define data struct", "derive RenderResources", "register Asset". The ShaderDefs system also helps cover a huge portion of the "traditional material featureset". However there are common aspects of a material (such as a transparency flag), that cannot be encoded as a uniform or shader def. I have two ideas so far:

* Build a Material<T> wrapper that contains the "common fields"
* Provide an optional Material interface that material types can implement

**Comment by alice-i-cecile** [comment]
This is done now.
