### ISSUE TITLE
Windows users unable to use bevy/dynamic at all on latest

### ISSUE THREAD

**Issue by BrainBacon** [bevyengine/bevy#3907]
## Bevy version
0.6.0

## Operating system & version

Windows 10

## What you did

Run `-features=bevy/dynamic` on stable rust.
Attempt to compile on nightly.

## What you expected to happen

Windows users should be able to use bevy/dynamic on latest.

## What actually happened

Running `-features=bevy/dynamic` on stable or Rust will fail. In stable there is the [LNK1189 error](https://github.com/bevyengine/bevy/issues/1110).

On nightly compilation will fail because of the [unreachable format error](https://github.com/bevyengine/bevy/pull/3889).

## Additional information

`-Zshare-generics=off` is not available on stable, so we currently can't run there, then nightly is unavailable until that PR is part of a release.

As it stands I don't see a way to use dynamic features at all on Windows using latest.

**Comment by BrainBacon** [comment]
I realize this is a duplicate of both #1110 and the PR fixed in #3889 but together they cause this catch 22.

**Comment by alice-i-cecile** [comment]
@cart this is a good argument to cut 0.6.1 with that fix IMO.

**Comment by alice-i-cecile** [comment]
We're planning to release 0.6.1 to backport this fix. I'm going to close this out because it's fixed on `main`.

**Comment by mrchantey** [comment]
I'm on Windows 10 with Bevy 0.7 and no luck:

```
...  
= note: LINK : fatal error LNK1189: library limit of 65535 objects exceeded
error: could not compile `bevy_dylib` due to previous error
```

**Comment by CaptainOachkatzl** [comment]
> I'm on Windows 10 with Bevy 0.7 and no luck:
> 
> ```
> ...  
> = note: LINK : fatal error LNK1189: library limit of 65535 objects exceeded
> error: could not compile `bevy_dylib` due to previous error
> ```

same setup and error for me

**Comment by alice-i-cecile** [comment]
Actually; keeping this closed. #1110 is the place for ongoing discussions.
