### ISSUE TITLE
Module-style doc strings for examples

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3951]
Every example should have a consistent, basic description of what it does.

IMO, the cleanest way to do this is to use the following style at the beginning of each example .rs file:

```rust
//! This example demonstrates how to do something really cool with Bevy
//! Check out all of the [`Structs`] and [`Traits`] it uses

use bevy::prelude::*;
use bevy::ecs::SomethingSpecial;

fn main(){
   App::new()
   .add_system(do_cool_things)
   .run()
}
```

If you would like to tackle this issue, please go through each example and add / move the description to this format.

**Comment by Nilirad** [comment]
I did a search pass on open PRs adding new examples and posted a comment pointing to this issue (with some suggestions sometimes).

**Comment by alice-i-cecile** [comment]
Closed by #4438.

**Comment by tigregalis** [comment]
Out of interest, is there any first-class support for Module-style doc strings for examples in Rust(Rustdoc)? (If there isn't, there should be)

**Comment by alice-i-cecile** [comment]
Hmm, I'm not immediately sure! Try building the repo docs locally with `cargo doc` and see what shows up.

**Comment by Nilirad** [comment]
@tigregalis AFAIK, cargo doc can't render docs for examples. Using barebones rustdoc you should be able to do that, but I never did that.
