### ISSUE TITLE
Compute Shader Integration

### ISSUE THREAD

**Issue by Ku95** [bevyengine/bevy#3970]
## What problem does this solve or what need does it fill?

For now Bevy does not have a dedicated compute pipeline abstraction, but only exposes the raw wgpu API for this use case.
The [game of life example](https://github.com/bevyengine/bevy/blob/main/examples/shader/compute_shader_game_of_life.rsl) shows how to implement your own compute pipelines.

Currently there is no way to use Bevy's shader abstraction(shader defs, shader imports and hot shader reloading) for compute, which makes writing those shaders quite cumbersome. 

## What solution would you like?

I would like to have a way of turning a `Handle<Shader>` into a `ShaderModule`, which can be use for creating the compute pipeline.
For the render pipelines we use a `RenderPipelineCache`, which intern stores a `ShaderCache`, for processing the shaders.
We probably need something similar for compute pipelines (`ComputePipelineCache`), or we decouple the `ShaderCache` entirely from the `RenderPipelineCache` to cache all shaders in a single place (resource).

**Comment by cart** [comment]
Agreed. I think we should heavily consider renaming RenderPipelineCache to PipelineCache and extending it to include compute pipelines. Render and Compute pipelines could (and should) both utilize the same LayoutCache and ShaderCache. It would be a pretty nasty UX reduction to break those out / force users to contend with passing them around directly.

The only missing piece here is adding a higher level ComputePipelineDescriptor (that largely mirrors our RenderPipelineDescriptor) and wiring that up to the PipelineCache.

**Comment by Ku95** [comment]
Sounds reasonable, I will try taking a stab at it .
