### ISSUE TITLE
Demonstrate how to run a schedule directly in `Schedule` docs

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3980]
## How can Bevy's documentation be improved?

[Schedule](https://docs.rs/bevy/latest/bevy/ecs/schedule/struct.Schedule.html) is a powerful tool for advanced users of bevy_ecs. The docs should be clear that you can add systems to it (by adding a stage as part of it), initialize those systems and then run them directly on the `World`.

**Comment by vedant-z** [comment]
@alice-i-cecile I want to work on this but I am completely blank of what needs to be done and how 

A little help would be appreciated ☺️

**Comment by remiCzn** [comment]
Hi @alice-i-cecile! Is it still needed? I'm working on this, so if yes, I'll create a draft PR with my work.

**Comment by alice-i-cecile** [comment]
This is an increasingly important pattern, so if you have ideas on how to improve the docs I'd love to see a PR :)

**Comment by remiCzn** [comment]
I just opened a PR, don't hesitate to suggest me things about what you were expecting.
