### ISSUE TITLE
Add collision prevention to `HandleId::random()`

### ISSUE THREAD

**Issue by BGR360** [bevyengine/bevy#3993]
## Background

<details>
<summary>Background</summary>

At the time of writing the Bevy version is 0.6.1.

Here is the implementation of `HandleId::random()`: https://github.com/bevyengine/bevy/blob/544b6dfb8662f589658445ac4c9387918e3e6c1a/crates/bevy_asset/src/handle.rs#L53-L55

Here is where the method is used in `bevy_asset`: https://github.com/bevyengine/bevy/blob/544b6dfb8662f589658445ac4c9387918e3e6c1a/crates/bevy_asset/src/assets.rs#L77-L88

I use this method manually to immediately return a handle to an asset that I will generate asynchronously, and then later use `Assets::set_untracked` to place the generated asset into the collection.

</details>

## What problem does this solve or what need does it fill?

**Problem:** It's possible (although unlikely) for `HandleId::random()` to produce a `HandleId` that is already in use by an existing asset in the `Assets` collection. This would result in overwriting the existing asset rather than adding a new one. This would be confusing for the user and very difficult to root-cause (and nearly impossible to reproduce).

## What solution would you like?

Require users to provide a `&Assets<T>` reference so that collisions can be detected and the dice can be re-rolled:

```rust
fn random<T: TypeUuid>(assets: &Assets<T>) -> Self {
    loop {
        let handle_id = HandleId::Id(T::TYPE_UUID, rand::random());
        if !assets.contains(handle_id) {
            return handle_id;
        }
    }
}
```

## What alternative(s) have you considered?

Implement the suggestion above, but do so as an additional method and call it something like `random_unique()`.

## Additional context

We may well decide that the likelihood of this is so low that it's not worth bothering.

See also a short Discord conversation here: https://discord.com/channels/691052431525675048/749332104487108618/944733810577264720

**Comment by mockersf** [comment]
I think adding the check would be better in https://github.com/bevyengine/bevy/blob/544b6dfb8662f589658445ac4c9387918e3e6c1a/crates/bevy_asset/src/assets.rs#L81-L88

**Comment by bjorn3** [comment]
That will not help `set()` with `HandleId::random()`.

**Comment by aloucks** [comment]
The whole point of v4 (random) UUIDs is so you don't to perform these kinds of checks, assuming that you don't cripple your entropy. 

https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random)

> For example, the number of random version-4 UUIDs which need to be generated in order to have a 50% probability of at least one collision is 2.71 quintillion, computed as follows:[[22]](https://en.wikipedia.org/wiki/Universally_unique_identifier#cite_note-22)
> 
> <img src="https://render.githubusercontent.com/render/math?math={\displaystyle n\approx {\frac {1}{2}}+{\sqrt {{\frac {1}{4}}+2\times \ln(2)\times 2^{122}}}\approx 2.71\times 10^{18}.}"/>
> 
> This number is equivalent to generating 1 billion UUIDs per second for about 85 years. A file containing this many UUIDs, at 16 bytes per UUID, would be about 45 [exabytes](https://en.wikipedia.org/wiki/Exabyte).

**Comment by BGR360** [comment]
@aloucks Asset handles don't use UUIDs. They use pseudorandom 64-bit numbers. Generating a UUID for each asset sounds prohibitively expensive.

**Comment by aloucks** [comment]
> @aloucks Asset handles don't use UUIDs. They use pseudorandom 64-bit numbers. Generating a UUID for each asset sounds prohibitively expensive.

Ah, I see it's using the UUID of the Type combined with the random `u64`. My mistake!

**Comment by MalpenZibo** [comment]
It's not an elegant solution but in my engine that it's heavily inspired by bevy I use an `AtomicU64` to manually generate an id instead of `HandleId::random()`.

The idea is to create (using a derive macro) a `static {ASSET_NAME}_COUNTER: AtomicU64 = AtomicU64::new(0)` for each `Asset` and implement the `next_counter` function using that `AtomicU64`.

```rust
pub trait Asset: Downcast + Send + Sync + std::fmt::Debug + 'static {
    fn next_counter() -> u64
    where
        Self: Sized;
}

....

#[proc_macro_derive(Asset)]
pub fn asset_macro_derive(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    
    let name = input.ident;
    let asset_counter = format_ident!("{}_COUNTER", name.to_string().to_uppercase());
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    let expanded = quote! {
        static #asset_counter: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
        impl #impl_generics Asset for #name #ty_generics #where_clause {
            fn next_counter() -> u64
            where
                Self: Sized,
            {
                #asset_counter.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
            }
        }
    };

    TokenStream::from(expanded)
}
```
usage 
```rust
let next_id = TestAsset::next_counter();
let handle_id = HandleId::new_from_u64::<TestAsset>(next_id);
```

**Comment by james7132** [comment]
HandleId no longer exists, and `AssetId`, there is no randomized initialization option anymore. Is this issue still relevant?

**Comment by BGR360** [comment]
Sounds like no
