### ISSUE TITLE
Transparency should be per material/draw-call

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#40]
Transparency is currently per-entity (Draw::is_transparent), but this breaks down when an entity has multiple materials or draw calls. I _think_ it makes sense to somehow plug this in to the Draw component.

Currently the `Draw` component is a flat list of low level render commands. Maybe it could be grouped by draw call and paired with additional draw config?

**Comment by IceSentry** [comment]
Is this still relevant? I'm pretty sure transparency is done separately now. Unless I misunderstand the description.

**Comment by superdump** [comment]
Closing as we have per/material alpha blending stuff.
