### ISSUE TITLE
Yet another GPU issue (backend=gl, no Vulkan)

### ISSUE THREAD

**Issue by raimundomartins** [bevyengine/bevy#4025]
## Bevy version

v0.6.0/v0.6.1

## Operating system & version

Voidlinux with nvidia-390 (no Vulkan support)

## What you did

`WGPU_BACKEND=gl cargo run --example breakout`

## What you expected to happen

The example runs properly

## What actually happened

`thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!'`

## Additional information

Naturally, I have drivers installed and working properly, I can run games in this setup.

**Comment by alice-i-cecile** [comment]
Do the examples here work for you? https://github.com/gfx-rs/wgpu 

If not, please file an issue upstream and link to this one from there :)

**Comment by raimundomartins** [comment]
Apparently the nvidia GPU is not even detected. Created issue https://github.com/gfx-rs/wgpu/issues/2507

**Comment by mockersf** [comment]
closing to centralise in #3191
