### ISSUE TITLE
linux user requirements

### ISSUE THREAD

**Issue by wotori** [bevyengine/bevy#4031]
For Ubuntu users I found that two packages doesn't installed by default so we need them before made this command work 
`cargo run --example breakout`
It'll be good to have "troubleshot" or "required packages" for each operation system where user will find steps how to quick start with bevy

```
sudo apt-get install -y libudev-dev
sudo apt install librust-alsa-sys-dev
```

**Comment by jakobhellermann** [comment]
Yup, this is documented in [docs/linux_dependencies.md](https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md) and linked to the the setup docs: <https://bevyengine.org/learn/book/getting-started/setup/>

**Comment by bjorn3** [comment]
librust-alsa-sys-dev is not used in any way by cargo. It is an artifact of how debian and derivatives handle building rust programs on their build servers. This package contains the source of the alsa-sys crate. Cargo downloads it from the internet if you don't explicitly tell it to use the source in this package.

**Comment by CptPotato** [comment]
It's a bit "hidden", but there's [`docs/linux_dependencies.md`](https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md).

I wasn't aware of this at first, too. I think it should probably be linked somewhere in `readme.md`.
