### ISSUE TITLE
#[derive(Bundle)] should support sub bundles

### ISSUE THREAD

**Issue by CAD97** [bevyengine/bevy#4058]
## What problem does this solve or what need does it fill?

The following code shape should work:

```rust
#[derive(Bundle)]
struct PhysicsSpriteBundle {
    sprite: SpriteBundle, // impl Bundle
    rigid_body: RigidBody, // impl Component
    collision: CollisionShape, // impl Component
}
```

## What solution would you like?

Use [autoref specialization](https://github.com/dtolnay/case-studies/blob/master/autoref-specialization/README.md) (or [autoderef specialization](https://lukaskalbertodt.github.io/2019/12/05/generalized-autoref-based-specialization.html)) to appropriately either use the field `impl Component` directly or recurse into the field `impl Bundle`.

## What alternative(s) have you considered?

- Put the components from the "sub bundle" directly into the new bundle.
- Use setup system instead of bundle.
- Use plugin instead of bundle.

## Additional context

Ran into during Bevy Jam #​1. Bevy 0.6.1.

**Comment by alice-i-cecile** [comment]
Are you aware of the #[bundle] field annotation? Will that meet your needs?

Also #2974 will solve this directly.

**Comment by CAD97** [comment]
Ah, I didn't see that, I'm sort of moving too fast in jam mode 🙃

It's nice to see that this is already sort of planned to end up just working, though!

I'm closing this, as the direct request is served by the bundle attribute.
