### ISSUE TITLE
Wireframe rendering & Debug lines

### ISSUE THREAD

**Issue by Neo-Zhixing** [bevyengine/bevy#409]
While developing games, it would be tremendously helpful to have mesh wireframes & debug lines.

We should be able to enable wireframe rendering easily. In the mean time, there could be a separate `DebugLinesComponent` similar to [Amethyst's implementation](https://docs.amethyst.rs/stable/amethyst_rendy/debug_drawing/struct.DebugLinesComponent.html) for drawing debug lines manually.

We should be able to mark the type of the debug line so that it is possible to enable or disable the rendering of a specific type of debug line globally.

**Comment by verzuz** [comment]
add `polygon_mode: PolyonMode` to `RasterizationStateDescriptor` to allow drawing wireframes 336d070b260591e546ad9372f6423e0be6afbe97
Commit date:	1 week ago (09.09.2020 21:34:37)
was added to wgpu https://github.com/gfx-rs/wgpu - we might use that?

**Comment by Neo-Zhixing** [comment]
@verzuz This is great news! Yeah wgpu didn't allow us to set the ploygon mode, and it was a major blocker. Now that this was added we can start to look into wireframes and debug lines!

**Comment by Neo-Zhixing** [comment]
blocked by #542

**Comment by alice-i-cecile** [comment]
Nice functionality for debug lines currently exists in [bevy_mod_raycast](https://lib.rs/crates/bevy_mod_raycast). This is a helpful stopgap, and worth looking at for when we want to include this functionality natively.

**Comment by lassade** [comment]
Hey a bit of shameless self promotion I'm working on a crate to implement debug gizmos (bevy_gizmos)[https://github.com/lassade/bevy_gizmos] I got many features working as well as debug lines, thers also other crate liked in,

`bevy_mod_raycast` have debug lines?
