### ISSUE TITLE
Add example for grabbing the mouse

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4094]
## How can Bevy's documentation be improved?

Demonstrate [how to grab the mouse / lock the cursor] in a small example.

**Comment by emersonmx** [comment]
Hello 👋🏻 

Lately I've been creating examples of Bevy's features as a study. And one of the examples that was in my backlog was about grabbing the cursor.
https://github.com/emersonmx/sandbox/blob/main/rust/bevy/simple_mouse_grab/src/main.rs

If it works for this issue, I can open a PR with the example I made.

**Comment by alice-i-cecile** [comment]
@emersonmx that looks great! Please open that PR and link this issue :)
