### ISSUE TITLE
TextComponents Artifacts

### ISSUE THREAD

**Issue by TheNeikos** [bevyengine/bevy#412]
I was trying out a font ([Bungee Inline Regular](https://fonts.google.com/specimen/Bungee+Inline?category=Display&preview.text=1234567890&preview.text_type=custom)) and saw that it drew with weird artifacts:

![image](https://user-images.githubusercontent.com/1631166/91869807-d5bce580-ec65-11ea-94ba-7a38bcbb0454.png)

I feel like that is a bug, here is how I drew it: 

```rust
        .spawn(TextComponents {
            style: Style {
                align_self: AlignSelf::FlexEnd,
                ..Default::default()
            },
            text: Text {
                value: "Hello!".to_string(),
                font: font_handle,
                style: TextStyle {
                    font_size: 50.0,
                    color: Color::WHITE,
                },
            },
            draw: Draw {
                is_transparent: true,
                ..Default::default()
            },
            ..Default::default()
        })
```
The `is_transparent` does not change the artifacts on my machine.

I am running on an up-to-date Archlinux with a "NVIDIA Corporation GP107GLM [Quadro P620]" graphics card.

**Comment by TheNeikos** [comment]
This seems to be related to #419, as when `Msaa { samples: 1 }` is used, then the artifacts do not appear.

**Comment by Cupnfish** [comment]
![QQ截图20200923184528](https://user-images.githubusercontent.com/40173605/94003083-5c7c6280-fdcd-11ea-89eb-5f61f3e554d2.png)
I think this is a platform-related issue, I did not encounter the situation you mentioned on win10.
I tried several situations(`Msaa { samples:1 }`、`Msaa { samples:4 }`、`Msaa { samples:8 }`), none of your situation.

**Comment by nicopap** [comment]
Bevy's rendering and text rendering changed so much since this issue, and no further similar issues rose up, it is therefore very unlikely to still be a problem. I'm closing this.
