### ISSUE TITLE
BorderlessFullscreen, and Fullscreen { use_size: false } window modes not working

### ISSUE THREAD

**Issue by forbjok** [bevyengine/bevy#414]
When supplying a WindowDescriptor resource with mode set to either BorderlessFullscreen or Fullscreen { use_size: false }, the project will still compile and run but only display a large white rectangle instead of the actual game content.

Here's a minimal reproduction project: [bevy-borderless-bug-repro.zip](https://github.com/bevyengine/bevy/files/5158277/bevy-borderless-bug-repro.zip)
(using the current 0.1.3 release of bevy)

Expected output always (as shown with window mode set to Windowed):
![bevy-borderless-bug-repro_CLgYREQDpl](https://user-images.githubusercontent.com/4687674/91894549-29dfbe00-ec96-11ea-8529-7d4cd0cf64eb.png)

Actual output with BorderlessFullscreen or Fullscreen { use_size: false }:
![bevy-borderless-bug-repro_PmL0mZbBXA](https://user-images.githubusercontent.com/4687674/91894571-3106cc00-ec96-11ea-8aa7-8637556c2989.png)

The same result can be observed by adding a WindowDescriptor resource with either of the broken modes to the Breakout example in the current bevy master branch, so this is not specific to my test project.

**Comment by scriptandcompile** [comment]
looks like #278 popping up again. Need to go through #65 and #69 discussions still.

**Comment by akien-mga** [comment]
I think I have a similar issue by running the `window_settings.rs` example with bevy 0.2.1 on Linux, Plasma desktop with KWin/X11.

My screen is 4K but configured to use 1920x1080p, when I run the `window_settings` example (which uses `Fullscreen { use_size: false }`), my display goes back to 4K but the active desktop area is only the top-left quarter (1080p).
The actual Bevy window is not visible, and none of the desktop elements can be interacted with. I have to go to tty2 and then back to tty1 to fix it, which lets me kill the Bevy app and then tweak the KDE system settings to go back to properly using the full monitor size in 1080p.

Removing the custom `window_mode` from the example fixes the issue.

(If this would be better suited as it's own issue, please tell me.)

**Comment by cart** [comment]
The example is now "fixed" until we can sort out a real solution.

**Comment by alice-i-cecile** [comment]
This seems to have been fixed; please reopen this if you can reproduce it.
