### ISSUE TITLE
Move dynamic plugin loading to its own crate

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#415]
Currently we are utilizing features to selectively enable/disable dynamic plugin loading code throughout the bevy codebase. @Dispersia had the good idea to move this to a separate crate, which I think should be possible. This would simplify the cargo features and move all of the dynamic plugin loading code to one spot.

**Comment by EthanYidong** [comment]
#544 
I've moved all the code that requires `libloading` to a separate crate, but I'm not sure how to test the changes as none of the examples make use of dynamic loading. Could someone help me figure out how to test these changes?

**Comment by CleanCut** [comment]
I think this can be closed now that #544 has been merged.
