### ISSUE TITLE
Missing Web/WASM example

### ISSUE THREAD

**Issue by emilk** [bevyengine/bevy#4151]
https://bevyengine.org/ mentions Web as a supported platform, but I cannot find an example of how to use Bevy on the web (i.e. in WASM). There is also no mention of web in [the book](https://bevyengine.org/learn/book).

There is an example at https://github.com/bevyengine/bevy/tree/main/examples/wasm but without any documentation or code.

What I'd like is a small, simple project with instruction on how to compile to WASM and an `index.html` that loads that WASM.

**Comment by DJMcNab** [comment]
There are some instructions in https://github.com/bevyengine/bevy/blob/main/examples/README.md#WASM .

Do these provide what you need?

**Comment by emilk** [comment]
Yes they do! Thank you for pointing me in the right direction @DJMcNab ❤️
