### ISSUE TITLE
multiple_windows example is broken

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#4167]
It panics with:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/bevy_pbr/src/render/light.rs:996:43
```

This is a regression introduced recently by #3968
@robtfm @superdump

**Comment by cart** [comment]
I'm thinking this is because the window doesn't exist yet for the first frame that the secondary camera is spawned, which results in a "default" screen size of `(0, 0)` in the cluster assignment algorithm / cluster assignments being skipped. Seems like a "corner case" that we missed in #3968. I'm guessing this would also be a problem for single window scenarios that behave the same way.

**Comment by superdump** [comment]
Ouch!

**Comment by superdump** [comment]
Did you see:
* https://github.com/bevyengine/bevy/pull/4148

and does that fix it?

**Comment by cart** [comment]
I would not expect it to, as that only touches `update()` and the "core" issue is that update() isn't called because we "skip" it.
