### ISSUE TITLE
Expose `.with_class()` in `WindowDescriptor` after new winit release to allow setting window class on X11 and app_id on Wayland.

### ISSUE THREAD

**Issue by heavyrain266** [bevyengine/bevy#4188]
## What problem does this solve or what need does it fill?

Field `.with_app_id()` is used to set App's ID to be accessed by Compositor to e.g. set specific rules for given window or group of windows under same id, for example enabling/disabling server-side opacity, disabling CSD, hardcoding tag/workspace on startup, setting position etc.

## What solution would you like?

```rs
use bevy::prelude::*;

fn main() {
    App::new()
        .insert_resource(
            WindowDescriptor {
                title: "Game Title".into(),
                // Value should be not have spaces, can be e.g. org.bevy.gameTitle (like in GTK) or anything else.
                app_id: "game_title".into(),
            
               ..Default::default()
            }
        )
        .run();
}
```

## What alternative(s) have you considered?

None.

## Additional context

For now, every bevy game have `app_id` exposed as `<NULL>`, there are programs like [lswt](https://git.sr.ht/~leon_plickat/lswt) or [waylevel](https://git.sr.ht/~shinyzenith/waylevel) for querying info about connected clients and their `app_id`, programs like that may not work under KDE/GNOME if they don't implement protocols which allow clients to query such info from Compositor.

**Comment by mockersf** [comment]
relevant winit api: https://docs.rs/winit/latest/winit/window/struct.WindowBuilder.html#method.with_app_id. This should be feature gated on wayland

**Comment by bjorn3** [comment]
Why should it be feature gated on wayland? It would be much easier to allow it on all platforms and just pass it to winit on unix. In addition while winit currently only uses it on wayland, other OSes do have a similar concept. For example macOS has the bundle id. And gtk has an application id that is used for wayland and for remote control using dbus. In addition things like the `RegisterClient` method of the `org.Xfce.Session.Manager` dbus interface also require an app id for session management.

**Comment by mockersf** [comment]
Maybe, but the method is written has working only on wayland. Otherwise we should expose the `canvas` option on all platforms too I guess.

**Comment by HeavyRain266** [comment]
> Why should it be feature gated on wayland? It would be much easier to allow it on all platforms and just pass it to winit on unix. In addition while winit currently only uses it on wayland, other OSes do have a similar concept. For example macOS has the bundle id. And gtk has an application id that is used for wayland and for remote control using dbus. In addition things like the `RegisterClient` method of the `org.Xfce.Session.Manager` dbus interface also require an app id for session management.

I don't really know how other systems handle that kind of feature, I'm not really interested in GTK becUse it's does everything in weird way just like GNOME itself, X11 doesn't even have any documentation other than XML file with general implementation, as well as Xorg's 400k lines of code.

**Comment by HeavyRain266** [comment]
Future winit release will include unified `.with_class` method which is used to set window class on X11 and app_id on Wayland. We should expose that one instead.

**Comment by kchibisov** [comment]
New winit will have unified call `with_name` on unix to set class/app_id.
