### ISSUE TITLE
glxgears works but bevy cant find my gpu

### ISSUE THREAD

**Issue by lizelive** [bevyengine/bevy#4199]
## Bevy version
0.6
The release number or commit hash of the version you're using.

## Operating system & version

Ubuntu 20.04 in docker [.devcontainer](https://code.visualstudio.com/docs/remote/create-dev-container) https://github.com/lizelive/try-bevy/tree/main/.devcontainer
Nvida gpu

## What you did

[install docker + nvida container toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker)
[install remote](https://code.visualstudio.com/docs/remote/remote-overview)
[clone](https://github.com/lizelive/try-bevy/)

## What you expected to happen

if `glxgears` works `cargo run` should work

## What actually happened

```
thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.6.1/src/renderer/mod.rs:74:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Additional information
- used [bevy_game_template](https://github.com/NiklasEi/bevy_game_template) with no changes
- [wgpu](https://github.com/lizelive/try-bevy/tree/main/wgpu) works
- this .devcontainers are really popular and save ton of money
- allows going back to old project and have just work

```
vscode ➜ /workspaces/try-bevy (main ✗) $ glxinfo -B
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 10240 MB
    Total available memory: 10240 MB
    Currently available dedicated video memory: 8451 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 3080/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 510.47.03
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 510.47.03
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 510.47.03
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by mockersf** [comment]
closing to centralise in #3191
