### ISSUE TITLE
Feature render depends on bevy_ui

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#4202]
## Bevy version

0.6.1

## Operating system & version

Archlinux

## What you did

```toml
[dependencies]
bevy = { version = "0.6", default-features = false, features = ["render"] }
```

## What you expected to happen

Feature `render` does not depend on `bevy_ui`.

## What actually happened

`cargo tree` shows that `bevy_ui` depends on `bevy_internal` which is required by Bevy. My `Cargo.lock`:

``` toml
[[package]]
name = "bevy_internal"
version = "0.6.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "f92af28d95bba80d11840c24fa4ce8ff84ae27af1def2f5cf8a6891acce5d714"
dependencies = [
 "bevy_app",
 "bevy_asset",
 "bevy_core",
 "bevy_core_pipeline",
 "bevy_derive",
 "bevy_diagnostic",
 "bevy_ecs",
 "bevy_gltf",
 "bevy_input",
 "bevy_log",
 "bevy_math",
 "bevy_pbr",
 "bevy_reflect",
 "bevy_render",
 "bevy_scene",
 "bevy_sprite",
 "bevy_tasks",
 "bevy_text",
 "bevy_transform",
 "bevy_ui",
 "bevy_utils",
 "bevy_window",
 "ndk-glue",
]
```

**Comment by Shatur** [comment]
Oh, so its intended? Thanks for the explanation. I think I should send a lot of PRs to other crates then.

**Comment by mockersf** [comment]
> I think I should send a lot of PRs to other third-party plugins then.

I try to do that when trying a new plugin, you're welcome in joining the fight for minimal dependencies!
