### ISSUE TITLE
`.just_released()` is `true` on every frame `.release()` is called instead of just the first.

### ISSUE THREAD

**Issue by cdbfoster** [bevyengine/bevy#4208]
## Bevy version

0.6.1

## What you did

Calling `.release()` on an `Input<T>` multiple frames in a row causes `.just_released()` to be true each frame.  This is in opposition to calling `.press()` on that same input multiple frames in a row, which causes `.just_pressed()` to be true only on the first frame.

This appears to be because `.press()` checks the `.pressed` set before insertion into the `.just_pressed` set, whereas `.release()` does not.

## What you expected to happen

I expected `.just_released()` to return true on only the first frame, like `.just_pressed()`.

## Other thoughts

Is there a reason for this behavior that I'm missing?  If so, it's a bit of a gotcha, and should be documented, at least.  If not, it should be a very simple fix to bring the `.release()` behavior in line with `.press()`.  I'd be happy to submit a PR if that's the case.

**Comment by alice-i-cecile** [comment]
This seems like a clear bug to me. PR please :)

**Comment by mockersf** [comment]
> Is there a reason for this behavior that I'm missing?

I think mostly that all the input devices that were tested sends the `Release` event only once, while they can send the `Press` event a few time in case of a long press. Out of curiosity, do you have a device that sends multiple `Release` event when a button is released?

**Comment by cdbfoster** [comment]
Ah, I see.  No, I don't, but while writing an intermediate `Input` type for player actions that I can collect from my (potentially heterogeneous) input devices, I found I wished I could call `release()` multiple times without worrying about it.
