### ISSUE TITLE
Unable to find integrated UDH 620 GPU

### ISSUE THREAD

**Issue by celtichawk** [bevyengine/bevy#4228]
I'm running into the 'unable to find gpu' issue when trying to run a project. I've been trying to fix this with the developer but to no avail so figured I'd check here as well

I can run other things that need my Intel UDH 620 GPU fine, such as games, other software but Bevy projects fail stating they cannot find the GPU.

I do have the Intel Vulkan drivers installed, running under Arch Linux. Previously, on my last distro these projects ran flawlessly, however I've followed the advice from issues here which is simply to install Vulkan which I have done, but to no avail.

I'm not sure where to go next from here however, I have the needed Intel Vulkan drivers and followed both the advice here, and the Arch wiki and had no luck at all

**Comment by mockersf** [comment]
closing to centralise in #3191
