### ISSUE TITLE
Step-through debugging via a specialized app runner

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4245]
## What problem does this solve or what need does it fill?

When debugging, it's common to want to advance logic one frame (or even system) at a time.

It's not clear to end users how exactly this should be done, and each user ends up re-inventing the wheel.

## What solution would you like?

The most straightforward way to solve this problem is to provide a specialized `debug_runner` that users can set, along with an associated `DebugRunnerPlugin`.

Eventually, this should provide the following functionality:

- Pause and resume the App loop
  - The app should start paused
- The ability to advance the App loop by one schedule pass
- The ability to advance the App loop by one system, logging which system was run
- The ability to adjust the rate of elapsed time (#1343) of the game 
- The ability to add `Breakpoint` system labels to individual systems and advance to the next breakpoint
- The ability to continue to run certain systems while the game is otherwise paused (critical for `bevy_inspector_egui` integration)

These should all be event-triggered, with default customizable hotkeys (stored in a resource).

## What alternative(s) have you considered?

Write more unit tests!

## Additional context

This functionality is obviously very useful for the eventual editor, but should be entirely doable today.

We may want to clean up and refactor the `winit_runner` code to make it more reusable before or during this PR process, as it's currently very monolithic and previous attempts I've seen to modify it have just copy-pasted and tweaked the code.

**Comment by nicopap** [comment]
This should be fixed when/if #8453 gets merged..

**Comment by mgi388** [comment]
@alice-i-cecile https://github.com/bevyengine/bevy/pull/8453 was merged, does this mean the issue can be closed or is nicopap's comment suggesting that this issue is now unblocked now that it's merged? The linked PR has what looks to me like a good setup for enabling system stepping, but I can't tell from reading the OP if there's still a bigger goal that's missing.

**Comment by alice-i-cecile** [comment]
Yep this is effectively done. There's work to be done still in terms of UX, but that will be clearer in follow-up issues.
