### ISSUE TITLE
Create `NonSendLocal` type

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4247]
## What problem does this solve or what need does it fill?

Users sometimes want to store data in system-`Local` storage that is not `Send` or `Sync`.

## What solution would you like?

Allow the storage of `!Send` and `!Sync` types in the `Local`. This will cause the system itself to be nonsend, just like a `NonSend` type parameter. This probably requires the creation of a `NonSendLocal` type.

## What alternative(s) have you considered?

Wrap it in an `Arc<Mutex>`.

**Comment by james7132** [comment]
Tentatively closing this for the same reason as #1719 as the `Local` state being held in `SystemState` types would force all systems to be `!Send`/`!Sync`.
