### ISSUE TITLE
Registering an Event twice causes events to get lost for some systems

### ISSUE THREAD

**Issue by ZainlessBrombie** [bevyengine/bevy#4257]
https://github.com/bevyengine/bevy/blob/fee7a26137689248733b64ce84f17316921c2ab5/crates/bevy_app/src/app.rs#L621

When calling `.add_event::<SomeResource>()` twice for the same resource, e.g. from different Plugins, sometimes some systems no longer receive events.

The reason for this is in the `App::add_event` I think  
`init_resource` on an already registered resource is a no-op, but `add_system_to_stage` is also called twice, causing the system to clear & swap buffers multiple times.

The following Code would alleviate this, I think (still reproducing):
```rust
    pub fn add_event<T>(&mut self) -> &mut Self
    where
        T: Resource,
    {
        if !self.world.contains_resource::<Events<T>>() {
            self.init_resource::<Events<T>>()
                .add_system_to_stage(CoreStage::First, Events::<T>::update_system);
        }
        self
    }
```

Is this sensible?  
I don't know how to make a test case for this - it just happens sporadically after all. Is one needed?

**Comment by alice-i-cecile** [comment]
IMO we should panic with a clear warning, rather than silently succeeding here. Generally when this happens, it's a copy-paste / code migration error.

P.S. Your code logic is flipped: you want `!self.world.contains_resource`  :)

**Comment by ZainlessBrombie** [comment]
> PS: Your code logic is flipped
Oh dear silly me... my reproduction is still compiling, thanks ^^

Hmm I see.  
Thoughs: I think it is reasonable that multiple distant pieces of Code need the same event to be registered. However they could depend on the same Plugin which registers it, making it that other Plugins responsibility.    
If I am not mistaken, Plugins can be registered twice though too, right? I vaguely recall there being an Issue discussing this, but I can't find it.

**Comment by alice-i-cecile** [comment]
> If I am not mistaken, Plugins can be registered twice too though, right? I vaguely recall there being an Issue discussing this, but I can't find it.

Ah right: yes. Typically, this will be done with a generic type parameter, to create related but distinct behavior.

Okay, alright, I think I like your proposed solution then. Open a PR?

**Comment by alice-i-cecile** [comment]
Generally speaking, this is part of #1255: the fact that we're using an unstructured approach to plugins using the builder pattern makes this flavor of error pop up all over the place.

**Comment by ZainlessBrombie** [comment]
> Open a PR

:+1: will do
