### ISSUE TITLE
Failing CI due unavalibity of Azure repositories

### ISSUE THREAD

**Issue by qarmin** [bevyengine/bevy#426]
This was fixed in Godot just by simple removing and replacing it with default Ubuntu repository
https://github.com/godotengine/godot/blob/71833520da2bfa39201bc9734432de47a18aaa14/.github/workflows/linux_builds.yml#L17-L22

and sources file from which is this taken

https://github.com/godotengine/godot/blob/master/misc/ci/sources.list

**Comment by alice-i-cecile** [comment]
No longer relevant, so I'm closing this <3
