### ISSUE TITLE
Add a system closure example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4262]
## How can Bevy's documentation be improved?

Systems can be created through closures. This will be a surprising fact to many, and should be demonstrated in an example.

Steps:
1. Create a "closure_system" example.
2. Demonstrate the use of a simple closure system.
3. Demonstrate configuring `Local` variables with closure systems, as shown in the [corresponding docs](https://dev-docs.bevyengine.org/bevy/ecs/system/struct.Local.html).

Previously attempted in https://github.com/bevyengine/bevy/pull/2231: please try to build off that branch and credit the author.

**Comment by cab** [comment]
Sorry for missing your other comments, and for leaving that PR hanging!

And thank you for picking it up! In case you need anything from that original PR or if it makes anything easier, I've commented on the [licensing thread](https://github.com/bevyengine/bevy/issues/2373#issuecomment-1073128083).

**Comment by alice-i-cecile** [comment]
Awesome; I'll port that over quick.

**Comment by wilk10** [comment]
With #4327 having been merged, can this issue be closed?
