### ISSUE TITLE
GLTF Loader - trouble with blender exports

### ISSUE THREAD

**Issue by Dapeos** [bevyengine/bevy#427]
I must be missing something simple. 
I am able to spawn Suzanne and the other gltf files provided in the assets/models folder just fine. 

However when I try to use a different gltf file it loads them without error however they do not seem to be rendered.

I have tried gltf files exported from Blender as well as from window's 3D Viewer. I have tried very simple meshes including the default cube and ensured UVs and normals exist. I have tried including a material and not. I have tired adding vertex coloring in case it mattered. I tried every export option I could see. 

Not sure what I am missing but if any one has any ideas any help would be appreciated. 
Thanks.

**Comment by cart** [comment]
The current GLTF loader is pretty limited. It only loads the first mesh it finds. More complex multi-mesh files fill break down (among other things).

Could you attach an example of a cube exported from blender that doesn't load?

**Comment by Dapeos** [comment]
Thanks cart, included in the zip are two exported cube gltf files from blender 2.9, one using the embedded option and one using the separate assets option.
 
[frames.zip](https://github.com/bevyengine/bevy/files/5172144/frames.zip)

**Comment by cart** [comment]
This should largely be resolved by #693

**Comment by Nickan** [comment]
Seems like this bug reappear in 0.3, I attach the file which is not showing but no errors.

[char1.zip](https://github.com/bevyengine/bevy/files/5497361/char1.zip)

**Comment by rafalp** [comment]
I'm seeing same problem: I can use blender exported `glb` file for scene, but if I try something as basic as:

```
        .spawn(PbrBundle {
            mesh: asset_server.load("test.glb"),
            ..Default::default()
        })
```

I don't get anything rendered.

**Comment by mockersf** [comment]
```
asset_server.load("test.glb")
```
This load the whole GLB file, not just a mesh

If you're just interested in a mesh, you can target it specifically by adding `#Mesh0/Primitive0` after the file name, check this example:
https://github.com/bevyengine/bevy/blob/f61e44db2824c0cc4b4815748c4d3f051002ada7/examples/asset/asset_loading.rs#L20

Or if you want to display a while scene from the file, check this example:
https://github.com/bevyengine/bevy/blob/f61e44db2824c0cc4b4815748c4d3f051002ada7/examples/3d/load_gltf.rs#L13

**Comment by rafalp** [comment]
Where can I find the definition of the `Scene`? It sounds to me that scene is an entire level, and I've didn't see on `spawn_scene` how I can apply any transforms to the loaded data.

Thank you for helping!

**Comment by mockersf** [comment]
to apply a transform on a scene, you can check this example : https://github.com/bevyengine/bevy/blob/main/examples/3d/update_gltf_scene.rs
