### ISSUE TITLE
Migrate to `encase` from `crevice` for uniform and storage buffer data formatting

### ISSUE THREAD

**Issue by superdump** [bevyengine/bevy#4272]
**Q:** Should we migrate from using vendored `crevice` to using `encase` for formatting of data for uniform and storage buffers?

Noteworthy benefits of `encase`:
* supports runtime-sized `Vec` in the Rust struct types
  * it has validation to ensure a `Vec` is only used where allowed (i.e. at the end of a storage buffer type)
  * it has a convenient way of writing the runtime-sized array length into the binding buffer
* supports configurable dynamic offset alignments for both uniform and storage buffers
  * `crevice` only supports configuring alignment for dynamic offsets for std140 for uniform buffers
  * `crevice` DynamicUniformOffset enforces alignment of `max(256, T::ALIGNMENT)`, so _at least_ 256 in all cases
  * the alignment requirement of 256 for dynamic offsets for uniform buffers is often prohibitive for packing as much data as possible into uniform buffers for WebGL2 where uniform buffer binding sizes are limited to 16kB
  * the required minimum alignments vary by platform, graphics API, and GPU vendor
* the author has been active on our Discord, receptive to feedback/input, responsive in fixing issues we've noted so far, and has created a branch using `encase` in bevy here: https://github.com/teoxoy/bevy/tree/encase

**Comment by superdump** [comment]
As a note, I didn't look through the internals of `encase` yet. The API docs look nice, and I like the structure of the APIs too.

**Comment by mockersf** [comment]
We would need a way to have the `WgslType` derive macro be usable without having a direct dependency on `encase`.
This was done in bevy_crevice with this: https://github.com/bevyengine/bevy/blob/main/crates/bevy_crevice/bevy-crevice-derive/src/lib.rs#L37

**Comment by superdump** [comment]
And I don't think we should switch before 0.7 unless we're somehow very confident. This decision is rather to unblock some changes I have to use storage buffers for point lights and some changes needed to the helper impls for more efficient handling of binding data for animations.

**Comment by teoxoy** [comment]
> We would need a way to have the WgslType derive macro be usable without having a direct dependency on encase.

I tried to find a way to get the derive to work when reexported but without luck.

I only found serde's derives can be reexported like [here](https://github.com/serde-rs/serde/issues/1465#issuecomment-800686252) but that extra attribute has to be on every struct with the derive. I'd rather have a direct dependency than do that.

**Comment by mockersf** [comment]
> I tried to find a way to get the derive to work when reexported but without luck.

To get it to work without an extra attribute, encase would need to know the path where Bevy will reexport the macro. It can be done behind a "bevy" feature flag without needing to depend on Bevy. Where it becomes painful is if Bevy want to change the reexport path

**Comment by teoxoy** [comment]
I don't think that will be the best approach since feature flags are supposed to be additive. If the user would like to have encase as a direct dependency while also having bevy in their dependencies, the derive imported from encase will stop working.

Is there a big advantage in wanting to reexport rather than direct dependency?

**Comment by superdump** [comment]
This was addressed by #4339 which is now merged. Closing.
