### ISSUE TITLE
Add a docs.rs badge to README for stable docs

### ISSUE THREAD

**Issue by colepoirier** [bevyengine/bevy#4283]
A lot of crates have a docs.rs badge next to their crates.io badge that links to the crate's stable docs. I propose a docs.rs badge be added to the Bevy README.

Are there reasons why this addition would be undesirable?

**Comment by colepoirier** [comment]
I agree. In fact, using the badge/favicon that someone  (@aevyrie ?) made for the dev docs would be quite cool if that's feasible.

**Comment by colepoirier** [comment]
> I'm not a fan of those links. The readme is copied to the crates.io page which already link to the doc. That means that whatever we add to the readme will also be present on the crates.io page. Add a link to the dev docs? it will be present on the page for the version on crates.io. Add a link to the released docs? It means every tag on Bevy repo will link to the docs for the latest release, even an older release.

This adds a second step to the process and a layer of indirection. I almost always access and find crates via their github pages and rarely go to their crates.io page. I much prefer accessing the crates' stable and dev docs via badges on their README, than through their crates.io page. I think we should support both; we already support the flow of users like yourself; I would advocate  we also support the flow of users like me. There are significant numbers of users in both categories, and I don't think it is justified to give one group preferential treatment at the expense of the other.

With regard to your concern of linking to the docs for the latest release even for older released on crates.io, I would suggest that this is the ideal scenario. By default a user should always be directed to the most up-to-date info as the inverse leads, in my opinion, to much more frequent confusion. If a user is genuinely looking for the older docs they will change the version on the docs.rs page. Adding the extra step here instead I think leads to better user outcomes.

**Comment by rparrett** [comment]
A docs badge was added by #9993
