### ISSUE TITLE
Add a method to get `Vec<Entity>` from `Entities`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4307]
## What problem does this solve or what need does it fill?

I have access to the world or an `Entities` system parameter, and want a list of `Entity` in a useful format.

This is a natural method, and would be useful for writing tests or editor-like functionality.

## What solution would you like?

Add a method to get `Vec<Entity>` from `Entities`.

## What alternative(s) have you considered?

Current workaround: use a query for `Query<Entity>`.

**Comment by BoxyUwU** [comment]
`Entities` doesnt actually store a `Vec<Entity>` so you'd probably want an iterator to avoid allocating the vec at which point using a `Query<Entity>` seems reasonable :sweat_smile:

**Comment by alice-i-cecile** [comment]
> Entities doesnt actually store a Vec<Entity> so you'd probably want an iterator to avoid allocating the vec at which point using a Query<Entity> seems reasonable 😅

Yeah, I'm fine if it returns a `impl Iterator<Item = Entity>`. Fundamentally, this is about aligning with user expectations: it's super weird that you can't get a list of the entities from the system parameter `Entities`.

**Comment by BoxyUwU** [comment]
I think in some cases a `Query<Entity>` could probably be more efficient than something from `Entities` since `Entities` hasnt got a fast way to only iterate "alive" entities. I think it'd have to iterate over `Vec<EntityMeta>` checking if each element is alive and then constructing an entity if it is. `Query<Entity>` can just iterate all tables/archetypes automatically skipping dead entities since they dont exist there :thinking:

**Comment by alice-i-cecile** [comment]
Agreed there, but this isn't a perf-sensitive path. This would be almost entirely for debugging and tests.

**Comment by pubrrr** [comment]
What is actually the purpose of `Entities` (it's missing docs)? Isn't even more confusing to be able to query entities via a resource?

I always had the impression that ECS is designed to `Query` entities that represent the objects living in the world. Resources are for global state that are not related to an entity. Is this impression wrong? How does this relate to this issue? Isn't `Entities` kinda violating this separation?

**Comment by alice-i-cecile** [comment]
> What is actually the purpose of Entities (it's missing docs)?

This is an internal collection of "which entities are valid", that is exposed as a system parameter. You can access metadata about entities (such as whether or not they exist) and reserve specific entities for later use using it.

> Isn't even more confusing to be able to query entities via a resource?

It's not a resource, it's part of the `World`'s assorted internal-ish state. This wouldn't permit you to query for any of their data, merely get a list.

Overall, I think this is a questionable idea: I'm going to close this out and we can revisit it later once we have a better idea of what `Entities` is used for in real code.
