### ISSUE TITLE
enhance `UiRect` with convenience methods

### ISSUE THREAD

**Issue by pubrrr** [bevyengine/bevy#4323]
## What problem does this solve or what need does it fill?

[`Rect`](https://github.com/bevyengine/bevy/blob/v0.6.1/crates/bevy_math/src/geometry.rs#L31), `UiRect` respectively after #4276 is merged, is a plain data structure representing rectangles used for UI. There are certain computations associated to rectangles, that users might frequently need.

## What solution would you like?

Offer convenience methods such as 
* `center(&self) -> Point`
*  `translate(self, Vec2) -> Self`,
*  ...

## Additional context

[Egui](https://github.com/emilk/egui/blob/0.17.0/emath/src/rect.rs) already has a similar struct.

**Comment by mockersf** [comment]
`Rect`/`UiRect` is not really a rectangle, it's informations about each side of a rectangle: the width of the border, the margins, ...
So `center` or `translate` don't really make sense for this

**Comment by KDecay** [comment]
Adding to what @mockersf said:

I think the `Rect` that should be updated here is not the `Rect`/`UiRect` from `bevy_math`/`bevy_ui` but the `Rect` from `bevy_sprite`. This one also has two points like the one in `egui` and offers the same `width`, `height` and `size` methods. For this `Rect` it would make sense to have something like a `center` function.

## `bevy_math`

```rust
/// A rect, as defined by its "side" locations
#[derive(Copy, Clone, PartialEq, Debug, Reflect)]
#[reflect(PartialEq)]
pub struct Rect<T: Reflect + PartialEq> {
    pub left: T,
    pub right: T,
    pub top: T,
    pub bottom: T,
}
```

## `bevy_sprite`

```rust
/// A rectangle defined by two points. There is no defined origin, so 0,0 could be anywhere
/// (top-left, bottom-left, etc)
#[repr(C)]
#[derive(Default, Clone, Copy, Debug, Reflect)]
pub struct Rect {
    /// The beginning point of the rect
    pub min: Vec2,
    /// The ending point of the rect
    pub max: Vec2,
}
```

**Comment by pubrrr** [comment]
For my understanding: What is the difference between those two Rects? How are they supposed to be used?

**Comment by KDecay** [comment]
## `Rect`/`UiRect` from `bevy_math`/`bevy_ui`

The `Rect`/`UiRect` from `bevy_math`/`bevy_ui` is used to define a size for each side of a rectangle (e.g. position, margin, padding, borders). So essentially stuff like "How large should my padding on the left be?" or "How thick should the right border be?".

For more details about how the `UiRect` is used you can read through the documentation [here](https://github.com/bevyengine/bevy/pull/3503/files#diff-b33608d8591bbaf2e08e2b467eb467379dfdeb4ffca4b2369bc316d169e842edR119-R239).

## `Rect` from `bevy_sprite`

The `Rect` from `bevy_sprite` is used to define an actual rectangle. This is for example used in the `TextureAtlas` to define the area/ the rectangle of every sprite that is located inside of it (see [TextureAtlas](https://github.com/bevyengine/bevy/blob/main/crates/bevy_sprite/src/texture_atlas.rs#L20)).

**Comment by pubrrr** [comment]
Isn't it a bit weird to express a position or a margin as a rectangle? At least for me this sounds really confusing.

**Comment by mockersf** [comment]
The name isn't very good... Don't hesitate if you have a better idea in #4276

**Comment by viridia** [comment]
Naming suggestion: "Insets".

**Comment by Jax-Hax** [comment]
Should there be a way to convert between the two? Then it would allow for building a Rect in `bevy_math` then converting it to a UIRect in `bevy_ui`. Or should there be the corresponding functions like center() on the UIRect as well? Sorry if these already exist, trying to find my first contribution and I don't really know what I'm doing.

**Comment by theotherphil** [comment]
I'm another new user who's stumbled across this issue while looking to make a first contribution to Bevy and is not sure what, if anything, needs to actually be done here.

I think this issue is either fixed by https://github.com/bevyengine/bevy/pull/5686 or is too vague to be actionable.

I'm not sure what the etiquette is for pinging maintainers, so I'll just ask @alice-i-cecile directly: do you agree that this issue should be closed, or is there something specific required to resolve it?

**Comment by viridia** [comment]
Other name suggestions:

* `UiEdgeWidths`
* `UiEdges`
* `UiSides`
* `UiInsets`
* `UiMargins`

**Comment by alice-i-cecile** [comment]
I think this should be closed. I'm not opposed to more utility methods, but I don't think this is a useful place to start.
