### ISSUE TITLE
Use a circle for the ball in Breakout

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4324]
Once #3730 is merged, we should represent the ball as a circle, rather than a square. We can probably stick with the AABB collision though for simplicity.

**Comment by rparrett** [comment]
I have a feeling that in practice, not doing proper circle-aabb collision would end up looking pretty janky, but I'd personally love to see that if it doesn't complicate the example too much.

**Comment by mockersf** [comment]
as a side note, this could already be done by using a round image, like https://github.com/bevyengine/bevy/blob/main/assets/branding/icon.png

**Comment by alice-i-cecile** [comment]
#3730 is merged so this is now quite easy :)

**Comment by galkowskit** [comment]
I made a PR pretty much exactly the same as the #4682, if there is no answer from the creator of that PR, I can submit mine.

**Comment by alice-i-cecile** [comment]
Yes please @galkowskit :) Just link to the other PR and we'll credit you both.

**Comment by galkowskit** [comment]
https://github.com/bevyengine/bevy/pull/5657

**Comment by rparrett** [comment]
So the obvious collision "corner case" is this sort of thing:

https://user-images.githubusercontent.com/200550/184248507-13ab64bc-52c9-41bd-b874-9b3dbd088b2c.mov

We could

1. Have a circle with slightly wrong collisions
2. Have a square with better collisions
3. Fix the collision code

I have a slight preference for 2 but it seems like fixing the collision code would be sort of involved, so I suppose I don't really mind 1.

**Comment by galkowskit** [comment]
I think it also touches the physics issue. There is a very rudimentary code for reflections.

**Comment by AlexBrodbelt** [comment]
Hi, I'm trying to make a (modified) billiards game and need to detect to collision between balls. I was wondering if there already exists an implementation within bevy or whether I should make my own (and if its good/suitable enough I can contribute it back to bevy?). I've never contributed before so I'm not sure how this works. Thank you!

**Comment by mockersf** [comment]
Bevy currently only has Axis Aligned Bounding Box for collisions, which probably wouldn't work very well for billiard
