### ISSUE TITLE
Remove the ability to directly use strings as labels

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4341]
## What problem does this solve or what need does it fill?

Following #4219, system function types can be used directly as labels.

This removes the last serious use of strings as labels: for "quick and dirty" implementations.

"Stringly typed" labels are inferior because:

1. They are not IDE or compiler aware, and so typos are very challenging to detect.
2. They can clash in very surprising ways between crates.
3. They cannot be kept private.

## What solution would you like?

1. Remove the ability to use string types as labels.
2. Update codebase, including examples and tests, to reflect this change.

## Additional context

Raised in #4340 by @DJMcNab.

Note that labels that store a string may be useful in some applications for e.g. scripting integration. This is still supported: you just have to newtype your string.

**Comment by DJMcNab** [comment]
We've had a discussion in discord, and my understanding of the consensus is that we should wait for stageless to implement this

We can fix the tests which rely on this beforehand - a lot of them can probably use const generics.

**Comment by hymm** [comment]
&str no longer implements label (SystemSet) after #6587
