### ISSUE TITLE
Firefox fails to load any wasm example with bevy builds on main (0.7.0 dev)

### ISSUE THREAD

**Issue by JCBuck** [bevyengine/bevy#4353]
## Bevy version

28ba87e6c8f48a6b41b6743b748a72d41728523c

## Operating system & version

Windows 10 x64
Firefox 98.0.2 (64-bit)

## What you did

Built WASM of `text_debug` example with latest main branch as per WASM build instructions in examples readme.

## What you expected to happen

The example would load and show text.

## What actually happened

Shows just white screen and an error.

## Additional information
Firefox will load with WASM builds based on Bevy 0.6.1, but not with builds based on the current main. 
Screenshot is showing Chrome (Left) and firefox (right)
![image](https://user-images.githubusercontent.com/5351275/160379619-8873a5e2-8fa3-44c8-b7a9-269f14369698.png)
Points to here
![image](https://user-images.githubusercontent.com/5351275/160380216-a1dbcc2d-8438-455e-8332-3f7ad33c3350.png)

Also interestingly enough firefox thinks the gpu is "HD graphics 400", where as chrome shows it as "5500" on a Thinkpad X1 Carbon 3rd gen.
The same thing happens with a W530 with a K1000M gpu, shows up as a gtx 480 if that makes any difference.
![image](https://user-images.githubusercontent.com/5351275/160380755-29f68731-493c-4d47-a410-778d7b946ec0.png)

**Comment by mockersf** [comment]
`text_debug` from d51b54a6580431ca2fa1e154b8162aa53bc3d430 works in Firefox on macOS

**Comment by JCBuck** [comment]
It seems it may be due to non https context in firefox as suggested by this comment in another issue here
https://github.com/bevyengine/bevy/issues/4431#issuecomment-1090325958
