### ISSUE TITLE
ClearColor and Sprite same value yields different color

### ISSUE THREAD

**Issue by RobotSnowOtter** [bevyengine/bevy#4356]
## Bevy version

Bevy 0.6.1

## Operating system & version

Pop!_OS 21.10 x86_64

## What you did
Set a sprite and the background to the same rgb value
```rust
use bevy::prelude::*;

const BG_COLOR: Color = Color::rgb(0.16, 0.16, 0.16);

fn main() {
    App::new()
        .insert_resource(ClearColor(BG_COLOR))
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn_bundle(OrthographicCameraBundle::new_2d());

    commands.spawn_bundle(SpriteBundle {
        sprite: Sprite {
            color: BG_COLOR,
            custom_size: Some(Vec2::new(50.0, 50.0)),
            ..Default::default()
        },
        ..Default::default()
    });
}
```

## What you expected to happen

The rectangle sprite should be indistinguishable from the background.
Only one color should be visible.

## What actually happened

The sprite (center) renders *slightly* darker than the background.

![image](https://user-images.githubusercontent.com/20213672/160469318-e337b3d6-dba5-4a5d-8ea0-a8f21040306d.png)

**Comment by alice-i-cecile** [comment]
Good find. Thanks for the excellent issue and report. Under the hood, I bet this has something to do with linear vs sRGB colors.

**Comment by mockersf** [comment]
Issue is that [`Color`](https://docs.rs/wgpu/latest/wgpu/struct.Color.html) in wgpu is using `f64`, but we're using `f32`, and the difference is in the rounding

**Comment by CptPotato** [comment]
> Issue is that [`Color`](https://docs.rs/wgpu/latest/wgpu/struct.Color.html) in wgpu is using `f64`, but we're using `f32` then `u8`, and the difference is in the rounding

Is it confirmed that this is a rounding issue? I would have expected the rgb value to be off by one in that case but the values are `38` vs `41` in the screenshot.

Even considering `f32` to `u8` conversion, you'd expect `0.16` to be `40.8` so either 40 or 41 which matches the background color. Compared to that the sprite is too dark. Though, maybe there are other things at play, too (desktop composition / color management / etc).

**Comment by CptPotato** [comment]
Didn't see the PR, thanks for elaborating. I tried it with a few different colors and they all seem to match up.

Though, I would prefer a different fix if I'm honest. With #4357 I'm not able to set accurate clear colors using `Color::rgb_u8()`. Anything below `(13, 13, 13)` is black for example.

I guess it's because the quantization to `u8` is done using linear color, not srgb which makes it loose a ton of accuracy for darker colors.

**Comment by mockersf** [comment]
> If anything this is a "bug" there

I'm not sure this is so much a bug as a "known limitation" that should be documented... This would only be visible when using the sprite color instead of an image, which doesn't feel like the main feature.
If a user want more accurate color, it is possible with the `Mesh2dBundle` instead of the `SpriteBundle`

**Comment by mockersf** [comment]
```rust
fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    commands.spawn_bundle(OrthographicCameraBundle::new_2d());

    commands.spawn_bundle(SpriteBundle {
        transform: Transform::from_xyz(50.0, 0.0, 0.0),
        sprite: Sprite {
            color: BG_COLOR,
            custom_size: Some(Vec2::new(100.0, 100.0)),
            ..Default::default()
        },
        ..Default::default()
    });

    commands.spawn_bundle(MaterialMesh2dBundle {
        mesh: meshes.add(Mesh::from(shape::Quad::default())).into(),
        transform: Transform::default()
            .with_scale(Vec3::splat(100.0))
            .with_translation(Vec3::new(-50.0, 0.0, 0.0)),
        material: materials.add(ColorMaterial::from(BG_COLOR)),
        ..default()
    });
}
```
the `MaterialMesh2dBundle` will have the expected color, `SpriteBundle` won't
