### ISSUE TITLE
AssetServer.load does not work in wasm32-unknown-unknown target.

### ISSUE THREAD

**Issue by mattatz** [bevyengine/bevy#4366]
## Bevy version

0.6.1

## Operating system & version

Windows10,  Google Chrome 100.0.4896.60

## What you did

1. Call AssetServer.load in startup system.
2. Assign resulting handle id to base_color_texture in StandardMaterial.

## What you expected to happen

The texture is displayed in a material.

## What actually happened

- in x86_64-pc-windows-msvc target, the result is correct. (the texture is displayed in a material)
- the texture is saved in public folder with "assets" root path.
- The result from AssetServer.get_load_state is LoadState::NotLoaded.

## Additional information

- I tried to [examples/asset/custom_asset_io](https://github.com/bevyengine/bevy/blob/main/examples/asset/custom_asset_io.rs) approach, but CustomAssetIo.load_path is never called in wasm32-unknown-unknown target.

**Comment by rparrett** [comment]
`load` should work just fine on the web (although `load_folder` isn't really possible.)

You can see an example of this here: <https://bevyengine.org/examples/3d/texture/>
