### ISSUE TITLE
win10 2004 link error

### ISSUE THREAD

**Issue by hekia** [bevyengine/bevy#438]
Can't run example on win10 2004,here is the error message.
some one what's going on,I don't know how to fix this.

compiling bevy v0.1.3 (C:\workspace\bevy)
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.10pvhrp7ky0jqt59.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.12lglme5tsljemy.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.12t87pvbus5kl993.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.1583lt9m1z5tta69.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.1b7vikflwao0kv1o.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.1ctvnmpoafohsatt.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.1d47vul4wn19nkas.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.1heymbf0ippatwa9.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.1ldn8xx9gejd6nkd.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.1n8rg3skyvlyfzd6.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.1sbdd4e9de7hlahu.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.1svgayns11m4qk0v.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.1vaer4jgtq861e0q.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.1w07wwnsovf55lx4.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.21krlmbdgyrne7ze.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.248yjxnmyask6utx.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.25tby0p948fo87g1.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.27qiduz8gv8u9vnr.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.2b1i8rdhakwxgjdq.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.2cbtvpyva8mwk43i.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.2g3q1fbd3hft54yg.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.2jgrw1cfo1pz3zjw.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.2l0maq84mop62zp2.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.2pf2u3lm1e439m9l.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.2r4p1y1mnqn325q0.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.2w3t10xbnuavtrul.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.2zz6azf07yqm6vy3.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.319622fb3ysrjdou.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.34llb1il6un48zhs.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.350k9892p8piio2o.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.39on0jtsnr6k1vo0.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.3be26vrk32io10ff.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.3ha4wvmt2n3wlyq6.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.3kl3pvbduhmbi6ig.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.3rnebmqyjtvtqckw.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.3w84wbtqdtx0w0uy.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.3xziw4trjoxujw3f.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.3zyuxe4dirkxfh2u.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.45eo56duc4dwvkee.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.47h0s7utk4324434.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.4fuz0sdkt6rap3r0.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.4idsz5446m3757mw.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.4oahmseiywbj96jk.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.4odkvzrg0bizwttz.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.4ras6w3wlh6eji3n.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.4vxu453fyk9993c8.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.4ww28o7joipndleb.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.4xz8j71opqs8q81g.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.52r9hfhs68mdrwhy.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.54bpc3q39p6l5zlq.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.56a9jb9y4bf6jz19.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.5a01gsj113zjbk6y.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.5aplbic5e4h308se.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.5cmyhx7kb98sy0dl.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.5dacf9g2y3awy0wf.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.5sggd33up5554vn.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.5tzmem3pks2el85.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.6k0cwbfbyesuyjv.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.aedi7f51lqssupg.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.b9yqnqv7hxdxbsk.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.dsilz1c2bmqe5lx.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.meedu2h2g06q0su.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.sw81akwd28ekncd.rcgu.o" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.wgfawzuzm08sb14.rcgu.o" "/OUT:C:\\workspace\\bevy\\target\\debug\\examples\\breakout.exe" "C:\\workspace\\bevy\\target\\debug\\examples\\breakout.3h4hw9krsdr9d7jt.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" 
"/NATVIS:C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:C:\\workspace\\bevy\\target\\debug\\deps" "/LIBPATH:C:\\workspace\\bevy\\target\\debug\\build\\minimp3-sys-45124e794e45a5cc\\out" "/LIBPATH:C:\\workspace\\bevy\\target\\debug\\build\\spirv-reflect-d7fd50bb1cb14186\\out" "/LIBPATH:C:\\workspace\\bevy\\target\\debug\\build\\spirv_cross-d5a136eac7136d8f\\out" "/LIBPATH:C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy-9f614a1194898ede.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_wgpu-0a054c67d95990db.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libwgpu-5350745d8006ec0a.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libwgpu_core-ccac4edc259a4bfd.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libtracing-9cc4e1f72eb661e4.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libtracing_core-c897190c7d0a8857.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libnaga-c909b8da910503cc.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libgfx_memory-7255235ceab54ea9.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libhibitset-c14af4db8a1847c2.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libatom-ce2d8459a8d4c3c3.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libcopyless-2cb77a78a03750b4.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libwgpu_types-b6da7ef0fcf82e9a.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libgfx_descriptor-abf16fccb155a1a8.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libgfx_backend_vulkan-9dd0b842dea3bf34.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libinplace_it-6c58d816cd9b9fe5.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libash-3ba09801f1f2f83d.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libgfx_backend_dx12-15563acf0f73771d.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libd3d12-cf05b03ef02004a9.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libgfx_backend_dx11-0e75339fd9fb0670.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libparking_lot-e7463d032c6e7598.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libparking_lot_core-5fa361fc0094cd83.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\liblock_api-f84615a7115e6fbd.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libwio-68ae9697a56be62b.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\librange_alloc-0d082ca999d8d6f7.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libgfx_auxil-2d859dab93dde57b.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfxhash-e941ce87a226ff20.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libspirv_cross-877b8ab66c51a9c3.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libgfx_backend_empty-8bc09d544e7dc96a.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libgfx_hal-9f64311c4f5421cb.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libtyped_arena-d9b4b72f2e50c99c.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfutures-8038bde1cdc0bce0.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfutures_executor-49d95f8d5afdc133.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfutures_util-d5d7e5cb06c886fd.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libmemchr-c7aad2958aa9138e.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libproc_macro_nested-836e056072f38471.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfutures_io-5e53cf830214179e.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libslab-d6ec32805f3e0bc9.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfutures_channel-2313e12415e51554.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libpin_project-c551cac3932a7c6a.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfutures_sink-fc243322df0f8e79.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfutures_task-27f235b7772b2829.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libpin_utils-9294f0394db3f7f4.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfutures_core-f768e95ffb0c1652.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libarrayvec-0be7986ec2b1f42c.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_winit-178decc8e2ac27c3.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libcart_tmp_winit-1ba4c9f646086f7e.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libraw_window_handle-17e87e38cd5626ea.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\liblibc-a0b81185824f2315.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libinstant-d56e75b00409e015.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_gltf-ddf3824c510cb749.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libgltf-91c58ce6d69ae103.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libgltf_json-9afe0460154929be.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libserde_json-6ca49a16376d6291.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libryu-b55a2715159c0eef.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libitoa-7e6e2bed7748ac7f.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_audio-4761e42cabf7a5ba.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\librodio-d7023ed138df30d4.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libminimp3-54c8f0d9579908a7.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libslice_deque-7128fcf8939b5fd9.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libminimp3_sys-a009a6a85d4846be.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libcpal-5de7351f7bd1d03e.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_ui-cbcffbdd19554428.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libstretch-a676ee75856c4216.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_text-6ada49aa5859bdd2.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libab_glyph-5a8c079b7a19b50e.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libowned_ttf_parser-6d91d7b3d2d7b2f5.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libttf_parser-aea061eb3bcfbdb4.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libab_glyph_rasterizer-a53dc83be7e32fb3.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_sprite-c0e7f7f2db706dd0.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\librectangle_pack-d0a328c0f21ab318.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libguillotiere-ca378f2d98683537.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libsvg_fmt-89284e6424ec83fb.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libeuclid-59637f3db623d4ce.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_scene-e37220c8439c3882.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_pbr-e403ce69ae2e847a.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_render-ccd41f7c96dd4843.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libimage-dfcfc673da1d25cc.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbytemuck-148b29785526abe6.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libnum_iter-07ff550d6ed7df69.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libpng-2ac1ec4feee8b97e.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libminiz_oxide-851919d42cb564d2.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libcrc32fast-dd38f54970b34815.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libdeflate-6c2623cbd909a733.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libadler32-540ac614fd299068.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libnum_rational-8219fa213aa02ee6.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libnum_integer-0e98903ad85614fc.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbyteorder-b4b519bd06525baa.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libscoped_threadpool-7ce6573370126f8c.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_glsl_to_spirv-040de7394f880d2e.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libtempfile-e207ec766f9fff00.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libremove_dir_all-73b98d755db3b18e.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libhex-fd4f9f9302f37808.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libspirv_reflect-6fea3242e84c28ef.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libspirv_headers-e84a311a83767490.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libnum_traits-bc68f6b05bbb551b.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libdowncast_rs-f3b0f2e332dc39e4.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libonce_cell-c4843eb4431378d4.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libhexasphere-b42426a1f305108c.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_transform-71d88a4b2255ad82.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_window-b1f2978382093228.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_input-375a7bbed0fcf1d0.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_diagnostic-eea30531930f1c67.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_core-418d1995427e00ae.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_asset-c7ce252add522759.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libuuid-9d6413983bbf2246.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libnotify-e13d10ce5419bb7b.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libwalkdir-9a251c0d3168106c.rlib" 
"C:\\workspace\\bevy\\target\\debug\\deps\\libsame_file-c2dc8332b32a0b4f.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libwinapi_util-0ae23a90e2fdc944.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfiletime-0edcc231723de7a6.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libanymap-83bf965749d3b5bf.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_type_registry-3137918756f64c24.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_property-ecfc7e667fc8b331.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_ron-0caf464bafbda258.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbase64-90ddff7f5bef1dc6.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbitflags-f5232c5e063b3cf9.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\liberased_serde-e26adeebeeeac5ec.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libthiserror-9c56b33e166686f5.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libanyhow-2c3137b3a068a479.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_app-3dfa13c83f7e3799.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_math-2799579dda90e18c.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libglam-210132546b472a06.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\liblog-44e7312cbb15574b.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\liblibloading-a3d72c5da39566ef.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_ecs-f76708b1c6a50941.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_tasks-154ec4f5c04dbe21.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libpollster-1dd79f41b0f50193.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libnum_cpus-1535f8ebfb94b69c.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libmultitask-4617ff62382da6ab.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfastrand-d5910e4d72d308ba.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libasync_task-ec24a32ca2890c89.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libconcurrent_queue-446428f32bbcfc3b.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libcache_padded-14d9aa2f95afd9c1.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libparking-53bcd2ee1b988141.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libparking_lot-c8742f8694c28693.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libparking_lot_core-39c7a077ff3dbac5.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libwinapi-8c0bcbeb0f4f2267.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libsmallvec-0d011bf51f04daaf.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\liblock_api-f37d3bddde9d5d1a.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libscopeguard-2ba64b74a98e9d72.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libfixedbitset-fd4d0f1947e737c3.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libcrossbeam_channel-c017c2fd878d3d2c.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libcrossbeam_utils-debe2257da1e1759.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_hecs-0390a36ddd1ce68a.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\librand-8afa672c0d237adc.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\librand_chacha-123449efb30197c2.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libppv_lite86-4056fc0930bece18.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\librand_core-685da3ac9d35bb8b.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libgetrandom-2d753085fd810409.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libcfg_if-9c041a88e2165932.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\liblazy_static-b8ae71fc410dcc1f.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libspin-5c9233e6e318a9ab.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libserde-3b421fe3e0990ee4.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libbevy_utils-8d7a39075ce0e343.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libahash-36f220a6bdf6873c.rlib" "C:\\workspace\\bevy\\target\\debug\\deps\\libconst_random-3189378471e7642d.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-098718ea823008f4.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-6a7fb52d1138932f.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-6a663e98da9bc9d7.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-35acfeb1bd722cd7.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libbacktrace-5789469546c93c74.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-6b40c36b7a5ce598.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-ce5287493729af9a.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-3d66b8897882cc1e.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-2f1bb63f49853f4b.rlib" 
"C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-e769bcc0ed78b3c4.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-2182f71ae05a8995.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-77514af2604d16ea.rlib" "C:\\Users\\Zhongkai.He\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-ebafcb87dc3d8679.rlib" "advapi32.lib" "cfgmgr32.lib" "comctl32.lib" "d3d11.lib" "d3d12.lib" "d3dcompiler.lib" "dwmapi.lib" "dxgi.lib" "fwpuclnt.lib" "gdi32.lib" "kernel32.lib" "mmdevapi.lib" "msimg32.lib" "ntdll.lib" "ole32.lib" "opengl32.lib" "shcore.lib" "shell32.lib" "shlwapi.lib" "synchronization.lib" "user32.lib" "uxtheme.lib" "winspool.lib" "ws2_32.lib" "advapi32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: LINK : fatal error LNK1181: cannot open input file 'd3d12.lib'

error: aborting due to previous error

error: could not compile `bevy`.

To learn more, run the command again with --verbose.

**Comment by Moxinilian** [comment]
Have you ever tried building an example of at gfx-rs/wgpu with your current config?
It seems like DirectX stuff is failing to link, so maybe it's an issue upstream.
