### ISSUE TITLE
input doesn't update when dragging the window 

### ISSUE THREAD

**Issue by RoadRoller01** [bevyengine/bevy#4394]
## Bevy version

0ed08d6a15f48e5030fcfdcb5d417a84d315e69b

## Operating system & version

Windows 10 21H1

## What you did
i try to make a drag window app,

it works when i first try to drag the window but the second time
doesn't work the third time works the fourth doesn't etc...,

after i tried to find a solution,

i found that the input doesn't update when dragging the window (released input)
the input when i drag the window:
```
Input { pressed: {Left}, just_pressed: {}, just_released: {} }
```
after i release the window
```
Input { pressed: {Left}, just_pressed: {}, just_released: {} }
```
the reason that the second time didn't work,
was because when i click the pressed update (or released)

the code:
```rust
use bevy::{prelude::*, window::WindowId, winit::WinitWindows};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_system(drag_window)
        .run();
}

fn drag_window(windows: NonSend<WinitWindows>, mouse: Res<Input<MouseButton>>) {
    let window = windows.get_window(WindowId::primary()).unwrap();
    print!("{:?}\n", mouse);
    if mouse.just_pressed(MouseButton::Left) {
        window.drag_window().unwrap();
    }
}

```

## Additional information
it's not winit problem,

because when i try to just use winit it works 

the winit code:
```rust
use winit::{
    event::{ElementState, Event, MouseButton, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    let event_loop = EventLoop::new();

    let window_1 = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.run(move |event, _, control_flow| match event {
        Event::WindowEvent {
            event,
            window_id: _,
        } => match event {
            WindowEvent::CloseRequested => *control_flow = ControlFlow::Exit,
            WindowEvent::MouseInput {
                state: ElementState::Pressed,
                button: MouseButton::Left,
                ..
            } => window_1.drag_window().unwrap(),
            _ => (),
        },
        _ => (),
    });
}
```
meow

**Comment by RoadRoller01** [comment]
it's winit issue :)

**Comment by alice-i-cecile** [comment]
@RoadRoller01 could you like the appropriate winit issue if you could find one? Then we can know where to direct efforts later.

**Comment by RoadRoller01** [comment]
this is it 
https://github.com/rust-windowing/winit/issues/2192

**Comment by dimvoly** [comment]
Not sure that [winit](https://github.com/rust-windowing/winit/issues/2999) issue is getting fixed any time soon. For now the cheap workaround I used was to release the window drag event right away:

```rust
  fn drag_window(windows: NonSend<WinitWindows>, mut mouse: ResMut<Input<MouseButton>>) {
      let window = windows.get_window(WindowId::primary()).unwrap();
      print!("{:?}\n", mouse);
      if mouse.just_pressed(MouseButton::Left) {
          mouse.release(MouseButton::Left);
          window.drag_window().unwrap();
      }
  }
```
