### ISSUE TITLE
At high FOV, there are bars on the sides of the screen with no lighting.

### ISSUE THREAD

**Issue by steoh-01** [bevyengine/bevy#4395]
## Bevy version

0.6.1

## Operating system & version

Windows 10

## What you did

I was moving the camera around with `bevy_flycam` in the `3d/3d_scene` example when I turned the FOV of the camera up from its default to 90 degrees, and I noticed some dark bars on the sides of the screen that seemed to only affect lighting and were perfectly aligned with the screen axes. To rule out `bevy_flycam` as a problem, i removed it, but the problem was still happening.

These bars move around when moving the camera and when resizing the window.

At this point, the only change I've made from the example is the non default perspective_projection with a higher FOV and moving the camera into a position where the error is visible.
There are no dependencies other than bevy 0.6.1.

Here is the code:

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .insert_resource(Msaa { samples: 4 })
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

/// set up a simple 3D scene
fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    // plane
    commands.spawn_bundle(PbrBundle {
        mesh: meshes.add(Mesh::from(shape::Plane { size: 5.0 })),
        material: materials.add(Color::rgb(0.3, 0.5, 0.3).into()),
        ..Default::default()
    });
    // cube
    commands.spawn_bundle(PbrBundle {
        mesh: meshes.add(Mesh::from(shape::Cube { size: 1.0 })),
        material: materials.add(Color::rgb(0.8, 0.7, 0.6).into()),
        transform: Transform::from_xyz(0.0, 0.5, 0.0),
        ..Default::default()
    });
    // light
    commands.spawn_bundle(PointLightBundle {
        point_light: PointLight {
            intensity: 1500.0,
            shadows_enabled: true,
            ..Default::default()
        },
        transform: Transform::from_xyz(4.0, 8.0, 4.0),
        ..Default::default()
    });
    // camera
    commands.spawn_bundle(PerspectiveCameraBundle {
        // the transform position and the non default perspective_projection are the
        // only changes i've made to the 3d_scene example
        transform: Transform::from_xyz(2.5, 2.0, 0.0).looking_at(Vec3::ZERO, Vec3::Y),
        perspective_projection: PerspectiveProjection {
           fov: (90.0 / 360.0) * (std::f32::consts::PI * 2.0),
           ..Default::default()
        },
        ..Default::default()
    });
}
```

## What you expected to happen

this screenshot is at the default FOV. I expect to see this but with a 90 degree FOV.

![buggy2](https://user-images.githubusercontent.com/81672701/161409279-1b1c3b4a-e453-4bb0-b928-9be5f74fe081.png)

## What actually happened

![buggy](https://user-images.githubusercontent.com/81672701/161409226-1a7e8df3-513c-42a1-ba31-a740b1b91287.png)

**Comment by superdump** [comment]
If you leave the fov as default and just translate the camera back, are those black bars there then? I suspect this is simply that the directional light shadow projection does not fully cover the objects in the scene so there is some false shadow being cast.

**Comment by steoh-01** [comment]
> If you leave the fov as default and just translate the camera back, are those black bars there then? I suspect this is simply that the directional light shadow projection does not fully cover the objects in the scene so there is some false shadow being cast.

I checked if the plane is in the shadow map with renderdoc. It appears to be fully in view, so there shouldn't be any false shadows, unless Ive misinterpreted the shadow map.

camera view:
![camera_view](https://user-images.githubusercontent.com/81672701/161435034-e99455a0-0e2d-4e46-8b04-8378008621ab.png)
shadow view:
![shadow](https://user-images.githubusercontent.com/81672701/161435037-2a95926c-2974-4551-8aa7-a92c2d4e30f2.png)

Also, it works perfectly when i move the camera far back with a default FOV. Here's 2 videos of the camera sweeping in with default FOV and with 90 degrees:

default:
https://user-images.githubusercontent.com/81672701/161434762-267b14d0-4a0d-461a-a4ad-0c3bed4da42c.mp4

90 degrees:
https://user-images.githubusercontent.com/81672701/161434740-3f55690e-295b-433c-afd6-86670a3b1450.mp4

90 degrees, moving the camera manually to better show the bars:
https://user-images.githubusercontent.com/81672701/161436000-e636e105-ad69-4ca6-a4cb-936886a1cd5c.mp4

You'd know better than I do, but I think it might be the light clustering system not working properly given that the bars have no light (but still have ambient light), and move in large blocks across the screen (the light cluster width?), not continuously like you'd expect if the shadow map wasn't capturing the edge of the plane.

**Comment by superdump** [comment]
Ah, indeed. I thought this scene had a directional light. You're right that it's probably a bug in the clustering. I'll check to see if it's still present in some upcoming change to the clustering algorithm. No point fixing it in the current one if we're anyway going to change it. FYI @robtfm

**Comment by superdump** [comment]
I cannot reproduce this on `main` and there were some fixes to frustum culling since 0.6.1 so it was probably that.

**Comment by superdump** [comment]
@steoh-01 can you try on `main` to double-check that you cannot reproduce there? If so, we can close this as the upcoming 0.7 release will include the fixes.

**Comment by steoh-01** [comment]
Have confirmed it doesn't happen on `main` for me.
