### ISSUE TITLE
Add secondary keybinding to "move camera" in `scene_viewer` example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4407]
## What problem does this solve or what need does it fill?

On some touchpads it can be challenging to both click and pan simultaneously, making it onerous to pan the camera in the `scene_viewer` example following #4405.

## What solution would you like?

Add another keybinding (in addition Left Mouse Button) to enable camera movement. @superdump suggested `KeyCode::L`, which I like.

## Additional context

https://github.com/bevyengine/bevy/pull/4405#issuecomment-1087032550

**Comment by Sheepyhead** [comment]
`KeyCode::L` is already bound to light animation, I'll be using M for Move if that's acceptable
