### ISSUE TITLE
Split out camera movement functionality into separate `tools` example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4408]
## What problem does this solve or what need does it fill?

The camera controls in `scene_viewer` is very useful, and should be reused in other 3d examples.

We shouldn't copy paste this code.

## What solution would you like?

Split out this code into its own example, and import it as a plugin in each 3D example.

## What alternative(s) have you considered?

This could be included as a first-class tool in Bevy, along the lines of [`bevy_config_cam`](https://github.com/BlackPhlox/bevy_config_cam). This would need more time to mature, and more serious design thought.

Keeping this as example code allows us to iterate more quickly and clearly indicate to users that this code is intended to be hacked.

## Additional context

Discussed in #4405.

**Comment by superdump** [comment]
The way I have seen to do this is to add another crate underneath examples and include it as a dev dependency I think. Then examples that want to use it, can.

**Comment by rparrett** [comment]
One of the mentioned alternatives was done in #11338. Can this be closed?

**Comment by alice-i-cecile** [comment]
Yep, although I still want to move this into `bevy_dev_tools`.
