### ISSUE TITLE
`Timer::just_finished()` returns true forever when paused during finish tick

### ISSUE THREAD

**Issue by Madadog** [bevyengine/bevy#4436]
## Bevy version

0.6.1

## Operating system & version

Ubuntu 20.04

## The problem

The description of `Timer::just_finished()` claims it "returns true _only_ on the tick the timer reached its duration", but pausing _during_ that tick causes it to return true indefinitely. This causes inconsistent behaviour as it means pausing a timer will occasionally make `Timer::just_finished()` return true every frame, usually resulting in a massive speedup for anything the method is being used for: periodic entity spawning, advancing an animation, or printing info to the console.

It's possible this isn't actually a bug, but at the very least it leads to unintuitive behaviour which should be correctly indicated in the method's description.

### Minimal example:

```rust
use bevy::prelude::*;
use std::time::Duration;

fn main() {
    // consistent for both repeating and non-repeating timers
    let mut timer = Timer::from_seconds(1.0, false);

    // finish timer
    timer.tick(Duration::from_secs_f32(1.0));
    assert!(timer.just_finished());
    
    // pause timer while just_finished()
    timer.pause();

    // timer is now just_finished() forever
    for _ in 0..100 {
        timer.tick(Duration::from_secs_f32(0.5));
        assert!(timer.just_finished());
    }
}
```

### What you did

Used a timer to advance an animation when `timer.just_finished() == true`. Paused the timer.

### What you expected to happen

The animation would stop.

### What actually happened

The animation would stop unless it was paused on the tick `timer.just_finished() == true`. If this happened, the animation would speed up to the screen's refresh rate. Unpausing the animation would slow it back down.

## Solutions you have considered
* Make `tick()` reset times_finished to 0 when paused
    * In general, ticking a paused timer is supposed to do nothing.
    * Need to consider what exactly times_finished means while paused / if anything relies on it not changing.

**Comment by Protowalker** [comment]
@alice-i-cecile this has since been fixed. Good to close?
