### ISSUE TITLE
QuerySet not available anymore

### ISSUE THREAD

**Issue by BrunoWallner** [bevyengine/bevy#4439]
## Bevy version

latest version after `cargo clean` and `cargo update`
hash: `f907d67d7ed5cfd8b11b2ad78e9dfd6eeb913cea`

## Operating system & version

Arch Linux on Kernel: `5.17.1-arch1-1`

## What I did

Updated bevy version to latest git version and now my Game will not compile if it utilizes `QuerySet`

And now none of these are available anymore:
```rs
bevy::ecs::prelude::QuerySet
bevy::ecs::system::QuerySet
bevy::prelude::QuerySet
bevy::ecs::system::QuerySetState
```

**Comment by alice-i-cecile** [comment]
This has been changed to the more general `ParamSet` in #2765 :) The migration should be relatively painless, but do let us know if you run into problems.
