### ISSUE TITLE
Transparency Visual Bug / Alpha Artifact

### ISSUE THREAD

**Issue by c48v** [bevyengine/bevy#4442]
## Bevy version

0.6.1

## Operating system & version

Fedora Linux 35 (Workstation Edition), 64-bit
Gnome 41.5
Wayland Windowing System

## What you did

I have a sprite with a transparent background. The transparent part looks 'glitchy'
I'm attaching a screen capture of how it looks.
It seems like this bug only happens specifically on my PC.
Also, I have another machine that also runs Fedora and the bug doesn't happen there, so my guess is that it has to do with the hardware I'm using, or the very specific combination of hardware and software.

## Hardware Specification

Hardware Model:
Micro-Star International Co., Ltd. MS-7C77

Processor:
Intel® Core™ i7-10700T CPU @ 2.00GHz × 16 

Graphics:
Mesa Intel® UHD Graphics 630 (CML GT2)

## Examples:

https://user-images.githubusercontent.com/103264822/162453261-843e51c4-2b59-48f9-94b2-9e8780803d88.mp4

![BevySpriteExample](https://user-images.githubusercontent.com/103264822/162452438-bf79d74a-5dc8-4a87-8285-0295c6bc62bf.png)

![bevyTransparency](https://user-images.githubusercontent.com/103264822/162452651-bc6f8a65-e43d-4d3e-9eaa-da7fed2f79fb.png)

**Comment by inodentry** [comment]
It would be useful if you can try to see if the issue also occurs with the latest bevy from the git main branch. Or, you could also wait a little, as 0.7 is planned to be released in a few days / next week, and test it with Bevy 0.7 when it comes out.

I suspect it would (I don't remember an issue like yours being encountered and fixed), but a confirmation would be nice. 0.6 is kinda old at this point.

**Comment by rparrett** [comment]
Looks like a duplicate of #3593

**Comment by c48v** [comment]
> Looks like a duplicate of #3593

ahh thanks, disabling MSAA fixed it : )
