### ISSUE TITLE
custom shade node not work before main pass

### ISSUE THREAD

**Issue by foxzool** [bevyengine/bevy#4453]
## Bevy version

0.6 / main

## Operating system & version

Windows 11,  arch linux

## What you did

to make a  augmented reality  app, so i want to render shade before main pass

so i make a [demo](https://github.com/foxzool/bevy_background);

```

fn main() {
    let mut app = App::new();
    app.insert_resource(Msaa { samples: 4 })
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup);

    let render_app = app.sub_app_mut(RenderApp);
    render_app.init_resource::<BackgroundPipeline>();
    let mut graph = render_app.world.get_resource_mut::<RenderGraph>().unwrap();

    graph.add_node(BACKGROUND_NODE, BackgroundNode::default());
    graph
        .add_node_edge(node::MAIN_PASS_DEPENDENCIES, BACKGROUND_NODE)
        .unwrap();

    // it's now work before main pass
    graph
        .add_node_edge(node::CLEAR_PASS_DRIVER, BACKGROUND_NODE)
        .unwrap();
    graph
        .add_node_edge(BACKGROUND_NODE, node::MAIN_PASS_DRIVER)
        .unwrap();


    // it's worked after main pass
    // graph
    // .add_node_edge(node::MAIN_PASS_DRIVER, BACKGROUND_NODE)
    // .unwrap();

    app.run();
}
```

## What you expected to happen

the  brown triangle should render as background

## What actually happened

the shade not rendered

## Additional information
the brown triangle should render as background
![image](https://user-images.githubusercontent.com/217027/162628360-04a55f21-e0b4-4c3d-86df-78db0f63f6c7.png)
![image](https://user-images.githubusercontent.com/217027/162628406-4034c241-7265-41bb-99fb-86cc5d33b8cf.png)

**Comment by CptPotato** [comment]
Does your background node use the depth buffer / depth comparisons?

**Comment by foxzool** [comment]
render capture file
[render_doc.zip](https://github.com/bevyengine/bevy/files/8599143/render_doc.zip)

look like render cleaning before main pass
