### ISSUE TITLE
`collide` doesn't get all possible intersections

### ISSUE THREAD

**Issue by dbofmmbt** [bevyengine/bevy#4478]
## Bevy version

0.6 (I checked and `main` has the problem too).

## What you did

![image](https://user-images.githubusercontent.com/34381457/163502247-47232288-636d-445e-bcf2-6f2d8c81c748.png)

## What you expected to happen

`collide` should return `Some(...)`.

## What actually happened

It returned `None` i.e. it didn't get a intersection when there's no corner inside the intersection area.

**Comment by alice-i-cecile** [comment]
Checks out. Should be an easy tweak to use a more sensible AABB collision algorithm :)

**Comment by dbofmmbt** [comment]
I decided to work on it. :rocket:

**Comment by dbofmmbt** [comment]
I just noticed that #2489 fixed it. I must have looked at tag 0.6 instead of the `main` branch when checking if the problem was present in the latest version of the code base. Anyway, my PR became a refactor... still worth it, though =)
