### ISSUE TITLE
Unlit materials don't seem to respect AlphaMode::Mask

### ISSUE THREAD

**Issue by JohnEmhoff** [bevyengine/bevy#4479]
## Bevy version

0.6.1

## Operating system & version

Ubuntu 21.10

## What you did

Using a `StandardMaterial` with `unlit: true` seems to ignore `AlphaMode::Mask`. 

I'm rendering a reticle as a cube with a mostly transparent texture. Using this material:

```
let ret_mat = materials.add(StandardMaterial {
        base_color_texture: Some(reticle_texture),
        unlit: false,
        alpha_mode: AlphaMode::Mask(0.9),
        ..Default::default()
    });
```
...renders like this:

![Screenshot from 2022-04-14 23-05-57](https://user-images.githubusercontent.com/1692535/163511868-64f7341b-67df-4a16-a607-006bca53edf7.png)

But using this material:

```
let ret_mat = materials.add(StandardMaterial {
        base_color_texture: Some(reticle_texture),
        unlit: true,  // this is the only change
        alpha_mode: AlphaMode::Mask(0.9),
        ..Default::default()
    });
```

...renders like this:

![Screenshot from 2022-04-14 23-05-40](https://user-images.githubusercontent.com/1692535/163511927-5811ce28-f81e-49eb-8ed6-c4a2c5169da8.png)

## What you expected to happen

The black area in the latter image should be transparent. For whatever reason `AlphaMode::Blend` *does* work with both lit and unlit, but it has the side effect of messing with depth ordering. (This is reasonable, right? It doesn't seem crazy that when blending nothing writes to the depth buffer)

## What actually happened

`unlit: true` causes `AlphaMode::Mask` to be ignored

## Additional information

It's entirely possible this is behaving as expected for some interesting reason that I'm just not aware of. If so I apologize and appreciate the opportunity to learn something :)

**Comment by LoopyAshy** [comment]
This issue has been causing me quite a bit of grief recently, I imagine the issue however is within the standard shader.

I may have a look later but my shader knowledge is very hit and miss.
