### ISSUE TITLE
Document underlying algorithms and data structures

### ISSUE THREAD

**Issue by SUPERCILEX** [bevyengine/bevy#4500]
I'm finding that I still don't understand how entities, components, or bundles work. For example I just discovered that you can write this query without having to do anything special: `Query<Entity, With<SomeComponent>>`. The problem is that I have no idea why it works or how I could know that it should work without needing to see it in some random examples.

It'd be amazing if there were docs that explained the following:
- An explanation of how entities, components, and bundles interact with each at the data structure level. That is, walk through an example of adding and then removing some entities, showing what the memory layout looks like (I think Bevy has two, so show both). Also, what's an archetype? IIRC, that has to do with how the entities are stored, so show what happens when some component changes archetypes (again, with some ascii/visual representation of the memory).
- Explain how queries work. I'd love to know how the compile-time stuff works and see an example of how it traverses memory to find stuff.
- Explain the algorithm that decides whether or not systems can run in parallel, i.e. if I add this param what'll happen to the system ordering.
- Other technical details that would be valuable to know

Giving devs an approachable, yet highly technical explanation to Bevy's fundamentals would make a huge difference in understanding what should be possible and having an intuition for what APIs should be available and where they would be.

If more convincing is needed, there are more reasons to do this:
- Make contributing to Bevy itself more approachable. If you know how the system works, then it's much easier to find what you're looking for.
- Attract talent/publicity: a good article would probably get featured on HN and generate more interest in Bevy.

**Comment by alice-i-cecile** [comment]
Yep! This is all planned as part of the new book! It's tracked over in https://github.com/bevyengine/bevy-website/issues/265.
 
 This is an excellent list of topics to make sure we cover though; thank you <3

**Comment by SUPERCILEX** [comment]
Woohoo, that's awesome!
