### ISSUE TITLE
Static type introspection

### ISSUE THREAD

**Issue by IcyDefiance** [bevyengine/bevy#4504]
## What problem does this solve or what need does it fill?

It would be nice if I could get the names and types of fields in a struct, without creating an instance of that struct.

## What solution would you like?

Static methods on `Struct`, `Tuple`, etc. 

## What alternative(s) have you considered?

I could probably make my own macro to get just the info I need. It just feels like this is something that should be in a more general-purpose reflection crate.

## Additional context

My personal use case was an experimental entity-first ORM. I was hoping to use bevy_reflect to help generate migrations, but I needed this feature to make it work that way.

I already scrapped that whole idea in favor of a headless CMS, but I'm sure this would be useful for others.

**Comment by MrGVSV** [comment]
Would #4042 fit your needs?

**Comment by IcyDefiance** [comment]
Yep, 100%.

Now that I see that, my idea of adding a method to `Struct`, `Tuple`, etc, seems a little silly. The new `Typed` trait is a much better idea.
