### ISSUE TITLE
Unable to play mp3 sound files.

### ISSUE THREAD

**Issue by VeyronSakai** [bevyengine/bevy#4509]
## Bevy version

0.7

## Operating system & version

macOS Monterey 12.3 
(Chip is Apple M1)

## What you did

1. The dependencies in Cargo.toml as follows

```toml
[dependencies]
bevy = {version = "0.7", features = ["mp3"]}
```

2. Define the function as follows
```rust
fn play_se<'a, T: Into<AssetPath<'a>>>(
    asset_server: &Res<AssetServer>,
    audio: &Res<Audio>,
    path: T,
) {
    audio.play_with_settings(
        asset_server.load(path),
        PlaybackSettings::ONCE.with_volume(1.0)
    );
}
```

3. Execute play_se() function, where the path arg is the path to the mp3 sound source.

## What you expected to happen

Sound plays normally.

## What actually happened

A fairly low-pitched noise is played.

**Comment by mockersf** [comment]
I couldn't reproduce locally (with an m1 too).

Does it happen with any mp3 file? Could you share more of your code?

**Comment by VeyronSakai** [comment]
I tried using a different mp3 and this error did not occur.
Perhaps the mp3 I used is the cause.
I apologize very much.

**Comment by mockersf** [comment]
Thanks for checking!

If the mp3 plays fine in other players, you can try and report an issue in Bevy upstream crates for mp3 ([rodio](https://github.com/RustAudio/rodio) or [minimp3](https://github.com/germangb/minimp3-rs))
