### ISSUE TITLE
Windows as entities

### ISSUE THREAD

**Issue by fowenix** [bevyengine/bevy#4530]
## What problem does this solve or what need does it fill?

Windows can't be closed from within bevy, #3575 mentions windows as entities and i really like that idea of that, so here is a proposal on how it could be done

## What solution would you like?

`WindowId` is now `Entity`

Extend `Commands` with a `window` method returns `WindowCommands` similar to how the `entity` method returns `EntityCommands`, `WindowCommandQueued` will implement `Command` and on `write` send itself as an event that window backends like `bevy_winit` will process.

`Window` should be separated into different components, `WindowCursor`, `WindowCursorPosition`, `WindowHandle`, `WindowPosition`, `WindowResizeConstraints`, `WindowResolution`, `WindowTitle`, as well as these markers `WindowCurrentlyFocused` (`WindowFocused` is taken by a window event), `WindowDecorated`, `WindowResizable`. 
A world query struct containing all these components and markers should be publicly exposed..

Windows should be spawned like an entity in `Commands` with a `WindowDescriptor` component, window backends should query `Added<WindowDescriptor>` and create the windows for them, while also applying a `Window` marker confirming they have been created, query `Added<Window>` or use a `WindowCreated` event to get newly created windows.

Despawning windows should be done just as entities (as they are now entities), window backends should close/destroy windows their internal component has been dropped, e.g. `WinitWindow` (wrapper around winit's `Window` that destroys itself on drop)

A resource called `PrimaryWindow` contains the entity id of initial window created by `WindowPlugin`, this replaces Windows::primary

`WindowPlugin` should change `exit_on_close` into a enum called `ExitCondition` with the values `OnPrimaryClosed` (when primary window is closed), `OnAllClosed` (when all windows are closed), `DontExit` (keep app headless)

**Comment by Shatur** [comment]
I like it so much. Could also solve #3754 because I will be able to such entities myself without winit.

**Comment by SpecificProtagonist** [comment]
Sounds great.  
> The marker WindowPrimary should exist on only one window at a time
To guarantee that invariance, maybe it should be a resource holding an entity id instead?

**Comment by Weibye** [comment]
I'm trying my hands at this, not sure if I'm going to be able to but I might as well try. I've started work and come across my first puzzle. I'm trying to solve this particular issue: 

> Extend `Commands` with a `window` method returns `WindowCommands` similar to how the entity method returns `EntityCommands`

1. It seems I can't `impl Commands` somewhere other than in `bevy_esc`
2. This means I would have to either move the definitions of `WindowCommands` over to `bevy_esc` or have `bevy_esc` depend on `bevy_window`
3. Both seems not ideal: Is there some obvious solution I'm not understanding here?

**Comment by SpecificProtagonist** [comment]
You could have `CommandsExt` trait in the `bevy_window`, include it in the bevy_window prelude and impl it for `Commands`

**Comment by Weibye** [comment]
> You could have `CommandsExt` trait in `bevy_window`, include it in the bevy_window prelude and impl it for `Commands`

That would only work if `bevy_esc` now started depending on `bevy_window`(?)

**Comment by SpecificProtagonist** [comment]
You can have 
```rust
struct WindowCommands { /*todo*/ }

pub trait CommandsExt {
    fn window(&mut self) -> WindowCommands;
}

impl CommandsExt for Commands {
    fn window(&mut self) -> WindowCommands { todo!() }
}
```
in `bevy_window` without changing `bevy_ecs`. If the trait then is in bevy_window's prelude, everyone that has the window feature active and imports `bevy::prelude::*` has access to `Commands::window`.

**Comment by Weibye** [comment]
Ok, thanks for the clarification! Will look more into this in the morning.

**Comment by Weibye** [comment]
Status update: Work continues over at #5589
