### ISSUE TITLE
Compilation bug on Qubes OS

### ISSUE THREAD

**Issue by patranger** [bevyengine/bevy#4553]
## Bevy version

commit
26c3b20f1ce1e04fcd37816d35fdff4d8433064f

## Operating system & version

Debian 11 inside Qubes OS R4.0.4

## What you did

I try to compile an empty window with the title only but it doesn't compile and throws the following errors.

https://0bin.net/paste/0IgZRfe6#PvqQT3CZqG4IpqFXGSbXSy1waXH9BiA8sjpJd4-SNGr

https://pastebin.com/J87JKWKJ

https://hardbin.com/ipfs/Qmb98jVEKE2jnsSEiYsY9mBZiC4qEAzda5xdk7BaGSYuLA/#AoKgeVMifCeyhAUgk8LkbHDB6fUTDN1MNAWcgaYYg7CD

## What you expected to happen

Compilation without problem.

## Additional information

Please note that Qubes OS is based on Xen virtualization and is very specific.

**Comment by alice-i-cecile** [comment]
Are you using `resolver=2` and/or Rust 2021 in your project?

**Comment by patranger** [comment]
I did not use: / I changed the version from 2018 to 2021 and now I have a different error when compiling

`error[E0560]: struct `bevy::prelude::WindowDescriptor` has no field named `vsync`
 --> src/main.rs:9:13
  |
9 |             vsync: true,
  |             ^^^^^ `bevy::prelude::WindowDescriptor` does not have this field
  |
  = note: available fields are: `width`, `height`, `position`, `resize_constraints`, `scale_factor_override` ... and 8 others

For more information about this error, try `rustc --explain E0560`.`

**Comment by bjorn3** [comment]
What is the source code you are using? The vsync field indeed doesn't exist anymore.

**Comment by alice-i-cecile** [comment]
Yep; try `cargo clean` and then `cargo update`.

**Comment by bjorn3** [comment]
@alice-i-cecile  The code @patranger wrote (or copied from somewhere) is using vsync, not bevy itself.

**Comment by patranger** [comment]
@bjorn3 Okay, you have right and as I removed the vsync field it compiles without a problem.

Source code is:
use bevy::prelude::*;
```
fn main() {
    App::new()
        .insert_resource(WindowDescriptor {
            title: "Test".to_string(),
            width: 500.,
            height: 400.,
            ..Default::default()
        })
        .add_plugins(DefaultPlugins)
        .run();
}
```

Just another problem arises. As we know, Qubes OS is based on Xen virtualization and the machines running in it do not have direct access to the GPU.
After compilation, the program starts and disappears immediately.

2022-04-26T14:54:13.943006Z  WARN winit::platform_impl::platform::x11::util::randr: XRandR reported that the display's 0mm in size, which is certifiably insane    
2022-04-26T14:54:13.943141Z  WARN winit::platform_impl::platform::x11::util::randr: XRandR reported that the display's 0mm in size, which is certifiably insane    
2022-04-26T14:54:13.943526Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!', /home/user/.cargo/git/checkouts/bevy-f7ffde730c324c74/46acb77/crates/bevy_render/src/renderer/mod.rs:95:10

**Comment by bjorn3** [comment]
Right, you will have to setup software rendering some way. For example using lavapipe. Depending on which version of mesa Qubes OS ships with I think installing mesa-vulkan-drivers would be enough for that.

**Comment by bjorn3** [comment]
This should have been fixed 11 months ago in mesa upstream: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4323 This is first included in mesa 21 I think (maybe even a release later). You are still on mesa 20. I guess you will have to either wait until a new debian release or get a newer mesa version. If you don't want to risk messing up your system you could for example use flatpak. The `org.freedesktop.Platform.GL.default` flatpak runtime contains the latest mesa version which should contain the fix. Personally I have used the terminal of my vscode version I installed using flatpak to use a newer mesa version for veloren (which crashed with the mesa version of the previous debian release).

**Comment by patranger** [comment]
Solved the problem by adding [env] to config.toml
`WGPU_BACKEND="gl"`

Thanks @bjorn3 :smiley:
