### ISSUE TITLE
WgpuRenderResourceContext::map_buffer forces wgpu::MapMode::Write

### ISSUE THREAD

**Issue by soycan-sim** [bevyengine/bevy#457]
Since this is rust, I think the default should be `wgpu::MapMode::Read`. `Write` should be accessed either by `RenderResourceContext::map_buffer_mut` (new fn) or by an additional argument on the existing `map_buffer`.

Otherwise it's impossible (?) to read from a `BufferUsage::MAP_READ` buffer.

**Comment by mockersf** [comment]
[`map_buffer`](https://docs.rs/bevy/latest/bevy/render/renderer/struct.RenderDevice.html#method.map_buffer) now takes the `MapMode` as parameter
