### ISSUE TITLE
Artificial 1 frame of input delay

### ISSUE THREAD

**Issue by aevyrie** [bevyengine/bevy#4573]
## Bevy version

main

## Operating system & version

Windows 11

## What you did

Modified the UI example to move a ui element to the most recent cursor position
Add a 1 second sleep in the last stage to make delays obvious

gist: https://gist.github.com/aevyrie/5fe6d9dad38d094300fed45c286ff26b

## What you expected to happen

When the screen updates every second, the ui element should move to the last position the cursor was before the update

## What actually happened

The ui element moves to the last position of the cursor the *previous* update. In other works, the cursor position is delayed by a full frame, regardless of how long a frame lasts.

## Additional information

https://user-images.githubusercontent.com/2632925/164956062-4a41138c-e01e-4268-bb2b-8f9a725e32bc.mp4

**Comment by alice-i-cecile** [comment]
Sounds like a system ordering issue of some form.

**Comment by alice-i-cecile** [comment]
@aevyrie could you post a link to the modified example so we can quickly reproduce and verify that it's squashed?

**Comment by aevyrie** [comment]
> @aevyrie could you post a link to the modified example so we can quickly reproduce and verify that it's squashed?

Uploaded a gist and included in the original post.

**Comment by aevyrie** [comment]
I dug into this a bit more, and I was wrong. The sleep was happening in in the main world. I realized this meant it was pausing between input and rendering.

Moving the sleep system to the render world's cleanup phase, generates the expected output - no frame delays!
