### ISSUE TITLE
check-markdown-links is painfully flaky

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4575]
This step of the CI is *incredibly* flaky (see https://github.com/bevyengine/bevy/pull/4469 for an example). Blocking merges is pointless friction, and confuses new contributors.

There are several options here:

1. Make sure the check doesn't block CI.
2. Use an alternative strategy for testing for dead links that is more reliable.
3. Somehow scope the check to only make sure it checks newly added or modified links.
4. Move dead linking to an action that is run once a day, with some form of alerting.

These are not mutually exclusive by any means. @mockersf, do you have preferences?

**Comment by superdump** [comment]
Do we have any idea why it fails? What errors are returned when it does fail? All I saw seemed to be a github token error message.

**Comment by superdump** [comment]
The errors in #4469 seem to be that requests to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews get a 403 response, meaning the requests are forbidden, usually an authorisation problem, but I wonder if it’s rate limiting or something.

**Comment by Nilirad** [comment]
I think internal links should always be valid, so it is good to check them on the PR.

On line other hand, external links are outside of our control, and therefore it makes more sense to check them outside of the PR workflow, e.g. periodically.

**Comment by mockersf** [comment]
The recent failures are all (all the ones I checked at least) on a link to docs.github.com. My guess is that GitHub added a protection to avoid being ddos from actions. Links to GitHub.com were already ignored, I added docs.github.com to the ignore list in #4578

**Comment by rparrett** [comment]
I was poking around at this and discovered [lychee-action](https://github.com/lycheeverse/lychee-action) as an alternative to [github-action-markdown-link-check](https://github.com/gaurav-nelson/github-action-markdown-link-check).

It's a rust project that seems to have all the features that we're using from `github-action-markdown-link-check` but also supports using a personal access token for requests to github as a way of getting around rate limits.

> A personal token with no extra permissions is enough to be able to check public repos links.

**Comment by alice-i-cecile** [comment]
I'd be interested in trying that out. Want to make a PR to replace it?
