### ISSUE TITLE
Image Based Lighting and HDRI Support

### ISSUE THREAD

**Issue by NHodgesVFX** [bevyengine/bevy#4581]
## What problem does this solve or what need does it fill?

Currently, the only way to add a sky would be to add a sphere with a texture applied or add use a plugin of some kind. However at least from what I have found no plugins support proper based image based lighting with HDRI support. This feature should be in bevy and not a plugin because PBR, which is already supported by Bevy, goes hand in hand with IBL. Without IBL PBR still looks fake, IBL dramatically increases the realism of the scene.

## What solution would you like?

Proper PBR style IBL with support for a "Sky Light" where you can add 360 degree 32bit .hdr or .exr textures or be dynamically set with a shader. The implementation should be able to work in real-time so its possible to update the texture either from disk or from a shader to simulate things like a day / night cycle or clouds. The HDRI  should also be rendered as the background of the scene. 

Godot has a implementation that is fast and looks good, I have also included links to the LearnOpenGl article on the subject although i'm not sure that implementation works in real-time.

https://github.com/godotengine/godot/pull/36588
https://www.ppsloan.org/publications/ggx_filtering.pdf
https://learnopengl.com/PBR/IBL/Diffuse-irradiance
https://learnopengl.com/PBR/IBL/Specular-IBL

## What alternative(s) have you considered?

Using a sphere with a texture applied but this has the issue that the light will not be cast onto objects and will not be shown in reflections.

## Additional context

Bevy's PBR without IBL
![image](https://user-images.githubusercontent.com/11403345/164999874-88976bf8-f8bb-4037-a1af-2960ca008c39.png)

PBR with IBL From LearnOpenGL
![image](https://user-images.githubusercontent.com/11403345/164999849-59dbdd60-1d3b-4b71-a9d0-3e5424a9d6c8.png)

**Comment by superdump** [comment]
Yup. https://google.github.io/filament/Filament.md.html#lighting/imagebasedlights is a good reference. Distant light probes is the part of interest for this issue I think.

**Comment by Rust-Ninja-Sabi** [comment]
Will ibl a part of bevy?

**Comment by superdump** [comment]
> Will ibl a part of bevy?

Almost certainly, yes.

**Comment by Rust-Ninja-Sabi** [comment]
Great👍

**Comment by expenses** [comment]
https://bruop.github.io/ibl/ is a great blog post on IBL. It's what's referenced in the [Khronos glTF Sample Viewer code](https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/563ab2796f693426c098faa1ab332aa7afffdcde/source/Renderer/shaders/ibl.glsl#L106-L129).

**Comment by stellanhaglund** [comment]
Any news on this?

**Comment by MAG-AdrianMeredith** [comment]
YES!!  This has been the one thing thats stopped me from wanting to explorer bevy further, can't wait to try it out.  good work everyone
