### ISSUE TITLE
Make Vec* methods const

### ISSUE THREAD

**Issue by SUPERCILEX** [bevyengine/bevy#4600]
## What problem does this solve or what need does it fill?

I'd like to use Vec2 in a static declaration, but that's currently not possible.

## What solution would you like?

Make Vec* methods const.

**Comment by mockersf** [comment]
This is not possible as `Vec2` takes floats, and floats can't be const...

However, there is [a macro `const_vec2`](https://docs.rs/glam/latest/glam/macro.const_vec2.html) that does that 🙂

**Comment by alice-i-cecile** [comment]
Very reasonable. This is fundamentally blocked on float math being usable in const functions. Once that's in, I expect `glam` to rapidly migrate away from the mentioned macros.

**Comment by SUPERCILEX** [comment]
Floats can't be const? TIL, though I guess that makes sense if a machine doesn't adhere to 754.

**Comment by SUPERCILEX** [comment]
Actually, are you sure? This compiles just fine for me:

```rust
#[derive(Debug)]
struct Blah(f32, f32);

const BLAH: Blah = foo(1., 2.);

const fn foo(blah: f32, boo: f32) -> Blah {
    Blah(blah, boo)
}

pub fn use_it() {
    println!("{:?}", BLAH);
}
```

**Comment by alice-i-cecile** [comment]
```rust
const fn add_two() -> f32 {
  2. + 2.
}
```

This should fail to compile :( Here's the Rust issue: https://github.com/rust-lang/rust/issues/57241

**Comment by SUPERCILEX** [comment]
Hmmm, all I'd want is `Vec2::new`. Would it be reasonable to only allow construction? Or is there some extra magic happening that would prevent that?

**Comment by alice-i-cecile** [comment]
That's ultimately a question for upstream. Maybe try it out in a `glam` fork?

**Comment by mockersf** [comment]
> Hmmm, all I'd want is `Vec2::new`.

If you just want that in a `const` context, the macro should work for you?

**Comment by SUPERCILEX** [comment]
Good point, I guess I'll just use the macro though it seems weird to require that.

**Comment by alice-i-cecile** [comment]
Closing out, although once the linked `glam` issue is resolved I'll be thrilled to be able to migrate.
