### ISSUE TITLE
Cast query of mutable components to query of immutable

### ISSUE THREAD

**Issue by Dekakaruk** [bevyengine/bevy#4606]
Because of Rust borrow checker I'm usually forced to pass around entities and queries. But there seems to be a problem when I've got a mutable query but it suffices to have immutable one, like

```rust
fn some_function(entities: &Vec<Entity>, query: &Query<&SomeComponent>){...}

fn some_system(some_entities: Res<Vec<Entity>>, query: Query<&mut SomeComponent>)
{
    for mut c in query.iter_mut() {...};

    some_function(some_entities, query);
}
```

As far as I can see there is no way to cast the query although it seems reasonable to do so. I believe there should exist some implementation of `AsRef` trait or perhaps some new trait like `CanQuery<ComponentType>`.

**Comment by alice-i-cecile** [comment]
I agree here. I'd really like to see a unified API for casting mutable ECS data into its immutable form, in order to resolve this sort of challenge. You see this with e.g. `ResMut` and `NonSendMut` as well.
