### ISSUE TITLE
No Support for Integrated Graphics T-T

### ISSUE THREAD

**Issue by revdeluxe** [bevyengine/bevy#4623]
![image](https://user-images.githubusercontent.com/38414584/165693820-c60126f3-a798-42c8-b5c0-14306edc4faa.png)
Here's my Attempt in a iGPU.
SPECS:
CPU: Intel Celeron N3060 2.4GHZ x2
iGPU: Intel HD BSW/400 (For some reason it has vulkan but it's unsable)
RAM: 4GB LPDDR4, 6GB SWAP
ROM: 500GB GPT Toshiba BRFS
DESKTOP: XORG,XFCE
OS: ARCH Linux, 'ArchCraft' 

Hypothetically bevy should run fine on Intel Iris iGPU. or on RDNA based iGPU.

_Originally posted by @revdeluxe in https://github.com/bevyengine/bevy/issues/807#issuecomment-1111814481_

**Comment by alice-i-cecile** [comment]
Closing as spam.

**Comment by alice-i-cecile** [comment]
My bad. I didn't understand your intent and we've been hit by periodic spam that copies old messages. This isn't spam, but I'm going to reopen #807 instead, which has more details and history.
