### ISSUE TITLE
Res<Windows> is always changed... only run code when window is resized for example?

### ISSUE THREAD

**Issue by SUPERCILEX** [bevyengine/bevy#4632]
## Bevy version

0.7

## What you did

```rust
fn window_scaling(windows: Res<Windows>) {
    if !windows.is_changed() {
        return;
    }

    // ...
}
```

## What you expected to happen

`is_changed` returns false sometimes.

## What actually happened

Instead, it appears to always be true. Is this expected?

https://github.com/bevyengine/bevy/issues/4530 seems like it could fix things.

**Comment by DJMcNab** [comment]
To react to window events, you should listen to the relevant events. For example,
```rust
fn react_to_resize(mut resized_events: EventReader<WindowResized>){
     for size_change in resized_events.iter() {
         // React to change
     }
}
```

I don't think `Windows` being `changed` every frame was explicitely known, but I didn't have any indication it wouldn't have been.

**Comment by SUPERCILEX** [comment]
Oooooh, TIL! Thanks. BTW, is there a more performant way to get the last event than just `.iter().last()`?

**Comment by SUPERCILEX** [comment]
Actually I need to filter by the primary window anyway, so nvm.
