### ISSUE TITLE
Add an ergonomic Query method similar to single() / get_single() that can differentiate between 0 and many for the failure case

### ISSUE THREAD

**Issue by Luminoth** [bevyengine/bevy#4633]
## What problem does this solve or what need does it fill?

Currently, ```single()``` and ```get_single()``` can be used to ensure that a Query contains exactly 1 item. In the case of components that should have 0 or 1 item in the query, neither can be used to ensure that multiple components weren't returned:

```
if let Ok(item) = query.get_single() {
  // the Query has exactly one item
} else {
  // the Query has either 0 items (this is fine) or many items (this is bad)
}
```

## What solution would you like?

Another set of methods that look something like this would probably solve it just fine (apologies for the naming, I'm not sure what these would actually be called):

```
/// This panics if more than one of the item exists
fn optional_single() -> Option<Item>;

/// This returns an error only when more than one of the items exists
fn get_optional_single() -> Result<Option<Item>, Err>;
```

## What alternative(s) have you considered?

Right now the only way I know of to do this is a mix of ```single()``` / ```get_single()``` and using the Query iterator to see if there is more than one item. It's workable, but not very ergonomic.

## Additional context

For my use case I'm tagging entities with an optional, but exclusive component and would very much like to rely on the Query ergonomics to panic if there is ever more than 1 of them returned, but still be ok when there are none.

**Comment by MinerSebas** [comment]
Why introduce an extra function if you can just used the returned error of get_single?

```rs
match query.get_single() {
	Ok(item) => {
		// Exactly one item
	},
	Err(QuerySingleError::NoEntities(_)) => {
		// No items
	}
	Err(QuerySingleError::MultipleEntities(_)) => {
		// many matching entitys
	}
}
```

**Comment by Luminoth** [comment]
To be most honest, it's the panicing version I want more than anything. Having something like this:

```
if let Some(item) = query.optional_single() {
}
```

is a lot cleaner to me than matching on ```get_single()``` and calling ```panic()``` in every ```MultipleEntities``` block.

**Comment by alice-i-cecile** [comment]
I think the match on the `Result` of `get_single` is my preferred library solution to avoid API bloat. If this is a pattern you find yourself reaching for a lot, I'd suggest using a [trait extension method](https://rust-lang.github.io/rfcs/0445-extension-trait-conventions.html) to implement `optional_single` on `Query` in your own code.

**Comment by Luminoth** [comment]
Something like this look about right?

```
pub trait OptionalSingle<'s, Q>
where
    Q: WorldQuery,
{
    fn optional_single(&self) -> Option<<Q::ReadOnlyFetch as Fetch<'_, 's>>::Item>;
}

impl<'w, 's, Q, F> OptionalSingle<'s, Q> for Query<'w, 's, Q, F>
where
    Q: WorldQuery,
    F: WorldQuery,
    F::Fetch: FilterFetch,
{
    fn optional_single(&self) -> Option<<Q::ReadOnlyFetch as Fetch<'_, 's>>::Item> {
        match self.get_single() {
            Ok(item) => Some(item),
            Err(QuerySingleError::NoEntities(_)) => None,
            Err(QuerySingleError::MultipleEntities(_)) => {
                panic!("multiple items from optional single query")
            }
        }
    }
}
```

**Comment by alice-i-cecile** [comment]
Yep, that's exactly what I'd write :)


Closing this out; I think the workaround is very good.
