### ISSUE TITLE
Improve incrementality of transform propagation updates for siblings

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#4647]
As of #4608 (for legitimate correctness reasons), adding or removing any child now results in recomputing the transform hierarchy for _every_ sibling. This is extremely suboptimal for large scenes. For example, despawning a single "house" entity in a scene with thousands of houses should not recompute the transform for every house (and the things inside of it). Given that transform propagation is often a bottleneck, fixing this should be a priority.

**Comment by alice-i-cecile** [comment]
Added to the 0.8 milestone; I agree that we should aim to get this fixed ASAP.

**Comment by yilinwei** [comment]
Apologies, I haven't quite followed the discussion on Github or Discord; but what was the proposed fix going to be since adding a marker component was seen as untenable?

Was it going to be the proposed [rfc](https://github.com/bevyengine/bevy/issues/3329#issuecomment-1062160801)?

**Comment by alice-i-cecile** [comment]
> what was the proposed fix going to be since adding a marker component was seen as https://github.com/bevyengine/bevy/pull/3340#discussion_r786930527?

If we can get better performance characteristics with a marker component, I'm alright with that as a stop-gap. 

If we can get either the scheduling changes or a [hierarchy redesign](https://github.com/bevyengine/rfcs/pull/53) in in time for  the next release, I'd prefer a more elegant and robust approach instead.

**Comment by alice-i-cecile** [comment]
@cart @james7132, this is in the milestone. Is this still relevant following #4197?

**Comment by james7132** [comment]
Definitely still an issue. Any change to Children leads to propagating through the entire tree.

**Comment by cart** [comment]
This won't be solved / reviewed in time for 0.8. But should be prioritized / not forgotten. For now I'm adding a P-High so we don't lose it. We should also add this to the 0.9 milestone when that is created.

**Comment by james7132** [comment]
Spurious thought: since `Children`/`Parent`s are changed in tandem when applying hierarchy changes, and child order doesn't really matter. Shouldn't we be checking for `Changed<Parent>` instead of `Changed<Children>`? It'd be localized only to only the children which has a changed parent instead of all children of a parent with one or more changed children.
