### ISSUE TITLE
error[E0308]: mismatched types

### ISSUE THREAD

**Issue by chuiliuyiyi** [bevyengine/bevy#4654]
error[E0308]: mismatched types
   --> crates\bevy_ecs\src\query\iter.rs:253:37
    |
253 |     pub fn fetch_next(&mut self) -> Option<[QueryItem<'_, Q>; K]>
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime mismatch
    |
    = note: expected type `<<Q as fetch::WorldQueryGats<'_>>::Fetch as Sized>`
               found type `<<Q as fetch::WorldQueryGats<'w>>::Fetch as Sized>`
note: the anonymous lifetime defined here...
   --> crates\bevy_ecs\src\query\iter.rs:253:23
    |
253 |     pub fn fetch_next(&mut self) -> Option<[QueryItem<'_, Q>; K]>
    |                       ^^^^^^^^^
note: ...does not necessarily outlive the lifetime `'w` as defined here
   --> crates\bevy_ecs\src\query\iter.rs:160:6
    |
160 | impl<'w, 's, Q: WorldQuery, F: WorldQuery, const K: usize> QueryCombinationIter<'w, 's, Q, F, K> {
    |      ^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `bevy_ecs` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by DJMcNab** [comment]
What's your rust version, and bevy version? Have you tried updating `rustc`?

**Comment by chuiliuyiyi** [comment]
D:\Program Files\rust>cargo -V
cargo 1.57.0 (b2e52d7ca 2021-10-21)

**Comment by chuiliuyiyi** [comment]
bevy is now

**Comment by DJMcNab** [comment]
We don't support old Rust versions

To update your Rust version, you should use `rustup update`.

You're welcome to maintain your old fork keeping the support, but the current rust version is 1.60.
