### ISSUE TITLE
Physics Plugin

### ISSUE THREAD

**Issue by Dev380** [bevyengine/bevy#466]
Hello. I was just looking at Bevy and I saw that there wasn't any default plugin for physics. Are there any plans to integrate a physics engine into Bevy? Thanks.

**Comment by memoryruins** [comment]
#83 tracks physics in bevy. [Rapier](https://www.dimforge.com/blog/2020/08/25/announcing-the-rapier-physics-engine/), which is the successor to nphysics, provides 2d and 3d [bevy plugins](https://rapier.rs/docs/user_guides/rust_bevy_plugin/getting_started) ^^
