### ISSUE TITLE
Disable query, system, etc validation in release mode?

### ISSUE THREAD

**Issue by SUPERCILEX** [bevyengine/bevy#4667]
## What problem does this solve or what need does it fill?

Performance.

## What solution would you like?

I'm actually not sure how much validation there is or how much it costs. The main thing I can think of right now is query validation to check that two queries don't overlap and system validation to ensure there aren't cycles. Do those checks run every frame or once on startup? If it's every frame, I think it's worth considering disabling them in release mode (or adding a feature that needs to be disabled to get rid of the checks) to squeeze out a bit of extra perf.

In general, it probably makes sense for a game engine to disable all assertions in release mode. For testing, people can still build in release mode with debug assertions enabled, but for the final release, everything can be disabled since weird behavior is better than a crash anyway.

## What alternative(s) have you considered?

Leave things as is: memory + cpu is potentially wasted validating stuff.

**Comment by TheRawMeatball** [comment]
Validation only runs on startup.

**Comment by SUPERCILEX** [comment]
Awesome, nevermind then! (For whatever reason, I thought I'd read that it happened every frame.)
