### ISSUE TITLE
Query<Added> are not guaranteed to run first.

### ISSUE THREAD

**Issue by visualcode-t** [bevyengine/bevy#467]
It would be nice if we could have a guarantee that functions with Query<Added> be called before any regular queries.

**Comment by cart** [comment]
I think that is a game-specific logical requirement that won't apply in every case. In general I think systems should use the existing rules for ordering. Adding exceptions for Added seems like it would just make it harder to reason about and would limit other use cases.

You can force a specific order by adding a new stage before the default "Update" stage.

```rust
app.add_stage_before(stage::UPDATE, "added")
   .add_system_to_stage("added", add_things.system())
```

We might also eventually add the ability for systems to directly depend on other systems within a stage.

**Comment by visualcode-t** [comment]
For this specific instance, stages are perfect, thank you for that input. I also agree having dependent stages could be helpful for more complex situations without over-complicating the stage-system.

**Comment by cart** [comment]
Cool cool. Glad that works!
