### ISSUE TITLE
Setting fullscreen mode at runtime leads to crash in 0.7 and main

### ISSUE THREAD

**Issue by HeavyRain266** [bevyengine/bevy#4671]
## Bevy version

0.7 and main branch with latest commit

## Operating system & version

Windows 11,
Arch Linux,
~~macOS 12~~ Stopped crashing after reboot

## What you did

Moved to bevy 0.7 to create new game and wanted to use fullscreen system from 0.6
```rs
fn fullscreeen(
    input: Res<Input<KeyCode>>,
    mut windows: ResMut<Windows>,
) {
    let window = windows
        .get_primary_mut()
        .unwrap();

    if input.pressed(KeyCode::LAlt) && input.just_pressed(KeyCode::Return) {
        if window.mode() == WindowMode::Windowed {
            window.set_mode(WindowMode::Fullscreen);
        } else {
            window.set_mode(WindowMode::Windowed);
        }
    }
}
```

## What you expected to happen

Bevy should set fullscreen mode properly instead of crashing

## What actually happened

When you press `LAlt + Enter`, bevy tries to set fullscreen and crashes like on included GIF from Windows 11
<img src="https://i.imgur.com/twjU3zE.gif" width="480" height="270" />

## Additional information

None

**Comment by alice-i-cecile** [comment]
We should have a test like in #3597 to avoid regressions of this sort.

**Comment by DJMcNab** [comment]
Cannot reproduce on Windows 10. You might need to install the vulkan validations layers - the exit code in your gif looks similar to other vulkan issues I've seen.

Can you reproduce this in wgpu's examples?

**Comment by rparrett** [comment]
I am unable to reproduce on MacOS 12.2/m1. Although I did get to witness https://github.com/rust-windowing/winit/issues/2050 when switching back to windowed mode.

**Comment by HeavyRain266** [comment]
> Can you reproduce this in wgpu's examples?

Nope, I have installed full Vulkan 1.3 SDK which I'm using daily and wgpu examples works fine

After switching backends to DirectX 12 with `WgpuSettings` works fine, seems to be Vulkan specific, mayby too new SDK version and bevy uses some features through wgpu which were deprecated between 1.1 (used by wgpu) and 1.3

**Comment by HeavyRain266** [comment]
So, Im closing it as bug caused by upstream Vulka SDK version regression between wgpu and local one, I think we should put note somewhere about required SDK version to prevent future bug reports like this one
