### ISSUE TITLE
Add traces to run criteria

### ISSUE THREAD

**Issue by SUPERCILEX** [bevyengine/bevy#4681]
## What problem does this solve or what need does it fill?

Understanding the performance of run criteria.

## What solution would you like?

Set up trace spans around run criteria. Currently there are none. See https://github.com/bevyengine/bevy-website/issues/265#issuecomment-1119996162 where it would be helpful to see the overhead of run criteria.

**Comment by hymm** [comment]
> If a system includes a top-level guard such as mouse_button_input.just_pressed(MouseButton::Left), is it faster to put that in run criteria so that the actual system doesn't get run? My guess based on [this line](https://github.com/bevyengine/bevy/blob/b1afe2dcca52fc28c8f412e2e2ee01e2192c9191/crates/bevy_ecs/src/schedule/executor_parallel.rs#L179) would be yes, but I'm not sure how much overhead adding run criteria entails so maybe not.

*I didn't want to answer this question on the other thread and add noise there. So I'm putting it here where there is likely to be less activity.*

Current yes, using run criteria will be faster in most situations. Spawning tasks for parallel systems is currently very single threaded and avoiding the cost of that spawning will be faster with a simple run criteria check. You can see some of this in the run criteria benches I added. But the executor is currently undergoing some changes for stageless and I expect that we'll end up with a design that will spawn tasks while running the other systems. In that model it'll be more dependent on where your bottlenecks are. For example if you are bottlenecked by a long running system, the overhead of spawning a task during that time would have no effect on the actual execution time of a frame.

Definitely makes sense to add spans for run criteria in case someone makes a complicated one. I'll add them if someone else doesn't beat me to it.

**Comment by SUPERCILEX** [comment]
Thanks for the great explanation! :)
