### ISSUE TITLE
Support 3D textures

### ISSUE THREAD

**Issue by sadmac7000** [bevyengine/bevy#4702]
## What problem does this solve or what need does it fill?

Most back ends support textures with more than two addressable dimensions. Bevy doesn't present any obvious way to construct such a texture for use.

## What solution would you like?

Any method of loading a 3D texture into a Texture object.

**Comment by superdump** [comment]
You can create an Image from data. The Image has a default texture descriptor member. That can be modified to configure the dimension member to TextureDimension::D3.

**Comment by sadmac7000** [comment]
That looks like what I need. The rename from Texture -> Image made the documentation a bit hard to parse.
