### ISSUE TITLE
tracy frame timings broken for multiple windows

### ISSUE THREAD

**Issue by hymm** [bevyengine/bevy#4727]
In the below image you can see that the frame timings in tracy are wrong when running the multiple_windows example. It shows two frame timings during a single frame.

![image](https://user-images.githubusercontent.com/2180432/167960689-908a36f7-7a5a-4b4b-a667-61dd205f1381.png)

This is caused by the code below, where we mark the frame ending for every window.

https://github.com/bevyengine/bevy/blob/ae580e58dd1d8539e26a44a4d428e1aa45a3d6f9/crates/bevy_render/src/renderer/mod.rs#L61-L74

We could fix this by only send the event when the primary window is done presenting. Tracy also has the ability do secondary timings by naming the event, but I'm not sure how to access that functionality through the tracing lib. 

![image](https://user-images.githubusercontent.com/2180432/167961208-89032310-b2c5-4665-a8ba-bc182b789d9a.png)

**Comment by james7132** [comment]
It should probably be mentioned that this also is the case when there are zero windows open. (i.e. when `MinimalPlugins` is used).

**Comment by bjorn3** [comment]
Maybe move the event out of the for loop?

**Comment by hymm** [comment]
fixed by https://github.com/bevyengine/bevy/pull/4731
