### ISSUE TITLE
Make a note of the algorithmic complexity of each of the query operations

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#4742]
## How can Bevy's documentation be improved?

This question comes up pretty regularly. I would like to see this described for:

- archetypal filters: O(a)
- change detection filters: O(a + n)
- ordinary iteration: O(n)
- iter_combinations: ???
- get and get_mut: O(1)
- get_multiple: O(k)
- get_multiple_mut: O(k^2)

**Comment by Nilirad** [comment]
I would like to take this. I'm currently working on improving `Query` and `WorldQuery` docs, and I think this data fits very well into a table under a “Performance” section at the bottom of `Query` docs.

**Comment by james7132** [comment]
Adding one more to that: single and get_single is `O(a)`
