### ISSUE TITLE
Camera2dComponents spawned after frame 3 no more display anything.

### ISSUE THREAD

**Issue by Bobox214** [bevyengine/bevy#476]
I reproduced the issue by modifying the sprite.rs example to not spawn on startup, but after X frames.
If X >=3 the bevy logo no more appear.

Is there something that needs to be done to have the 2d camera work when spawned later in the life of the application ?

```rust
use bevy::prelude::*;
fn main() {
    App::build()
        .add_default_plugins()
        .add_resource(1u32)
        .add_system(setup.system())
        .run();
}

const FRAME_SPAWN: u32 = 3;

fn setup(
    mut commands: Commands,
    count: Res<u32>,
    asset_server: Res<AssetServer>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    if *count <= FRAME_SPAWN {
        println!("FRAME {}", *count);
        if *count == FRAME_SPAWN {
            let texture_handle = asset_server.load("assets/branding/icon.png").unwrap();
            commands.spawn(Camera2dComponents::default());
            commands.spawn(SpriteComponents {
                material: materials.add(texture_handle.into()),
                ..Default::default()
            });
            println!("Camera spawned");
        }
        commands.insert_resource(*count + 1);
    }
}
```

**Comment by Bobox214** [comment]
Doing the same test for the example/3d_scene.rs with the Camera3dComponents gave the same strange behaviour.
Spawning at frame 1 or 2 is displaying correctly, spawning starting from frame 3 nothing appears.

**Comment by cart** [comment]
Hmm looks like resizing the window "fixes" this problem. Printing out the `OrthographicProjection` component illustrates that the projection isn't getting updated to match the current window size.

**Comment by cart** [comment]
We could probably fix this by extending `camera_system` to also update projections when a camera is added. We could use an `Added<T>` query for this.

**Comment by Kurble** [comment]
I'm still having this bug on the current master, so it seems to me there was a regression

**Comment by cart** [comment]
Interesting. It works for me on master. Did you update the asset path to look like this: `asset_server.load("branding/icon.png")`

**Comment by Kurble** [comment]
I managed to reproduce the problem in the example by moving the setup system to the POST_UPDATE stage:
```rust
use bevy::prelude::*;
fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_resource(0u32)
        .add_system_to_stage(bevy::app::stage::POST_UPDATE, setup.system())
        .run();
}

const FRAME_SPAWN: u32 = 3;

fn setup(
    mut commands: Commands,
    mut count: ResMut<u32>,
    asset_server: Res<AssetServer>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    if *count <= FRAME_SPAWN {
        println!("FRAME {}", *count);
        if *count == FRAME_SPAWN {
            let texture_handle = asset_server.load("branding/icon.png");
            commands.spawn(Camera2dComponents::default());
            commands.spawn(SpriteComponents {
                material: materials.add(texture_handle.into()),
                ..Default::default()
            });
            println!("Camera spawned");
        }
        *count += 1;
    }
}
```
In my own game I have it like that because I have a scene switching system that despawns all entities and then spawns new ones. Made sense to me to do that at the end of the frame.
