### ISSUE TITLE
Introduce `Events::send_from` to make it easier to construct and send events

### ISSUE THREAD

**Issue by frewsxcv** [bevyengine/bevy#4771]
## What problem does this solve or what need does it fill?

Make it easier to construct an event that immediately gets sent. Similar to `Events::send_default`, but allows one to specify arguments.

## What solution would you like?

Something like:

```rust
impl<T> Events<T> { // And also for `EventWriter`
    pub fn send_with<Args: Into<T>>(&mut self, args: Args) {
        self.send(args.into());
    }
}
```

So instead of:

```rust
center_camera_events.send(rgis_events::CenterCameraEvent(layer.id))
```

We can write:

```rust
center_camera_events.send_from(layer.id)
```

Assuming `impl From<LayerId> for CenterCameraEvent` exists.

## What alternative(s) have you considered?

Function name could also be `send_with` or `send_new` or `send_with_args`.

## Additional context

N/A

**Comment by DJMcNab** [comment]
I don't really like this. Why not use instead?
```rust
center_camera_events.send(layer.id.into())
```

Maybe `send` should accept `Into<T>`, but it definitely shouldn't be a different method.
