### ISSUE TITLE
Failure to load an asset file should resut in some form of error message

### ISSUE THREAD

**Issue by fNek** [bevyengine/bevy#479]
Steps to reproduce:

 1. Copy the code from `examples/2d/sprites.rs` into a new bevy project
 2. Intentionally save the bevy logo, which this example depends upon, under a different file name
 3. Forget to change the path in the code you copied
 4. Wonder why nothing is shown in the window

I believe there should be an error message printed to stderr or something, since it might easily happen under circumstances where it's less obvious what happened.

**Comment by cart** [comment]
Agreed. We currently swallow these error messages and that certainly isn't ideal :smile:

**Comment by zicklag** [comment]
I think this can be closed now. We get nice warnings for failed assets now, and in master we don't get the panics we used to get for asset hot reload failures either.

**Comment by cart** [comment]
Makes sense to me!
