### ISSUE TITLE
Tracy does not show thread names

### ISSUE THREAD

**Issue by hymm** [bevyengine/bevy#4795]
## What you did

Run bevy with feature `trace_tracy`

## What you expected to happen

Viewing a `trace_chrome` in perfetto shows the thread names on the left.

![image](https://user-images.githubusercontent.com/2180432/169096903-341b5f4d-be9e-488b-8c24-1ae883a4e54d.png)

## What actually happened

Viewing a trace in tracy shows thread numbers.

![image](https://user-images.githubusercontent.com/2180432/169096994-1e5371e6-7e77-42be-aa7d-28133fc3ac42.png)

## Additional information

I know tracy should support this because their readme shows names on the left. https://github.com/wolfpld/tracy/blob/master/doc/profiler.png

**Comment by infmagic2047** [comment]
I created https://github.com/nagisa/rust_tracy_client/pull/38 on tracing-tracy for this feature. It's for the 0.9.0 version though, while we're using 0.8.0 (see #4786), so anyone who want to try it would need to upgrade.

**Comment by hymm** [comment]
looks like this is fixed in 0.9
![image](https://user-images.githubusercontent.com/2180432/207785392-10c87dc6-dc25-495e-9620-69048290ec36.png)
