### ISSUE TITLE
heavy_compute bench has bad parameters

### ISSUE THREAD

**Issue by hymm** [bevyengine/bevy#4798]
bevy 0.8-dev e5eb8376180e7571b68f99b19d77675a433e3a79

# What happened

The current heavy_compute benchmark is testing 1000 entities / 128 batch = 8 batches and using the default task pool. This makes the test overly sensitive to the number of cores on a machine.

# Desired Fix

Not sure what the best fix is here. Playing with the batch size, I was seeing the best perf at around 8 to 16. We could change the batch size or increase the number of entities or fix the number of threads to a lower number. Or vary the number of threads, Or vary the batch size.

**Comment by mockersf** [comment]
https://github.com/bevyengine/bevy/pull/4777 would remove the need to specify the batch size manually
