### ISSUE TITLE
Provide NixOs project file

### ISSUE THREAD

**Issue by Stupremee** [bevyengine/bevy#481]
Since the setup to use bevyengine on NixOs is quite tricky, it would be nice to provide a `shell.nix`
that the user can put in his project directory and then use it to install every dependencies using `nix-shell`
and patch the specific libraries.

[Amethyst](https://amethyst.rs) also provides a `shell.nix` [file](https://github.com/amethyst/amethyst/blob/master/README.md#nixnixos) that can be used directly.

**Comment by cart** [comment]
Resolved by #491
