### ISSUE TITLE
Push Constants

### ISSUE THREAD

**Issue by MDeiml** [bevyengine/bevy#4825]
## What problem does this solve or what need does it fill?

It would be nice to support using push constants. Even though the initial wgsl spec will not have push constants (https://github.com/gpuweb/gpuweb/issues/612) they are supported in naga (https://github.com/gfx-rs/naga/blob/master/tests/in/push-constants.wgsl) as well as wgpu.

But it seems that there was a decision not to include them. Specifically you cannot create pipelines with layouts that contain push constants. This is because the concept of a `RenderPipelineLayout` in wgpu was not translated to the bevy API and instead became just `&[BindGroupLayout]`. To create a `RenderPipelineLayout` in wgpu you specify bind group layouts and push constant ranges, so this seems like a weird design to me.

I'm talking about this code, which always sets the push constant ranges to be empty:
https://github.com/bevyengine/bevy/blob/fed93a0edce9d66586dc70c1207a2092694b9a7d/crates/bevy_render/src/render_resource/pipeline_cache.rs#L236-L239

## What solution would you like?

Change `RenderPipelineDescriptor` or it's `layout` field so it's possible to specify push constant ranges. 

## What alternative(s) have you considered?

Create a pipeline without using pipeline cache or don't use push constants.

## Additional Context

In order to use push constants in shaders we would also need #4824 

---

I'd be happy to implement this, but it would require minor breaking changes to `RenderPipelineDescriptor` and it seems to me that maybe there already was a decision to not support them, so I wanted to ask first.

**Comment by alice-i-cecile** [comment]
Previously discussed in #1733 and #1369.

> The rework directly exposes the ability to enable push constants via gpu (because it uses wgpu directly), so I do think we can close this out.

- @cart in #1369.

I don't have the expertise to evaluate the matter further, but I figured I can surface the most relevant bits of the conversation.

**Comment by MDeiml** [comment]
Thanks for the context. Assuming the mentioned rework is already done, this is still relevant. Push constants are still not exposed in `RenderPipelineDescriptor` and in `TrackedRenderPass`.

Even if push constants will not be used with the "built-in" shaders, it would still make sense to make them available to people who want to write their own shaders / render pipelines.

**Comment by cart** [comment]
I would like to support push constants. Things have changed a lot since #1733 and #1369. I _think_ the only missing piece at this point is updating the RenderPipelineDescriptor to include the push constant layout and adapting LayoutCache to accept push constant layouts (and take them into account for layout identity ... they must be a part of the key used to identify the layout).

**Comment by james7132** [comment]
@cart would you be opposed to having platform specific optimizations using push constants? The push constant size limitations are basically just big enough to fit two `Affine3`s and a few extra bits, which coincidentally is exactly the right size for a `MeshUniform`. It'd preclude users from using them for mesh rendering, but it'd likely be a sizable speed up opportunity on platforms that support it.

**Comment by cart** [comment]
If this can be done without adding extra complexity to user-facing shaders, I think I'm open to it. Hard to say before looking at the impl + perf tradeoffs first, but its an area I think we should explore.

**Comment by MDeiml** [comment]
> I would like to support push constants. Things have changed a lot since #1733 and #1369. I _think_ the only missing piece at this point is updating the RenderPipelineDescriptor to include the push constant layout and adapting LayoutCache to accept push constant layouts (and take them into account for layout identity ... they must be a part of the key used to identify the layout).

That and #4824. I got push constants working in my fork. It's not a lot of changes, but `RenderPipelineDescriptor` does have to change I think.

**Comment by alice-i-cecile** [comment]
@mdeiml if you're comfortable, a link to that branch or a PR would be great. It doesn't need to be perfect to start, but having something tangible will help focus the discussion.
