### ISSUE TITLE
ever-increasing memory usage -- specially on WASM

### ISSUE THREAD

**Issue by flipbit03** [bevyengine/bevy#4851]
## Bevy version

0.7.0

## Operating system & version

Windows 10, Ubuntu 20.04, also WASM

## What you did

Ran my game for a hour while checking world entity count and other stuff, which was stable.
Memory usage kept growing, regardless of entity count.
Native build memory grew 2mb in a hour, which was quite okay.
Running on a tab in Google Chrome, the [Wasm build of the game](https://chinese-warriors.sync-party.com/) keeps growing in memory usage.

## What you expected to happen

That the memory usage would be constant if we are not growing in entity amount.

## What actually happened

We noticed a sensible but every growing memory increase in Local builds, and growing by quite a bit in the WASM builds.

## Additional information

@alice-i-cecile @james7132 and @devil-ira have been given access to my game's source code to debug/possibly check.

**Comment by alice-i-cecile** [comment]
> So then the reason why memory usage grows so much on wasm is just the performance stuff.

This was the conclusion from our Discord conversation on the matter.

**Comment by alice-i-cecile** [comment]
@flipbit03 when you get the chance, can you expand on my summary?

**Comment by superdump** [comment]
@alice-i-cecile @flipbit03 where is the discord conversation?

**Comment by alice-i-cecile** [comment]
The `#WASM memory leak` thread, starting at [this message](https://discord.com/channels/691052431525675048/979434858696806410/979436784998047774).

**Comment by superdump** [comment]
So the reason for the leak seems to be Chrome performance instrumentation code rather than bevy app code. Apparently calling performance.clearMeasures() and performance.clearMarks() clears (most of?) the memory used for tracking memory usage (ironic right?) and so this was not a bevy problem.

**Comment by Niedzwiedzw** [comment]
https://github.com/rustwasm/wee_alloc/issues/106 is this related?

**Comment by Tarnadas** [comment]
Thx @Niedzwiedzw, removing wee_alloc worked for me.
I had the problem that Chrome's garbage collector went crazy after couple of minutes until it crashed and disabling Chrome performance tools didn't make a difference

**Comment by Niedzwiedzw** [comment]
wowowow, really? I haven't tested yet, gonna do that when I grt home

**Comment by alice-i-cecile** [comment]
@Tarnadas, just to clarify, were you using wee_alloc in your own program and removing it fixed it? We don't appear to use wee_alloc in Bevy itself.

**Comment by Tarnadas** [comment]
Yes I was using it in my own program, because almost every WASM guide suggests to use it, if you want to shrink binary size.
I know that it’s not part of bevy

**Comment by bjorn3** [comment]
The savings fron using wee_alloc instead of the default dlmalloc are neglectible in comparison with the size of bevy itself. In addition wee_alloc is slow and suffers a lot from memory fragmentation.
