### ISSUE TITLE
Bevy_render fails to build with error E0658

### ISSUE THREAD

**Issue by eliaspekkala** [bevyengine/bevy#4862]
## Bevy version

Bevy main@https://github.com/bevyengine/bevy/commit/d353fbc6ea9e0c4fa69fc3b8e646e1ce79fbbc16

## Operating system & version

Operating system: Alpine Linux v3.16 x86_64
Rustc version: 1.60.0

## What you did

I did `cargo build` and got an error and a failed build.

I have the `wayland` and `dynamic` features enabled.

## What you expected to happen

Bevy would build successfully.

## What actually happened
```bash
desktop:~/Documents/bevy$ cargo build
   Compiling bevy_render v0.8.0-dev (/home/elias/Documents/bevy/crates/bevy_render)
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
  --> crates/bevy_render/src/render_resource/buffer_vec.rs:17:6
   |
17 | impl<T: Pod> BufferVec<T> {
   |      ^
18 |     pub const fn new(buffer_usage: BufferUsages) -> Self {
   |     ---------------------------------------------------- function declared as const here
   |
   = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `bevy_render` due to previous error
```

## Additional information

The lines that produce the error were last changed here: https://github.com/bevyengine/bevy/commit/b6eededea454cc3c44492f0ff76a0604f2e27921

**Comment by james7132** [comment]
Try updating to rustc 1.61. This should let it compile.

**Comment by alice-i-cecile** [comment]
Closing this out; the suggestion given should work. If it doesn't, let us know :)

**Comment by eliaspekkala** [comment]
That will probably work. Thanks. I haven't been able to try it yet since Rust 1.61 is not yet available through my package manager (even though I run rolling-release). Closing this issue is fine.
