### ISSUE TITLE
Unable to run bevy  (or webgpu) in workspace

### ISSUE THREAD

**Issue by erikpa1** [bevyengine/bevy#4870]
## Bevy version
0.7

## Operating system & version

Windows 10

## What you did

Hi I divide my project to workspace, where I have:

[workspace]
members = [
    "myapp_core"
    "myapp"
]

and **myapp** contains bevy includes and first start code from github page, after build I get error:

```
error: Metal API enabled on non-Apple OS. If your project is not using resolver="2" in Cargo.toml, it should.
  --> C:\Users\erikp\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-hal-0.12.5\src\lib.rs:51:1
   |
51 | compile_error!("Metal API enabled on non-Apple OS. If your project is not using resolver=\"2\" in Cargo.toml, it should.");
```

Is there some problem with running bevy / webgpu in workspaces ? I tried to add resolver but it didn't helped

[package]
name = "buildTest"
version = "0.1.0"
edition = "2021"
resolver ="2"

**Comment by devil-ira** [comment]
`resolver = "2"` needs to be added under `[workspace]`.

**Comment by erikpa1** [comment]
Oh stupid me, thanks :D :D

**Comment by mickare** [comment]
It took me a long time (+1 week) to find this solution. We need to add this information to the docs and howtoguide.
^^'
