### ISSUE TITLE
Automatically create labels for events?

### ISSUE THREAD

**Issue by SUPERCILEX** [bevyengine/bevy#4872]
## What problem does this solve or what need does it fill?

I've found that I keep creating labels for systems that write events so that I can create a fence between the readers and writers. I've also done this with ResMut systems.

## What solution would you like?

I don't know if this is a good idea, but it might be helpful to auto generate labels for events and resources (maybe even mutable queries if it's cheap) that get applied to systems that write to those things. Then you can add systems that go before or after anything that writes to an event, resource, or component.

## What alternative(s) have you considered?

Manually label stuff which is error prone. Then again it's not that hard and I don't know if the automation is worth it.

**Comment by alice-i-cecile** [comment]
Automatic reads and writes labels are an interesting idea.

I think I like the ergonomics, but I'm a bit worried about significant schedule construction costs.

I think that should be fine; this will be linear time with n in the hundreds.

**Comment by SUPERCILEX** [comment]
> I'm a bit worried about significant schedule construction costs.

Yeah, my thought here is that you probably need to define a label anyway for correctness so doing it automatically shouldn't come at an additional cost (in theory).

**Comment by alice-i-cecile** [comment]
Condensing into #7857, which is more general <3
