### ISSUE TITLE
Center Window on Windows

### ISSUE THREAD

**Issue by Rigidity** [bevyengine/bevy#4876]
## What problem does this solve or what need does it fill?

The window is not currently centered on Windows, but is on MacOS. This is inconsistent and can be pretty annoying.

## What solution would you like?

The window to be centered by default, or for there to be a `WindowDescriptor` field and or `Window` method that centers the window. The `position` does not help here, since it can't be centered before the window is created and shown.

## What alternative(s) have you considered?

I have tried setting the `position` in a startup system to get around this, based on the window size. This does work, but it is off-center for around a second which looks particularly bad.

I believe there is a way to do this in `winit`, but this is something that should be part of the `Window` API and not require using platform-specific code for.

**Comment by object71** [comment]
Did you try adding ```WindowDescriptor``` before adding any bevy plugins? Specifically either the default plugins or the window plugins.

**Comment by Rigidity** [comment]
Yes, this is not the issue. The `WindowDescriptor` has no way to center windows.

**Comment by alice-i-cecile** [comment]
Closed by #4999.
