### ISSUE TITLE
entity show and hide

### ISSUE THREAD

**Issue by griffenliu** [bevyengine/bevy#4907]
## What problem does this solve or what need does it fill?

I don't think it's very convenient to show and hide entities, wish there was a more convenient API like:
commands.entity(entity).show(recursive:bool);
commands.entity(entity).hide(recursive:bool);

be similar to
commands.entity(entity).despawn_recursive();

**Comment by james7132** [comment]
I believe #2087 attempted to tackle this. There's also #4216 that attempts to generalize transform propagation to provide similar capabilities.
