### ISSUE TITLE
EntityCommands get mutable reference to added components

### ISSUE THREAD

**Issue by starwolfy** [bevyengine/bevy#4917]
## What problem does this solve or what need does it fill?

When implementing modular systems-based entity spawning, you gather `Commands` to obtain `EntityCommands` for the specific entity that is being spawned in the series of added entity builder systems running that frame. Sometimes one entity builder system wants to obtain a mutable component a previous builder already added to that specific *(ie adding an offset to the entity's existing `Transform` component)*. To my knowledge, this is not possible right now.

## What solution would you like?

Some methods similar to that of `Query`. Ie `get_component` and `get_component_mut` get added to `EntityCommands`.

## What alternative(s) have you considered?

One could add their own resource shared across those entity building systems and store&modify components through it and add a final system that wraps it up and adds it to `EntityCommands`.

## Additional context

In the context of plugins expanding the default spawn components of each entity: plugins would insert their own labeled builder systems to the loop to tap into the spawning process of entities coming to life in the next frame from the `EntityCommands` frame. Currently, you cannot obtain or edit components that have already been passed to `EntityCommands` and building entities this way requires your own Resource that has to be some type of generic component container with various implementations to deal with it.

**Comment by bushrat011899** [comment]
As an alternative to adding this functionality to Bevy itself, you can get this functionality entirely through the published API and a `trait`. This is based on my PR #9544, which provides the same functionality, just without the use of a `trait`. In my opinion, either #9544 could be accepted, or the below could be used to justify closing this issue.

<details>
  <summary>Trait Implementation</summary>
  
```rust
use bevy_ecs::prelude::*;

/// Provides access to [`WithQuery::with_query`] and [`WithQuery::with_query_filtered`].
pub trait WithQuery {
    /// Allows querying of an entity's components with a filter. This is most useful when working
    /// with a highly composed entity where you wish to modify some of its components.
    fn with_query_filtered<Q, F>(
        &mut self,
        function: impl for<'t> FnOnce(Q::Item<'t>) + Send + 'static,
    ) -> &mut Self
    where
        Q: WorldQuery + 'static,
        F: ReadOnlyWorldQuery + 'static;

    /// Allows querying of an entity's components. This is most useful when working with a highly
    /// composed entity where you wish to modify some of its components.
    fn with_query<Q>(
        &mut self,
        function: impl for<'t> FnOnce(Q::Item<'t>) + Send + 'static,
    ) -> &mut Self
    where
        Q: WorldQuery + 'static,
    {
        self.with_query_filtered::<Q, ()>(function)
    }
}

impl WithQuery for EntityCommands<'_, '_, '_> {
    fn with_query_filtered<Q, F>(
        &mut self,
        function: impl for<'t> FnOnce(Q::Item<'t>) + Send + 'static,
    ) -> &mut Self
    where
        Q: WorldQuery + 'static,
        F: ReadOnlyWorldQuery + 'static
    {
        self.add(move |entity: Entity, world: &mut World| {
            let mut query = world.query_filtered::<Q, F>();

            if let Ok(result) = query.get_mut(world, entity) {
                function(result);
            };
        });

        self
    }
}
```
  
</details>

```rust
use bevy_ecs::prelude::*;

#[derive(Resource)]
struct PlayerEntity { entity: Entity }

#[derive(Component)]
struct Health(u32);

#[derive(Component)]
struct LuckyStart;

fn spawn_player(mut commands: Commands, player: Res<PlayerEntity>) {
    commands
        .entity(player.entity)
        .insert((Health(100), LuckyStart))
        /* ... */
       .with_query_filtered::<&mut Health, With<LuckyStart>>(|mut health| {
            // Players with the LuckyStart component start with double health.
            health.0 *= 2;
        });
}
```

**Comment by alice-i-cecile** [comment]
I much prefer the solution proposed here, to implement `EntityCommand` for `FnOnce(EntityMut)`:

https://github.com/bevyengine/bevy/pull/9544#issuecomment-1694355624

**Comment by bushrat011899** [comment]
Ok so I've had a crack at implementing this but I've hit a usability road-block that I think I just need some advice on. Because `EntityCommand` is already implemented for `FnOnce(Entity, &mut World)`, in order to implement it for `FnOnce(EntityMut)` as well, I think we need to add a level of indirection first.

What I tried was adding the following types:

```rust
struct EntityCommandFunction<F, Args> {
    f: F,
    _phantom: PhantomData<(F, Args)>,
}

trait IndirectEntityCommandFunction<Args> {
    fn apply(self, id: Entity, world: &mut World);
}

pub trait IntoEntityCommand<C: EntityCommand> {
    fn into_entity_command(self) -> C;
}
```

I can then implement `EntityCommand` for the indirect `EntityCommandFunction` type:

```rust
impl<F, Args> EntityCommand for EntityCommandFunction<F, Args>
where
    Args: Send + 'static,
    F: IndirectEntityCommandFunction<Args> + Send + 'static,
{
    fn apply(self, id: Entity, world: &mut World) {
        self.f.apply(id, world);
    }
}
```

Which would let me implement `EntityCommand` for two different function signatures:

```rust
impl<F> IndirectEntityCommandFunction<(Entity, &mut World)> for F
where
    F: FnOnce(Entity, &mut World) + Send + 'static,
{
    fn apply(self, id: Entity, world: &mut World) {
        self(id, world);
    }
}

impl<'w, F> IndirectEntityCommandFunction<EntityMut<'w>> for F
where
    F: FnOnce(EntityMut) + Send + 'static,
{
    fn apply(self, id: Entity, world: &mut World) {
        self(world.entity_mut(id));
    }
}
```

To then allow the `.add(...)` function to accept a closure which could become an entity command, I add the following `From` and `Into` implementations:

```rust
impl<T, C: EntityCommand> IntoEntityCommand<C> for T
where
    T: Into<C>,
{
    fn into_entity_command(self) -> C {
        self.into()
    }
}

impl<F, Args> From<F> for EntityCommandFunction<F, Args>
where
    Args: Send + 'static,
    F: IndirectEntityCommandFunction<Args> + Send + 'static,
{
    fn from(value: F) -> Self {
        Self {
            f: value,
            _phantom: PhantomData,
        }
    }
}
```

And modify `.add(...)` to accept anything that can become an `EntityCommand`:

```rust
pub fn add<C: EntityCommand>(&mut self, command: impl IntoEntityCommand<C>) -> &mut Self {
    let command = command.into_entity_command();
    self.commands.add(command.with_entity(self.entity));
    self
}
```

All this nonsense does preserve the current usage of `.add(..)` for concrete types that implement `EntityCommand`, but for closures, a type hint is required:

```rust
Commands::new(&mut command_queue, &world)
    .entity(entity)
    .add::<EntityCommandFunction<_, _>>(|id: Entity, world: &mut World| {
        /* no-op */
    })
    .add::<EntityCommandFunction<_, _>>(|mut entity: EntityMut| {
        let mut w = entity.get_mut::<W<u32>>().unwrap();
        w.0 *= 2;
    });
```

This all works, but I think that end result isn't very nice to use. I think the simpler option would be to just add an alternate signature for adding "arbitrary" closures as `EntityCommand`s:

```rust
Commands::new(&mut command_queue, &world)
    .entity(entity)
    // One FnOnce signature can be cannon for this, so this preserves this fuinction
    .add(|id: Entity, world: &mut World| {
        /* no-op */
    })
    .add_function(|mut entity: EntityMut| {
        let mut w = entity.get_mut::<W<u32>>().unwrap();
        w.0 *= 2;
    })
    .add_function(|id: Entity, world: &mut World| {
        /* no-op */
    })
    .add_function(|id: Entity| {
        /* no-op */
    });
```

The problem with that is I think we've just looped back onto #9544 but with extra steps. Anyone have any suggestions?

**Comment by alice-i-cecile** [comment]
Hmm. That indirection is quite unfortunate. I can see why it's needed: the conflicting blanket impls since it's technically possible for a single type to implement multiple `Fn` traits with different signatures :/

What if we had a dedicated method on `EntityCommands`? E.g.

```rust
impl EntityCommands<'w, 's> {
   fn mutate<F: FnOnce(EntityMut)>(&mut self, function: F) -> &mut Self
}
```

That avoids breaking anything, but should still preserve a nice API.

**Comment by bushrat011899** [comment]
> Hmm. That indirection is quite unfortunate. I can see why it's needed: the conflicting blanket impls since it's technically possible for a single type to implement multiple `Fn` traits with different signatures :/
> 
> What if we had a dedicated method on `EntityCommands`? E.g.
> 
> ```rust
> impl EntityCommands<'w, 's> {
>    fn mutate<F: FnOnce(EntityMut)>(&mut self, function: F) -> &mut Self
> }
> ```
> 
> That avoids breaking anything, but should still preserve a nice API.

I think that's the least-worst option. I'll make a PR for an implementation of this shortly. Just to spur discussion on naming:

1. `mutate`
2. `add_mutation`
3. `add_entity_mutation`
4. `for_entity_mut`

I personally like number 4, `for_entity_mut`, but I'm open to being told otherwise!
