### ISSUE TITLE
Add spawn callback for scene entities

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#4933]
## What problem does this solve or what need does it fill?

When spawning a scene, you often need to add additional components. For example, generate a collision from a mesh or assign a collision group.

## What solution would you like?

It would be great to be able to specify a closure with [EntityCommands
](https://docs.rs/bevy/latest/bevy/ecs/system/struct.EntityCommands.html) and [EntityRef](https://docs.rs/bevy/latest/bevy/ecs/world/struct.EntityRef.html) as arguments which will be called for each spawned entity from scene.

So I would suggest adding a bean called `SceneHook` with a closure that users can assign on scenes. For convenience, I would add it to `SceneBundle` introduced in #2424.

Example:

```rust
commands.spawn_bundle(SceneBundle {
    scene: asset_server.load("models/FlightHelmet/FlightHelmet.gltf#Scene0"),
    hook: SceneHook::new(|entity_ref, entity_commands| {
        if let Some(mesh) = entity_ref.get::<Mesh>() {
            // Entity have mesh, let's assign collision:
            entity_commands.insert(RigidBody::Fixed);
            entity_commands.insert(Collider::from_bevy_mesh(mesh));
        } else if let Some(name) = entity_ref.get::<Name>() {
            // Can insert some components based on name
        }
    }),
    ..Default::default()
});
```

## What alternative(s) have you considered?

* Scene spawn events (was suggested in #2218)
* `SceneRoot` component that users can monitor for addition using a variety of change detection tools (was suggested by `@cart` in [this](https://github.com/bevyengine/bevy/issues/2218#issuecomment-1032064091) comment).

But both approaches require adding a separate system for each scene for which you need to add components after spawn. Also it forces user to create a separate component for each scene to somehow differentiate events or added `SceneRoot`s in "post-spawn" systems.

**Comment by alice-i-cecile** [comment]
Can you give a realistic snippet of what this proposed API would look like? I'm having a bit of trouble piecing together the design and its value.

**Comment by MrGVSV** [comment]
Yeah a snippet would be helpful. I don't think it can just take an `EntityCommands`. You might also need to query or check resources. Maybe even full access to the `&mut World`.

**Comment by Shatur** [comment]
Here is how I imagined it:

```rust
let map = asset_server.load("my_map.gltf");
commands.spawn_scene(map).with_commands(|entity_commands| {
    entity_commands.insert(RigidBody::Fixed);
});
```

In heron we have [PendingConvexCollision](https://github.com/jcornaz/heron/pull/190) and in rapier we have [AsyncSceneCollider](https://github.com/dimforge/bevy_rapier/pull/160) for it. In Heron it just copy physics-based components from the root and assign them to all children with meshes, but the list of components is just hardcoded. In Rapier it just assigns colliders, so I was going to submit a PR with behavior similar to heron, but then I realized that we probably could solve it here.

> Maybe even full access to the &mut World.

Yes, you are right. I think we should have a world and an `Entity` instead of `EntityCommands`.

**Comment by alice-i-cecile** [comment]
I don't know if `EntityCommands` is the right paradigm here 🤔 Scenes can contain multiple entities. I think you probably want the `&mut World` version and some helper APIs for common tasks. Or a version of entity commands that applies to all entities in the scene?

**Comment by Shatur** [comment]
> I don't know if EntityCommands is the right paradigm here thinking Scenes can contain multiple entities.

I would expect to have this callback called for each spawned entity. Here is a better example:

```rust
let map = asset_server.load("my_map.gltf");
commands.spawn_scene(map).with_commands(|world, entity_commands| {
    if let Some(mesh) = world.entity(entity_commands.id()).get::<Mesh>() {
        // Entity have mesh, let's assign collision:
        entity_commands.insert(RigidBody::Fixed);
        entity_commands.insert(Collider::from_bevy_mesh(mesh));
    }
});
```

Having [EntityRef](https://docs.rs/bevy/latest/bevy/ecs/world/struct.EntityRef.html) instead of world could be nicer to read, but it could be more limiting.

**Comment by nicopap** [comment]
I've came up with something here https://github.com/nicopap/bevy-scene-hook Which seems to be _exactly what you are describing_. There is a `world` module with access to the world (which I use in some private code to do exactly what you are describing). It call some `hook_node` method once for each entity with a `Name` field spawned from a specified scene. (I think it would combine amazingly with https://github.com/bevyengine/bevy/pull/2424) I've an update coming up with some improvement. Notably the ability for it to work for more than a single loaded scene.

**Comment by nicopap** [comment]
Ok. Having read your issue more carefully. You seem to specifically not want that, but rather want a "lightweight" sort of thing, that doesn't require adding a system to the schedule. `bevy-scene-hook` does require adding a  system to the schedule. But I think it's really not a big loss, since you statically need to know what kind of scenes you are spawning, usually, and you also need to know the hierarchy of your scene (or stuff like names of some entities) to add the correct components to the correct entity (which is something you are overlooking in describing this issue).

**Comment by Shatur** [comment]
Looks nice. But instead of name I would use [EntityRef](https://docs.rs/bevy/latest/bevy/ecs/world/struct.EntityRef.html) to be able to access components. To generate collisions from mesh, for example.

**Comment by Shatur** [comment]
> You also need to know the hierarchy of your scene (or stuff like names of some entities) to add the correct components to the correct entity (which is something you are overlooking in describing this issue).

With `EntityRef` you will be able to get `Name` component. And the callback is specific to spawned scene. This is exactly the problem that this proposal is supposed to solve :) Because the suggested events in #2218 or change detection of `SceneRoot` isn't enough.

**Comment by MrGVSV** [comment]
> So what if we add a component called SceneHook, similar to what https://github.com/nicopap/bevy-scene-hook with the mentioned callback?

Should this be included in `SceneBundle` directly? Since they're so related at least.

**Comment by Shatur** [comment]
> Should this be included in SceneBundle directly? Since they're so related at least.

I thought of it, but declaring a boxed closure will look like this:

```rust
commands.spawn_bundle(SceneBundle {
    scene: asset_server.load("models/FlightHelmet/FlightHelmet.gltf#Scene0"),
    hook: Box::new(|entity_ref, entity_commands| {
        if let Some(mesh) = entity_ref.get::<Mesh>() {
            // Entity have mesh, let's assign collision:
            entity_commands.insert(RigidBody::Fixed);
            entity_commands.insert(Collider::from_bevy_mesh(mesh));
        } else if let Some(name) = entity_ref.get::<Name>() {
            // Can insert some components based on name
        }
    }),
    ..Default::default()
});
```

Or is it okay?
We could avoid having box by replacing it with `fn`, but it means that users won't be able to move anything to it.
With `SceneHook::new` we could use somethings like `impl FnOnce(&EntityRef, EntityCommands)`.

**Comment by nicopap** [comment]
I made a prototype that mirrors this PR's `SceneBundle`:
- The definition: https://github.com/nicopap/bevy-scene-hook/blob/8346709ae9966c34ee6712f749420347a8373aa7/src/lib.rs#L13-L19
- Example usage: https://github.com/nicopap/bevy-scene-hook/blob/8346709ae9966c34ee6712f749420347a8373aa7/src/hook.rs#L68-L79

**Comment by Shatur** [comment]
@MrGVSV, oh, right, updated the description with your suggestion.

> I made a prototype that mirrors this PR's SceneBundle:

I like it, but I would remove the trait and use `Box<dyn FnOnce(&EntityRef, &mut EntityCommands)>` as the `SceneHook` field. Things like:

```rust
hook: SceneHook::new_comp::<Name, _>(move |name, cmds| hook(&decks, name.as_str(), cmds)),
```

and

```rust
hook: SceneAssets {
    deck: deck_assets.clone(),
    cards: cards_assets.clone(),
}.into(),
```

Looks awkward as to me. So I would replace `new`, `new_fn` and `new_comp` with a single `new` with closure as an argument.

**Comment by Shatur** [comment]
Closing per https://github.com/bevyengine/bevy/pull/4980#issuecomment-1161394951 (better to modify scenes once loaded as discussed in https://github.com/bevyengine/bevy/discussions/3972)
Until we have a better asset system we could use https://github.com/nicopap/bevy-scene-hook to solve the problem.
