### ISSUE TITLE
Avoid unwrap log initialization

### ISSUE THREAD

**Issue by allevo** [bevyengine/bevy#4934]
## What problem does this solve or what need does it fill?

I would like to test heavily my application. Obviously my test suite is composed by multiple test and every test create a new through `App::new()` and register the plugin I need to the new app instance.
Because logs are important I really would like keep them active during the tests runs.

## What solution would you like?

Remove the `unwrap` from here https://github.com/bevyengine/bevy/blob/5e2cfb2f19e0e2287fd48d55df92f78617acf831/crates/bevy_log/src/lib.rs#L127 substituting it with a different error handling.

## What alternative(s) have you considered?

Remove LogPlugin from my tests

## Additional context

```rust
// test 1
let mut app = App::new();
app.add_plugin(LogPlugin::default());
// test 2
let mut app = App::new();
app.add_plugin(LogPlugin::default()); // <----- this 
```

Error log:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', .......\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_log-0.7.0\src\lib.rs:127:27
```

**Comment by mockersf** [comment]
when you are using multiple app (or in test), you should setup login yourself, and not add the `LogPlugin` several time. That way you would have unified login and no panic 🙂

**Comment by allevo** [comment]
Hi, thanks for your comment.

I wouldn't like to configure by myself the log part because:
- this is not how other plugins work. In fact I'm able to adding them in different tests and all works fine
- tests can not behave like the debug/release build doesp
- copy and paste the code from bevy code to my one just for removing an `unwrap` is not so ok 
- could be a messy managing a own version for future changes

If my solution (adds a flag `force`) is not the best one, we can leverage on` #[config(test)]` to avoid the `unwrap`.

**Comment by bjorn3** [comment]
> we can leverage on #[config(test)] to avoid the unwrap.

`#[cfg(test)]` is only enabled for the crate actually being tested, and not for it's dependencies like `bevy_log`.

**Comment by allevo** [comment]
`unwrap` in a library still seems to me an ugly stuff...
Which approach we can take?
Just for knowing if you are interested in this enhancement or no....

**Comment by bjorn3** [comment]
Honestly to me it feels like `LogPlugin` shouldn't be a plugin in the first place as it mutates global state and doesn't affect the `App` at all. Instead I feel like it should be a `bevy::log::setup()` call at the start of `main`. This would have a negative effect on ergonomics in case only a single `App` is used though.

**Comment by allevo** [comment]
Fair enough. 
If you want, I can submit a PR for that

**Comment by Ryder17z** [comment]
> Fair enough. If you want, I can submit a PR for that

please do. having to change it locally is annoying.

**Comment by bjorn3** [comment]
Maybe the same thread pool is reused by multiple tests and once the test spawning the thread pool tests initially libtest doesn't know to which test to attribute the output anymore?

**Comment by james7132** [comment]
This was changed to a non-panicking warning in #6757.
