### ISSUE TITLE
Sprite bundle's disappear and are not being rendered if orthographic camera is being moved

### ISSUE THREAD

**Issue by jrasanen** [bevyengine/bevy#4935]
## Bevy version

Latest 0.7

## Relevant system information

Can replicate on Apple macOS, Windows and on Linux

The attached video is recorded on:

`AdapterInfo { name: "AMD Radeon Pro 5500M", vendor: 0, device: 0, device_type: DiscreteGpu, backend: Metal }`

## What you did

Translating camera like so causes sprite bundles to disappear after a while,

```rust
fn spawn_camera_follow(
    time: Res<Time>,
    actions: Res<Actions>,
    mut camera_query: Query<&mut Transform, (With<Camera2d>)>,
) {
    for mut transform in camera_query.iter_mut() {


        if let Some(mouse) = actions.mouse_right_drag {
            if mouse.is_nan() {
                return;
            }
            transform.translation = transform
                .translation
                .lerp(mouse.extend(0.0), time.delta_seconds() * 1.2);
        }
    }
}
```

## Additional information

- Reproduction repo: https://github.com/jrasanen/bevy-disappearing-sprites-issue-debug

### Videos of the issue

From reproduction repo:

https://user-images.githubusercontent.com/13303/172063359-8f63ca6a-d6c1-4bd7-ac10-566e3e5a81f3.mov

Issue in my own small project. Sprite bundles disappear in the order. Last one created disappears first:

https://user-images.githubusercontent.com/13303/172063551-c204b585-12d0-4123-b8bd-b907787ee1a7.mp4

**Comment by superdump** [comment]
I think the z component of the translation is meant to be far - 0.1 which by default is 1000.0 - 0.1: https://github.com/bevyengine/bevy/blob/f487407e07c15af878e0d6886f9cd4c146f1f94f/crates/bevy_core_pipeline/src/core_2d/camera_2d.rs#L62 If you make that change, does that work?

**Comment by mockersf** [comment]
could you try with:
```
            transform.translation = transform
                .translation
                .lerp(mouse.extend(transform.translation.z), time.delta_seconds() * 1.2);
```

**Comment by jrasanen** [comment]
Ah, of course. That makes total sense: I’m also lerping away my z-index 🤦 

Thank you!
