### ISSUE TITLE
Add example for testing systems that use events.

### ISSUE THREAD

**Issue by its-danny** [bevyengine/bevy#4936]
I couldn't find any good examples of this. Got some help on the Discord and it seems to work, but would be nice to have some clear examples. Could potentially extend [this example](https://github.com/bevyengine/bevy/blob/main/tests/how_to_test_systems.rs).

```rust
fn test() {
    let mut app = App::new();

    app.add_event::<NetworkInput>();
    app.add_event::<NetworkOutput>();
    app.add_system(super::do_things);

    app.world
        .resource_mut::<Events<NetworkInput>>()
        .send(NetworkInput {
            // ...
        });

    app.update();

    let output_events = app.world.resource::<Events<NetworkOutput>>();
    let mut output_reader = output_events.get_reader();
    let output = output_reader.iter(&output_events).next().unwrap();

    // assert on `output`
}
```

**Comment by its-danny** [comment]
I'm down to add this myself, just don't want to open a PR without having an issue created and going through whatever discussion/triaging happens.

**Comment by alice-i-cecile** [comment]
I think extending that example is a great place to start! I started on this in https://github.com/bevyengine/bevy/pull/3839, but feel free to go ahead and I'll adapt my changes to your PR.
