### ISSUE TITLE
wasm builds are broken: 'data' : array members of structs must specify a size

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#4946]
## Bevy version

main. this happens since cc4062ec4359b80a8c88a63aa45f17c681bb0e71 (https://github.com/bevyengine/bevy/pull/4867)

## What you did

Run the lighting example in wasm

## What went wrong

```
panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `shadow_pipeline`
    Internal error in VERTEX shader: ERROR: 0:39: 'data' : array members of structs must specify a size
ERROR: 0:42: 'data' : array members of structs must specify a size
ERROR: 0:45: 'data' : array members of structs must specify a size
```

**Comment by superdump** [comment]
The array sizes should depend on the NO_STORAGE_BUFFER_SUPPORT shader def. They’re in the mesh_view_bindings.wgsl I think. Could it be that shader_defs in imported files aren’t working or something? But they were previously in mesh_view_bind_group.wgsl with a similar setup. I think most of what I changed was to split out the types into mesh_view_types.wgsl and then mesh_view_bindings.wgsl imports the types.

**Comment by superdump** [comment]
https://github.com/bevyengine/bevy/blob/cc4062ec4359b80a8c88a63aa45f17c681bb0e71/crates/bevy_pbr/src/render/mesh.rs#L585 Here is where the shader def is added during specialisation.

**Comment by superdump** [comment]
And the shader preprocessor stuff is here: https://github.com/bevyengine/bevy/blob/b47291264b4d2508e288b4ec122589d3aae7a0e5/crates/bevy_render/src/render_resource/shader.rs#L386
