### ISSUE TITLE
`AlphaMode::Mask` keeps shadow on invisible objects

### ISSUE THREAD

**Issue by MiniaczQ** [bevyengine/bevy#4969]
## Problem

While `AlphaMode::Opaque` renders shadow as intended, `AlphaMode::Blend` renders shadow in full opacity as intended,
`AlphaMode::Blend(f32)` still renders shadow on all objects, despite them only being fully opaque or fully transparent.

## Example

This is clearly visible in the `transparency_3d` example. (One of the spheres is masked away, yet still has a shadow)

![image](https://user-images.githubusercontent.com/13040204/172722416-d0abde85-9135-4e86-986f-f57327d8cf5b.png)

**Comment by superdump** [comment]
This was covered in another issue but I don’t remember which it was at the moment.

**Comment by MiniaczQ** [comment]
I've checked 2 other issues which had to do with `Mask` and shadow casting, but I didn't see it pointed out, at least directly.
Those are:
#4576 - platform issue
#4372 - similar, but about the shape of the shadow instead

I guess the main difference is, if the whole object is masked away, there is no need to render it what so ever.

**Comment by JonahPlusPlus** [comment]
How about creating a `ShadowMode` enum (this would be a solution to #4372 as well)? Like `AlphaMode` but for shadows. If #4372 gets solved by applying the alpha mask to shadow, it might make sense to also have a mode for blending shadows together like `AlphaMode::Blend` does with textures. They could all be in one enum, so: `ShadowMode::Opaque`, `ShadowMode::Mask(f32)`, `ShadowMode::Blend` and `ShadowMode::None`.

Pros: More control
Cons: If there is a default, you would have to set it every time in the material (Default for corresponding `AlphaMode` could be provided by making `StandardMaterial.shadowMode` be an `Option<ShadowMode>`, and using a default shadow mode if `None`)

**Comment by james7132** [comment]
This should be fixed now that we're using prepass shaders for shadows.
