### ISSUE TITLE
Adding a child to an entity with sprite components occassionally makes that entity and it's parents invisible

### ISSUE THREAD

**Issue by Matthew-Maclean** [bevyengine/bevy#498]
When adding a child to an entity that has sprite components, sometimes the entity and some (but not always all) of it's parents become invisible, adding further children sometimes resolves this, but not permanently.

Here's the code that I'm using to get this, there is a single red square in the center on startup:

In full disclosure, the 2D camera I'm using has been zoomed in (`scale = 1.0 / 80.0`), and had it's `far = 1000.0 / scale`.

```rust
struct ChildMarker;

 fn add_children(
     mut commands: Commands,
     keys: Res<Input<KeyCode>>,
     mut mats: ResMut<Assets<ColorMaterial>>,
     mut query: Query<Without<ChildMarker, (Entity, &Sprite)>>)
 {
     if keys.just_pressed(KeyCode::C)
     {
         for (entity, _) in &mut query.iter()
         {
             let child = commands
                 .spawn(SpriteComponents
                 {
                     sprite: Sprite { size: Vec2::new(1.0, 1.0), },
                     draw: Draw
                     {
                         is_transparent: true,
                         ..Default::default()
                     },
                     material: mats.add(ColorMaterial::color(
                         Color::rgba(0.0, 1.0, 0.0, 0.25))),
                     translation: Translation::new(-0.5, -0.5, 0.1),
                     ..Default::default()
                 })
                 .current_entity()
                 .unwrap();

             commands.push_children(entity, &[child]);

             commands.insert_one(entity, ChildMarker);
         }
     }
 }
```

![examples](https://user-images.githubusercontent.com/20546688/93268691-9de09280-f77b-11ea-9d6e-55fa5a4af8b7.png) Above are some images that show what's happening. You can clearly see when some squares are missing, and that they re-appear later.

**Comment by memoryruins** [comment]
Thanks for reporting! If you're using version `0.1.3`, this is likely the same root issue experienced in #328 and #440 , which has been fixed in master.

**Comment by Matthew-Maclean** [comment]
Yes, I am using `0.1.3`, and I can confirm that after updating to the latest commit (as of this comment), and doing a bit of fiddling with the new transform system, it works as expected.

As an aside, is there anywhere that hosts the docs for the latest commit, or do I have to build them myself if I want them?

**Comment by cart** [comment]
Fantastic. Currently we don't host `master` docs anywhere. You'll need to build them yourself using `cargo doc --open`
