### ISSUE TITLE
The example with scale component return different result after transform rewrite #374

### ISSUE THREAD

**Issue by langbamit** [bevyengine/bevy#499]
Run: `cargo r --example texture_atlas` on master

Before https://github.com/bevyengine/bevy/pull/374:
![image](https://user-images.githubusercontent.com/43192714/93293030-3412c800-f811-11ea-8191-b3e4fb9988ba.png)

After https://github.com/bevyengine/bevy/pull/374:
![image](https://user-images.githubusercontent.com/43192714/93293077-53a9f080-f811-11ea-8544-f58f083ecb71.png)

P/s: my English is not good

**Comment by cart** [comment]
Yup this is definitely broken. Rotation suffers from the same problem. We need to "untranslate" first I think.

**Comment by cart** [comment]
Resolved by #500
