### ISSUE TITLE
Use `surface.get_preferred_format()` to prevent crashes on wayland with nvidia cards.

### ISSUE THREAD

**Issue by HeavyRain266** [bevyengine/bevy#4995]
## What problem does this solve or what need does it fill?

Currently bevy usee hardcoded sRGB surface format which is not (yet) supported by nvidia on linux.

## What solution would you like?

Straight forward solution is to request GPUs' prefered surface format which will use best available on each platform.

## What alternative(s) have you considered?

Perhaps we could wait months or even years until nvidia decides on adding sRGB support on Wayland.

## Additional context

None.

**Comment by bjorn3** [comment]
> Straight forward solution is to request GPUs' prefered surface format which will use best available on each platform.

Doing so correctly will require adding code to convert from sRGB to whichever colorspace said surface format uses, which isn't straight forward in the general case.

**Comment by johanhelsing** [comment]
We no longer crash, but randomly choose the first available format the compositor reports. Explained in f5322cd757. On proprietary nvidia drivers on wayland, this results in `ARGB8888`, which means all the colors are too dark, see #7318
