### ISSUE TITLE
Some tests sometimes randomly fail

### ISSUE THREAD

**Issue by LoipesMas** [bevyengine/bevy#4996]
## Bevy version
[f969c62](https://github.com/bevyengine/bevy/commit/f969c62f7bfaf1932fbb533dfd87467aeddf75cb)

## What you did

Run `cargo test` (in `crates/bevy_transform`)

## What went wrong

Sometimes (~10% of the time) test `systems::test::correct_transforms_when_no_children` or `systems::test::did_propagate_command_buffer` fail.

## Additional information
Output:
```
---- systems::test::correct_transforms_when_no_children stdout ----
thread 'systems::test::correct_transforms_when_no_children' panicked at 'assertion failed: `(left == r
ight)`
  left: `1v0`,
 right: `2v0`: Malformed hierarchy. This probably means that your hierarchy has been improperly mainta
ined, or contains a cycle', crates/bevy_transform/src/systems.rs:69:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    systems::test::correct_transforms_when_no_children
```
Same assert fails for `systems::test::did_propagate_command_buffer`.
Considering it happens randomly it's probably a race-condition.

I'm on Linux, but it also happens on GitHub CI (see #4994), so I assume my system information is not relevant.

Also, during my testing it happened ~7 times for `correct_transforms_when_no_children` and once for `systems::test::did_propagate_command_buffer`.

**Comment by LoipesMas** [comment]
Some more testing:
- Running only, for example, `correct_transforms_when_no_children` hasn't failed.
- Running `cargo test --jobs 1` can fail.

**Comment by mockersf** [comment]
git bisect seems to point to https://github.com/bevyengine/bevy/pull/2250 as causing the issue

**Comment by alice-i-cecile** [comment]
Ping @james7132 and @hymm; any ideas?

**Comment by hymm** [comment]
how do globals work in cargo tests? Does each test get it's own instance or are the sharing them?

**Comment by bjorn3** [comment]
They are shared as tests run in the same process on unique threads.

**Comment by hymm** [comment]
it looks like the tests don't explicitly order `transform_propagate_system` and `parent_update`, but the plugins do. Maybe they would run in the added order normally, but with #2250 the executors get starved they can run in the reverse order sometimes.

**Comment by hymm** [comment]
hmm, adding an explicit ordering didn't fix the problem.

I think it has something to do with the panicking test. If I #[ignore] that test the problem seems to go away. Maybe if one of the other tests tasks gets onto the local queue of the thread that panics that causes a problem? I'm not sure what will happen to the task in that scenario.

**Comment by hymm** [comment]
opened https://github.com/bevyengine/bevy/pull/4998 to fix this. @LoipesMas can you test the PR and see if it fixes things for you?

**Comment by LoipesMas** [comment]
Yep, that fixed it!
