### ISSUE TITLE
Issue/Weird behaviour with VerticalAlignment::Center/Bottom (Text2dBundle) while using variable fonts.

### ISSUE THREAD

**Issue by FarmingtonS9** [bevyengine/bevy#5018]
## 0.7.0

The release number or commit hash of the version you're using.

Relevant system information
OS Name: Microsoft Windows 10 Home	
Version: 10.0.19043 Build 19043	
System Type: x64-based PC	
Processor: AMD Ryzen 7 3700X 8-Core Processor, 4200 Mhz, 8 Core(s), 16 Logical Processor(s)
Graphics Card: NVidia RTX 2070 8GB (Driver version: 511.23)	
Installed Physical Memory (RAM): 32.0 GB

Rust version: rustc 1.61.0 (fe5b13d68 2022-05-18)
AdapterInfo { name: "NVIDIA GeForce RTX 2070", vendor: 4318, device: 7943, device_type: DiscreteGpu, backend: Vulkan }

## What you did

Attempting to set the vertical field with VerticalAlignment (Center or Bottom) inside the TextAlignment struct, of Text2dBundle.

## What went wrong

2 different behaviours occur:
1. When setting VerticalAlignment to Center, the program crashes.
- Error: thread 'Compute Task Pool (6)' panicked at 'Invalid glyph_hor_side_bearing', \.cargo\registry\src\github.com-1ecc6299db9ec823\ab_glyph-0.2.15\src\ttfp.rs:334:1

2. When setting VerticalAlignment to Bottom, the program launches the window (is unresponsive) and crashes at the same time (I have to manually close the program). (This is the weird behaviour)
- Error: thread 'Compute Task Pool (5)' panicked at 'Invalid glyph_hor_side_bearing', \.cargo\registry\src\github.com-1ecc6299db9ec823\ab_glyph-0.2.15\src\ttfp.rs:334:1
## Additional information
I have no issues setting VerticalAlignment to Top.
I assume there is some error with the ab_glyph library or how Bevy works with OpenType fonts. Not sure.
The font I'm using is Nunito (https://fonts.google.com/specimen/Nunito). Specifically "Nunito-Italic-VariableFont_wght.ttf".

Other information that can be used to further reproduce or isolate the problem.
- I haven't updated my nVidia driver (I wouldn't expect this to be an issue though).
- I haven't tried setting VerticalAlignment with TextBundle.
- This is my issue I've opened on GitHub so please let me know if I've setup this issue properly. :)

**Comment by FarmingtonS9** [comment]
Further testing, with help from Elogain, shows the font is the issue. And it seems to be an error with [ab_glyph](https://github.com/alexheretic/ab-glyph).

**Comment by Elogain** [comment]
(correction: Not egui :) ) I think we can conclude its in ab_glyph, and incorrect assumptions about variable fonts. Do you want to cross post an issue there too and perhaps link to this? I read the readme's in ab_glyph and I cant see any mention of not supporting variable fonts, so either the fix is "mentioning it" or perhaps they'll fix it.

**Comment by FarmingtonS9** [comment]
Alright, I'll link it over there. Although, ab_glyph doesn't seem too active at the moment.

**Comment by FarmingtonS9** [comment]
ab_glyph has been updated with a fix. https://github.com/alexheretic/ab-glyph/issues/62#issuecomment-1158682839

**Comment by mockersf** [comment]
nice, thanks for following up on it!
