### ISSUE TITLE
Replace `ParamSet` with `GhostCell`-like system parameters

### ISSUE THREAD

**Issue by JoJoJet** [bevyengine/bevy#5041]
## What problem does this solve or what need does it fill?

Right now, `ParamSet` works fine, but it produces large and complex types, doesn't play well with `rustfmt`, and does not allow you to name the parameters. It would be ideal if we could get the functionality of `ParamSet` while still keeping the parameters separate.

## What solution would you like?

* Any `SystemParam`s that conflict with one another must be wrapped in type `ParamCell`.
    * `ParamCell` is a zero-cost wrapper that restricts access to multiple
    * Accessing the data behind `ParamCell` requires a `Token`.
* `Token` is a ZST that can only safely be produced by specifying it as a `SystemParam`. Only one may exist at a time.
* Read-only reference to `ParamCell` requires `&Token`, mutable reference requires `&mut Token`. This ensures that only one mutable parameter is accessed at a time, but allows multiple read-only parameters at once.

```rust
fn system(
    mut token: Token,
    foo: ParamCell<Query<(&Name, &Transform)>>,
    bar: ParamCell<Query<&mut Transform>>,
) {
    for _ in foo.get(&token).iter() {
        // Error: `token` is already borrowed
        // bar.get_mut(&mut token)
    }
    for _ in bar.get_mut(&mut token).iter_mut() {
        // ...
    }
}
```

...and the same in the current pre-existing design

```rust
fn system(
    // rustfmt has a grudge against bevy
    mut p: ParamSet<
        (
            Query<(&Name, &Transform)>,
            Query<&mut Transform
        )
    >,
) {
    // no names! just gotta remember
    for _ in p.p0().iter() {
        // Error: `p` is already borrowed
        // p.p1().iter_mut()
    }
    for _ in p.p1().iter_mut() {
        // ...
    }
}
```

(bikeshedding welcome)

## Problems

The current described design does not allow for multiple disjoint parameter sets within one system. This issue may be solvable by allowing a system to declare multiple tokens, and link each `PCell` to its respective token with a lifetime. 

```rust
fn system<'a, 'b>(
    mut t1: Token<'a>,
    foo1: ParamCell<'a, ResMut<Time>>,
    bar1: ParamCell<'a, Res<Time>>,

    mut t2: Token<'b>,
    mut foo2: ParamCell<'a, Query<&mut Transform>>,
    mut bar2: ParamCell<'a, Query<&Transform>>,
) -> // ...
```

The lifetimes are ugly, but they do allow the programmer to give meaningful names to groups of `ParamCell`s if they desire. This would likely make for terrible compiler errors though.

## What alternative(s) have you considered?

Just leave the current system, which is simpler. However, it is overly restrictive with read-only accesses.

**Comment by DJMcNab** [comment]
Your multiple sets suggestion is impossible, as far as I know, since we can't do runtime dispatch based on lifetimes.

An easier way to achieve naming might be to have a `derive(ParamSet)`?
It's not quite as ad-hoc, but it gets the job done.

**Comment by TheRawMeatball** [comment]
While it likely wouldn't be a derive, a paramset macro has been proposed in #4885

**Comment by Nilirad** [comment]
I actually prefer #4885 over this. The only advantage of this is that it can be inlined in a system.

**Comment by lukechu10** [comment]
I believe this is unsound because it would be possible to do something like
- System A gets a `Token` and stores it in some kind of global variable (with `lazy_static`).
- System B also gets a `Token`. System B then reads from the global variable. We now have access to two `Token`s!

We might be able to do something with lifetimes because that would prevent you from putting it into a global variable, but it would still be possible to create a `Token<'static>`.
To solve this, we need to force the system to be generic over the lifetime of the token, i.e. `for<'a> Fn(Token<'a>)` so that we can't get the `Token` a `'static` lifetime. I haven't looked at the code for `SystemParam` yet so I don't know if this would be possible.

**Comment by bag42** [comment]
S 🎉😆😆🇹🇯 se

**Comment by JoJoJet** [comment]
So I've been thinking, and I agree with the others that the derive macro solution is better. At first I didn't like it since it's more verbose, but I realized that the macro solution would be way more teachable for new users, so it's probably the best solution.
