### ISSUE TITLE
Add texture atlas stress test

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5073]
## What problem does this solve or what need does it fill?

While we can test standard 2D performance in realistic ways, we have no comparable tests that involve texture atlases.

This is particularly important as we start to build out 2D animation features.

## What solution would you like?

Add a [stress test](https://github.com/bevyengine/bevy/tree/main/examples/stress_tests) that uses [`TextureAtlas`](https://dev-docs.bevyengine.org/bevy/sprite/struct.TextureAtlas.html) heavily.

This would likely be most realistic if it involved many desynchronized sprite-sheet animations (which currently must be manually operated on). A naive tile-map texture atlas stress test may also be useful.

## Additional context

This is required by #5072.

**Comment by alice-i-cecile** [comment]
I'm unsure about whether or not to give this issue a `good-first-issue` label. Should be pretty straightforward (and fun) for experienced users of Bevy, but may be a bit frustrating if you're new to Bevy in a way that some of the simpler code quality fixes aren't.

**Comment by james-j-obrien** [comment]
I have created a stress test based on the many_sprites and sprite_sheet examples here: [many_animated_sprites](https://github.com/james-j-obrien/bevy/blob/animated-sprite-stress-test/examples/stress_tests/many_animated_sprites.rs).

It's largely just the many_sprites test swapping out SpriteBundle with SpriteSheetBundle and slightly offsetting the animations, this similarity may assist in doing "on vs off" comparisons although if the goal is to test TextureAtlas more thoroughly it might not be appropriate.

If this is the right direction I'm happy create a PR and continue iterating on it.

**Comment by alice-i-cecile** [comment]
I'm happy with that! I like the idea of doing a head-to-head comparison. A PR would be great @james-j-obrien.
