### ISSUE TITLE
Distinction between MouseMotion and CursorMoved events is unclear in docs

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5083]
## What problem does this solve or what need does it fill?

As shown in the [mouse_input_events example](https://github.com/bevyengine/bevy/blob/main/examples/input/mouse_input_events.rs), Bevy exposes both a `MouseMotion` and `CursorMoved` event type.

These are poorly documented, but it appears that `MouseMotion` is relative, while `CursorPosition` is absolute (and tied to a specific window).

## What solution would you like?

Clearly differentiate these types in the docs and explain why they both exist (and when you should use one vs the other).

## What alternative(s) have you considered?

Remove `MouseMotion`, and only expose `CursorMoved`. However,  it's not clear if `MouseMotion` can always be reconstructed; I'm particularly nervous about what happens when the cursor is locked to the screen.

## Additional context

Related to #5034, which also tries to simplify the UX here.

**Comment by alice-i-cecile** [comment]
It's also not clear why one refers to "mouse" and the other refers to "cursor". Perhaps there's a significance to this upstream in `winit`?

**Comment by alice-i-cecile** [comment]
And of course, `MouseMotion` is stored in `bevy_input`, while `CursorMoved` comes from `bevy_window`.

**Comment by DJMcNab** [comment]
My understanding is that mouse motion is about the physical motion of the actual mouse - this ignores pointer acceleration for example.

Cursor movement is about the movement of the cursor, i.e. the thing that you use to click with.
