### ISSUE TITLE
Be more specific when event is not added to app

### ISSUE THREAD

**Issue by Pulau-Komodo** [bevyengine/bevy#5088]
When an EventWriter (or presumably an EventReader) is requested for an event that was not added to the app, the application panics on launch, with a message like

> Resource requested by [system path] does not exist: bevy ecs::event::Events<[event struct]>

Because the Bevy API distinguishes between resources and events, it would be clearer to specify that the *event* does not exist.

**Comment by alice-i-cecile** [comment]
These are implemented through the derive macro:

```rust
#[derive(SystemParam)]
pub struct EventReader<'w, 's, E: Event> {
    reader: Local<'s, ManualEventReader<E>>,
    events: Res<'w, Events<E>>,
}
```

As a result, changing this error message would involve either a) passing some custom information to the derive macro or b) swapping to a manual implmentation.

Both of those incur some pretty serious code quality costs that I don't think I'm willing to pay here.
