### ISSUE TITLE
Fails to find Intel Integrated GPU

### ISSUE THREAD

**Issue by sdfgeoff** [bevyengine/bevy#509]
When running on my desktop (nvidia GPU), Bevy examples compile and run fine. However when running on my laptop (Intel integrated GPU), I see a message that it cannot find the GPU:
```
$ cargo run --example ui
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/examples/ui`
thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!', crates/bevy_wgpu/src/wgpu_renderer.rs:28:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It's worth noting that other applications run fine including ones that use the GPU such as games, CAD software etc.
I am not sure if this is an issue with Bevy or with wgpu. This issue is to see if anyone else has encountered this problem or if it is just me. 

-------------------------------------------------------------

**Relevant info**

```
$ git log
commit 70ad6671dba9e7dc93e8a085ad8bb73904ca1fa5 (HEAD -> master, origin/master, origin/HEAD)
```

```
$ sudo lshw -C display
  *-display                 
       description: VGA compatible controller
       product: UHD Graphics 620 (Whiskey Lake)
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:148 memory:a0000000-a0ffffff memory:80000000-9fffffff ioport:2000(size=64) memory:c0000-dffff
```

```
$ lscpu
Architecture:                    x86_64

<< snip >>

Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz

<< snip >>
```

**Comment by chemicstry** [comment]
Do you have vulkan compatible driver? Can you check the output of `vulkaninfo`?

**Comment by sdfgeoff** [comment]
@chemicstry You are completely correct, I did not have `intel-vulkan` package installed. Installing it solved the problem.
I've created a PR on the website to add a "troubleshooting section" with the solution.
