### ISSUE TITLE
dev-docs.bevyengine.org branch should be force-pushed to avoid bloating the repo

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5092]
`gh-pages` appears to be the [branch in question](https://github.com/bevyengine/bevy/tree/gh-pages) and [this](https://github.com/bevyengine/bevy/blob/main/.github/workflows/docs.yml) appears to be the workflow.

We don't care about history here, so we should just erase this to make `git pull` faster for contributors and stave off hitting Github's repo size limit.

Discovered by @james7132.

**Comment by james7132** [comment]
Seems like we can just use `single-commit` and `force` together to wipe out the history here.
