### ISSUE TITLE
Organize ECS benchmarks

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5110]
## What problem does this solve or what need does it fill?

The current organization of ECS benchmarks is rather arbitrary, hard to read, and makes it hard to run relevant subsets in a batch.

## What solution would you like?

Split ECS benchmarks according to the sections of the ECS that they are testing.

## Additional context

Previously attempted in https://github.com/bevyengine/bevy/pull/4914. Feel free to rebase off of that, or start over (I don't care about credit for these changes at all). I ran into some tedious errors when re-organizing this, so move slowly and make sure to test your changes incrementally.

Code quality fixes should likely be a seperate PR; this sort of change should be as simple and uncontroversial as possible to minimize the amount of time it sits open.

**Comment by Vrixyz** [comment]
Related to : https://github.com/bevyengine/bevy/issues/5161
