### ISSUE TITLE
Update to `glam` 0.21.2

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5115]
As @dependabot tried in #5112, this migration should be relatively simple. However, we need to migrate off the deprecated `const_vec` macros and use the much nicer `Vec3::from_array` methods instead.

This should be nice and simple, but is too hard for a little robot.

**Comment by james7132** [comment]
I think hexasphere needs to be updated too

**Comment by bitshifter** [comment]
I think it's failing due to the `encase` dependency which will need to be updated first - https://github.com/bevyengine/bevy/runs/7067058036?check_suite_focus=true.

Also `Vec3::new` and `Vec3::splat` are `const fn` as well so there are a few options for moving off the macros.
