### ISSUE TITLE
many_foxes stress test example has very visible shadow artifacting

### ISSUE THREAD

**Issue by colepoirier** [bevyengine/bevy#5118]
## Bevy version

bevy main 9eb69282efe57b9e3922e66ade887e6239bff175

## \[Optional\] Relevant system information

cargo 1.61.0 (a028ae4 2022-04-29)
stable-x86_64-unknown-linux-gnu

linux mint 20.3 5.18.6-051806-generic

`AdapterInfo { name: "AMD RADV RENOIR", vendor: 4098, device: 5708, device_type: IntegratedGpu, backend: Vulkan }`

## What you did

Run `cargo r -r --example many_foxes`

## What went wrong

Foxes closes to the camera have grey bar artifacts instead of shadows like the foxes further from the camera:

![Screenshot_from_2022-06-27_11-26-52](https://user-images.githubusercontent.com/37318670/176011644-e1e8a618-0c2a-4906-be64-7e1f87e79b68.png)

**Comment by mockersf** [comment]
not reproduced on macOS. A vulkan issue?

**Comment by cart** [comment]
I can't repro on Linux/Vulkan/Nvidia GTX 1070 (proprietary driver):
![image](https://user-images.githubusercontent.com/2694663/176024434-450614cd-5b36-4220-815e-cd565e843501.png)

**Comment by james7132** [comment]
This seems isolated specific Linux drivers, and may be something upstream of Bevy. Marking down as platform specific.

**Comment by colepoirier** [comment]
Also worth noting that the rendering appears to be shifted down within the window which strikes me as odd/a bug. This screenshot is taken at 1920 x 1080:

![Screenshot_from_2022-06-27_14-23-48](https://user-images.githubusercontent.com/37318670/176038443-cab1b119-6ca8-45a7-96fa-7528b47dcae1.png)

**Comment by alice-i-cecile** [comment]
Clearing from the milestone as this appears to be driver-driven. @colepoirier, have you updated your graphics drivers?

**Comment by colepoirier** [comment]
> Clearing from the milestone as this appears to be driver-driven. @colepoirier, have you updated your graphics drivers?

Indeed. My graphics drivers are up to date with the latest release. Unfortunately testing with dev mesa drivers isn’t something I can do without taking a pretty permanent dependency on them; last time I did this I ended up having to reinstall my whole OS to get back to released mesa deivers because of how apt package depencies seem to work 😢

**Comment by rpjohnst** [comment]
I also see this, using the v0.8.0 tag, on Windows with an AMD integrated GPU (specifically a Surface Laptop 3, which claims to have some sort of "Microsoft Edition" Ryzen), with both the Vulkan and Dx12 WGPU backends. The relevant log output:

```
2022-07-30T20:47:34.536221Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon(TM) RX Vega11 Graphics", vendor: 4098, device: 5592, device_type: IntegratedGpu, backend: Vulkan }```

A graphics debugger shows that the shadow map looks reasonably unscathed, though it has some pretty heavy banding along the floor plane that corresponds to the shape of the shadow artifacts. Maybe some sort of precision issue that only shows up on some hardware and/or drivers?

I've tried tweaking the parameters of the light and camera but haven't found any smoking guns- let me know if there's anything else I can try or collect!

**Comment by JorgeVV** [comment]
Experiencing this in a Macbook Pro 2016 on `latest` branch.
```sh
INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon Pro 450", vendor: 0, device: 0, device_type: DiscreteGpu, backend: Metal }
```

**Comment by id05** [comment]
I have same issue on both drivers + missing textures on radeon-vulkan

Arch Linux 
cargo 1.64.0 (387270bc7 2022-09-16)
Kernel: 5.19.13-arch1-1


Are they suppose to be yellow? 
`AdapterInfo { name: "AMD Radeon Vega 8 Graphics", vendor: 4098, device: 5597, device_type: IntegratedGpu, backend: Vulkan }`
![изображение](https://user-images.githubusercontent.com/76026849/195007751-c16ee8c1-ec16-4cf1-a994-949984921b20.png)



`AdapterInfo { name: "AMD RADV RAVEN", vendor: 4098, device: 5597, device_type: IntegratedGpu, backend: Vulkan }`

![изображение](https://user-images.githubusercontent.com/76026849/195005646-557b6c3c-7610-4ed6-892e-339f788f5440.png)

**Comment by SecretPocketCat** [comment]
This issue also happens on Win 11 with RX590 on c4e791d62
I updated my driver today for the newest for shadow tech, but no dice

```
AdapterInfo { name: "Radeon RX 590 Series", vendor: 4098, device: 26591, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "22.5.1", backend: Vulkan }
```

many_foxes
![2022-11-11 07_43_55-🦊🦊🦊 Many Foxes! 🦊🦊🦊](https://user-images.githubusercontent.com/17273703/201283824-38031620-a536-4ff8-8b36-4b67e741bb5e.png)

shadow_caster_receiver - Using PointLight
![2022-11-11 07_48_21-  - C__Projects_GameDev_bevy_bevy_Cargo toml](https://user-images.githubusercontent.com/17273703/201284151-7f346305-c9b3-4746-bfe0-0abd5e1f2c89.png)

shadow_biases
![2022-11-11 07_46_09-  - C__Projects_GameDev_bevy_bevy_Cargo toml](https://user-images.githubusercontent.com/17273703/201284458-45d616e0-1e64-413a-a8f4-67e90836ae44.png)

**Comment by superdump** [comment]
shadow_biases is meant to look like that unless you adjusted the biases to appropriate values.

**Comment by Elabajaba** [comment]
This was fixed for `many_foxes` in https://github.com/bevyengine/bevy/pull/7339 (the huge plane with no subdivisions was the root cause), and there's a tracking issue to look into why AMD/Nvidia/etc behave differently in https://github.com/bevyengine/bevy/issues/6542 (AMD iGPUs reproduce this issue at smaller plane sizes than AMD dGPUs, and Nvidia and Apple M1s can reproduce it if you use an even more massive plane than `many_foxes` used to use).
