### ISSUE TITLE
load_gltf example is broken on main

### ISSUE THREAD

**Issue by Elabajaba** [bevyengine/bevy#5127]
## Bevy version

main e28b88b3782b11d61cfe8fbca6c9b4f0ff7173e5

## \[Optional\] Relevant system information

Windows+AMD+Vulkan

## What you did

run the load_gltf example

## What went wrong

Shader validation fails, nothing gets shown on screen.

```
2022-06-28T20:42:44.114908Z ERROR bevy_render::render_resource::pipeline_cache: failed to create shader module: Validation Error

Caused by:
    In Device::create_shader_module

Shader validation error:
    ┌─ :556:2
    │
556 │   }
    │ ╭─^
557 │ │
558 │ │ // NOTE: This ensures that the world_normal is normalized and if
559 │ │ // vertex tangents and normal maps then normal mapping may be applied.
    · │
588 │ │         Nt = vec3<f32>(textureSample(normal_map_texture, normal_map_sampler, uv).rg * 2.0 - 1.0, 0.0);
    │ │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ naga::Expression [67]
    · │
604 │ │     return N;
605 │ │ }
    │ ╰─^ naga::Function [30]


    Function [30] 'prepare_normal' is invalid
    Required uniformity of control flow for IMPLICIT_LEVEL in [67] is not fulfilled because of Expression([38])
```

## Additional Information

Started with the array_texture commit. 84991d34f3fdf985b2721a193352d4adb30eab75

**Comment by DGriffin91** [comment]
Just tested and I'm seeing this problem as well. I'm not sure why exactly it doesn't work since I had also made a really similar change passing `standard_material_flags` to `prepare_normal()` in some tests a few days ago.

One possible solution would be to sample the texture outside the branch at:
https://github.com/bevyengine/bevy/blob/e28b88b3782b11d61cfe8fbca6c9b4f0ff7173e5/crates/bevy_pbr/src/render/pbr_functions.wgsl#L43-#L51

Like this:
```glsl
    // Nt is the tangent-space normal.
    var Nt = textureSample(normal_map_texture, normal_map_sampler, uv).rgb;
    if ((standard_material_flags & STANDARD_MATERIAL_FLAGS_TWO_COMPONENT_NORMAL_MAP) != 0u) {
        // Only use the xy components and derive z for 2-component normal maps.
        Nt = vec3<f32>(Nt.rg * 2.0 - 1.0, 0.0);
        Nt.z = sqrt(1.0 - Nt.x * Nt.x - Nt.y * Nt.y);
    } else {
        Nt = Nt * 2.0 - 1.0;
    }
```
