### ISSUE TITLE
Events can be read twice by the same system when a state change occurs

### ISSUE THREAD

**Issue by Seldom-SE** [bevyengine/bevy#5140]
## Bevy version

`bevy = "0.7"`

## What you did

I've run into this bug a few times since Bevy 0.5. If an event-reading system is added to multiple `SystemSet`s, and the event is written as a state change occurs, then the system can receive the event, once before the state change, and once after. This can occur when a system that handles an event that leads to a state change is reused between `SystemSet`s or when a system that changes the state also sends other events. I imagine it can also lead to difficult to reproduce and diagnose bugs when an event is randomly written at the same time as a state change, but I haven't run into this as far as I know.

Here's a minimal reproduction of the bug:

```Rust
use bevy::prelude::*;

#[derive(Clone, Debug, Eq, Hash, PartialEq)]
enum GameState {
    First,
    Second,
}

struct MyEvent;

fn send_event(mut my_events: EventWriter<MyEvent>, mut state: ResMut<State<GameState>>) {
    info!("Sending an event!");
    my_events.send(MyEvent);
    state.set(GameState::Second).unwrap();
}

fn event_listen(mut my_events: EventReader<MyEvent>) {
    for _ in my_events.iter() {
        info!("Now that's an event!");
    }
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_state(GameState::First)
        .add_event::<MyEvent>()
        .add_system_set(
            SystemSet::on_update(GameState::First)
                .with_system(send_event)
                .with_system(event_listen.after(send_event)),
        )
        .add_system_set(SystemSet::on_update(GameState::Second).with_system(event_listen))
        .run();
}

```

```
2022-06-29T18:18:34.414457Z  INFO bevy_test: Sending an event!
2022-06-29T18:18:34.415308Z  INFO bevy_test: Now that's an event!
2022-06-29T18:18:34.417425Z  INFO bevy_test: Now that's an event!
```

## What went wrong

I would expect the event to only be read once, but it is actually read twice.

## Additional information

I think the issue is because Bevy treats a system that is added to different `SystemSet`s as multiple different systems when determining whether it has already received an event. If so, this could be resolved in a number of ways that I can think of:

* Prevent a system from receiving an event if a copy of it has already received that event
* Allow the user to manually specify that two systems are the same
* Clear events when a state change occurs

Since I've run into this bug a few times, I've used many different workarounds:

* Make your event generic and add it once for each `SystemSet` that it can be read in, and add a type parameter to your system to specify which copy of the event it should use
* Manually clear events on state exit using `ResMut<Events<T>>`
* Explicitly order your systems
* Add a resource when the state changes that prevents your system from acting on the event, then remove it after the first frame
* Remove your system from `SystemSet`s entirely and add it using `.add_system()`

The first workaround adds a lot of redundant code, especially when your events are already generic. The third doesn't always work for some reason, but it does solve the above code (when the order of the systems is reversed). With the last one, you may need to change some of your `Res<T>`s to `Option<Res<T>>`s if that resource isn't always present.

Thank you!

**Comment by alice-i-cecile** [comment]
No longer the case, as looping run conditions are gone.
