### ISSUE TITLE
PhantomData does not implement Reflect

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5144]
## What problem does this solve or what need does it fill?

PhantomData is a common and useful type, it should implement the Reflect trait.

Users cannot do this themselves because of orphan rules, and wrappers are very frustrating here.

## What solution would you like?

Implement Reflect for PhantomData in bevy_reflect.

**Comment by BenjaminBrienen** [comment]
You can assign this one to me

**Comment by BenjaminBrienen** [comment]
A better solution has been suggested to instead have a way to automatically ignore marker types.
