### ISSUE TITLE
world::World doctests sometimes hangs with Miri

### ISSUE THREAD

**Issue by RalfJung** [bevyengine/bevy#5164]
When running the `world::World (line 56)` doctest in Miri with many different seeds, it eventually runs into an endless loop. This can be avoided by using `-Zmiri-disable-weak-memory-emulation`. This probably indicates a bug in bevy or its dependencies, but could also be a bug in Miri. 

Weak memory emulation makes it so that an atomic load can return "outdated" values, as is permitted by the concurrent memory model of Rust (and C/C++). So likely, some code somewhere reads an old value, thinks it is current, and goes into some kind of spin loop -- and stays there forever.

See [here](https://github.com/bevyengine/bevy/pull/4988#issuecomment-1167973221) for further analysis by @cbeuw.

**Comment by LegNeato** [comment]
Possibly relevant: https://github.com/kanidm/concread

**Comment by RalfJung** [comment]
The fact that the advise to disable Stacked Borrows does not inspire a ton of confidence though. ;)

FWIW, latest Miri has `-Zmiri-track-weak-memory-loads`, which should help diagnose this issue. But OTOH @cbeuw [pretty much figured it out already](https://github.com/bevyengine/bevy/pull/4988#issuecomment-1167973221) I think; someone probably needs to go fix smol-rs.

**Comment by RalfJung** [comment]
Ah looks like this is tracked in concurrent-queue: https://github.com/smol-rs/concurrent-queue/issues/17

**Comment by taiki-e** [comment]
The problem in concurrent-queue that we agreed on is that it was using x86-specific fences that Miri does not understand. This has been fixed in concurrent-queue 1.2.4 (https://github.com/smol-rs/concurrent-queue/commit/d61005fc792bcd9a20ae9f61726b6842211cc10a).

**Comment by RalfJung** [comment]
> that Miri does not understand

To be more precise, using those fences is just wrong when writing Rust code, and Miri understands that correctly. They can only be used correctly when writing inline assembly.
