### ISSUE TITLE
Add InvisibleEntities vector [enhancement] [rendering]

### ISSUE THREAD

**Issue by rostyslav52** [bevyengine/bevy#518]
I have looked into https://docs.rs/bevy_render/0.1.3/src/bevy_render/camera/visible_entities.rs.html#26-60
If I understand correctly, this system looks into all entities in camera view and 
- if entity is_visible, renders it
- if not, then entity will be ignored and will never be detected by camera

My suggestion is to add a vector InvisibleEntities to  https://docs.rs/bevy/0.1.3/bevy/prelude/struct.Camera2dComponents.html
This vector will contain entities that are in camera view, but have is_visible set as false.

I believe that this would greatly simplify the detection of entities to render or not.

My usecase was that I wanted to render only entities that are in camera view. 
Since there is no such vector as InvisibleEntities, I don't see any way to detect whether hidden entities (with is_visible set to false) are in camera view or not.

Obviously, the name of parameter can be different : HiddenEntities, InvisibleEntitiesInCameraView...

This seems related to https://github.com/bevyengine/bevy/issues/190 , but it is not.

**Comment by rostyslav52** [comment]
Mainly, what bothers me is the condition : 
https://docs.rs/bevy_render/0.1.3/src/bevy_render/camera/visible_entities.rs.html#38-40

It seems like there should be an additional check to render only what is in camera view. This way there won't even be any need to have InvisibleEntities vector.

**Comment by rostyslav52** [comment]
I describe a workaround that I think will work in my case : 

I will create a Resource that will contain a vector of Tiles. Each Tile will contain an enum for tile type (grass, water etc) and a vector of entities to describe who is standing on that tile (for, example, if both flying and walking creatures are allowed on the same tile).

Then, I will have a system run constantly and query the camera to compute the corners of camera view. This way I will know the coordinates of tiles (and units on those tiles) to render. 

As for rendering, I think I will simply add and remove Draw components.


I am aware of https://github.com/stararawn/bevy_tiled , but, unless I am wrong, it does not handle units (creatures).



Also, this is a workaround that will work for me because of the design of my game. I think that the Issue should still be considered in case other users need this feature.

**Comment by rostyslav52** [comment]
It turned out that my solution has already been implemented by others :
https://github.com/alexschrod/bevy_isometric_rendering_demo/blob/master/src/map_render.rs

It is quite similar to what I will develop in terms of tilemap data structure.
At least for now.

**Comment by GabLotus** [comment]
Hey thanks a lot for what you're doing here :) 
There's not need to put tags in the title we gotchu

Depending on how we feel about this we might move this into Discussions to have a longer discussion on these improvements
Thanks a bunch for helping the community

**Comment by alice-i-cecile** [comment]
The new idiom for setting visibility is the `Visibility` component. We should investigate how the new changes impact this issue. 

See
https://github.com/bevyengine/bevy/blob/ffecb05a0ab423b46ab991b49c54516bcaf2ea7b/crates/bevy_render/src/view/visibility/mod.rs

**Comment by mockersf** [comment]
cameras now have a [`VisibleEntities`](https://docs.rs/bevy/latest/bevy/render/view/struct.VisibleEntities.html) component listing the visible entities
