### ISSUE TITLE
Do not suffix methods with `_component` and `_resource` in reflected types.

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#5202]
## What problem does this solve or what need does it fill?

All methods in [ReflectComponent](http://dev-docs.bevyengine.org/bevy/ecs/prelude/struct.ReflectComponent.html) and [ReflectResource](http://dev-docs.bevyengine.org/bevy/ecs/prelude/struct.ReflectResource.html) end with `_component` and `_resource` respectively. I think this is redundant and not very consistent with the rest of the API in the engine.

## What solution would you like?

Remove `_component` and `_resource` suffixes in  `ReflectComponent` and `ReflectResource`.

**Comment by oliverpauffley** [comment]
This sounds like a good first issue for me to learn how the process works. So I will pick this one up if that's ok!

**Comment by Shatur** [comment]
@oliverpauffley feel free to take it!

**Comment by Shatur** [comment]
Closed by #5219.
