### ISSUE TITLE
No shadows when camera is added later

### ISSUE THREAD

**Issue by jonri** [bevyengine/bevy#5203]
## Bevy version

0.7

## Relevant system information
```AdapterInfo { name: "AMD Radeon RX 570 Series", vendor: 4098, device: 26591, device_type: DiscreteGpu, backend: Vulkan }```

## What you did
Added geometry and PointLight with shadows in an initial stage, and then added a camera in a later stage.

## What went wrong
Everything rendered as expected except there were no shadows.

## Additional information
If the camera is instead added at the same time, shadows will work as expected.

## Minimal reproduction project
Note the two alternatives that add the `make_camera` in different states.  One will work, the other will cause the issue.
[shadowtest.zip](https://github.com/bevyengine/bevy/files/9041609/shadowtest.zip)

**Comment by afpatmin** [comment]
I can confirm this happened to me also, specifically when using point lights - shadows from directional lights seems to work in both cases

**Comment by superdump** [comment]
Can you retest with `main`? There have been lots of changes relating to point lights since 0.7.

**Comment by afpatmin** [comment]
I tested now, the issue seems to be resolved on `main`

**Comment by superdump** [comment]
Great, thanks!

**Comment by alice-i-cecile** [comment]
Closing as fixed :)
