### ISSUE TITLE
Store and expose timing of previous frame on the `Time` resource

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5218]
## What problem does this solve or what need does it fill?

Basing measurements off of the "time at the previous tick" is common. In some cases, delta time is not enough.

## What solution would you like?

1. Rename `time.last_update()` to `time.current_instant()` for clarity. Update is used in two different senses in this API currently.
2. Add `time.previous_instant()`, computed using `time.delta()`

Source link: https://github.com/bevyengine/bevy/blob/main/crates/bevy_time/src/time.rs

## Workarounds

1. Track this yourself using a `Local` system parameter.
2. Compute it manually.

## What alternative(s) have you considered?

We could store the previous update, and compute the delta time instead. I think this is slightly worse as delta time is much more commonly used.

We could store both, but I don't think we should. Doing so introduces a new class of bugs in correctness-critical code.

**Comment by alice-i-cecile** [comment]
Ping @cart for a `Time` label please 🙏🏽

**Comment by djeedai** [comment]
I'm having difficulties finding an example use case for `previous_instant()`, especially since [the documentation of `Instant` states](https://doc.rust-lang.org/std/time/struct.Instant.html):

> Opaque and useful only with [Duration](https://doc.rust-lang.org/std/time/struct.Duration.html).

So essentially you can only meaningfully use the value returned by `previous_instant()` if you calculate a delta with another instant, and so likely with the current frame's, which is exactly what `delta()` gives you.

**Comment by alice-i-cecile** [comment]
Yeah, I managed to get a decent workaround for this. We can close this out for now.

**Comment by djeedai** [comment]
Could you anyway please describe your original use case though? If you feel like your solution is a _workaround_ then maybe there's a valid use case we should consider?

**Comment by alice-i-cecile** [comment]
In order to solve bugs and reliability issues with tracking timing of input events, I treat them as if they're sent on the frame before: see [this code](https://github.com/Leafwing-Studios/leafwing-input-manager/blob/c6a1e9736fd7aec3a62e9abc3edfc6a25c1d75d8/src/systems.rs#L34). 

In order to do so, I can either cache this myself, as shown, or I could compute this from the duration of the previous frame.
