### ISSUE TITLE
Parameter collections - Simple access to the same few queries/resources in multiple systems

### ISSUE THREAD

**Issue by DreamplaySE** [bevyengine/bevy#5226]
## What problem does this solve or what need does it fill?

Currently, if you've got a few systems that all interact with the same queries/resources you have to individually declare them. This leads to long system declarations with repeated code.

## What solution would you like?

Adding a way for you to declare a struct with the required queries/resources and then request that struct in systems would simply syntax and allow users to very simply write abstractions like implementing specific behavior that should be run based on those queries, ie. wrappers around Bevy primitives.
```rust
struct ParameterCollection {
    ducks: Query<&Duck>,
    children: Query<&Children>,
    meshes: Query<&mut Handle<Mesh>>,
}

pub fn system(
    collection: ParameterCollection,
) {
    // Use queries such as collection.ducks
    //  ...
}
```

## What alternative(s) have you considered?

You can do what is possible right now, namely to just copy/paste code, but it's a drag. Furthermore, you can use exclusive systems with abstractions to avoid having to paste in the queries over and over again but that's of course not a real solution.

## Additional context

None.

**Comment by nicopap** [comment]
Look up `SystemParam`, See https://docs.rs/bevy/latest/bevy/ecs/system/trait.SystemParam.html

**Comment by DreamplaySE** [comment]
Also, in considered, solutions, I'd like to add that you can do this with nested parameters, however it would require you to construct your wrapper or alternatively use a trait which is possible, but named structs would provide more ergonomy. I guess this PR can be considered an extension to those tuples, just as a named struct.

**Comment by DreamplaySE** [comment]
> You can already do that. You are describing what `SystemParam` does. See https://docs.rs/bevy/latest/bevy/ecs/system/trait.SystemParam.html

Woops, I missed that those existed, only found tuples, nvm closing, thanks. :)
