### ISSUE TITLE
Build error "missing lifetime specifier" in bevy_tasks/src/task_pool.rs

### ISSUE THREAD

**Issue by navaati** [bevyengine/bevy#529]
See for example this build of the CI: https://github.com/bevyengine/bevy/pull/528/checks?check_run_id=1140557857#step:7:169

Right now it’s impossible to git clone bevy and cargo build, be it with stable or nightly toolchain.

**Comment by navaati** [comment]
Ah, apparently the solution is around here: https://github.com/bevyengine/bevy/pull/526

**Comment by stjepang** [comment]
The easiest fix until that PR is merged is to add this as a dependency to your `Cargo.toml`:

```rust
async-executor = "=1.3.0"
```

**Comment by navaati** [comment]
Yes, works, thank you :). What I don’t understand is why the Cargo.lock didn’t work (when building directly the Bevy repository, for the examples).

**Comment by manzt** [comment]
Ran into the same issue, thanks!

**Comment by cart** [comment]
This is resolved by the `0.2.1` patch release.
