### ISSUE TITLE
iter_inner is either accidentally public or undocumented

### ISSUE THREAD

**Issue by kornelski** [bevyengine/bevy#5290]
The docs show `iter_inner` method, but this method has the exact same docstring as `iter`:

https://docs.rs/bevy/latest/bevy/ecs/system/struct.Query.html#method.iter_inner

**Comment by devil-ira** [comment]
Those docs do need to be updated but it's not the *exact* same.
`iter_inner` states "Returns an [Iterator](https://doc.rust-lang.org/nightly/core/iter/traits/iterator/trait.Iterator.html) over the query results, *with the actual “inner” world lifetime.*"

**Comment by alice-i-cecile** [comment]
Yeah, this could use a bit more context on why exactly you may want to use it.

**Comment by james7132** [comment]
Following #5742, #4243, and #5591, the function seems to be pretty well documented. Closing.
