### ISSUE TITLE
Change detection for keyboard input is not working correctly.

### ISSUE THREAD

**Issue by ruibinx** [bevyengine/bevy#5292]
## Bevy version

0.7

## What you did

As discussed in https://discord.com/channels/691052431525675048/996224340733472828, there is a simple system querying current keyboard input, code as below.

```rust
fn keyboard(keyboard: Res<Input<KeyCode>>) {
    if !keyboard.is_changed() {
        return;
    }

    info!("activated");
}
```

## What went wrong

The system should print "activated" only when there are keyboard input changes. Currently the system is activated no matter if there are new keyboard event. It might be some internal system greedily updating `Input<KeyCode>`.

**Comment by ruibinx** [comment]
> With the code as written above, this seems like intended behavior. But it seems like a real issue is being described.
> 
> I would expect a system like this to only print "activated" when there are keyboard input changes, but this currently happens on every frame.
> 
> ```rust
> fn keyboard(keyboard: Res<Input<KeyCode>>) {
>     if !keyboard.is_changed() {
>         return;
>     }
> 
>     info!("activated");
> }
> ```
> 
> This seems like a reasonable thing to want to do for e.g. a "Press any key" screen.

Unlike the provided example which has only a single keyboard resource param, the actual code in my game is:

```rust
fn keyboard(keyboard: Res<Input<KeyCode>>, some_query: Query<&SomeComponent1, &SomeComponent2>) {
     if keyboard.just_pressed(keycode1) {
            do_sth()
     } else if ..{
            do_sth()
     } else  {
            ...
     }
}

```

I'm kind of worried about the `some_query` part, if resource change detection should happen inside the system, would that mean the query would be made every frame thus may slow downthe whole game ?

I'm new to bevy and ECS and game dev, so please correct me if I'm wrong.

**Comment by rparrett** [comment]
> I'm kind of worried about the some_query part, if resource change detection should happen inside the system, would that mean the query would be made every frame thus may slow downthe whole game ?

Queries should be cheap to create, so you probably don't to be worrying about that.

It's possible to prevent a system from running with [Run Criteria](https://bevy-cheatbook.github.io/programming/run-criteria.html) but there area some caveats and that would be a bit of a micro-optimization.

**Comment by ruibinx** [comment]
Thanks, I've updated the description. Should be more accurate now. 😃 @rparrett
