### ISSUE TITLE
`Entity` does not implement `Component`

### ISSUE THREAD

**Issue by CGMossa** [bevyengine/bevy#5295]
While attempting to count all newly added entities, I tried:

- `Query<(), Added<()>>`, but `()` does not impl. `Component`.
- `Query<Entity, Added<Entity>>`, but (again) `Entity` does not implement `Component`.
- `Query<ChangeTrackers<Entity>>` but this too doesn't work.

First, what's a way to query for all newly added entities of any type?

Second, is this perhaps a missing feature due to `derive(Component)` that no-one caught?
Is there a new pattern to accomplish this?

# Additional

Bevy version: `main`
rust: `rustc 1.62.0 (a8314ef7d 2022-06-27)`

**Comment by DJMcNab** [comment]
The best way to detect all new entities would be to add a `Processed` component (or a more specialised name), and query for all entities without this component in your system.

`#[derive(Component)]` has nothing to do with this - `Added<Entity>` would never have done what you want.

**Comment by afonsolage** [comment]
Even tho I agree the currently solution is explicitly marking the entities that one wanna track, it would be a good idea to have a way to track all newly added Entities? I don't think have something like `Changed<>` is reasonable, but maybe something similar to `Added` may be.

Btw I can't think in a use case where would be needed to have this kind of behavior. This can be an edge used-case or even a misunderstanding of how ECS works.

**Comment by PROMETHIA-27** [comment]
Entity definitely should not implement `Component`. That would be a *major* footgun in multiple places.
I also don't think there should be a built-in mechanic to track new entities- it would add overhead to every entity spawn, when ultimately very few will need to do this and the current method (detailed above) is perfectly fine.
