### ISSUE TITLE
Add archetype cache to queries 

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#53]
Currently hecs queries iterate over all archetypes to check if that archetype matches the query. For a small number of archetypes, this is probably faster, but it will get more expensive as the number of archetypes (and/or number of components per archetype) gets larger. for a game engine (which will have many archetypes), it makes sense to have a cache. we could then invalidate the cache whenever an archetype is added/removed.

**Comment by DJMcNab** [comment]
I think this was fixed by #863 - at least `QueryIter` now has an archetypes field.

**Comment by cart** [comment]
Note quite. It has an archetypes field, but it doesn't cache matches, which means we need to check every archetype every time. My bevy_ecs core rewrite adds "stateful queries" which cache these results.

**Comment by alice-i-cecile** [comment]
Is this closed by #1525 @cart?

**Comment by cart** [comment]
Yup!
