### ISSUE TITLE
Gamepad Disconnected Event not dispatched correctly

### ISSUE THREAD

**Issue by PradeepKumarRajamanickam** [bevyengine/bevy#530]
Gamepad Disconnected Event not dispatched instead Connected is dispatched again.

tested using:
XBox 360 Controller
MacBook Pro (Catalina)

**Comment by CleanCut** [comment]
I can't replicate this with an Xbox One or PS4 Dualshock controller on macOS Catalina. 😕

**Comment by PradeepKumarRajamanickam** [comment]
Hmm.. maybe be this is a device specific driver issue. Let me try it on a Xbox series x controller i.e. if I manage to get hold of one this holiday season.

**Comment by Bobox214** [comment]
I have not encountered the issue testing on an Ubuntu 20.04 with an XBox360 Controller, Disconnected event is correctly detected by the gamepad_input example.

**Comment by PradeepKumarRajamanickam** [comment]
Recent os updates seem to have solved the disconnect not firing issue.

There however still seems to be an issue with connected event. Each time I unplug and reconnect my controller the Gamepad id seems to increase even though there is only one usb controller plugged in. Can someone please confirm if they are experiencing it or is it just my device?

**Comment by CleanCut** [comment]
@PradeepKumarRajamanickam 

I'm not aware of any official USB controller support in macOS. Am I missing something, or are you using a third-party driver like [USB Overdrive](https://www.usboverdrive.com/)?

From what I see for game controller support in general, macOS doesn't have stable device id's.  Quite the opposite, it looks like macOS expects you to assign a player id to a newly-connected controller to indicate which player the controller should represent (and light up the corresponding player light). See the [Player Indices Identify a Controller](https://developer.apple.com/library/archive/documentation/ServicesDiscovery/Conceptual/GameControllerPG/DiscoveringControllers/DiscoveringControllers.html#//apple_ref/doc/uid/TP40013276-CH2-SW1) section of this developer document.  I haven't found any references to `playerIndex` in `gilrs`, `io-kit-sys`, or `core-foundation`, so I don't think this particular ability is yet exposed.

Nevertheless, I _think_ the pattern we need to follow is to take each new incoming gamepad id as if it were a unique identifier, and manually map it within our game logic to an available player.

**Comment by PradeepKumarRajamanickam** [comment]
"Nevertheless, I think the pattern we need to follow is to take each new incoming gamepad id as if it were a temporary unique identifier, and manually map it within our game logic to an available player."
@cart or @simpuid Are we (plugin writers) supposed to manage player handle to gamepad handle map or will this be abstracted for us.

@CleanCut I am using a community built driver https://github.com/360Controller/360Controller#about

**Comment by cart** [comment]
Short term I think it makes sense to handle this sort of mapping in game code (or plugin code). This sort of logic is context-specific and I'd rather not dictate it on bevy, especially this early in development.

**Comment by simpuid** [comment]
According to [gilrs](https://docs.rs/gilrs/0.7.4/gilrs/), it supports _Hotplugging_ but it is not reliable. It works with my controller but may not work with others(not frequent).

One of the solution is:
* For an old device, map them to the old player entity
* For a new device, either map them to an old player entity or create a new one depending on the button input, player count and player limit

This kind of solution is suitable in game code.

**Comment by PradeepKumarRajamanickam** [comment]
@simpuid Thanx will try it.

**Comment by PradeepKumarRajamanickam** [comment]
I am going to go ahead and close this ticket. I got what I needed.

Thanx for the support everyone.
