### ISSUE TITLE
`with_children` takes a FnMut which prevents some use cases

### ISSUE THREAD

**Issue by HyperLightKitsune** [bevyengine/bevy#531]
FnMut prevents transferring ownership.

For example, the following will not compile.
```rust
fn spawn(mut commands: Commands, text: String) {
    commands.spawn((0,)).with_children(move |parent| parent.spawn((text,));
}
```
This is because FnMut can be called multiple times. I believe Commands will only call this function once so it shouldn't be a problem.

This should be a simple change. I'm pretty sure we can just change the input from a FnMut to a FnOnce. 

I am completely willing to implement this myself.

**Comment by karroffel** [comment]
I think you're free to work on it and open a PR! I can assign you so nobody else does duplicate work. If you don't want to/can implement that just let me know and I remove you again as the asignee! :blue_heart:

**Comment by HyperLightKitusne** [comment]
I am sure there are other functions like this (for example `for_current_entity`). Should I do it for all of them? Should I open different PRs for each one?

**Comment by karroffel** [comment]
You can rename the PR to something like "Use `FnOnce` where possible" maybe? That way it works for more cases too.

**Comment by HyperLightKitusne** [comment]
Ok, will do.
