### ISSUE TITLE
Post processing example doesn't support resizing

### ISSUE THREAD

**Issue by johanhelsing** [bevyengine/bevy#5315]
## How can Bevy's documentation be improved?

The `post_processing` example doesn't currently support resizing. Its stated intent is to be:

> useful to implement your own post-processing effect such as
> edge detection, blur, pixelization, vignette... and countless others.

If people copy this code to their own projects it would be really nice if it properly supported resizing.

I think there may be two viable solutions to this:

1. Write a system that resizes the full screen quad whenever the window size changes
2. Write a custom vertex shader that takes the view.width and height uniform values into account and is always snapped to the edges of the viewport.

**Comment by mockersf** [comment]
I couldn't reproduce any issue with resizing, but after playing with values in the example a little more it's possibly due to having a 2x screen scale, and the mesh being sized with physical screen size. This should also be fixed.

**Comment by johanhelsing** [comment]
I's a bit subtle in the example because there is nothing near the edges of the screen. If you set a small initial size using `WindowDescriptor` and then scale the window up, you can see it more clearly, though.

**Comment by AndrewB330** [comment]
I just hit this problem and I couldn't figure out how to write this resizing system. From what I understand we need to resize render target image as well as the quad. 

When I'm calling resize on the image I'm getting an error that "color" and "resolve" attachments have different sizes, and I can't understand why since attachments should be synced on the extract stage, right? And for the quad, I guess we should just create a new quad every time?

**Comment by Vrixyz** [comment]
For future reference:
- https://github.com/bevyengine/bevy/pull/5902 adds a full screen triangle with high level Material2d bevy functions
- https://github.com/bevyengine/bevy/pull/5084 seems to implement a fullscreen triangle, but it's doing so via a render pipeline

**Comment by AntonZelenin** [comment]
In case it might be useful, for this example resizing works on Mac, but on Windows it doesn't and I needed to write a system to support it.

**Comment by JMS55** [comment]
@IceSentry this issue can probably be closed now that we removed the old post processing example?

**Comment by IceSentry** [comment]
Yep, this isn't an issue anymore
