### ISSUE TITLE
Latest rust nightly breaks bevy due to compiler regression

### ISSUE THREAD

**Issue by TheButlah** [bevyengine/bevy#5332]
## Bevy version

`0.6`

## \[Optional\] Relevant system information

`cargo 1.64.0-nightly (8827baaa7 2022-07-14)`

## What you did

`cargo build`

## What went wrong

```
error[E0658]: use of unstable library feature 'core_intrinsics': intrinsics are unlikely to ever be stabilized, instead they should be used through stabilized interfaces in the rest of the standard library
 --> /home/ryan/.cargo/registry/src/github.com-1ecc6299db9ec823/inplace_it-0.3.3/src/guards/slice_memory_guard.rs:6:5
  |
6 | use std::intrinsics::copy_nonoverlapping;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add `#![feature(core_intrinsics)]` to the crate attributes to enable
```

## Additional information

The latest version of rust nightly introduces a compiler [regression](https://github.com/rust-lang/rust/issues/99286), which breaks [`inplace_it`](https://github.com/NotIntMan/inplace_it/pull/11), which bevy 0.6 depends on.

No fix is necessary, allegedly this should be resolved shortly. Created this issue to track this and help any bevy folks

**Comment by alice-i-cecile** [comment]
Discussed in #5331; follow the bread crumbs from there. 

We can close this once https://github.com/rust-lang/rust/pull/99288 lands.

**Comment by SkiFire13** [comment]
Both rust-lang/rust#99288 and NotIntMan/inplace_it#11 landed
