### ISSUE TITLE
Cannot use bevy::ui::Size

### ISSUE THREAD

**Issue by OragonEfreet** [bevyengine/bevy#5338]
## Bevy version

main branch ([25d222b73e57f27cf7f346015c7f554dafab131a](https://github.com/bevyengine/bevy/commit/25d222b73e57f27cf7f346015c7f554dafab131a))

## What you did

Take any example code and add `use bevy::ui::Size` directive.
Run `cargo check --example the_example`

## What went wrong

```
error[E0432]: unresolved import `bevy::ui::Size`
 --> examples/2d/rotation.rs:3:5
  |
3 | use bevy::ui::Size;
  |     ^^^^^^^^^^^^^^ no `Size` in `ui`
```

## Additional information

Of course a solution is to use the prelude, but according to the migration guide provided in [this PR](https://github.com/bevyengine/bevy/pull/4285), we should be able to use `bevy::ui::Size` as well.

**Comment by KDecay** [comment]
Thank you for the bug report! This problem was caused because the `Size` was imported twice in the `lib.rs` of `bevy_ui` which made it private instead of public.

**Comment by OragonEfreet** [comment]
Thanks for the quick fix!
