### ISSUE TITLE
Reintroduce `Mutated<>` filter, and maybe more

### ISSUE THREAD

**Issue by CGMossa** [bevyengine/bevy#5351]
## What problem does this solve or what need does it fill?

Bevy used to have 
> bevy used to have `Added`, `Mutated`, and `Changed` (= `Added` OR `Mutated`) - Ida Iyes#0981

- [ ] Bring back the `Mutated`,
- [ ] Bring back `Removed`

## What alternative(s) have you considered?

One may use `ChangeTrackers` to achieve the same result.

## Additional context

Here I would like to give my context, even though it might be outside this issue.

I'm using `bevy_ecs` to create a simulation; The simulation has to be aware of entities
(actually components) being added and/or removed; as these have consequences for
other entities. *However*, to start the process, I have components that are seeded, just to
kick of things. These components are technically `Added` but they shouldn't provoke the
systems that currently reacts to `Added` components.

Thus, I need to distinguish between:

- Added due to seed / startup
- Added due to some event in the simulation (post seed / startup phase)

Currently, what I have to do is the following:

All seeded components have `Seeded` marker type inserted.

Then systems that have to react on `Added` or `RemovedComponents` or whatever, have to
have `Query<Option<ChangeTrackers<Seeded>, Added<AnotherThing>>`. First, the effect
of the system is only applied if `!seeded_component.is_added()`; And the `Option<>` is due
to the fact that entities spawned after startup / seed stage may not contain the marker
component `Seeded`. 

This is a very common pattern; Maybe there is a slicker way to apply it.
I don't know what a filter for this could look like, so I think we should atleast start with
bringing back `Mutated`.

**Comment by alice-i-cecile** [comment]
Closing in favor of #15070, which is a bit better scoped. The `Removed` pattern is much easier these days due to hooks and observers thankfully.
