### ISSUE TITLE
Activate/Deactivate UI Elements

### ISSUE THREAD

**Issue by undersquire** [bevyengine/bevy#5360]
## What problem does this solve or what need does it fill?

In my game right now, I want to be able to deactivate UI components when closing a menu, and re-activate them when I show that menu. Right now the only way to achieve this is to completely _despawn_ the entities of this menu, which is a bit inconvenient as I have to completely reconstruct this menu when respawning it.

I originally had the impression that making a UI element _invisible_ (via `Visibility` component) would disable the the ability to interact with the UI element.

## What solution would you like?

I was thinking either making the Visible component control the active state of a UI element, or having a separate component `UIState` or something.

## What alternative(s) have you considered?

I've had discussions on the discord before about a possible universal "entity de-activation" system via multiple worlds (when this is implemented). This could work by moving an entity into another inactive world and moving them back when you need to "re-activate" it.

**Comment by alice-i-cecile** [comment]
I'm going to make a quick PR to tackle this tomorrow.

**Comment by Nilirad** [comment]
The title of this issue can be misleading: first I thought this was referring to things like “graying out” a button to disable interaction. Instead it is requesting to automatically disable a UI element if non visible.

**Comment by mockersf** [comment]
the correct way to hide UI nodes is to set the `display` field of the `Style` component to `Display::None`
https://docs.rs/bevy/latest/bevy/ui/struct.Style.html#structfield.display

**Comment by undersquire** [comment]
Closing in favor of https://github.com/bevyengine/bevy/issues/5368
