### ISSUE TITLE
Visual Artifacts in `3d_scene` Example on macOS

### ISSUE THREAD

**Issue by x-52** [bevyengine/bevy#5369]
## Bevy version

Commit `9c116d557df5a88940ed2e29dab6ff13c84d61a9` on `main`

## Relevant system information

- Rust 1.62.0 Stable
- macOS Monterey 12.4

`AdapterInfo { name: "Intel(R) Iris(TM) Graphics 6000", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Metal }`

## What you did
`cargo run --example 3d_scene`
As expected, the 3d scene appeared.
![Screen Shot 2022-07-18 at 2 03 53 PM](https://user-images.githubusercontent.com/56453634/179575385-83fe530c-abbd-4051-8764-c908e717da48.png)

## What went wrong
There are clearly artifacts in the shadow.

For comparison, here's a screenshot of the same example running in WASM:
![Screen Shot 2022-07-18 at 2 05 36 PM](https://user-images.githubusercontent.com/56453634/179575680-7fd582aa-130a-4e51-9663-74c087bd0a93.png)
(Same computer, Firefox Developer Edition 103.0b9, but using bevyengine.org/examples)

## Additional information
This seems to be a Bevy-specific problem, since `wgpu`'s [`shadow` example](https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples/shadow) works perfectly fine:
![Screen Shot 2022-07-18 at 2 20 33 PM](https://user-images.githubusercontent.com/56453634/179577189-4be1da83-1fb2-4254-8aa1-2a0d7776a405.png)

**Comment by mockersf** [comment]
looks like #3315...

**Comment by superdump** [comment]
Yup, it's #3315.
