### ISSUE TITLE
error occurred: Failed to find tool. Is `c++` installed?

### ISSUE THREAD

**Issue by jjlrjjlr** [bevyengine/bevy#537]
There seems to be an error when attempting to build/run on Linux (Linuxmint 20) related to ``spirv-reflect``. I have attached the output i'm getting when trying to run my project.
[error.txt](https://github.com/bevyengine/bevy/files/5253092/error.txt)

**Comment by memoryruins** [comment]
Do you have a C++ compiler installed -- e.g., what is the output of `g++ --version` or `clang++ --version`?
If neither are found, `sudo apt install g++` might be all that is needed. If that works, we can add a note to https://github.com/bevyengine/bevy/blob/master/docs/linux_dependencies.md

**Comment by jjlrjjlr** [comment]
It builds after installing g++. Thank you for the help. I had assumed gcc would work, though i guess it doesn't.

**Comment by alice-i-cecile** [comment]
Fixed in #1874, as @MinerSebas noticed <3
