### ISSUE TITLE
update_gltf_scene looks broken on main

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#5444]
## Bevy version

rev: 619c30c036ddfceb66030922099961bd17b65e35
(both WASM and native)

## What you did

I ran 
```sh
cargo run --example update_gltf_scene
```

## What went wrong

The scene looks broken:

https://user-images.githubusercontent.com/26321040/180644541-bf9d35ea-9607-413c-8476-0cd208f4d2ff.mp4

**Comment by mockersf** [comment]
that's exactly what the example is supposed to look like 😄

**Comment by nicopap** [comment]
Sneakily updated to "_looks_ broken". I guess the example either needs a description of how it should look like or use a different effect.

**Comment by nicopap** [comment]
>  I guess the example either needs a description of how it should look like or use a different effect.

Turns out there is already a description in the example, I quote:

> This system will move all entities that are descendants of MovedScene (which will be all entities spawned in the scene)
