### ISSUE TITLE
`From<NonSendMut<'a, T>> for Mut<'a, T>` has wrong trait bound `Resource` instead of `'static`

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#5456]
Copy/paste typo in #5438 led to `Resource` trait bound instead of `'static`. Fix:

```diff
- impl<'a, T: Resource> From<NonSendMut<'a, T>> for Mut<'a, T> {
+ impl<'a, T: 'static> From<NonSendMut<'a, T>> for Mut<'a, T> {
```

My bad!

**Comment by alice-i-cecile** [comment]
Ah right, I'd forgotten that we haven't changed that yet... Make a follow-up PR and we'll get it merged.

**Comment by alice-i-cecile** [comment]
https://github.com/bevyengine/bevy/blob/6a1ba9c456663808aecce2bcdc0a181eed6204d5/crates/bevy_ecs/src/change_detection.rs#L220
