### ISSUE TITLE
Conversion of EntityMut into EntityRef

### ISSUE THREAD

**Issue by Moulberry** [bevyengine/bevy#5459]
## What problem does this solve or what need does it fill?

If a function exists that takes an EntityRef, it would be nice to be able to call this function using an EntityMut.
Currently, this is not possible and you have to do a second lookup to get the EntityRef you need.

## What solution would you like?

Add a function, like the following, onto EntityMut:

```rust
pub fn to_ref(self) -> EntityRef {
    EntityRef {
        world: self.world,
        entity: self.entity,
        location: self.location
    }
}
```

Could be implemented like this, or by leveraging `From`

## What alternative(s) have you considered?

Shared super-trait for EntityRef and EntityMut, though this is more complicated and would force use of generics unnecessarily

**Comment by alice-i-cecile** [comment]
Related to #5438, #5376.
