### ISSUE TITLE
Add a set of memory conversion methods to bevy_utils

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5460]
I would actually prefer to have a function on `bevy_utils` that formats a memory measurement to `KiB`, `MiB`, `GiB`, ... depending on the value. Memory measurements will be quite common in game engines.

_Originally posted by @Nilirad in https://github.com/bevyengine/bevy/pull/5454#discussion_r929795808_

**Comment by mockersf** [comment]
I disagree this needs to be part of Bevy.

**Comment by alice-i-cecile** [comment]
Closing until we can find a clear motivation. This may fit well as a truly external crate that we import for the editor.

**Comment by mockersf** [comment]
https://crates.io/crates/unit-conversions

**Comment by Nilirad** [comment]
Also that crate doesn't help to automatically display the more convenient unit based on the value.

**Comment by alice-i-cecile** [comment]
We should see about PRs to fix those limitations upstream (and existing alternatives) before trying to fork IMO.
