### ISSUE TITLE
Add more system information as a diagnostics

### ISSUE THREAD

**Issue by IceSentry** [bevyengine/bevy#5464]
## What problem does this solve or what need does it fill?

When debugging performance it can be helpful to know things like cpu usage and memory usage

## What solution would you like?

Add a `SystemInformationDiagnosticsPlugin` to bevy_diagnostics that queries the cpu usage and memory usage and adds them as a diagnostic.

This plugin could also add the SystemInfo from https://github.com/bevyengine/bevy/pull/5454 as a `Res` to make this data accessible to other parts of the engine.

## What alternative(s) have you considered?

None

## Additional context

https://github.com/bevyengine/bevy/pull/5454 added a log on startup to give more information about the system, The same crate used in that PR should be used to query this data each frame.

**Comment by zeroacez** [comment]
Hello!
I have never contributed before but I would like to give this a shot if that is okay with you guys.

**Comment by Nilirad** [comment]
Try to hear @IceSentry and @l1npengtul first, since they already opened the PRs you see above.

**Comment by zeroacez** [comment]
I see! #5911 seams to already solve this issue. I will move on to something else then. Thank you.

**Comment by elbertronnie** [comment]
I guess this issue can be closed now as #5911 has been merged.
