### ISSUE TITLE
Fast Compiles issue with debugging in IDE

### ISSUE THREAD

**Issue by Parallel-Paradox** [bevyengine/bevy#5486]
## Bevy version

Bevy 0.7.0

## \[Optional\] Relevant system information

macOS Monterey 12.5
Intel Core i5
Intel Iris Plus Graphics 655 1536 MB

## What you did

Exactly as https://bevyengine.org/learn/book/getting-started/setup/ "Enable Fast Compiles"

## What went wrong

Test in VSCode and CLion, while `cargo run --features=bevy/dynamics` runs well, Debug mode in IDE can't properly work.

Terminal Report:

```txt
dyld[11362]: Library not loaded: '@rpath/libstd-2b42fd6bb1400760.dylib'
  Referenced from: '/path_to_proj/bevy_playground/target/debug/bevy_playground'
  Reason: tried: '/usr/local/lib/libstd-2b42fd6bb1400760.dylib' (no such file), '/usr/lib/libstd-2b42fd6bb1400760.dylib' (no such file)
Signal: SIGABRT (signal SIGABRT)
Terminated due to signal 6
```

Same report in VSCode and CLion.

## Additional information

The launch.json for VSCode:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Cargo launch",
            "type": "lldb",
            "request": "launch",
            "cargo": {
                "args": [
                    "build",
                    "--features=bevy/dynamic"
                ],
            },
            "cwd": "${workspaceFolder}",
            "args": []
        },
    ]
}
```

The project is quite easy (In fact it's just a hello world):

```rust
use bevy::prelude::*;

fn main() {
    println!("Hello, world!");
    App::new().run();
}
```

**Comment by Parallel-Paradox** [comment]
This issue block me from using breakpoint... which really hurts me.

**Comment by alice-i-cecile** [comment]
This is almost certainly an upstream issue, but I'm not entirely sure where to point you.

**Comment by bjorn3** [comment]
You need to add the output of `rustc --print target-libdir` and `target/debug/deps` to the `DYLD_LIBRARY_PATH` (`LD_LIBRARY_PATH` on unixes other than macOS and `PATH` on Windows) env var (separated by a colon (`:`), or a semicolon (`;`) on windows). Rustup and cargo do this for you if you use `cargo run`, but when VSCode directly invokes the executable without setting this env var.

**Comment by Parallel-Paradox** [comment]
> You need to add the output of `rustc --print target-libdir` and `target/debug/deps` to the `DYLD_LIBRARY_PATH` (`LD_LIBRARY_PATH` on unixes other than macOS and `PATH` on Windows) env var (separated by a colon (`:`), or a semicolon (`;`) on windows). Rustup and cargo do this for you if you use `cargo run`, but when VSCode directly invokes the executable without setting this env var.

Problem solved, thx!
Note that `target/debug/deps` is in the project directory.
