### ISSUE TITLE
RenderLayer is not effect with SceneBundle

### ISSUE THREAD

**Issue by haike0513** [bevyengine/bevy#5501]
## Bevy version
0.8

## What you did
```rust

    let ui_layer = RenderLayers::layer(1);
    commands
    .spawn_bundle(Camera3dBundle {
        transform: Transform::from_xyz(100.0, 100., 150.0).looking_at(Vec3::ZERO, Vec3::Y),
        camera: Camera {
            priority: 1,
            ..default()
        },
        camera_3d: Camera3d {
            clear_color: ClearColorConfig::None,
            ..default()
        },
        ..default()
    })
    .insert(ui_layer)
    ;

    commands.spawn_bundle(SceneBundle {
        scene: asset_server.load("ui/Character.glb#Scene0"),
        ..default()
    })
    .insert(ui_layer)
    ;

    commands.spawn_bundle(PbrBundle {
        mesh: meshes.add(Mesh::from(shape::Cube { size: 10.0 })),
        material: materials.add(Color::rgb(1.0, 0.9, 0.2).into()),
        ..default()
    })
    .insert(ui_layer)
    ;


```

## What went wrong

If it's not clear, break this out into:

- what were you expecting?
 I think the scene with `ui_layer` can be render by the camera with `ui_layer`

- what actually happened?
  the cube with `ui_layer` can be render by camera with `ui_layer`,  but the scene is still render by the main camera not the camera with `ui_layer`

## Additional information

Other information that can be used to further reproduce or isolate the problem.

Here is the render with ui_layer
![image](https://user-images.githubusercontent.com/81543786/182004798-f5da8d9a-bd12-4ee2-a77b-51dfa3e73da5.png)

when I remove the ui_layer of cube and scene, only the  render of cube change,   the scene is still.

![image](https://user-images.githubusercontent.com/81543786/182004897-99fdf191-e7c7-4e03-acfd-329a438293d1.png)

**Comment by superdump** [comment]
RenderLayers are not hierarchical currently. You have to add the layer to every entity spawned by the scene bundle.

**Comment by haike0513** [comment]
> RenderLayers are not hierarchical currently. You have to add the layer to every entity spawned by the scene bundle.

Thx, I'm not familiar with it, sorry to trouble with
