### ISSUE TITLE
Iterate ALL Entities in world (get EntityRef/EntityMut)

### ISSUE THREAD

**Issue by Moulberry** [bevyengine/bevy#5504]
## What problem does this solve or what need does it fill?

There are cases where direct access to EntityRef/EntityMut is needed in an iterating context

## What solution would you like?

An archetype-based solution, ideally we could have a &EntityRef or &mut EntityMut in queries, which would automatically imply exclusive world access thinking. (https://github.com/bevyengine/bevy/discussions/5496#discussioncomment-3288227)

## What alternative(s) have you considered?

Iterating Entity (the ID) and calling World::entity. This solution works, but it is unintuitive and suffers from worse performance than a built-in solution for iterating EntityRef/EntityMut

## Additional context

Original discussion: https://github.com/bevyengine/bevy/discussions/5496

**Comment by alice-i-cecile** [comment]
Blocked on #4166. This work will require us to fully unify exclusive and ordinary systems.

**Comment by james7132** [comment]
#6843 should add support to get an iterator of `EntityRef` over all entities given a `World`, however getting an `Iterator` of `EntityMut` is going to be highly unsound without `LendingIterator` to ensure only one `EntityMut` is valid at any given time.

**Comment by james7132** [comment]
> This is just because we currently store a `&mut World` in `EntityMut`, right? In theory nothing prevents us from having two `EntityMut`s that refer to different entities that are alive at the same time?

Due to the use of `swap_remove` and entity locations being updated, structural mutations (adding/removing components) to entities via EntityMut can and will invalidate the locations in other EntityRefs/EntityMuts and the metadata used to make the original iterator.

We'd likely need a mutable version of EntityRef that disallows structural mutations.
