### ISSUE TITLE
Fast compile generics setting causes build fail on windows

### ISSUE THREAD

**Issue by Parallel-Paradox** [bevyengine/bevy#5505]
## Bevy version

The main version with commit code: 83a9e16158ede23c7636a7a106a507d05e86c7b8

##  Relevant system information

Windows, rust nightly version installed.

```txt
stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default) (override)
```

## What you did

Do exactly as [Enable fast compile](https://bevyengine.org/learn/book/getting-started/setup/#enable-fast-compiles-optional)

## What went wrong

I got error message when `cargo run --features bevy/dynamic`:

```txt
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Zshare-generics=n --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler
```

## Additional information

After I disable the config in ${workspaceFolder}/.cargo/config.toml:

```toml
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=n"]
```

The compile process runs properly. I've checked the rust-lld.exe is in .rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\bin\rust-lld.exe, so it might caused by rustflags.

**Comment by bjorn3** [comment]
The full fast compile configuration only works with nightly rustc.

**Comment by Parallel-Paradox** [comment]
> The full fast compile configuration only works with nightly rustc.

I see... I've checked the version of rustc, it turns out that, after I do `rustup default nightly`, the rustc version is still rustc 1.62.1 (e092d0b6b 2022-07-16), which is suppose to be rustc 1.64.0-nightly... Is there a way to change the version manually?

**Comment by bjorn3** [comment]
What does `rustup show` output?

**Comment by Parallel-Paradox** [comment]
> What does `rustup show` output?

I've tried both in default and overrive

```
$ rustup toolchain list
stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc (override)

$ rustup toolchain list 
stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default) (override)
```

But the rustc version dosen't change.

```
$ rustc --version
rustc 1.62.1 (e092d0b6b 2022-07-16)
```

By the way I set custom env var CARGO_HOME and RUST_HOME to download rust in D:/ .

 Maybe I should re-install rust..

**Comment by Parallel-Paradox** [comment]
```txt
Default host: x86_64-pc-windows-msvc
rustup home:  D:\rust\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (overridden by 'D:\code_project\bevy_playground\rust-toolchain.toml')
rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)

```
This is `rustup show`

**Comment by Parallel-Paradox** [comment]
I checked the path of rustc by running `where rustc` in CMD.

```
D:\rust\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\rustc.exe
D:\rust\.cargo\bin\rustc.exe
```

I realize that it might because that shell can't recognize the path of rustc because I checked the existence of rustc.exe in the folder of nightly version.

**Comment by Parallel-Paradox** [comment]
So I solved this problem in a cheat way: I changed the folder's name from nightly-x86_64-pc-windows-msvc into stable-x86_64-pc-windows-msvc, and the original one is changed into stable-x86_64-pc-windows-msvc-backup.

Also I changed the rust-toolchain.toml's channel from nightly into stable.

Now the generics feature can work properly, but this methods may have some potential side-effect so I'm still in search of a better way to solve this issue.

**Comment by mockersf** [comment]
`cargo` is handling rust nightly selection for you, it's not directly calling the `rustc` binary

**Comment by Parallel-Paradox** [comment]
Simply uninstall stable version also solve this issue. But this [#2921](https://github.com/bevyengine/bevy/issues/2921#issue-1018514400) still occurs since I'm using Win11... So I guess I'm just going to clost this generics feature.
