### ISSUE TITLE
The `iter_many_mut` documentation is confused

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#5506]
> Calls a closure on each result of [Query](https://docs.rs/bevy/latest/bevy/ecs/system/struct.Query.html) where the entities match.

The documentation talks about calling a "closure", but `iter_many_mut` doesn't have a closure argument, as the example shows. https://docs.rs/bevy/latest/bevy/ecs/system/struct.Query.html#method.iter_many_mut

**Comment by Nilirad** [comment]
I'll rebase #4989 to `main` and add more appropriate doc comments.

**Comment by ian-h-chamberlain** [comment]
To add to this, it would be helpful to add a mention that the returned value is not actually an `Iterator`. I was confused by the errors when I tried
```rust
for foo in q.iter_many_mut(&entities) {}
```

The comment on the `Iterator` impl for `QueryManyIter` explains this a bit:
```rust
/// Iterator type is intentionally implemented only for read-only access.
/// Doing so for mutable references would be unsound,
/// because calling `next` multiple times would allow multiple owned references to the same data to exist.
```

but it might be good to mention as well on `iter_many_mut` as well, to explain the need for this usage (which can easily be misread as the more common `while let Some(_) = it.next()`:
```rust
let mut it = q.iter_many_mut(&entities)
while let Some(foo) = it.fetch_next() {}
```
