### ISSUE TITLE
Rendering Regression from 0.5.0 to 0.8.0

### ISSUE THREAD

**Issue by barrettTom** [bevyengine/bevy#5510]
## versioning

```
bevy 0.8.0
archlinux 5.15.55-2-lts
rustc 1.62.1 (e092d0b6b 2022-07-16)
cargo 1.62.1 (a748cf5a3 2022-06-08)
2022-07-31T12:09:13.849899Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD RADV RAVEN", vendor: 4098, device: 5592, device_type: IntegratedGpu, backend: Vulkan }
```

## testing

i ran various wgpu examples and didn't see the issue, although they don't have many sprite examples
i also tried the opengl backend renderer, and the issue was still there

## how i got here
I made a sort of bejeweled demo back in 0.5.0, it didn't have this graphical artifact (see screenshots)
I now moved the codebase to using 0.8.0, and noticed there is a white line above the green gems but only sometimes.
in the spritesheet, there is a white sprite above the green gem, so I assume it is coming from that.
i have not changed much in how the spritesheet bundle operates.

the 0.5.0 code can be found here:
https://git.tombarrett.xyz/gems/log.html

and the 0.8.0 diff is here
https://pastebin.com/0BcK0XLS

## 0.5.0
![2022-07-31-140350_3200x1080_scrot](https://user-images.githubusercontent.com/5176580/182027052-334b6151-c95b-492f-a76f-801c384816ee.png)
## 0.8.0
![2022-07-31-140138_3200x1080_scrot](https://user-images.githubusercontent.com/5176580/182027054-839582a7-cfae-4e3e-a781-476df3ad1569.png)

**Comment by alice-i-cecile** [comment]
Duplicate of #5266 :) See that thread for the fix.

**Comment by adals** [comment]
also got it when run cargo run --release --example many_foxes

<img width="1234" alt="Screen Shot 2022-07-31 at 5 39 46 PM" src="https://user-images.githubusercontent.com/169691/182031551-34448588-4cce-48fb-9461-08f5ac66d728.png">

**Comment by rparrett** [comment]
I think that your issue is more like https://github.com/bevyengine/bevy/issues/1949 but that sort of thing is also present in 0.5.0, so that's curious.

If you don't have any padding in your sprite sheet, I'd add some and see if that fixes the issue.

You might also try [setting the default filter mode to nearest](https://bevyengine.org/learn/book/migration-guides/0.7-0.8/#change-default-image-filtermode-to-linear).

The many_foxes issue is a separate thing: https://github.com/bevyengine/bevy/issues/5118

**Comment by barrettTom** [comment]
> Pretty sure this is a duplicate of #5266 :) See that thread for the fix.

I already have `.insert_resource(ImageSettings::default_nearest())` as when I didn't, the 2d pixels were very blurry.

> also got it when run cargo run --release --example many_foxes

I just ran that and do have the same issue, but it seems a little different more related to textureatlases

I also have a build for 0.7.0 that has the same bug

> I think that your issue is more like #1949 but that sort of thing is also present in 0.5.0, so that's curious.

oh this looks very similar, sorry for the repost must have missed it in my search

> If you don't have any padding in your sprite sheet, I'd add some and see if that fixes the issue.

i figured I could give padding to fix it

thanks for the help
