### ISSUE TITLE
WindowDescriptor doc still features a vsync option.

### ISSUE THREAD

**Issue by lotosprogrammer** [bevyengine/bevy#5517]
WindowDescriptor doc still features a vsync option even though it was removed from the crate and is not an option anymore.

https://docs.rs/bevy/0.4.0/bevy/window/struct.WindowDescriptor.html

**Comment by IceSentry** [comment]
Your link is to the 0.4 version of bevy. If you click the warning in the top right it will bring you to the up to date version of the docs.
