### ISSUE TITLE
Color::rgb suggestion 

### ISSUE THREAD

**Issue by Yurovskyy** [bevyengine/bevy#5530]
hello, I have a suggestion about Color::rgb. In the last 24 hours I was trying to render some colors properly, but can't get it. In the end, I found that for some reason the Color::rgb works with 0 to 1 parameters, and not the "default" 0 to 255. It can be my fault, because the parameters are f32, but i really didn't know that this different parameters exists. I think if Color::rgb has a description about it, other people wont have to pass trough this suffer.

**Comment by rparrett** [comment]
Adding docs for this seems like a good idea.

`Color::rgb_u8` or `Color::hex` might be more intuitive for you

**Comment by rparrett** [comment]
Good call on `D-Good-First-Issue`. Accidentally sniped this one though.
