### ISSUE TITLE
Add "how to adopt pull requests" section in Contributing.md

### ISSUE THREAD

**Issue by Weibye** [bevyengine/bevy#5539]
## How can Bevy's documentation be improved?

When encountering PRs labeled `S-Adopt-Me` I'm unsure what is the correct way to "adopt a PR" that also preserves credit of the original authors. 

We should add a section in the CONTRIBUTING.md explaining a short how-to-guide of correctly adopting pull requests

**Comment by oCaioOliveira** [comment]
Hello @Weibye, I and @erickMVDO are going to contribute with this issue.
