### ISSUE TITLE
Add ability to ignore field of bundle

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5559]
## What problem does this solve or what need does it fill?

Add the ability to ignore a field of a bundle using the `#[derive(Bundle)]` macro, causing it to not be included in the generated list of components.

This is primarily useful when working with `PhantomData`.

## What solution would you like?

```rust
#[derive(Bundle)]
struct GenericBundle<T>{
 transform: Transform,
  #[bundle(ignore)]
  _phantom: PhantomData<T>,
}
```

Modify the derive Bundle macro to accomplish this :)

Be sure to add this to the `Bundle` docs as a doc test so this keeps working and can be discovered.

**Comment by mockersf** [comment]
We already have a `#[bundle]` attribute, it could be confusing to add a `#[bundle(ignore)]`. Feel free to find better names either for the existing one or the new one 🙂

**Comment by alice-i-cecile** [comment]
IMO we should be hygienic and use `#[bundle(nest)]` to be clearer about what's going on and keep a quasi-namespace for the trait.

**Comment by LegNeato** [comment]
Serde uses "skip" fwiw

**Comment by maccesch** [comment]
Almost finished implementing this but I just realized that if you add a `#[bundle(ignore)]` to a field, this field type has to implement `Default` or we can't initialize it in the `from_components()` method that is generated in the macro.

Or am I missing sth here?
