### ISSUE TITLE
Viewport Specific UI

### ISSUE THREAD

**Issue by Weibye** [bevyengine/bevy#5570]
## What problem does this solve or what need does it fill?

We should be able to specify which viewport UI should be rendered to in order to facilitate use cases such as split-screen UI:

![image](https://user-images.githubusercontent.com/13300393/182685867-4fa6c7bc-0b44-450e-a424-39cecd447fa0.png)
Source: Mario Kart 8 Deluxe

## What solution would you like?

The root node should contain data defining which viewport it should relate to. 
- The viewport rect should be the layouting context
- This defines which viewport should render the this UI tree / hierarchy
- There should be some relation between viewports and inputs
- I don't think it makes sense to be able to specify this on a per-node basis

## What alternative(s) have you considered?

Ideas are welcome!

## Additional context

- Somewhat related to #1211
- Also related to the topic of render layers for UI

We should add the four-way split-screen to #1974

**Comment by aevyrie** [comment]
> The root node should contain data defining which viewport it should relate to.
>   * The viewport rect should be the layouting context
>   * This defines which viewport should render the this UI tree / hierarchy
>   * There should be some relation between viewports and inputs
>   * I don't think it makes sense to be able to specify this on a per-node basis

Agreed on all counts.

>   * There should be some relation between viewports and inputs

For pointers, I have been using rendertargets to map inputs to cameras targets, then checking if the pointer is within the viewport of the target. With the use case outlined here, it might make more sense to map pointers to windows instead, then check all rendertargets in that window.
