### ISSUE TITLE
Resolve `Val::Percent` into `Val::Px` on the Node

### ISSUE THREAD

**Issue by Weibye** [bevyengine/bevy#5574]
## What problem does this solve or what need does it fill?

- User should be able to get the fixed value equivalents of fields defined in `Val::Percent` on the `Node`. 
- This in order so that you can add, subtract, multiply or divide these values
- This is useful for building higher level features on top and to increase ergonomics when composing and designing UI.

Sizes, borders, margins are expressed in Val:

```rs
pub enum Val {
    /// No value defined
    #[default]
    Undefined,
    /// Automatically determine this value
    Auto,
    /// Set this value in pixels
    Px(f32),
    /// Set this value in percent
    Percent(f32),
}
````

## What solution would you like?

- Add a function `calc()` or `resolve()` on the Node which is responsible for resolving a percent-value to a Px value
  - This Px value can then be operated on
- The function should travel up the node-hierarchy until it reaches a fixed size value, then calculate the final value based on the hierarchy

## What alternative(s) have you considered?

- Not implement this but require the user to manually figure out the sizes in question.

## Additional context

See previous implementation attempt and discussion here: https://github.com/bevyengine/bevy/pull/5555#issuecomment-1204614042

**Comment by maccesch** [comment]
I guess this should also resolve the `Undefined` and `Auto` variants to their effective pixel values?

**Comment by Weibye** [comment]
> In my opinion, this task is "impossible" to do on Bevy side: a way to fix this issue would be that layout engine exposes the whole result of the box model for each node

I think I agree. Should the data in this box model only contain the 'resolved' data given in Pixels? (The original Undefined / auto / percent could still be found in the Style)

This could actually be very valuable for debugging layout 🤔

**Comment by nicoburns** [comment]
Closing this as it's not possible.
