### ISSUE TITLE
Add a workflow that adds a `S-Needs-Review` to all PRs meeting the "review" criteria

### ISSUE THREAD

**Issue by Weibye** [bevyengine/bevy#5620]
## What problem does this solve or what need does it fill?

Bevy's progress is currently bottlenecked by community reviews. [[*Citation needed*](https://c.tenor.com/Dp--4fYUHtgAAAAC/game-of-thrones-go-t.gif)]
Users can search PRs with the following filters and find issues that need their review:

https://github.com/bevyengine/bevy/pulls?q=is%3Aopen+is%3Apr+-label%3AS-Ready-For-Final-Review+-draft%3A%3Atrue+-label%3AS-Needs-RFC+-reviewed-by%3A%40me+-author%3A%40me

This is isn't a very visible approach and it is hard for users to find something that they don't necessarily know how to look for.

## What solution would you like?

Setup an automated workflow that adds the label `S-Needs-Review` to all pull requests that meets these criteria:

- is pull request
- is open
- is not draft
- without `S-Ready-For-Final-Review`
- without `S-Needs-RFC`
- without `S-Blocked`
- without `S-Adopt-Me`?
- Has less than 3 reviews (or less than 3 *approved* reviews?)

Open to discussion if these filters / criteria is the correct ones.

Either the same action or a separate one could also be responsible for removing the `S-Needs-Review` once the PR no longer fits the criteria.

## What alternative(s) have you considered?

- Doing it manually is unfeasible.
- Not adding the label will make it harder to find where to put review focus

**Comment by BD103** [comment]
> "Closing this out: we've moved away from this workflow." - @alice-i-cecile in #5650

I'm going to close this issue as not planned.
