### ISSUE TITLE
Support multiple UI roots

### ISSUE THREAD

**Issue by Weibye** [bevyengine/bevy#5622]
## What problem does this solve or what need does it fill?

In order to support #5570 or #5621 we need a way to define multiple separate UI trees. Each UI root should have data defining which window, viewport and / or render layer they belong to.

> I think the best way of handling it would be to support multiple UI roots with an explicit component that also encodes the settings for the whole tree under the root. This would be one place to specify the `RenderLayer` (or for a better higher level API: specify the camera that renders the UI under the root)

_Originally posted by @nicopap in https://github.com/bevyengine/bevy/issues/5414#issuecomment-1199134972_

**Comment by djeedai** [comment]
For context, Draft PR #1211 has plenty of discussion.
