### ISSUE TITLE
Add an API to manually set change ticks for advanced users

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5633]
## What problem does this solve or what need does it fill?

This API is essential to ensure the reliability of change detection with rollback networking.

> [6:42 AM] Joy: and another thing is I haven't fully figured out how to not break change detection with the whole rollback thing
> [6:42 AM] Joy: simulation component and system change ticks need to be reset like everything else that gets rolled back, so I need us to add a method that lets users manually set change ticks

From @maniwani.

## What solution would you like?

Add a `set_last_changed` method to [`DetectChanges`](https://docs.rs/bevy/latest/bevy/ecs/change_detection/trait.DetectChanges.html). This should come with warnings in the docs about the need to carefully think through exactly what you're doing.

## What alternative(s) have you considered?

Never use change detection in games with rollback networking?

Use a different networking strategy?

## Additional context

If we're adding this, we should similarly add a change-detection bypass to avoid users cobbling together an approach to do this by manually setting the change ticks. 

This was previously done in #2363, but IMO should be unconditionally enabled instead.

**Comment by maniwani** [comment]
For context, any plugins (not just multiplayer) that want to cleanly reset some/all of the data in a `World` to an earlier state and pretend like nothing happened have to reset system and component change tick values too, or else they'll be different and the second run of your systems might see completely different changes.

Also, this is not something blocking me *today*, I'm not even that far lol. Another alternative would be attaching your own versions of system and component ticks as `Local` params and components respectively (e.g. `MyCustomTicks<T>`), but that's a little clunky and it'd be nice to not have to duplicate anything.

**Comment by alice-i-cecile** [comment]
Right; we'll need the ability to muck with system change ticks too. IMO that should be a seperate PR, and be done after the bulk of stageless.
