### ISSUE TITLE
Memory leak when changing font sizes

### ISSUE THREAD

**Issue by xtr3m3nerd** [bevyengine/bevy#5636]
## Bevy Release v0.8.0

commit 0149c41
Rust Version: cargo 1.62.1 (a748cf5a3 2022-06-08)

## What you did

Just recently completed in a game jam which was my first time using both Bevy and Rust (after which I want to say I really enjoyed both and am looking forward to being a part of the community). That being said please forgive any ignorance in my usage of either. One effect I attempted to implement during the game jam was to have the title text grow and shrink over time. My first approach was to modify the font size over time. 

## What went wrong

Modifying the font size over time performs the behavior I desired just fine, however I noticed if I left my game title screen running for a little(like 5 minutes or so) my computer would start chugging and when looking at resource usage, the game was eating over 30GB of memory. 

I worked around this by modding the scale of the transform on the text entity rather than modifying the text size. Thinking on it this is probably a more "correct" solution to the problem, but seeing my simple game take up 30+ GB of memory just sitting at the title screen of my game was concerning. This also means that dynamically modifying fonts can pose a memory leak issue that might be harder to catch in a more complicated use case. I would expect the font system to cleanup after itself ( or if not better communicate to the user that each change to the font is allocating more memory, since that is not a base expectation) 

## Additional information

Here is a minimal example to recreate the issue: 

```rust
use bevy::prelude::*;

const TEST_FONT_SIZE: f32 = 100.0;
const TEST_FONT_VARIATION: f32 = 0.25;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .add_system(leaky_text_updates)
        //.add_system(not_leaky_text_updates)
        .run();
}

#[derive(Component)]
struct TestText;

fn setup(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
) {
    commands.spawn_bundle(Camera2dBundle::default());

    // Text to Test
    commands.spawn_bundle(NodeBundle {
        style: Style {
            size: Size::new(Val::Percent(100.0), Val::Percent(100.0)),
            justify_content: JustifyContent::Center,
            align_items: AlignItems::Center,
            ..default()
        },
        color: Color::NONE.into(),
        ..default()
    }).with_children(|parent| {
        parent.spawn_bundle(
            TextBundle::from_section(
                "Leaky Text?",
                TextStyle {
                    font: asset_server.load("fonts/FiraSans-Bold.ttf"),
                    font_size: TEST_FONT_SIZE,
                    color: Color::WHITE,
                },
            )
        )
        .insert(TestText);
    });
}

fn leaky_text_updates(
    time: Res<Time>,
    mut query: Query<&mut Text, With<TestText>>,
) {
    for mut text in &mut query {

        let seconds = time.seconds_since_startup() as f32;

        // Grow and shrink text
        text.sections[0].style.font_size = TEST_FONT_SIZE +
            TEST_FONT_SIZE * TEST_FONT_VARIATION * (1.25 * seconds).sin();
    }
}

fn not_leaky_text_updates(
    time: Res<Time>,
    mut query: Query<&mut Transform, With<TestText>>,
) {
    for mut transform in &mut query {

        let seconds = time.seconds_since_startup() as f32;

        // Grow and shrink text
        transform.scale = Vec3::ONE +
            TEST_FONT_VARIATION * (1.25 * seconds).sin();
    }
}
```

Then run the following to see the memory usage continue to grow uncontrolled
```
cargo run & top -p $!
```

To test workaround comment out 
```
     //.add_system(leaky_text_updates)
```
and uncomment
```
      .add_system(not_leaky_text_updates)
```

- theories about what might be going wrong
I haven't had a chance to dig into the Bevy code just yet so I might be speaking out my rear, but my current theory is that when the font size is modified bevy allocates some memory to cache the font pre-rendered to the font size. This allocated memory isn't cached so or referenced (or if it is, it doesn't get referenced since the code above references the font at an arbitrary floating point number). As such new pre-rendered font sizes keep getting allocated indefinitely with no cleanup.

- links to related bugs, PRs or discussions
I looked around, but could not find related issue.

**Comment by alice-i-cecile** [comment]
This is a great write-up for a nasty bug. Thanks a ton.

**Comment by xtr3m3nerd** [comment]
Just wanted to update my theory some more after some testing and browsing through code. After some testing I looks like the issue only occurs when you are changing the font size to non-repeating floating point numbers. Exploring around the Bevy code I am seeing that the generated Fonts are stored in a Hashmap indexed by fontsize:

https://github.com/bevyengine/bevy/blob/55957330351828e84bfc63cf8e151e2805e9d278/crates/bevy_text/src/font_atlas_set.rs#L13-L17

Haven't had an opportunity to test and confirm this theory, but looking at the code I am guessing we are continually adding to this hash map since the font sizes are are different calculated floats. This results in this hashmap blowing up as new fonts are generated to match up with the new font sizes.

That being said here are some thoughts on how to handle this. Probably needs some design input since each of these solutions has pluses and minuses. Additionally there may be a solution I am not thinking of. 

## Proposed Solution 1 
Limit the size of the hashmap. 

### Pros:
- simple to implement
- will definitely stop this memory leak
- fail fast, fail early
- provides a way to warn the user that they are doing something potentially dangerous and in an unintended way. 

### Cons:
- what is an appropriate limit? 
- doesn't really address the underlying issue
- Still allows the user to waste a ton of memory caching FontAtlas'es that they wont use very often if at all

## Proposed Solution 2
Implement limited life entries on the hashmap

### Pros:
- helps the FontAtlasSet clean up after itself, while still having the higher performance of caching the textures (only regenerate if it hasn't been used in a while) 

### Cons:
- Still possible to create memory leak situations if fonts are being changed very rapidly
- Having to rebuild fonts occasionally
- Setting a good timing for cleaning up the font
- Having to track the usage of a font

## Proposed Solution 3 
Store fonts in the hashmap based off an approximate or rounded value instead of at the true 32bit floating point precision?

### Pros: 
- It is impractical to need to store fonts at floating point precision's. The generated textures will have the same pixels for a wide range of floating point values

### Cons: 
- Would need to determine at what precision is an appropriate change required to generate a new set.
- Still allows the end user to needlessly store tons of cached fonts for very tiny size changes. 

## End thoughts
Personally leaning towards proposed solution 1 as it will provide a quick way for people who are using this to receive an error that can specifically call out that they should not being dynamically changing the font size. The error can even propose the "workaround" of modifying the scale. Additionally I believe the documentation should be updated to warn user's that dynamically modifying the font size is not an intended use case and can lead to this error. Ideally this FontAtlasSet limit should be something that the end user could modify if they had a specific use case where they needed more FontAtlas'es than provided by default.

**Comment by alice-i-cecile** [comment]
Excellent investigation. My intuition suggests that we should be trying to reuse the handle strategy here. What if we made fonts, as stored in Assets, be specific to a single font size?

**Comment by xtr3m3nerd** [comment]
Forgive my ignorance, but I am not sure I follow. I think that is what we currently do, but Im going to read through the code to better grasp it. 

Writing this down to document my understanding of the font lifecycle. Looking at the TextPlugin we add FontAtlasSet as an asset
``` rust
.add_asset::<FontAtlasSet>()
```
A FontAtlasSet holds a HashMap with the Font Size as a key and a list(Vec) of FontAtlas'es as the value
``` rust
pub struct FontAtlasSet {
    font_atlases: HashMap<FontSizeKey, Vec<FontAtlas>>,
}
```
During runtime either bevy_ui::widget::text::text_system() or bevy_text::text2d::update_text2d_layout(), (Which both update the layout and size information whenever the text or style is changed) will pass this asset to the text_pipeline.queue_text() which then passes this to the GlyphBrush to process_glyphs()

In GlyphBrush::process_glyphs() we call get_or_insert_with() on the Asset<FontAtlasSet> which will find a FontAtlasSet with an existing font_id or it will generate a default FontAtlasSet for this font_id. Then we will call get_glyph_atlas_info() on this FontAtlasSet which is where we get in trouble since this looks up the value in this HashMap based on the font size.

https://github.com/bevyengine/bevy/blob/55957330351828e84bfc63cf8e151e2805e9d278/crates/bevy_text/src/glyph_brush.rs#L103-L108

Seeing this it looks like we do make fonts as stored in asset specific to a single font size, but the issue come from small incremental changes in the font size, since even a small change would result in new Glyphs being generated (even if the underlying glyph texture is exactly the same for a font size of 12 and 12.000001)

What would would the intended behavior be if the user attempts to modify the font style after it has been loaded? 
``` rust 
// repeated every frame
text.sections[0].style.font_size += 0.0000001;
```
Ultimately the core of the issue is communicated expectations to the user. As a user if you know that each font_size caches generated glyphs in memory, doing the above operation each frame is a bad idea, but if you don't know that, modifying the font_size each frame seems like a reasonable way to go about making your text dynamically change size. Since the documentation doesn't mention it, and the code lets you do it we have the potential of leaving the user confused when their RAM fills up, or even worse if that makes it past QA, their players getting confused when their game eats up all their RAM. Proposed solution 1 addresses that by communicating to the user that they are doing something that is unintended and potentially dangerous. Like I cant see a reason why anyone would want to cache over 10,000 generated FontAtlas'es for a single font across 10,000 different font sizes. The other 2 proposed solutions just limit the fallout of a user deciding to take an action like the one above.

**Comment by IceSentry** [comment]
Limiting the hashmap is a good enough solution, but I don't understand why tracking the usage of font sizes would also create a memory leak.

**Comment by xtr3m3nerd** [comment]
I believe I may have miscommunicated. Tracking the usage of font sizes would not create a memory leak (since the memory would be cleaned up), but the memory could still get out of hand if we don't clean this up frequently. So I guess the design question here would be if we do have the cache clean itself, how frequently should it clean itself up? Additionally my concern is that if the user is doing something where that is necessary I believe they are using the system in a way that is unintended , especially considering generating new glyph textures at these arbitrary font sizes has a significant performance impact (which is why we cache it in the first place). 

I was running some experiments to see what this impact is and to better assess what a good default limit would be for the hashmap. If you allow for 10,000 font-sizes in the cache the font hashmap will use approximately 10GB of memory (font used was FiraMono-Bold.ttf, font sizes used in my experiment were between 75 and 125, font-size is important since the size affects how big the generated textures are which in turn affects how much memory they occupy). This seem to scale linearly so 1,000 font sizes resulted in ~1GB of ram used to story cached font glyph textures and 100 font sizes used ~100MB of memory. 

From this data I wanted to propose using a limit of 100 for the hashmap (That is unique font-sizes per font). I believe this is more than enough unique font sizes per font for any reasonable use case. If a user were to require more font-sizes they could be recommended to use Transform.scale to achieve the result(which is much more performant) and/or provide them with a configuration setting that would allow for them to modify this limit. This would encourage the user to not use arbitrary font sizes due to both its memory and performance cost.

**Comment by alice-i-cecile** [comment]
Personally I think that the cached scaled version of the font should be deleted as soon as there are no strong handles actively using that exact font size. That gives the user control over the strategy, and is consistent with the rest of the asset strategy.

**Comment by xtr3m3nerd** [comment]
My main concern with that approach is that it would encourage code like my original example above which has a high performance impact because you are effectively generating a new font texture every frame, which then gets thrown out the subsequent frame, making the cache effectively useless.  In my opinion a framework should not let the user shoot itself in the foot, and it it does it should at least warn the user that they are doing so. 

A second concern is from a technical side the font-size cache currently doesn't use the Asset handles so it wouldn't be as simple as checking if there are any strong handles.

Currently the data is structured as follows:
The fonts are stored in an Assets<FontAtlasSet> so we have handles per font. ( so we have one FontAtlasSet per font ex. "FiraMono-Medium.ttf", "FiraSans-Bold.tff", etc. ) 
Each font size is cached in the FontAtlasSet with the font-size as a key.

FontAtlasSet defined as follows. 
``` rust
pub struct FontAtlasSet {
    font_atlases: HashMap<FontSizeKey, Vec<FontAtlas>>,
}
```

**Comment by IceSentry** [comment]
I'm starting to agree with you that a size limit seems like a better solution. Having more than 100 different font sizes loaded for a single font seems already more than enough. I'd be even willing to go even lower than that, especially if it's configurable and I do believe it should be.

@alice-i-cecile the issue is that this font_atlas is already the asset. Changing this would mean essentially to have one handle for each combination of font size and computed glyphs. This would require some pretty big refactors of the current font rendering code _and_ it would be a lot more complicated. Since this is already an edge case that only happens when someone does something that's probably not the best solution anyway I think we should just go with the size limit approach. It's much simpler and solves the issue while also pushing people towards not doing something that's not a good idea.

**Comment by alice-i-cecile** [comment]
Alright, I'll defer to your expertise here and we can see what the rest of the team thinks at the PR phase :)

**Comment by mockersf** [comment]
Would it make sense to change the font size from a f32 to a u32? With a quick look at Godot, Unity and Unreal Engine, all use int rather than float.

**Comment by xtr3m3nerd** [comment]
That would certainly curb the issue since it would be impractical to make thousands of integer font sizes. Also not sure how useful fractional font sizes actually are. It also would be a much cleaner fix than any of the other proposed solutions. 

Only mild concern I have is that it would be a breaking change

**Comment by IceSentry** [comment]
Breaking changes are fine, that's why we have a big experimental warning at the top of the repo README. And yeah, it does seem like the most simplest fix.

**Comment by alice-i-cecile** [comment]
My preference is definitely integer font sizes. If we find we need more granularity, we should swap to fixed point font sizes with maybe one decimal point instead.

**Comment by tigregalis** [comment]
I remember encountering this a while ago - I thought I created an issue at the time but it was actually just a discord discussion (my bad).

https://discord.com/channels/691052431525675048/743663673393938453/784944159785091132

> #### tigregalis — 12/06/2020
> 
> by doing something I probably shouldn't be doing, animating the font size - at least not in the way I have done it, I ran into a problem where the amount of memory in use continuously grows until we run out of memory and the app crashes.
> 
> this is easily understood: each frame we change the font size, and (because it's a float and frame time isn't 100% uniform) each frame we are likely using a new and unique font size, and so we are creating a new font atlas (with one or more textures).
> 
> the problem is that, as far as I can tell, we never unload the old font atlases (textures).
> 
> the code below simply animates the font size between 20.0 and 40.0.
> ```rust
>     const DURATION: f32 = 2.0;
>     *prog += time.delta_seconds();
>     if *prog >= DURATION {
>         *prog -= DURATION;
>     }
>     let prog = *prog / DURATION;
>     for (mut text, mut _style) in query.iter_mut() {
>         if (0.0..0.5).contains(&prog) {
>             text.style.font_size = 40.0 + 40.0 * (prog - 0.5); // <-
>         } else if (0.5..1.0).contains(&prog) {
>             text.style.font_size = 40.0 + 40.0 * (0.5 - prog); // <-
>         }
>     }
> ```
> 
> the problem from a user's perspective is that they wouldn't assume this would lead to the app consuming all of the system's memory
> 
> #### OvermindDL1 — 12/06/2020
> 
> If you want easily, cleanly, and costless resizable fonts then you probably want a 2-dimension signed distance field font, not bitmap fonts
> 
> I don't think bevy has an SDF loader yet but it's really trivial to write one, the hard part is finding a good 2-dim SDF font
> 
> #### cart — 12/06/2020
> 
> yeah sdf text would be super nice
> 
> we could add a primitive garbage collector in the interim
> 
> ex: if an atlas isn't used for X frames, free it
> 
> #### tigregalis — 12/06/2020
> 
> Having read about SDF now, I'm a little confused by your comment about an "SDF loader" and "finding a good 2-dim SDF font" - I see that it's a class of algorithms but don't see any reference to it being a file format so to speak, though I suppose you could cache the "SDF" representation for a font, and load that. Currently Bevy rasterises the fonts into an atlas "on the fly" (specifically for the characters/glyphs that are actually used), and I suppose you could build an SDF representation "on the fly" instead of rasterising.
> 
> #### tigregalis — 12/06/2020
> 
> This had been my initial thought and it would be fairly straightforward to implement. Animating font sizes is probably an unusual thing to do however... so I don't know if it makes sense to optimise for this particular case (even though I was the one who brought up this problem): In many (most?) cases, a font will be loaded once, and be used in one or a few font sizes, and it's a good optimisation to keep re-using that same font at that font size without having to re-build the texture each time, say if a font only appears once every few seconds.
> 
> An alternative approach might be to provide different APIs for different uses. If you're animating the font size, then choose some type where this is garbage collected, or rendered immediately perhaps and without any caching involved. If you want to keep the font atlas around and re-use it, then choose some type where you would load it with a character set and a font size, then future accesses would pull from that existing atlas - basically as it is now, but more explicit than implicit.
> 
> #### cart — 12/06/2020
> 
> yeah in the case of animation, im not sure garbage collection is a full fix
> 
> because it would still be expensive to allocate new atlases that frequently
> 
> #### tigregalis — 12/06/2020
> 
> The explicit version of what bevy does now with text might be something like let font_atlas = FontAtlas::new(font_handle.clone(), 40.0) or let font_atlas = FontAtlas::new(font_handle.clone(), 40.0, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJLMNOPQRSTUVWXYZ0123456789./?!") then add a reference to font_atlas on the text entity, with whatever text you want to represent. The charset would be growable as required.
> 
> Another approach - before I heard of SDF, and without any understanding really of the performance, or how you'd implement it - might be to generate meshes for each character/glyph.
> 
> Some interesting reading https://aras-p.info/blog/2017/02/15/Font-Rendering-is-Getting-Interesting/
> 
> #### OvermindDL1 — 12/06/2020
> 
> @tigregalis I don't mean a file format, rather the format is usually just png or so, I mean such a properly encoded image.  Building SDF's on the fly is absolutely a solveable problem, however every library I've seen so far that can do that has a lot of nasty (visually) looking corner cases that need to be solved.  So far a human fixed-up SDF font looks far better then generated ones so far.
