### ISSUE TITLE
Camera-driven render to texture breaks when the texture size is changed

### ISSUE THREAD

**Issue by TheRawMeatball** [bevyengine/bevy#5638]
## Bevy version

v0.8.0, still there on main (55957330351828e84bfc63cf8e151e2805e9d278)

## The problem

Changing the size of an `Image` asset which is used as a render target causes a panic. This can be worked around by using set_changed the `Projection` of the camera.

## Additional information

This bug seems to be caused by `AssetEvent`s being processed after `PostUpdate` where the `camera_system` lives. This causes the `camera_system` to miss the change to the texture, leading to a mismatch between the values used for the texture size in different parts of rendering. Setting change detection of `Projection` solves this by forcing an update regardless.

## Potential fix

The ordering of AssetEvents might need to be pulled forward, potentially into PostUpdate, with a particular label.

**Comment by mockersf** [comment]
You don't mention the panic message, but this looks like a duplicate of https://github.com/bevyengine/bevy/issues/5595

**Comment by TheRawMeatball** [comment]
Whoops!
