### ISSUE TITLE
System Labeling docs should include an example

### ISSUE THREAD

**Issue by ItsDoot** [bevyengine/bevy#5653]
## How can Bevy's documentation be improved?

https://docs.rs/bevy/0.8.0/bevy/ecs/system/index.html#system-ordering

This section mentions system labeling, but doesn't explain how the methods it provides should be used. And if an example exists elsewhere in the docs, it should link to there.

**Comment by Gingeh** [comment]
Would adding a link to [this example](https://github.com/bevyengine/bevy/blob/main/examples/ecs/system_sets.rs) be sufficient?
