### ISSUE TITLE
Adding a TextComponent to a SpriteComponents causes a crash

### ISSUE THREAD

**Issue by jmrgibson** [bevyengine/bevy#566]
on both master and 0.2.1
```rust
    for (x, y) in unit_start_positions.into_iter() {
        commands
            .spawn(SpriteComponents {
                material: materials.add(Color::rgb(0.8, 0.2, 0.2).into()),
                transform: Transform::from_translation(Vec3::new(x, y, 1.0)),
                sprite: Sprite::new(Vec2::new(30.0, 30.0)),
                ..Default::default()
            })
            .with_children(|parent| {
                parent.spawn(TextComponents {
                    text: Text {
                        value: "".to_string(),
                        font: asset_server.load("assets/fonts/FiraSans-Bold.ttf").expect("Couldn't find font"),
                        style: TextStyle {
                            font_size: 40.0,
                            color: Color::rgb(0.8, 0.8, 0.8),
                        },
                    },
                    ..Default::default()
                });
            })
            .with(Unit::default())
            .with(Waypoint::default())
            ;
    }
```
The addition of the `.with_children()` method causes the crash

```
thread 'Compute Task Pool (1)' panicked at 'called `Option::unwrap()` on a `None` value', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ui-0.2.1/src/flex/mod.rs:141:64
```

**Comment by TheNeikos** [comment]
It's not the source of crash, but maybe it helps you. But `TextComponents` is meant to be used for UI related tasks. It draws in screen coordinates and not world.

**Comment by mockersf** [comment]
As a UI element, `TextComponents` is meant to hav all its parents also UI elements, meaning that they need a few components like `Node`, `Style` and `Draw`. They are used by the flex system to place UI elements.

`SpriteComponents` is outside of the flex system, so you can't (easily) place a `TextComponents` inside it...

**Comment by jmrgibson** [comment]
Ok, I can probably add some docs to the structs to make that more obvious for future users. Is it worth putting in some run-time type checking to make the error messages better too?

**Comment by MeirKlemp** [comment]
Is there a way to add a text into a sprite?
I am making a 2048 clone with bevy. for now, the tiles are just colors, but I want to add text.
I thought about making the board and the tiles as a UI component and then adding the text,
but if there is a way to add text into a sprite, it will be easier.

**Comment by alice-i-cecile** [comment]
You can now have behavior of this sort using the [`Text2dBundle`](https://docs.rs/bevy/0.5.0/bevy/text/struct.Text2dBundle.html) introduced in 0.5 :)
