### ISSUE TITLE
Unsupported supercompression scheme: Zstandard

### ISSUE THREAD

**Issue by 7flash** [bevyengine/bevy#5660]
## \[Optional\] Relevant system information

```ignore
AdapterInfo { name: "NVIDIA GeForce RTX 3060", vendor: 4318, device: 9351, device_type: DiscreteGpu, backend: Vulkan }
```

## What you did

Running example https://github.com/bevyengine/bevy/blob/main/examples/3d/skybox.rs

```
cargo run --features bevy/ktx2 bevy/zstd
```

## What went wrong

It says that cannot render ktx2 files

![image](https://user-images.githubusercontent.com/4569866/184299929-dd4b0491-f779-4134-886b-d0c6bc50a12d.png)

**Comment by superdump** [comment]
Try `cargo run --features bevy/ktx2,bevy/zstd`

**Comment by 7flash** [comment]
Same error

> Try `cargo run --features bevy/ktx2,bevy/zstd`

![image](https://user-images.githubusercontent.com/4569866/184473587-1d96a11b-dce4-4fc9-8fa0-917b50a82071.png)

**Comment by superdump** [comment]
That isn’t the same error. GPUs support only specific compressed formats in the hardware itself. Usually desktop GPUs support BCn codecs, and mobile support ASTC and perhaps ETC2. The example cycles through them to show which work on your system.

**Comment by clarfonthey** [comment]
Perhaps the error could be slightly improved here, saying that the hardware doesn't support the format, and not the software.
