### ISSUE TITLE
Give an opportunity to provide a padding from the top for `TextureAtlas::from_grid_with_padding`

### ISSUE THREAD

**Issue by MadMed677** [bevyengine/bevy#5661]
## What problem does this solve or what need does it fill?
`TextureAtlas::from_grid_with_padding` assumes that sheets start from texture and then have padding. But some sheets start not from texture but with padding.

## What solution would you like?
I see two options:

1. Be able to provide padding for all 4 sides: top, right, bottom, and left
2. Describe how the sheet starts: from texture or padding

### As an example for point 1
```rust
let texture;
let tile_size = Vec2::new(10.0, 10.0);
let columns = 10;
let rows = 1;

// Create a matrix of 4 elements (top, right, bottom, left)
// But it might be something else
let padding = Matrix4x1::new(0.0, 0.0, 10.0, 10.0);

TextureAtlas::from_grid_with_padding(texture, tile_size, columns, rows, padding);
```

### As an example for point 2
```rust
let texture;
let tile_size = Vec2::new(10.0, 10.0);
let columns = 10;
let rows = 1;

// Create the same padding as it was
let padding = Vec2::new(20.0, 20.0);

enum SheetStartsFrom {
  /// Describes that sheet starts from padding
  Padding,

  /// Describes that sheet starts from texture
  Texture
}

let sheet_starts_from = SheetStartsFrom::Padding;

TextureAtlas::from_grid_with_padding(texture, tile_size, columns, rows, padding, sheet_starts_from);
```

## What alternative(s) have you considered?

Just cut the sheet with hands to provide the padding after the texture (I think for now this is only one way to do so without Bevy)

**Comment by rparrett** [comment]
Your suggestion in point 2 was added in Bevy 0.8.

https://docs.rs/bevy/latest/bevy/sprite/struct.TextureAtlas.html#method.from_grid_with_padding

**Comment by MadMed677** [comment]
Got it. Thanks!
