### ISSUE TITLE
Event persists two frames if added from startup system

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#5663]
## Bevy version

0.8

## What you did

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_event::<TestEvent>()
        .add_plugins(MinimalPlugins)
        .add_startup_system(setup)
        .add_system(test)
        .run();
}

#[derive(Default)]
struct TestEvent;

fn setup(mut test_events: EventWriter<TestEvent>) {
    test_events.send_default();
}

fn test(test_events: EventReader<TestEvent>) {
    if !test_events.is_empty() {
        println!("Event is fired!");
    }
}
```

## What went wrong

It prints `Event is fired!` twice, but I believe it should be printed only once.

## Workaround

Use `Events` directly and call [update](https://docs.rs/bevy/latest/bevy/ecs/event/struct.Events.html#method.update):

```rust
fn setup(mut test_events: ResMut<Events<TestEvent>>) {
    test_events.send_default();
    test_events.update();
}
```

**Comment by DJMcNab** [comment]
This is expected. You never consume the events in the `EventReader` - you only check whether the reader would read any events if you iterated it.

**Comment by DJMcNab** [comment]
Consider the documentation on the [`EventReader::is_empty`](https://docs.rs/bevy/latest/bevy/prelude/struct.EventReader.html#method.is_empty):

> Determines if no events are available to be read without consuming any. If you need to consume the iterator you can use [`EventReader::clear`](https://docs.rs/bevy/latest/bevy/ecs/event/struct.EventReader.html#method.clear).

The docs also have an example of what your system should look like.

Fundamentally, this is not really fixable, aside from through docs. And the docs already sufficiently cover this case. I'd move to close this.

**Comment by Shatur** [comment]
Thanks for the info!

**Comment by Shatur** [comment]
@DJMcNab am I understand correctly that events persists for two frames and after it they will be cleaned up automatically from `Events`, but `EventReader` makes sure that each system that have it receives the event only once?

**Comment by DJMcNab** [comment]
The most comprehensive resource of our events system and related is the documentation on [`Events`](https://docs.rs/bevy_ecs/latest/bevy_ecs/event/struct.Events.html). What I think you're trying to say broadly tracks with my understanding.

**Comment by alice-i-cecile** [comment]
> am I understand correctly that events persists for two frames and after it they will be cleaned up automatically from Events, but EventReader makes sure that each system that have it receives each event only once?

This is exactly correct :)
