### ISSUE TITLE
Alsa and Libudev Error on Pop!_OS

### ISSUE THREAD

**Issue by ArikRahman** [bevyengine/bevy#5677]
- Bevy 0.8
- Cargo Version 1.63
- Pop!_OS 22.04 LTS
-Related issue: https://github.com/bevyengine/bevy/issues/4611

## What I did

##Tried to run this (hello world)

use bevy::prelude::*;

fn main() {
    App::new().add_system(hello_world_system).run();
}

fn hello_world_system() {
    println!("hello world");
}

## What went wrong

##I was expecting cargo run to work, and be greeted with a Hello, World! Instead I was hit with this error:

error: failed to run custom build command for `libudev-sys v0.1.4`

  process didn't exit successfully: `/media/arikrahman/DATA/Rust/bevyproject/bevygame/target/debug/build/libudev-sys-2780f1f32c94568d/build-script-build` (exit status: 101)

##Also, hit with an alsa error.

##Potentially related:
https://github.com/bevyengine/bevy/issues/1855
https://github.com/bevyengine/bevy/issues/850
##Error log attached
[error.txt](https://github.com/bevyengine/bevy/files/9331978/error.txt)

**Comment by bjorn3** [comment]
You will need to install the dependencies listed for Ubuntu here: https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md#ubuntu

**Comment by ArikRahman** [comment]
That solved my issue, thanks!
