### ISSUE TITLE
Asset path wrong parsed (probably)

### ISSUE THREAD

**Issue by r4v3n6101** [bevyengine/bevy#5707]
### Discussed in https://github.com/bevyengine/bevy/discussions/5704

<div type='discussions-op-text'>

<sup>Originally posted by **r4v3n6101** August 15, 2022</sup>
Hello. Recently I've found a strange logic of loading assets [here](https://github.com/bevyengine/bevy/blob/dc3b4b6c850898c922dff9fd6d312823e07096f1/crates/bevy_asset/src/path.rs#L157)
If we use something with 2 "#" in asset_path then we never get full label because only 2 parts of `label` taken (`asset.zip#123#abc` => `asset.zip` as path and  `123` as label). Probably there should be used the `splitn` method, am I right? Should we ever use 2 "#" in paths?</div>

**Comment by rparrett** [comment]
Using `splitn` there does seem more appropriate. It looks like we're just assuming that a label will never contain a `#`.

**Comment by r4v3n6101** [comment]
We should also consider that only `from_string` argument will not contain `#`. User still may create a label with `#` using `AssetPath::new` or `AssetPath::new_ref`.
