### ISSUE TITLE
par_for_each deadlocks on macOS if called concurrently by more systems than there are threads in the ComputeThreadPool

### ISSUE THREAD

**Issue by SJSeckmeyer** [bevyengine/bevy#5743]
## Bevy version

0.8.0

## Relevant system information

Rust version: cargo 1.62.1 (a748cf5a3 2022-06-08)
macOS version: 12.5.1
Processor: Apple M1 Max

## What you did

I derived this test case by reducing the hang originally reported in [https://github.com/TeamAtomECS/AtomECSDemos/issues/1](https://github.com/TeamAtomECS/AtomECSDemos/issues/1).

The below code creates 1 entity with 5 empty components. Each of these components is queried by a minimal system that only calls `par_for_each` on its query with an empty closure.

I added an additional simple `tick` system that prints the number of frames that have already elapsed in order to easily see the deadlock.

In order to reproduce the deadlock it is necessary that each system has a separate component. Multiple systems querying the same component do not produce a deadlock.
So both the number of components and the number of systems calling `par_for_each` must be larger than the number of threads in the `ComputeTaskPool`. (Edit: On my system the ComputeTaskPool has 4 threads.)

The number of frames that elapse before hanging range between zero and a few hundred. More components and tasks make the deadlock more likely.

```rust
use bevy::prelude::*;

struct FrameNumber(u64);

const BATCH_SIZE: usize = 1024;

fn main() {
    let mut app = App::new();

    app.add_system(comp1_system);
    app.add_system(comp2_system);
    app.add_system(comp3_system);
    app.add_system(comp4_system);
    app.add_system(comp5_system);

    app.add_plugins(MinimalPlugins);
    app.add_startup_system(create_entity);
    app.insert_resource(FrameNumber(0));
    app.add_system(log_tick);
    app.run();
}

fn log_tick(mut _commands: Commands, mut frame_number: ResMut<FrameNumber>) {
    dbg!(frame_number.0);
    frame_number.0 += 1;
}

fn create_entity(mut commands: Commands) {
    let compute_task_pool = bevy::tasks::ComputeTaskPool::get();
    dbg!(compute_task_pool.thread_num());

    // Add entity
    let mut entity = commands.spawn();
    entity.insert(Comp1 {});
    entity.insert(Comp2 {});
    entity.insert(Comp3 {});
    entity.insert(Comp4 {});
    entity.insert(Comp5 {});
}

macro_rules! par_for_each_system {
    ($comp:ident, $sys:ident) => {
        #[derive(Component)]
        struct $comp {}
        fn $sys(query: Query<&$comp>) {
            query.par_for_each(BATCH_SIZE, |_| {})
        }
    };
}

par_for_each_system!(Comp1, comp1_system);
par_for_each_system!(Comp2, comp2_system);
par_for_each_system!(Comp3, comp3_system);
par_for_each_system!(Comp4, comp4_system);
par_for_each_system!(Comp5, comp5_system);
```

## What went wrong

The program prints a few frames and then deadlocks.
I would expect bevy to count up and print the frame number indefinitely.

## Additional information

I also tested this on Ubuntu 20.04 and there it does not deadlock even when the number of systems exceeds the number threads in the `ComputeTaskPool`.

**Comment by SJSeckmeyer** [comment]
The update to bevy 0.9.1 fixes at least this example on my system with Rust 1.67.1 and macOS 13.2.
Is that enough to close this issue?


The updated code:
```rust
use bevy::prelude::*;

#[derive(Resource)]
struct FrameNumber(u64);

const BATCH_SIZE: usize = 1024;

fn main() {
    let mut app = App::new();

    app.add_system(comp1_system);
    app.add_system(comp2_system);
    app.add_system(comp3_system);
    app.add_system(comp4_system);
    app.add_system(comp5_system);

    app.add_plugins(MinimalPlugins);
    app.add_startup_system(create_entity);
    app.insert_resource(FrameNumber(0));
    app.add_system(log_tick);
    app.run();
}

fn log_tick(mut _commands: Commands, mut frame_number: ResMut<FrameNumber>) {
    dbg!(frame_number.0);
    frame_number.0 += 1;
}

fn create_entity(mut commands: Commands) {
    let compute_task_pool = bevy::tasks::ComputeTaskPool::get();
    dbg!(compute_task_pool.thread_num());

    // Add entity
    let mut entity = commands.spawn_empty();
    entity.insert(Comp1 {});
    entity.insert(Comp2 {});
    entity.insert(Comp3 {});
    entity.insert(Comp4 {});
    entity.insert(Comp5 {});
}

macro_rules! par_for_each_system {
    ($comp:ident, $sys:ident) => {
        #[derive(Component)]
        struct $comp {}
        fn $sys(query: Query<&$comp>) {
            query.par_for_each(BATCH_SIZE, |_| {})
        }
    };
}

par_for_each_system!(Comp1, comp1_system);
par_for_each_system!(Comp2, comp2_system);
par_for_each_system!(Comp3, comp3_system);
par_for_each_system!(Comp4, comp4_system);
par_for_each_system!(Comp5, comp5_system);
```

**Comment by james7132** [comment]
> The update to bevy 0.9.1 fixes at least this example on my system with Rust 1.67.1 and macOS 13.2. Is that enough to close this issue?

Does this exceed the number of logical cores on your machine? If it does, it probably can be considered fixed.

**Comment by SJSeckmeyer** [comment]
The 5 components from above never exceeded the number of logical cores (10) on my machine but only the number of threads in the compute task pool (4) which did not change between versions. Just to be safe I tested it just now with 15 components and this also does not deadlock.

**Comment by james7132** [comment]
If that's the case, I'll close the PR. This likely got fixed as a part of the stageless work.
