### ISSUE TITLE
Remove render feature group

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#5753]
## What problem does this solve or what need does it fill?

Almost every Bevy plugin use `render` feature group by mistake. It pulls `bevy_ui`, `bevy_sprite` and a lot of other plugins. I did so many PRs for third party crates that fixed this :smile:
For how many crates made this mistake see references to https://github.com/bevyengine/bevy/issues/4202

## What solution would you like?

I would remove this feature group. We already have `default` feature which provides full engine experience.

**Comment by Nilirad** [comment]
I agree, but we need to document all those rendering features, so people can choose what they need.

**Comment by mockersf** [comment]
I agree too 👍
