### ISSUE TITLE
when setting the rotation of a ui node it will scale too

### ISSUE THREAD

**Issue by astreetsign** [bevyengine/bevy#5765]
## Bevy version
0.8.0

## \[Optional\] Relevant system information

AdapterInfo { name: "AMD RV710 (DRM 2.50.0 / 5.18.16-arch1-1, LLVM 14.0.6)", vendor: 0, device: 0, device_type: Other, backend: Gl }

## What you did

i set the rotation with a system

`use bevy::prelude::*;

fn main() {
    App::new()

	     .add_plugins(DefaultPlugins)
	    .add_startup_system(setup_camera)
            .add_system(make_ui)

            .add_system(move_ui)

        .run()
        ;

    }

#[derive(Reflect, Component,Default)]
#[reflect(Component)]
struct Ui;

#[derive(Reflect, Component,Default)]
#[reflect(Component)]
struct JustMade;

fn setup_camera(
mut commands :Commands
){

    commands.spawn_bundle(Camera2dBundle::default());
}

fn make_ui(

    mut commands : Commands,
    mut keys: ResMut<Input<KeyCode>>,

){
    if keys.just_pressed(KeyCode::D) {

        commands.spawn_bundle(NodeBundle {
            style: Style {
                position_type : PositionType::Absolute,
                flex_direction: FlexDirection::ColumnReverse,
                justify_content: JustifyContent::Center,
                size: Size::new(Val::Px(200.0), Val::Px(300.0)),
                ..default()
            },
            color: Color::rgb(0.15, 0.15, 0.15).into(),
            ..default()
        })
        .insert(Ui)
        .insert(JustMade)

        ;

        keys.reset(KeyCode::W);

    }

}

fn move_ui(

    mut commands : Commands,
    mut ui_entity_query : Query<(Entity,&mut Transform),With <JustMade>>,
    mut windows: ResMut<Windows>,

){

    for (e,mut transf) in ui_entity_query.iter_mut(){

        let current_angle = 1.632;

        transf.rotation.z = current_angle;

    commands.entity(e)

        .remove::<JustMade>();

    }

}

`

## What went wrong

If it's not clear, break this out into:

- what were you expecting?
i was expecting the ui to just rotate

- what actually happened?
the ui scaled

## Additional information
without setting the rotation:
![Bildschirmfoto_2022-08-22_08-46-17](https://user-images.githubusercontent.com/111244785/185880289-5eb7ac6b-aef6-4dbd-9b03-2da29f7a76bd.png)

setting the rotation:
![Bildschirmfoto_2022-08-22_08-47-24](https://user-images.githubusercontent.com/111244785/185880325-423b2030-d2fc-4f74-8d20-4f873c0e485a.png)

**Comment by tguichaoua** [comment]
It's because `Transform::rotation` is a quaternion and not a vec of euler angles.
To set the rotation around z, you should do this:
```rs
transf.rotation = Quat::from_rotation_z(current_angle);
```
