### ISSUE TITLE
No GPU Version Found

### ISSUE THREAD

**Issue by aftix** [bevyengine/bevy#5767]
## Bevy version

v0.8.0

## \[Optional\] Relevant system information

Arch linux, Wayland, nouveau drivers

cargo 1.63.0-nightly (4d92f07f3 2022-06-09)

## What you did

Followed the bevy book for initializing default plugins (https://bevyengine.org/learn/book/getting-started/plugins/). I am using the `wayland` feature in my `Cargo.toml`.

## What went wrong

No window appears, instead I get the message `thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!', /home/aftix/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.8.0/src/renderer/mod.rs:103:10`

## Additional information

I have done a system update and rebooted. I have verified that wgpu and winit examples work on this setup.

**Comment by DJMcNab** [comment]
Can you compare the features activated for our depedency on wgpu with the features enabled for wgpu when you run the example?

This can probably be done with `cargo tree -e features -p wgpu`

**Comment by aftix** [comment]
They seem to both be default features. There's a lot of dependencies to check, but the main ones all have the same features ("default")

**Comment by aftix** [comment]
Using some UNIX tools, it looks like all the things that the two wgpu's share have the same features enabled.

**Comment by DasLixou** [comment]
I get sort of the same error with x11 and amd-gpu drivers: `thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!', /home/lixou/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.8.1/src/renderer/mod.rs:103:10`

**Comment by DasLixou** [comment]
Solved it by installing `vulkan-radeon` on linux

**Comment by rsaihe** [comment]
> Solved it by installing `vulkan-radeon` on linux

A similar fix worked for me on Alpine Linux (`mesa-vulkan-intel` in my case).

**Comment by mockersf** [comment]
closing to centralise in #3191
