### ISSUE TITLE
Add support for detecting release of a button

### ISSUE THREAD

**Issue by Weibye** [bevyengine/bevy#5769]
## What problem does this solve or what need does it fill?

Currently we detect when a button is being hovered, or clicked, but not _released_.
```
pub enum Interaction {
    /// The node has been clicked
    Clicked,
    /// The node has been hovered over
    Hovered,
    /// Nothing has happened
    #[default]
    None,
}
```
In this case `Clicked` is true when the user presses down on the button.

## What solution would you like?

Add a `Released` variant to the `Interaction` enum, then add whatever logic necessary to correctly detect it.

## What alternative(s) have you considered?

- Not supporting it is not really an option. Most applications (and games) only trigger the button's action on release.

**Comment by nicopap** [comment]
#5378  handles this by sending an event on release. Also handles nicely when you hold down the mouse button, but slide the mouse off the button before releasing it.

**Comment by alice-i-cecile** [comment]
This is now complete due to `bevy_picking`'s creation and integration with `bevy_ui`.
