### ISSUE TITLE
Files outside of the assets folder causes crash on edit

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#5770]
## Bevy version

0.8

## What you did

1. Enable watching for changes 
2. Load a scene outside of the `assets` folder (for example, from `~/.config/my_game/scene.scn`)
3. Edit the scene.

## What went wrong

Engine crashes with the following error:

```
called `Result::unwrap()` on an `Err` value: StripPrefixError(())
```

on this line:

https://github.com/bevyengine/bevy/blob/cde5ae8104a0473ffe82c0ba2380bdd96a0b17ab/crates/bevy_asset/src/io/file_asset_io.rs#L191

## Additional information

I would expect to just ignore files that are outside of the asset folder. Because things like savegames don't need to be reloaded on change.

**Comment by devil-ira** [comment]
I think this would be fixed by https://github.com/bevyengine/bevy/pull/5690.

**Comment by Shatur** [comment]
Yes, it would. But maybe we shouldn't try to reload assets outside of the `assets` folder?

**Comment by Shatur** [comment]
Found a workaround: deserialize scene manually. Probably the only way for now if you want to use `DynamicScene` for savegames.

https://github.com/bevyengine/bevy/blob/cde5ae8104a0473ffe82c0ba2380bdd96a0b17ab/crates/bevy_scene/src/scene_loader.rs#L31-L35

**Comment by devil-ira** [comment]
> maybe we shouldn't try to reload assets outside of the assets folder?

Nah. Restricting that seems arbitrary.

It may make sense to allow users to configure which assets/asset types get reloaded though.
