### ISSUE TITLE
Can't Install Bevy With Cargo

### ISSUE THREAD

**Issue by archuser555** [bevyengine/bevy#5771]
hello, i get the folowing error when run the command: **cargo install bevy**
here is the error:
_   Updating crates.io index
error: failed to download `bevy v0.8.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy-0.8.0/Cargo.toml`

Caused by:
  feature `named-profiles` is required

  The package requires the Cargo feature called `named-profiles`, but that feature is not stabilized in this version of Cargo (1.56.0).
  Consider trying a more recent nightly release.
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#custom-named-profiles for more information about the status of this feature._
Thanks! if any information's needed just say that to me!

**Comment by rparrett** [comment]
Bevy needs a newer version of rust. If you installed rust with rustup, you can update it with `rustup update`.

**Comment by Nilirad** [comment]
Anyway, bevy is a library, not an executable, therefore it can't be `cargo installed`. It is added as a dependency to the user's project.
