### ISSUE TITLE
Upgrade cpal to 0.14.0

### ISSUE THREAD

**Issue by TimJentzsch** [bevyengine/bevy#5774]
## What problem does this solve or what need does it fill?

The previous version of `cpal` depended on two versions of `parking_lot`, increasing compile times and sizes. With release 0.14.0, this has been fixed.

## What solution would you like?

We should upgrade to the latest `cpal` version and update the skipped crates in `deny.toml`. We should at least be able to remove the `parking_lot` lines:

<https://github.com/bevyengine/bevy/blob/5e2d9b4ae4b6c996900428e3f3980611ac497ce3/deny.toml#L36-L48>

## Additional context

- Issue on `cpal`: <https://github.com/RustAudio/cpal/issues/664>

**Comment by harudagondi** [comment]
- My PR is now merged: RustAudio/rodio#435

now we just have to wait for a new rodio release
