### ISSUE TITLE
Unable to Load Quat Type for Scene Example

### ISSUE THREAD

**Issue by Carter0** [bevyengine/bevy#5790]
## Bevy version

I just pulled down main right now. 

## What you did

I ran the scene example with `cargo run --example scene`

## What went wrong

I get this warning... 

` WARN bevy_asset::asset_server: encountered an error while loading an asset: No registration found for glam::f32::scalar::quat::Quat`

If I delete the transform component from the ron file, it seems to work fine and I get

```
2022-08-24T22:28:06.755070Z  INFO scene:   Entity(3)
2022-08-24T22:28:06.755115Z  INFO scene:     ComponentA: { x: 1 y: 2 }

2022-08-24T22:28:06.816769Z  INFO scene:   Entity(4)
2022-08-24T22:28:06.816809Z  INFO scene:     ComponentA: { x: 3 y: 4 }
```

**Comment by DJMcNab** [comment]
It's better than that. The name for the glam types depends on your target features - see e.g. https://github.com/bitshifter/glam-rs/blob/main/src/f32.rs

That is, there is no true type name for glam's `Quat`, as currently defined.

We need https://github.com/bevyengine/bevy/issues/5745#issuecomment-1221389131
