### ISSUE TITLE
Compiled WASM example is not working on iPadOS 15.6.1

### ISSUE THREAD

**Issue by bofh** [bevyengine/bevy#5795]
## Bevy version

0.8.1

## Relevant system information

* iPad Air 4th gen
* Chrome/Safari (WebAssembly)
* iPadOS 15.6.1
* rustc 1.63.0 (4b91a6ea7 2022-08-08) at Ubuntu 20.04.4 LTS
```
LOG%cINFO%c crates/bevy_render/src/renderer/mod.rs:106%c AdapterInfo { name: "Apple GPU", vendor: 0, device: 0, device_type: Other, backend: Gl } color: whitesmoke; background: #444 color: gray; font-style: italic color: inherit
LOG%cWARN%c %c Context is not secure, gamepad API may not be available. log.target = "gilrs_core::platform::platform::gamepad";
log.module_path = "gilrs_core::platform::platform::gamepad";
log.file = "/home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/gilrs-core-0.4.1/src/platform/wasm/gamepad.rs";
log.line = 30; color: orange; background: #444 color: gray; font-style: italic color: inherit
```

## What you did

* Updated iPadOS to 15.6.1
* Observed that my project is no longer works
* Compiled lighting example as per documentation

## What went wrong

I could only see html background (stripes), not even gray clear color on bevy canvas

## Additional information
* #3574
* Version 0.7.0 also doesn’t seem to work
* Unchecking WebGL via Metal leads to “error repeatably occurs on this page” error screen in Safari
* 2D examples at https://bevyengine.org/examples are working, lighting does not

### Edited
* Clarified which examples are working

**Comment by maxammann** [comment]
We are also hitting this problem in maplibre-rs: https://github.com/maplibre/maplibre-rs/issues/164

I think we should further narrow down which exact feature of bevy and wgpu is causing it.

**Comment by maxammann** [comment]
This should be resolved with iOS 16 and Safari 16.

**Comment by mockersf** [comment]
Still broken 👎

**Comment by maxammann** [comment]
Oh oke, sorry, in that case my Problem was probably unrelated.

**Comment by rparrett** [comment]
Looks likes this was fixed in Safari over a year ago.

Checked some PBR stuff in Safari on iOS 17.5.1 just to confirm.
