### ISSUE TITLE
#[derive(Bundle)] is not hygienic

### ISSUE THREAD

**Issue by derivator** [bevyengine/bevy#5817]
## Bevy version

0.8

## What you did

```rust
use egui::Shape::Vec;

#[derive(Bundle)]
pub struct MyBundle {
    f: Foo,
}
```

## What went wrong
Compilation fails with:
```
error[E0573]: expected type, found variant `Vec`
```
because [this](https://github.com/bevyengine/bevy/blob/70106773f2f70bdc19c89e57c64d38918aab9c02/crates/bevy_ecs/macros/src/lib.rs#L152) does not use the fully qualified type name `std::vec::Vec` and proc-macros are not hygienic.

## Additional information

Yes, egui has an [enum-variant called Vec](https://docs.rs/egui/latest/egui/enum.Shape.html) and my IDE sometimes randomly tries to be helpful and imports it for me. :smile: 

[`impl_param_set`](https://github.com/bevyengine/bevy/blob/70106773f2f70bdc19c89e57c64d38918aab9c02/crates/bevy_ecs/macros/src/lib.rs#L183) also uses lots of bevy-specific types without fully qualified names, but I'm not sure if that's a problem.

**Comment by jgoday** [comment]
Hi, just started to look and play with bevy.
This is a simple [#5835 PR](https://github.com/bevyengine/bevy/pull/5835) that tries to address this issue.
