### ISSUE TITLE
Clarify that `Node` is calculated and should not be set by the user

### ISSUE THREAD

**Issue by Weibye** [bevyengine/bevy#5820]
## How can Bevy's documentation be improved?

- Users sometime struggle understanding the difference between `Node.size` and `Style.size`. 
- `Node` is a calculated component but nowhere in the documentation are we making this clear

In the short term we should consider:
1. Rename `Node.size` -> `Node.calculated_size`
2. Add documentation specifically noting that `Node` should only be read from by the user

In the long term we need better documentation teaching the ins and outs of UI in Bevy

**Comment by djeedai** [comment]
Thanks @Weibye !
