### ISSUE TITLE
`bevy_window::PresentMode` says `Immediate` and `Mailbox` will panic if unsupported, but also says they will fallback to `Fifo` if unsupported

### ISSUE THREAD

**Issue by LikeLakers2** [bevyengine/bevy#5831]
Hi! I was browsing Bevy's documentation, just thinking up ideas for games, when I chanced upon some rather curious documentation.

Within [`bevy_window::PresentMode`](https://docs.rs/bevy_window/0.8.1/bevy_window/enum.PresentMode.html)'s documentation, it states the following:

> `Immediate` or `Mailbox` will gracefully fallback to `Fifo` when unavailable.

This statement is also repeated in the [descriptions of `Immediate`](https://docs.rs/bevy_window/0.8.1/bevy_window/enum.PresentMode.html#variant.Immediate) and [`Mailbox`](https://docs.rs/bevy_window/0.8.1/bevy_window/enum.PresentMode.html#variant.Mailbox):

> Will fallback to `Fifo` if unavailable on the selected platform and backend.

However, under both variants, there's also this statement which seems to conflict with the above statements:

> Selecting this variant will panic if not supported, it is preferred to use `PresentMode::AutoNoVsync`.

Having read all this, I'm now confused as to whether `Immediate` and `Mailbox` are safe to use because they will fall back to `Fifo` if they're unsupported, or if I should prefer another mode due to the possibility of a panic.

To be clear: I will most likely never need to use `PresentMode` myself, so whatever is meant here will not mean much to me. But I fear that the documentation may be confusing to others, so I hope it can be updated to avoid this conflict of statements.

**Comment by mockersf** [comment]
If I remember correctly, the gracious fallback behavior is not true anymore and should be removed. Now only the ˋAutoˋ variants do fallback

**Comment by NoahShomette** [comment]
Hi is this just a docs update? I would be happy to update it and submit a PR
