### ISSUE TITLE
Vertex Weirdness

### ISSUE THREAD

**Issue by ZacharyKamerling** [bevyengine/bevy#584]
I'm generating vertices with marching cubes. I split up the terrain into size 32x32x32 chunks of voxels. I'm currently generating 4x4x4 (or 64) chunks. I'm just doing some simple sin maths to generate voxels. Adjusting the *f* value yields "interesting" results.

```rust
let f = 1.0/16.0;
((x as f32 * f).sin() + (y as f32 * f).sin() + (z as f32 * f).sin()) / 3.0
```

![Err1](https://user-images.githubusercontent.com/1644598/94349631-3dfbae80-fffb-11ea-839b-3dc7ce8ac344.png)

```rust
let f = 1.0/8.0;
```

![Err2](https://user-images.githubusercontent.com/1644598/94349633-3f2cdb80-fffb-11ea-823a-48a240129564.png)

In the first image, the number of *chunks* with at least 1 triangle generated is 62. In the second image it's 64.

Here's a list with the number of triangles per chunk for the first image.
```
527
2868
61
527
2558
4356
1098
2868
4356
627
3891
61
1098
3891
271
527
2558
4356
1098
2558
4120
3348
3190
4356
3348
163
4215
1098
3190
4215
1673
2868
4356
627
3891
4356
3348
163
4215
627
163
473
3891
4215
473
4402
61
1098
3891
271
1098
3190
4215
1673
3891
4215
473
4402
271
1673
4402
553
```

Here's a list with the number of triangles per chunk in the second image.
```
3325
5135
5637
3322
5135
4720
4950
5304
5637
4950
5188
5960
3322
5304
5960
3096
5135
4720
4950
5304
4720
3820
3830
5002
4950
3830
3828
5253
5304
5002
5253
5481
5637
4950
5188
5960
4950
3830
3828
5253
5188
3828
3790
5436
5960
5253
5436
6237
3322
5304
5960
3096
5304
5002
5253
5481
5960
5253
5436
6237
3096
5481
6237
2858
```

**Comment by julhe** [comment]
Hey, can you add more information, like example code?

**Comment by ZacharyKamerling** [comment]
I'm pretty convinced the problem was I was adding too many vertices to a mesh (limited to 65_536).
