### ISSUE TITLE
Mention `QueryItem` in `WorldQueryGats`

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#5842]
## How can Bevy's documentation be improved?

`QueryItem` can be extremely useful, but is not very discoverable, leading to questions like [this](https://github.com/bevyengine/bevy/discussions/5810#discussioncomment-3489085). Note that this is not the first time such a question is asked.

A good first step in making `QueryItem` more discoverable is mentioning it in the documentation of other items, such as `WorldQueryGats`.

**Comment by afonsolage** [comment]
I was using `<<T as WorldQueryGats<'w>>::Fetch as Fetch<'w>>::Item` until I read this issue, so yeah, I second this.
