### ISSUE TITLE
Warn about broken hierarchies

### ISSUE THREAD

**Issue by asafigan** [bevyengine/bevy#5849]
## What problem does this solve or what need does it fill?

Currently things like rendering require that every ancestor in a hierarchy have a set of components in order to work. Adding a child to a parent which doesn't have these components silently fails. For example, adding a entity with a `PbrBundle` to a parent that doesn't have a `SpatialBundle` causes the child not to be rendered. It can be confusing what the cause of the problem is.

## What solution would you like?

On debug builds, warn that a child has `SpatialBundle` components but it's parent doesn't.

## What alternative(s) have you considered?

Writing my own system to do this for me.

## Additional context

A missing `SpatialBundle` wasted me an hour of time on Bevy Jam 2. A simple warning would have pointed out the issue to me immediately and saved me all that time and energy.

There are other issues that show this is a common foot gun: https://github.com/bevyengine/bevy/issues/2277, https://github.com/bevyengine/bevy/issues/5081

**Comment by devil-ira** [comment]
There's an open PR for this: https://github.com/bevyengine/bevy/pull/5590.

**Comment by asafigan** [comment]
Great!
