### ISSUE TITLE
A way to determine if an entity exists with `Commands`

### ISSUE THREAD

**Issue by asafigan** [bevyengine/bevy#5850]
## What problem does this solve or what need does it fill?

Some times you may be trying to work with entities that may or may not exist anymore. It would be helpful to have a way of determining is an entity exists with `Commands`

## What solution would you like?

Add a `get_entity()` method on `Commands` that returns an `Option<EntityCommands>`.

Maybe a `entity_exists()` method on `Commands` that return a `bool`.

## What alternative(s) have you considered?

You could have a `Query<Entity>` and check it before calling `entity()` on `Commands`.

## Additional context

There are a lot of issues about handling command errors: https://github.com/bevyengine/bevy/issues/2004, https://github.com/bevyengine/bevy/issues/3845, https://github.com/bevyengine/bevy/pull/2241, https://github.com/bevyengine/bevy/issues/5617. 

I feel like this would still be useful even with command error handling.

**Comment by hymm** [comment]
We're already calling Entities.contains on a `commands.entity`, so having a non panicking `get_entities` makes sense to me

FYI: another alternative is to use the `Entities` system param and call `.contains` on it. https://docs.rs/bevy/latest/bevy/ecs/entity/struct.Entities.html#method.contains
