### ISSUE TITLE
STATUS_HEAP_CORRUPTION after modifying rows/columns for the breakout example

### ISSUE THREAD

**Issue by jgrimes** [bevyengine/bevy#586]
In the breakout example at SHA `3abfcad7ab5e194e1b79daedc0234e2d3afbfb24`
Modifying this:

    let brick_rows = 4;
    let brick_columns = 5;

To this:

    let brick_rows = 9;
    let brick_columns = 9;

Causes this:

    $ cargo run --example breakout
       Compiling bevy v0.2.1 (C:\Users\jg\github\bevy)
        Finished dev [unoptimized + debuginfo] target(s) in 8.25s
         Running `target\debug\examples\breakout.exe`
    error: process didn't exit successfully: `target\debug\examples\breakout.exe` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)

Here is my compiler version:

    active toolchain
    ----------------

    stable-x86_64-pc-windows-msvc (default)
    rustc 1.46.0 (04488afe3 2020-08-24)

**Comment by cart** [comment]
Can you update to latest master? I think this is fixed by #582

**Comment by jgrimes** [comment]
@cart Yep, that fixed it. Thanks!
