### ISSUE TITLE
Bevy game crashed on ios if swipe from screen bottom up

### ISSUE THREAD

**Issue by shuoli84** [bevyengine/bevy#5882]
I've met a reproducible crash on bevy ios game. After some trouble shooting, it seems the root cause is, window is not created inside UIApplicationMain. For more info, refer to https://github.com/rust-windowing/winit/issues/1705#issuecomment-1236363196, [madsmtm](https://github.com/madsmtm) mentioned that the window should created in StartEvent(Init) handler.

In bevy_winit code, window is created early, any idea why? Is it possible to move this code to StartEvent(Init)?

https://github.com/bevyengine/bevy/blob/76ae6f4c6e77866104229659a211045748cfb4bf/crates/bevy_winit/src/lib.rs#L58

**Comment by bjorn3** [comment]
> In bevy_winit code, window is created early, any idea why?

See the comment above that line:

> Note that we create a window here "early" because WASM/WebGL requires the window to exist prior to initializing the renderer.

**Comment by shuoli84** [comment]
@bjorn3 yea, I saw it. But not sure is it a hard requirement, any other way to solve the WebGL requirement?

**Comment by bjorn3** [comment]
I think it is a hard requirement for WASM/WebGL as the render context is created by calling a method on the `<canvas>` element of the winit "window".

**Comment by shuoli84** [comment]
@bjorn3 Good to know, if this is purely for wasm/webgl, then we can condition compile just for that platform?

**Comment by shuoli84** [comment]
I just tried comment that code out, crash gone. 🎉 🎉

**Comment by bjorn3** [comment]
You could change the line above from `#[cfg(not(target_os = "android"))]` to `#[cfg(not(any(target_os = "android", target_os = "ios")))]`.

**Comment by HackerFoo** [comment]
Related issue: https://github.com/bevyengine/bevy/issues/3185
