### ISSUE TITLE
Add a warning if `WindowDescriptor` is inserted after the render plugin

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#5884]
## How can Bevy's documentation be improved?

To set the `present_mode` (aka vsync) of the bevy app, it is required that the `WindowDescriptor`  resource be inserted before the insertion of the core bevy rendering plugin, so that it's possible to set the present mode when initializing rendering-related resources.

It is easy to mistakenly add the `WindowDescriptor` **after** the default bevy plugins. And there is absolutely no feedback telling user that they are "holding it wrong," resulting in difficult-to-understand unexpected behavior.

There should be a check on whether `WindowDescriptor` was inserted/updated after its useful insertion time and print a warning, explaining what problems this entails and how to fix the issue (adding the resource _before_ the rendering plugin).

**Comment by IceSentry** [comment]
This PR would solve this more generally instead of being WindowDescriptor specific https://github.com/bevyengine/bevy/pull/2988
