### ISSUE TITLE
Add `pop` method to reflection `List` trait

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5897]
Yeah that's what I was getting at in my other comment. I don't think it's going to be beneficial to add a new trait for each data structure type. That can probably be served somehow via `TypeData`.

But a `pop` method at least let's us handle lists, queues, and stacks in a general way.

_Originally posted by @MrGVSV in https://github.com/bevyengine/bevy/pull/5792#discussion_r955195316_

**Comment by MrGVSV** [comment]
I believe this was handled in #5797
