### ISSUE TITLE
Commands is poorly communicated to new users

### ISSUE THREAD

**Issue by Sheepyhead** [bevyengine/bevy#5913]
## How can Bevy's documentation be improved?

I've had to tell new users that things done through Commands don't apply until the end of the stage tens of times. I'm fine with that, but it does indicate to me that there's something about the Commands documentation or API that is misleading to new users, and I'm not sure if it'd take a rethinking of how the Commands API is named, or just more obvious documentation of this, but I thought I'd bring it up because I do see it as a general communication issue with Bevy right now.

**Comment by Nilirad** [comment]
If only those users checked the documentation...

https://docs.rs/bevy_ecs/0.8.1/bevy_ecs/system/struct.Commands.html

**Comment by Sheepyhead** [comment]
> If only those users checked the documentation...
> 
> https://docs.rs/bevy_ecs/0.8.1/bevy_ecs/system/struct.Commands.html

Regardless we have to work with the world we have and not the world we wish we had 😅

**Comment by rparrett** [comment]
Interpreting those docs correctly requires an understanding of the engine that users often do not have yet when this hits them.

This seems like a book problem to me.

**Comment by mockersf** [comment]
let's just rename `Commands` to `DeferredCommands` 😄  #5930

**Comment by Nilirad** [comment]
> let's just rename `Commands` to `DeferredCommands` smile #5930

I can already hear people asking where is `InstantCommands` 😆
