### ISSUE TITLE
Scale factor increase / decrease no longer works in example

### ISSUE THREAD

**Issue by Weibye** [bevyengine/bevy#5927]
## Bevy version

`main`: 7d9e864d9cbd2e755d2458b3d204328776687227

## Relevant system information

Windows 11

## What you did

- `cargo run --example scale_factor_override`
- Follow instructions in example
  - Pressing `return` should toggle scale-factor override
  - Pressing `Up` and `Down` should increase or decrease scale-factor override

## What went wrong

 - Pressing `Up` and `Down` produces no tangible change in the UI.

**Comment by rparrett** [comment]
I can't reproduce.

It looks like you are meant to toggle the override first with the enter key.

**Comment by Weibye** [comment]
Ooops, yup you are correct! First pressing `return` then `Up` and `Down`, the example works as expected.
