### ISSUE TITLE
Example involving uniform/storage buffers for compute shaders

### ISSUE THREAD

**Issue by HugoPeters1024** [bevyengine/bevy#5939]
## How can Bevy's documentation be improved?

Especially since the ergonomics improvements around materials such as deriving `AsBindGroup`, it has become quite unclear how to create and use buffers in other cases. A very reasonable place to use them I think would be compute shaders. It would be great to add an example (or perhaps extent the game of life example, although not if that makes sense) that shows how to create, update, and bind buffers to a compute dispatch.

Opening this issue was also the idea of @superdump

**Comment by IceSentry** [comment]
#5843 was created to track this and there's already #5925 as the first example made for that. Feel free to add a comment on that issue if you think something is missing.

**Comment by alice-i-cecile** [comment]
Closing to track this in #5843 :) Thanks though!
