### ISSUE TITLE
Docs for SystemState should mention using apply() to effect Commands

### ISSUE THREAD

**Issue by chrispetkau** [bevyengine/bevy#5940]
https://docs.rs/bevy/latest/bevy/ecs/system/struct.SystemState.html

This detail pulled from the Bevy Cheat Book should appear in the Basic Usage section for SystemState:

> If you are using Commands, you can choose when you want to apply them to the world. You need to manually call .apply(world) on the SystemState, to apply them.

**Comment by zeroacez** [comment]
Sorry I haven't been very active recently. I was wondering if you just want me to add this line to the documentation of ``SystemState`` or if there is something more from #6184 that I should also consider?

**Comment by JoJoJet** [comment]
@zeroacez you can just make the doc changes, no need to worry about #6184.
