### ISSUE TITLE
Changing the `Viewport` of a camera doesn't update its projection

### ISSUE THREAD

**Issue by jakobhellermann** [bevyengine/bevy#5944]
## Bevy version

_main_ (`6f2cc0b30e335f3084f7028498c0866279c78099`

## What you did

```rust
    cam.viewport = Some(Viewport {
        physical_position: UVec2::new(viewport_pos.x as u32, viewport_pos.y as u32),
        physical_size: UVec2::new(viewport_size.x as u32, viewport_size.y as u32),
        depth: 0.0..1.0,
    });
```

## What went wrong

The projection of the camera got messed up.

## Why does this happen?

The `Camera` maintains some computed values, like the projection matrix `Mat4` and the render target size.
This computed info is only updated if 1. the render target changed, 2. the camera got added or 3. the camera projection got changed.
Changing the viewport also changed the projection which isn't caught here.

https://github.com/bevyengine/bevy/blob/6f2cc0b30e335f3084f7028498c0866279c78099/crates/bevy_render/src/camera/camera.rs#L380-L392

## How to solve this

I can think of two solutions.
1. we add `|| camera.is_changed()`, relying on change detection.
This is overly sensitive as this would also return true if someone changed `is_active` or `priority`, or if someone mistakenly had a unused `deref_mut` somewhere.
2. keep track of the old viewport in the `computed_state`, and if `camera.viewport != camera.computed_state.old_viewport`, then update the projection. This is more reliable, but needs to store two `UVec2`s more in the camera (probably not a big deal).

**Comment by zicklag** [comment]
Just ran into this. For anybody who wants a workaround that works right now, just add this plugin to your game:

```rust
pub struct WorkaroundsPlugin;

impl Plugin for WorkaroundsPlugin {
    fn build(&self, app: &mut App) {
        app.add_system_to_stage(
            CoreStage::PostUpdate,
            update_camera_projection_when_camera_changes.before(CameraUpdateSystem),
        );
    }
}

/// Workaround for bevy not updating camera projection when viewport changes:
/// <https://github.com/bevyengine/bevy/issues/5944>
fn update_camera_projection_when_camera_changes(
    mut changed_cameras: Query<&mut OrthographicProjection, Changed<Camera>>,
) {
    // For every changed camera
    for mut projection in &mut changed_cameras {
        // Force a change to the projection in order to trigger a re-building of the camera
        // projection for the new viewport.
        projection.set_changed();
    }
}
```

And thanks for working on the fix @jakobhellermann!
