### ISSUE TITLE
Add a method on Timer to get the remaining time

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5963]
## What problem does this solve or what need does it fill?

Getting the remaining time is a natural operation, and particularly useful when working with cooldowns or countdowns.

## What solution would you like?

Add a `remaining()` method to [`Timer`](https://docs.rs/bevy/latest/bevy/time/struct.Timer.html).

**Comment by Sergi-Ferrez** [comment]
Working on this!
