### ISSUE TITLE
Hot reloading is broken in the post_processing example

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#5964]
## Bevy version

main

## What you did

- `cargo run --example post_processing`
- Update `custom_material_chromatic_aberration.wgsl`

## What went wrong

Shader did not reload

## Additional information

Shader examples should use the `AssetServerSettings` resource to ensure that hot reloading is setup in time for it to actually work.

These other examples are not broken, but we should probably also switch to using `AssetServerSettings` there to avoid leading people astray when they try to do this with a material shader.

```
./shader/shader_instancing.rs
./scene/scene.rs
```

**Comment by superdump** [comment]
In my opinion we should remove the watch for changes method. It’s racey and so unpredictable. Better to use the resource from the beginning, in my opinion.
