### ISSUE TITLE
Implement Serialize and Deserialize for gamepad events

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#5979]
## What problem does this solve or what need does it fill?

This is useful for input capture and playback of gamepad events, enabling automated testing and advanced input mocking.

## What solution would you like?

Derive `Serialize` and `Deserialize` for `GamepadEvent`, `GamepadEventRaw`, `Gamepad`, `GamepadButtonType` and `GamepadAxisType`.

## What alternative(s) have you considered?

Use Serde's https://serde.rs/remote-derive.html in an external crate.

## Additional context

This should also likely be done for `WindowEvent` upstream in `winit`, but that's likely blocked on https://github.com/rust-windowing/winit/issues/1387

**Comment by object71** [comment]
Gamepad seems to have this behind a feature called serialize `#[cfg_attr(feature = "serialize", derive(serde::Serialize, serde::Deserialize))]`. Do you want it implemented for the rest of the structs with the same feature?

**Comment by alice-i-cecile** [comment]
Ah right! I've made these exact mistake before...
