### ISSUE TITLE
Bundle Registering

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#60]
It should be possible to register Bundles the same way we currently register components. This would enable a number of things:

* ```app.register_bundle<MyBundle>()``` would be a nice shorthand for registering all components in the bundle
* It would allow us to use bundles in the scene system
* It would allow the editor to be aware of bundles / use them during scene construction

**Comment by alice-i-cecile** [comment]
#4154 proposes an alternate strategy for type registration.

#4072 discusses the levels of abstraction, and whether or not bundles are the right tool for the job.

**Comment by james7132** [comment]
This was added in a public facing way in #12573.

**Comment by MalekiRe** [comment]
Is this still desired with the move to Required Components?

**Comment by alice-i-cecile** [comment]
Being able to go from `Bundle` -> `Vec<ComponentId>` would maybe be nice for weird dynamic use cases, but I think that all of the other motivation here is irrelevant. Closing: dear reader, please open a new issue if you still care about this explaining why.
