### ISSUE TITLE
Sprite doens't show up when WindowDescriptor height and width are changed.

### ISSUE THREAD

**Issue by luiz734** [bevyengine/bevy#6003]
## Bevy version

0.8.1

## System Info
**System:** Pop!_OS 22.04 LTS

**AdapterInfo:** { name: "NVIDIA GeForce 940MX", vendor: 4318, device: 4941, device_type: DiscreteGpu, backend: Vulkan }

## What you did
```
// main.rs
use bevy::prelude::*;

fn main() {
    App::new()
        .insert_resource(WindowDescriptor {
            width: 500.0,
            height: 500.0,
            ..default()
        })
        .add_startup_system(setup_system)
        .add_plugins(DefaultPlugins)
        .run();
}

fn setup_system(mut commands: Commands) {
    commands.spawn_bundle(Camera2dBundle::default());
    // example from examples/2d/shapes.rs
    commands.spawn_bundle(SpriteBundle {
        sprite: Sprite {
            color: Color::rgb(0.25, 0.25, 0.75),
            custom_size: Some(Vec2::new(50.0, 100.0)),
            ..default()
        },
        ..default()
    });
}
```

## What went wrong
- **Most of the time** the rectangle doesn't show up.
- **Sometimes** it appears, but grayed out.
- **Sometimes** it shows as it should (very rarely).

I've already tried changing the z property of `Transform.translate` but it didn't work.

When I leave the width or height as default or greater then 600 it works normally.

## Additional information
```
// Cargo.toml
[dependencies]
bevy = { version = "0.8.1", features = ["dynamic"] }

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
```

**Comment by bjorn3** [comment]
WindowDescriptor describes how the initial window is created. After that it will be ignored. You need WindowCommands to change window properties.

**Comment by luiz734** [comment]
Do you mean using `ResMut<Windows>`? I **can** change the width and height. When the app runs with the code I've shown the window is resized to 500x500 but the sprite doesn't appear. As as said, this happens at 500x500, but not at 600x600 or higher. At some point between this values the sprite starts to appear.

I tried removing the WindowDescriptor and adding the following to the `setup_system`:
```
    let window = windows.get_primary_mut().unwrap();
    window.set_title("foo".to_string());
    window.set_resolution(500., 500.);
```
- The title changed as expected
- The resolution hasn't changed
- The sprites appear normally

Maybe I am missing something?
