### ISSUE TITLE
Restrict trait bound on `F` generic in query filters to `ReadOnlyWorldQuery`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6005]
This is an interesting bound; we don't require `ReadOnlyWorldQuery` on the `F` in `Query<Q, F>`. Perhaps we should though?

_Originally posted by @alice-i-cecile in https://github.com/bevyengine/bevy/pull/6004#discussion_r973628162_

Query filters cannot mutate data (by definition); as a result we can strengthen the trait bound on the appropriate generics from `WorldQuery` to `ReadOnlyWorldQuery`.

This better communicates how these generics are supposed to be used, and catches mistakes that are likely to be user error at compile time.

**Comment by alice-i-cecile** [comment]
@BoxyUwU, I'd like your tak here.

For anyone considering tackling this, this should be super easy from an implementation perspective. Just make sure to hit `QueryState` too!

**Comment by BoxyUwU** [comment]
seems reasonable to me

**Comment by james7132** [comment]
Should be addressed as of #6008
