### ISSUE TITLE
Make bevy_window and bevy_input events serializable

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6021]
## What problem does this solve or what need does it fill?

All of the events in [this file](https://github.dev/bevyengine/bevy/blob/b6efe0f318b93330376cd44849281e919eec4a53/crates/bevy_window/src/event.rs#L91) should be serializable, in order to enable effective playback of window events for testing.

Similarly, many events in `bevy_input` are not serializable.

## What solution would you like?

Add derives for `Serialize` and `Deserialize`, controlled by an off-by-default feature flag.

**Comment by emersonmx** [comment]
Hello.
I started to see this issue, but I can't tell what should be serialized or not in `bevy_input`.
I found [this too](https://github.com/bevyengine/bevy/blob/37860a09de897218e6698eaf16dcc7836525a9fb/crates/bevy_input/src/touch.rs#L30), but I don't know if I need to put it in all struct of `touch.rs` or if only in those that are commented out as an event. Example: `A touch input event`.

**Comment by alice-i-cecile** [comment]
Hmm, good question. WRT touch data, it's hard to say, as I haven't experimented with Bevy on touch devices yet. For my purposes, I think `TouchInput` is the only critical one.

**Comment by alice-i-cecile** [comment]
Reopening so we can tackle touch input events too.

**Comment by emersonmx** [comment]
Hello again 👋🏻 
The only places I could find to put "serialize" were TouchInput and ForceTouch.
