### ISSUE TITLE
Events in bevy_window and bevy_input should implement PartialEq

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6024]
# What problem does this solve or what need does it fill?

These types can be compared by value, and this functionality is essential for tests.

## What solution would you like?

Derive PartialEq.

## Additional context

Sibling to #6021 and #6022. If you notice anything else dumb that's missing (like `Debug`) please just impl it too 🙃

**Comment by targrub** [comment]
How about `Hash`?

**Comment by alice-i-cecile** [comment]
Nah, I don't think there's much use for it.
