### ISSUE TITLE
Add `resource_scope` variant for nonsend resources

### ISSUE THREAD

**Issue by jakobhellermann** [bevyengine/bevy#6037]
## What problem does this solve or what need does it fill?

Bevy has a `resource_scope` method which lets you have mutable access to a resource and the world at the same time by temporarily removing the resource:
```rust
world.resource_scope(|world, mut a: Mut<A>| {
    let b = world.get_mut::<B>(entity).unwrap();
    a.0 += b.0;
});
```
Is is roughly equivalent to 
```rust
let a = world.remove_resource::<A>();
f(world, b);
world.insert_resource(a);
```

Bevy also has the concept of non-send resources; resources which do not implement the `Send` auto trait (and `Sync`?) so any systems that access them are only scheduled on the main thread. This is useful for example for some scripting language runtimes or OS operations that can only run on one thread.

There is, however, no variant of `resource_scope` which works for nonsend resources.

## What solution would you like?

Add a `non_send_resource_scope` function, which is pretty much a copy of `resource_scope` (https://github.com/bevyengine/bevy/blob/bc863cec4d046cc69f58e7325a996ccb7a910f3f/crates/bevy_ecs/src/world/mod.rs#L1087) but relaxes the `R: Resource` bound to `R: 'static`.
The method also needs to validate that it is being run on the main thread, https://github.com/bevyengine/bevy/issues/6037#issuecomment-1253523688.

## What alternative(s) have you considered?

Write
```rust
let runtime = world.remove_non_send_resource::<JsRuntime>().unwrap();
f(runtime, world);
world.insert_non_send_resource(runtime);
```
instead. Less ergonomic and a tiny bit less performant.

**Comment by DJMcNab** [comment]
In theory, `resource_scope` should just work for `NonSend` resources - there's no part of that API which requires the type be `Send` - if you have an `&mut World`, you're already on the main thread (at least in theory, in practise that's not necessarily true, but we have enough information to panic in those cases).

**Comment by DJMcNab** [comment]
We store whether a resource is registered as `non_send` though? So we read that field to validate?

**Comment by Pietrek14** [comment]
I would like to try it, since noone is assigned.
