### ISSUE TITLE
Gltf Examples have inconsitent behavior for rendering gltf

### ISSUE THREAD

**Issue by rctrj** [bevyengine/bevy#6043]
## Bevy version
Cloned from github, currently on `d1e5c507614e7c5da51349bc72c898a2ce9232be`

## \[Optional\] Relevant system information
- Windows 11 Pro
- cargo 1.63.0 (fd9c4297c 2022-07-01)
- AdapterInfo { name: "NVIDIA GeForce RTX 2070 SUPER", vendor: 4318, device: 7812, device_type: DiscreteGpu, backend: Vulkan }

## What you did

1. Run the example [load_gltf](https://github.com/bevyengine/bevy/blob/main/examples/3d/load_gltf.rs) with a custom GLTF exported from Blender
2. Run the example [scene_viewer](https://github.com/bevyengine/bevy/blob/main/examples/tools/scene_viewer.rs) with the same model

### Expected
Both the examples should render the model
### Found
- Model is visible in `scene_viewer`
- Model is not visible in `load_gltf`

## Additional information

I have tested the model with various other sources: 
- [This](https://gltf-viewer.donmccurdy.com/) online viewer
- Using [this](https://github.com/BVE-Reborn/rend3/tree/trunk/examples/static-gltf) example of rend3 crate which also uses wgpu (I had to comment the tangents part here as the model doesn't contain tangents)

Model seems to be rendering properly in these

### Screenshots
From `load_gltf`
![load_gltf](https://user-images.githubusercontent.com/21234957/191440427-c8fcaa4f-4126-4370-bda9-d7e3a707acf5.png)

From `scene_viewer`
![scene_viewer](https://user-images.githubusercontent.com/21234957/191440521-5e62d47e-79df-45ca-bed5-5bddff4e06d1.png)

### Changes
Only the paths of the models were changed in both examples.

In `load_gltf`
```
commands.spawn_bundle(SceneBundle {
        scene: asset_server.load("demo/house03.gltf#Scene0"),
        ..default()
    });
```

In `scene_viewer`: 
```
 let scene_path = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "assets/demo/house03.gltf".to_string());
```

### Model info
I cannot share the model as it falls under a commercial license that prohibits sharing the model.
Model was exported by keeping textures outside the GLTF : `.bin + .gltf + textures`.

### Troubleshoot
Disclaimer that I'm pretty new to rust and bevy
I tried to find the cause but couldn't pinpoint it. I believe the issue should be somewhere in `GltfLoader`.
 I can try to find a solution if someone can point me in the right direction.

**Comment by mockersf** [comment]
Example `load_gltf` is a basic example that just loads the file and displays it.

`scene_viewer` tries to be a little more clever and has a better camera. In this case, the important point is that it will compute the size of the model, and move the camera to make sure it is completely visible.

The `load_gltf` camera may be looking inside the house, or too far away, or just not in the right direction

**Comment by rctrj** [comment]
Hi @mockersf 
I've considered that case and have tried to change the scale and position of items for the same. I've also played with the camera `position` and `look_at` for the same. Other models (of similar size in blender) are working fine.

I'll try to integrate the camera used in `scene_viewer` to the `load_gltf` example and see if I missed something earlier.

**Comment by mockersf** [comment]
You can try putting debug print for the values at https://github.com/bevyengine/bevy/blob/2eb9dd9dd9ae88c8adaf39bf7159b6832fd4e98f/examples/tools/scene_viewer.rs#L246-L249

That will show you the camera used in `scene_viewer`

**Comment by rctrj** [comment]
Thanks for the help. 
It was an issue with the position. Gltf has provided the translation value which I missed, and that's why I had this issue. Setting the translation in the gltf fixed it.

Closing this, as it's not an issue with bevy
