### ISSUE TITLE
`Entity`'s “ID” should be named “index” instead

### ISSUE THREAD

**Issue by Nilirad** [bevyengine/bevy#6059]
In Bevy ECS, an `Entity` is just an identifier (ID for short) that is implemented as a generational index: a data structure containing both an index and a generation.

There is a problem however: the entity's index is actually called “ID”, both in documentation and in the APIs.

## How can Bevy's documentation be improved?

The solution would be to change all incorrect occurrences of “ID” to “index”.

[`Entity`] seems to be the only item that needs to be fixed. In particular:
- struct level documentation
- `id` struct field
- `id` method and its documentation

`EntityCommands::id` and `EntityMut::id` are correct, they must not be changed.

**Remember to add the `C-Breaking-Change` label to your PR.**

[`Entity`]: https://dev-docs.bevyengine.org/bevy/ecs/entity/struct.Entity.html

**Comment by Edwox** [comment]
Hi! I have never contributed before, but I would like to try and solve this issue.

**Comment by Nilirad** [comment]
@Edwox Great, go for it!

**Comment by cart** [comment]
I'm on board for this (scoped to the Entity internals). `index` makes more sense in this context.

**Comment by Edwox** [comment]
@Nilirad could you clarify what you mean by "struct level of documentation"? 
Do you mean the documentation for the ``Entity`` struct?

**Comment by Nilirad** [comment]
@Edwox Yes, the struct-level documentation is about the struct itself. In practical terms, in the source code file, it's the docstring directly above the struct definition.
