### ISSUE TITLE
Links on bevy crate page for `render` module are incorrect

### ISSUE THREAD

**Issue by targrub** [bevyengine/bevy#6062]
## How can Bevy's documentation be improved?

On https://docs.rs/bevy/latest/bevy/, under the `render` module, the description contains several links:

> Use [RenderDevice::features](https://docs.rs/bevy/latest/bevy/bevy_render::renderer::RenderDevice::features), [RenderDevice::limits](https://docs.rs/bevy/latest/bevy/bevy_render::renderer::RenderDevice::limits), and the [WgpuAdapterInfo](https://docs.rs/bevy/latest/bevy/bevy_render::render_resource::WgpuAdapterInfo) resource

Those links go to a page saying each of those resources don't exist.

They should either not be links, or go to the appropriate pages.
I think those might be these pages:
https://docs.rs/bevy/latest/bevy/render/renderer/struct.RenderDevice.html#method.features
https://docs.rs/bevy/latest/bevy/render/renderer/struct.RenderDevice.html#method.limits
https://docs.rs/bevy/latest/bevy/render/render_resource/struct.WgpuAdapterInfo.html

**Comment by Lucidus115** [comment]
Hello! I'd like to try fixing this one if that's okay
