### ISSUE TITLE
Rust 1.64 broke CI

### ISSUE THREAD

**Issue by Nilirad** [bevyengine/bevy#6063]
See [this log] for a CI error example.

This clippy error is probably caused by an improvement of the [`unnecessary_lazy_evaluations`] lint.

[this log]: https://github.com/bevyengine/bevy/actions/runs/3106389044/jobs/5033205274
[`unnecessary_lazy_evaluations`]: https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#suggestion-fixesimprovements

**Comment by targrub** [comment]
I'll grab this one.

**Comment by targrub** [comment]
What is the process by which the project upgrades to new tool versions (in this case, Rust 1.64)?

**Comment by harudagondi** [comment]
updating the toolchain?

**Comment by targrub** [comment]
What I mean is, in my experience, tools should be upgraded manually, after the fixes required for them have been committed on a branch.

**Comment by mockersf** [comment]
We always install the latest stable version of Rust. We prefer the optional PR to fix new lints on new version rather than the mandatory PR to update on new version.

**Comment by mockersf** [comment]
Installing latest stable is done with https://github.com/bevyengine/bevy/blob/dc5836f5b73e10a65285cb92d4e2c688138211df/.github/workflows/ci.yml#L58-L62
