### ISSUE TITLE
Delay when dragging the created window on macos.

### ISSUE THREAD

**Issue by senicko** [bevyengine/bevy#6075]
At first I want to say that there is high chance that I am doing something wrong. I don't have much experience with rust / gamedev.

## Bevy version

0.8.1

## Relevant system information

OS macOS Monterey 12.5.1

MacBook Pro (16-inch, 2019)
Processor `2,3 GHz 8-Core Intel Core i9`

Graphics 
- `AMD Radeon Pro 5500M 4 GB`
- `Intel UHD Graphics 630 1536 MB`

Rust
`cargo 1.62.1 (a748cf5a3 2022-06-08)`

AdapterIinfo
`AdapterInfo { name: "AMD Radeon Pro 5500M", vendor: 0, device: 0, device_type: DiscreteGpu, backend: Metal }`

## What you did

I wrote a simple bevy app, that just creates a window (with all of the default plugins)
```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run();
}

```

## What went wrong

When I drag the window it does not move instantly. There is over a second of delay after which the window jumps back to the cursor and moves smoothly.

This happens every time when I want to move the window.

https://user-images.githubusercontent.com/25861704/191930752-e07c3fad-b9a8-468e-abc2-82a534689f47.mov

**Comment by bjorn3** [comment]
Did you compile in release mode? How much cpu usagr is there? If you add a button, does it have the same delay when clicking on this button? I believe on macOS window decoration and by extension dragging (or at least signaling that window dragging should happen) is handled by the program itself, so if the program is overloaded, it may take a while to respond.

**Comment by senicko** [comment]
It is empty bevy project. Code I provided is all I have. Only bevy as a dependency.

Cpu usage goes CRAZYYYY when I minimize the app. iStat Menus says that the process takes 241%. But there is an issue about this already I believe.

Regarding buttons delay, I will check this later today (It is 12:50pm now where I live), because now I have some work to do. I will also try to create a window with winit to check if i's the same.

**Comment by senicko** [comment]
Okay I've made a quick app with button in it. I can't notice any lag (for sure not a second lag or sth, which could cause window to jump like that).

**Comment by senicko** [comment]
Okay also created an empty window with winit, and everything works as expected. There is no lag wen moving it. 

I was writing about extremely high CPU usage when I minimized the bevy app, but now when I run the app with button inside everything works fine (CPU usage is very low, about 5%).

Lag when moving the window still exists though. That's my code:
<https://gist.github.com/senicko/5a0971c628731b6ab57db9c7afc9d5ab>

**Comment by senicko** [comment]
Just played with breakout example, and it is laggy. Like controls and everything have a noticable delay / lag / slide. :(

**Comment by mockersf** [comment]
I don't notice any lag when dragging the window on an m1 mac

**Comment by senicko** [comment]
Oh wow,
I was browsing issues related to lags, and in one of them (#5778) the issue was caused by magnet app (window management utility app for macos). Well I am using it, and after turning it off everything works fine!!!!!! There is no lag when moving the window. Thanks a lot and have a nice day!

**Comment by Zajozor** [comment]
Just came to say that using [BetterTouchTool](https://folivora.ai) on MacOS/M1/Ventura had the same effect for me as described/on the video.
Turning BetterTouchTool off made any lag go away.

It's quite unfortunate though as I use it for a bunch of shortcuts and window snapping.
Any ideas on what to explore to get around this ?

**Comment by bjorn3** [comment]
I would suggest asking the developers at https://community.folivora.ai/.
