### ISSUE TITLE
Remove or rename `UiColor`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6078]
This indirection seemingly buys us very little, at cost of verbosity, duplication and friction.

We should remove `UiColor` completely, and just use `Color` in its place.

**Comment by mockersf** [comment]
This would mean making `Color` a component, even though it's a basic type without a meaning by itself

**Comment by alice-i-cecile** [comment]
Fair. I would strongly prefer `Fill(Color)` instead, which avoids the problem you raise while much more clearly declaring intent.

**Comment by Nilirad** [comment]
> Fair. I would strongly prefer `Fill(Color)` instead, which avoids the problem you raise while much more clearly declaring intent.

Seems the right choice, we could even add alternatives like `Gradient(Color, Color)` and similar...
