### ISSUE TITLE
Add utility methods to `Val`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6080]
## What problem does this solve or what need does it fill?

The [`Val`](https://docs.rs/bevy/latest/bevy/prelude/enum.Val.html) type is an expressive way to represent UI scales across unit types.

However, working with these values can be quite frustrating; basic utility methods are missing.

## What solution would you like?

1. Add `try_add` and `try_sub` methods to `Val`, which only return Ok if the enum variants are identical.
2. Remove the `Add` and `AddAssign` impls for `Val`.
3. Add `evaluate(size: f32)` method that converts from `Val::Percent` to `Val::Px`.
4. Add `try_add_with_size` and `try_sub_with_size` methods to `Val`, which evaluate `Val::Percent` values into `Val::Px` values before adding.

## What alternative(s) have you considered?

We could implement the `Add` and `Sub` traits (and already implement the `Add` trait).

However, this results in some fairly tricky implicit behavior. For example, what happens when we add `Val::Undefined` to `Val::Auto`? This implicit introduction of `NaN`-like behavior can be very frustrating to debug.

**Comment by mockersf** [comment]
previous try in #5525 / #5555

**Comment by Pietrek14** [comment]
I'll try to implement this.

**Comment by Pietrek14** [comment]
When adding or subtracting non-numeric variants, like `Undefined`, should it return the same variant or an error?

**Comment by alice-i-cecile** [comment]
I think the same variant should be fine.
