### ISSUE TITLE
Bevy `0.8` and Nightly Rust : No `OrthoGraphicCameraBundle` in `camera`

### ISSUE THREAD

**Issue by stanley355** [bevyengine/bevy#6085]
## Bevy version
0,8

## \[Optional\] Relevant system information
Rust version:  `rustc 1.66.0-nightly (2019147c5 2022-09-19)`
OS: Debian 11

```
[dependencies]
bevy = { version = "0.8.0", features = ["dynamic"] }
bevy-inspector-egui = "0.13.0"
bevy_mod_debugdump = "0.5.0"
bevy_prototype_debug_lines = "0.8.1"
```

```ignore
`AdapterInfo { name: "NVIDIA GeForce RTX 2070", vendor: 4318, device: 7938, device_type: DiscreteGpu, backend: Vulkan }`
```

## What you did
I'm building a 2d game, setup the games following the one on official bevy book: https://bevyengine.org/learn/book/getting-started/setup/ .
I want to add `bevy::render::camera::OrthoGraphicCameraBundle` as my camera and I've imported it on my module, however I encounter the following strange issue :
```
use bevy::render::camera::OrthoGraphicCameraBundle;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `OrthoGraphicCameraBundle` in `camera`
```
I noticed some games built with bevy `0.7` can work with it, is it the issue with bevy `0.8` or is it due to my nightly compiler ? 
Thanks

## Additional information
This is the link to my game project: https://github.com/stanley355/bevies/tree/bevy/ortocamera-issue

**Comment by harudagondi** [comment]
`OrthographicCameraBundle::new_2d` is now `Camera2dBundle::default()`. See the migration guide for [0.7 -> 0.8](https://bevyengine.org/learn/book/migration-guides/0.7-0.8/#camera-driven-rendering).

**Comment by DJMcNab** [comment]
Where in the book did you find a reference to `OrthographicCameraBundle`? Doing a <kbd>ctrl-f</kbd> on each page of the book failed to find anything for "ortho".

Is something broken with GitHub pages that it's showing an outdated version of the book to some users?

**Comment by stanley355** [comment]
Ah I see thanks for answering @harudagondi
