### ISSUE TITLE
Random silent crashes possibly related to ScheduleRunnerPlugin 

### ISSUE THREAD

**Issue by ashneverdawn** [bevyengine/bevy#609]
I have this weird issue where bevy will randomly crash silently.
The issue tends to happen sooner the higher the framerate is set to.

```
use bevy::{app::ScheduleRunnerPlugin, prelude::*};
use std::time::{Duration, Instant};

fn main() {
  App::build()
    .add_plugin(ScheduleRunnerPlugin::run_loop(Duration::from_secs_f64(1.0 / 120.0)))
    .add_resource(Timer(Instant::now(), 0))
    .add_system(bevy_update.system())
    .run();
  println!("bevy shutdown unexpectedly!");
}
pub struct Timer(Instant, u64);
pub fn bevy_update(mut timer: ResMut<Timer>) {
  let elapsed = Instant::now().duration_since(timer.0).as_secs();
  if elapsed != timer.1 && elapsed % 3 == 0 {
    timer.1 = elapsed;
    println!("seconds elapsed: {}", elapsed);
  }
}
```

Tested on master:
at 240fps, I get it 1-5 secs in.
at 120fps, 10-30 secs in.
at 60fps, 30-60 secs in.
at 30fps, it happened 255 secs in.

This was tested on an old 2014 macbook pro, so if you're on a more recent machine, you may have to up the framerate to successfully reproduce it in a timely manner.

Note: What I refer to as "framerate" is from this line: 
```
    .add_plugin(ScheduleRunnerPlugin::run_loop(Duration::from_secs_f64(1.0 / 120.0)))
```

**Comment by DJMcNab** [comment]
Instant is not guaranteed to be monotonic, so my first guess is that `duration_since` is panicing

**Comment by DJMcNab** [comment]
I've got it
If your tick takes longer than the wait duration, the schedule runner exits, because the exit condition of `tick` doesn't determine between no wait and app exit requested, which is clearly wrong.

https://github.com/bevyengine/bevy/blob/408114269b36cbc088dc9b3a0a58ba8acba21acf/crates/bevy_app/src/schedule_runner.rs#L97
