### ISSUE TITLE
Implement `Mul<Aabb>` for `Transform`, or put a method on `Aabb` that allows application of a `Transform`

### ISSUE THREAD

**Issue by bzm3r** [bevyengine/bevy#6090]
## What problem does this solve or what need does it fill?

One probably wants to store a "default" [AABB](https://docs.rs/bevy/latest/bevy/render/primitives/struct.Aabb.html) for all instances of a given object. However, these AABBs will then want to be updated based on any transforms applied to the object. There is no nice way to do this currently.

## What solution would you like?

Implement `Mul<Aabb>` for `Transform`, or put a method on `Aabb` that applies application of a `Transform`.

I think the solution would have some form like this:
```rust
/// Apply a [`Transform`] to an [`Aabb`].
///
/// Workaround for: https://github.com/bevyengine/bevy/issues/6090
pub fn apply_transform_to_aabb(transform: Transform, aabb: Aabb) -> Aabb {
    let center = (transform * Vec3::from(aabb.center)).into();

    let half_x = Vec3::new(aabb.half_extents.x, 0.0, 0.0);
    let half_y = Vec3::new(0.0, aabb.half_extents.y, 0.0);
    let half_z = Vec3::new(0.0, 0.0, aabb.half_extents.z);
    // We only need to scale and rotate the half-extents; they should not be translated.
    let scale_and_rotate = transform.rotation * transform.scale;
    let hx = scale_and_rotate * half_x;
    let hy = scale_and_rotate * half_y;
    let hz = scale_and_rotate * half_z;
    let half_extents = Vec3A::new(
        hx.x.max(hy.x.max(hz.x)),
        hx.y.max(hy.y.max(hz.y)),
        hx.z.max(hy.z.max(hz.z)),
    );

    Aabb {
        center,
        half_extents,
    }
}
```

## What alternative(s) have you considered?

The user should just individually multiply the `center` and `half_extents` of an `Aabb` by a `Transform`, and then create a new `Aabb` out of the transformed `center` and `half_extents`. This seems like unnecessary duplicated work wherever such transform application is needed.

## Additional context

This is currently coming up `bevy_ecs_tilemap`, where we want to carry around un-transformed `Aabb`s of tilemap chunks, and then in the render preparation phase, we'd like to cull the `Aabb`'s of a render chunk (*transformed by whatever transforms are acting on the render chunk*) by checking to see if they intersect with the camera's frustum.

**Comment by superdump** [comment]
A mesh local aabb transformed to world space is then an obb in world space. The global transform should be used. The 3x3 part of the Affine3A contains the scale and rotation and the translation is stored in a separate vector.

Also there’s an algorithm used for 3d that avoids transforming multiple points which is then more efficient for plane-obb interaction given a plane normal and signed distance, and mesh local aabb and global transform.

**Comment by bzm3r** [comment]
@superdump I think I am thinking of transforming an `Aabb` so that the result is an `Aabb` too. We could have a separate method that returns an `Obb`, but it is possible to transform an `Aabb` so that the result is also an `Aaabb` (but it might be larger than the original `Aabb`).

**Comment by bzm3r** [comment]
It turns out this was not necessary, as the `intersects_obb` function simply takes the transform to be applied to the AABB as input (that is what `model_to_world` is).
