### ISSUE TITLE
Entities are invisible when spawned as child via add_child()

### ISSUE THREAD

**Issue by svenallers** [bevyengine/bevy#6105]
## Bevy version

0.8.1 (I also tested on master branch (39467e30fdb967cb57ac41bc116a090e748ded3a) and did have the sam issue)

## \[Optional\] Relevant system information

Rust version: 1.64.0
OS: Windows 11 & Mac OS Monterey 12.6

```ignore
AdapterInfo { name: "AMD Radeon Pro 5300M", vendor: 0, device: 0, device_type: DiscreteGpu, backend: Metal }
```
I tested it on an Nvidia RTX 3070ti with Vulkan as the backend as well and did have the same issue.

## What you did

I tried to spawn an entity as a child of another entity but it was not visible. After downgrading to `0.7.0` everything went fine. Thus I assume that this is a regression introduced with `0.8`.

The code to reproduce:
```rust
use bevy::prelude::*;

const RECT_SIZE: f32 = 16.0;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(spawn_camera)
        .add_startup_system(spawn_as_child)
        .run();
}

fn spawn_camera(mut commands: Commands) {
    commands.spawn_bundle(Camera2dBundle::default()); // use OrthographicCameraBundle::new_2d() in 0.7.0
}

fn spawn_as_child(mut commands: Commands) {
    let rect_entity = commands
        .spawn_bundle(SpriteBundle {
            sprite: Sprite {
                color: Color::RED,
                custom_size: Some(Vec2::splat(RECT_SIZE)),
                ..Default::default()
            },
            ..Default::default()
        })
        .insert(Transform::default())
        .id();

    commands
        .spawn()
        .insert_bundle(TransformBundle::default())
        .add_child(rect_entity);
}
```

## What went wrong

The sprite spawned is not visible in `0.8.1`:
<img width="1276" alt="0 8 1" src="https://user-images.githubusercontent.com/7449886/192269755-8e78d7d7-ef6a-4c11-ad65-553f47f86909.png">

I expected to see a red rectangle as you do in version `0.7.0`:
<img width="1280" alt="0 7 0" src="https://user-images.githubusercontent.com/7449886/192269877-97321e63-51ec-4e32-93df-99fc769e1152.png">

**Comment by DJMcNab** [comment]
I think the parent needs to have a Visibility component

**Comment by nicopap** [comment]
Should be fixed by #5590
To fix this, do this:
```rust
// replace this line when spawning the parent entity
         .insert_bundle(TransformBundle::default())
// by the following line
         .insert_bundle(SpatialBundle::default())
```

**Comment by svenallers** [comment]
Thanks, you saved my day 🙂  Using `SpatialBundle` worked. This issue was driving me nuts yesterday. I did try using the `Visibility` component before already but it did not work. I did not know about the `ComputedVisibility` component.

**Comment by nicopap** [comment]
> This issue was driving me nuts yesterday.

Don't worry, you are not the only one. I've counted a dozen people that got very frustrated by that. (including me, twice) I'm glad the warning message will make it to 0.9.0
