### ISSUE TITLE
Make `Window` and `Windows` structs easier to test with

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6106]
Writing tests for these types is quite challenging.

We should have:

1. Constant constructors wherever possible.
2. Doc tests demonstrating simple testing practices (likely using the `Default` struct update syntax for `WindowDescriptor`.
3. A `const fn new` method on `Windows` that accepts a single `Window`.

**Comment by alice-i-cecile** [comment]
The sticking point is the `RawWindowHandle` type: we cannot reasonably construct this in tests. IMO this should be optional in order to enable headless testing of various utility methods.

**Comment by targrub** [comment]
I'm taking a look at tackling this.
