### ISSUE TITLE
Audio channels are sometimes reversed

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#6122]
## Bevy version

main, 0.8.1

## Relevant system information

macOS 12.6
Macbook Pro (M1 Max)

## What you did

Modified the audio example to play this sound:

[RL.zip](https://github.com/bevyengine/bevy/files/9669090/RL.zip)

<img width="720" alt="image" src="https://user-images.githubusercontent.com/200550/192894035-42b3f784-2656-46fe-8446-1d662583029e.png">

```
cargo run --example audio --release
```

## What went wrong

This audio file consists of some tones alternating from right->left->right->left.

However, when played with bevy, I hear left->right->left->right

This behavior is not consistent. Without `--release`, the audio plays in the correct channels.

**Comment by rparrett** [comment]
It seems likely that this is an issue upstream with rodio or cpal.

I found the same behavior in a rodio example. https://github.com/RustAudio/rodio/issues/444

But some naive attempts in cpal didn't produce the same behavior.

**Comment by alice-i-cecile** [comment]
Interesting: this was discovered in #6028. Apparently it's a pre-existing issue.
