### ISSUE TITLE
GTLF animations only work with keyboard when in the same system

### ISSUE THREAD

**Issue by LarsDu** [bevyengine/bevy#6139]
## Bevy version

"0.8.1"

The release number or commit hash of the version you're using.
Should be `latest`

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`): `1.63.0`
  - Bevy relies on the "latest stable release" of Rust
  - nightly should generally work, but there are sometimes regressions: please let us know!
- the operating system or browser used, including its version `Mac OSX 12.5.1 Monterey`

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

- [`wgpu`](https://github.com/gfx-rs/wgpu) for rendering problems
- [`winit`](https://github.com/rust-windowing/winit) for input and window management
- [`gilrs`](https://docs.rs/gilrs/latest/gilrs/) for gamepad inputs

## What you did

Describe how you arrived at the problem. If you can, consider providing a code snippet or link.

## What went wrong

If it's not clear, break this out into:

I've provided a [minimal working example here](https://github.com/LarsDu/bevy_animation_bug)

- what were you expecting? It should be possible to separate keyboard input logic from animation triggering into separate systems to separate concerns and decouple animation from player input. 

- what actually happened?
Instead, animation in response to player input only works when everything is in the same system (function)## Additional information

Other information that can be used to further reproduce or isolate the problem.

Theory: I think there is some sort of synchronization issue with the way bevy handles keyboard inputs.

**Comment by mockersf** [comment]
Your system `set_animation_direction` is starting to play an animation at every frame. So the animations are never played, and always restarted.

You could check that `movement` was actually changed in that system before starting an animation, for example with `movement.is_changed()`

**Comment by LarsDu** [comment]
Yep this is correct. I'll cancel this report
