### ISSUE TITLE
Add a test fly camera

### ISSUE THREAD

**Issue by coffee-is-power** [bevyengine/bevy#6141]
## What problem does this solve or what need does it fill?
This would be useful for 3d games to see the objects before you code the movement system, you're maybe you're just testing something and you don't want to implement a whole fly camera from scratch

## What solution would you like?

Add a built-in fly camera plugin on the engine

## Additional context
There's a crate called [bevy_fly_camera](https://crates.io/crates/bevy_fly_camera), but it doesn't seem very active and it aged like milk, the bevy version is kinda old and the documentation is outdated, some bevy apis have been renamed, so if we include this in bevy, it would a lot easier for developers to just get up and running with a test 3d program/game

**Comment by mockersf** [comment]
There is one in an example: https://github.com/bevyengine/bevy/blob/main/examples/tools/scene_viewer.rs

There are also a few other plugins available, you can find them at https://bevyengine.org/assets/. For example [bevy_pancam](https://github.com/johanhelsing/bevy_pancam), [smooth-bevy-cameras](https://github.com/bonsairobo/smooth-bevy-cameras) or [bevy_flycam](https://github.com/sburris0/bevy_flycam) seem to be updated for Bevy 0.8

Before adding one officially in Bevy, there would need to be a discussion on the API...

**Comment by DGriffin91** [comment]
There's also this PR: https://github.com/bevyengine/bevy/pull/4458/

**Comment by coffee-is-power** [comment]
@mockersf but I proposed to add to the bevy game engine, not create a plugin or a crate

**Comment by coffee-is-power** [comment]
There could be a TestFlyCamera bundle that is the same as a normal 3d camera but it can be controlled using the mouse and keyboard.
