### ISSUE TITLE
Fully serialize entities

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#6143]
## What problem does this solve or what need does it fill?

Currently for entities we serialize only `id`:
https://github.com/bevyengine/bevy/blob/b995b4662a9481e8d6fd984b2d2fd02e1c2d1a5d/crates/bevy_ecs/src/entity/serde.rs#L9
But this is not very expected behavior. For example, if you serialize an entity, send it over the network, and map it to an entity on another machine, this will not work correctly, because [generation](https://docs.rs/bevy/latest/bevy/ecs/entity/struct.Entity.html#method.generation) is skipped for serialization.

## What solution would you like?

Fully serialize entities. It may only be redundant for scenes, but Bevy use [DynamicEntity](https://docs.rs/bevy/latest/bevy/scene/struct.DynamicEntity.html) for them anyway.

**Comment by alice-i-cecile** [comment]
From what I've heard from @cart, this is a deliberate decision. Entity identifiers are intended to be opaque, and should not be used for serialization over the network. This is because other incidental entities (such as UI elements or particles) may be spawned, taking up the entity identifier you were planning to use.

Instead, the suggested solution is to use a secondary identifier for network synchronization.

**Comment by Shatur** [comment]
> Entity identifiers are intended to be opaque, and should not be used for serialization over the network. This is because other incidental entities (such as UI elements or particles) may be spawned, taking up the entity identifier you were planning to use.

No, no, it's not for reusing the same entities. It is needed for mapping.
When the server sends its state, it contains entities and components. On the client, I create new objects and map them (using `EntityMap`) to those received from the server (to know which one matches which). And `generation` field is missing, this mapping can be broken.

**Comment by alice-i-cecile** [comment]
Ah, okay! I've seen a lot of people trying to reuse identifiers, so I was a bit suspicious. I'm okay with this change now that you've explained the pattern you're using now; feel free to open a PR.

**Comment by james7132** [comment]
I'm curious why a secondary index (i.e. a `NetworkIdentity`/`NetworkId`) is insufficient here. Both `bevy_backroll` and `bevy_ggrs` utilize a secondary and network-wide unique identifier that is handled separately from how the ECS world ID's entities, which makes the ID assignment deterministic and isolated from the rest of the engine.

**Comment by Shatur** [comment]
It's simpler. This way I do not need to handle uniqueness and I do not map back and forth. I just send server state as usual and client just maps server entity to its own entity.
Another use case for entity serialization is scenes, but Bevy already uses `DynamicEntity` for it. This is why I suggested this change. Also it simplifies the code :)
