### ISSUE TITLE
Using `SceneBundle` should not require specifying `#scene0`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6148]
## What problem does this solve or what need does it fill?

A user tried to do

```rust
    cmds.spawn_bundle(SceneBundle {
        scene: asset_server.load("tile.glb"),
        ..default()
    });
```

This silently failed.

Instead, you have to add:

```rust
    cmds.spawn_bundle(SceneBundle {
        scene: asset_server.load("tile.glb#scene0"),
        ..default()
    });
```

You can see this in practice in [this example](https://github.com/bevyengine/bevy/blob/01aedc8431cb218226cee866262e0ccfca00b3b3/examples/3d/update_gltf_scene.rs).

## What solution would you like?

When only one top-level entity exists, it should be used without having to specify a subpath.

## What alternative(s) have you considered?

Provide a warning rather than failing silently.

Document this behave on `SceneBundle`.

**Comment by mockersf** [comment]
Even when a gltf only has one scene, it still has other sub assets:
* meshes
* materials
* gltf meshes (a mesh and its associated material)
* animations
* skins

gltf files can also be used as a catalog of meshes, with a default scene that is actually useless, and all the meshes available directly

**Comment by alice-i-cecile** [comment]
If we're passing it into `SceneBundle` we presumably want to use the scene however? 

We should at least be validating that the supplied gltf file path does in fact lead to a scene, and warning the user if it doesn't.
