### ISSUE TITLE
Sending window events via the ECS doesn't update the corresponding fields on the `Window`.

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6163]
## Bevy version

0.8.1

## What you did

Sent a [`CursorMoved`](https://docs.rs/bevy/latest/bevy/window/struct.CursorMoved.html) event, or another event from `bevy_window`.

## What went wrong

The corresponding fields on the appropriate [`Window`](https://docs.rs/bevy/latest/bevy/window/struct.Window.html#method.set_cursor_position) were not updated.

## Additional information

This was discovered while attempting to get input playback working properly: https://github.com/Leafwing-Studios/leafwing_input_playback/issues/10

Users can workaround this by manually setting the appropriate fields: https://docs.rs/bevy/latest/bevy/window/struct.Window.html#method.set_cursor_position. While it would be nice to have #4530 to make this pattern easier, simply adding a set of systems that runs at the start of each frame, reads these events and then sets the corresponding window fields would probably be enough to fix this surprising behavior.

**Comment by DJMcNab** [comment]
To clarify, the correct way do this is to make your own custom runner which both updates the window fields and sends the events you need. That is, mock bevy_winit

**Comment by alice-i-cecile** [comment]
Alright, I've managed to get this working without upstream changes. #4537 will make the strategy proposed by @DJMcNab much less painful.
