### ISSUE TITLE
Reduce code duplication in gamepad_viewer example

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6164]
This example involves spawning and configuring a very large number of similar buttons, as seen in https://github.com/bevyengine/bevy/blob/8a268129f9efbe0b35a53622e5ff59053ace457f/examples/tools/gamepad_viewer.rs#L119

We should instead be using a custom `Bundle` type, with a convenient `new` method to improve clarity and reduce boilerplate.

**Comment by polarvoid** [comment]
Hey, I'd love to take a jab at this one

**Comment by alice-i-cecile** [comment]
Awesome, feel free to open a draft PR and ask for any help there!

**Comment by polarvoid** [comment]
Done, I opened up a draft at #6175
