### ISSUE TITLE
Children do not render unless the parent has the components of SpatialBundle

### ISSUE THREAD

**Issue by ixru** [bevyengine/bevy#6188]
## Relevant system information

```ignore
`AdapterInfo { name: "AMD RADV SIENNA_CICHLID", vendor: 4098, device: 29631, device_type: DiscreteGpu, backend: Vulkan }`
```
## Description

While converting to 0.8 I got stuck on having to add a VisibilityBundle to parent entities for the children to render. Initially I thought this would be unnecessary as I did not want propagation. This is what the issue was originally going to be about, but while making the minimal repro, I notice that not only does the parent need VisibilityBundle, it also needs TransformBundle. 

I don't think this is the desired behaviour, propagation of both transform and visibility should be optional, as in the parent should not require the components of SpatialBundle. It is the expected behaviour I think, and makes cleaner code.
I don't know if it is a bug or as intended, but it works the same on 0.7(with only TransformBundle) so I can only assume.

```
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    commands.spawn_bundle(Camera3dBundle::default());
    commands
        .spawn()
        // None of these can be removed, don't want any of them.
        .insert_bundle(TransformBundle::default())
        .insert_bundle(VisibilityBundle::default())
        .with_children(|parent| {
            parent.spawn_bundle(PbrBundle {
                mesh: meshes.add(Mesh::from(shape::Icosphere::default())),
                material: materials.add(StandardMaterial {
                    base_color: Color::ALICE_BLUE,
                    ..default()
                }),
                transform: Transform::from_xyz(0.0, 0.0, -5.0),
                ..default()
            });
        });
}
```

**Comment by alice-i-cecile** [comment]
@cart I think we should revert this behaviour if possible. It's very hard to debug, inconsistent with transform inheritance and forces users to add components they don't care about.

**Comment by mockersf** [comment]
> It is the expected behaviour I think

Yup it is: https://bevyengine.org/news/bevy-0-8/#spatialbundle-and-visibilitybundle

@alice-i-cecile it's not really possible to revert without removing all visibility inheritance which works exactly like transform inheritance.
Requiring all entities in hierarchy to have the components is an optimisation strategy to not need querying over *all* entities

**Comment by alice-i-cecile** [comment]
> Requiring all entities in hierarchy to have the components is an optimisation strategy to not need querying over all entities

Ah, this was what I was missing. Unfortunate, but you've convinced me :( Closing this out, we can revisit when we get relations.
