### ISSUE TITLE
`OrthographicProjection`'s public fields are misleading

### ISSUE THREAD

**Issue by xgbwei** [bevyengine/bevy#6190]
## What problem does this solve or what need does it fill?

While working on #6177, I noticed some problems with `OrthographicProjection`'s public fields:
- `left`, `right`, `bottom`, and `top`, which are used to set the borders of the projection, are public, even though they'll be set automatically if `scaling_mode` is anything other than `ScalingMode::None`.

- `window_origin` affects the origin of the scaling, which means it doesn't have any effect if `scaling_mode` is `ScalingMode::None`.

## What solution would you like?

- `left`, `right`, `bottom`, and `top` should be private with public getters. Maybe they can be set through `ScalingMode::None`'s fields; this might make it a bit difficult to update though.

- `window_origin` should be renamed to `scaling_origin` or something similar.

## What alternative(s) have you considered?

Replace `scale` with separate width and height values, which will scale the entire projection whether `scaling_mode` is enabled or not. Then make `window_origin` (`scaling_origin`) more flexible with a fractional value of the width and height instead of just `WindowOrigin::BottomLeft` and `WindowOrigin::Center`. This will improve usability overall.

**Comment by xgbwei** [comment]
Just looking for some input here. I can merge this into #6177 (or create a new PR? whatever the conventions is) if it's deemed an issue.

**Comment by alice-i-cecile** [comment]
I'm on board with all of these changes. I think a second PR is better; smaller PRs are much easier to review and merge.

Your call on which solution you prefer; both seem reasonable to me.

**Comment by xgbwei** [comment]
> If you make it scale the entire projection regardless of `scaling_mode`, then won't this clash with `scaling_mode`'s purpose: https://docs.rs/bevy/latest/bevy/render/camera/enum.ScalingMode.html?

The `width` and `height` values replace `scale` and the `left`, `right`, `bottom` and `top` values when applied with `ScalingMode::None`, but for every scaling mode. They don't affect the size of the viewport and instead only scales the view frustum (the image will stretch if `width` and `height` aren't equal).

**Comment by bzm3r** [comment]
> > If you make it scale the entire projection regardless of `scaling_mode`, then won't this clash with `scaling_mode`'s purpose: https://docs.rs/bevy/latest/bevy/render/camera/enum.ScalingMode.html?
> 
> The `width` and `height` values replace `scale` and the `left`, `right`, `bottom` and `top` values when applied with `ScalingMode::None`, but for every scaling mode. That is, they don't affect the size of the viewport and instead only scales the view frustum (the image will stretch if `width` and `height` aren't equal).

Oh, I see! That's important to document then. The view frustrum really provides an "image" which is then stretched into the window.
