### ISSUE TITLE
Add the Ability to Reflect Doc Strings

### ISSUE THREAD

**Issue by zicklag** [bevyengine/bevy#6197]
## What problem does this solve or what need does it fill?

When using `Reflect` to power an automatically generated scripting API, it would be useful to have access to the type and field documentation strings, in addition to the type information.

That would allow auto-generated, typed bindings such as TypeScript bindings to include useful documentation on the meaning of the fields and types.

## What solution would you like?

Concretely, I just want the ability to get the docstring related to types and fields. For instance, with this struct:

```rust
/// My struct is awesome
struct MyStruct {
    /// This is somebody's name
    name: String,
}
```

If I have a `Box<dyn Reflect>` containing this struct, then I should be able to get the doc string "My struct is awesome", possibly by calling a new method on the `Reflect` trait, such as:

```rust
fn doc_string(&self) -> Option<&str>;
```

Additionally, I should be able to get the documentation for the `name` field, for instance, if I use `reflect_ref()` to find out that it is a [`Struct`](https://docs.rs/bevy/latest/bevy/reflect/trait.Struct.html). We could probably add a method to get the docstring of fields in a struct:

```rust
fn doc_string_at(&self, index: usize);
```

## What alternative(s) have you considered?

Instead of adding more methods to `Reflect` and `Struct` traits, _maybe_ we could add a `ReflectDocs` type that could be gotten as associated type data in a `TypeRegistry`, but I'm not sure if that would be as ergonomic, and might not work as well for getting the doc strings for specific fields.

## Additional context

None yet.

**Comment by alice-i-cecile** [comment]
This could add to the size of the objects and code gen significantly, and won't be useful for many use cases. We should definitely make this an extra, optional trait.

**Comment by zicklag** [comment]
If it was optional, then that would make it very easy to leave out the extra derive, and leave a lot of docs out in many Bevy plugins, etc. I've already noticed that a little bit in the case of reflecting `Default`, which is easy to forget to do, even when types already implement default, and then scripts are left unable to create the type.

It's understandable and fine if that ends up the case, but it'd be nice if people didn't have to manually opt-in.

I wonder if it could be a compile time feature flag or something like that. So that the derive macro would automatically include the docs for for everything, without the user having to opt-in, but people who want to compile it out because it's not used could easily do so.

Maybe could even be disabled by default, because even in a scripting scenario, we only really need it for type generation, unless we're building an editor.  I'm not a big fan in general of adding cargo features for things that don't really need it, but this might be a scenario where it makes sense, for something so often un-needed.

---

As far as object size, though, does adding another method increase the size of the trait object much? The string will be static for any Rust type, and the trait object just needs a pointer to the method that returns the static string, so it shouldn't be copied around with each `Box<dyn Reflect>`, if I'm understanding that right. ( It's a little fuzzy in my head right now, so I might have that wrong. )

**Comment by MrGVSV** [comment]
I was thinking about this recently as well. Imo it should be hidden behind a feature flag. If people need it (and most probably don't), they can choose to enable it

**Comment by alice-i-cecile** [comment]
Feature flag that's off by default sounds great to me.

**Comment by alice-i-cecile** [comment]
For the record: you're right about object size; I was thinking executable size but misspoke.

**Comment by MrGVSV** [comment]
I think one modification I'd make to your suggestion is to supply the doc strings on the `TypeInfo` types (e.g. `StructInfo`, `NamedField`, etc.) instead of `Reflect` as this is pretty much what `TypeInfo` is for. And it could very easily be added to that system.

However, my question regarding using `TypeInfo` for this: would this work for scripting purposes? I know there are cases where static compile-time info can be problematic for scripting which is inherently dynamic. 

If it is a problem to register this info statically, I think we should go with the type data approach. I just don't feel that doc string info should be accessible directly from `Reflect`. It _could_ but it just doesn't belong there imo.

**Comment by zicklag** [comment]
I'm still building an intuition for how the `Reflect` API is designed, but what you're saying seems to make sense to me.

As far as the `static`-ness of data is concerned, static values can still be created fine at runtime, as long as you "leak" them and make sure they are never dropped ( like a `lazy_static` or static `OnceCell`, etc. ), so I don't think that's an issue.

**Comment by MrGVSV** [comment]
Sounds good. Are you planning on working on this @zicklag? I can maybe take it on if you're not planning to.

**Comment by zicklag** [comment]
I'm quite busy at the moment, and this is really a bonus for me, so if you can get to it that'd be great. :D
