### ISSUE TITLE
Add screen/world point transformation helpers

### ISSUE THREAD

**Issue by kramer425** [bevyengine/bevy#620]
Bevy should include some helpers similar to Unity's [Camera.ScreenToWorldPoint](https://docs.unity3d.com/ScriptReference/Camera.ScreenToWorldPoint.html) and [Camera.WorldToScreenPoint](https://docs.unity3d.com/ScriptReference/Camera.WorldToScreenPoint.html)

**Comment by GabLotus** [comment]
Hey Thanks for the suggestion? Do you have a suggestion on how it could be integrated to bevy?

**Comment by smokku** [comment]
There is a raycasting code in https://github.com/aevyrie/bevy_mod_picking - maybe it could be exposed for stand-alone use.

**Comment by kramer425** [comment]
> Hey Thanks for the suggestion? Do you have a suggestion on how it could be integrated to bevy?

No problem. I started to look into it last week but I've been really busy with work/life, so I wanted to open it up to discussion now in case someone as already implemented it in their games or have experience with it.

**Comment by aevyrie** [comment]
See #1258 for world_to_screen.
#1799 would need to be extended with a function that accepts z-depth to return a Vec3 in world space instead of a line.

**Comment by devil-ira** [comment]
I think this can be closed since #6126 landed.
