### ISSUE TITLE
index out of bounds : for animation_player, irregular bug

### ISSUE THREAD

**Issue by pinkponk** [bevyengine/bevy#6204]
## Bevy version

stable 0.8.0 release 

```ignore
AdapterInfo { name: "NVIDIA GeForce GTX 1080 Ti", vendor: 4318, device: 6918, device_type: DiscreteGpu, backend: Vulkan }
```

## What you did

Running a bunch of gltf animations. I change speed, animation clip very often.

## What went wrong

I get the panic error at random but after a while of running my game. 

One of my animations is 111 long but the error have occurred on other animations as well.

Error:

thread 'Compute Task Pool (4)' panicked at 'index out of bounds: the len is 111 but the index is 111', /home/pinkponk/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_animation-0.8.1/src/lib.rs:252:38
thread 'main' panicked at 'task has failed', /home/pinkponk/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/task.rs:426:45

## Additional information
Bevy code, animation_player
```
                        // Find the current keyframe
                        // PERF: finding the current keyframe can be optimised
                        let step_start = match curve
                            .keyframe_timestamps
                            .binary_search_by(|probe| probe.partial_cmp(&elapsed).unwrap())  <--- Problem probably here
                        {
                            Ok(i) => i, <-------------------------------------------------------------------------------- And here
                            Err(0) => continue, // this curve isn't started yet
                            Err(n) if n > curve.keyframe_timestamps.len() - 1 => continue, // this curve is finished
                            Err(i) => i - 1,
                        };
                        let ts_start = curve.keyframe_timestamps[step_start];
                        let ts_end = curve.keyframe_timestamps[step_start + 1]; <--------------------- Error here
                        let lerp = (elapsed - ts_start) / (ts_end - ts_start);
```

discord help thread: https://discord.com/channels/691052431525675048/1019697973933899910/threads/1026824382418522162

**Comment by mockersf** [comment]
would you have code to reproduce? maybe with the example many_foxes?

**Comment by pinkponk** [comment]
This bug is irregular and does not always happen. I don't know how to exactly trigger it so I don't have code to reproduce. I can stop in the debugger automatically when the panic happens in vs code with lldb but I'm too noob to understand how to go up in the call stack and retrieve the variables such as the timestamps. I tried "rerun frame" in the debugger but the game just continues and stops at the break point without the error.

**Comment by pinkponk** [comment]
I tried to use the many_fox example and play around with but wasn't successful in recreating the bug there. I played around with the set_elapsed and even used my own model but to no avail.

**Comment by thebluefish** [comment]
I am able to reliably reproduce this bug in the `animated_fox` example with this replacement function:

```rs
fn keyboard_animation_control(
    keyboard_input: Res<Input<KeyCode>>,
    anims: Res<Animations>,
    time: Res<Time>,
    animations: Res<Assets<AnimationClip>>,
    mut animation_player: Query<&mut AnimationPlayer>,
) {
    if let Ok(mut player) = animation_player.get_single_mut() {
        // Trigger the bug
        if keyboard_input.just_pressed(KeyCode::Return) {
            player.play(anims.0[0].clone_weak());
            let duration = animations.get(&anims.0[0]).unwrap().duration();
            let elapsed = duration - time.delta_seconds() * player.speed(); // align the planets
            println!("duration {duration}, elapsed {elapsed}");
            player.set_elapsed(elapsed);
        }
    }
}
```

My understanding is that this can randomly occur, but it would be extremely rare.

**Comment by pinkponk** [comment]
Great and awesome! I now see that I forgot to turn off the repeat() when I tried to reproduce this.
