### ISSUE TITLE
Expose more `wgpu::RenderPass` draw APIs to `RenderCommand`s

### ISSUE THREAD

**Issue by bonsairobo** [bevyengine/bevy#6216]
## What problem does this solve or what need does it fill?

Users should be able to use the full extent of the `wgpu` draw APIs. While users have access to the `wgpu::RenderPass` via the `RenderContext` provided to `Node::run`, the `RenderCommand` API only has access to a `TrackedRenderPass`, which has a limited subset of draw APIs exposed; in particular, all of the `multi_draw...` variants are missing.

## What solution would you like?

Either add more wrapper methods to `TrackedRenderPass` or find some other abstraction that makes it feasible to work directly with the `wgpu::RenderPass` from the `RenderCommand` trait.

## What alternative(s) have you considered?

Implementing my own `Node` instead of using `RenderCommand`. This would be a major change.

**Comment by MDeiml** [comment]
`TrackedRenderPass` is just a wrapper to avoid calls to `set_render_pipeline`, `set_bind_group`, `set_vertex_buffer` and `set_index_buffer`. It should be possible to just add the `multi_draw_...` methods in the same way the `draw_...` methods are implemented.
