### ISSUE TITLE
Add support for reflection to remaining input types

### ISSUE THREAD

**Issue by TehPers** [bevyengine/bevy#6223]
## What problem does this solve or what need does it fill?

This allows users to access the input types via reflection, which could be useful for scripting, debugging (via `bevy-inspector-egui` for example), etc.

## What solution would you like?

Add `#[derive(Reflect, FromReflect)]` to input types and register their types in the `InputPlugin`. Also add `#[reflect(Traits)]` for relevant traits to the types.

Common:
- `ButtonState`

Keyboard:
- `KeyCode` (`register_type` only, since it doesn't seem to be done in the `InputPlugin`)
- `KeyboardInput`

Mouse:
- `MouseButton`
- `MouseButtonInput`
- `MouseScrollUnit`
- `MouseMotion`
- `MouseWheel`

Gamepads:
- `GamepadButtonType`
- `GamepadAxisType`
- `Gamepad`
- `GamepadButton`
- `GamepadAxis`
- `GamepadEventType`
- `GamepadEvent`

Touch:
- `TouchPhase`
- `ForceTouch`
- `TouchInput`
- `Touch` (maybe?)
- `Touches` (maybe?)

For most (if not all) of these types, it's just a matter of adding `#[derive(Reflect, FromReflect)]` to the type and reflecting the relevant traits.

## What alternative(s) have you considered?

Users can recreate these types (with reflection support) in their own projects and create a system which maps the input types, but this step seems unnecessary. (This is different than mapping raw inputs to actions, it's mapping raw inputs to raw inputs.)

## Additional context

`KeyCode` already implements `Reflect` and `FromReflect`. The only change needed there is to add `.register_type::<KeyCode>()` in the `InputPlugin`.

**Comment by alice-i-cecile** [comment]
You'll want most of the window events too to round this out.

**Comment by TehPers** [comment]
I'll open a PR for the input types. I can create a separate PR for window events too, unless you think that should be included in the input types PR. I think separating makes sense because they are two different crates but either way works for me.

**Comment by alice-i-cecile** [comment]
I'm fine with either approach.
