### ISSUE TITLE
Add logging variants of system chaining / piping adaptors

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6224]
## What problem does this solve or what need does it fill?

When using system chaining (soon to be system piping), I often want to simply log the error using tracing's macros.

## What solution would you like?

Add `dbg`, `info`, `warn` and `error` system adaptor variants to expand https://github.com/bevyengine/bevy/pull/5776, which call the corresponding re-exported [bevy_log macros](https://docs.rs/bevy/latest/bevy/log/macro.info.html) when the result is an error.

## What alternative(s) have you considered?

Write these adaptors myself in each code base I use. IMO these are simple, natural, and should be made ergonomic.

**Comment by Edwox** [comment]
Hi! I'd like to try and resolve this issue.

**Comment by alice-i-cecile** [comment]
Awesome, that would be great :)

**Comment by alice-i-cecile** [comment]
It got moved to `system_piping` :)

**Comment by Edwox** [comment]
Okay, great. Thank you!
