### ISSUE TITLE
index out of bounds when running any Bevy example

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#6231]
## Bevy version

7673db731e7de0039dd97aa9c1b4ddf675ef9d60

Issue exists since #5413, and disappear if I revert that commit

## \[Optional\] Relevant system information

```ignore
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Metal }
```

## What you did

```
cargo run --example load_gltf --release

    Finished release [optimized] target(s) in 0.16s
     Running `target/release/examples/load_gltf`
2022-10-11T00:45:54.918977Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Metal }
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/bevy_render/src/lib.rs:168:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mockersf** [comment]
it seems to be running OK in CI so potentially a macOS bug

**Comment by alice-i-cecile** [comment]
Ping @VitalyAnkh for thoughts.

**Comment by alice-i-cecile** [comment]
Presumably this is only occurring for you on examples that invoke the renderer? Hello World for example shouldn't hit this path at all.

**Comment by alice-i-cecile** [comment]
I can't reproduce this on Window 10; I suspect this is Mac specific.

**Comment by mockersf** [comment]
reading the code, this will happen on iOS and android too. on those systems we don't create the window early, so the surface is not yet available when initialising the renderer

**Comment by VitalyAnkh** [comment]
> this will happen on iOS and android too

The linked PR makes sense. Thanks! I wonder why the "run exampes" check didn't catch this problem. Should we make this check examples on more platforms/features?

**Comment by rparrett** [comment]
There is a balance with CI time and example coverage.

At one point I wanted to try to mitigate this by running the examples occasionally in a separate repo with a dashboard: https://rparrett.github.io/prototype_bevy_example_runner/

This runs all examples, but only on Linux right now.

**Comment by mockersf** [comment]
Bevy CI is running a few examples in wasm on firefox and chrome, and in native on linux and windows.

There may be a way to also run them on macOS, but I haven't had the time to set it up yet. Running on iOS and android would be great, but I'm not aware of it being possible in GitHub actions
