### ISSUE TITLE
Better error message when render is used without wgpu.

### ISSUE THREAD

**Issue by iMplode-nZ** [bevyengine/bevy#626]
I think there should be a better error message when the render plugin is used without wgpu. The current error message is very unhelpful (see below), and could be improved.

```
thread 'thread 'Compute Task Pool (2)Compute Task Pool (1)' panicked at '' panicked at 'Resource does not exist alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>Resource does not exist alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>', ', C:\Users\____\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.2.1\src\resource\resources.rsC:\Users\____\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.2.1\src\resource\resources.rs::175175::3232
```

I would suggest panicking with an error message like "Render backend not found. Currently, the render plugin needs the wgpu plugin to be supported; maybe that should be enabled?"

**Comment by GabLotus** [comment]
Seems like a good point. Developer experience should definitely be a top priority. Thanks for the suggestion. Do you have a suggested implementation for this feature?

**Comment by DJMcNab** [comment]
See also #622

**Comment by iMplode-nZ** [comment]
@GabLotus I don't actually know how bevy works at all, so no. Also, it seems that `CorePlugin` has a dependency on `TypeRegistryPlugin`, which should also be fixed. (also which plugin has the event loop...)

**Comment by memoryruins** [comment]
> it seems that CorePlugin has a dependency on TypeRegistryPlugin, which should also be fixed. 

It uses the `RegisterType` trait for the plugin
https://docs.rs/bevy_type_registry/0.2.1/bevy_type_registry/trait.RegisterType.html
https://github.com/bevyengine/bevy/blob/9a4167ef7f5115f7fc045a881f5c865f568d34c0/crates/bevy_core/src/lib.rs#L36-L38

> also which plugin has the event loop

The high-level runner is in `bevy_app`, which either uses `bevy_app::ScheduleRunner` or `bevy_winit::winit_runner` if there is windowing.
