### ISSUE TITLE
#[derive(WorldQuery)] on Foo produces FooState which docs don't really mention

### ISSUE THREAD

**Issue by Xion** [bevyengine/bevy#6264]
## Bevy version

bevy v0.8.1

## What you did

I was trying to make a `WorldQuery` item (and the `SystemParam`) for `big_brain`'s common query item:

```rust
use big_brain::prelude::*;

#[derive(WorldQuery)]
#[world_query(mutable)]
pub struct Action {
    actor: &'static Actor,
    state: &'static mut ActionState,
}
```

Both `Actor` and `ActionState` are types from `big_brain`.

## What went wrong

Got very confusing compilation errors about `ActionState` not implementing `Component`, even though `big_brain::ActionState` does implement it.

It was doubly-confusing because when I tried to see the definition of `ActionState` to check, rust-analyzer would point me back to my own `Action` struct. It basically looked like rust-analyzer was confused and/or broke.

## Additional information

I have since traced the problem to the fact that `WorldQuery` derive produces a `-State` type in addition to `-Item` and `-ReadOnly`. This is touched upon very lightly in `WorldQuery` docs that say:

> The implementation also generates two other structs that implement [Fetch](https://docs.rs/bevy/latest/bevy/ecs/query/trait.Fetch.html) and [FetchState](https://docs.rs/bevy/latest/bevy/ecs/query/trait.FetchState.html) and are used as [WorldQuery::Fetch](https://docs.rs/bevy/latest/bevy/ecs/query/trait.WorldQueryGats.html#associatedtype.Fetch) and [WorldQuery::State](https://docs.rs/bevy/latest/bevy/ecs/query/trait.WorldQuery.html#associatedtype.State) associated types respectively.

but it doesn't explicitly mention their names (which, in addition to `FooState`, I presume also includes `FooFetch`).

## Suggestion

Any derive macro that introduces new symbols to the module namespace should have all those symbols clearly outlined in the docs, preferably close to the beginning, and possibly as a prominent note/warning.

**Comment by DJMcNab** [comment]
This appears to be a rehash of https://github.com/bevyengine/bevy/issues/1727 (which incidentally I think was solved by https://github.com/bevyengine/bevy/pull/4100), but for `WorldQuery`.

**Comment by DJMcNab** [comment]
There isn't any reason that you should need access to the `State` types, since every part of their design is implementation detail. Those types should be in an unnameable namespace.

The case of adding accessors to the `FooReadOnlyItem`/`FooItem` structs does however seem valid. I'd be tempted to say that if you want to support custom readonly methods, you should have to manually create your own `Item` $\lor$ `ReadOnlyItem` structs, so that you have complete control over the struct.

That is, we should avoid creating any new structs in the local namespace under any circumstances, but allow the user's own struct which matches the correct layout to be used if desired.

**Comment by BoxyUwU** [comment]
What's the point in making users create their own `Item` type thats exactly identical to the auto generated one, just so that they can do `impl MyItem` when `impl FooItem` would work just fine

**Comment by DJMcNab** [comment]
Broadly, to mitigate the issue that tooling does not like it when item names collide, and fails to provide adequate diagnostics/suggestions when that case does occur. I thought it was therefore unidiomatic to create new items in a derive macro, although [the docs](https://doc.rust-lang.org/reference/procedural-macros.html#derive-macros) I can find don't suggest that.

In addition, a number of `derives` which may be useful need the specific fields to be marked (e.g. fields on a `Serialize` for the `ReadOnly` versions may need the `#[serde(rename="...")]`). This requires a complexity explosion to handle all the permutations of this.

My point is more broadly that we should not be in the business of choosing names to pollute the local namespace with. My updated position would be that we can have three cases:

1. If nothing is specified, use an item in the implemenation anonymous namespace
2. If specified, create the item in the current scope with the given name
3. Optionally, support using an item with the given name which matches the correct field types at a given path

I would predict that ~75% of cases should use the first form, so polluting the local scope is not a good default.

**Comment by BoxyUwU** [comment]
no, that PR doesn't do anything about the `State` for the worldquery, just the readonly version of the worldquery
