### ISSUE TITLE
PerspectiveProjection fields

### ISSUE THREAD

**Issue by Feilkin** [bevyengine/bevy#6279]
## How can Bevy's documentation be improved?

Provide a link to the documentation and describe how it could be improved. In what ways is it incomplete, incorrect, or misleading?

The fields of the [PerspectiveProjection](https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/camera/projection.rs#L106 ) have no documentation, and this is extremely confusing for the `fov` field at least, since it is not told if this should be in degrees or radians, and if it is the vertical or horizontal FOV. Looking at the default value, I'd guess it is supposed to be given in radians.

If you have suggestions on exactly what the new docs should say, feel free to include them here. Or alternatively, make the changes yourself and [create a pull request](https://bevyengine.org/learn/book/contributing/code/) instead.

I suggest that documentation is added for all these fields, what they are used for and what units they should be in.

**Comment by rparrett** [comment]
`fov` is the vertical fov in radians.
