### ISSUE TITLE
Link broken on `AppTypeRegistry`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6281]
## How can Bevy's documentation be improved?

https://dev-docs.bevyengine.org/bevy/app/struct.AppTypeRegistry.html

This should point to https://dev-docs.bevyengine.org/bevy/reflect/struct.TypeRegistryInternal.html.

Maybe we should make the internal type `pub`? I'll defer to @mockersf @MrGVSV @PROMETHIA-27 on that point.

**Comment by MrGVSV** [comment]
I think the broken link in `AppTypeRegistry` should point to [`TypeRegistryArc`](https://dev-docs.bevyengine.org/bevy/reflect/struct.TypeRegistryArc.html) rather than [`TypeRegistryInternal`] since that's what it actually contains and we probably shouldn't try to hide that information.

**Comment by ZarakiKanzaki** [comment]
Hi @MrGVSV  where is possible to edit the documentation in order to point to the correct link?

**Comment by MrGVSV** [comment]
> Hi @MrGVSV  where is possible to edit the documentation in order to point to the correct link?

@ZarakiKanzaki You should be able to find the broken link defined here: https://github.com/bevyengine/bevy/blob/cb5e2d84beb7f36427eeec13729f6dd52e04fbc0/crates/bevy_app/src/app.rs#L26

**Comment by ZarakiKanzaki** [comment]
> > Hi @MrGVSV  where is possible to edit the documentation in order to point to the correct link?
> 
> @ZarakiKanzaki You should be able to find the broken link defined here:
> 
> https://github.com/bevyengine/bevy/blob/cb5e2d84beb7f36427eeec13729f6dd52e04fbc0/crates/bevy_app/src/app.rs#L26

thanks for the quick reply, once fixed the broken link, is there a way to verify it works correctly locally?

**Comment by alice-i-cecile** [comment]
`cargo doc` is the best way :)

**Comment by ZarakiKanzaki** [comment]
@alice-i-cecile @MrGVSV  I didn't really understand if the pipe failed beacuse of my changes, could you look at the Pr so that I can change it if I made something wrong?

**Comment by mockersf** [comment]
> I think the broken link in `AppTypeRegistry` should point to [`TypeRegistryArc`](https://dev-docs.bevyengine.org/bevy/reflect/struct.TypeRegistryArc.html) rather than [`TypeRegistryInternal`] since that's what it actually contains and we probably shouldn't try to hide that information.

I would prefer it to link to `TypeRegistryInternal`. There is already a link to `TypeRegistryArc` automatically built with the type signature, it's more interesting for the doc to point to what is the completely unwrapped type

**Comment by ZarakiKanzaki** [comment]
> signature, it's more interesting for the doc to point to what is the completely unwrapped type

If we need to change to the Internal it wouldn't be a problem for me, I just need to know which one is the one we want to link 😊

**Comment by mockersf** [comment]
Oh actually there's something funny happening with how those types are exported: bevy re-export the internal crate, which re-export the reflect crate but a few renames, some of which are shadowing other imports.
This is the doc of `TypeRegistryArc`: https://dev-docs.bevyengine.org/bevy/reflect/struct.TypeRegistry.html (which is also https://dev-docs.bevyengine.org/bevy/reflect/struct.TypeRegistryArc.html)
This is the doc of `TypeRegistry`: https://dev-docs.bevyengine.org/bevy/reflect/struct.TypeRegistryInternal.html

good luck getting the link right 😄

**Comment by ZarakiKanzaki** [comment]
> Oh actually there's something funny happening with how those types are exported: bevy re-export the internal crate, which re-export the reflect crate with a few renames, some of which are shadowing other imports. This is the doc of `TypeRegistryArc`: https://dev-docs.bevyengine.org/bevy/reflect/struct.TypeRegistry.html (which is also https://dev-docs.bevyengine.org/bevy/reflect/struct.TypeRegistryArc.html) This is the doc of `TypeRegistry`: https://dev-docs.bevyengine.org/bevy/reflect/struct.TypeRegistryInternal.html
> 
> good luck getting the link right 😄

So do you have in mind anything to solve this problem?

**Comment by mockersf** [comment]
Sorry, no, I'm not confident enough in how cargo doc works for that. Trying things and building doc locally would be the way...

**Comment by ZarakiKanzaki** [comment]
@alice-i-cecile  or @MrGVSV do you have any example of issue in which  the docs links to another class that is in another namespace?

**Comment by james7132** [comment]
This looks very similar to that of #3654 and #4511, but the links provided are still broken.

**Comment by mockersf** [comment]
no dead links for me anymore, this was probably fixed by rustdoc
