### ISSUE TITLE
`World` has similarly named methods

### ISSUE THREAD

**Issue by BoxyUwU** [bevyengine/bevy#6285]
`World::init_resource` and `World::initialize_resource` both exist but do completely different things, this is pretty confusing and one of the names should be changed. `initialize_resource` is `pub(crate)` so this only matters for bevy devs not users.

**Comment by alice-i-cecile** [comment]
Removed good-first-issue tag; this is likely to be bikeshed heavy :p

Note that `App` has `init_resource` as well, which is widely used. On the `World` end, a similar `init_component` method exists, which should be renamed to match whatever we do for `initialize_resource`.
