### ISSUE TITLE
[Minor] Rename or hide bevy_ui::ui_node::Direction

### ISSUE THREAD

**Issue by lewiszlw** [bevyengine/bevy#6286]
I'm a new bie to game dev and writing my first 2d game with bevy. 
`Direction` is basic component I think when developing games, but it conflicts with `bevy_ui::ui_node::Direction` when I want to import it, so I have to import it with mod name. I check the desc on `bevy_ui::ui_node::Direction`, this enum is for text direction, so is this reasonable to rename `bevy_ui::ui_node::Direction` to `bevy_ui::ui_node::TextDirection`, or may hide it in `bevy::prelude::*` if useless for game developers?

**Comment by alice-i-cecile** [comment]
Agreed. This should be fixed as we split the Style component.

**Comment by lewiszlw** [comment]
Nice, hope to see this improvement in next version. Closing.
