### ISSUE TITLE
Redundant pub(crate) methods for getting resources with id

### ISSUE THREAD

**Issue by BoxyUwU** [bevyengine/bevy#6294]
- `World::get_non_send_with_id` is redundant, we should remove it and use the public dynamic API `get_resource_by_id`
- `World::get_resource_with_id` is unsound since it has no `Send`/`Sync` checks and is redundant, we should remove it and use the public dynamic API `get_resource_by_id`

**Comment by alice-i-cecile** [comment]
I'm tempted to tag this as good-first-issue. Should be easy to clean up.

**Comment by BoxyUwU** [comment]
I think that's a correct label choice

**Comment by targrub** [comment]
I can take this.

So the goal is: remove the two methods on `World`, make sure any code that currently uses them is fixed to use "the public dynamic API `get_resource_by_id`" instead, and document the API change for the Migration Guide?

**Comment by BoxyUwU** [comment]
since the methods are `pub(crate)` there shouldnt need to be a migration guide, but otherwise yeah

**Comment by targrub** [comment]
What about `World::get_resource_unchecked_mut_with_id` and `World::get_non_send_unchecked_mut_with_id`?

**Comment by alice-i-cecile** [comment]
If those are redundant as well, feel free to do likewise.

**Comment by targrub** [comment]
There is neither a `World::get_resource_unchecked_mut_by_id` nor a `World::get_resource_mut_by_id` method so I gave up pursuing that avenue.

**Comment by targrub** [comment]
@james7132 has comments on my PR for this issue that you may want to reply to.

**Comment by targrub** [comment]
Moved changes to PR #6369 because a previous merge was incorrect.

**Comment by JoJoJet** [comment]
Should this be closed for the same reasons that #6369 was closed?

> * `World::get_resource_with_id` is unsound since it has no `Send`/`Sync` checks

This is still a concern but I think it should be its own issue.
