### ISSUE TITLE
Now that we have Changed<T>, optimize all the things

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#63]
We should be using `Changed<T>` everywhere we can to avoid doing redundant work:
- [X] Transforms
- [ ] Parents/Children
- [X] Labels
- [ ] Render Nodes
  - [ ] lights
  - [ ] camera
  - [X] render_resources (potentially a _huge_ win here)
- [X] Cameras
- [ ] ShaderDefs
- [ ] Sprites
- [ ] UI update system (only update "dirty" parts of the tree)
- [X] Pipeline Compiler (only run when RenderPipelines component has changed)

**Comment by tristanpemble** [comment]
I was looking into doing this for the transforms systems. For `transform_translation_rotation_scale_system`, the current query is:

```rs
Query<Without<LocalTransform, Without<NonUniformScale, (&mut Transform, &Translation, &Rotation, &Scale)>>>
```

ideally we could do something like

```rs
Query<Without<LocalTransform, Without<NonUniformScale, (&mut Transform, &Translation, &Rotation, &Scale, Any<Changed<Translation>, Changed<Rotation>, Changed<Scale>>)>>>
```

the idea being we want to run this system on anything that has `Transform`, `Rotation` and `Scale`, and at least one of those was changed.

I asked in Discord and it seems like this is not currently possible (tldr queries are `and` only, no `or` right now)

**Comment by tristanpemble** [comment]
@cart it may be worth changing your list into checkboxes so we can track status

**Comment by Axighi** [comment]
What's left for this task?

**Comment by chrisburnor** [comment]
> What's left for this task?

Camera seems undone (from my cursory grepping through the codebase) but it's honestly kind of hard to figure out what *has* been done.

**Comment by cart** [comment]
Just updated the description with checkboxes indicating whats been done.

**Comment by cart** [comment]
I'm currently working on a rework of parenting/children. And #1046  is covering the ShaderDefs case.

**Comment by alice-i-cecile** [comment]
This should be looked at again once #68 is solved and we add explicit dependencies to our default systems for 0.5.
