### ISSUE TITLE
Custom Eventloop?

### ISSUE THREAD

**Issue by iMplode-nZ** [bevyengine/bevy#630]
I would find it helpful to have an event loop that functions without a window. This could be useful for automated tests so that people don't have to deal with windows popping up unnecessarily. It could also provide more features such as `set_timeout` (the thing the JavaScript event loop has), etc.

**Comment by memoryruins** [comment]
> I would find it helpful to have an event loop that functions without a window.
 
Check out the [headless example](https://github.com/bevyengine/bevy/blob/master/examples/app/headless.rs,) where it runs with `bevy_app::ScheduleRunnerPlugin`. You may need to add back some plugins or features individually by need.

> It could also provide more features such as set_timeout

Currently, I have been using a system that uses a time resource or counts ticks that sends an [`bevy_app::AppExit`](https://github.com/bevyengine/bevy/blob/master/examples/ecs/ecs_guide.rs#L131) when complete.
