### ISSUE TITLE
Expose `symphonia` feature of `rodio` for `bevy_audio`

### ISSUE THREAD

**Issue by harudagondi** [bevyengine/bevy#6301]
## What problem does this solve or what need does it fill?

Related to #6299, bevy_audio is limited to `wav`, `ogg`, `flac`, or `mp3` audio formats. However, `rodio` have the `symphonia` feature which enables [file formats and codecs](https://docs.rs/symphonia/latest/symphonia/#support) such as:

- ISO/MP4
- MKV/WebM
- OGG
- Wave
- AAC-LC
- ALAC
- FLAC
- MP3
- PCM
- Vorbis

## What solution would you like?

Add a new feature in `bevy_audio` and possibly in `bevy` as well that enables this feature

## What alternative(s) have you considered?

Implement your own `Decodable` type that uses the `Decoder` from `rodio` that has the `symphonia` feature enabled. (I don't think this works)

## Additional context

#3145 is a tangentially related issue that discusses the viability of `symphonia` as a "backend". (`symphonia` is a decoder and a demuxing framework, not an audio backend)

**Comment by alice-i-cecile** [comment]
Fully on board. Should be a simple PR. For enabling audio formats, probably follow what was done for the various image and asset formats?

**Comment by james7132** [comment]
Please keep said feature optional or at most conditional on other features. To take a page out of Unity and Unreal's books, their built games only support a small list of codecs and containers at runtime, but support transcoding many more in the editor on asset import. This avoids needing to ship the equivalent of ffmpeg with every game download.

**Comment by harudagondi** [comment]
> Please keep said feature optional or at most conditional on other features. To take a page out of Unity and Unreal's books, their built games only support a small list of codecs and containers at runtime, but support transcoding many more in the editor on asset import. This avoids needing to ship the equivalent of ffmpeg with every game download.

Yeah I'm just asking for a Cargo feature reexport to `symphonia-all` of rodio. Should be simple to do.

**Comment by Ian-Yy** [comment]
Hi. Is anyone working on this? Can I help on this?
