### ISSUE TITLE
return_after_run example is broken

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#6311]
There are multiple issues with this example.

- The `ClearColor` which is meant to visually distinguish the first app from the next is never shown because there are no cameras. This has been broken between Bevy 0.7 and Bevy 0.8 with the Camera Driven Rendering stuff.

- Since the recent winit upgrade, we get this error after the first window is closed.

```
thread 'main' panicked at 'Creating EventLoop multiple times is not supported.', /Users/robparrett/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.4/src/event_loop.rs:106:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

- Prior to that, I think this was still broken on at least MacOS with a different error after closing the first window.

```
thread 'main' panicked at 'The panic info must exist here. This failure indicates a developer error.', /Users/robparrett/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/macos/app_state.rs:375:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/robparrett/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/macos/event_loop.rs:237:55
```

## Additional information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: DiscreteGpu, backend: Metal }
```

**Comment by rparrett** [comment]
It seems that we're just not allowed to do what we're doing in that example anymore.

https://github.com/rust-windowing/winit/blob/v0.27.4/src/event_loop.rs#L82

So I guess we just need to find another way to demonstrate `return_from_run`?

**Comment by mockersf** [comment]
> So I guess we just need to find another way to demonstrate return_from_run?

Yup... let's try to find a good use case for it.

Putting this in the 0.9 milestone. Worst case fix is to remove the second app and show that the final `println` is printed

**Comment by rparrett** [comment]
Some background info in #167 for those digging into this. I still don't feel informed about how people are using this feature.

**Comment by CGMossa** [comment]
I believe this is a critical feature for users outside of gaming; As an example, take this feature:
> Entities can be transferred between worlds without serialisation using the [World::transfer method](https://docs.rs/rs-ecs/*/rs_ecs/struct.World.html#method.transfer). We use this to completely remove entities from the simulation while keeping their full dynamic state around for later inspection.
which comes from [`rs-ecs`](https://github.com/adamreichold/rs-ecs/)

**Comment by mockersf** [comment]
I'm not sure I see the relation between being able to run multiple windows one after the other and transferring entities between worlds?
