### ISSUE TITLE
`TextureAtlasSprite` has no docs

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6322]
## How can Bevy's documentation be improved?

[`TextureAtlasSprite`] has no documentation, making it very hard to figure out:

1. What it is, in summary
2. How it differs from `Sprite`
3. How you might construct it
4. How you might use it
5. How it relates to the `Handle<Image>`s you might get out of a [`TextureAtlas`](https://dev-docs.bevyengine.org/bevy/sprite/struct.TextureAtlas.html#structfield.texture_handles)

Similar changes for `Sprite` and even `UiImage` may make sense to do in the same PR.

**Comment by rparrett** [comment]
Seems like this was fixed and/or made obsolete by #5103
