### ISSUE TITLE
Transparent windows on macOS are opaque

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#6330]
## Bevy version

main

## What you did

run the `transparent_window` example

## What went wrong

window is not transparent

## Additional information

Related to https://github.com/gfx-rs/wgpu/issues/687

This can be "worked around" by setting `alpha_mode` to `CompositeAlphaMode::PostMultiplied` instead of `CompositeAlphaMode::Auto` (in bevy 0.9-dev+). I'm not sure what the other implications of doing that are.

See also a similar issue on linux: https://github.com/bevyengine/bevy/issues/5779

**Comment by aprchen** [comment]
Thanks, this worked for me

> This can be "worked around" by setting `alpha_mode` to `CompositeAlphaMode::PostMultiplied` instead of `CompositeAlphaMode::Auto` (in bevy 0.9-dev+). I'm not sure what the other implications of doing that are.
