### ISSUE TITLE
glTF not being rendered correctly. UV texture issue? 

### ISSUE THREAD

**Issue by OriginLive** [bevyengine/bevy#6335]
## Bevy version

bevy = "0.8.1"

## What you did

Created an image of a plane in blender with 100x100 m size. Gave a texture for each 1x1meter.
![image](https://user-images.githubusercontent.com/24319526/197322093-59e87be3-98fc-45b1-9fb6-3ade208c21a9.png)

![image](https://user-images.githubusercontent.com/24319526/197322074-07844f8c-9e57-4317-9d40-4bf675cc2546.png)

Bevy has no clue UV isn't the whole plane.

```rs
    let grid_plane = asset_server.load("models\\planewgrid.gltf#Scene0");

    // plane
    commands
        .spawn_bundle(SceneBundle {
            scene: grid_plane,
            ..Default::default()
        })
        .insert(Collider::cuboid(100.0, 0.1, 100.0));
```

## What went wrong

This is what breaks in bevy:

![image](https://user-images.githubusercontent.com/24319526/197322118-195cc4e0-744e-4581-82e9-f8403ea9ab3d.png)

## Additional information

Here's the files:
http://gofile.me/6dlZG/cQxW3Sc6H

**Comment by mockersf** [comment]
Could you try your gltf file in https://gltf-viewer.donmccurdy.com?

Textures done with nodes are often not exported by blender in the gltf format.

**Comment by OriginLive** [comment]
Looks fine 
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/24319526/197329896-46bfd26d-7a92-4dee-a2ff-cad8bb3c9177.png">

**Comment by vonforum** [comment]
Could be missing [KHR_texture_transform](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_texture_transform/README.md) support, which is how blender exports scaled textures in glTF, I think.
