### ISSUE TITLE
Gamepad names

### ISSUE THREAD

**Issue by terhechte** [bevyengine/bevy#6339]
## What problem does this solve or what need does it fill?

Bevy uses Gilrs for gamepad support. Gilrs knows the names of all detected gamepads. E.g. when I connect a Nintendo Switch Joy-Con, the `gilrs` `ev` example prints:

```
Power info of gamepad 0(Joy-Con (R)): Unknown
```

Bevy, however, doesn't take this information into account. Thus, within bevy, I can only identify gamepads by their `id` which is not a nice user experience when I want to have an in-game menu where a user can choose between multiple selected gamepads.

## What solution would you like?

Extending the `Gamepad` struct with a `name` would require cloning a lot of `String` types around, maybe a better solution would be to have a `Resource` `HashMap<Gamepad, String>` which would allow getting the name of a gamepad when needed?

## What alternative(s) have you considered?

I suppose I could directly import `gilrs` and get the names from there, but that would be quite the overhead.

**Comment by alice-i-cecile** [comment]
> Extending the Gamepad struct with a name would require cloning a lot of String types around, maybe a better solution would be to have a Resource HashMap<Gamepad, String> which would allow getting the name of a gamepad when needed?

IMO we can put this in the existing `Gamepads` resource, which tracks the registered game pads :)
