### ISSUE TITLE
Cannot compile v0.8.1 after running cargo update

### ISSUE THREAD

**Issue by obulka** [bevyengine/bevy#6353]
## Bevy version

0.8.1

## Relevant system information

rustc 1.64.0 (a55dd71d5 2022-09-19)
cargo 1.64.0 (387270bc7 2022-09-16)
and
rustc 1.66.0-nightly (6e95b6da8 2022-10-22)
cargo 1.66.0-nightly (071eeaf21 2022-10-22)

Ubuntu 20.04.4 LTS

## What you did

Ran:
`git checkout latest`
`rustup update`
`cargo update`
`cargo run --example hello_world`

## What went wrong

I received a bunch of compilation errors that look like the following:
```
error[E0308]: mismatched types
   --> /home/ob1/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:803:40
    |
803 |             Err(err) if err.errno() == nix::errno::Errno::EPIPE => {
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: enum `nix::errno::Errno` and enum `host::alsa::alsa::nix::errno::Errno` have similar names, but are actually distinct types
note: enum `nix::errno::Errno` is defined in crate `nix`
   --> /home/ob1/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.23.1/src/errno.rs:774:5
    |
774 |     pub enum Errno {
    |     ^^^^^^^^^^^^^^
note: enum `host::alsa::alsa::nix::errno::Errno` is defined in crate `nix`
   --> /home/ob1/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.24.2/src/errno.rs:776:5
    |
776 |     pub enum Errno {
    |     ^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `nix` are being used?
```

## Additional information

This does not happen on the `main` branch, but I cannot use `bevy = "0.8"` in my project anymore. This was not happening yesterday, and the only difference is that I ran `cargo update`.

**Comment by Helaxious** [comment]
Same here

**Comment by alice-i-cecile** [comment]
This is due to https://github.com/diwic/alsa-rs/issues/90. 

The workaround here should work for now: https://github.com/diwic/alsa-rs/issues/90#issuecomment-1288134557

**Comment by alice-i-cecile** [comment]
FYI, this is also why our CI is broken.

**Comment by Helaxious** [comment]
The workaround worked for me, thanks for the quick response!

**Comment by obulka** [comment]
Works for me too, thank you!
