### ISSUE TITLE
Keyboard input not handled without a primary window

### ISSUE THREAD

**Issue by mcpar-land** [bevyengine/bevy#636]
I'm trying to run a game solely in the terminal, including all the default plugins aside from any that are for 2d/3d rendering.

Expected behavior below: game should run solely in the terminal, and panic when the P key is pressed.
Actual: game runs in the terminal, but nothing happens when P is pressed.

```rust
use bevy::prelude::*;

fn panic_on_p(input: Res<Input<KeyCode>>) {
  if input.pressed(KeyCode::P) {
    panic!("P was pressed!");
  }
}

fn main() {
  App::build()
    .add_plugin(bevy::type_registry::TypeRegistryPlugin::default())
    .add_plugin(bevy::core::CorePlugin::default())
    .add_plugin(bevy::diagnostic::DiagnosticsPlugin::default())
    .add_plugin(bevy::input::InputPlugin::default())
    .add_plugin(bevy::window::WindowPlugin {
      add_primary_window: false,
      exit_on_close: true,
    })
    .add_plugin(bevy::asset::AssetPlugin::default())
    .add_plugin(bevy::scene::ScenePlugin::default())
    .add_plugin(bevy::audio::AudioPlugin::default())
    .add_plugin(bevy::winit::WinitPlugin::default())
    .add_system(panic_on_p.system())
    .run();
}
```

However, if you change:
```rust
    add_primary_window: true
```

Then the keyboard input is handled - but an unwanted, empty window appears.

Is this a bug, or is there a better way to prevent a primary window from appearing?

**Comment by CleanCut** [comment]
@mcpar-land In general, terminals don't pass raw input to their programs unless the program explicitly enables raw input mode.  You can see an [example of using crossterm to enable raw mode](https://github.com/CleanCut/invaders/blob/7cc2d7414c8d0f386d15758072a58b3784ec29fa/src/main.rs#L27) in my [invaders](https://github.com/CleanCut/invaders) terminal-based game demonstration I made for the course I teach.

In Bevy, I _think_ all keyboard (and mouse) input is currently handled by [winit](https://github.com/rust-windowing/winit) through a native OS GUI window.  So with headless Bevy I think you would need to either use something like crossterm  to handle keyboard input directly within your game, or someone would need to add a plugin to that effect to Bevy for you to use.

**Comment by cart** [comment]
@CleanCut's assessment is correct. Bevy uses winit for windowing + input. We would likely need an alternative bevy_input backend for terminal scenarios.

**Comment by mcpar-land** [comment]
Got it 👍  I'll close this issue.
