### ISSUE TITLE
Renderable entities with non-renderable parents can break z-order for unrelated entities

### ISSUE THREAD

**Issue by jabuwu** [bevyengine/bevy#6366]
## Bevy version

0.8.1

## Relevant system information

Bug appears on both OS X and Windows. Does not occur on WASM.

```ignore
`AdapterInfo { name: "Apple M2", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Metal }`
`AdapterInfo { name: "NVIDIA GeForce GTX 1050 Ti", vendor: 4318, device: 7298, device_type: DiscreteGpu, backend: Vulkan }`
```

## What you did

I have a red `SpriteBundle` (with the default texture), and a black `MaterialMesh2dBundle` (with `Quad`/`ColorMaterial`).

```rust
commands.spawn_bundle(SpriteBundle {
    sprite: Sprite {
        custom_size: Vec2::new(300., 75.).into(),
        color: Color::RED,
        ..Default::default()
    },
    transform: Transform::from_xyz(0., 0., 1.),
    ..Default::default()
});

let mesh = Mesh::from(Quad::new(Vec2::splat(100.)));
let mesh_handle = meshes.add(mesh);
commands.spawn_bundle(MaterialMesh2dBundle {
    mesh: Mesh2dHandle(mesh_handle),
    material: materials.add(ColorMaterial::from(Color::BLACK)),
    transform: Transform::from_xyz(0., 0., 0.),
    ..Default::default()
});
```

The red sprite has z of 1.
The black mesh has a z of 0.

The expectation is that the sprite will render above the mesh.

<img width="420" alt="Screen Shot 2022-10-25 at 2 12 19 AM" src="https://user-images.githubusercontent.com/46233424/197733912-5990b937-1e52-4c1c-9c2c-c1ec7cc792d7.png">

## What went wrong

Adding a seemingly unrelated hierarchy causes the z ordering of these two entities to become unpredictable.

```rust
commands
    .spawn_bundle((
        Transform::from_xyz(0., -200., 0.).with_scale(Vec3::ONE * 0.5),
        GlobalTransform::default(),
        Visibility::default(),
        ComputedVisibility::default(),
    ))
    .with_children(|parent| {
        parent.spawn_bundle(SpriteBundle {
            sprite: Sprite {
                custom_size: Some(Vec2::new(32., 32.)),
                color: Color::BLUE,
                ..Default::default()
            },
            ..Default::default()
        });
    });
```

Now, sometimes, the black mesh will appear above the red sprite. The order doesn't change at runtime and requires restarting the application, occurring about 50% of the time.

<img width="358" alt="Screen Shot 2022-10-25 at 2 15 52 AM" src="https://user-images.githubusercontent.com/46233424/197734793-8a532a22-94c4-4dd7-8049-08cdf1e070da.png">

Adding a SpriteBundle to the parent, or removing the SpriteBundle from the child causes the bug to disappear. Changing the child to use a mesh instead of a sprite also fixes the issue.

## Additional information

Repro: https://github.com/jabuwu/bevy_z_issue

**Comment by devil-ira** [comment]
This is a weird one! Can definiteley reproduce.
It happens when adding the blue sprite on its own, so I think it's unrelated to the hierarchy.

**Comment by jabuwu** [comment]
Oh yeah, you're right. I did try that but it's sort of random so I guess I missed it. The original title isn't correct then, and this seems to have more do with sprites and meshes not ordering properly.

**Comment by jabuwu** [comment]
Oh, good call, yes it seems to be fixed in main 👍
