### ISSUE TITLE
Option to set the `is_srgb` flag when loading textures

### ISSUE THREAD

**Issue by mousetail** [bevyengine/bevy#6371]
## What problem does this solve or what need does it fill?

When manually loading some types of textures like normal maps, roughness maps, and occlusion maps, you do not want sRGB compensation, as this ruins images. There should be some option to disable it.

Right now when loading textures from a `.gltf` file normal maps etc. are already marked linear:

https://github.com/bevyengine/bevy/blob/main/crates/bevy_gltf/src/loader.rs
```rs
if let Some(texture) = material.normal_texture() {
            linear_textures.insert(texture.texture().index());
        }

let is_srgb = !linear_textures.contains(&gltf_texture.index());
Image::from_buffer(
                buffer,
                ImageType::MimeType(mime_type),
                supported_compressed_formats,
                is_srgb,
            )?
```

However, in https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/texture/image_texture_loader.rs the `sRGB` setting is hard coded to `true`:

```rs
let dyn_img = Image::from_buffer(
                bytes,
                ImageType::Extension(ext),
                self.supported_compressed_formats,
                true,
            )
```

This option should also be exposed for manually loaded textures.

## What solution would you like?

A long term solution would be to store this info in a `.meta` file as suggested here: https://github.com/bevyengine/bevy/discussions/3972

However, just to make normal mapping even possible right now I'd suggest adding a URL parameter to the asset loader, something like this:

```rs
let texture: Handle<Image> = asset_server.load("normal_map.png#?colors=linear");
```

This uses the existing extended parameter syntax also used in the GLTF loader. It's also consistent with how URLs work which is something you seem to be trying to emulate.

This could also be extended to other settings like the various options in the sampler.

This syntax might still be useful even with the new asset system if for some reason you need to load the same texture with different settings in different situations. For example you might want to change the filtering mode depending on performance settings.

## What alternative(s) have you considered?

Removing the bevy image system and writing my own image loaded that doesn't have this limitation

## Additional context

Any other information you would like to add such as related previous work,
screenshots, benchmarks, etc.

![Screenshot of bugged normals](https://media.discordapp.net/attachments/1034142108807876719/1034142431786057738/unknown.png)

**Comment by mousetail** [comment]
Another option that might be better, as it is more type safe, is to extend the asset loader to allow for settings, something like:

```rs
pub trait AssetLoader: Send + Sync + 'static {
    type Settings: Default = ();
    /// Processes the asset in an asynchronous closure.
    fn load<'a>(
        &'a self,
        bytes: &'a [u8],
        load_context: &'a mut LoadContext,
        settings: Settings
    ) -> BoxedFuture<'a, Result<(), Error>>;

    /// Returns a list of extensions supported by this asset loader, without the preceding dot.
    fn extensions(&self) -> &[&str];
}
```

Then it can be used something like:

```rs
asset_server.load_with_settings("normal_map.png", {is_srgb: false, ..default()})
```

`aset_server.load()` could keep working like normal. This would break all existing asset loaders though.

**Comment by alice-i-cecile** [comment]
I prefer the latter solution. Breaking existing asset loaders is fine.

**Comment by mockersf** [comment]
I don't think those two solutions are possible without a *very* large refactor of `bevy_assets`. This will be done as part of https://github.com/bevyengine/bevy/discussions/3972

**Comment by mousetail** [comment]
If anyone comes across this issue this is how I solved it in the meantime:

```rs
use bevy::asset::{AssetLoader, Error, LoadContext, LoadedAsset};
use bevy::render::texture::{CompressedImageFormats, Image, ImageType};
use bevy::utils::BoxedFuture;

#[derive(Default)]
pub struct NormalMappedImageTextureLoader;

impl AssetLoader for NormalMappedImageTextureLoader {
    fn load<'a>(
        &'a self,
        bytes: &'a [u8],
        load_context: &'a mut LoadContext,
    ) -> BoxedFuture<'a, Result<(), Error>> {
        Box::pin(async move {
            // use the file extension for the image type
            let ext = load_context.path().extension().unwrap().to_str().unwrap();

            let dyn_img = Image::from_buffer(
                bytes,
                ImageType::Extension("png"),
                CompressedImageFormats::all(),
                false,
            )
            .unwrap();

            load_context.set_default_asset(LoadedAsset::new(dyn_img));
            Ok(())
        })
    }

    fn extensions(&self) -> &[&str] {
        &["norm"]
    }
}
```

Most of this code is copies verbatim from the normal texture loader.

This has the major disadvantage of requiring to change your textures to `.norm` extension.

**Comment by bonsairobo** [comment]
@mockersf Is this issue resolved by the ability to configure loader settings in asset metadata files?

**Comment by mockersf** [comment]
`is_rgb` is one of the field of the new [`ImageLoaderSettings`](https://docs.rs/bevy/latest/bevy/render/texture/struct.ImageLoaderSettings.html#structfield.is_srgb) so I would say yes, but didn't try it myself

**Comment by bonsairobo** [comment]
I can confirm this is fixed in my own app when I added the asset metadata files.
