### ISSUE TITLE
Vector component methods

### ISSUE THREAD

**Issue by sullyj3** [bevyengine/bevy#6399]
I'm happy to implement this if people like the idea.

## What problem does this solve or what need does it fill?

Make vector math code slightly more expressive/easier to understand.

## What solution would you like?

```rust
impl Vec3 {
    fn x_part(&self) -> Self {
        Vec3::new(self.x, 0.0, 0.0)
    }
    fn y_part(&self) -> Self {
        Vec3::new(0.0, self.y, 0.0)
    }
    fn z_part(&self) -> Self {
        Vec3::new(0.0, 0.0, self.z)
    }
}
```
And similar for other vector types. 

Usage code, before and after:
```rust
pub fn draw_aabbs(
    mut lines: ResMut<DebugLines>,
    q: Query<(&Transform, &AABB), With<DrawAABB>>,
) {
    for (transform, AABB { scale }) in q.iter() {
        // determine coordinates for drawing aabb
        let the_scale: Vec3 = scale.extend(0.);

        // before
        let top_left: Vec3 = transform.translation - the_scale / 2.;
        let top_right: Vec3 = top_left + the_scale.x * Vec3::X;
        let bottom_left: Vec3 = top_left + the_scale.y * Vec3::Y;
        let bottom_right: Vec3 = top_left + the_scale;
        
        // after
        let top_left: Vec3 = transform.translation - the_scale / 2.;
        let top_right: Vec3 = top_left + the_scale.x_part();
        let bottom_left: Vec3 = top_left + the_scale.y_part();
        let bottom_right: Vec3 = top_left + the_scale;

        lines.line_colored(top_left, top_right, 0.0, Color::GREEN);
        lines.line_colored(top_right, bottom_right, 0.0, Color::GREEN);
        lines.line_colored(bottom_right, bottom_left, 0.0, Color::GREEN);
        lines.line_colored(bottom_left, top_left, 0.0, Color::GREEN);
    }
}
```

## What alternative(s) have you considered?

- Not sure about the name. I was reluctant to go with `x_component` because 
  - it could cause confusion between vector components and ECS components. 
  - it's slightly longer
- Could introduce traits with the same methods:
  - `HasX`, implemented by `Vec2`, `Vec3`, `Vec4`
  - `HasY`, implemented by `Vec2`, `Vec3`, `Vec4`
  - `HasZ`, implemented by `Vec3`, `Vec4`
  - `HasW`, implemented by `Vec4`
- Perhaps I'm missing some existing part of the API which solves this better?
- Coping with having to do one little multiplication

**Comment by james7132** [comment]
This might be best upstreamed to `glam` instead of made to Bevy. bevy_math just reexports these types as is.

**Comment by sullyj3** [comment]
Ah I hadn't realized, cheers
