### ISSUE TITLE
Enabling transparency is cumbersome 

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#64]
Currently when using common materials like ColorMaterial and StandardMaterial, users need to remember to enable `draw.is_transparent`. This will be a common "foot gun" and it should really happen automatically if the color has an alpha component.

```rust
// currently this is required
world.spawn(NodeComponents {
    material: materials.add(Color::rgba(1.0, 0.9, 0.9, 0.4).into()),
    draw: Draw {
        is_transparent: true,
        ..Default::default()
    },
    ..Default::default()
})

// ideally the `0.4` alpha value results in alpha transparency
world.spawn(NodeComponents {
    material: materials.add(Color::rgba(1.0, 0.9, 0.9, 0.4).into()),
    ..Default::default()
})
```

**Comment by iMplode-nZ** [comment]
Yeah I just shot myself in the foot with this.

**Comment by mockersf** [comment]
would it be a good fix to have the default being transparent?

**Comment by cart** [comment]
Thats a good idea. It comes at the cost of "early fragment discarding" by default for obscured opaque object fragments, but in 2d fully opaque is less common.

At the very least it seems like a reasonable default for `NodeBundle` while we sort out more complicated solutions

**Comment by blaind** [comment]
For anyone wondering, this also applies to textures with alpha channel. 

The `Draw` component seems to have changed, and current iteration (comment in code that might be moved to materials eventually) works with modifying a Visible -component in a bundle (e.g. `PbrBundle`):

```rust
visible: Visible {
    is_transparent: true,
    ..Default::default()
},
```

**Comment by IceSentry** [comment]
Now that #4658 is merged I believe this can be closed.
