### ISSUE TITLE
Dynamic window abstraction

### ISSUE THREAD

**Issue by eliaspekkala** [bevyengine/bevy#641]
Bevy's window abstraction isn't very dynamic; it doesn't let you set window properties on demand like you can with Winit. This means you have to use the Winit API directly (though `WinitWindows`) to do things like mouse grabbing (see #614).

@cart [said](https://github.com/bevyengine/bevy/pull/614#issuecomment-703826532) the following about this issue:
> In the medium term, we need to revisit our Window abstraction and either:
> 1. Expose a way to easily / dynamically set window properties at runtime
> 2. Fully embrace Winit as our windowing abstraction (which implicitly means that we must extend Winit whenever we want to support new platforms, such as consoles). This is a pretty big commitment, so I'm pretty hesitant to do this. But it would certainly simplify the code / immediately expose a bunch of nice features.

**Comment by karroffel** [comment]
It seems like #644 is relevant here

**Comment by cart** [comment]
I just left some comments there about the various paths we can take.

**Comment by cart** [comment]
Closed by #644
