### ISSUE TITLE
Add `FromReflect::from_reflect_owned`

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#6419]
## What problem does this solve or what need does it fill?

Currently to apply a reflect value that was deserialized from bytes it copies all its fields. It would be nice to have an ability avoid this extra copy. For example, when doing networking and sending world state in a form of reflect - it could be a lot of extra copies.

## What solution would you like?

Add `from_reflect_owned` to `FromReflect` trait.

## Implementation strategy.

1. Add `ReflectOwned` enum with boxes like [`ReflectRef`](https://docs.rs/bevy/latest/bevy/reflect/enum.ReflectRef.html) to get owned version.
2. Add `reflect_owned` method to `Reflect` like [`reflect_ref`](https://docs.rs/bevy/latest/bevy/reflect/trait.Reflect.html#tymethod.reflect_ref) that returns `ReflectOwned` introduced above.
3. Use `drain` method from https://github.com/bevyengine/bevy/pull/5728 for arrays / maps and add owned versions of things like `Struct::field`.
4. Use all of the above to implement `from_reflect_owned` similar to non-owned version:
https://github.com/bevyengine/bevy/blob/aa8c74591bf539aa23778914b45e1231b0bc6426/crates/bevy_reflect/bevy_reflect_derive/src/from_reflect.rs#L132-L137

**Comment by alice-i-cecile** [comment]
Great writeup! This is a bit more advanced than most good-first-issues, but the detailed plan and existing methods to learn from should help a ton (assuming you're not planning to tackle this yourself).

**Comment by Shatur** [comment]
I think I could try to tackle if people like this suggestion.

**Comment by alice-i-cecile** [comment]
I like it a lot! The basic motivation is solid and the approach seems good.

**Comment by Shatur** [comment]
Having an issue with implementing `from_reflect_owned` for structs and tuples. `DynamicStruct` stores its elements inside `Vec`:
https://github.com/bevyengine/bevy/blob/aa8c74591bf539aa23778914b45e1231b0bc6426/crates/bevy_reflect/src/struct_trait.rs#L261
Non-owned version uses acess by index or field name:
https://github.com/bevyengine/bevy/blob/aa8c74591bf539aa23778914b45e1231b0bc6426/crates/bevy_reflect/src/struct_trait.rs#L262-L263
But in owned version I need to move out the value somehow. Can't figure out how to do it, so help is appreciated (just take a look at  `todo!()` in #6421).

**Comment by Shatur** [comment]
No longer interested in it, closing.
