### ISSUE TITLE
Mouse capture API

### ISSUE THREAD

**Issue by eliaspekkala** [bevyengine/bevy#642]
The pull request "[Add mouse capture example](https://github.com/bevyengine/bevy/pull/614)"  and the recipe "[Grabbing the mouse](https://github.com/jamadazi/bevy-cookbook/blob/master/bevy-cookbook.md#grabbing-the-mouse)" in the Bevy cookbook both illustrate how mouse capturing is done currently. It's done using the Winit API directly (though `WinitWindows`), which ties these Bevy apps to using Winit's backends.

Bevy should have a mouse capture API that lets us do the same thing, but on a higher level of abstraction that isn't tied directly to Winit.

In the short term, @cart is cool with adding more properties to the existing `WindowDescriptor` to unblock scenarios like mouse grabbing, but in the medium term one issue is that Bevy doesn't let you set window properties on demand like you can with Winit (see [comment](https://github.com/bevyengine/bevy/pull/614#issuecomment-703826532) and issue #641).

**Comment by cart** [comment]
Closed by #679
