### ISSUE TITLE
Fix double re-exports without hiding preludes

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6433]
## How can Bevy's documentation be improved?

Currently, we use `#[doc(hidden)]` on the prelude of each crate (and [bevy_internal](https://github.com/bevyengine/bevy/blob/main/crates/bevy_internal/src/prelude.rs)). 

Instead, we can use the [no_inline](https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html#inline-and-no_inline) property to solve this problem while still letting users browse what's in the preludes.

Before submitting a PR, validate this locally using `cargo doc`.

**Comment by pascualex** [comment]
Hi, I'll take this simple task as I want to start contributing to the project.

**Comment by alice-i-cecile** [comment]
Awesome, thanks!

**Comment by alice-i-cecile** [comment]
Doesn't work as intended. Needs to be reverted.

**Comment by alice-i-cecile** [comment]
This doesn't seem to have changed much for me, but the semantics are better?

**Comment by alice-i-cecile** [comment]
This doesn't work, see #6449.
