### ISSUE TITLE
Upgrade `notify` prerelease dependency `5.0.0-pre.15` -> `5.0.0`

### ISSUE THREAD

**Issue by mrchantey** [bevyengine/bevy#6434]
## Bevy version: 8.1

`bevy_asset` relies on a pre-release for `notify`, which creates dependency conflicts when using bevy in projects that also have a notify dependency.

It seems to be the only pre-release dependency in the bevy codebase, and AFIK we can't use dependency renaming to use prerelease versions alongside releases. The result is that I have been unable to publish my crate which depends on both `bevy` and `notify`, even using the prerelease version.

Let me know you'd like me to create a PR with the changes.

**Comment by mockersf** [comment]
a PR to update `notify` would be most welcomed 🙂

**Comment by mrchantey** [comment]
gah! i was on the `8.1` branch! sorry, its already been done.
