### ISSUE TITLE
Add default trait for HandleUntyped 

### ISSUE THREAD

**Issue by andrewhills** [bevyengine/bevy#6454]
## What problem does this solve or what need does it fill?

I prefer to use the HandleUntyped instead of Handle (which has implemented the default trait), so forces me to have implement the Default trait for every struct I use it in.

## What solution would you like?

Implement Default trait for HandleUntyped.

**Comment by harudagondi** [comment]
HandleUntyped could potential implement the Default trait, however [`HandleId`](https://docs.rs/bevy_asset/latest/bevy_asset/enum.HandleId.html#method.default) does not because it relies on the type of the Asset.

**Comment by andrewhills** [comment]
> HandleUntyped could potential implement the Default trait, however [`HandleId`](https://docs.rs/bevy_asset/latest/bevy_asset/enum.HandleId.html#method.default) does not because it relies on the type of the Asset.

Just noticed, not sure how go about implementing an unset HandleUntyped variable now.
