### ISSUE TITLE
Can cgpath be supported？

### ISSUE THREAD

**Issue by kotlin2018** [bevyengine/bevy#6455]
## What problem does this solve or what need does it fill?

A description of why this particular feature should be added.

## What solution would you like?

The solution you propose for the problem presented.

## What alternative(s) have you considered?

Other solutions to solve and/or work around the problem presented.

## Additional context

Any other information you would like to add such as related previous work,
screenshots, benchmarks, etc.

**Comment by james7132** [comment]
Do you mind providing more information about this? A quick google shows cgpath as being a Swift UI API? How would you imagine a Bevy integration here working?

**Comment by kotlin2018** [comment]
> Do you mind providing more information about this? A quick google shows cgpath as being a Swift UI API? How would you imagine a Bevy integration here working?

<img width="486" alt="截屏2022-11-14 下午3 54 44" src="https://user-images.githubusercontent.com/56008171/201604998-48aecbc5-c5ba-4dcb-98fc-d2020b176633.png">

**Comment by mockersf** [comment]
Bevy is using glam for math: https://crates.io/crates/glam

You can enable the `mint` feature on cgmath and glam to have compatibility between them, but cgmath won't be supported as first party.
