### ISSUE TITLE
`AppBuilder#add_asset_loader_from_instance` does not add handler in extension_to_handler_index properly

### ISSUE THREAD

**Issue by jornvandebeek** [bevyengine/bevy#647]
For a minimal repro, change the contents of the setup fn in `examples/asset/custom_asset_loading.rs`  to the following:

```rust
let data1_handle: Handle<MyCustomData> = asset_server.load("assets/data/test_data.data1").unwrap();
```

The `load` call will return an `MissingAssetHandler` error even though the `load_sync` call in the example worked fine. 

I did some research into this, apparently the `asset_server`'s `extension_to_handler_index` does not get an entry for the `data1` extension. This is because `TLoader::from_resources(self.resources())` on line 167 of assets.rs will construct a default instance of your loader (with empty extensions) instead of using the supplied one. 

I am unsure of the proper fix for this, since you need to add an instance to both the handler index and the loader index. Strangely, adding  `.add_resource::<DataFileLoader>(DataFileLoader::from_extensions(vec!["data1"]))` in my app builder does not help like I expected it to.

As a workaround you can return a static list of extensions in the AssetLoader fn extensions implementation for your custom asset loader so it will make a valid default implementation. An example can be found in  https://github.com/bevyengine/bevy/blob/master/crates/bevy_gltf/src/loader.rs . Then use `.add_asset_loader::<YourAsset, YourCustomLoader>()` instead of `add_asset_loader_from_instance`.

**Comment by mockersf** [comment]
Asset loading seems to have evolved and fixed this. At least the code mentioned here doesn't exist anymore and the scenario works
