### ISSUE TITLE
`clippy::as-ptr-cast-mut` warning in `From for ThinSlicePtr`

### ISSUE THREAD

**Issue by targrub** [bevyengine/bevy#6475]
## Bevy version

https://github.com/bevyengine/bevy/commit/c019a60b39c5683656025bc9d24a02744aa59dea

## What you did

Ran `cargo +nightly clippy --workspace --all-targets --all-features -Z unstable-options --keep-going -- -Aclippy::type_complexity -Wclippy::nursery -Aclippy::use_self -Aclippy::missing_const_for_fn -Aclippy::redundant_pub_crate -Aclippy::cognitive_complexity -Aclippy::branches_sharing_code -Aclippy::option_if_let_else -Aclippy::useless_let_if_seq -Aclippy::equatable_if_let -Aclippy::iter_with_drain -Aclippy::iter_on_single_items -Aclippy::iter_on_empty_collections -Aclippy::type_repetition_in_bounds -Aclippy::trait_duplication_in_bounds -Aclippy::fallible_impl_from -Aclippy::future_not_send -Aclippy::imprecise_flops -Aclippy::suboptimal_flops -Wclippy::doc_markdown -Wclippy::redundant_else -Wclippy::match_same_arms -Wclippy::semicolon_if_nothing_returned -Wclippy::explicit_iter_loop -Wclippy::map_flatten -Dwarnings`

## What went wrong

```
error: casting the result of `as_ptr` to *mut T
   --> crates\bevy_ptr\src\lib.rs:238:50
    |
238 |             ptr: unsafe { NonNull::new_unchecked(slice.as_ptr() as *mut T) },
    |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `slice.as_mut_ptr()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#as_ptr_cast_mut
    = note: `-D clippy::as-ptr-cast-mut` implied by `-D warnings`
```

from this code:

```rust
impl<'a, T> From<&'a [T]> for ThinSlicePtr<'a, T> {
    #[inline]
    fn from(slice: &'a [T]) -> Self {
        Self {
            // SAFETY: a reference can never be null
            ptr: unsafe { NonNull::new_unchecked(slice.as_ptr() as *mut T) },
            #[cfg(debug_assertions)]
            len: slice.len(),
            _marker: PhantomData,
        }
    }
}
```

**Comment by alice-i-cecile** [comment]
This is an easy change, I'd approve a PR that did this.

**Comment by hymm** [comment]
@alice-i-cecile I don't think the fix as suggested is right. It would require changing everything to take a `&mut [T]`. Not sure what the right fix is here. The API's for `ThinSlicePtr` don't seem to allow getting a &mut [T] back out of the `ThinSlicePtr`, so at least there isn't any UB. The only reason we need a `*mut T` is to satisfy the API for making a NonNull.

**Comment by alice-i-cecile** [comment]
Hmm, right. Okay, closing this out.

**Comment by hymm** [comment]
> Notice that NonNull<T> has a From instance for &T. However, this does not change the fact that mutating through a (pointer derived from a) shared reference is undefined behavior unless the mutation happens inside an [UnsafeCell<T>](https://doc.rust-lang.org/stable/std/cell/struct.UnsafeCell.html). The same goes for creating a mutable reference from a shared reference. When using this From instance without an UnsafeCell<T>, it is your responsibility to ensure that as_mut is never called, and as_ptr is never used for mutation.

^^ Looking at the docs for NonNull. We could potentially change to `NonNull::from(&*slice.as_ptr())`.
