### ISSUE TITLE
`clippy::future-not-send` in `Task<T>::cancel()`

### ISSUE THREAD

**Issue by targrub** [bevyengine/bevy#6477]
## Bevy version

https://github.com/bevyengine/bevy/commit/c019a60b39c5683656025bc9d24a02744aa59dea

## What you did

Ran `cargo +nightly clippy --workspace --all-targets --all-features -Z unstable-options --keep-going -- -Aclippy::type_complexity -Wclippy::nursery -Aclippy::use_self -Aclippy::missing_const_for_fn -Aclippy::redundant_pub_crate -Aclippy::cognitive_complexity -Aclippy::branches_sharing_code -Aclippy::option_if_let_else -Aclippy::useless_let_if_seq -Aclippy::equatable_if_let -Aclippy::iter_with_drain -Aclippy::iter_on_single_items -Aclippy::iter_on_empty_collections -Aclippy::debug_assert_with_mut_call -Aclippy::as_ptr_cast_mut -Aclippy::type_repetition_in_bounds -Aclippy::trait_duplication_in_bounds -Aclippy::fallible_impl_from -Aclippy::imprecise_flops -Aclippy::suboptimal_flops -Wclippy::doc_markdown -Wclippy::redundant_else -Wclippy::match_same_arms -Wclippy::semicolon_if_nothing_returned -Wclippy::explicit_iter_loop -Wclippy::map_flatten -Dwarnings`.

## What went wrong

```rust
error: future cannot be sent between threads safely
  --> crates\bevy_tasks\src\task.rs:41:34
   |
41 |     pub async fn cancel(self) -> Option<T> {
   |                                  ^^^^^^^^^ future returned by `cancel` is not `Send`
   |
note: future is not `Send` as this value is used across an await
  --> crates\bevy_tasks\src\task.rs:42:24
   |
42 |         self.0.cancel().await
   |         ------         ^^^^^^ await occurs here, with `self.0` maybe used later
   |         |
   |         has type `async_executor::Task<T>` which is not `Send`
43 |     }
   |     - `self.0` is later dropped here
   = note: `T` doesn't implement `std::marker::Send`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#future_not_send
   = note: `-D clippy::future-not-send` implied by `-D warnings`
```

**Comment by 2ne1ugly** [comment]
Future here is `Send` only if `T: Send` which sounds reasonable.
The future of `async_executor::Task<T>::cancel` is also `Send` if `T: Send`
(It fails the same clippy check)

Does this check actually cause any problem?
Not sure if this issue is solvable 🤔

**Comment by hymm** [comment]
This seems like a false positive. We have spawn_local for spawning !Send futures, which would give back a !Send Task if T is !Send.

**Comment by mockersf** [comment]
I agree on the false positive here 👍
