### ISSUE TITLE
Gamepad input not working for DualSense (PS5) controller

### ISSUE THREAD

**Issue by Lisieshy** [bevyengine/bevy#6555]
## Bevy version

Tested both v0.8.1 and commit c3c4088317f0ea09de8d96e22fa5beb28e486c30 of bevy

## What you did

Running the official gamepad input examples of bevy

`cargo run --example gamepad_input` and `cargo run --example gamepad_input_events`

plugging and unplugging my controller and pressing buttons.

## What went wrong

Controller doesn't log anything in the terminal when pressing buttons or connecting/disconnecting it.

## Additional information

Tested with the official example from gilrs repo and it works perfectly fine, outputs as expected when gilrs is standalone.

**Comment by alice-i-cecile** [comment]
That's very strange that this is working for gilrs but not here. The translation layer is very simple.

Are you sure you were testing the version of gilrs that we're currently using?

**Comment by Lisieshy** [comment]
That's my bad, it does not work with versions earlier than 0.10 of gilrs!

**Comment by alice-i-cecile** [comment]
Leaving this open until we bump that version then :)
