### ISSUE TITLE
Multiple Animations on the same Mesh/Skeleton which can run Simultaneously.

### ISSUE THREAD

**Issue by Xzenotrex** [bevyengine/bevy#6562]
## What problem does this solve or what need does it fill?

Meshes and skeletons should be able to run multiple animations simultaneously, providing the animations do not overlap. For example imagine a player model/skeleton - you may want a lower-body running animation and an upper-body throwing animation happening at the same time.

## What solution would you like?

A solution could be something similar to the Unity Animation Layer system:

- Layers are used to seperate different animations on the same skeleton
- Masks are used on each layer to specify which bones each animation applies to - this ensures animations don't overlap and cause issues.

## What alternative(s) have you considered?

You could seperate the mesh into multiple parts and then load the seperate meshes into bevy, however this is unwieldy and may cause issues in some scenarios.

**Comment by james7132** [comment]
This is already (partially) proposed via https://github.com/bevyengine/rfcs/pull/51, which builds out a set of components that allows for higher level blending. Feedback on that RFC would be much appreciated.

**Comment by Xzenotrex** [comment]
I had a look at that RFC earlier - looks really good! Would this be covered under something with the animation blending then?

**Comment by james7132** [comment]
Animation masking technically does, and it's not 100% covered by that RFC, but it is something we could build on top of it.

**Comment by Xzenotrex** [comment]
Ah okay, I'm guessing something like this is probably quite far off then, at least until things layed out in RFC 49 and 51 have been implemented.

**Comment by Xzenotrex** [comment]
Closing for now as it seems far off / covered by RFCs.

**Comment by james7132** [comment]
I'd actually rather keep this open since it's a reasonable feature request, even if it will take a bit of time to tackle. It should help us keep track of the goals and discussion for it and also deters other duplicate issues.

**Comment by Xzenotrex** [comment]
Ah okay sounds good👍

**Comment by james7132** [comment]
I don't think it's possible to tackle this in the 0.12 dev cycle, going to defer this to 0.13.

**Comment by lee-orr** [comment]
Is this resolved with #11670?

**Comment by james7132** [comment]
Yep it is! Closing this out.
