### ISSUE TITLE
Warning has incorrect link

### ISSUE THREAD

**Issue by DasLixou** [bevyengine/bevy#6565]
this is a thing between a `Issue: Docs Improvement` and `Issue: Bug Report` but i've chosen Docs Improvement.

so i've got this warning:
```
2022-11-12T19:09:04.160915Z  WARN bevy_hierarchy::valid_parent_check_plugin: warning[B0004]: An entity with the ComputedVisibility component has a parent without ComputedVisibility.
This will cause inconsistent behaviors! See https://bevyengine.org/learn/errors/#B0004
```

but when i visit this page there are only errors from 0001 to 0003. this should be readded or the link should be fixed.

**Comment by DasLixou** [comment]
This also applies to ComputedTransform error

**Comment by nicopap** [comment]
I think the error page will be generated once bevy 0.9 is published. This error was added in 0.9, this is why the page is not yet accessible.

**Comment by DasLixou** [comment]
:o that makes sense
