### ISSUE TITLE
Add a screen shake effect

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#6569]
## What problem does this solve or what need does it fill?

Adds a nice effect to games.

## What solution would you like?

Add some kind of component or animation to a Camera to add a screen shake.

## Additional context

See also: https://shaggydev.com/2022/02/23/screen-shake-godot/

**Comment by soqb** [comment]
there is already [bevy_camera_shake](https://github.com/andrewp2/bevy_camera_shake/tree/6915da96652d4453fa220fa5b5049e5df5c45b0b/) for 0.8.1 but with the 0.9 release on the horizon it looks like it could do with an update.

**Comment by soqb** [comment]
this definitely feels like it fits an ecosystem implementation rather than something in Bevy itself. [Unreal](https://docs.unrealengine.com/4.27/en-US/AnimatingObjects/Sequencer/Cameras/CameraShakes/) is the only engine I can find which provides builtin camera shake. Unity and Godot both leave it up to the user.

**Comment by james7132** [comment]
Going to second the opinion that this is ideal for an ecosystem crate solution. Not every game needs it and the implementation is relatively simple to maintain separately from the core engine. Might even be doable via just normal animation systems or user-made game code.

**Comment by Weibye** [comment]
> this definitely feels like it fits an ecosystem implementation

Agreed. Bevy would need to have quite extensive video-sequencing and camera tools in-house before it starts to make sense to first-party supply camera effects.

**Comment by JMS55** [comment]
Related: https://github.com/bevyengine/bevy/issues/15564
