### ISSUE TITLE
Seg Fault on MacOs

### ISSUE THREAD

**Issue by roboteng** [bevyengine/bevy#6576]
## Bevy version

0.9.0

## \[Optional\] Relevant system information

MacOS version: 13.0.1 (22A400)
Intel i7 (not M1/M2)

Rust version:
`rustc 1.65.0 (897e37553 2022-11-02)`

## What you did

I found this on a more complicated program, but I found the same seg fault on this:

```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run();
}
```

## What went wrong

It runs, but crashes in runtime, and gives this error:
```
Finished dev [optimized + debuginfo] target(s) in 1.70s
     Running `target/debug/bevy_test`
[1]    45941 segmentation fault  cargo run
```
- what were you expecting?

To show the basic window

- what actually happened?

A segfault

## Additional information

if `MinimalPlugins` is used instead, then everything works as expected. It's obviously something that is specific to `DefaultPlugins`

Additionally, I was able to run bevy 0.8.1 fine, but I ran into this issue when switching to 0.9.0

I did some quick searches in winit's and wgpu's repos, and didn't see anything related to seg faults

I'm not 100% sure what commands I can run to get more information, but I'll try what people suggest

**Comment by james7132** [comment]
Can you try to narrow down which potential plugin is causing this? `DefaultPlugins` includes quite a few items that could be causing this crash.

**Comment by superdump** [comment]
Could you run bevy in a debugger and get a backtrace of where it segfaults?

**Comment by roboteng** [comment]
The issue seems to be in the `RednerPlugin`

```rust
use bevy::{prelude::*, render::RenderPlugin, window::WindowPlugin};

fn main() {
    App::new()
        .add_plugin(WindowPlugin::default())
        .add_plugin(AssetPlugin::default())
        .add_plugin(RenderPlugin)
        .run();
}
```

This seg faults, but if I comment out the `RenderPlugin` line, then it doesn't. I'll try and look into this some more, but I haven't touched these plugins before

**Comment by sambriels** [comment]
I can reproduce the seg fault on macOS 13.0.1 with bevy `0.9.0` and can also confirm it does not occur on bevy `0.8.1`. 

If I turn off any optimisations for packages 
```
[profile.dev.package."*"]
opt-level = 1
```
it the seg fault does not occur. @roboteng could you give that a try and see if that is also the case for you?

I am trying to disable optimisation for specific packages to track down the issue in more detail, but so far I have not been able to get it working without setting the `opt-level = 1` for every package. I will try to delve deeper once I get some free time.

I also tried stepping through the code with the debugger, and noticed that the seg fault sometimes does not occur then. So there may be a race condition somewhere. The error seems to occur while gathering and handling the device adapters. I just started out with bevy and rust, so my knowledge is a bit limited. If anyone has any additional pointers to solutions I am all for trying them.

**Comment by mockersf** [comment]
does it segfault also with `--release`?

**Comment by sambriels** [comment]
No seg fault when running with `--release` either. I did notice that eventhough it does not seg fault, no window is actually spawned. This is also the case in the optimised regular `cargo dev` run. I am not sure what other plugins need to be added as a minimum to actually spawn a window though.

**Comment by roboteng** [comment]
Hmm, it seems like it's been fixed. Using just the `DefaultPlugins` I don't get the error anymore. When I tried with `WIndowPlugin`, `AssetPlugin`, and `RenderPlugin`, I still got an error, but the main point of using `DefaultPlugins` seems to be fixed. Doing a simple `cargo run` vs `cargo run --release` doesn't make a difference either, currently. I think there may still be some issues if you don't include all the correct plugins, but that seems expected to me

**Comment by 1moeses** [comment]
Still not fixed for me on Mac (Ventura 13.0.1, 2019). I get segfaults with `--release` and
```toml
[profile.dev.package."*"]
opt-level = 3
```

Cargo.toml:
```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 1

[dependencies]
bevy = { version = "0.9.1", features = ["dynamic"] }
bevy-inspector-egui = "0.14.0"
```

Min example:
```rs
use bevy::{prelude::*, render::RenderPlugin};

fn main() {
    App::new()
        .add_plugins(MinimalPlugins)
        .add_plugin(WindowPlugin::default())
        .add_plugin(AssetPlugin::default())
        .add_plugin(RenderPlugin)
        .add_plugin(ImagePlugin::default())
        .run();
}
```
This example runs fine without the `--release' flag.

**Comment by AxiomaticSemantics** [comment]
This one sounds like a compiler bug to me(My gut is saying it's somewhere deep inside of LLVM), which is way more concerning than just being a bevy bug, this is also why I rarely optimize at level 3(unless it's been well tested against level 2 compiled bins), I think what should probably be done is that the docs should be updated to suggest a more conservative optimization level of either 2 or z with the suggested optimized debug builds.

**Comment by AxiomaticSemantics** [comment]
> Still not fixed for me on Mac (Ventura 13.0.1, 2019). I get segfaults with the `--release` flag and
> ```toml
> [profile.dev.package."*"]
> opt-level = 3
> ```
> But this example runs fine without the `--release` flag and without `opt-level = 3`:

Does this also happen with just a minimal `App::new().run();`? Does it happen with non-bevy projects compiled with such a configuration to optimize dev deps?

**Comment by 1moeses** [comment]
> Does this also happen with just a minimal `App::new().run();`? Does it happen with non-bevy projects compiled with such a configuration to optimize dev deps? What CPU architecture? One user noted it's only with optimizations but disabled RenderPlugin, can you confirm it only happens with O3 and RenderPlugin?

Thank you very much for you reply. You're right. It's definitely the render plugin. I must have overlooked that. I get everything compiled: a simple "Hello World", your minimal example and my example above - without the render plugin. With the RenderPlugin enabled I get a seg fault.

My specs:
MacOS Ventura 13.0.1.16 inch, 2019
CPU: 2.4GHz 8-core Intel Core i9
GPU: AMD Radeon Pro 5600M 8GB
Memory: 32GB 2667MHz DDR4

**Comment by 1moeses** [comment]
Seems fixed 🤷‍♀️ I no longer get this error with Rust 1.67.0. Can anyone reproduce it?

**Comment by Patryk27** [comment]
fwiw, when a shader is instantiated, Mac compiles it asynchronously in the background using MTLCompilerService - and I've found out that this shader-compiler is... pretty flake'y - it can easily segfault even on simple shaders.

To narrow down the issue, if it happens again, one could open `Console.app` and look for logs from that service - on my machine (M1 Pro) it likes to crash with something akin to `generated non-G1 instruction for G1`.

**Comment by roboteng** [comment]
Yeah, I just tried running the breakout bevy example, and that worked without modification. My test project works now too. I'm not sure what fixed it, but I think we can close this
