### ISSUE TITLE
Setting cursor grab mode causes errors to be printed with no way to handle it

### ISSUE THREAD

**Issue by IceSentry** [bevyengine/bevy#6590]
## Bevy version

0.9 and latest

## What you did

Ran the mouse_grab example.

## What went wrong

When pressing the left button, winit does successfully set the grab mode, but bevy prints an error message:

> ERROR bevy_winit: Unable to un/grab cursor: the requested operation is not supported by Winit

In the example this happens only once because it's behind a condition, but if you run it unconditionally in a system it will print this every frame even when the cursor is clearly locked/unlocked. In other words the feature clearly is supported yet winit reports an error.

The main issue here is that we can't get the result from winit and handle it user side. Ignoring the error in bevy wouldn't be ideal either, but that means an unavoidable error message for anyone that uses this api.

## Relevant system information

Windows 10

**Comment by IceSentry** [comment]
After a bit more investigation, it seems to be that `CursorGrabMode::Locked` is not supported, but `CursorGrabMode::Confined` is. This should probably be documented somewhere since it seems it falls back to Confined when Locked isn't supported but it still reports it as Locked when using `window.cursor_grab_mode()`

**Comment by BlackPhlox** [comment]
Yeah, the un/grab is now an enum, and I think that CursorGrabMode::Locked is not supported for winit as of yet, we should change it to `Confined` for the moment

**Comment by IceSentry** [comment]
To add a bit more detail, `CursorGrabMode::Locked` is supported in macOS but not Windows, `CursorGrabMode::Confined` is supported by windows but not macOS. On windows setting it to Locked will silently treat it as Confined and spam the error message but keep working correctly and report it as `CursorGrabMode::Locked` even if internally it isn't using it.

We should at least document this behaviour.

**Comment by BlackPhlox** [comment]
CursorGrabMode works almost functionally the same. It is only relevant if you wanna see the mouse and or when you ungrab that determines the mouse position. I would put this at warning log-level at most and include that it does a fallback.

**Comment by alice-i-cecile** [comment]
Punting to 0.10 as I'm unsure how to solve this effectively.

**Comment by IceSentry** [comment]
My current fix is semver compatible so it could be in 0.9.1. At the very least I think we should update the docs to explain the issue and maybe add a snippet to show how to make it cross platform.
