### ISSUE TITLE
Make `Size::new` const

### ISSUE THREAD

**Issue by bzm3r** [bevyengine/bevy#6594]
## What problem does this solve or what need does it fill?

It is often useful to implement a `const` `Size` for a widget. But, one cannot use `Size::new` to define this `const`...

## What solution would you like?

Make `Size::new` const.

**Comment by alice-i-cecile** [comment]
In general, we should be making methods like this const wherever possible. If we're unlikely to change it in the future to make it non-const, and it *can* be const, it should be const IMO.
