### ISSUE TITLE
Bevy 0.9 UI Style Documentation still claims Flexbox is upside down 

### ISSUE THREAD

**Issue by mwbryant** [bevyengine/bevy#6606]
The docs for [Style](https://docs.rs/bevy/latest/bevy/ui/struct.Style.html) still claim: 

> Note: Bevy’s UI is upside down compared to how Flexbox normally works, to stay consistent with engine paradigms about layouting from the upper left corner of the display

This is untrue as of Bevy 0.9 as I understand it

**Comment by imustend** [comment]
I can do that 👍
