### ISSUE TITLE
How to use query sets in version 0.9.0

### ISSUE THREAD

**Issue by kotlin2018** [bevyengine/bevy#6613]
## How can Bevy's documentation be improved?

Provide a link to the documentation and describe how it could be improved. In what ways is it incomplete, incorrect, or misleading?

If you have suggestions on exactly what the new docs should say, feel free to include them here. Or alternatively, make the changes yourself and [create a pull request](https://bevyengine.org/learn/book/contributing/code/) instead.

**Comment by rparrett** [comment]
It would be nice to have internal documentation for `ParamSet` which replaced `QuerySet` in Bevy 0.7.

Here's a third party resource that describes how to use it: <https://bevy-cheatbook.github.io/programming/paramset.html>

See the following migration guides if you're updating an older project.

https://bevyengine.org/learn/book/migration-guides/0.6-0.7/
https://bevyengine.org/learn/book/migration-guides/0.7-0.8/
https://bevyengine.org/learn/book/migration-guides/0.8-0.9/

**Comment by kotlin2018** [comment]
> It would be nice to have internal documentation for `ParamSet` which replaced `QuerySet` in Bevy 0.7.
> 
> Here's a third party resource that describes how to use it: https://bevy-cheatbook.github.io/programming/paramset.html
> 
> See the following migration guides if you're updating an older project.
> 
> https://bevyengine.org/learn/book/migration-guides/0.6-0.7/ https://bevyengine.org/learn/book/migration-guides/0.7-0.8/ https://bevyengine.org/learn/book/migration-guides/0.8-0.9/

Thank you very much

**Comment by james7132** [comment]
Next time, if you have a question, please use [Discussions](https://github.com/bevyengine/bevy/discussions) instead of issues. They're better suited for general questions than issues.
