### ISSUE TITLE
When we draw Quad with Mesh and then draw other sprite in the same Z-coordinate the result is uncertain

### ISSUE THREAD

**Issue by lishaoxia1985** [bevyengine/bevy#6628]
## Bevy version
Bevy version is 0.9, platform is window 10, GPU is Nvidia Geforce mx250, driver is 516.40
## Bug
If you use the code below, when we draw Quad with Mesh and then draw other sprite in the same Z-coordinate the result is uncertain
```
let pentagon = Quad::new(Vec2 { x: 100., y: 100.});
let handle = meshes.add(Mesh::from(pentagon));
commands.spawn(ColorMesh2dBundle {
        mesh: handle.into(),
        transform: Transform::from_translation(Vec3::new(0., 0., 1.)),
        ..default()
    });

commands.spawn(SpriteBundle {
        sprite: Sprite {
            color: Color::rgb(0.25, 0.25, 0.75),
            custom_size: Some(Vec2::new(150.0, 100.0)),
            ..default()
        },
        transform: Transform::from_translation(Vec3::new(0., 0., 1.)),
        ..default()
    });
```
Sometimes it only shows blue rectangle, sometimes it shows purple and blue rectangles.
You can try to build more and more times.

**Comment by devil-ira** [comment]
The Z coordinate is the only tool in this scenario that decides what renders in front/behind.
If it's the same as another item then the computer can't figure it out and floating point imprecision decides for you.

You will have to decide which one you want to render on top of the other by changing their Z translation.

**Comment by lishaoxia1985** [comment]
@devil-ira Do you mean that it's not a bug?
The dos should Give some hints or message.
You mean that the method to solve this problem is give the different bundle with different Z translation, have i got it?
I test if you use the same type bundle in the same Z translation the problem will disappear.
If you are right, you can close this issue.

**Comment by mockersf** [comment]
Drawing overlapping polygons at the same distance of the camera (in 2d case, with the same z translation) is called Z-Fighting.

The engine could render them in the same order, but it would be slower, and it can't work as you expect. In a way it's better to keep it random to avoid thinking "oh it's working fine, let's stay like that". The correct fix is to use different value for each "layer" you have.

**Comment by devil-ira** [comment]
> I test if you use the same type bundle in the same Z translation the problem will disappear.

This behavior is a coincidental result of entity iteration order. While this order is deterministic it's no longer predictable when you start despawning entities.

> The result of commands.spawn() should be certain.

It is certain; the entity spawned is identical. The randomness comes from somewhere else.

Like mockersf said, we could make this consistent, but there's no point because it would still be unpredictable.

Bevy is not unique in this regard. The situation in Unity and Godot is the same.

**Comment by lishaoxia1985** [comment]
@devil-ira @mockersf Thank you very much, I get it.
