### ISSUE TITLE
Add a variant of `spawn` that returns the spawned entity's ID

### ISSUE THREAD

**Issue by JoJoJet** [bevyengine/bevy#6635]
## What problem does this solve or what need does it fill?

A very common pattern for spawning entities looks like this:

```rust
let id = commands
    .spawn((
        Transform::default(),
        GlobalTransform::default(),
    ))
    .id();
```

The `.id()` call makes rustfmt add an extra level of indentation, which makes the code worse.

## What solution would you like?

Add a variant of `spawn` that returns the spawned entity's ID:

```rust
let id = commands.spawn_with_id((
    Transform::default(),
    GlobalTransform::default(),
));
```

## What alternative(s) have you considered?

Instead of adding a new method, change `spawn` to return the entity's ID. I do not like this solution, since it would get in the way if you want to use `EntityCommands`.

**Comment by HugoPeters1024** [comment]
I agree with this proposal, but I would say that `spawn_with_id` is not an ideal name, because it suggests that one of the arguments is the id. Perhaps `spawn_get_id`?

**Comment by JoJoJet** [comment]
Bikeshed: what about just `spawn_entity`? It's shorter and refects that it returns an `Entity`, although I suppose it may feel kinda arbitrary.

**Comment by alice-i-cecile** [comment]
Echoing my thoughts from the linked PR: I don't like the addition of this method. It's a common pattern, but this doesn't make anything clearer or much shorter and adds multiple ways to do the same thing.

**Comment by JoJoJet** [comment]
Closing this out since it seems unpopular.
