### ISSUE TITLE
Bevy 0.9 apps can not compile

### ISSUE THREAD

**Issue by MeaterBeater27** [bevyengine/bevy#6638]
## Bevy version
0.9.0

## \[Optional\] Relevant system information
Windows 10 Pro 
version 21H1

## What you did
![image](https://user-images.githubusercontent.com/92642398/202015022-09329bad-6589-4422-b405-f869e231d2a8.png)
![image](https://user-images.githubusercontent.com/92642398/202015130-4f9b4dd8-2328-447f-a1c2-614a89a69fd2.png)

## What went wrong
On all of my projects I get the same error when compiling.
![image](https://user-images.githubusercontent.com/92642398/202015438-11a0e183-bad7-4fb2-b9d7-5c5bfae1bf3d.png)

**Comment by IceSentry** [comment]
You need to compile bevy using the latest version of rustc which is currently 1.65

**Comment by alice-i-cecile** [comment]
Easy mistake to make, and I'm glad this issue exists so others can search it. Closing it out; feel free to open it back up if this doesn't resolve your problem.

**Comment by miketwenty1** [comment]
if you're like me `rustup update` did the trick for me.
