### ISSUE TITLE
KeyCode::D not being detected among other keys

### ISSUE THREAD

**Issue by Dworv** [bevyengine/bevy#6652]
## Bevy version

0.9.0

## \[Optional\] Relevant system information

OS X 12.1

## What you did

I am detecting multiple key presses at a time using `Input<KeyCode>`.

## What went wrong

While pressing multiple keys at a time, and my D key isn't working when multiple other keys are being pressed. For example, when it is pressed while holding `C` and `N`, it isn't detected as being pressed. It seems like on other apps, the D key works normally.

**Comment by alice-i-cecile** [comment]
Can you debug this further with https://github.com/bevyengine/bevy/blob/main/examples/input/keyboard_input_events.rs ?

Does the same effect occur with other keys? Seems likely to be a hardware or driver issue 🤔

**Comment by Dworv** [comment]
I was attempting to debug it by pressing the buttons while printing the `Input` object.
```
println!("{:?}", keyboard_input);
```

After further investigation, it seems like it isn't only D that is inconsistent with other keys. There doesn't seem to be any pattern, but some patterns seem to disallow certain other keys from working. I'm not sure why.

**Comment by Dworv** [comment]
Actually, I see that uses `EventReader` instead of `Input`. I could try that.

**Comment by Dworv** [comment]
Yeah, its returning the same thing. Didn't fix it.

**Comment by devil-ira** [comment]
This is likely a hardware issue called keyboard ghosting.
You can test your keyboard on this page: https://drakeirving.github.io/MultiKeyDisplay/.

**Comment by Dworv** [comment]
Interesting, it seems like mac os keyboard behaviour is just unusual.
