### ISSUE TITLE
`Directional Light`'s computed_visiblity becomes false when it becomes children of `Camera`.

### ISSUE THREAD

**Issue by AllenDang** [bevyengine/bevy#6660]
## Bevy version

0.9.0

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
  - cargo 1.65.0 (4bc8f24d3 2022-10-20)
- the operating system or browser used, including its version
  - macOS 13.0

## What you did

I created a DirectionalLightBundle as children of CameraBundle like below.

```rust
    let translation = Vec3::new(-2.0, 2.5, 5.0);
    let radius = translation.length();

    commands
        .spawn((
            Camera3dBundle {
                transform: Transform::from_translation(translation).looking_at(Vec3::ZERO, Vec3::Y),
                ..default()
            },
            camera_control::PanOrbitCamera {
                radius,
                ..default()
            },
        ))
        .with_children(|parent| {
            parent.spawn(DirectionalLightBundle {
                directional_light: DirectionalLight {
                    shadows_enabled: true,
                    ..default()
                },
                transform: Transform::from_translation(Vec3::new(5.0, 5.0, 5.0))
                    .looking_at(Vec3::ZERO, Vec3::Y),
                ..default()
            });
        });
```

## What went wrong

Directional light's computed_visibility becomes false which makes it doesn't work.

- what were you expecting?

Directional light works as normal.

## Additional information

![image](https://user-images.githubusercontent.com/18550/202394917-6d90d0a0-7ec3-4292-9ce5-3bda8f8de7a1.png)

**Comment by nicopap** [comment]
Did you get any warning messages in the console when running your game? This looks like [B0004](https://bevyengine.org/learn/errors/#B0004)

**Comment by mockersf** [comment]
https://bevyengine.org/learn/errors/#b0004 (not `B` in the link, it needs to be lowercase)

**Comment by AllenDang** [comment]
This should not be closed. I added a ComputedVisibility Component to Camera, warning message is gone, but since it's the main camera, it still remain invisible and the children remains invisible too.

**Comment by AllenDang** [comment]
Here is the code.
```rust
    commands
        .spawn((
            Camera3dBundle {
                transform: Transform::from_translation(translation).looking_at(Vec3::ZERO, Vec3::Y),
                ..default()
            },
            camera_control::PanOrbitCamera {
                radius,
                ..default()
            },
            ComputedVisibility::default(),
        ))
        .with_children(|parent| {
            parent.spawn(DirectionalLightBundle {
                directional_light: DirectionalLight {
                    shadows_enabled: true,
                    ..default()
                },
                transform: Transform::from_translation(Vec3::new(5.0, 5.0, 5.0))
                    .looking_at(Vec3::ZERO, Vec3::Y),
                ..default()
            });
        });
```

**Comment by AllenDang** [comment]
@nicopap Might need to reopen this?

**Comment by nicopap** [comment]
Note: B0004 recommends adding a `SpatialBundle` to the parent entity. However, following the advice for this particular situation since 0.9 **will result in a panic** because both `Camera3dBundle` and `SpatialBundle` add the `GlobalTransform` and `Transform` components (see #6622).

Following this, user AllenDang decided to replace `SpatialBundle` with the `ComputedVisibility` component. But for visibility propagation to work, both `ComputedVisibility` and `Visibility` components must be present. Hence, the child light was still invisible.

The fix was to add `VisibilityBundle`  to the parent, rather than `SpatialBundle` or `ComputedVisibility` alone.

* #6622
