### ISSUE TITLE
Mouse cursor locks while press any key

### ISSUE THREAD

**Issue by nizovtsevnv** [bevyengine/bevy#6678]
## Bevy version
0.9.0

## What you did

Add a system with `EventReader<MouseMotion>` and getting events in a loop:
```
for event in mouse_motion_input.iter() {
  ...
}

```

## What went wrong

If I press any key this loop halts until key will be released.

**Comment by alice-i-cecile** [comment]
What OS are you on? Are you on a laptop? Can you reproduce this outside of Bevy?

 I've seen similar problems before with a setting where touchpads are disabled while keyboards are in use.

**Comment by mockersf** [comment]
can't reproduce on macOS

**Comment by nizovtsevnv** [comment]
> What OS are you on? Are you on a laptop? Can you reproduce this outside of Bevy?
> 
> I've seen similar problems before with a setting where touchpads are disabled while keyboards are in use.

OS: Fedora Linux v36, v37 with Gnome v43 desktop environment.
Compiler: rustc 1.65.0 (897e37553 2022-11-02)
PM: cargo 1.65.0 (4bc8f24d3 2022-10-20)

P.S.:
Keys like Ctrl/Alt/Shift/CapsLock/Tab.. doesn't halt the mouse, the issue only with alphanumeric input (WASD doesn't work with mouse, but arrow keys works)

**Comment by nizovtsevnv** [comment]
> can't reproduce on macOS

I tried on MacOS and there is no problem with it.

**Comment by alice-i-cecile** [comment]
Hmm. Can you reproduce this upstream in `winit`? I can't reproduce this on PopOs.

**Comment by nizovtsevnv** [comment]
> Hmm. Can you reproduce this upstream in `winit`? I can't reproduce this on PopOs.

Only if you can help me with source code, I'm a newbuy in rust and game dev )

**Comment by nizovtsevnv** [comment]
Finally I found the reason and the solution :)

Reason of this issue is on touchpad option: `libinput Disable While Typing Enabled Default`.

**Solutions:**
- remove this option via `xinput set-prop`
- or use a mouse
