### ISSUE TITLE
Gltf scene is not properly rendered.

### ISSUE THREAD

**Issue by AllenDang** [bevyengine/bevy#6679]
## Bevy version

0.9.0

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
  - cargo 1.65.0 (4bc8f24d3 2022-10-20)
- the operating system or browser used, including its version
  - macOS 13.0

## What you did

Load a gltf scene from file.

## What went wrong

- what were you expecting?
  The whole scene should be rendered properly.
  Here is the screen shot from https://gltf-viewer.donmccurdy.com/
  
<img width="958" alt="image" src="https://user-images.githubusercontent.com/18550/202685190-af1f0643-87a2-44ed-a1e5-158d7c28cdaa.png">

- what actually happened?
  Only one model is rendered.
  
![image](https://user-images.githubusercontent.com/18550/202685373-c4bb3bcc-b06c-4729-be51-f7053b963bcd.png)

## Additional information

Here is a minimal code to reproduce. Make sure to enable "jpeg" feature for bevy in `Cargo.toml`.

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

/// set up a simple 3D scene
fn setup(mut commands: Commands, server: ResMut<AssetServer>) {
    // load asset
    commands.spawn((SceneBundle {
        scene: server.load("/Users/allen/Downloads/shu.glb#Scene0"),
        ..default()
    },));

    // camera
    commands.spawn(Camera3dBundle {
        transform: Transform::from_xyz(-2.0, 2.5, 5.0).looking_at(Vec3::ZERO, Vec3::Y),
        ..default()
    });
}
```

Here is the gltf model to repo.
[shu.glb.zip](https://github.com/bevyengine/bevy/files/10040514/shu.glb.zip)

**Comment by AllenDang** [comment]
@alice-i-cecile I know the core dev of bevy may not have time to fix it now, I'm wondering if you or anyone could give me a hint about where should I start to look at, I could start fixing this and contribute a PR.

**Comment by alice-i-cecile** [comment]
This looks like a gltf file with multiple sub-scenes. Have you tried changing or removing `#scene0`?

**Comment by AllenDang** [comment]
@alice-i-cecile Removing #scene0 still the same.

**Comment by alice-i-cecile** [comment]
And changing it to e.g. #scene1? Does that change what's displayed? Are there multiple scenes withing the gltf file?

**Comment by AllenDang** [comment]
@alice-i-cecile I'm loading it directly with file path and omit #scene section like `server.load(path)`. I think all meshes are loaded, because I can read all kind of information like face count, vertex and AABB from them, just cannot see them.

**Comment by alice-i-cecile** [comment]
@mockersf you've looked into 3D much more than I have; any ideas on where to look?

**Comment by mockersf** [comment]
after opening the glb file in blender and re-exporting it, I get something similar to the online gltf viewer:
<img width="1392" alt="Screenshot 2022-12-05 at 02 04 27" src="https://user-images.githubusercontent.com/8672791/205527807-cde8d23f-ba79-4217-bdf1-8ea562ac57ce.png">

and when moving the camera inside the cube
<img width="1392" alt="Screenshot 2022-12-05 at 02 03 59" src="https://user-images.githubusercontent.com/8672791/205527828-aea32d45-c383-4285-9e54-36f08076de6a.png">

Do you know how the original gltf file was produced? Would it be possible to create a smaller file showing the same kind of issue?

**Comment by AllenDang** [comment]
@mockersf It is created by Blender. Here is the blender file.
[lowpoly_final.blend.zip](https://github.com/bevyengine/bevy/files/10150348/lowpoly_final.blend.zip)

**Comment by mockersf** [comment]
@AllenDang there are two scenes in your blender file (and your glb too I guess)
<img width="476" alt="Screenshot 2022-12-05 at 10 00 49" src="https://user-images.githubusercontent.com/8672791/205596712-afa89819-8a2c-49c8-a3e6-60cf972d903c.png">

If in blender you delete the "Library" scene, or if you try to display the second scene in Bevy, you will get what you expect.

**Comment by AllenDang** [comment]
@mockersf I think we should iterate and display all models from all scenes if no scene is specified.
