### ISSUE TITLE
Integer vectors

### ISSUE THREAD

**Issue by wihrl** [bevyengine/bevy#6731]
## What problem does this solve or what need does it fill?

A vector of integers seems like a pretty basic thing to be missing. It is mostly useful for things with discrete coordinates - anything snapped to a grid. Tiles,  chunks, ...

## What solution would you like?

VecNi with mostly the same operations as VecN.

## What alternative(s) have you considered?

Using an external math library or writing my own. Possible, works, but is a major pain.

**Comment by SkiFire13** [comment]
Have you already considered using `bevy::math::IVecN` and `bevy::math::UVecN`? What are they missing?

**Comment by wihrl** [comment]
Welp, I was looking at an old version of the docs. If only all issues were resolved this way.
