### ISSUE TITLE
std::path::Path doesn't implement Reflect in 0.9

### ISSUE THREAD

**Issue by Xion** [bevyengine/bevy#6739]
Code similar to the following used to work in 0.8.x:

```
use std::path::Path;

/// Path to the storage database.
#[derive(Clone, Copy, Debug, Default, Eq, Hash,  PartialEq, Reflect)]
pub enum StoragePath {
    /// In-memory database for testing.
    #[default]
    Memory,

    /// Database stored in an application- & platform-specific directory in the filesystem
    Filesystem(&'static Path),
}
```

In 0.9, it looks like `&Path` doesn't implement `Reflect` anymore (which would be a strange oversight), or at least the derive doesn't work correctly when a `Path` field is inside an enum variant.

**Comment by MrGVSV** [comment]
I think the main thing is adding the impl for `Path` itself. Not sure if that will handle the `&Path` case, but at least adds support for this missing type.
