### ISSUE TITLE
Mix of HDR and non-HDR cameras breaks rendering

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#6754]
## Bevy version

0.9 and main

## Relevant system information

```
AdapterInfo { name: "NVIDIA GeForce RTX 2070", vendor: 4318, device: 7938, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "517.48", backend: Vulkan }
```

## What you did

Change the `split_screen.rs` example to add `hdr: true` on one camera but not the other (doesn't matter which one).

## What went wrong

Background becomes black, default clear color (grey) not applied anymore. I **both** cases (whether hdr is set on left or right), only the _right_ camera shows something. 

![image](https://user-images.githubusercontent.com/6532395/204041789-6f3518af-6701-4e14-b835-7a275dbf0235.png)

Testing this on another 4-camera 🎆 Hanabi example, where things animate, I can confirm clearing doesn't work (all particles render on the previous frame) and the HDR camera stops rendering:

![image](https://user-images.githubusercontent.com/6532395/204041891-998d3c55-346d-4730-ad0c-c2a1a8ded074.png)

Although the latter _could_ be a bug in 🎆 Hanabi, the similarity of artifacts might help diagnosing the issue.

## Additional information

I'm guessing the cameras have incompatible render target, and there's no "smart" resolution applying tonemapping only to HDR ones.

It's unclear if this is supposed to work in the first place but logged as bug because @superdump said it should "maybe" be supported.

**Comment by torsteingrindvik** [comment]
Think I found the same issue.

I'll copy paste my question from Discord:

![image](https://user-images.githubusercontent.com/52322338/224506938-710027fe-21dc-4ad7-923c-c0a6959af457.png)

**Comment by JMS55** [comment]
https://github.com/bevyengine/bevy/pull/10325 should let us implement a proper fix for this now

**Comment by JMS55** [comment]
We don't need `clear_color: ClearColorConfig::None` in the split screen example anymore.

**Comment by migimunz** [comment]
Also happening on 0.13.1. Here's a [minimal example](https://github.com/bevyengine/bevy/files/14853289/hdr_issue.zip) that replicates it.

Tested on M1: `AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }`

**Comment by tychedelia** [comment]
I'd like to tackle this tomorrow if no one is already working on it.

**Comment by JMS55** [comment]
No one else is working on it, feel free to.
