### ISSUE TITLE
`#[derive(Reflect)]` on enum that wraps another enum does not work

### ISSUE THREAD

**Issue by jenanwise** [bevyengine/bevy#6783]
## Bevy version

Tried: `0.9` and `523072902cecad440b5d2109077e437fcb7580b6`

## What you did

Deriving `Reflect` on a simple enum works:

```rust
#[derive(Reflect)]
enum Inner {
    Foo,
}
```

But deriving `Reflect` on an `enum` that wraps another enum does not:

```rust
#[derive(Reflect)] // <-- the trait `FromReflect` is not implemented for `Inner`
enum Outer {
    Inner(Inner),
}
```

**Comment by alice-i-cecile** [comment]
This should be documented on the Reflect trait via a doc test :)

**Comment by MrGVSV** [comment]
> You need to derive `FromReflect` for the inner enum as well. I forgot why it is required, but without it the enum can't be reflected.

It's required because of `Reflect::apply`. Just like with `Vec<T: FromReflect>` we need to ensure we can create concrete instances of new data. For `Vec<T>` this means possibly inserting a brand new value. For enums, this means possibly setting it to a different variant.

**Comment by MrGVSV** [comment]
Should we close this out and open a new issue for the documentation on `Reflect` (or maybe `Enum`) to indicate this?

**Comment by alice-i-cecile** [comment]
Yes please. Ping me when you've made one and I'll do so.

**Comment by MrGVSV** [comment]
@alice-i-cecile created #6985
