### ISSUE TITLE
Importing bevy_pbr::mesh_view_types imples defining MAX_DIRECTIONAL_LIGHTS

### ISSUE THREAD

**Issue by torsteingrindvik** [bevyengine/bevy#6799]
## Bevy version

Main @ `e954b8573`

## What you did

I did this in a shader:

```wgsl
#import bevy_pbr::mesh_view_types
```

Because I wanted the definition of the `Globals` struct to re-use in my own shader.

## What went wrong

```text
error: expected constant, found '#'
   ┌─ wgsl:59:49
   │
59 │     directional_lights: array<DirectionalLight, #{MAX_DIRECTIONAL_LIGHTS}u>,
   │                                                 ^ expected constant
```

### theories about what might be going wrong

Importing `bevy_pbr::mesh_view_types` implies that this value is defined.

### workarounds that you used

1. I could redefine the `Globals` struct, but I would like to not repeat that.
2. I currently add 
```rust
shader_defs: vec![ShaderDefVal::Int("MAX_DIRECTIONAL_LIGHTS".to_string(), 1)],
```
to my code and that works. But this feels like something I should not have to do.

**Comment by JMS55** [comment]
This happens because of Lights struct in mesh_view_types.wgsl. Almost all importers of this file are not actually using the Lights struct. For now, I think we should hard-code MAX_DIRECTIONAL_LIGHTS to always be added to all shader defines. Eventually, this will be fixed by https://github.com/bevyengine/bevy/pull/5703.

**Comment by torsteingrindvik** [comment]
As far as I can tell this is still not fixed.
In my custom shader I still want to have `struct Globals { ... }` defined, so I import `mesh_view_types`.
That shader expects `#{MAX_CASCADES_PER_LIGHT}` and `#{MAX_DIRECTIONAL_LIGHTS}`.
