### ISSUE TITLE
Unnecessary internal use of World::read_change_ticks

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#6812]
We're currently using `World::read_change_ticks` in a variety of locations in `bevy_ecs` where we have a `&mut World`. This adds unnecessary atomic reads in locations where we can use normal loads. These usages can be replaced with `World::change_tick` instead.

**Comment by mnmaita** [comment]
Most places where I checked that were using `read_change_ticks` were also borrowing `World` as an immutable reference, so using `change_tick` makes it to be also borrowed as mutable.

e.g.

```rs
    /// Returns an [`Iterator`] over the query results for the given [`World`].
    #[inline]
    pub fn iter_mut<'w, 's>(&'s mut self, world: &'w mut World) -> QueryIter<'w, 's, Q, F> {
        // SAFETY: query has unique world access
        unsafe {
            self.update_archetypes(world);
            self.iter_unchecked_manual(world, world.last_change_tick(), world.change_tick())  // world is borrowed both as immutable and mutable here
        }
    }
```

I did find two places where we can just replace the method but do you have any suggestions on these places where we can't?

**Comment by james7132** [comment]
The change tick does not increment before those function calls, so it should still be correct to use `World::change_ticks` to read it, cache a value, and then pass that in place of the atomic read.

**Comment by mnmaita** [comment]
Oh! I see, thanks for the clarification.😅

I can take care of this task @james7132.

**Comment by mnmaita** [comment]
I'll push a PR that addresses this soon. One more question though @james7132:

```rs
    #[inline]
    pub unsafe fn get_unchecked_mut<T: Component>(&self) -> Option<Mut<'_, T>> {
        get_component_and_ticks_with_type(self.world, TypeId::of::<T>(), self.entity, self.location)
            .map(|(value, ticks)| Mut {
                value: value.assert_unique().deref_mut::<T>(),
                ticks: Ticks::from_tick_cells(
                    ticks,
                    self.world.last_change_tick(),
                    self.world.read_change_tick(),
                ),
            })
    }
```

In this case, `world` field is `mut` but `self` is not. I'm unsure if I should change this method signature to be able to access `world` mutably.
