### ISSUE TITLE
Cannot play animation correctly.

### ISSUE THREAD

**Issue by AllenDang** [bevyengine/bevy#6814]
## Bevy version

0.9.1

## What you did

View a model with animation from GLTF via scene_viewer

## What went wrong

The animation is incorrect.

Here is the result from scene_viewer.

https://user-images.githubusercontent.com/18550/205034634-9ee13913-545e-4961-80bc-952f9771e464.mp4

And here is the result from official GLTF viewer.

https://user-images.githubusercontent.com/18550/205034721-f764cdf5-395f-4219-8640-85a1835d8e66.mp4

Here is the GLTF file.

[dragon_flying.glb.zip](https://github.com/bevyengine/bevy/files/10131676/dragon_flying.glb.zip)

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used
- links to related bugs, PRs or discussions

**Comment by james7132** [comment]
A quick glance makes it seem like it's binding the animations to the wrong bones or the wrong mesh. This could be an issue with the way we're extracting the hierarchy or the animations from the GLTF file.

**Comment by mockersf** [comment]
it looks like the model is using morph animation which are not supported in Bevy yet

**Comment by nicopap** [comment]
How this looks with #8158 

https://github.com/bevyengine/bevy/assets/26321040/d2a0c544-0ef8-45cf-9f99-8c3792f5a258
