### ISSUE TITLE
ZIndex::Global doesn't seem to work for children

### ISSUE THREAD

**Issue by GuillaumeGomez** [bevyengine/bevy#6838]
This is a bug occurring on both 0.9.0 and 0.9.1.

Short example:

```rust
// The building
commands
    .spawn((
        Building::GeneralShop,
        crate::game::OutsideWorld,
        SpriteSheetBundle {
            texture_atlas: texture.clone(),
            sprite: TextureAtlasSprite {
                index: 0,
                custom_size: Some(Vec2 {
                    x: GENERAL_SHOP_WIDTH,
                    y: GENERAL_SHOP_HEIGHT,
                }),
                ..default()
            },
            transform: Transform::from_xyz(x, y, 2.0),
            ..default()
        },
        ZIndex::Global(10),
    ))
    .with_children(|children| {
        children.spawn((
            SpriteSheetBundle {
                texture_atlas: texture,
                sprite: TextureAtlasSprite {
                    index: 1,
                    custom_size: Some(Vec2 {
                        x: GENERAL_SHOP_WIDTH,
                        y: GENERAL_SHOP_HEIGHT,
                    }),
                    ..default()
                },
                ..default()
            },
            ZIndex::Global(1),
        ));
    });

// the player
commands
    .spawn((
        Player {
            is_running: false,
            waiting_for_rerun: false,
            old_x: 0.,
            old_y: 0.,
        },
        SpriteSheetBundle {
            texture_atlas: texture_atlas_handle,
            sprite: TextureAtlasSprite {
                custom_size: Some(Vec2 {
                    x: PLAYER_WIDTH,
                    y: PLAYER_HEIGHT,
                }),
                ..default()
            },
            transform: Transform::from_xyz(0.0, 210.0, 1.0),
            ..default()
        },
        ZIndex::Global(2),
    ));
```

In here, I have split my building in two parts: the roof and the rest so that the character passes under the roof but stay on top for the door. Little screenshot:

![image](https://user-images.githubusercontent.com/3050060/205454468-ca0014ec-e0e0-43c7-b21f-fbef8eab3e4d.png)

As the low part of the building has a `ZIndex::Global` of 1, it should be under the player which has a `ZIndex::Global` of 2, however it's not the case.

**Comment by GuillaumeGomez** [comment]
I pushed this change in a branch if you want to try it locally: https://github.com/GuillaumeGomez/rust-toy-game/tree/shop-zindex

**Comment by DasLixou** [comment]
I think `ZIndex` is only for UI elements. you should use the z coordinate in transform instead.

**Comment by DasLixou** [comment]
But cool assets :D

**Comment by DasLixou** [comment]
@GuillaumeGomez you should use the z coordiante (3rd parameter in `Vec3::new`) in the transform and remove the ZIndex Component, because it is only used for UI elements. 

When you read this you can close the issue.

**Comment by GuillaumeGomez** [comment]
> I think `ZIndex` is only for UI elements. you should use the z coordinate in transform instead.

Oh I see.



> But cool assets :D

Minish cap :)



> @GuillaumeGomez you should use the z coordiante (3rd parameter in `Vec3::new`) in the transform and remove the ZIndex Component, because it is only used for UI elements.
> 
> When you read this you can close the issue.

The z coordinate is sometimes replaced, not sure why, so not very reliable. Might be better if I opened an issue once I can find a way to reproduce this bug.

Closing as this is not the intended way of using `Zindex`. Thanks for the answers!
