### ISSUE TITLE
tracing-tracy suppresses tracing to stdout

### ISSUE THREAD

**Issue by brandon-reinhart** [bevyengine/bevy#6862]
## Bevy version

0.9.1

## What you did

Enabling tracing-tracy via the trace_tracy feature.

## What went wrong

Once enabled, info! and debug! type messages that would have been routed to stdout no longer appear.

It would be nice to be able to have tracing-tracy enabled but also see info! and debug! messages.

**Comment by alice-i-cecile** [comment]
Will be fixed by #6955.
