### ISSUE TITLE
bevy_reflect: Improve `List::push` and `List::pop` docs

### ISSUE THREAD

**Issue by MrGVSV** [bevyengine/bevy#6866]
## How can Bevy's documentation be improved?

The docs on [`List::push`](https://github.com/bevyengine/bevy/blob/f9c52f98b9858a685ac08871eade1ab704137a51/crates/bevy_reflect/src/list.rs#L15-L16) and [`List::pop`](https://github.com/bevyengine/bevy/blob/f9c52f98b9858a685ac08871eade1ab704137a51/crates/bevy_reflect/src/list.rs#L18-L19) should better explain the directionality of those operations, as explained in [this](https://github.com/bevyengine/bevy/pull/6831#issuecomment-1338287623) comment.

We should direct manual (and internal) implementors to uphold the contract that:
1. "pushing" always appends the element _to the end_ of the list
2. "popping" always removes the element _from the end_ of the list

The docs already do this to an extent, but they could give just a bit more detail and make the guarantee more explicit so implementors don't miss it!

**Comment by LinusKall** [comment]
I clarified the meaning of _first_/_front_ element and _last_/_back_ element with some emphasis. What do you think, should I make a PR?

```rust
/// An ordered, mutable list of [Reflect] items. This corresponds to types like [`std::vec::Vec`].
///
/// This is a sub-trait of [`Array`] as it implements a [`push`](List::push) function, allowing
/// it's internal size to grow.
///
/// This trait expects index 0 to contain the _first_ or _front_ element.
/// The _last_ or _back_ element refers to the element with the largest index.
pub trait List: Reflect + Array {
    /// Appends an element to the _back_ of the list.
    fn push(&mut self, value: Box<dyn Reflect>);

    /// Removes the _last_ element from the list and returns it, or [`None`] if it is empty.
    fn pop(&mut self) -> Option<Box<dyn Reflect>>;

    /// Clones the list, producing a [`DynamicList`].
    fn clone_dynamic(&self) -> DynamicList {
        DynamicList {
            name: self.type_name().to_string(),
            values: self.iter().map(|value| value.clone_value()).collect(),
        }
    }
}
```

**Comment by LinusKall** [comment]
>I wonder if words like `last` should backlink to those docs? 🤔

By the way, how do I create backlinks? 🤔

**Comment by devil-ira** [comment]
> Personally I prefer `end` over `back`, but maybe that's just me

Don't mind personally, but `front`/`back` would match the method names and docs for [`VecDeque`](https://doc.rust-lang.org/std/collections/struct.VecDeque.html) so I think we should go with that.
