### ISSUE TITLE
bevy_reflect: #[derive(Reflect)] support custom lifetime and Box<T> fields in structure.

### ISSUE THREAD

**Issue by devillove084** [bevyengine/bevy#6880]
Some example code
``` rust
    #[derive(Default, Reflect)]
    struct TestStruct<'a> {
        data1: Vec<u8>,
        data2: &'a [u8],
        prev: Option<Box<TestStruct>>
        next: Option<Box<TestStruct>>,
    }
```

**Comment by devillove084** [comment]
I will spend a little time doing research, hoping to give some useful suggestions, if necessary, I may try to participate in @jakobhellermann

**Comment by james7132** [comment]
Unless `std::any::Any` relaxes it's lifetime requirements or we develop our own `Any` alternative (unlikely), this is probably impossible. Closing this for now.
