### ISSUE TITLE
General confusion - E missing in ECS for official tutorial

### ISSUE THREAD

**Issue by miketwenty1** [bevyengine/bevy#6904]
## How can Bevy's documentation be improved?
As it currently stands I'm a bit confused on Entities, primarily because the examples don't use in the tutorial. 
I'm aware of the `bevy::prelude::Entity` struct, but there is no actual usage of this. It seems in the tutorial that components have the ability to be entities as well as components. 
Starting with the idea that Person is a component and we sort of missed any code representing an entity.
https://bevyengine.org/learn/book/getting-started/ecs/
```rust
#[derive(Component)]
struct Person;
```
The only code we get on entity is that it's a unique u64?
```rust
struct Entity(u64);
```
I look forward to the official tutorial becoming more robust it seems to not have much added to it in the last year. I'm happy to help come up with ideas!

**Comment by mockersf** [comment]
That's a good point, could you recreate the issue on the website repo? https://github.com/bevyengine/bevy-website. This is where this doc lives.

**Comment by miketwenty1** [comment]
Opps!, didn't realize that where I should be opening this issue. Thanks @mockersf
