### ISSUE TITLE
Setting MSAA to 1 sample to disable it is really confusing

### ISSUE THREAD

**Issue by Andrewp2** [bevyengine/bevy#6931]
## What problem does this solve or what need does it fill?

It's confusing that you have to set the `samples` value to 1 to turn off MSAA.

## What solution would you like?

Ira presented a pretty good one: https://discord.com/channels/691052431525675048/1051819150189809715/1051822325907079208 Just have the MSAA be a field on the camera like HDR.

## What alternative(s) have you considered?

Could have an MSAA enum like:

```rust
enum MSAA {
    On(u32),
    Off,
}
```

and insert that as a resource.

**Comment by IceSentry** [comment]
It always made sense to me, but I guess it assumes a lot of rendering knowledge. I'd approve a PR with this change.

**Comment by Cet0s** [comment]
Sample counts can be (or at least I have never seen anything else) only be 2^n. But even this rule is limited. In Vulkan there are only the values 1, 2, 4, 8, 16, 32 and 64. I don't think anything beyond that would be useful or even supported by any platform. Therefore I would suggest the following MSAA enum:
`enum MSAA {
    Off,
    Sample2,
    Sample4,
    Sample8,
    Sample16,
    Sample32,
    Sample64
} `
As a positive side effect, no invalid values could be provided.

**Comment by mockersf** [comment]
Only 1 and 4 are supported for now: https://github.com/gfx-rs/wgpu/issues/1832

**Comment by Cet0s** [comment]
Good point, and as you said this could still change in the future. For this reason I think it makes sense to use `#[non_exhaustive]` and for now only use the available values.
