### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by naithar** [bevyengine/bevy#697]
**Bevy version**
5df6804

**Operating system & version**
iOS 14.0.1

**What happened**
Running any iOS bevy app results in crash on startup.

**Additional information**

Commenting out this lines fixes the issue: https://github.com/bevyengine/bevy/blob/d004bce0c9d4049549a2f2a6f47aa217ff39d931/crates/bevy_winit/src/winit_windows.rs#L74-L77
Seems like https://github.com/bevyengine/bevy/pull/679 introduced this crash.

Logs:

```
2020-10-18 02:01:26.418233+0300 BevyTest[12738:4248545] fopen failed for data file: errno = 2 (No such file or directory)
2020-10-18 02:01:26.418290+0300 BevyTest[12738:4248545] Errors found! Invalidating cache...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported(NotSupportedError)', bevy/crates/bevy_winit/src/winit_windows.rs:76:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

**Comment by cart** [comment]
Resolved by #703
