### ISSUE TITLE
Transform combined with_children is ignored

### ISSUE THREAD

**Issue by frondeus** [bevyengine/bevy#699]
**Bevy version**

`git+https://github.com/bevyengine/bevy#5df6804daf056f75872c92800d3312ce71056692`

**Operating system & version**

Windows 10

**What you did**

I expect that code like this
```rust
commands
    .spawn((Transform::from_translation(local_pos),))
    .with_children(|commands| {
        commands.spawn(SpriteSheetComponents {
            texture_atlas: texture_atlas_handle,
            sprite: TextureAtlasSprite::new(0),
            transform: Transform::from_scale(64.0),
            ..Default::default()
        });
   });
```

Should give the same result as

```rust
 commands.spawn(SpriteSheetComponents {
     texture_atlas: texture_atlas_handle,
     sprite: TextureAtlasSprite::new(0),
     transform: Transform::from_translation(local_pos).with_scale(64.0),
     ..Default::default() 
   });
```

**What actually happened**

The sprite was not moved nor scaled.

Am I missing something? Unfortunately example with matching squares is not using new Transform code so I couldn't catch correct pattern.

**Comment by cart** [comment]
I'm pretty sure the issue is that you need to add a GlobalTransform to the parent too. Let me know if that works for you!

**Comment by frondeus** [comment]
Oh, I see. Yes, it works :) I didn't understand why `examples/hierarchy.rs` was working but now I see it is because `GlobalTransform` is a part of `SpriteComponents`. 

Thank you :)!
