### ISSUE TITLE
render app: Added stages get ignored

### ISSUE THREAD

**Issue by dcz-self** [bevyengine/bevy#6990]
## Bevy version

0.9.1

## What you did

The use case (same as https://github.com/bevyengine/bevy/issues/6989): I want to have a uniform which is created based on 2 separate sets of extracted data. I'm bound on one side by the Extract stage where the extraction takes place, and the Prepare stage, where the instantiated uniform is written to the buffer via UniformComponentPlugin.

There is no stage between them. Adding a stage results in the system not running:

```
use bevy::prelude::*;
use bevy::render::{RenderApp, RenderStage};

fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins);
    let render_app = app.get_sub_app_mut(RenderApp).unwrap();
    render_app
        .add_stage_after(RenderStage::Extract, "combine", SystemStage::single(system));
    app.run();
}


fn system() {
    println!("I want to break free");
}
```

## What went wrong

Expected: the system runs.

Actual: nothing gets printed.

**Comment by hymm** [comment]
The render app runs all of it's stages by hand, so you can't really add a stage. https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/lib.rs#L244

This will be fixed in the pipelined rendering pr.
https://github.com/bevyengine/bevy/pull/6503
