### ISSUE TITLE
Bors retry can cause unreviewed code to be merged

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#6994]
Currently it is possible for the following to happen:
1. Maintainer queues a merge with `bors r+`
2. Bors fails for some reason
3. PR author adds new arbitrary unreviewed code
4. PR author calls bors retry 

This allows arbitrary unreviewed code to be committed. In general this isn't a problem because the PR author has already indicated that they are trustworthy by getting the initial approval / not adding malicious code. But this is still a hole and we should close it.

#6992 was created in an attempt to fix it, but it wasn't a full solve. Ideally this is fixed in upstream bors, probably by making `bors retry` require the same permissions as `bors r+`.

**Comment by mockersf** [comment]
> Ideally this is fixed in upstream bors, probably by making bors retry require the same permissions as bors r+.

Simpler would be to have an option to disable `bors retry`. A user that can trigger it should already be able to use the commands they have permissions for.

**Comment by Weibye** [comment]
Is this considered solved with the transition to Github merge queue?

**Comment by mockersf** [comment]
Yup
