### ISSUE TITLE
CursorGrabMode::Confined on Linux panicks on startup

### ISSUE THREAD

**Issue by vrmaurice** [bevyengine/bevy#7007]
## Bevy version

Bevy 9.1

## Operating System

Fedora Linux Workstation 37

## What you did

I tried to confine the mouse cursor using WindowDescriptor.
```
App::new()
.add_plugins(DefaultPlugins.set(WindowPlugin {
            window: WindowDescriptor {
                title: "Test Window".to_string(),
                present_mode: bevy::window::PresentMode::AutoVsync,
                cursor_grab_mode: CursorGrabMode::Confined,
                cursor_visible: false,
                ..default()
            },
            ..default()
        }))
.run()
```

## What went wrong

The code compiles successfully, but panicks at startup.
I get this error: 

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os(OsError { line: 1333, file: "/home/maurice/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/window.rs", error: XMisc("Cursor could not be confined: confine location not viewable") })', /home/maurice/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.9.1/src/winit_windows.rs:171:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

## Additional information

This occurs both on Wayland and X11.

**Comment by nicopap** [comment]
Can reproduce on 2938792 on my archlinux.

Of course this is a bug, but here is a workaround until we get around to fix it:

## Workaround

1. Write a setup system that accepts a `mut windows: ResMut<Windows>`
2. In the system, access the primary window with `let primary = windows.get_primary_mut().unwrap()`
3. Set the grab mode using `primary.set_cursor_grab_mode(new_grab_mode)`

**Comment by VitalyAnkh** [comment]
I will pick up this issue.
