### ISSUE TITLE
ndk-glue looks to be archived and marked unmaintained

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7028]
LGTM, but https://github.com/rust-mobile/ndk-glue looks to be archived and marked unmaintained. We should probably look at the proposed alternative.

_Originally posted by @james7132 in https://github.com/bevyengine/bevy/pull/7027#pullrequestreview-1229706278_

**Comment by mockersf** [comment]
this will be fixed by https://github.com/bevyengine/bevy/pull/6830 and the update to winit 0.28

**Comment by mockersf** [comment]
no dependency on ndk-glue since #7480
