### ISSUE TITLE
Make `asset_manager` configurable

### ISSUE THREAD

**Issue by jinleili** [bevyengine/bevy#7029]
## What problem does this solve or what need does it fill?

Integrating the Bevy engine into an existing app may be a common scenario, but in this scenario it is difficult for the user to manually initialize the `ndk-glue` because the `ANativeActivity` parameter cannot be provided and the ndk-glue is not initialized which causes `AndroidAssetIo::load_path` panic.

## What solution would you like?

Since `ANativeActivity` is only used in bevy to get `asset_manager`:
```rust
let asset_manager = ndk_glue::native_activity().asset_manager()
```
Allowing `asset_manager` to be made available through configuration would give users more freedom.

## Additional context

Scenario demo: [bevy-in-app](https://github.com/jinleili/bevy-in-app)

**Comment by mockersf** [comment]
`ndk-glue` will be removed in https://github.com/bevyengine/bevy/pull/6830

**Comment by jinleili** [comment]
@mockersf Thank you for the link, I learned how to customize AssetIoPlugin from https://github.com/bevyengine/bevy/pull/6830, now solved the configuration issue of `asset_manager`.
