### ISSUE TITLE
Custom Materials with Atomic Counter

### ISSUE THREAD

**Issue by DasLixou** [bevyengine/bevy#7030]
## What problem does this solve or what need does it fill?

After #6988 I've questioned myself if it would be also possible to make custom materials use atomic counter for their AsBindGroup, instead of TypeUUID.

## What solution would you like?

Make the AsBindGroup derive also increasing the atomic counter, so that lines like https://github.com/bevyengine/bevy/blob/b6066c30b6cfa7bffa598d45706dbe6e46ad24fc/examples/shader/shader_material.rs#L57 don't need to exist anymore.

**Comment by james7132** [comment]
That line is for the TypeUuid derive. It's required to support using it as an asset. The use case is entirely different and definitely needs a stable independent unique ID that is the same across compilations and executions of the same binary.

**Comment by DasLixou** [comment]
Oh I See.. should this be closed?
