### ISSUE TITLE
Add `Query::get_many_unchecked` and `Query::many_unchecked`

### ISSUE THREAD

**Issue by tasgon** [bevyengine/bevy#7052]
## What problem does this solve or what need does it fill?

`Query::get_unchecked` allows for the retrieval of single query items at a time, but there is no clean way of doing the same for entity lists.

## What solution would you like?

Just as `Query::get` has `Query::get_many`, there should be `Query::get_many_unchecked`. In addition, `get_mut` and `get_many_mut` have their corresponding panicking versions `many` and `many_mut`, so it may be useful to have a non-panicking `Query::many_unchecked` (and possibly `Query::unchecked` too).

**Comment by JoJoJet** [comment]
This can already be done manually: `Query::get_unchecked` takes `&self`, so you can just call it multiple times in the same scope if you want multiple disjoint mutable references. I don't think it's worth adding convenience functions for heavily discouraged unsafe operations.

**Comment by tasgon** [comment]
It can, but you have the overhead of a `Result` for each one of them.

**Comment by tasgon** [comment]
And while I generally agree with the sentiment, there are a few tasks (such as graph traversal) that require such operations to do optimally.

**Comment by Guvante** [comment]
What difference are you seeing between the versions? Unchecked is basically about bypassing the borrow checker and little more.

The majority of the helper functions are simple wrappers around the unchecked functions that use more restrictive parameters.

For instance `get_many` just calls `get_unchecked` in a loop.

**Comment by tasgon** [comment]
You're right about the lack of overhead, my apologies.

I'll leave the issue open in case somebody feels like spending the time but, since this is effectively a non-issue, I don't mind it being closed, either.
