### ISSUE TITLE
reflect: `insert` and `remove` methods for `List`

### ISSUE THREAD

**Issue by soqb** [bevyengine/bevy#7061]
## What problem does this solve or what need does it fill?

Currently, the reflect `List` trait implements only `push` and `pop` functionality. There is no way to insert or remove elements other than from/to the end other than by downcasting. This is especially notable using types like `VecDeque` with reflection.

## What solution would you like?

Add `insert` and `remove` methods for `List` and implement them.
Give `push` and `pop` default implementations using on the `insert`/`remove` and `len` methods.

## What alternative(s) have you considered?

We might not need to implement the methods by default but since we can I believe we should as to not put to much burden on the implementor.

## Additional context

Discussed first [on discord](https://discord.com/channels/691052431525675048/1002362493634629796/1054711227454078977).

**Comment by alice-i-cecile** [comment]
Yep, if we can have a default impl for this I'm on board. Probably warn in the trait docs that manual impls may be faster.

**Comment by soqb** [comment]
trying to implement this. for the signature of `insert` and `remove`, should it match `Vec` where insertion and removal panic when the index is out of bounds or have them as fallible operations `fn insert(...) -> bool` and `fn remove(...) -> Option<Box<dyn Reflect>>`?

**Comment by MrGVSV** [comment]
> trying to implement this. for the signature of insert and remove, should it match Vec where insertion and removal panic when the index is out of bounds or have them as fallible operations: fn insert(...) -> bool and fn remove(...) -> Option<Box<dyn Reflect>>?

I’m in favor of just matching `Vec`. We have ways for users to reflectively perform their own bounds checking to ensure they don't panic, so I think it's fine to match that behavior
