### ISSUE TITLE
Implement mouse position query/resource

### ISSUE THREAD

**Issue by Vaelint** [bevyengine/bevy#709]
**What problem does this solve or what need does it fill?**

The RTS, Point and Click, and Twin Stick Shooter genres need this for core functionality.
 - RTS: Directing units/structures
 - PNC: The point part of point and click
 - TSS: Controlling ship direction on mouse/keyboard

**Describe the solution would you like?**

There seems to be an existing implementation in
`cart_tmp_winit::event::WindowEvent::CursorMoved::Position`
Afaik this is not exposed to the user

**Describe the alternative(s) you've considered?**
 
One could use the delta field of [bevy_input::mouse::MouseMotion](https://docs.rs/bevy_input/0.2.1/bevy_input/mouse/struct.MouseMotion.html) and implement a fake cursor, but this can be awkward outside of full screen contexts

**Additional context**
See the [Unity input.mousePosition](https://docs.unity3d.com/ScriptReference/Input-mousePosition.html) docs for an example of the desired behavior.

**Comment by smokku** [comment]
The solution today is to write a simple system, that reads `CursorMoved` events and stores the cursor position in some resource.

We could extend `bevy_window::Window` and add such system to `bevy_window` plugin.
Although this would add overhead to games that do not use mouse.

**Comment by Vaelint** [comment]
You can get the mouse window position of the cursor through the resource system

 Example:
```rust
struct ExampleInputState {
    motion_event_reader: EventReader<MouseMotion>,
}

/// Example system showcasing absolute mouse coordinate functionality
fn example_system(
    state: ResMut<ExampleInputState>,
    mouse_motion_event: Res<Events<MouseMotion>>
) {
    // Iterate through mouse motion events
    for event in state.cursor.iter(&mouse_motion_event) {
        // Read absolute cursor position into cursor_pos
        let cursor_pos = event.position;
    }
}

```
