### ISSUE TITLE
Component which picks a sprite from texture atlas based on entity's rotation

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [bevyengine/bevy#7090]
## What problem does this solve or what need does it fill?

Allow for making graphics where a sprite is picked for a current direction the entityt is facing instead of rotating the sprite itself

## What solution would you like?

A component that contains info about how to map entity's rotation to an index in a texture atlas instead of setting the atlas on entity creation or through a system. The entity's rotation is ignored when orienting the sprite when rendering.

## What alternative(s) have you considered?

I don't see an alternative, so I didn't try any

## Additional context

Such mechanism exists in a number of games, one of them being Factorio where entity rotations are defined in a spritesheet and a sprite is picked based on entity's rotation.

**Comment by infmagic2047** [comment]
I would argue it's better to use your own rotation component and updating Sprite based on that, as in your case the rotation is probably discrete and doesn't fit well into the use cases of `Transform`. Try something like this:
```
commands.spawn((
    SpriteBundle { ... },
    SpriteRotation(...),
    SpriteRotationSheet(...),
));

fn update_sprite_rotation_system(mut query<(&mut Handle<Image>, &SpriteRotation, &SpriteRotationSheet)>) {
    for (mut texture, rotation, rotation_sheet) {
        *texture = ...;
    }
}
```

**Comment by JohnTheCoolingFan** [comment]
That solution won't work for my usecase. I also want to use the Tranform's rotation for orienting collision boxes (rapier), for example. Also I think it's not that hard to map a f32 rotation amount to a discrete number of positions.

**Comment by rparrett** [comment]
I think that this is something that can very easily be done as a plugin or user code, so it probably should be.

It seems like this would be a pretty niche feature as described. Users may want to

- Use 4, 8, or any other number of discrete rotation steps to control a rotation.
- Not use `Transform` at all for rotation, as infmagic mengtioned.
- Use a flip for the left/right facing sprites.
- Use rotation to determine an animation to play rather than a single sprite to display.

**Comment by alice-i-cecile** [comment]
Agreed, I think this can and should be handled in user space code. This is a lot of complexity without a clear design for a fairly niche (if reasonable!) pattern.
