### ISSUE TITLE
Bevy + Rapier no determinist even without query

### ISSUE THREAD

**Issue by syrm** [bevyengine/bevy#7093]
## Bevy version

0.9.1

## What you did

I launch my physic simulation twice (bevy + rapier), with the same initial condition, and the simulation run differently each time.

## What went wrong

The simulation should be deterministic and run each time exactly the same simulation

You can find an example here : https://github.com/syrm/bevy-rapier-no-determinism

**Comment by mrec** [comment]
Apologies if this is a dumb question, but is Rapier using `TimestepMode::FixedTimestep` here? I can't see it explicitly but am not sure what the default is.

**Comment by Guvante** [comment]
The default is [Variable](https://github.com/dimforge/bevy_rapier/blob/master/src/plugin/configuration.rs#L84) which is explained [in the source](https://github.com/dimforge/bevy_rapier/blob/master/src/plugin/configuration.rs#L23) as:
> Use a variable timestep: the physics simulation will be advanced by the variable value `min(max_dt, Time::delta_seconds() * time_scale)` seconds at each Bevy tick.

Note that the `time_scale` and `substeps` are 1.

I would rerun your tests after grabbing the `RapierConfiguration` resource as part of your initialization and setting `timestep_mode` to `Fixed` setting `dt` and `substeps` to what you want.

**Comment by alice-i-cecile** [comment]
https://github.com/bevyengine/bevy/discussions/2480 has more information on possible causes here. I'm leaving this open for now, but I suspect this is more likely either a configuration issue or a bug in bevy_rapier.

**Comment by alice-i-cecile** [comment]
Closing as unactionable for now.
