### ISSUE TITLE
Merge SpriteBundle and TextureAtlasBundle

### ISSUE THREAD

**Issue by cBournhonesque** [bevyengine/bevy#7123]
## What problem does this solve or what need does it fill?

My game is composed of entities that contain a `SpriteBundle` bundle or a `SpriteSheetBundle` bundle.
When I want to update the color of an entity, I need to check every time if it contains a `Sprite` bundle or a `TextureAtlasSprite` bundle to be able to set the inner `color` field of these components. I don't want to have to make this check, because functionally it doesn't matter to me if an entity is rendered via a Sprite or a SpriteSheet, I just want to change the color of the texture.

Basically I believe the `Sprite` and `TextureAtlasSprite` components contain data that is too coupled.

Ideally I would like to be able to set `Color` only once for the entity, and then have the color be propagated to any sprite bundle of the entity. Same for 'anchor' or other sprite-related fields like `flip_x`, etc.

## What solution would you like?

I think i would like to see most fields common to ['Sprite'](https://docs.rs/bevy/latest/bevy/sprite/struct.Sprite.html) and ['TextureAtlasSprite'](https://docs.rs/bevy/latest/bevy/sprite/struct.TextureAtlasSprite.html) grouped into a separate component.
Something like:
```rust
pub struct SpriteRenderComponent {
    pub color: Color,
    pub flip_x: bool,
    pub flip_y: bool,
    pub custom_size: Option<Vec2>,
    pub rect: Option<Rect>,
    pub anchor Anchor,
}
```
And then change the bundles into:
```rust
pub struct SpriteBundle{
   pub render: SpriteRenderComponent,
   pub texture: SpriteTextureEnum,
   ...
}

#[derive(Component)]
pub enum SpriteTextureComponent{
   SpriteTexture(Handle<Image>),
   TextureAtlasSpriteTexture{texture_atlas: Handle<TextureAtlas>, index: usize},
}
```

and then all sprite-based entities can just use the `SpriteBundle`, instead of having separate `SpriteBundle` or `TextureAtlasBundle`.
This way I can change the `color` of all sprite-based entities without having to worry if they were created using a texture-atlas or not (which is just an inner implementation detail)

The solution you propose for the problem presented.

## What alternative(s) have you considered?

- I was thinking of having a global 'Color' component per entity, which can be propagated to `sprite.color` or `textureAtlasSprite.color`, but that seems overly complicated (some entities do not need a color) + the actual problem is that the `Sprite` and `TextureAtlasSprite` components are **doing too much**, some information should be shared between them.

**Comment by rparrett** [comment]
Linking this related PR which I think would address the issue #5103

**Comment by cBournhonesque** [comment]
Ah I didn't see the PR; that's exactly what I wanted, perfect :D

**Comment by mgi388** [comment]
@cBournhonesque I think you should be able to close this since #5103 was merged?
