### ISSUE TITLE
"Border" around circle in 2d_shapes exmaple

### ISSUE THREAD

**Issue by Munksgaard** [bevyengine/bevy#7126]
## Bevy version
v0.9.1

## \[Optional\] Relevant system information

```console
$ cargo --version
cargo 1.66.0-nightly (071eeaf21 2022-10-22)

$ uname -a
Linux church 5.15.77 #1-NixOS SMP Thu Nov 3 14:59:20 UTC 2022 x86_64 GNU/Linux
```

```ignore
AdapterInfo { name: "Intel(R) UHD Graphics 620 (WHL GT2)", vendor: 32902, device: 16032, device_type: IntegratedGpu, driver: "Intel open-source Mesa driver", driver_info: "Mesa 22.2.2", backend: Vulkan }
```

## What you did

```console
$ cargo run --features wayland --example 2d_shapes
```

## What went wrong

There's a "border" around the circle:

![screenshot](https://user-images.githubusercontent.com/230613/211189948-3937b764-3c91-48c5-b652-cf1cb4b49d79.png)

I don't think that's supposed to be there.

**Comment by nicopap** [comment]
Probably a duplicate of

- #2374

**Comment by Munksgaard** [comment]
True, that looks very much like the issue I'm also experiencing.
