### ISSUE TITLE
Allow direct editing of a camera's projection matrix

### ISSUE THREAD

**Issue by mattatz** [bevyengine/bevy#7155]
## What problem does this solve or what need does it fill?

I want to edit a camera's projection matrix so that I can flip the screen left and right.

Although it is possible to flip the camera left and right by `postprocessing`, I would like to realize it by editing the projection matrix of the camera, because I would like to make a screen space `ray` correctly from the mouse position, for example.

## What solution would you like?

I would like to achieve this in one of the following ways

- Set camera viewport physical_size from `UVec2` to `IVec2` (If I can put a negative value in the update argument of the `CameraProjection` trait, I can invert it.)
- Make the `projection_matrix` field in `ComputedCameraValues `to public (Set `projection_matrix` by yourself after running `CameraUpdateSystem`)

**Comment by devil-ira** [comment]
You can implement your own projection type via the [`CameraProjection`](https://docs.rs/bevy/latest/bevy/render/camera/trait.CameraProjection.html) trait. The docs are a bit incomplete so you'll need to dig through the code a little.

If you just want a ray then I think you're looking for [`viewport_to_world`](https://docs.rs/bevy/latest/bevy/render/camera/struct.Camera.html#method.viewport_to_world).

**Comment by rparrett** [comment]
> You can implement your own projection type via the [`CameraProjection`](https://docs.rs/bevy/latest/bevy/render/camera/trait.CameraProjection.html) trait. The docs are a bit incomplete so you'll need to dig through the code a little.

There's an example of this over in the cheatbook as well https://bevy-cheatbook.github.io/cookbook/custom-projection.html

**Comment by mattatz** [comment]
@devil-ira @rparrett 
I didn't know such a trait. 
Thank you for sharing! I will look at the tutorial.

Many bevy libraries use the `projection` enum, which is a direct sum of `Perspective ` and `Orthographic`, so it will be necessary to modify the related libraries, but now it seems that rendering with a custom projection matrix can be realized.
