### ISSUE TITLE
`DefaultPlugins` is not a super-set of `MinimalPlugins` if `bevy_winit` is not set: it includes no schedule runner.

### ISSUE THREAD

**Issue by stephenmartindale** [bevyengine/bevy#7173]
**Bevy Version**: `v0.9.1`

While looking at precisely what is included by the plugin group [`bevy::DefaultPlugins`](https://docs.rs/bevy/latest/bevy/struct.DefaultPlugins.html), I noticed that [`bevy::app::ScheduleRunnerPlugin`](https://docs.rs/bevy/latest/bevy/app/struct.ScheduleRunnerPlugin.html) is not, but it *is* included in [`bevy::MinimalPlugins`](https://docs.rs/bevy/latest/bevy/struct.MinimalPlugins.html). Through discussion on *Discord* and experimentation, I discovered an inconsistency.

A newcomer to *Bevy* – such as myself – could be forgiven for assuming that [`MinimalPlugins`](https://docs.rs/bevy/latest/bevy/struct.MinimalPlugins.html) is a subset of [`DefaultPlugins`](https://docs.rs/bevy/latest/bevy/struct.DefaultPlugins.html) but this is not the case where the schedule runner is concerned.

1. Using [`DefaultPlugins`](https://docs.rs/bevy/latest/bevy/struct.DefaultPlugins.html) with default *Cargo* *features* (which [includes `bevy_winit`](https://github.com/bevyengine/bevy/blob/main/Cargo.toml#L35)) would use the runner initialised by [`WinitPlugin` which calls `App::set_runner`](https://github.com/bevyengine/bevy/blob/main/crates/bevy_winit/src/lib.rs#L43).
2. Using [`MinimalPlugins`](https://docs.rs/bevy/latest/bevy/struct.MinimalPlugins.html) with default features would use [`ScheduleRunnerPlugin`](https://docs.rs/bevy/latest/bevy/app/struct.ScheduleRunnerPlugin.html)
3. Using neither of the above plugin groups would cause the app to run the schedule once and then exit.

However, should the default *Cargo* *features* be disabled and `bevy_winit` not be manually included then the behaviour changes:

4. [`DefaultPlugins`](https://docs.rs/bevy/latest/bevy/struct.DefaultPlugins.html) now no longer includes `WinitPlugin` and so no schedule runner is set – it executes the schedule once and then exits.
5. [`MinimalPlugins`](https://docs.rs/bevy/latest/bevy/struct.MinimalPlugins.html) continues to behave as before, with a schedule runner – it is has functionality that is not in [`DefaultPlugins`](https://docs.rs/bevy/latest/bevy/struct.DefaultPlugins.html)

### Steps to Reproduce

The end result of the *Getting Started* guide – [as reproduced in this *gist*](https://gist.github.com/stephenmartindale/9d93547fc7fa7cc521f7cff7ef41cfaa) – suffices to reproduce this issue. (Note that this uses [`DefaultPlugins`](https://docs.rs/bevy/latest/bevy/struct.DefaultPlugins.html).)

Case **1**: the schedule runs, repeatedly, in the default case – default *Cargo* *features*:

```toml
[dependencies]
bevy = "~0.9"
```

With default features disabled and `bevy_winit` explicitly enabled will show the same behaviour:

```toml
[dependencies]
bevy = { version = "~0.9", default-features = false, features = [ "bevy_winit" ] }
```

Case **2**: Changing [line 38](https://gist.github.com/stephenmartindale/9d93547fc7fa7cc521f7cff7ef41cfaa#file-main-rs-L38) to use [`MinimalPlugins`](https://docs.rs/bevy/latest/bevy/struct.MinimalPlugins.html) will make the app *headless* but the schedule will still run, repeatedly – independently of the presence of the `bevy_winit` *Cargo* *feature*.

Case **3**: Removing both [`DefaultPlugins`](https://docs.rs/bevy/latest/bevy/struct.DefaultPlugins.html) and [`MinimalPlugins`](https://docs.rs/bevy/latest/bevy/struct.MinimalPlugins.html) will cause the schedule to run only once – independently of the presence of the `bevy_winit` *Cargo* *feature*. (Note: Since `Res<Time>` is used, calling `.add_plugin(bevy::time::TimePlugin::default())` will be necessary.)

Case **4**: Reverting [line 38](https://gist.github.com/stephenmartindale/9d93547fc7fa7cc521f7cff7ef41cfaa#file-main-rs-L38) to use [`DefaultPlugins`](https://docs.rs/bevy/latest/bevy/struct.DefaultPlugins.html) but excluding `bevy_winit` demonstrates the bug:

```toml
[dependencies]
bevy = { version = "~0.9", default-features = false, features = [ ] }
```

Instead of behaving akin to case **2** and running the schedule, repeatedly, the schedule is now run only once, like case **3**.

### Proposed Solution

In the event that `bevy_winit` is not set, [`DefaultPlugins`](https://docs.rs/bevy/latest/bevy/struct.DefaultPlugins.html) should add [`ScheduleRunnerPlugin`](https://docs.rs/bevy/latest/bevy/app/struct.ScheduleRunnerPlugin.html) just like [`MinimalPlugins`](https://docs.rs/bevy/latest/bevy/struct.MinimalPlugins.html) does:

```rs
        #[cfg(feature = "bevy_winit")]
        {
            group = group.add(bevy_winit::WinitPlugin::default());
        }
        #[cfg(not(feature = "bevy_winit"))]
        {
            group = group.add(bevy_app::ScheduleRunnerPlugin::default());
        }
```

Source code references:

- https://github.com/bevyengine/bevy/blob/main/crates/bevy_internal/src/default_plugins.rs#L141
- https://github.com/bevyengine/bevy/blob/main/crates/bevy_internal/src/default_plugins.rs#L59-L62

### Proposed Documentation

Additional documentation should be added to `ScheduleRunnerPlugin` explaining to confused newcomers:

1. *why* it is needed in [the minimal *headless* case](https://github.com/bevyengine/bevy/blob/main/examples/app/headless.rs)
2. that it is *not* needed in the case that the winit event-loop runs the schedule – case **1**, above.
3. that it will be used in the non-minimal *headless* case – i.e. case **4**, assuming implementation of my proposed solution.

**Comment by stephenmartindale** [comment]
I am in the process of writing a simple merge-request that will implement the proposed solution and add an additional line or two of documentation comments.

**Comment by stephenmartindale** [comment]
Having performed some further experimentation, it seems that I was mistaken: my proposed solution does not actually work because the majority of other plugins in `DefaultPlugins` basically assume that some kind of window or presentation is present.

I'm now of the mind that only a documentation patch is worthwhile. It would be great if `MinimalPlugins` was actually named `HeadlessPlugins` or something similar because it seems clear to me, now, that that is the intention behind the two groups, but documentation could suffice.

Would a merge-request that added clarifications such as these, below, be desirable?

1. On `DefaultPlugins`: "... the group of plugins typically required to build a *Bevy* application which includes a *window* and presentation components. … For *headless* cases... see [`MinimalPlugins`]."
2. On `MinimalPlugins`: "... intended for use for minimal, *headless* programs ... For a more complete set of plugins intended for use in applications that include window see [`DefaultPlugins`]."
3. On `ScheduleRunnerPlugin`: there are basically no docs. at pressent, so:

```rs
/// [`ScheduleRunnerPlugin`] is the only plugin that is included in the group of *minimal* *Bevy* plugins
/// ([`MinimalPlugins`](crate::MinimalPlugins)) but excluded from [`DefaultPlugins`](crate::DefaultPlugins).
///
/// Whereas windowed applications are usually driven by some kind of *event loop* or *message loop* –
/// *Bevy's* being no exception, employing that provided by `winit` (see [`WinitPlugin`](crate::winit::WinitPlugin))
/// by default – *headless* programs and other, minimal cases require a schedule runner such as this.
/// [`ScheduleRunnerPlugin`] is not required by apps that use the [`DefaultPlugins`](crate::DefaultPlugins)
/// group because they typically include a *window* and presentation components.
///
/// See also: the [*Bevy* *headless* example](https://github.com/bevyengine/bevy/blob/main/examples/app/headless.rs)
```

**Comment by alice-i-cecile** [comment]
@stephenmartindale I would be happy with that PR :)

**Comment by stephenmartindale** [comment]
@alice-i-cecile : Documentation only: https://github.com/bevyengine/bevy/pull/7226

**Comment by stephenmartindale** [comment]
@alice-i-cecile : Could you, perhaps, take a glance at https://github.com/bevyengine/bevy/pull/7226 please? It's had one review – approved.
