### ISSUE TITLE
Demonstrate how to use `Camera::viewport_to_word`

### ISSUE THREAD

**Issue by lewiszlw** [bevyengine/bevy#7177]
## What problem does this solve or what need does it fill?

Seems `Camera::viewport_to_word` is similiar to [bevy_mode_raycasting](https://github.com/aevyrie/bevy_mod_raycast). I prefer engine built-in functionality over third-party plugins. But there is no any example to demonstrate how to use it.

## What solution would you like?

Create an example to demonstrate how to use `Camera::viewport_to_word`.

**Comment by devil-ira** [comment]
`Camera::viewport_to_word` does return a ray, but Bevy does not have a raycasting API yet.
It does deserve an example though. I'll make one.
