### ISSUE TITLE
Avoid the need for SRes::into_inner

### ISSUE THREAD

**Issue by kurtkuehnert** [bevyengine/bevy#7187]
## What problem does this solve or what need does it fill?

When defining custom `RenderCommand`s one often wants to fetch ECS resources using the `SRes<T>`(`Res<'static, T>`) system parameter. 
Due to lifetime issues, one has to call `into_inner` on each of them manually instead of having it de-refed automatically, like in normal systems.
If you forget to put `into_inner` after the resource, the error message is quite unhelpful and it is not obvious how to fix this error without looking at other similar rendering code.
This is annoying and confusing. 

```rust
// current
type Param = SRes<PipelineCache>;
pipeline_cache.into_inner().get_render_pipeline(pipeline_id);

// preferred solution
type Param = SRes<PipelineCache>;
pipeline_cache.get_render_pipeline(pipeline_id);
```        

## What solution would you like?

Is there a way we can make `SRes` work the same way in systems and render commands?

## What alternative(s) have you considered?

Add further documentation to `RenderCommand`, explaining this quirk.

**Comment by 2ne1ugly** [comment]
This seems like a limitation of `Deref` trait.
Its lifetime is based on the struct reference, not `'w` and I'm not sure if there is anyway to deref without `Deref` in current Rust 🤔.

**Comment by kurtkuehnert** [comment]
That sounds unfortunate. 
If there really is no way to get rid of this quirk then we should at least document it on the `RenderCommand` trait.
If nobody proposes a different solution, then I will make a PR soon.

**Comment by 2ne1ugly** [comment]
I was lying in my bed thinking about this problem and I remembered that Rust actually has [variance](https://doc.rust-lang.org/nomicon/subtyping.html#variance).
So I think it is possible to solve this issue 🤔 I'll work on a PR

**Comment by 2ne1ugly** [comment]
> I was lying in my bed thinking about this problem and I remembered that Rust actually has [variance](https://doc.rust-lang.org/nomicon/subtyping.html#variance). So I think it is possible to solve this issue 🤔 I'll work on a PR

Well, Rust doesn't support return type covariance yet I guess
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6bfb2e55dd412b7802fb15a5cb441490

Sorry for the false alarm

**Comment by kurtkuehnert** [comment]
No problem, thank you for trying anyway 😄. 

If we document this issue properly, then it wont confuse our users as well.
