### ISSUE TITLE
Move Msaa to a component, instead of a resource

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#7194]

**Comment by alice-i-cecile** [comment]
I take it this should be a component on individual cameras?

**Comment by JMS55** [comment]
Yes, aligning with how all the other rendering stuff is now per-camera.

**Comment by mockersf** [comment]
from #7215, msaa configuration should not be on the camera but on the window

**Comment by Aceeri** [comment]
Also ideally it shouldn't be another component, but just added to the Window component here: https://github.com/bevyengine/bevy/blob/884ebbf4b7a61d8748b2b309ab0bcdf02b51abbf/crates/bevy_window/src/window.rs#L96

**Comment by lain-dono** [comment]
A real world example where MSAA can be used in the camera, but not in the whole window:

![ss_8945ebb46c719d5f8377bfea5b0ec572c9231b33 1920x1080](https://user-images.githubusercontent.com/1550625/231954013-902b311f-cdb3-4fa2-b5ed-45d44cee11d4.jpg)

The portraits at the top left are a separate realtime scene. Sometimes you may want a better quality for them than the world map.

Using separate MSAA settings for each camera makes it easier to reimplement something like this in bevy.

**Comment by alice-i-cecile** [comment]
@JMS55 can you polish up the description and migration guide for this?
