### ISSUE TITLE
Hierarchy propagation opt-out

### ISSUE THREAD

**Issue by Aceeri** [bevyengine/bevy#7225]
## What problem does this solve or what need does it fill?
There are a lot of cases where I'd like to group entities logically together, but I can't because it would mean their positions would be required to be relative to each-other. 

For example, one common usecase I've found (maybe a bit more common for me than other people given the physics-y-ness of my project) is anything with a joint needs to not have a parent entity. Otherwise the joint will either be overridden by the transform propagation and the joint essentially doesn't exist or it explodes out to infinity because it'd try to keep correcting position.
<img width="259" alt="hierarchy" src="https://user-images.githubusercontent.com/5142292/212659571-7ec0f4ef-3edb-4dec-8668-ffe426e4b23a.png">
These are all logically the `Player 1` entity in my mental model, but the hierarchy doesn't really represent that very well, it also makes it more difficult to traverse this non-standard hierarchy which I have ended up having to do quite often.

## What solution would you like?
Adding a `Split` component that would act as if it wasn't a child of its parent during propagation.
Or maybe call it `NoTransformPropagation` if it won't be that generic over the different propagation stuffs.

## What alternative(s) have you considered?
- Having alternative hierarchies be less error prone for users to create.
- Maybe propagation as an opt in? But I don't see that worth the confusion with more basic cases.

**Comment by alice-i-cecile** [comment]
The main challenges here are avoiding serious performance hits and user-facing complexity. Definitely want this though in some form.

See #3742 for a general purpose tool for alternative hierarchies.

**Comment by Aceeri** [comment]
Actually yeah, thinking about it I think relations in general would solve this in a cleaner way.
