### ISSUE TITLE
Incorrect element resizing logic in WASM examples

### ISSUE THREAD

**Issue by LoopyAshy** [bevyengine/bevy#7250]
## Bevy version

Bevy version used for https://bevyengine.org/examples

## Hardware & Software

I used:
Browser: Brave, Firefox and Chrome and each had the same result.
I am using:
OS: `Windows 11 Pro`
CPU: `Intel i9 13900k`
GPU: `Nvidia RTX 3090 TI`

## What you did

I resized my browser in windowed mode horizontally while on the pages with WASM examples.

## What went wrong

The WASM browser element infinitely grew and sometimes the camera would zoom into the scene to match.

## Notes

This doesn't happen on https://bevyengine.org/examples/ui/button/ and instead resizes correctly.

## Screenshots

![image](https://user-images.githubusercontent.com/42229301/212842116-eb5245b5-5dbe-4be1-9ab3-63cb8219ec68.png)

![image](https://user-images.githubusercontent.com/42229301/212841858-6c0b4a1a-cab8-4381-87be-39cf1475605b.png)

![image](https://user-images.githubusercontent.com/42229301/212841776-72398429-f731-4028-ae7b-6ec8bd1eb046.png)

![image](https://user-images.githubusercontent.com/42229301/212841751-bbfe7c34-7d60-4615-8f27-99e349ffe3ef.png)

**Comment by mockersf** [comment]
This is https://github.com/bevyengine/bevy-website/issues/432

**Comment by LoopyAshy** [comment]
> This is [bevyengine/bevy-website#432](https://github.com/bevyengine/bevy-website/issues/432)

My bad, I did look through the issues but surprised I missed that one of all things.
