### ISSUE TITLE
The `GlobalTransform` did not get updated when `Parent` was removed

### ISSUE THREAD

**Issue by vby** [bevyengine/bevy#7263]
## What problem does this solve or what need does it fill?

The `GlobalTransform` did not get updated (it should be) when `Parent` was removed.

## What solution would you like?

- Always recalculate the new `GlobalTransform` then `set_if_neq`.
```rust
if transform_changed {
    *global_transform = GlobalTransform::from(*transform);
} else {
    global_transform.set_if_neq(GlobalTransform::from(*transform));
}
```

-  Or use `RemovedComponents<Parent>`, _which may have poor performance_ if there have so many entities without `Transform`.

-  Or use `Removed` change detection, _but does not exist currently_.
```rust
Query<(&Transform, &mut GlobalTransform, Removed<Parent>)>
```
```rust
if parent_removed || transform_changed {
  *global_transform = GlobalTransform::from(*transform);
}
```

## What alternative(s) have you considered?
none

## Additional context
none

**Comment by nicopap** [comment]
Bevy 0.10 will have new commands to update parent while updating the transform, see
* #7024
* #7020

**Comment by nicopap** [comment]
I may have misunderstood the issue. Could you provide a minimal reproducible example or at least try with the last `main` commit? It might have been fixed with a recent commit.

* https://github.com/bevyengine/bevy/pull/6870

**Comment by vby** [comment]
> I may have misunderstood the issue. Could you provide a minimal reproducible example or at least try with the last `main` commit? It might have been fixed with a recent commit.
> 
> * [[Merged by Bors] - Improve change detection behavior for transform propagation #6870](https://github.com/bevyengine/bevy/pull/6870)


Here is a simple test case for this.

```rust
#[test]
fn correct_parent_removed() {
    ComputeTaskPool::init(TaskPool::default);
    let mut world = World::default();

    let mut update_stage = SystemStage::parallel();
    update_stage.add_system(sync_simple_transforms);
    update_stage.add_system(propagate_transforms);

    let mut schedule = Schedule::default();
    schedule.add_stage(Update, update_stage);

    let (root, parent, child) = {
        let mut command_queue = CommandQueue::default();
        let mut commands = Commands::new(&mut command_queue, &world);
        let root = commands.spawn(TransformBundle::from_transform(Transform::from_xyz(1.0, 0.0, 0.0))).id();
        let parent = commands.spawn(TransformBundle::IDENTITY).id();
        let child = commands.spawn(TransformBundle::IDENTITY).id();
        commands.entity(parent).set_parent(root);
        commands.entity(child).set_parent(parent);
        command_queue.apply(&mut world);
        schedule.run(&mut world);
        (root, parent, child)
    };

    assert_ne!(
        world.get::<GlobalTransform>(parent).unwrap(),
        &GlobalTransform::from(Transform::IDENTITY)
    );

    // Remove parent of `parent`
    {
        let mut command_queue = CommandQueue::default();
        let mut commands = Commands::new(&mut command_queue, &world);
        commands.entity(parent).remove_parent();
        command_queue.apply(&mut world);
        schedule.run(&mut world);
    }

    assert_eq!(
        world.get::<GlobalTransform>(parent).unwrap(),
        &GlobalTransform::from(Transform::IDENTITY)
    );
}
```

**Comment by nicopap** [comment]
yeah I can reproduce. I've a fix working, I'll open a PR shortly
