### ISSUE TITLE
Can't compile any of the examples

### ISSUE THREAD

**Issue by computermouth** [bevyengine/bevy#7282]
## Bevy version

v0.9.1
v0.9.0
v0.8.1
v0.8.0

## \[Optional\] Relevant system information

rustc 1.66.1

## What you did

```
git checkout ${tag_above}
cargo run --example hello_world
```

## What went wrong

Every build, regardless of git tag failed to resolve bytemuck_derive::ByteEq

```
$ cargo run --example hello_world
   Compiling proc-macro2 v1.0.50
[...]
error[E0432]: unresolved imports `bytemuck_derive::ByteEq`, `bytemuck_derive::ByteHash`
   --> /home/computermouth/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.12.4/src/lib.rs:129:18
    |
129 |   AnyBitPattern, ByteEq, ByteHash, CheckedBitPattern, Contiguous, NoUninit,
    |                  ^^^^^^  ^^^^^^^^ no `ByteHash` in the root
    |                  |
    |                  no `ByteEq` in the root

For more information about this error, try `rustc --explain E0432`.
```

## Additional information

Debian Sid -- but producing the same error on Debian Stable.

**Comment by mockersf** [comment]
this is due to a dependency that just had a release with an issue: https://github.com/Lokathor/bytemuck/issues/165

the problematic version is going to be yanked

**Comment by mockersf** [comment]
https://crates.io/crates/bytemuck/1.12.4 has been yanked, you should be good if you clear your lock file 👍

**Comment by computermouth** [comment]
Yep, works! Interesting that the Cargo.lock is not checked in. I'm relatively new to rust, is that normal?

**Comment by mockersf** [comment]
Rust recommends to not check in the lock file for libraries: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries
