### ISSUE TITLE
Querying Window with .single() makes app panic on close

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#7287]
## Bevy version

latest main

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.1 ", kernel: "22.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

- `cargo run --example bevymark`
- click x to close window

Also, here's a minimum reproducer:
```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).add_system(sys).run();
}

fn sys(query: Query<&Window>) {
    let window = query.single();
}
```

## What went wrong
```
thread 'Compute Task Pool (2)' panicked at 'called `Result::unwrap()` on an `Err` value: NoEntities("bevy_ecs::query::state::QueryState<&bevy_window::window::Window>")', examples/stress_tests/bevymark.rs:224:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-01-20T03:11:43.479485Z  INFO bevy_window::system: No windows are open, exiting
thread 'Compute Task Pool (1)' panicked at 'called `Result::unwrap()` on an `Err` value: NoEntities("bevy_ecs::query::state::QueryState<&bevy_window::window::Window>")', examples/stress_tests/bevymark.rs:157:26
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/me/src/bevy/crates/bevy_tasks/src/task_pool.rs:354:49
```

**Comment by alice-i-cecile** [comment]
Does this only occur on bevymark? I've seen this happen for ages across virtually all apps, although I don't think it's consistent.

**Comment by rparrett** [comment]
No, but it does seem to happen consistently with (so far)
- bevymark
- contributors
- mouse_grab

**Comment by rparrett** [comment]
The trend so far seems to be any example where the window size is explicitly configured.

**Comment by alice-i-cecile** [comment]
Was this broken before the Windows As Entities PR as well?

**Comment by rparrett** [comment]
I had assumed that was the culprit, but I just checked and confirmed.

**Comment by Aceeri** [comment]
Tbh I'm not entirely sure the best way to get around this, maybe just replacing
```rust
let window = windows.single();
// ->
let window = if let Ok(window) = windows.try_single() {
    window
} else {
    return;
};
```

**Comment by dlras2** [comment]
This seems to still be happening (or is happening again). E.g. the `window_settings` example is displaying this behavior where presumably `close_when_requested` appears to be despawning the primary window before `toggle_theme`, which panics when the window is closed.
