### ISSUE TITLE
Support MSAA with 2x and 8x samples

### ISSUE THREAD

**Issue by wilk10** [bevyengine/bevy#7295]
## What problem does this solve or what need does it fill?

When checking out https://github.com/bevyengine/bevy/pull/7292 i noticed that the linked WGPU issue ( https://github.com/gfx-rs/wgpu/issues/1832 ) has been closed by https://github.com/gfx-rs/wgpu/pull/3140 . 

The WGPU issue is linked in [this comment](https://github.com/bevyengine/bevy/blob/cab065bad4302e4df427ffbafcdb112e755321ce/crates/bevy_render/src/view/mod.rs#L76), which I think is really visible to new users because adding the `Msaa` resource is one of the first settings new users learn, imo.

I'm not 100% sure what is needed in Bevy to support them, beyond offering the option to set these values, but I've seen issues being opened around trying to the the samples count to something other than 1x and 4x, and Cart [has said](https://github.com/bevyengine/bevy/issues/3961#issuecomment-1042504181) it's something Bevy should support.

## What solution would you like?

Bevy should support setting the MSAA samples count to 2x and 8x as well. Ideally by adding them to the enum introduced in  https://github.com/bevyengine/bevy/pull/7292 (if that gets merged, it seems the preferred solution based on [this other comment](https://github.com/bevyengine/bevy/pull/6954#discussion_r1053907478) by Cart).

## What alternative(s) have you considered?

At the very least imo the [linked comment](https://github.com/bevyengine/bevy/blob/cab065bad4302e4df427ffbafcdb112e755321ce/crates/bevy_render/src/view/mod.rs#L76) should reference this internal issue instead of the WGPU one, until there's support for 2x and 8x samples in Bevy.

## Additional context

Nothing else.

**Comment by devil-ira** [comment]
The issue is closed, but wgpu has not released a new version yet so we are still blocked on wgpu.

**Comment by wilk10** [comment]
Now that Bevy has upgraded on main to wgpu 0.15, is this unblocked?

**Comment by Hellzbellz123** [comment]
> Now that Bevy has upgraded on main to wgpu 0.15, is this unblocked?

should be as simple as updating the msaa struct with more variants, i have a local copy im testing on. currently i have x4 x8 x16, i do not know if theres others that should be used OR if we want too go back too the older system of specifying ints. tho i doubt theres much point above x16, heck proably even x8
someone with more experience should probably decide on that
