### ISSUE TITLE
Wireframe configuration

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#7309]
## What problem does this solve or what need does it fill?

Currently `Wireframe` is a marker component that enables wireframe for its entity. There is also a global switch to enable wireframe on all objecrts.
But sometimes it may be necessary to disable only certain entities. In this case I can't use global switch and need to add `Wireframe` component to every object I spawn except the ones I want to exclude. For example, I want to exclude wireframe for previews I that I generate:
![изображение](https://user-images.githubusercontent.com/22453358/213827999-9cc806cf-5a6c-4a5a-9cad-902f6f6fcee2.png)

## What solution would you like?

It would be better if the `Wireframe` component acted like `Visibility` - containing a boolean field to turn it on and off. And global switch could be used to enable or disable the wireframe rendering entirely.

**Comment by alice-i-cecile** [comment]
Why not just remove the component from the entities you want to exclude?

**Comment by Shatur** [comment]
Because in cases like preview where I only need to exclude one entity (the one I use to generate previews), I need to add a `Wireframe` component to every object with mesh I create. I.e. I can't use the global switch because it turns on rendering for all entities regardless of the `Wireframe` component.
