### ISSUE TITLE
Support IME events abstraction

### ISSUE THREAD

**Issue by liquidhelium** [bevyengine/bevy#7315]
## What problem does this solve or what need does it fill?

To be honest, not having input method support can be seen as a bug, which even makes me discouraged from `bevy`. Whether it is a GUI integration made by someone else (such as `bevy_egui`) or a GUI system made by ourselves, sooner or later it will have to deal with the problem of input methods. For users like us, GUI systems without input method support are not usable, so I hope we can take a small step in this regard by providing the ability to handle IME events with an abstract API.

## What solution would you like?
The definition of these events should probably be put in bevy_window/events.rs, and then we convert these events in the backend. For `winit`, the definition of these events can be found at `winit::event::ime`. Notice that we need to add methods that provide access to `window.set_ime_position`.

## What alternative(s) have you considered?

I guess you can only enter CJK characters by copy-pasting. I have to say it's very bad UX.

## Additional context

Here is a pull request that adds IME support to `egui_winit`: https://github.com/emilk/egui/pull/2046

and a solution for web: https://github.com/emilk/egui/pull/253

**Comment by liquidhelium** [comment]
I would appreciate it if someone could respond quickly, as the issue I created in some other repositories went unanswered.

**Comment by minecrawler** [comment]
related to #6213 

I'm not sure if IME should be handled in the window/events, since you'll only want to do IME in a text input - correct me if I'm wrong, but I never used it any other way...

So I'd rather see a solid base text input component, which gets re-used in other widgets. Shouldn't that be also part of the endeavour of writing the editor (dogfeeding solid, usable UI components)?

On the other hand, handling IME on a lower level (window/events) would allow other UI implementations to also write custom IME support easily. How likely is that once Bevy offers a solid solution?

**Comment by liquidhelium** [comment]
In fact I was trying bevy_egui but found it has no IME support. I tried to add this functionality to it, and then found that there is no API to handle these events.

**Comment by minecrawler** [comment]
> I would appreciate it if someone could respond quickly, as the issue I created in some other repositories went unanswered.

If you want to have a quick discussion, btw, you might find that easier on the [Discord](https://discord.gg/bevy)!

**Comment by mockersf** [comment]
I have no knowledge of how IME works, but it looks like it needs to be enabled on winit with [`Window.html::set_ime_allowed()`](https://docs.rs/winit/0.27.5/winit/window/struct.Window.html#method.set_ime_allowed)

To get winit window:
- you'll need the resource [`Windows`](https://docs.rs/bevy/latest/bevy/prelude/struct.Windows.html) in a system
- call [`Windows::primary()`](https://docs.rs/bevy/latest/bevy/prelude/struct.Windows.html#method.primary) to get the main window
- call [`Window::id()`](https://docs.rs/bevy/latest/bevy/window/struct.Window.html#method.id) to get the window id
- then with the non send resource [`WinitWindows`](https://docs.rs/bevy/latest/bevy/winit/struct.WinitWindows.html) in your system
- call [`WinitWindows::get_window()`](https://docs.rs/bevy/latest/bevy/winit/struct.WinitWindows.html#method.get_window) with the id you got before

that should give you the winit windows where you can enable IME
