### ISSUE TITLE
Documented list of `DefaultPlugins` is out-of-date.

### ISSUE THREAD

**Issue by mbrc12** [bevyengine/bevy#7332]
## How can Bevy's documentation be improved?

The list of default plugins at [`DefaultPlugins` docs](https://docs.rs/bevy/0.9.1/bevy/struct.DefaultPlugins.html) appears to be out of date. In particular, it does not list:

* `ImagePlugin` with feature `bevy_render`
* `CorePipelinePlugin` with feature `bevy_core_pipeline`
* `AnimationPlugin` with feature `bevy_animation`

as can be seen from the [source code](https://docs.rs/bevy_internal/0.9.1/src/bevy_internal/default_plugins.rs.html#25) (I might have missed one or two).

**Comment by mockersf** [comment]
so... is the correct fix to remove the (not so) manually updated list, or to update it until the next time it's out of date?

**Comment by JoJoJet** [comment]
What about adding a `plugin_group!` macro that automatically generates the struct and documentation? The docs seem very basic and easy enough to generate in a macro.

**Comment by alice-i-cecile** [comment]
The current out-of-dateness has been fixed, but I don't like having to manually rely on updating this. Leaving this open in hopes of an automated solution.
