### ISSUE TITLE
Give  `dynamic` feature a more explicit name like `dynamic_linking`?

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7334]
Could you give the feature a more explicit name like `dynamic_linking`?

_Originally posted by @mockersf in https://github.com/bevyengine/bevy/pull/7333#pullrequestreview-1264862055_

**Comment by Nilirad** [comment]
The culprit here was `bevy_dynamic_plugin`'s name being confused for the dynamic linking feature. I agree though that `dynamic_linking` is better than `dynamic`.
