### ISSUE TITLE
The utils.wgsl shader has an implicit dependency to another shader

### ISSUE THREAD

**Issue by torsteingrindvik** [bevyengine/bevy#7353]
## Bevy version

a3baf2ae869611a84cf1bc062c498ea08128cbd9 (very recent main)

## What you did

I did `#import bevy_pbr::utils` in my own plugin's shader.
I want to use that for things such as `PI`, `random1D`, and `coords_to_viewport_uv`, which can be useful to anyone.

## What went wrong

```
error: no definition in scope for identifier: 'normal_prepass_texture'
   ┌─ wgsl:44:37
   │
44 │     let normal_sample = textureLoad(normal_prepass_texture, vec2<i32>(frag_coord.xy), 0);
   │                                     ^^^^^^^^^^^^^^^^^^^^^^ unknown identifier
```

### theories about what might be going wrong

It's assumed that `mesh_view_bindings.wgsl` is imported.

That file defines `normal_prepass_texture`. But I can't just import that shader because it defines lots of bindings which I'm not using.

### workarounds that you used

I can just copy-paste the stuff in `utils.wgsl` into my own shaders.

**Comment by JMS55** [comment]
This is happening because `utils.wgsl` now needs `mesh_view_bindings.wgsl`, as of the prepass getting added to bevy. Perhaps we should move the prepass sample functions out of utils.

CC @IceSentry

**Comment by IceSentry** [comment]
I really hope we can get the new shader import stuff soon which would make this a non-issue. For now, I'll just create a `prepass_utils.wgsl`
