### ISSUE TITLE
shader_prepass example is broken

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#7375]
## Bevy version

first bad commit is c3a46822e14003970e2de0ea20ca09839a64d913

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.1 ", kernel: "22.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

- `cargo run --example shader_prepass`
- press space bar

## What went wrong

Depth information in grayscale should be shown, but it's just a black screen.

There's some error output:

```
2023-01-26T21:15:17.623605Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: expected constant, found '#'
   ┌─ wgsl:38:41
   │
38 │     cascades: array<DirectionalCascade, #{MAX_CASCADES_PER_LIGHT}>,
   │                                         ^ expected constant


2023-01-26T21:15:17.842460Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: expected constant, found '#'
   ┌─ wgsl:38:41
   │
38 │     cascades: array<DirectionalCascade, #{MAX_CASCADES_PER_LIGHT}>,
   │                                         ^ expected constant

```

**Comment by JMS55** [comment]
CC @IceSentry

**Comment by Elabajaba** [comment]
Copying my answer from the wgpu 0.15 pr

> Looks like the cascaded shadow maps (CSM) PR probably broke both of them, as I'm now getting failures when running those examples after rebasing on main with CSM.

> https://github.com/bevyengine/bevy/pull/6997 is a bit of a bodge and needs to be updated for CSM, but should fix them. https://github.com/bevyengine/bevy/pull/5703 is probably the better fix, but might not land in time for the next bevy release.

**Comment by hymm** [comment]
the post_processing example is broken too with the same error.
