### ISSUE TITLE
MSAA is unsupported on Intel+Vulkan+Linux Mesa drivers

### ISSUE THREAD

**Issue by Elabajaba** [bevyengine/bevy#7376]
See https://gitlab.freedesktop.org/mesa/mesa/-/issues/3355, and [the Mesa pr that adds support](https://gitlab.freedesktop.org/mesa/mesa/-/issues/6052).

The fix is that we need to query for Msaa support (needed anyways for implementing 2x and 8x Msaa), and fall back to no Msaa when it's unsupported.

**Comment by mockersf** [comment]
done in https://github.com/bevyengine/bevy/pull/7684
