### ISSUE TITLE
Consider promoting `bevy::render::primitives::Aabb` to `bevy_math` for interop

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#7395]
## What problem does this solve or what need does it fill?

This is similar to #5575 which was already merged, but this time for the 3D counterpart. There is no common `Aabb` type that can be easily reused and shared among crates, like `Vec3` or other math types. The current `bevy::render::primitives::Aabb` is in the render module, but it's generic enough to be used elsewhere.

## What solution would you like?

Either or all of, in order of priority:

1. "Promote" `bevy::render::primitives::Aabb`, which is a center-half-extent AABB with SIMD support (`Vec3A`) so is fairly general, to the `bevy_math` crate for sharing and reuse, without having to depend on an optional part of Bevy.

2. Add useful methods similar to what was done for `Rect` on #5575.

3. Evaluate if the center-half-extent is the best option. Min-max is an alternative with other nice properties. See for example https://fgiesen.wordpress.com/2013/01/14/min-max-under-negation-and-an-aabb-trick/ -- note that if changing the representation, we _might_ have to keep a render-only copy if the render library requires the current representation for optimization purpose.

## What alternative(s) have you considered?

Roll my own :'( -- see also #5575, same concerns.

**Comment by NiseVoid** [comment]
It seems I missed this issue when working on bounding. The `Aabb3d` type in bounding matches solution 3 so this should be done. In the future the bounding volume types from `bevy_render` should get replaced by the ones from `bevy_math`.
