### ISSUE TITLE
`App::update` crashes with default plugins due to pipelined rendering

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7412]
## Bevy version

9d52aaede325a43612bccb571f640cddfa842bc5

## What you did

Run

```rust
fn main() {
    App::new().add_plugins(DefaultPlugins).update();
}
```

## What went wrong

Two different errors, depending on the run:

1. `thread 'main' panicked at 'resource does not exist: bevy_render::ExtractStage', /home/alice/Documents/Code/bevy/crates/bevy_ecs/src/world/mod.rs:1311:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

2. `thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/bevy_render/src/pipelined_rendering.rs:143:84
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/alice/Documents/Code/bevy/crates/bevy_tasks/src/task_pool.rs:354:49`

## Additional context

This failure does not occur with App::run instead.

**Comment by hymm** [comment]
This is because only App.run calls the setup functions that are used by pipelined rendering. Is this just necessary for testing?

If it is we could add a setup/build function that you can call explicitly to run that step.

**Comment by alice-i-cecile** [comment]
I can replicate this on #7267.

Yes, I primarily want this for testing and teaching purposes. Walking one-frame-at-a-time through the app is very useful for catching bugs.

Right, that explanation makes sense. I think ultimately we should go back to `AppBuilder`, for this and other reasons. 
I'm unsure if that's the right fix for this immediately though: it's fairly controversial and invasive.

**Comment by hymm** [comment]
> I think ultimately we should go back to AppBuilder

I agree here. There's a bunch of stuff for improving plugins that can only really be done with a finalizing build step.

> I'm unsure if that's the right fix for this immediately though: it's fairly controversial and invasive.

Also agree here. I'm not sure I want to try to get something like this in before 0.10. Just adding a method you can call explicitly for testing isn't ideal, but it should work as a temporary workaround.
