### ISSUE TITLE
bevy_reflect: Array cannot be fully implemented on user-defined types

### ISSUE THREAD

**Issue by ItsDoot** [bevyengine/bevy#7430]
## Bevy version

`0.9`

## What you did

Attempted to fully implement the `Array` trait for a user-defined List-like type.

```rust
impl<T: FromReflect> Array for Listlike<T> {
    // ...
    fn iter(&self) -> ArrayIter {
        ArrayIter {
            array: self, // error: field `array` of struct `ArrayIter` is private
            index: 0, // error: field `index` of struct `ArrayIter` is private
        }
    }
    // ...
}
```

## What went wrong

There is no way to manually construct an `ArrayIter` from a separate crate.

## Additional information

It also appears that `ArrayIter` may be vulnerable to an index overflow.

**Comment by elbertronnie** [comment]
I checked all the instances of `fn iter(&self) -> ArrayIter` in the codebase. They all have the same implementation:
```rust
#[inline]
fn iter(&self) -> ArrayIter {
    ArrayIter {
        array: self,
        index: 0,
    }
}
```

I think we can make this a provided method so there would no need to implement it everywhere.

@ItsDoot @MrGVSV @jakobhellermann What are your thoughts on this as it would not allow custom implementations of `iter` in user-defined types.

**Comment by MrGVSV** [comment]
> I think we can make this a provided method so there would no need to implement it everywhere.
> 
> @ItsDoot @MrGVSV @jakobhellermann What are your thoughts on this as it would not allow custom implementations of iter in user-defined types.

Yeah a method on `ArrayIter` should be totally reasonable here. 

Unless you’re referring to a default trait implementation. If so, I'm not sure that will work without `Self: Sized`.

**Comment by elbertronnie** [comment]
> Unless you’re referring to a default trait implementation. If so, I'm not sure that will work without `Self: Sized`.

Actually I was refering to default trait implementation, but I have now understood why that won't work.

I will create a new method (or constructor) on `ArrayIter`.
