### ISSUE TITLE
transform_hierarchy example doesn't seem to do anything

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#7433]
## Bevy version

`main`

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.1 ", kernel: "22.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

`cargo run --release --example transform_hierarchy chain`

## What went wrong

It's not clear how to use this tool to stress test things.

I had assumed that it was meant to be used with the `tracing` feature, but I don't think that works without `LogPlugin`, which isn't included in `MinimalPlugins`. At least, I can't get `tracy` to connect to it.

Additionally, it looks like it probably should have `HierarchyPlugin`.

## Additional information

Discovered this while attempting to benchmark #7264

**Comment by rparrett** [comment]
Rewriting this issue...

**Comment by alice-i-cecile** [comment]
We should just remove this at this point.

**Comment by rparrett** [comment]
I hadn't seen #11760 until I looked over this issue again today, but it looks like this example was useful over there with a very small modification: using `DefaultPlugins` instead of `MinimalPlugins`.

**Comment by rparrett** [comment]
Opened #14374 as an alternative.
