### ISSUE TITLE
Bevy Audio Sync Bug

### ISSUE THREAD

**Issue by c12hz** [bevyengine/bevy#7462]
## Expected behaviour
I'm attaching an example code where I'm playing 4 audio files at the same time from the same System every time you press 'X'.
The 4 audio files are actually the exact same short 'click' sound under 4 different names.
The expected behaviour is to hear one loud click (from combining 4 copies of the click sound), and the click should sound exactly the same every time you press 'X'.

## What actually happens
What is happening currently is the individual clicks get out of sync from each other by random amounts each time you press 'X'. So you every time you press 'X' the output sounds slightly different, and it's more like a short sequence of clicks rather than a singular click.

[AudioTest.zip](https://github.com/bevyengine/bevy/files/10560878/AudioTest.zip)

**Comment by c12hz** [comment]
I get much more consistent output when running in release mode, but even in release mode the clicks still get out of sync from time to time

**Comment by A-Walrus** [comment]
Did some digging and I think I understand the issue. 
Below is a stripped down version of what is going on in this example, using `rodio` directly and not through bevy. It has the same results: not very synchronized on debug, better on release.
```rust
    // Get a output stream handle to the default physical sound device
    let (_stream, stream_handle) = OutputStream::try_default().unwrap();

    // What is happening in our example
    for _ in 0..4 {
        let source = get_source("assets/click1.ogg");
        let source = source.convert_samples();

        stream_handle.play_raw(source).unwrap();
    }
    std::thread::sleep(std::time::Duration::from_secs(5));

```
And here is some code that doesn't have this issue.
```rust
    // Get a output stream handle to the default physical sound device
    let (_stream, stream_handle) = OutputStream::try_default().unwrap();
    let mut v = vec![];

    for _ in 0..4 {
        let source = get_source("assets/click1.ogg");
        let source = source.convert_samples::<f32>();
        v.push(source);
    }
    let mut source: Box<dyn Source<Item = f32> + Send> = Box::new(v.pop().unwrap());
    for s in v {
        source = Box::new(source.mix(s));
    }
    stream_handle.play_raw(source).unwrap();
    std::thread::sleep(std::time::Duration::from_secs(5));
```

In the second example instead of playing the sounds one after another, we **gather all of them and mix**, playing the resulting mix.

**Comment by SolarLiner** [comment]
I don't agree that this is what's happening @A-Walrus. In the provided code 4 different handles are created, which means they are played at the same time and mixed directly by `rodio`, whereas adding 4 sounds to a single handle queues them to play one after the other.

In any case, the API changed in the meantime with the arrival of the component-based API, and if this problem persist I think we should open a new issue with up to date information.
