### ISSUE TITLE
`AmbientLight` docs do not explain how to use the struct

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7465]
## How can Bevy's documentation be improved?

The docs for [`AmbientLight`](https://dev-docs.bevyengine.org/bevy/pbr/struct.AmbientLight.html) do not explain how it should be used.

By experimentation (and checking the trait impls), you insert it as a resource to light the scene. This should be explained in the docs.

**Comment by alice-i-cecile** [comment]
Ah, apparently this is inserted by default via `PbrPlugin`. That would be very useful to explain too, along with listing the default values.

**Comment by rparrett** [comment]
Looks like this was fixed in #10712
