### ISSUE TITLE
UiScale no longer scales text correctly in Bevy main branch

### ISSUE THREAD

**Issue by forbjok** [bevyengine/bevy#7476]
## Bevy version

The Bevy main branch, currently commit: 1a18ab34c41a4822bf8f673106cb0ec4b9edd327

## \[Optional\] Relevant system information

Rust: 1.67.0
OS: Windows 10 Pro version 10.0.19045 Build 19045

```ignore
`AdapterInfo { name: "NVIDIA GeForce RTX 2070", vendor: 4318, device: 7943, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "528.24", backend: Vulkan }`
```

## What you did

After updating an existing game project to work with the current Bevy main branch for testing purposes, I noticed that all UI text was extremely tiny and borderline unreadable.

## What went wrong

This is because UiScale, which in 0.9.x works correctly and upscales all UI elements, doesn't seem to work on text anymore.

>what were you expecting?

UiScale to work the same as before and scale the text up, so that it matches with the rest of the UI and looks correct at all pixel scale values.

>what actually happened?

Text always stays the same size (as scale = 1.0), and there also seems to be something very odd going on with positioning, which I'm not entirely sure of the logic of. When pixel scale is increased, all text seems to move to the left, eventually completely off screen.

## Additional information

Minimal reproduction repository:
https://github.com/forbjok/bevy_ui_repro
(Press X to increase pixel scale)

![Code_nSB5bLfEUl](https://user-images.githubusercontent.com/4687674/216387424-e12a3fd8-e1f0-43f8-b6d4-9bee36945d04.gif)

**Comment by alice-i-cecile** [comment]
Thanks for the minimal reproduction :)

Next step here is probably to bisect to find the offending commit. I've added this to the milestone; I'd really like to avoid shipping this.

**Comment by rparrett** [comment]
bisected to #5589

**Comment by alice-i-cecile** [comment]
Unsurprising, thanks @rparrett.

**Comment by DanielJin21** [comment]
This piece of code may be relevant to the issue:
https://github.com/bevyengine/bevy/blob/52f06175dd27816f804771673aebe00547cc3269/crates/bevy_ui/src/widget/text.rs#L68-L71 Previous to #5589, `ui_scale.scale` was multiplied with the window's scale if a primary window exists, or used as-is if not. With the current code, `ui_scale.scale` is ignored if a primary window exists, and text will only scale according to window scale.
