### ISSUE TITLE
thread 'main' panicked at Stage does not exist or is not a SystemStage

### ISSUE THREAD

**Issue by bekraoui** [bevyengine/bevy#7511]
## Bevy version

9.1

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
  - cargo 1.67.0 (8ecd4f20a 2023-01-10)
- the operating system or browser used, including its version
  - Windows 10

## What you did

try to run create startup stages and run systems within the created stages:

`
use belly::prelude::*;
use bevy::prelude::*;

//we must run "setup_viewport" befor "setup_ui" 
#[derive(StageLabel)]
enum AppSetup{
    Viewport,
    Ui,
}

fn main() {
    App::new()
	.add_plugins(DefaultPlugins)
        .add_startup_stage(AppSetup::Viewport, SystemStage::parallel())
        .add_startup_stage_after(AppSetup::Viewport, AppSetup::Ui, SystemStage::parallel())
        .add_system_to_stage(AppSetup::Viewport, setup_viewport)
        .add_system_to_stage(AppSetup::Ui, setup_ui)
        .run();
}

fn setup_viewport(
    mut commands: Commands,
) {
}

fn setup_ui(
    mut commands: Commands, 
) {
}

`

## What went wrong

If it's not clear, break this out into:

- what were you expecting?
- what actually happened?

## Additional information
the programe panick at issuing the following error:
thread 'main' panicked at 'Stage 'AppSetup::Viewport' does not exist or is not a SystemStage',

ps : there is no compiler error.

**Comment by MrGVSV** [comment]
You’re creating startup stages but adding regular systems. You either need to add your systems as startup systems or make your stages regular stages.

**Comment by bekraoui** [comment]
Thank you, worked like a charm:

`
fn main() {
    App::new()
	.add_plugins(DefaultPlugins)
        .add_startup_stage(AppSetup::Viewport, SystemStage::parallel())
        .add_startup_stage_after(AppSetup::Viewport, AppSetup::Ui, SystemStage::parallel())
        .add_startup_system_to_stage(AppSetup::Viewport, setup_viewport)
        .add_startup_system_to_stage(AppSetup::Ui, setup_ui)
        .run();
}
`

**Comment by MrGVSV** [comment]
Awesome! @bekraoui If you need any more help, feel free to ask a question in [`#help`](https://discord.com/channels/691052431525675048/1019697973933899910) or start a [Discussion](https://github.com/bevyengine/bevy/discussions) post as well 🙂
