### ISSUE TITLE
Flaky example testing in CI

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7533]
Build failed (retrying...):
  * [run-examples](https://github.com/bevyengine/bevy/actions/runs/4108143290/jobs/7088483022)

_Originally posted by @bors[bot] in https://github.com/bevyengine/bevy/issues/7423#issuecomment-1419802907_
            
           
@mockersf and I think there's a system that's exiting the window that has a critical system order ambiguity. Hence why it only sometimes fails.

**Comment by mockersf** [comment]
command to run the example as in CI:
```
CI_TESTING_CONFIG=.github/example-run/alien_cake_addict.ron cargo run --example alien_cake_addict --features "bevy_ci_testing,trace,trace_chrome"
```

I couldn't reproduce on macOS, the issue happened on Linux in CI. It seems it didn't happen in CI in the last few runs

**Comment by alice-i-cecile** [comment]
Closing unless / until we reproduce.
