### ISSUE TITLE
Add Read-only system::run_read_only

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7558]
Good call! As a potential followup (idk if we actually need this) we could add a `ReadOnlySystem::run_readonly()`  that allows you to safely run the system with an `&World`.

_Originally posted by @cart in https://github.com/bevyengine/bevy/pull/7547#pullrequestreview-1288091587_
           

I think this would be valuable, and should be a very straightforward method to implement. Look at how System's method works for reference.

**Comment by JoJoJet** [comment]
I think we should wait until we're done with properly migrating the engine to `UnsafeWorldCell`. `&World` is still being used for interior mutability, so it feels a bit odd to also use `&World` to guarantee immutable access.

**Comment by JoJoJet** [comment]
This is unblocked by #8833.
