### ISSUE TITLE
Incorrect Text Rendering Under DX11

### ISSUE THREAD

**Issue by cwfitzgerald** [bevyengine/bevy#758]
**Bevy version**

Latest master. 

**Operating system & version**

Win10/NVidia

**What you did**

Change the wgpu backends [here](https://github.com/bevyengine/bevy/blob/master/crates/bevy_wgpu/src/wgpu_renderer.rs#L25) to DX11. Run any example with text rendering.

**What you expected to happen**

Beautiful text to grace my eyeballs

**What actually happened**

No text.

**Additional information**

I debugged this in renderdoc and it appears that when rendering text, the storage buffer in `set = 1, binding = 1` has a bind group layout entry that declares it `readonly`, but the readonly qualifier isn't used in the shader. To resolve this, either the buffer needs to be `readonly buffer` in the shader, or the bind group entry needs to have `readonly: false`. This only affects DX11 because the DX11 binding model mandates I need to trust the readonly qualifier to be correct.

This will, some day, be caught by shader validation, but shader validation for wgpu 0.6 still has a long way to go.

**Comment by mockersf** [comment]
DX11 is not supported currently
