### ISSUE TITLE
Add OR and AND combinators for system run conditions

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7584]
> I suspected that the only way to make an OR-combinator might be using a custom System impl, and now you confirmed it. So, I think it's out of scope for this PR.

Agreed. I'd like both OR and AND combinators (to follow-up #7559), but that's out of scope here.

_Originally posted by @alice-i-cecile in https://github.com/bevyengine/bevy/issues/7579#issuecomment-1424683773_

**Comment by JoJoJet** [comment]
Just to clarify the behavior of these combinators, they should short-circuit, right? A non-short-circuiting `And` combinator would be fairly useless, since you could achieve the same effect by just calling `.run_if()` multiple times.

**Comment by alice-i-cecile** [comment]
Yeah, short-circuiting is essential. And should have non-surprising behavior (barring interior mutability) because run conditions are read-only.

**Comment by JoJoJet** [comment]
In that case, I think it would be good to call these `and_then`/`or_else`, in order to emphasize the fact that they short circuit.
