### ISSUE TITLE
HDRs cannot be loaded in WASM

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy#7588]
## Bevy version

0.9.1

## What you did

I used the asset server to load an HDR in WASM.

## What went wrong

The game crashed with the console reporting `'failed to spawn thread: Error { kind: Unsupported, message: "operation not supported on this platform" }'`

## Additional information

This happens because the underlying `image` crate uses `scoped_threadpool` to decode HDRs, which spawns a thread pool: https://github.com/image-rs/image/blob/v0.24.5/src/codecs/hdr/decoder.rs#L463
As the error message says, this is not allowed in WASM

Per https://github.com/image-rs/image/issues/772#issuecomment-1382406241, we could just remove the multithreading entirely from the HDR decoding to solve this for the time being.

**Comment by mockersf** [comment]
seems it's blocked on someone making that change in the `image` crate then

**Comment by janhohenheim** [comment]
My friend @bash is working on it as we speek :)

**Comment by bash** [comment]
PR created 🙂 https://github.com/image-rs/image/pull/1857

**Comment by janhohenheim** [comment]
Little update: even after the fix, using HDRis in WASM remains of limited use since [WebGPU does not support texture filtering on 32 bit depth textures](https://gpuweb.github.io/gpuweb/#texture-format-caps) . Using filter-less samplers in Bevy is [possible, but annoying to setup](https://github.com/bevyengine/bevy/discussions/7592). Dropping texture filtering quite limits what one can do with the HDRis. This means that in practice, I ended up converting my HDRis to 16 bit depth JPGs.
