### ISSUE TITLE
Xcode debug: the platform is not currently connected

### ISSUE THREAD

**Issue by Alphapage** [bevyengine/bevy#7608]
Hello,

I'm trying to debug Bevy frames from Xcode using load_gltf example.
I follow the instructions from this video: https://www.youtube.com/watch?v=uNB4RMZg1AM
But I get this error: "the platform is not currently connected" when launching on Mac M1.

Any idea ?
Thank you in advance for your help.

**Comment by superdump** [comment]
Random guess - is your target set to macOS or iOS? I could imagine if it is set to iOS and it’s trying to connect to and run the program on an iOS device or so then it could give that kind of message.

**Comment by Alphapage** [comment]
Yes, sorry my mistake!!
Thank you very much.
