### ISSUE TITLE
Regreesion: bevy:: window ::close_on_esc doesn't work correctly

### ISSUE THREAD

**Issue by ameknite** [bevyengine/bevy#7612]
## Bevy version

Main
Commit: 9ef840e8e95e86ea7885700a0d439f2f571e536f

# Relevant system information

  - SystemInfo { os: "MacOS 13.2 ", kernel: "22.3.0", cpu: "Apple M1" }

## What you did

I was looking at the new examples and I came across this system:

`bevy::window::close_on_esc`

```
pub fn close_on_esc(
    mut commands: Commands,
    focused_windows: Query<(Entity, &Window)>,
    input: Res<Input<KeyCode>>,
) {
    for (window, focus) in focused_windows.iter() {
        if !focus.focused {
            continue;
        }

        if input.just_pressed(KeyCode::Escape) {
            commands.entity(window).despawn();
        }
    }
}
```
## What went wrong

It doesn't close the window when I press Esc.
I have to click outside the window and back inside the window and it works.

## Additional information
- It works fine in 0.9.1
- When I print `focus.focused` it says false, it doesn't seem to detect focus the first time I run the program.

**Comment by mockersf** [comment]
I'm on macOS too, and I get two focus event for the window on startup, one true then one false.

Could someone try to reproduce on another platform?

**Comment by hymm** [comment]
was this fixed by https://github.com/bevyengine/bevy/pull/7628?

**Comment by mockersf** [comment]
no, windows still start as unfocused
