### ISSUE TITLE
Migrate to `cosmic-text`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7616]
## What problem does this solve or what need does it fill?

Our font rendering is subpar. See #2404 for an example of the rendering problems and #1325 / #1017 for some missing features.

## What solution would you like?

Migrate to the well-made, well-supported [`cosmic-text`] crate that is quickly becoming the ecosystem standard.

## What alternative(s) have you considered?

We could try and fix all of these issues in the assorted font crates we depend on.

## Additional context

Iced's migration should be informative: https://github.com/iced-rs/iced/pull/1697

**Comment by tigregalis** [comment]
Some things to consider / possible limitations, when using `cosmic_text`'s existing high level APIs:

- It is not clear how to mix spans of different font sizes, see https://github.com/pop-os/cosmic-text/issues/64
- It is not clear how you supply your own font (i.e. as bytes, needed to load a font as an asset), see comment https://github.com/iced-rs/iced/pull/1610/files#r1054666431 - Iced seems to tackle this elsewhere as part of its implementation

**Comment by grovesNL** [comment]
> It is not clear how you supply your own font (i.e. as bytes, needed to load a font as an asset)

You can use [`load_font_data`](https://docs.rs/fontdb/latest/fontdb/struct.Database.html#method.load_font_data) to load a font from bytes

**Comment by tigregalis** [comment]
> > It is not clear how you supply your own font (i.e. as bytes, needed to load a font as an asset)
> 
> You can use [`load_font_data`](https://docs.rs/fontdb/latest/fontdb/struct.Database.html#method.load_font_data) to load a font from bytes

The challenge I had with it was that...

`cosmic_text` starts with a [`FontSystem`](https://pop-os.github.io/cosmic-text/cosmic_text/struct.FontSystem.html#) and borrows the `FontSystem` for all of its high level APIs:
```rust
// A FontSystem provides access to detected system fonts, create one per application
let font_system = FontSystem::new();

// A SwashCache stores rasterized glyphs, create one per application
let mut swash_cache = SwashCache::new(&font_system);

// Text metrics indicate the font size and line height of a buffer
let metrics = Metrics::new(14, 20);

// A Buffer provides shaping and layout for a UTF-8 string, create one per text widget
let mut buffer = Buffer::new(&font_system, metrics);
```

`FontSystem` holds the [`fontdb::Database`](https://pop-os.github.io/cosmic-text/fontdb/struct.Database.html) privately.

To add fonts as the application is running (such as when the asset server loads font files) we would need to access the inner `Database` somehow.

`FontSystem` only exposes a method to access the `Database` immutably via [`db`](https://pop-os.github.io/cosmic-text/cosmic_text/struct.FontSystem.html#method.db); there is no mutable method.

As a really hacky workaround:

- We could perhaps clone the `Database`.
- We could then replace the existing `FontSystem` resource with a new `FontSystem` constructed using [`new_with_locale_and_db`](https://pop-os.github.io/cosmic-text/cosmic_text/struct.FontSystem.html#method.new_with_locale_and_db).
  - Using that method though we would also have to duplicate the locale checking logic which you don't get out of the box, as you would with [`new`](https://pop-os.github.io/cosmic-text/cosmic_text/struct.FontSystem.html#method.new).
- We would also need to replace the [`SwashCache`](https://pop-os.github.io/cosmic-text/cosmic_text/struct.SwashCache.html) resource as well, as it holds a reference to the original `FontSystem`, but it doesn't seem ideal.
  - Actually can replacing the `SwashCache` even be done?
  - If it can, can it be done cheaply?
  - Does `SwashCache` holding a reference to `FontSystem` play nicely with Bevy's ECS that wants to own all the data?
  - If that's not workable, would we have to effectively reimplement `SwashCache`?

The easiest solution would probably be to fork `cosmic_text` and expose the APIs we need exposed.

**Comment by nicoburns** [comment]
> The easiest solution would probably be to fork cosmic_text and expose the APIs we need exposed, and contribute back upstream if and when they are open to the changes.

FWIW, cosmic-text seems very open to changes in general. They have already accepted PRs from both the Iced and Vizia developers. Discussion of cosmic-text development happens partly in it's github issues, but also partly in this thread in Iced's discord https://discord.com/channels/628993209984614400/1027584473631555604

**Comment by hecrj** [comment]
@tigregalis The lifetime dependencies will be most likely gone soon (see https://github.com/pop-os/cosmic-text/pull/39), but in the meantime you can [use `ouroboros` to safely deal with self-referential types](https://github.com/iced-rs/iced/blob/368cadd25a8b57ee5c41e45d1abe8d1dfb194c69/wgpu/src/text.rs#L22-L33).

For font loading, you can leverage `FontSystem::into_locale_and_db` to mutate the `Database` and then create a new `FontSystem` with `new_with_locale_and_db`. [Here's how `iced` does it!](https://github.com/iced-rs/iced/blob/368cadd25a8b57ee5c41e45d1abe8d1dfb194c69/wgpu/src/text.rs#L62-L79)

**Comment by tigregalis** [comment]
> @tigregalis The lifetime dependencies will be most likely gone soon (see [pop-os/cosmic-text#39](https://github.com/pop-os/cosmic-text/pull/39)),

Great news. That looks exactly like the design I was envisioning to resolve this. Glad to learn someone's already working on it.

> but in the meantime you can [use `ouroboros` to safely deal with self-referential types](https://github.com/iced-rs/iced/blob/368cadd25a8b57ee5c41e45d1abe8d1dfb194c69/wgpu/src/text.rs#L22-L33).

In this case, I guess it means we store the `SwashCache` and `FontSystem` together under a single resource, at least until then?

> For font loading, you can leverage `FontSystem::into_locale_and_db` to mutate the `Database` and then create a new `FontSystem` with `new_with_locale_and_db`. [Here's how `iced` does it!](https://github.com/iced-rs/iced/blob/368cadd25a8b57ee5c41e45d1abe8d1dfb194c69/wgpu/src/text.rs#L62-L79)

Ah, that's a smart workaround. And once https://github.com/pop-os/cosmic-text/pull/39 is merged, with nothing long-borrowing the `FontSystem`, it should be possible to expose a method to mutate the database directly right?

**Comment by jackpot51** [comment]
https://github.com/pop-os/cosmic-text/pull/97 has been merged, this should now be possible.

**Comment by pooroligarch** [comment]
`FontSystem::db_mut` is now [released](https://github.com/pop-os/cosmic-text/releases/tag/0.8.0).

**Comment by Zaplime** [comment]
Is this migration for 0.11 or should we expect it for another update?

**Comment by VitalyAnkh** [comment]
I'm working on this, but the progress is slow. Since 0.11 will be released one or two weeks later, it's hopefully done in 0.12.

**Comment by argxentakato** [comment]
It is very disappointing that we are unlikely to meet the 0.12 milestone. Do you have anything I can contribute?

**Comment by alice-i-cecile** [comment]
>  my PR is blocked on my own work on multi-size text upstream in cosmic-text (which is blocked on IRL commitments)
> More than happy for you to adopt the PR. There's been a lot of changes upstream in cosmic-text which will simplify this PR too, so that could be a good start.


From the OP on [Discord](https://discord.com/channels/691052431525675048/789987800014651412/1163580553384173728). https://github.com/pop-os/cosmic-text/pull/150 appears to be the linked PR.

Adopting either this PR or that PR would be incredibly useful: I'm sure the OP will be around to give feedback and review.

**Comment by viridia** [comment]
@alice-i-cecile Apparently there is a new contender for text layout: https://github.com/dfrg/parley/blob/master/doc/concept.md

**Comment by alice-i-cecile** [comment]
Neat! IMO for this sort of dependency we should prioritize stability and longevity though, and cosmic-text has a funded open source team with a long history behind it.

**Comment by viridia** [comment]
Agreed. The reason this popped up on my radar is that I've been chatting with Raph Levien, and apparently the Xilem team is going to be working on this.

**Comment by alice-i-cecile** [comment]
Ah, that's also a sensible team to rely on. Probably worth evaluating on the merits then.

**Comment by alice-i-cecile** [comment]
We've opened a new working group to handle this migration, and decide between `cosmic-text` and `parley`.

Draft design doc: https://hackmd.io/-0nNajS9QaGNu9FWg41ziA?edit

Open membership working group (join us!): https://discord.com/channels/691052431525675048/1248074018612051978
