### ISSUE TITLE
Rename `App::add_plugins` to `App::add_plugin_group`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7631]
## What problem does this solve or what need does it fill?

This method is very easily and subtly typo'd and regularly bites new users.

## What solution would you like?

Rename it to `add_plugin_group`.

## Additional context

See #7630 for an example, but I've seen this regularly.

**Comment by CmPons** [comment]
Hey, I'm not sure if this is a good first issue, but I'm starting to look into this. @alice-i-cecile I have the changes ready, just trying to test it right now.

**Comment by alice-i-cecile** [comment]
Should be easy to implement! The real trick is convincing everyone that it's a good change :)

**Comment by alice-i-cecile** [comment]
I think we should consider fixing this upstream by improving the diagnostics instead. There's not a clear argument for either API (as called out by Cart in #7643), and this is a Rust wide problem with a confusing / misleading diagnostic.

**Comment by BD103** [comment]
With `add_plugin` being deprecated and only `add_plugins` remaining, I'm going to close this as not planned.
