### ISSUE TITLE
App::add_state + additional state flushes are incompatible

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7636]
## Bevy version

0.10 pre-release

## What you did

Add an additional copy of  `apply_state_transitions::<S>` after calling `App::add_state`.

## What went wrong

The schedule panics with a `SystemTypeSetAmbiguity` error.

## Additional information

> `after(apply_state_transition::<S>)` can easily turn into a SystemTypeSetAmbiguity error if a user just adds another instance of `apply_state_transition::<S>`. If we're keeping that, we should add it to a set (probably another base set in CoreSet) and order on that.

From @maniwani in #7634.

**Comment by simbleau** [comment]
Confirmed on my side too. +1
