### ISSUE TITLE
Add an example demonstrating run conditions

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7646]
From what I can tell, none of our examples use run conditions at all (except for `.on_update()`). We should address this, but IMO there should be a separate issue for this.

_Originally posted by @JoJoJet in https://github.com/bevyengine/bevy/issues/7605#issuecomment-1427101406_
            
This should capture the combinators added in #7605 as well.

**Comment by LiamGallagher737** [comment]
I am working on this
