### ISSUE TITLE
LCH Color Function

### ISSUE THREAD

**Issue by iMplode-nZ** [bevyengine/bevy#766]
**What problem does this solve or what need does it fill?**

Colors are difficult to read. For example, it's hard to tell that `Color::rgb(0.8, 0.3, 0.7)` is pink.

**Describe the solution would you like?**

Add a LCH color function as well as the HEX colors. The LCH color space allows for colors that are somewhat related to how people actually see it.

**Describe the alternative(s) you've considered?**

N/A

**Additional context**

This blog post (https://lea.verou.me/2020/04/lch-colors-in-css-what-why-and-how/) provides a good explanation of what the LCH color space is.

**Comment by MikP0** [comment]
Hello! 
There is actually a way to make colors more readable. Just use `Color::hex` function like this:
``` Rust
let rgb_color = Color::hex("ff0000");
let rgba_color = Color::hex("ffff0001");
println!("{:?}", rgb_color); //Ok(Color { red: 1.0, green: 0.0, blue: 0.0, alpha: 1.0 })
println!("{:?}", rgba_color); //Ok(Color { red: 1.0, green: 1.0, blue: 0.0, alpha: 0.003921569 })
```
However, I do agree that another color space would be a nice addition. I'll try to take further steps in order to contribute. 
Cheers!

**Comment by LU15W1R7H** [comment]
I'd suggest #1146 for solving this issue.
