### ISSUE TITLE
Added query filter selecting entities which were not added when used alone

### ISSUE THREAD

**Issue by gwafotapa** [bevyengine/bevy#7679]
## Bevy version
0.9.1

## What you did
I used the query filter `Added` to find out if any entity of the given type had been created since last frame.
Here's a minimal working example :

```
use bevy::prelude::*;

#[derive(Component)]
struct Foo;

fn spawn_foo(mut commands: Commands) {
    commands.spawn(Foo);
}

fn added(q_foo_0: Query<Added<Foo>>, q_foo_1: Query<&Foo, Added<Foo>>) {
    println!(
        "q_foo_0: {}, q_foo_1: {}",
        q_foo_0.iter().count(),
        q_foo_1.iter().count()
    );
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(spawn_foo)
        .add_system(added)
        .run();
}

```

## What went wrong

I was expecting both queries to find one entity on the first frame and no entities on the subsequent frames,
but the first query `q_foo_0` keeps finding the Foo entity created on startup every frame.

**Comment by alice-i-cecile** [comment]
You're using it in the data field of the query (`Q`), not the filter field `F`. If you look at its values you can see the true / false correspond correctly.

Ultimately I think we should have seperate traits for `QueryData` and `QueryFilter` in order to catch this sort of problem at compile time.

**Comment by gwafotapa** [comment]
Oh I see. Thank you !
