### ISSUE TITLE
Use distinct types for query "data" generics and query "filter" generics

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7680]
## What problem does this solve or what need does it fill?

It's easy for users to accidentally mix up their "data" (`Q`) and "filter" (`F`) generics on `Query`.

For example:

- `Query<(&A, With<B>)`: forces ugly unpacking.
- `Query<(&A, Without<B>)`: likely seriously wrong.
- `Query<Changed<T>)`: probably not what the user wants.
- `Query<(), Entity>`:  nonsensical
- `Query<&A, &B>`: very weird, probably broken

See #7679 for an example of this footgun in the wild.

## What solution would you like?

1. Add `WorldQueryData: WorldQuery` and `WorldQueryFilter: WorldQuery`.
2. Split `derive(WorldQuery)` macro into two parts.
3. Only implement `WorldQueryData` / `WorldQueryFilter` for the correct `WorldQuery` types.

## What alternative(s) have you considered?

We could use a custom linter #1602, but a) this catches errors later / less elegantly and b) we don't have one yet.

**Comment by wainwrightmark** [comment]
Hi, I've had a quick go at this and gotten all the tests and examples working - there's no logic changes, just changing some types and type parameters. I haven't done any of the "fun" bits like fixing documentation and writing tests yet.

I've added `WorldQueryData: WorldQuery` and `WorldQueryFilter: WorldQuery`, implemented them for the appropriate types, and forced you to use them in the left and right hand sides of the query respectively.

The thing I'm unsure of is how the derive macros ought to work.
In bevy 0.10 you do one of these

```rust
#[derive(WorldQuery)]
pub struct DataQuery {
    a: &'static A,
}

#[derive(WorldQuery)]
#[world_query(mutable)]
pub struct MutDataQuery {
    pub a: &'static mut A,
}

#[derive(WorldQuery)]
struct FilterQuery{
    a: With<A>,
}
```

and it generates implementations of `WorldQuery` and `ReadOnlyWorldQuery` (on the same struct, unless you specify mutable). But with the split, we need a way of specifying whether to generate `WorldQueryFilter` or `WorldQueryData` or, in principle, both.

Should we use two different macros like this:

```rust
#[derive(WorldQueryData)]
pub struct DataQuery {
    a: &'static A,
}

#[derive(WorldQueryData)]
#[world_query(mutable)]
pub struct MutDataQuery {
    pub a: &'static mut A,
}

#[derive(WorldQueryFilter)]
struct FilterQuery{
    a: With<A>,
}
```

That seems good but I worry that that makes it impossible to derive both for the same struct. (Both macros would generate a `WorldQuery` impl and they would clash). Is that a use case we want to support? I think it's probably only possible for trivial or generic types anyway but I worry that doing it this way would take away that possibility.

The other options would be:

```rust
#[derive(WorldQuery)]
#[world_query(data)]
pub struct DataQuery {
    a: &'static A,
}

#[derive(WorldQuery)]
#[world_query(mutable)] //data is implied by mutable
pub struct MutDataQuery {
    pub a: &'static mut A,
}

#[derive(WorldQuery)]
#[world_query(filter)]
struct FilterQuery{
    a: With<A>,
}
```

or 

```rust
#[derive(WorldQuery, WorldQueryData)]
pub struct DataQuery {
    a: &'static A,
}

#[derive(WorldQuery, WorldQueryData)]
#[world_query(mutable)]
pub struct MutDataQuery {
    pub a: &'static mut A,
}

#[derive(WorldQuery, WorldQueryFilter)]
struct FilterQuery{
    a: With<A>,
}
```

or possibly one I haven't thought of.

**Comment by urben1680** [comment]
> That seems good but I worry that that makes it impossible to derive both for the same struct.

I would want to keep having this use case possible. I want to implement `WorldQuery` for my type that has a `&mut Foo` and a `Without<Bar>` in the same struct. Only in this combination I want to offer methods on the Item of this `WorldQuery`.

**Comment by alice-i-cecile** [comment]
I like the two distinct `WorldQueryData` versus `WorldQueryFilter` macros here: I think it's much clearer.

> I would want to keep having this use case possible. I want to implement WorldQuery for my type that has a &mut Foo and a Without<Bar> in the same struct. Only in this combination I want to offer methods on the Item of this WorldQuery.

Yeah, this is an important pattern to consider how to support. We could implement `WorldQueryData` for the filter types as well, but have them fetch `()` instead, and be omitted from the query item completely?


My personal experience has been that these types are only really used as the only type in `Query`: we could instead encourage people to use the `SystemParam` derive 🤔 But that won't give us a nice way to implement methods on the `Item` associated type, which is really what you tend to need.
