### ISSUE TITLE
Set audio volume globally

### ISSUE THREAD

**Issue by st0rmbtw** [bevyengine/bevy#7690]
## What problem does this solve or what need does it fill?

When you want to create a sound volume control system in your game It becomes really inconvenient to provide a volume to every `audio.play_with_settings()` call.  So it would be nice to provide a way to set sound volume globally to avoid boilerplate code.

## Additional context

Also, it would be nice to have a possibility to set a volume to a specific sound type (e.g. Music, Weather, Ambient) in your game.

**Comment by mockersf** [comment]
global volume could be in a resource

There is one open question: if a global volume is set, should the volume set when using `play_with_settings` be absolute and ignore the global volume settings, or relative to it?

**Comment by st0rmbtw** [comment]
I think it should be relative to a global volume. Though, we can add two functions which would respect a global volume and do not.

**Comment by undersquire** [comment]
I think there should be two functions: `play_with_settings` and `play_with_relative_settings` (or something) that makes it explicit what the behavior is.

**Comment by LiamGallagher737** [comment]
I'm going to have a go at this one, I'll let you know if I give up.
