### ISSUE TITLE
Can't add systems to multiple sets.

### ISSUE THREAD

**Issue by LiamGallagher737** [bevyengine/bevy#7702]
## Bevy version

Main branch commit 8d51f4a

## What you did

Tried to add a group of systems to multiple sets.

https://github.com/LiamGallagher737/bevy_flappy_bird/blob/aac44a1572ecb5487f829a11e88059ea7e813275/src/game.rs#L43

This is the previous solution that I was trying to clean up.
https://github.com/LiamGallagher737/bevy_flappy_bird/blob/7a8fe6c7b06e8c409f4b5e7ba81336178e123ac7/src/game.rs#L43

## What went wrong

The app threw an error on startup.
```rs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SystemInMultipleBaseSets { system: "Some(System bevy_flappy_bird::game::bird::animate_bird: {is_send})", first_set: "Update", second_set: "Update" }', E:\rust\.cargo\git\checkouts\bevy-f7ffde730c324c74\8d51f4a\crates\bevy_ecs\src\schedule\schedule.rs:196:32
```

## Additional information

Here are some related messages in the Bevy discord.
https://discord.com/channels/691052431525675048/742569353878437978/1075623498493476904

**Comment by alice-i-cecile** [comment]
The fix here should be pretty simple: adding a system to the same base set multiple times should not fail.

Make sure to include a simple test for that.

**Comment by SkiFire13** [comment]
Aren't those technically different sets? `OnUpdate<GameState>` and `OnUpdate<PlayState>` are two different types, although the type constructor is the same.

**Comment by alice-i-cecile** [comment]
Yep, they're different sets. The problem is that both of them are also nested in CoreSet::Update, which is a base set.
