### ISSUE TITLE
Make `WorldId` a `SystemParam`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7736]
While I don't think this is a bad idea, the justification of using `Local<WorldId>` has me set off a bit (akin to how `Query<Option<With<T>>>` does). Could we not make `WorldId` a `SystemParam`?

_Originally posted by @james7132 in https://github.com/bevyengine/bevy/pull/7726#pullrequestreview-1304112341_
            
This should be able to draw directly from the implementation in the linked PR: it should return the `WorldId` of the world that the system is running on.

**Comment by LiamGallagher737** [comment]
I have tested this, and it seems to work in practice, but I have no idea if it's safe or if it's the correct way to do this.
```rs
/// SAFETY: No idea
unsafe impl ReadOnlySystemParam for WorldId {}

/// SAFETY: No idea
unsafe impl SystemParam for WorldId {
    type State = WorldId;

    type Item<'world, 'state> = WorldId;

    fn init_state(world: &mut super::World, _: &mut crate::system::SystemMeta) -> Self::State {
        world.id
    }

    unsafe fn get_param<'world, 'state>(
        _: &'state mut Self::State,
        _: &crate::system::SystemMeta,
        world: &'world super::World,
        _: u32,
    ) -> Self::Item<'world, 'state> {
        world.id
    }
}
```

**Comment by james7132** [comment]
That looks generally correct to me beyond the safety comments. Something along the lines of `read-only access to shared World metadata` for `ReadOnlySystemParam`, and `A World's ID is immutable and fetching it from the World does not borrow anything` for `SystemParam` should work, bar some wordsmithing.
