### ISSUE TITLE
impl `Reflect` for `std::collections::HashMap` instead of only `bevy::utils::HashMap`

### ISSUE THREAD

**Issue by PROMETHIA-27** [bevyengine/bevy#7739]
I've seen this pop up a few times for people getting used to `Reflect` in the discord;
the std impls in `bevy_reflect` aren't general enough, and only work on `bevy::utils::HashMap`. This is also the cause of #1044.

**Comment by james7132** [comment]
Wonder if we could just make the implementation generic over the Hasher provided the entire HashMap meets certain trait requirements.

**Comment by 13ros27** [comment]
I'd be interested in having a go at this, if its still free

**Comment by james7132** [comment]
Should still be! Feel free to file a PR whenever you're ready.
