### ISSUE TITLE
Add `const fn Color::hue`, `Color::saturation` and `Color::lightness` etc

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7746]
## What problem does this solve or what need does it fill?

When working with color palettes, you often want to match the hue/saturation/lightness of existing colors.

Matching these directly is a bit frustrating: there's no easy way to check "what hue is this".

## What solution would you like?

Add methods that parallel [`Color::r`](https://docs.rs/bevy/latest/bevy/prelude/enum.Color.html#method.r) for all other provided color spaces.

## What alternative(s) have you considered?

You can work around this by storing a `const DARK_MODE_BACKGROUND_HUE` etc and using that repeatedly.

**Comment by mockersf** [comment]
not sure it's possible to have those functions as `const` as they will involve float operations when converting from one colourspace to another

**Comment by alice-i-cecile** [comment]
Yeah we may get blocked on const float arithmetic for now. Still handy to have even if not const.

**Comment by LiamGallagher737** [comment]
I'm working on it

**Comment by LiamGallagher737** [comment]
Hlsa and Lcha both have a lightness and hue values. What are your opinions on how we should differentiate in the naming. Would a simple `_hsl` or `_lch` suffix do? And if so, should this be added to all methods or only the ones with conflicts?

**Comment by alice-i-cecile** [comment]
Hmm. I'd start with it on all of them

**Comment by alice-i-cecile** [comment]
This is now obsolete, with the addition of bevy_color.
