### ISSUE TITLE
cannot load asset

### ISSUE THREAD

**Issue by christopher-wilke** [bevyengine/bevy#777]
**Bevy version**

0.2.1

**Operating system & version**

Windows 10

**What you did**

`let player_texture_handle = asset_server.load("assets/icon.png").unwrap();`

**What you expected to happen**

compiles successfully

**What actually happened**

```
let player_texture_handle = asset_server.load("assets/icon.png").unwrap();
         ---------------------                ^^^^ cannot infer type for type parameter `T` declared on the associated function `load`    
         |
         consider giving `player_texture_handle` the explicit type `bevy::prelude::Handle<T>`, where the type parameter `T` is specified 

```

**Comment by Moxinilian** [comment]
In order to determine the type of the handle you just loaded, the compiler needs a hint. You can do that by either using it somewhere in your code where it is not ambiguous, or specifying the type of the handle : `Handle<T>` where `T` is the asset type you are loading.

**Comment by christopher-wilke** [comment]
Thanks @Moxinilian for your quick reply! I am new to Rust and still in my learning phase ;)
