### ISSUE TITLE
Fine tuning FrameTimeDiagnosticsPlugin

### ISSUE THREAD

**Issue by EmiOnGit** [bevyengine/bevy#7776]
## What problem does this solve or what need does it fill?
Currently, adding the `FrameTimeDiagnosticsPlugin` will automatically log frame time, fps and frame count.
However, most of the time I am only interested in one of these options.
You could of course let the user write his own tiny system, but I think this is something that should be easily doable in bevy

## What solution would you like?
I'd still argue that the default should stay as is.
I would enable the user to use the plugin as follows
```rust
App::new()
  // adds everything as before
  .add_plugin(FrameTimeDiagnosticsPlugin::default())
  // only adds frame time
  .add_plugin(FrameTimeDiagnosticsPlugin::log_frame_time())
  // only adds fps
  .add_plugin(FrameTimeDiagnosticsPlugin::log_fps())
  // only adds frame count
  .add_plugin(FrameTimeDiagnosticsPlugin::log_frame_time())
````
## What alternative(s) have you considered?
Also I feel like the amount history size should also be easily configurable.
Which I would propose as a slight variation of the first solution using a builder.
```rust
App::new()
  // default
  .add_plugin(FrameTimeDiagnosticsPlugin::default())
  // with default history size
  .add_plugin(FrameTimeDiagnosticsPlugin::from_fps(FpsLogger::default()))
  // with configured history size
  .add_plugin(FrameTimeDiagnosticsPlugin::from_fps(FpsLogger::history_size(100)))
  // ... also for other 2 options
```
Even though, I think this would make it even more configurable, I honestly am not sure if it is to verbose.

## Additional context
**I would gladly take over the part of implementing this,**
but would be interested if this behavior is even welcomed/needed.

**Comment by LiamGallagher737** [comment]
What about having `FrameTimeDiagnosticsPlugin` be a plugin group with each option being a plugin inside, this way you can just use the `.disable<T>()` method to remove unwanted logging.

**Comment by EmiOnGit** [comment]
Also a great idea! 
Since each of the 3 options are then outsourced to their own plugin, a user could also just add this specific plugin

**Comment by mockersf** [comment]
It's already possible to filter which diagnostics are logged with https://docs.rs/bevy/latest/bevy/diagnostic/struct.LogDiagnosticsPlugin.html#method.filtered

For example:
```rust
  app.add_plugin(bevy::diagnostic::LogDiagnosticsPlugin::filtered(vec![
      bevy::diagnostic::FrameTimeDiagnosticsPlugin::FPS,
  ]));
```
will only log the FPS

**Comment by EmiOnGit** [comment]
This surely is handy too, but as you add more and more `Diagnostics`, you'd have to add them to the filter one by one right?
