### ISSUE TITLE
Add `Has<C>` `WorldQuery` type to replace `Option<&C>` when checking existence

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7811]
## What problem does this solve or what need does it fill?

I commonly find myself reaching for `Option<&C>` when I just need to check whether or not a component exists, and then branching on `Some` versus `None`.

This works well enough, but:

1. The access is more restrictive than it needs to be: we request read access, but only actually need existence checking. This limits parallelism, as these systems could run in parallel with mutating systems.
2. It's less clear to read: the pattern is a bit strange and implicit.
3. It may be measurably slower.

## What solution would you like?

Add a `Has<C: Component>` type. Implement `WorldQuery` for this, with no access required.

The item type of each query element should be `bool`.

## What alternative(s) have you considered?

We could do nothing, the eixisting pattern isn't terrible.

We could name this `Is<C>`: I'm not sure which one is clearer.

**Comment by SkiFire13** [comment]
It's pretty horrible but `Or<(With<T>,)>` (when used as query rather than filter) does yield a `bool` indicating whether the `T` is present or not. This is kinda weird though since `With<T>` by itself does not do this.

**Comment by alice-i-cecile** [comment]
Ah right, that's caused by #7680.

**Comment by BoxyUwU** [comment]
`Option<With<T>>` works which is nicer than `Or<(With<T>,)`

**Comment by BoxyUwU** [comment]
sidenote: `Or` does not return `bool` it returns `()`
