### ISSUE TITLE
Use GitHub Merge Queues instead of Bors

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#7824]
## What problem does this solve or what need does it fill?
GitHub now supports [Merge Queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue), which is what bors has been doing for us for the longest time.

## What solution would you like?
Migrate to GitHub's merge queue instead of relying on Bors.

## What alternative(s) have you considered?
Keep using Bors.

**Comment by james7132** [comment]
We probably should wait until 0.10 releases before we attempt this.

**Comment by superdump** [comment]
What benefits/drawbacks are there of changing to GitHub/continuing with bors?

**Comment by james7132** [comment]
AFAIK, GitHub's are publicly viewable and each attempt is public information, unlike bors where the permissions to view the queue are also the same that allows use of `bors r+`. It also minimizes the attack surface in the case bors is compromised for whatever reason.  Not sure if there are Actions triggers for each queue attempt, but if there are, we can have tighter control and integration with our existing CI actions.

It does, however, increase our dependence on GitHub as a platform, and we'd need to find a suitable replacement if we ever move away from GitHub for whatever reason. However, given that our Q&A is in Discussions and our extensive CI use is entirely built on GitHub Actions, I think it's probably OK to switch.

**Comment by charleskawczynski** [comment]
Hello 👋🏻 ,

My team over at [CliMA](https://github.com/orgs/CliMA) is interested in switching from bors to the GitHub merge queue (GHMQ), however, it seems that GHMQ requires at least two serially run CI cycles before merging. Our CI is a bit long (~1 hr) and doubling the time is painful.

I wanted to know, have you run into this issue as well?

**Comment by mockersf** [comment]
Hi @charleskawczynski!

Yup, same for us. The merge queue uses branch protection rules, so it means the same jobs must pass once on the PR, and once in the merge queue.

We improved by:
- parallelising as much as possible our jobs, to get fast feedbacks on a PR. If I remember correctly, with our current parallelisation GitHub actions can run on two PRs at a time, after that we reach the maximum number of free executors. It's a choice between faster feedback on an individual PR, or faster start on a group of PR
- splitting our checks in two groups. One that must pass on every update, on that must pass only on the merge queue. The second group is made of jobs that are less likely to fail if the first one pass and may take longer, but we still want to have their status

The first group, in https://github.com/bevyengine/bevy/blob/main/.github/workflows/ci.yml, takes around 15 minutes to run, but would take 1 hour if all were done sequentially, see [here](https://github.com/bevyengine/bevy/actions/runs/5074394186) for example run.
The second group, in https://github.com/bevyengine/bevy/blob/main/.github/workflows/validation-jobs.yml (see [this line](https://github.com/bevyengine/bevy/blob/a9ca40506e3dbc5048dc38601d1e3baed6f4a172/.github/workflows/validation-jobs.yml#L16) to have it not run on PR update), takes 20 minutes to run, but would take 65 minutes to run sequentially. [here](https://github.com/bevyengine/bevy/actions/runs/5070449188) is an example run.
