### ISSUE TITLE
Add a base set (like `CoreSet`) for `FixedUpdate`

### ISSUE THREAD

**Issue by jabuwu** [bevyengine/bevy#7835]
## What problem does this solve or what need does it fill?

The `CoreSet` is a useful tool for library authors to quickly push something before normal updates (via `CoreSet::PreUpdate`) or after (via `CoreSet::PostUpdate`). It allows library authors to create certain guarantees around "normal" updates without any extra work from the user (`.after`/`.before` on systems). This same guarantee is lacking from `FixedUpdate`. `FixedUpdate` has no default base set to build this functionality around, so a library must add one themselves, but only one library can do this.

## What solution would you like?

At the very least, `FixedUpdate` should have a default base set (`CoreFixedUpdateSet`), so libraries can add new base sets before or after this default base set.

A `PreUpdate` and `PostUpdate` could be added to handle most cases so each library won't have to add these themselves.

## What alternative(s) have you considered?

`FixedUpdate` could share the same `CoreSet`, so its configured identically on both update and fixed update (ignoring `CoreSet::StateTransitions` and `CoreSet::FixedUpdate`). As a newcomer to Bevy, this would probably be my expectation, as currently applying `CoreSet` to fixed update silently does nothing - it's easy to just assume it's working.

## Additional context

A natural evolution of this feature request is adding `Flush` sets which call `apply_system_buffers`, same as `CoreSet`. This isn't as crucial because work that absolutely needs to be done visually can still be done in `CoreSet::PostUpdate`, after `FixedUpdate`, but there are situations where `apply_system_buffers` is necessary in `FixedUpdate`. For example, systems that wish to immediately process newly created entities/components in the same frame require an `apply_system_buffers`.

This is another case where, if a library desires the functionality of `apply_system_buffers`, it must add one, and thus every library desiring this functionality will need to do this, resulting in redundant `apply_system_buffers`. So I think at least one default `apply_system_buffers` in `FixedUpdate` is preferable.

**Comment by alice-i-cecile** [comment]
Base sets have been removed.
