### ISSUE TITLE
XlibsWrapper Nix Dependency is Depercated

### ISSUE THREAD

**Issue by Okirshen** [bevyengine/bevy#7843]
The XlibsWrapper dependency in  [Nix dependencies](https://github.com/bevyengine/bevy/blob/latest/docs/linux_dependencies.md#nixos) is deprecated giving the error `error: 'xlibsWrapper' has been replaced by its constituents`. Those constituents are: `freetype fontconfig xorg.xorgproto xorg.libX11 xorg.libXt xorg.libXft xorg.libXext xorg.libSM xorg.libICE`.

**Comment by VitalyAnkh** [comment]
It's already fixed: https://github.com/bevyengine/bevy/pull/7044.
