### ISSUE TITLE
Add timer-based common run conditions

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7864]
## What problem does this solve or what need does it fill?

Users often want to run a system (like logging, polling or factory ticks) on a regular timer. Currently, this involves a fair bit of type-level boilerplate to define a resource type, or clever use of either run conditions or `Local` system variables.

## What solution would you like?

Create a run condition that stores a `Timer` in its `Local`, with a convenient method to generate such a run conditions.

Ideally this would look like:
```rust
app.add_system(my_system.run_if(on_timer(custom_duration))`
```

There should also be a `on_fixed_timer` variant, which uses elapsed `FixedTime`.

See the existing common run conditions in `bevy_ecs` and `bevy_input` for how to do so.

## What alternative(s) have you considered?

We could add multiple fixed time steps again (which were previously used for this), but these are not equivalent and this previous pattern was incorrect. See #7637.

## Additional context

Credit to @maniwani for the idea: I just made the ticket ;)

**Comment by jabuwu** [comment]
I'm working on it. I'm hoping to finally start my "bevy contributor" career and this seems easy enough. I wonder if `on_timer_once` conditions would be useful? I'm thinking no, they seem really niche.

Another potential API is `on_timer(Timer)` (instead of `Duration`), but its more wordy.

```
add_system(tick.run_if(on_timer(Timer::from_seconds(1., TimerMode::Repeating))))
// or
add_system(tick.run_if(on_timer(Duration::from_secs(1)))
```

I like the originally proposed idea, but throwing this out there.

**Comment by alice-i-cecile** [comment]
Yeah, I think that the original suggestion is the most generally useful and comfortable of those. Users can make their own variants if they have unusual needs.
