### ISSUE TITLE
Stageless: Cannot schedule nested tuples of systems.

### ISSUE THREAD

**Issue by rj00a** [bevyengine/bevy#7880]
## What problem does this solve or what need does it fill?

The stageless RFC describes how tuples of nested systems can be scheduled using `add_systems`. Here's a relevant snippet from the RFC:

```rust
        // Bulk-add systems
        .add_systems((
            some_system
                .in_set(MySystems::Menu)
                // Attach multiple conditions to this system, and they won't conflict with Menu's conditions.
                // (All of these must return true or this system will be skipped.)
                .run_if(some_condition_system)
                .run_if(|value: Res<Value>| value > 9000),
            // nesting tuples of systems is allowed, enabling grouped configuration of systems
            (
                some_system,
                // Choose when to process commands with instances of this dedicated system.
                apply_system_buffers,
            )
                .chain()
                // Configure these together.
                .in_set(MySystems::Menu)
                .after(some_other_system),
            
        ))
```

This functionality appears to be absent on the main branch because the relationship between `SystemConfigs` and `SystemConfig` is only one level deep. For instance, this does not compile:

```rust
fn a() {}
fn b() {}
fn c() {}

App::new().add_systems((
    (a, b),
    c
).chain());
```

## What solution would you like?

I'm not very familiar with bevy 0.10, but the problem appears to be that `SystemConfigs` is simply a flat list of `SystemConfig`. If `SystemConfigs` could contain other `SystemConfigs`, then system sets can be nested arbitrarily as described by the RFC. The relevant `IntoSystemConfigs`/`IntoSystemConfig` traits would have to be changed too.

Perhaps `SystemConfig` and `SystemConfigs` should be unified?

## What alternative(s) have you considered?

Flattening my large schedule into separate calls to `add_systems`/`add_system` and referring to the system sets by name.

## Additional context

[stageless RFC](https://github.com/alice-i-cecile/rfcs/blob/stageless/rfcs/45-stageless.md)

**Comment by JoJoJet** [comment]
Fixed by #8079
