### ISSUE TITLE
`FromWorld` should take `&World`, not `&mut World`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7908]
## What problem does this solve or what need does it fill?

The `FromWorld` trait, primarily used to initialize resources on the basis of existing data in the `World` takes a `&mut World` in its `from_world` method.

This is bad because:
- it's semantically bizarre: reading data from the `World` should not require mutable access!
- it can result in surprising mutations and side effects
- it limits where the `from_world` method can be used in end-user code
- it severely limits our ability to parallelize initialization and forces us to care strongly about ordering

## What solution would you like?

Have `from_world` take `&World` instead.

## What alternative(s) have you considered?

We could add a `from_read_only_world` method, but that definitely doesn't seem worth the complexity and fallibility implied.

## Additional context

A similar change was made to run conditions to avoid surprising mutations: they now only permit read-only system params.

**Comment by alice-i-cecile** [comment]
@james7132, playing with an initial impl, there's two problems:

1. `SystemState` uses `FromWorld`, but needs mutable access to initialize this.
2. `ComponentIdFor` uses mutable access to initialize itself.

In both cases I think we should just move these onto a method, rather than using the `FromWorld` trait.

**Comment by nicopap** [comment]
I'm with @Mathspy on this. `World` being `&mut` allows creating assets inside `FromWorld` impls. I've used this extensively in the two jam games I did. `&World` only works (most of the time) because `AssetServer` is behind a mutex.

**Comment by beeryt** [comment]
What if there were `from_world` and `from_world_mut` functions on `FromWorld`? Most access patterns I'm seeing in the examples which don't explicitly use a `&mut World` are accessing resources via `World::resource` which appears to work with a `&World`.

I didn't see any instances in my quick browse of `examples/`, but I imagine there are scenarios where a `FromWorld` impl doesn't *need* mutable access and I think the points made by @alice-i-cecile in the description are still valid.
