### ISSUE TITLE
Show an example of rendering to a texture without a window?

### ISSUE THREAD

**Issue by richardanaya** [bevyengine/bevy#7933]
## What problem does this solve or what need does it fill?

With the support of headless Bevy and Windows as entities, it would be interesting to see how one could write a CLI application that had no windows.  What interests me is how Bevy might be used for something like a stadia or unreal cloud like experience where 3D rendering happens on a remote server and is piped by video to another light client browser.

## What solution would you like?

An example of how to render to texture in examples.

## What alternative(s) have you considered?

N/A

## Additional context

N/A

**Comment by alice-i-cecile** [comment]
Likely to be blocked on #7163 :)

**Comment by richardanaya** [comment]
> Likely to be blocked on #7163 :)

Thank you! Closing this as dupe :)
