### ISSUE TITLE
Gather all examples from blog posts

### ISSUE THREAD

**Issue by EmiOnGit** [bevyengine/bevy#7935]
## What problem does this solve or what need does it fill?
First of, I'm only writing about the 0.10 and up coming releases, everything else is unrealistic
Me and I think a lot of other users often remember a cool example from the blog posts they want to reproduce/study.
Currently, there is almost no way to find the source besides asking around.
I think we all are aware that making a new release is stressful enough and no one has the time nor the extra motivation to collect and document these examples.
However, I would argue that a big part of the problem is that no infrastructure exists to collect the examples.

## What solution would you like?
A list of all examples with links to there repositories or creators.
It should be clear to the reader that the examples were not written for educational reason but to show this specific feature,
therefore the code quality doesn't have to be perfect. If someone wants to take a look it is on their own risk.

This list could be inside a small external repository which  
## What alternative(s) have you considered?
To let the external repository contain the examples.
Would have the advantage that the example owner couldn't just change or delete his example
How ever I like the thought that some time **after** the release the example owner could still cleanup the example if wanted. 

## Additional context
I also think it would be a nice way to honor the people doing the examples.

**Comment by alice-i-cecile** [comment]
Could you re-open this on https://github.com/bevyengine/bevy-website :) This is a good idea, and something we want to do, but that's where it belongs.

**Comment by EmiOnGit** [comment]
alright, will do :)
