### ISSUE TITLE
Combine `State` and `NextState`

### ISSUE THREAD

**Issue by lewiszlw** [bevyengine/bevy#7940]
## What problem does this solve or what need does it fill?

System may need receive two params to process one state (a bit redundant and counterintuitive). Is it possible that combining `State` and `NextState` into one?

**Comment by hymm** [comment]
here's some discussion from the Stageless RFC about this 
```text

**Comment by lewiszlw** [comment]
Hmmm, make sense. What about `Query`-like feature to combine resources?

**Comment by alice-i-cecile** [comment]
The `SystemParam` derive macro works nicely for that :)

I'm leaning towards "this won't actually be an improvement" because of the change detection argument, so are you okay to close this out?

**Comment by lewiszlw** [comment]
OK, I'll look at how SystemParam works.
