### ISSUE TITLE
Commands' Current Entity within Arc<Mutex<>>

### ISSUE THREAD

**Issue by iMplode-nZ** [bevyengine/bevy#795]
Commands can be cloned and passed between threads. This makes it so each thread has the same `current_entity`, which can cause interference; say if one does a `.spawn` and the other thread does a `.with` the other thread might pick up the `current_entity` from the first thread.

I suggest moving the `current_entity` to be outside of `CommandsInternal` to solve this problem.

**Comment by iMplode-nZ** [comment]
(And make `insert` set `current_entity` while you're at it...)

**Comment by cart** [comment]
In #798 we removed the arc/mutex from Commands by default, but this issue does still exist for the new `Arc<Mutex<Commands>>` system parameter. We might need to swap that out for something like `ParallelCommands`, which would maintain the current entity in each instance.

**Comment by jamadazi** [comment]
Oh ... so this explains the deadlocks that i was trying to figure out over the past few hours, from naively trying to switch to using `Arc<Mutex<Commands>>` everywhere.

**Comment by MinerSebas** [comment]
In 0,5 spawning a new Entity returns an `EntityCommands` that stores the Entity Id instead.
This means that this Issue can now be closed.

**Comment by iMplode-nZ** [comment]
I have no idea why I wanted this or why it doesn't exist so I'll close it.
