### ISSUE TITLE
why latest bevy is 0.1.0?? there are a bug with doc.rs and other doc 

### ISSUE THREAD

**Issue by syapk** [bevyengine/bevy#7955]
nothing else. or.. its the choice of carter ?

**Comment by james7132** [comment]
Can you point to where you're seeing this? The Getting Started page of the book shows 0.10.0 for me, and docs.rs shows the latest as 0.10.0 as well.

**Comment by syapk** [comment]
https://docs.rs/bevy_ecs/latest/bevy_ecs/index.html

**Comment by alice-i-cecile** [comment]
Ah, docs.rs hasn't finished building the new release yet. It'll get there soon: we just end up deprioritized.
