### ISSUE TITLE
It's possible to create aliasing mutable references using safe code by constructing custom queries

### ISSUE THREAD

**Issue by easynam** [bevyengine/bevy#796]
**Bevy version**

5bd6deb9749067143efb2dbb681448d94af54e83 (current master)

**Operating system & version**

Windows 10

**What you did**

I've been digging through the ecs code, and the fact that you can construct queries safely means that bevy lets you make and run incompatible queries without unsafe code, which can result in aliasing mutable pointers etc.

The following thread local system, run on a world with a single entity that has a Transform shows the mutable access happening:
```
fn query_test(world: &mut World, resources: &mut Resources) {
    let access = TypeAccess::new(vec![], vec![]);

    let mut query1 = Query::<(Entity, &mut Transform)>::new(world, &access);
    let mut query2 = Query::<(Entity, &mut Transform)>::new(world, &access);

    for (entity1, mut transform1) in query1.iter_mut() {
        for (entity2, mut transform2) in query2.iter_mut() {
            dbg!(transform1.translation);

            transform1.translation += Vec3::new(1.0, 0.0, 0.0);
            dbg!(transform2.translation);
        }
    }
}
```
And the log output:
```
[src\main.rs:45] transform1.translation = Vec3(
    0.0,
    0.0,
    0.0,
)
[src\main.rs:48] transform2.translation = Vec3(
    1.0,
    0.0,
    0.0,
)
```

**Comment by cart** [comment]
Hmm yeah good point. I think Query::new() needs to be `unsafe`.

**Comment by memoryruins** [comment]
Would it make sense to hide this method (or make it private) from users too?
So far in thread local systems, I have only accessed queries through `World`, which correctly errors.
```rust
fn system(world: &mut World, _resources: &mut Resources) {
    let mut query1 = world.query_mut::<(Entity, &mut Transform)>();
    let mut query2 = world.query_mut::<(Entity, &mut Transform)>();
    for _ in query1 {}
}
```
```
error[E0499]: cannot borrow `*world` as mutable more than once at a time
  --> src\main.rs:20:22
   |
19 |     let mut query1 = world.query_mut::<(Entity, &mut Transform)>();
   |                      ----- first mutable borrow occurs here
20 |     let mut query2 = world.query_mut::<(Entity, &mut Transform)>();
   |                      ^^^^^ second mutable borrow occurs here
21 |     for _ in query1 {}
   |              ------ first borrow later used here
```

**Comment by cart** [comment]
Yeah generally users shouldn't be calling Query::new. My rational was that somebody in the future might want to do their own IntoSystem impl. But that's honestly pretty unlikely
