### ISSUE TITLE
Rename Quad to Rectangle

### ISSUE THREAD

**Issue by lewiszlw** [bevyengine/bevy#7973]
## What problem does this solve or what need does it fill?

I'm a game dev beginer. When I first saw 2d shape `Quad`, I'm very confusing. According to wikipedia https://en.wikipedia.org/wiki/Quadrilateral , quad is completely different from rectangle, but bevy treat quad as rectangle everywhere. I found some other engines do the same too. Could you explain why? (I didn't find explation in google)

**Comment by james7132** [comment]
A Quad specifically exists on a singular plane embedded in a 3D space. A rectangle is a 2D object.

Should note that any skew in the quad's transform would also result in it no longer being a rectangle on any plane in the global frame of reference.

We also have a dedicated 2D `Rect` type too. Renaming it to `Rectangle` would only cause even more confusion.
