### ISSUE TITLE
`DetectChanges` + `DetectChangesMut` traits should be exported in prelude

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7987]
## What problem does this solve or what need does it fill?

Traits are hard to discover and add useful functionality.

Previously, `.is_changed` and `.is_changed` etc were just ordinary methods. In 0.10, these stopped compiling as the functionality was added to a trait.

## What solution would you like?

Add these to the bevy_ecs `prelude` module.

**Comment by LiamGallagher737** [comment]
I'll take this

**Comment by LiamGallagher737** [comment]
Aren't they already being exported?

https://github.com/bevyengine/bevy/blob/2908bb5e8a3ec00b883c7120a7a69f6e34bb642e/crates/bevy_ecs/src/lib.rs#L37

**Comment by alice-i-cecile** [comment]
Yeah looks like it. Closing out: I appear to have stumbled on this due to not importing the prelude in the file I was migrating.
