### ISSUE TITLE
Deprecate `App::add_system` in favor of allowing single systems to be passed into `add_systems`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#7992]
## What problem does this solve or what need does it fill?

There are several problems here:

1. It's easy to typo `add_system` as `add_systems` and vice versa.
2. The APIs are duplicative and somewhat confusing.
3. The APIs are annoying to refactor between.
4. Working with the complex mess of traits is a pain when writing app extension methods and internally.

## What solution would you like?

1. Use the same trick as in #2975 and impl the relevant trait for single systems.
2. Deprecate `App::add_system`.
3. Remove all of the single system traits if possible.

This *must* have a deprecation notice to reduce the migration pain.

## Additional context

Discussed on [Discord](https://discord.com/channels/691052431525675048/749335865876021248/1083210064782970970) with @cart. 

We could do the same thing for plugins later. See #7631 for a parallel problem there.

**Comment by hymm** [comment]
Should this be closed? add_system was deprecated in https://github.com/bevyengine/bevy/pull/8079.
