### ISSUE TITLE
Consider making mutating Assets<T> more Scheduler friendly 

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#8]
Modifying an asset currently requires grabbing a mutable reference to `Assets<T>`. This makes sense conceptually, but Legion's Scheduler (correctly) synchronizes when a mutable reference is grabbed. This means multiple systems requiring mut access to the same `Assets<T>` storage cant run in parallel.

It is worth adding some interior mutability / `RwLock`s to `Assets<T>` to see if this improves performance for common use cases.

**Comment by alice-i-cecile** [comment]
We encountered this in https://github.com/bevyengine/bevy/pull/6341, where there were a large number of spurious system order ambiguities caused by Assets<Image>.

**Comment by cart** [comment]
Closing this because I'm not convinced it is worth solving. The odds of multiple systems writing assets at the same time (and that being a bottleneck) is slim, whereas something like RwLock-ing everything would be a constant overhead.

If this ever shows up in benchmarks we can reconsider.
