### ISSUE TITLE
Use cargo's sparse protocol in CI

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#8004]
## What problem does this solve or what need does it fill?
Rust 1.68 stablizes the [Cargo sparse protocol](https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol) to reduce the time spent updating Cargo's index. 

To my knowledge, we're caching this index already, but it doesn't hurt to use a more efficient way of fetching our dependencies.

## What solution would you like?
Set `CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse` in our `.cargo/config.toml` or in our CI environment variables.

## What alternative(s) have you considered?
Don't.

**Comment by SkiFire13** [comment]
Looks like CI uses `dtolnay/rust-toolchain@stable` which should automatically set `CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse`

**Comment by james7132** [comment]
https://github.com/dtolnay/rust-toolchain/blob/stable/action.yml#L102

Oh dang, already solved!
