### ISSUE TITLE
WorldQuery derive State and Fetch types are still accidentally nameable

### ISSUE THREAD

**Issue by ItsDoot** [bevyengine/bevy#8010]
## Bevy version

Latest commit as of writing ([`7d9cb1c`](https://github.com/bevyengine/bevy/commit/7d9cb1c4ab210595c5228af0ed4ec7d095241db5))

## What you did

```rust
#[derive(WorldQuery)]
pub struct Client<S: ClientState> {
    pub state: &'static S,
    // ...
}

pub trait ClientState: Component {}
```

## What went wrong

```rust
error[E0404]: expected trait, found struct `ClientState`
  --> crates/example/src/client.rs:11:22
   |
11 | pub struct Client<S: ClientState> {
   |                      ^^^^^^^^^^^ not a trait
...
35 | pub trait ClientState: Component {
   |           ----------- you might have meant to refer to this trait
   |
help: consider importing this trait instead
   |
1  | use crate::client::ClientState;
   |
```

## Additional information

To workaround it currently, we can prepend `self::` to the struct bound:
```rust
#[derive(WorldQuery)]
pub struct Client<S: self::ClientState> {
    pub state: &'static S,
    // ...
}
```

**Comment by JoJoJet** [comment]
Interesting, I'll look into this. Not sure if there's a clean way of solving this, but it should at least be possible to *check* for this footgun and emit a descriptive error message.

**Comment by JoJoJet** [comment]
Similar: #1727.

I should have a fix for both of these up pretty soon.
