### ISSUE TITLE
`Text2dBundle::text_anchor` is inverted on one axis

### ISSUE THREAD

**Issue by benfrankel** [bevyengine/bevy#8011]
## Bevy version

`0.10.0`

## What you did

```rust
use bevy::prelude::*;
use bevy::sprite::Anchor;

fn set_up(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera2dBundle::default());
    commands.spawn(Text2dBundle {
        text: Text::from_section(
            "Hello, world!",
            TextStyle {
                font: asset_server.load("Ubuntu-B.ttf"),
                font_size: 64.0,
                color: Color::BLACK,
            },
        ),
        text_anchor: Anchor::TopLeft,
        ..default()
    });
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(set_up)
        .run();
}
```

With `assets/Ubuntu-B.ttf` in the project directory.

## What went wrong

- Expected the text to be to the _bottom right_ of its transform (the center of the window), since its anchor point should be to its top left.
- Saw the text to the _bottom left_ of its transform.

## Additional information

Probably relevant line of code:

https://github.com/bevyengine/bevy/blob/7d9cb1c4ab210595c5228af0ed4ec7d095241db5/crates/bevy_text/src/text2d.rs#L106

**Comment by ickshonpe** [comment]
I'm pretty sure what happened here is that I just can't tell left from right.
I added a simple text anchor case to the `Text2d` example:

<img width="549" alt="text2d_correct" src="https://user-images.githubusercontent.com/27962798/224294474-14504365-2772-4bae-927e-a75f36be9b07.PNG">

that's what you expected it to be?
