### ISSUE TITLE
Missing `in_schedule` API for `configure_set`

### ISSUE THREAD

**Issue by devil-ira** [bevyengine/bevy#8020]
## What problem does this solve or what need does it fill?

The inconsistency with `add_system` is probably unintentional and may confuse users.
Avoid the need to use `edit_schedule` just to configure a set in a specific schedule.

## What solution would you like?

I really think we should add this in the patch release (0.10.1).
This is a simple but core bit of API that's missing.

## What alternative(s) have you considered?

Adding it in 0.11.

## Additional context

https://github.com/bevyengine/bevy/issues/8013#issuecomment-1463607084

**Comment by alice-i-cecile** [comment]
I'm on board with cherrypicking this into 0.10.1 if we can get it working.
