### ISSUE TITLE
EventReader is_empty() false multiple times if you don't use iter()

### ISSUE THREAD

**Issue by AlexOkafor** [bevyengine/bevy#8031]
## 0.10.0
`cargo 1.70.0-nightly (7d3033d2e 2023-03-08)`
`Windows 11`

## What you did
I was writing some event code and I had considered using the expression:
```rust
fn read_event(reader: EventReader<MyEvent>) {
    if reader.is_empty() {
        return;
    }
    println!("Event received!");
}
```
to short-circuit a system and had assumed it's equivalent to:
```rust
fn read_event_iter(mut reader: EventReader<MyEvent>) {
    for _ in reader.iter() {
        println!("Event received via iter!");
    }
}
```
With the caveat that as long as a single event is coming through, they should function identically. 1 output when 1 event is sent. i started seeing the "Event received" twice in my logs and the iter version only once. This _only_ happens when you've got the reader scheduled _after_ the writer. The `read_event_iter()` system works as expected regardless of the ordering of the systems.

Am I making an incorrect assumption on how event readers and writers work or is this an actual bug?
 
Complete repo below:
```rust
use bevy::prelude::*;

struct MyEvent;

#[derive(Resource, Default)]
struct Checker {
    wrote: bool,
}

fn write_event(mut writer: EventWriter<MyEvent>, mut checker: ResMut<Checker>) {
    if checker.wrote {
        return;
    }
    writer.send(MyEvent);
    checker.wrote = true;
}

fn read_event(reader: EventReader<MyEvent>) {
    if reader.is_empty() {
        return;
    }
    println!("Event received!");
}

fn read_event_iter(mut reader: EventReader<MyEvent>) {
    for _ in reader.iter() {
        println!("Event received via iter!");
    }
}

fn main() {
    App::new()
        .add_event::<MyEvent>()
        .insert_resource(Checker::default())
        .add_plugins(MinimalPlugins)
        .add_system(write_event)
        .add_system(read_event.after(write_event))
        .add_system(read_event_iter.after(write_event))
        .run();
}

```
## What went wrong

I was expecting the status of whether we have an event or not to be identical in both systems either via the `is_empty()` method or the `iter()` method. What ended up happening was it seemed `iter()` worked as expected in every case while `is_empty()` doesn't in some cases.

## Additional information
Interestingly enough, if I remove the `MinimalPlugins`, the bug goes away.

**Comment by AlexOkafor** [comment]
Addendum:
I noticed the example for [is_empty()](https://docs.rs/bevy/0.8.0/bevy/ecs/event/struct.EventReader.html#method.is_empty)
suggests using `clear()`.

I had initially understood it as a way to single-flight events and not having to deal with multiple events in a single frame, whereas in my case, there is only ever 1 event fired so I didn't think it would be an issue. 1 event would flip is_empty() to false for 1 frame, and the next frame it would get cleaned up.

If this is as designed, then feel free to close.

**Comment by JoJoJet** [comment]
You are correct, this is intended behavior. One way to consume all events in a single expression is `reader.iter().last().is_some()`

**Comment by AlexOkafor** [comment]
> You are correct, this is intended behavior. One way to consume all events in a single expression is `reader.iter().last().is_some()`

Ah ok, thank you!
