### ISSUE TITLE
0.9 -> 0.10 migration errors

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#8033]
Here's a list of migration errors with no corresponding items in the migration guide:

- The stageless migration really doesn't explain the basics of how to migrate from _e.g._ `add_system_to_stage()` to ... (?) There's not even a single example.
- `ReportExecutionOrderAmbiguities` (likely: `bevy::ecs::schedule::ScheduleBuildSettings::ambiguity_detection`)
- `ModifiesWindows` (?)
- `StageLabel` (?)
- `MonitorSelection` moved to inner of `WindowPosition`, `Window::monitor` field deleted
- `App::add_system_set()` removed, how to replace?
- `ResMut<State<X>>` doesn't build anymore; this needs the new `States` trait which is not mentioned in the migration guide
- `State::current()` (likely `state.0`). (`NextState` is mentioned but it's not super clear either)

(TODO : didn't finish my update)

**Comment by alice-i-cecile** [comment]
Can you reopen this on the bevy-website repo? The changes need to be made there <3

**Comment by djeedai** [comment]
Reopened as bevyengine/bevy-website#603.
