### ISSUE TITLE
Transparency_3d example looks broken

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#8092]
## Bevy version

13196613ee3a1add2e525dc8d6a52d8534ebef81

Against the background, part of the cube still seems to show even when it should be faded out.

![image](https://user-images.githubusercontent.com/47158642/225158244-edaf12af-b69b-4187-8f08-8ca6cd4c42c8.png)

![image](https://user-images.githubusercontent.com/47158642/225158203-3d5629db-8b9e-4bd2-922e-1e8535c8f343.png)

**Comment by rparrett** [comment]
I can't seem to reproduce on an MacOS (M1).

**Comment by rparrett** [comment]
Also unable to reproduce with
```
AdapterInfo { name: "NVIDIA GeForce GTX 1660", vendor: 4318, device: 8580, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "472.12", backend: Vulkan }
SystemInfo { os: "Windows 10 Home", kernel: "19044", cpu: "Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz", core_count: "4", memory: "16.0 GiB" }
```

**Comment by geieredgar** [comment]
I also couldn't reproduce this, but what I noticed was that my background color is different.
![Screenshot from 2023-03-15 20-19-29](https://user-images.githubusercontent.com/7457961/225419803-3d8fdaaf-b066-44d5-9816-f24f0fecd7ca.png)
It somehow looks like that only fragments that were never written to have this darker background color (see the edges of the plane or the sphere, which also have this more light grey artifacts).

**Comment by JMS55** [comment]
The darker colors is a known issue https://github.com/bevyengine/bevy/issues/7318.

I'm going to close this issue, as I think it's just a driver bug with mesa/intel igpus. It's not the first time this has happened...
