### ISSUE TITLE
Asset Server assets not found after upgrade to 0.3

### ISSUE THREAD

**Issue by btrepp** [bevyengine/bevy#810]
**Bevy version**

0.3 from cargo

**Operating system & version**

Windows 10

**What you did**

Upgraded from bevy 0.1 to 0.3

Tried to load an asset with assert_server.load("folder/asset.ext")

**What you expected to happen**

Asset loaded.

**What actually happened**

Asset loader fails with file not found

**Additional information**

This is in a workspace application. Where assets are at the root, 

I have also moved them into being next to the exectuable project (in case it is ran from there). 
Copying the assets to be near the compiled .exe file in the target folder. 
Running it directly instead of cargo run.
Also changing the path to be windows style.

While this is a custom asset, it appears to me its failing to try to load even find the files. I'm not sure why, i suspect maybe the behaviour of current working directory + relative paths is the issue here.

```
thread 'thread 'IO Task Pool (1)IO Task Pool (0)' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: PathLoaderError(NotFound("assets/ship.aseprite"))called `Result::unwrap()` on an `Err` value: PathLoaderError(NotFound("assets/background.aseprite"))', ', C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_asset-0.3.0\src\asset_server.rsC:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_asset-0.3.0\src\asset_server.rs::295295::6060

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task thread panicked while executing: Any', C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.3.0\src\task_pool.rs:75:18
```

**Comment by kumorig** [comment]
I ran into this as well and looked at the updated examples. Now it assumes you are using a folder named "assets"
So if you used to do `let font: Handle<Font> = asset_server.load("assets/fonts/FiraMono-Medium.ttf");`
you need to change it to `let font: Handle<Font> = asset_server.load("fonts/FiraMono-Medium.ttf");`

**Comment by btrepp** [comment]
Ah this makes me have to rethink my assetloader. I was shelling out to convert unknown asset to png, in a tempdir from the OS. This works in 0.1x but if all assets now must be in the asset folder I must rethink the design.

I suspect it may just be easier to add this as an xtask for compiling my assets, and wait until atelier is integrated instead.

**Comment by btrepp** [comment]
Also for anyone who is a bit perplexed as to where the assets folder should be. Here's what I have (in a workspace project)

assets at workspace root = doesn't work
assets at target/debug/assets = works only if running compiled game from target/debug
assets at workspaceroot/mainentry/assets = works.

**Comment by Gregoor** [comment]
For me `workspace_root/assets` worked btw. In case we mean the same thing with `workspace_root` (where your `Cargo.toml` is located).

**Comment by cart** [comment]
Yup the rules are:

1. Assets (by default) are rooted at `ROOT/assets`. This folder can be configured by overriding the `AssetFolderSettings` resource.
2. When using `cargo run` it will automatically detect the cargo workspace root and make that `ROOT`
3. When running the binary directly, it will make `ROOT` the folder containing the binary

**Comment by CAD97** [comment]
> 3. When running the binary directly, it will make `ROOT` the folder containing the binary

The way it's currently set up, that means that running under vscode-lldb from vscode is looking in the target directory for the assets folder, which is unfortunate.

> 2. When using `cargo run` it will automatically detect the cargo workspace root and make that `ROOT`

To be more specific, it checks `$env:CARGO_MANIFEST_DIR`, which is "[The directory containing the manifest of your package](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates)", i.e. your package manifest directory, not the workspace root. [There is currently no way to actually get the workspace root](https://github.com/rust-lang/cargo/issues/3946), beyond [calling `cargo metadata`](https://github.com/mitsuhiko/insta/blob/b113499249584cb650150d2d01ed96ee66db6b30/src/runtime.rs#L67-L88) or just doing what cargo does (walk up the fs tree looking for a `Cargo.toml` with `[workspace]`).

-----

That said, I don't think there's really a better option here, beyond explicitly noting at some point that `$env:CARGO_MANIFEST_DIR` is involved in the lookup path, and giving some way of overriding that behavior if people need specialized behavior. Requiring certain cargo environment variables such as `$env:CARGO_MANIFEST_DIR` to be set by the debugger doesn't seem like too much of a burden, so long as it's noted.

**Comment by johnnyw** [comment]
This took me a couple of reads and diving into `file_asset_io.rs` to understand what's going on in regards to debugging inside VS Code, so in case anyone else stumbles on this thread by googling like I did, adding `"env" : { "CARGO_MANIFEST_DIR" : "${workspaceFolder}" }` to my `launch.json` configurations set things right.

I know CAD97 basically said as much, just thought I'd make it more explicit for Rust VS Code debugging newbies like me. :slightly_smiling_face:

I wonder if there's a case to be made for noting this in debug panic messages when this `assets` folder isn't in the folder containing the binary.
