### ISSUE TITLE
`crate_name` misused in Bundle macro

### ISSUE THREAD

**Issue by Plecra** [bevyengine/bevy#812]
https://github.com/bevyengine/bevy/blob/f54788527be49c445ec6e1c8831496a821d4fcc2/crates/bevy_ecs/hecs/macros/src/lib.rs#L54

`crate_name` returns the new name of the crate if it has been renamed, making this sort of import more robust. The "real" name should instead be used:

```rust
let path_str = if let Ok(name) = crate_name("bevy") {
    format!("{}::ecs", name)
}
// ...
```

**Comment by cart** [comment]
Resolved by #808
