### ISSUE TITLE
A helper system to set a state

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#8139]
## What problem does this solve or what need does it fill?

Sometimes you need to change state on some condition (resource removal or insertion, for example). But writing systems that just set state is tedious.

## What solution would you like?

It would be great to have a build-in helper that accepts the state and returns a function that sets the state to the specified value. Example:

```rust
app.add_system(set_state(MyState::MainMenu).run_if(resource_removed::<GameWorld>()));
```

Should be very trivial to implement.

**Comment by alice-i-cecile** [comment]
I think this is a) a bit too magic and b) very easy for users to write their own helper for. I'm not in favor of adding this.

**Comment by Shatur** [comment]
Good point. I just noticed that after migration to 0.10 I sometimes have a few repetitive systems like [this](https://github.com/dollisgame/dollis/blob/9b9acb51ad4332e8450c0cc547570db07c25aab4/src/core/game_world.rs#L51-L57).

**Comment by alice-i-cecile** [comment]
Yep, perfectly reasonable, but we can let users build this out as they need it :)
