### ISSUE TITLE
Port hecs EntityBuilder::add_bundle

### ISSUE THREAD

**Issue by mvlabat** [bevyengine/bevy#814]
This method adds a convenient way to build an entity from a bundle. Introduced in https://github.com/Ralith/hecs/commit/5d29b318a09b7878dcf84ff2e920760e1b54a100

**Comment by alice-i-cecile** [comment]
From the link:
```
    /// Add all components in `bundle` to the entity.
    ///
    /// If the bundle contains any component which matches the type of a component
    /// already in the `EntityBuilder`, the newly added component from the bundle
    /// will replace the old component and the old component will be dropped.
 ```

This seems redundant to [Commands::insert](https://docs.rs/bevy/0.4.0/bevy/ecs/struct.Commands.html#method.insert). Am I missing some nuance?

**Comment by mvlabat** [comment]
Yeah, I believe this is not actual anymore, thanks. `EntityCommands` provides all the needed functions.
