### ISSUE TITLE
TextureAtlasBuilder does not pad the textures

### ISSUE THREAD

**Issue by GlennFolker** [bevyengine/bevy#8150]
## Bevy version
`0.10.0`

## Relevant system information
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
$ uname -r
5.19.0-35-generic
```
```rs
AdapterInfo { name: "Intel(R) HD Graphics 520 (SKL GT2)", vendor: 32902, device: 6422, device_type: IntegratedGpu, driver: "Intel open-source Mesa driver", driver_info: "Mesa 22.2.5", backend: Vulkan }
```

## What I did
- Enable linear filtering by adding `ImagePlugin::default_linear()`.
- Pack several textures (that have no "free" borders of clear textures) into an atlas with `TextureAtlasBuilder`.
- Draw some stuff with it.
- There are some stray pixels in the edge of some sprite rectangles.
![image](https://user-images.githubusercontent.com/63218676/226598902-8059cd1f-ffec-4a9a-8f89-179948dfcb2a.png)
- Increase the sprite canvas size allocating a border of transparent pixels to simulate padding, now the stray pixels are gone.
![image](https://user-images.githubusercontent.com/63218676/226599050-f48da04d-bd1a-43d5-b187-51c074d3af60.png)

## Additional information
This is most likely caused by lack of padding in the atlas texture, causing linear filtering to accidentally sample from other sprites.

**Comment by thetrav** [comment]
On the flip side of this I've noticed that when using a texture atlas with spacing (which I do for 2d tile map games) and default_nearest, at some zoom levels it picks the border pixels leaving my game with many vertical and horizontal lines.

I read about some artifacts coming out of MSAA however turning it on and off seems to have no impact, pretty sure it's in the texture atlas somewhere

**Comment by GlennFolker** [comment]
> it picks the border pixels leaving my game with many vertical and horizontal lines.

That's why some people also "bleed" the pixel one or two pixel into the padding. So for example, 4 pixels for padding and 1 pixel for bleeding.

**Comment by thetrav** [comment]
Yes, I guess I could solve it that way.  It's probably even possible to write a bit of code that takes the input tile-map (I'm not an artist I'm just using CC free stuff) spaces it out more and just duplicates the pixels on the borders.

Still probably won't look 100% pixel perfect, which makes me a little sad, but will be a lot better than the mesh of flat window background colour.  Thanks for the tip.

**Comment by ickshonpe** [comment]
I made a crate that implements an alternative TextureAtlasBuilder that adds padding:
https://crates.io/crates/bevy_texture_atlas_tools

It hasn't been updated for a while because some changes in 0.10 broke my TextureAtlas crates, 0.11 reversed those changes though. It's really simple and you can probably fork it and update it yourself, or you can wait I plan to put aside an afternoon next week to update my third-party crates (at least the useful ones).
