### ISSUE TITLE
Add Roadmap

### ISSUE THREAD

**Issue by vladislav1nikov** [bevyengine/bevy#8159]
It would be nice to add a Roadmap with goals for the year so that the community understands Bevy's goals and plans.

An example of a good roadmap: https://github.com/flutter/flutter/wiki/Roadmap

**Comment by alice-i-cecile** [comment]
> As of a few moments ago, the roadmap has been retired. The decision was to have more targetted project boards to keep track of smaller targeted features for each focus area of the engine. A new one under the "beta projects category at the org level will be made soon with more actionable items on each card.

https://github.com/bevyengine/bevy/issues/2399#issuecomment-1061189336

This was tried and ultimately wasn't a good fit for this project. The upcoming milestones (and "What's Next" from the blog posts) are our decentralized alternative for the time being.
