### ISSUE TITLE
UI node gets compressed in `ui` example scrollable area boundary

### ISSUE THREAD

**Issue by doup** [bevyengine/bevy#8167]
## Bevy version

`v0.11.0-dev` (ce33354cee55322b12768d4ef7da58ce02adc43d)

## Relevant system information

```
AdapterInfo { name: "Apple M2 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

- In the `ui` example, scroll until a node shows at the boundary

## What went wrong

See how `Item 18` gets vertically compressed when it's on the boundary:

![image](https://user-images.githubusercontent.com/188612/227031999-056714d3-d9c9-44e2-bcd3-b350f4b81b02.png)

For comparison, this is how it should look like (this image is when the node it's not at the boundary):

![image](https://user-images.githubusercontent.com/188612/227032065-ee2d8a8b-aac6-4548-b86c-f7a82f69fc14.png)

I've debugged in XCode and I'm seeing this:

![image](https://user-images.githubusercontent.com/188612/227038329-3ef8a728-fab9-4e16-a4c6-385b9667fff7.png)

I've compared the Y position & UVs for the letter `m` from `Item 17` and `Item 18`:

![image](https://user-images.githubusercontent.com/188612/227043478-d7721349-8d0e-4ea4-86e4-69ececcf4965.png)

<img width="241" alt="image" src="https://user-images.githubusercontent.com/188612/227043573-875797c5-dad2-4192-8b37-f12bf81b95b9.png">

- The height of `Item 17` `m` letter is `9.5` (pos 2-1), and vertical UV range is `0.37` (uv 2-1)
- The height of `Item 18` `m` letter is `3.5` (36.8% of `9.5`)
- The UV (v) for 4 is `0.25` (67.6%), instead it should be `0.136` (36.8%)

**Comment by rparrett** [comment]
A previous instance of this bug was dependent on scale factor, and that seems to be the case here too.

Adding
```
.add_plugins(DefaultPlugins.set(WindowPlugin {
    primary_window: Some(Window {
        resolution: WindowResolution::default().with_scale_factor_override(1.),
        ..default()
    }),
    ..default()
}))
```
removed the squish.

**Comment by doup** [comment]
That "fixes" the issue… but it also scales everything to half the size. 😅 

I'm looking `/bevy_ui/src/render/mod.rs` and I have the hunch that the issue might be here:
https://github.com/bevyengine/bevy/blob/main/crates/bevy_ui/src/render/mod.rs#L492

The clipping should be affecting `atlas_extent`, no?

**Comment by mockersf** [comment]
this was fixed in https://github.com/bevyengine/bevy/pull/6351 and seems to have been removed

**Comment by mockersf** [comment]
I think fixing this for text broke it for images, then fixing it for image broke it back for text...

Be sure to test both when trying a new fix 👍

**Comment by doup** [comment]
I think overflow clipping is just broken, it only supports AABB positions clipping (not UVs). If a node is rotated/scaled inside an `Overflow::Hidden` node it gets funky. **To be fair, there is a comment mentioning that this is not supported.**

Without overflow:
![image](https://user-images.githubusercontent.com/188612/227150843-8d1ae99a-fedb-4575-9af1-d621ad7ec3be.png)

With overflow:
![image](https://user-images.githubusercontent.com/188612/227150542-40cefa81-7a5b-4860-b322-a5ff6809ae96.png)

**Comment by doup** [comment]
OK, I think I'm going to prepare an overflow clipping debug example.

**Comment by ickshonpe** [comment]
I think this was probably introduced when `scale_factor` was removed from `ExtractedUiNode`.
