### ISSUE TITLE
Add support for enum fields in the #[derive(States)

### ISSUE THREAD

**Issue by togetherwithasteria** [bevyengine/bevy#8187]
## What problem does this solve or what need does it fill?
For me, I'm developing a visual novel engine. I wrote a state for managing the navigation of the app. Since this engine focuses on extensibility, there needs a way for users to add their own state to work inside my state. In Rust, that's possible with type arguments and fields (`enum Foobar(T){ Foo, Bar(T), }`)

That's also how it was done in [Inox2d](https://docs.rs/inox2d/latest/inox2d/nodes/node_data/enum.InoxData.html). 

However, in the implementation of the States derive macro, [enum fields are not supported](       https://github.com/bevyengine/bevy/blob/4f16d6e0dc14c12ab29b72880d5d3d22003eed72/crates/bevy_ecs/macros/src/states.rs#LL12C15-L12C15).

## What solution would you like?
As described in issue title.

## What alternative(s) have you considered?
We can implement `States` manually, but won't that be tedious?

Or we can "flatten" the enums. So from:
```rs
pub enum Foo {
   Fieldless
   Bar(Bar)
}
pub enum Bar {
   Alice,
   Bob
}
```
to:
```rs
pub enum Foo {
 Fieldless,
 BarAlice,
 BarBob
}
```

But for adding states that we can't control (e.g. user-defined states), that won't be possible.

## Additional context
N/A

**Comment by benfrankel** [comment]
This is possible in bevy 0.13, so this can be closed.

**Comment by alice-i-cecile** [comment]
And this pattern will be much better supported in general with the upcoming computed and sub states support in 0.14.
