### ISSUE TITLE
It's surprising that using 'transitioning' to the same state triggers `OnEnter`

### ISSUE THREAD

**Issue by deifactor** [bevyengine/bevy#8191]
## Bevy version

0.10

## What you did

I was writing a system to transition to a "game over" state when the player's HP hit zero and one to show the UI on entering that state:

```rs

fn check_game_over(mut commands: Commands, query: Query<&HP, With<Player>>) {
    for hp in &query {
        if hp.0 <= 0 {
            commands.insert_resource(NextState(Some(GameState::GameOver)));
        }
    }
}

pub fn game_over_plugin(app: &mut App) {
    app.add_system(check_game_over)
        .add_system(show_game_over_screen.in_schedule(OnEnter(GameState::GameOver)));
}
```

## What went wrong

Since `NextState` triggers `OnEnter` schedules unconditionally, this code constantly generates UI nodes. I assumed that since `States: Eq`, bevy would compare the next state to the current state, see that they're the same, and just do nothing (similar to `DetectChangesMut::set_if_neq`).

**Comment by alice-i-cecile** [comment]
I'd like to see docs for this, and a set_if_neq method on NextState IMO

**Comment by hymm** [comment]
> a set_if_neq method on NextState IMO

Note that this would need to compare to the value in `Res<State<T>>`

**Comment by deifactor** [comment]
> > a set_if_neq method on NextState IMO
> 
> Note that this would need to compare to the value in `Res<State<T>>`

Wouldn't it be enough to just change `apply_state_transition`?

**Comment by alice-i-cecile** [comment]
>  I meant that the state transition logic should check this automatically.

Hmm. Maybe with the addition of the `Transition` schedules this is a safe default: users who want this behavior can add a self -> self schedule?

**Comment by deifactor** [comment]
> Maybe with the addition of the `Transition` schedules this is a safe default: users who want this behavior can add a self -> self schedule?

What are the use cases for wanting self -> self transitions to trigger things? I'm sure there are some, I just can't think of any. But I think it's reasonable to say "this is weird enough that you have to do something different".

**Comment by alice-i-cecile** [comment]
To me this is the standard "power cycle" pattern, where you reinitialize everything to reset the state :)
