### ISSUE TITLE
Hecs World currently allows for "unsafe" component access via immutable references

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#82]
This isn't actually a memory safety problem because hecs also has runtime safety checks, but in some contexts it is useful to provide "immutable only" world references. For example, render graph nodes currently receive an `&World` reference, which was intended to be an immutable-only reference. Graph nodes are scheduled to run in parallel based on graph dependencies, so mutable access to components could cause undefined behavior. With legion &World was truly immutable. Which hecs, &World is "mutable with runtime safety checks".

To fix this i think we have two choices:
 
* modify World to label unsafe access as _literally_ "unsafe" 
* add an `ImmutableWorld` wrapper that only allows read actions

**Comment by Ratysz** [comment]
For what it's worth, I opted for a [wrapper](https://github.com/Ratysz/yaks/blob/master/src/system_context.rs#L12) to solve a similar problem in `yaks` (I wanted to disallow doing anything that would break invariants the executor assumes within a system).

**Comment by DJMcNab** [comment]
I think this is fixed now (in #504?). We ended up taking approach 1.

**Comment by cart** [comment]
Yeah now that we rely on lifetimes in "safe" code to protect storage access, we can close this. Thanks for the follow up!
