### ISSUE TITLE
thread 'Compute Task Pool (0)' panicked at 'index out of bounds: the len is 0 but the index is 0', 

### ISSUE THREAD

**Issue by stanley355** [bevyengine/bevy#8210]
## Bevy version
0.10.0

## \[Optional\] Relevant system information
- the Rust version you're using (you can get this by running `cargo --version`)
1.68.1

- the operating system or browser used, including its version
Endeavour OS

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```
thread 'Compute Task Pool (0)' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/stanley/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_sprite-0.10.0/src/render/mod.rs:399:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (0)' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/stanley/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.0/src/schedule/executor/multi_threaded.rs:459:45
```

## What you did
1. I'm building a simple bevy component on initial main.rs
```
#[derive(Debug, Component)]
struct Player;

pub fn setup_player(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    mut texture_atlas_res: ResMut<Assets<TextureAtlas>>,
) {
    let player_sprites: Handle<Image> = asset_server.load("player_sprites.png");
    let texture_atlas = TextureAtlas::new_empty(player_sprites, Vec2::new(0.0, 0.0));
    let texture_atlas_handle = texture_atlas_res.add(texture_atlas);

    commands.spawn(SpriteSheetBundle {
        texture_atlas: texture_atlas_handle,
        ..default()
    });
}
```

2. The cargo run works fine, then as the sprite doesn't show, I tried to add the camera bundle
```
fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugin(WorldInspectorPlugin::new())
        .add_startup_system(camera_setup)
        .add_system(player::setup_player)
        .run();
}

fn camera_setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
}
```

## What went wrong
- It shows up these error on my terminal, I tried building on this OS with bevy 0.8 and it works fine before
- The issue only shows after I add the camera setup, if I turned off the camera or component setup it works fine, but if I run it altogether it shows the below error.
```
thread 'Compute Task Pool (0)' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/stanley/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_sprite-0.10.0/src/render/mod.rs:399:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (0)' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/stanley/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.0/src/schedule/executor/multi_threaded.rs:459:45
```

Does anybody have similar eeror?

**Comment by mockersf** [comment]
[`TextureAtlas::new_empty`](https://docs.rs/bevy/latest/bevy/sprite/struct.TextureAtlas.html#method.new_empty) probably doesn't do what you would want it to, could you try using [`TextureAtlas::from_grid`](https://docs.rs/bevy/latest/bevy/sprite/struct.TextureAtlas.html#method.from_grid) ?

**Comment by alice-i-cecile** [comment]
We should have nicer error reporting for `TextureAtlas::new_empty`; that's not a very helpful error message.

**Comment by stanley355** [comment]
@mockersf works, thanks! Can we have better error message for that?
