### ISSUE TITLE
max_size from the flexbox layout not working ?

### ISSUE THREAD

**Issue by gwafotapa** [bevyengine/bevy#8221]
## Bevy version

0.10.0

## What you did

I'm using Bevy ui but cannot get it to render how I want it to. More specifically, the fields `flex_basis`, `flex_grow` and `max_size` don't seem to matter. Here's a minimal working example of part of the problem :

```
use bevy::prelude::*;

pub fn spawn_camera(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
}

pub fn spawn_ui(mut commands: Commands, asset_server: Res<AssetServer>) {
    let texture = asset_server.load("bevy_logo.png");
    commands.spawn(ImageBundle {
        style: Style {
            max_size: Size::width(Val::Px(200.0)),
            ..default()
        },
        image: UiImage::new(texture.into()),
        ..default()
    });
}

fn main() {
    App::new()
        .insert_resource(ClearColor(Color::rgb(0., 0., 0.)))
        .add_plugins(DefaultPlugins)
        .add_startup_system(spawn_camera)
        .add_startup_system(spawn_ui)
        .run();
}

```

## What went wrong

Setting `max_size` has no impact on rendering whereas if I replace it with `size`, the image is shrinked accordingly.
I thought `size` was not supposed to exceed `max_size` which the doc specifies. Or maybe I am missing something about the way flexbox operates ?

**Comment by rparrett** [comment]
Thanks for the report.

This is #7946. A fix should be included in an upcoming minor release in the next week or so.
