### ISSUE TITLE
Loading an asset that has been planned for removal does not clear the removed event.

### ISSUE THREAD

**Issue by Bobox214** [bevyengine/bevy#824]
**Bevy version**

v0.3.0 

**Operating system & version**

Ubuntu 20.04

**What you did**

I have migrated Kataster to bevy 0.3.0 ( https://github.com/Bobox214/Kataster ).
The HEAD compile and runs but show a regression in UI behaviour.

I have a start screen with 2 Text components.
On pressing enter:
a. On first frame, the two UI Text of the start screen are despawned.
b. On the second frame, the UI Text for the Score is added.

The three UI Text are using the same font.

**What you expected to happen**

The Score Text should be shown

**What actually happened**

The Score text is only shown for one or two frames then disappear.

**Additional information**

The Score UI is no more shown because the font is being removed from the Assets<Font>.

As far as I have been able to debug :
- The removal of the 2 UI Text, decrease the font handle refCount to 0, this triggers an AssetEvent::Removed for the font.
- The addition of the score UI Text, does not do anything because the font is still present in the assets. ( goes into the if branch of // if asset is already loaded (or is loading), don't load again )
- The effective handling of the AssetEvent::Removed happens after the score UI Text addition, and effectively remove the font used by the Score UI.

**Comment by Bobox214** [comment]
No sure how to fix that.

In the asset_server, I don't think we can have access to the Events<Assets<T>> to check for already planed for removal assets and trigger a 'force'.
In the Assets<T> , when handling the Removed event, we don't have access to the ref_counts to double check the Handle is still ref_count 0.

If somebody can give me the appropriate direction to handle this issue, I am eager to try to  implement it.

**Comment by memoryruins** [comment]
Thanks for reporting! Perhaps its worth making a branch on Kataster specific to this issue so that it preserves the behavior you ran into. I'll mention the most recent commit for posterity: https://github.com/Bobox214/Kataster/commit/98bafc306848c13cce592970439501afc4ad4013

---

Something that could avoid this behavior in Kataster today is storing a strong handle to the font in a longer living resource. Since the UI is always using the same font, the resource can be re-used in all the systems that need it. This would avoid loading the asset more than once, and would allow weak handles to be used by all UI elements since it's never removed.

<details>

<summary>example</summary>


```rust

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .init_resource::<GameFonts>()
        .add_system(system.system())
        .run()
}

struct GameFonts {
    primary: Handle<Font>,
}

impl FromResources for GameFonts {
    fn from_resources(resources: &Resources) -> Self {
        let assets = resources.get::<AssetServer>().unwrap();
        GameFonts { primary: assets.load("kenvector_future.ttf") }
    }
}

fn system(game_fonts: Res<GameFonts>) {
    // ... game_fonts.primary.clone() ...
    // ... game_fonts.primary.clone_weak() ...
}
```

</details>

**Comment by Bobox214** [comment]
Good idea effectively, I have created the following branch that allow to reproduce the described issue :
https://github.com/Bobox214/Kataster/tree/bevy_issue_824

Effectively, Kataster does not try to optimize assets handles, like for the laser sprite I re-get the handle from the path each new entity creation ....
I probably should do it as multiple people are taking this project as a starting point, so better provide a good one :)
