### ISSUE TITLE
Window never opens when using `Reactive` or `ReactiveLowPower` on Wayland

### ISSUE THREAD

**Issue by obj-obj** [bevyengine/bevy#8259]
## Bevy version

0.10

## What you did

Tried to enable `ReactiveLowPower` on Wayland

## What went wrong

The window never opened (but did open fine when disabling wayland support)

## Additional information

This could be a Winit issue rather than a Bevy one

**Comment by obj-obj** [comment]
It seems that at least one frame needs to be sent for the window to open, as if I change `max_wait` to 1 second, the window opens after 1 second

**Comment by james7132** [comment]
Seems related to, if not a duplicate of, #7974.

**Comment by obj-obj** [comment]
> Seems related to, if not a duplicate of, #7974.

Yeah, if the default desktop_app settings has a long `max_wait` then it could be the same thing

**Comment by obj-obj** [comment]
Tested it and it seems to be the same problem as #7974 on default settings, closing this issue as it's a duplicate
