### ISSUE TITLE
To make a Blender addon that treats it like a game engine

### ISSUE THREAD

**Issue by Joe23232** [bevyengine/bevy#828]
Like the game engine Armory, it would be nice if there was an extension that can be installed that will turn Blender into a full fledged game engine that utilities Bevy.

**Comment by cart** [comment]
I think you might be interested in @zicklag's [Arsenal](https://github.com/katharostech/arsenal) project :smile: 

I'm closing this out because its not a goal for the official Bevy project, but we're definitely willing to collaborate with other projects that want to build on top of us.

**Comment by Joe23232** [comment]
> I think you might be interested in @zicklag's Arsenal project 😄

He killed the project off mate, that is why I was suggesting it over here.

**Comment by cart** [comment]
Hmm when did that happen? I haven't seen/heard anything that indicates that. They posted a blog post with updates 7 days ago.

https://katharostech.com/post/arsenal-development-week-4-lock-free-dynamic-queries

Haha @zicklag did you cancel since then?

**Comment by Joe23232** [comment]
> Hmm when did that happen? I haven't seen/heard anything that indicates that. They posted a blog post with updates 7 days ago.

He just told me today in his email that they canceled the development mate :(

**Comment by cart** [comment]
Well thats too bad. Direct blender integration isn't a goal for us at the moment, but others are welcome to pick up the torch.

**Comment by Joe23232** [comment]
I see.
