### ISSUE TITLE
Inefficient use of Vec::push in prepare_uniform_components function

### ISSUE THREAD

**Issue by CrazyRoka** [bevyengine/bevy#8284]
I created a stress test scenario with the Bevy engine ([link](https://github.com/CrazyRoka/bevy-multiple-objects-performance-test)) where I created 100K entities. I noticed that the `prepare_uniform_components` function was using 4.23% of the CPU time, and upon investigating the code, I found that the `Vec3::push` method was being called for each of the entities, which is not efficient.

To improve performance, I suggest copying all the objects in batches instead of pushing them one by one. Apart from that, `DynamicUniformBuffer::write` can be optimized as well. I am attaching my Flamegraph to this issue.

https://github.com/bevyengine/bevy/blob/aefe1f0739bb395d2454e05a1a812acab767892c/crates/bevy_render/src/extract_component.rs#L126-L153

![Screenshot from 2023-04-01 17-06-22](https://user-images.githubusercontent.com/19844144/229302214-9da60480-c7a1-47a5-b391-606c443010af.png)

**Comment by JMS55** [comment]
You may be interested in weighing in on https://github.com/bevyengine/bevy/pull/8204

**Comment by james7132** [comment]
@CrazyRoka turns out the `values` Vec is basically unused. #8299 removes it. As for the performance issues with `encase`, I strongly suggest making a PR upstream to address it. The flamegraph you provided definitely shows there's some non-trivial overhead when using it.

**Comment by CrazyRoka** [comment]
@james7132 Thank you for your PR to improve Bevy performance. I have 2 more questions:
1. How did you measure performance improvements in your PR?
2. Can we replace `component_uniforms.uniforms.push(component.clone())` with batch write? I was diving deeper into the implementation and it looks like each `push` call creates `Writer Cursor`, writes and closes this complex object. I think it will make a difference to open `WriteCursor` once and write all the components together.

**Comment by james7132** [comment]
> 1. How did you measure performance improvements in your PR?

I used Tracy and the `trace_tracy` feature. You can find the docs on how to use it under `docs/profiling.md` in the repo.

> 2. Can we replace `component_uniforms.uniforms.push(component.clone())` with batch write? I was diving deeper into the implementation and it looks like each `push` call creates `Writer Cursor`, writes and closes this complex object. I think it will make a difference to open `WriteCursor` once and write all the components together.

Batch insertion probably is for the best here. We need to construct both the buffer and the Vec for Commands, and preallocating then skipping the capacity checks likely will have a significant speedup. Though with that said, with dynamic uniform offsets being pessimistically aligned to 256 bytes, we might not see much gain there.
