### ISSUE TITLE
Replace `once_cell` with std lib's implementation

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#8303]
`OnceCell` is set to be partially stabilized in Rust 1.70. (https://github.com/rust-lang/rust/pull/105587).

If it releases as a part of Rust 1.70,  it may be possible to replace the `once_cell` dependency within Bevy's crates with the stdlib's implementation.

**Comment by hymm** [comment]
this was at least partially completed with https://github.com/bevyengine/bevy/pull/8739

**Comment by mockersf** [comment]
Remaining are [`Lazy`](https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html) and [`OnceBox`](https://docs.rs/once_cell/latest/once_cell/race/struct.OnceBox.html) that are not stabilised yet
