### ISSUE TITLE
Official WebGPU Support

### ISSUE THREAD

**Issue by simbleau** [bevyengine/bevy#8315]
## What problem does this solve or what need does it fill?

WebGPU is now shipping on major platforms, like stable Chrome, as of April 6th 2023.
https://developer.chrome.com/blog/webgpu-release/

It's important that Bevy begins to officially support WebGPU, since it is now stable on the browser with > 60% of the browser market. Firefox and Safari will soon follow suit (Firefox sooner). 

Currently, Bevy only supports WebGL as a backend, and that's a problem. Major performance benefits can be gained with WebGPU and there's no reason we can't change the backend-bit and fallback to WebGL (the only current backend for Bevy). 

## What solution would you like?

Attempt to use WebGPU on WASM, and fallback to WebGL (the only backend-bit Bevy uses currently).

## Additional context

This seems uncontroversial for the team, as I've seen previous conversations by members such as @mockersf stating that WebGPU support should be tackled when the browsers actually roll out WebGPU stable. Now is that time.

**Comment by mockersf** [comment]
Definitely something we want! I opened a first proposition a few months ago: https://github.com/bevyengine/bevy/pull/5027

I'll try to finish another proposition I have for Bevy 0.10... soon.

To note, it's unlikely Bevy will support a builtin fallback to WebGL2, but it's possible to build both version and decide in JS which to load.

**Comment by daxpedda** [comment]
Related: https://github.com/gfx-rs/wgpu/issues/2804.
