### ISSUE TITLE
error: multiple packages link to native library `alsa`, but a native library can be linked only once

### ISSUE THREAD

**Issue by marko-lazic** [bevyengine/bevy#833]
After changing all of my modules from 0.2.1 to 0.3.0 I get this error:
error: multiple packages link to native library `alsa`, but a native library can be linked only once

> package `alsa-sys v0.1.2`
>     ... which is depended on by `cpal v0.11.0`
>     ... which is depended on by `rodio v0.11.0`
>     ... which is depended on by `bevy_audio v0.2.1`
>     ... which is depended on by `bevy v0.2.1`
>     ... which is depended on by `bevy_prototype_input_map v0.1.4`
>     ... which is depended on by `corp-input v0.1.0 (/home/marko/projekti/corp_one_bevy_game/crates/corp-input)`
>     ... which is depended on by `corp_one_bevy_game v0.1.0 (/home/marko/projekti/corp_one_bevy_game)`
> links to native library `alsa`
> 
> package `alsa-sys v0.3.0`
>     ... which is depended on by `alsa v0.4.3`
>     ... which is depended on by `cpal v0.13.1`
>     ... which is depended on by `rodio v0.13.0`
>     ... which is depended on by `bevy_audio v0.3.0`
>     ... which is depended on by `bevy v0.3.0`
>     ... which is depended on by `corp-console v0.1.0 (/home/marko/projekti/corp_one_bevy_game/crates/corp-console)`
>     ... which is depended on by `corp_one_bevy_game v0.1.0 (/home/marko/projekti/corp_one_bevy_game)`
> also links to native library `alsa`
> 

Probably not a bug but something changed but i couldn't find what.

**Comment by memoryruins** [comment]
```
... which is depended on by bevy v0.2.1
... which is depended on by bevy_prototype_input_map v0.1.4
```
https://crates.io/crates/bevy_prototype_input_map hasn't updated to `bevy 0.3.0` yet so it is pulling in `bevy 0.2.1` still.

**Comment by marko-lazic** [comment]
Well spotted
