### ISSUE TITLE
Extensible `StandardMaterial`

### ISSUE THREAD

**Issue by paulkre** [bevyengine/bevy#8345]
When creating custom shaders, I've frequently noticed that it would technically make sense to use the shader of the `StandardMaterial` as a base. AFAIK this is currently not really possible, because you can't replace the WGSL code of a material with custom code and you can't modify its `RenderCommand` to add custom bind groups either. The only way I found is to copy the entire code of the standard material ([bevy/crates/bevy_pbr/src/pbr_material.rs](https://github.com/bevyengine/bevy/blob/v0.10.1/crates/bevy_pbr/src/pbr_material.rs)) and then make alterations to it. This solution can not easily be maintained though.

Are there any plans to make materials more extensible/modular in the future?

**Comment by nicopap** [comment]
You might be interested in reviewing the following PR. I also find it frustrating and error-prone to copy/paste the bevy standard material (which is currently the only way to extend the PBR shader)

- https://github.com/bevyengine/bevy/pull/7820

**Comment by paulkre** [comment]
Thanks for the quick reply @nicopap. Good to see work is already being done in this area.

**Comment by nicopap** [comment]
Completed in #7820
