### ISSUE TITLE
Bevy Book 2.3. ecs fails to build

### ISSUE THREAD

**Issue by Wesxdz** [bevyengine/bevy#835]
**Bevy version**
Using latest commit as dependency with Nightly Rust Compiler
bevy = {git = "https://github.com/bevyengine/bevy", rev = "60fa2d5f9300db7c0819481cd5550ed9557c8e6b"}

Working through https://bevyengine.org/learn/book/getting-started/ecs/

no method named `system` found for fn item `fn(bevy::prelude::Commands) {add_people}` in the current scope

method not found in `fn(bevy::prelude::Commands) {add_people}`

note: `add_people` is a function, perhaps you wish to call it

**Comment by cart** [comment]
Yeah we made some breaking changes on the bevy master branch. The book is currently tailored to the latest crates.io release, not the latest master commit.

Eventually I think it makes sense to have an "unstable" book for the master branch and a "stable" book for the latest crates.io release, but we don't have that process yet.

**Comment by alice-i-cecile** [comment]
This looks to be fixed now :)

**Comment by MarTango** [comment]
@alice-i-cecile What's the fix? Using bevy 0.3.0, I'm having the same issue.
