### ISSUE TITLE
Directional lights are 4800x dimmer than point lights and spot lights 

### ISSUE THREAD

**Issue by fintelia** [bevyengine/bevy#8369]
## Bevy version

2ec38d146 (but also happens on 0.10.x and probably others).

## What you did

Delete the environment map lighting from the PBR example, then compare point light and directional light strengths.

The point light is `sqrt(50^2 + 50^2 + 50^2) ≈ 86 meters` from the origin and has a strength of 600K lumens. Which means `600,000 / (4 * PI * 86^2) ≈ 6.5 lux` reaching the origin.

### Point light
![image](https://user-images.githubusercontent.com/4943209/231623213-95b5d9c7-1b6f-421c-932b-75f813e6808d.png)

### Same strength directional light
```rust
commands.spawn(DirectionalLightBundle {
    transform: Transform::from_xyz(50.0, 50.0, 50.0).looking_at(Vec3::ZERO, Vec3::Y),
    directional_light: DirectionalLight {
        illuminance: 6.5,
        ..default()
    },
    ..default()
});
```
![image](https://user-images.githubusercontent.com/4943209/231620994-2e9f6427-410a-47ce-ba62-eea14c4530c6.png)

### 4800x scaled directional light
```rust
commands.spawn(DirectionalLightBundle {
    transform: Transform::from_xyz(50.0, 50.0, 50.0).looking_at(Vec3::ZERO, Vec3::Y),
    directional_light: DirectionalLight {
        illuminance: 6.5 * 4800.0,
        ..default()
    },
    ..default()
});
```
![image](https://user-images.githubusercontent.com/4943209/231622225-a11de4e5-8cfa-48e0-9047-78bcec84cd5c.png)

## Additional information

The bug is caused by this code which dims the strengths of directional lights by 4800x, but leaves point lights and spotlights unchanged:
https://github.com/bevyengine/bevy/blob/2ec38d1467c0f5f6de70fc28120dd6302806dfa0/crates/bevy_pbr/src/render/light.rs#L857-L867

**Comment by alice-i-cecile** [comment]
This will be a silly migration. Better to fix it up sooner than later.

**Comment by benny-n** [comment]
Hi, I'd like to take this one, if possible. I think I have a rough idea of what to change to solve it.  
Let me know if there's anything else I should know before getting started.

**Comment by CptPotato** [comment]
I think this is because of a fundamental difference between point/spot lights (which have a spatial position and a `1/d²` falloff) and directional lights that are infinitely far away and have no distance attenuation.

With spot and point lights you can assign them a value like `1500 lumens` that corresponds to the amount of light emitted which does not work for directional lights (they're using illuminance (lux), I think). So you're essentially using completely different units for these types of lights.

If I remember correctly the PBR implementations somewhat follows the Filament docs. There is some more information on light units [there](https://google.github.io/filament/Filament.html#lighting/units).

That being said, maybe one of the people who worked on the PBR implementation can chime in and confirm that the current behavior is correct.

**Comment by fintelia** [comment]
This is not caused by the inverse square falloff. In my post, I use the amount of light emitted by the point light together with the distance to calculate the amount of light received at the origin. Then I construct a directional light produces the same illuminance.

Rather, this is caused by not following the Filament docs. Specifically, section 5.2.6 says that you have to pre-expose both directional _and_ point/spot lights but Bevy is only pre-exposing directional lights while forgetting to do the same for point/spot lights.

**Comment by superdump** [comment]
It seems like we could implement a quick fix that uses hard-coded exposure settings, but also that using per-camera defined exposure settings should be pretty straightforward to implement anyway?

**Comment by fintelia** [comment]
There's currently `Camera3dBundle::color_grading::exposure`, but that's an exposure value _offset_ which means that it is intended to be subtracted from the calculated automatic exposure. The main problem with using it as a fixed exposure setting directly is that it is negated (if you want a scene ev=15, then you'd set exposure=-15)

**Comment by superdump** [comment]
I made a draft PR that I think does what is suggested, but it makes everything look very dark. There's a lot of information in the filament docs and I need to read it more carefully. I noticed that only part of all the maths is being used and I didn't have time today to understand it. If you see errors, please point them out and I'll fix them ASAP.

**Comment by benny-n** [comment]
Umm I guess I should close #8378 in favor of #8407 ?

**Comment by alice-i-cecile** [comment]
Agreed, I think that's the right way forward. Thanks for looking into this!
