### ISSUE TITLE
Add Commands::insert_batch

### ISSUE THREAD

**Issue by wzjsun** [bevyengine/bevy#8384]
## What problem does this solve or what need does it fill?
Creating multiple entities of the same prototype in the system is a very common requirement, and existing Commands::spawn_batch can create entities in bulk and achieve efficient insertion, but this interface cannot return the Enity I have already created. If I need these entities, I have adopted the following method:

```rust
let mut entity_ list = Vec::new();

let mut bundle_ list= Vec::new();
for _ in 0..100 {
  let entity = commands.spawn_ empty();
  entity_ list.push(entity);
  bundle_ list.push((entity, Bundle))
}
commands.insert_ or_ spawn_ batch(bundle_list.into_iter());
```

But I encountered a very serious performance issue, some entities may need to check if they are in pending , and this inspection will go through an iterative process, and the code snippet is:

```rust
else if let Some(index) = self.pending.iter().position(|item| *item == entity.index) {
  self.pending.swap_ remove(index);
  let new_ free_ cursor = self.pending.len() as IdCursor;
  *self.free_ cursor.get_ mut() = new_ free_ cursor;
  self.len += 1;
  AllocAtWithoutReplacement::DidNotExist
}
```

This approach is slower than inserting one at a time

## What solution would you like?

Add Commands::insert_batch, but do not check if each entity is in pending, panic If the entity does not exist.

**Comment by Connor-McMillin** [comment]
I see there is also `World::insert_or_spawn_batch`, should a similar thing be done there?

**Comment by Connor-McMillin** [comment]
I made a draft PR that I think addresses the issue. @wzjsun or @nicopap let me know if this solution is in line with what you're expecting

**Comment by wzjsun** [comment]
Thank you for reaching out. I'm pleased to inform you that my requirements have been met. I greatly appreciate the effort you have put into addressing this issue.

**Comment by wzjsun** [comment]
@Connor-McMillin Thank you for reaching out. I'm pleased to inform you that my requirements have been met. I greatly appreciate the effort you have put into addressing this issue.
