### ISSUE TITLE
Physically Based Rendering (PBR)

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#84]
Bevy should have PBR shaders, probably based on the Filament docs: https://google.github.io/filament/Filament.html

**Comment by aclysma** [comment]
Not sure how helpful it is, but I had some resources and mini-roadmap in my own renderer here: https://github.com/aclysma/engine_prototype/issues/8

Happy to be a resource or sounding board if you think it will be helpful - I just went through the process of implementing this myself on top of ash/vulkan. :)

**Comment by RedlineTriad** [comment]
I think this can be closed since it is listed as one of the new features in https://bevyengine.org/news/bevy-0-5/#physically-based-rendering-pbr.

**Comment by alice-i-cecile** [comment]
I agree: we have basic functionality now, and further work is better organized in more specific issues.
