### ISSUE TITLE
`Window` fields doc should go beyond "window creation" assumption.

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#8433]
## How can Bevy's documentation be improved?

Reading [the `Window` doc](https://docs.rs/bevy/latest/bevy/prelude/struct.Window.html) one thinks the fields are only used when _creating_ windows. But it's far from the truth. Bevy tracks window states and reflect them in the relevant `Window` components. The current docs are misleading and should be updated to make readers understand that they can read back from `Window` to check for current state.

**Comment by waywardmonkeys** [comment]
I think this was done in f7ea93a7cf / #8858.

**Comment by nicopap** [comment]
@waywardmonkeys Indeed! Nice catch, thank you for bringing it up, it's always nice to be able to close an issue!
