### ISSUE TITLE
Document `#[system_set(base)]`

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#8439]
I had to add `#[system_set(base)]` to an enum that derives `SystemSet` to make it build. I have zero idea why, nor what `#[system_set(base)]` does. I just found that my app builds with it and doesn't without. This was a very wild guess; I just saw that line in some Bevy code and tried it because my sets are inserted between built-in sets so they might be somehow related to some "base" thing. Maybe?

**Comment by alice-i-cecile** [comment]
Basw sets are removed in 0.11.
