### ISSUE TITLE
Entities without `Aabb` component do not cast shadow

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#8442]
## Bevy version

0.10.1, 0174d632a56964494a5edfaf3612b8dc0b2c9a44

* **What I did**: Add the `NoFrustrumCulling` component to the cube entity in the `lighting.rs` example
* **What happen**: The cube doesn't cast a shadow anymore.
* **Why**: Because `NoFrustrumCulling` prevents the addition of the `Aabb` component, and apparently this causes the lighting system to ignore the cube as a shadow caster.

**Comment by IceSentry** [comment]
> NoFrustrumCulling prevents the addition of the Aabb component

That's an interesting find, I wonder why this happens. Does NoFrustumCulling _remove_ the Aabb?
