### ISSUE TITLE
Reflect for AssetPath

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#8458]
## What problem does this solve or what need does it fill?

`AssetPath` does not implement reflect, so I can't send it over the network. I can only send a regular string with `#` to separate label from the path, but it's not very convenient.

## What solution would you like?

Add `Reflect` and `FromReflect` impls for `AssetPath`.

**Comment by MrGVSV** [comment]
Note: We'll only be able to reflect `AssetPath<'static>` due to the [lifetime requirements](https://docs.rs/bevy_reflect/latest/bevy_reflect/index.html#requirements), but this should be a straightforward derive.

**Comment by minchopaskal** [comment]
How would one use the derive macro for the `'static` lifetime only? Isn't it required for `Reflect` to be manually implemented for `AssetPath<'static>`?
