### ISSUE TITLE
Camera culls 3D model too early

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#8461]
## Bevy version

0.10.1

## What you did

I downloaded character model from Mixamo in FBX format and re-exported it to GLTF using Blender. I spawned a model and move my camera closer to it.

## What went wrong

The model looks okay, but it disappears even if the camera is farther away than the default `near` in projection settings (10 cm).

## Additional information

Looks like happens only with this model. Other models that I create in Blender works just fine.
Minimal project to reproduce: [bevy_camera_bug.zip](https://github.com/bevyengine/bevy/files/11301601/bevy_camera_bug.zip)
Screenshots:
![изображение](https://user-images.githubusercontent.com/22453358/233791945-646c2d3e-bfda-463a-9ec8-3f05dc45a454.png)
![изображение](https://user-images.githubusercontent.com/22453358/233791950-f6ec8888-3812-49d0-8b05-d3701ca4b618.png)

**Comment by nicopap** [comment]
I think I found the issue. The model is weirdly backed. Try deleting the skeleton in blender and see that the "original" model is actually a very different shape than the T-pose.

Due to #4971, the bounding box is incorrect, and bevy's culling acts weird.

**Comment by alice-i-cecile** [comment]
I think this is a duplicarte of #4971, which is easier to understand and address.

**Comment by Shatur** [comment]
Thanks, you are right closing as a duplicate.
