### ISSUE TITLE
Alpha mask transparency discarded when enabling prepass.

### ISSUE THREAD

**Issue by awowogei** [bevyengine/bevy#8464]
## Bevy version

d8102a0

## \[Optional\] Relevant system information

```ignore
`AdapterInfo { name: "AMD Radeon RX 6800 XT (RADV NAVI21)", vendor: 4098, device: 29631, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 23.0.2", backend: Vulkan`
```

## What you did

Tried to render transparent textures through a custom material with alpha mask and specified vertex layout buffer, depth prepass enabled. 

## What went wrong

The transparent parts are discarded.

## Additional information

I have tracked this down to the prepass mesh shader. The uv is at location 1 and normal at 2 which is opposite of what it is in main shader. Swap them and it works. I assume it has to do with specifying the vertex layout also overwrites the layout for the prepass.
I did test by copying the standardmaterial to debug, but you can see [here](https://github.com/awowogei/fmc/blob/master/client/src/rendering/materials/block_material.rs) for a material that does it. Change locations [here](https://github.com/awowogei/fmc/blob/master/client/src/rendering/shaders/mesh_prepass.wgsl#L10) to reproduce. 
![image](https://user-images.githubusercontent.com/125923016/233803268-9c695f20-ee1f-4bef-9049-3b4c8abd7f56.png)

**Comment by IceSentry** [comment]
After some discussions on discord, this isn't exactly a bevy bug. Specializing the vertex layout combined with using the prepass is a known limitation of the current approach. The fix can be done user side, but there should be better documentation around this.
