### ISSUE TITLE
`collide_aabb` docs are incorrect

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#8465]
I think the docs should be updated and the `collide` method should be left as it was.
Currently on this PR, the breakout ball behaves incorrectly when it hits a corner of a block or the paddle.

_Originally posted by @devil-ira in https://github.com/bevyengine/bevy/issues/8356#issuecomment-1503861847_
            
See the linked PR for details.

**Comment by wpederzoli** [comment]
Hey @alice-i-cecile I've been following Bevy for some time now and I would like to start contributing to it as well with what I can. I think this is a good place to start :) So, is it alright if I pick up this ticket?

**Comment by RaminKav** [comment]
seems like this was fixed in the linked PR? should this issue be closed?
