### ISSUE TITLE
Warning when adding multiple systems with the same `in_schedule` condition

### ISSUE THREAD

**Issue by Lukastos** [bevyengine/bevy#8469]
## Bevy version

0.10

## What you did
I have a code like that:
```rust
.add_system(setup_game_over_screen.in_schedule(OnEnter(GameState::GameOver)))
.add_system(game_over_clear.in_schedule(OnEnter(GameState::GameOver)))
```

## What went wrong

It produces a warning:
```
2023-04-22T22:07:49.019366Z  WARN bevy_ecs::schedule::schedule: schedule with label OnEnter(GameOver) already exists
```

I would expected that we could add multiple system triggering on the same `in_schedule` condition.

**Comment by alice-i-cecile** [comment]
Before tackling this, make sure it's reproducible on `main`. Should be simple enough to follow the logic back and see where the warning is coming from.

**Comment by 2ne1ugly** [comment]
I don't get any warnings in the new schedule system
```rust
use bevy::prelude::*;

#[derive(Clone, Debug, Default, Eq, Hash, PartialEq, States)]
pub enum GameState {
    #[default]
    GameOver,
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(OnEnter(GameState::GameOver), setup_game_over_screen)
        .add_systems(OnEnter(GameState::GameOver), game_over_clear)
        .run();
}

fn setup_game_over_screen() {}

fn game_over_clear() {}
```

Interestingly I don't get any errors in 0.10 either
```rust
use bevy::prelude::*;

#[derive(Clone, Debug, Default, Eq, Hash, PartialEq, States)]
pub enum GameState {
    #[default]
    GameOver,
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_state::<GameState>()
        .add_system(setup_game_over_screen.in_schedule(OnEnter(GameState::GameOver)))
        .add_system(game_over_clear.in_schedule(OnEnter(GameState::GameOver)))
        .run();
}

fn setup_game_over_screen() {}

fn game_over_clear() {}
```

What may have happened is that you might have added the State twice in some parts of your code
```rust
    App::new()
        .add_plugins(DefaultPlugins)
        .add_state::<GameState>()
        .add_state::<GameState>()
```
Can you write a minimal example for this bug?

**Comment by Lukastos** [comment]
Sorry, I put that late yesterday.

> What may have happened is that you might have added the State twice in some parts of your code
> 
> ```rust
>     App::new()
>         .add_plugins(DefaultPlugins)
>         .add_state::<GameState>()
>         .add_state::<GameState>()
> ```

Yeah...that's definitely what happened. Sorry for the inconvenience.

**Comment by 2ne1ugly** [comment]
No problem! Glad that it helped.
