### ISSUE TITLE
Unexpected behavior for Resource<>.is_changed()

### ISSUE THREAD

**Issue by meanbeanmachine** [bevyengine/bevy#8472]
## Bevy version

0.10.1

## What you did

Used Resource<>.is_changed() to detect a change to a Resource

## What went wrong

.is_changed() keeps firing whenever I init my Resources, which results in an false-positive when my app starts.  The info text for .is_changed() states:

> Returns true if this value was added or mutably dereferenced after the system last ran.

So, OK, the method is working as intended, since I did add a resource.  Since the text states "**AFTER** the system last ran", I figured I could avoid this false-positive by adding my resources during a previous state before my systems even ran once.

I create a state enum with two variants: Init, Done.  The app is initialized in 'Init' state, which is where I add my resources.  I then change to 'Done' state, which is where my systems monitoring the resources are: OnUpdate(State::Done).

Well, guess what, as soon as I change to Done state, my systems are still detecting the Resource as added/changed, even though the systems never ran a single time before the Resource was added.  To me, this means either:
- The info text is not accurate and needs to be updated, since my system wasn't running before the Resource was added
- the method is bugged and is not ignoring resource adds/changes that occurred before the system ever ran the first time

I hope that this is a bug because it's annoying getting the false-positive when your app starts and resources are initialized.  As a redneck solution to avoid this false-positive, I created a Local<bool> to test if this is the first time the event has fired, and if so, ignore it and update the bool to true.

**Comment by alice-i-cecile** [comment]
Try using `resource.is_changed() && !resource.is_added()`. This isn't a bug, but the docs are not sufficiently clear.

**Comment by nicopap** [comment]
What would be a good alternative wording?

> (1) Returns false if this value wasn't touched since the last time the system ran

> (2) Returns true if this value was added or mutably dereferenced either since the last time the system ran or, if the system never ran, since the beginning of the program.

> (3) Returns true if this value was added or mutably dereferenced after the last time the system ran or the beginning of the program if the system never ran.

(1) is confusing even if technically true and a lot shorter.

(3) is confusing because the sentence is too complex and difficult to parse.

I like (2) best: it describes in its entirety the behavior, but is verbose. I did my best to avoid ambiguity, by replacing "after" by "since" and repeating "since" in the two clauses, and using commas.
