### ISSUE TITLE
Examples crash when using `--features debug_asset_server`

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#8484]
**bevy version**: main a1e442cd
**what I do**: run any bevy example with `cargo run --features debug_asset_server --example 3d_scene`
**what happens**: a panic at startup with:

```
thread 'main' panicked at 'Resource requested by
(ResMut<debug_asset_server::HandleMap<Font>>, Res<AssetServer>) does not exist:
debug_asset_server::HandleMap<Font>',
./bevy/crates/bevy_ecs/src/system/system_param.rs:545:17
```

**Comment by superdump** [comment]
Do you feel like bisecting? I was using debug_asset_server just the other day and it was fine…

**Comment by nicopap** [comment]
Good idea. I'll do this right now
