### ISSUE TITLE
Rename View matrices in the form world_to_view, etc

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#8492]
Currently, the View uniform looks like this:
```rust
struct View {
    view_proj: mat4x4<f32>,
    unjittered_view_proj: mat4x4<f32>,
    inverse_view_proj: mat4x4<f32>,
    view: mat4x4<f32>,
    inverse_view: mat4x4<f32>,
    projection: mat4x4<f32>,
    inverse_projection: mat4x4<f32>,
    ...
};
```

There's been much confusion over which of these do what. It would be much better to call, for instance the projection matrix, view_to_clip. We could then put "This is the projection matrix" in a doc comment.

We could also use a doc comment for unjittered_view_proj vs view_proj. The unjittered matrix is basically only useful for calculating motion vectors for TAA, and is equivalent to the view_proj matrix when the motion vector prepass is disabled. Users shouldn't really need to touch the unjittered matrix ever.

**Comment by ickk** [comment]
In Hotham we eventually settled on `y_from_x` as the naming convention of transforms, since it composes better than `x_to_y`;
we have lots of code that looks like:
```rust
let global_from_local = global_from_stage * stage_from_local;

let local_from_mesh = local_from_global * global_from_joint * joint_from_mesh;
```

which is easier to quickly read than
```rust
let local_to_global = stage_to_global * local_to_stage;

let mesh_to_local = global_to_local * joint_to_global * mesh_to_joint;
```

**Comment by JMS55** [comment]
Good point, I agree :)
