### ISSUE TITLE
Bevy crashes when not found any audio device

### ISSUE THREAD

**Issue by qarmin** [bevyengine/bevy#850]
**Bevy version**

**Operating system & version**
Ubuntu 20.10 docker

**What you did**

I wanted to run bevy inside ubuntu docker image 

**What you expected to happen**

App should open properly

**What actually happened**
This error was shown and later crash happens
```
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4743:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4743:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4743:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5231:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
thread 'main' panicked at 'The device doesn't support any format!?: DeviceNotAvailable', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.0/src/stream.rs:191:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Additional information**
When not found audio device, bevy shouldn't crash but only show error - https://github.com/RustAudio/rodio/issues/334

**Steps to reproduce**
- Open 20.10 docker image
- Install xvfb `apt install xvfb`
- Download and compile Mesa from source and install it  (it contains LavaPipe, which allow to run Vulkan app in CI)
- Clone Bevy
- `cargo run --example clear_color` (it is a little strange that this example needs audio)
- `xvfb-run target/debug/examples/clear_color`

**Comment by castarco** [comment]
Can you provide a minimal code example? I guess that for developers involved it's probably quite straightforward to find the problem source, but I'm curious about what are the plugins involved.

I actually came here to write about another less problematic bug, but probably related. When I use `DefaultPlugins`, and I don't do anything with the sound, I get this error message (although without crashing the process):

```
thread '<unnamed>' panicked at 'attempt to multiply with overflow', /home/castarco/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.1/src/host/alsa/mod.rs:692:23
```

My system is Ubuntu 20.04 64bits, without Docker.

**Comment by iwikal** [comment]
This happened to me as well. I had ALSA configured to use a sound card that wasn't connected. I would be very surprised if the minimal example isn't just using the AudioPlugin.

**Comment by k-brk** [comment]
I encountered same panic lately when I was trying out Bevy. I'm using Bevy v0.3  on Arch 5.8.12-arch1-1 without docker, I'm able to reproduce it every time with following minimal example(AudioPlugin alone is enough to cause this but we will get other panics without rest of plugins)
<details>
  <summary>Minimal code example</summary>

```
use bevy::{asset::AssetPlugin, audio::AudioPlugin,core::CorePlugin, type_registry::TypeRegistryPlugin, prelude::*};

fn main() {
    App::build()
    .add_plugin(TypeRegistryPlugin::default())
    .add_plugin(CorePlugin::default())
    .add_plugin(AssetPlugin::default())
    .add_plugin(AudioPlugin::default())
    .run();
}
```
  
</details>
<details>
<summary>Backtrace</summary>

```
ALSA lib pcm_dmix.c:1090:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at 'The device doesn't support any format!?: DeviceNotAvailable', /home/ja/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.0/src/stream.rs:193:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: core::result::Result<T,E>::expect
             at /home/ja/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:933
   4: <cpal::platform::platform_impl::Device as rodio::stream::CpalDeviceExt>::new_output_stream
             at /home/ja/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.0/src/stream.rs:191
   5: rodio::stream::OutputStream::try_from_device
             at /home/ja/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.0/src/stream.rs:32
   6: rodio::stream::OutputStream::try_default
             at /home/ja/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.13.0/src/stream.rs:46
   7: <bevy_audio::audio_output::AudioOutput<P> as core::default::Default>::default
             at /home/ja/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_audio-0.3.0/src/audio_output.rs:22
   8: <T as bevy_ecs::resource::resources::FromResources>::from_resources
             at /home/ja/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.3.0/src/resource/resources.rs:401
   9: bevy_app::app_builder::AppBuilder::init_thread_local_resource
             at /home/ja/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.3.0/src/app_builder.rs:255
  10: <bevy_audio::AudioPlugin as bevy_app::plugin::Plugin>::build
             at /home/ja/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_audio-0.3.0/src/lib.rs:23
  11: bevy_app::app_builder::AppBuilder::add_plugin
             at /home/ja/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.3.0/src/app_builder.rs:271
  12: bevy_game::main
             at ./src/main.rs:4
  13: core::ops::function::FnOnce::call_once
             at /home/ja/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>
It panics on following unwrap:

https://github.com/bevyengine/bevy/blob/f69cc6f94c9df675457b56297d582c16b5d37cef/crates/bevy_audio/src/audio_output.rs#L22

Workaround for this issue on Arch is to set default sound card ( https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture#Set_the_default_sound_card ), tried setting sound card order via kernel module and it solves issue.

**Comment by VictorAlbertsson** [comment]
I'm running Arch and also have this issue however I can't seem to fix it, maybe my ALSA setup is completely broken and I haven't noticed it until now (everything except this is working fine) or a more in-depth solution would be appreciated.

**Comment by samuel-cavalcanti** [comment]
I'm a arch user to and have the same issue, I following the getting started tutorial when this happens 

https://bevyengine.org/learn/book/getting-started/plugins/  
my code:  
```rust
   App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(add_people.system())
        .add_system(hello_world.system())
        .add_system(greet_people.system())
        .run();
```
OBS: i installed the dependencies  __libx11 pkgconf alsa-lib__

**Comment by norman784** [comment]
Installing `pulseaudio-alsa` fixed the issue for me.

**Comment by samuel-cavalcanti** [comment]
> Installing `pulseaudio-alsa` fixed the issue for me.

I have `pulseaudio-alsa` installed, for me it's not work :sob:

**Comment by norman784** [comment]
> Workaround for this issue on Arch is to set default sound card ( https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture#Set_the_default_sound_card ), tried setting sound card order via kernel module and it solves issue.

@samuel-cavalcanti I'm not sure if following the guide above helped too, because I first tried to add the `/etc/asound.conf` and `/etc/modprobe.d/alsa-base.conf` files,  after that I restarted and lastly I installed the `pulseaudio-alsa` package.

**Comment by samuel-cavalcanti** [comment]
Wtf ?!  reinstalling the package  works .
Thank you @norman784 ,  I do not know why, but  adding  the config in  `~.asound.conf` and reinstalling the `pulseaudio-alsa` works for me.
Someone can put this information in  docs/linux_dependencies.md , helps a lot

**Comment by unknownue** [comment]
I work out a solution on **ubuntu container** (20.04):

1. Install audio package by: `apt install alsa pulseaudio`
2. Set audio source as described in [here](https://superuser.com/a/1545361), to be specific:
    1. Give audio access to current user: `adduser $(id -u -n) pulse-access`
    2. `rm -rf /var/run/pulse /var/lib/pulse /root/.config/pulse`
    3. `pulseaudio -D --verbose --exit-idle-time=-1 --system --disallow-exit`
    4. `pactl load-module module-virtual-source master=auto_null.monitor format=s16le source_name=VirtualMic`
    5. `pactl set-default-source VirtualMic`
3. Run your problem: `cargo run`

**Comment by visualcode-t** [comment]
I have noticed this same issue on many different machines. I don't think this is as much a driver issue as it is a problem that should be addressed with Bevy. Bevy should opt out of audio before crashing, or at least, it should allow the developer to make this decision. Many applications and even games are fine without audio and a developer shouldn't have to offer two versions of a program (one with and one without audio dependencies).

I know there has been discussion to change the audio system in Bevy, perhaps this should be addressed there? @Moxinilian @Dash-L

**Comment by cart** [comment]
Yeah I agree that Bevy shouldn't crash in this case. Ideally it just displays an error message when a device can't be found (and probably when audio is played but no device is available). Additionally, it would be great if it could gracefully respond to devices being connected / defaults being switched.

**Comment by forbjok** [comment]
This issue is present in Windows as well, although the error message is slightly different.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoDevice', C:\Users\forbjok\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_audio-0.5.0\src\audio_output.rs:22:67
```

While it's probably not super common to not have an audio device, it definitely should not cause a crash.
