### ISSUE TITLE
example shader_material_glsl panics due to missing feature

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#8505]
## Bevy version

main since #8491

## What you did

```
cargo run --example shader_material_glsl
```

## What went wrong

It panics with
```
thread 'Compute Task Pool (0)' panicked at 'not implemented: Enable feature "shader_format_glsl" to use GLSL shaders', crates/bevy_render/src/render_resource/shader.rs:215:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread 'Compute Task Pool (1)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', crates/bevy_render/src/pipelined_rendering.rs:135:45
```

## Additional information

This is expected as glsl support is now behind a feature. Should the example be removed? Or the feature enabled by default? Or the example updated to have a better fallback when the feature is not enabled?

**Comment by wpederzoli** [comment]
Hi @mockersf. I am not able to reproduce this on `main` or `latest` branches. I'm on Linux, is this maybe a MacOS specific behavior?

**Comment by mockersf** [comment]
It is also failing on CI on Linux: https://rparrett.github.io/prototype_bevy_example_runner/

Maybe it's working if you use the OpenGL renderer, CI is on Vulkan

**Comment by wpederzoli** [comment]
Hmm... Interesting. I just ran the example out of the box (no changes) and I can see in the terminal output `backend: Vulkan`. 
Maybe I'm missing something

**Comment by rparrett** [comment]
What is the status of the `shader_format_glsl` after #5703 ?

It seems like the `shader_material_glsl` example no longer needs it to function.

**Comment by rparrett** [comment]
It looks like `shader_material_glsl` was causing `naga/glsl-in`, `naga/wgsl-out` to be added, but now those are added unconditionally by `naga-oil`.

So it seems like `shader_material_glsl` can be removed now, which is effectively the second suggestion in https://github.com/bevyengine/bevy/pull/8657#issuecomment-1572183250

**Comment by mockersf** [comment]
`shader_format_glsl` is now a required feature of the example
