### ISSUE TITLE
Quickstart requires Rust Nightly

### ISSUE THREAD

**Issue by daniel-butler** [bevyengine/bevy#8519]
Hi when following the [getting started guide](https://bevyengine.org/learn/book/getting-started/) the line below fails with this error below because it requires rust nightly build as the default.

`cargo run --example breakout`

Error:
```
error: failed to load manifest for workspace member `/code/bevy/crates/bevy_a11y`

Caused by:
  failed to load manifest for dependency `bevy_app`

Caused by:
  failed to parse manifest at `/code/bevy/crates/bevy_app/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
```

It is pretty easy to fix with the command `rustup default nightly`.

**Comment by mockersf** [comment]
The `dep:` syntax has been stabilized on Rust 1.60, you don't need nightly but a version more recent than that. Generally Bevy works better with the last est stable, which is 1.69 currently

**Comment by daniel-butler** [comment]
Good to know! Running `rustup upgrade` fixed it. I'll update the CR I sent.
