### ISSUE TITLE
Transparent Rendering of Isospheres Completely Screwed Up

### ISSUE THREAD

**Issue by iMplode-nZ** [bevyengine/bevy#853]
**Bevy version**

0.3, 0.2.1, 0.2, latest

**Operating system & version**

Windows 10, Ubuntu 20.04

**What you did**

Rendered two transparent icospheres on top of each other.

**What you expected to happen**

I should be able to see both of them.

**What actually happened**

One of them clips the other, and it changes depending on viewing angle/

**Comment by iMplode-nZ** [comment]
![image](https://user-images.githubusercontent.com/31631663/99032154-a6600a00-252d-11eb-8c63-5e2095a15af6.png)

**Comment by alice-i-cecile** [comment]
@iMplode-nZ, does this still occur with the new renderer?

**Comment by aevyrie** [comment]
This is because bevy doesn't have order-independent transparency yet. See https://github.com/bevyengine/bevy/issues/2223

**Comment by alice-i-cecile** [comment]
Sounds good. Closing in favor of #2223 then to keep this tidy.
