### ISSUE TITLE
`texture_binding_array` example no longer runs on main

### ISSUE THREAD

**Issue by DGriffin91** [bevyengine/bevy#8556]
## Bevy version: main d319910d36e65fe6b7537ca40e4e44f81d8e6bba

71842c5ac92dc61b0c73446a233078d5285ecf7c broke the `texture_binding_array` example:

thread 'main' panicked at 'Requested resource `bevy_render::renderer::render_device::RenderDevice` does not exist in the `World`. 
                Did you forget to add it using `app.insert_resource` / `app.init_resource`?
                Resources are also implicitly added via `app.add_event`,
                and can be added by plugins.', examples/shader/texture_binding_array.rs:20:35

**Comment by JMS55** [comment]
See https://github.com/bevyengine/bevy/pull/8553
