### ISSUE TITLE
implement From<Color> for [u8; 4]

### ISSUE THREAD

**Issue by atornity** [bevyengine/bevy#8563]
## What problem does this solve or what need does it fill?

It's convenient when working with images to be able to convert a color to a u8 array.

## What solution would you like?

either:
    - implement From\<Color\> for [u8; 4]
    - implement a method with a specific name in Color.

## What alternative(s) have you considered?

manually convert it.
```
[
    color.r().mul(255.0) as u8,
    color.g().mul(255.0) as u8,
    color.b().mul(255.0) as u8,
    color.a().mul(255.0) as u8,
]
````

it feels a bit unnecessary

**Comment by james7132** [comment]
The primary issue I see with this is that it's unclear what color space the result is supposed to be in using a `From` impl. An explicitly named conversion is probably the way to go here.

**Comment by atornity** [comment]
ah, I should have read that lol

**Comment by atornity** [comment]
> The primary issue I see with this is that it's unclear what color space the result is supposed to be in using a `From` impl. An explicitly named conversion is probably the way to go here.

what name would make sense for this? `into_rgba_u8`?

**Comment by atornity** [comment]
> The primary issue I see with this is that it's unclear what color space the result is supposed to be in using a `From` impl. An explicitly named conversion is probably the way to go here.

From<Color> is implemented for [f32; 4] already. what makes this different?

**Comment by james7132** [comment]
Oh yeah you're right. IMO that should be removed since it has an implicit conversion and it's unclear what color space it's using.
