### ISSUE TITLE
`LoadState` does not provide useful information on why asset loading failed

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#8566]
## Bevy version

0.10.1

## What you did

Load an asset using an `AssetServer`, and call `get_load_state` on the returned handle.

## What went wrong

The [`LoadState`](https://docs.rs/bevy/latest/bevy/asset/enum.LoadState.html) enum only returns `AssetState::Failed`, which is not actionable or useful for debugging.

## What solution would you like

Bubble the error that caused loading to fail up to the user.

**Comment by SET001** [comment]
we can extend `LoadState` with `Failed(String)`, but then we shall sacrifice with `Copy` trait. Is it ok?

**Comment by alice-i-cecile** [comment]
Yeah, I don't think there's any fundamental reason why this needs to be `Copy`. As long as `Clone` is around we'll be fine.

It might make more sense to store an internal enum instead of a `String`, explaining why failure occured.

**Comment by SET001** [comment]
if by internal enum you mean `AssetServerError` then making `Failed(AssetServerError)` would be a bit problematic to implement since `LoadState` enum implements too many trains that is not implemented in `AssetServerError`. Not sure what is the correct solution in this situation but at least I have a working solution for the case with `Failed(String)`, that's why I suggest it.

**Comment by alice-i-cecile** [comment]
Hmm, that would be ideal. I don't think that's unsolvable: those trait impls don't appear particularly important or tricky.

**Comment by SET001** [comment]
Implemented `Clone` for `AssetServerError` and `AssetIoError` (not sure about the correctness of the implementation, I'm still learning)

**Comment by countcb** [comment]
Hello everyone :)

Is this solved in bevy 0.14? 
https://bevyengine.org/learn/migration-guides/0-13-to-0-14/#add-error-info-to-loadstate-failed

Or does this issue request something else / more than is implemented with the current change?

**Comment by alice-i-cecile** [comment]
Nope this is done now!
