### ISSUE TITLE
Asset loading fails on Linux but succeeds on Windows

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#8568]
## Bevy version

0.10.1

## What you did

Ran `cargo run -p ci` on https://github.com/Leafwing-Studios/Emergence/pull/746 after using `git lfs pull`.

## What went wrong

On PopOS, all assets end up in `AssetState::Failed`.

On Windows, the same list of assets end up in `AssetState::Loaded`.

## Additional information

Asset loading in general works for me on PopOS.

There *may* be some file path weirdness going on here: this is being run in a subfolder as it is intended to be used in CI. Oddly though the complete list of assets is discovered correctly in both cases.

**Comment by mockersf** [comment]
could you try to reproduce without git ifs and with less assets?

**Comment by alice-i-cecile** [comment]
Going to close out for now: there's a good chance this is fixed with our better path handling.
