### ISSUE TITLE
Left mouse button press not registered after hitting a keyboard key

### ISSUE THREAD

**Issue by tgbrooks** [bevyengine/bevy#8576]
## Bevy version

0.10.1

## \[Optional\] Relevant system information
Windows 11

## What you did

Press (and release) any keyboard key, say 'A', then click the left mouse button. The click is not registered. Left click again and it will be registered, but the first press after a keyboard key is not picked up by `pressed()` or `just_pressed` or `just_released`. The right mouse button work just fine.

``` rust
use bevy::{prelude::*, input::mouse::MouseButtonInput};

fn basic_mouse(buttons: Res<Input<MouseButton>>) {
    if buttons.pressed(MouseButton::Left) {
        info!("LEFT");
    }
}

fn main() {
    App::new().add_system(basic_mouse)
        .add_plugins(DefaultPlugins)
        .run()
    ;
}
```

## What went wrong

I was expecting all presses of the left mouse button to display a "LEFT" message. However, presses immediately following a keyboard press were not. Moreover, if you hold down a key, left mouse button presses are not registered, even when clicking repeatedly. The same behavior happens when using `EventReader<MouseButtonInput>` instead.

Some keyboard keys don't generate this problem, for example the arrow keys or ctrl/shift/alt.

The window doesn't loose focus at any point, which was my only guess as to what could be going wrong.

**Comment by alice-i-cecile** [comment]
Very strange. Do you have any other devices or OS's you can test this on? Can you reproduce it on web builds?

**Comment by tgbrooks** [comment]
I'll try to do a web build or run it on another PC tomorrow. I also tried to find a `winit` example that I could test, but I don't see any that print out the mouse events or anything like that. Is there one that would be useful? Otherwise I'll have to try to cook one up.

**Comment by alice-i-cecile** [comment]
Yeah, I suspect you'll have to hack together a small example on Winit :)

**Comment by tgbrooks** [comment]
Okay I reproduced the problem with just `winit` and not `bevy` with the following program:

``` rust
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            } if window_id == window.id() => *control_flow = ControlFlow::Exit,
            Event::WindowEvent {
                event: WindowEvent::KeyboardInput {
                    device_id,
                    input,
                    is_synthetic
                },
                window_id,
            } if window_id == window.id() => {
                println!("Keyboard event {device_id:?} {input:?} {is_synthetic:?}");
            },
            Event::WindowEvent {
                event: WindowEvent::MouseInput {
                    device_id,
                    state,
                    button,
                    modifiers
                },
                window_id,
            } if window_id == window.id() => {
                println!("Mouse event {device_id:?} {state:?} {button:?} {modifiers:?}");
            },
            _ => (),
        }
    });
}
```

I'll go ahead and close this issue as it doesn't appear to be a `bevy` problem.
