### ISSUE TITLE
One-frame lag when spawning scenes

### ISSUE THREAD

**Issue by thefakeplace** [bevyengine/bevy#8616]
## Bevy version

0.10

## What you did

Create an entity with a `Handle<Scene>` in `FixedUpdate` during game logic.

## What went wrong

Spawns one frame later, once `scene_spawner` in `PreUpdate` runs.

## Additional information

Seems like a natural consequence of `bevy_scene`'s design.

**Comment by Shatur** [comment]
Should be fixed by #9260.

**Comment by doonv** [comment]
Can you still reproduce this?

**Comment by Shatur** [comment]
I think we can close it.
