### ISSUE TITLE
post_processing example crashes when trying to run

### ISSUE THREAD

**Issue by louiidev** [bevyengine/bevy#8620]
## Bevy version
tested on: https://github.com/bevyengine/bevy/commit/1da726e046b378f347eb72b072fac2509c5367e6

I ran the example and it immediately crashes.

## Additional information
example:  `examples/shader/post_processing.rs`

compiler output: 
```
thread 'main' panicked at 'Requested resource bevy_render::renderer::render_device::RenderDevice does not exist in the `World`. 
                Did you forget to add it using `app.insert_resource` / `app.init_resource`? 
                Resources are also implicitly added via `app.add_event`,
                and can be added by plugins.', examples/shader/post_processing.rs:243:35
```

**Comment by mockersf** [comment]
Should be fixed by https://github.com/bevyengine/bevy/pull/8553
