### ISSUE TITLE
Replace remaining usages of the word "stage" in the context of ECS

### ISSUE THREAD

**Issue by ItsDoot** [bevyengine/bevy#8641]
## How can Bevy's documentation be improved?

As of Schedule V3, we now design system *schedules*, not *stages*. However there's still a few places where the word `stage` is mentioned. These can be found with a simple recursive directory search.

## Example
https://github.com/bevyengine/bevy/blob/f76b3c4230e890e3cdeb01c26809cf4bde8d26f4/errors/B0003.md#L57-L67

**Comment by alice-i-cecile** [comment]
Let me know if you need help figuring out how to replace any existing usages!
