### ISSUE TITLE
Directional light shadows disappear when camera is rotated

### ISSUE THREAD

**Issue by GitGhillie** [bevyengine/bevy#8645]
## Bevy version
0.10.1,
main [(f76b3c4)](https://github.com/bevyengine/bevy/commit/f76b3c4230e890e3cdeb01c26809cf4bde8d26f4)

## Relevant system information
- SteamOS 3.4.6
`AdapterInfo { name: "AMD Custom GPU 0405 (RADV VANGOGH)", vendor: 4098, device: 5695, device_type: IntegratedGpu, driver: "radv", driver_info: "Mesa 22.2.5", backend: Vulkan }`

## What you did

- Spawn two horizontal planes above each other
- Spawn directional light and a camera between the planes
- Rotate camera

See somewhat minimal example [here](https://gist.github.com/GitGhillie/349873973418e3d2c548ef73b2310c7f).

## What went wrong
Depending on the distance and angle of the camera some shadows partially disappear. As seen [here](https://github.com/bevyengine/bevy/discussions/8571) it can quickly ruin a scene.

In the example code I gave only rectangular shadows should be possible but when you spawn in it looks like this:
![bevy_shadow](https://github.com/bevyengine/bevy/assets/23659539/a6a59e8c-d13e-4cf3-93c9-207e3afcfcd6)
Move around the camera with the mouse and you will see the shadow change shape.

## Additional information
Same issue on my Windows 10 desktop (tested with Bevy 0.10.1) but I'm currently abroad so I cannot check the exact `AdapterInfo`. It has an AMD Vega 56 gpu and uses the Vulkan backend as well.

**Comment by DGriffin91** [comment]
I've also noticed this issue.

**Comment by GitGhillie** [comment]
@DGriffin91 good to know it's not just me. Are you also using Vulkan + AMD card?

**Comment by DGriffin91** [comment]
I've seen it on both DX12 and Vulkan on Nvidia. I think it's probably an issue with the directional light shadow cascade calculations. Maybe something in https://github.com/bevyengine/bevy/blob/ca81d3e4359f158bcf2e20e77d82d7ab52daafc5/crates/bevy_pbr/src/light.rs#L513

**Comment by DGriffin91** [comment]
Here's a video of the issue: 

https://github.com/bevyengine/bevy/assets/33357138/666b07d1-0f71-4f18-a0f5-ac6b2bbbc92a

This is with these settings:
```
CascadeShadowConfigBuilder {
    num_cascades: 4,
    minimum_distance: 0.01,
    maximum_distance: 50.0,
    first_cascade_far_bound: 3.0,
    overlap_proportion: 0.2,
}
```

This issue also happens in the sponza test scene.

**Comment by superdump** [comment]
Hmm, I can't seem to reproduce with the example code on an M1 Max in macOS. Could someone make a video of the problem with the example code? Or else make a minimal example that reproduces the problem, plus a video showing the problem you see?

**Comment by superdump** [comment]
Ok, I tried on `AdapterInfo { name: "NVIDIA GeForce RTX 3080 Laptop GPU", vendor: 4318, device: 9372, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "528.02", backend: Vulkan }` on Windows 11 and it looked fine. But with `WGPU_BACKEND=dx12` I see the issue. The shadow on the plane beneath the camera should be rectangular, but when looking down a bit the corner kind of inverts such that light cuts into the shadow region. Hmm, @danchia and @DGriffin91 were discussing near plane problems on Discord and now I've seen it first hand I'm inclined to agree.

**Comment by DGriffin91** [comment]
@superdump I made a little test, the included one was a bit disorienting for me: https://github.com/DGriffin91/bevy_csm_test I see the issue on both vulkan and dx12 on a RTX3060. I have the camera spawn near one issue. You can also see it it you go up to one of the upper corners.

**Comment by GitGhillie** [comment]
https://github.com/bevyengine/bevy/assets/23659539/3dc8e065-efbd-48d5-9fbe-39eea864397d

Looks like the issue occurs near the camera and near the transitions of the cascade bounds.
Cascade settings for this video:
```
cascade_shadow_config: CascadeShadowConfigBuilder {
                num_cascades: 3,
                maximum_distance: 20.0,
                overlap_proportion: 0.0,
                ..default()
            }
```

**Comment by GitGhillie** [comment]
[Discord thread on the issue](https://discord.com/channels/691052431525675048/1116857436528181300)

**Comment by DGriffin91** [comment]
This appears to still be an issue in sponza with bevy 0.11
![image](https://github.com/bevyengine/bevy/assets/33357138/b412dfb8-e4f4-4e4a-a6a2-9fd83e33112f)
![image](https://github.com/bevyengine/bevy/assets/33357138/0ae0cfd7-952f-40c4-9e7c-f295bbc1246d)
![image](https://github.com/bevyengine/bevy/assets/33357138/8bf5be29-e405-4a63-8262-02b447d3bc44)
https://github.com/DGriffin91/bevy_sponza_scene

**Comment by DGriffin91** [comment]
This appears to still be an issue in bistro with bevy 0.11
https://github.com/DGriffin91/bevy_bistro_scene
![image](https://github.com/bevyengine/bevy/assets/33357138/b408aecf-9a92-41e0-94a9-951e98664fd1)
