### ISSUE TITLE
Change detection doesn't work inside parallel queries

### ISSUE THREAD

**Issue by Dauthdaert** [bevyengine/bevy#8656]
## Bevy version

0.10.0

## What you did

I have a query using a Ref parameter and is_changed() to detect if one of two conditions (position changed or override flag) is true in order to avoid calculating FoV every frame. Since it's an expensive operation, I also want to use par_iter_mut in order to make the query parallel.
My problem is that, once I add par_iter_mut to my query, change detection seems to break and position.is_changed() is never true.

Example code
```rust
query
    .par_iter_mut() // If I remove this line, then change detection starts working again.
    .for_each_mut(|mut to_change, maybe_changed| {
        if maybe_changed.is_changed() || to_change.some_flag {
            to_change.expensive_change();
        }
   });
```

## What went wrong

I would expect change detection to work in either case, but it seems to only work with sequential queries.

## Additional information

In case it changes something, the specific query I'm having trouble with is also inside a ParamSet.
Also, this is a regression from bevy 0.9, where it worked fine.

**Comment by hymm** [comment]
I believe this is the same issue already fixed in https://github.com/bevyengine/bevy/pull/8029

**Comment by Dauthdaert** [comment]
Oops, my mistake. Looked for an issue before posting, but didn't think to search for a PR unassociated to an issue.
Thanks.
