### ISSUE TITLE
without_winit example panics

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#8658]
## Bevy version

main df3e81c1fb1f49fc59103e0eaed522dc123a2982
bisected to 71842c5ac92dc61b0c73446a233078d5285ecf7c, but the specific panic has changed at some point between then and now.

## Relevant system information

```
SystemInfo { os: "MacOS 13.3.1 ", kernel: "22.4.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

`cargo run --example without_winit`

## What went wrong

```
thread 'Compute Task Pool (0)' panicked at 'Resource requested by bevy_render::render_resource::pipeline_cache::PipelineCache::extract_shaders does not exist: bevy_render::render_resource::pipeline_cache::PipelineCache', /Users/me/src/bevy/crates/bevy_ecs/src/system/system_param.rs:545:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::extract_shaders`!
```

**Comment by re0312** [comment]
it's probably an issue with async render initialisation , since #8336 all plugins should call  `finish`  and  `cleanup`  before app is ready to update,But it is only executed within the winitplugin
