### ISSUE TITLE
`TextAlignment` has no effect on text alignment, only controls justification for multi-line texts

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy#8659]
Unlike [CSS `text-align`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align) which aligns the text inside a box and justify it, in Bevy the alignment of text is based on the concept of anchors. One _can_ build a similar result to CSS `text-align` based on anchors and a parent node, but by default the anchor itself does the alignment.

The `TextAlignment` property actually controls the justifying of multi-line text only.
- It has no effect on single-line text, which is a major difference with CSS
- For multi-line texts, it aligns all-but-the-longest lines inside the horizontal space defined by the longest line.

It's arguable the name `TextAlignment` is suited, due to confusion with CSS and general meaning of "align" which for UI actually move elements to the left/right, whereas here the text as a whole never moves (some parts of it do, but the bounds are unaffected).

To make things more confusing, the [documentation](https://docs.rs/bevy/latest/bevy/text/enum.TextAlignment.html) talks about changes to bounds, but text alignment has no effect on the text bounds, sine all "alignment" is done within the computed bounds derived from the max line length and number of lines.

## Proposed actions

- A minima, fix docs to not talk about bounds
- Call out the major difference with CSS `text-align`
- I'd personally be for a rename of that type to avoid confusion.

**Comment by djeedai** [comment]
> To clarify, are we talking about Text2d or text in the UI?

I tested with `Text2dBundle`. Although that's part of the issue: I'm well unable to tell what "text in the UI" is and how it's different from `Text2d`. We shouldn't have multiple text behaviors.

**Comment by rparrett** [comment]
I believe this was fixed by #10854. Please reopen if I'm wrong.
