### ISSUE TITLE
Hide Naga Info Logs

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#8662]
## What problem does this solve or what need does it fill?

Currently Naga prints noisy / unhelpful messages to the console (ex: "skip function X") for the Bevy PBR shaders:
![image](https://github.com/bevyengine/bevy/assets/2694663/b7807046-7b4a-4ae6-99ad-64d32fde1db5)

These aren't really relevant to Bevy users.

## What solution would you like?

Hide Naga info logs by default. This can be done in the `bevy_log` crate by adding a "naga=warn" entry to the default `LogPlugin::filter` config.

**Comment by IceSentry** [comment]
I was curious if this would cause us to lose some important logs, but it looks like the only info logs in naga are about skipping stuff. So we aren't losing anything by going to warn level.
