### ISSUE TITLE
Better error messages for unsupported shading language features

### ISSUE THREAD

**Issue by bonsairobo** [bevyengine/bevy#869]
**What problem does this solve or what need does it fill?**

I have noticed a couple instances where people write a shader for bevy, but the shader reflection code gives an opaque error that a certain shading language feature is not supported. This results in confusion and questions popping up in the Discord.

For example, if someone tries to use a combined image sampler like this:

```glsl
layout(set = 0, binding = 0) uniform sampler2DArray samp;
```

They will get this error:

```
thread 'Compute Task Pool (0)' panicked at 'unsupported bind type CombinedImageSampler'
```

**Describe the solution would you like?**

Just some more actionable error messages would be nice. They should tell you that the feature is explicitly not supported, and what to do instead. In the example above, tell the user that they should split the binding into separate texture and sampler, like so:

```glsl
layout(set = 0, binding = 0) uniform image2DArray tex_array; // I think this is right. Maybe "texture2D[N]"?
layout(set = 0, binding = 1) uniform sampler samp;
```

**Describe the alternative(s) you've considered?**

If there is a way to let wgpu handle the error, that would be extra cool, although I don't expect that to be as easy, since the errors occur during bevy's own shader reflection.

**Additional context**

Some of the discord discussion: https://discord.com/channels/691052431525675048/743663924229963868/777642132965294091

Related wgpu issue: https://github.com/gfx-rs/wgpu-rs/issues/93#issuecomment-548444263

**Comment by amberkowalski** [comment]
Would this kind of feedback be useful?
`panicked at 'unsupported bind type CombinedImageSampler (set 10, binding 0)'`

**Comment by bonsairobo** [comment]
@amberkowalski Yea sure, the descriptor set and binding would be useful info. It already points you at a file and line number, which I didn't include in my example, but the more explicit the better.

The main thing I'm looking for though is some kind of message that offers a suggestion on how to proceed, kind of like how the rust compilter will give hints sometimes.

**Comment by amberkowalski** [comment]
I wouldn't mind putting the effort into building a nicer error stack, but I'd like someone else's feedback on the idea first.

**Comment by MyIsaak** [comment]
I open a PR for this issue: https://github.com/bevyengine/bevy/pull/2598
