### ISSUE TITLE
Support for multiple texture coordinates / UV maps

### ISSUE THREAD

**Issue by jurisk** [bevyengine/bevy#8699]
### Summary 

Bevy `bevy_gltf` and meshes currently do not support multiple texture coordinate sets (multiple UV maps).

glTF spec https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#meshes indicates that it should:

> Client implementations **SHOULD** support at least two texture coordinate sets, one vertex color, and one joints/weights set

### Discussed in https://github.com/bevyengine/bevy/discussions/8698

<div type='discussions-op-text'>

<sup>Originally posted by **jurisk** May 28, 2023</sup>
When loading a glTF scene, I'm getting `WARN bevy_gltf::loader: Unknown vertex attribute TEXCOORD_1` errors, and the model loads, but without textures shown (it's completely grey).

I think this is because:
- The model has multiple UV Texture coordinate attributes defined
- https://github.com/bevyengine/bevy/blob/main/crates/bevy_gltf/src/vertex_attributes.rs#L251 only supports texture coordinate 0
- Likewise for https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/mesh/mesh/mod.rs#L68

Two questions:
- Is there an open issue or RFC in Bevy for adding support for multiple sets of texture coordinates / UV maps?
- What are my options for loading / converting such a model?</div>

@nicopap responded:
> Yeah, you can open an issue as a feature request. #1802 lists "Multiple UVs" as a goal, but there isn't an open issue.
> 
> Looking at the GLtf spec (https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#meshes), I see:
> 
> > Client implementations **SHOULD** support at least two texture coordinate sets, one vertex color, and one joints/weights set
> 
> searching for "texture coordinate" in the GLtf document, it seems multiple UVs are used to have a different set of coordinate per material textures (say the normal texture could map differently to the mesh than the diffuse/color texture) I don't quite see how we could implement it in bevy, but I think it's probably a worthwhile feature to consider.

**Comment by Adriaaaaan** [comment]
This is key for those of us using lightmaps,  gltfs exported from unreal can go as high as uv4 so It would be great if it was more than just adding uv1 also

**Comment by superdump** [comment]
Fixed by #9992
