### ISSUE TITLE
`render::primitive::Plane` is confusing

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#8730]
## How can Bevy's documentation be improved?

[`render::primitive::Plane`](https://github.com/bevyengine/bevy/blob/4ce37395da029eb8b58c78c32812fe8329a3a1a4/crates/bevy_render/src/primitives/mod.rs#L84-L91) is used mostly for frustum culling.

It is used as a half-space (discriminate between two sides of a plane in 3d space) to find which sector of a frustum we are in , and I think it should be renamed to `HalfSpace`, especially given we already have a `shape::Plane` that has nothing to do with it.

**Comment by alice-i-cecile** [comment]
Agreed here :)
