### ISSUE TITLE
SIGSEGV when closing windows on X

### ISSUE THREAD

**Issue by A-Walrus** [bevyengine/bevy#8735]
## Bevy version
4ce37395da029eb8b58c78c32812fe8329a3a1a4

## \[Optional\] Relevant system information
Rust version: 1.69.0
Linux 6.3.5-arch1-1, on X11

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```ignore
AdapterInfo { name: "NVIDIA GeForce GTX 1050", vendor: 4318, device: 7309, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "530.41.03", backend: Vulkan }
```

## What you did
`cargo run --example <any example>`
hit close button on window

## What went wrong
first logged, as normal:
`2023-06-01T12:58:18.583448Z  INFO bevy_winit::system: Closing window 0v0` 
Then program freezes.
Sometimes program also crashes with SIGSEGV
## Additional information
On Wayland (without the `wayland` feature, i.e. running through XWayland) window closes perfectly fine, problem is only on Xorg

**Comment by AxiomaticSemantics** [comment]
@A-Walrus Is this still an issue in recent bevy? If so which window manager are you using?

**Comment by A-Walrus** [comment]
I'm unable to reproduce this anymore, closing
