### ISSUE TITLE
Add `WindowResolution::logical_width` and `logical_height`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#8799]
## What problem does this solve or what need does it fill?

All of the required information needed to compute the logical width and height of a window is present on [`WindowResolution`](https://docs.rs/bevy/latest/bevy/window/struct.WindowResolution.html#).

But since these methods don't exist, snippets like [this](https://github.com/bevyengine/bevy/pull/7795/files#diff-fd92b1243b4cfed68b98f0027f06728c121f50117b01f6a167d2e21511b9663cR207) are written.

## What solution would you like?

Add the methods.

## What alternative(s) have you considered?

We could also add a `logical_resolution` method that returns a `Vec2` as well, as shown in the snippet linked above.

## Additional context

Scale factor bugs are abundant and this is frustratingly easy to screw up. This is a simple step towards improving that.

**Comment by hate** [comment]
Forgive me if I'm mistaken, but aren't the logical width and height already available using the following [width](https://github.com/bevyengine/bevy/blob/a1494e53dfa90e56bd14452b1efb930bd3e79821/crates/bevy_window/src/window.rs#L517) and [height](https://github.com/bevyengine/bevy/blob/a1494e53dfa90e56bd14452b1efb930bd3e79821/crates/bevy_window/src/window.rs#LL523C1-L523C1) methods?

**Comment by alice-i-cecile** [comment]
Ah, I see! I missed this because there was no doc alias.
