### ISSUE TITLE
Text doesn't want to move even with transform

### ISSUE THREAD

**Issue by timleg002** [bevyengine/bevy#880]
**Bevy version**

latest (db2d20e)

**Operating system & version**

Windows 10

**What you did**

Copied the font script from "contributors.rs" example and expected it when I use a transform for it to move

**What you expected to happen**

I expected it whenI changed transform coordinates to change

**What actually happened**

It did not change, it stayed the same

**Additional information**
```rust
commands
        .spawn(UiCameraComponents{
            transform: Transform::from_translation(Vec3::new(100.0, 10.0, 0.0)),
            ..Default::default()
        })
        .with_bundle(TextComponents {
            style: Style {
                align_self: AlignSelf::FlexEnd,
                position: Rect {
                    left: Val::Px(200.0),
                    right: Val::Px(200.0),
                    top: Val::Px(200.0),
                    bottom: Val::Px(200.0)
                },
                size: Size::new(Val::Px(200.0),Val::Px(200.0)),
                ..Default::default()
            },
            text: Text {
                value: "Contributor showcase".to_string(),
                font: asset_server.load("fonts/FiraSans-Bold.ttf"),
                style: TextStyle {
                    font_size: 60.0,
                    color: Color::WHITE,
                },
                
                ..Default::default()
            },
            transform: Transform::from_translation(Vec3::new(2000.0, 150.0, 0.0)),
            global_transform: GlobalTransform::from_translation(Vec3::new(2000.0, 150.0, 0.0)),
            ..Default::default()
        });
```

I reckon those values could be overriden with another transform, but then that would be illogical, as to why? Just let one value change it.
![is1](https://user-images.githubusercontent.com/35149140/99383555-53d87200-28ce-11eb-861a-c80b13182b7e.png)
![is2](https://user-images.githubusercontent.com/35149140/99383624-6b175f80-28ce-11eb-81bd-eff22bc8d01c.png)

**Comment by mockersf** [comment]
Text `Transform` (like all UI bundles) is replaced by the one computed from the `Style` component. This is using an implementation of FlexBox.

You will have to set the `position` of `Style` to where you would expect your text...

**Comment by timleg002** [comment]
I couldn't fix this issue by using `position` of `Style`. No matter how I change the coordinates it stays at the same place. I tried changing `top`/`bottom`, `left`/`right` values with only one of them being positive, and the other one being zero, so they wouldn't cancel out. It didn't work. See a picture:
![image](https://user-images.githubusercontent.com/35149140/99448814-e5240480-291f-11eb-906a-95f452d52337.png)

**Comment by cart** [comment]
Looks like top-level nodes need absolute positioning:

```rust
style: Style {
    position: Rect {
        top: Val::Px(200.0),
        right: Val::Px(200.0),
        ..Default::default()
    },
    position_type: PositionType::Absolute,
    ..Default::default()
},
```

Note that I left `bottom` and `left` as the default "undefined" value. Setting the values to `0` is basically saying that you _also_ want to anchor them to those locations.

> Shouldn't the Transform parameter be abolished from UI bundles then?

This is something I've thought a lot about, and the decision we make will apply to a number of other parts of the engine. In essence it boils down to: if we build a layer of abstraction that "drives" a lower abstraction layer (ex: Node/Style driving the Transform), do we remove the lower level abstraction layer entirely to prevent users from knowing about it / touching it. This would mean:

1. re-implementing the Transform system logic and gpu data binding logic directly for Node/Style
2. maintaining the abstracted state internally somewhere else (probably in Resources, but maybe in a separate World)

Doing that would add a lot of complexity. But hiding complexity form users is also valuable.

**Comment by timleg002** [comment]
Thank you for your comment. I will try this tomorrow. And also, I think adding a warning to the user changing the `Transform` field of UI structs, that they should use the `Style` positioning instead.

**Comment by Moxinilian** [comment]
Have you had time to try the suggested solution? If so, did it work out?

**Comment by timleg002** [comment]
I indeed could work it out, but I met with an issue of not being able to load a font.

**Comment by Moxinilian** [comment]
Okay, feel free to open a new issue regarding the font loading problem. I'm closing this one.
