### ISSUE TITLE
bevy logo has disapeared from the `ui.rs` example

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#8805]
It seems commit #6874 removed the `image` field at line 278 of the `ui.rs` example, and we don't see the bevy logo anymore in the example, even though there is a comment alleging the opposite.

Just adding back the line doesn't seem enough though. It's all flattened, and the label text displays with the image.

```rust
                        image: asset_server.load("branding/bevy_logo_dark_big.png").into(),
```

**Comment by ickshonpe** [comment]
It was broken by the alt-text implementation. 
If UI nodes with a `MeasureFunc` (`ImageBundle` and `TextBundle`) have children then the layout algorithm ignores the `MeasureFunc` and derives the size of the node from the style properties like for a normal UI node.

I opened an issue about alt-text #7928 and there was more discussion at #7894.
