### ISSUE TITLE
FrameTimeDiagnosticsPlugin fails on WASM

### ISSUE THREAD

**Issue by mrk-its** [bevyengine/bevy#881]
**Bevy version**
current master branch

**Operating system & version**
Ubuntu 20.04

**What you did**
Run bevy `text` example with bevy_webgl2

**What you expected to happen**
Example runs without errors

**What actually happened**
```
panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:39:9
```

**Comment by amberkowalski** [comment]
Would we want to disable the plugin on WASM or find a workaround, because this is a limitation of WASM itself.

**Comment by chemicstry** [comment]
Just replace `std::Instant` with `instant` crate which supports wasm and is compatible with `std`. I think this was already done with some other part of `bevy`.
