### ISSUE TITLE
Rename `Command::write`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#8811]
## What problem does this solve or what need does it fill?

This name is unclear: it actually evaluates the `Command` on the `World`.

## What solution would you like?

Rename this to `act`, `execute` or `apply`.

**Comment by alice-i-cecile** [comment]
> [11:04 PM]AbleHeathen: maybe to apply to go along with apply_deferred

**Comment by neithanmo** [comment]
Hi @alice-i-cecile I want to implement this. 
looking at the code I found [this](https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/src/system/commands/mod.rs#L45-L48), so the name is not entirely intuitive for what method does. is this what needs to be changed to either "execute" or "apply":

**Comment by Themayu** [comment]
@neithanmo That's the correct trait, yes. Bear in mind that existing implementations throughout Bevy's own code will need updating to match the new name.

**Comment by neithanmo** [comment]
> @neithanmo That's the correct trait, yes. Bear in mind that existing implementations throughout Bevy's own code will need updating to match the new name.
> 
> **EDIT**: Just to weigh in on the name, I think `apply` works better than `execute`, since it falls in line with `apply_deferred` (formerly `apply_system_buffers`) from the ECS.
I thought that execute would be due to the method's documentation, so thanks for the suggestion, i will change it to  "apply" and update any other implementations/references to it throughout Bevy's code base.
i guess the crate version has to change as well to a major version, as this is a breaking one, right?

**Comment by Themayu** [comment]
> i guess the crate version has to change as well to a major version, as this is a breaking one, right?

No, that's handled by the maintainers. The next major release will be 0.11.

**Comment by Selene-Amanita** [comment]
Apply also matches https://docs.rs/bevy/latest/bevy/ecs/system/struct.SystemState.html#method.apply

I wanted to add that EntityCommand needs to be changed to but I see it's alreadydone in the PR :+1:
