### ISSUE TITLE
ECS: SystemConfig::after(BoxedSystemSet) does not work

### ISSUE THREAD

**Issue by farnoy** [bevyengine/bevy#8813]
## Bevy version

0.10.1

## What you did

I arrange some of my systems at runtime and pass around their dependencies expressed as `BoxedSystemSet`s. It's impossible to then use definitions like:

```rs
#[derive(SystemSet, Debug, Hash, PartialEq, Eq, Clone)]
pub(crate) enum MySet { One, Two, Three }

fn test_system(world: &mut World) { }

fn custom_add_systems(schedule: &mut Schedule, anchor: BoxedSystemSet) {
    schedule.add_system(test_system.after(anchor));
}
```

## What went wrong

I think it's because there's no implementation of `IntoSystemSet` for `BoxedSystemSet`? I'm not sure

## Additional information

The workaround that I think should work for now is to do 

```rs
fn custom_add_systems(schedule: &mut Schedule, anchor: BoxedSystemSet) {
    schedule.add_system(test_system).configure_set(anchor.dyn_clone().before(test_system));
}
```

**Comment by farnoy** [comment]
I think this is probably outdated and we [have](https://docs.rs/bevy_ecs/0.12.1/bevy_ecs/schedule/trait.IntoSystemConfigs.html#foreign-impls) `impl IntoSystemConfigs<()> for BoxedSystem<(), ()>` in 0.12.1

**Comment by james7132** [comment]
Tentatively closing this since we have support for system set label configurations, systems as their own labels, and `BoxedSystemSet` no longer exists.
