### ISSUE TITLE
setting `address_mode` to `AddressMode::Repeat` in `SamplerDescriptor` but it still stretches.

### ISSUE THREAD

**Issue by atornity** [bevyengine/bevy#8846]
## Bevy version
commit: 2551ccb
I have this same issue on 0.10.1

## \[Optional\] Relevant system information

- OS: Windows 11
- cargo: 1.72.0-nightly (49b6d9e17 2023-06-09)
tried on 1.70.0 (ec8a8a0ca 2023-04-25) as well, same issue

```ignore
`AdapterInfo { name: "NVIDIA GeForce RTX 3060 Ti", vendor: 4318, device: 9350, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "535.98", backend: Vulkan }`
```

## What you did

- I tried setting the `address_modes` on the `default_sampler` to `AddressMode::Repeat`.
- Spawned a sprite with a texture and a different aspect ratio than the image (16x16)

```rust
use bevy::{
    prelude::*,
    render::render_resource::{AddressMode, SamplerDescriptor},
};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(ImagePlugin {
            default_sampler: SamplerDescriptor {
                address_mode_u: AddressMode::Repeat,
                address_mode_v: AddressMode::Repeat,
                address_mode_w: AddressMode::Repeat,
                ..Default::default()
            },
        }))
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands, assets: Res<AssetServer>) {
    // camera
    commands.spawn(Camera2dBundle::default());

    // sprite
    commands.spawn(SpriteBundle {
        transform: Transform::from_xyz(0.0, 0.0, 1.0),
        texture: assets.load("textures/cross.png"),
        sprite: Sprite {
            color: Color::WHITE,
            custom_size: Some(Vec2::new(300.0, 100.0)),
            ..Default::default()
        },
        ..Default::default()
    });
}

```

## What went wrong

- I expected the texture to repeat rather than stretch.
- it stretched :(

## Additional information

pictureofitnotworking
![image](https://github.com/bevyengine/bevy/assets/29124561/a4605105-d434-48b6-a7a0-7986bdbe972e)

I have also tried setting the sampler descriptor via system but still no luck :(

**Comment by mattzque** [comment]
Hi, I don't think this is a bug.

The `address_mode_` settings on a texture sampler descriptor describe how out of bounds accesses (of UVs) should be interpreted, the default is ClampToEdge. So what that means is that when the mesh UVs are accessed with coordinates greater than 1, the texture will repeat (e.g. 0x0 -> 2x2 creates a 2 by 2 grid of the texture).

Now in the case of Sprite/SpriteBundle, by default it just creates UVs going from 0 to 1. But you can use the rect on the Sprite to affect the UVs generated, so for example:

```
use bevy::prelude::*;
use bevy::render::render_resource::{AddressMode, SamplerDescriptor};
use bevy::math::Rect;

fn main() {
    App::new()
    .add_plugins(DefaultPlugins.set(ImagePlugin {
        default_sampler: SamplerDescriptor {
            address_mode_u: AddressMode::Repeat,
            address_mode_v: AddressMode::Repeat,
            address_mode_w: AddressMode::Repeat,
            ..Default::default()
        },
    }))
    .add_systems(Startup, setup)
    .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera2dBundle::default());
    commands.spawn(SpriteBundle {
        texture: asset_server.load("branding/icon.png"),
        sprite: Sprite {
            color: Color::WHITE,
            custom_size: Some(Vec2::new(512.0, 512.0)),
            rect: Some(Rect::new(0., 0., 512.0, 512.0)),
            ..Default::default()
        },
        ..default()
    });
}
```

The icon.png has a native size of 256x256, so the logo is shown 4 times.

**Comment by atornity** [comment]
Oooo that makes sense, I'll try this tomorrow
