### ISSUE TITLE
f32 scale factor

### ISSUE THREAD

**Issue by ickshonpe** [bevyengine/bevy#8900]
## What problem does this solve or what need does it fill?

`UiScale` and `Window` `scale_factor` are represented by `f64`s but it doesn't seem we get any tangible benefits from the extra precision.

## What solution would you like?

Use `f32`s instead. 

The conversions when we multiply by scale factor aren't a major source of complexity but Bevy UI has had a lot of bugs to do with scale factor and they've been reintroduced repeatedly. Any little thing that can be done to simplify how scale factor is used and reduce the confusion is worthwhile I think.

**Comment by thmsgntz** [comment]
Hi :)
If it's okay, I would like to give it a try on this one for my first contribution!

**Comment by james7132** [comment]
This was finished in #10897, but we forgot to close it out.
