### ISSUE TITLE
2d_gizmos and 3d_gizmos are broke in WebGPU

### ISSUE THREAD

**Issue by ameknite** [bevyengine/bevy#8908]
## Bevy version

main 910f984709fb58cddbb7393c948634a2540e8d72

## Relevant system information
cargo 1.70.0 (ec8a8a0ca 2023-04-25)

SystemInfo { os: "MacOS 13.4 ", kernel: "22.5.0", cpu: "Apple M1", core_count: "8", memory: "8.0 GiB" }
AdapterInfo { name: "", vendor: 0, device: 0, device_type: Other, driver: "", driver_info: "", backend: BrowserWebGpu }

Chrome: Version 114.0.5735.133 (Official Build) (arm64)

## What you did

I run the examples 2d_gizmos and 3d_gizmos with WebGPU in Chrome
## What went wrong

The example don't show, only a black screen
![Screenshot 2023-06-20 at 19 42 50](https://github.com/bevyengine/bevy/assets/104745335/2c4c2068-0b3a-4867-b1c7-e36eec82826d)

## Additional information

```
127.0.0.1/:1 Attribute offset (12) with format VertexFormat::Float32x3 (size: 12) doesn't fit in the vertex buffer stride (12).
 - While validating attributes[1].
 - While validating buffers[0].
 - While validating vertex state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor "LineGizmo Pipeline 2D"]).
 ```

```
[Invalid RenderPipeline "LineGizmo Pipeline 2D"] is invalid.
 - While encoding [RenderPassEncoder "main_pass_2d"].SetPipeline([Invalid RenderPipeline "LineGizmo Pipeline 2D"]).
```

```
[Invalid RenderPipeline "LineGizmo Pipeline"] is invalid.
 - While encoding [RenderPassEncoder "main_transparent_pass_3d"].SetPipeline([Invalid RenderPipeline "LineGizmo Pipeline"]).
 ```

**Comment by mockersf** [comment]
Could be related to https://github.com/bevyengine/bevy/pull/8427. @devil-ira any idea?

**Comment by devil-ira** [comment]
Yes, this was introduced in #8427.
Seems this limitation is specific to metal (https://github.com/gpuweb/gpuweb/issues/693#issuecomment-610984010).
Maybe it's one of those 'works in practice' things and the validation only happens on WebGPU?

I'll try out the workarounds mentioned in https://github.com/gpuweb/gpuweb/issues/1357.
