### ISSUE TITLE
Wrapped elapsed time calculation probably needlessly complicated

### ISSUE THREAD

**Issue by nakedible** [bevyengine/bevy#8912]
Currently the wrapped version of elapsed time is calculated as such:

```rust
self.elapsed_wrapped = duration_div_rem(self.elapsed, self.wrap_period).1;

fn duration_div_rem(dividend: Duration, divisor: Duration) -> (u32, Duration) {
    // `Duration` does not have a built-in modulo operation
    let quotient = (dividend.as_nanos() / divisor.as_nanos()) as u32;
    let remainder = dividend - (quotient * divisor);
    (quotient, remainder)
}
```

However, it's kind of unrealistic that `wrap_period` would have a subsecond component (the default is 1 hour, tests use 3 seconds). And the quotient part is totally unused by this calculation. The compiler may fix all this, but it's doubtful.

If we decide that `wrap_period` needs to be an integral amount of seconds, we can simplify this to just:
```rust
self.elapsed_wrapped = Duration::new(self.elapsed.as_secs() % self.wrap_period.as_secs(), self.elapsed.subsec_nanos());
```

Adding the check that `wrap_period` indeed is integral can be added easily to `set_wrap_period`, so any previous users would be clearly notified of the change.

Probably irrelevant for performance in the big picture, but wanted to make an issue about this if anyone cares. If nobody cares, just close it, it's noise to keep it hanging around.

Also, can make a pull for the changes if desired.

## Bevy version

master, <0.11, [910f984](https://github.com/bevyengine/bevy/commit/910f984709fb58cddbb7393c948634a2540e8d72)

**Comment by alice-i-cecile** [comment]
I'd be happy to see a PR that does this and swaps to a integers-only approach.

**Comment by maniwani** [comment]
Umm, why? This won't have an impact on performance (this value normally only changes once per update).

What do we gain by imposing an arbitrary restriction here instead of allowing "any `Duration` value" like we currently do?

**Comment by nakedible** [comment]
There was a long discussion here and it was deemed that there's no point on doing just for the difference in complexity.

**Comment by alice-i-cecile** [comment]
Start of conversation: https://discord.com/channels/691052431525675048/1121600587897770034/1124399725500715178
