### ISSUE TITLE
`EventReader::iter()` is confusing as it moves the cursor of events read

### ISSUE THREAD

**Issue by olegus199** [bevyengine/bevy#8966]
## What problem does this solve or what need does it fill?

I would like to propose to consideration the following thing: usually, in Rust there is a function iter() that allows to iterate containers multiple times without consuming elements of the container. And the fact that EventReader has a function named iter() that consumes events is making me a bit confused. I'm totally agreed, that the consuming of the events is necessary while iterating them, but I have a case in which it doesn't seem to work: 
<img width="613" alt="Screenshot 2023-06-27 at 16 20 57" src="https://github.com/bevyengine/bevy/assets/128966780/e71cbb49-3c9c-4598-bcdb-0b462f722d71">
First of all I iterate dog's entities for ticking their timers (every dog has it's own timer). And in the inner cycle I iterate events, so I need to save them into the Vec in the beginning of the system.  

## What solution would you like?

Either you could rename iter() to something like iter_once (or anything else you'll prefer) to make it more noticeable that the event is consumed in this system, or you can create another iterator that won't consume the events

## What alternative(s) have you considered?

A workaround here is to create a Vec (for instance) to save events, but this Vec could theoretically allocate excess memory for events that are copied and have big size. I know, that practically it's almost impossible, but still...

## Additional context

I'm new in Rust and therefore I can be wrong, so if it's a peace of garbage, never mind :)

**Comment by alice-i-cecile** [comment]
Yeah, this is a bit confusing: it advances the iterator specific to *this* system param's view of events.

This is both not quite "drain" or "consume" like behavior, but also surprising for those who want to reuse the iterator in the same system.

In your particular case, you could add two `EventReader` system parameters to your same system, each of which will have their own tracker. Just a workaround, but hopefully helpful.

**Comment by olegus199** [comment]
Thank's a lot! I'll try it out :)
