### ISSUE TITLE
bevy fails to compile/run on musl based linux distros

### ISSUE THREAD

**Issue by lxea** [bevyengine/bevy#898]
**Bevy version**
0.3/master also fails the same way

**Operating system & version**
Alpine linux edge

**What you did**
Attempt to compile and run a bevy example on alpine linux.

**What you expected to happen**

the sample would run

**What actually happened**

The engine fails to compile when compiling cart/glsl-to-spirv

**Additional information**

The engine fails to compile as `x86_64-unknown-linux-gnu` is being used but alpine expects `x86_64-unknown-linux-musl`
If I edit the glsl-to-spirv build.rs files to use `-musl`the compilation succeeds however, it then fails to launch and exits with a segfault to the usage of the precompiled static libraries expecting glibc (as far as i can understand anyway).

Also worth mentioning, if I dont use the fast compile .cargo/config i get a huge error that ends with the log below.
```
  = note: /usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /home/alex/glsl-to-spirv/build/linux-musl/libglslang.glsltospirv.a(Constant.cpp.o): undefined reference to symbol 'acos'
          /usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /lib/libc.musl-x86_64.so.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
```

Since reporting this I've also tried building with shaderc adding conditionals for musl/linux which when running an example segfaults

**Comment by AlexKraak** [comment]
Having spent a bit of time debugging this, I changed some conditionals to make this use shaderc and it doesnt fail to compile the render crate now, it still segfaults though

It segfaults seemingly when loading rodio, and also when running a rodio example, so I'm going to spend some time looking at this now.

**Comment by jamadazi** [comment]
Yes, FYI (to anyone attempting to compile Bevy apps for any target other than the most common explicitly supported ones (x86_64 windows/linux-gnu/macos, AArch64 ios/android/macos, wasm)):

Bevy uses a temporary ugly hack for shader compilation (`bevy-glsl-to-spirv`) that makes builds on the officially-supported platforms easier by using some precompiled C/C++ binaries (to avoid the need for extra build tools). However this means that on *unsupported* platforms, bevy will fail to compile.

To use bevy on other platforms, you need to switch out `bevy-glsl-to-spirv` for `shaderc`. This is currently done in the official bevy for iOS and Arm macOS. You can just simply patch your bevy to remove the conditional selection of `shaderc` for only those platforms, to use it unconditionally. This should unblock Bevy to compile for your target, at the cost of extra build-time dependencies (`ninja`, `cmake`, `python`).

You need to remove the conditional compilation checks in the `Cargo.toml` and in `crates/bevy_render/src/shader/shader.rs`.
