### ISSUE TITLE
`bevy_ui` doesn't compile without the `bevy_text` feature

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#8984]
## Bevy version

main branch: c24520cb72f98

## What you did

```sh
cargo check --package bevy_ui --no-default-features
```

## What went wrong

Compilation error (several)

```
error[E0432]: unresolved import `crate::widget::TextFlags`
 --> crates/bevy_ui/src/node_bundles.rs:4:22
  |
4 |     widget::{Button, TextFlags, UiImageSize},
  |                      ^^^^^^^^^ no `TextFlags` in `widget`

error[E0412]: cannot find type `Without` in this scope
   --> crates/bevy_ui/src/widget/image.rs:137:22
    |
137 |         (With<Node>, Without<UiImage>),
    |                      ^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
1   + use bevy_ecs::prelude::Without;
    |
1   + use crate::Without;
    |

error[E0599]: the method `before` exists for fn item `fn(Local<'a, f64>, Query<'b, 'c, &Window, With<...>>, ..., ..., ...) {update_atlas_content_size_system}`, but its trait bounds were not satisfied
   --> crates/bevy_ui/src/lib.rs:163:54
    |
163 |             widget::update_atlas_content_size_system.before(UiSystem::Layout),
    |                                                      ^^^^^^ method cannot be called due to unsatisfied trait bounds
    |
```

## Why it's happening

`bevy_text` is marked as `optional = true` in the `bevy_ui` `Cargo.toml`. And there is several `#[cfg(feature = "bevy_text")]` that indicates it is intended to be possible to run `bevy_ui` without `bevy_text`.

When I use the `--no-default-feature`, `bevy_text` is removed as a dependency, and the feature flag "bevy_text" is also removed.

**Comment by ickshonpe** [comment]
Put in a pr a while ago #8760 I think

**Comment by nicopap** [comment]
Still doesn't fix the compilation error. There is more than a single compilation error.

**Comment by ickshonpe** [comment]
Can we get this checked for by CI? It seems like every time there is a non-trivial UI change it gets broken again.

**Comment by ickshonpe** [comment]
Can we get this checked for by CI? It seems like every time there is a non-trivial UI change it's going to get broken again.

**Comment by nicopap** [comment]
It's a fairly difficult choice. On one hand, we should make sure bevy compiles with all possible combination of feature flags, on the other hand, it's going to eat CI time like crazy.

@mockersf

**Comment by mockersf** [comment]
Compiling each crate individually without default features wouldn't add a lot, but currently there's no easy way to get a list of all crates in the workspace, so that's a bit painful to set up in CI.

A few crates are checked without default features: https://github.com/bevyengine/bevy/blob/7aa0a47607ce369c96b1ad271095a7bb47f171f8/.github/workflows/validation-jobs.yml#L162
