### ISSUE TITLE
`GamepadButtonInput` event

### ISSUE THREAD

**Issue by bravely-beep** [bevyengine/bevy#8988]
## What problem does this solve or what need does it fill?

Currently, Bevy exposes keyboard and mouse button inputs through two mechanisms:
- through the event system, via `EventReader<KeyboardInput>` and `EventReader<MouseButtonInput>`
- through the input system, via `Res<Input<KeyCode>>` and `Res<Input<MouseButton>>`

Bevy handles gamepad buttons differently; they are natively handled using continuous values for how far they're pressed down, but they also have an abstraction layer built on top to treat them as boolean buttons (via the thresholds defined with `ButtonSettings`). However, this abstraction layer only provides `Input<GamepadButton>`; there is no equivalent in the event system.

## What solution would you like?

Add the `GamepadButtonInput` type, which is emitted as an event by Bevy, and can be read from user code with `EventReader<GamepadButtonInput>`.

## What alternative(s) have you considered?

- Do nothing, and suggest that user code simply polls `Input<GamepadButton>` every frame. This would likely be less performant than a dedicated event, and would duplicate polling already performed by the engine internals. Additionally, this would be less accurate, as it would not be able to detect when multiple presses occur within a single frame.
- Do nothing, and suggest that user code only polls  `Input<GamepadButton>` when an `GamepadButtonChangedEvent` has been emitted. This could be slightly more performant than polling every frame, but would still require iterating through and discarding many irrelevant events that do not change the boolean button state.

## Additional context

This would be more performant than user code, but would be unnecessary overhead if the user does not need to use this event. Perhaps it could be feature-gated, if it's deemed to be an unacceptable performance hit?

**Comment by nicopap** [comment]
I personally like this suggestion.

The code sounds very burdensome to implement, and it is a requirement in order to handle gamepad input through events (which has benefits beyond performance). We wouldn't want each user to implement it themselves.
