### ISSUE TITLE
Rename Interaction::Click

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#8989]
## What problem does this solve or what need does it fill?

When I saw this variant, I thought that it works like in usual in UI - if I press and release the RMB over the button, then it is considered as "clicked". Also all examples check `Interaction::Click` for button pressing.
But it's not how it works! `Interaction::Click` just represents the pressed state of a button.

## What solution would you like?

Rename `Interaction::Click` into `Interaction::Pressed`. This will by much clear. No functional changes.

## Additional context

I think `Interaction` represents the state of the button and it's handy for changing the appearance.
But to check for clicking, I would add additional mechanism and I think it should be an event, not a state (an RMB press and then release over the button).

**Comment by AnthonyKalaitzis** [comment]
I don't mind giving this one a go if no one else is doing it :)

**Comment by Shatur** [comment]
@AnthonyKalaitzis do it, maybe we could get it to 0.11 since it's a simple rename.

**Comment by AnthonyKalaitzis** [comment]
@Shatur When you say `Interaction::Click`, do you mean `Interaction::Clicked`? The `Interaction` enum appears to be in `bevy_ui/src/focus.rs` and I don't see any others so just double checking that's what you mean.

**Comment by Shatur** [comment]
@AnthonyKalaitzis Yes :)
