### ISSUE TITLE
Implement hecs Query for DynamicBundle

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#9]
This would provide useful shorthand in "function systems" when there are a lot of components. Something like:

```rust
#[derive(Bundle)]
struct MyBundle {
  a: ComponentA,
  b: ComponentB
}

fn some_system(component_group: Bundle<MyBundle>) {
  println!("a: {:?}", component_group.a);
  println!("b: {:?}", component_group.b);
}
```

Ideally it could be used alongside normal queries like `(&MyComponent, Bundle<MyBundle>)`

**Comment by Moxinilian** [comment]
Fixed in #798
