### ISSUE TITLE
Canvas API

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#90]
Right now the only way to draw UI and 2D scenes is via sprites and rectangles. Bevy needs an immediate-mode drawing api capable of drawing anti-aliased curves and shapes. This can then be used to do code-driven drawing of things like rounded corners in Bevy UI, performance graphs in the editor, etc. It's very possible that we will integrate projects like [pathfinder](https://github.com/servo/pathfinder) or [lyon](https://github.com/nical/lyon) for this.

**Comment by kazimuth** [comment]
[Nannou](https://docs.rs/nannou/0.14.1/nannou/draw/index.html) has a very nice drawing API over wgpu as well.

**Comment by cart** [comment]
Fantastic. Nannou is a really cool project. "Creative coding" is a niche I regrettably havent explored enough.

**Comment by alice-i-cecile** [comment]
bevy_prototype_lyon has continued to advance nicely as the community standard for this :)

**Comment by spindlebink** [comment]
Right now a canvas API is the only thing really holding me back from adopting Bevy for a serious project. I feel like a canvas API is right at home in an ECS engine. May I recommend looking at LÖVE for inspiration? Some of LÖVE's coding style doesn't fit a strict ECS, but the API is a joy to use and feels spiritually very similar to Bevy's ergonomics.

Also, if/when canvas rendering gets added, it'd be amazing if it would include a way to render text outside of dedicated text objects, although that might be a given for the territory.

**Comment by alice-i-cecile** [comment]
Some more community progress:
- https://docs.rs/bevy_canvas/latest/bevy_canvas/ is  a nice lyon-backed canvas implementation.
- https://github.com/johanhelsing/bevy_smud creates signed-distance field (SDF) shapes with a custom shader.
- https://github.com/frewsxcv/bevy-earcutr chops up shapes (defined in a point-by-point fashion) to generate Bevy meshes.

**Comment by Nul-led** [comment]
Any progress yet im missing?

**Comment by alice-i-cecile** [comment]
There's an immediate-mode "gizmo" API now, with additional features coming in 0.11.

In addition https://docs.rs/bevy_vector_shapes/latest/bevy_vector_shapes/ is quite powerful and well reviewed.

**Comment by bushrat011899** [comment]
> There's an immediate-mode "gizmo" API now, with additional features coming in 0.11.

Out of curiosity, what extra functionality should a Bevy Canvas API offer beyond what the current Gizmo API does? Based on the original issue description, Gizmos appear to address everything, at least to my somewhat inexperienced eye.

**Comment by alice-i-cecile** [comment]
Yeah this appears to be effectively resolved with the addition of gizmos. There are always improvements to make there (and I don't think we should use them for rounded corners in UI), but this issue is no longer helpful.
