### ISSUE TITLE
WebGPU support is broken, naga_oil panics on standard shaders.

### ISSUE THREAD

**Issue by Neopallium** [bevyengine/bevy#9028]
## Bevy version

commit `889a5fb13099e0978649033a892760a5714bde13`

## What you did

Build a wasm example with WebGPU api:

```
cargo run -p build-wasm-example -- --api webgpu pbr
basic-http-server examples/wasm
```

The WebGL2 version still works.

## What went wrong

Got a panic when opening the example in chrome:
```
panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/naga_oil-0.8.0/src/derive.rs:362:23
```

## Additional information

Seems to happen with the standard PBR shaders.

**Comment by Neopallium** [comment]
The panic is in `naga_oil` here: https://github.com/bevyengine/naga_oil/blob/c4d75347889c4d439e73efac5d1c9ef44143b818/src/derive.rs#L362

**Comment by Neopallium** [comment]
I can confirm that those two commits fix the problem.  I tested it by adding:
```
[patch.crates-io]
naga = { git = "https://github.com/gfx-rs/naga.git", branch = "v0.12" }
```
to the Cargo.toml file.

**Comment by Elabajaba** [comment]
WebGPU should work now, as both `naga_oil` and `naga` have had patch releases with the requisite fixes included.

**Comment by Neopallium** [comment]
It works.  Thanks!
