### ISSUE TITLE
Add `#[repr(transparent)]` to bevy_ptr types

### ISSUE THREAD

**Issue by PROMETHIA-27** [bevyengine/bevy#9064]
## What problem does this solve or what need does it fill?

Currently, bevy pointer types are not FFI-safe because they have no layout guarantees.

## What solution would you like?

Putting the `#[repr(transparent)]` attribute on bevy_ptr types would make them FFI-safe and enable using untyped lifetime-tracked pointers at FFI boundaries, which makes catching bugs easier.

## What alternative(s) have you considered?

They could also be `#[repr(C)]`, but `#[repr(transparent)]` probably works better.
They could have no attribute added, but then they cannot be used at FFI boundaries without converting them to raw pointers and back.

**Comment by fgrust** [comment]
Hello! Im excited to make my first contrib here, and I've chosen this issue. While I'm not new to Rust, game engine development is a fresh territory for me and my hope. I want to believe this will serve as a great starting point for my journey.
