### ISSUE TITLE
Transform propagation after adding `GlobalTransform`

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#9075]
## Bevy version

v0.10

## What you did

I added an entity that have only `Transform` to hierarchy. And on the next update I added `GlobalTransform`.

## What went wrong

I would expect `GlobalTransform` to be updated with `Transform`. But it's not. I think we should look not only for `Transform` change, but also for `GlobalTransform` add.

**Comment by SkiFire13** [comment]
Is there a reason you're not adding the `GlobalTransform` together with the `Transform`?

**Comment by Shatur** [comment]
Because of deserialization. I serialize  and deserialze only necessary components and automatically insert complement ones like `GlobalTransform`.

**Comment by Shatur** [comment]
Opened #9081.
