### ISSUE TITLE
const Style build failed in Bevy 0.11.0

### ISSUE THREAD

**Issue by Dumpinground** [bevyengine/bevy#9095]
## Bevy version

0.11.0

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
  1.70.0
- the operating system or browser used, including its version
  Windows 10 19045.3086 (22H2)

## What you did

I manage to migrate [the project](https://github.com/Dumpinground/bevy_try) from 0.10.1 to 0.11

## What went wrong

It could not compile as the const Style uses `..Style::DEFAULT`
The error is `the destructor for this type cannot be evaluated in constants`

with command `cargo b --example bevy-ball-game`

## Additional information

- screenshots
![image](https://github.com/bevyengine/bevy/assets/56429201/ca862840-c88b-4740-b4b3-70090b8e3c04)

**Comment by Selene-Amanita** [comment]
I think this is because in `RepeatedGridTrack` (fields `grid_template_rows` and `grid_template_columns` of `Style`) ther is a `SmallVec` from the crate `smallvec` which implements `Drop` and cannot be const time.

Using the struct literal update syntax crates the struct, copies from it, and destroys it, I think, which triggers this error when trying to do that in const time.

For now you can enumerate all the fields I guess :(

**Comment by cart** [comment]
Hmm yeah pretty sure that was an oversight. "Const style" was something we added a lot of stuff to support explicitly (ex: Style::DEFAULT and co). Not sure theres a good solve to this other than splitting out the non-const fields. But then if Style is no longer a "full" style, idk if the value is there anymore. It feels like it would compromise the integrity of the design.

This will require some thought. I'm sure this won't be the last non-const style type.

**Comment by codeWonderland** [comment]
It seems like this should be navigable via changing Style constants to functions. IE:

old:
```rust
pub const BUTTON_STYLE: Style = Style {
    justify_content: JustifyContent::Center,
    align_items: AlignItems::Center,
    width: Val::Px(200.0),
    height: Val::Px(80.0),
    ..Style::DEFAULT
}
```

new:
```rust
pub fn get_button_style() -> Style {
    Style {
        justify_content: JustifyContent::Center,
        align_items: AlignItems::Center,
        width: Val::Px(200.0),
        height: Val::Px(80.0),
        ..Style::DEFAULT
    }
}
```

**Comment by Dumpinground** [comment]
> It seems like this should be navigable via changing Style constants to functions. IE:
> 
> old:
> 
> ```rust
> pub const BUTTON_STYLE: Style = Style {
>     justify_content: JustifyContent::Center,
>     align_items: AlignItems::Center,
>     width: Val::Px(200.0),
>     height: Val::Px(80.0),
>     ..Style::DEFAULT
> }
> ```
> 
> new:
> 
> ```rust
> pub fn get_button_style() -> Style {
>     Style {
>         justify_content: JustifyContent::Center,
>         align_items: AlignItems::Center,
>         width: Val::Px(200.0),
>         height: Val::Px(80.0),
>         ..Style::DEFAULT
>     }
> }
> ```

Yes. I have already updated those constants into functions. It runs.

**Comment by Selene-Amanita** [comment]
> If there's no good fix, maybe this could be mentioned in the style documentation.

I didn't think of that! It should probably be mentioned in the migration guide at least

**Comment by doonv** [comment]
I have created a macro which allows you to create const styles using a method very similar to the spread syntax:
```rs
macro_rules! style {
    {$( $name:ident: $val:expr ),*$(,)?} => {
        {
            let mut style = Style::DEFAULT;
            $(
                style.$name = $val;
            )*
            style
        }
    };
    {$( $name:ident: $val:expr ),*,..$default:expr} => {
        {
            let mut style = $default;
            $(
                style.$name = $val;
            )*
            style
        }
    };
    {..$default:expr} => {
        $default
    };
}
```

Which can be used like this:
```rs 
pub const FILL: Style = style! {
    width: Val::Percent(100.0),
    height: Val::Percent(100.0),
};

pub const HOTBAR_CONTAINER_STYLE: Style = style! {
    justify_content: JustifyContent::Center,
    align_items: AlignItems::End,
    ..FILL
};
```

**Comment by Dumpinground** [comment]
As it has alternatives, there seems no need to bring the old const feature back.
Thanks for responding.
