### ISSUE TITLE
Rendering silently does not work without "tonemapping_luts" feature

### ISSUE THREAD

**Issue by NotAFile** [bevyengine/bevy#9098]
## Bevy version

v0.11.0

## \[Optional\] Relevant system information

```ignore
`AdapterInfo { name: "AMD Radeon RX 470 Graphics (RADV POLARIS10)", vendor: 4098, device: 26591, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 23.1.3", backend: Vulkan }`
```
## What you did

Run the "3d_scene.rs" example under 0.11.0 without the "tonemapping_luts" feature enabled 

## What went wrong

The materials display as FF00FF with no error, log, crash, or other hint as to indicate what is going wrong.

![image](https://github.com/bevyengine/bevy/assets/5447747/1a670c84-5730-4617-bb07-869e43748e67)

## Additional information

Presumably with the switch to TonyMcMapface, this feature is now required by default, exposing some untested error paths.

**Comment by mockersf** [comment]
fixed by https://github.com/bevyengine/bevy/pull/9073

**Comment by NotAFile** [comment]
Even when that is fixed, having some sort of error when not being able to load tonemaps might be a good idea?

**Comment by JMS55** [comment]
Fixed by https://github.com/bevyengine/bevy/pull/10253
