### ISSUE TITLE
Mention new audio playback modes in 0.11 migration guide

### ISSUE THREAD

**Issue by tbillington** [bevyengine/bevy#9108]
With the switch to ECS based audio playback, users must now spawn entities to play once off sound effects.

A key usability feature of this new design is the ability for these spawned entities to clean themselves up via the `PlaybackMode`: `Despawn` and `Remove`.

Unfortunately these variants aren't mentioned in the 0.11 blog post or the migration guide. I was about to write my own cleanup marker code & component before someone helpfully mentioned them to me in the discord.

https://docs.rs/bevy_audio/latest/bevy_audio/enum.PlaybackMode.html

**Comment by alice-i-cecile** [comment]
Note that the PR to fix this will have to be submitted here: https://github.com/bevyengine/bevy-website
