### ISSUE TITLE
Enbed a webkit view

### ISSUE THREAD

**Issue by johan-smits** [bevyengine/bevy#9109]
## What problem does this solve or what need does it fill?

We want to show a live website

## What solution would you like?

Be able to embed a webkit window

## What alternative(s) have you considered?

None

**Comment by NiklasEi** [comment]
There is a third party plugin that allows embedding webviews, but it seems quite outdated: https://github.com/blaind/bevy_webview

**Comment by james7132** [comment]
Integrating a full browser rendering stack into the core engine is almost 100% guaranteed to be out of scope, both in terms of general usability, and also maintenance burden. As mentioned prior, this is an excellent opportunity for a third party plugin. Either way, closing this out as not planned.

**Comment by mockersf** [comment]
https://github.com/tauri-apps/wry would probably be a good building block for a third party web view
