### ISSUE TITLE
`ambiguous_with` breaks run conditions

### ISSUE THREAD

**Issue by NiseVoid** [bevyengine/bevy#9114]
## Bevy version

0.11

## What you did

I migrated my project to bevy 0.11 and noticed a system in Last started misbehaving despite having the configuration for the set it was in in all schedules.

This is the most simplified version of my code that still produces the bug
```rust
#[derive(States, Default, Clone, PartialEq, Eq, Debug, Hash)]
pub enum ConnectionState {
    #[default]
    Menu,
    Connecting,
    Connected,
}

#[derive(SystemSet, Clone, PartialEq, Eq, Debug, Hash)]
pub enum ConnectionSet {
    Menu,
    Connecting,
    Connected,
}

fn main() {
    fn configure_connecting_sets(schedule: &mut Schedule) {
        schedule.configure_set(ConnectionSet::Connected.run_if(in_state(ConnectionState::Connected)));
    }

    let mut app = App::new();

    app.add_state::<ConnectionState>();

    for label in app.world.resource::<bevy::app::MainScheduleOrder>().labels.to_vec() {
        println!("{:?}", label);
        app.edit_schedule(label.dyn_clone(), configure_connecting_sets);
    }

    app.
        .add_plugins(MinimalPlugins.build().disable::<bevy::app::ScheduleRunnerPlugin>())
        .add_plugins(bevy::asset::AssetPlugin::default())
        .add_plugins(bevy::a11y::AccessibilityPlugin)
        .add_plugins(bevy::input::InputPlugin::default())
        .add_plugins(bevy::window::WindowPlugin::default())
        .add_plugins(bevy::winit::WinitPlugin::default())

        .add_systems(Update, (|| {println!("This should not run in Update");}).in_set(ConnectionSet::Connected))
        .add_systems(Last, (|| {println!("This should not run in Last");}).in_set(ConnectionSet::Connected))

        .run();
}
```

## What went wrong

The above code should output:
```
First
PreUpdate
StateTransition
RunFixedUpdateLoop
Update
PostUpdate
Last
```
and then stop.

Instead, if the `WinitPlugin` is enabled it also outputs this every frame:
```
This should not run in Last
````

Since the runcondition of the set that system is in is not met, it should not be printing this. Especially considering it only happens in Last while Update works as expected. If the `WinitPlugin` is disabled and the `ScheduleRunnerPlugin` is turned back on this problem is gone.

**Comment by devil-ira** [comment]
Removing `.ambiguous_with(exit_on_all_closed)` from the following line fixes this, somehow.
https://github.com/bevyengine/bevy/blob/7c3131a76136f1f05f6380cc3ca291543d4b891b/crates/bevy_winit/src/lib.rs#L96
