### ISSUE TITLE
Emit event when scene is ready

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#9115]
## What problem does this solve or what need does it fill?

Scenes spawned with delay and in order to check if scene is spawned we use [SceneSpawner::instance_is_ready](https://docs.rs/bevy/latest/bevy/scene/struct.SceneSpawner.html#method.instance_is_ready). But it's not very convenient because you can't actually react on spawning.

## What solution would you like?

Introduce `ReadyScene` component that inserted after scene spawning.

## What alternative(s) have you considered?

Events, but marker component is more flexible because we also be able to filter loaded scenes in queries.

**Comment by Olle-Lukowski** [comment]
Hey, I want to get into contributing to Bevy and I think this would be a good place for me to start, so if I can try working on this that would be awesome!

**Comment by Shatur** [comment]
> Should this component be applied for both types of spawning?

Yes, I think so.

**Comment by james7132** [comment]
Could we make this an event instead of a component? Seems more appropriate than a persistent component that forces more archetype fragmentation.

**Comment by Shatur** [comment]
> Could we make this an event instead of a component?

This is what I outlined in "alternatives". But I think "valid scene" is a persistent state. And you will be able to iterate over all valid scenes + easier to get components of such scene via query.

**Comment by mockersf** [comment]
it's possible to invalidate a scene by changing the handle, so it would make handling an additional component needs to be kept in sync with that. I would much prefer an event as a one time thing

**Comment by Shatur** [comment]
Yes, I thought that we will keep the component in sync...

But I see your point, let's go with event then.

**Comment by Shatur** [comment]
> But I see your point, let's go with event then.

On second thought, how we will check if scene was "just loaded" to emit the event? With component approach we can use `Without` for iteration.

**Comment by Shatur** [comment]
> On second thought, how we will check if scene was "just loaded" to emit the event?

I have an idea, we can emit the event when we insert the scene handle to spawned map.
@Olle-Lukowski if you planning to work on it, please switch your PR to events.

**Comment by Shatur** [comment]
Opened #9313.
