### ISSUE TITLE
Panic whilst loading ktx2 file

### ISSUE THREAD

**Issue by 66OJ66** [bevyengine/bevy#9121]
## Bevy version

v0.11.0

## \[Optional\] Relevant system information

Rust 1.70
OS: openSUSE Tumbleweed

```ignore
`AdapterInfo { name: "AMD Radeon RX 6600 XT (RADV NAVI23)", vendor: 4098, device: 29695, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 23.1.2", backend: Vulkan }`
```

## What went wrong

I attempted to load a `ktx2` file which led to the following panic.

```
2023-07-11T22:23:24.829163Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (5)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Texture format Astc { block: B4x4, channel: UnormSrgb } can't be used due to missing features.
    Features Features(TEXTURE_COMPRESSION_ASTC) are required but not enabled on the device

', /home/_/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.2/src/backend/direct.rs:3019:5
```

This file loaded without issue in Bevy v0.10.1 (and earlier) with these features enabled:

```
[dependencies]
bevy = { version = "0.10.1", features = ["ktx2", "zstd", "basis-universal"]}
```

## Additional information

I've uploaded a basic example here: https://github.com/66OJ66/basis_universal_error_repo

The original PNG file was sourced from here: https://ambientcg.com/view?id=Ground037

I converted it to ktx2 using toktx (https://github.khronos.org/KTX-Software/ktxtools/toktx.html).
The exact command was:
`toktx --encode uastc --zcmp 22 --genmipmap --uastc_rdo_l 0.5 {output} {input.png}`

**Comment by Elabajaba** [comment]
I don't know how this worked previously, but the only desktop/laptop hardware that supports ASTC was Intel iGPUs, and they dropped support for it recently.

**Comment by 66OJ66** [comment]
> edit2: It seems like https://github.com/bevyengine/bevy/pull/8336 is when the crashing started.

Yeah, I checked the original PR where compressed texture support was added, and this comment mentioned an potential issue with WebGPU:  https://github.com/bevyengine/bevy/pull/3884#issuecomment-1059886666

**Comment by 66OJ66** [comment]
After investigating a bit more, this is caused by a combination of 2 issues:

1) If the `RenderDevice` resource is missing when the `ImageTextureLoader` is initialised, it defaults to supporting all compressed textures (line 85)
https://github.com/bevyengine/bevy/blob/05a35f6f484862fabd8225fcce2157d7e31c796c/crates/bevy_render/src/texture/image_texture_loader.rs#L80-L91

2) The `RenderPlugin` and `ImagePlugin` are added sequentially, but in https://github.com/bevyengine/bevy/pull/8336 the renderer initialisation was made async. As a result, now at the time of `ImagePlugin` initialisation the `RenderDevice` resource doesn't exist yet, triggering the fallback condition above
https://github.com/bevyengine/bevy/blob/05a35f6f484862fabd8225fcce2157d7e31c796c/crates/bevy_internal/src/default_plugins.rs#L76-L82

So, fixing this should just be a case of delaying the `ImageTextureLoader` initalisation within `ImagePlugin` - I'll prepare a PR for this shortly
