### ISSUE TITLE
Scene from glb file did not rendered when compiled to WASM in bevy 0.11

### ISSUE THREAD

**Issue by volodalexey** [bevyengine/bevy#9137]
## Bevy version

0.11

## What you did

Once I updated [my simple game](https://github.com/volodalexey/simple-bevy-wasm-ball-game) to bevy `0.11` I do not see scenes/meshes/models from `gltf/glb` file in WASM. I still hear the sound and see 2d menu.

Everything works in `0.11` when compiled natively on my Linux Mint 21.1 Cinnamon.

## Additional information

Everything worked in WASM in bevy `0.10`. I haven't changed anything except essential migration updates.

[DEMO link](https://volodalexey.github.io/simple-bevy-wasm-ball-game/) compiled to WASM with bevy 0.11 - this bug is reproduceable on all my devices in browsers.

The same game in bevy `0.10` can be compiled from this [commit](https://github.com/volodalexey/simple-bevy-wasm-ball-game/tree/7304cee84cc69a228104acc7b41739bc2d931b0d).

WebInspector shows that scene file is loaded as before. The only one new message I see is following:
```
WARN /home/lex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_pbr-0.11.0/src/ssao/mod.rs:98 ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
```

Scene file created in Blender is also [pretty simple](https://github.com/volodalexey/simple-bevy-wasm-ball-game/blob/main/blend/models/scene.blend).

I assume [that new SSAO](https://bevyengine.org/news/bevy-0-11/#screen-space-ambient-occlusion) is enabled some-how, however it should not, because I am using only [default plugins](https://github.com/volodalexey/simple-bevy-wasm-ball-game/blob/main/src/window_camera/mod.rs#L17) or maybe the problem lies somewhere else...

**Comment by volodalexey** [comment]
Investigated some more.
In Blender my ball looks like this:
![2023-07-14_21-37](https://github.com/bevyengine/bevy/assets/8973562/07a9ab57-953c-4496-94c1-212a1444a3c8)

Current approach using gltf scene does not work in WASM:
```rust
SceneBundle {
  scene: model_assets.player.clone_weak(),
  ..default()
},
```
Instead of using gltf scene with this ball I tried to use only mesh and material from gltf:
```rust
let gltf = assets_gltf.get(&my.0).unwrap();
let ball_meshes = assets_gltfmesh
        .get(&gltf.named_meshes["Icosphere.002"])
        .unwrap();

PbrBundle {
  mesh: ball_meshes.primitives[0].mesh.clone(),
  material: model_assets.player_material.clone(),
  ..Default::default()
}
```
When run natively I still see my ball:
![2023-07-14_21-48](https://github.com/bevyengine/bevy/assets/8973562/5ffaba2a-a044-4bf5-b20d-099707f2296d)

When compile to WASM I can see finally the ball (at least), however material is broken:
![2023-07-14_21-48_1](https://github.com/bevyengine/bevy/assets/8973562/7d275283-6291-47f6-8b38-8f69b147a956)

**Comment by nicopap** [comment]
Looks like #9098. Have you tried enabling ktx2, tonemapping_luts, and zstd features?

**Comment by volodalexey** [comment]
Tested with `bevy = { version = "0.11.0", features = ["tonemapping_luts", "tonemapping_luts", "zstd"]}` - I still see the empty scene when using the whole `glb`.
When using only mesh and material from gltf - I see red ball as mentioned.

**Comment by mockersf** [comment]
the `run_if` here: https://github.com/volodalexey/simple-bevy-wasm-ball-game/blob/main/src/game/models/mod.rs#L23 doesn't work like you think. it runs the system only on the frame the resource is added, which is not the same as the frame the gltf model is finished loading. if you remove the `run_if` condition, it should work.

**Comment by volodalexey** [comment]
Thanks! I was pretty sure that this is due to migration to `0.11`.  I also didn't catch this while running natively, brobably because of instant file load.
