### ISSUE TITLE
No text visible when running example files builds from file system

### ISSUE THREAD

**Issue by Jupp56** [bevyengine/bevy#915]
**Bevy version**

1e9a0544bdaf2794664b71d3567600e786eefd10

**Operating system & version**

Windows 10 1909 18363.1198

**What you did**

Run a bevy example with text directly from the file rather than via cargo run. So I tried ```cargo build --example text``` and also ```cargo build --example text --release``` and ran the resulting file manually

**What you expected to happen**

I see text.

**What actually happened**

I do in fact not see any text. 

**Additional information**
When using ```cargo run --example text```, I do see the fps counter.
No error in logs. This might have to do with other issues regarding text rendering.
In the logs, it says ```Running target\debug\examples\text.exe```. I copypasted that path, so it really IS the right file.

Am I missing something? AFAIK this should not happen, but I am not that experienced in Rust.

Why did I even try that?
I modified an example to try something, and was not inclined to first fix the errors resulting out of the difference between bevy`s master branch and the older crates.io version.

**Comment by mockersf** [comment]
The issue is about assets discovery.

When running with cargo, it looks for the `assets` folder next to the `Cargo.toml` file.
When running the binary directly, it looks for the `assets` folder next to the binary itself.

Either copy `target\debug\examples\text.exe` as the root of the project, or `assets` to `target\debug\examples\` and it should work

**Comment by Jupp56** [comment]
I am now a certified stupid moron and sincerely apologize for stealing valuable time. 
I did for some obscure reason not see the error message about that in the console yesterday. Today, I see it clear as day.
Thank you for your help.
