### ISSUE TITLE
`bevy_window::PresentMode`: The documentation for the `AutoVsync` and `AutoNoVsync` variants causes confusion.

### ISSUE THREAD

**Issue by LikeLakers2** [bevyengine/bevy#9151]
Hi again! I was browsing the documentation, and noticed that two of the variants of `bevy_window::PresentMode` have slightly confusing documentation.

First off, the `AutoVsync` variant on `bevy_window::PresentMode` mentions something about `FifoRelaxed`. My intuition says that this is meant to reference `Mailbox`, but without testing I would not know either way.

And second off, in the `AutoNoVsync` variant, says "Chooses Immediate -> Mailbox -> Fifo (on web)". The "(on web)" causes some level of confusion, as I'm unsure what it's meant to mean. Does that mean that Fifo is only considered when on the web? Or does it mean something else? In any case, separating the "(on web)" part out into its own sentence (i.e. "Fifo is only considered when running on the web.") may be a good idea.

Thanks for your hard work, whoever responds to this!

**Comment by VitalyAnkh** [comment]
How about just adding the `FifoRelaxed`?

**Comment by LikeLakers2** [comment]
> How about just adding the `FifoRelaxed`?

That would work for one of my issues. However, it doesn't fix the other issue - the confusing "(on web)" descriptor on the `AutoNoVsync` variant.

Would that be something I report to `wgpu`'s repo?

**Comment by VitalyAnkh** [comment]
I also found "on web" confusing in https://wgpu.rs/doc/wgpu/enum.PresentMode.html#variant.AutoNoVsync. I think it's great to report this to wgpu and improve the documentation there, then bevy updates the doc back.
