### ISSUE TITLE
`GizmoPlugin`: AABBs are rendered with one frame lag

### ISSUE THREAD

**Issue by LeshaInc** [bevyengine/bevy#9156]
## Bevy version

0.11.0

## What went wrong

AABBs are rendered with one frame lag, which is noticeable when objects are moving.

## Additional information

`GizmoPlugin` is not configuring `draw_aabb` and `draw_all_aabbs` systems properly. They read `GlobalTransform` and thus should run after `TransformSystem::TransformPropagate`

**Comment by wpederzoli** [comment]
@LeshaInc @alice-i-cecile @Selene-Amanita  I pushed a change for this issue but I see some CI jobs were cancelled and I am not able to re-run them. Please let me know if I'm missing something

**Comment by alice-i-cecile** [comment]
Nothing on your end there: I've rerun them for you.
