### ISSUE TITLE
Lift `Send` requirement in wasm builds

### ISSUE THREAD

**Issue by extrawurst** [bevyengine/bevy#9157]
## What problem does this solve or what need does it fill?

Right now there is a requirement for a lot of things to be `Send` even in single-threaded targets like wasm: e.g `Plugin` and `Resource`. Would be great to lift that in wasm targets.

## What solution would you like?

Do not require things to be `Send`

## What alternative(s) have you considered?

-

## Additional context

This blocks being able to use `bevy_tokio_tasks` for more stuff on wasm: see https://github.com/EkardNT/bevy-tokio-tasks/issues/18#issuecomment-1636076278

**Comment by konsti219** [comment]
Wasm is not single-threaded. You can create multi-threaded wasm applications that run in browsers today. 

Afaik bevy does not currently make use of this but keeping it as a future option without a breaking change is the way I personally would go.

**Comment by james7132** [comment]
Please see #4078 for more information. We eventually want to support full use of Web Workers in all WASM targets, but there are fundamental limitations that we may need to find a workaround for. Knowing this, conditionally lifting `Send` constraints, where relevant, seems shortsighted.

**Comment by james7132** [comment]
With the work in #12205, it's pretty apparent that any `!Send` component or resource on wasm can be wrapped in [`send_wrapper`](https://docs.rs/send_wrapper/latest/send_wrapper/) or `bevy_utils::SyncCell` to achieve Send + Sync required for Resources or Components. If the actual environment is truly single threaded, both should be a non-issue to deal with. Closing this out for now.
