### ISSUE TITLE
KTX2 And Related Features: Doc Issue or Bug

### ISSUE THREAD

**Issue by rs017991** [bevyengine/bevy#9179]
## Unclear if this is a bug or a documentation issue

Provide a link to the documentation and describe how it could be improved. In what ways is it incomplete, incorrect, or misleading?
https://github.com/bevyengine/bevy/blob/a30da0001ea3479fda32ac286e1a6647c791e5c1/docs/cargo_features.md

When trimming down Bevy's feature flags to only those I actually need, I hit an odd snag with these three:
|feature name|description|
|-|-|
|ktx2|KTX2 compressed texture support|
|tonemapping_luts|Include tonemapping Look Up Tables KTX2 files|
|zstd|For KTX2 supercompression|

As written, it sounds like the `ktx2` feature adds support for a specific file format, and the other two just add some vague goodies on top of that.

Never even heard of a `.ktx2` file, so I'm definitely not using that... I figured that I could nix all three of them.
I was wrong; after removing those features, all of my textured entities turned pink.

The plot thickened when I tried to zero in on which of the features was the problem.
The following are the results of each combination:
* The only combination that actually works is when all three features are enabled.
* These combinations all result in textures turning pink:
  * `[] # (all omitted)`
  * `["ktx2"]`
  * `["zstd"]`
  * `["ktx2","zstd"]`
* These combinations all result in **runtime panic** at startup:
  * `["tonemapping_luts"]`
  * `["tonemapping_luts","ktx2"]`
  * `["tonemapping_luts","zstd"]`
<details><summary><i>for reference, these are the other features I had enabled at the time of the experiments (click to show)</i></summary>

```
["animation","bevy_asset","bevy_winit","bevy_core_pipeline","bevy_pbr","bevy_render","bevy_sprite","bevy_text","bevy_ui","multi-threaded","png","bevy_gizmos"]
```
</details>

The panics were particularly surprising; if both `ktx2` and `zstd` are required for `tonemapping_luts` to not crash, then it seems like they ought to be automatically activated when `tonemapping_luts` is.

Similarly, if all three are necessary for correct functioning of rendering within Bevy, then they ought be attached to the respective features.

In any case, there are clearly some highly-consequential _(and likely more subtle than I was able to deduce above)_ inter-dependencies that are not being represented in the doc.

**Comment by nicopap** [comment]
This is a known issue. I opened a discussion (#9100), A PR is open at #9073, feel free to drop a review so that it gets merged and fixed for everyone.

**Comment by rs017991** [comment]
I don't see how I missed that when I was digging around, sorry for the noise.

I'd say Let's close this one in favour of updating the documentation as part of the PR, unless you (as implied by your tagging updates) are interested in tracking the crashes here?

**Comment by JMS55** [comment]
Fixed by https://github.com/bevyengine/bevy/pull/10253
