### ISSUE TITLE
Error:canvas context is not a GPUCanvasContext

### ISSUE THREAD

**Issue by shenjiangqiu** [bevyengine/bevy#9189]
## Bevy version

0.11.0

## What you did

compile an example using webgpu backend in bevy repo
```
cargo run -p build-wasm-example -- --api webgpu load_gltf
```
and deploy the server:
```
python3 -m http.server 8081
```

## What went wrong

the browser throws an error:
```
canvas context is not a GPUCanvasContext
```

**Comment by mockersf** [comment]
Which browser are you using? It looks like it doesn't support webgpu

**Comment by shenjiangqiu** [comment]
I'm using chrome 114, and I can successfully run the Bevy examples in https://bevyengine.org/examples-webgpu/

**Comment by mockersf** [comment]
then I guess there's some issue with the web server you're using? some people have reported issues with the built in python server missing mime types, can you try another? also, make sure you're serving the `examples/wasm` from the repo, not the root

**Comment by shenjiangqiu** [comment]
Yes! I use several other HTTP servers which also failed, but when I use wasm-server-runner, it succeeds! I checked the response header and I didn't find any special headers.
