### ISSUE TITLE
In the `keyboard_input_events` example, does the `EventReader<KeyboardInput>` need to be `mut` since we're only reading from it?

### ISSUE THREAD

**Issue by DjebbZ** [bevyengine/bevy#9198]
https://github.com/bevyengine/bevy/blob/8ba9571eedada4f3ff43cdf1402670b7fe7c280d/examples/input/keyboard_input_events.rs#L13

**Comment by RCoder01** [comment]
`keyboard_input_events.iter()` requires `&mut self`.

I believe this is because events track when they are read to ensure the same event is never read twice.

**Comment by DjebbZ** [comment]
Makes sense. Thanks for the quick answer!

Closing.
