### ISSUE TITLE
Vec4 should impl Property

### ISSUE THREAD

**Issue by lassade** [bevyengine/bevy#921]
**Bevy version**
commt 01ba7c44255059f833c2b90d3d6b7ac7e9c025ca

**What you did**
Tried to look for a `Vec4` attribute, but it doesn't impl the Property trait

**Additional information**
It's useful and fairly easy to add

**Comment by cart** [comment]
Good call. I'm wrapping up a `bevy_property` crate rewrite now. I'll include a Vec4 implementation there.

**Comment by cart** [comment]
Resolved by #926
