### ISSUE TITLE
Regression in binding_array after update to 0.11.0

### ISSUE THREAD

**Issue by trixnz** [bevyengine/bevy#9221]
## Bevy version

0.11.0

## Relevant system information
OS: `NixOS 23.11.20230719.7f256d7 (Tapir)`
```ignore
AdapterInfo { name: "AMD Radeon RX 6800 XT (RADV NAVI21)", vendor: 4098, device: 29631, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 23.1.3", backend: Vulkan } 
```

## What you did

I'm using `binding_array<texture_2d<f32>>` in my shaders.

## What went wrong

When upgrading from `0.10.0` to `0.11.0`, I started experiencing weird artifacts in my textures.

## Additional information

While investigating, I decided to sanity check myself and make sure the [texture_binding_array](https://github.com/bevyengine/bevy/blob/main/examples/shader/texture_binding_array.rs) example worked. It worked great on `0.10.0`, but had issues on `0.11.0`, as shown below:

![image](https://github.com/bevyengine/bevy/assets/2995953/382f23fe-d069-4453-bfa8-9bf01057b413)

*Left: 0.10.0 - Right: 0.11.0*

Bisecting the commits revealed the culprit as being the upgrade to [wgpu](https://github.com/gfx-rs/wgpu) `0.16.0`: https://github.com/bevyengine/bevy/commit/4d54ce14aaee8d7432380df37c41c03c28594b27.

Running the [texture_binding_array](https://github.com/bevyengine/bevy/blob/main/examples/shader/texture_binding_array.rs) example works great on the commit prior (https://github.com/bevyengine/bevy/commit/75130bd5ecfe58693b6a6777fd5cee04b6a34489), and after backporting my project and dependencies back to that commit, my texture artifacts also disappeared.

**Comment by mockersf** [comment]
I can't reproduce on macOS / Metal, the example look like the left cube for me

**Comment by trixnz** [comment]
I'm closing this, I've bisected all the way up to naga as being the problem child. Continuing in [#2408](https://github.com/gfx-rs/naga/issues/2408)
