### ISSUE TITLE
Bloom is only white

### ISSUE THREAD

**Issue by valaphee** [bevyengine/bevy#9235]
## Bevy version

[6093385b](https://github.com/bevyengine/bevy/tree/6093385b31851bc0758f38d46125c8446d0d9800)

## \[Optional\] Relevant system information

```ignore
AdapterInfo { name: "AMD Radeon RX 6900 XT", vendor: 4098, device: 29631, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "23.7.1 (AMD proprietary shader compiler)", backend: Vulkan }
SystemInfo { os: "Windows 11 Pro N", kernel: "22621", cpu: "AMD Ryzen 9 3900X 12-Core Processor", core_count: "12", memory: "63.9 GiB" }
```

## What you did

Clone and run the bloom_2d and bloom_3d example.

## What went wrong

Bloom is shown as white, might be a regression, as the WebGL2 example works on the Bevy website as expected but newest git commit, with either Vulkan or Dx12 doesn't.

## Additional information

![Screenshot 2023-07-21 221057](https://github.com/bevyengine/bevy/assets/32491319/f1ed2ef0-1bb7-4f62-8489-6fc83483400d)

**Comment by rparrett** [comment]
For anyone else searching for the same issue, this is being tracked here: #9234
