### ISSUE TITLE
Deprecate `configure_set` & make `configure_sets` work for single params.

### ISSUE THREAD

**Issue by iiYese** [bevyengine/bevy#9244]
## Bevy version
0.11

## What you did
Tried to use `.configure_sets` with a single system set parameter.

## What went wrong
Received a compile error. It seems `configure_set` was not deprecated and `configure_sets` was not changed to support single item calls like other APIs in this family for `0.11`.

**Comment by urben1680** [comment]
Worth noting that `confiture_set` exists both for `App` and `Schedule`.
