### ISSUE TITLE
Replace `MESH_BINDGROUP_1` with a `ShaderDefVal`

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#9256]
Using `MESH_BINDGROUP_1` as a define results duplicate code. And sometimes nested `#ifdef` in bevy shader code.

```c++
#ifdef MESH_BINDGROUP_1
@group(1) @binding(0)
var<storage> mesh: array<Mesh>;
#else // MESH_BINDGROUP_1
@group(2) @binding(0)
var<storage> mesh: array<Mesh>;
#endif // MESH_BINDGROUP_1
```

Duplicate code has been a source of programming bumps when developing rendering features. We should aim to reduce it.

## What solution would you like?

Use a `ShaderDefVal` instead of a define for `MESH_BINDGROUP`.

The previous code would become:

```c++
@group(#{MESH_BINDGROUP}) @binding(0)
var<storage> mesh: array<Mesh>;
```

**Comment by JMS55** [comment]
I use the same pattern in bevy_solari, I'm in favor :)

**Comment by robtfm** [comment]
I didn’t do this originally because I didn’t want to force every pipeline author to include a def which would 95% of the time be the same thing (i.e. 2) … 
As long as we have 2 as the default for when it’s not defined, it sounds good.

**Comment by JMS55** [comment]
MESH_BIND_GROUP_1 was removed https://github.com/bevyengine/bevy/pull/10485
