### ISSUE TITLE
EnvironmentMap modulation

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#9268]
## What problem does this solve or what need does it fill?

I'd like to be able to simulate day / night cycles in my game. Unfortunately this is hard to do when using environment maps because the intensity of the map is fixed, so the daytime sky is at full brightness even in the middle of the night.

## What solution would you like?

I'd like to be able to set a modulation intensity for an environment map. Note that three.js has this feature (but only on a per-material basis - I want it to be global).

Ideally, I would use two environment maps, one representing the daytime sky and one representing the nighttime. At noon, the intensity of the daytime env map would be one, and the intensity of the night time map would be 0. The opposite would be true at midnight. The intensity of each map would be interpolated based on the diurnal cycle.

Alternatively, if it is only possible to have a single env map, then I would just have one map for the daytime, and no map for the nighttime.

## What alternative(s) have you considered?

Well, one solution is to use ambient light (which can be modulated) instead of environment maps, but you lose a lot in scene quality especially for reflective materials. Alternatively, one could have a whole bunch of environment maps and switch between them, but this would consume a lot of memory.

## Additional context

There's been a discussion on the three.js issue tracker about adding global backround intensity for environment maps. Although the idea is generally favorable, the discussion is stalled because of concerns about backwards incompatibility with the existing per-material intensity setting. Since Bevy doesn't have this feature, backwards compatibility is not a concern.

**Comment by alice-i-cecile** [comment]
Seems like a sensible request: feel free to make a PR!

**Comment by JMS55** [comment]
I'm in favor of adding this. The only part that needs discussion is how are we going to specify the "strength"?

DirectionalLights use lux, and Point/Spot Lights use lumens (although the docs suck, that's a different issue). 

We could specify the EnvironmentMapLight as a simple multiplier, or in one of these units, or as an Ev100 exposure, or something else.

The recent God of War: Ragnarok presentation has some info on how they manage physical lighting values https://sms.playstation.com/media/documents/GOWR_Stephen_Mcauley_RenderingGOWR_GDC23.pdf.

CC @superdump

**Comment by viridia** [comment]
The main constraint is that the default value should preserve the existing behavior. Other than that I don't care.
