### ISSUE TITLE
Left/right and up/down are flipped for anchored text

### ISSUE THREAD

**Issue by bonsairobo** [bevyengine/bevy#9286]
## Bevy version

Revision `0566e73af460b9d128354a20970b1e1e0cc3b719`

## What you did

`cargo run --example text2d`

## What went wrong

It looks like the text anchors are *opposite* from where they should be.

![flipped_text_anchors](https://github.com/bevyengine/bevy/assets/3229981/2b46624f-ee93-48c3-8c3b-e7206aa13ba8)

**Comment by bonsairobo** [comment]
FWIW this change seems to put the text where I would expect. But I don't understand the intent of the original code or what might have changed since it was written to cause the bug.

```
diff --git a/crates/bevy_text/src/text2d.rs b/crates/bevy_text/src/text2d.rs
index a7c72c5d4..ae9446bd9 100644
--- a/crates/bevy_text/src/text2d.rs
+++ b/crates/bevy_text/src/text2d.rs
@@ -105,7 +105,7 @@ pub fn extract_text2d_sprite(
             continue;
         }
 
-        let text_anchor = -(anchor.as_vec() + 0.5);
+        let text_anchor = anchor.as_vec() - 0.5;
         let alignment_translation = text_layout_info.size * text_anchor;
         let transform = *global_transform
             * scaling
```

**Comment by rdrpenguin04** [comment]
The anchor point specifies which corner of the text is tied to the position of the object. As all of these are at the origin, the one with top-left anchoring puts (0,0) at the top-left of the text, making the text go down and to the right. Works as intended, if counterintuitively at first

**Comment by bonsairobo** [comment]
@rdrpenguin04 I see. Thanks for explaining. This deserves to be explained in the documentation. Right now, the docs for `Anchor` say:

> How a sprite is positioned relative to its Transform. It defaults to Anchor::Center.

IMO your explanation was better than the docs.

**Comment by bonsairobo** [comment]
I'll close this issue though, since there is no bug, just a lack of clarity in the docs.
