### ISSUE TITLE
Default window title leaks "bevy" context

### ISSUE THREAD

**Issue by ickk** [bevyengine/bevy#9298]
The default window title is "bevy app" but should be just "app".

This decision was made in https://github.com/bevyengine/bevy/pull/3404#issuecomment-999806086 and was later patched in #3417.

However there was a small regression when moving to windows-as-entities #5589.

Leaking small details like this can look a little bit unprofessional for applications.

**Comment by DDiekmann** [comment]
I would like to work on this as my first contribution, if that is okay?

**Comment by floreal** [comment]
Oh, I am about to submit my PR. Do you want me to leave it to you ?

**Comment by DDiekmann** [comment]
Thanks, but that's fine. I'll find something else.
