### ISSUE TITLE
NPhysics Backend

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#93]
Once we implement #83, we will need a backend for it. I think nphysics is a good choice as it is pure rust, has a decent feature set, and supports both 2d and 3d physics.

**Comment by ncallaway** [comment]
Consider also Rapier (https://rapier.rs), which was announced very recently and sounds like it's now the primary focus of the nphysics developer (which nphysics now listed as passively maintained https://www.dimforge.com/).

**Comment by cart** [comment]
Given that there is already an official bevy_rapier physics plugin, I'm comfortable closing this.
