### ISSUE TITLE
Potential window calculation bug in 0.11.0

### ISSUE THREAD

**Issue by bfg-coding** [bevyengine/bevy#9309]
## Bevy version

0.11.0

## \[Optional\] Relevant system information

```
AdapterInfo { name: "NVIDIA GeForce RTX 4090", ven
dor: 4318, device: 9860, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "536.67", backend: Vulkan }
```

## What you did

Working on asteroid clone.  When spawning the asteroids I notice that they were not spawning inside the primary window dimensions but instead inside the monitors dimensions

## What went wrong

# Expectation
- Spawn 4 asteroids inside the primary window

# Actual
- Spawned 4 asteroids inside the monitor's space

## Additional information

spawn function
```rs
fn spawn_enemies(
    mut commands: Commands,
    window_query: Query<&Window, With<PrimaryWindow>>,
    asset_server: Res<AssetServer>
) {
    let window = window_query.get_single().unwrap();

    for i in 0..INIT_ENEMY_COUNT {
        println!("random: {}", random::<f32>());
        let random_x = random::<f32>() * window.width();
        let random_y = random::<f32>() * window.height();


        println!("asteroid {} x {} < {}", i, random_x, window.width());
        println!("asteroid {} y {} < {}", i, random_y, window.height());

        commands.spawn(
        (
                SpriteBundle {
                    transform: Transform::from_xyz(random_x, random_y, 0.0),
                    texture: asset_server.load("sprites/astroid/astroid_1.png"),
                    ..default()
                },
                Asteroid {
                    direction: Vec2::new(random::<f32>(), random::<f32>()).normalize()
                }
            )
        );
    }
}
```

Logs
```
random: 0.6633456
asteroid 0 x 1127.3723 < 1280
asteroid 0 y 677.8708 < 720
random: 0.21800572
asteroid 1 x 1112.581 < 1280
asteroid 1 y 310.15686 < 720
random: 0.43018222
asteroid 2 x 684.5423 < 1280
asteroid 2 y 597.50165 < 720
random: 0.89251626
asteroid 3 x 478.23364 < 1280
asteroid 3 y 611.35547 < 720
```
Window size at startup
![bevy-astroid-game_PMEYCWG05u](https://github.com/bevyengine/bevy/assets/11151592/079face2-2d55-42de-9c16-ea8366af3c7d)

Full monitor view
![bevy-astroid-game_DciK9cQzjM](https://github.com/bevyengine/bevy/assets/11151592/8fad5a3f-1bf0-4719-9f42-910d20aa7b77)

**Comment by bfg-coding** [comment]
I guess I'm not following.  When I read window I assume the actual display window.  In the case above is 720x1280 and all the random values I'm generating are with in those values but when working they are spawned based on the monitor resolution not the window resolution

**Comment by rparrett** [comment]
Let's take your example and change `INIT_ENEMY_COUNT` to 10000.

<img width="1280" alt="image" src="https://github.com/bevyengine/bevy/assets/200550/b7e55eb5-ee16-47e4-98a9-a43591567b1a">

You're spawning enemies in the range of `0..1280, 0..720` which is a rectangle the size of the window, but the camera is showing `-640..640,-360..360` because the origin is at `0.0, 0.0`.

You can make this small change to your code to spawn the enemies in the right area.

```rust
let random_x = random::<f32>() * window.width() - window.width() / 2.;
let random_y = random::<f32>() * window.height() - window.height() / 2.;
```

**Comment by bfg-coding** [comment]
Oh I got you now.   Thank you for taking the time.  I'm just getting into this stuff and want to understand what's going on over just blunt forcing my way through it.  Thank you again for taking the time

**Comment by rparrett** [comment]
Happy to help!
