### ISSUE TITLE
Despawning audio entity does not stop the sound

### ISSUE THREAD

**Issue by Cyborus04** [bevyengine/bevy#9324]
## Bevy version

Bevy 0.11

## What you did

Create an entity with `AudioBundle`, then despawn it.

[Example](https://codeberg.org/Cyborus/bevy_music_bug) (note: you'll need to put your own song at `./assets/song.mp3`. I didn't want to hassle with song licensing)

## What went wrong

I expected this to stop the music from playing. It, however, kept going.

## Additional information

[Discord discussion where I was suggested to make a bug report](https://discord.com/channels/691052431525675048/691052431974465548/1135664662332055572)

I imagine manually `.stop()`-ing the `AudioSink` would solve this, but I haven't tried that yet.

**Comment by alice-i-cecile** [comment]
I agree that this is how it should work.

**Comment by Cyborus04** [comment]
woah you're fast to respond haha

**Comment by alice-i-cecile** [comment]
IIRC, this is going to be quite challenging to make work based on how the current audio backend works. My recollection is that it spawns and detaches audio tasks.

**Comment by Cyborus04** [comment]
Running `.stop()` on the audio sink before deleting it did work around it. Not surprising, but I thought I'd confirm it in case anyone else needs it.

**Comment by Cyborus04** [comment]
should this be under the 0.11.1 milestone?
