### ISSUE TITLE
Asset not loaded when loading it one frame after it gets unloaded

### ISSUE THREAD

**Issue by idanarye** [bevyengine/bevy#9337]
## Bevy version

v0.11

## \[Optional\] Relevant system information

This replicates in both native and WASM, meaning it's not environment-specific.

## What you did

* Delete the last handle to an asset.
* In the next frame, `load` the same asset.

### what were you expecting?

One of two options:
* The asset will not be unloaded because only one frame had passed where no strong handle was not point at it.
* The asset will be unloaded and then loaded again.

Either way - I'd expect the asset to eventually be loaded.

### what actually happened?

The asset remained `Unloaded` even though a strong handle is pointing at it.

## Additional information

I've created a minimal reproducible example for this issue: https://github.com/idanarye/demonstrate-race-in-bevy-assets. It reproduces when you run it with `cargo run`, and it also reproduces with WASM - https://idanarye.github.io/demonstrate-race-in-bevy-assets/bevy_github_ci_template

This example has an egui window with a _Recreate_ button. When you click on it, it despawns the entity, and also create a new entity with a tag component. On the next frame, after that new entity is created, another system adds the texture to it.

The egui window also shows information about the asset. Every time you click the button, you can see there that load status of the asset chances from `Loaded` to `Unloaded` or from `Unloaded` to `Loaded`. And you can or cannot see the actual sprite accordingly. The handle itself has the same `AssetPathId`, and is always a `StrongHandle`.

**Comment by mockersf** [comment]
it's kind of expected... let's wait for https://github.com/bevyengine/bevy/pull/8624 before revisiting this

**Comment by idanarye** [comment]
I've tried to use the Asset V2 branch in my demonstration repository (had to do some changes, like getting rid of egui), and the bug does not replicate there.

**Comment by viridia** [comment]
This appears to be fixed in Assets V2.
