### ISSUE TITLE
Potentially incorrect barrier in Game of Life example

### ISSUE THREAD

**Issue by SludgePhD** [bevyengine/bevy#9353]
## Bevy version

git (but any that contain the game of life example have the issue)

## What you did

The `game_of_life.wgsl` compute shader example uses a barrier in an attempt to synchronize all threads before writing to the storage texture:

https://github.com/bevyengine/bevy/blob/42098192c228bd1329ff9ff1a4848c030ec171ec/assets/shaders/game_of_life.wgsl#L63-L65

This synchronization is needed because all threads also *read* from the same texture (from various pixels that are written to by other invocations).

## What went wrong

To my knowledge, GPU barriers only affect threads *within a single workgroup*, but not those in different workgroups (that would require running an *unbounded* number of threads until they reach the barrier, saving their state, and then resuming them later). The shader uses 8x8 threads per workgroup, but runs on a texture that is much larger.

The potential impact of this is that a workgroup might read from pixels that were already written to by a different workgroup (outside of its 8x8 pixel block), leading to incorrect simulation results. Not the end of the world, but an example meant for teaching should probably get this right.

AFAIK the only way to correctly implement game of life in a compute shader is by using *two* textures and flipping between them every simulation step. That implementation wouldn't need a barrier at all, which is by far the simplest barrier to reason about :)

**Comment by JMS55** [comment]
Yes, barriers only synchronize the IO and execution from within the same workgroup. We'll need to double buffer the textures like you said.
