### ISSUE TITLE
Provide "empty" object bundle.

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#9354]
## What problem does this solve or what need does it fill?

It is common in 3D graphics to have a parent object in the scene graph which by itself has no appearance, but which serves as a way to organize and transform child objects. In three.js this role is provided by the `Group` class.

Right now, it's relatively easy to do this using a custom bundle which has a transform but no mesh or materials:

```rust
#[derive(Bundle, Clone, Default)]
pub struct GroupBundle {
    pub transform: Transform,
    pub global_transform: GlobalTransform,
    pub visibility: Visibility,
    pub computed_visibility: ComputedVisibility,
}
```
The advantages of this approach is that the children will inherit the transform and visibility of the parent, which is what you would expect.

However, this solution is brittle: if in the future Bevy decides to add additional components to the standard bundles like `MaterialMeshBundle`, or decides to change the way that `global_transform` or `computed_visibility` work, then everyone who uses this recipe will have to update their code. Normally users shouldn't have to concern themselves with `global_transform` or `computed_visibility` since those are managed by the engine.

## What solution would you like?

What I propose is simply to make `GroupBundle` as defined above, as an officially blessed solution and add it to the set of provided bundles in Bevy.

## What alternative(s) have you considered?

Continuing to do this on an ad-hoc basis.

## Additional context

Bikeshedding on the name `GroupBundle` is welcome.

**Comment by rparrett** [comment]
[SpatialBundle](https://docs.rs/bevy/latest/bevy/prelude/struct.SpatialBundle.html) is exactly that.

**Comment by viridia** [comment]
Thanks. Closing...

**Comment by viridia** [comment]
> Maybe discoverability of this could be improved... This is called [`Group`](https://threejs.org/docs/#api/en/objects/Group) in three.js, [`Node3D`](https://docs.godotengine.org/en/stable/classes/class_node3d.html)/[`Node2D`](https://docs.godotengine.org/en/stable/classes/class_node2d.html) in Godot.
> 
> What would you try to search in Bevy docs to find it? Maybe we could add doc aliases

Yeah, that was exactly my problem, I didn't know what to search for. I looked in the Bevy Book, the cheat guide, I even looked in the source code - `bundle.rs` - and I saw various types of bundles (MaterialMeshBundle, PbrBundle, etc.) but didn't see anything matching what I was looking for.

**Comment by dmyyy** [comment]
A place where all built-in bundles (bundle name + short comment) would be nice. I usually look here: https://bevy-cheatbook.github.io/builtins.html#bundles but it can be hard to find if you don't know what to look for (and if you don't know this section of the cheatbook exists)

**Comment by mockersf** [comment]
`Bundle` is a trait, you can find its implementors on docs.rs: https://docs.rs/bevy/latest/bevy/ecs/bundle/trait.Bundle.html#implementors

But this lacks any kind of explanation...
