### ISSUE TITLE
Bevy-reflect:  cannot call non-const fn in constant functions

### ISSUE THREAD

**Issue by hector-crean** [bevyengine/bevy#9374]
## Bevy version

v.0.11.0

## \[Optional\] Relevant system information

cargo 1.71.0 (cfd3bbd8f 2023-06-08)

## What you did

Attempted to compile package with bevy 0.11 as dependency.

## What went wrong

error[E0015]: cannot call non-const fn `parking_lot::lock_api::RwLock::<parking_lot::RawRwLock, bevy_utils::hashbrown::HashMap<TypeId, &<T as TypedProperty>::Stored, FixedState>>::new` in constant functions

    |
221 |         Self(RwLock::new(StableHashMap::with_hasher(FixedState)))
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: calls in constant functions are limited to constant functions, tuple structs and tuple variants

(https://github.com/bevyengine/bevy/blob/10797d4f159e8686719b32cf95eec69134b11eaa/crates/bevy_reflect/src/utility.rs#L221)

**Comment by lbenard** [comment]
Did you figure out a way to fix the issue? I tried compiling both on `main` and `v0.11.0` with different Rust versions but the error remains

**Comment by nicopap** [comment]
Can you run `cargo tree -i lock_api` and tell what version of `lock_api` you have?

**Comment by lbenard** [comment]
I'm getting `lock_api v0.4.6` (building bevy 0.11 https://github.com/bevyengine/bevy/commit/8ba9571eedada4f3ff43cdf1402670b7fe7c280d)

**Comment by nicopap** [comment]
Yeah this should not happen. It should be at least be `0.4.7`. Make sure to run `cargo update` or `cargo clean` if `cargo update` doesn't fix it.

Technically bevy should depend explicitly on `lock_api 0.4.7` since it depends on a feature introduced by that version, but it's weird because it's only a transitive dependency through `parking_lot 0.12.1` which re-exports `RwLock` in a non-forward-compatible way.

**Comment by chamons** [comment]
I am running into this as well, and I deleted my cargo.lock file, update, cleaned and it did not go away.

My lockfile had:

name = "parking_lot"
version = "0.12.1"

name = "parking_lot_core"
version = "0.9.8"

name = "lock_api"
version = "0.4.6"

**Comment by johnbchron** [comment]
@hector-crean Are you still experiencing this issue or is it good to close?

**Comment by hector-crean** [comment]
cargo update + cargo clean equally did the trick for me. All working. Thanks for the help
