### ISSUE TITLE
Mention `--cfg=web_sys_unstable_apis` in WebGPU build instructions

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#9382]
## How can Bevy's documentation be improved?

To be able to use WebGPU on web, you need to set the `RUSTFLAGS` environment variable to `--cfg=web_sys_unstable_apis`. Nowhere is it mentioned in the bevy docs, and it's not trivial to find out from searching the bevy repo.

Reading the docs at:
* https://github.com/bevyengine/bevy/blob/main/docs/cargo_features.md
* https://github.com/bevyengine/bevy/tree/main/examples

No mention is made of that environment variable. Also, it's implied that everything should work, there is no obvious disclaimer that it's "experimental" or "unsupported" and instructions are provided specifically wrt to WebGPU.

Apparently I'm not the only one who encountered this: #9177

* See: https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html

**Comment by mnmaita** [comment]
I had this exact same issue when trying to ship a WASM build to itch.io. I just pushed #10163 to try to add some more details on this matter. Please let me know if the added documentation is enough and is understandable. Thanks for filing it!
