### ISSUE TITLE
Make `scene_viewer` movement speed proportional to scene size

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#9384]
## What problem does this solve or what need does it fill?

In the wild west of 3d asset collections, the scale of 3d models can go from simple to the 10⁶. If we load a scene of extremely large scale with `scene_viewer`, we are stuck in place, basically not moving at all. Inversely, if the model is tinny, we won't even be able to move close to it

## What solution would you like?

The `scene_viewer` already computes the total size of a scene to place properly the camera (very clever whoever thought of that!) We could re-use this data to set the movement speed.

### Problems with approach

This might make it difficult for users to judge the actual size of things they load. An option is to spawn a grid (or a banana) for scale.

**Comment by DGriffin91** [comment]
I personally like the UE5 approach of having the movement speed control on the scroll wheel.

If someone loads a really large scene that has typical human traversable dimensions like a town vs another like a single room, having a super fast movent speed in one and super slow in the other isn't very helpful imo.
