### ISSUE TITLE
"Custom Render Pass" wasm example uses not 16-byte aligned type and crashes

### ISSUE THREAD

**Issue by necromfox** [bevyengine/bevy#9386]
## Bevy version

0.11.0 (?)

## What you did

Opened [example](https://bevyengine.org/examples/Shaders/post-processing/)

## What went wrong

```
In the provided shader, the type given for group 0 binding 2 has a size of 4. As the device does not support `DownlevelFlags::BUFFER_BINDINGS_NOT_16_BYTE_ALIGNED`, the type must have a size that is a multiple of 16 bytes
```

## Additional information

![image](https://github.com/bevyengine/bevy/assets/76201108/2993d4de-1f8c-47a4-a5c1-bd7ac0a1d549)

**Comment by rparrett** [comment]
This was fixed by #9361, but not yet deployed to the website.

**Comment by termisaal** [comment]
also skill issue

**Comment by JMS55** [comment]
I think we can close this then?
