### ISSUE TITLE
failed to build on win10

### ISSUE THREAD

**Issue by weiby3** [bevyengine/bevy#939]
**Bevy version**

0.3.0

**Operating system & version**

Windows 10

Got the following link error when build bevy-snake
```
glslang.glsltospirv.lib(intermOut.obj) : error LNK2019: unresolved external symbol __imp__fpclass referenced in function "void __cdecl glslang::OutputDouble(class TInfoSink &,double,enum glslang::TOutputTraverser::EExtraOutput)" (?OutputDouble@glslang@@YAXAEAVTInfoSink@@NW4EExtraOutput@TOutputTraverser@1@@Z)
glslang.glsltospirv.lib(ParseHelper.obj) : error LNK2019: unresolved external symbol __imp_log2 referenced in function "double __cdecl log2<int,0>(int)" (??$log2@H$0A@@@YANH@Z)
fatal error LNK1120: 2 unresolved externals
```

**Comment by cart** [comment]
I'm guessing this is another case of #788. Can you try installing Visual Studio 2019 build tools?

Lets leave this issue open until we've updated the Bevy Setup part of The Book to include a note that VS2019 build tools are a dependency on Windows.

**Comment by weiby3** [comment]
I had used vs2019 build tools.
I had searched that issue, and know vs2019 is required.
So I open this issue.

**Comment by ccoenen** [comment]
I ran into the same issue while following the bevy book getting started guide on windows 10. This happened right after [adding `DefaultPlugins`](https://bevyengine.org/learn/book/getting-started/plugins/)

Should we add the [vs 2019 build tools](https://visualstudio.microsoft.com/de/downloads/) to the book somewhere?

**Comment by cart** [comment]
closed by https://github.com/bevyengine/bevy-website/pull/79
