### ISSUE TITLE
There is a missing safety comment in `bevy_render`

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#9393]
## How can Bevy's documentation be improved?

`bevy_render::view::window` has a fairly large `unsafe` block with no safety comment.

https://github.com/bevyengine/bevy/blob/9e8de2aa94fd345b556542717e3ef8464150cc4a/crates/bevy_render/src/view/window.rs#L240-L242

The unsafe operation is `render_instance.create_surface(…)` (https://docs.rs/wgpu/latest/wgpu/struct.Instance.html#method.create_surface).

* The `unsafe` block could be limited to `create_surface`, the rest of the `unsafe` block doesn't uphold any invariants related to `create_surface`
* There should be a safety comment explaining why the `RawWindowHandle` passed to `create_surface` are valid. (to be fair, this seems particularly tricky, since I don't see any definition of "valid" in the wgpu doc)

**Comment by JaySpruce** [comment]
Fixed by #10646
