### ISSUE TITLE
Joystick support

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#94]
We should support joysticks / gamepads. I think https://gitlab.com/gilrs-project/gilrs is probably the right choice.

**Comment by PradeepKumarRajamanickam** [comment]
Is anyone working on this ticket? I can try to roll out a plugin/pr if I get some free time. Do let me know if this should be 3rd party first approach?

**Comment by cart** [comment]
Yup #280 adds joystick support. I've already given it a first pass and it seems like the right approach.

**Comment by PradeepKumarRajamanickam** [comment]
Great. Should we move this to in-progress on the roadmap project board? It is currently on to-do.

**Comment by cart** [comment]
closed by #280
