### ISSUE TITLE
Redundant `AppExit` event checking in ScheduleRunnerPlugin

### ISSUE THREAD

**Issue by Pixelstormer** [bevyengine/bevy#9420]
## Bevy version

`0.11`

## Description

While looking through Bevy's source code, I noticed that the `ScheduleRunnerPlugin` is [checking for `AppExitEvents` twice in the main loop](https://github.com/bevyengine/bevy/blob/37915e1d9370a7ea46afb3eec6d62b4074a9f120/crates/bevy_app/src/schedule_runner.rs#L92-L110) - once immediately before calling `App.update()` and once immediately after. Meanwhile, the main loop of the `WinitPlugin` only does this check [once in the main loop](https://github.com/bevyengine/bevy/blob/37915e1d9370a7ea46afb3eec6d62b4074a9f120/crates/bevy_winit/src/lib.rs#L732-L736), a bit after calling `App.update()`.

As the WinitPlugin is only checking for `AppExit` events once per loop, I believe that means the extra check in `ScheduleRunnerPlugin` is redundant and unneccessary (Or if it somehow is necessary, it's completely undocumented). The secondary check was added in [this commit](https://github.com/bevyengine/bevy/commit/2fb9e115ffb6bafaae5e940dc5ec2d2209d37d39#diff-2b1017791a02dd2eff14f21b5d03a59d2b0c6253c4d1107d163541d3e994da35R57-R63), if it's any help.

**Comment by alice-i-cecile** [comment]
Let's get a PR open for this and do some testing? This definitely looks redundant to me.
