### ISSUE TITLE
Methods on `Color` to get/set HSL

### ISSUE THREAD

**Issue by Selene-Amanita** [bevyengine/bevy#9438]
## What problem does this solve or what need does it fill?

It's easily possible to set or get rgba (red/green/blue/alpha) values on `Color` no matter the variant of the Color, using methods like `r`, `set_r` or `with_r`.

It's more convoluted to get or set hsl/lch (hue/saturation/luminance/chroma) values.

## What solution would you like?

- Similar `s`/`set_s`/`with_s` methods, same for `l`, `h` and `c`
- Document that `set_*` and `with_*` modify the variant of the `Color`

## What alternative(s) have you considered?

Do what `set_r`/`with_r` are doing but for hsl manually.

**Comment by alice-i-cecile** [comment]
Will be fixed by https://github.com/bevyengine/bevy/pull/9201.

**Comment by alice-i-cecile** [comment]
Also see #7759.

**Comment by Selene-Amanita** [comment]
Ah I searched the issues but didn't think to check the pull requests sorry ><'
Also didn't find https://github.com/bevyengine/bevy/issues/7746 for some reason.
