### ISSUE TITLE
Clean up doc string in `NodeBundle`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#9440]
There's also a copy of this "`NodeBundle`" comment here, associated with the `node` field, with the same copy/paste mistake.

Seems safe to get rid of this one too to me. Not every bundle has it. But maybe it was intended that it say "to alter the **size**"?

_Originally posted by @rparrett in https://github.com/bevyengine/bevy/pull/9404#discussion_r1291327481_

**Comment by hate** [comment]
Considering that the doc string for the `style` component already mentions adjusting the size and position of the `ImageBundle`, I'd concur that the aforementioned string should be removed.
