### ISSUE TITLE
Add panicking versions of `get_component` and `get`

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#9443]
## What problem does this solve or what need does it fill?

It's annoying to call `unwrap` or `expect` on `get` or `get_component` calls if you know that the entity will contain the component for sure. Happens a lot if you working with hierarchy or reference entities in components.

## What solution would you like?

It would be great to have panicking versions for convenience. I think that `get_component(_mut)` could have `component(_mut)` alternative. But `get` need to be renamed to `get_entity` in order to have panicking `entity` function. I would like to hear your thoughts about it.

**Comment by alice-i-cecile** [comment]
Hmm, I can see the value in that, especially for consistency with `.resource`.

Maybe `.get` should be renamed regardless, to more clearly communicate that it fetches the selected query data for the entity?

Or we could do `get_unchecked`, as I think generally users should be checking and matching on this.

**Comment by Shatur** [comment]
> Or we could do get_unchecked, as I think generally users should be checking and matching on this.

This sounds like something that requires `unsafe`, so I would rename `.get`, yes.

**Comment by alice-i-cecile** [comment]
Perhaps `Query::get_data` and `Query::get_data_mut`? I think that using `entity` in the name gives the wrong impression / mental model, since you don't have access to all of it's components (and it's not somehow fetching an `Entity` identifier).

**Comment by Shatur** [comment]
Agree, I like it!
I also thought about `components` (plural), but it's too similar to `component`.

**Comment by IAmSegfault** [comment]
Hi, I'm a new contributor and would like to take this on as a first issue. I do have some experience porting the `bracket-bevy` module in bracket-lib to newer versions of Bevy.

What does [this function](https://github.com/bevyengine/bevy/blob/b30ff2ab766e71e5ef7b07fbc5f94534235d7c67/crates/bevy_ecs/src/query/mod.rs#L737) do in particular? I noticed it calls `get_component` and it would be helpful to know if it needs to call the new methods as well. Also if it's agreed upon I'll label the methods `Query::get_data` and `Query::get_data_mut`.

**Comment by Shatur** [comment]
> What does [this function](https://github.com/bevyengine/bevy/blob/b30ff2ab766e71e5ef7b07fbc5f94534235d7c67/crates/bevy_ecs/src/query/mod.rs#L737) do in particular?

It checks if a query with `&mut` can return immutable components.

> it would be helpful to know if it needs to call the new methods as well.

Yes, you will need to call new methods here.

**Comment by Shatur** [comment]
@IAmSegfault are you planning to start working on it?
Asking because I considering implementing in myself :)

**Comment by IAmSegfault** [comment]
Sure if you want to take over that's fine. I've been busy with work lately and was going to try squeeze in time before the next release.

**Comment by Shatur** [comment]
No longer relevant since `get_component` was removed.
