### ISSUE TITLE
Asset loading issue after 0.11.1

### ISSUE THREAD

**Issue by Shatur** [bevyengine/bevy#9452]
## Bevy version

0.11.1

## What you did

Consider the following example [breaking_change.zip](https://github.com/bevyengine/bevy/files/12353353/breaking_change.zip) with Bevy 0.11.0. Model and its animations loaded successfully. If you try to update it to Bevy 0.11.1 it will break.
 

## What went wrong

If you update Bevy version to 0.11.0 I see either model without animations of no model at all. Looks like https://github.com/bevyengine/bevy/pull/9429 solved the issue for animated fox, but larger model I observe race condition.

### 0.11.0:
![image](https://github.com/bevyengine/bevy/assets/22453358/b7805f0a-af40-49df-b44b-9cc2d4849a37)
### 0.11.1
![image](https://github.com/bevyengine/bevy/assets/22453358/9442cc2e-d31c-4be0-b483-a459da0d856a)

**Comment by robtfm** [comment]
you're right, only one pending request gets unblocked. this diff fixes it for me, can you please test as well (i guess you have a larger project to try it with)

```diff
diff --git a/crates/bevy_asset/src/asset_server.rs b/crates/bevy_asset/src/asset_server.rs
index 2217c80c9..e5daf1112 100644
--- a/crates/bevy_asset/src/asset_server.rs
+++ b/crates/bevy_asset/src/asset_server.rs
@@ -236,7 +236,7 @@ impl AssetServer {
             loaders[existing_index] = MaybeAssetLoader::Ready(Arc::new(loader));
             if let Some(sender) = maybe_sender {
                 // notify after replacing the loader
-                let _ = sender.send_blocking(());
+                let _ = sender.close();
             }
         } else {
             loaders.push(MaybeAssetLoader::Ready(Arc::new(loader)));
```

**Comment by Shatur** [comment]
Can confirm that this change fixes the issue for my project too.
