### ISSUE TITLE
naga_oil interprets field access as imported binding

### ISSUE THREAD

**Issue by amfaber** [bevyengine/bevy#9466]
## Bevy version
Hash - 43fe83b7c681b56b47b17127d16673be36da83b2

## What you did
In my wgsl code I have `#import bevy_pbr::mesh_view_bindings view`. Later I try to use the "view" field of the "view" binding - ... `view.view` ...
This results in the following wgsl validation error
```
error: invalid field accessor `bevy_pbr::mesh_view_bindings::view`
   ┌─ shaders/instancing.wgsl:39:86
   │
39 │     let idk = bevy_pbr::mesh_view_bindings::view.bevy_pbr::mesh_view_bindings::view;
   │                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ invalid accessor
   │
   = invalid field accessor `bevy_pbr::mesh_view_bindings::view`
```

- what were you expecting?
Field access to work like expected
- what actually happened?
The field is interpreted as the imported binding

## Additional information
I assume this is an unintended consequence of https://github.com/bevyengine/bevy/pull/5703

**Comment by JMS55** [comment]
I believe this should be fixed by https://github.com/bevyengine/naga_oil/pull/31?

**Comment by amfaber** [comment]
It even lists the exact same example of view.view, so I think it is safe to assume so. Awesome to see it fixed already :) I'll just have to watch out for when the version is bumped
