### ISSUE TITLE
UI node layout doesn't refresh when patching entity children

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#9492]
## Bevy version

0.11.1

## What you did

I'm writing a UI system that has a "virtual DOM" similar to what React does. This entails doing a "diff" between the old and new node hierarchy, and then incrementally patching the tree of entities based on what's changed.

What I have discovered is that Bevy UI doesn't like this very much. Specifically, when I have a node that has some number of children, and I replace some of the children but not others, the layout gets messed up. Even more significant, is that if I resize the window even a tiny bit, the layout fixes itself. So something is not getting refreshed.

Specifically, what I am doing is (pseudo-code):

* For a given entity
  * visit each child to see if that child changed.
    * If the child changed, replace it with a new child entity and despawn the old one and its descendants.
    * If the child did not change, keep it
  * Now take the vector of all the new child ids - both the ones that were kept from before, and the ones that are new - and call `parent.replace_children()`.
  * Finally, recurse downward and do the same for each child element.

## What went wrong

What I'm seeing is that the node layout is random, nodes appearing displaced from where they should be, nodes off the edge of the screen and so on.

## Additional information

The problem only seems to manifest when I enable mixing of new and old children. I can disable the bug in one of two ways: either by re-creating the node tree every time (by disabling the diff algorithm), or by not mutating the tree at all.

I realize that you'll probably want a reproducible case. I can provide this, but it's a considerable amount of work and will take some time. That is, I can easily demonstrate the bug in my current github repo, but if you want a "minimal" example I'll need to spend time cutting out all of the parts of the game that aren't relevant to the bug, which can go on a branch or something.

Let me know what you need.

**Comment by ickshonpe** [comment]
I think this example captures at least some of the issues: 

```rust
use bevy::prelude::*;
use bevy::utils::HashMap;

fn main() {
    let mut app = App::new();
    
    app.add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(Update, replacement)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
    let root_id = commands.spawn(NodeBundle {
        style: Style {
            flex_direction: FlexDirection::Column,
            justify_content: JustifyContent::Center,
            margin: UiRect::horizontal(Val::Auto),
            row_gap: Val::Px(25.),
            ..Default::default()
        },
        background_color: Color::WHITE.into(),
        ..Default::default()
    })
    .id();

    let mut container = root_id;

    for i in 0..4 {
        let wrapper_id = commands.spawn(NodeBundle {
            style: Style {
                flex_direction: FlexDirection::Column,
                align_items: AlignItems::Center,
                border: UiRect::all(Val::Px(10.)),
                ..Default::default()
            },
            border_color: BorderColor(Color::YELLOW),
            background_color: BackgroundColor(Color::RED),
            ..Default::default()
        })
        .id();
        let row_id = commands.spawn(NodeBundle {
            style: Style {
                flex_direction: FlexDirection::Row,
                column_gap:  Val::Px(25.),
                padding: UiRect::all(Val::Px(25.)),
                ..Default::default()
            },
            background_color: Color::BLACK.into(),            
            ..Default::default()
        }).with_children(|commands| {
            for j in 0..4 {
                commands.spawn(NodeBundle {
                    style: Style {
                        width: Val::Px(70.),
                        height: Val::Px(70.),
                        align_items: AlignItems::Center,
                        justify_content: JustifyContent::Center,
                        ..Default::default()
                    },
                    background_color: Color::WHITE.into(),
                    ..Default::default()
                }).with_children(|commands| {
                    commands.spawn(TextBundle::from_section(format!("{i}, {j}"), TextStyle { font_size: 25., color: Color::BLACK, ..Default::default() }));
                });
            
            }
        })
        .id();
        commands.entity(wrapper_id).add_child(row_id);
        commands.entity(container).add_child(wrapper_id);
        container = wrapper_id;
    }        
}

fn replacement(
    input: Res<Input<KeyCode>>,
    mut commands: Commands,
    query: Query<(Entity, &Children), With<Node>> 
) { 
    if input.just_pressed(KeyCode::Space) {
        let mut children_map: HashMap<Entity, Vec<Entity>> = HashMap::default();

        query.for_each(|(entity, children)| {
            children_map.insert(entity, children.iter().cloned().collect());
        });

        for (entity, children) in children_map {    
            commands.entity(entity)
                .remove_children(&children)
                .replace_children(&children);
        }
    }
}
```
After startup:
<img width="329" alt="9492_example_capture_1" src="https://github.com/bevyengine/bevy/assets/27962798/8976c774-c80f-4c89-b873-df1277ad5d3b">

Then after pressing space and triggering the global children replacement:

<img width="329" alt="9492_example_capture_2" src="https://github.com/bevyengine/bevy/assets/27962798/27f81d8b-98af-4ded-a8a8-46da25d6b147">

The text has disappeared and we can see a green leaf node in the top left corner.

Then after resizing the window, it resets back to the original state:

<img width="329" alt="9492_example_capture_1" src="https://github.com/bevyengine/bevy/assets/27962798/8febeffc-8d38-4e24-bc90-31f9a710c092">

It's only the leaf nodes that get displaced. Perhaps it's something to do with how the UI queries for entities with changed `Children` and updates them, but doesn't query for entities with a changed `Parent`. This might be something I've already fixed in one of my unmerged `ui_layout_system` PRs. IIRC there are a couple of subtle problems caused because we do removal detection, hierarchy change detection and hierarchy updates in the wrong order.

**Comment by ickshonpe** [comment]
This wasn't what I thought it was initially at all, it's a bug in transform propagation. Issue #9517.

**Comment by viridia** [comment]
> This wasn't what I thought it was initially at all, it's a bug in transform propagation. Issue #9517.

I'm attempting to verify that this fixes my problem. Unfortunately I'm having trouble using the bevy main branch - bevy_trait_query no longer compiles, and my UI code depends on that.

**Comment by ickshonpe** [comment]
You could try a system that forces the transforms to update every frame. Something like this should work:
```rust
fn force_update(mut transforms: Query<&mut Transform>) {
   for mut transform in transforms.iter_mut() {
        transform.set_changed();
   }
}
```

**Comment by viridia** [comment]
> You could try a system that forces the transforms to update every frame. Something like this should work:

Yep, that did the trick! Looks beautiful.

**Comment by viridia** [comment]
This was fixed, can be closed.
