### ISSUE TITLE
Skeletal Animation

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#95]
Bevy should support skeletal animation / skinning. It should probably integrate with the Animation API (#91) if possible

**Comment by alice-i-cecile** [comment]
Here's an excellent detailed blog post about implementing this: https://vladh.net/articles/game-engine-skeletal-animation.html

**Comment by Pauan** [comment]
Ideally this should be done on the GPU, and it should support [skeleton animation instancing](https://github.com/bevyengine/bevy/issues/89#issuecomment-849705018).

**Comment by Roba1993** [comment]
What should also be directly added for Skeletal Animation is a Socket system. So that we can have other entities at a bone position (with offset if needed) follow the animation.

**Comment by alice-i-cecile** [comment]
> What should also be directly added for Skeletal Animation is a Socket system. So that we can have other entities at a bone position (with offset if needed) follow the animation.

Oh this is nice. I'll keep it in mind as we start refining our idea of what exactly a "child" means in a hierarchy.

**Comment by taladar** [comment]
Just as another data point for something that might be useful in the medium to long-term:

For games with user-adjustable avatars (e.g. Second Life) it would be useful to be able to define skeletal animations with some sort of inverse kinematics support so the relevant parts of the avatars (e.g. mouths for a kiss, hand to pick something up) are in the right spot when height, arm length,... differ.

**Comment by cart** [comment]
Closing in favor of #4026
