### ISSUE TITLE
System set names are too aggressively stripped when reporting system order ambiguities

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#9509]
## Bevy version

0.11

## What you did

Enable [system 

## What went wrong

```rust
2023-08-20T17:23:10.908705Z  WARN bevy_ecs::schedule::schedule: 1 pairs of systems with conflicting data access have indeterminate execution order. Consider adding `before`, `after`, or `ambiguous_with` relationships between these:
 -- update_action_state<PlayerAction> (in set Update) and ui_focus_system (in set Focus)
    conflict on: ["bevy_ui::focus::Interaction"]
 ```
 
## Additional information

The set names should be [`InputManagerSystem::Update`](https://docs.rs/leafwing-input-manager/0.10.0/leafwing_input_manager/plugin/enum.InputManagerSystem.html) and [`UiSystem::Focus`](https://docs.rs/bevy/latest/bevy/ui/enum.UiSystem.html) instead.

These are much clearer.

Note that this bug is due to `get_short_name` not differentiating between the `::` used for enum variants correctly. The enum type should be retained, while other module path info is stripped.

**Comment by nicopap** [comment]
I guess the heuristic to recognize enum names should be to check if the one-to last path item is uppercase.
