### ISSUE TITLE
Add `Val::Zero`

### ISSUE THREAD

**Issue by jim-ec** [bevyengine/bevy#9533]
## What problem does this solve or what need does it fill?

When requesting a UI length of zero, there is no clear choice of unit.

In CSS e.g., the zero literal does not have to be followed by any unit:

```css
p {
  right: 0;
}
```

## What solution would you like?

Add the `Val::Zero` case to the `ui_node::Val` enum.

## What alternative(s) have you considered?

Just continue using `Val::Px(0.0)` / `Val::Percent(0.0)` / etc.

## Additional context

https://stackoverflow.com/questions/7923042/when-specifying-a-0-value-in-css-should-i-explicitly-mark-the-units-or-omit

**Comment by ickshonpe** [comment]
Having different representations of `0.` is annoying but I'm not sure another variant would help. Like now we not only have `Val::Px(0.)` or `Val::Percent(0.)` or `Val::VMin(0.)` etc to choose from but also `Val::Zero`, is that progress?

I've suggested before that we change all the UI functions to take `Into<Val>` and implement:
```rust
impl From<f32> for Val {
    fn from(value: f32) -> Self {
        Val::Px(value)
    }
}
```
So that then you could just use 
```rust
margin: UiRect::all(0.0)
```
It wasn't a popular idea though and I withdrew the PR.

**Comment by jim-ec** [comment]
Link to PR mentioned above: #7500

**Comment by jim-ec** [comment]
As far as I see it, the problem with #7500 is the ambiguity between units. `Val::from(2.0)` should mean pixels, but that was not clear from context. For zero, however, the unit does not matter, so the problem with unit ambiguity vanishes.

Of course, it is somewhat paradoxical to complain about too many options and trying to fix the problem by adding another option. However, I personally find it more elegant to use `Val::Zero` instead of deciding on a specific unit, but I guess that is a purely personal preference. That's why I am raising this issue, to see how others think about it.

**Comment by mockersf** [comment]
`Val::ZERO` could be a const value  that means `Val::Px(0.0)`

**Comment by ickshonpe** [comment]
> `Val::ZERO` could be a const value  that means `Val::Px(0.0)`

Yeah, that's not so bad.

**Comment by ickshonpe** [comment]
This got me thinking, and I think a bigger problem is that the `Val` arithmetic functions are wrong. We should be able to add numeric `Val`s of zero to anything, regardless of variant. #9534

**Comment by alice-i-cecile** [comment]
I think we should go with the const approach instead of another variant, because of the multiple representations problem.
