### ISSUE TITLE
`#[deref]` fails when properties have other attributes or doc comments: "unexpected token in attribute"

### ISSUE THREAD

**Issue by Jondolf** [bevyengine/bevy#9550]
## Bevy version

0.11.2

## What you did

I have a struct with several properties and would like to use the `#[deref]` attribute for one of them.
However, this doesn't work if any of the struct's fields have documentation comments or other attributes.

Minimal reproduction:

```rust
#[derive(Component, Deref, DerefMut)]
struct MyComponent {
    #[deref]
    foo: bool,
    /// Important documentation. (throws error)
    pub bar: bool,
}
```

## What went wrong

I get the error `unexpected token in attribute`. The publicity or type of the properties doesn't seem to matter, and I think it happens with all attribute types.

## Additional information

My use case for this is bevy_xpbd's components like `ExternalForce`. It has multiple documented fields, but I want to deref the actual force property so that you can do e.g. `*force = Vec3::Y` instead of `force.force = Vec3::Y`. I can do (and currently do) this manually, but for ergonomics it would be nice if `#[deref]` worked properly.

**Comment by MrGVSV** [comment]
Replicated! I'll post a fix shortly
