### ISSUE TITLE
Add first-party asset-based cursor icons to Bevy

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#9557]
FYI, winit's existing `set_cursor_icon` method is inadequate for games: it only supports a fixed, unstyled list and relies on OS support. In games, you often need new options (a mining pick! an axe! a sword!), and virtually always want custom assets.

This isn't something `winit` *can* fix, since it doesn't come with an asset / rendering solution. Instead, we should build our own cursor icon solution, with a "native" variant that just uses the OS ones provided by winit.

_Originally posted by @alice-i-cecile in https://github.com/bevyengine/bevy/discussions/9538#discussioncomment-6808163_

**Comment by alice-i-cecile** [comment]
The first PR for this should be quite simple: just create a UI element from an image, and keep it synced with the mouse while disabling the built in cursor.

Probably have a `CursorBundle` or something, and then just let users manually swap the image handle as needed.

Picking-integrated reactivity can come later.

**Comment by aevyrie** [comment]
We actually need winit support to do this correctly. Relying on the rendered window to draw a cursor is never going to have the same low latency as the OS cursor.

https://github.com/rust-windowing/winit/issues/3005

I've noticed other games with custom cursors have properties that prove this:
- during game streaming, the custom cursor will become visible before the rendered output is visible
- the cursor can leave the frame of the window when the cursor is positioned in the bottom right
- the latency and udpate rate is perfect even when the game is not running amazingly well

**Comment by aevyrie** [comment]
More proof this is possible, navigate to this page and hover over the demo to get the rainbow icon.

https://webdesign.tutsplus.com/how-to-create-a-custom-mouse-cursor-with-css-or-javascript--cms-106724t

Scroll up so the demo is at the bottom edge of the screen. You will be able to see the custom cursor image hanging outside the bounds of the browser window. Additionally, the latency is perfect.

**Comment by alice-i-cecile** [comment]
Definitely agree that we *should* hook into the OS layer.

Unsure if there's a sensible way to do this with `winit` itself though 🤔 It's not asset or graphics aware. Same sort of problem we ran into with window icons.

**Comment by aevyrie** [comment]
The winit API should just accept image bytes for the `Custom` variant. We just need a layer of indirection on the current `Window` cursor setting that accepts an asset handle once winit supports the feature.

**Comment by Friz64** [comment]
https://github.com/rust-windowing/winit/pull/3218 has just been merged 🎉

**Comment by djeedai** [comment]
Came to say the same :) Is there a tracking issue for upgrading `winit` itself, or a process, or someone usually handling it? Note that a `winit` version with that feature did **not** release yet, but that should happen soon I guess.

**Comment by alice-i-cecile** [comment]
#10702 just bumped the winit version to the latest release :) For the next release, whoever wants to can claim it. Just split apart the "minimal migration" from the "use new feature" for easier reviews.

**Comment by eero-lehtinen** [comment]
Winit maintainers said that the changes won't be released in a patch version, so we might need to wait for a while. They also want to bake the feature a little bit more.

**Comment by benfrankel** [comment]
Custom cursor tracking issue: https://github.com/rust-windowing/winit/issues/3306.

**Comment by eero-lehtinen** [comment]
Custom cursors are already released in 0.30 and work fine. The tracking issue is just for improvements. So this issue is ready to be implemented.
