### ISSUE TITLE
Remove the `Val::try_*` arithmetic functions

### ISSUE THREAD

**Issue by ickshonpe** [bevyengine/bevy#9571]
## What problem does this solve or what need does it fill?

Wondering if these are useful at all, or even make sense.
They aren't used internally or in any of the examples. 

```
let mut r = UiRect::new(Val::Px(10.), Val::Percent(5.), Val::Auto, Val::VMin(50.));

// Just feels like nonsense; they don't compose or handle failure well
r.left.try_sub_assign(Val::Px(10.).unwrap();
r.right = r.right.try_add(Val::Px(10.)).unwrap_or(r.right.try_add(Val::Percent(10.)));
```

The `try_*_assign_with_size` functions seem problematic too:
```
r.bottom.try_add_assign_with_context(Val::Px(50.), 100., vec2(800., 600.));
```

`r.bottom` equals `Val::VMin(50.)` and is resolved to `600. * 50. / 100. = 300.`. 

So `r.bottom` is assigned the value: `Val::Px(350.)`.

This might seem like it's okay. But now `r.bottom` is no longer responsive to changes in the viewport size.

**Comment by 772** [comment]
I use try_add_asign() to move some background cloud images in my game from the right side to the left side.

```
fn move_background_cloud_images(
    mut background_images: Query<&mut Style, With<IsBackgroundImage1>>,
    time: Res<Time>,
) {
    let speed = 10.0;
    for mut image in background_images.iter_mut() {
        image
            .left
            .try_sub_assign(Val::Px(speed * time.delta_seconds()))
            .unwrap();
        let Val::Px(bar) = image.top else { unreachable!() };
        if bar < -1000.0 {
            image.left.try_add_assign(Val::Px(1000.0)).unwrap();
        }
    }
}
```

I agree that unimportant functions should be removed from the engine. And there are likely other ways to to what I did, but this is what I came up with using bevy docs.

**Comment by alice-i-cecile** [comment]
I'm fine to defer to you and remove these.

**Comment by ickshonpe** [comment]
>
> I agree that useless functions should be removed from the engine. And there are likely other ways to to what I did, but this is what I came up with using bevy docs.

Thats a really helpful example. Rewritten using pattern matching it feels much more natural to me (hopefully I understood the intent of your code correctly):

```
fn move_background_cloud_images(
    mut background_images: Query<&mut Style, With<IsBackgroundImage1>>,
    time: Res<Time>,
) {
    let speed = 10.0;
    for mut style in background_images.iter_mut() {
        match style.left {
            Val::Px(ref mut bar) => {
                *bar -= speed * time.delta_seconds();
                if *bar < -1000. {
                    *bar += 1000.;
                }
            }
            _ => { unreachable!() }
        }
    }
}
```

**Comment by 772** [comment]
Yes, that does the same job. Sorry for the poor variable name.

**Comment by ickshonpe** [comment]
> I'm fine to defer to you and remove these.

Definitely think this is the way to go. They seem actively unhelpful and confusing.
