### ISSUE TITLE
Loaded Mesh::new(PrimitiveTopology::TriangleList) disappear/appear randomly 

### ISSUE THREAD

**Issue by davids91** [bevyengine/bevy#9572]
## Bevy version

0.11.2

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- the Rust version you're using (you can get this by running `cargo --version`)
  - Bevy relies on the "latest stable release" of Rust
  - nightly should generally work, but there are sometimes regressions: please let us know!
- the operating system or browser used, including its version
  - e.g. Windows 10, Ubuntu 18.04, iOS 14

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.
AdapterInfo { name: "AMD Radeon RX 6650 XT (RADV NAVI23)", vendor: 4098, device: 29679, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 23.1.5", backend: Vulkan }

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

- [`wgpu`](https://github.com/gfx-rs/wgpu) for rendering problems
- [`winit`](https://github.com/rust-windowing/winit) for input and window management
- [`gilrs`](https://docs.rs/gilrs/latest/gilrs/) for gamepad inputs

## What you did

Generated 

## What went wrong

Textured meshes on screen disappear/appear based on camera view.
(Please read Additional information, I would like to expand this section once I can reproduce the issue) 

## Additional information

![image](https://github.com/bevyengine/bevy/assets/4211067/4eb0af44-2c44-4ae0-ba53-c6683f9f0699)
![image](https://github.com/bevyengine/bevy/assets/4211067/74176107-56bc-4db1-b2e5-7ed95ce8082a)

I tried to reproduce this but to no success.. I isolated a minimal mesh display  without textures, but there 
I couldn't reproduce the issue.  I am actually at a loss how to reproduce this, as the meshes are generated by a random function and it only seem to affect the meshes I manually add. 

I would think it is related to frustum based display cuts, because the meshes disappearing are temporary, and only seems to do it if some part of them are out of the field of view.  See screen below(relevant part is at bottom right):
 
![image](https://github.com/bevyengine/bevy/assets/4211067/da3a6c02-ded5-4df5-9728-e9ab4b40bbff)
 
![image](https://github.com/bevyengine/bevy/assets/4211067/c5d4b8f2-e9ef-4892-b546-e43a6d4ce3bb)

Are there any tips on how can I reproduce the problem? I've set up an environment fairly isolated for this, so if I can reproduce it I'd be more than happy to post a minimal example of it, right now I'm just not sure about the next steps.

**Comment by Lemonzyy** [comment]
It could be frustum culling that is causing that if your generated meshes doesn't have a correct AABB.
By any chance, are you updating the mesh handle / mesh asset after spawning the entity? If so, it may be related with the issue #4294.

**Comment by davids91** [comment]
What I do is to generate different meshes ( for every n*n*n square) with an Asnyc Task. This task is placed inside an entity, and when done, it switches the optionally already available meshes with the new ones, or insert the new meshes. ( physics mesh and display ) .

I think the issue you linked might be related to it!

**Comment by davids91** [comment]
Confirmed! The workaround there fixed the problem ( briefly tested it, once I confirmed for sure I'Ll close this issue ); Thank you so much!
