### ISSUE TITLE
Bevy Doesn't work

### ISSUE THREAD

**Issue by sk-1197897** [bevyengine/bevy#9574]
## Bevy version 0.11.2

The release number or commit hash of the version you're using.

If you cannot get Bevy to build or run on your machine, please include:

- cargo 1.72.0 (103a7ff2e 2023-08-15)
  - Debain 11

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

```ignore
```AdapterInfo { name: "virgl (Mesa Intel(R) UHD Graphics (TGL GT2))", vendor: 65541, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }

You should also consider testing the examples of our upstream dependencies to help isolate any setup-specific issue:

2023-08-25T15:04:35.441084Z  WARN bevy_pbr::ssao: ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.

2023-08-25T15:04:35.496849Z ERROR wgpu_core::device: surface configuration failed: incompatible window kind    

This error pops up when running examples or programs

**Comment by Elabajaba** [comment]
I see it's using virgl. Are you running it in a vm, or some headless x11 forwarding setup?

**Comment by jimmcnulty41** [comment]
I saw a similar error (`ERROR wgpu_core::device: surface configuration failed: incompatible window kind`) while investigating 
#9590 . Seems related

**Comment by sk-1197897** [comment]
I am running it in a VM

**Comment by rparrett** [comment]
I would imagine this is an issue with [virgl](https://gitlab.freedesktop.org/virgl/virglrenderer) or [wgpu](https://github.com/gfx-rs/wgpu).

Could you try some of the wgpu examples to narrow it down? I would try `skybox` and `cube` at the very least.

Are you able to setup gpu passthrough or something? Sorry, I am not very familiar with VMs. Is this qemu or some other VM?

**Comment by Elabajaba** [comment]
Should maybe also consider using venus as well instead of virgl as vulkan tends to work better/is more supported when using bevy than gl.

**Comment by james7132** [comment]
Was this issue upstreamed to either virgl or wgpu? Either way, it doesn't look like this is actionable on Bevy's end. Closing this out for now.
