### ISSUE TITLE
Allow non-static references as system Input in systems that are ran directly

### ISSUE THREAD

**Issue by ItsDoot** [bevyengine/bevy#9584]
## What problem does this solve or what need does it fill?

Directly ran systems (i.e. one-shot systems) currently effectively require a `'static` bound on the `System::In` associated type, preventing one from passing (non-`'static`) references as input to a system via `System::run`: https://github.com/bevyengine/bevy/blob/365cf3114a8756f3fcc7e1d783df01a079bc6e0c/crates/bevy_ecs/src/system/system.rs#L63

Being able to pass non-`'static` references to one-shot systems would likely allow us to create full systems as `egui` widgets, an extension of #5522's rudimentary `WidgetSystem` into full-featured (exclusive) `System`s, for example.

Given that `System::In` is only ever used as a function argument, it *should* be possible to implement this in a way that doesn't lose trait objects? I did some experimental implementing of this recently by turning it into a GAT, but ran into the trait object issue and haven't attempted since.

## What solution would you like?

For systems that are ran directly (one-shot systems), allow passing non-`'static` references as system input.

## What alternative(s) have you considered?

Clone objects that need to be passed in. This doesn't work for all cases, though.

**Comment by ItsDoot** [comment]
Here's a sample showing that `'static` is required:

```rust
use bevy::{ecs::system::BoxedSystem, prelude::*};

pub struct Callback<In, Out> {
    initialized: bool,
    system: BoxedSystem<In, Out>,
}

impl<In: 'static, Out: 'static> Callback<In, Out> {
    pub fn new<M>(system: impl IntoSystem<In, Out, M>) -> Self {
        Self {
            initialized: false,
            system: Box::new(IntoSystem::into_system(system)),
        }
    }

    pub fn is_initialized(&self) -> bool {
        self.initialized
    }

    pub fn run(&mut self, world: &mut World, input: In) -> Out {
        if !self.initialized {
            self.system.initialize(world);
        }

        let output = self.system.run(input, world);
        self.system.apply_deferred(world);

        output
    }
}
```

Try removing the `'static` bounds on the `impl` block.

**Comment by ItsDoot** [comment]
Dang, seems like we're blocked by https://github.com/rust-lang/rust/issues/81823 for now, if the solution requires GATs.

**Comment by SkiFire13** [comment]
GATs may not be needed if we move the `In` associated type to a generic of `System`, kinda like how it's done for the `Fn*` traits. This way you would be able to have a `for<'a> System<&'a Foo, Out = &'a Bar>` which would be callable with non `'static` inputs and even get non-`'static` outputs that borrow from the input. A downside of this is that some things may not be able to take advantage of it (e.g. `System::register_system`, though I don't see how it would work with GATs either).
