### ISSUE TITLE
The window pops up and disappears immediately

### ISSUE THREAD

**Issue by mucahitkurtlar** [bevyengine/bevy#9599]
## Bevy version

0.11.2

### Cargo Version
1.72.0

### Rendering Platform
```ignore
`AdapterInfo { name: "AMD Radeon RX Graphics", vendor: 4098, device: 26607, device_type: DiscreteGpu, driver: "AMD open-source driver", driver_info: "2023.Q2.3 (LLPC)", backend: Vulkan }`
```

## What you did

I tried some window application examples but none of them worked on my machine. It just creates a window and breaks.

## What went wrong

The window pops up and disappears immediately.

## Additional information

 The outout of `cargo run --example clear_color` is here.
```
2023-08-27T19:51:55.754191Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-08-27T19:51:55.754706Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1.1666666666666667    
ac_compute_device_uuid's output is based on invalid pci bus info.
2023-08-27T19:51:56.381952Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX Graphics", vendor: 4098, device: 26607, device_type: DiscreteGpu, driver: "AMD open-source driver", driver_info: "2023.Q2.3 (LLPC)", backend: Vulkan }
2023-08-27T19:51:56.556052Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux rolling Arch Linux", kernel: "6.4.11-arch1-1", cpu: "AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx", core_count: "4", memory: "13.6 GiB" }
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost
', /home/allesfresser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:734:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (2)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', crates/bevy_render/src/pipelined_rendering.rs:143:45
```

[This issue](https://github.com/bevyengine/bevy/issues/8936) seems related my problem.

**Comment by alice-i-cecile** [comment]
Which OS are you on?

**Comment by mucahitkurtlar** [comment]
> Which OS are you on?

Arch GNU Linux

**Comment by alice-i-cecile** [comment]
Can you get the examples in either winit or wgpu working?

**Comment by mucahitkurtlar** [comment]
> Can you get the examples in either winit or wgpu working?

Thanks for assist to find the problem. I tried few [winit](https://github.com/rust-windowing/winit) example without a problem. Then tried [cube](https://github.com/gfx-rs/wgpu/tree/trunk/examples/cube) example on [wgpu](https://github.com/gfx-rs/wgpu) but no luck. It throws an error like
```
ac_compute_device_uuid's output is based on invalid pci bus info.
Using AMD Radeon RX Graphics (Vulkan)
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost
', wgpu/src/backend/direct.rs:771:18
```

So I searched for the `ac_compute_device_uuid's output is based on invalid pci bus info` and saw [this](https://bbs.archlinux.org/viewtopic.php?id=287174) thread on Arch Forum. I understand it's about the AMD Vulkan drivers. I've read [this](https://www.reddit.com/r/vulkan/comments/12cl3e2/help_with_invalid_pci_bus_info_error_on_ubuntu/) and [this](https://www.reddit.com/r/linux_gaming/comments/h8b7zv/amd_gpu_vulkan_driver_how_to_easily_switch/) posts on Reddit. So in summary switching `AMDVLK` to `RADV` fixed my problem.

Now I know it's not Bevy related problem but I wrote it in detail in case it happens to anyone else. Thanks again. :smiley:
