### ISSUE TITLE
Rename `EventReader::iter`

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#9624]
Agreed. I am also in favor of renaming `.iter()` to something clearer like `.read()`. Having a function named `.iter()` that modifies state has always rubbed me the wrong way.

_Originally posted by @JoJoJet in https://github.com/bevyengine/bevy/pull/9583#pullrequestreview-1597040569_

**Comment by JoJoJet** [comment]
One objection I foresee is that calling it 'read' also implies a read-only operation. However, `read` being a stateful operation is idiomatic rust: see `std::io::Read` as one example.

**Comment by EmiOnGit** [comment]
Issue has been resolved by #9631 and could therefore be closed
