### ISSUE TITLE
Add a const constructor for the default handle

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#9633]
## What problem does this solve or what need does it fill?

I want to create a constant text style with the default font for use in prototypes and examples.

`Handle::default()` is not constant though, so I can't do it.

## What solution would you like?

Extract the code used to call `Handle::default()` currently, expose it as a helpfully named `Handle::UNLOADED` constant, and then use that constant in the `Default` impl, mentioning where it's from in the trait impl documentation.

## What alternative(s) have you considered?

Just use a resource to store this.

**Comment by alice-i-cecile** [comment]
The default handle doesn't use the default font. Instead, you need to use the default provided by `TextStyle`.

**Comment by mockersf** [comment]
if you need a const for the default font handle, you can try [`DEFAULT_FONT_HANDLE`](https://docs.rs/bevy/latest/bevy/text/constant.DEFAULT_FONT_HANDLE.html)
