### ISSUE TITLE
Allow Children query to have zero members

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#9642]
## What problem does this solve or what need does it fill?

Currently when querying an entity which may or may not have children (for example, walking a tree), you have to write the query like this:

```rust
    mut view_query: Query<(&mut MyComponent, Option<&Children>)>,
```

In other words, `Children` has to be optional because otherwise the query won't return entities that have no children. However, this makes processing inconvenient because now you have to unwrap the children list.

## What solution would you like?

I'd like to have the ability to query `Children` and always have it return a result. If the entity has no children, it will return a zero-length list. For backwards-compatibility, this could be a different predicate, perhaps `ChildrenList` or something.

## What alternative(s) have you considered?

For now, I'm using conditional logic:

```rust
let children = match view_query.get(parent) {
    Ok((_, Some(ch))) => ch,
    _ => &[],
};
```

However, it would be nice to get rid of boilerplate like this.

**Comment by alice-i-cecile** [comment]
Hmm. I'm strongly opposed to special-casing this. The alternative is to keep empty `Children` components around? But then we lose the ability to query for "all entities with at least one child".

**Comment by JoJoJet** [comment]
Note that you can create a custom `WorldQuery` that does this.

```rust
#[derive(WorldQuery)]
pub struct Kids {
    children: Option<Children>,
}

impl Deref for Kids {
    type Target = [Entity];
    fn deref(&self) -> &Self::Target {
        self.children.map_or(&[], |c| &*c)
    }
}
```

**Comment by viridia** [comment]
Closing issue. It was "only a suggestion".
