### ISSUE TITLE
Add a flag to hide bounding box gizmos

### ISSUE THREAD

**Issue by JoJoJet** [bevyengine/bevy#9643]
## What problem does this solve or what need does it fill?

The `AabbGizmo` component provides a very easy way of visualizing an entity's bounding box. However, the only way to hide the bounding box is to remove the component.

## What solution would you like?

Add a boolean flag to the `AabbGizmo` component that allows toggling the visibility. This should default to being shown.

## What alternative(s) have you considered?

Just keep adding and removing the component when I need to toggle visibility.

## Additional context

Any other information you would like to add such as related previous work,
screenshots, benchmarks, etc.

**Comment by Fedron** [comment]
I would like to have a go at this as my first contribution to bevy! :)
