### ISSUE TITLE
some prepare_systme performance exhibits anomalies in certain scenarios.

### ISSUE THREAD

**Issue by re0312** [bevyengine/bevy#9661]
## Bevy version
main
Windows 11  rust 1.72.0
 { name: "NVIDIA GeForce RTX 4070 Ti", vendor: 4318, device: 10114, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "528.49", backend: Vulkan }

## What you did
run many_foxes stress test with directional_light removed and increase foxes number to 100,000

## What went wrong
some system such as prepare_cluters,prepare_fog take far more time than expected (takes 15ms in write buffer)

- screenshots
![image](https://github.com/bevyengine/bevy/assets/45868716/6119e74e-f46a-4458-99cf-fb561cf2b20d)

**Comment by alice-i-cecile** [comment]
I've seen the assorted `prepare` systems take a large amount of time in my projects as well. From what I was told, this is due to the way that they block, waiting on all data to be uploaded to the GPU.

**Comment by superdump** [comment]
Yup. They get blocked writing to buffers that are in use by the GPU. At some point I want to try having a rotation of buffers to see if that helps for dynamic data that is updated every frame.

**Comment by alice-i-cecile** [comment]
I'm going to close this as "unactionable known issue", but we will keep working to improve this!
