### ISSUE TITLE
Text2d is broken

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#9676]
## Bevy version

main, since #9236

## What you did

`cargo run --example text2d`

## What went wrong

No text shows up.

## Additional information

This is a known issue, but not yet documented here on GitHub. I'm posting here so there's a place for discussion and to point to in other issues/PRs and so that it's not forgotten.

From discord:

> the queue_sprites is checking against visible_entities in order to determine whether it renders each sprite and since we are using a sparseset for sprites the text2d individual glyphs get assigned new entity ids that don't match the original Text2dBundle so they are considered not visible. Ideally we have a better way of storing text glyphs for both ui and 2d (and eventually 3d) so we don't have to spawn a bunch of empty entities. 

> (this doesn't currently affect UI text as it is clipped later rather than using visible_entities)

**Comment by mockersf** [comment]
also example `gamepad_viewer`, probably for the same reasons

**Comment by rparrett** [comment]
Yeah, should apply to any example utilizing Text2d: 

```
gamepad_viewer
text_input
many_glyphs
text_pipeline
external_source_external_thread
text2d
```
