### ISSUE TITLE
Mesh renders offset at incorrect position during movement, then snap back when movement ends

### ISSUE THREAD

**Issue by spoorn** [bevyengine/bevy#9682]
## Bevy version

0.11.2

## \[Optional\] Relevant system information

cargo 1.71.1 (7f1d04c00 2023-07-29)

```ignore
2023-09-03T11:44:41.206922Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 4070", vendor: 4318, device: 10118, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "537.13", backend: Vulkan }
2023-09-03T11:44:41.499007Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 10 Pro", kernel: "19045", cpu: "AMD Ryzen 5 5600X 6-Core Processor", core_count: "6", memory: "31.9 GiB" }
```

## What you did

Created a player character entity, with a `SceneBundle` attached to it using a gltf/glb asset to spawn in a bunch of meshes.  I made the character move, and had the camera follow the character's position from above.

## What went wrong

While moving, the character meshes would render at an offset ahead of the actual position (`Translation`) of the entity.  At the end of the movement, the rendered meshes would snap/jump back to the correct position.  
When I render in colliders (via `bevy_rapier`) and a world (for a better frame of reference), some runs will show the same behavior above, but the collider that's attached to the character entity is at the correct position during the movement (ignore the small jitters, they're unrelated):

https://github.com/bevyengine/bevy/assets/12925899/a17bf223-8333-4885-9af3-e971bf24cd52

But sometimes when I re-run, the character meshes will be in the correct position, but the collider is now at an offset trailing behind the correct position:

https://github.com/bevyengine/bevy/assets/12925899/9c94b834-79e6-409a-9534-26f74cb0146a

This happens even if I disable `bevy_rapier` and only spawn in the single character scene:

https://github.com/bevyengine/bevy/assets/12925899/90208377-b864-435a-b529-cd6e1f035400

I verified via print statements that the camera and character `Transform.translation`s are correct and the positions themselves are not jumping at the end of movement.

```
player position: Vec3(120.5, 0.0, 150.0)
camera position: Vec3(120.5, -5.0, 160.0)

player position: Vec3(121.0, 0.0, 150.0)
camera position: Vec3(121.0, -5.0, 160.0)

player position: Vec3(121.5, 0.0, 150.0)
camera position: Vec3(121.5, -5.0, 160.0)

player position: Vec3(122.0, 0.0, 150.0)
camera position: Vec3(122.0, -5.0, 160.0)

player position: Vec3(122.5, 0.0, 150.0)
camera position: Vec3(122.5, -5.0, 160.0)

player position: Vec3(122.5, 0.0, 150.0)
camera position: Vec3(122.5, -5.0, 160.0)

player position: Vec3(122.5, 0.0, 150.0)
camera position: Vec3(122.5, -5.0, 160.0)

player position: Vec3(122.5, 0.0, 150.0)
camera position: Vec3(122.5, -5.0, 160.0)
```

I'm wondering if bevy is not rendering all children of an entity at the same transform at every frame?  meaning sometimes the character's meshes are slightly offset from the root entity's position, but other times the collider which is also attached to the character's root entity is offset instead, and then bevy triggers a correction a few frames later?  

Both the Collider and the character meshes are attached to the same entity.

**Comment by rparrett** [comment]
The current release of `bevy_rapier` has a bug where the debug renderer lags behind 1 frame.

https://github.com/dimforge/bevy_rapier/issues/403

But also, for a follow camera to work without a 1 frame delay, your system needs to run after `PhysicsSet::Writeback` but before `TransformSystem::TransformPropagate` which are in the `PostUpdate` schedule.

Something like
```rust
app.add_systems(
    PostUpdate,
    follow
        .after(PhysicsSet::Writeback)
        .before(TransformSystem::TransformPropagate)
);

**Comment by spoorn** [comment]
@rparrett worked like a charm, thanks for the pointers!

Is this documented anywhere?  Maybe a bevy follow camera example would be nice

**Comment by rparrett** [comment]
I'm now aware of any place where this is explicitly documented.

I think the most appropriate place would be in `bevy_rapier`'s docs. Bevy can't really add examples involving third party plugins due to the circular dependency.

**Comment by spoorn** [comment]
I meant for the follow camera, is this only relevant when bevy_rapier is present?  Or would the follow camera always have to be ran before `TransformSystem::TransformPropagate`?

**Comment by rparrett** [comment]
This is necessary because `bevy_rapier` is doing its thing in the `PostUpdate` schedule. Typically, user systems are running in the `Update` schedule, so they don't need to explicitly specify that ordering.
