### ISSUE TITLE
Using TAA causing panic when  entity is despawned

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#9721]
### Discussed in https://github.com/bevyengine/bevy/discussions/9719

<div type='discussions-op-text'>

<sup>Originally posted by **PatrickChodowski** September  8, 2023</sup>
Hello,

I added TAA to my game and I noticed it causes panic whenever I reload the scene or randomly when one of entities gets despawned:

```
thread 'main' panicked at 'error[B0003]: Could not insert a bundle (of type `bevy_pbr::prepass::PreviousGlobalTransform`) for entity 21v0 because it doesn't exist in this World.', /home/patrick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.2/src/system/commands/mod.rs:957:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic when applying buffers for system `bevy_pbr::prepass::update_mesh_previous_global_transforms`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

Is there a way to avoid it? Should I set the TemporalAntiAliasSettings::reset to true everytime I am about to despawn entities? Or maybe there is a way for TAA to not track certain entities? Thank you for help
</div>

**Comment by JMS55** [comment]
Fixed by https://github.com/bevyengine/bevy/pull/10200
