### ISSUE TITLE
WindowDescriptor resizable ignored when false

### ISSUE THREAD

**Issue by Luminoth** [bevyengine/bevy#975]
**Bevy version**

0.3

**Operating system & version**

Ubuntu 20.04 (XFCE window manager)

**What you did**

Simple example:

```
use bevy::prelude::*;

fn main() {
   App::build()
        .add_resource(WindowDescriptor {
            title: "NO Resize".to_owned(),
            width: 1024,
            height: 768,
            vsync: true,
            resizable: false,
            ..Default::default()
        })
        .add_plugins(DefaultPlugins)
        .run();
}
```

**What you expected to happen**

Window should not be resizable

**What actually happened**

Window is resizable

**Additional information**

Not sure what else would be useful here. The window size and title seem to be setting correctly. I've also tried it on Pop_OS! 20.04 (XFCE window manager) with the same result.

**Comment by Moxinilian** [comment]
Could somebody try to reproduce this on a different platform?

**Comment by Luminoth** [comment]
If not, I can give it a shot later tonight when I'm able to get on a different PC.

**Comment by Luminoth** [comment]
Ok, gave that same example a test in Win10 @Moxinilian and it worked as expected - I was unable to resize the window. Looks like it might be just a Linux issue?

**Comment by amberkowalski** [comment]
In my experience Linux window management solutions do what they please, resizing wise.

**Comment by cart** [comment]
On Arch/Gnome3 I can't resize windows when this flag is set. Sounds like something specific to XFCE. This sounds like its either:

1. A winit issue where it can't send a signal XFCE understands
2. An XFCE issue where winit sends the correct signal but XFCE ignores it.

I recommend looking into to XFCE to see if this is a common issue and if not, filing an issue on the winit repo.

**Comment by Luminoth** [comment]
Indeed it does look to be the case, from the winit source:

```
...
    /// Due to a bug in XFCE, this has no effect on Xfwm.
...
    #[inline]
    pub fn set_resizable(&self, resizable: bool) {
        self.window.set_resizable(resizable)
    }
```
