### ISSUE TITLE
Add UntypedHandle::default()

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#9773]
## What problem does this solve or what need does it fill?

When reading in assets using the new V2 asset framework, I sometimes need to deserialize a reference to an asset, where the type of the asset is not yet known. Because I'm using serde for deserialization, initially all I have to work with is a string, not a handle, because the asset server is not available within a context of a deserializer. So any handle fields have to be left blank. These are then filled in later, via a second pass which walks the tree and fills in any empty handles from the path strings. This works fine for typed handles, but doesn't work for untyped handle because there's no way to create a default untyped handle. I could use Option, but this is inconsistent with the way typed handles are treated.

## What solution would you like?

Implement `Default` for untyped handles.

## What alternative(s) have you considered?

For now what I am doing is deferring the loading of untyped handles until the asset is actually used, at which point the type of the asset is known. However, this solution is inferior because it means that the asset can't keep a strong handle, nor can it declare a dependency on the referenced asset. This can cause extra loading to occur.

**Comment by NiklasEi** [comment]
#10198 adds a `load_untyped` function. It returns a handle to a `LoadedUntypedAsset` which depends on the asset at the given path and contains a handle for it. If you would use this instead, the assets would start loading already and you could resolve the `LoadedUntypedAsset` to the correct handles in a second step once they are loaded.
I think default untyped handles might be a bit of a foot gun here. They will not cause any loads and are not at all related to the actual asset.
