### ISSUE TITLE
Terminal outputting ALSA function 'snd_pcm_poll_descriptors' failed with error 'UnknownErrno: Unknown errno'

### ISSUE THREAD

**Issue by samuelwatsonofficial** [bevyengine/bevy#9798]
## Bevy version 0.11
##archlinux with sway and pulseaudio
I used the line2d function in a piece of code here https://pastebin.com/VdShgSSJ.

The console started outputting 
"an error occurred on output stream: A backend-specific error has occurred: ALSA function 'snd_pcm_poll_descriptors' failed with error 'UnknownErrno: Unknown errno'" very fast, this has not caused any issues for me besides clogging up the console, I'm happy to show any logs or do any testing if needed.

The code I am using makes no audio calls and shouldn't be interacting with ALSA

**Comment by alice-i-cecile** [comment]
Does this still happen with default features disabled for Bevy?

**Comment by alice-i-cecile** [comment]
Ah no, I meant "we should make sure Bevy's audio features are disabled"!

See: https://doc.rust-lang.org/cargo/reference/features.html#the-default-feature

In this case, try changing the exact features of Bevy that you rely in, starting with `default_features = false` and then progressively enabling the features needed to make your code compile.

**Comment by samuelwatsonofficial** [comment]
Building and running with the Cargo.toml as [dependencies] bevy = { version = "0.11", default-features = false } runs with no errors whatsoever however i had to remove everything except running the app to make it compile without any complaints. I'm currently trying to add use:bevy for all the features but can't seem to find what the import paths for Gizmos, Color or Camera2dbundle are.

**Comment by alice-i-cecile** [comment]
Check out the features list [here](https://github.com/bevyengine/bevy/blob/main/Cargo.toml). I suspect you'll need `bevy_gizmos` and `bevy_core_pipeline`.

**Comment by mockersf** [comment]
While setting the correct features is the correct way for long term as it improves performances and reduces build time, I tried a "fix" in https://github.com/bevyengine/bevy/pull/9811. This PR should delay the interaction with ALSA until you actually try to play audio

**Comment by samuelwatsonofficial** [comment]
Thanks both of you this is huge! I'm glad bevy has such active maintainers

**Comment by alice-i-cecile** [comment]
Closing as won't fix, since there's a good workaround (don't include features you don't need), and the spawn-as-needed fix introduces unacceptable lag.

**Comment by maufl** [comment]
I have the same problem now and I tried to follow the workaround but wasn't successful (bevy version 0.16.1). Simply disabling the default features and not including `bevy_audio` doesn't work, somehow `bevy_internal` still requires it, probably because of some other feature. (The [code is here](https://github.com/maufl/gaia-generate))

**Comment by alice-i-cecile** [comment]
@maufl can you open a new issue with a reproduction for the unwanted inclusion? We shouldn't be pulling in alsa with audio disabled.

**Comment by maufl** [comment]
False alarm, but I'm leaving this as a hint for other people. I had added https://github.com/DGriffin91/bevy_basic_camera which depends on `bevy` without specifying the features it needs, thus pulling in the default features ... So check your other dependencies which might depend on bevy.
