### ISSUE TITLE
Currently doesn't compile on windows

### ISSUE THREAD

**Issue by Dispersia** [bevyengine/bevy#98]
Hello, under https://github.com/bevyengine/bevy/commit/4393af5e25424da21517836d7c3f0e57424d0548 it is using a feature of winit (with_drag_and_drop(false)) that isn't in the released version yet. Is it ok to make winit depend on git version or do you typically republish with those changes? I see there is no git reference, but you did the above for wgpu

**Comment by cart** [comment]
Uh oh we should definitely fix that asap. I'd prefer to fix the version on crates.io too, which would require a non-git fix. Worst case scenario we can publish a temporary updated version of winit.

I'm booting into windows now :smile:

**Comment by cart** [comment]
I think I fixed it (both on crates.io and master). I'm about to boot back into windows to test. You might need to delete your Cargo.lock to pick up the fix

**Comment by cart** [comment]
Yup works for me (and you affirmed it works for you too on discord)

resolved by: 6db89da324895df8f9aed0dd4803f500e7abc52e
