### ISSUE TITLE
SMAA (Sub-pixel morphological antialiasing) support

### ISSUE THREAD

**Issue by yhslai** [bevyengine/bevy#9819]
## What problem does this solve or what need does it fill?
Feature: Support SMAA (Sub-pixel morphological antialiasing). It's a pracital implementation of MLAA (Morphological antialiasing).
Use Case: As far as I know, It's the best antialiasing that based on full-screen postprocessing only. It has the following advantages:

1. No temporal blur. TAA is a quite big trade-off: sometimes it looks absolutely amazing, sometimes horribly blur. There is even a dedicate subreddit for complaining about TAA: [/r/fuckTAA](https://www.reddit.com/r/FuckTAA/).
2. Render pipeline independent: Unlike MSAA, SMAA doesn't need you to change anything on the render pipeline. It's truly just a post-processing effect. Forward or deferred rendering doesn't matter.
3. Anti-aliasing on texture: MSAA only anti-aliases the boundaries of triangles. SMAA anti-aliases the aliasing cause by low-res textures too. (Of course it's a trade-off as well. Sometimes you don't want that.)
4. Looks better than FXAA: well never mind, anything looks better than FXAA.

## What solution would you like?

Implement a SMAA post processing effect.

## What alternative(s) have you considered?

TAA, MSAA, FXAA. But as I stated, SMAA has unique advantages over them.

## Additional context

Official SMAA implementation: https://github.com/iryoku/smaa (MIT license)
Paper: http://www.iryoku.com/smaa/
3D Graphics Discussion: https://github.com/bevyengine/bevy/discussions/4630 (I'm not sure if I should just posted there, but some items in that post link to separate issuse so I assume it's fine to open a new issue for further discussion/details)

**Comment by alice-i-cecile** [comment]
Pulling this out into its own issue was the right idea :) Much easier to track this way.

**Comment by superdump** [comment]
I think @jakobhellermann had implemented SMAA a while ago.

**Comment by Elabajaba** [comment]
CMAA2 is a newer and faster SMAA alternative, but is worse at actually removing aliasing (and has a few other tradeoffs vs SMAA).

Also note that SMAA won't fix specular aliasing or temporal instability (though there is SMAA T2x which iirc uses the previous frame and motion vectors for a basic single history frame TAA), and specular aliasing tends to be a major problem with PBR materials.

https://www.intel.com/content/www/us/en/developer/articles/technical/conservative-morphological-anti-aliasing-20.html
https://github.com/GameTechDev/CMAA2
