### ISSUE TITLE
Flex does not center the node and node does not respond to height change in window.

### ISSUE THREAD

**Issue by Hossein-Noroozpour** [bevyengine/bevy#9841]
In version "0.11.2"

I wanted to place an image in the centre and keep its height 100% of the window and width proportional to the height (keep the aspect)

This is the equivalent of flex in CSS.
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .image-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .image {
            width: auto;
            height: 100%;
        }
    </style>
</head>
<body>
<div class="image-container">
    <img class="image" src="../assets/ui/main-menu.png" alt="Image">
</div>
</body>
</html>
```

but the behaviour in Bevy is different:

```
use bevy::prelude::*;

fn setup_camera(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
}

fn setup_ui(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands
        .spawn(NodeBundle {
            style: Style {
                height: Val::Vh(100.0),
                display: Display::Flex,
                align_items: AlignItems::Center,
                justify_content: JustifyContent::Center,
                ..default()
            },
            ..default()
        })
        .with_children(|parent| {
            parent.spawn(ImageBundle {
                style: Style {
                    height: Val::Percent(100.0),
                    width: Val::Auto,
                    ..default()
                },
                image: UiImage::new(asset_server.load("ui/main-menu.png")),
                ..default()
            });
        });
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup_camera)
        .add_systems(Startup, setup_ui)
        .run();
}
```

**Comment by alice-i-cecile** [comment]
Can you reproduce this on this branch? https://github.com/bevyengine/bevy/pull/9637

**Comment by nicoburns** [comment]
I can reproduce this on top of #9637 (I have to add `width: Val::Vw(100.0),` to the outer node to account for the changes in #9637 and make the outer node fill the width of the screen).

Adding an explicit `aspect_ratio: Some(1.0)` style (replace `1.0` with the actual aspect ratio of your image) produces the behaviour which I believe you want / are expecting. But for some reason the image's inherent aspect ratio doesn't seem have any effect on it's final size/position.

**Comment by nicoburns** [comment]
Hmm... interestingly it also does seem to work if the parent node is `Display::Grid` (with `justify_items: JustifyItems::Center,` set)

**Comment by nicoburns** [comment]
This is indeed a Taffy bug. Fix incoming.

**Comment by nicoburns** [comment]
@Hossein-Noroozpour Taffy `v0.3.14` has been released with a fix for this issue. You can get the fix by running `cargo update`.
