### ISSUE TITLE
RenderLayers are ignored by pointlights

### ISSUE THREAD

**Issue by LIMachi** [bevyengine/bevy#9852]
## Bevy version
bevy 0.11.2

## What you did

Created 2 camera, each with a separate layer ("main", layer 0, camera supposed to be attached to a moving entity, another for UI, layer 1, fixed and using an orthonormal projection).
Created a default point light in layer 0.
Created a cube pbrbundle in layer 0. (used as visual reference, to make sure the main camera is actually working and only seeing this cube and not the other).
Created a cube pbrbundle in layer 1 with a transform to make it isometric. (supposed to be an object in inventory, similar to how minecraft renders a block in your hot bar).
Add bevy_inspector_egui plugin to manually change entities while running (could have used a system that moved the light)

## What went wrong

Expected: when moving the light, only the cube on layer 0 should have it's light/illumination change.
Result: while moving the light, both cubes on both layers reacted to it, as if the light was ignoring layers.

**Comment by rparrett** [comment]
Thanks for the report.

This is known issue being tracked in #3462.
