### ISSUE TITLE
load_gltf example not rendering

### ISSUE THREAD

**Issue by b333z** [bevyengine/bevy#986]
**Bevy version**

72b2fc98437f39a8099efcc137697efc32a21800 

**Operating system & version**

NixOS 20.09, wayland 

**What you did**

```
cargo run --example load_gltf
```

**What you expected to happen**

The model rendered

**What actually happened**

Blank screen, no model rendered

**Additional information**

@cart noticed this was in master https://github.com/bevyengine/bevy/pull/958#issuecomment-735519477 and just picked it up myself as I rebased from a week or so ago.

I did some jumping around and in-case useful just wanted to point out it looks to be introduced by 72b2fc98437f39a8099efcc137697efc32a21800 the Bevy Reflection commit, if anything there rings a bell... The commit before seems OK.

**Comment by wuyin1985** [comment]
I got the same problem. 72b2fc9 the Bevy Reflection  commit seem broken the function world.spawn_scene , the component like Draw, Mesh is ignore during the scene spawn with reflection

**Comment by b333z** [comment]
Took your fix for a spin @cart and looks all good from here, thanks!
