### ISSUE TITLE
Text wraps incorrectly for a frame after a change to its font size

### ISSUE THREAD

**Issue by ickshonpe** [bevyengine/bevy#9874]
## Bevy version

main 038d113

## What you did

```
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(Update, update)
        .run();
}

fn setup(
    mut commands: Commands,
) {
    commands.spawn(Camera2dBundle::default());
    commands.spawn(TextBundle::from("Hello, world!"));
}

fn update(
    mut text_query: Query<&mut Text>,
) {
    for mut text in text_query.iter_mut() {
        text.sections[0].style.font_size *= 1.001;
    }
}
```

## What went wrong

As the text increases in size it flickers between being displayed on one line and wrapped across two lines
It should always be on one line.

## Additional Information

Could just be a system ordering issue

**Comment by rparrett** [comment]
I think that this is scale-factor dependent. I am able reproduce on every run with e.g.
```
.add_plugins(DefaultPlugins.set(WindowPlugin {
    primary_window: Some(Window {
        resolution: WindowResolution::default().with_scale_factor_override(7. / 3.),
        ..default()
    }),
    ..default()
}))
```
But not 2.0 or 1.0.

**Comment by ickshonpe** [comment]
> I think that this is scale-factor dependent. I am able reproduce on every run with e.g.
> 
> ```rust
> app.add_plugins(DefaultPlugins.set(WindowPlugin {
>     primary_window: Some(Window {
>         resolution: WindowResolution::default().with_scale_factor_override(7. / 3.),
>         ..default()
>     }),
>     ..default()
> }))
> ```
> 
> But not 2.0 or 1.0.

Probably not a system ordering issue then, probably the bounds calculated by the measure func and the text system are different at certain scale factors. The text systems badly need more tests I think.

**Comment by rparrett** [comment]
Simplified the repro slightly, although maybe there's more going on than just this.
```rust
use bevy::{prelude::*, window::WindowResolution};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                resolution: WindowResolution::default().with_scale_factor_override(7. / 3.),
                ..default()
            }),
            ..default()
        }))
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
    commands.spawn(TextBundle::from_section(
        "Hello, world!",
        TextStyle {
            font_size: 12.02,
            ..default()
        },
    ));
}
```

<img width="640" alt="Screenshot 2023-09-22 at 11 19 37 AM" src="https://github.com/bevyengine/bevy/assets/200550/2a9d8fbf-3d2f-432d-b372-aacec074b775">

**Comment by rparrett** [comment]
Bisected above:

After #9784, text appears on two lines instead of one, but both lines are rendered.
After #9637, second line disappears
