### ISSUE TITLE
Revert change to default OrthographicProjection

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#9876]
As mentioned in the discord, this is gonna cause problems for 3d. With this objects behind the camera are going to be rendered when they shouldn’t be visible. 

Example: two xz planes, you put the camera between them pointed at one, and only the other will be visible. 

I don’t know what the proper solution is, but devil_ira pointed out this is coming in 0.12

_Originally posted by @dmlary in https://github.com/bevyengine/bevy/issues/9537#issuecomment-1727938674_
            
            
Discussed more on Discord [here](https://discord.com/channels/691052431525675048/1154114310042292325/1154115841231700018)

**Comment by alice-i-cecile** [comment]
This should be able to be done as a simple "Revert commit" PR.

**Comment by mnmaita** [comment]
Just opened https://github.com/bevyengine/bevy/pull/9878 to fix this.
