### ISSUE TITLE
Missed just_released event for the second simultaneously pressed key.

### ISSUE THREAD

**Issue by ElderJoy** [bevyengine/bevy#9890]
## Bevy version

Latest main branch commit: 1116207f7dbcc04fbcfd10eecc09e3988a4c726a from Thu Sep 21 2023

## Relevant system information

Rust rustc 1.72.0
22.04.1-Ubuntu

**Note**: Don't reproducable on my Mac.

## What you did

Press one button (Left in my case), keep it pressed, press second one (Down), then release first, then second.

## What went wrong

Second key stay pressed. Tere is no just_released event passed for the second key.

If then again press and release just single second key - release event passed.

I founf out, that event does not pass to keyboard_input_system(). Added logs there. 

## Additional information

Reproducable 100% on simplest example:
```
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Update, update_keyboard)
        .run();
}

fn update_keyboard(keyboard: Res<Input<KeyCode>>) {
    println!("keyboard: {:?}", keyboard);
}
```

Log:
```
keyboard: Res(Input { pressed: {}, just_pressed: {}, just_released: {} })
key_input.press(Left)
scan_input.press(105)
keyboard: Res(Input { pressed: {Left}, just_pressed: {Left}, just_released: {} })
keyboard: Res(Input { pressed: {Left}, just_pressed: {}, just_released: {} })
keyboard: Res(Input { pressed: {Left}, just_pressed: {}, just_released: {} })
key_input.press(Down)
scan_input.press(108)
keyboard: Res(Input { pressed: {Left, Down}, just_pressed: {Down}, just_released: {} })
keyboard: Res(Input { pressed: {Left, Down}, just_pressed: {}, just_released: {} })
keyboard: Res(Input { pressed: {Left, Down}, just_pressed: {}, just_released: {} })
key_input.release(Left)
scan_input.release(105)
keyboard: Res(Input { pressed: {Down}, just_pressed: {}, just_released: {Left} })
keyboard: Res(Input { pressed: {Down}, just_pressed: {}, just_released: {} })
keyboard: Res(Input { pressed: {Down}, just_pressed: {}, just_released: {} })
```

Looks like problem could be somehow related to my hardware/software setup, as it is not reproducable on my Mac. And once it was not reproducable on my Linux machine but then become 100% reproducable again. I wander, if it is only my issue? What can be done to diagnose issue in more deep?

**Comment by hymm** [comment]
Can you switch keyboards and test?

**Comment by ElderJoy** [comment]
Well, finally I found issue of this behavior. It is xneur keyboard layout switcher. If I stop it, keyboard works as expected. Will open ticket there.
