### ISSUE TITLE
Query-level change detection

### ISSUE THREAD

**Issue by UkoeHB** [bevyengine/bevy#9892]
## What problem does this solve or what need does it fill?

When tracking despawns, such as for replication or reactivity, it is currently necessary to iterate over a cache of tracked entities to identify ones no longer alive even if no entities have been spawned or despawned since the last time you checked.

## What solution would you like?

The ability to detect if the contents of a query in a system have changed since the last time you ran that system (not per-tick, but per-system-run).

Using `Without<Added<>>` and `Added<>` does not work because the `Added<>` list may gain/lose entities throughout a tick, so multiple invocations of the tracker system (e.g. in a reactivity framework) will not properly account for despawns.

## What alternative(s) have you considered?

- Keep iterating and hope it doesn't impact perf.

**Comment by maniwani** [comment]
Queries are the wrong place to look at for reactivity.

They have no "content" themselves. They also do not cache metadata about specific entities. Queries only cache a list of entity *archetypes*, and that cache is only updated when that list of matching archetypes changes.

There are plans to implement an observer pattern for certain types of "events" (you may have seen the word "hook" used if you're in the Discord). For an event like an entity being despawned, you'd be able to register a callback/observer that'll be called/notified whenever it happens. Then you wouldn't have to poll.
