### ISSUE TITLE
``Query::get_component`` does not respect filters

### ISSUE THREAD

**Issue by cfognom** [bevyengine/bevy#9904]
## Bevy version

0.11.2

## What you did

Created a system query: ``query: Query<&Transform, Changed<Transform>>`` and then used ``query.get_component(entity_with_unchanging_transform)``.

## What went wrong

- what were you expecting?
I expected to get no result since the query has the Changed filter.
- what actually happened?
I got a result.

## Additional information

- theories about what might be going wrong
 From looking at the source it seems like the ``Query::get_component[_mut]()`` variants are missing logic to respect the filter of the query.
 Or the name of the method fails to clarify its use. Perhaps ``get_component_ignore_filter()`` is more suitable if this is the intended behaviour.

- links to related bugs, PRs or discussions
https://github.com/bevyengine/bevy/pull/9523
https://github.com/bevyengine/bevy/issues/9011

**Comment by james7132** [comment]
As the filters can be used to ensure mutual exclusion, this is a soundness bug, and we should address this as soon as possible.

I'm actually strongly tempted to say we should remove `Query::get_component`. It's a very prominent source of unsoundness, it's nowhere near the same performance as Query::get, and the effort to patch up its soundness issues is immense compared to the utility it provides.

**Comment by cfognom** [comment]
How does ``Query::get()`` + discarding of some of the results compare to ``Query::get_component()``. If the performance of ``Query::get()`` is still better in such a case. Why not just let ``Query::get_component()`` call ``Query::get()`` internally?

**Comment by iiYese** [comment]
> How does `Query::get()` + discarding of some of the results compare to `Query::get_component()`. If the performance of `Query::get()` is still better in such a case. Why not just let `Query::get_component()` call `Query::get()` internally?

The component can be in an arbitrary position or nested deep in a worldquery. You can't solve this with metaprogramming either in the case where `Q` is a generic.

**Comment by alice-i-cecile** [comment]
I think we should remove it too. It's rarely useful as well.

**Comment by james7132** [comment]
Removing the unsoundness tag as it's only unsound if this ignores `With`/`Without` or other access based filters, where it can potentially cause aliased mutable access, which it doesn't. It simply just doesn't respect the return value on `F::filter_fetch`.

Even with this in mind, I'm still in support of removing the API since it's often a performance footgun to use over `Query::get` and discarding the unused results.

**Comment by alice-i-cecile** [comment]
Removal is discussed more in https://github.com/bevyengine/bevy/discussions/9910
