### ISSUE TITLE
Assets V2: allow UntypedHandle::default()

### ISSUE THREAD

**Issue by viridia** [bevyengine/bevy#9916]
## What problem does this solve or what need does it fill?

Currently the `Handle` type in Assets V2 supports `default()`, but `UntypedHandle` does not. The use case here is for asset loaders that deal with multiple types of assets in a single archive file - when deserializing an asset, it's sometimes necessary to have a placeholder for a handle which will get filled in once the asset has finished deserializing.

Also, adding support for `default` would make the two types of handles more consistent.

## What solution would you like?

Implement `Default` for `UntypedHandle`. The result should be effectively the same as a default handle, that is, a handle that doesn't point to anything.

## What alternative(s) have you considered?

The alternative is to wrap the handle in an `Option` and set it to `None`. However, this is cumbersome because the handle isn't actually optional, it's just deferred. Using `Option` requires every consumer of the handle to unwrap it, even though it will never be `None` after loading is finished.

**Comment by cart** [comment]
It seems like there isn't a good "default" value for `UntypedHandle` (which _is_ typed internally, it is just "dynamically typed" by storing a TypeId).

If we really want this, we would need to pick a "default asset type" for the "default untyped handle". Probably something like a new `NullAsset`. This feels a bit hackey to me. There are "real" use cases for things like `Handle<Mesh>::default()`. From my perspective there are no good use cases for `Hande<NullAsset>::default().untyped()`, and making that easily expressible with `UntypedHandle::default()` will open the door to unnecessary error cases.

This seems like a requirement that comes from a specific code flow. I'm assuming its something like:

```rust
let mut foo = deserialize_foo(input);
// bar is UntypedHandle
foo.bar = deserialize_bar(input);
```

Generally if you are deserializing a parent object that can't be constructed before its fields / children are deserialized, you just deserialize those children / fields first and then construct the parent object after they are ready.

**Comment by viridia** [comment]
I've worked around the issue for now. Part of the difficulty was due to my using serde for deserialization, because there's no way in serde to pass context to the object being deserialized; Now that I have decided to move away from serde my need for this feature is not as urgent.
