### ISSUE TITLE
Consider `Added`, `Changed`, and `AddedOrChanged` instead of `Added`, `Mutated`, `Changed`

### ISSUE THREAD

**Issue by ndarilek** [bevyengine/bevy#992]
**What problem does this solve or what need does it fill?**

I've been doing a lot more Bevy development recently, and keep hitting the following sharp edges around query operation naming:

* I regularly have to remind myself about the difference between `Mutated` and `Changed`, both when writing code and editing existing code.
* I routinely have to remind myself that `Changed` doesn't handle removed components, even though it handles added components. This just now bit me--I did a major subsystem refactor, only to realize that I'm not handling a component removal case and may have wanted to rethink things before starting along this path.

**Describe the solution would you like?**

Rename operators as follows:

* `Mutated` to `Changed`. No big reason for this one, other than the vague feeling that "changed" is a more common word and might be slightly easier for some non-English speakers to intuitively know.
* `Changed` to `AddedOrChanged`. While this is slightly more characters, it makes the supported operations very explicit. If I'm refactoring a system with queries for `AddedOrChanged`, it is instantly apparent without thought that I'm going to have to special-case removals right when I'm writing the system signature, not most of the way through the refactor when I've forgotten about it.

**Describe the alternative(s) you've considered?**

I suppose we can keep things as they are now, and eventually I'll intuitively remember the differences between these operations. But given the focus on ergonomics, I think it makes more sense to be explicit on an operation's limitations even at the cost of more characters, and to do so in 0.4 rather than 1.X. Also, to be clear, I'm not asking for a `Removed` operation. I'm just asking that existing operators' names explicitly call out their limitations.

**Additional context**

This is well-documented in many places, so the issue isn't that. It's that when you're deep in thinking about how a system works, you're thinking "I want to trigger this operation when a component changes." So you write `Changed<Component>` somewhere, and only later remember all those docs. :)

Thanks.

**Comment by mockersf** [comment]
> `Mutated` to `Changed`. No big reason for this one, other than the vague feeling that "changed" is a more common word and might be slightly easier for some non-English speakers to intuitively know.

No strong opinion here, but I feel that in rust `Mutated` is clear and can relate to the `mut` you have to use to mutate the component. it could use an alias in the docs to help discoverability

**Comment by ndarilek** [comment]
Oh, that's a great point I hadn't considered. I'm also happy with 
`Added`, `Mutated`, `AddedOrMutated`. Just dump `Changed`, then. :)

**Comment by cart** [comment]
My counterpoint is that in almost every case, the current `Changed<T>` (added | mutated) is what people actually want. Ex: anything that wants to incrementally perform an action will want to perform it on "added | mutated". Something like 95% of bevy's internal "change detection" usage is `Changed<T>`. Id like the "common" case to have a nice name.

Theres no clear cut answer here imo.

**Comment by bonsairobo** [comment]
To me, "overwrite" seems to clearly indicate that something was mutated but not added

**Comment by alice-i-cecile** [comment]
This should be revisited and hopefully resolved once #68 is solved.

**Comment by alice-i-cecile** [comment]
I think this can be closed now, since we're planning to remove `Mutated` completely with #1471.
