### ISSUE TITLE
World::resource and allies do not return Res / ResMut smart pointers

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#9926]
## Bevy version

0.11

## What you did

Called World::resource

## What went wrong

I expected a Res or ResMut smart pointer, so I could call change detection methods and reuse code more easily.

Instead I got a & or a Mut.

**Comment by A-Walrus** [comment]
Should `UnsafeWorldCell` change as well, or just `World`

**Comment by alice-i-cecile** [comment]
Yes, I think it should.

**Comment by mockersf** [comment]
Maybe not a good first issue, as getting a `Res` or a `ResMut` requires system metadata (for last run tick), and you don't have those from just a `World`.

Resource changed/added ticks can be retrieved from `get_resource_with_ticks`

**Comment by cart** [comment]
Fully on board for making APIs consistent. But as an alternative, maybe we should add `get_res` and `get_res_mut` variants? Currently not in love with the fact that we're doing unnecessary change detection state retrievals for `Res` everywhere. And doubling down on that by making resource-only-access impossible in our World APIs feels wrong to me. Looking at Bevy internals, the number of times we access Res _without_ something like `is_changed` vs the number of times we _do_ access change state is minuscule. That is work that we eat per-resource per-system per-frame.

**Comment by alice-i-cecile** [comment]
An additional argument for consistency here: you can get the change ticks for a resource from the World, but only when extracting it mutably.

**Comment by JoJoJet** [comment]
Closing in favor of #11825
