### ISSUE TITLE
Textures don't render correctly on Bistro

### ISSUE THREAD

**Issue by Elabajaba** [bevyengine/bevy#9946]
## Bevy version

b6ead2be95d8e6d955fa026a826410b640db4dbd

This appears to have started when assets v2 was merged.

## Relevant system information

`AdapterInfo { name: "AMD Radeon RX 6800 XT", vendor: 4098, device: 29631, device_type: DiscreteGpu, driver: "", driver_info: "", backend: Dx12 }`

Also happens on linux vulkan on the same system.

## What you did

Convert bistro (https://developer.nvidia.com/orca/amazon-lumberyard-bistro) to a gltf using blender, then view it with the scene viewer.

## What went wrong

The textures aren't tiling correctly.

## Additional information

The current incorrect texture rendering:

![Screenshot 2023-09-27 233257](https://github.com/bevyengine/bevy/assets/177631/6ac10ed0-1d36-4fae-8a5f-694e2682146b)

**Comment by Kanabenki** [comment]
What export settings did you use when exporting to gltf ? I tried reproducing by exporting as glb from the fbx with the default settings in blender.  When loading the scene with the scene viewer from the bevy examples on 20ed3e0e765405ee334a44ce3c49c72bd29ab753, the textures are properly tiling but I'm getting some extreme flickering from most of the meshes.

**Comment by Elabajaba** [comment]
Blender 3.6.4 is outputting broken gltfs that flicker (at least for bistro, tested in bevy and unreal 5.2). Blender 3.5.1 gltf exports work, but in bevy post assets v2 have broken texture rendering (at least for bistro).

**Comment by superdump** [comment]
Looks like embedded textures have their sampler descriptor set but loading via uri doesn’t: <https://github.com/bevyengine/bevy/blob/20ed3e0e765405ee334a44ce3c49c72bd29ab753/crates/bevy_gltf/src/loader.rs#L634>

<https://github.com/bevyengine/bevy/blob/20ed3e0e765405ee334a44ce3c49c72bd29ab753/crates/bevy_gltf/src/loader.rs#L1070> that texture_sampler() function is where the address mode is set

So the two cases which handle uris need to use that function

To make the sampler descriptor
