### ISSUE TITLE
No warning/error on invalid gltf asset label ("#")

### ISSUE THREAD

**Issue by A-Walrus** [bevyengine/bevy#9952]
## Bevy version
20ed3e0e765405ee334a44ce3c49c72bd29ab753
## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- 20ed3e0e765405ee334a44ce3c49c72bd29ab753us know!
- Linux: Fedora 38, Gnome, Wayland

## What you did
Modified this line in the example:
https://github.com/bevyengine/bevy/blob/20ed3e0e765405ee334a44ce3c49c72bd29ab753/examples/3d/load_gltf.rs#L53
replacing `Scene0` with random gibberish `asdfasdf`

## What went wrong
Expected to see some error or warning, instead the only thing that happened is no model showed up.

**Comment by hymm** [comment]
does https://github.com/bevyengine/bevy/pull/9751 fix this?

**Comment by A-Walrus** [comment]
> does #9751 fix this?

I think so

**Comment by ZainlessBrombie** [comment]
![image](https://github.com/bevyengine/bevy/assets/14111053/0ba0de72-cb1f-47a2-a991-1b766fa6a326)
Got this error when trying on the new branch, so looks good :+1:

**Comment by A-Walrus** [comment]
Closed by #11254
