### ISSUE TITLE
UI Node Collapsible

### ISSUE THREAD

**Issue by thirdq** [bevyengine/bevy#9953]
## What problem does this solve or what need does it fill?

I was thinking why there is no Visibility::Collapsed option on the Ui nodes. When you hide a node, it becomes hidden but still occupies space in the layout. But when you collapse the node it doesn't fill space in the layout anymore. There are scenarious when you want this behaviour in you app/game.

## What solution would you like?

Visibility is part of 2D/3D too so maybe creating a new component called Collapsible with a boolean and two floats: cached_width and cached_height. So when you want to reverse it from collapsed, it goes back to the previous size. Also, if you modify the size while collapsed, the Collapsible should be notified immediately maybe through a system/event to update its cached values. Also there are some other considerations such as when you collapse the parent, children should be collapsed recursively and when you revert the collapse, all its children must update too. Also you shouldn't be allowed to reverse a collapsed node if its parent is also collapsed because it can lead to bugs, such as strange rendering.

## Additional context

I implemented this functionality in my game but I thought it would be nice for Bevy to have it by default.

**Comment by alice-i-cecile** [comment]
@nicoburns, this should be possible with flexbox already using `Style`'s `Display::Hidden` setting, right?

**Comment by hymm** [comment]
https://docs.rs/bevy/latest/bevy/ui/enum.Display.html#variant.None

**Comment by nicoburns** [comment]
Yeah, `Display::None` is what you want.
