### ISSUE TITLE
sprite spawned after start is not displayed

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#996]
**Bevy version**

[git 7699f8b6db0af6ca62fcd033e05df4f6c71ecb23](https://github.com/bevyengine/bevy/commit/7699f8b6db0af6ca62fcd033e05df4f6c71ecb23) (current master at the time of this issue) - #987 

**Operating system & version**

macOS 10.15.7

**What you did**

Spawn a sprite during game when none has been displayed at start
```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .add_system(display)
        .run();
}

fn setup(commands: &mut Commands) {
    commands.spawn(Camera2dBundle::default());
}

fn display(
    commands: &mut Commands,
    mut first: Local<bool>,
    asset_server: Res<AssetServer>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    if !*first {
        let texture_handle = asset_server.load("branding/icon.png");
        info!(
            "displaying sprite: {:?}",
            commands
                .spawn(SpriteBundle {
                    material: materials.add(texture_handle.into()),
                    ..Default::default()
                })
                .current_entity()
        );
        *first = true;
    }
}
```

**What you expected to happen**

The sprite should have been displayed

**What actually happened**

The sprite wasn't displayed

**Additional information**

It was working with previous bevy commit

**Comment by cart** [comment]
Nice catch. I'll try to fix this asap!

**Comment by cart** [comment]
1. It doesn't display because the material asset's RenderResouceBindings aren't populated for the Texture/Sampler. The base color is populated
2. Rendering sprites with solid color materials (not textures) works

So for some reason texture bindings aren't getting populated for texture assets
