### ISSUE TITLE
Render App systems are blocking the Main app's primary thread

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#9964]
## Bevy version
main (f8fd93f418bf044455751bbcdf5528593b216510)

## What you did
I ran `cargo run --profile stress-test --features trace_tracy --example many_cubes` and viewed the trace in Tracy.

## What went wrong
I was expecting that no blocking systems from the render app would block the main app from progressing.

![image](https://github.com/bevyengine/bevy/assets/3137680/2d68a8f6-7a7a-4e74-81dc-da312074af24)

In this screenshot, `prepare_windows` is blocking UpdateAssets from terminating. Delaying it from terminating and blocking PreUpdate and subsequent schedules.

We currently do not schedule tasks from the ComputeTaskPool onto the render app thread, it may be a good idea to avoid doing so with all dedicated app schedule threads.

**Comment by hymm** [comment]
I think `prepare_windows` might only need to run on main thread for ios. Someone should survey the winit api's, we're using and if they're all ok, add a conditional compiling to NonSendMarker.

**Comment by daxpedda** [comment]
> i.e. a lot of the docs here https://docs.rs/winit/latest/winit/window/struct.Window.html say that these api's can only be called from main thread on ios.

This has been addressed in https://github.com/rust-windowing/winit/pull/2985 and https://github.com/rust-windowing/winit/pull/3045.

Though keep mind that functions that return values might block the calling thread until these values are returned.

**Comment by jmintb** [comment]
Can I have a go at this issue? :)

**Comment by alice-i-cecile** [comment]
@jmintb absolutely; let us know what you find out!

**Comment by timo-scaleio** [comment]
For whoever reported this for MacOS... do you have [Magnet](https://apps.apple.com/us/app/magnet/id441258766) running?  I have had a similar issue when testing something in Raylib. I see the same thing in Bevy now... the window is super unresponsive, CPU is high and sometimes the whole Mac UI gets locked up and nothing can be clicked anymore until I manage to close the Bevy game entirely.
