### ISSUE TITLE
bevy_render 0.11.3 using old code? Compute Shader example won't compile

### ISSUE THREAD

**Issue by Rippletank** [bevyengine/bevy#9970]
## Bevy version

bevy 0.11.3
bevy_render 0.11.3

## What you did

copied example code for compute_shader_game_of_life.rs into new project along with shader code in assets/shaders folder

## What went wrong

Build fails with:
error[E0599]: no variant or associated item named `PrepareBindGroups` found for enum `RenderSet` in the current scope

 src\main.rs:79:50

prepare_bind_group.in_set(RenderSet::PrepareBindGroups)

## Additional information

Using "Go to definition" in VSCode shows the enum that is, I believe, the version of lib.rs from 2 months ago (July 4th commit):

[https://github.com/bevyengine/bevy/blob/608367f9059c4391cade8dfbc811a8e02255ae25/crates/bevy_render/src/lib.rs](url)

Not the more recent ones with PrepareBindGroups added around the end of August.

**Comment by rparrett** [comment]
Where was the `compute_shader_game_of_life` example copied from? 

Here's a link to the version that works with the latest release of Bevy: https://github.com/bevyengine/bevy/blob/latest/examples/shader/compute_shader_game_of_life.rs

The `main` branch likely has breaking changes, but examples are always kept in a working state.

**Comment by Rippletank** [comment]
Ah, thank you! That explains it. That version does compiles fine. 

So, basically, I need to go to the examples via the link on the main readme.md to have them work with the cargo releases.
