### ISSUE TITLE
Visibility component flags *per camera*

### ISSUE THREAD

**Issue by ActuallyHappening** [bevyengine/bevy#9983]
## What problem does this solve or what need does it fill?

I have a game which uses the same `App` (and `&mut World`, resources, window, e.t.c. a default `App::default().run()`) and its space in two different ways. I am using `Camera3dBundle` to render the main 3d space that the player occupies, and `Camera2dBundle` to render a form of 'ui' formed from various meshes. The advantages of using such a UI is the increased flexibility, how would you create a circular odometer using `bevy_ui` or `bevy_egui`?

The problem is sometimes randomly spawned objects accidentally 'intersect' with the 2d space/plane of the Camera2d/UI and (with the `bevy_rapier3d` debugging plugin added) show up rather strangely! I initially wrote up this issue before realising the only reason the meshes appear across the 3D-2D boundary is because of the 3d physics debugging I have added, of which the images below demonstrate. However I would also like to develop 'physically seperate' parts of my game, as in multiple entities existing in the same space (ignoring physics) but depending on which camera you are viewing from a different scene can show.

## What solution would you like?

I would like the ability to flag the `Visibility` (or equivalent semantic) components of Entities to *not* show up on certain cameras. This would preserve the expected default of all meshes showing on all cameras, which is a very sensible default. I don't know bevy internals or the terminology, so maybe 'mesh' and 'entity' is the wrong term, but I would like to flag all of the 'main world' entities with a marker component / flag in that allows for, effectively, two seperate cameras to view the same space but actually render only runtime-configurable subsets of entities.

I don't mind if these flags have finite limits like a bit mask or they involve marker components, my current game only uses 5 cameras at the moment (4 for ui sticky to each corner) and I don't see why a `u32` isn't appropriate for such circumstances

## What alternative(s) have you considered?

I have tried to understand how I would use a sub app to solve this problem, but I don't quite know where they fit into this sort of problem. Maybe I would `std::men::replace` the `&mut World` of one app into another between renders, but that is getting a bit too advanced for my liking. In a similar vein, I have considered mutating the `Visibility` components of entities between camera renders but don't even know where to start on that!

## Additional context

This image shows both normal 3d asteroids (larger) and the smaller 2d slices of asteroids in solid red.
This was with the `bevy_rapier3d` debugging plugin enabled, which is where the lines appear.

<img width="828" alt="image" src="https://github.com/bevyengine/bevy/assets/105958073/aa753ad3-155f-482d-b315-329d034a3e45">
<img width="450" alt="image" src="https://github.com/bevyengine/bevy/assets/105958073/c282424d-c590-453a-b283-d58fc43653ca">

**Comment by alice-i-cecile** [comment]
Can you use [`RenderLayers`](https://docs.rs/bevy/latest/bevy/render/view/struct.RenderLayers.html) to achieve this effect?

**Comment by ActuallyHappening** [comment]
I am taking a look at its documentation, how do I use it in relation to cameras?

**Comment by alice-i-cecile** [comment]
Awesome: for future readers, the [example here](https://github.com/bevyengine/bevy/blob/latest/examples/3d/render_to_texture.rs) is pretty good!
